### ISSUE TITLE
🐛 Bug: Auto-Upstall fails installing docker on AWS Linux with Error: unsupported distribution 'amzn'

### ISSUE THREAD

**Issue by DavidIsaacBPS** [nocodb/nocodb#10008]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Create AWS EC2 instance on us-east-2, version 2023-1-20230912.
Run bash <(curl -sSL http://install.nocodb.com/noco.sh) <(mktemp)

### Desired Behavior

NocoDB should install without errors.

### Project Details

N/A...not installed.

**Comment by sinanmohd** [comment]
looks like amazon Linux doesn't ship the compose plugin with docker
https://github.com/NixOS/nixpkgs/blob/e2605d0744c2417b09f8bf850dfca42fcf537d34/pkgs/applications/virtualization/docker/default.nix#L11

you can install docker with compose support using nix, but i would recommend to just spin up a ubuntu instance instead, you can select the OS from the launch instance screen
