### ISSUE TITLE
🐛 Bug: Auto-upstall ends with message "docker: 'compose' is not a docker command."

### ISSUE THREAD

**Issue by DavidIsaacBPS** [nocodb/nocodb#10009]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

On AWS EC2 Linux:
* Install docker: sudo yum install docker -y; sudo systemctl start docker
* Run auto-upstall command

### Desired Behavior

Install should complete with success message

### Project Details

N/A

**Comment by sinanmohd** [comment]
Duplicate of #10008
