### ISSUE TITLE
🐛 Bug: Unable to upgrade SQLite database from prior version

### ISSUE THREAD

**Issue by DavidIsaacBPS** [nocodb/nocodb#10052]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Install new version of NocoDB with SQLite database option
2. Move old NocoDB database (noco.db) over the new one
3. Start the service

The database update fails with the message "Unable to access properties of "undefined" (reading Bold).  The database schema update hangs in an infinite loop.

### Desired Behavior

Database update should complete successfully

### Project Details

Most recent version using Auto Upstall.
Prior version is at least a year old.

### Attachments

![image](https://github.com/user-attachments/assets/e93f5443-a5d8-41b2-8d58-4c821b5e96b5)

**Comment by DavidIsaacBPS** [comment]
Thank you.

How can I upgrade NocoDB to a specific version such as 0.207.3 ?

On Dec 14, 2024 6:06 PM, "dosubot[bot]" ***@***.***> wrote:

The error you're encountering might be related to a migration issue when upgrading from an older version of NocoDB. NocoDB ensures backward compatibility by implementing a structured upgrade path with version checks. If the version is lower than 0100002, it requires upgrading to version 0.207.3 before proceeding to the latest version [1]<https://github.com/nocodb/nocodb/blob/develop/packages/nocodb/src/providers/init-meta-service.provider.ts>[2]<https://github.com/nocodb/nocodb/blob/develop/packages/nocodb/src/version-upgrader/NcUpgrader.ts>.

The error message "TypeError: Cannot read properties of undefined (reading 'bold')" suggests there might be an issue with the migration process handling undefined properties. This could be related to changes in how text formatting properties like 'bold' are managed in the newer version [3]<https://github.com/nocodb/nocodb/blob/develop/tests/playwright/disabledTests/docs/selections.spec.ts>[4]<https://github.com/nocodb/nocodb/blob/develop/packages/nc-gui/components/smartsheet/PlainCell.vue>.

To resolve this, ensure that you follow the recommended upgrade path by first upgrading to version 0.207.3 if your current version is older than 0100002. This step is crucial to ensure that all necessary migrations are applied in the correct order. If the issue persists, you may need to investigate further into the specific migration scripts and how they interact with your existing database schema.

To continue talking to Dosu<https://dosu.dev>, mention @dosu<https://github.com/dosu>.

________________________________

Help Dosu learn! Give it feedback: Great Response<https://app.dosu.dev/response-feedback/aaa4bff1-5451-49a2-add8-d4924d86aedb?feedback_type=great_response> | Irrelevant Answer<https://app.dosu.dev/response-feedback/aaa4bff1-5451-49a2-add8-d4924d86aedb?feedback_type=irrelevant_answer> | Incorrect Sources<https://app.dosu.dev/response-feedback/aaa4bff1-5451-49a2-add8-d4924d86aedb?feedback_type=incorrect_sources> | Too Verbose<https://app.dosu.dev/response-feedback/aaa4bff1-5451-49a2-add8-d4924d86aedb?feedback_type=too_verbose> | Hallucination<https://app.dosu.dev/response-feedback/aaa4bff1-5451-49a2-add8-d4924d86aedb?feedback_type=hallucination> | Other<https://app.dosu.dev/response-feedback/aaa4bff1-5451-49a2-add8-d4924d86aedb?feedback_type=other>

**Comment by DavidIsaacBPS** [comment]
Thank you.
@dosu please provide the specific command to pull the docker image for a specific version of NocoDB.

**Comment by DavidIsaacBPS** [comment]
@dosu Thank you.  Where can I find the specific parameters for my installation to start NocodB using Docker?

**Comment by DavidIsaacBPS** [comment]
Please help.  I have spent six hours trying to upgrade my instance.  I downloaded version 0.207.3 and updated the docker compose file accordingly, and can start all services fine using docker compose.  But when I try to connect from my browser I get a 404 error or dashboard not found error.  There must be some other parameters or environment variables being set by the Auto Upstall script that are not provided in the docker compose file?

**Comment by pranavxc** [comment]
> ![image](https://private-user-images.githubusercontent.com/131489274/395822112-e93f5443-a5d8-41b2-8d58-4c821b5e96b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzQzODAsIm5iZiI6MTczNDMzNDA4MCwicGF0aCI6Ii8xMzE0ODkyNzQvMzk1ODIyMTEyLWU5M2Y1NDQzLWE1ZDgtNDFiMi04ZDU4LTRjODIxYjVlOTZiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwNzI4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODhiODQ1YTc2OTkwYjFiMTgzN2ZmZDFkMmZmYTc0ZjFlZmEzYTMwYzhhZDQ3ZmY3NWMyNDRkMDkwODU1NmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4Nm3QNX6LeiXP9cFRGDxHFn7TwffL1S7PjLklM_xtLM)

Can you share the error message above in the shared image log, which includes some upgrader error it looks like.

> ![image](https://github.com/user-attachments/assets/6ad6aea9-c3fd-4cfd-a1ca-60e1ea440e46)

Here the version defined is pretty old and it's not including the migration which already applied from the latest version.

**Comment by DavidIsaacBPS** [comment]
Hi Pranav-
Can you please provide instructions on how to obtain the log info you need?
Using the Auto Upstall script, the log continuously scrolls offscreen as it retries over and over, so its hard to capture info.  But if I stop the service, it cannot retrieve the log.
Please advise, and thank you very much for your attention to this!

PS: this is a fairly old (1.5 years) instance of NocoDB.
It uses the built-in SQLite database.

**Comment by DavidIsaacBPS** [comment]
PS: I can screenshare and give you direct access to the server if that helps.

**Comment by pranavxc** [comment]
Fixed in following PR - https://github.com/nocodb/nocodb/pull/10066 . If you are facing same issue with latest docker then ping dm me in discord. (Discord  link - https://discord.gg/5RgZmkW , username `pranavxc`)
