### ISSUE TITLE
🐛 Bug: turn off the infinite scrolling function edit data bug

### ISSUE THREAD

**Issue by c2006878** [nocodb/nocodb#10070]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

After I turn off the infinite scrolling function, when I edit the extended form and click on the previous or next record, the data keeps loading and cannot be displayed.
![image](https://github.com/user-attachments/assets/61d32793-53a6-41c1-8432-5b4f4705e494)

![image](https://github.com/user-attachments/assets/98bb327b-32e4-4817-bd9c-2922b3e5f348)

### Desired Behavior

/

### Project Details

/

**Comment by DarkPhoenix2704** [comment]
Hi @c2006878 

Just tested in app.nocodb.com and open source. Seems working. Would you be able to share what version of NocoDB you are using?

**Comment by c2006878** [comment]
> Hi @c2006878
> 
> Just tested in app.nocodb.com and open source. Seems working. Would you be able to share what version of NocoDB you are using?

I also tested in app.nocodb.com

**Comment by DarkPhoenix2704** [comment]
Seems like an edge case. Can reproduce randomly but not consistently. Will have a look

**Comment by dstala** [comment]
@DarkPhoenix2704 I am able to reproduce this issue on this base - invited you into it.
https://app.nocodb.com/#/wpq9c053/pjiuewct4cckaae/mulfqrrhs9xohpc
