### ISSUE TITLE
🐛 Bug: S3 storage doesn't work

### ISSUE THREAD

**Issue by monahxxx** [nocodb/nocodb#10072]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Upgrade to 0.258.7
1. Open UI -> Setup -> Storage -> S3
2. Click test connection
3. Error in logs. TypeError: Cannot read properties of undefined (reading 'region') 

Same happens when trying to upload an attachment or view existing attachment.

At the same time I counldn't downgrade to the previous version (0.258.3) - I see the following error Error: The migration directory is corrupt, the following files are missing: nc_069_ai_prompt.

I'm using ECS Fargate for deployments.

### Desired Behavior

S3 storage works correctly, attachments could be viewed and uploaded.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.258.7**

**Comment by DarkPhoenix2704** [comment]
hi @monahxxx . Would you be able to test the below docker image and check if it resolves the issue

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.258.3-pr-10076-20241218-1715
```

**Comment by monahxxx** [comment]
> hi @monahxxx . Would you be able to test the below docker image and check if it resolves the issue
> 
> ```
> docker run -d -p 8888:8080 nocodb/nocodb-timely:0.258.3-pr-10076-20241218-1715
> ```

It resolved the issue, thanks.

**Comment by DarkPhoenix2704** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/10076

Will be available in next bug fix release
