### ISSUE TITLE
🐛 Bug: Unreferenced nocodb release 0.258.7

### ISSUE THREAD

**Issue by IamLunchbox** [nocodb/nocodb#10092]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

The current latest nocodb release in github is 0.258.3 - as is the latest tagging git. But the latest docker image is tagged as [0.258.7](https://hub.docker.com/layers/nocodb/nocodb/0.258.7/images/sha256-4903312b666b74a87330108550074269b3077fd6cbdcda2529ec1980dd747b8e). There are neither release notes,  changelogs  nor other notes for this version.

Why was this version bump released and why is 0.258.7 not referenced anywhere?

### Desired Behavior

Image releases and their tags should be consistent with the github release notes to enable administrator to track changes and upgrade procedure.

### Project Details

Is this important in this context?

**Comment by dstala** [comment]
There was an issue with that release & hence was removed from Github. Latest release now is v0.258.10.
Please ignore the docker release v0.258.7. This tag will be removed soon.
