### ISSUE TITLE
🐛 Bug: Attachments - This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by raf-microsoft** [nocodb/nocodb#10122]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

I'm on `0.251.1`, had this issue with the previous versions as well. Uploaded images are served over http rather than https. When I click the image and open in a new tab it will open over https. Is there a way to fix this? It happens with any type of the attachment.

**Console Error**
`This request has been blocked; the content must be served over HTTPS.`

### Desired Behavior

Show image.

### Project Details

Node.js

### Attachments

![image](https://github.com/user-attachments/assets/631eb604-ec4d-4b23-8892-a5cca94b3b95)
![image](https://github.com/user-attachments/assets/8c0725f2-dc4c-4202-9b56-e55949cf97a9)

**Comment by raf-microsoft** [comment]
I patched the issue by forcing the server to route any `http `requests over `https` and the images shows.

**Comment by DarkPhoenix2704** [comment]
For existing installation you can follow the below steps for resolving SSL related issues. https://github.com/nocodb/nocodb/issues/9786#issuecomment-2467352769

**Comment by DarkPhoenix2704** [comment]
We have also patched the AutoUpstall script to fix the issues and provide proper warning to users in all installation cases.
