### ISSUE TITLE
Treeview item order

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#1021]
Currently when you connect an external databases with tables and views, tables come first and views come after. However, if you add a new table, it would put it at the end. It's better to order them by type first and then sort alphabetically.

Screenshot:

![image](https://user-images.githubusercontent.com/35857179/151652684-65ab32cc-a196-4f90-8175-4be7fded7a7d.png)

Node: **v14.18.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.8**

**Comment by o1lab** [comment]
There is ability to reorder tables now. Closing this @wingkwong :)
