### ISSUE TITLE
Default DateTime value "now()" does not fill the field

### ISSUE THREAD

**Issue by captain-otter** [nocodb/nocodb#1031]
NocoDB used as docker : true
NocoDB version : 0.84.8
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project 
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Debian Buster VM inside Proxmox
Node.js version if running as node : 
Database version : PostgreSQL 13.3

**Steps To Reproduce**
1. Create a new table
2. Add a new column of type DateTime
3. Set `now()` as the default value

**Expected behavior**
When opening the form view the column should have current datetime filled into the field. 
I would also assume adding a new row would automatically fill the datetime into that column.

Looking at the schema I can see that the default value is correctly set.
![image](https://user-images.githubusercontent.com/57947291/152243607-ccc2c1f9-2195-458d-8a50-5573ed046500.png)

**Comment by wingkwong** [comment]
Extracted from Discord.

The default values are assigned to columns when they are not specified. They won't show in UI when you create a new row nor a form view. System fields are disabled in Form View on purpose. 

> For the "Option" field even though the type of it is text, I can only use integers as Default value.

The single quote is required.
