### ISSUE TITLE
Webhook to send email notification can't be cancelled

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#1034]
**Please enter the following details**

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.84.8**

**Steps To Reproduce**
1. I installed SMTP-App, did the configuration and created a weebhook in table "Arztadressen"
 to send email notification when entries are changed
2. I deleted the webhook 
3. Even everything is empty now i still get notifications for changing entries
4. After uninstalling and reinstalling the SMTP-plugin the notifications are still sent!!!

**Expected behaviour**
After the weebhook is deleted there shouldn´t be any email notifications anymore

**Screenshots**
Creation of webhook:
![Webhook neu](https://user-images.githubusercontent.com/20600342/152325805-88164bca-0261-4f7a-9702-f1b4dc2a5829.jpg)

Canceling webhook:
![Webhook](https://user-images.githubusercontent.com/20600342/152323340-cff8d924-ba64-4002-8297-7c792f9503dd.jpg)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by wingkwong** [comment]
Fixed in ``0.84.9``.
