### ISSUE TITLE
Currency validator crashing when not adding two decimal places

### ISSUE THREAD

**Issue by FerLSanchez** [nocodb/nocodb#1042]
NocoDB used as docker : true
NocoDB version : 0.848
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : Ubuntu
Database version : 8.0.28-1debian10
--

**Steps To Reproduce**
1. Create a project
2. Create a table
3. Create a Currency column, leaving database part as default (decimal(10,2))
4. Add a new register with a decimal with a single decimal place, like 55.9
5. In previous noco versions there were a message regarding the validator, now it is just a 400

**Expected behavior**
It should work and save the value (it works for 55.91)

**Screenshots**
<img width="563" alt="Screenshot 2022-02-03 at 18 55 00" src="https://user-images.githubusercontent.com/2619609/152400756-a29d993b-9b22-457e-94f8-b3863c7097c9.png">

**Comment by o1lab** [comment]
55,9 -> there is a comma instead of a decimal - Is that a typo ?

**Comment by FerLSanchez** [comment]
Spanish localization for numbers... it works for 55,91... :/

**Comment by FerLSanchez** [comment]
In fact, the only workaround I have right now is entering a two decimal number like 55,91 and correct it directly in database... :_(

**Comment by wingkwong** [comment]
@FerLSanchez It fails because the currency format is not correct. Two decimal places are fixed. Correct formats like ``123``, or ``123.50``.  However, it should show the validation error in Form View instead of 400 for better UX. It should be the one in Grid View. Let me take this.

![image](https://user-images.githubusercontent.com/35857179/152524927-aa9d6adc-ae01-4254-bb18-fe4e4682c62b.png)

**Comment by FerLSanchez** [comment]
123,50 (Spanish-like) doesn't work, the field deletes the 0, and go back to the error. If I try to use the point instead of the comma, the field goes to 0 automatically as fast as I click the key...
Let me know if I can help with anything. Thank you very much.

**Comment by wingkwong** [comment]
I'm able to reproduce it. It seems like the validation starts on keydown. I'm able to input ``12.50`` if I type very fast (before the validation starts). Will take a look.

**Comment by FerLSanchez** [comment]
Great! Thank you very much!

**Comment by wingkwong** [comment]
Let's summary a bit first. The problems we are facing right now are 

- [Enhancement] In Form View, or expanded form in Grid View, saving with an invalid currency return ``Request failed with status code 400`` instead of ``Validation Failed`` message.
- [Bug] Currency field is saved immediately if there is no further input (~1000ms) which triggers validation. (I've fixed this in another branch)
- [Bug] Spanish-like value doesn't work.

**Comment by wingkwong** [comment]
@FerLSanchez If decimal separator is ``,`` in spanish localization, then what is the separator for thousands? Like how would you display ``123,456,789.50``  in spanish localization?

**Comment by FerLSanchez** [comment]
Exactly the opposite: 123.456.789,50
(and, investigating a bit, it is quite common in the whole Europe)

**Comment by FerLSanchez** [comment]
Hi! Any needs on this?
It has improved, but the initial problem still persists, if you try to add a currency value with an ending (second) decimal value of 0, the 0 is removed and the validator fails.
The only workaround is adding another number and then change the value directly in the database.

Let me know if I can help in any way, please.
Thank you!

**Comment by FerLSanchez** [comment]
Happy to hear that, and thanks for the update!

**Comment by FerLSanchez** [comment]
Hey, how is this going? At least in 0.84.15, version I'm running right now, it still fails with numbers with just one decimal position :S
Count on me if I can help or support you in any way.
Thank you!

**Comment by FerLSanchez** [comment]
Thank you very much for the update, I absolutely understand :)
Keep in touch and, again, congrats on this awesome project!

**Comment by mertmit** [comment]
@FerLSanchez I am happy to announce we have revised the currency column to support different locales and currency codes. I hope our new implementation in develop branch cover your needs. Feel free to update the issue if anything missing for you.
![image](https://user-images.githubusercontent.com/59797957/170151515-7d0ff620-d1d2-44d3-a7e8-62947d4fcc15.png)

**Comment by FerLSanchez** [comment]
This is super nice! Thank you very much! If you don't mind, I will wait for it to be integrated into the next release, unless you want me to test it :)

**Comment by mertmit** [comment]
Of course you can wait for the release, I just wanted to update you on current state, feel free to feedback any time.
