### ISSUE TITLE
Lookup on "Formula field" not available - bug or just normal?

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#1045]
Please enter the following details

Node: v12.22.6
Arch: x64
Platform: linux
Docker: true
Database: mysql2
ProjectOnRootDB: true
RootDB: mysql2
PackageVersion: 0.84.8

**Steps To Reproduce**
1. Add new row on table "Arztadressen", format it as formula field and choose the needed values
2. There is already a "Link to another table" from "Arztadressen" to table "Impfbuch_xyz"
3. On table "Impfbuch_xyz" create new ro as "Lookup", choose from "Arztadressen" - the formula field in Arztadressen won´t show up. Not sure if it is a bug or just impossible because it is a special field

**Expected behavior**
A field defined as "Formula" should show up under "Lookup".

**Screenshots**

**Comment by malyzeli** [comment]
Just want to add that it doesn't work in the other direction either - cannot reference lookup column in a formula. 

Probably not implemented yet?

**Comment by o1lab** [comment]
There is an [open issue](https://github.com/nocodb/nocodb/issues/512) for it and we are looking into it.
