### ISSUE TITLE
URL field layout type is temporay lost after Metadata synchronization

### ISSUE THREAD

**Issue by scali** [nocodb/nocodb#1046]
NocoDB used as docker : true
NocoDB version : 0.84.8
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Ubuntu
Database version : 11.11

Steps to reproduce :
1. Go to 'Add new table' 
2. Keep to default new table template
3. Change the layout type to 'URL'
4. Add new row with a random URL
5. Go to 'Project Metadata' > 'Metadata' > click on 'Sync Now'
6. Back to the created table in step 1
7. See error : URL field is blank

**Expected behavior**
URL field should display the data

If we go to 'Edit' on the URL field, the layout is working as expected

**Comment by o1lab** [comment]
Changing the column type from singleLineText to URL is leading to errors. Tried on PG.

@scali 
Any reason - step 5 was done ?

**Comment by scali** [comment]
Our workflow is DB-first, so we are doing metadata sync regulary. I mention step 5 here just to reproduce the problem

**Comment by o1lab** [comment]
Fixed in ```0.84.9```
