### ISSUE TITLE
[Solved] Attachment uploaded via https will try to load (and fail) via http

### ISSUE THREAD

**Issue by bmscmoreira** [nocodb/nocodb#1051]
**Description**
An image attachment is not displayed in the browser because it tries to fetch it using http when it should be using https.

**Project info**
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.84.8**

**Steps To Reproduce**
1. Upload a file to an attachment field
2. Try to open the file
3. The file will not load: using web inspector tools one realizes it's trying to load the image from the url "http://nocodb.mydomainname.com/[ommited]" when it should be loading it from "**https**://nocodb.mydomainname.com/[ommited]"
(changing it to https in the browser developer tools allows the image to be loaded, so it was uploaded to the server)

**Expected behavior**
The image should be loaded.

**Aditional info**
I'm using nocodb as a docker package in a synology NAS, with a reverse proxy configured to redirect https calls from a synology.me domain to the corresponding container IP/Port.
Using just one environment variable NC_DB.

**Comment by wingkwong** [comment]
which file storage are you using?

**Comment by bmscmoreira** [comment]
@wingkwong I have not configured any specific file storage so I think everything is being stored inside the docker container.
But I have just figured how to solve this: if I add to my docker-compose the environment variable NC_PUBLIC_URL with the correct path (https://nocodb.mydomain.com) the attachments work ok.

Maybe I should have realized this but it was not immediate. Maybe it should be helpful to state that NC_PUBLIC_URL should be used in https scenarios, otherwise attachments will not work as expected.

Should this issue be considered "closed"?
