### ISSUE TITLE
After upgrading docker-installation all attachments in tables are lost

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#1055]
Please enter the following details

Node: v12.22.6
Arch: x64
Platform: linux (QNAP 5.0.0.1891)
Docker: true
Database: mysql2 (MariaDB10.5)
ProjectOnRootDB: true
RootDB: mysql2 (MariaDB 10.5)
Database 10.5.8
PackageVersion: 0.84.9

**Steps To Reproduce**
1. Everytime after upgrading docker installation (even the past 2 releases) all attachments are lost
2. The names are still there but the files can´t be found

**Expected behavior**
After updating docker installation all attached files should be accessable

**Screenshots**
![Attachment5](https://user-images.githubusercontent.com/20600342/152798345-5fc30a1f-851f-474d-9103-e079c6bbfb3d.jpg)
![Attachment4](https://user-images.githubusercontent.com/20600342/152797953-c7cfddb0-c154-4866-bce5-149368d3d05a.jpg)
![Attachment2](https://user-images.githubusercontent.com/20600342/152797000-f1855972-337a-4675-a7fb-fe736e8625da.jpg)
![Attachment3](https://user-images.githubusercontent.com/20600342/152797004-8597c6c4-74b3-4fa8-bb00-95aefa081bc3.jpg)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by wingkwong** [comment]
Have you mounted the volume to persist the files? 

```
docker run -d -p 8080:8080 --name nocodb -v /local/path:/usr/app/data/ nocodb/nocodb:latest
```

**Comment by WeT-Klb** [comment]
No - i thought it is only needed when using SQLLight.

**Comment by wingkwong** [comment]
If ``NC_DB`` is missing, a SQLite file ``noco.db`` will be generated in your container for storing the metadata. Similarly, if you haven't specified any other file storage such as S3, then your uploaded files will be stored in your container. When you upgrade NocoDB, it is actually recreating a new container with the new image. Therefore you may lose the data if you haven't mounted the volume.

**Comment by WeT-Klb** [comment]
Ah got it. I thougt as long as i use MariaDB definded through NC_DB i don´t need a mount.
Of course now it is clear the files themself are not stored in MariaDB - only the link to them (into the container).
Now i mapped /xyz/NocoDB to /usr/app/data - and now i can see the files are stored there.
Thanks so much for the fast reply.
