### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#1123]
Using node 17 to start ``nc-gui`` would throw ``ERR_OSSL_EVP_UNSUPPORTED`` error. This is because some modules attempting to use an algorithm or key size which is no longer allowed by default with OpenSSL 3.0. A new [command-line option](https://nodejs.org/api/cli.html#--openssl-legacy-provider), --openssl-legacy-provider, has been added to revert to the legacy provider as a temporary workaround for these tightened restrictions.

Change 
```
"dev": EE=true nuxt",
```

To
```
"dev": "NODE_OPTIONS=--openssl-legacy-provider EE=true nuxt",
```

in ``package.json`` in ``nc-gui``

**Comment by o1lab** [comment]
With moving to vue3 - this is good to be closed now.
