### ISSUE TITLE
[Feature] Extract Date from SingleLineText or DateTime column types

### ISSUE THREAD

**Issue by alfureu** [nocodb/nocodb#1134]
**Need for this feature**
Obtained a dataset with DateTime or SingleLineText values (e.g. 2022-02-02 00:00). If I want to see only the dates, switching to Date column type ends in error requiring tedious data sanitization

**Is your feature request related to a problem? Please describe.**
See above. Extracting various date formats from values would be overall a smart feature

**Describe the solution you'd like**
Something similar what multiple calendar apps are supporting, extracting a date from a value in multiple formats. If the algorithm is confused, one could define patterns, e.g. `yyyy-mm-dd hh:mm` or `M D yyyy` for Feb 2nd 2022, etc).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anonfreak** [comment]
Bump. We're currently looking for a solution to convert data from a datetime-column to a date-column, but currently we don't see any possibility in doing this.

**Comment by ballinger** [comment]
is there some nocodb solution other than to reformat csv's manually? got something like this -> 2024-04-10T16:00:47.447+02:00

**Comment by dstala** [comment]
Type conversion for single line text to date is supported now. If you face any hurdles, please reopen this ticket
