### ISSUE TITLE
[Feature] Simplify release

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1139]
Need a github action to make a release. 

Problem with current setup is
- It takes lot of time
- Manual intervention to checkout, publish npm etc is required
- This leads to tests being repeated. 

We'd an attempt which has the needed bearings to make this work.

**Comment by wingkwong** [comment]
**Manual Action:**
1. PR & Merge ``develop`` to ``master``.  (at least one members review is required.)
2. Create a new release branch from ``master``

**Github Actions:**
3. Publish frontend (Existing Action)
4. Install frontend (Existing Action)
5. Publish backend (Existing Action)
6. Close all issues (Need to implement)
7. PR from release branch to ``master``
8. Prepare Release notes (Existing Action + Manual update draft notes)
9. Publish Docker & Release (Existing Action)
10. Sync changes back to develop branch (Need to implement / Manual sync)

CI/CD Actions may need to be fine-tuned as well.

**Comment by wingkwong** [comment]
Further combined into different sub-flows.

- Master Workflow (input: tag, prev_tag)
  - Action 1: release-npm (input: tag, prev_tag) (step 3 - step 5)
  - Action 2: close-issues (input: N/A) (step 6)
  - Action 3: release-draft (input: tag, prev_tag) (step 8)
  - Action 4: release-docker (input: tag) (step 9)

New files:
- release-nocodb.yml (master workflow)
- release-close-issue.yml

Modified files:
- release-npm.yml
- release-draft.yml
- release-docker.yml
