### ISSUE TITLE
Cannot POST row to table

### ISSUE THREAD

**Issue by Kuuchuu** [nocodb/nocodb#1146]
NocoDB used as docker : true
NocoDB version : 0.84.10
Database used in NC_DB URL : pg
Project was created by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Docker/Rocky Linux 8
Database version : 14.1-1.pgdg110+1
ProjectOnRootDB: true

**Steps To Reproduce**
1. Use REST API via cURL or directly on the Swagger API docs page to POST a row:
```
NocoData='{"BusinessDate":"'"$CurrentHour"'","LaborPercentage":"'"$LaborPercent"'","LaborHours":"'"$LaborHours"'","TotalPay":"'"$TotalPay"'"}'
echo "NocoData $NocoData"
        ---> 'NocoData {"BusinessDate":"2022-02-09T16:00:00Z","LaborPercentage":"0.25","LaborHours":"97.40","TotalPay":"719.60"}'
curl -X 'POST' 'https://noco.****.com/nc/cornerstone_8pzg/api/v1/'"$Location"'_Labor' -H 'accept: application/json' -H 'xc-token: '"$NocoToken" -H 'Content-Type: application/json' -d "$NocoData"
        ---> {"msg":"Cannot read property 'insert' of undefined"}
```
2. POST fails

**Expected behavior**
Response:
```
{"id":1,"BusinessDate":"2022-02-09T16:00:00.000Z","LaborPercentage":0.25,"LaborHours":"97.40","TotalPay":"719.60"}
```
The cURL command works fine for one table ("Bowman_Labor"), but fails on another table ("LewisCrossing_Labor").
I have verified that the table is named correctly and that all four columns match exactly.
The Swagger API docs page also fails to POST to that specific table.

**Screenshots**
LewisCrossing_Labor:
![image](https://user-images.githubusercontent.com/20036947/153303225-2705ee83-6d4f-49af-9f83-71b53c4b997c.png)
![image](https://user-images.githubusercontent.com/20036947/153303283-82742206-e077-4f35-8d7f-18d817c3a561.png)
![image](https://user-images.githubusercontent.com/20036947/153303612-e37375d7-de60-4f69-8c24-f85d72aa5011.png)
Bowman_Labor:
![image](https://user-images.githubusercontent.com/20036947/153303410-40ec6795-ddd9-448d-848a-841432de241b.png)
![image](https://user-images.githubusercontent.com/20036947/153303447-cbdc2173-8048-4891-9884-b1b9f261253d.png)
![image](https://user-images.githubusercontent.com/20036947/153303580-43a2d5a8-917f-487e-b73e-573f14b6b2b4.png)

I'm able to provide whatever other info you may need. Thanks

**Comment by wingkwong** [comment]
@Kuuchuu I've tried it in cURL and Swagger API but couldn't reproduce issues.

1. What is the difference between two tables?
2. If you create a new table with the same columns, would it be still reproducible?

**Comment by o1lab** [comment]
Docker logs and browser network error message would be helpful

**Comment by Kuuchuu** [comment]
Running Get List produces this 400 error:
```
{
  "msg": "Cannot read property 'nestedList' of undefined"
}
```
Docker log:
```
nocodb     | GET /nc/cornerstone_8pzg/api/v1/LewisCrossing_Labor 400 56 - 4.297 ms
```

**Comment by o1lab** [comment]
What timezone are you in ? Please ping @wingkwong  in our [discord](https://discord.gg/5RgZmkW).
