### ISSUE TITLE
[Feature] Multilink between tables

### ISSUE THREAD

**Issue by DOFfactory** [nocodb/nocodb#1158]
**Need for this feature**
Being able to link Table1 `rows` to multiple `columns` in Table2.

**Is your feature request related to a problem? Please describe.**
I have a normalized list of names in Table1, which I want to consistently use across other tables. Currently the LinkToAnotherRecord allows only 1 has-many and 1 many-to-many link. I need something like multilink. 

![image](https://user-images.githubusercontent.com/10846169/153586721-f1e95f81-1c97-458a-827e-db7f1a9d18dc.png)

**Describe the solution you'd like**
I want to be able to use the values from Table1 multiple times in multiple columns in Table2. Possibly this can be repeated with Table3, Table4, ..., TableN

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dstala** [comment]
Multiple LTAR columns can be created to serve the scenario discussed above
