### ISSUE TITLE
🐛 Bug: Digital Ocean default docker setup with a postgres database provided by DO doesn't run.

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1174]
Below is a template of ```DATABASE_URL``` from
`postgresql://user:password@host:port/testbench-nocodb-database?sslmode=require`

We arent handling the translation of sslmodel=require while converting JDBC URL to NC_DB

**Comment by sudermanjr** [comment]
I'm so glad you filed this. I've been trying to get it to connect for a bit now to a DO postgres instance, and could not figure out what I was doing wrong.

**Comment by sudermanjr** [comment]
It does seem that this can be done via NC_DB_JSON:

```
{
    "client": "pg",
    "connection": {
        "host": "URL",
        "port":  PORT,
        "user": "nocodb",
        "password": "",
        "database": "nocodb",
        "ssl": true
    }
}
```

It does also seem that the URL parameter in the `pg://` sring should be `ssl=true`, but I couldn't get that to work either.

**Comment by o1lab** [comment]
@wingkwong : please see that we parse and adapt ssl param in DATABASE_URL and NC_DB

**Comment by dopry** [comment]
I've looked at this a bit more closely.  
The postgres databases provided by digital ocean require ssl connect. the postgres jdbc connection string uses sslmode=require, which nocodb doesn't look at. Nocodb expects ssl=true. 

However even with postgresql://user:pass@host:port/db?ssl=true  D.O. uses self signed certs for their databases. I'm testing with app platform so I don't have  place to store the self signed cert, at best I have a url. I've tries adding ?caCertFile=${cacerturl} which doesn't seem to work.  I'm going to try with the other NC_DB string to see if I can make that work...  It would be nice if the DATABASE_URL and NC_DB options were better documented, and I didn't need to look at https://github.com/nocodb/nocodb/blob/e0ab288aba2d96fb32a5d5868987fcdf37eb51a4/packages/nocodb/src/lib/utils/NcConfigFactory.ts#L52 to figure them out as an end user.

**Comment by dopry** [comment]
I finally figured this out... I had to set the env var `NC_DB_JSON` so I could embed the `ca` certificate downloaded from D.O.. You also need to use the `doadmin` user, it is the only user by default with permissions necessary to create the required schema. someone more familiar with postgres could probably write the grant for another user.  You also must set `rejectUnauthorized` to false to work with D.O. self signed certs I believe. 
```json
{
  "client": "pg",
  "connection": {
    "host": "yourhost.db.ondigitalocean.com",
    "port": "your port",
    "user": "doadmin",
    "password": "you password from d.o.",
    "database": "nocodb",
    "ssl": {
      "ca": "-----BEGIN CERTIFICATE-----\n.....\n..... \n....\n-----END CERTIFICATE-----",
      "key": "",
      "cert": "",
      "rejectUnauthorized": false
    }
  }
}
```

**Comment by o1lab** [comment]
Good to close given it works with NC_DB_JSON
