### ISSUE TITLE
Different 400 response structure of API like /auth/signin

### ISSUE THREAD

**Issue by LancerComet** [nocodb/nocodb#1266]
## Current behavior

When I sigin without email or password, nocodb responses the data like this:

```json
{ "message": "Missing credentials" }
```

When I sigin with incorrect email or password, it responses the data like this:

```json
{ "msg": "Email XXX is not registered! (Or some other reasons)" }
```

The reason is that it throws the exception directly in the first situation, but it returns a hand-made json in the other situation.

https://github.com/nocodb/nocodb/blob/4defd2944e2ed0e168732474ac26863b5743e9e8/packages/nocodb/src/lib/noco/rest/RestAuthCtrl.ts#L638

https://github.com/nocodb/nocodb/blob/4defd2944e2ed0e168732474ac26863b5743e9e8/packages/nocodb/src/lib/noco/rest/RestAuthCtrl.ts#L643

## Expected behavior

It would be nice to have them in the same format:

```json
{ "msg": "Wow such a reason" }
```
If this were making the breaking change, we could give it a fallback like this:

```json
{ "msg": "Missing credentials", "message": "Missing credentials" }
```

**Comment by wingkwong** [comment]
Fixed in ``0.84.12``.
