### ISSUE TITLE
Multiselect edits not reflected across row values

### ISSUE THREAD

**Issue by DOFfactory** [nocodb/nocodb#1286]
**Steps To Reproduce**
1. Create multiple inputs in multiselect
2. select from multiselect options from the list in rows
3. Go back editing the multiselect column and make some changes
4. The changes are not reflected in the rows

**Expected behavior**
The changes made in the general multiselect settings of the column should be reflected in all of the the row-values automatically, whenever there is a change

**Screenshots**
![image](https://user-images.githubusercontent.com/10846169/154316103-439accc5-d07c-49cf-8017-7d20d78437c3.png)

the multiselect value has been changed from `consumer` >> `consumer_edited`

![image](https://user-images.githubusercontent.com/10846169/154316008-ca9b663e-a52e-4447-9112-c20b79e1dd9c.png)

the change is not reflected in the rows, only the ones created after the change

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.10**

**Comment by dstala** [comment]
fixed as observed in current release;
