### ISSUE TITLE
[Feature] Reorder multiselect options in column settings (manually or other)

### ISSUE THREAD

**Issue by DOFfactory** [nocodb/nocodb#1287]
**Need for this feature**
Reorder multiselect options in column settings, either manually or based on other sorting

**Is your feature request related to a problem? Please describe.**
Currently it is not possible to reorder (for example to alphabetic order) the values in the multiselect column values.

**Describe the solution you'd like**
A drag&drop holder similar present in the Fields should be desirable

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by o1lab** [comment]
This was supported since 0.96.0
