### ISSUE TITLE
[Feature] Support for logos and background images in Form view

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1291]
**Need for this feature**
Better designed forms for custom needs

**Is your feature request related to a problem? Please describe.**
- Allow images & color/gradient choice as background for forms
- Allow custom logos to be embedded on forms

**Describe the solution you'd like**
Option to upload background image as title header & to configure background color for form layout 

**Additional context**
Feature request created based on discussion comment from @candideu 
https://github.com/nocodb/nocodb/discussions/704#discussioncomment-2191287

**Comment by candideu** [comment]
Thank you! I just realized that I had found a similar issue a while back: https://github.com/nocodb/nocodb/issues/494

**Comment by dstala** [comment]
ah! I had missed it. will close this one & track this request under https://github.com/nocodb/nocodb/issues/494
