### ISSUE TITLE
The Datetime column will increase by 8 hours and must be saved repeatedly to save successfully

### ISSUE THREAD

**Issue by liulaneletao** [nocodb/nocodb#1293]
NocoDB used as docker : true
NocoDB version : v0.84.10
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : linux

**Steps To Reproduce**
1. choose 2022/01/01 12:00
![image](https://user-images.githubusercontent.com/53805492/154438844-7d11b352-be76-42e4-81cd-13097a4be4c6.png)
2.it will automatically add 8 hours
![image](https://user-images.githubusercontent.com/53805492/154439436-9dec5dd9-cddc-44e5-96cb-556e66c66bb1.png)
3.Then I change 2022/01/01 20:00 to 2022/01/01 12:00. It won't automatically add another 8 hours.

**Expected behavior**
save only once

Node version : **v12.22.1**
Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
packageVersion: **0.9.27**

**Comment by wingkwong** [comment]
Have you set the timezone?

Example:

```
docker run -d -e TZ=Asia/Hong_Kong --name nocodb -p 8080:8080 nocodb/nocodb:0.84.10
```

**Comment by wingkwong** [comment]
Checked with user. Closing this issue.
