### ISSUE TITLE
[Feature] order by ASC or DESC with Rest API get list

### ISSUE THREAD

**Issue by jdbrice** [nocodb/nocodb#1310]
RestAPI: Specify order by asc or desc for rest API GET calls (get list).

**Need for this feature**
I want to be able to fetch N newest / oldest entries (using the created or updatedAt columns)

**Is your feature request related to a problem? Please describe.**
I cannot find any way to specify ASC vs. DESC for rest API calls.

**Describe the solution you'd like**
additional query parameter for specifying ASC or DESC

**Describe alternatives you've considered**
- I started by fetching the entire dataset and sorting client side, not viable for large data
- I tried adding ?sort=updatedAt%20DESC etc. and I found nothing that worked
- It looks like the graphQL API is more full featured, I have considered using it instead

**Comment by o1lab** [comment]
See sort query params in docs. https://docs.nocodb.com/developer-resources/rest-apis#query-params
