### ISSUE TITLE
Changing single select fields results in webhooks getting called twice

### ISSUE THREAD

**Issue by lawzava** [nocodb/nocodb#1312]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.12**

**Steps To Reproduce**
I've set up an ON UPDATE + condition webhook (URL). (when a field is set to true execute POST call)
But for some reason, it always executes twice. 
i.e. I get 2 calls executed for a single update.

Only 1 webhook is being used throughout the whole organization (there were more previously which I've removed).

Not sure what it does but clicked on "reload" as well.

**Expected behavior**
Webhook is only executed once for a single row update

**Screenshots**
https://i.imgur.com/4rGpHg6.png

**Comment by wingkwong** [comment]
Hi @lawzava. I couldn't reproduce the issue based on the setup you described. After a single update, there was only one call triggered on my machine. My POST request is to insert a record in DB and only one record was inserted as expected. Also, I could only see one ``AfterUpdate`` hook that was triggered. Lemme DM you in Discord.

**Comment by wingkwong** [comment]
No response from Github & Discord. Please reopen if necessary.

**Comment by yellowskyandbluesun** [comment]
Hi, I can reproduce this issue. NocoDB should write a note in a ticket system (Freshservice). The note is posted twice. I tried to add the webhook from scratch. The result is the same.

**Comment by o1lab** [comment]
@yellowskyandbluesun : can you please paste your project info and exact scenario.

I tried it in below setting (on heroku) - webhooks got triggered one time.

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.14**

**Comment by yellowskyandbluesun** [comment]
I am using a 'post' call. I am changing data (a Single Select field) via UI.

<img width="533" alt="Bildschirmfoto 2022-03-14 um 13 23 03" src="https://user-images.githubusercontent.com/92078639/158171585-4d5f80bc-c417-4cbe-975a-6c44c11a0f66.png">

I tried using a checkbox and voila it only sends one request.

**Comment by o1lab** [comment]
Also, are you using NocoDB's rest/gql APIs or just webhooks (question is not relevant to the problem)

**Comment by yellowskyandbluesun** [comment]
We are using the rest API to push data into the table (also from Freshservice) and after editing it we are using the Webhook to set a note in the corresponding ticket in Freshservice.

**Comment by wingkwong** [comment]
Able to reproduce. The root cause is when you're editing, it would auto-save from time to time. Hence, multiple webhooks are triggered.

**Comment by o1lab** [comment]
The webhook triggering twice issue is seen only with single select and mult-select. 

Original issue with boolean/checkbox is not reproducible.
