### ISSUE TITLE
Column re-order doesn't work on Postgres Views

### ISSUE THREAD

**Issue by lukurde** [nocodb/nocodb#1319]
**Please enter the following details**

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false** (this is a copy&paste, but in reality this is a container, just running on `podman` instead of docker)
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.84.12**

please provide the following details :
NocoDB used as docker : true
NocoDB version : 0.84.12
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Rocky Linux 8.5 (up-to-date as of writing)
Node.js version if running as node : n/a
Database version : postgresql-server-10.17-2.module+el8.5.0+685+b03fcc47.x86_64

**Steps To Reproduce**
1. Go to: https://docs.nocodb.com/setup-and-usages/column-operations/#fields
2. Works on Tables, doesn't work on Views

**Expected behavior**
Column re-ordering works on Vews as well

**Comment by o1lab** [comment]
Available in 0.90
