### ISSUE TITLE
Adding Farsi to NocoDB interface

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#1321]
We are translating the interface into Farsi (fa) and it's formerly done by Google Translate engine but it's not actually correct in some cases. So we're editing the translation and the process won't take more than a week.
The most important thing about Farsi is its direction. Unlike many languages, Farsi is RTL (right-to-left); just like Hebrew & Arabic.
Therefore NocoDB should support RTL text direction.
The translation is already in progress.

Language: Farsi (aka Persian)
Language code: fa
Translation status: in progress
Language direction: RTL
Spoken in: mostly Iran & Afghanistan

**Comment by dstala** [comment]
@okaeiz, we will look into support for RTL text direction
Anything else, feel free to connect over here / discord. You can DM @dstala

**Comment by okaeiz** [comment]
Hi back!
We have nearly finished translating the interface to Farsi and are almost ready to share it with you.
We need to know when RTL text direction is available.

**Comment by o1lab** [comment]
Available in 0.90 release
