### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by alprotasov** [nocodb/nocodb#1337]
**Steps to reproduce:**
1. Click forgot you password link at login page (https://markuphero.com/share/2wTg8P8ZE0wAdtWkg6MR)
2. Click the link from email (https://markuphero.com/share/3sGGU2kjXm3rtZT1bSPe)

**AR**:
"Password reset successful!" message on top left corner (https://markuphero.com/share/WHF0mIlQVcF0Q4AkWKQq)
**ER:**
Form to reset password (I guess so, never used this flow before)

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.84.12**

Installed NocoDB with docker-compose (latest)

**Comment by dstala** [comment]
@alprotasov Thanks for the details.
Able to reproduce issues locally. We will investigate further.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/commit/c7e7603f58e46b24d0978033c586ecb5a1daa4f8

**Comment by cuizhao** [comment]
This bug reappears in the version of   0.90.5. The user use the funciton of "change password" shows sucessfully,But there is nothing changed,you also must use the old password login ,and the new password not valid.The I check the mysql ,I found that nc_users_v2 is not have any changed.

**Comment by wingkwong** [comment]
@cuizhao Are you talking about Change Password instead of Reset Password? If so, please create a new issue instead.

**Comment by cuizhao** [comment]
> The user use the funciton of "change password" shows sucessfully,But there is nothing changed,you also must use the old password login ,and the new password not valid.Then I check mysql's table ,I found that nc_users_v2 is not have any changed.

Yes ,I will create a new issue!
