### ISSUE TITLE
[Feature] Limit Swagger API access

### ISSUE THREAD

**Issue by richnourichnou** [nocodb/nocodb#1338]
For security reasons, it would be nice to be able to:

- disable swagger completely
- limit the access of the swagger only to certain roles, for each Project

It's a handy tool, but a bit talkative for my taste ;-)

**Comment by dstala** [comment]
Swagger API link is not visible for `commenter` and `viewer` roles (as observed in latest release)
@richnourichnou If this doesn't suffice your requirements, do re-open this issue.
