### ISSUE TITLE
Has Many single select filtering not working

### ISSUE THREAD

**Issue by DOFfactory** [nocodb/nocodb#1341]
**Steps To Reproduce**
1. Create a LinkToAnotherRecord column with Has Many option
2. The linked column has to be single select type
3. Add a value
4. Search for a value from the list, the filtering does not work

**Expected behavior**
The filtering should work similarly as in the Many to Many option

**Screenshots**
N/A

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.12**

**Comment by wingkwong** [comment]
Mind to provide some screenshots? Are you talking about the search in Link Record?

<img width="586" alt="image" src="https://user-images.githubusercontent.com/35857179/155455795-86e5570e-1fa4-47c1-b6c9-14c8d3a1c59b.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/35857179/155455809-9a1be0f4-1c57-43e0-adec-8cd423c85a0f.png">

**Comment by DOFfactory** [comment]
Yes, this is exactly the place, did you try with a longer list? I have around 600 records with names (sorry cannot share a screenshot), and while the Link Record page filters some of these, it does not filter to the single name

**Comment by wingkwong** [comment]
Could you help provide some dummy data based on your records? Not sure if there is a specific pattern to make it fail.

**Comment by ylsama** [comment]
One to Many Select
Node: v16.14.1
Platform: linux
Docker: false
Database: pg
ProjectOnRootDB: true
RootDB: pg

Build from source commit 8400c313906da8293014fd57b27653b0d806d4f8
nocodb: 8.6.0

![Screenshot from 2022-04-06 14-26-37](https://user-images.githubusercontent.com/31164703/161919336-ab11e1e7-fc44-48fd-b11f-74c8e4b4c2e6.png)
![Screenshot from 2022-04-06 14-27-15](https://user-images.githubusercontent.com/31164703/161919347-76622f2e-c46e-4965-bd9d-1254c63ab710.png)

**Comment by wingkwong** [comment]
Version is a bit old. Suggest to try on latest version. Free feel to reopen it if neccesary.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/35857179/197950548-2a6c1a7a-e177-46c1-90a9-549a37cda8f2.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/35857179/197950517-0041ee2d-9a45-4f83-b4e5-4ab1abaad746.png">

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.98.1**
```
