### ISSUE TITLE
No Access to any project using API Key

### ISSUE THREAD

**Issue by sutidor** [nocodb/nocodb#1344]
**Please enter the following details**

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.12**

please provide the following details :

**Steps To Reproduce**
1. Create Project
2. Create API Key
3. Go To Swagger, Authenticate (works using API Key)
4. (optional) change user password etc., all from "Authenticate" works fine
5. Get List in Project, does not work using API key. `ERROR: Forbidden - perhaps check your credentials?
Access Denied : Please Login or Signup for a new account`. It works using "Copy Auth Token" though.

**Extra steps undertaken (suspected header auth issue)
1. Using nginx reverse proxy, forwarded xc-header. No change in behavior.
2. deployed exposing the port directly, no change in behaviour
3. added the URL and backend URL, no change in behaviour

**Expected behavior**
Works normally without error

I mean, it should be possible using the API key, right? Or am I SUPPOSED to use the refresh token from the login?

**Comment by wingkwong** [comment]
If you're using Swagger, you need ``xc-auth`` rather than ``xc-token``. ``xc-auth`` is for internal users while ``xc-token`` is for external users (like third-party apps).
