### ISSUE TITLE
[Feature] Currency Column Improvement

### ISSUE THREAD

**Issue by vijayrathore8492** [nocodb/nocodb#1352]
## Recommending Features

NocoDB thrives on community needs. Many of our existing features are derived from community requirements & we will continue to build that way. We invite ideas to make NocoDB better. Do note that, we being an open-source team are constrained by resources & will be able to pick only limited **high demand** ideas for release. So, if you wish to pick this feature request early - spread the word, discuss it in Discord/blog/Reddit, ask your peers & colleagues to vote up for this feature request!

**Need for this feature**
Current currency column is very basic and does not serve it's purpose fully. 

**Describe the solution you'd like**
Currency column creation window should offer a currency and a data type - INT, DECIMAL for the new column. 
The currency should be indicated in column header and every value in a column should be postfixed or prefixed with the currency.

**Describe alternatives you've considered**
I am using regular decimal column for now as currency column provides nothing extra.

**Comment by wingkwong** [comment]
For the data type, you can click ``Show more options`` to choose it.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/35857179/155513396-532180e1-b941-4890-93be-d11d008e27d1.png">

**Comment by vijayrathore8492** [comment]
@wingkwong I am aware of that. But that brings no more advantage than a plain number column.

**Comment by wingkwong** [comment]
@vijayrathore8492 Agree. Some also shared their thoughts about currency field (See [here](https://github.com/nocodb/nocodb/issues?q=is%3Aissue+is%3Aopen+currency)). We'll work on it accordingly.

**Comment by mertmit** [comment]
@vijayrathore8492 I am happy to announce we have revised the currency column to support different locales and currency codes. I hope our new implementation in develop branch cover your needs. Feel free to update the issue if anything missing for you.
![image](https://user-images.githubusercontent.com/59797957/170151515-7d0ff620-d1d2-44d3-a7e8-62947d4fcc15.png)
