### ISSUE TITLE
Text doesn't show up in Swagger Form for POST requests body

### ISSUE THREAD

**Issue by aksanoble** [nocodb/nocodb#1367]
**Please enter the following details**

Copy and paste project info 

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.84.9**

**Steps To Reproduce**

1. Go to 'Swagger docs for a particular table'
2. Click on the Body section of any post request, try typing anything
3. Cursor isn't shown and text doesn't appear in body. 

**Expected behavior**
Text should be shown.

**Comment by wingkwong** [comment]
Able to reproduce. Will take a look.

**Comment by wingkwong** [comment]
Fixed in `v0.84.15`.
