### ISSUE TITLE
Support ?ssl=true is NC_DATABASE_URL

### ISSUE THREAD

**Issue by frwickst** [nocodb/nocodb#1369]
**Please enter the following details**

NocoDB used as docker : true
NocoDB version : 0.84.14
Database used in NC_DB URL  : pg
Database version : 12.9

**Steps To Reproduce**
Create a postgres database that requires SSL and try to connect to it with a DATABASE_URL including`ssl=true`

**Expected behavior**
For it to connect to the database.

**Issue**
The issue here seems to be that you are using a very old package for parsing the database url `node-parse-database-url` this package does not seem to support this feature as made apparent here https://github.com/pwnall/node-parse-database-url/issues/8
Please consider moving to a more modern library that would support this feature.

**Comment by wingkwong** [comment]
> Create a postgres database that requires SSL

Is it for meta database or data database?

**Comment by frwickst** [comment]
If I understand your question correctly, then a "data database" is what I'm referring to.

**Comment by wingkwong** [comment]
I'm not sure if you are using one-click deployment as `NC_DATABASE_URL` is used in Heroku and the database specified in ``NC_DATABASE_URL`` is used as a meta database. If your database is used to store the data that is displayed in Nocodb, then you can specify under SSL & Advanced parameters when you create a project.

![image](https://user-images.githubusercontent.com/35857179/159106957-5ca5db56-8df4-4e75-b7a7-b4c46a389d53.png)

If you are confused about meta / data database, you may check out this [link](https://docs.nocodb.com/#architecture---simple-overview). The meta database is NC_DB (aka master database) and the data database is the external databases.

**Comment by wingkwong** [comment]
Tested on latest version (0.100.2). You can append the following in `NC_DATABASE_URL`.

```
?ssl={rejectUnauthorized: false}
```
