### ISSUE TITLE
Feature : SQL Editor

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#137]
- [ ] MySQL
- [ ] Postgres
- [ ] SQL Server
- [ ] MariaDB
- [ ] SQLite

**Comment by cleder** [comment]
May I draw your attention to https://github.com/vuerd/vuerd 
A visual SQL is on the roadmap, and the visualization of the ERD of the DB would come in handy as well ;-)

**Comment by o1lab** [comment]
This wont be part of our roadmap
