### ISSUE TITLE
Feature : Spreadsheet : Formula Column

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#138]
- [x] MySQL
- [x] Postgres
- [x] SQL Server
- [x] MariaDB
- [x] SQLite

**Comment by o-data** [comment]
Hi o1lab, 

Does this mean that nocodb will be supporting Formula or calculation? 

For example; multiplication (\*), addition (+), subtraction (-), division?

**Comment by verekia** [comment]
They plan to support much more than that, there is a lot of functions shown in the field details, but unfortunately, it's "Coming Soon" at the moment.

<img width="404" alt="Screenshot 2021-05-28 at 10 44 59" src="https://user-images.githubusercontent.com/522007/119926621-ffe2d000-bf77-11eb-8b08-5e954375e367.png">

For my personal usage, this is an essential feature. I'm using Airtable extensively, but I wouldn't if they didn't have the formula field. That's what actually enables "no-code" in my opinion.

Looking forward to NocoDB supporting it :)

**Comment by crueber** [comment]
I agree with the above. NocoDB is pretty great so far, but this is what makes airtable my replacement for spreadsheets. Looking forward to this!

**Comment by pranavxc** [comment]
Basic Formula support added in `0.11.17`

**Comment by pranavxc** [comment]
> Hi o1lab, 
> 
> Does this mean that nocodb will be supporting Formula or calculation? 
> 
> For example; multiplication (*), addition (+), subtraction (-), division?

Yes these operations are available
