### ISSUE TITLE
Failed to create column with datatype 'Time'

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1380]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.84.14**

Steps
- Add column of type 'Time'
- Toast message 'Update failed' pops up
- Any subsequent column addition fails from this point onwards

**Comment by wingkwong** [comment]
It seems that this issue has been fixed at some point.

![image](https://user-images.githubusercontent.com/35857179/164217236-10714032-3129-487f-aa63-d62155827d84.png)

Node: **v12.22.12**
Arch: **arm64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.5**
