### ISSUE TITLE
Excel import : long text cells not displayed with column title containing commas and accents

### ISSUE THREAD

**Issue by cacmar** [nocodb/nocodb#1387]
Hello,

I have some troubles when I import my Excel file to create a new project with NocoDB.

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.10**

I noticed that NocoDB dont realy like commas, spaces and accents in columns titles. 
When importing datas, the "_" is used to replace unwanted characters, but in my case my data are not displayed after loading. When I rename the column title, my datas are back.

Do you have any suggestions ?

**Steps To Reproduce**
1. Create a new project with my file 'test_import_longtext - lorem'
2. Check the cells (they seams to be empty)
3. Rename the column 'Pr_sentation_de_mon_activit___entreprise__parcours_de_chef_d_entreprise__' to 'test' for exemple
4. The cells are full

[test_import_longtext - lorem.xlsx](https://github.com/nocodb/nocodb/files/8154521/test_import_longtext.-.lorem.xlsx)

All the best and thank you for this great project

**Comment by dstala** [comment]
Issue reproduced as described in Heroku PG environment.
Problem appears to be associated with length of column name. If I rename column name to Pr_sentation_de_mon_activit___ from Pr_sentation_de_mon_activit___entreprise__parcours_de_chef_d_entreprise__, import works fine.

Import works fine with following environment
Node: **v12.22.6**
Arch: **arm64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.84.14**

**Comment by dstala** [comment]
Could be associated with this PG constraint

https://www.postgresql.org/docs/7.0/syntax525.htm#:~:text=Names%20in%20SQL%20must%20begin,but%20they%20will%20be%20truncated.

By default, NAMEDATALEN is 32 so the maximum name length is 31 (but at the time the system is built, NAMEDATALEN can be changed in src/include/postgres_ext.h).

**Comment by cacmar** [comment]
Thank you @dstala for your answer

Could it be possible to add some control on the title lenght ? End users will always forget it.

Have a nice day
