### ISSUE TITLE
it's maybe to easy to delete rows

### ISSUE THREAD

**Issue by cacmar** [nocodb/nocodb#1388]
Hello,

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.10**

Even with practice I feel like it's to easy to delete data by mistake and even more at the bottom of the page.
At the last row, with a single right click we are at the same level as the feature "delete" which don't need any user confirmation.

![image](https://user-images.githubusercontent.com/95369211/156014043-04b1b08f-ee64-40d3-befd-fb10a12f778d.png)

What do you think about adding a yes/no pop-up ? or any UX trick ?

Thank you

**Comment by o1lab** [comment]
I believe, adding popup will not be a good experience as we dont see this in spreadsheets.

However, we can think of undo option.

**Comment by Xpressdesigns** [comment]
an undo option for this scenario would be great
