### ISSUE TITLE
Formula should support date arithmetic

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1389]
```IF(Category=="A lot",ADD(lastcontact,21))```

**Comment by thunderrabbit** [comment]
Thank you Naveen

This came up for me when trying nocodb for https://jakobgreenfeld.com/stay-in-touch

I hope nocodb can do something like `DATEADD({date column},12,'month')`

and `IF(NOW() >= {date column}, ....)`

**Comment by wingkwong** [comment]
Available in `v0.84.15`.
