### ISSUE TITLE
[i18n] Language support extension- fr

### ISSUE THREAD

**Issue by Rouffi** [nocodb/nocodb#1398]
# i18n translation request

1. Existing language translation corrections request
2. Associated language code : fr
3. Google spreadsheet [[Shared link](https://docs.google.com/spreadsheets/d/1MM_QJlxWimcuJ3lWurfZN90f6vM63-rAmSOXQZPRtks/edit?usp=sharing)]
4. Summary of the changes made: I went through the entire language column to make a massive batch of corrections. Some of them were blocking especially at the login stage.

**Comment by dstala** [comment]
Proposed changes: 

<google-sheets-html-origin><style type="text/css"></style>

fr (old) | fr (new)
-- | --
Montre plus | Montrer plus
Enlever tout | Tout retirer
Déconnexion | Inscription
Télécharger | Téléverser
Suite | Plus
État | Condition
Avant de | Avant
Une fonction | Fonction
les tables | Tableaux
Domaine | Champ
Des champs | Champs
Enregistrement | Entrée
Record | Entrées
Voir | Vue
Les rôles | Rôles
Téléspectateur | Spectateur
Texte unique | Texte court (une ligne)
Attachement | Pièce jointe
Sélectionner un seul | Menu déroulant
An | Année
E-mail | Couriel
URL | Lien URL
Rouler | Synthèse
Compter | Compteur
Créer du temps | Date de création
Dernière heure modifiée | Dernière modification
Numéro automatique | Numérotation automatique
code à barre | Code barre
Cascade | Chevauchement
Restreindre | Limité
Se mettre de null | Laisser vide
est égal | est égale
n'est pas égal | n'est pas égale
Titre de formulaire | Intitulé du formulaire
Roles & Gestion utilisateurs | Rôles & Gestion utilisateurs
Metadata d'exportation / importation | Exporter / importer les métadonnées
Contrôle d'accès interface utilisateur | Contrôle d'accès à l'interface utilisateur
réinitialisez votre mot de passe | Réinitialiser le mot de passe
Nom de colonne | Nom de la colonne
Tapez la base de données | Écrire dans la base de données
Type de fonctionnement | Type d'opération
Fonctionnement Sous-type | Sous-type d'opération
La description | Description
Discuter | Discussion
E-mail | Courriel
Des modèles | Modèles
Établi | Créé
Fonction globale | Fonction agrégée
Base de données : la créér si elle n'existe pas | Base de données : la créer si elle n'existe pas
serveur d'AC | Serveur d'authentification
AC requise | Authentification requise
Donner nous une étoile | Étoile
Planifier une démo gratuite | Planifier une démonstration gratuite
Join Discord | Rejoindre le serveur Discord
Join /r/NocoDB | Rejoindre /r/NocoDB
Sur la mise à jour | Mise à jour en cours
Sur Supprimer | Suppression en cours
Projet d'importation | Importer un projet
Editer le projet | Éditer le projet
Rafraichir les projets | Actualiser les projets
Créer en se connectant<br>à une base de données | Créer en se connectant<br>à une base de données externe
Créer un projet d'Excel | Créer un projet depuis Excel
Créer un projet à partir du modèle | Créer un projet à partir d'un modèle
Projet OK et sauvegarder | Valider et enregistrer le projet
Mise à niveau disponible | Mise à jour disponible
Comment mettre à niveau? | Comment mettre à jour ?
Aide à traduire | Aider à la traduction
Copier Auth Jeton | Copier le jeton d'authentification
Sorte | Trier
Filtre | Ajouter un filtre
Lien de base partagé | Partager le lien de la base
Inviter jeton | Inviter via un jeton
Rôles de rechargement | Actualiser les rôles
Record | Prochain enregistrement
Enregistrement précédent | Précédent enregistrement
Créer une table | Créer un tableau
Tables rafraîchir | Actualiser le tableau
Table Renommer | Renommer le tableau
Tableau Supprimer | Supprimer le tableau
Importer Excel | Importer depuis Excel
Télécharger csv | Téléverser un CSV
Liste de visualisation partagée | Liste de vues partagées
Créer une vue de grille | Créer une vue grille
Créer une vue de la galerie | Créer une vue galerie
Créer une vue de formulaire | Créer une vue formulaire
Copier le code HTML incorporable | Copier le code HTML intégré
Ajouter une nouvelle webhook | Ajout de webhook
Ajouter de nouveaux jetons | Ajout de nouveau jeton
Exportation zip | Exporter un zip
Importer zip | Importer un zip
Aperçu comme | Aperçu
Test la connexion à la base de données | Tester la connexion à la base de données
Editer le JSON de la connexion | Éditer le JSON de connexion
Parrainez-nous | Nous Parrainer
Il vient en noir (^ ^b) | Nuit (^⇧B)
Vient-il en noir? (^ ⇧b) | Jour (^⇧B)
Liste de rechargement | Actualiser la liste
Annuler et revenir | Annuler et revenir en arrière
Selectionner le fichier .key | Selectionner un fichier .key
Selectionner le fichier .cert | Selectionner un fichier .cert
Selectionner le fichier CA | Selectionner un fichier d'authentification
Tables de recherche | Chercher un tableau
Applications de recherche | Chercher une application
Modèles de recherche | Chercher un modèle
Filtrer par e-mail | Filtrer par courriel
Rangées par page | Lignes par page
Sélectionnez Fichier pour télécharger | Sélectionnez un fichier à téléverser
ou fichier glisser-déposer | ou glisser-déposer un fichier
Voulez-vous arrêter le projet? | Voulez-vous arrêter le projet ?
Voulez-vous commencer le projet? | Voulez-vous démarrer le projet ?
Voulez-vous redémarrer le projet? | Voulez-vous redémarrer le projet ?
Voulez-vous supprimer le projet? | Voulez-vous supprimer le projet ?
Générer une base réadonnée partageable partageable | Générer une base partagée en lecture seule
Toute personne sur Internet avec ce lien peut voir | Toute personne avec ce lien peut consulter
On dirait que vous n'avez pas encore configuré Mailer! \ n S'il vous plaît copier ci-dessus inviter lien et l'envoyer à | On dirait que vous n'avez pas encore configuré Mailer! \ n Merci de copier-coller le lien d'invitation ci-dessous et l'envoyer à
Entrez le formulaire étiquette d'entrée | Entrer le libelé du formulaire
Ajouter du texte d'aide | Ajouter du texte d'assitance
Ajouter un formulaire Description | Ajouter un formulaire de description
Cette vue est partagée via un lien privé | Cette vue est partagée avec un lien privé
Après le formulaire est soumis | Après que le formulaire est soumis
E-mail moi à | Écrivez-moi à
Export Project Meta vers Zip Fichier et télécharger. | Exporter le meta projet dans un fichier Zip et le télécharger.
Importer le projet META ZIP et redémarrer. | Importer le fichier ZIP du meta projet et redémarrer.
Dégager | Effacer
Vous pouvez nous aider! | Vous pouvez nous aider !
Vous avez déjà un compte ? | Avez-vous déjà un compte ?
Adresse Email requise | Adresse mail requise
L'adresse Email doit être valide | L'adresse mail doit être valide
Les métadonnées de projet ont exporté avec succès | Les métadonnées de projet sont exportée avec succès
Les métadonnées du projet ont importé avec succès | Les métadonnées du projet sont importée avec succès
Les métadonnées du projet ont effacé avec succès | Les métadonnées du projet sont effacée avec succès
Projet a commencé avec succès | Projet démarré avec succès
Auth Token copié dans le presse-papiers | Auth Token copié dans le presse-papier
Informations de projet copiées au presse-papier | Informations de projet copiées dans le presse-papier
Envoi d'une URL d'invitation copiée dans le presse-papier | URL d'invitation copiée dans le presse-papier
Voir créé avec succès | Vue créé avec succès
Passé avec succès à la vision collaborative | Vous êtes bien dans la vue collaborative
Passé avec succès à la vue verrouillée | Vous êtes bien dans la vue vérouillée
Bientôt disponible! | Bientôt disponible !

**Comment by dstala** [comment]
Thanks a lot @Rouffi 
https://github.com/nocodb/nocodb/commit/947570e265da3ab5f4c8e07a2e1a9cd11862f1d8
