### ISSUE TITLE
[Feature] Choose how many rows to show on each page. 

### ISSUE THREAD

**Issue by kristinbb** [nocodb/nocodb#1418]
Currently, only 25 rows can fit on the same page. Sometimes it is tedious and time consuming to scroll through multiple pages in NocoDB. 

I would like to be able to choose how many rows to show on each page. For example like 25, 50, 100, all.

**Comment by wingkwong** [comment]
You can find the answer in this discussion thread - [How do I increase the number of rows in each page in a table ?](https://github.com/nocodb/nocodb/discussions/942)
