### ISSUE TITLE
[Feature] Better copy pasting from NocoDB

### ISSUE THREAD

**Issue by kristinbb** [nocodb/nocodb#1419]
I would like a better user experience of coping certain rows and columns and the pasting them into another spreadsheet like Excel. Request:
- Select certain columns and rows to copy with Command/Ctrl
- Mouse hover and select rows/columns to copy.

**Comment by wingkwong** [comment]
Duplicated. See #978 which was also created by you. You can modify the old one if you have new ideas related to copy-pasting.

**Comment by kristinbb** [comment]
Sorry, forgot I already asked this. Thanks 🙏
