### ISSUE TITLE
Feature : Spreadsheet : Support Form View

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#142]

**Comment by Charuru** [comment]
Any updates on this?

**Comment by almereyda** [comment]
When implementing a form submission flows through the form view, it will be very useful to send email confirmations to the user who submit, and to the maintainers of the table.

**Comment by o1lab** [comment]
on insert webhook + SMTP app within our app store can be used to send emails.

**Comment by almereyda** [comment]
thanks, will check! that will come in handy, when form support lands

**Comment by o1lab** [comment]
0.11.42

**Comment by o1lab** [comment]
advanced features will come in this #608

**Comment by candidexmedia** [comment]
Love this feature! Is it possible to change the logo in the form?
