### ISSUE TITLE
[i18n] Language support extension- <fa>

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#1420]
# i18n translation request for Farsi (Persian)

**1. Correction & Addition**
- We have completed the translation which had been done using google translate and was inaccurate. So we removed the Google Translate formulas and wrote the correct translations.

**2. Associated language code : fa**

**3. Google spreadsheet (public link included)**
- https://docs.google.com/spreadsheets/d/1Kf17eiCwWFTgjNzl9-E2E7WrdoV-R7ffr2aDc0bXu1A/edit?usp=sharing

**4. Summary of the changes made**
- The translation had been done incompletely and inaccurately. Therefore, we translated every single string again.

**5. Any specific message to be conveyed to moderators?**
- Farsi ( also Arabic & Hebrew ) is written from right to left. So we need NocoDB developers to include RTL direction in the interface to make it more convenient for Persian clients.

**Comment by dstala** [comment]
changes so far are integrated, disabled for now to include RTL direction in the interface.
https://github.com/nocodb/nocodb/commit/5511671426875c5aea5c117fc0ea8197b7713f40

[master spreadsheet](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172) is updated

@okaeiz
there were recent additions to the master spreadsheet (listed below). For these, we have picked up results from google translate. help us confirm if they are right. they are highlighted in yellow too in the master spreadsheet. you can make a copy and share change proposals here.

<google-sheets-html-origin><style type="text/css"></style>

fa | en
-- | --
درج کردن | Insert
عنوان | Title
بارگذاری | Upload
دانلود | Download
پیش فرض | Default
بیشتر | More
کمتر | Less
رویداد | Event
شرایط. شرط | Condition
بعد از | After
قبل از | Before
جستجو کردن | Search
اطلاع | Notification
ارجاع | Reference
تابع | Function
هیچ اقدام | No Action
آبشار | Cascade
محدود کردن | Restrict
تنظیم صفر | Set NULL
مجموعه پیش فرض | Set Default
کنترل دسترسی UI | UI Access Control
از طریق اطلاع | Notify Via
نام جدول | Table name
گزینه اضافه کردن | Add option
تابع جمع | Aggregate function
مرجع سند | Document Reference
نقش کاربر را انتخاب کنید | Select User Role
جدول کودک | Child table
ستون کودک | Child column
در به روز رسانی | On Update
در حذف | On Delete
حذف جدول | Table Delete
ذخیره تغییرات | Save changes
متاداده جداول همگام سازی است | Tables metadata is in Sync
شما می توانید چندین ایمیل جداگانه کاما (،) را اضافه کنید | You can add multiple comma(,) separated emails
نام جدول را وارد کنید | Enter table name
ستون های پیش فرض را اضافه کنید | Add default columns
نام جدول به عنوان ذخیره شده در پایگاه داده | Table name as saved in database

**Comment by okaeiz** [comment]
Hi back!
We have made a few changes and here's the final edition.

https://docs.google.com/spreadsheets/d/1DFzEqoMgAHerNwugm5DU0fn6St1zSjcsjbmmb01DVFk/edit?usp=sharing

We will be thankful if RTL direction gets included as well.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/1797
