### ISSUE TITLE
/distinct Rest API endpoint throws error for table with json columns |PG|

### ISSUE THREAD

**Issue by vijayrathore8492** [nocodb/nocodb#1422]
**Please enter the following details**

please provide the following details :
NocoDB used as docker :  false
NocoDB version : 0.84.14
Database used in NC_DB URL  : sqlite3 
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : MacOS Monterey
Node.js version if running as node : v12.22.10
Database version : 

**Steps To Reproduce**
1. Create a JSON column in a table.
2. Call /distinct endpoint of the table
3. You will see error as `could not identify an equality operator for type json`

**Expected behavior**
It should not fail.

**Screenshots**

Join our discord : https://discord.gg/5RgZmkW for realtime help.

Node version : **v12.22.1**
Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
packageVersion: **0.9.27**

**Comment by wingkwong** [comment]
Able to see `/distinct` not working as expected but didn't see the error message you provided. Could you please share your curl command?

**Comment by vijayrathore8492** [comment]
@wingkwong Yeah, This is the PR for fixing `/distinct` https://github.com/nocodb/nocodb/pull/1433. The error comes when there's json column in `postgres` and you try to find distinct.

**Comment by wingkwong** [comment]
What does `selectFormulasForColumns` & `filterFormulaColumns` do in this issue?

**Comment by vijayrathore8492** [comment]
@wingkwong The PR is fixing the `/distinct` API. Distinct on JSON column would still result in SQL error. I have noticed this behavior in `Postgres`. 

`selectFormulasForColumns` gives back decoded formulas for given columns, inspired by `selectFormulas` and `filterFormulaColumns` filter formula columns from given columns.

**Comment by wingkwong** [comment]
@vijayrathore8492 Okay. Will take a look.
