### ISSUE TITLE
Not fetching the data of tables after meta-sync

### ISSUE THREAD

**Issue by richnourichnou** [nocodb/nocodb#1429]
# Issue

I've access to all my data in nocodb, structure seems to be not accessible by the system...

But when I'm going to pg with DBeaver, data are allways here...

# Steps

-   Sync metadata tables
-   Stop Project
-   Start Project
-   Tables are empty in Noco, with message "Update & Delete not allowed since the table doesn't have any primary key" on all tables...
-   Tables Empty with restapi access
-   but data are still here...

# Screenshots

### Noco is empty
![](https://atontour.eu/nocodb-issues/nocodb-empty.jpg)

### Rest API is empty
![](https://atontour.eu/nocodb-issues/restapi-empty.jpg)

### But database looks correct...
![](https://atontour.eu/nocodb-issues/database-full2.jpg)

# project info

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.14**

Hosting by Heroku (free version)

**Comment by o1lab** [comment]
What was the database change done via DBeaver which required a meta sync in nocodb GUI ?

I've DMed you in discord - happy to help.

**Comment by o1lab** [comment]
Feel free to reopen if the issue exist in latest version.
