### ISSUE TITLE
Primary key column contains duplicate values

### ISSUE THREAD

**Issue by aksanoble** [nocodb/nocodb#1435]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.84.9**

**Steps To Reproduce**
1. Go to table
2. Click on create new column > Single Line Text + advanced option > select PK (primary key) 
3. Create 2 new rows with the same value for the column
4. No error thrown with the same value in the primary key column

**Expected behavior**
failure to add two rows with the same value for primary key column

**Screenshots**
<img width="153" alt="Screenshot 2022-03-12 at 3 07 49 PM" src="https://user-images.githubusercontent.com/7472506/158012868-9a4dcbea-104d-49f1-8245-0c4a7a3ec96f.png">

**Comment by o1lab** [comment]
When table is created - There is an auto increment ID that is already created. (to see this primary key, go to, fields -> show system fields)

And in step2 - you are essentially creating a composite primary key. And hence the duplicate value in singline text is allowed.

**Comment by wingkwong** [comment]
When you create a table, there is a primary key called `id`. If you create a new column called `primary` and set it as PK, then it would be composite PK. You can show the system field to see that field.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/35857179/158013206-abf88aee-ca05-41fd-93c2-b4dde5228aed.png">

If there is only one PK, you are expected to see this error.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/35857179/158013132-21929c2f-d489-45c8-ac96-b72008e9a8bb.png">

**Comment by aksanoble** [comment]
@wingkwong @o1lab  While I do see this error the values are reflected in the column. Isn't that a problem? 
Also is there a way to add a constraint to make a column have unique values only?

**Comment by wingkwong** [comment]
> While I do see this error the values are reflected in the column. Isn't that a problem?

The values are not saved. You can simply refresh the page or click reload button.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/35857179/158013471-1bdf1baa-29df-4c52-983b-99bb32cba886.png">

> Also is there a way to add a constraint to make a column have unique values only? Should I be doing it directly via alter table ?

Yes. You can alter your table to make your column unique.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/35857179/158013544-3de6c316-3438-41d2-9a30-135f3fc4e216.png">

**Comment by aksanoble** [comment]
Thanks! I still see the values post refresh. 

<img width="603" alt="Screenshot 2022-03-12 at 3 35 38 PM" src="https://user-images.githubusercontent.com/7472506/158013720-c8e381cd-8c09-43bf-beda-07ad392f8cb6.png">

**Comment by wingkwong** [comment]
You have a composite PK. It is expected to see that. If you want to have a composite PK while keeping primary unique, you need to clean the data first, then make the column unique and add the data.

**Comment by aksanoble** [comment]
@wingkwong Got it. Thank you. I also noticed while adding values to the composite key column I get `Undefined binding(s) detected`. Not sure what to make of it. 
![Uploading Screenshot 2022-03-12 at 4.58.25 PM.png…]()

**Comment by o1lab** [comment]
Supporting composite primary key is tricky as of now. However, I 've to say we 've the necessary APIs in place - need to get the UI aspect right while creating these keys and data entry.

**Comment by o1lab** [comment]
Composite PK is tracked in #871.
Will close this.
