### ISSUE TITLE
Importing metadata creates new project instead of update

### ISSUE THREAD

**Issue by aksanoble** [nocodb/nocodb#1436]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.9**

**Steps To Reproduce**
1. Go to My projects
2. Click on import metadata for any project
3. Upload meta.zip file and a new project gets created. 

**Expected behavior**
Existing project's meta data gets updated.

**Comment by wingkwong** [comment]
Import / Export have been deprecated.
