### ISSUE TITLE
🐛 Bug: Updating an existing webhook leads to an error

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1439]
- Create a webhook calling an URL
- Now try updating some aspect of it - like GET/POST or URL Change
- Hitting save an error is shown.

`0.84.14`

**Comment by wingkwong** [comment]
Not able to reproduce at `v0.84.15`. Any error message?

**Comment by o1lab** [comment]
Node: **v12.22.10**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.15**

**Comment by o1lab** [comment]
Was reproducible on heroku. Changing from get to post.

**Comment by o1lab** [comment]
Good to close. Works now.
