### ISSUE TITLE
Display problem on two columns on a table that addresses the same external table 

### ISSUE THREAD

**Issue by cvalla** [nocodb/nocodb#1444]
NocoDB used as docker : true 
NocoDB version : 0.84.15
Database used in NC_DB URL  : mysql 
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql 
OS on which NocoDB is running :  Linux (container on Kubernetes
Node.js version if running as node : 
Database version :  5.7.36

**Steps To Reproduce**
On mysql nocodb ver with these tables:
```
CREATE TABLE `ccoe_domini` (
  `nome_dominio` varchar(100) NOT NULL,
  `layer` varchar(100) NOT NULL,
  PRIMARY KEY (`nome_dominio`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ccoe_processi` (
  `nome_processo` varchar(100) NOT NULL,
  `fk_dominio` varchar(100) NOT NULL,
  `descrizione` mediumtext,
  PRIMARY KEY (`nome_processo`),
  KEY `ccoe_processi_FK` (`fk_dominio`),
  CONSTRAINT `ccoe_processi_FK` FOREIGN KEY (`fk_dominio`) REFERENCES `ccoe_domini` (`nome_dominio`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ccoe_internal_interfaces` (
  `from` varchar(100) NOT NULL,
  `to_processo` varchar(100) DEFAULT NULL,
  `to_dominio` varchar(100) NOT NULL,
  `descrizione` mediumtext NOT NULL,
  `id_internal_rel` varchar(203) DEFAULT NULL,
  KEY `ccoe_internal_interfaces_FK_2` (`to_dominio`),
  KEY `ccoe_internal_interfaces_FK` (`from`),
  KEY `ccoe_internal_interfaces_FK_1` (`to_processo`),
  CONSTRAINT `ccoe_internal_interfaces_FK` FOREIGN KEY (`from`) REFERENCES `ccoe_processi` (`nome_processo`) ON UPDATE CASCADE,
  CONSTRAINT `ccoe_internal_interfaces_FK_1` FOREIGN KEY (`to_processo`) REFERENCES `ccoe_processi` (`nome_processo`) ON UPDATE CASCADE,
  CONSTRAINT `ccoe_internal_interfaces_FK_2` FOREIGN KEY (`to_dominio`) REFERENCES `ccoe_domini` (`nome_dominio`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

When the table **ccoe_internal_interfaces** is displayed in nocodb seems that columns **from** and **to_processo** (that are fk of the same  table but have different values) have the same value. Only values of the  **from** column is displayed also on **to_processo**.

**Expected behavior**
Two columns referencing the same table displays correct values

**Screenshots**
![image](https://user-images.githubusercontent.com/11733442/158345761-697facba-d516-4a28-9bac-788a916368cf.png)

Data used to visualize 
|from|to_processo|id_internal_rel|
|----|-----------|---------------|
|Building Block Architecture and Implementation|Cloud Platform Change Management|Building Block Architecture and Implementation -> Cloud Platform Change Management|
|Building Block Architecture and Implementation|Cloud Service on the shelf Management|Building Block Architecture and Implementation -> Cloud Service on the shelf Management|
|Cloud Onboarding Management|Building Block Architecture and Implementation|Cloud Application Onboarding Management -> Building Block Architecture and Implementation|
|Cloud Onboarding Management|Cloud Capacity & Performance Management|Cloud Application Onboarding Management -> Cloud Capacity & Performance Management|

**Comment by cvalla** [comment]
Hi there, there are any update on this issue?

**Comment by cvalla** [comment]
@pranavxc  could  you take a look to this issue?

**Comment by pranavxc** [comment]
@cvalla Since `0.9.x` we are supporting duplicate relations, you can try our latest version.

**Comment by cvalla** [comment]
Hi @pranavxc  and thank you for the prompt respose. updated to version 0.92.4 but seems that the issue is NOT resolved. 
![image](https://user-images.githubusercontent.com/11733442/182832029-4f1270f9-93cf-44d2-bba1-88983671ae65.png)

**Comment by pranavxc** [comment]
@cvalla - Update one of the column names, currently both are the same, probably that will solve the issue with the new version.

**Comment by cvalla** [comment]
Hi, @pranavxc, I updated the tables and confirm that now everithing is OK. Thank you very much
