### ISSUE TITLE
Trying to connect nocodb(docker-compose) to patroni cluster in docker swarm. Error: pg_hba.conf rejects connection for host (ip address from overlay network). 

### ISSUE THREAD

**Issue by knurdmas** [nocodb/nocodb#1450]
I have vm with nocodb and patroni cluster for services. If i try connect nocodb to patroni i have error "pg_hba.conf rejects connection for host". Nocodb image version 0.84.14.  Patroni cluster in docker swarm with HAproxy and VIP address.

**Comment by knurdmas** [comment]
Я проверял pg_hba.conf, в нем все в порядке. Другие вмки в одной сети с nocodb не испытывают проблем с подключением к кластеру

**Comment by wingkwong** [comment]
Have you setup SSL when creating the project?

**Comment by knurdmas** [comment]
> Have you setup SSL when creating the project?

No. ssl verification is disabled, in the environment that needs this patroni ssl is not used

**Comment by knurdmas** [comment]
what other information can i provide?

**Comment by dstala** [comment]
@knurdmas if you still have issues connecting, please get in touch with us over discord.
