### ISSUE TITLE
multiple after-update webhooks being triggered when changing value in SingleLineText / LongText

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#1453]
When editing these cells, `onCellValueChange` will be triggered from time to time if the current value is different than the previous one to prevent data loss. However, if users configure after-update webhooks, they will be triggered along with `onCellValueChange`.

**Comment by o1lab** [comment]
The update is getting called twice from the frontend.

**Comment by wingkwong** [comment]
more than twice if you keep editing
