### ISSUE TITLE
[i18n] Language support extension- ru

### ISSUE THREAD

**Issue by LostAlly** [nocodb/nocodb#1460]
# i18n translation request

1. Select applicalbe
- [ ] **New language support request**
- [V] **Existing language translation corrections request** 

2. Associated language code (pick from [here](https://developers.google.com/admin-sdk/directory/v1/languages)): 
ru

3. Google spreadsheet
https://docs.google.com/spreadsheets/d/1vwvJ-pWKXOCkvcKyGNofmHAQNAGvr8MI0ETBOWCPcLM/edit?usp=sharing
- [ ] **Attached**
- [V] **Shared link**:

4. Summary of the changes made
- So many modified items...

5. Any specific message to be conveyed to moderators?

**Comment by dstala** [comment]
master spreadsheet updated
[noco-i18n - i18n_ru.csv](https://github.com/nocodb/nocodb/files/8318305/noco-i18n.-.i18n_ru.csv)

**Comment by dstala** [comment]
@LostAlly Thank you for the translations! we@nocodb appreciate!
