### ISSUE TITLE
Removed owner can add themselves

### ISSUE THREAD

**Issue by TsjipTsjip** [nocodb/nocodb#1466]
Node: **v12.22.10**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.84.15**

**Steps To Reproduce**
(Reproducible from a fully clean install.)
1. Open two private windows in your browser.
2. [In private tab 1] Log in as a user with the 'owner' role for a project. (Create one if necessary, no external database is needed.)
3. [In private tab 1] Open the ACL interface for this project (Team & Auth in the bottom left) and invite a new (or exisiting) user as project owner.
4. [In private tab 2] Log in as this other user and navigate to the ACL interface for the project.
5. [In private tab 1] Remove access for the second user to this project.
6. [In private tab 2] Click the "Reload" button on the ACL interface. Observe that the 'owner' label has been removed.
7. [In private tab 2] Re-add yourself.

**Expected behavior**
The second user should not be able to do anything to the project anymore, as their access has been revoked by the first user. This includes managing ACL.

Even further, it might be desired behavior that a user cannot manage themselves at all (much like the error you get when you try to delete yourself from a project).

**Actual behavior**
The second user can still access the project as if they were still a project owner for as long as they remain on the ACL page. Specifically, this allows them to re-add themselves as an owner. This is only limited by actually changing/reloading tabs. "Reload" buttons in the interface still work, along with any other functionality provided through the API (Might need verification on this.)

**Edit:** Note that I have only tested this on a clean docker install from production. This might already have been resolved, I was however unable to find it if this is the case.

**Comment by wingkwong** [comment]
Seems it has been resolved at some point. Please feel free to reopen if you can reproduce the issue.

![image](https://user-images.githubusercontent.com/35857179/176994081-ea5f62ba-738a-4fe8-8ece-ad9e5147281d.png)
