### ISSUE TITLE
[i18n] Language support extension-nl

### ISSUE THREAD

**Issue by TsjipTsjip** [nocodb/nocodb#1467]
# i18n translation request

- [ ] **New language support request**
- [x] **Existing language translation corrections request** 

2. Associated language code:  nl

3. Google spreadsheet shared link: https://docs.google.com/spreadsheets/d/1UeGxzEH228FXJexNpOmY79ooUBM3DheOqtasHHzBuDQ/edit?usp=sharing

4. Summary of the changes made
- I ran over both nl columns on both tabs of the master sheet, with many updates. Only a few cells have been left unchanged.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/commit/2a7f0d1e03bb847299d801d2c99fadf29fb9ef44
