### ISSUE TITLE
Failed to Update Row - 400

### ISSUE THREAD

**Issue by HelloImCamden** [nocodb/nocodb#1469]
**Steps To Reproduce**
1. Add Row
2. Edit any information in row
3. Save Row
Error 400

**Expected behavior**
Row would be saved. 

**Screenshots**
https://cdn.discordapp.com/attachments/728443930621902869/955903010503028766/unknown.png

Docker logs: https://www.toptal.com/developers/hastebin/conevihimi.sql

Node: v12.22.10
Arch: x64
Platform: linux
Docker: true
Database: mysql2 ( 10.3.31-MariaDB-0+deb10u1 )
ProjectOnRootDB: false
RootDB: sqlite3
PackageVersion: 0.84.15

**Comment by wingkwong** [comment]
Finding :

- The column name includes a character `?` which causes this error.

**Comment by Cirsten** [comment]
I have same problem, when changing column type

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.91.7**
