### ISSUE TITLE
Azure managed database causes GraphQL errors.

### ISSUE THREAD

**Issue by titouancreach** [nocodb/nocodb#1514]
NocoDB used as docker : true
NocoDB version : 0.84.15
Database used in NC_DB URL  : mssql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mssql
OS on which NocoDB is running : Linux
Node.js version if running as node : NA
Database version : 

**Steps To Reproduce**
- Create a managed database in Azure
- Azure generate a view `DatabaseFirewallRules` and `Ipv6DatabaseFirewallRules` (https://docs.microsoft.com/fr-fr/sql/relational-databases/system-catalog-views/sys-database-firewall-rules-azure-sql-database?view=azuresqldb-current)
- I cannot see the rows of all my tables
- GraphQL doesn't work

**Expected behavior**
- View all the rows of my tables
- The GraphQL client should work

**My guess**
When I see the error on the server I see:
```
[INFO]  GraphQLError [Object]: Syntax Error: Expected Name, found "}".
```
 
So, when I look at the schema generated for those 2 tables:

`select [Schema] from [nc_models] where [project_id] = 'mydbname' and [Alias] = 'Ipv6DatabaseFirewallRules'`

I've something like:

```     input Ipv6DatabaseFirewallRulesInput {  	}      type Query {  		Ipv6DatabaseFirewallRulesList(where: String,condition:ConditionIpv6DatabaseFirewallRules, limit: Int, offset: Int, sort: String,conditionGraph: String): [Ipv6DatabaseFirewallRules] 		Ipv6DatabaseFirewallRulesRead(id:String!): Ipv6DatabaseFirewallRules 		Ipv6DatabaseFirewallRulesExists(id: String!): Boolean 		Ipv6DatabaseFirewallRulesFindOne(where: String,condition:ConditionIpv6DatabaseFirewallRules): Ipv6DatabaseFirewallRules 		Ipv6DatabaseFirewallRulesCount(where: String,condition:ConditionIpv6DatabaseFirewallRules,conditionGraph: String): Int 		Ipv6DatabaseFirewallRulesDistinct(column_name: String, where: String,condition:ConditionIpv6DatabaseFirewallRules, limit: Int, offset: Int, sort: String): [Ipv6DatabaseFirewallRules] 		Ipv6DatabaseFirewallRulesGroupBy(fields: String, having: String, limit: Int, offset: Int, sort: String): [Ipv6DatabaseFirewallRulesGroupBy] 		Ipv6DatabaseFirewallRulesAggregate(column_name: String!, having: String, limit: Int, offset: Int, sort: String, func: String!): [Ipv6DatabaseFirewallRulesAggregate] 		Ipv6DatabaseFirewallRulesDistribution(min: Int, max: Int, step: Int, steps: String, column_name: String!): [distribution] 	} ,      type Mutation {  		Ipv6DatabaseFirewallRulesCreate(data:Ipv6DatabaseFirewallRulesInput): Ipv6DatabaseFirewallRules 		Ipv6DatabaseFirewallRulesUpdate(id:String,data:Ipv6DatabaseFirewallRulesInput):  Ipv6DatabaseFirewallRules 		Ipv6DatabaseFirewallRulesDelete(id:String): Int 		Ipv6DatabaseFirewallRulesCreateBulk(data: [Ipv6DatabaseFirewallRulesInput]): [Int] 		Ipv6DatabaseFirewallRulesUpdateBulk(data: [Ipv6DatabaseFirewallRulesInput]): [Int] 		Ipv6DatabaseFirewallRulesDeleteBulk(data: [Ipv6DatabaseFirewallRulesInput]): [Int] 	},       type Ipv6DatabaseFirewallRules {  	} type Ipv6DatabaseFirewallRulesGroupBy {  		count: Int, 	} type Ipv6DatabaseFirewallRulesAggregate {  		count: Int, 		avg: Float, 		min: Float, 		max: Int, 		sum: Float 	}   input ConditionIpv6DatabaseFirewallRules {       _or:[ConditionIpv6DatabaseFirewallRules]     _not:ConditionIpv6DatabaseFirewallRules     _and:[ConditionIpv6DatabaseFirewallRules]          	}       ```

And when I put this schema in a schema validator I have:

```json
{
  "errors": [
    {
      "message": "Syntax Error: Expected Name, found \"}\".",
      "extensions": {
        "code": "GRAPHQL_PARSE_FAILED"
      }
    }
  ]
}
```

It seems coherent but I'm not sure

Thanks

**Comment by o1lab** [comment]
Can you try the same with REST project and see how that goes ? It can be a character in table/columnname which is not going well with GraphQL schema

**Comment by wingkwong** [comment]
GQL has been deprecated.
