### ISSUE TITLE
[Feature] search / sort / filter on the primary value of linked records

### ISSUE THREAD

**Issue by jpbourgeon** [nocodb/nocodb#1522]
**Need for this feature**
A major added value of nocodb over spreadsheets is the ability to link table records. Being able to search / sort / filter on the primary value of linked records would push this advantage even further.

**Is your feature request related to a problem? Please describe.**
Currently it is simply not possible to do such searching /sorting / filtering in advanced usage scenarios.

**Describe the solution you'd like**
Being able to pick linked columns in the action bar for searching / sorting / filtering.

**Describe alternatives you've considered**
It is possible to export to CSV and do the searching / filtering / sorting in a spreadsheet but it obviously loses most of its interest.

**Comment by o1lab** [comment]
Available in 0.90
