### ISSUE TITLE
[Feature] CSV export through REST API

### ISSUE THREAD

**Issue by fishnux** [nocodb/nocodb#1524]
## Recommending Features

**Need for this feature**
Similar to get all route in REST API, but instead of JSON returns CSV

For my use-case, JSON is significantly heavy due to repetition of the field names. CSV results in a much smaller file

**Comment by fishnux** [comment]
It seems this feature already exists, but it's not working

**Comment by wingkwong** [comment]
Covered in https://github.com/nocodb/nocodb/pull/2441
