### ISSUE TITLE
[i18n] Language support extension- <tr>

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#1533]
# i18n translation request

1. Select applicable
- [x] **New language support request**

2. Language code: tr (Turkish)

3. Google spreadsheet
- [x] **Shared link**: https://docs.google.com/spreadsheets/d/1c2rtfTW_gFYKg5EYKZ_fSxkDZPX3yWlTdYDE5KClgxM/edit?usp=sharing

4. Summary of the changes made
- Added the Turkish language

**Comment by dstala** [comment]
Issue: https://github.com/nocodb/nocodb/issues/1533
 Master spreadsheet updated
 CSV: [noco-i18n - i18n_tr.csv](https://github.com/nocodb/nocodb/files/8356808/noco-i18n.-.i18n_tr.csv)
 Contributed by: @mertmit

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/commit/1a15d42ffd0ff312943bcd7955fccfbdb459bd44

**Comment by dstala** [comment]
@mertmit Thank you for the changes! We appreciate that ~
