### ISSUE TITLE
CSV import fail with NULL value

### ISSUE THREAD

**Issue by Chernfalin** [nocodb/nocodb#1537]
Nocodb columns set to Text type have no problem, 
But when set columns as Number/Decimal/Date/[anything else than default values is not string '']  and the imported CSV contains null values, Fail to import with error code: 400

nocodb created by official docker-compose with pg database.

**Comment by wingkwong** [comment]
is the target column set as not null? besides, do you have a dummy csv for reproducing this issue?

**Comment by Chernfalin** [comment]
> is the target column set as not null? besides, do you have a dummy csv for reproducing this issue?

nocodb table:
![image](https://user-images.githubusercontent.com/33632784/160354391-53378ee5-f7e2-4830-8cb9-04d21d71aaab.png)
col1(SingleLineText),col2(Number).
import csv:
![image](https://user-images.githubusercontent.com/33632784/160354601-ce4eb378-7557-46de-9041-766348ace69a.png)
Error 400.
