### ISSUE TITLE
[Feature] Helm chart

### ISSUE THREAD

**Issue by just1689** [nocodb/nocodb#1544]
**Need for this feature**
A helm chart makes it easy to install in Kubernetes clusters

**Is your feature request related to a problem? Please describe.**
Running in Kubernetes using Helm requires a Helm chart.

**Describe the solution you'd like**
I'd like to contribute the initial Helm chart. I'm sure the team and the community will help shape it into what it should be.

**Describe alternatives you've considered**
Someone else could do it if you would prefer. 

**Additional context**
NA

**Comment by just1689** [comment]
Let me know. Would be happy to contribute the chart

**Comment by o1lab** [comment]
Available [here](https://github.com/nocodb/nocodb/tree/develop/charts/nocodb)

**Comment by erikalfthan** [comment]
Is it packaged somewhere? I.e. is there a publicly available path? `helm repo add nocodb https://<path>`
(Or maybe I am just a helm newbie - is it possible to install the chart directly from git?)

**Comment by debugger24** [comment]
@erikalfthan you can download the repo run helm install.

**Comment by debugger24** [comment]
We should publish this helm chart so it is easy to install and extend.

**Comment by vjm** [comment]
has this been published anywhere?

**Comment by koalalorenzo** [comment]
Any update on this?

**Comment by Serubin** [comment]
Bumping this - this chart should be published. It cannot be easily integrated into GitOps systems.
