### ISSUE TITLE
Dashboard loading too long

### ISSUE THREAD

**Issue by workman-Lu** [nocodb/nocodb#1545]
NocoDB used as docker : true 
NocoDB version : least
OS on which NocoDB is running : centos7.9
Node.js version if running as node : 
Database version : nocoDB

The block was happen when i new a project Whitout db-connection and restart it .
then:
![image](https://user-images.githubusercontent.com/23043492/160732507-4e0b4214-c551-4476-98e8-9718e58a36c5.png)

This usually takes a few minutes

**Comment by workman-Lu** [comment]
project was lost in front page. What seems to be the impact of connection.

**Comment by workman-Lu** [comment]
![image](https://user-images.githubusercontent.com/23043492/160733509-c5814bfa-46b2-4b76-a4cc-e83554455a90.png)

**Comment by wingkwong** [comment]
1. Can you show your docker command? Sensitive info can be redacted.
2. Did it happen after creating the project? or before?

**Comment by workman-Lu** [comment]
> 

before the creating, and i create a nil database :);
I reckon that may be able to tolerate any bad connection; and show the state.

**Comment by wingkwong** [comment]
Could you please double check the connection to your database? Also you may check if the port is being used by other orphan processes.

**Comment by o1lab** [comment]
Please confirm if you had access to write into local file system ? if not it looks like it is struggling to connect to SQLite database (which is our meta database)

You can always point metadatase to an MySQL, PG etc using NC_DB variable. [See here for more details](https://docs.nocodb.com/getting-started/installation#production-setup).
