### ISSUE TITLE
App configuration

### ISSUE THREAD

**Issue by HSUCHING** [nocodb/nocodb#1563]
Hi,

     I cannot connect with Discord in app store in NocoDB. I want know what is the Channel name and Webhook URL in config discord and how i find them?

Best regards,
Hsuching

**Comment by wingkwong** [comment]
Check this out - https://docs.nocodb.com/developer-resources/webhooks#discord

**Comment by wingkwong** [comment]
Closing as there is no further response. Please feel free to reach us at Discord / Community if you have more questions to ask.
