### ISSUE TITLE
Repository Description should include SQLite

### ISSUE THREAD

**Issue by captn3m0** [nocodb/nocodb#1588]
The README says; 

'Turns any MySQL, PostgreSQL, SQL Server, SQLite & MariaDB into a smart-spreadsheet.'

While the repository description just says Postgres/MySQL. 

The description is used by GitHub in a lot of places(trending/explore pages for eg), so probably worth including the other databases.

**Comment by o1lab** [comment]
Added SQLite. The idea is to keep it short in the github description :)
