### ISSUE TITLE
Query Connection Timeout using Unix Socket and Cloud Run

### ISSUE THREAD

**Issue by stantonius** [nocodb/nocodb#1590]
NocoDB used as docker: *true*
NocoDB version: *0.84.15*
Database used in NC_DB URL: *mysql*
Project was created  by clicking : *New Project by connecting to external database*
Database on which spreadsheet is created : *mysql*
OS on which NocoDB is running: *linux* (using the official NocoDB image) 
Node.js version if running as node: *v12.22.10* (from official image)
Database version : *both 8.0 and 5.7 - same issue for both versions*

**Steps To Reproduce**
1. Create Dockerfile and a knex.json file as described in my workaround for issue #752 
2. Deploy to GCP Cloud Run (works with setup described above)
3. Connect to your MySQL instance using the 'New Project by connecting to external database'. Connection is successful and table metadata is loaded.
4. No table rows appear. When refreshing the page to re-establish the request, the 'Loading' icon spins for 5-10 seconds

Error log from the Cloud Run instance is here:

```
{
  "textPayload": "Error: connect ETIMEDOUT\n    at Connection._handleTimeoutError (/usr/src/app/node_modules/mysql2/lib/connection.js:189:17)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers (internal/timers.js:497:7) {",
...
}
```

**Expected behavior**
Let me preface this by saying that I understand Cloud Run and other similar serverless container technologies may not necessarily be designed for this. However they are just so much more cost effective and convenient than VMs. So it was worth a try - the fact that GCP has a specific mechanism to connect Cloud Run to MySQL suggests that this should be doable.

The two tables I am trying to load are not massive at all - a couple hundred rows of a few float columns. I was able to make the connection initially when starting a new project, so I expected the table loading to also work.

Note that when I sign out and sign back in, the table metadata loads as does the new NocoDB test grid I had created - so NocoDB is able to retrieve its state from the MySQL instance. It just will not load the table data.

Thanks for any guidance you may have

Node: **v12.22.10**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.84.15**

**Comment by dstala** [comment]
@stantonius if you still face this issue with release v0.202.5, please reopen this thread. Or you can connect with me over discord for more help (@dstala)
