### ISSUE TITLE
Failed to exec filter request with a non-english column

### ISSUE THREAD

**Issue by David-Gan** [nocodb/nocodb#1593]
Hi,

NocoDB is a great project. But it looks like not perfect with Chinese content. It will failed when filter with a non-english column.

If it is a bug and no one handle it, I will try fixing it myself.

Best regards,

**Screenshots**
<img width="1260" alt="nocodb-bug" src="https://user-images.githubusercontent.com/8855424/161551460-53bd3b7f-e51e-4e9b-803a-bf8e6e291356.png">

Node: **v12.22.10**
Arch: **arm64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.84.15**

**Comment by wingkwong** [comment]
We've revised filter in the upcoming `v0.90.0`. Please stay tuned.

**Comment by David-Gan** [comment]
> We've revised filter in the upcoming `v0.90.0`. Please stay tuned.

That's great! Thank you!

**Comment by o1lab** [comment]
Please try it in latest version (0.90) and let us know.

**Comment by o1lab** [comment]
Verified & works
