### ISSUE TITLE
Blank inscription form when NC_DASHBOARD_URL="/" (serving by Apache)

### ISSUE THREAD

**Issue by Suniron** [nocodb/nocodb#1594]
Hello,

I'm trying to use Nocodb on my stack but i can't do an inscrpition from UI.

In fact, after init, i got this blank form:
![image](https://user-images.githubusercontent.com/36677774/161556242-0f1864e9-a6d9-4f4f-8558-5cd4911513cb.png)

I serve Nocodb with pm2 and pm2 by Apache2 (with mod proxy).

I use 2 variables for this context: `DATABASE_URL` which point on a PostgreSQL url and `NC_DASHBOARD_URL: "/"`

**Server**: Ubuntu 20.04
**Nodejs**: v16.14.0
**Apache**: 2.4.29

**Comment by o1lab** [comment]
Try setting dashboard url to something else

**Comment by o1lab** [comment]
Feel free to reopen if issue exists in latest.
