### ISSUE TITLE
🐛 Bug: Can't update metadata of deleted tables with foreign keys

### ISSUE THREAD

**Issue by RobinFrcd** [nocodb/nocodb#1601]
Hi,

Node: **v12.22.10**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.84.15**

I've created a few tables directly in my PSQL DB. They have some foreign key relationships. I then dropped one of these table and tried to re-sync the metadata, but I get a 400 error `msg: Cannot read property 'indexOf' of undefined`.

![Screenshot 2022-04-05 at 17 04 08](https://user-images.githubusercontent.com/29704178/161784794-7f664966-fcc0-4098-ad6e-15f2a3cb4556.png)

**Comment by jakobzach** [comment]
This caused some huge issues for us, definitely need a fix for this!

**Comment by amisdun** [comment]
I want work on this bug

**Comment by amisdun** [comment]
How do I reproduce this error

**Comment by dstala** [comment]
@RobinFrcd if you still see this issue with release v0.202.5, please reopen this thread. Or get in touch with me over discord (@dstala)
