### ISSUE TITLE
Changing the Persian strings' font in NocoDB interface

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#1610]
## Recommending Features

We have just upgraded NocoDB to v0.8.16 and the Persian interface has been included to the interface - thanks to the developers and @dstala - but the font is actually weird that it cannot be read properly.
We have chosen a nice font which you can find in another repository in Github that I will share its address.

**Need for this feature**
The current Persian font (which is included in v0.8.16) is unreadable in some cases. Adding another font will solve this issue.

**Is your feature request related to a problem? Please describe.**
The current Persian font is sort of unreadable and not really interesting. So we have come up with a nice alternartive.

**Describe the solution you'd like**
We want NocoDB developers to include Vazir font for Persian interface. The font we have chosen is supported by Google; as they have included it to their valid fonts.
https://github.com/rastikerdar/vazirmatn.git

**Describe alternatives you've considered**
-

**Additional context**
I have also put the corresponding address of the font I mentioned. It's a Github repository.
rastikerdar / vazirmatn (https://github.com/rastikerdar/vazirmatn.git)

**Comment by o1lab** [comment]
Would be helpful if you send a PR as we do not know much about RTL.

**Comment by okaeiz** [comment]
Vazirmatn is a public repo; everybody can pull the code and play with it.
What do you mean by a pull request?
