### ISSUE TITLE
Error: Fields - Hide all

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1615]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

![Screenshot 2022-04-07 at 6 10 40 PM](https://user-images.githubusercontent.com/86527202/162200951-efa86040-401f-42eb-b22f-44ed0e0593f8.png)

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
