### ISSUE TITLE
Bug: A user without internet access faces missing fonts and stylesheets

### ISSUE THREAD

**Issue by hoh** [nocodb/nocodb#162]
When a user wants to use NocoDB without internet access or behind a firewall, he faces issues due to:

- Fonts are hosted on `fonts.gstatic.com`
- Stylesheets are hosted on `fonts.googleapis.com` and `cdn.jsdelivr.net`
- A script is hosted on `cdn.jsdelivr.net`

**Comment by o1lab** [comment]
resolved in subsequent releases since the issue raised.
