### ISSUE TITLE
Incorrect migration of UI ACL

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1622]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.84.16**

- use the attached SQL file (dumped after migration from v1 to v2)
- ACL entries are recorded in both the v1 and v2 backend table, but somehow not reflected in UI for v2
- issue was observed with cache disabled as well

[Dump20220408_acl.sql.zip](https://github.com/nocodb/nocodb/files/8454100/Dump20220408_acl.sql.zip)

![Screenshot 2022-04-08 at 10 52 33 PM](https://user-images.githubusercontent.com/86527202/162493281-655c3892-c088-4029-96c6-b86f1d24dad5.png)
![Screenshot 2022-04-08 at 10 53 26 PM](https://user-images.githubusercontent.com/86527202/162493289-3d092317-f736-41b7-9709-2cd5468098f0.png)

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
