### ISSUE TITLE
Redshift Support

### ISSUE THREAD

**Issue by tegansnyder** [nocodb/nocodb#163]
Has the Postgres connection been tested against a Redshift DB?

**Comment by tegansnyder** [comment]
I think I just answered my own question. It can connect but can't create tables because of the differences in Redshift and Postgres.

**Comment by o1lab** [comment]
Nope, we 'vent tried with redshift.

We use knex and pg npm packages to acecss postgres.

If they are compatible - we will work with them.

But looks like there are issues with it : https://github.com/knex/knex/issues/1255
