### ISSUE TITLE
Multiselect on pg is leading to an error

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1630]
Looks like latest change made to ignoreWebhook is causing it.

@mertmit : I will share more details over chat

<img width="1206" alt="Screenshot 2022-04-08 at 23 27 35" src="https://user-images.githubusercontent.com/5435402/162542169-32c3b3c4-c577-47d3-a25a-6a3c25bc1582.png">
.

**Comment by mertmit** [comment]
I disabled update call if there is no column given which is causing that issue. This change will prevent this error but I will further investigate frontend what is causing 'onCellValueChange' to fire with undefined column.

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
