### ISSUE TITLE
Cell won't update properly in version 0.84.16

### ISSUE THREAD

**Issue by cj-wong** [nocodb/nocodb#1637]
**Please enter the following details**
NocoDB used as docker : true
NocoDB version : 0.84.16
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : Ubuntu 20.04 LTS
Database version : mysql:5.7 (per docker-compose.yml)

**Steps To Reproduce**
1. Write value in existing cell in existing project.
2. Click refresh, refresh the tab, or click another tab and then back.
3. The cell reverts to previous value. There is also no related log in `docker-compose logs` or the built-in audit log. 

**Expected behavior**
The cell should update to the new value. The audit log should reflect on this change, as well. This expected behavior occurs in 0.84.15 and prior versions, so I have downgraded back for the time being. I have not had this issue since using NocoDB, which by now has been months.

**Comment by henk23** [comment]
Can confirm the behavior also with sqlite in docker. New cell value and also values of new rows are not saved, even on blur. I can create a new table, add 5 new rows, fill in values, nothing is saved. After hitting the refreh button on the top right, the table is empty again.

**Comment by mertmit** [comment]
@henk23 this looks like another issue. Can you provide your [project info](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-).
Also it would be awesome if you can give reproduction steps from creation of new table.

**Comment by cj-wong** [comment]
I see that more info is needed. Additional details:

I run NocoDB on an amd64 device. I access NocoDB primarily through a reverse proxy on a separate machine serving nginx, on its own subdomain. If required, I can provide snippets of my nginx configuration for NocoDB.

**Comment by wingkwong** [comment]
I couldn't reproduce this issue. If you finish editing, the change will be saved within 1 second (you should see `Loading ...` next to NocoDB logo on the top left corner). Would it be possible you refresh the page right after you edit the cell & before auto-saving?

**Comment by cj-wong** [comment]
No, I don't close the page immediately. I've even edited the cell and expected it to stick, waiting for a couple minutes at a time. It's unfortunate that the issue could not be reproduced. I'll stay on the 0.84.15 for now and maybe the next update will be better.

**Comment by cj-wong** [comment]
Related to aforementioned issue and may be fixed in PR #1817
