### ISSUE TITLE
Server does not start, error installing mysql

### ISSUE THREAD

**Issue by ojotoxy** [nocodb/nocodb#164]
This is what happens when I try to run the docker image from the readme with a mysql server:

```
Knex: run
$ npm install mysql --save
Cannot find module 'mysql'
Require stack:
```

Also, I would think it to be better design to avoid the docker image requiring any run-time installation of packages.

**Comment by jsaltzman** [comment]
I am having a similar issue. See below from my Docker log:

Knex: run

$ npm install mysql --save

nnot find module 'mysql'

Require stack:

- /usr/src/app/node_modules/knex/lib/dialects/mysql/index.js

- /usr/src/app/node_modules/knex/lib/config-resolver.js

- /usr/src/app/node_modules/knex/lib/knex.js

- /usr/src/app/node_modules/knex/lib/index.js

- /usr/src/app/node_modules/knex/knex.js

- /usr/src/app/node_modules/nc-help/dist/main/main.js

- /usr/src/app/docker/main.js

Error: Cannot find module 'mysql'

**Comment by o1lab** [comment]
Oops, I will fix the docs : please use mysql2 instead

NC_DB=mysql2://localhost:3306?u=root&p=password&d=yourdb

My bad

**Comment by jsaltzman** [comment]
I resolved this by not having a NC_DB variable and then manually entering database details.
