### ISSUE TITLE
table create- project tree records not updated

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1648]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- connect to sakila mysql db
- create table
- no errors observed in backend logs
- vue errors captured below

### after table create
![Screenshot 2022-04-12 at 12 58 39 PM](https://user-images.githubusercontent.com/86527202/162905341-f4e1a904-5d6b-435f-8c2a-add029411307.png)

### vue error
![Screenshot 2022-04-12 at 1 00 24 PM](https://user-images.githubusercontent.com/86527202/162905458-d5fce45a-03e7-4476-87e9-c65384756958.png)

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
