### ISSUE TITLE
shared form view- error while fetching linked records

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1649]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- country table, create form view, share
- click on `link record`in city list field

![Screenshot 2022-04-12 at 1 12 38 PM](https://user-images.githubusercontent.com/86527202/162907814-1d8b1efd-024c-4fad-bee2-cdd6fba72577.png)

**Comment by wingkwong** [comment]
It seems that this issue has been fixed.

![image](https://user-images.githubusercontent.com/35857179/162942063-ffe6cb1a-923a-45f0-8cd8-cfbc649308a8.png)
