### ISSUE TITLE
Additional column displayed in actor table/ category table

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1650]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

Additional columns are listed (FilmActorList, FilmCategoryList -- associated with mm relation)

### Nc V2
![Screenshot 2022-04-12 at 1 19 43 PM](https://user-images.githubusercontent.com/86527202/162909475-c7286121-75c7-49ee-888e-3b0cd5198684.png)
![Screenshot 2022-04-12 at 1 21 31 PM](https://user-images.githubusercontent.com/86527202/162909491-a6e3dba6-6eb5-48e2-b0f8-7989dac5868a.png)

### Nc V1
![Screenshot 2022-04-12 at 1 20 51 PM](https://user-images.githubusercontent.com/86527202/162909488-623fce79-8793-4858-ae8c-fed5b19877a8.png)

**Comment by dstala** [comment]
Fixed in https://github.com/nocodb/nocodb/commit/1c4d470782acd9e635d4106d38bca04da6047c65

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
