### ISSUE TITLE
rename view- active screen toggles to default view

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1653]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- open country table, create multiple views
- rename one of the views. 
- post rename, display automatically toggles to default view

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
