### ISSUE TITLE
Additional field option displayed in shared grid view

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1654]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- connect to mysql sakila db
- open country table
- enable only 'CountryID' field
- share view
- open shared view URL; field option displays 'country' instead; when enabled, shows empty skeletons

> issue not observed with v1

### Before share
![Screenshot 2022-04-12 at 1 36 56 PM](https://user-images.githubusercontent.com/86527202/162912467-50a8c48b-5d8f-45de-930d-440fa76497f3.png)

### After share
![Screenshot 2022-04-12 at 1 37 20 PM](https://user-images.githubusercontent.com/86527202/162912450-b4bf7cd8-e54c-472f-adaf-8af9ec919aa7.png)

**Comment by pranavxc** [comment]
Fixed in https://github.com/nocodb/nocodb/commit/1c4d470782acd9e635d4106d38bca04da6047c65

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
