### ISSUE TITLE
shared view- download failure

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1655]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- connect to sakila db
- country table, share view
- open shared URL
- download CSV

![Screenshot 2022-04-12 at 1 40 19 PM](https://user-images.githubusercontent.com/86527202/162913035-2b92ecc2-3dfa-4801-a38f-33b38c4906a6.png)

**Comment by wingkwong** [comment]
Found it has been fixed in https://github.com/nocodb/nocodb/commit/f87db007d4a582867876983917dbbb26efaacf2d.

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
