### ISSUE TITLE
delete record- failure

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1656]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- connect to sakila db
- open country table
- add a record
- delete record

> Failed to delete row : Cannot read properties of undefined (reading 'delete')

![Screenshot 2022-04-12 at 1 47 39 PM](https://user-images.githubusercontent.com/86527202/162915086-883c79be-42d6-407e-b97a-0987c4421351.png)

![Screenshot 2022-04-12 at 1 48 52 PM (2)](https://user-images.githubusercontent.com/86527202/162914946-21ed352c-fc6e-455e-9d4b-c057881b7b5e.png)

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
