### ISSUE TITLE
Question: How to view API endpoints?

### ISSUE THREAD

**Issue by OkkarMin** [nocodb/nocodb#166]
[In this demo video regarding REST API access](https://www.youtube.com/watch?v=He4CrHPEMpI) the demo goes to 'Project Info' and click on the link to see API endpoints.

Current version does not have the `Project Info` button and only `Swagger APIs Doc` button and on clicking the button it shows

![Screenshot 2021-05-28 at 09 39 47](https://user-images.githubusercontent.com/24297303/119917193-a5a63700-bf98-11eb-96ae-27e79ae6e84d.png)

How could I then see the API end points?

**Comment by supermamon** [comment]
+1 
i'm getting the same issue

**Comment by supermamon** [comment]
I found a work-around for now by manually changing `v1/graphql` to `db/swagger` on the url

**Comment by almosnow** [comment]
Same exact issue 😬

Aside from that, what an amazing product, this is HUGE for me.

**Comment by OkkarMin** [comment]
> I found a work-around for now by manually changing `v1/graphql` to `db/swagger` on the url

Same here 👍

**Comment by OkkarMin** [comment]
Also, it seems to be that the base URL is always `localhost:8080`

**Comment by pranavxc** [comment]
Fixed in nocodb@0.9.15
