### ISSUE TITLE
shared grid view- column operations (hide/sort/filter) have no impact on download CSV

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1660]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- open country table
- create shared view
- access shared view URL
- enable column operations (hide/ sort/ filter)
- download CSV

(on main window)
![Screenshot 2022-04-12 at 3 10 29 PM](https://user-images.githubusercontent.com/86527202/162933493-9fb4ad56-437b-4802-9af0-0483658aadff.png)

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
