### ISSUE TITLE
external db- toast doesn't disappear on attempt to create project with existing name

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1669]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- create new mysql project (project name = 'x')
- try to create another MySQL project with same name
- toast throws error that project name exists & also shows project creating toasts
- 'please wait' toast doesn't disappear

![Screenshot 2022-04-13 at 12 35 12 PM](https://user-images.githubusercontent.com/86527202/163119853-80085111-d962-4d06-9be5-1bbaa0e68f6f.png)

**Comment by wingkwong** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/1672.

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
