### ISSUE TITLE
[minor] LTAR - UI improvement

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1673]
Issue: LTAR datatype shows self-link also as an option
Change request: Don't show self-link option for "link to another record"

![Screenshot 2022-04-13 at 3 10 11 PM](https://user-images.githubusercontent.com/86527202/163148362-22029815-e7a4-4bd0-87c3-c8f0b584820f.png)

**Comment by o1lab** [comment]
Self link is required.
