### ISSUE TITLE
Enable scroll for sort & filter

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1675]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

**Steps To Reproduce**
1. open any table
2. keep adding sort menu options/ filter

**Expected behavior**
Scroll option to appear after page width exceeds

**Screenshots**
<img width="659" alt="Screenshot 2022-04-13 at 15 32 26" src="https://user-images.githubusercontent.com/5435402/163204114-e0eab82c-28ec-4230-a80a-c1b5e7c3e617.png">

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
