### ISSUE TITLE
Commenter / Viewer see controls they cannot use

### ISSUE THREAD

**Issue by isgroup** [nocodb/nocodb#168]
Both in preview mode and in a normal user session CRUD controls (and not only the view-only/commenting ones) are shown to the user. Then an error is shown but it would be more intuitive to hide such controls.

This happens in multiple places:

- "My Projects" page
- "Table" view toolbar (Add new row, Save, Delete table)
- "Table" view (contextual controls, like add a file to be uploaded etc)
- Edit row modal box (Toggle comments, Save Row)

I'm not able to suggest an elegant and practical solution as I'm no familiar with the codebase. Normally there is some centralized component that exposes the permission system to the UI.

BTW: Very cool project!

**Comment by pranavxc** [comment]
Fixed in `0.11.29`
