### ISSUE TITLE
[i18n] Language support extension- ja

### ISSUE THREAD

**Issue by darakee** [nocodb/nocodb#1680]
# i18n translation request

**Please enter the following details**

1. Select applicalbe
- [x] **Existing language translation corrections request** 

2. Language code:  ja (Japanese)

3. Google spreadsheet

- [x] **Shared link**: https://docs.google.com/spreadsheets/d/11ZyGb_uFFKm_PO6dvV92v1j5OqtiSc6tI5QtD3xiYBY/edit?usp=sharing

4. Summary of the changes made
- Corrected the unnatural Japanese to make it as natural as possible.
- Changed the background color of the modified row to yellow.

5. Any specific message to be conveyed to moderators?
Please containe variables in the part to be translated.
Differences in English and Japanese grammar made it difficult to translate some parts accurately. If you can use template strings and have the variable part included in the part to be translated, the translation will be more accurate.

For example, if a term in google spreadsheet like `E-mail me at {Email Address}` , it can translate to Japanese as natural. But only `E-mail me at` in the list now. 

Thank you,

**Comment by dstala** [comment]
- [x] Update [master spreadsheet](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172)
- [x] Contributor [shared spreadsheet](https://docs.google.com/spreadsheets/d/11ZyGb_uFFKm_PO6dvV92v1j5OqtiSc6tI5QtD3xiYBY/edit#gid=2076107172)
- [x] Attach downloaded CSV [noco-i18n - i18n.csv](https://github.com/nocodb/nocodb/files/8522098/noco-i18n.-.i18n.csv)
- [x] Contributor: @darakee
- [x] Github issue https://github.com/nocodb/nocodb/issues/1680

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/1796
