### ISSUE TITLE
[Feature] The Editor need the function of ”Upload CSV“

### ISSUE THREAD

**Issue by cuizhao** [nocodb/nocodb#1683]
In the actual scenario, it is usually the editor who needs to import the CSV file. But now noly the "creator " can "Upload CSV". Please adjust the function permissions，so that the editor can use  ”Upload CSV“  import data。Thank you for your attention to this Issue。

**Comment by cuizhao** [comment]
In PackageVersion: **0.84.16** the creater can ”Upload CSV“ ,But when I updated to PackageVersion: **0.90.5** Only owner can use ”Upload CSV“. This is an very important bug on  PackageVersion: **0.90.5** .I wish nocodb team can fix this bug or grant editer the authority of ”Upload CSV“.Thanks a lot!

**Comment by wingkwong** [comment]
> But when I updated to PackageVersion: 0.90.5 Only owner can use ”Upload CSV“.

This statement is not true. Creator can also do that.

![image](https://user-images.githubusercontent.com/35857179/164390020-25120305-cc57-4d96-a595-8ae1346ed163.png)

<img width="791" alt="image" src="https://user-images.githubusercontent.com/35857179/164389973-f76b7eaa-392b-4e9d-8e54-4672f2ae7e14.png">

>  grant editor the authority of ”Upload CSV“

Will do. Thanks for reporting.

**Comment by cuizhao** [comment]
> > But when I updated to PackageVersion: 0.90.5 Only owner can use ”Upload CSV“.
> 
> This statement is not true. Creator can also do that.
> 
> ![image](https://user-images.githubusercontent.com/35857179/164390020-25120305-cc57-4d96-a595-8ae1346ed163.png)
> 
> <img alt="image" width="791" src="https://user-images.githubusercontent.com/35857179/164389973-f76b7eaa-392b-4e9d-8e54-4672f2ae7e14.png">
> 
> > grant editor the authority of ”Upload CSV“
> 
> Will do. Thanks for reporting.

Thanks for your answer，I restart my docker and browser then I found your answer is correct,creator can also do that.
