### ISSUE TITLE
Form view- error on configuring title

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1688]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- create form view
- configure form title

![Screenshot 2022-04-16 at 8 52 08 AM](https://user-images.githubusercontent.com/86527202/163659666-c9126ba3-1804-404c-94ae-cec2b55e3ca2.png)

issue observed with both MySQL external DB & XCDB project

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
