### ISSUE TITLE
XCDB migration- displays incorrect meta-sync data

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1692]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- use attached NC v1 noco.db file
- migrate to NC v2
- open meta sync tab

[noco_apr16.db.zip](https://github.com/nocodb/nocodb/files/8499505/noco_apr16.db.zip)

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
