### ISSUE TITLE
hmList- error on removing linked record

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1695]
Node: v14.18.0
Arch: arm64
Platform: darwin
Docker: false
Database: sqlite3
ProjectOnRootDB: true
RootDB: sqlite3
PackageVersion: 0.84.16

- create country hm city list
- link few records
- remove linked record from country table

![Screenshot 2022-04-16 at 2 29 25 PM](https://user-images.githubusercontent.com/86527202/163669151-36e53d3a-a3e2-430b-90fb-92e6f6022c6a.png)

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
