### ISSUE TITLE
link to record using pop up "add row" modal - does not work

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1696]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- create country hm city relation
- add new city in city table (Karachi). don't link to country yet
![Screenshot 2022-04-16 at 2 47 48 PM](https://user-images.githubusercontent.com/86527202/163669560-0d8c4752-2a6f-4ff3-80ab-2d92f0f90a02.png)

- from country table, open add-row pop up modal - enter country name & link to new city added (Karachi)
![Screenshot 2022-04-16 at 2 47 25 PM](https://user-images.githubusercontent.com/86527202/163669565-2607bfa6-1800-4655-ab38-c9881d4f419d.png)

- save record. says successful, but in the table - record is not reflected
![Screenshot 2022-04-16 at 2 47 33 PM](https://user-images.githubusercontent.com/86527202/163669573-957f1961-20bd-49b0-a305-9c084d0e2bf2.png)

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
