### ISSUE TITLE
Feature: Realtime collaboration

### ISSUE THREAD

**Issue by isgroup** [nocodb/nocodb#172]
Does NocoDB table view page automatically refresh it's data? It would be useful for collaborative access (two or more users editing the same dataset at the same time) or for example monitors in public areas, the latter is correlated to #171.

**Comment by mull** [comment]
Seconding this request with another use case:

1. editing (validating) the schema in Postgres
2. manipulating the data in nocodb

Currently it seems impossible(?) to get nocodb to recognise new columns added from the outside.

**Comment by o1lab** [comment]
These two are seperate issues :

One is realtime collaboration.

Second is syncing metadata from changed database - this is not as easy as it sounds. This could be done using our metadata manager - see project metadata tab.

**Comment by mull** [comment]
@o1lab Oh my I misread the description! Sorry about that. Real-time collaboration is not what I was after, but rather the syncing of metadata. I think it may be broken between Postgres<>NocoDB then, I shall have another look. Thanks!

**Comment by Vadorequest** [comment]
Realtime collaboration is a must-have to hope compete with Airtable. Tools like Google Sheet and such all support this.

**Comment by openmind-gnerlich** [comment]
We need Realtime collaboration. Do you plan it?

**Comment by tanyo520** [comment]
We need Realtime collaboration. Do you plan it?+1

**Comment by o1lab** [comment]
Tracked in #148
