### ISSUE TITLE
[Feature] Please support  oracle database ,thank you very much!

### ISSUE THREAD

**Issue by renyunsanpi** [nocodb/nocodb#1730]
## Recommending Features

NocoDB thrives on community needs. Many of our existing features are derived from community requirements & we will continue to build that way. We invite ideas to make NocoDB better. Do note that, we being an open-source team are constrained by resources & will be able to pick only limited **high demand** ideas for release. So, if you wish to pick this feature request early - spread the word, discuss it in Discord/blog/Reddit, ask your peers & colleagues to vote up for this feature request!

**Need for this feature**
What purpose does your Idea serve? What use cases does it solve?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dstala** [comment]
To be tracked under

[Need Oracle Support](https://github.com/nocodb/nocodb/issues/446)
