### ISSUE TITLE
Error upgrading 0.84.16 -> 0.90.2 on heroku using command line

### ISSUE THREAD

**Issue by niccolosanarico** [nocodb/nocodb#1736]
NocoDB used as docker : true
NocoDB version : 0.90.2
Database used in NC_DB URL  :  pg 
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Heroku
Node.js version if running as node : N/A
Database version : N/A

**Steps To Reproduce**

Hello, upgrading on heroku from 0.84.16 to the latest version using the command line and docker results in a 

> Cannot GET / 

from the browser, and the following error in the log:

> `error: insert into "nc_columns_v2" ("ai", "au", "base_id", "cc", "cdf", "clen", "column_name", "cop", "created_at", "csn", "ct", "dt", "dtx", "dtxp", "dtxs", "fk_model_id", "id", "np", "ns", "order", "pk", "project_id", "pv", "rqd", "system", "title", "uidt", "un", "unique", "updated_at", "validate") values ($1, $2, $3, DEFAULT, $4, $5, $6, $7, CURRENT_TIMESTAMP, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, DEFAULT, $18, $19, DEFAULT, $20, $21, $22, $23, $24, DEFAULT, CURRENT_TIMESTAMP, $25) - value too long for type character varying(255)`

Rolling back to 0.84.16 returns everything to normal.

Thank you for your support.

**Comment by o1lab** [comment]
Thanks for the report

**Comment by o1lab** [comment]
@niccolosanarico : is the project id lengthy by any chance or is the column name. Trying to get some preliminary info on the issue.

**Comment by wingkwong** [comment]
@niccolosanarico in your previous version, did you have any columns with long default values?

**Comment by niccolosanarico** [comment]
> @niccolosanarico : is the project id lengthy by any chance or is the column name. Trying to get some preliminary info on the issue.

Thank you! 

I have two projects, and neither of them has lengthy ids (they are <60 chars). Column names are all quite normal, none looks too long.

**Comment by niccolosanarico** [comment]
> @niccolosanarico in your previous version, did you have any columns with long default values?

Thank you. No, no column in the DB has long default values as far as I can check.

**Comment by pranavxc** [comment]
> > @niccolosanarico : is the project id lengthy by any chance or is the column name. Trying to get some preliminary info on the issue.
> 
> Thank you!
> 
> I have two projects, and neither of them has lengthy ids (they are <60 chars). Column names are all quite normal, none looks too long.

Do you have a single-select or multi-select column in any of the tables with a lot of options or lengthier options?

**Comment by pranavxc** [comment]
Fixed in `0.90.3`
