### ISSUE TITLE
Failed to import CSV

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#1737]
**Steps To Reproduce**
1. Create a table
2. More Action -> Import CSV
3. Failed 

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.90.2**

**Comment by alexrtou** [comment]
Very good news.
Thanks for your reactivity ! I check that this evening.

**Comment by alexrtou** [comment]
grr... the problem "r is undefined" still here in 0.90.3...

**Comment by wingkwong** [comment]
@alexrtou Please show your Project Info in below format.

```
Node: **v12.22.12**
Arch: **arm64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.90.3**
```

![image](https://user-images.githubusercontent.com/35857179/164147416-b718e6db-ab16-4a53-9246-5a73e00fd66f.png)

![image](https://user-images.githubusercontent.com/35857179/164147306-e4fe2bbc-9c3c-4634-9d9e-4bf0e419ba34.png)

![image](https://user-images.githubusercontent.com/35857179/164147339-bf98e99f-4043-4ac6-bb04-14527c2dcdf2.png)

![image](https://user-images.githubusercontent.com/35857179/164147379-f258c04d-a60a-4c30-8d25-3d3512de8c40.png)

**Comment by alexrtou** [comment]
I checked again the problem does not exists any more !
![Capture d’écran de 2022-04-20 17-57-23](https://user-images.githubusercontent.com/11272280/164274034-ae83a8bd-f284-4085-a0b4-a9302dd9a497.png)

**Comment by cuizhao** [comment]
n PackageVersion: 0.84.16 the creater can ”Upload CSV“ ,But when I updated to PackageVersion: 0.90.5 Only owner can use ”Upload CSV“. This is an very important bug on PackageVersion: 0.90.5 .I wish nocodb team can fix this bug or grant editer the authority of ”Upload CSV“.And the ”Upload CSV“ is a very important function to editer!
Thanks a lot!

**Comment by wingkwong** [comment]
> In PackageVersion: 0.84.16 the creater can ”Upload CSV“ ,But when I updated to PackageVersion: 0.90.5 Only owner can use ”Upload CSV“. This is an very serious bug on PackageVersion: 0.90.5 .I wish nocodb team can fix this bug or grant editer the authority of ”Upload CSV“.And the ”Upload CSV“ is a very important function to editer! @wingkwong Thanks a lot!

Let's track in https://github.com/nocodb/nocodb/issues/1683 instead.
