### ISSUE TITLE
Bug: A column has been specified more than once 

### ISSUE THREAD

**Issue by brakmic** [nocodb/nocodb#174]
Hi,

I'm testing nocodb with nocodb-seed and most of my Swagger API calls return this error: *A column has been specified more than once in the order by list. Columns in the order by list must be unique*. 

In my case it's the ID column that's included twice in the order by list.
I'm using a remote **MSSQL Server** **v14.0.3391.2**

The same problem appears in the UI as most of the tables I select don't return any data. Only the few tables I'm able to query via Swagger also show their data in the UI.

**Comment by o1lab** [comment]
Please provide table structure if possible.

**Comment by brakmic** [comment]
Sorry, not possible.

**Comment by pranavxc** [comment]
Can you share the column names?

**Comment by o1lab** [comment]
Feel free to reopen with more details.
