### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#1742]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux (Qnap-NAS)**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.90.2**

**Steps To Reproduce**
1. Sign in to NocoDB'
2. Click on NocoDB-Logo on top left
3. Even v90.0.2 is installed the logo (and even the project info) will report v90.0.1 is used. I manually edited "PackageVersion" to 0.90.2 in the line above.

**Expected behavior**
The correct release should be shown

**Screenshots**

Join our discord : https://discord.gg/5RgZmkW for realtime help.
![NocoDB1](https://user-images.githubusercontent.com/20600342/163777216-9ae1da6e-a1e8-4fbd-aa09-fdeaecc13a29.jpg)

![NocoDB2](https://user-images.githubusercontent.com/20600342/163777235-7fddf20f-84d9-463f-8b86-5d405c840e0f.jpg)

![NocoDB3](https://user-images.githubusercontent.com/20600342/163778423-4f37e9fe-260b-4a4b-b1cc-a4f85fe2a420.jpg)

**Comment by wingkwong** [comment]
After upgrading, have you tried hard refresh of browser?

**Comment by WeT-Klb** [comment]
Yes I did. After used Microsoft Edge and after your question i tried in Google Chrome.
But the result is the same.
This is whate i get from Google Chrome (exactly the same info like in Microsoft Edge):
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.90.1**

**Comment by stepanof** [comment]
I have the same problem. I pulled 0.90.2 version form docker hub but proj info and logo show me 0.90.1

**Comment by WeT-Klb** [comment]
Exactly. First i pulled "latest" from docker hub. After i saw 90.0.1 i NocoDB i tried again but choosing v90.0.2 instead of "latest"  this time - but again i got 90.0.1 as reported release.

**Comment by wingkwong** [comment]
Okay. We found the root cause now. Will make a release as soon as possible.

**Comment by wingkwong** [comment]
@WeT-Klb @stepanof Please try in `90.0.3`.

**Comment by stepanof** [comment]
@wingkwong Bag fixed! 
Thank you for efficiency
