### ISSUE TITLE
[i18n] Language support extension- zh-CN

### ISSUE THREAD

**Issue by zprial** [nocodb/nocodb#1744]
# i18n translation request

**Please enter the following details**

1. Select applicalbe
- [ ] **New language support request**
- [x] **Existing language translation corrections request** 

2. Associated language code (pick from [here](https://developers.google.com/admin-sdk/directory/v1/languages)): 
zh-CN
3. Google spreadsheet

- [ ] **Attached**
- [x] **Shared link**: https://docs.google.com/spreadsheets/d/1s_gUW-fC0DCTl_64P2vQ6elbwl2tW5TsOhmDmWtaKcM/edit?usp=sharing

4. Summary of the changes made
I changed the color to **blue** to mark it;

5. Any specific message to be conveyed to moderators?
THK

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/1748
