### ISSUE TITLE
schema immediately out of sync on postgres when creating table, columns

### ISSUE THREAD

**Issue by tlonic** [nocodb/nocodb#1753]
please provide the following details :
NocoDB used as docker : true
NocoDB version : 0.90.3
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg

**Steps To Reproduce**
1. Create new table
2. Go to Metadata 
3. See that metadata associated with system fields is already out of sync: 
"Column type changed(id), Column type changed(created_at), Column type changed(updated_at)" 
4. Create new column
5. See that metadata associated with new column is out of sync,
"Column type changed(newcolumn)" 

**Expected behavior**
Column type should already be synced on creating a table and a column

**Screenshots**
![image](https://user-images.githubusercontent.com/2394967/163896074-470edda8-6b0f-4b27-ac99-2f2f7c27ce17.png)

**Comment by wingkwong** [comment]
Able to reproduce. It seems this issue only exists in Postgres.

**Comment by rajeshdhanda** [comment]
still facing the issue, updated data in postgres via psql command line, not able to sync in nocodb. also modifying table from UI doesn't update the swagger UI and CRUD endpoints. i.e. dropped a column and added a new column via psql did not reflect the changes in UI and creates Internal server error in CRUD endpoints.  
docker used : nocodb/nocodb:latest
