### ISSUE TITLE
System fields not being appropriately marked for linked records on Postgres

### ISSUE THREAD

**Issue by tlonic** [nocodb/nocodb#1754]
**Please enter the following details**

please provide the following details :
NocoDB used as docker : true
NocoDB version : 0.90.3 
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : linux
Node.js version if running as node : 

**Steps To Reproduce**
1. Create a new database.
2. Create a new table.
3. In that table, create a linked record.
4. Look at project metadata, notice that system columns associated with linked records are out of sync with schema, as described in https://github.com/nocodb/nocodb/issues/1753
5. Sync schema
6. Go back to table view, look at fields.
7. See that columns associated with linked records (i.e. table_id columns) are not being correctly marked as system columns.

**Expected behavior**
Columns created to do behind the scenes stuff for linked records should not be showing up as non-system columns.

**Screenshots**
![image](https://user-images.githubusercontent.com/2394967/163896292-7dd2f6c1-6b8d-4069-9baf-87e1c821fcb5.png)

**Comment by wingkwong** [comment]
It exists when the meta is out of sync. I did it in this order 1 -> 5 -> 2 -> 3 -> 6 and it looks fine.

**Comment by wingkwong** [comment]
Fixed in `0.90.7`.
