### ISSUE TITLE
Filter doesn't return correct results on linked record

### ISSUE THREAD

**Issue by tlonic** [nocodb/nocodb#1756]
please provide the following details :
NocoDB used as docker : true
NocoDB version : 0.90.3
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created : sqlite3

**Steps To Reproduce**
1. Create two new tables, populate with entries.

Case 1:
2. In second table, create a "has many" linked record linked to the first table.
3. Populate the linked record with entries from the first table.
4. Go to the first table, filter by the one-many linked record column.
5. Filter returns every entry if any entry matches the condition, returns no entries if no entry matches the condition (i.e., if the linked records in all of the rows are "A", "B", and "C", filtering for "A" will return all entries, including those linked to "B" and "C", and filtering for "D" will not return anything)

Case 2: 
6. Now, create a "has many" linked record in the first table which also links to the first table. Populate this with records.
7. Filter by this column.
8. Filter returns the opposite of what is expected -- ie if you filter for "is like" "A", it  will return everything that is not like "A", if you filter for "is not like" "A", it will return everything that is like "A".

**Expected behavior**
In Case 1, the filter should return only the matching entries, not every entry.
In Case 2, the filter should return the opposite of what it currently returns.

**Comment by wingkwong** [comment]
Here's some screenshots for illustrations.

Table A:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/35857179/163918138-49097102-e46a-46e6-a97a-575afa36c018.png">

Table B:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/35857179/163918154-c667bbae-3bac-4250-885c-f092d363c49c.png">

Case 1: 
<img width="910" alt="image" src="https://user-images.githubusercontent.com/35857179/163918169-c5c9348b-c95d-4a76-8e45-5502b71e340d.png">

Case 2: 

Somehow I got this when linking records.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/35857179/163918518-845cb416-888c-4cfd-9900-5bd8dd67de1d.png">
