### ISSUE TITLE
Search Columns & Filter feature do not work with non english title columns.

### ISSUE THREAD

**Issue by Chernfalin** [nocodb/nocodb#1758]
![image](https://user-images.githubusercontent.com/33632784/163953451-1f185ae6-e499-4e2b-9677-faaabaf3ed06.png)
only title & title2 column work in this sample.

Version: official docker-compose image.

**Comment by wingkwong** [comment]
Could you please provide [Project Info](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-)? Also could you please paste some Japanese words here for us to reproduce the issue? Thanks.

**Comment by Chernfalin** [comment]
> Could you please provide [Project Info](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-)? Also could you please paste some Japanese words here for us to reproduce the issue? Thanks.

upgrade to v0.9.0 fix this bug, thanks all the same.
