### ISSUE TITLE
'fields' query parameter in REST API has no effect

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#1762]
Returned results of the following GET requests are the same : (

`/api/v1/db/data/{orgs}/{projectName}/{tableName}`
`/api/v1/db/data/{orgs}/{projectName}/{tableName}?fields=field_name`

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.3**

**Comment by wingkwong** [comment]
Able to reproduce. 

At the same time, you can use `/api/v1/db/data/{orgs}/{projectName}/{tableName}/views/{viewName}?fields= field_name` to get the same result.

**Comment by wingkwong** [comment]
covered in #1856.
