### ISSUE TITLE
Color code for HasMany, ManyToMany, Lookup and Rollup

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1766]
We'd them < 0.90 - lets bring them back

**Comment by o1lab** [comment]
<img width="609" alt="Screenshot 2022-04-19 at 19 33 42" src="https://user-images.githubusercontent.com/5435402/164072169-bfc3c535-1129-4579-a9f8-d14a8cc2d1d5.png">
<img width="612" alt="Screenshot 2022-04-19 at 19 33 49" src="https://user-images.githubusercontent.com/5435402/164072179-587c6c9f-0669-4b3a-9efc-58abb7377216.png">
<img width="629" alt="Screenshot 2022-04-19 at 19 33 58" src="https://user-images.githubusercontent.com/5435402/164072186-2abab08f-3968-462b-bded-d177db8444da.png">

**Comment by o1lab** [comment]
In <0.90 - this was how it was
<img width="751" alt="Screenshot 2022-04-19 at 19 37 18" src="https://user-images.githubusercontent.com/5435402/164072763-7e99af72-e133-413a-bad1-fce38ace9129.png">
<img width="1030" alt="Screenshot 2022-04-19 at 19 37 30" src="https://user-images.githubusercontent.com/5435402/164072768-1e538ae1-4bac-46b1-b9d3-2f1cc7326218.png">

<img width="522" alt="Screenshot 2022-04-19 at 19 37 14" src="https://user-images.githubusercontent.com/5435402/164072760-389951cb-8db7-4216-9508-fd80376c8945.png">

@mertmit could you please see through this.

We will have to take care of HasMany (orange), ManyToMany (pink), BelongsTo (blue), Lookups, Rollups

**Comment by wingkwong** [comment]
@mertmit Also the owner badge color is different than previous one under User Management, while other colors for roles look fine.
