### ISSUE TITLE
Bug: ID column is unknown 

### ISSUE THREAD

**Issue by brakmic** [nocodb/nocodb#177]
In most of my tables the PK columns aren't visible and therefore I can't execute queries like *SELECT * FROM SomeTable Where SomeEntry_ID*

Interestingly, the ID columns seem to be unknown. This is the error message I get via Swagger: 

`Undefined binding(s) detected when compiling FIRST. Undefined column(s): [SomeEntry_ID] query: select top(?)....`

**Comment by pranavxc** [comment]
Can you share more informations?

**Comment by o1lab** [comment]
Feel free to reopen with more details.
