### ISSUE TITLE
LTAR field- update operation not reflected till hard refresh

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1770]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.3**

- create country hm city table
![Screenshot 2022-04-19 at 11 46 22 PM](https://user-images.githubusercontent.com/86527202/164069506-a96664d5-0429-4281-a6a8-dab114b67592.png)
![Screenshot 2022-04-19 at 11 46 30 PM](https://user-images.githubusercontent.com/86527202/164069532-8696767f-c699-4579-9f5c-16fc5ff56c89.png)

- in country table, expand row for 'aus' & link to sydney record, save
![Screenshot 2022-04-19 at 11 46 46 PM](https://user-images.githubusercontent.com/86527202/164069854-2ab2e3b5-20f1-41b7-be28-7a757d25ff20.png)

- toast says `no columns to update`
![Screenshot 2022-04-19 at 11 46 51 PM (2)](https://user-images.githubusercontent.com/86527202/164069898-f3502427-357f-4b34-b4ce-0b5763f2f5b5.png)

- column entry is displayed only after hard refresh
![Screenshot 2022-04-19 at 11 47 09 PM](https://user-images.githubusercontent.com/86527202/164069982-c2dfae26-5b49-41f8-bdaf-15e06138fa57.png)

**Comment by o1lab** [comment]
Good to close with launch of new UI.
