### ISSUE TITLE
Migration from 0.84.16 to 0.90.4 failed (mssql, docker)

### ISSUE THREAD

**Issue by pnose** [nocodb/nocodb#1790]
**Please enter the following details**

please provide the following details :
NocoDB used as docker : true
NocoDB version : 0.90.4
Database used in NC_DB URL  : mssql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mssql
OS on which NocoDB is running : Linux
Node.js version if running as node : 
Database version : 15.0.4198.2

**Steps To Reproduce**
1. docker stop; docker rm
2. Update docker image to latest (a71915c3a2dc)
3. docker run
4. Dashboard isn't shown in frontend ("Cannot GET /")
5. See error

**Expected behavior**
Frontend starting; Dashboard shown; Migration done; No error in log

**Error**
App started successfully.
Visit -> ***********
Wed, 20 Apr 2022 07:11:17 GMT tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. at node_modules/mssql/lib/tedious/connection-pool.js:61:23
Creating REST APIs mssql - > projectdb
┌ Migration from 0084002 to 0090000 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      ││   TransactionError: insert into [nc_columns_v2] ([ai], [au], [base_id],      ││   [cc], [cdf], [clen], [column_name], [cop], [created_at], [csn], [ct],      ││   [dt], [dtx], [dtxp], [dtxs], [fk_model_id], [id], [np], [ns], [order],     ││   [pk], [project_id], [pv], [rqd], [system], [title], [uidt], [un],          ││   [unique], [updated_at]) values (DEFAULT, DEFAULT, @p0, DEFAULT, DEFAULT,   ││   DEFAULT, DEFAULT, DEFAULT, CURRENT_TIMESTAMP, DEFAULT, DEFAULT, DEFAULT,   ││   DEFAULT, DEFAULT, DEFAULT, @p1, @p2, DEFAULT, DEFAULT, DEFAULT, DEFAULT,   ││   @p3, DEFAULT, DEFAULT, DEFAULT, @p4, @p5, DEFAULT, DEFAULT,                ││   CURRENT_TIMESTAMP) - Can't acquire connection for the request. There is    ││   another request in progress.                                               ││   at Transaction.acquire                                                     ││   (/usr/src/app/node_modules/mssql/lib/base/transaction.js:63:30)            ││   at Immediate.<anonymous>                                                   ││   (/usr/src/app/node_modules/mssql/lib/tedious/request.js:409:19)            ││   at processImmediate (internal/timers.js:461:21)                            ││                                                                              ││                                                                              ││   Please raise an issue in our github by using following link :              ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   ││   e=bug_report.md                                                            ││                                                                              ││   Or contact us in our Discord community by following link :                 ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
TransactionError: insert into [nc_columns_v2] ([ai], [au], [base_id], [cc], [cdf], [clen], [column_name], [cop], [created_at], [csn], [ct], [dt], [dtx], [dtxp], [dtxs], [fk_model_id], [id], [np], [ns], [order], [pk], [project_id], [pv], [rqd], [system], [title], [uidt], [un], [unique], [updated_at]) values (DEFAULT, DEFAULT, @p0, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, CURRENT_TIMESTAMP, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, @p1, @p2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, @p3, DEFAULT, DEFAULT, DEFAULT, @p4, @p5, DEFAULT, DEFAULT, CURRENT_TIMESTAMP) - Can't acquire connection for the request. There is another request in progress.
    at Transaction.acquire (/usr/src/app/node_modules/mssql/lib/base/transaction.js:63:30)
    at Immediate.<anonymous> (/usr/src/app/node_modules/mssql/lib/tedious/request.js:409:19)
    at processImmediate (internal/timers.js:461:21) {
  code: 'EREQINPROG'
}

**Comment by o1lab** [comment]
Can't acquire connection for the request. There is ││ another request in progress. ││ at Transaction.acquire │

**Comment by o1lab** [comment]
Could you please try 0.90.5 and let us know if u still face the issue?

**Comment by pnose** [comment]
Sorry, my mistake. I already tried 0.90.5. Thought I was pulling 0.90.4 when I ran latest.

REPOSITORY          TAG       IMAGE ID       CREATED        SIZE
nocodb/nocodb       0.90.5    a71915c3a2dc   11 hours ago   104MB
nocodb/nocodb       latest    a71915c3a2dc   11 hours ago   104MB
nocodb/nocodb       0.84.16   d2133f3cbc4f   13 days ago    103MB

The error mentioned in this issue is from 0.90.5.

When I look into the SQL sessions, there's the docker container holding a lock. According to dbcc inputbuffer, the command run is the one mentioned in the error message.

**Comment by o1lab** [comment]
Thank you, will take a look

**Comment by titouancreach** [comment]
does rollback fix this ?

**Comment by o1lab** [comment]
Please try it out. It should work. 

Any more details on this would be really helpful.

**Comment by titouancreach** [comment]
I can confirm that using: https://hub.docker.com/layers/nocodb/nocodb/nocodb/0.84.16/images/sha256-5645ec5b2198163d00e8a3f26b12bc2e6b8c00264eec0e6b1bd97f2726e9269d?context=explore works as a workaround. Even if the migration has failed before.

**Comment by pranavxc** [comment]
@titouancreach Hi, if we shared a custom docker build can you test it out?

**Comment by titouancreach** [comment]
@pranavxc no problem

**Comment by pranavxc** [comment]
> @pranavxc no problem

Thanks for the quick response, let me build a custom image and I will share it with you.

**Comment by pranavxc** [comment]
@titouancreach once this action completed i will share the image details

https://github.com/nocodb/nocodb/actions/runs/2219952050

**Comment by pranavxc** [comment]
@titouancreach - Please try with this docker image - `nocodb/nocodb-timely:20220425-1200`

**Comment by titouancreach** [comment]
@pranavxc It works, Good job :)
