### ISSUE TITLE
Styling issue with Team & Settings modal

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#1793]
Side menu's background in any dark theme leaves inactive menu items barely visible.

<details> 
  <summary>gif</summary>
  
![Peek 2022-04-20 11-02](https://user-images.githubusercontent.com/61871501/164181893-271d7551-4e7e-4677-922b-f6f9aa99ad0b.gif)

</details>

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.5**

**Comment by o1lab** [comment]
Thank you reporting improvements/bugs @RawmanGrey - we really appreciate it. 

If possible could you make a PR to this. Here is how to [get started with our dev setup](https://github.com/nocodb/nocodb#development-setup).

**Comment by RawmanGrey** [comment]
> Thank you reporting improvements/bugs @RawmanGrey - we really appreciate it.
> 
> If possible could you make a PR to this. Here is how to [get started with our dev setup](https://github.com/nocodb/nocodb#development-setup).

Thank **you** for the great project, it's very helpful with my current fire-fight! I promise to find a way contribute it : )
