### ISSUE TITLE
My user is suddenly missing

### ISSUE THREAD

**Issue by erikboberg** [nocodb/nocodb#1794]
Hi,
I have used NocoDb for a couple of weeks and I like it. However I now ran in to an issue that completely prevents me from accessing my databases.

I created a user (erik@erikboberg.se) when I first set up the app. I am using Docker. 

Suddenly the user I created was missing and I was presented with the create new user screen. I re-created the same user, but now I do not have permission to access my old projects, I get a 403 error. Perhaps the container was updated and restarted, I have automatic updates turned on, using the `:latest` branch

In the log this is posted: 

```
s [Error]: projectGet - user : Not allowed

at Function.forbidden (/usr/src/app/docker/main.js:2:36294)
at /usr/src/app/docker/main.js:2:14137
at /usr/src/app/docker/main.js:2:35562
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
at /usr/src/app/docker/main.js:2:13845
at /usr/src/app/docker/main.js:2:35562
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
at t.default (/usr/src/app/docker/main.js:2:487981)
GET /api/v1/db/meta/projects/monsterservern_fzgq 403 41 - 1.886 ms
GET /api/v1/db/auth/user/me 304 - - 0.824 ms
GET /api/v1/db/meta/projects/ 304 - - 0.647 ms
```

When I check the mysql database it contains duplicate tables ending in `_v2`. For example it has both `nc_projects_users` and `nc_projects_users_v2`.

How can I regain access to my data? Where are the users stored? Maybe they are not persisted when resetting the container during an update? 

I mounted the folder `/usr/app/data/` to a folder on my server, and it has now a bunch of subfolders with the same names as my projects, but no files in them. 

Thank you.
Erik

**Comment by wingkwong** [comment]
> Suddenly the user I created was missing and I was presented with the create new user screen. I re-created the same user, but now I do not have permission to access my old projects, I get a 403 error. Perhaps the container was updated and restarted, I have automatic updates turned on, using the :latest branch

Can you show the project info? 

> When I check the mysql database it contains duplicate tables ending in _v2. For example it has both nc_projects_users and nc_projects_users_v2.

Yes. It is expected to see `_v2` tables which are introduced since `>=0.90.0`. Do you have other users in previous version? If so, can you help check if they can be found in `nc_users_v2`?

> How can I regain access to my data? Where are the users stored? Maybe they are not persisted when resetting the container during an update?

We need to investigate more. The users are stored in the meta database. If you upgrade to version `>=0.90.0`, we'd migrate the existing meta to the new schema. 

> I mounted the folder /usr/app/data/ to a folder on my server, and it has now a bunch of subfolders with the same names as my projects, but no files in them.

Are you using docker-compose or just docker? Have you specified `NC_DB`?

**Comment by erikboberg** [comment]
Thank you for quick reply!

> Can you show the project info?
When I click on the projects in the "My projects" list I immediately get the 403 error. Or what do you mean? 

> Do you have other users in previous version? 
I only had one user in the previous version (erik@erikboberg.se)

> If so, can you help check if they can be found in nc_users_v2?
I do not have an `nc_users_v2` table. I have `nc_projects_users_v2`. This table is empty. The `nc_projects_users` contains 2 rows, one for each project, with a user id of "1" in them and the project name and roles: `owner`. 

> We need to investigate more. The users are stored in the meta database. If you upgrade to version >=0.90.0, we'd migrate the existing meta to the new schema.
I can not find the "meta" database.

> Are you using docker-compose or just docker? Have you specified NC_DB?
Just docker. 

NC_DB is specified: `mysql2://192.168.2.2:3308?u=root&p=MY_DB_ROOT_PASSWORD&d=d1`

**Comment by wingkwong** [comment]
Please DM me in discord. (same username)

**Comment by erikboberg** [comment]
> Please DM me in discord. (same username)

I need your 4 last digits of discord ID

**Comment by wingkwong** [comment]
> I need your 4 last digits of discord ID

I think it's `3278`. 

Alternatively, you can go to our [NocoDB Discord](https://discord.gg/5RgZmkW) and you can see my name right under NOCO-TEAM.
