### ISSUE TITLE
Multiple lookup columns in one table result in malfunction

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#1799]
Using more then one lookup (no matter what kind of relation is used as source) properly returns data in GET requests, but only data from first created lookup can be used in formulas and filtering table (including querying via `where` parameter). Referencing other lookup's data result in errors.

<details> 
  <summary>.gif illustration</summary>
   
![Peek 2022-04-20 18-32](https://user-images.githubusercontent.com/61871501/164271851-f999f34a-5d4c-48a1-afa2-dea799cd10bf.gif)
  
</details>

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.5**

---
Just a little bit remaining to be absolutely happy with an opportunity to use lookups and formulas in filters and REST API calls : )

**Comment by o1lab** [comment]
Hey @RawmanGrey, this looks like second filter you are applying is a like and the column is a number - hence its not working. Can you try an equal or other operator ?

We will improve the option available for each field.

**Comment by RawmanGrey** [comment]
Sorry, my bad with numbers - I thought Lookups return strings (like they are handled in Notion). How do they handle multiple numbers, though?

But unfortunately bug is real. It should be described as following:

Lookup columns referencing parent's field return errors if used in filters or formulas. 
Issue is not related to data type (tested with strings and numbers). Lookups from parent entry work as expected.

Error message from example below complains on missing  `__nc0.nc_0ysj__types_id` column.

<details> 
  <summary>.gif example</summary>
   
![Peek 2022-04-21 15-17](https://user-images.githubusercontent.com/61871501/164456773-81693c89-a7b3-461d-80a3-c11b98b41912.gif)

</details>

**Comment by RawmanGrey** [comment]
@o1lab I'm sorry, if it's inappropriate, but should I close this issue and open new one with problem redefined above?

**Comment by o1lab** [comment]
yes @RawmanGrey that would be helpful. We really appreciate all the bugs/improvements you are suggesting.

**Comment by RawmanGrey** [comment]
Issue closed due to improper problem definition. Issue made clear in #1866 .
