### ISSUE TITLE
Feature request : add support for JDBC

### ISSUE THREAD

**Issue by morandalex** [nocodb/nocodb#180]
The most of the times a person working in system integrations needs more database connection.
It would be amazing having a bridge like jdbc drivers to autogenenerate a rest or graphql, as is doing Cloudbeaver.

**Comment by o1lab** [comment]
Adding a new database support is considerably a significant effort as seen from our current implementation and others. 

We will consider JDBC and likes but I imagine it isn't straightforward.

**Comment by NathanQ** [comment]
I'd recommend eliminating mentioning JDBC url format as use case does not follow [JDBC format](https://www.codejava.net/java-se/jdbc/jdbc-database-connection-url-for-common-databases).
