### ISSUE TITLE
[Feature] interactive filter/selector like Grafana variables.

### ISSUE THREAD

**Issue by Chernfalin** [nocodb/nocodb#1807]
Grafana variables instance:
![image](https://user-images.githubusercontent.com/33632784/164355514-1ad204c7-7823-4245-b54f-632ad3f86ee1.png)
When there are many data in one table, use the search or filter to find one data with multi tag is not an easy thing.
A better way is interactive filter/selector, just like what Grafana variables feature have done.
Creators can create variables to query and unique the tag data to make an interactive filter. 
Users can the interactive filter to select and find the data quickly.

**Comment by dstala** [comment]
To be handled along with

[🔦 Feature: Ability to Create Presets for Visible Fields, Filters, and Sorting](https://github.com/nocodb/nocodb/issues/5893)
