### ISSUE TITLE
[Feature] Use formula column as primary value

### ISSUE THREAD

**Issue by tlonic** [nocodb/nocodb#1809]
## Recommending Features

**Need for this feature**
Allows one to create a title for every row which combines elements from multiple fields. Especially helpful since the primary view determines what shows up in linked records.

**Is your feature request related to a problem? Please describe.**
You cannot set a formula column as a primary view

**Describe the solution you'd like**
Ability to set formula column as a primary view

**Comment by rallisf1** [comment]
In 0.91.7 for some reason it automatically uses the formula field of the linked table as the primary value, although you can't manually set it. See #2316

**Comment by Curiuke** [comment]
I´d love this feature too :)

**Comment by paullaffitte** [comment]
**Definitely a must have!**

Here is my case: I import my bank statements in nocodb for my personal accounting. My columns are: `accounting_date`, `label`, `reference`, `credit` and `debit`. So for example I can have a record like this:

```json
{
  "accounting_date": "2022-09-03",
  "label": "PRLV SEPA XXXXXX",
  "reference": "WJCO239",
  "debit": 42.42,
  "credit": 0,
}
```

For some reason, my bank sometimes use the same reference for several transactions, for recurring transaction, the label isn't very helpful for identification and the date is obviously not a candidate.

I would like to use as primary value a formula including at least the date and the total value of the transaction, example: `[2022-09-03] 42.42`. This way it would be much easier to link a transaction to a budget for instance.

**Comment by pareshpandit** [comment]
**+1 for this feature request.**

This gives one the flexibility to concatenate one or two fields in a (hidden) column, and use it as a sort of "data-label" in related table entries, such that the relation/origin can be more readily identified.  _/|\_  :)

**Comment by dstala** [comment]
available now in https://github.com/nocodb/nocodb/releases/tag/0.105.0
