### ISSUE TITLE
Only owner can use ”Upload CSV“  when updated to PackageVersion: 0.90.5

### ISSUE THREAD

**Issue by cuizhao** [nocodb/nocodb#1810]
In PackageVersion: 0.84.16 the creater can ”Upload CSV“ ,But when I updated to PackageVersion: 0.90.5 Only owner can use ”Upload CSV“. This is an very serious bug on PackageVersion: 0.90.5 .I wish nocodb team can fix this bug or grant editer the authority of ”Upload CSV“.And the ”Upload CSV“ is a very important function to  editer!
Thanks a lot!

**Comment by wingkwong** [comment]
Closing as it is duplicate as https://github.com/nocodb/nocodb/issues/1683.
