### ISSUE TITLE
multiple LTAR to same table- not distinguishable in UI

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1811]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.5**

- Create country hm city
- Add second relation between country & city (hm/mm)
- Try to add lookup field in country table. Two entries shown - but indistinguishable

![Screenshot 2022-04-21 at 12 41 46 PM](https://user-images.githubusercontent.com/86527202/164397891-47247a6d-d87e-477a-8c8b-9fc2dda311e3.png)

**Comment by tlonic** [comment]
same issue as https://github.com/nocodb/nocodb/issues/1768
