### ISSUE TITLE
JSON type data is not getting saved from UI

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1814]
Reported by @vijayrathore8492 via discord

**Comment by mertmit** [comment]
I wasn't able to reproduce the issue.
@vijayrathore8492 Is it possible for you to provide an example JSON to reproduce the issue (also your project info would be awesome)

JSON used:
```
{
  "name": "Noco",
  "age": 2,
  "car": null
}
```

**Project Info:**
Node: **v14.18.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.90.5**

**Comment by wingkwong** [comment]
Able to reproduce. 

Steps to reproduce:

- create a JSON type column
- copy @mertmit 's JSON and paste to the cell
- Refresh the page
- The data is not saved

**Comment by wingkwong** [comment]
@mertmit The root cause is 

`jsonEditableCell` emits `input` to `editableCell` which emits `save` to `XcGridView`. However, `save` in `xcGridView` only executes `editEnabled = {}` but not saving the actual value. This also applies to other files using `EditableCell`.

**Comment by mertmit** [comment]
Then this should be also solved by https://github.com/nocodb/nocodb/pull/1817

**Comment by wingkwong** [comment]
Okay. Haven't checked that yet. Will review soon. Thanks!

**Comment by o1lab** [comment]
0.90.7
