### ISSUE TITLE
error 400 when upload to S3

### ISSUE THREAD

**Issue by wingchee89** [nocodb/nocodb#1822]
please provide the following details :
NocoDB used as docker : true
NocoDB version : 0.90.4
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql 
OS on which NocoDB is running : Amazon Linux
Node.js version if running as node : 
Database version : 8.0

**Steps To Reproduce**
1. Add S3 from App Store
2. Add attachment to table 
3. 400 error. 

Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: ** mysql**

**Comment by wingkwong** [comment]
Any logs / error messages you can provide?

**Comment by o1lab** [comment]
Recently, @vijayrathore8492 mentioned about this. And the fix will make it next release (today)

**Comment by wingkwong** [comment]
Linking https://github.com/nocodb/nocodb/commit/83e13a1fbc2aaf85859279f9500b73e04f0b5035 for the record.

**Comment by phpb-com** [comment]
This is still an issue when you have Minio (S3 clone) configured. Same symptoms and errors as described above. Below is the log snippet:
```
2022-04-27 00:32:38.156731+00:00v :: TypeError: Cannot read property 'fileCreate' of undefined
2022-04-27 00:32:38.156817+00:00at /usr/src/app/docker/main.js:2:452611
2022-04-27 00:32:38.156835+00:00at Array.map (<anonymous>)
2022-04-27 00:32:38.156846+00:00at v (/usr/src/app/docker/main.js:2:452517)
2022-04-27 00:32:38.156911+00:00at runMicrotasks (<anonymous>)
2022-04-27 00:32:38.156924+00:00at processTicksAndRejections (internal/process/task_queues.js:97:5)
2022-04-27 00:32:38.156933+00:00at async /usr/src/app/docker/main.js:2:35545
2022-04-27 00:32:38.158037+00:00POST /api/v1/db/storage/upload?path=noco%2FTest+Project%2FFiles%2FFile+PDF 400 56 - 23.683 ms
```

**Comment by phpb-com** [comment]
Pinging @wingkwong

**Comment by wingkwong** [comment]
++ Error from Discord user silverlight

```
upload :: TypeError: storageAdapter.fileCreate is not a function
    at /Users/liemnguyen/code-int/nocodb/packages/nocodb/src/lib/noco/meta/api/attachmentApis.ts:25:38
    at Array.map (<anonymous>)
    at upload (/Users/liemnguyen/code-int/nocodb/packages/nocodb/src/lib/noco/meta/api/attachmentApis.ts:22:25)
    at /Users/liemnguyen/code-int/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:6:14
```

**Comment by vijayrathore8492** [comment]
@wingkwong changing [line](https://github.com/nocodb/nocodb/blob/de8fd072aef8d30b1aefbf7bb7ddb811404b9f07/packages/nocodb/src/lib/noco/meta/helpers/NcPluginMgrv2.ts#L126) to `return plugin.getAdapter() as IStorageAdapter;` fixed it for me. (for S3)

**Comment by ovizii** [comment]
> Can confirm that it now works with Minio for uploading of attachments. Unrelated to this bug report is that access is impossible (with Minio) to non-public buckets. Files makes it to the bucket but trying to get it results in denied access since no temp access signature is passed via URL. This feature is not useful for files that are not publicly shared.

I can confirm. Even though nocodb has been supplied with a minio key and secret which has read/write permissions to this bucket downloading something which nocodb has previously uploaded is not possible unless you make the bucket public.
