### ISSUE TITLE
Build Docker image for ARM, ARM64 (M1)

### ISSUE THREAD

**Issue by NN708** [nocodb/nocodb#183]
Is it possible to build a Docker image for ARM and ARM64 to run on Raspberry Pi?

**Comment by gquelch** [comment]
I tried building a container on my raspberry pi but ran into an issue with a missing main.js file:

```
Sending build context to Docker daemon  84.75MB
Step 1/12 : FROM alpine:3.12
3.12: Pulling from library/alpine
420c7481a3a7: Pull complete
Digest: sha256:36553b10a4947067b9fbb7d532951066293a68eae893beba1d9235f7d11a20ad
Status: Downloaded newer image for alpine:3.12
 ---> 36a8b93b867d
Step 2/12 : ENV PORT 8080
 ---> Running in aa97abef4489
Removing intermediate container aa97abef4489
 ---> f992bf32726a
Step 3/12 : ENV NODE_ENV=dev
 ---> Running in da3eb2bd8b4b
Removing intermediate container da3eb2bd8b4b
 ---> d36c149addff
Step 4/12 : ENV NC_VERSION=0.6
 ---> Running in 4df2cbb8741c
Removing intermediate container 4df2cbb8741c
 ---> b15dedee6cc1
Step 5/12 : ENV NC_DOCKER=0.6
 ---> Running in a2a1d9764f89
Removing intermediate container a2a1d9764f89
 ---> 54aff99fb420
Step 6/12 : WORKDIR /usr/src/appTemp
 ---> Running in 1246787cadfd
Removing intermediate container 1246787cadfd
 ---> 35519430b3fd
Step 7/12 : COPY ./docker/main.js ./docker/main.js
COPY failed: file not found in build context or excluded by .dockerignore: stat
docker/main.js: file does not exist
```

It seems to be missing because its in the .gitignore located here:

 nocodb/packages/nocodb/.gitignore

I tried building with that line commented out of the dockerfile but that led to this error once the container was running:

```

Error: Cannot find module '/usr/src/app/docker/main.js'


    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)


    at Function.Module._load (internal/modules/cjs/loader.js:667:27)


    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)


    at internal/main/run_main_module.js:17:47 {


  code: 'MODULE_NOT_FOUND',


  requireStack: []


}


internal/modules/cjs/loader.js:818
```

**Comment by pranavxc** [comment]
> I tried building a container on my raspberry pi but ran into an issue with a missing main.js file:
> 
> ```
> Sending build context to Docker daemon  84.75MB
> Step 1/12 : FROM alpine:3.12
> 3.12: Pulling from library/alpine
> 420c7481a3a7: Pull complete
> Digest: sha256:36553b10a4947067b9fbb7d532951066293a68eae893beba1d9235f7d11a20ad
> Status: Downloaded newer image for alpine:3.12
>  ---> 36a8b93b867d
> Step 2/12 : ENV PORT 8080
>  ---> Running in aa97abef4489
> Removing intermediate container aa97abef4489
>  ---> f992bf32726a
> Step 3/12 : ENV NODE_ENV=dev
>  ---> Running in da3eb2bd8b4b
> Removing intermediate container da3eb2bd8b4b
>  ---> d36c149addff
> Step 4/12 : ENV NC_VERSION=0.6
>  ---> Running in 4df2cbb8741c
> Removing intermediate container 4df2cbb8741c
>  ---> b15dedee6cc1
> Step 5/12 : ENV NC_DOCKER=0.6
>  ---> Running in a2a1d9764f89
> Removing intermediate container a2a1d9764f89
>  ---> 54aff99fb420
> Step 6/12 : WORKDIR /usr/src/appTemp
>  ---> Running in 1246787cadfd
> Removing intermediate container 1246787cadfd
>  ---> 35519430b3fd
> Step 7/12 : COPY ./docker/main.js ./docker/main.js
> COPY failed: file not found in build context or excluded by .dockerignore: stat
> docker/main.js: file does not exist
> ```
> 
> It seems to be missing because its in the .gitignore located here:
> 
> nocodb/packages/nocodb/.gitignore
> 
> I tried building with that line commented out of the dockerfile but that led to this error once the container was running:
> 
> ```
> 
> Error: Cannot find module '/usr/src/app/docker/main.js'
> 
> 
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
> 
> 
>     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
> 
> 
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
> 
> 
>     at internal/main/run_main_module.js:17:47 {
> 
> 
>   code: 'MODULE_NOT_FOUND',
> 
> 
>   requireStack: []
> 
> 
> }
> 
> 
> internal/modules/cjs/loader.js:818
> ```

Generate `main.js` file using following commands

```
npm run build
npm run docker:build
```

**Comment by thinkpace** [comment]
I'd love to see it running on a Raspberry Pi using Docker and I think this would enable a lot of users to use NocoDB.

**Comment by azrikahar** [comment]
@NN708 @gquelch @thinkpace Hi guys, I've recently tried to help out and created an arm64 & armv7 variant of nocodb image over at https://hub.docker.com/r/azrikahar/nocodb. Would you guys mind helping to test whether it works for your machine? If it does work, I can then move forward to create a PR for this :)

**Comment by dbarrosop** [comment]
@azrikahar I tested it on a raspberry pi 4 and it worked great :)

**Comment by gquelch** [comment]
@azrikahar Thanks for doing that, on my RPi 2 model B I seem to always get the following error:

```
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7eafa27c
Illegal instruction (core dumped)
```

**Comment by thinkpace** [comment]
@azrikahar Thank you very much, unfortunately I have the same issue as @gquelch when running "`docker run azrikahar/nocodb:latest`":

    #
    # Fatal error in , line 0
    # unreachable code
    #
    #
    #
    #FailureMessage Object: 0xbe9c827c
    Illegal instruction (core dumped)

My test system:

Raspberry Pi 4 Model B PCB Revision 1.4
Raspbian GNU/Linux 10 (buster)
Linux amalthea 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

**Comment by dbarrosop** [comment]
In case it helps, it works fine on my device which is:

Raspberry Pi 4 Model B PCB Revision 1.4
Linux jupiter 5.10.42 #1-NixOS SMP Thu Jun 3 07:00:52 UTC 2021 aarch64 GNU/Linux

**Comment by azrikahar** [comment]
@dbarrosop thanks for sharing the details! These responses lead me to believe the arm64 image works, but not the armv7 one, which seems to be quite a number of other devs facing the same thing when using docker buildx.

@gquelch  @thinkpace  seems like the armv7 image is the issue here (and there are numerous reports on armv7 target using docker buildx). Thanks for the prompt feedback guys. Will try to investigate this further!

**Comment by azrikahar** [comment]
@gquelch @thinkpace can you guys help test a new image, specifically `azrikahar/nocodb:experimental`? It was built yesterday but I didn't want to repetitively ask you guys to test every images I built (which unfortunately is quite many but I removed all of them from dockerhub) so I had to wait until I got the chance to format my RPi and test it myself. Thankfully it actually works! hopefully this works for you guys as well.

**Comment by thinkpace** [comment]
Looks great, I'm testing on the same device as before and it works great so far, here my test cases:

- [x] Container startup
- [x] Dashboard is loading and loads first configuration
- [x] Create new project
- [x] Create a simple table with content

I just found one thing, but I'm not totally sure if this is related to your container. When I'm trying to use the API (using internal Swagger), I get `TypeError: NetworkError when attempting to fetch resource.`. It shows `http://localhost:8080/nc/test_IWRz/api/v1/Foobar/1` as request URL.
Possible reason could be that I'm using your container on port 8081 instead of 8080.

**Comment by o1lab** [comment]
> It shows http://localhost:8080/nc/test_IWRz/api/v1/Foobar/1

@azrikahar : any idea on which version the fork was made ? Looks like the port 8080 issue got resolved in bug fix.

**Comment by azrikahar** [comment]
@o1lab it was definitely before the bugfix was added. I've just pushed a new `azrikahar/nocodb:experimental` image with the newer commits, tested the swagger API right on `<my-rpi-ip>:8081` and the `/auth/signin` worked perfectly!

@thinkpace as o1lab mentioned, it was indeed the codebase issue but luckily it got patched just a few hours earlier :) Would you mind trying to pull the newer `azrikahar/nocodb:experimental` and let us know how it goes? Personally I did try exactly what you mentioned (port 8081, swagger and tested /auth/signin with my admin credentials) with the new image and it worked!

**Comment by thinkpace** [comment]
@azrikahar perfect, now it works and it shows the right URL as `request URL` (DNS entry which I'm using in my browser and right port).

Totally great, thanks a lot!

**Comment by azrikahar** [comment]
@thinkpace thanks once again for your prompt testings & detailed info each time. I'll start creating the PR now 👍

**Comment by MrOneTwo** [comment]
I'm seeing the issues on Raspberry Pi 3

```
tar: ./node_modules/pg-types/lib/builtins.js: time stamp 2023-02-21 06:54:11 is 1040556707 s in the future
tar: ./node_modules/pg-types/lib/binaryParsers.js: time stamp 2023-02-21 06:54:10 is 1040556706 s in the future
tar: ./node_modules/pg-types/lib/arrayParser.js: time stamp 2023-02-21 06:54:09 is 1040556705 s in the future
tar: ./node_modules/verror/package.json: time stamp 2023-02-21 06:53:56 is 1030556720 s in the future
tar: ./node_modules/verror/lib/verror.js: time stamp 2023-02-21 06:54:05 is 1030556729 s in the future
tar: ./package-lock.json: time stamp 2023-02-21 06:50:02 is 1030556486 s in the future
tar: ./package.json: time stamp 2023-02-21 06:50:02 is 990556600 s in the future
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ea46634
Trace/breakpoint trap (core dumped)
```
The Docker command I use:

```
docker run -d --name nocodb -v "$(pwd)"/nocodb:/usr/app/data/ -p 8080:8080 nocodb/nocodb:latest
```
