### ISSUE TITLE
[Feature] Support rollup columns on virtual columns

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#1844]
Currently, rollup columns only works with non-virtual columns and non-system fields. As virtual columns don't have `column_name`, it results in querying null columns. Nested query is required to populate as well.

Virtual columns include:

- LinkToAnotherRecord
- UITypes.Formula
- UITypes.Rollup
- UITypes.Lookup

**Comment by dstala** [comment]
Associated Issue / feature requests
https://github.com/nocodb/nocodb/issues/1844
https://github.com/nocodb/nocodb/issues/1331

**Comment by dstala** [comment]
To be tracked under https://github.com/nocodb/nocodb/issues/1331
