### ISSUE TITLE
Migration error from 0.84.16 to 0.90.7 for sqlite3 database

### ISSUE THREAD

**Issue by ed-parsadanyan** [nocodb/nocodb#1847]
NocoDB used as docker : true
NocoDB version : 0.90.7
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created : sqlite3
OS on which NocoDB is running : Ubuntu 18.04.5 TLS
Node.js version if running as node : NA 
Database version : NA

**Steps To Reproduce**
1. docker pull nocodb/nocodb
2. sudo docker-compose stop
3. sudo docker-compose up -d
4. See error: "Cannot GET /"

Docker container log file:

[2J[0fApp started successfully.
Visit -> http://localhost:8080/dashboard
Creating REST APIs mysql2 - > <_blabla database name_>
Creating REST APIs sqlite3 - > /usr/app/data/noco.db
Creating REST APIs sqlite3 - > /usr/app/data/noco.db
Creating REST APIs sqlite3 - > /usr/app/data/noco.db
Creating REST APIs sqlite3 - > /usr/app/data/noco.db
Creating REST APIs sqlite3 - > /usr/app/data/noco.db
┌ Migration from 0080000 to 0090000 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      
││   TypeError: Cannot read property 'id' of undefined                          
││   at /usr/src/app/docker/main.js:2:1060056                                   
││   at async Object.t.default [as handler]                                     
││   (/usr/src/app/docker/main.js:2:1059862)                                    
││   at async Function.upgrade (/usr/src/app/docker/main.js:2:1045212)          
││   at async B.init (/usr/src/app/docker/main.js:2:3749)                       
││   at async /usr/src/app/docker/main.js:2:455689                              
││                                                                              
││                                                                              
││   Please raise an issue in our github by using following link :              
││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   
││   e=bug_report.md                                                            
││                                                                              
││   Or contact us in our Discord community by following link :                 
││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
TypeError: Cannot read property 'id' of undefined
    at /usr/src/app/docker/main.js:2:1060056
    at async Object.t.default [as handler] (/usr/src/app/docker/main.js:2:1059862)
    at async Function.upgrade (/usr/src/app/docker/main.js:2:1045212)
    at async B.init (/usr/src/app/docker/main.js:2:3749)
    at async /usr/src/app/docker/main.js:2:455689

Expected behaviour:
able to log in after the update.

Thanks a lot for your help!

**Comment by wingkwong** [comment]
Fixed in `0.90.8`
