### ISSUE TITLE
Lookup columns used in filters and formulas cause errors

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#1866]
Lookup columns referencing parent's field return errors if used in filters or formulas. Issue is not related to data type (tested with strings and numbers). Lookups from parent entry work as expected.

Error message from example below complains on missing '__nc0.nc_0ysj__types_id' and named alike columns.

<details> 
  <summary>.gif example</summary>
 
![Peek 2022-04-21 15-17](https://user-images.githubusercontent.com/61871501/165140280-18c1e1f6-13d9-4b0a-a6d0-1a3ff584cccc.gif)
</details>

Known since v0.90.5.

**Comment by pranavxc** [comment]
Can you share error details with the formula? Also, you can include the steps to reproduce the issue which will be helpful for us.

**Comment by RawmanGrey** [comment]
> Can you share error details with the formula? Also, you can include the steps to reproduce the issue which will be helpful for us.

If it's still relevant:

1. Create new project
2. Create table 'parents' and make new row there - 'Foo Parent'
3. Create table 'children' and make new row there - 'Bar Child'
4. Switch to 'parents' and create column with a type of 'LinkToAnotherRecord', choose 'Has Many' type 5. related to 'children' table. Link the only record in just created column.  
6. Switch to 'children' and create column  named 'lookup_child_name' with a type of 'Lookup'. Choose 'parents' as a child table and pick 'Title' child column. (bug can be reproduced with any other column as well)

Now you can see 'lookup_child_name' column's content as expected, so as get it's content in REST API call. But referencing it in flowing cases cause errors:

* Set filter in 'children' table where 'lookup_child_name' ...anything, check network requests in browser console and see requet with 400 code.

* Create 'formula' column in 'children' table. To keep it simple just reference `lookup_child_name` in formula column. It will show output as expected - 'Foo Parent'. Now, create filter based on 'formula' column. It will work as expected if using 'is equal' and 'is not null', but filtering 'is not empty' will return response with code 400 and message complaining on some empty id in quotes. Filtering by 'is like' return responses with code 200, but not returning expected results.
<details> 
  <summary>'is like' problem .gif illustration</summary>
   
![Peek 2022-04-26 10-04](https://user-images.githubusercontent.com/61871501/165242292-9c2dfcbf-a1da-4b53-b79a-65befa764b20.gif)  
</details>

It's worth to notion, that before version 0.90, GET requests containing filters had filters parameters shown in urls, but now they end up with empty '&where=', may be it is related? 

<details> 
  <summary>urls with empty 'where' at screenshoots</summary>

![Screenshot_20220426_090839](https://user-images.githubusercontent.com/61871501/165244090-ae6fa71f-d6d8-4971-923f-3423263f6f90.png)
![Screenshot_20220426_090743](https://user-images.githubusercontent.com/61871501/165244093-ed1344c7-15ae-433c-82a9-76404ef7964c.png)

</details>

PS:
I'm sorry, my postgres returns errors localized, so  I'm loosely translating those.
