### ISSUE TITLE
Formula columns on heroku not showing results.

### ISSUE THREAD

**Issue by hxdvka** [nocodb/nocodb#1868]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.7**```

**Steps To Reproduce**

1. Host on heroku with 1 click free deploy button (everything as is) and create a new project with internal db.
2. Add a table, add 2 number columns (cost, days), and any number of formula columns which use the number columns.
3. Add rows
4. The formula columns fail to show any result and there're no error reports.

**Expected Behavior**

The formula columns to be filled or an error notification.

**Screenshots**
![image](https://user-images.githubusercontent.com/104383186/165142735-32979050-c1d6-4cbe-a4c4-8483824ad971.png)
formulas are respectively:
"MAX(cost, days)" , "cost" and "(cost / days)".

also noted that when downloading the sheet as csv all values are filled correctly.
refreshing/reloading does nothing.
(view of sample sheet: https://testlvl2nocodb.herokuapp.com/dashboard/#/nc/view/dc4cb9be-110e-4856-9d34-211bb78645f5 )

**Comment by pranavxc** [comment]
It could be related to https://github.com/nocodb/nocodb/issues/1873

**Comment by hxdvka** [comment]
> It could be related to #1873
it was the same issue, ty.
(account was flagged so it wouldn't show it)
