### ISSUE TITLE
Support multiple Postgres schemas

### ISSUE THREAD

**Issue by flobaader** [nocodb/nocodb#187]
Hello,

first of all thank you for this great project, I was looking for something like this for several months.

I have a question regarding the postgres integration: is it possible to see tables from multiple schemas? Currently it looks like only the tables in the `public` schema are scanned.

Cheers!
Florian

**Comment by o1lab** [comment]
Connecting to non public schema in postgres is possible.

Below is the trick :) Use the latest 0.9.16

https://youtu.be/rS0NRwRCjx0

**Comment by flobaader** [comment]
Thank you @o1lab for the very quick reply and the helpful video! 🎉

Is it possible to include a regex here to include all schemas (like `searchPath: ["*"]` ) or is there any way to update the search path after the project creation?
