### ISSUE TITLE
Feature : Group By

### ISSUE THREAD

**Issue by Erwyn** [nocodb/nocodb#188]
Hi there!

I know the project is quite new, I just want to be sure I'm not missing something. I played a bit with the docker container to test nocodb bare, meaning with the Sqlite db that is created when we click on new project. As the target is AirTable, I tried some things I liked to do with AirTable when I tried their product.

I have two questions:

* I haven't found how to make Group bys, is it possible or planned ?
* I hanen't found how to apply functions to columns. For instance I'd like to make a group by and them sum a column. Is this possible today ?

Thanks is advance, and nice work, I can see quite a few nice use-cases.

**Comment by o1lab** [comment]
Will track this issue for Group By - Yes there is a plan. And honestly, Airtable group by is sort of columns to an extent.

For functions we 've another feature open.

**Comment by Erwyn** [comment]
> Airtable group by is sort of columns to an extent

I'm not sure of what you meant here. There is something I can already do ?

**Comment by o1lab** [comment]
There is something I can already do ?

Nope.

**Comment by Erwyn** [comment]
Thanks for all the info ! I'm very excited about your project ! :)

**Comment by ralphilius** [comment]
Can we do a vertical group by as well? Please check Coda.io for inspiration.

**Comment by o1lab** [comment]
>> Can we do a vertical group by as well? Please check Coda.io for inspiration

We do have really powerful group by APIs - I imagine those could be used.

**Comment by vilts** [comment]
One more vote for this. We use "group by" heavily in Airtable and would love to see this here too. Sorting kind of gives the same functionality, but closing/hiding groups is very convenient way to show only necessary data.

**Comment by alexn-s** [comment]
+1 it would be really helpful. i am also regularly using this feature in Airtable to simple not get lost in my data

**Comment by davebrny** [comment]
i use groups quite a bit myself so thats great to see its going to be somewhere on the roadmap

to be honest, even the groups feature that airtable uses isnt really enough for some of my use cases and i find myself wanting the option of multiple grids in one view with each group having its own filters and sort order. has anyone else has wanted something like that? it would solve a lot of problems for me anyway but i get that it might be a bit of a harder UI problem to figure out compared to just regular groups

**Comment by jkmribeiro** [comment]
+1 for colum grouping. This is something i've been using heavily in airtable, and would be awesome to have it in nocodb too!

**Comment by roman-zaiats** [comment]
+1 for grouping! It's such an desirous feature!

**Comment by ivishalgandhi** [comment]
+1 for grouping

**Comment by cwagar** [comment]
"Group By" would spur much more adoption. There is a reason PivotTables are so popular in Excel. +1 on the comment that it's a basic UI feature for users managing large amounts of data.

A good MVF would be a basic Group By function which consists of a single column sort, plus basic UI enhancements (header for each group and an accordion like show/hide).

**Comment by lublak** [comment]
A other view can be implemented for this: https://pivottable.js.org/examples/

**Comment by Sof31t** [comment]
+1 for grouping

**Comment by wanggrplus123** [comment]
+1

**Comment by atticcas** [comment]
+1

**Comment by jory3** [comment]
+1 we might be able to help here by financing some development hours, since that'd be very useful for us

**Comment by physx2494** [comment]
+1
Grouping will be tremendously helpful to cut and slice complex datasets

**Comment by folk-connect** [comment]
+1 for grouping feature. It helps to see totals at a glance. Such things are simple for DB query. But for UI users, it means to download csv and calculate in Excel

**Comment by cspocsai** [comment]
+1 for grouping

**Comment by sunnights** [comment]
+1 for colum grouping!! really need this feature

**Comment by mimyarahmadi** [comment]
+1

**Comment by ogarzlin** [comment]
+1

**Comment by DanyaBrain** [comment]
+1, need it so much

**Comment by hardrockone** [comment]
+1 for grouping

**Comment by jayce** [comment]
+1 need this feature

**Comment by kenzomartins** [comment]
+1 this is a very useful feature. my most desired feature

**Comment by gcolson** [comment]
+1, for now it is the only reason i'm not totally switching from airtable to nocodb..

**Comment by luisorbaiceta** [comment]
Reacting with a 👍 at the top is better than commenting with a "+1". Helps maintainers easily keep track of the number of people interested in the feature rather than having to count all the comments

**Comment by guy-borderless** [comment]
The groupings view is extremely useful IMO.

> Fyi, we do have underlying groupby apis already. One of the challenges here is that users are connecting to tables which has million+ rows

In my specific case, this is mainly used for views used by sales and back office workers. Humans use those views so mostly shouldn't include millions of rows anyway. so in my use-case I don't mind a LIMIT to get the awesome grouping view.

An idea about scaling this in cases where number of returned rows is big might be to show the groupings without the rows and load the grouping's rows on click.

**Comment by guy-borderless** [comment]
BTW, since I heavily use this on airtable I wonder if it's on the horizon for NocoDB. Maybe someone from the team can comment?

**Comment by o1lab** [comment]
Thank you for the details @WinstonFassett - appreciate the attempt on this. I believe it will help us when we get to it. Some notes below.

Yes, this get tricky for the following reasons.
- GroupBy column could be a lookup column that could be coming from deeply nested relation.
- GroupBy column could also be a formula which means this column has dependencies on other columns (some of which can be again lookups)
- And the scale of rows can make the things slow.

Solving above would mean the AST resolution can be complex but I believe it could be done. I think we are at a stage now where most of the formula creation and optimisations around it are in good shape. So we will look at it soon.

**Comment by sprklinginfo** [comment]
any progress on this feature? really miss it which prevents me from switching to nocodb entirely from airtable

**Comment by briankinney** [comment]
This is pretty close to a must-have feature for me to adopt nocodb!

**Comment by mertmit** [comment]
Added in https://github.com/nocodb/nocodb/releases/tag/0.111.0

**Comment by jory3** [comment]
This is great, thanks for your work! 
As far as I understand it's not (yet) possible to group by fields with linked content, that would be even more helpful

**Comment by jkmribeiro** [comment]
First of all congrats guys. This has been a long waited feature 👏👏👏
But i agree with @jory3 , not grouping by linked content could not help on most of my cases.
Are there any issue for supporting grouping linked content? Or should we comment here?

**Comment by vilts** [comment]
Yes! Please add the functionality to group by linked content.

**Comment by physx2494** [comment]
I appreciate this commit and agree that adding a group-by content feature could match Airtable's capabilities. The framework may already exist, this sub-feature just needing prioritization.
