### ISSUE TITLE
There seems to be no UI for renaming a project

### ISSUE THREAD

**Issue by ryancwalsh** [nocodb/nocodb#1885]
I'm new to Nocodb, and I find it confusing that projects seem to have names that aren't choosable upfront and instead are randomly-generated names that aren't editable.

And even when I edited the `title` field in `public.nc_projects_v2`, logged out, and logged back in, the original random project names were still used. 

Maybe I'm misunderstanding something, but based on https://github.com/nocodb/nocodb/discussions/838#discussioncomment-2635564 and https://github.com/nocodb/nocodb/discussions/838#discussioncomment-2636614 it seems like I'm not.

**Comment by magadan** [comment]
hello, i cannot a rename a project too. +1

**Comment by ainilili** [comment]
++

**Comment by pauljura** [comment]
@ryancwalsh I did the same as you (`title` change in `public.nc_projects_v2`), then figured it was being cached somewhere, ended up just restarting the docker container, and the project name was updated.
