### ISSUE TITLE
Swager API doc shows endpoints from all projects

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#1899]
XC Swigger UI shows endpoints to all projects on NocoDB instance. All endpoints have 'project_name' in URL as in project from which user came. 

Unauthorized users won't get access, but can see data structure. 
Confusing, but not critical.

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.7**

**Comment by o1lab** [comment]
reproducible
