### ISSUE TITLE
Feature Request: Default to autosave after lose focus on an input field

### ISSUE THREAD

**Issue by lifehome** [nocodb/nocodb#190]
Hello there,

I and a quite a few volunteers are heavily dependent on Google Spreadsheet, tried Airtable also. It is thrilled for us to see this new product getting launched!

It is however, not everyone pays attention to the details, especially the save button in NocoDB in Grid View(I mean, it's so small that I missed it out the first time I tried the demo, lost some testing data like lorem ipsum).

I suggest **making autosave a default behavior** after the user lost focus on an input field, this way people can work and focus on the data, instead of doing clicks and inputs.

Thanks! Stay safe and healthy!

Regards,
Ivan

**Comment by arladmin** [comment]
I second this request.

**Comment by pranavxc** [comment]
Available in `0.10.0`
