### ISSUE TITLE
XC Swager UI fails to load in local docker container

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#1900]
Can't get access to XC Swager UI from locally running docker container with "Failed to load API definition" error. My production-ready environment with same NocoDB image and Postgres database works as expected. 

The one known difference is no SSL. For local testing I run NocoDB with flowing:
```
docker run -d --name nocodb-v90 -p 8080:8080 \
-e TZ=Europe/Moscow \
-e NC_DB="pg://....." \
-e NC_AUTH_JWT_SECRET="................" \
-e NC_INVITE_ONLY_SIGNUP="true" \
--net=host \
nocodb/nocodb:0.90.7
```

<details> 
  <summary>error .png</summary>
   
![image](https://user-images.githubusercontent.com/61871501/165520410-373ac0db-c0d2-4aa7-bf62-e655682e1011.png)

</details>

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.7**

**Comment by o1lab** [comment]
I am unable to reproduce it. Possible to give more details.

**Comment by o1lab** [comment]
This might be occuring when there is a table inserted. And @pranavxc seems to have a fix already in the development branch.

**Comment by RawmanGrey** [comment]
> Can you share the docker log which contains the error and error in the browser network tag?

GET request for '/api/v1/db/meta/projects/project_name/swagger.json' got response with error code 400 and message "Cannot read property 'getRelatedTable' of null"

Btw, cleared all caches and rebuilt container with no effect. 

Confirming that some tables and m2m relations were deleted.
