### ISSUE TITLE
Webhook error in postgres heroku for an user 

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1903]
From @captainkranch

I have the access to the problematic db

<img width="1101" alt="Screenshot 2022-04-27 at 20 27 50" src="https://user-images.githubusercontent.com/5435402/165605300-1b0aeede-9e77-4d43-bd07-c6fde7fa443f.png">

Looks like the problem is in inserting to logs of webhook

**Comment by CaptainKranch** [comment]
Is this still an ongoing issue? I can see some fix-test but the issue is still open

**Comment by wingkwong** [comment]
@CaptainKranch Yes. The issue is still open and changes are under review currently. We only close the issue when the fixes have been released. You may expect it to be fixed in the next release.

**Comment by o1lab** [comment]
@CaptainKranch : you can already test and let us know if its fine on your end using the PR build below

`
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.90.8-pr-1917-20220504-0759
`

**Comment by CaptainKranch** [comment]
It's ok, I'll wait for the release. Thanks guys keep the great work

**Comment by o1lab** [comment]
Please feel free to reopen if it exists.
