### ISSUE TITLE
meta database tables shown in UI

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#1910]
Reported by Discord user Xpressd.

Previously they are not shown in UI. Now they are back.

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.90.7**
```

**Steps To Reproduce**

1. Create a project connecting to `NC_DB`
2. meta tables are not filtered out

**Expected Behavior**

Meta tables are filtered out when getting table list

**Comment by wingkwong** [comment]
Able to reproduce. It exists when meta database is same as data database excluding sqlite case.

![image](https://user-images.githubusercontent.com/35857179/165682521-f99707d8-fcd6-482b-95c9-f3ba7811b50c.png)

**Comment by o1lab** [comment]
Connecting to metadb as external db is not advisable. We've to make this explicit in our docs.
