### ISSUE TITLE
cannot import excel spreadsheets on v0.90.8

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#1915]
***Project info***

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.90.8**

**Steps To Reproduce**

1. Go to the main page in NocoDB admin panel.
2. Click on New Project
3. See? There's no Excel option.

**Expected Behavior**

Before upgrading to the latest major release, we could import Excel files. But now we cannot.

**Comment by wingkwong** [comment]
As the underlying APIs have been changed, we hide the option on purpose for the time being. We're working on it.

**Comment by okaeiz** [comment]
so it there any chance we can import Excel files again in future?

**Comment by wingkwong** [comment]
Yes. It will be available in the future. We're working on it.
