### ISSUE TITLE
Feature Request: Use Postgres JSON type to store attachements

### ISSUE THREAD

**Issue by flobaader** [nocodb/nocodb#193]
Hi,

currently, the images are stored in the Postgres DB as a JSON(B) string in a text field.
We are using Hasura for accessing the attachments and that would require a JSON datatype on the DB level.
Do you have any plans to support that field type for attachments?

(I think that would also leverage all the Postgres optimizations on the JSON type).

Cheers!

**Comment by pranavxc** [comment]
Added `json` datatype support for attachment in `0.10.2`
