### ISSUE TITLE
Can not store phone numbers in international format

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#1937]
**Please enter the following details**

```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux (NAS QNAP TS-251)**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true (one database noco_meta in docker and one database noco_data as external database on same machine**
RootDB: **mysql2**
Database Server: **MariaDB 10.5.8**
PackageVersion: **0.90.8**
```

**Steps To Reproduce**

1. Create a new table
2. Define one column as "PhoneNumber"
3. Enter a phone number like +49 9221 xxxxx
4. You will see this picture:
![PhoneNumber 1](https://user-images.githubusercontent.com/20600342/166101995-14066b6a-69ba-4a28-ab64-3d6be5262e59.jpg)
5. Change the column to "SingleLineText", clear the cell by rightclick and re-enter +49 9221 xxxxx - you still will get an error like here:
![PhoneNumber 2](https://user-images.githubusercontent.com/20600342/166102029-51212fc2-431d-49bf-943a-a6065a6bf898.jpg)
6. If you create a completely new column and from beginning define it as "SingleLineText" without any problem you can enter +49 9221 xxxxx:
![PhoneNumber 3](https://user-images.githubusercontent.com/20600342/166102053-b24f903c-02d5-4cb9-8eb5-6a7e4a97a050.jpg)

It seems once the column was set to "PhoneNumber" even you change it to "SingleLineText" there won´t be any change - at least in my case

**Expected Behavior**

When i set a column to "PhoneNumber" it should accept international format. If it doesn´t and i set column to "SingleLineText" - at least now it should accept any input.

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by wingkwong** [comment]
From what I saw in validator, the regex for `de-DE` is 

```bash
/^((\+49|0)[1|3])([0|5][0-45-9]\d|6([23]|0\d?)|7([0-57-9]|6\d))\d{7,9}$/
```

Visualised version:

![image](https://user-images.githubusercontent.com/35857179/166409026-a2989e95-bd4d-43fe-826b-531dfc2c79af.png)

**Comment by WeT-Klb** [comment]
1. I found out entering the number with space between "+49" and the numer cause a problem.
2. If i enter a cellphone number in international format like +49171xxxxx without space the entry works like it should.
3. If i enter a non-cellphone number like +499221xxxxx no matter with space between or not the error appears, too.
4. So the problem is a) the space and b) the error message is shown only with standard phone numbers (non cell-phone-numbers)
6. Your picture show the numbers of cellphone numbers - after "+49" the "1" is not regular standard phone number (it is like service numbers or cellphone). The regular phone numbers after +49 are 2 to 0.
7. Maybe this make it clear: https://www.wirecloud.de/sites/default/files/redaktion/bilder/telefonnummer.png
8.

**Comment by wingkwong** [comment]
Validation logic resides in third party library. Suggest to create an issue on [validator.js](https://github.com/validatorjs/validator.js) instead.
