### ISSUE TITLE
Table names in postgres get the project id as prefix

### ISSUE THREAD

**Issue by s-h-a-r-d** [nocodb/nocodb#1942]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.8**
```

**Additional Info** 
I started with a 0.8x.x version and have recently upgraded to 0.90.8. 
Tables created with either version always get a project id as a prefix to the table name.

**Expected Behavior**
Apparently this is an expected behaviour only if you are using sqlite, but not expected with postgres.

**Screenshots**
![image](https://user-images.githubusercontent.com/5573972/166155238-5cfefc85-4d21-43e7-9f70-6b5325e3f248.png)

In the screenshot above first three projects have been created with a pre 0.9 version and the last project named `discord project` is created with 0.90.8 version.

**Comment by o1lab** [comment]
We no longer add the prefix and it should not have any issues going forward.

Are you facing any issues ?

**Comment by wingkwong** [comment]
Supplement a bit.

For existing version, creating a project with Sqlite would give something like `nc_xxxx__` to a prefix column, while that for other DBs would be null. The prefix would be prepended to the table name.

Example:

nc_model_v2:
SQLite - Table Name: `nc_c5ps__test`
Others - Table Name: `test`

nc_project_v2:
SQLite - prefix: `null`
Others - prefix: `nc_c5ps__`

**Comment by s-h-a-r-d** [comment]
@o1lab For me the tables created with version 0.90.8 still get the prefix.

**Comment by wingkwong** [comment]
@s-h-a-r-d checked with the team. it's an expected behaviour as adding prefix allows users to create multiple projects (connecting to NC_DB) with the same table names.

**Comment by pranavxc** [comment]
The purpose of `prefix` are following,

- If you are creating a project without connecting external DB(metadb project) then it will use `NC_DB` for the project. So multiple projects can come under the `NC_DB` database to differentiate between projects we are keeping the prefix.
- Without a prefix, we can't create the same tables in multiple projects (or it will map to the same table and it will lead to more issues)
- Meta sync will show tables from another project if we are ignoring prefixes currently, we are relying on prefixes.
