### ISSUE TITLE
Unable to delete table with Self m2m link

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1945]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.8**

- create new table
- add self m2m relation
- delete table
![Screenshot 2022-05-02 at 12 30 54 PM](https://user-images.githubusercontent.com/86527202/166196883-cc7cdebe-ce31-40a8-9e4a-54532ea89acf.png)

- delete relation & delete table
![Screenshot 2022-05-02 at 12 31 12 PM](https://user-images.githubusercontent.com/86527202/166196890-8a2417e0-9475-48d8-a4ab-327edc60e687.png)

**Comment by o1lab** [comment]
First thing : we need to actual column names and table names here
