### ISSUE TITLE
Can't create a new column with PK option

### ISSUE THREAD

**Issue by s-h-a-r-d** [nocodb/nocodb#1947]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.90.8**
```

**Steps To Reproduce**

1. Create a table and fill it with some data.
2. Show the system columns and delete the Id column
3. Now there is no column with PK and nocodb gives this error: `Update & Delete not allowed since the table doesn't have any primary key`
4. Try to create a new column and tick PK option. Like this: 
![image](https://user-images.githubusercontent.com/5573972/166203321-eff94a4d-41bb-428e-9e0d-c0e4961a871a.png)
5. Get this error in the log: `ALTER TABLE "table_name"  ADD "name" character varying NOT NULL DEFAULT placeholder;;alter TABLE "table_name" add constraint "table_name_pkey" PRIMARY KEY("name"); - cannot use column reference in DEFAULT expression`

**Expected Behavior**
A new column is created that becomes the PK.

**Comment by wingkwong** [comment]
The issue is not related to PK option. It's about default value missing single quote when choosing `character varying` type. Therefore, please try `'placeholder'` instead of `placeholder`. 

Will revise eg: later.
