### ISSUE TITLE
🐛 Bug: Nocodb doesn't recognize the PK change made using database queries.

### ISSUE THREAD

**Issue by s-h-a-r-d** [nocodb/nocodb#1948]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.90.8**
```

**Steps To Reproduce**

1. Delete the system Id column that has PK.
2. Using db query, try to make another column PK.
3. First do: `ALTER TABLE table_name DROP CONSTRAINT table_name_pkey`
4. Then: `ALTER TABLE table_name ADD CONSTRAINT table_name_pkey PRIMARY KEY (name);`

**Expected Behavior**
The existing column called `name` gets PK and is synced back to nocodb. But from db tools I can see that the column was successfully made into PK, but nocodb doesn't recognize that.

**Screenshots**
Screenshot from db: 
![image](https://user-images.githubusercontent.com/5573972/166204047-82107ebe-2a86-4222-9095-be9d6b1df221.png)

but nocodb still doesn't recognize the change even after reload & refresh:
![image](https://user-images.githubusercontent.com/5573972/166204118-fb969285-afb0-42e0-911c-d9ca80452788.png)

**Comment by s-h-a-r-d** [comment]
If I delete the project and create it again linking to the same database, the issue gets resolved. Nocodb correctly recognizes the PK column.

**Comment by noseshimself** [comment]
I tried to do that to move the PK field from int to varchar(36) with UUIDs but failed miserably, too. And it seems that the PK has to keep its name; even changing that fails.

**Comment by bird-in-a-tree** [comment]
Just had the same issue:

- Table didn't have a primary key.
- Added with SQL alter.
- Sync Metadata didn't recognise the change.
- To fix had to remove and add back the Data Source. Unfortunately all the views are lost.

**Comment by o1lab** [comment]
The original issue reported is in v old version. What version are you on @bird-in-a-tree ?

**Comment by bird-in-a-tree** [comment]
We have `0.204.0`. I can try to reproduce this issue again if needed.
But I see a PR merged, maybe it's fixed?

**Comment by dstala** [comment]
closing this issue. if you see again, please reopen this thread
