### ISSUE TITLE
Can't change the type of the default column "title"

### ISSUE THREAD

**Issue by s-h-a-r-d** [nocodb/nocodb#1949]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.90.8**
```

**Steps To Reproduce**

1. Create a new table
2. Try to change the automatically created "title" column to any other non-text type.
3. Get this error in the log:
```
ALTER TABLE "test_table" RENAME COLUMN "title" TO "value" ;
ALTER TABLE "test_table" ALTER COLUMN "value" TYPE decimal;
; - column "value" cannot be cast automatically to type numeric
```

**Expected Behavior**
Expected to be able to change the title column name and type to something else. Currently I always have to delete the first column and then create a new column with name/type I want.

**Comment by wingkwong** [comment]
It seems that you have some existing records in the table. If so, then it's not possible to convert from text to numeric like the error indicates, i.e. you cannot represent `abc` in decimal format. You need to clear the values first.

**Comment by s-h-a-r-d** [comment]
Happens with newly created table that at least seems empty.

**Comment by wingkwong** [comment]
You're right. Able to reproduce. It seems something is wrong in Postgres.
