### ISSUE TITLE
Single select issues (reported in discord)

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1955]
Hi, I'm trying out NocoDB and I'm loving it! I have two questions, though: 
- is it possible to reorder records, like drag&drop or some other way? 
- I'm using docker latest image and when adding a new SingleSelect field, the options provided are not saved. But I can edit the field and add them after. Did anyone come across this problem? It seems it didn't happen in a version I tried prior to 0.90

**Comment by mertmit** [comment]
The issue seems reproducible on PostgreSQL and SQLite.
Also there seems to be another SingleSelect related issue on MSSQL.
