### ISSUE TITLE
Formula fields throw an error when referencing fields that start with a number

### ISSUE THREAD

**Issue by shtev21** [nocodb/nocodb#1964]
```
Node: **v16.14.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.84.16**
```

**Steps To Reproduce**

1. In any table, create a new column of any type and input a `Column name` that starts with a number (e.g. `1st`)
2. In the same table, create a new column of the `Formula` type and attempt to reference the column named `1st`
3. You should see an error: `Variable names cannot start with a number (foo) at character bar`
4. Cancel that menu and change the name of the column from `1st` => `First`
5. Edit the formula column and add a reference to the column `First` to see that it resolves successfully
6. Save the changes and close the edit menu
7. Rename the column back from `First` => `1st`
8. Edit the formula column to see that the reference has also changed to match
9. Note that this does not throw any errors unless you try to edit the reference at which point it will once again throw the variable name error.

**Expected Behavior**

Allow for numbers to be used as column names and to be referenced by formulae without issue
OR
Have consistent behaviour by enforcing stricter column naming rules

**Screenshots**

![image](https://user-images.githubusercontent.com/2514805/166605334-ec4e39b9-4b30-4618-a92c-fa357ced80d9.png)
![image](https://user-images.githubusercontent.com/2514805/166605354-1f4ec736-afd1-4e28-ad32-c4efffe3b27a.png)

**Comment by wingkwong** [comment]
preliminary findings:

- `formula` takes the correct column id
- `formula_raw` still takes the old value
