### ISSUE TITLE
Configuring Heroku 1-click install, improve documentation "Cannot GET /" error

### ISSUE THREAD

**Issue by Vadorequest** [nocodb/nocodb#197]
I'm trying to get started with this using Heroku.

![image](https://user-images.githubusercontent.com/3807458/120083896-447f8000-c0cc-11eb-9966-b9b4f940c6df.png)

It created a domain at https://test-nocodb-world.herokuapp.com/ but doesn't show anything besides `Cannot GET /`.

![image](https://user-images.githubusercontent.com/3807458/120083944-94f6dd80-c0cc-11eb-83ca-29e0d09464e3.png)

I'm not familiar with Heroku and didn't immediately understood what I had to do.

It seems I haven't specified the requested [environment variables](https://github.com/nocodb/nocodb#environment-variables), especially `DATABASE_URL`.

![image](https://user-images.githubusercontent.com/3807458/120083975-ca9bc680-c0cc-11eb-8e75-c55a8c4b4aa5.png)

I think it'd be better to:
- Specify all requested environment variables when configuring Heroku (e.g: add `DATABASE_URL=TO DO`) to make it obvious it should be set
- Specify in the https://github.com/nocodb/nocodb#1-click-deploy section to check https://github.com/nocodb/nocodb#environment-variables to configure Heroku (I didn't notice it at first)

**Comment by Vadorequest** [comment]
Well, it seems a default `DATABASE_URL` env var is set, I noticed it created one with value `postgres://mjvcmehagkhmms:e99ddd438e0b58661a8bc64fdb019f93e006ed7c84cae8e4b68d32e6dbfb952b@ec2-63-34-97-163.eu-west-1.compute.amazonaws.com:5432/dauaso3eqvu7il` automatically.

I'm not sure what's missing and why it doesn't work then. Why is there a default DB url defined? 🤔

**Comment by pranavcbalan** [comment]
Dashboard is served under `/dashboard` path, so try `https://test-nocodb-world.herokuapp.com/dashboard`

**Comment by Vadorequest** [comment]
Great! I totally missed that, it should probably be made more obvious in the doc, or maybe adding a redirect from `/` to `/dashboard` would save people some trouble?
