### ISSUE TITLE
Synologoy NAS : the 0.90.10 docker container crash

### ISSUE THREAD

**Issue by xavier-GitHub76** [nocodb/nocodb#1970]
Hello

the 0.90.10 docker container crash

docker run nocodb/nocodb

Digest: sha256:5cee7583b5bbe93d79b4ee83d73160480daa697521f2c94bf06a14d45f3e6187
Status: Downloaded newer image for nocodb/nocodb:latest
Knex: run
$ npm install sqlite3 --save
Error relocating /usr/src/app/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node: fcntl64: symbol not found
Error: Error relocating /usr/src/app/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node: fcntl64: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
App started successfully.
Visit -> http://localhost:8080undefined

Regards

**Comment by o1lab** [comment]
Can you please provide more details - like is it on windows or linux ?

and try `docker run -d -p 8080:8080 nocodb/nocodb`

**Comment by xavier-GitHub76** [comment]
I have this error on my Synology NAS and on my personnel computer (Linux)

I try docker run -d -p 8080:8080 nocodb/nocodb
http://localhost:8080/
=> I have a blanck page with just "Cannot GET /"

**Comment by o1lab** [comment]
We do not have access to NAS you are mentioning. Some of users have used it without a problem with NAS before. See [if this helps](https://github.com/nocodb/nocodb/tree/develop/scripts/setups/TrueNAS).

**Comment by o1lab** [comment]
Please also paste your NAS details (version etc)

**Comment by mertmit** [comment]
This looks like a compatibility issue with SQLite3 on some linux distributions.
Reference: https://issuemode.com/issues/TryGhost/node-sqlite3/73519273

**Comment by petrm** [comment]
I can reproduce this on plain docker on arch linux. Just upgraded to latest tagged image and I am now getting the same error.
Logs:
`nocodb  | Knex: run
nocodb  | $ npm install sqlite3 --save
nocodb  | Error relocating /usr/src/app/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node: fcntl64: symbol not found
nocodb  | Error: Error relocating /usr/src/app/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node: fcntl64: symbol not found
nocodb  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
nocodb  |     at Module.load (internal/modules/cjs/loader.js:863:32)
nocodb  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
nocodb  |     at Module.require (internal/modules/cjs/loader.js:887:19)
nocodb  |     at require (internal/modules/cjs/helpers.js:74:18)
nocodb  |     at Object.<anonymous> (/usr/src/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
nocodb  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
nocodb  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
nocodb  |     at Module.load (internal/modules/cjs/loader.js:863:32)
nocodb  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
nocodb  | App started successfully.
nocodb  | Visit -> http://localhost:8080undefined
nocodb  | Error: Knex: run
nocodb  | $ npm install sqlite3 --save
nocodb  | Error relocating /usr/src/app/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node: fcntl64: symbol not found
nocodb  |     at Client_SQLite3.initializeDriver (/usr/src/app/node_modules/knex/lib/client.js:235:13)
nocodb  |     at Client_SQLite3.Client (/usr/src/app/node_modules/knex/lib/client.js:69:10)
nocodb  |     at new Client_SQLite3 (/usr/src/app/node_modules/knex/lib/dialects/sqlite3/index.js:17:10)
nocodb  |     at Knex (/usr/src/app/node_modules/knex/lib/knex.js:14:28)
nocodb  |     at t.default (/usr/src/app/docker/main.js:2:306847)
nocodb  |     at new v (/usr/src/app/docker/main.js:2:420866)
nocodb  |     at new s (/usr/src/app/docker/main.js:2:1045593)
nocodb  |     at new B (/usr/src/app/docker/main.js:2:2791)
nocodb  |     at Function.init (/usr/src/app/docker/main.js:2:3439)
nocodb  |     at /usr/src/app/docker/main.js:2:459406`

**Comment by o1lab** [comment]
Yes, looks like there has been issue with recent sqlite version. We 're downgrading it and making a release. Please stay tuned.

**Comment by xavier-GitHub76** [comment]
what responsiveness !
👍
