### ISSUE TITLE
Can´t create gallery view or form view

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#1971]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux QNAP-TS251**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false** NC_DB = noco_meta and external database = noco_data on the same machine
RootDB: **mysql2**
PackageVersion: **0.90.10**```
DataBase version: **MariaDB 10.8.5**
**Steps To Reproduce**

1. Go to table "Arztadressen" and create gallery view or form view
2. I get error message 400
3. The weired thing is the other two tables inside the same project and same database can create both views without any problem - only table "Arztadressen" has this problem
4. According to issue #1937 even i enter the phone number like +499221xxxxx after switching to other table and switching back to "Arztadressen" the entry has gone and cell is empty!!! I tried to delete column "Telefon" and "Telefax" and created new columns as SingleLineText - then I can enter and store numbers.
5. If needed i can share SQL-dump of noco_meta and noco_data (not public). 

**Expected Behavior**
Gallery view and form view should be created

**Screenshots**

![Formula](https://user-images.githubusercontent.com/20600342/166736282-a02889d9-172e-43c4-b240-17f508c53c0e.jpg)
![Gallery](https://user-images.githubusercontent.com/20600342/166736295-b90b9b13-d66a-49d2-ab6f-d7dc3aee8791.jpg)

**Comment by WeT-Klb** [comment]
With 0.90.11 this problem with Error 400 is gone but the size of some columns can´t be changed now. When i move separating line and release mouse the size of column change back directly like when i created that column.

**Comment by o1lab** [comment]
In `0.90.11` - only change was we downgraded a package version of sqlite. Thinking how this would be related (?)

Re : release mouse. Which browser is it ?

**Comment by wingkwong** [comment]
I think something was wrong with the columns "Telefon" and "Telefax". After deleting them, you should be able to create those views. It shouldn't relate to `0.90.11`. As I remember, you are using Microsoft Edge right?

**Comment by WeT-Klb** [comment]
Yes, i use Edge. But really with 0.90.10 i deleted those two columns and recreated them as SingleLineText. Then i tried to create gallery view and form view - end both attempts ended with that Error400. The same bahaviour was shown with Chrome portable version.
Then i updated NocoDB to 0.90.11 - and when entering the table i was able to create the views without any problem.
So at least this error has gone. 
In fact the size of column is not that important, but at least wanted to say it.
Somehow if you open more tables the views interact with each other.

**Comment by WeT-Klb** [comment]
And when i only open one table and adjust column width, then open a 2nd table the column width will shrink down. When i close 2nd table the column width in first table will switch back like before opening the 2nd table.

![One table](https://user-images.githubusercontent.com/20600342/166914381-1dbcabb0-cacf-4a62-b65c-29b030f5806d.jpg)
![Two tables](https://user-images.githubusercontent.com/20600342/166914387-9d8a8272-9337-40fd-8eaa-c6390821a7b6.jpg)

**Comment by duc-ctm-jacobins-digital** [comment]
I just tested. The issue will appear if we have a field LinkToAnotherRecord ManyToMany. After I delete the field, creating form works normally

**Comment by dstala** [comment]
@WeT-Klb If issue persists with latest release, do let us know. closing this, as this pertains to relatively older release of NocoDB
