### ISSUE TITLE
DateTime value not saved 

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#1978]
**Steps To Reproduce**

1. Create a table with DateTime value
2. Input something
3. Refresh the page
4. The value is gone

**Expected Behavior**

DateTime value is saved

**Info**

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.90.11**
```

**Comment by mertmit** [comment]
@wingkwong I can't reproduce this.
I tried every db, tried changing RootDB between mysql/sqlite had no luck reproducing. This might be platform/node dependent.

**Info**
```
Node: **v14.18.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.90.11**
```

**Comment by wingkwong** [comment]
@mertmit Right. I recreated my meta db and it works fine now.
