### ISSUE TITLE
Bug: SingleSelect does not render dropdown

### ISSUE THREAD

**Issue by bykof** [nocodb/nocodb#198]
Hey folks, first I want to thank you for this piece of gold!

I found an issue with `SingleSelect` fields. 
If I create a `SingleSelect` field and want to edit it, it doesn't show me a dropdown or a selection. 
It only shows me a `Cancel` and `Save` button. 

![Screenshot 2021-05-30 at 10 48 16](https://user-images.githubusercontent.com/5264141/120098230-edfa5c00-c134-11eb-94e8-2570a1fb85fd.png)
![Screenshot 2021-05-30 at 10 50 06](https://user-images.githubusercontent.com/5264141/120098237-f81c5a80-c134-11eb-89ca-cb9ef9db0766.png)

I am using postgres, but this also doesn't work with sqlite.

**Comment by sethii** [comment]
Hey, I think it is the same with MultiSelect.

**Comment by bykof** [comment]
> Hey, I think it is the same with MultiSelect.

Yup, I tested it right now. It's exactly the same behaviour

**Comment by bhanuc** [comment]
Also affected by this.  Also was expecting a date selector for the date type, it is not showing currently.

**Comment by nsakibp** [comment]
Any update on this please?
