### ISSUE TITLE
Multiselect color is not shown, when more than 10 slection options are given

### ISSUE THREAD

**Issue by maxehrhardt** [nocodb/nocodb#2002]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.90.11**
```

**Steps To Reproduce**

1. Add a multi select column
2. Add more then 10 selection options
3. If option 11 or above is selected the tag in the DB is shown without background

**Expected Behavior**

It seems like the color for the multi select options is cycling with 10 color options. But 

**Screenshots**

That is how the tag is showing up
![image](https://user-images.githubusercontent.com/18333348/167367484-fb63d75d-a9b6-4d8f-b0d1-d9e1d7f3a6aa.png)

When clicked the tag actually shows the right color:
![image](https://user-images.githubusercontent.com/18333348/167371389-98676c05-f31f-46fd-9724-400180aef801.png)

**Comment by wingkwong** [comment]
This is what I see in `0.90.11`.

![image](https://user-images.githubusercontent.com/35857179/168011203-bc47cd89-7bc7-4399-9f53-d4f8b52f017f.png)
![image](https://user-images.githubusercontent.com/35857179/168011239-0951af45-3225-47b7-bc6a-c4195bd7724c.png)

**Comment by o1lab** [comment]
Good to close given the discussion. Feel free to reopen if the issue exist in latest release
