### ISSUE TITLE
Can't import XLSX -   /dashboard/?q=sqlOp_projectCreateByWebWithXCDB 404

### ISSUE THREAD

**Issue by kuchel77** [nocodb/nocodb#2005]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.11**
```

**Steps To Reproduce**
Drag Excel file into new project. Doesn't matter if it has formatting or not. 

It doesn't get the column names from the first row. But if you fill them separately, it then comes up with the following error in the logs

POST /dashboard/?q=sqlOp_projectCreateByWebWithXCDB 404 150 - 1.313 ms,
POST /dashboard/?q=sqlOp_projectCreateByWebWithXCDB 404 150 - 1.053 ms

It has the other data overall but it doesn't get imported.

**Expected Behavior**

The data gets imported.

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by wingkwong** [comment]
Excel Import has been disabled for a while and will be available in the next release. In `0.90.11`, you shouldn't able to do that. May I know how you imported that?

![image](https://user-images.githubusercontent.com/35857179/167540152-f7e63067-b8c5-4f0d-87cf-944a412ff991.png)
![image](https://user-images.githubusercontent.com/35857179/167540172-e49a9c01-806b-4ff7-90c2-9a90a273feeb.png)

**Comment by kuchel77** [comment]
Drag and drop the file below the New Project.

**Comment by wingkwong** [comment]
Mind to take a screenshot or video? I couldn't see if drag-and-drop area.

**Comment by kuchel77** [comment]
https://user-images.githubusercontent.com/52343790/167562451-c6224075-07d4-44e6-b097-a8778e4141cc.mp4

**Comment by wingkwong** [comment]
Mine will just download the file. Anyway it'll be available in New Project menu in next release. Please stay tuned.
