### ISSUE TITLE
[Feature] Offer random UUID generation as alternative for the mandatory column ID

### ISSUE THREAD

**Issue by noseshimself** [nocodb/nocodb#2008]
**Need for this feature**
In case you want to use objects for other purposes you need a globally unique ID for them. As you can't get rid of the auto-incremente row IDs that are generated anyway it would be a good idea to have a choice

**Is your feature request related to a problem? Please describe.**
I need the databases to be using unique keys as primary key so it would be helpful if I could select them as mandatory ID column if I whether I want thos integer IDs or something like varchar(35) not NULL default ( UUID()).

It's even worse that I have to use ALTER TABLE on the database because requesting default values of UUID() will just succeed in putting the string "UUID()" into the fields.

**Describe the solution you'd like**
Implement the requested feature from https://github.com/nocodb/nocodb/issues/2007 (UUID as column type) and use them as primary key.

**Describe alternatives you've considered**
Adding the UUID field by hand using a database tool, synchronizing it, marking it as primary key and then delete the column. Sure, works but I still don't solve the packing and unpacking problem (varchar(35) instead of 16 bytes.

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/2007
