### ISSUE TITLE
PostgreSQL : migration from 0084002 to 0090000 failed

### ISSUE THREAD

**Issue by cacmar** [nocodb/nocodb#2012]
Hello,
I tried to update my NocoDB using PostgreSQL from 0084002 to 0090000 and I had this message.

> ┌ Migration from 0084002 to 0090000 failed ────────────────────────────────────┐│ ││ Error ││ ----- ││ error: insert into "nc_form_view_v2" ("banner_image_url", "base_id", ││ "created_at", "email", "fk_view_id", "heading", "logo_url", ││ "project_id", "redirect_after_secs", "redirect_url", "show_blank_form", ││ "subheading", "submit_another_form", "success_msg", "updated_at") values ││ (DEFAULT, $1, CURRENT_TIMESTAMP, $2, $3, $4, DEFAULT, $5, DEFAULT, ││ DEFAULT, DEFAULT, $6, DEFAULT, $7, CURRENT_TIMESTAMP) - value too long ││ for type character varying(255) ││ at Parser.parseErrorMessage ││ (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98) ││ at Parser.handlePacket ││ (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29) ││ at Parser.parse ││ (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38) ││ at Socket.<anonymous> ││ (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42) ││ at Socket.emit (events.js:314:20) ││ at Socket.EventEmitter.emit (domain.js:483:12) ││ at addChunk (_stream_readable.js:297:12) ││ at readableAddChunk (_stream_readable.js:272:9) ││ at Socket.Readable.push (_stream_readable.js:213:10) ││ at TCP.onStreamRead (internal/stream_base_commons.js:188:23) ││ ││ ││ Please raise an issue in our github by using following link : ││ [https://github.com/nocodb/nocodb/issues/new?labels=Type: Bug&templat](https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat) ││ e=bug_[report.md](http://report.md/) ││ ││ Or contact us in our Discord community by following link : ││ https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong ) ││ │└──────────────────────────────────────────────────────────────────────────────┘
error: insert into "nc_form_view_v2" ("banner_image_url", "base_id", "created_at", "email", "fk_view_id", "heading", "logo_url", "project_id", "redirect_after_secs", "redirect_url", "show_blank_form", "subheading", "submit_another_form", "success_msg", "updated_at") values (DEFAULT, $1, CURRENT_TIMESTAMP, $2, $3, $4, DEFAULT, $5, DEFAULT, DEFAULT, DEFAULT, $6, DEFAULT, $7, CURRENT_TIMESTAMP) - value too long for type character varying(255)
at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
at Socket.emit (events.js:314:20)
at Socket.EventEmitter.emit (domain.js:483:12)
at addChunk (_stream_readable.js:297:12)
at readableAddChunk (_stream_readable.js:272:9)
at Socket.Readable.push (_stream_readable.js:213:10)
at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
length: 99,
severity: 'ERROR',
code: '22001',
detail: undefined,
hint: undefined,
position: undefined,
internalPosition: undefined,
internalQuery: undefined,
where: undefined,
schema: undefined,
table: undefined,
column: undefined,
dataType: undefined,
constraint: undefined,
file: 'varchar.c',
line: '632',
routine: 'varchar'

Do you have any information ?

Thanks a lot

**Comment by o1lab** [comment]
We will look into this. Looks like, for one of the field.. value is too big. If you go back to 0.84.15 - you will still manage to use project. Will have a fix soon.

**Comment by cacmar** [comment]
I rolled back to the 0.84.15.
Thanks for the tips

**Comment by o1lab** [comment]
Good to close now. Fixed in subsequent releases since may.
