### ISSUE TITLE
docker 0.9.16 - postgres 11 -  foreign-key fields must display the name (title) and not the ID

### ISSUE THREAD

**Issue by ferdiga** [nocodb/nocodb#202]
After creating a foreign-key field it is necessary to enter the ID of the foreign record 

It should be possible to select / search in the foreign key records and the name of the foreign key must be displayed

I also would like to see a foreign key constraint in the database

**Comment by o1lab** [comment]
We are creating foreign key constraint - that is fine.

**Comment by ferdiga** [comment]
well I can't see it then.
<img width="418" alt="20210601 161844 bin — openerp@service: ~ — ssh ◂ ssh_rs — 130×24" src="https://user-images.githubusercontent.com/6248560/120339029-0ca75100-c2f5-11eb-92b4-f583202bee65.png">
From should have a foreign key constraint to account.id

**Comment by o1lab** [comment]
This has been fixed in previous releases.

Foreign key id shows the title (primary value) instead of ID
