### ISSUE TITLE
docker 0.9.16 - postgres 11 - create project upper lower case issue

### ISSUE THREAD

**Issue by ferdiga** [nocodb/nocodb#203]
Creating the project

<img width="330" alt="20210530 175723 Create Project | XC" src="https://user-images.githubusercontent.com/6248560/120111058-a5609400-c170-11eb-892b-aa6fc73c8d41.png">

creates the following db schema
<img width="83" alt="20210530 175916 bin — openerp@service: ~ — ssh ◂ ssh_rs — 183×24" src="https://user-images.githubusercontent.com/6248560/120111094-d80a8c80-c170-11eb-852f-9e8b883093e6.png">

note the lower case 

the schema is not accessible for further operations

<img width="212" alt="20210530 180129 NocoDB" src="https://user-images.githubusercontent.com/6248560/120111144-13a55680-c171-11eb-90bd-8dac18c432c5.png">

can not start or restart the project

currently only works the database name is lower case

**Comment by pranavxc** [comment]
Fixed in `nc-help@0.1.102`
