### ISSUE TITLE
Can´t create form view

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#2031]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux (QNAP TS-251**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **noco_meta in docker; noco_data as external data base**
RootDB: **mysql2**
PackageVersion: **0.90.11**
**Steps To Reproduce**

1. Click to add form view, give it a name and save it (Picture 1)
2. See error 400 (Picture 2)
3. Close table and open again - form view is suddenly there!!! (Picture 3)
4. Move all items into position and press "Übertragen" (Transfer) (Picture 4)
5. Close form view and open again
6. The chosen items are back on the left side and are not stored in the created view. (Picture 6)

**Expected Behavior**

Form view creation should work without problem

**Screenshots**
![Formular 1](https://user-images.githubusercontent.com/20600342/168149238-a94d5f00-e579-4368-adf8-aed6ef3541f9.jpg)
![Formular 2](https://user-images.githubusercontent.com/20600342/168149244-917f1570-4d8c-4ded-a82f-0de46ae9dc06.jpg)
![Formular 3](https://user-images.githubusercontent.com/20600342/168149252-d1935279-a8d0-447a-b45b-75209e626b33.jpg)
![Formular 4](https://user-images.githubusercontent.com/20600342/168150137-2edc6610-a5b6-4f48-b0e7-c54a9f421e3b.jpg)
![Formular 5](https://user-images.githubusercontent.com/20600342/168150959-36091c0c-e107-4d61-a9e6-9b7831309b2f.jpg)
![Formular 6](https://user-images.githubusercontent.com/20600342/168150964-9648a4fb-b9db-4a5d-b1fd-3f1ed6653048.jpg)

**Comment by WeT-Klb** [comment]
I sent a dump in Discord.

**Comment by JamesKai** [comment]
I have also encountered the exact issue regardless the database, schema or whether using docker or not. After dragging those properties into the form, whenever I switch to another view and switch back, those just added properties in the form will be gone. However, if I kill the server or the stop docker container and get it running up again, I can see those added properties in the form as expected.

**Comment by o1lab** [comment]
@JamesKai : please raise an issue with the steps to reproduce. We're happy to look into it.

**Comment by WeT-Klb** [comment]
One weired thing: I have three tables in project.
The problem only appear in first table "Arztadressen", in table "Impfbuch_Mian" and "Impfbuch Werner" the creation of form view works perfectly!!!

**Comment by dstala** [comment]
@WeT-Klb Closing this issue as its related to older release. Please connect with us on discord if you still observe any issue with form view 

@dstala 
https://discord.gg/5RgZmkW
