### ISSUE TITLE
[UIDT-improvements] Migration considerations & other items

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2037]
Do not prune existing data in any scenario.
- [ ] During migration, if the rating field has a value > 10, convert datatype to number.
- [ ] If rating field had decimal values, convert datatype from rating to number/ decimal appropriately
- [ ] In all other cases - retain rating field and set the max value to 10

General
- [ ] If user reconfigures from higher max value to lower value- modify existing higher value contents in database records according to new max configured
- [ ] Gallery view- show configured icons instead of numbers

**Comment by o1lab** [comment]
Will be closing this for now since we got past the migration.
