### ISSUE TITLE
[Formula] Validation missing in one of scenarios; additional records created

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2046]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.90.11**

- create formula field (<=3), save
- add records
- update the formula field to SQRT(4), save
- additional duplicated records observed

https://user-images.githubusercontent.com/86527202/168439559-6b8fc577-e0f2-40a6-b0f6-6c16b708930c.mov

**Comment by wingkwong** [comment]
Closing as formula validation has been enhanced in [0.91.1](https://github.com/nocodb/nocodb/releases/tag/0.91.1).

![image](https://user-images.githubusercontent.com/35857179/171997639-043e9c6b-40ec-422b-b9a2-80c97fdd8ced.png)
