### ISSUE TITLE
Delete table error (with relational column)

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2047]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.11**

- create city <mm> country relation
- delete one of the link columns (link column on other side persists)
- try to delete other table, or link column - fails

https://user-images.githubusercontent.com/86527202/168442951-1ee75ba2-7dff-41e1-abab-347e4513246f.mov

**Comment by dstala** [comment]
```
GET /api/v1/db/data/noco/x/Country/views/Country?limit=25&offset=0&where= 304 - - 9.575 ms
TypeError: Cannot read property 'id' of undefined
    at Function.getByIdOrName (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco-models/Model.ts:250:60)
    at exports.default (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/extractProjectIdAndAuthenticate.ts:34:21)
GET /api/v1/db/meta/tables/md_5rjt7ans0dq7wy 400 24 - 32.921 ms
columnDelete :: TypeError: Cannot read property 'fk_model_id' of null
    at columnDelete (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/api/columnApis.ts:654:16)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:6:14
DELETE /api/v1/db/meta/columns/cl_v1e8fg3x87dugy 400 52 - 33.914 ms

```

**Comment by alexjj** [comment]
Did you figure out a solution or stuck? I tried deleting the whole table but can't due to the existing linked column.

**Comment by elvus** [comment]
The bug was solved in the last version!!

**Comment by o1lab** [comment]
Thank you for confirming.
