### ISSUE TITLE
[i18n] Language Improve - <zh-CN>

### ISSUE THREAD

**Issue by Tim-Paik** [nocodb/nocodb#2049]
# i18n improvement request

**Please enter the following details**

1. Select applicalbe
- [ ] **New language support request**
- [x] **Existing language translation corrections request** 
Verify if language support already exists in the NocoDB i18n master spreadsheet [here](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172)

2. Associated language code (pick from [here](https://developers.google.com/admin-sdk/directory/v1/languages)): **zh-CN**

3. Google spreadsheet
- Procedure to share google spreadsheet can be found [here](https://support.google.com/docs/answer/2494822?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cshare-a-file-publicly) 
  - When requested, select public sharable link. 
- Alternatively, you can download & attach a spreadsheet here along with the issue as well. 
- [ ] **Attached**
- [x] **Shared link**: https://docs.google.com/spreadsheets/d/1PDkNSrh6q7M_WP8HnXAOZTGg62oJMueDm440kB4Kzyc/edit?usp=sharing

4. Summary of the changes made
 - zh_CN column of table i18n
 - zh column of table [v1.0] banner-images

5. Any specific message to be conveyed to moderators?
- Help us simplify the process if you find something hard about it

**Comment by wingkwong** [comment]
Mind to highlight which cells you've modified?

**Comment by dstala** [comment]
@wingkwong

**Comment by dstala** [comment]
[1/2 Completed] https://github.com/nocodb/nocodb/commit/e3b6839e462b36ef488ca789eab778f319c22f56

**Comment by dstala** [comment]
[2/2 Completed] https://github.com/nocodb/nocodb/commit/046d3b7fbd78b696d5307b8112c2951b6f87ed39
