### ISSUE TITLE
Bug: Rename Table does not work

### ISSUE THREAD

**Issue by bykof** [nocodb/nocodb#205]
Hello folks, trying to rename a table fails.

Following POST request to address: `http://localhost:8080/dashboard/?q=sqlOpPlus_tableRename`: 
```
{"api":"tableRename","env":"dev","dbAlias":"db","project_id":"crm_cUWK","args":{"tn":"Company","tn_old":"Customer"},"sqlOpPlus":true}
```

Getting following response: 
```
{"msg":"alter table \"Customer\" rename to \"Company\" - relation \"Customer\" does not exist"}
```

**Comment by o1lab** [comment]
Analysis : Renaming issue is happening when we are creating a project in root database (NC_DB or DATABASE_URL).

**Comment by ajjaic** [comment]
> Analysis : Renaming issue is happening when we are creating a project in root database (NC_DB or DATABASE_URL).

can you elaborate. ? when you say root database, are you talking about the first database that is created on a new instance of nocodb?

**Comment by bykof** [comment]
I am using following startup configuration: 
```
docker run -p 8080:8080 -d -e NC_DB="pg://host.docker.internal:5432?u=noco&d=noco" nocodb/nocodb:latest
```

**Comment by o1lab** [comment]
@bykof : thank you. 

We'd a look at the issue, this would need more time. We support aliases/inflection internally hence.

**Comment by wingkwong** [comment]
Subscribed this thread as I'm encountering the exact same issue.

**Comment by bmscmoreira** [comment]
Facing same issue (error renaming table) using latest docker version, pushed 6 hours ago.
As for deleting tables, as @wingkwong reported, I'm facing a different issue: I get a message of the table being correctly deleted, but the table only disappears from the "tables" list on the sidebar after manually refreshing the page.

**Comment by pranavxc** [comment]
> Facing same issue (error renaming table) using latest docker version, pushed 6 hours ago.
> As for deleting tables, as @wingkwong reported, I'm facing a different issue: I get a message of the table being correctly deleted, but the table only disappears from the "tables" list on the sidebar after manually refreshing the page.
> 
> EDIT: As with #276 I now don't experience the issue (i.e. the table does disappear without refreshing the page). I'll report back if I figure out how to replicate the issue.

Is there any error in the browser console after deleting the table ?

**Comment by wingkwong** [comment]
@pranavxc 

Supposing I have a table called ``Test`` and I want to rename it to ``Test2``. I got ``500 Internal Server Error`` when calling ``/dashboard?q=sqlOpPlus_tableRename`` with the following error:

```
alter table \"Test\" rename to \"Test2\" - relation \"Test\" does not exist
```

I've also tried the following cases 

1. Create a table called ``test`` and rename to ``test2`` ==> OK
2. Create a table called ``test``, rename to ``test_test`` (OK but it becomes ``testTest``), rename to ``test`` ==> Failed
3. Create a table called ``foo_foo``, rename to ``foo`` (OK but it becomes ``Foo``), rename to ``foo_foo`` ==> Failed
2. Create a table, create a M2M column, and rename ==> Failed
3. Create a table, create a M2M column, delete a M2M column, and rename ==> Failed
4. Create a table, create a M2M column, recreate metadata for that table, and renamed ==> Failed

The menu displays ``Foo`` but it shows ``foo`` when hovering. I guess somehow it reads the wrong one (case sensitive) so that it says the relation does not exist.

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.11.6**

**Comment by bmscmoreira** [comment]
> > Facing same issue (error renaming table) using latest docker version, pushed 6 hours ago.
> > As for deleting tables, as @wingkwong reported, I'm facing a different issue: I get a message of the table being correctly deleted, but the table only disappears from the "tables" list on the sidebar after manually refreshing the page.
> > EDIT: As with #276 I now don't experience the issue (i.e. the table does disappear without refreshing the page). I'll report back if I figure out how to replicate the issue.
> 
> Is there any error in the browser console after deleting the table?

Tested the following:
1) created new table;
2) deleted the table using the icon on the top right corner

Observed:
1) the table did not disappear from the sidebar on the left;
2) the browser console shows the following:

`TypeError: undefined has no properties
    NuxtJS 69
        t
        m
        _invoke
        e
        r
        l
        o
        o
        loadTablesFromParentTreeNode
        S
        dispatch
        dispatch
        r
        n
        m
        _invoke
        e
        r
        l
        promise callback*r
        l
        promise callback*r
        l
        promise callback*r
        l
        promise callback*r
        l
        o
        o
        deleteTable
        click
        ee
        n
        ee
        $emit
        click
        ee
        n
        _wrapper
        Rr
        ge
        Dr
        x
        v
        ko
        _update
        r
        get
        Cn
        mount
        $mount
        init
        v
        v
        _
        v
        _
        v
        ko
        _update
        r
        get
        Cn
        mount
        $mount
        init
        v
        v
        _
`

I then refreshed the page, and the table DID disappear.

Using latest version from docker hub, pulled a few minutes ago, in Firefox 90.0.2 64bit for macOS.

**Comment by pranavcbalan** [comment]
Rename table have some issue, 

> @pranavxc
> 
> Supposing I have a table called `Test` and I want to rename it to `Test2`. I got `500 Internal Server Error` when calling `/dashboard?q=sqlOpPlus_tableRename` with the following error:
> 
> ```
> alter table \"Test\" rename to \"Test2\" - relation \"Test\" does not exist
> ```
> 
> I've also tried the following cases
> 
> 1. Create a table called `test` and rename to `test2` ==> OK
> 2. Create a table called `test`, rename to `test_test` (OK but it becomes `testTest`), rename to `test` ==> Failed
> 3. Create a table called `foo_foo`, rename to `foo` (OK but it becomes `Foo`), rename to `foo_foo` ==> Failed
> 4. Create a table, create a M2M column, and rename ==> Failed
> 5. Create a table, create a M2M column, delete a M2M column, and rename ==> Failed
> 6. Create a table, create a M2M column, recreate metadata for that table, and renamed ==> Failed
> 
> The menu displays `Foo` but it shows `foo` when hovering. I guess somehow it reads the wrong one (case sensitive) so that it says the relation does not exist.
> 
> Node: **v12.22.1**
> Arch: **x64**
> Platform: **linux**
> Docker: **true**
> Database: **pg**
> ProjectOnRootDB: **false**
> RootDB: **sqlite3**
> PackageVersion: **0.11.6**

Ya our rename implementation have some issue, we are still working on it.  The displayed value may be table name alias(`Foo` - by deafult we are applying `camelize` - it can change while creating project under advanced menu) and on hovering it shows the actual table name(`foo`)

**Comment by pranavcbalan** [comment]
> > > Facing same issue (error renaming table) using latest docker version, pushed 6 hours ago.
> > > As for deleting tables, as @wingkwong reported, I'm facing a different issue: I get a message of the table being correctly deleted, but the table only disappears from the "tables" list on the sidebar after manually refreshing the page.
> > > EDIT: As with #276 I now don't experience the issue (i.e. the table does disappear without refreshing the page). I'll report back if I figure out how to replicate the issue.
> > 
> > 
> > Is there any error in the browser console after deleting the table?
> 
> Tested the following:
> 
> 1. created new table;
> 2. deleted the table using the icon on the top right corner
> 
> Observed:
> 
> 1. the table did not disappear from the sidebar on the left;
> 2. the browser console shows the following:
> 
> `TypeError: undefined has no properties NuxtJS 69 t m _invoke e r l o o loadTablesFromParentTreeNode S dispatch dispatch r n m _invoke e r l promise callback*r l promise callback*r l promise callback*r l promise callback*r l o o deleteTable click ee n ee $emit click ee n _wrapper Rr ge Dr x v ko _update r get Cn mount $mount init v v _ v _ v ko _update r get Cn mount $mount init v v _ `
> 
> I then refreshed the page, and the table DID disappear.
> 
> Using latest version from docker hub, pulled a few minutes ago, in Firefox 90.0.2 64bit for macOS.

Thanks for sharing the details, we will look into it 👍

**Comment by bensdb01** [comment]
Errors renaming Tables here too

**Comment by Charlie-Rem** [comment]
I cannot rename a table neither.
When I try to do it, after pressing the submit button, I get the following error message, in red:

Table rename "." failed

**Comment by Charlie-Rem** [comment]
Exactly the same issue with version 0.81.1, tested on the 4th of November 2021 (I did exactly the same as in the video above)

**Comment by pranavxc** [comment]
Fixed in `v0.83.0`

**Comment by Charlie-Rem** [comment]
Thank you very much!

**Comment by bmscmoreira** [comment]
Thanks!

Bruno Moreira
