### ISSUE TITLE
Feature : Let's bundle noco in a single executable for all platforms

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2081]
We can use [pkg](https://www.npmjs.com/package/pkg) on [nocodb-seed](https://github.com/nocodb/nocodb-seed)

On release - we would need
- [ ] A github action to pkg
  - [ ] nocodb - this will be while releasing
  - [ ] nocodb-daily-seed 
- [ ] Then host it (probably we can keep it in github?).
- [ ] CURL command documentation
  - [ ] Readme 
  - [ ] Docs

**Comment by o1lab** [comment]
<img width="712" alt="Screenshot 2022-05-19 at 20 47 26" src="https://user-images.githubusercontent.com/5435402/169390670-57c22f62-7348-40c6-a4cc-b5aae63771e4.png">

Seeing this error.

**Comment by wingkwong** [comment]
> Mounting of noco's middleware never returns. I suspected it might be has to do with sqlite - so gave NC_DB variable. And weirdly, I no longer see the above error (mount still never returns though). Probably the earlier err was due to listening on http before mounting nocodb (this part I [fixed](https://github.com/nocodb/nocodb-seed/commit/97bb0ee6e4b4d307f0d65132a57ede90d08336ad))

Not related. You need to put `node_modules/**/*` to `pkg.assets`.

![image](https://user-images.githubusercontent.com/35857179/169633798-8aea9720-49c6-49da-9e38-c7dc747acb65.png)

**Comment by o1lab** [comment]
A place to host all the builds should be something like [this](https://dl.min.io/server/minio/).

**Comment by o1lab** [comment]
@wingkwong : Looks like its possible to logo and title - pls see [here](https://github.com/vercel/pkg/issues/1297)

**Comment by wingkwong** [comment]
Covered in [0.92.0](https://github.com/nocodb/nocodb/releases/tag/0.92.0)
