### ISSUE TITLE
Problem with CORS - Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by melondev7** [nocodb/nocodb#2089]
Node: **v16.13.2**
Arch: **x64**
Platform: **win32**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.90.11**

-  hi guys ! I'm trying to get data from NocoDB but i can't because the call is blocked by CORS policy. I can get data from Postman but not from my React project. Thanks ✌️
![cors](https://user-images.githubusercontent.com/105916275/169523872-8970f318-fc4e-40c1-ae1b-deb91bd1de91.png)

**Comment by o1lab** [comment]
Looks like you are using it from a nodejs project. So you can setup cors easily.

**Comment by melondev7** [comment]
You know I can fix it ?

**Comment by melondev7** [comment]
You know I can fix it ?

**Comment by melondev7** [comment]
You know I can fix it ?

**Comment by o1lab** [comment]
https://expressjs.com/en/resources/middleware/cors.html
