### ISSUE TITLE
[import] post import, data disappears from table on deleting column

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2097]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.11**

- import shrO9PBPyPLTqalcr in ludicrous mode
- go to table 2, delete last column
- data from entire table disappears

**Comment by wingkwong** [comment]
https://github.com/nocodb/nocodb/commit/56041e4b7271eda0151d5a5931cc644efef803b7 in `feat/at-import`
