### ISSUE TITLE
Bug: when searching a query, `can't access property "dt", col is undefined`. Even though the field is selected correctly

### ISSUE THREAD

**Issue by baptisteArno** [nocodb/nocodb#210]
I'm managing my database with Hasura.

I connected it to Nocodb and whenever I'm trying to make a search key of any field in one of my table,
![CleanShot 2021-05-31 at 15 57 28](https://user-images.githubusercontent.com/16015833/120204304-f338d300-c228-11eb-9a2f-5492d781eddd.png)
 I get the following JS error in the console:
```
TypeError: can't access property "dt", col is undefined
```

**Comment by o1lab** [comment]
You can try selecting the field by dropping down the search icon. See if that helps.

Currently, the default search happens on first column. But I will make this as a feature request

**Comment by baptisteArno** [comment]
Thank you for the quick reply, I didn't mention it but I did select "Name" from the dropdown

**Comment by baptisteArno** [comment]
Also, it seems that it crashes the view, I can expand a record and I can't change the page.

**Comment by baptisteArno** [comment]
Hi, sorry we couldn't understand each other. I'm saying that the bug **is** appearing **even though I'm selecting the correct field from the dropdown**!

**Comment by o1lab** [comment]
Sorry, typo with issue fix in commit

**Comment by pranavxc** [comment]
It has been fixed in latest version
