### ISSUE TITLE
[formula] edit formula complains for $ 

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2100]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.11**

- create formula CONCAT({Title}, " ", {Title})
- try & edit formula

![Screenshot 2022-05-21 at 3 35 05 PM](https://user-images.githubusercontent.com/86527202/169646605-37b63dd6-f9ad-4af2-9977-2d5d9cbbb8b3.png)

**Comment by dstala** [comment]
Additional improvement suggestions
- prefix column datatype icon to the column name
- display formula without `$` in the edit window
- on typing `{`, narrow down search results to only column names
- accept 'enter key' as trigger to save. tried entering formula 8*8*8 & then enter - didn't save formula

**Comment by wingkwong** [comment]
I don't see $ is added. Besides, PR 2090 includes quite a lot of changes. The 3rd & 4th points are aware and I plan to fix them afterwards.

![image](https://user-images.githubusercontent.com/35857179/169652691-85753425-3dd0-4082-90c2-310b30c03258.png)

**Comment by wingkwong** [comment]
For the issue, it is due to outdated sdk. `npm i && npm run build` on sdk and `npm i` again on frontend and backend .

Other enhancement items will be moved to to-do list and will be handled in the future.
