### ISSUE TITLE
🐛 Feature: [web hook] update to LTAR doesn't trigger 'on-update' webhook

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2104]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.11**

- add Rating field to table
- add on-update discord webhook
- update Rating field/ LTAR field

**Comment by o1lab** [comment]
* Rating we should fix.
* LTAR can be looked later.
