### ISSUE TITLE
[decimal] datatype decimal accepts non-numeric characters

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2106]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.11**

- should accept only numbers & a `.`

![Screenshot 2022-05-21 at 9 27 45 PM](https://user-images.githubusercontent.com/86527202/169659699-3e68d391-ffe3-4f2e-b243-f9e168ddb926.png)

**Comment by GurukiranMH** [comment]
Assign this issue to me

**Comment by wingkwong** [comment]
@GurukiranMH 

1. Always pull the latest code first before you start working
2. Adding the following line in getAbstractType() should work - please help verify (remember to build sdk)

<img width="420" alt="image" src="https://user-images.githubusercontent.com/35857179/171987415-de2a7199-9b2a-4252-8d1c-db0649ba007e.png">
