### ISSUE TITLE
Error: Cannot find module 'jsonfile'

### ISSUE THREAD

**Issue by vjpr** [nocodb/nocodb#212]
When running pnpm.

```
Error: Cannot find module 'jsonfile'
Require stack:
- /xxx/node_modules/.pnpm/nc-help@0.1.100_sqlite3@5.0.0/node_modules/nc-help/dist/main/main.js
- /xxx/node_modules/.pnpm/nocodb@0.9.17/node_modules/nocodb/dist/bundle.js
```

You need to add `jsonfile` as a dep to `nc-help`. Where is `nc-help` by the way?

---

`axios` is also missing.

And `mkdirp` from `nocodb`.

**Comment by pranavxc** [comment]
Added missing dependencies in `nc-help@0.1.101`

**Comment by o1lab** [comment]
As mentioned in discord, we will be moving this package form gitlab. There are a lot of experimental things in it.

**Comment by o1lab** [comment]
jsonfile issues is fixed now. nc help package is tracked in #336

**Comment by rocmen** [comment]
trying to install langflow get error cannot find module package JSON I have tried every thing youtube videos say to do won't work
