### ISSUE TITLE
Creating a new project will imort all tables of existing projects

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#2123]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux (Qnap-TS251)**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **noco_meta in Docker, noco_data as external database**
RootDB: **mysql2**
PackageVersion: **0.90.11**
MariaDB: **10.5.8**

**Steps To Reproduce**

In Docker i set link to database noco_meta, the projects are created by clicking to create in external database named noco_data.
Both databases are inside the same MariaDB on the same machine (Qnap-NAS TS-251).

1. Create a new project (with external database)
2. Sign in to new project
3. See error: All tables of existing projects will appear in new project

**Expected Behavior**

A new project should be created without any tables

**Screenshots**

https://user-images.githubusercontent.com/20600342/169792419-cc4143af-5817-408d-83e7-fae6e59c9252.mp4

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by wingkwong** [comment]
This is an expected behaviour - you create a project by connecting to an external database so that you will see those tables in that connected database.
