### ISSUE TITLE
Bug: Nocodb and Postgres (google cloud) not working together: cannot create table

### ISSUE THREAD

**Issue by dominikmukrecki** [nocodb/nocodb#2130]
**Please enter the following details**

I am only able to connect to the database. Creating tables is impossible - they disappear. Server logs are below.

`POST /api/v1/db/meta/connection/test 200 33 - 93.635 ms
P :: error: remaining connection slots are reserved for non-replication superuser connections
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:506:15)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 140,
  severity: 'FATAL',
  code: '53300',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postinit.c',
  line: '833',
  routine: 'InitPostgres'
}
POST /api/v1/db/meta/projects/ 400 91 - 1353.172 ms
GET /api/v1/db/meta/projects/ 200 394 - 2.328 ms
GET /api/v1/db/auth/user/me 304 - - 1.353 ms
GET /api/v1/db/auth/user/me?project_id=p_ait6svm18ha57m 200 169 - 2.384 ms
GET /api/v1/db/meta/projects/p_ait6svm18ha57m 200 551 - 2.246 ms
R :: TypeError: Cannot read property 'order' of null
    at /usr/src/app/docker/main.js:2:16093
    at Array.sort (<anonymous>)
    at Function.list (/usr/src/app/docker/main.js:2:16071)
    at async u (/usr/src/app/docker/main.js:2:229875)
    at async R (/usr/src/app/docker/main.js:2:1087670)
    at async /usr/src/app/docker/main.js:2:35787
GET /api/v1/db/meta/projects/p_ait6svm18ha57m/tables?includeM2M= 400 46 - 17.875 ms
GET /api/v1/db/meta/projects/p_ait6svm18ha57m/users?limit=20&offset=0&query= 200 260 - 9.924 ms
GET /api/v1/db/meta/projects/p_ait6svm18ha57m/users?limit=10&offset=0&query= 200 260 - 9.636 ms
x :: i [Error]: Duplicate table name
    at Function.badRequest (/usr/src/app/docker/main.js:2:36452)
    at x (/usr/src/app/docker/main.js:2:1088924)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/src/app/docker/main.js:2:35787
POST /api/v1/db/meta/projects/p_ait6svm18ha57m/tables 400 30 - 6.649 ms
GET /dashboard/ 304 - - 1.248 ms
GET /api/v1/db/meta/nocodb/info 304 - - 5.328 ms
GET /api/v1/db/meta/nocodb/info 304 - - 4.347 ms
GET /api/v1/db/auth/user/me?project_id=p_ait6svm18ha57m 304 - - 1.592 ms
GET /api/v1/db/meta/projects/p_ait6svm18ha57m 304 - - 2.957 ms
R :: TypeError: Cannot read property 'order' of null
    at /usr/src/app/docker/main.js:2:16093
    at Array.sort (<anonymous>)
    at Function.list (/usr/src/app/docker/main.js:2:16071)
    at async u (/usr/src/app/docker/main.js:2:229875)
    at async R (/usr/src/app/docker/main.js:2:1087670)
    at async /usr/src/app/docker/main.js:2:35787
GET /api/v1/db/meta/projects/p_ait6svm18ha57m/tables?includeM2M= 400 46 - 18.055 ms
R :: TypeError: Cannot read property 'order' of null
    at /usr/src/app/docker/main.js:2:16093
    at Array.sort (<anonymous>)
    at Function.list (/usr/src/app/docker/main.js:2:16071)
    at async u (/usr/src/app/docker/main.js:2:229875)
    at async R (/usr/src/app/docker/main.js:2:1087670)
    at async /usr/src/app/docker/main.js:2:35787
GET /api/v1/db/meta/projects/p_ait6svm18ha57m/tables?includeM2M= 400 46 - 17.378 ms
GET /api/v1/db/meta/nocodb/version 304 - - 446.339 ms
GET /dashboard/ 304 - - 1.460 ms
GET /api/v1/db/meta/nocodb/info 304 - - 5.323 ms
GET /api/v1/db/meta/nocodb/info 304 - - 4.188 ms
GET /api/v1/db/meta/projects/ 304 - - 1.904 ms
GET /api/v1/db/auth/user/me 304 - - 1.532 ms
GET /api/v1/db/meta/nocodb/version 304 - - 46.349 ms
GET /api/v1/db/auth/user/me?project_id=p_ait6svm18ha57m 304 - - 1.602 ms
GET /api/v1/db/meta/projects/p_ait6svm18ha57m 304 - - 1.965 ms
R :: TypeError: Cannot read property 'order' of null
    at /usr/src/app/docker/main.js:2:16093
    at Array.sort (<anonymous>)
    at Function.list (/usr/src/app/docker/main.js:2:16071)
    at async u (/usr/src/app/docker/main.js:2:229875)
    at async R (/usr/src/app/docker/main.js:2:1087670)
    at async /usr/src/app/docker/main.js:2:35787
GET /api/v1/db/meta/projects/p_ait6svm18ha57m/tables?includeM2M= 400 46 - 23.813 ms
GET /api/v1/db/meta/projects/p_ait6svm18ha57m/users?limit=20&offset=0&query= 304 - - 13.607 ms
GET /api/v1/db/meta/projects/p_ait6svm18ha57m/users?limit=10&offset=0&query= 304 - - 7.855 ms
x :: i [Error]: Duplicate table name
    at Function.badRequest (/usr/src/app/docker/main.js:2:36452)
    at x (/usr/src/app/docker/main.js:2:1088924)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/src/app/docker/main.js:2:35787
POST /api/v1/db/meta/projects/p_ait6svm18ha57m/tables 400 30 - 9.835 ms
`
docker-compose content below:

version: "3.7"

networks:
  traefik:
    name: traefik

volumes:
  nocodb-data:
    name: nocodb-data

services:

  nocodb:
    container_name: nocodb
    image: nocodb/nocodb:latest
    restart: always
    volumes:
      - nocodb-data:/usr/app/data
    networks:
      - traefik
    environment:
      - NC_DB=pg://${DATABASE_HOST}:5432?u=${DATABASE_USER}&p=${DATABASE_PW}&d=${DATABASE_NAME}
      - NC_PUBLIC_URL=https://nocodb.${DOMAINNAME}
      - NC_DISABLE_TELE=true
    labels:
      - traefik.enable=true
      - traefik.http.services.nocodb.loadbalancer.server.port=8080
      - traefik.http.routers.nocodb.rule=Host(`nocodb.${DOMAINNAME}`)
      - traefik.http.routers.nocodb.tls.certresolver=myresolver
      - traefik.http.routers.nocodb.service=nocodb
      - traefik.docker.network=traefik

connection JSON with redacted credentials:

`{
  "client": "pg",
  "connection": {
    "host": "internal ip of the host",
    "port": "5432",
    "user": "valid username",
    "password": "password",
    "database": "valid database",
    "ssl": {
      "ca": "",
      "key": "",
      "cert": ""
    }
  },
  "searchPath": [
    "public"
  ],
  "meta": {
    "tn": "nc_evolutions",
    "dbAlias": "db",
    "api": {
      "type": "rest",
      "prefix": "",
      "graphqlDepthLimit": 10
    },
    "inflection": {
      "table_name": "none",
      "column_name": "none"
    }
  },
  "ui": {
    "setup": -1,
    "ssl": {
      "key": "Client Key",
      "cert": "Client Cert",
      "ca": "Server CA"
    },
    "sslUse": "No"
  }
}`

**Comment by dominikmukrecki** [comment]
Project with local data storage works well (without connection to the external database):

![image](https://user-images.githubusercontent.com/64379788/169877762-84e9dbbd-b121-4824-b92d-43aedd0d9d7e.png)

**Comment by dominikmukrecki** [comment]
Some other server logs:

`Sql Migration Statement for 'tableCreate' {
  upStatement: [
    {
      sql: '/* xc */\n' +
        'CREATE TABLE "sheet2" ( "id" serial, "title" character varying NULL, "created_at" timestamp NULL DEFAULT now(), "updated_at" timestamp NULL DEFAULT now(), PRIMARY KEY("id"));'
    },
    {
      sql: '/* xc */\n' +
        'CREATE OR REPLACE FUNCTION "xc_au_sheet2_updated_at"()\n' +
        '                          RETURNS TRIGGER AS $$\n' +
        '                          BEGIN\n' +
        '                            NEW."updated_at" = NOW();\n' +
        '                            RETURN NEW;\n' +
        '                          END;\n' +
        '                          $$ LANGUAGE plpgsql;/* xc */\n' +
        'CREATE TRIGGER "xc_trigger_sheet2_updated_at"\n' +
        '            BEFORE UPDATE ON "sheet2"\n' +
        '            FOR EACH ROW\n' +
        '            EXECUTE PROCEDURE "xc_au_sheet2_updated_at"();'
    }
  ],
  downStatement: [
    {
      sql: '/* xc */\n' +
        'DROP TRIGGER IF EXISTS "xc_trigger_sheet2_updated_at" ON "sheet2";/* xc */\n' +
        'DROP FUNCTION IF EXISTS "xc_au_sheet2_updated_at"()'
    },
    { sql: '/* xc */\ndrop table "sheet2"' }
  ]
}
x :: TypeError: Cannot read property 'order' of null
    at /usr/src/app/docker/main.js:2:16093
    at Array.sort (<anonymous>)
    at Function.list (/usr/src/app/docker/main.js:2:16071)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async x (/usr/src/app/docker/main.js:2:1089599)
    at async /usr/src/app/docker/main.js:2:35787
POST /api/v1/db/meta/projects/p_f9fbadwimxblbl/tables 400 46 - 69.259 ms
`

**Comment by o1lab** [comment]
If you used our docker-compose - could you please make a PR. Thank you
