### ISSUE TITLE
Support SSL Certs

### ISSUE THREAD

**Issue by bladefist** [nocodb/nocodb#215]
Using the latest from the npx install.  Anytime you try to setup a connection to a real database and you click any of the cert buttons, you get the error below.  Any db driver.

```
44db1cc.js:2 ReferenceError: dialog is not defined
    at f.selectFile (3691437.js:2)
    at click (3691437.js:2)
    at te (44db1cc.js:2)
    at f.n (44db1cc.js:2)
    at te (44db1cc.js:2)
    at f.t.$emit (44db1cc.js:2)
    at f.click (be8fb6e.js:2)
    at te (44db1cc.js:2)
    at HTMLButtonElement.n (44db1cc.js:2)
    at HTMLButtonElement.Lr.c._wrapper (44db1cc.js:2)
ne @ 44db1cc.js:2
ee @ 44db1cc.js:2
Zt @ 44db1cc.js:2
te @ 44db1cc.js:2
n @ 44db1cc.js:2
te @ 44db1cc.js:2
t.$emit @ 44db1cc.js:2
click @ be8fb6e.js:2
te @ 44db1cc.js:2
n @ 44db1cc.js:2
Lr.c._wrapper @ 44db1cc.js:2
```

**Comment by o1lab** [comment]
This might be related to us using our electron code. We will have to look into this.

**Comment by bladefist** [comment]
Is there anyway to send "Trust Server Certificate=True;" in the connection string?

**Comment by nengine** [comment]
Hello, I keep getting "Connection Failure: SSL connection is required. Please specify SSL options and retry." message when connecting to postgre database.  Installed with npx on Windows 10.  In the config file I have sslUse: Required set.  

```js
"ui": {
    "setup": -1,
    "ssl": {
      "key": "Client Key",
      "cert": "Client Cert",
      "ca": "Server CA"
    },
    "sslUse": "Required"
  }
```

**Comment by o1lab** [comment]
@bladefist : please try the latest docker. We have a fix to connect to SSL.

There is a way to change the connection params as you have already looked up I think.

Ping me on discord, we will help this out.

**Comment by pranavxc** [comment]
> Is there anyway to send "Trust Server Certificate=True;" in the connection string?

You can put it in the knex config

```
{
  password: 'P@ssw0rd',
  database: 'master',
  stream: false,
  options: {
    enableArithAbort: true,
    encrypt: true
  },
  port: 1433,
  user: 'sa',
  server: 'localhost',
}
```

For more about editing knex config refer :  https://www.youtube.com/watch?v=rS0NRwRCjx0

**Comment by nengine** [comment]
@bladefist  Thank you.  I tried Docker but still getting same message.  Please let me know how can I connect you on Discord?

**Comment by o1lab** [comment]
@nengine : https://discord.gg/5RgZmkW

**Comment by pranavxc** [comment]
@nengine : can you try the latest docker, if still facing error please share it
.

**Comment by nengine** [comment]
@pranavxc I just tried latest Docker and getting the same result.  Also tried knex.js and got error below on Windows 10.

```
(async () => {
    const pg = require('knex')({
        client: 'pg',
        connection: process.env.PGDB,        
      });
      try {
        const r = await pg('tasks').select('title')
        console.log(r)
      } catch(error) {
          console.error(error)
      }
      
})();

```

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:208:20) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by o1lab** [comment]
@nengine : could you see what makes knex work with your database.

That will help is to know how to fix this.

**Comment by nengine** [comment]
@o1lab I meant to say that it didn't work, but got an error message show above.

**Comment by nengine** [comment]
Hi @o1lab it works now with knex with settings below. But Docker still does not work.  Many thanks.

```js

(async () => {
    var parse = require('pg-connection-string').parse;
    const pg = require('knex')({
        client: 'pg',
        connection: {
            ssl: true,
            sslmode: 'require',
            ...parse(process.env.PGDB)
        }
      });
      try {
        const r = await pg('tasks').select('title')
        console.log(r)
      } catch(error) {
          console.error(error)
      }
      
})();
```

**Comment by o1lab** [comment]
Cool, we allow adding extra connection params to knex : please check this out https://www.youtube.com/watch?v=rS0NRwRCjx0

You can add params that made it work, I believe these two are the ones. 

```
  ssl: true,
  sslmode: 'require',
```

**Comment by duffleit** [comment]
Hi, took me a while to figure out how SSL with Postgres works. I needed to add in the connection-json the key `ssl` with the string value `"true"` — just setting a boolean `true` was still throwing an error on my side. 

here an example config: 
```
{
  "client": "pg",
  "connection": {
    "host": "localhost",
    "port": "5432",
    "user": "postgres",
    "password": "password",
    "database": "postgres",
    "ssl": "true"
  },
  ...
```

Hope this helps! 🚀

**Comment by guzmonne** [comment]
In my case I had to configure the `ssl` option as an object, providing the `ca`:

```json
{
  "client": "pg",
  "connection": {
    "host": "localhost",
    "port": "5432",
    "user": "postgres",
    "password": "password",
    "database": "postgres",
    "ssl": {
      "rejectUnauthorized": false,
      "ca": "-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----"
  },
```
  ...

**Comment by o1lab** [comment]
This is resolved in subsequent releases & will close this.
