### ISSUE TITLE
`host` networking "shouldn't" work

### ISSUE THREAD

**Issue by jjasghar** [nocodb/nocodb#216]
Looking here: https://github.com/nocodb/nocodb/blob/master/README.md#using-docker-as-daemon-with-named-docker-process-as-nocodb-and-access-to-databases-on-the-host-and-automatic-restart

I believe that your `--network=host` will ignore the `-p 8080:8080` mapping. It'll actually throw a warning: 
```
WARNING: Published ports are discarded when using host network mode
```

**Comment by o1lab** [comment]
I've taken out additional instructions for docker daemon support etc. This was from a community pull request.

For quick try : we'll keep things simple :)

**Comment by jjasghar** [comment]
Rock on, thanks!
