### ISSUE TITLE
Import AirTable to SQL database : Missing 'rollup_function' property in request body

### ISSUE THREAD

**Issue by yoanbernabeu** [nocodb/nocodb#2171]
```
NocoDB used as docker : true 
NocoDB version :  0.91.0
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created : sqlite3
OS on which NocoDB is running :  Ubuntu 22.04
```

**Steps To Reproduce**

1. Go to 'import AirTable'
2. Click on 'import'
3. See error : Missing 'rollup_function' property in request body

**Expected Behavior**

The creation of the tables seems OK, but in the import logs I see the following message "Missing 'rollup_function' property in request body".

Tables are created, but no data is imported.

Thanks,
Yoan

**Comment by o1lab** [comment]
This was reported by one of our users and we have a fix for it in upcoming release. Please stay tuned.
Please reach out to me (@o1lab) on our [discord](discord.nocodb.com)
