### ISSUE TITLE
Bug/Feature Request

### ISSUE THREAD

**Issue by bhanuc** [nocodb/nocodb#218]
Really great project, though while entering date currently no date selector is coming up. Is it a bug or something that hasn't been planned ?

**Comment by o1lab** [comment]
Which database & version was this ?

**Comment by bhanuc** [comment]
postgres and using the latest docker image- nocodb/nocodb:latest

**Comment by pranavxc** [comment]
Please share the datatype of the field

**Comment by bhanuc** [comment]
DataType is Date.
