### ISSUE TITLE
Import Airtable base to NocoDB (postgresql database) issue

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2199]
- Schema gets migrated.
- One of the view has an issue.

From the user 

```
Syncing views
 :: [1/19] Grid : RFQ / Pending RFQs WEB
 viewColumnUpdate - viewer : Not allowed
```

**Comment by dstala** [comment]
Couldn't reproduce. Need more information.

**Comment by o1lab** [comment]
Good to close. I think that reporter was able to migrate successfully.
