### ISSUE TITLE
Webhook with condition has issues

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2209]
https://www.berrycast.com/conversations/ac419776-b002-550b-a295-08e6301da589

**Comment by alprotasov** [comment]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.91.1**

**Comment by alprotasov** [comment]
One more project info from Discord:

Node: v12.22.12
Arch: x64
Platform: linux
Docker: true
Database: sqlite3
ProjectOnRootDB: true
RootDB: sqlite3
PackageVersion: 0.91.1
