### ISSUE TITLE
Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by apiening** [nocodb/nocodb#2210]
I'm using the `MySQL` based `docker-compose` deployment on `amd64` based on https://github.com/nocodb/nocodb/blob/develop/docker-compose/mysql/docker-compose.yml

I've configured a MySQL Database and a non root user and I've set the environment variable `NC_DB` to `mysql2://root_db:3306?u=${MYSQL_USER}&p=${MYSQL_PASSWORD}&d=${MYSQL_DATABASE}`.
`nocodb` can access the database and all operations are working.

In the logs, I spot the line
```
[Note] Access denied for user 'root'@'localhost' (using password: NO)
```
every 30 seconds.
Why is `nocodb` trying to access the database with a `root` user and an empty password?
Can I disable this behaviour?

How to reproduce:
* Download a docker-compose project based on https://github.com/nocodb/nocodb/blob/develop/docker-compose/mysql/docker-compose.yml
* Bring the stack up with `docker-compose up -d --force-recreate && docker-compose logs -f` and wait for a while for the message to appear

**Comment by o1lab** [comment]
May be [this](https://github.com/nocodb/nocodb/blob/develop/docker-compose/mysql/docker-compose.yml#L18) line.

Do you see this log while using the product.

**Comment by apiening** [comment]
Oh yes, you're totally right.
It would be possible to add a valid username and password combination to the `mysqladmin ping` command. But this would just change the recurring message to
```
mysqld is alive
```
Since this would expose the password to the command line, this solution would be even worse.

I'm closing this issue.
