### ISSUE TITLE
TypeError after upgrade to 0.91.6 with Docker

### ISSUE THREAD

**Issue by akail** [nocodb/nocodb#2225]
**Project Info**

```
Node: **v12.22.12**
Arch: **arm64**
Platform: **linux**
Docker: **yes**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **nocodb**
PackageVersion: **0.91.6**
```

**Issue Description**

I recently attempted an upgrade to the latest version of nocodb from version 0.90.10 to 0.91.6 running in docker. My postgresql database is hosted on a separate machine.  After starting the new container I received a TypeError, posted below.  The web interface also appears to not be working.   Appears to have become stuck during a database update.

**Steps To Reproduce**

Unable to reproduce at the moment as downgrading the docker container fails due to some missing files, probably as a result of the upgrade?  

**Expected Behavior**

Upgrade should have completed.

**Screenshots**

![image](https://user-images.githubusercontent.com/2334566/171448019-4302518a-4568-4078-a18f-30d0f2847fa7.png)

![image](https://user-images.githubusercontent.com/2334566/171448075-7c19450f-9184-4b46-937e-58c4da8fefe8.png)

Thank you for any help and for developing a really nice product.

**Comment by o1lab** [comment]
We're looking into it.

**Comment by akail** [comment]
Can confirm its fixed!  Thanks!
