### ISSUE TITLE
Shared Form view is Empty

### ISSUE THREAD

**Issue by pcxnet** [nocodb/nocodb#2228]
**Please enter the following details**

Copy and Paste Project Info - Tutorials: How to check my Project info? ([YouTube Tutorial](https://www.youtube.com/watch?v=AUSNN-RCwhE) or [Documentation](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-))

Node: **v16.15.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.91.7**

**Steps To Reproduce**

1. Create form view
![Web capture_2-6-2022_35046_apps kal net au](https://user-images.githubusercontent.com/16738529/171470567-2f42d83a-8e79-4c60-9145-2308add7d3cc.jpeg)

3. Share form view
![image](https://user-images.githubusercontent.com/16738529/171470543-158203c6-827d-40b8-b80a-aa370aab8e3f.png)

5. Form is blank
![Web capture_2-6-2022_35144_apps kal net au](https://user-images.githubusercontent.com/16738529/171470588-5c3cd6bf-bae0-4357-be32-a0c6a3e3ea17.jpeg)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by wingkwong** [comment]
Could you please check the logs to see if there is any errors?

![image](https://user-images.githubusercontent.com/35857179/171547639-a5080de0-8f77-47ef-9a37-6f7a4a795308.png)

**Comment by pcxnet** [comment]
This was in the console log on the browser:
`msgport.js:70 {"notify":"init_tab"}
8f9dcbc.js:2 
        
       TypeError: Cannot read properties of undefined (reading 'title')
    at o (77fb7f6.js:2:31118)
    at f.validations (77fb7f6.js:2:31285)
    at f.children (77fb7f6.js:2:9553)
    at kn.get (8f9dcbc.js:2:31496)
    at kn.evaluate (8f9dcbc.js:2:32636)
    at f.children (8f9dcbc.js:2:34525)
    at f.refs (77fb7f6.js:2:4324)
    at kn.get (8f9dcbc.js:2:31496)
    at kn.evaluate (8f9dcbc.js:2:32636)
    at f.refs (8f9dcbc.js:2:34525)
re @ 8f9dcbc.js:2
3a22555.js:2 
        
       WebSocket connection to 'wss://apps.kal.net.au/socket.io/?EIO=4&transport=websocket&sid=ZQ-pPAyaHIv80CAhAAAO' failed: 
doOpen @ 3a22555.js:2
`


Can't see anything in the error log:
`App 10196 output: GET /api/v1/db/meta/tables/md_847n35hvo5lt1o 304 - - 16.617 ms
App 10196 output: GET /api/v1/db/meta/tables/md_847n35hvo5lt1o/views 304 - - 2.960 ms
App 10196 output: GET /api/v1/db/meta/views/vw_bkt5hp1cb9ijnj/columns 304 - - 3.197 ms
App 10196 output: GET /api/v1/db/meta/views/vw_bkt5hp1cb9ijnj/sorts 304 - - 5.317 ms
App 10196 output: GET /api/v1/db/meta/views/vw_bkt5hp1cb9ijnj/filters 304 - - 1.935 ms
App 10196 output: GET /api/v1/db/data/noco/KALPettyCash/md_847n35hvo5lt1o/views/vw_bkt5hp1cb9ijnj?limit=25&offset=0&where= 304 - - 52.510 ms
App 10196 output: GET /api/v1/db/meta/grids/vw_bkt5hp1cb9ijnj/grid-columns 304 - - 11.983 ms
App 10196 output: GET /api/v1/db/meta/audits/comments/count?ids[]=2&ids[]=3&ids[]=4&fk_model_id=md_847n35hvo5lt1o 200 2 - 23.567 ms
App 10196 output: GET /api/v1/db/meta/tables/md_74oi3xpk5qbnv2 304 - - 24.173 ms
App 10196 output: GET /api/v1/db/meta/tables/md_k64lymceo7mk0v 304 - - 24.727 ms
App 10196 output: GET /api/v1/db/meta/audits/comments/count?ids[]=2&ids[]=3&ids[]=4&ids[]=&fk_model_id=md_847n35hvo5lt1o 200 2 - 10.274 ms
App 10196 output: GET /api/v1/db/data/noco/KALPettyCash/Suppliers?limit=10&offset=0&where=(Supplier+Name,like,%25%25) 200 708 - 45.192 ms
App 10196 output: GET /api/v1/db/meta/plugins 304 - - 7.516 ms
App 10196 output: GET /api/v1/db/meta/projects/p_466ez3f61fe7wy/users?limit=20&offset=0&query= 304 - - 25.758 ms
App 10196 output: GET /api/v1/db/meta/projects/p_466ez3f61fe7wy/users?limit=10&offset=0&query= 304 - - 7.669 ms
App 10196 output: GET /api/v1/db/meta/projects/p_466ez3f61fe7wy/audits?limit=25&offset=0 304 - - 21.952 ms
App 10196 output: GET /api/v1/db/meta/projects/p_466ez3f61fe7wy/audits?limit=25&offset=0 304 - - 4.883 ms
App 10196 output: GET /api/v1/db/meta/projects/p_466ez3f61fe7wy/audits?limit=25&offset=0 304 - - 11.430 ms
App 10196 output: GET /api/v1/db/meta/audits/comments/count?ids[]=2&ids[]=3&ids[]=4&ids[]=&fk_model_id=md_847n35hvo5lt1o 304 - - 35.269 ms
App 10196 output: POST /api/v1/db/data/noco/KALPettyCash/md_847n35hvo5lt1o/views/vw_bkt5hp1cb9ijnj 200 262 - 60.066 ms
App 10196 output: GET /api/v1/db/meta/audits/comments/count?ids[]=2&ids[]=3&ids[]=4&ids[]=5&fk_model_id=md_847n35hvo5lt1o 200 2 - 11.479 ms
App 10196 output: GET /api/v1/db/data/noco/KALPettyCash/md_847n35hvo5lt1o/views/vw_bkt5hp1cb9ijnj/count 200 11 - 13.196 ms
App 10196 output: GET /api/v1/db/meta/projects/p_466ez3f61fe7wy/audits?limit=25&offset=75 200 7331 - 4.946 ms
App 10196 output: GET /api/v1/db/meta/projects/p_466ez3f61fe7wy/audits?limit=25&offset=0 200 11483 - 5.545 ms
App 10196 output: GET /dashboard/_nuxt/fonts/roboto-v27-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-700italic.7e573ef.woff2 304 - - 17.439 ms
App 10196 output: GET /dashboard/_nuxt/fonts/roboto-v27-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-italic.1075849.woff2 304 - - 10.548 ms
App 10196 output: GET /api/v1/db/meta/forms/vw_lgbx97xmgsuqtw 304 - - 6.683 ms
App 10196 output: POST /api/v1/db/meta/views/vw_lgbx97xmgsuqtw/share 200 376 - 3.491 ms
App 10196 output: GET /dashboard/ 304 - - 5.274 ms
App 10196 output: GET /dashboard/_nuxt/7dfa6a9.js 304 - - 5.397 ms
App 10196 output: GET /dashboard/_nuxt/8f9dcbc.js 304 - - 6.414 ms
App 10196 output: GET /dashboard/_nuxt/3a22555.js 304 - - 7.227 ms
App 10196 output: GET /dashboard/_nuxt/0ab0b2c.js 304 - - 7.928 ms
App 10196 output: GET /dashboard/_nuxt/acc5c2c.js 304 - - 2.813 ms
App 10196 output: GET /dashboard/_nuxt/b2b2085.js 304 - - 4.244 ms
App 10196 output: GET /dashboard/_nuxt/b8ad988.js 304 - - 3.036 ms
App 10196 output: GET /dashboard/_nuxt/77fb7f6.js 304 - - 2.572 ms
App 10196 output: GET /dashboard/_nuxt/f7a8eeb.js 304 - - 3.634 ms
App 10196 output: GET /dashboard/_nuxt/82c852f.js 304 - - 3.305 ms
App 10196 output: GET /dashboard/_nuxt/59867b2.js 304 - - 2.257 ms
App 10196 output: GET /api/v1/db/meta/nocodb/info 304 - - 1.986 ms
App 10196 output: GET /dashboard/_nuxt/fonts/roboto-v27-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-700.6a1f56a.woff2 304 - - 2.129 ms
App 10196 output: GET /dashboard/_nuxt/fonts/roboto-v27-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-500.ef8bb09.woff2 304 - - 2.220 ms
App 10196 output: GET /api/v1/db/meta/nocodb/info 304 - - 7.762 ms
App 10196 output: GET /dashboard/icon.png 304 - - 6.072 ms
App 10196 output: GET /dashboard/_nuxt/fonts/roboto-v27-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-regular.4227811.woff2 304 - - 5.345 ms
App 10196 output: GET /dashboard/_nuxt/a9500dc.js 304 - - 6.081 ms
App 10196 output: GET /dashboard/_nuxt/img/512x512-trans.5601bce.png 304 - - 5.246 ms
App 10196 output: GET /dashboard/_nuxt/c006b33.js 304 - - 5.024 ms
App 10196 output: GET /api/v1/db/public/shared-view/4c19bc27-eb2e-46ab-82d9-1622069b53e9/meta 200 64778 - 29.236 ms
App 10196 output: GET /api/v1/db/meta/nocodb/version 304 - - 352.985 ms
`
