### ISSUE TITLE
Time Zone in Audit Log incorrect

### ISSUE THREAD

**Issue by pcxnet** [nocodb/nocodb#2229]
**Please enter the following details**

Node: **v16.15.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.91.7**

Times in audit log showing as in the future, can't see settings to change time zones anywhere.
![Web capture_2-6-2022_35430_apps kal net au](https://user-images.githubusercontent.com/16738529/171471014-6c094927-455d-491a-969c-4d6ba7067b8b.jpeg)

**Comment by wingkwong** [comment]
> Times in audit log showing as in the future

Sorry. Which times are you referring? 7 hours ago under Created?

**Comment by pcxnet** [comment]
Yes see this is something i just created.
![Screenshot 2022-06-02 135410](https://user-images.githubusercontent.com/16738529/171549791-d234b9cf-56da-42f0-9145-50ee4c9d1cfa.png)

**Comment by wingkwong** [comment]
If you hover ``in XX hours``, is the date time showing correctly?

![image](https://user-images.githubusercontent.com/35857179/171550170-a07a5724-8346-4e78-8839-9288759d45f0.png)

**Comment by pcxnet** [comment]
Yes, that time is correct.
![image](https://user-images.githubusercontent.com/16738529/171550412-fb846f92-1c2e-4c58-b5cf-6cad6d3a5f40.png)

**Comment by wingkwong** [comment]
Okay. So what you mean is like instead of showing 7 hours, it should show something like ``in XX mins`` if we just create it right

**Comment by pcxnet** [comment]
Its in the past , you can't audit something from the future, so it should say (3 mins ago) or something.  it should never think its in the future.

**Comment by wingkwong** [comment]
Oh yes. I understand what you mean. It's not expected to show something like ``in ...``. Will take a look. Thanks for your prompt reply.

**Comment by o1lab** [comment]
We would need to handle the following
- which timezone the database is in ([mysql](https://stackoverflow.com/questions/3688731/is-it-better-to-create-an-index-before-filling-a-table-with-data-or-after-the-d), [pg](https://stackoverflow.com/questions/28216923/how-do-i-get-the-current-timezone-name-in-postgres-9-3))
- column type can also have timezone
- each project (on an external db) can have its own timezone
- user's browser timezone
- ability to configure timezone ( can be messy with cron in place )

**Comment by asaage** [comment]
there is still something strange.
my nocodb container is on UTC allthough i added env ```TZ=Europe/Berlin```
the base is mariadb outside on another system.
```SHOW SESSION VARIABLES LIKE 'time_zone';``` shows "SYSTEM"
the hostsystem of the base is on CET
When creating/updating records via nocodb the CreatedAt/UpdatedAt values are UTC and i don't find a way to dateformat them in my views.
