### ISSUE TITLE
More visible table borders to make it easier to read the table contents

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#2239]
## Recommending Features

When working with tables, we need to have the fields separated from each other by a bold & thick line. So it will be much easier to read each field's contents and differentiate them. 

**Need for this feature**
Designing a more visible border between table fields make it much easier to work with table.

**Is your feature request related to a problem? Please describe.**
Sometimes we cannot recognize which field possesses a specific piece of data; that's because of a proper border invisibility.  

**Describe the solution you'd like**
We want a visible border which has a high contrast to the surrounding background; like the table below.

![error2](https://user-images.githubusercontent.com/100111649/171632954-3a1f7ff8-7141-4ca7-88d3-002f13b9ccb7.PNG)

and this is the current state:

![error1](https://user-images.githubusercontent.com/100111649/171632999-ae47f95b-4991-45ec-8326-9b1ea29b18c1.PNG)

As you can see, this is actually visible but the contrast is too low that there are no difference between the border and the field colour.
In some monitors which have a low resolution, it gets worse.

**Comment by o1lab** [comment]
The dark screenshot is too much in the eye. See below of how it looks for google spreadsheet.

<img width="805" alt="Screenshot 2022-06-08 at 14 01 31" src="https://user-images.githubusercontent.com/5435402/172622957-6e526d38-c4b7-43c1-9533-ff3cfc80b1b9.png">
