### ISSUE TITLE
Arrow keys not working properly when moving across the table fields

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#2240]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.91.7**

**Steps To Reproduce**

When the interface is Persian and we want to move across the table fields, the LEFT arrow key on the keyboard moves RIGHT and the RIGHT arrow key moves LEFT. So it's not working fine and makes it difficult to move across the table fields.

**Expected Behavior**

When we press the LEFT arrow key, it should move one field to the LEFT direction and vice versa.

**Comment by o1lab** [comment]
@okaeiz Could you please send a pull request - that would be helpful.

**Comment by okaeiz** [comment]
Unfortunately we don't know how to do it. It'll we great if you guys make the keys work properly.

**Comment by okaeiz** [comment]
The bug is fixed in the image above ✅
