### ISSUE TITLE
Date cell with invalid date cannot be changed anymore

### ISSUE THREAD

**Issue by jakob-stoeck** [nocodb/nocodb#2251]
```
Node: **v12.22.12**
Arch: **arm64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.91.7**
```

**Steps To Reproduce**

1. Add a column with date type
2. Insert an invalid date using the calendar picker (not sure how I succeeded, I just selected year 2028, clicked a bit around and that was it)
3. You cannot recover from that error, since the calendar picker doesn’t let you choose a valid date anymore. The picker still opens, but no button is operable

The JavaScript console error is:

```
RangeError: Invalid time value
    at Object.titleDate (3a22555.js:2:1569966)
    at f.genPickerTitle (3a22555.js:2:1590789)
    at f.genPicker (3a22555.js:2:205546)
    at f.render (3a22555.js:2:1594481)
    at t._render (8f9dcbc.js:2:40188)
    at f.r (8f9dcbc.js:2:69953)
    at kn.get (8f9dcbc.js:2:31496)
    at kn.run (8f9dcbc.js:2:32380)
    at An (8f9dcbc.js:2:30479)
    at Array.<anonymous> (8f9dcbc.js:2:16678)
```

Using the latest Chrome Version 102.0.5005.61 (Official Build) (arm64)

**Expected Behavior**

1. Even if there is an invalid date, be able to recover using the calendar picker (or any other method)
2. Not being able to enter an invalid date to begin with

**Screenshots**

See invalid date in the top right cell

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/62809/171865653-24fc92a2-aec9-4d6f-b861-d73a3c4a124b.png">

When clicking on the invalid date, the calendar picker opens, but no button works 

<img width="347" alt="image" src="https://user-images.githubusercontent.com/62809/171866213-3c35fec8-10d4-4cb7-a7e9-da86d4b89c67.png">

**Comment by dstala** [comment]
- add a date using 'date-picker', save
- click on cell & type `x`
- throws error & stores record as invalid date
