### ISSUE TITLE
[i18n] Language support extension- <de>

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#2268]
# i18n translation request

**Please enter the following details**

1. Select applicalbe
- [ ] **New language support request**
- [X] **Existing language translation corrections request** 
Verify if language support already exists in the NocoDB i18n master spreadsheet [here](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172)

2. Associated language code (pick from [here](https://developers.google.com/admin-sdk/directory/v1/languages)): de 

3. Excel spreadsheet
- Alternatively, you can download & attach a spreadsheet here along with the issue as well. 
- [X] **Attached**
- [ ] **Shared link**:

4. Summary of the changes made
- You can highlight modified items in the Spreadsheet attached/shared, to help us quickly identify changes (**marked with yellow colour** on both - **i18n** and **v1.0 banner-images**)

5. Any specific message to be conveyed to moderators? No
 
[noco-i18n-05062022.xlsx](https://github.com/nocodb/nocodb/files/8839756/noco-i18n-05062022.xlsx)

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/commit/0b885e380e2aac0edef68f08e3c07fe0fd2124d0

**Comment by WeT-Klb** [comment]
Can you have a look on **v1.0 banner-images**-tab, too?

**Comment by dstala** [comment]
@WeT-Klb, thank you for your support!
https://github.com/nocodb/nocodb/blob/develop/scripts/markdown/readme/languages/german.md
