### ISSUE TITLE
Bug : Postgres : UUID field with gen_random_uuid() is failing.

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#227]
Hi, I was wondering how do I add an UUID field with autogenerated default entry in nocodb, I tried using gen_random_uuid() but it is not working[ using postgres with latest docker image)

From Discord user :bhanuc

**Comment by pranavxc** [comment]
You can set `gen_random_uuid()` as default value


![image](https://user-images.githubusercontent.com/61551451/120806135-1da9c980-c564-11eb-8a53-c88deeef803f.png)

**Comment by bhanuc** [comment]
This is confirmed working, though I was more interested in generating the v5 version of the uuid, for which I had to enable it for the database via CLI using the following statement 
` CREATE EXTENSION "uuid-ossp";` 
After which uuid_generate_v5(uuid_ns_url(), 'http://www.postgresql.org') also works.

References for Different versions of uuid
https://www.postgresql.org/docs/13/uuid-ossp.html#id-1.11.7.53.5

Can close this issue.

**Comment by pranavxc** [comment]
@bhanuc thanks for confirming, will close the issue
