### ISSUE TITLE
[Feature] Expanded fillable form for LongText cell

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2271]
vibrantium@discord
I have difficulty typing in long text fields bcs while I can drag it to look bigger, it returns to be small whenever I started typing? I think there's an option to show a fillable form per row but that's not exactly what I was looking for: in Airtable, there's a double-arrow in the corner of a long text cell & if you click it, it'll expand into a bigger cell but not a per-row fillable form. That way, I can still view other cells.

**Need for this feature**
Easy to feed into the LongText cell

**Is your feature request related to a problem? Please describe.**
Generic

**Describe the solution you'd like**
Pop window specific to LongText to feed in details

**Describe alternatives you've considered**
Expand row option open's up input option for all the columns

**Additional context**
Airtable behavior for reference
![Screenshot 2022-06-06 at 11 16 18 AM](https://user-images.githubusercontent.com/86527202/172102383-26472fd1-662b-4642-90f8-c602285b1678.png)

**Comment by Gari-sincere** [comment]
Definitely agree that this is an important feature. I want like some of the features of NocoDB over Baserow but this is a killer for me. Baserow has Longtext compacted by default and then expands it out when the cell is selected

![image](https://user-images.githubusercontent.com/44096102/201439696-af026786-4e45-4764-8a16-ad2634d7a6f5.png)

**Comment by dstala** [comment]
available from v0.111.0
