### ISSUE TITLE
email SMTP: missing credentials for plain

### ISSUE THREAD

**Issue by King-GO** [nocodb/nocodb#2276]
Fresh install via Docker

install SMTP email client
Setting email SMTP 
host: company's email server
port: 25
secure: false
ignore TLS

test: Missing credentials for "PLAIN"
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.91.7**
```

**Comment by wingkwong** [comment]
Have your provided username & password? Your company email server should require credentials.

**Comment by King-GO** [comment]
no need it!
usually i fill out the mail host, port  and set secure to false. the mail feature may work

**Comment by King-GO** [comment]
@wingkwong What about if encryption and authentication method are NONE? How to fill in the SMTP configuration?

**Comment by wingkwong** [comment]
Sorry for the delayed response. If encryption and authentication are not required, then I think your setup should be fine. Please ping me in discord (wkw - #3278) for further discussion.

**Comment by wingkwong** [comment]
probably missing `rejectUnauthorized`
