### ISSUE TITLE
Editing and testing webhook is not working - if its not the first webhook on list

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2277]
https://www.berrycast.com/conversations/1bca497d-7f6f-5857-aad2-261d74e6818d

**Comment by alprotasov** [comment]
The point is ... it doesn't work in "production", I mean testing is just example to show you that something goes wrong. If I can  help you with debugging please let me know how to do this

**Comment by o1lab** [comment]
On second look, it looks like the 2nd and 3rd webhooks have a condition. And on triggering test webhook the condition is not met for the sample payload sent and hence the issue.

Two ways to solve this :
- We can send a notification back mentioning : "Sample payload doesn't satisfy the condition & hence test webhook was not triggered"
- User is just testing webhook : we can simply invoke the webhook without testing condition.

To keep it simple : we can go with 2nd option. Once we've nested data available in payload - we can switch to first option.

**Comment by alprotasov** [comment]
What I mean here... it doesn't work at all in this two cases... testing is just an example. Let me record video with real production case

**Comment by dstala** [comment]
issue observed when condition-based trigger used over the single-select field.

**Comment by mertmit** [comment]
This is caused by single-select field change request post with `ignoreWebhook=true` param.
I will fix this.
