### ISSUE TITLE
Some Column types are missing when modifying columns

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#2285]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.91.7-pr-2267-20220605-0926** (Unofficial image)

**Steps To Reproduce**

1. Go to a table and select a column.
2. Click on 'Edit' & then 'Column Type'
3. Sometimes, some certain column types cannot be selected. For instance, I want to set the 1st column type to 'Formula' but I cannot find it. This is also true with some other columns and column types.

**Expected Behavior**

We expect to be able to set ANY column type for ALL the columns in a table.

**Comment by o1lab** [comment]
First column at the moment cannot be set to any type. There are limitations on it.

**Comment by okaeiz** [comment]
> First column at the moment cannot be set to any type. There are limitations on it.

Are these limitations going to be removed someday? We need the first column to be set Formula (e.g. CONCAT) and we need it to be the primary value but NocoDB doesn't let us set a Formula column to be the Primary value.

**Comment by wingkwong** [comment]
We have to tackle the following cases.

- In v1 lookup / LTAR columns are done in a hacky way so setting it up as primary will cause lot of issues
- If filter is applying to an LTAR then we are applying where condition is on primary column - if it's virtual column it's more complex to handle
- Rending children with pv (in child list - cell, modal, etc) could be difficult

**Comment by okaeiz** [comment]
I think it's okay to consider some limitations for the primary value.
But the problems of LTAR columns still need to be fixed.

**Comment by dstala** [comment]
Formula as primary column is now supported since v0.105.2
