### ISSUE TITLE
Download CSV error with specific non-english table/column name

### ISSUE THREAD

**Issue by Entmatix** [nocodb/nocodb#2286]
```
NocoDB used as docker : true
NocoDB version : v0.91.7
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : debian 11
Node.js version if running as node : v14.18.0
Database version : 14.3-1.pgdg110+1
```

**Steps To Reproduce**

1. Go to any table.
2. Open greed view.
3. Click More -> Download as CSV.
4. See error "Request failed with status code 400".

**Expected Behavior**

Get CSV file for current table.

**Screenshots**

...

**Additinal information**

In log I see this when try to download csv.

```
nocodb-nocodb-1   | l :: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
nocodb-nocodb-1   |     at ServerResponse.setHeader (_http_outgoing.js:533:3)
nocodb-nocodb-1   |     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:776:10)
nocodb-nocodb-1   |     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:779:12)
nocodb-nocodb-1   |     at l (/usr/src/app/docker/main.js:2:1225710)
nocodb-nocodb-1   |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
nocodb-nocodb-1   |     at async /usr/src/app/docker/main.js:2:35786 {
nocodb-nocodb-1   |   code: 'ERR_INVALID_CHAR'
nocodb-nocodb-1   | }
```

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by Entmatix** [comment]
That's wrong information above. The app is dockerized, arch amd64.

**Comment by dstala** [comment]
> That's wrong information above. The app is dockerized, arch amd64. Also it's not table name, it's project name. Tables names are different. And please, remove the name. I haven't agreed to publish this information.

@Entmatix , was just informing dev team about an easy way to identify error. I have deleted comment as per your request. If table name is confidential, I would recommend striking off encoded URI in your log.

**Comment by dstala** [comment]
@Entmatix , removed encoded URI from your log

**Comment by Entmatix** [comment]
> @Entmatix , removed encoded URI from your log

Thank you.

**Comment by okaeiz** [comment]
I have the same issue. I cannot download tables as a csv file.

**Comment by dstala** [comment]
issue reproducible & observed with a specific set of characters (current observations, often non-english) in use in either table/ column name. we will explore a workaround for such instances.

**Comment by Entmatix** [comment]
@dstala, I'd be happy to participate in testing when update comes to docker container.

**Comment by o1lab** [comment]
When we make a PR - there will be an automatic test that gets published. You can test that - appreciate your help :)

**Comment by okaeiz** [comment]
So currently we cannot have ANY export of our database at all? 😨

**Comment by okaeiz** [comment]
We have checked the image shared here.
Exporting csv was okay but now when we try to import the same csv, it raises an error. 
![Untitled](https://user-images.githubusercontent.com/100111649/172849362-d3ea3ac0-14cb-41a7-835f-2a04f36c328a.png)
