### ISSUE TITLE
password changing doesn't work (old password required)

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#2288]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.91.7-pr-2267-20220605-0926**

**Steps To Reproduce**

1. Go to your profile, where you can change your password.
2. Change your password.
3. Try to log in using your new password. See? It doesn't work. It requires the old password.

**Expected Behavior**

We want to log in using our new passwords.

**Comment by o1lab** [comment]
After changing the password & restarting the container - the user will have to use new password.
