### ISSUE TITLE
Issue: "expensive" filter on the front end

### ISSUE THREAD

**Issue by Bokitza** [nocodb/nocodb#229]
when filtering rows, every "KeyDown" appears to issue a GET request to update the table

should be only when pressing 'Add Filter'
![image](https://user-images.githubusercontent.com/58147254/120829219-d6bcd380-c565-11eb-8c91-02ca95701b60.png)

**Comment by pranavxc** [comment]
Added an option to disable this feature by toggling a checkbox, if the user toggled he have to click the apply filter button manually.

This will be available in the latest version.
