### ISSUE TITLE
[Feature] Expand a row in an embedded view

### ISSUE THREAD

**Issue by Cirsten** [nocodb/nocodb#2293]
**Need for this feature**
What purpose does your Idea serve? What use cases does it solve?
Able users/viewers of an embedded table to expand and focus on a row

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
When actually using the database I can expand a row, but this feature is not available when the same table/view is embedded in a website

**Describe the solution you'd like**
See http://siabodsmarvelcomicpage.weebly.com/test.html to compare how Airtable handles it, which is essentially the same while within NocoDB

**Describe alternatives you've considered**
None

**Additional context**

**Comment by dstala** [comment]
to be tracked under

[🔦 Feature: Expand record option for shared view](https://github.com/nocodb/nocodb/issues/5945)
