### ISSUE TITLE
Question mark is treated as a param in postgres' CONCAT

### ISSUE THREAD

**Issue by hell-io** [nocodb/nocodb#2294]
**Project info**

```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.91.1**
```

**Steps To Reproduce**

1. Create a Formula column
2. Type in `CONCAT('?', 'x')`
3. SQL query fails with an error "could not determine data type of parameter $1": `CONCAT('$1', 'x')`

**Expected Behavior**

`CONCAT` formula function should handle '?' characters.

**Comment by o1lab** [comment]
Things to probably handle `?` and `??`
