### ISSUE TITLE
Project Invite: Lost admin access to my project

### ISSUE THREAD

**Issue by ed-parsadanyan** [nocodb/nocodb#2301]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.91.7**
```

1. Go to Team&Auth -> User management -> New User
2. Invite Team: by accident entered the same email as the admin account, but picked the role "viewer"
4. Clicked 'Invite' and now due do access restrictions don't see anything. It seems that I downgraded myself.

**Expected Behavior**

An error that the user already exists

**Comment by o1lab** [comment]
If user exists, the invite leads to update of the user role. We should send back an error that `user@gmail.com exists with these roles editor.. etc`

**Comment by ed-parsadanyan** [comment]
@o1lab Thanks! is there a way how to get access back? Do I need to change something in postgres DB directly?

**Comment by wingkwong** [comment]
@ed-parsadanyan Seems behind the scene it didn't change the roles in DB but in cache. In this case, you may just restart the application so that you'd get the correct cache.

**Comment by ed-parsadanyan** [comment]
@wingkwong Thanks! I can confirm that
`sudo docker-compose stop
sudo docker-compose up -d
`

resolved the access issues
