### ISSUE TITLE
REST API JSON output limited to 1000

### ISSUE THREAD

**Issue by fishnux** [nocodb/nocodb#2306]
```
NocoDB used as docker : true 
NocoDB version : 
Database used in NC_DB URL  : mysql 
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : (unsure)
OS on which NocoDB is running : Linux
Node.js version if running as node : As Docker
Database version : Unsure
```

**Steps To Reproduce**

Do a Get All REST API with limit 10000 offset 0 on table that has more than 1000 rows

**Expected Behavior**

Returns more than 1000 rows (assuming table has about 4000 rows)

Defined ENV variables:
```
DB_QUERY_LIMIT_MAX = 10000
DB_QUERY_LIMIT_DEFAULT = 100
```

**Comment by wingkwong** [comment]
@fishnux Given the ENV variables you've set, how many records you've got? 100?

**Comment by fishnux** [comment]
> @fishnux Given the ENV variables you've set, how many records you've got? 100?

I get exactly 1000 elements in the JSON, in the database I have about 4000 rows. The "PageInfo" also seemed to indicate all 4000 rows were returned (despite only having 1000 elements), though I don't remember for sure

**Comment by wingkwong** [comment]
Can you show us `pageInfo` in your returned json?

**Comment by fishnux** [comment]
> Can you show us `pageInfo` in your returned json?

```
{
  "totalRows": 4050,
  "page": 1,
  "pageSize": "10000",
  "isFirstPage": true,
  "isLastPage": true
}
```
