### ISSUE TITLE
Bug: Auto save changes

### ISSUE THREAD

**Issue by akhmerov** [nocodb/nocodb#233]
To reproduce:

1. Pull nocodb image (I have 1094f1cd43a8)
2. Run `sudo docker run -p 8080:8080 --rm nocodb/nocodb:latest`
3. Create an admin user, create a table.
4. Add an entry to the table.
5. Specify the entry title.
6. Create a new column in the table, observe that the entry disappears.

**Comment by o1lab** [comment]
What machine is this docker running on - google-cloud run / aws fargate / something similar ?

**Comment by akhmerov** [comment]
Right, sorry. That just a local ubuntu 21:04.

**Comment by o1lab** [comment]
AH, guess save has to be hit! We will improve this.

**Comment by nathanclayton** [comment]
Would it be possible to have it auto-save by default, with the option to disable it? That way when you move from one row to another, it would automatically save any new entries/changes. Another helpful UI change would be changing the background of unsaved rows to something like a light grey to indicate that it still needs to be saved.

**Comment by pranavxc** [comment]
We are working on this 👍

**Comment by pranavxc** [comment]
Autosave is enabled in `0.10.1`
