### ISSUE TITLE
error importing CSV file ; can't access property "WBProps" e.wb.Workbook is undefined

### ISSUE THREAD

**Issue by clach04** [nocodb/nocodb#2334]
**Please enter the following details**

Copy and Paste Project Info - Tutorials: How to check my Project info? ([YouTube Tutorial](https://www.youtube.com/watch?v=AUSNN-RCwhE) or [Documentation](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-))

```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.91.7**
```

or provide the following info

```
NocoDB used as docker : true
```

**Steps To Reproduce**

1. Add/Import
2. CSV file
3. See error `can't access property "WBProps" e.wb.Workbook is undefined`

![image](https://user-images.githubusercontent.com/424032/173209183-3d477026-8cfd-4238-9442-cfca8934fd88.png)

![image](https://user-images.githubusercontent.com/424032/173209189-c9bbe0d0-0f8b-4db6-92b7-8c71b2778878.png)

**Expected Behavior**

Something that user can react to.

Best guess is the string/date read is failing.

Attached super small test file

[test_date.csv](https://github.com/nocodb/nocodb/files/8884947/test_date.csv)

    01/14/2020 7:06 AM

**Screenshots**

If applicable, add screenshots to help explain your problem. - see above

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by elvus** [comment]
Hi @clach04 try without the slash

**Comment by o1lab** [comment]
There appears no header in the csv.

**Comment by clach04** [comment]
> There appears no header in the csv.

Confirmed, see description and attachment

**Comment by clach04** [comment]
Someone messaged me with a suggestion to replace the `/` in the date to `-` That does avoid the error. I.e.:

    01-14-2020 7:06 AM

Instead of:

    01/14/2020 7:06 AM

Which is a US date format.
