### ISSUE TITLE
Can't delete the table after import csv as DateTime with SQLite

### ISSUE THREAD

**Issue by elvus** [nocodb/nocodb#2347]
```
Node: **v16.13.2**
Arch: **x64**
Platform: **Windows 10**
Docker: **false**
Database: **sqlite**
```
**Steps To Reproduce**
1. Go to Add/import
2. Click on csv file
[Table B_exported_1.csv](https://github.com/nocodb/nocodb/files/8894502/Table.B_exported_1.csv)
3. Change the column type as DateTime
4. See the bug

https://user-images.githubusercontent.com/24416449/173446989-8d14260b-f718-48fd-885a-74fbd0e719bb.mp4

**Comment by o1lab** [comment]
We will take a look.

Could you pls try it on non-sqlite db. SQLite db kinda accepts any value.

**Comment by elvus** [comment]
The error happen only with SQLite, with another db it work's
