### ISSUE TITLE
Shared base can't be put offline

### ISSUE THREAD

**Issue by dib0** [nocodb/nocodb#2358]
Once a share base link is generated, it can't be "removed". By sharing the base a link is generated. If after that the setting is changed to "Disable shared base", the old link will keep working. So there is no way, after generating a link to put that offline. Since the data is available for people without access rights, this could lead to unwanted disclosure of information.

```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.91.7**
```

**Steps To Reproduce**

1. Go to a project
2. Click on 'Share' (top right corner)
3. Set shared base to "anyone with a link"
4. close and test the share link (I used a private browser window for this)
5. Click on 'Share' again
6. Set to 'Disable shared base'
7. Close and test the previous link (keep working)

**Expected Behavior**

I would expect that the link would stop working after disabling the shared base.

**Comment by wingkwong** [comment]
Will take a look.
