### ISSUE TITLE
Import Airtable : Out of range issue on DECIMAL column

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#2363]
I try to import an Airtable table wich contains a number column.
I get an error when value equals to '361000000.00'.

```
NocoDB used as docker : true
NocoDB version : 0.91.7
Database used in NC_DB URL  : mysql 
Project was created  by clicking : New Project
Database version :  mariadb:10.7.4-focal
```

**Steps To Reproduce**

Try to import Airtable base with number column contains big value.

** Error in logs **

Out of range value for column '{my_colum_name}' at row 9

**Comment by o1lab** [comment]
Thank you for the report. Will get a fix for you to test - could you pls ping me on [discord](http://discord.nocodb.com).

You can DM me for any help

**Comment by dstala** [comment]
Datatype being treated as Decimal in MySQL has a limit of 10 digits.

**Comment by pranavxc** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/2368
