### ISSUE TITLE
Airtable to NocoDB: User already exists error while migrating 

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2370]
v0.91.9

**Comment by o1lab** [comment]
Error occurs when same user email exists as collaborator in airtable.

**Comment by Cirsten** [comment]
I'm still getting this errot using v0.91.9

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.91.9**

I think is same error?

This is being done via Heroku install

![nocodb error](https://user-images.githubusercontent.com/105973951/173710517-36cce8dc-5804-47f9-85cf-b7cf9718cd18.PNG)

**Comment by Cirsten** [comment]
as part this error it imports the tables and table structure but not the data (ie all have zero rows/records)

**Comment by mertmit** [comment]
@Cirsten those changes are not released (still in develop branch), you can expect them in next one
