### ISSUE TITLE
[Feature] Collaborator field (Link to User)

### ISSUE THREAD

**Issue by rallisf1** [nocodb/nocodb#2382]
**Need for this feature**
Hello, I am building a web app and using NocoDB as the backend as it eliminates the need for a dashboard. In my web app I am using the built-in users and auth API to log in the users keeping their token in their session etc.

What I feel lacking is the ability to link the users to an actual data table. In my case users they are clients and they have company info, address, orders etc. At the moment I treat their email as a PK and make an extra call to my `Client` table quering that.

**Is your feature request related to a problem? Please describe.**
 This does have its drawbacks though:

* Duplicate data (the email field)
* Updates / Deletes not cascading (can be solved via webhooks)

**Describe the solution you'd like**
New field type `User Link` which shall list the current project's users for (single?) selection. Also make the link info available to the `/auth/user/me` API endpoint.

**Comment by shahidcodes** [comment]
+1

**Comment by marlocarlo** [comment]
+1

**Comment by diegomm796** [comment]
+1

**Comment by dstala** [comment]
will be available from next feature release scheduled by end of this month
