### ISSUE TITLE
Display picture from connected table has wrong size

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#2392]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux (QNAP TS-251)**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.91.10**
DataBase Version: **MariaDB 10.5.8**

**Steps To Reproduce**

1. In table "Arztadressen" set pictures of doctors
2. Create link from "Impfbuch Werner" to "Arztadressen"
3. Set column in table "Impfbuch Werner" to show picture from table "Arztadressen"
4. In connected table "Impfbuch Werner" the picture from table "Arztadressen" isn´t shown completely

**Expected Behavior**

In table "Impfbuch Werner" the picture should have the same size like in original "Arztadressen"

**Screenshots**

![Bild1](https://user-images.githubusercontent.com/20600342/174043446-7864e80f-7ed7-4d1f-96d1-132672db2615.jpg)
![Bild2](https://user-images.githubusercontent.com/20600342/174043449-24e897b0-7e95-4a76-98c1-4d9982369f26.jpg)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by o1lab** [comment]
I think the bubble on LTAR, Lookedup columns should be handled better.
