### ISSUE TITLE
Inflection: none is still capitalising words in some places

### ISSUE THREAD

**Issue by pauljura** [nocodb/nocodb#2406]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mssql**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.91.10**
```

**Steps To Reproduce**

1. I create a new project with an existing database (tables are all lowercase) and choose "none" for inflection of table and columns
2. Table names in the left nav are lowercase, the name of the default grid view is lowercase, but the tab title is capitalised. e.g. I have a table "user" but the title of the tab is "User".
3. Column names are lowercase in the grid view, but when I expand a row, the column names are all capitalised in the dialog box
4. Column names are capitalised in gallery view, and form view

**Expected Behavior**

I expect table names and columns to be use the table and column choice for inflection in all places.

There is no option for inflection of the project title, but it gets capitalised regardless. No option is needed here, the user can capitalise it however they wish and it should remain as entered.

**Comment by o1lab** [comment]
I believe this is happening only at UI level.

**Comment by pauljura** [comment]
Correct. Yes, I should have made it clear. I am using nocodb to view an existing database (not create or modify) and so I would like to see table names and columns exactly as they are already capitalised.

**Comment by lublak** [comment]
I would be interested in that as well. Since I can not do much with the standard naming.

**Comment by dstala** [comment]
not observed in release v0.105.3
reopen this issue if you still notice this behaviour

**Comment by pauljura** [comment]
Looks good, thank you.
