### ISSUE TITLE
Confusing "Sign up" button loading state

### ISSUE THREAD

**Issue by yurkobb** [nocodb/nocodb#241]
EDIT: See first comment below.

Hi! While trying to explore nocodb I hit an issue on superuser sign up: as soon as I input a password, the Signup button freezes in an inactive loading state. This happens in Firefox an Chromium.

I run nocodb with the following command:
`podman run -d --name nocodb -p 8080:8080 --net=host nocodb/nocodb`

(I need `--net=host` to access a database running on the host, in fact `-p` is redundant in this case.)

In the logs I can see a suspicious 404: `POST /api/v1/auth/refresh-token 404 165 - 1.007 ms`.

![Screenshot 2021-06-07 at 09-58-56 Sign Up Noco](https://user-images.githubusercontent.com/479389/120974051-5ae6a500-c778-11eb-8ea4-6770c9e8ec0f.png)

<details><summary>Full log</summary>
<pre>
App started successfully.
Visit -> http://localhost:8080/dashboard
GET / 302 64 - 13.886 ms
GET /dashboard 301 185 - 2.510 ms
GET /dashboard/ 200 2855 - 6.491 ms
GET /dashboard/_nuxt/3905e44.js 200 3732 - 10.191 ms
GET /dashboard/_nuxt/44db1cc.js 200 209471 - 8.751 ms
GET /dashboard/_nuxt/6bd9d66.js 200 245540 - 8.778 ms
GET /dashboard/_nuxt/be8fb6e.js 200 1897780 - 8.907 ms
GET /dashboard/_nuxt/333a606.js 200 29825 - 5.407 ms
GET /dashboard/_nuxt/dfacdf9.js 200 27029 - 5.999 ms
GET /dashboard/_nuxt/5641aa5.js 200 72112 - 2.332 ms
POST /dashboard/?q=sqlOp_xcPluginRead 401 70 - 2.995 ms
POST /api/v1/auth/refresh-token 404 165 - 1.723 ms
GET /dashboard/auth/type 200 222 - 2.280 ms
GET /dashboard/favicon-32.png 200 1749 - 1.744 ms
GET /dashboard/ 304 - - 2.833 ms
GET /dashboard/_nuxt/3905e44.js 304 - - 6.835 ms
GET /dashboard/_nuxt/44db1cc.js 304 - - 8.020 ms
GET /dashboard/_nuxt/be8fb6e.js 304 - - 7.614 ms
GET /dashboard/_nuxt/6bd9d66.js 304 - - 7.398 ms
GET /dashboard/_nuxt/333a606.js 304 - - 4.110 ms
GET /dashboard/_nuxt/dfacdf9.js 304 - - 3.484 ms
GET /dashboard/_nuxt/5641aa5.js 304 - - 1.759 ms
POST /dashboard/?q=sqlOp_xcPluginRead 401 70 - 1.330 ms
POST /api/v1/auth/refresh-token 404 165 - 1.214 ms
GET /dashboard/auth/type 304 - - 2.357 ms
GET /dashboard/db/mysql.png.jpg 200 3132 - 12.526 ms
GET /dashboard/db/mssql.png.jpg 200 3619 - 12.299 ms
GET /dashboard/db/postgre.png.jpg 200 3892 - 11.900 ms
GET /dashboard/db/maria.png.jpg 200 3304 - 11.474 ms
GET /dashboard/db/aurora.png 200 2511 - 10.915 ms
GET /dashboard/_nuxt/img/512x512-trans.5601bce.png 200 246642 - 12.990 ms
GET /dashboard/db/sqlite.svg 200 9886 - 2.777 ms
GET /dashboard/_nuxt/c66fc74.js 200 21982 - 1.985 ms
GET /dashboard/_nuxt/fonts/MaterialIcons-Regular.12a47ed.woff2 200 60840 - 7.764 ms
GET /dashboard/_nuxt/fonts/materialdesignicons-webfont.2ec256c.woff2 200 224348 - 5.941 ms
GET /dashboard/ 200 2855 - 1.901 ms
GET /dashboard/_nuxt/3905e44.js 200 3732 - 8.117 ms
GET /dashboard/_nuxt/6bd9d66.js 200 245540 - 8.354 ms
GET /dashboard/_nuxt/44db1cc.js 200 209471 - 9.396 ms
GET /dashboard/_nuxt/be8fb6e.js 200 1897780 - 8.768 ms
GET /dashboard/_nuxt/c66fc74.js 200 21982 - 2.114 ms
POST /dashboard/?q=sqlOp_xcPluginRead 401 70 - 1.125 ms
GET /dashboard/favicon-32.png 200 1749 - 1.693 ms
POST /api/v1/auth/refresh-token 404 165 - 3.090 ms
GET /dashboard/auth/type 200 222 - 2.233 ms
GET /dashboard/_nuxt/333a606.js 200 29825 - 3.842 ms
GET /dashboard/_nuxt/dfacdf9.js 200 27029 - 3.703 ms
GET /dashboard/_nuxt/fonts/MaterialIcons-Regular.12a47ed.woff2 200 60840 - 8.130 ms
GET /dashboard/_nuxt/5641aa5.js 200 72112 - 8.410 ms
GET /dashboard/_nuxt/fonts/materialdesignicons-webfont.2ec256c.woff2 200 224348 - 7.499 ms
GET /dashboard/_nuxt/img/512x512-trans.5601bce.png 200 246642 - 8.860 ms
GET /dashboard 301 185 - 1.424 ms
GET /dashboard/ 200 2855 - 1.346 ms
GET /dashboard/_nuxt/3905e44.js 200 3732 - 2.546 ms
GET /dashboard/_nuxt/44db1cc.js 200 209471 - 4.712 ms
GET /dashboard/_nuxt/6bd9d66.js 200 245540 - 4.884 ms
GET /dashboard/_nuxt/be8fb6e.js 200 1897780 - 5.292 ms
GET /dashboard/_nuxt/333a606.js 200 29825 - 3.798 ms
GET /dashboard/_nuxt/dfacdf9.js 200 27029 - 3.443 ms
GET /dashboard/_nuxt/5641aa5.js 200 72112 - 1.940 ms
POST /dashboard/?q=sqlOp_xcPluginRead 401 70 - 1.148 ms
POST /api/v1/auth/refresh-token 404 165 - 1.007 ms
GET /dashboard/auth/type 200 222 - 1.519 ms
GET /dashboard/favicon-32.png 200 1749 - 1.883 ms
GET /dashboard/db/mysql.png.jpg 200 3132 - 11.375 ms
GET /dashboard/db/mssql.png.jpg 200 3619 - 11.608 ms
GET /dashboard/db/postgre.png.jpg 200 3892 - 12.592 ms
GET /dashboard/db/maria.png.jpg 200 3304 - 12.317 ms
GET /dashboard/db/aurora.png 200 2511 - 12.221 ms
GET /dashboard/_nuxt/img/512x512-trans.5601bce.png 200 246642 - 15.611 ms
GET /dashboard/db/sqlite.svg 200 9886 - 3.870 ms
GET /dashboard/_nuxt/c66fc74.js 200 21982 - 1.605 ms
GET /dashboard/_nuxt/fonts/MaterialIcons-Regular.12a47ed.woff2 200 60840 - 6.683 ms
GET /dashboard/_nuxt/fonts/materialdesignicons-webfont.2ec256c.woff2 200 224348 - 5.418 ms
</pre>
</details>

**Comment by yurkobb** [comment]
Hm, I was confused by the presence of the loading indicator - it seemed as though it is waiting for something on the network. When I input a randomly generated password satisfying the "Atleast..." requirements, the button became active again.

**Comment by idodav** [comment]
Saw it as well. This screen needs a fix.

**Comment by idodav** [comment]
fixed in pull request:
https://github.com/nocodb/nocodb/pull/257
waiting for approval
