### ISSUE TITLE
[FORM VIEW] Required fields can be blank

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#2412]
NocoDB used as docker : true 
NocoDB version : 0.91.9
Database used in NC_DB URL  :  pg
Project was created  by clicking : Import from Airtable
Database on which spreadsheet is created :  pg
Database version : 14-3

**Steps To Reproduce**

1. Create a simple form view on a table
2. Add one input type text, or number, or selected
3. make this fields as required

![image](https://user-images.githubusercontent.com/45880189/174270439-422e47a7-9471-4119-ac33-9d60fe696ff8.png)

4. Save the form view.
5. With an other user, use the form view
6. Click on submit button without fill the field
7. An empty row is added

**Expected Behavior**

I expect to see an error like 'this field is required', and no line record in table

**Comment by wingkwong** [comment]
Without other users or adding new fields, setting existing columns to required would also be able to reproduce the issue.
