### ISSUE TITLE
🐛 Bug: The server closed the connection

### ISSUE THREAD

**Issue by whyteserious** [nocodb/nocodb#2417]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.91.10**

NocoDB used as docker : true
NocoDB version : 0.91.10
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : Centos 7.4
Node.js version if running as node : 
Database version : 5.7

**Steps To Reproduce**

1.  remote connections accessing databases，use docker run command
     docker run -d --name=nocodb --restart always -v nocodb:/usr/app/data \
     -e NC_DB="mysql2://remote host:port?u=noco&p=password&d=noco_db" \
     nocodb/nocodb:latest 
2. visit localhost successfully。
3. page not closed，idle for about 2 hours，then add table andimport csv error。
```
GET /api/v1/db/meta/nocodb/info 400 104 - 8.242 ms
R :: Error: select * from `nc_models_v2` where `project_id` = 'p_bb896rlmj2ron9' and `base_id` = 'ds_4yzk0quzj8cyp3' order by `order` asc - Can't add new command when connection is in closed state
```
**Expected Behavior**

Problem solving after restart docker 
Database provided by DBA
I don't know whether it is a database configuration problem or a code problem

**Screenshots**

![add bug](https://user-images.githubusercontent.com/42569476/174305728-33fa1a0c-298c-4911-8745-072ef9b18af7.png)
![bug](https://user-images.githubusercontent.com/42569476/174305734-b0096e8c-8225-49f6-b537-59784c81b748.png)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by dstala** [comment]
> I don't know whether it is a database configuration problem or a code problem
@whyteserious , doesn't look like a database configuration problem. could be something associated with session timeout. thanks for bringing this to our notice.

> page not closed， idle for about 2 hours， then add table and import CSV error。
Just to confirm: The error you notice is after the session was idle for 2 hours and you tried to add a table on the UI. Please correct me.

**Comment by whyteserious** [comment]
The translation software used will have errors in understanding. The following supplementary instructions:

1. Around 4:00, start the container, visit the web page, register the administrator, configure SMTP, and invite new user by email.

2. around 4:30, a new user registers, and then he does other things. The web page is idle.

3. At about 6:30, he reported an error using the import table function and the new table function.

4. After 7 o'clock, I logged in to the environment to troubleshoot the problem. I couldn't log in to nocodb and recovered after restarting.

Its service is normal when I send messages.


By the way

1.Where there are no role settings.   The super administrator registered for the first time is different from the traditional root authority.    The permissions of creator and owner are different from those specified in the document.
   
Examples：admin invite creator，creator add a project，admin has no permission for new project.
                   who create the project, who is the owner.

4.If MySQL is used but no database is specified, an error will be reported that the database cannot be created.
![mysql_bug](https://user-images.githubusercontent.com/42569476/174415393-6c30f2c4-1af1-43eb-82ba-5b031f08df40.png)

5.The import / export function is not very friendly to Chinese.

The above does not affect the use. Maybe it can be improved.

**Comment by dstala** [comment]
@whyteserious - if you notice this issue even with latest release, reopen;
