### ISSUE TITLE
could nocodb consider use dual licence?

### ISSUE THREAD

**Issue by joebnb** [nocodb/nocodb#243]
gnu contains some risk in commercial could this to be supported

**Comment by zpl** [comment]
There is also problem for me. I can't use AGPL projects for my work. but probably I can buy commercial license

**Comment by o1lab** [comment]
AGPL doesnt stop you from commercial usage. Only if you change nocodb source code - you have to open soruce the code. And if included within another project that source code becomes AGPL.
