### ISSUE TITLE
issue while upgrading from 0.84.14 to 0.91.10 - migration failed

### ISSUE THREAD

**Issue by amarnath-wego** [nocodb/nocodb#2449]
**Please enter the following details**

```
NocoDB used as docker : true 
NocoDB version : **0.84.14**
Database used in NC_DB URL  : pg 
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql 
OS on which NocoDB is running : Linux
```

**Steps To Reproduce**

I have projects already running on 0.84.14, so upgrading the version to 0.90.0 provides with 
<img width="1407" alt="Screenshot 2022-06-22 at 9 02 41 AM" src="https://user-images.githubusercontent.com/88304484/174990109-9be1b6d0-41f9-490f-bbf8-c74eb2f25b75.png">

i was able to reproduce the issue locally as well. 
1. Run command below:
```
docker run -d -p 8080:8080 \
    -e NC_DB="mysql2://host.docker.internal:3306?u=root&p=password&d=d1" \
    -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
    nocodb/nocodb:0.90.0
```
2. go to, localhost:8080
3. cant get /dashboard

i have attached my ecs logs here as well.
[log-events-viewer-result.csv](https://github.com/nocodb/nocodb/files/8956179/log-events-viewer-result.csv)

**Comment by o1lab** [comment]
Pls try upgrading the latest one 0.91.10 - a lot of upgrade issues have been ironed out since 0.90.0.

**Comment by pranavxc** [comment]
@amarnath-wego : Hi can you share the Nocodb docker version of the attached log file? It could be helpful to debug if you can share that version.
