### ISSUE TITLE
BullMQ: DEPRECATION WARNING! Your redis options maxRetriesPerRequest must be null.

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#2452]
Reported by Vijay - Message thrown after starting the app

```
2022-06-21 15:06:39BullMQ: DEPRECATION WARNING! Your redis options maxRetriesPerRequest must be null. On the next versions having this settings will throw an exception
```

**Comment by hassanhafiz44** [comment]
I'm still getting this error. my bullmq version is `1.87.0`

**Comment by kthehatter** [comment]
I'm still getting this error. my bullmq version is 4.7.0

**Comment by seolhw** [comment]
I'm still getting this error. my bullmq version is 4.12.5

**Comment by DevWonder01** [comment]
Still getting this error, Nov 4 2023 :(

**Comment by digitalextremist** [comment]
Still required @DevWonder01 solution as of "2024 Q2"

**Comment by DYW972** [comment]
Yo !

I was getting the error today and I fixed it following @DevWonder01 solution.

Thanks !

**Comment by satyam7world** [comment]
> Yo !
> 
> I was getting the error today and I fixed it following [@DevWonder01](https://github.com/DevWonder01) solution.
> 
> package : `"bullmq": "^5.41.5",`
> 
> Thanks !

Fixed after changing redis imports 

removed Redis
import Redis from 'ioredis';

and added IO

import IORedis from 'ioredis';

const redisC = new IORedis({
  maxRetriesPerRequest: null,
});

**Comment by DevWonder01** [comment]
> > Yo !
> > I was getting the error today and I fixed it following [@DevWonder01](https://github.com/DevWonder01) solution.
> > package : `"bullmq": "^5.41.5",`
> > Thanks !
> 
> Fixed after changing redis imports
> 
> removed Redis import Redis from 'ioredis';
> 
> and added IO
> 
> import IORedis from 'ioredis';
> 
> const redisC = new IORedis({ maxRetriesPerRequest: null, });

Happy to help ser💯

**Comment by Kingestif** [comment]
The issue is caused b/c bull automatically attempt to handle you job multiple times and sometimes it might exceed the limit 

FIX: update your code like this

const connection = new IORedis({maxRetriesPerRequest:null})
