### ISSUE TITLE
Can't change column type from Decimal to Number

### ISSUE THREAD

**Issue by Cirsten** [nocodb/nocodb#2479]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.91.10**

**Steps To Reproduce**

1. Go to table
2. Click on column drop down list, Edit, Column Type, Number, Save 
3. See error: Failed to save column: Error: Request failed with status code 400

**Expected Behavior**
Column to change from Decimal to Number
The column already only hold numbers, so shouldn't be a conflict

**Comment by wingkwong** [comment]
Couldn't reproduce on my side. Could you please provide the detailed error messages from backend logs to give more insights?

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.91.10**
```

![image](https://user-images.githubusercontent.com/35857179/175756120-a97ba870-7b0c-4a44-a7d4-87e0233cb718.png)

**Comment by Cirsten** [comment]
Hopefully this has the info you need

[cirstennocodb-logs-1656151219215.txt](https://github.com/nocodb/nocodb/files/8984448/cirstennocodb-logs-1656151219215.txt)

**Comment by wingkwong** [comment]
The fix should've covered in https://github.com/nocodb/nocodb/pull/2411. Please try on the latest version. Feel free to reopen if it's still reproducible.
