### ISSUE TITLE
Field Check Boxes Unresponsive on Android

### ISSUE THREAD

**Issue by Cirsten** [nocodb/nocodb#2480]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.91.10**

**Steps To Reproduce**

1. Go to table on android
2. Click on Fields
3. See error: the check boxes don't respond to selection

This error occurs whether you're using a normal view or "Desktop Site" view

The "show all" and "hide all" buttons work

**Expected Behavior**
Check boxes to change with selection

**Comment by mertmit** [comment]
I couldn't reproduce, which browser are you using? Can you change order of columns?

**Comment by Cirsten** [comment]
Was using  chrome, on two separate devices
Are using instalked via Heroku

I can change the order of columns

**Comment by o1lab** [comment]
It works since vue3 release. Can be closed.
