### ISSUE TITLE
Docker failing on Apple with M1 chip

### ISSUE THREAD

**Issue by go4cas** [nocodb/nocodb#249]
When starting a nocodb Docker container, on an Apple MackBook with M1 (ARM64) chip, I get the following:
"**_The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested_**".

**Comment by maxnatt** [comment]
Duplicate of the https://github.com/nocodb/nocodb/issues/183.

**Comment by azrikahar** [comment]
@go4cas Hi, I've recently tried to help out and created an arm64 variant of nocodb image over at https://hub.docker.com/r/azrikahar/nocodb. Would you mind helping to test whether it works for you? After that we will be able to merge it into nocodb officially

**Comment by go4cas** [comment]
@azrikahar ... it is working 100%! Thank you very much!!

**Comment by Hu-Wentao** [comment]
replace `image: "mysql:5.7"`to `image: "mariadb:10.5.8"`
because mysql 5.7 not support arm64/v8
