### ISSUE TITLE
Unexpected errors when switching between tables

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#2494]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.91.10**

**Steps To Reproduce**

1. Go to 'Tables'
2. Click on a specific table.
3. See error (Screenshots included)

**Expected Behavior**

We expect to see the tables without any errors; but when we open some tables, we encounter red boxes indicating errors.

**Screenshots**

![Screenshot (1)](https://user-images.githubusercontent.com/100111649/176104576-89523ebd-9dfe-4d0c-9d94-f6c7c0cdbda1.png)

![Screenshot (2)](https://user-images.githubusercontent.com/100111649/176104604-cf8398d8-e81b-4153-a4d2-15a01d4ddd65.png)

**Comment by dstala** [comment]
@okaeiz will it be possible to share a sample DB file with data redacted?

**Comment by pranavxc** [comment]
Can you check following details and share more information

- Is there a column named `title` in the table?
- Can you share the server log as well ? which may have more information helpful for us to debug.
- Open `Meta sync` under `Team & settings` and confirm it doesn't show any changes.

**Comment by pranavxc** [comment]
> I headed to Team & Settings and then Meta sync; there were changes available so I had to sync the data. There were also a column in one of the tables which was named "Title" so I removed it. Now the problems seems to be solved but the question is this: doesn't NocoDB sync the data automatically? Do I have to sync the data manually after every single change?

If you are doing the changes from NocoDB GUI then there is no need for syncing. In case you had modified DB from any external tool then you have to do the sync manually which we don't recommend. 

If you had only done the changes using NocoDB sdk/GUI and facing the problem then, please share the steps to reproduce the problem and we will look into it.

**Comment by dstala** [comment]
@okaeiz marking this issue as resolved. reopen if you have any queries still
