### ISSUE TITLE
[Feature] nc-help, nc-common source cod

### ISSUE THREAD

**Issue by Bigezno** [nocodb/nocodb#2504]
Please tell me what I can see the source code of ne-help and nc-common module ?

**Comment by Bigezno** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/24370504/176393536-8bf0ed60-0902-4028-a4e5-7857bf9559c8.png">
I want to read the code for NC-Help and learn about the use of SqlClientFactory and so on

**Comment by Bigezno** [comment]
@janrito ，please🙏

**Comment by o1lab** [comment]
Can u elaborate what are your requirements please ?

**Comment by Bigezno** [comment]
@sesam @blucky
