### ISSUE TITLE
Suspected Memory Leak

### ISSUE THREAD

**Issue by boscodtt** [nocodb/nocodb#2510]
```
Node: **v12.22.10**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.84.15**
```

**Steps To Reproduce**

1. Start AWS ECS using nocodb docker image
2. Use nocodb a few days
3. memory usage increase steadily until 100% memory usage
4. ECS crashed and cycle repeated

**Expected Behavior**

nocodb will free up memory usage

**Screenshots**

![image](https://user-images.githubusercontent.com/95273176/176591957-51da80a4-24ab-4d5c-9f9f-3563aab07fea.png)

**Comment by wingkwong** [comment]
Lemme DM you.

**Comment by wingkwong** [comment]
It seems that the memory setup is not enough for your scenario. Can you share how much memory you've arranged (i.e. `memory` in your task definition file)? If your container attempts to exceed the memory specified here, the container is killed.

**Comment by wingkwong** [comment]
In case there's other people facing the memory issue and using node app. Try to pass `max-old-space-size`.

Example: 

```
node --max-old-space-size=4076 server.js
```

**Comment by o1lab** [comment]
Would helpful to know the usage scenario like
- How many projects are there ?
- How many tables are there ?
- Number of API requests over that period ?

**Comment by boscodtt** [comment]
In our scenario, we have 2 projects, 77 tables in total.

Around 53996 (GET) and 10229 (POST) request logged from 2022-06-12 to 2022-06-21.

**Comment by letianwei** [comment]
@wingkwong @o1lab  Dear both, may i know if there have any updates? thank you!

**Comment by letianwei** [comment]
@wingkwong @o1lab Dear both, may i know if there have any updates? any suggestion? thank you!

**Comment by wingkwong** [comment]
@letianwei Lemme get back to you in the afternoon.

**Comment by o1lab** [comment]
There are several customers running noco seamlessly, hard to tell from the above what is the reason. 

Plus your noco version is 0.84.15 and the current version is 0.92.x - there are significant architectural changes. Any reason for not upgrading it ?

**Comment by dstala** [comment]
@boscodtt closing issue for now. please reopen if issue persists after upgrading to latest release.
