### ISSUE TITLE
Wrong records shown when several tables are linked together

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#2512]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.91.10**

**Steps To Reproduce**

1. Create 2 tables.
2. In one of the tables, create a column which is of "Formula" type. The formula is "CONCAT" and is used to concatenate the first name and last name of people. ( e.g. CONCAT({firstname}, " ",{lastname} ) which results in "firstname lastname" ). 
3. In the another table, create a column with LinkToAnotherRecord type and link it to the first table.
4. Then, if you want to choose a person in the 2nd table from the first table, their name is not shown properly. Instead, it shows a string which is likely to be a datetime. ( screenshots included )

**Expected Behavior**

We expect to be able to choose the records from the destination table by the name we have assigned; but instead of seeing names, we see a nonsense string.

**Screenshots**

This is the first table (when the interface language is Persian); We have written a formula to join the first name and last name of people together.

![Screenshot (4)](https://user-images.githubusercontent.com/100111649/176599780-34245e63-773d-4bc6-a82b-894867ffef5b.png)

This is the first table (when the language interface is English); the picture is the same as the one above.

![Screenshot (5)](https://user-images.githubusercontent.com/100111649/176600026-c5f8aec7-27e4-43aa-a062-ba6f9f249f26.png)

This is what we see when we try to choose records in the 2nd table ( using LinkToAnotherRecord ). Instead of seeing Persian names, we see something like a datetime.

![Screenshot (6)](https://user-images.githubusercontent.com/100111649/176600210-25f6b08a-0c49-4af0-83d7-8b0b32a79e64.png)

**Comment by wingkwong** [comment]
Have you chosen the correct [Primary Value](https://docs.nocodb.com/setup-and-usages/primary-value)?

**Comment by okaeiz** [comment]
To fix this, I set the "last name" column to be the primary value. So it displays the last name only right now.
However, we can't set the first column (which is of Formula column type) to be the primary value. I have created an issue about this here:
https://github.com/nocodb/nocodb/issues/2285

**Comment by okaeiz** [comment]
Do you think it's because the strings are in Persian?

**Comment by wingkwong** [comment]
As Navi mentioned already in that PR, there's some limitations on Primary Value like you cannot set it on some columns such as Formula, LTAR Columns. Therefore, it's not related to Persian string at all. It's all about the column.
