### ISSUE TITLE
options not shown when choosing from a LTAR column

### ISSUE THREAD

**Issue by merrime-n** [nocodb/nocodb#2513]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.0**

**Steps To Reproduce**

1. Create two tables.
2. In one of the tables, create a LTAR column.
3. In the LTAR column, when you want to choose a record from the outer table, the record is not shown in the field.

**Expected Behavior**

We expect to choose the record and see what we have chosen in the field.

**Screenshots**

This is the LTAR column.

![first](https://user-images.githubusercontent.com/100111649/176620983-c7f82771-ce58-4068-945b-1adb0c40779f.PNG)

We choose a record from the linked table here.

![Screenshot (8)](https://user-images.githubusercontent.com/100111649/176621906-59d6caeb-c180-4238-98a4-c203cbaca482.png)

 
And the record is not shown in the field!

![Screenshot (9)](https://user-images.githubusercontent.com/100111649/176621761-1efe1195-638c-4f5a-bdde-81192054f616.png)

**Comment by wingkwong** [comment]
Please check logs to see if there is some detailed error messages to give more insight.

**Comment by okaeiz** [comment]
I checked the logs. There is nothing helpful.

**Comment by MGW-SumathyV** [comment]
Hi,

I am also facing the same issue . LTAR column(Many to Many) is not getting populated on selection. Moreover the selected value is getting deleted from the selection pop up which we get on clicking '+'.

Thanks and Regards,
Sumathy Venugopal
