### ISSUE TITLE
🐛 Bug: Form fields are loaded incompletely when the view is being shared

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#2514]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.0**

**Steps To Reproduce**

1. Go to 'Create a view'
2. Create a form
3. Hide some fields, show some other fields.
4. There are some annoying bugs here when we share the view. For instance, when the view is shared, sometimes none of the fields are shown. The strange thing in this case is the user can even submit the form even though they have not entered any piece of information. Sometimes some specific fields are shown and sometimes we cannot choose any option in LTAR fields. It's driving us crazy! 

**Expected Behavior**

We expect to create a custom form, hide some fields, share the view and have ALL our modifications applied. But the form is not loaded completely in most times.

**Screenshots**

We create the form, write labels and hide some unwanted fields here in the form builder.

![Screenshot (10)](https://user-images.githubusercontent.com/100111649/176628413-5bf96602-738b-4139-9b40-75cd14bf8dfd.png)

But when the view is shared, it's almost a different thing than what we created ( Moreover, the fonts have not been changed yet...! #2302 )

![Screenshot (11)](https://user-images.githubusercontent.com/100111649/176628760-1ec20536-b3dd-4328-a821-0b771faa697b.png)

**Comment by wingkwong** [comment]
Mind to record a video to show? It seems quite normal on my side.

![image](https://user-images.githubusercontent.com/35857179/176653376-abb43048-7126-4e05-aecc-2708e01b2985.png)

>  The strange thing in this case is the user can even submit the form even though they have not entered any piece of information.

If your form doesn't contain required field, technically users can submit a blank form.

**Comment by okaeiz** [comment]
> How does issue 1313 (excel import) relate to creating a form? Have you checked the logs to see if there is any useful error messages apart from `request failed with status code 400`?

I meant it outputs the same error in lots of spots. When importing different kinds of database or creating views and so on.
It has nothing to do with the so-called issue.

**Comment by wingkwong** [comment]
I think you misunderstood. The error `request failed with status code 400` is general. It can be thrown with different root causes. Issue 1313 is about excel import. The resolution there is not fixing all issues with such error but the one mentioned in that PR. To find out the exact problem, normally it comes with some detailed error messages from the network tab from browser or logs from backend.

**Comment by wingkwong** [comment]
Can you try restarting the application to see if it's due to cache problem?

**Comment by okaeiz** [comment]
We did restart the containers but it didn't work.

**Comment by wingkwong** [comment]
Can you check the following when getting the errors to see if you can have more error details.

- logs from backend
- network tab from browser

**Comment by okaeiz** [comment]
the problem exists in v0.92.3
I didn't find anything useful in the logs.

**Comment by wingkwong** [comment]
- Does row 2 - row 7 really have records? 
- If you create a table and do the same thing, is the issue still reproducible on the new table?

**Comment by okaeiz** [comment]
row 2 - row 7 are created after submitting an empty form, having filled none of the fields at all.
I deleted them now, the issue exists.
I also created a new table; the problem seems to be solved in the new table. But is there any guarantee that the problem will not appear in the future with the new table?

**Comment by wingkwong** [comment]
Can you try input the same data like the old table to see if it is caused by data problem?

**Comment by okaeiz** [comment]
I deleted the problematic table and create a new one with the same columns.
The problem seems to be fixed in the new column.

**Comment by wingkwong** [comment]
With the same data?

**Comment by okaeiz** [comment]
With the same MM relationships ( that are likely to cause the problem ).
But I'm afraid the problem will reappear.

**Comment by o1lab** [comment]
@okaeiz : are you still seeing this problem in latest version. Reason I ask : when submitted the version used is our old UI

**Comment by o1lab** [comment]
Feel free to reopen if reproducible.
