### ISSUE TITLE
Creating columns then renaming or arranging causes SQLITE_ERROR: no such column

### ISSUE THREAD

**Issue by drdomark** [nocodb/nocodb#252]
Hi,

When I create columns for table and rename or rearrange it then I get issue SQLITE_ERROR: no such column for random column names even if they exist. I tried debugging and issue I am getting from net is:
1- Either space in column names - I didn't find any space in column names in request nor given when defining
2- Or Use of quotes is causing issue like explained here https://stackoverflow.com/questions/52673703/error-sqlite-error-no-such-column-undefined

Steps to produce:
1- Create many columns like 8-10
2- Rename or rearrange the columns
3- Try inserting data - Get error while inserting
4- Refresh table view - Error could be seen in network call

**Comment by o1lab** [comment]
Thanks for the detailed report, steps & stackoverflow link.

Could you also please paste the error you see on terminal or browser console.

**Comment by drdomark** [comment]
The browser I am using is Firefox and sqlite database, in case issue exist for these

Query
msg: select `xa2__manga_chapters`.`id` as `id`, `xa2__manga_chapters`.`title` as `title`, `xa2__manga_chapters`.`created_at` as `created_at`, `xa2__manga_chapters`.`updated_at` as `updated_at`, `xa2__manga_chapters`.`Status` as `Status`, `xa2__manga_chapters`.`Content` as `Content`, `xa2__manga_chapters`.`Quotes` as `Quotes`, `xa2__manga_chapters`.`Images` as `Images`, `xa2__manga_chapters`.`Note` as `Note`, `xa2__manga_chapters`.`Category` as `Category`, `xa2__manga_chapters`.`Group` as `Group`, `xa2__manga_chapters`.`Links` as `Links` from `xa2__manga_chapters` limit 25 - SQLITE_ERROR: no such column: xa2__manga_chapters.Status

select `xa2__book_chapter`.`id` as `id`, `xa2__book_chapter`.`Book` as `Book`, `xa2__book_chapter`.`created_at` as `created_at`, `xa2__book_chapter`.`updated_at` as `updated_at`, `xa2__book_chapter`.`Chapter` as `Chapter`, `xa2__book_chapter`.`Category` as `Category`, `xa2__book_chapter`.`SubCategory` as `SubCategory`, `xa2__book_chapter`.`Group` as `Group`, `xa2__book_chapter`.`For` as `For`, `xa2__book_chapter`.`Tags` as `Tags`, `xa2__book_chapter`.`Rating` as `Rating`, `xa2__book_chapter`.`Score` as `Score`, `xa2__book_chapter`.`Links` as `Links`, `xa2__book_chapter`.`Vol` as `Vol`, `xa2__book_chapter`.`SubGroup` as `SubGroup`, `xa2__book_chapter`.`Section` as `Section`, `xa2__book_chapter`.`Status` as `Status` from `xa2__book_chapter` limit 25 - SQLITE_ERROR: no such column: xa2__book_chapter.Book

![Screenshot 2021-06-09 111511](https://user-images.githubusercontent.com/50301882/121300469-81414780-c914-11eb-85bf-c6641927ee16.jpg)
![Screenshot 2021-06-09 111626](https://user-images.githubusercontent.com/50301882/121300476-843c3800-c914-11eb-9fbe-138c2a4e5a28.jpg)
![Screenshot 2021-06-09 111704](https://user-images.githubusercontent.com/50301882/121300486-8605fb80-c914-11eb-829b-cf535041ac0d.jpg)

**Comment by o1lab** [comment]
Thank you that helps, we will take a look.

**Comment by ayushcsi** [comment]
Will renaming and edit column type be enabled in future versions? or is it locked forever?

**Comment by drdomark** [comment]
Will renaming and edit column type be enabled in future versions? or is it locked forever?

**Comment by pranavxc** [comment]
@drdomark column edit is not straightforward in SQLite. We have to recreate the table and then need to copy data for updating the column. Anyway, we will try to improve it.

**Comment by o1lab** [comment]
Just tested it out in latest release. This has been fixed.
