### ISSUE TITLE
API to views

### ISSUE THREAD

**Issue by alexkTWC** [nocodb/nocodb#253]
Exclusive API endpoints for different views on tables, respecting fields, sorting and filters applied to them.
I know when we filter then click on 'Copy API URL' it includes a `where` parameter on the URL but please do not use query params to do that, because for some scenarios the API needs to expose only the filtered results, not the entire table and can't allow who is consuming to have access to the entire table. Someone can easily remove the `where` parameter and see not allowed rows.

Ex.: Table Products, has all past offers (expired), and future (to be released).
The only results allowed to be fetched by a 3rd party are the active products.
It can be done filtering by date columns, if we have an API to that view.

- Product Table has: id_product, name, description, purchase_price, sale_price, release_date, expire_date
- View to product table has:  id_product, name, description, sale_price, expire_date (purchase_price is hidden) and there is a filter `TODAY() BETWEEN release_date AND expire_date`

**Comment by nocodb1** [comment]
We thought about this while implementing views.

**Comment by o1lab** [comment]
We thought about this while implementing views.

**Comment by alexkTWC** [comment]
Very important for a no-code solution

**Comment by alexkTWC** [comment]
Added details to the use case

**Comment by o1lab** [comment]
Available now - [see here](https://apis.nocodb.com/#operation/db-view-row-list)
