### ISSUE TITLE
Token ACL by API

### ISSUE THREAD

**Issue by alexkTWC** [nocodb/nocodb#254]
When creating authorization tokens, be able to select witch APIs each token can have access, for each verb:
- GET
- POST
- PUT
- DELETE

**Comment by alexkTWC** [comment]
- API table X
-- token abc123: GET, POST, PUT and DELETE
-- token zyx456: GET, POST
- API view Y (to table X)
-- token xpto321: GET

**Comment by alexkTWC** [comment]
Or... If we think on database views, it can only read data... So, an API to a view can only do GET...

**Comment by dstala** [comment]
to be tracked with https://github.com/nocodb/nocodb/issues/2707
