### ISSUE TITLE
API Authentication Failure

### ISSUE THREAD

**Issue by lhyphendixon** [nocodb/nocodb#2544]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.92.3**

Hey guys, I'm trying to get NocoDB connected in N8N and I'm having some issues.  Depending on which approach I use, I continue to get either 403 or 401 error when connecting the API.

![n8n-nocodb](https://user-images.githubusercontent.com/106199930/177014201-b1561acb-be12-4721-9285-1007c089a5a5.png)

The connection doesn't occur neither with the API Key nor the auth token. 

Further, and likely related, when I try to add the API key I've generated to the xcToken in the Swagger Doc as instructed in your guide, I click Authorize, then close, but it does not seem to actually save.  If I reload the page, that authorization is no longer there. 

Ultimately, I'm just at the start of this integration and am just trying to GET the first row of my NocoDB table to ensure the connection is working properly but am having no luck.  Any ideas?

**Comment by RawmanGrey** [comment]
This in n8n related - NocoDB node is deprecated there. HTTP node with xc-auth/xc-token header will work.

**Comment by o1lab** [comment]
n8n has added back the support now. Feel free to reopen if the issue exist in latest release
