### ISSUE TITLE
options not shown when choosing from a LTAR column (not solved yet)

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#2546]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.3**

**Steps To Reproduce**

1. Create two tables.
2. In one of the tables, create a LTAR column.
3. Create another grid view.
4. The MM relationship option is now shown in the first table, which is a grid view by default when created. But if we create another grid view, the MM relationship options is not shown in the column (recording included below).

**Expected Behavior**

We expect to choose the record and see what we have chosen in the field in ALL views of that table.

**Screenshots**

https://user-images.githubusercontent.com/100111649/177024663-43a0b53a-805a-4b70-8a10-bb47962eec61.mp4

**Comment by wingkwong** [comment]
If you expand the MM cell, would you see the option in an expanded form?

**Comment by okaeiz** [comment]
there aren't any options anywhere except the first Grid View (that is created automatically at first).

**Comment by wingkwong** [comment]
Just double confirm. I meant expanded list like this. Please check it for the first & second table.

![image](https://user-images.githubusercontent.com/35857179/177027532-ae16d8fb-04c3-4b3f-8ac2-63bb82f4fcb5.png)

**Comment by okaeiz** [comment]
my bad.
I expanded the list and the relation ID is visible there ( relation ID is the name of the column ).

**Comment by wingkwong** [comment]
Weird. I couldn't reproduce the issue. Could you please try to see if you can encounter the problem on the following execuable / image?

### Executables

#### MacOS

```bash
mkdir -p ./0.92.0/pr-2515-20220630-1010 && cd "$_" \
    && curl http://dl.nocodb.com/0.92.0-pr-2515-20220630-1010/Noco-macos-arm64 -o noco -L \
    && chmod +x noco \
    && ./noco
```
#### Linux

```bash
mkdir -p ./0.92.0/pr-2515-20220630-1010 && cd "$_" \
   && curl http://dl.nocodb.com/0.92.0-pr-2515-20220630-1010/Noco-linux-x64 -o noco -L \
   && chmod +x noco \
   && ./noco
```
#### Windows

```bash
iwp http://dl.nocodb.com/0.92.0-pr-2515-20220630-1010/Noco-win-arm64.exe
.\Noco-win-arm64.exe
```

### Docker

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.92.0-pr-2515-20220630-1010
```

**Comment by okaeiz** [comment]
Alright let me check it out.

**Comment by okaeiz** [comment]
It works fine in the image above.
I added a record and checked both grid views. I could see the options.

**Comment by wingkwong** [comment]
Weird. The latest release should include the same changes. Are you sure you were using 0.92.3? Probably try another browser as well.

**Comment by okaeiz** [comment]
I'm sure. I'm always eager to upgrade NocoDB as soon as a newer release is available.

**Comment by o1lab** [comment]
Feel free to reopen if the issue exist in latest release
