### ISSUE TITLE
PostgreSQL specific type "inet" looks as empty string on NocoDB

### ISSUE THREAD

**Issue by fishnux** [nocodb/nocodb#2556]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.92.3**

PostgreSQL specific type "inet" looks as empty string on NocoDB

<img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/29991194/177232235-98eda733-ab55-4a8f-b669-f8e87a974c8d.png">

**Comment by dstala** [comment]
@fishnux could you help us share more details. I tried connecting to a table with `inet` data type & it did show records.
![Screenshot 2022-07-05 at 11 31 44 AM](https://user-images.githubusercontent.com/86527202/177259971-cd4e12a6-1325-4ae6-b904-5583b525faed.png)
tried on PG 9.6

**Comment by fishnux** [comment]
I'm using PostgreSQL 12.4

I tried to re-add the database connection to NocoDB and it worked - inet column data started appearing again. I think some update broke the NocoDB schema or something

**Comment by dstala** [comment]
@fishnux closing this issue for now; please reopen if issue persists with latest release
