### ISSUE TITLE
🐛 Bug: `id primary key generated always as identity` is seen as a required field and prevents records from being created

### ISSUE THREAD

**Issue by sxsws** [nocodb/nocodb#2561]
**Please enter the following details**

```
Node: **v12.22.5**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.92.3**
```
**Steps To Reproduce**

I use identity for primary keys, e.g. 
```
create table currencies (
    id int primary key generated always as identity,
    title text not null,
    iso3 text not null unique,
    divider int not null default 100,
    note text null
);
create index idx_currencies_iso3 on currencies using btree(iso3);
create index idx_currencies_title on currencies using btree(title); 
```

nocodb sees the id field as a required field (which it shouldn't) and fails to save when an numerical value is provided  (as it should do).

I understand `intserial` and `bigintserial` are supported, but apparently these are for pre-version 10 postgres, with advice to switch to identity generation for newer databases.

**Expected Behavior**

The id field should be recognised as a read-only id field and not allow any input

**Screenshots**

![Screenshot from 2022-07-05 13-38-26](https://user-images.githubusercontent.com/95102939/177329330-2a1cc07a-33c2-410b-bc54-b8bf72b7be55.png)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by o1lab** [comment]
Thank you for the detailed report

**Comment by mertmit** [comment]
This happens because we miss out some new information schema from newer versions of pg
![image](https://user-images.githubusercontent.com/59797957/177406388-bb01c8d9-f08c-4580-8a7e-e528a14cceda.png)
also these are not directly from this issue but cause a similar issue
![image](https://user-images.githubusercontent.com/59797957/177406604-550327a2-52c6-4334-993d-1f4c9477e42a.png)
We should detect them and restrict editing accordingly.

**Comment by roja** [comment]
This continues to cause issues for postgres users - it looks to have been removed as a recent deliverable, is there any chance it may be reconsidered?

**Comment by fergmar** [comment]
This still appears to be an issue, can it be reconsidered? Int4 is generated always as identity shows to be required, preventing adding new records with out typing in the next generated id manually.
