### ISSUE TITLE
Filtering by formula column is broken

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#2562]
Filtering table by formula column leads to error "e.replace is not a function" with code 400. Problem met in both API and UI. 
Error reproduced with number, string and boolean formula result.

<details> 
  <summary>.gif illustration with numbers</summary>
   
![Peek 2022-07-05 15-34](https://user-images.githubusercontent.com/61871501/177329190-facbfc67-b784-485f-be6a-0f13f0d56d0c.gif)
</details>

Was working at v.0.91.10.

---
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.92.3**

**Comment by wingkwong** [comment]
The fix is covered in https://github.com/nocodb/nocodb/pull/2535
