### ISSUE TITLE
🐛 Bug: Sort by Lookup column does not work

### ISSUE THREAD

**Issue by Cirsten** [nocodb/nocodb#2573]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.92.3**
```

_**Steps To Reproduce**_

1. Go to 'Sort'
2. Click on 'Lookup' column type
3. See error: not sorted

_**Expected Behavior**
A clear and concise description of what you expected to happen._

In this case the Lookup column contains "Number"
When select to sort, it is not sorted at all

_**Screenshots**
If applicable, add screenshots to help explain your problem._

![Capture2](https://user-images.githubusercontent.com/105973951/177441634-84da80ce-045a-4947-94a8-a6012c5eccac.PNG)

**Comment by davidpfahler** [comment]
I ran into this bug today on the latest release.

```
Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.104.3**
```

**Comment by DavidIsaacBPS** [comment]
Still an issue on 0.111.2.  This is a very important feature to have working, especially because it is needed as a workaround for the inability to group by links/lookups.
