### ISSUE TITLE
Allow editing of a Lookup column

### ISSUE THREAD

**Issue by Cirsten** [nocodb/nocodb#2574]
_**Need for this feature**
What purpose does your Idea serve? What use cases does it solve?_

Would allow some time saving when changing a table structure

_**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is._ 

At the moment a Lookup can not be fully edited. That is, the name can be changed but not it's nature

_**Describe the solution you'd like**
A clear and concise description of what you want to happen._ 

Allow editing to change the "Child column" value

_**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered._

At the moment a new Lookup column needs to be created, and then the old one deleted (or visa versa)

**Additional context**

**Comment by dstala** [comment]
@Cirsten 
Edit option to lookup and rollup is now available in latest release

**Comment by MoSh3ban219** [comment]
@dstala  
Edit for lookup is only allowed for **Many to Many** link between tables
![Screenshot - 3_23_2023 , 2_37_59 PM](https://user-images.githubusercontent.com/95393526/227205970-28f04566-ceba-424f-a867-74d554893a94.png)

For **Has Many** link is not editable
 
![Screenshot - 3_23_2023 , 2_28_04 PM](https://user-images.githubusercontent.com/95393526/227203976-b4c22680-683c-4f08-a789-271c1274a6da.png)

**Comment by mattmoran56** [comment]
It would be great to see edit for all lookups implemented!

We have a one-to-many relationship and having to change table to edit a value is quite laborious.
