### ISSUE TITLE
Paste mutliple (100s) of rows at a time into an existing table

### ISSUE THREAD

**Issue by Cirsten** [nocodb/nocodb#2575]
_**Need for this feature**
What purpose does your Idea serve? What use cases does it solve?_

I am trying to transition from Airtable to NocoDB. However from the GUI (API is beyond me) each row of info needs to be manually entered. To be able to copy and then paste many rows from Airtable or a spreadsheet or from another table in NocoDB would save hours of work

_**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is._ 

Copy and paste is not available in or out of NocoDB

_**Describe the solution you'd like**
A clear and concise description of what you want to happen._ 

Select multiple rows and columns (cells) from an another source and paste into NocoDB. 

_**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered._

Using an API to do this, but well beyond me

**Additional context**

![Capture3](https://user-images.githubusercontent.com/105973951/177446567-060cbde4-d39c-42c2-9efe-6a6e48f072d8.PNG)

PS: sorry about the multiple requests

**Comment by dstala** [comment]
Related https://github.com/nocodb/nocodb/issues/3567

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/3567
