### ISSUE TITLE
could not run nocodb from latest (0.9.25) docker

### ISSUE THREAD

**Issue by SupakornYu** [nocodb/nocodb#258]
the page at http://localhost:8080/dashboard/ is stuck at a loading page.

![image](https://user-images.githubusercontent.com/6560459/121393337-728d7b80-c97a-11eb-9f7b-68244f5964c1.png)

and the log in docker desktop is below

![image](https://user-images.githubusercontent.com/6560459/121393472-9224a400-c97a-11eb-8b7d-1073759ba8b5.png)

**Comment by o1lab** [comment]
Could you do a hard refresh on your browser ?

0.9.26 is the latest docker image.

**Comment by SupakornYu** [comment]
> Could you do a hard refresh on your browser ?
> 
> 0.9.26 is the latest docker image.

same result on 0.9.26.

![image](https://user-images.githubusercontent.com/6560459/121395826-019b9300-c97d-11eb-94d5-544236323741.png)

**Comment by o1lab** [comment]
could you try incognito once ? what OS / browser is this >?

**Comment by SupakornYu** [comment]
> could you try incognito once ? what OS / browser is this >?

I do not open page in incognito mode.
OS --> windows 10 version 21H1
Browser --> Google Chrome is up to date Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by o1lab** [comment]
hard refresh is ctrl+shift+r

**Comment by SupakornYu** [comment]
> hard refresh is ctrl+shift+R

Thank you. That's the fix.
