### ISSUE TITLE
Add multiple row to existing table with a csv file

### ISSUE THREAD

**Issue by kristinbb** [nocodb/nocodb#2594]
I need to add multiple rows into an existing table in NocoDB. I have these rows in a csv file and I want to upload the rows from the csv file into the existing table.

**Comment by wingkwong** [comment]
Is it what you want?

https://docs.nocodb.com/setup-and-usages/table-operations#import-data

**Comment by include** [comment]
Works for me - in the meantime - is there any way to skip duplicate entries while performing an import like this? 10x

**Comment by o1lab** [comment]
From the discussion, closing this for now
