### ISSUE TITLE
losing unsaved changes when modifying table definition

### ISSUE THREAD

**Issue by pvdh** [nocodb/nocodb#260]
I am running docker latest (2021-6-9).

When I add new rows to a table and then change the table definition (changing a column, adding a column,...) without saving, the table refreshes and the new rows are lost.

This is quite annoying. I'm not sure which ux I'd prefer. Displaying a warning when adding/editing a column and there are unsaved changes would be OK ("you will lose unsaved changes to your content if you proceed to change the table definition").

Would be even better if I could just change the definition without losing my unsaved changes, but that's probably harder to accomplish.

I hit this issue when I needed to add a new option to a column of type SingleSelect when adding a new row.

**Comment by o1lab** [comment]
![projectinfo mov](https://user-images.githubusercontent.com/5435402/121416023-f6009a00-c985-11eb-9c8e-51a639ee2eba.gif)

We've a menu option that gives the details of the project info - could you pls paste it here.

See gif attached.

**Comment by pranavxc** [comment]
Fixed in `0.10.0`
