### ISSUE TITLE
Old table structure after upgrading from 0.84.16 to 0.92.3

### ISSUE THREAD

**Issue by j-stahl** [nocodb/nocodb#2601]
**Desciption**

On updating NocoDB to 0.92.3 the web ui tries to show up an old table structure, which has been discarded since months. It tries to show up columns which do not exist anymore. Since I am on docker, I can easily roll back to the old version and see what it does. The old NocoDB version shows the correct actual table structure.

I did not see any release notes or upgrade instructions telling me, I did something wrong with just easily replacing the docker image and start a new container.

**Project Info**
```
NocoDB used as docker : true
```
Old NocoDB
```
Node: **v12.22.10**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.84.16**
```
New NocoDB
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.3**
```

**Steps To Reproduce**
1. Create DB
2. Create table columns
3. Delete and change table columns
4. Update NocoDB from 0.84.16 to 0.92.3

**Expected Behavior**
See new table structure and its content.

**Screenshots**
NocoDB 0.84.16 - Correct actual table structure - 5 columns, 5 checkmarks, table content
![grafik](https://user-images.githubusercontent.com/15193774/177731750-d9f26488-4b8b-40c5-a534-edc5ac11a523.png)

NocoDB 0.92.3 - Wrong old structure shows not existing columns - 8 columns, 8 checkmarks, no table content
![grafik](https://user-images.githubusercontent.com/15193774/177732528-c1178139-2cdc-433b-96be-a74c6f4b9b2f.png)

This leads for sure to an SQL error and prevents showing table contents:
![grafik](https://user-images.githubusercontent.com/15193774/177732667-710684df-12ce-4039-b1d4-7c90a74f202b.png)

**Comment by o1lab** [comment]
ok so to understand it right - you are seeing columns created and deleted in 0.84.16 and are now showing up in 0.92.3?

Most migration issues have worked seamlessly and have had no issues lately. We can take a look and get back.

At the moment if you rollback to 84.16 it should still work.

**Comment by o1lab** [comment]
+ please paste your docker logs here - that would be really helpful.

**Comment by o1lab** [comment]
Thank you, will get back on this.

**Comment by j-stahl** [comment]
With NocoDB 0.92.4 the issue still persists.
Can I somehow help debugging this issue? Do you maybe need a history related table from the MySQL DB? I know there are audit related tables. I don't know which tables are needed for the API (or the UI) to get the current table layout the user wants to be shown.

**Comment by dstala** [comment]
@j-stahl for further help, please get in touch with us over discord
You can connect with @pranavxc
