### ISSUE TITLE
[Feature] Add DATE() function for formulas

### ISSUE THREAD

**Issue by djmaze** [nocodb/nocodb#2605]
We need to filter for past date, current date and future date via a formula field. So it would be useful to have a `DATE()` function additionally to the existing `NOW()` function which just returns the current date without time.

**Describe alternatives you've considered**
Via `IF()` and `NOW()`, it is not possible to check if a date field contains the _current date_.

**Comment by dstala** [comment]
`DATESTR(NOW())` supported now, and will be available from next OSS release scheduled by end of this mont.
