### ISSUE TITLE
[Feature] Allow showing week day for dates

### ISSUE THREAD

**Issue by djmaze** [nocodb/nocodb#2606]
**Need for this feature**
We want to show the week day (Monday, Tuesday, ..) for a given date field in the table.

**Describe the solution you'd like**
It should either be possible to change the date format for date columns to include the week day. Or alternatively, there should be a new formula function `WDAY(date_field)`, which returns the week day for a given date. Either as an (english) text or only as a number (0-6) so we can show the correct week day name using a `SWITCH(WDAY(date_field), ...)`.

**Describe alternatives you've considered**
We can add an additional text or single select field for selecting the week day additional to the date field to our table. But that is ugly and error prone.

**Comment by include** [comment]
I would love this too :)
