### ISSUE TITLE
Can't reset the password

### ISSUE THREAD

**Issue by whyteserious** [nocodb/nocodb#2607]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.92.3**

NocoDB used as docker : true
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql
Database version : 5.7

1.  forget the passwrod. 
2.  l got a email with the reset link
![Snipaste_2022-07-08_08-59-52](https://user-images.githubusercontent.com/42569476/177896117-e6672ae4-ad02-4a47-99e9-cde3d31f088a.png)
3.  visit the link  it shows “Password reset successful”，but l don‘’t reset the password.
![S1](https://user-images.githubusercontent.com/42569476/177897128-45548492-4646-45eb-a88e-e65081835d4b.png)

**Expected Behavior**
1. fix the bug
2. Team and Auth can change the password or provide a account like root

**Comment by whyteserious** [comment]
a few minutes later. 
"Password reset successful!" changed "Not a vaild url"
![1](https://user-images.githubusercontent.com/42569476/177897536-8ae9d1b1-6e0a-40f0-85f4-0b420766e62e.png)

**Comment by wingkwong** [comment]
Seems it's related to https://github.com/nocodb/nocodb/issues/2563. Can you test it on either executable / docker image below?

```bash
mkdir -p ./0.92.3/pr-2568-20220705-2015 && cd "$_" \
    && curl http://dl.nocodb.com/0.92.3-pr-2568-20220705-2015/Noco-macos-arm64 -o noco -L \
    && chmod +x noco \
    && ./noco
```
#### Linux

```bash
mkdir -p ./0.92.3/pr-2568-20220705-2015 && cd "$_" \
   && curl http://dl.nocodb.com/0.92.3-pr-2568-20220705-2015/Noco-linux-x64 -o noco -L \
   && chmod +x noco \
   && ./noco
```
#### Windows

```bash
iwp http://dl.nocodb.com/0.92.3-pr-2568-20220705-2015/Noco-win-arm64.exe
.\Noco-win-arm64.exe
```

#### Docker 

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.92.3-pr-2568-20220705-2015
```

**Comment by whyteserious** [comment]
nocodb-timely:0.92.3-pr-2568-20220705-2015 
This version can solve this problem
thank you

**Comment by wingkwong** [comment]
Thanks for confirmation.The fix is currently in the develop branch. Please stay tuned for the next release.

**Comment by bonacci-johannes** [comment]
Can't reset password when using reverse proxies.

When opening the link I receive the same message 'Password reset successful!' as discribed above.

For our nocodb we configured reverse proxies and nocodb is reachable via http://my_website.com/nocodb
As the enviroment backend_url variables don't work we redirect the url using apache2 on linux as follows:

<VirtualHost *:80>
    ServerName my_website
    ServerAlias my_website.com

    RewriteEngine on
    Redirect 301 /dashboard /nocodb/dashboard
    Redirect 301 /auth /nocodb/auth
    ProxyPass /nocodb "http://localhost:8080"
    ProxyPassReverse /nocodb "http://localhost:8080"
</VirtualHost>

Thank you for your help!
