### ISSUE TITLE
Handling SingleSelect: set to null value, easier adding of new values

### ISSUE THREAD

**Issue by pvdh** [nocodb/nocodb#261]
My table has several columns, one is titled "category" of type "SingleSelect" and has some "options". The column is not set to "not null".
When adding a new row, I do not have to add a value for this column.
But when I try to edit an existing row which has a value, then there is no option to remove the existing one, I can only change it to a different value/option.

Either change the column so SingleSelect implies "not null" or add an option to remove an existing value.

When modifying columns of type "SingleSelect", please consider easier adding of new options. I suppose it is not unusual to realize "I need an option that doesn't exist yet" when adding a new row. This is related to #260 where I lost new unsaved rows when I tried to quickly add a new option which I needed to add a new row...

**Comment by o1lab** [comment]
Please mention the database type, API type being used for the project in the issues.

Can be copied via menu option see #260

**Comment by pranavxc** [comment]
Will add a reset icon to clear the field if the field is `nullable`

**Comment by o1lab** [comment]
Closed in commits above.
