### ISSUE TITLE
vue3 : Spreadsheet

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2629]
- [ ] Filter
   - [x] Add
   - [x] Edit
   - [x] Delete
   - [ ] Manual sync
   - [ ] UI corrections
- [ ] Sort
   - [x] Add
   - [x] Edit
   - [x] Delete
   - [ ] UI corrections
- [ ] Fields
   - [x] Show
   - [x] Hide
   - [x] Show system field
   - [x] Show/Hide all
   - [ ] UI corrections
   - [ ] Draggable
- [ ] Locked view
- [ ] Header cell 
    - [x] Custom icon
    - [ ] Tooltip
    - [ ] Edit
    - [ ] Delete
- [ ] Column resize
    - [ ] Sync with DB  
- [ ] Column create/edit
    - [ ] Virtual column creation
         - [ ] Validation
    - [ ] Normal column creation
         - [ ] Validation
    - [ ] Delete
    - [ ] Edit
- [ ] Table create
   - [ ] Validation
   - [ ] Open tab after successful creation
   - [ ] Pre-fill with unique name
   - [ ] Advanced options
   - [ ] UI corrections
- [ ] Table rename
- [ ] View create
   - [ ] View Type based inputs
   - [ ] Validation
   - [ ] Pre-fill with unique name
   - [ ] UI corrections
- [ ] Other view operations
   - [ ] Clone
   - [ ] Delete
   - [ ] Rename

**Comment by dstala** [comment]
@pranavxc 

- [ ] edit column name updates associated filter/sort; delete column doesn't (v1 did clear `field` name in filter list)
- [ ] `add new row` at bottom of grid is getting compressed to first column width
  
![Screenshot 2022-08-08 at 5 43 40 PM](https://user-images.githubusercontent.com/86527202/183415477-4591643f-8ba4-4cae-b690-b186dc90d505.png)
