### ISSUE TITLE
'This spreadsheet is connected to an SQLite DB' alarm while using mysql

### ISSUE THREAD

**Issue by wiyin** [nocodb/nocodb#263]
OS: ubuntu 20.04
Compose file: docker-compose/mysql was used

symptom:

'Create By connecting To An External Database', - mysql connecting to xcdb - create new table OK

following error message when adding or editing column attribute:
This spreadsheet is connected to an SQLite DB.
For production please see here.

**Comment by pranavxc** [comment]
Fixed in latest version `v0.9.27`
