### ISSUE TITLE
vue3 : Gallery

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2631]

**Comment by dstala** [comment]
@pranavxc @mustafapc19 

Observations; we can route appropriately if some of the items listed here were not under development scope of this PR

- [ ] Field `active` badge appears on creating Gallery view
  
![Screenshot 2022-08-09 at 9 26 58 AM](https://user-images.githubusercontent.com/86527202/183561123-91621012-cb87-45c7-ac90-7f1f2a5f56f0.png)

- [ ] `Expanded form` should pop on clicking card (Pranav?)
  
![Screenshot 2022-08-09 at 9 30 32 AM](https://user-images.githubusercontent.com/86527202/183561879-f15406d9-3f03-4a84-b32c-ec9bc38126c1.png)

- [ ] Mark checkbox cell in gallery view as read-only. Click on it should not toggle its value
  
![Screenshot 2022-08-09 at 9 38 45 AM](https://user-images.githubusercontent.com/86527202/183562237-47df2e2f-a621-4153-8bfd-9b0e0aecc2b1.png)
   
![Screenshot 2022-08-09 at 9 38 39 AM](https://user-images.githubusercontent.com/86527202/183562231-b5673f98-9c38-4292-9846-effe68a02115.png)

- [ ] Filter & sort need hard refresh / reload (Pranav?)
- [ ] Fields enable & disable 'menu' is not reactive. changes are reflected only after toggling menu (close and open)
