### ISSUE TITLE
vue3 : Team & Settings

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2634]
- [ ] Team & settings
  - [ ] #2717
    - [ ] User Management
      - [ ] List users (E-mail, Roles(chip), Actions)
      - [ ] New user
      - [ ] Edit user
      - [ ] Remove user
      - [ ] Filter (search)
    - [ ] API Tokens Management
      - [ ] List tokens (Description, Token, Actions)
      - [ ] Add new token
  - [ ] [App store](https://github.com/nocodb/nocodb/issues/2714)
    - [ ] App cards
    - [ ] Install
    - [ ] Edit & reset
  - [ ] [Project metadata](2715)
    - [ ] Metadata
      - [ ] Is synced?
      - [ ] Sync now
    - [ ] UI Access Control
      - [ ] Tabs
        - [ ] List tables & views
          - [ ] Search models
          - [ ] Role Checkbox (change availability for role)
  - [ ] [Audit](https://github.com/nocodb/nocodb/issues/2714)
    - [ ] List audit logs (Operation type, Operation sub-type, Description, User, Created)

**Comment by wingkwong** [comment]
Closing - managed in separate issues.
