### ISSUE TITLE
Failed to connect backend if hosting frontend and backend separately

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#264]
Supposing hosting the frontend and backend separately is required. 

Steps to reproduce:
1. open cmd 1
2. cd packages/nc-gui
3. run ``npm i``
4. run ``npm run build`` so that the files will be built under ``dist/``
5. open cmd 2
6. cd packages/nocodb
7. run ``npm i``
8. run ``npm run watch:run``
```
App started successfully.
Visit -> http://localhost:8080/dashboard
```
9. after backend is started successfully, go back to cmd1 and run ``http-server -p 3000 .``
```
Starting up http-server, serving .
Available on:
  http://172.16.12.115:3000
  http://127.0.0.1:3000
  http://172.22.80.1:3000
  http://172.17.65.113:3000
```
10. access http://172.17.65.113:3000 in browser
11. Open DevTools and found the following errors
![image](https://user-images.githubusercontent.com/35857179/121493804-c182f180-ca0a-11eb-92f7-5661766d3dd7.png)
The request URL is ``http://172.17.65.113:3000/?q=sqlOp_xcPluginRead``

Note: 
I changed ``../`` to ``http://localhost:8080/`` in 

https://github.com/nocodb/nocodb/blob/master/packages/nc-gui/nuxt.config.js#L102 

and it still doesn't work. Somehow it is still accessing port 3000.

**Comment by pranavxc** [comment]
This may be helpful : https://axios.nuxtjs.org/options/

**Comment by wingkwong** [comment]
It seems that the current design assumes the frontend and the backend bound together. 

baseURL is defined in nuxt.config.js

```
  axios: {
    baseURL: process.env.NODE_ENV === 'production' ? '../' : 'http://localhost:8080/'
  },
```

However, I don't see this value is used in other files as they are hardcoded as follows 

Example 1: users.js
```
    return (await this.$axios({
      url: '/auth/admin/verify',
      baseURL: process.env.NODE_ENV === 'production' ? './' : 'http://localhost:8080/dashboard',
      // baseURL:  'http://localhost:8080/dashboard',
      method: 'post',
      data: {secret}
    })).data;
```

Example 2: sqlMgr.js
```
        result = (await this.$axios({
            url: '?q=sqlOpPlus_' + op,
            baseURL: process.env.NODE_ENV === 'production' ? './' : 'http://localhost:8080/dashboard',
            // baseURL: 'http://localhost:8080/dashboard',
            data: {api: op, ...args, ...params, args: opArgs, sqlOpPlus: true},
            headers,
            method: 'post'
          }
        )).data;
```

In this case, if the frontend is hosted separately listening on port 3000, then it assumes the backend is also listening on port 3000. 

And I think the origin design was commented out, i.e. setting baseURL: 'http://localhost:8080/dashboard'. This should work iff the backend is hosted locally listening to port 8080.

@pranavxc I'd like to suggest the following changes. 

We can keep ``nuxt.config.js``. If someone needs to host frontend and backend separately, then they can change '../' to the desired backend endpoint (we should add some guidelines for this part).

For all axios calls, use the baseURL defined in ``nuxt.config.js`` instead of hardcoding by utilising ``${$axios.defaults.baseURL}``. 

Let me know you thoughts. I can help make a PR for this issue.

**Comment by o1lab** [comment]
hey @wingkwong : thanks for the analysis.

> We can keep nuxt.config.js. If someone needs to host frontend and backend separately, then they can change '../' to the desired backend endpoint (we should add some guidelines for this part).

To add some context, we'd started with an environment variable based on which we used to mount the dashboard & backend APIs. However, we ran into trouble & decided to forego the env variable. 

Could you possibly see having an env variable in this path ?

**Comment by wingkwong** [comment]
@o1lab maybe we can define a environment variable, let's say ``NC_BACKEND_URL``, then we change ``nuxt.config.js`` like 

```
  axios: {
    baseURL: process.env.NC_BACKEND_URL || 'http://localhost:8080/'
  },
```

**Comment by o1lab** [comment]
Yes, please give it a shot.

**Comment by pranavxc** [comment]
> It seems that the current design assumes the frontend and the backend bound together.
> 
> baseURL is defined in nuxt.config.js
> 
> ```
>   axios: {
>     baseURL: process.env.NODE_ENV === 'production' ? '../' : 'http://localhost:8080/'
>   },
> ```
> 
> However, I don't see this value is used in other files as they are hardcoded as follows
> 
> Example 1: users.js
> 
> ```
>     return (await this.$axios({
>       url: '/auth/admin/verify',
>       baseURL: process.env.NODE_ENV === 'production' ? './' : 'http://localhost:8080/dashboard',
>       // baseURL:  'http://localhost:8080/dashboard',
>       method: 'post',
>       data: {secret}
>     })).data;
> ```
> 
> Example 2: sqlMgr.js
> 
> ```
>         result = (await this.$axios({
>             url: '?q=sqlOpPlus_' + op,
>             baseURL: process.env.NODE_ENV === 'production' ? './' : 'http://localhost:8080/dashboard',
>             // baseURL: 'http://localhost:8080/dashboard',
>             data: {api: op, ...args, ...params, args: opArgs, sqlOpPlus: true},
>             headers,
>             method: 'post'
>           }
>         )).data;
> ```
> 
> In this case, if the frontend is hosted separately listening on port 3000, then it assumes the backend is also listening on port 3000.
> 
> And I think the original design was commented out, i.e. setting baseURL: 'http://localhost:8080/dashboard'. This should work iff the backend is hosted locally listening to port 8080.
> 
> @pranavxc I'd like to suggest the following changes.
> 
> We can keep `nuxt.config.js`. If someone needs to host frontend and backend separately, then they can change '../' to the desired backend endpoint (we should add some guidelines for this part).
> 
> For all axios calls, use the baseURL defined in `nuxt.config.js` instead of hardcoding by utilising `${$axios.defaults.baseURL}`.
> 
> Let me know you thoughts. I can help make a PR for this issue.

Ya, we'd noticed a few of the hardcoded `baseUrl` and replaced it with relative path. Few of them are still there will update them as well 👍 .

**Comment by wingkwong** [comment]
Thanks for the confirmation. I'll make a PR in the coming days.

**Comment by wingkwong** [comment]
Thanks for the confirmation. I'll make a PR in the coming days.

**Comment by wingkwong** [comment]
Thanks for the confirmation. I'll make a PR in the coming days.

**Comment by pranavxc** [comment]
@wingkwong hope we can close this issue now 👍

**Comment by wingkwong** [comment]
Agree.
