### ISSUE TITLE
Deleten SingleSelect or MultiSelect is not possible - no error shown

### ISSUE THREAD

**Issue by nosorio2** [nocodb/nocodb#2650]
**Please enter the following details**

```

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.92.3**
```

**Steps To Reproduce**
On a table 
1. create a property of multi SelectType
2. create a second property SingleSelect with more than 25 characters and a question mark
3. Error pops
4. then it's not possible to delete any property column in that table, in another table is possible. 
5. This is a local installation in Docker. I tried stopping the instance and restarting but it didn't help

**Expected Behavior**

- I would expect not being able to save a property if the title exceeds the amount of characters allow for the title 
- I'd also expect to be able to delete and if can't delete some info why not

**Screenshots**

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/46441491/178441947-e5c34b77-555e-4d1f-82d4-326113d45576.png)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by dstala** [comment]
seems to be working fine with our latest release v0.202.5; @nosorio2 if issue persists, please reopen this thread
