### ISSUE TITLE
"Email must be valid" error for valid email with a four-character top-level domain

### ISSUE THREAD

**Issue by tom-leamon** [nocodb/nocodb#267]
Version: Latest
Docker

When attempting to create a new user that has a four-character top-level domain in the email address, an "E-mail must be valid" error is returned. For example, the email test@test.live is said to be invalid. However, I was able to sign up with that email, without seeing any errors.

Steps to Replicate

Create a new user with a four-character TLD in the email such as "test@test.live"
Sign out
Try to sign back in
Observe the "E-mail must be valid" message
What is Expected?
The Email is valid per RFC spec and should be allowed.

**Comment by pranavxc** [comment]
This has been already fixed, please try with our latest docker `nocodb/nocodb:0.9.30`.
