### ISSUE TITLE
Querying API which has some LTAR & lookups is slow even when just table fields are mentioned

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2671]
This is from @RawmanGrey 

- There is a table with 30K records.
- A LTAR and a lookup is created (m2m)
- API query is made to just fetch : id,title (takes 6 seconds)
- Remove LTAR and lookup.
- API query takes ~2 seconds.

**Comment by RawmanGrey** [comment]
o1lab, again thanks for your help and starting this issue : )  

Unfortunately, querying is slowed down by any 'expensive' field existing in table, including roll-ups and formulas. In my [case](https://github.com/nocodb/nocodb/discussions/2626#discussion-4207291), formulas affect was wild. Probably, all fields now have a certain affect...

Basically, expectation is to get table data faster if not all fields are requested. I guess, the same performance issue can be met in UI, when loading table views with limited fields.

To get response times mentioned above, load testing was made with [siege](https://www.joedog.org/siege-manual/) tool, where 15 concurrent users were querying 20 entries limited to Id and text title every 3 seconds:
```
siege -H "xc-token: <<XC_TOKEN>>" -c 15 -t5M "https://<<BASE_URL>>/api/v1/db/data/noco/<<PROJECT_NAME>>/<<TABLE_NAME>>?sort=-updated_at&limit=20&fields=Id,number"
``` 

---

Project info, where issue was tested:
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.91.10**
