### ISSUE TITLE
Error during password resetting

### ISSUE THREAD

**Issue by stepanof** [nocodb/nocodb#2673]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.92.3**
```

**Steps To Reproduce**

1. Open 'Sign in' page (http://<nocodb_host>:8080)
2. Click 'Forgot your password ?' (http://<nocodb_host>:8080/dashboard/#/user/password/forgot)
3. Write email for password resetting
4. Follow link which was sent for email
![image](https://user-images.githubusercontent.com/68236577/178778256-62656bf7-7e12-460f-bafb-428f678a7495.png)
5. See error in browser
![image](https://user-images.githubusercontent.com/68236577/178778410-48f2e8dc-25c3-4837-a9cb-356f1c53b57b.png)

link for password resetting is 
http://<nocodb_host>:8080/api/v1/auth/password/reset/52d1b75c-2c8d-4996-b1cd-61aeeaf4cce8

**Expected Behavior**

Password reset option works without errors

**Comment by o1lab** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/2672
