### ISSUE TITLE
Error importing Chinese data

### ISSUE THREAD

**Issue by whyteserious** [nocodb/nocodb#2677]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.92.3**

**Steps To Reproduce**

1. Go to 'Add/Import', CSV or Excel.
2. Chinese Column name and  Chinese sheet name Unrecognized

**Expected Behavior**

Please solve this problem

**Screenshots**

![image](https://user-images.githubusercontent.com/42569476/178895445-e1493251-6194-4617-93fb-6d111bc053f3.png)

![image](https://user-images.githubusercontent.com/42569476/178895110-9ff30cee-9cd4-4113-9a7b-e61ded711603.png)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by wingkwong** [comment]
Can you provide the sample file for us to reproduce the issue?

**Comment by whyteserious** [comment]
[chinesetest1.xlsx](https://github.com/nocodb/nocodb/files/9116840/chinesetest1.xlsx)
[chinesetest2.csv](https://github.com/nocodb/nocodb/files/9116841/chinesetest2.csv)
The column names of two documents with different contents cannot be recognized, but the contents can.
