### ISSUE TITLE
[i18n] Language support extension- <language code>

### ISSUE THREAD

**Issue by seokjunjin** [nocodb/nocodb#2684]
# i18n translation request

**Please enter the following details**

1. Select applicalbe
- [ ] **New language support request**
- [x] **Existing language translation corrections request** 
Verify if language support already exists in the NocoDB i18n master spreadsheet [here](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172)

2. Associated language code (pick from [here](https://developers.google.com/admin-sdk/directory/v1/languages)): 

3. Google spreadsheet
- Procedure to share google spreadsheet can be found [here](https://support.google.com/docs/answer/2494822?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cshare-a-file-publicly) 
  - When requested, select public sharable link. 
- Alternatively, you can download & attach a spreadsheet here along with the issue as well. 
- [ ] **Attached**
- [ ] **Shared link**:

4. Summary of the changes made
- You can highlight modified items in the Spreadsheet attached/shared, to help us quickly identify changeset

5. Any specific message to be conveyed to moderators?
- Help us simplify the process if you find something hard about it

**Comment by dstala** [comment]
@seokjunjin Please attach your proposed modifications in a spreadsheet. You can make a copy of [this](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172) and apply changes for the language you would like to propose changes for.

**Comment by seokjunjin** [comment]
@dstala oops, this is my bad. I've created a new one instead. Please see the #2685. Thanks!

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/commit/582bcf2dbef78438e62b82620bb9cfc52c331faa
