### ISSUE TITLE
[i18n] Language support extension- <ko>

### ISSUE THREAD

**Issue by seokjunjin** [nocodb/nocodb#2685]
# i18n translation request

**Please enter the following details**

1. Select applicalbe
- [ ] **New language support request**
- [x] **Existing language translation corrections request** 
Verify if language support already exists in the NocoDB i18n master spreadsheet [here](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172)

2. Associated language code (pick from [here](https://developers.google.com/admin-sdk/directory/v1/languages)): Korean - ko

3. Google spreadsheet
- Procedure to share google spreadsheet can be found [here](https://support.google.com/docs/answer/2494822?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cshare-a-file-publicly) 
  - When requested, select public sharable link. 
- Alternatively, you can download & attach a spreadsheet here along with the issue as well. 
- [ ] **Attached**
- [x] **Shared link**: https://docs.google.com/spreadsheets/d/1mUKkoyEpLCflQGZGtpKFEmH5vH-PVnygt90kRn4KpcQ/edit?usp=sharing

4. Summary of the changes made
- Added improvements by creating a new column('ko-renewed') next to the 'ko' column. I couldn't verify all the text, but corrected all that could be verified. It would be nice to replace the 'ko' column with a new one 'ko-renewed' if possible.

5. Any specific message to be conveyed to moderators?
- It's always good to use. Thank you!

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/commit/582bcf2dbef78438e62b82620bb9cfc52c331faa

**Comment by dstala** [comment]
@all-contributors please add @seokjunjin for translation
