### ISSUE TITLE
[Feature] Usernames for Accounts

### ISSUE THREAD

**Issue by Megamezzomixer** [nocodb/nocodb#2696]
**Need for this feature**
Making User Management more easy
Maybe create an opportunity to log in with usernames as well

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see a possibility to add Usernames along with the E-Mail Address for accounts. More or less just to recognize people by their username. Therefore it could be easier to recongize authorized people and give them permissions accordingly. Currently we have to guess what user is behind a certain Mail address.

**Comment by aagrawal7** [comment]
@wingkwong  i want to work on this feature  , asked you same on discord

**Comment by dstala** [comment]
Profile names are now available; login, we will continue to use Email ID.
