### ISSUE TITLE
Not all fields are populated when using uuid field instead of serial id field

### ISSUE THREAD

**Issue by bhanuc** [nocodb/nocodb#270]
NocoDB used as docker : true 
NocoDB version : latest docker 
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Ubuntu
Node.js version if running as node : Using docker
Database version : 13.3

**Steps To Reproduce**
1. Create UUID field in Table A, Manually add unique constrainst by creating an index - CREATE UNIQUE INDEX UniqueUID ON A (uid);
2. Create UUID field in Table B, Manually add unique constrainst by creating an index - CREATE UNIQUE INDEX UniqueUID ON B (uid); Table B also has a field a_id which is a foreign key to uuid field of table A.
3. Create table C, add a field a_id which is a foreign key to uuid field of table A and b_id which is a foreign key to uuid field of Table B.
4- Now when creating entries in table C, by using the has many dropdown of table B, I expect both a_id and b_id to be populated, but only b_id is currently getting populated.

**Expected behavior**
I expected both a_id and b_id to get populated in table C, this used to work when the ids were serial ids

Node version : **using docker image**
Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **postgres**
packageVersion: **0.9.27**

**Comment by o1lab** [comment]
In step 3, how did you go about adding foreign key - was this via nocodb or done externally ?

**Comment by o1lab** [comment]
We would be handling relational values in new way - so this can be relooked then.

**Comment by bhanuc** [comment]
Would like to close this issue, as I stopped using nocodb for the time being. Awesome project btw, will retry in near future again for sure.
