### ISSUE TITLE
Exporting CSV does not support Chinese.

### ISSUE THREAD

**Issue by sfdzkj** [nocodb/nocodb#2701]
导出csv  不支持中文。
Exporting CSV does not support Chinese.
![微信截图_20220717181613](https://user-images.githubusercontent.com/35343217/179393779-ab91b134-0786-4c47-8ddf-297a5a9d474e.png)

**Comment by wingkwong** [comment]
@sfdzkj 

**Please enter the following details**

Copy and Paste Project Info - Tutorials: How to check my Project info? ([YouTube Tutorial](https://www.youtube.com/watch?v=AUSNN-RCwhE) or [Documentation](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-)) 

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.4**
```

Couldn't reproduce the problem. Texts are generated from [here](https://generator.lorem-ipsum.info/_chinese).

![image](https://user-images.githubusercontent.com/35857179/179440215-6834abed-9666-4a2c-bf81-ee4086c36349.png)

```
Id,泉面所,官法家太権再暮,CreatedAt,UpdatedAt
1,泉面所戸点里頭本異形建長潟多検応渡方,当注者影月発逃奏間研速回提供大市押。,2022-07-18 11:12:09,2022-07-18 11:13:01
2,形建長潟,逃奏間,2022-07-18 11:13:12,2022-07-18 11:13:15
```

**Comment by whyteserious** [comment]
The default format for exporting CSV is UTF-8, which does not support Chinese. Open it in Notepad and save it as ANSI.
