### ISSUE TITLE
code snippet - baseurl  how to Generate HTTPS link

### ISSUE THREAD

**Issue by systemctls** [nocodb/nocodb#2711]
**Please enter the following details**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.92.4**

**Steps To Reproduce**

1. Go to tables
2. Click on  right button ‘Get API Snippet’
3. URL in the generated fragment （url or baseURL or CURLOPT_URL）is http，but my website is https，`window.location.protocol`  ‘https: ’

![image](https://user-images.githubusercontent.com/37177191/179474991-04c52ea1-1c3b-4769-9bb6-e8f185048177.png)

**Comment by o1lab** [comment]
If you can help this with a PR - will much appreciate it.

**Comment by systemctls** [comment]
> If you can help this with a PR - will much appreciate it.

OK, give me some time and I'll try

**Comment by wingkwong** [comment]
@systemctls Please don't close the issue yourself next time. The issue will be closed and marked with the release version by github bot in the next release.
