### ISSUE TITLE
vue3 : Project metadata

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2715]
- [x] Project metadata
  - [x]  Metadata
    - [x] List models
    - [x] Is synced?
    - [x] Sync now
   - [x] UI Access Control
     - [x] List tables & views
     - [x] Search models
     - [x] Role Checkbox (change availability for role)

**Comment by dstala** [comment]
0729: manual tests
- Root DB: SQLite
- Project: MySQL

- [ ] Add new table
  - Hard refresh was required to make table names appear on project tree view
  - Table name isn't displayed
  
![Screenshot 2022-07-29 at 9 45 30 AM](https://user-images.githubusercontent.com/86527202/181681778-1dd15038-85bc-4f40-9ce6-3e7db87ecf49.png)

- [ ] Delete existing table
  - Table name isn't displayed
  
![Screenshot 2022-07-29 at 9 51 53 AM](https://user-images.githubusercontent.com/86527202/181684572-f88a9715-7652-4577-be54-6c80b84c259b.png)

- [ ] Rename table
- [x] Add column
- [x] Delete column
- [x] Rename column
- [x] Change column type
- [x] Add relation
- [x] Remove relation
