### ISSUE TITLE
vue3 : Settings > Team & Auth

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2717]
- [ ] #2825
  - [ ] List users (E-mail, Roles(chip), Actions)
      - [ ] New user
      - [ ] Edit user
      - [ ] Remove user
      - [ ] Filter (search)
- [ ] #2826
  - [ ] List tokens (Description, Token, Actions)
  - [ ] Add new token

**Comment by mustafapc19** [comment]
Closing this issue. Progress will be tracked in the sub issues.
