### ISSUE TITLE
vue3: Templates

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#2719]
Import from Excel, JSON, and CSV

- [x] Editor
  - [x] antdv integration
  - [x] parse template data
  - [x] create column with type - single line text
  - [x] create column with type - long text
  - [x] create column with type - numeric field
  - [x] delete table
  - [x] delete column 
  - [x] render icons
  - [x] autocomplete for column type
  - [x] validation
  - [x] spinning 
  - [x] style tuning
- [x] Create button
  - [x] create table(s)
  - [x] create column(s)
  - [x] bulk insert data 
  - [x] reload table
  - [x] add tab (the first table)

**Comment by dstala** [comment]
@wingkwong 
use attached XLSX to import; the first sheet name is displayed incorrectly as `Sheet1`; the actual sheet name is `Sheet2`
[simple.xlsx](https://github.com/nocodb/nocodb/files/9219538/simple.xlsx)

**Comment by dstala** [comment]
Issue in v1 as well

- allow support for links without supported extension suffix (.xlsx for example). Lets verify file extension after step-1 where we display attached file from URL.
https://go.microsoft.com/fwlink/?LinkID=521962
