### ISSUE TITLE
Feature: unique URL for each row (when previewed in a pop-up)

### ISSUE THREAD

**Issue by Victor239** [nocodb/nocodb#273]
When using the expand button to preview a row in a pop-up, it would be useful if the URL changed to match this unique row. This enables saving specific rows to bookmarks, sharing links, it allows browser history to track which you've viewed, going forward and back in tab history, etc.

**Comment by n-sviridenko** [comment]
Yes, this is super important for us as well. As we want to use nocodb as a CRM, so we want to share links to different rows. And currently we're unable to do this :-(
