### ISSUE TITLE
small problem with the menu UI under the settings module

### ISSUE THREAD

**Issue by systemctls** [nocodb/nocodb#2737]
**Please enter the following details**

```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.92.4**
```

**Steps To Reproduce**

1. Go to `my project`
2. Click on `Team & Settings`
3. Click on `Revidere` 

![image](https://user-images.githubusercontent.com/37177191/179732626-90533730-2c30-4ef7-9af9-623e94ff1621.png)

**Comment by systemctls** [comment]
There are two scrollbars, and I think only one should appear. Scrolling in the tables area will look much better

**Comment by o1lab** [comment]
Please help us with a pull request 🙏

**Comment by wingkwong** [comment]
@systemctls Please don't close the issue yourself next time. The issue will be closed and marked with the release version by github bot in the next release.

**Comment by systemctls** [comment]
> @systemctls Please don't close the issue yourself next time. The issue will be closed and marked with the release version by github bot in the next release.

OK
