### ISSUE TITLE
[i18n] Language support extension-fr

### ISSUE THREAD

**Issue by yohanboniface** [nocodb/nocodb#2743]
# i18n translation request

**Please enter the following details**

1. Select applicalbe
- [ ] **New language support request**
- [x] **Existing language translation corrections request** 
Verify if language support already exists in the NocoDB i18n master spreadsheet [here](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172)

2. Associated language code (pick from [here](https://developers.google.com/admin-sdk/directory/v1/languages)): fr

3. Google spreadsheet
https://docs.google.com/spreadsheets/d/1kxJA67bUkjJpYzpqekvpIm34aERtcCvixpRVw55rrhU/edit?usp=sharing

4. Summary of the changes made
- You can highlight modified items in the Spreadsheet attached/shared, to help us quickly identify changeset

I've made a lot of small fixes in French translation: mainly typo, some consistency changes.
Highlighting any changed value would be quite long, can you update all French strings ?
And maybe add in the i18n doc to highlight changed cells, so next time one will do it on the fly :)

Thanks!

**Comment by dstala** [comment]
@yohanboniface Spreadsheet link isn't made public. Can you mark access as public?

**Comment by yohanboniface** [comment]
Oops, sorry, it's now fixed!
