### ISSUE TITLE
How to refresh the database?

### ISSUE THREAD

**Issue by systemctls** [nocodb/nocodb#2745]
**Please enter the following details**

How to refresh the database?

Through other tools to redesign the table, nocodb cannot synchronize after adjusting the column name order。

```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.92.4**
```

**Comment by dstala** [comment]
@systemctls 
- You can perform `schema sync` for changes carried outside NocoDB. Details [here](https://docs.nocodb.com/setup-and-usages/sync-schema)
- NocoDB retains column order applied using its UI. Details to re-arrange columns on NocoDB UI are [here](https://docs.nocodb.com/setup-and-usages/column-operations#re-order-columns)

**Comment by systemctls** [comment]
> @systemctls
> 
> * You can perform `schema sync` for changes carried outside NocoDB. Details [here](https://docs.nocodb.com/setup-and-usages/sync-schema)
> * NocoDB retains column order applied using its UI. Details to re-arrange columns on NocoDB UI are [here](https://docs.nocodb.com/setup-and-usages/column-operations#re-order-columns)

thank you í get it
