### ISSUE TITLE
[Feature] Include the name of the deleting project into the dialog

### ISSUE THREAD

**Issue by nilsreichardt** [nocodb/nocodb#2752]
https://user-images.githubusercontent.com/24459435/179985397-7ffb4b43-fb30-40cd-a9ca-acae808a1d36.mov

At the moment, the name of the project is not included into the confirmation dialog. This can be very dangerous. It would be more helpful to include the name of the project into the dialog, like: "Do you want to delete the project "airtable-import-test"?

**Comment by o1lab** [comment]
@nilsreichardt : help us with a PR please :)

**Comment by bcakmakoglu** [comment]
@o1lab Current version of the UI already shows the name of the project in the delete dialog 😉 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/78412429/190014785-8fbccb4e-8b53-47a9-a659-e3131cb74a4e.png">

**Comment by o1lab** [comment]
thank you @bcakmakoglu
