### ISSUE TITLE
Table List is not refreshing and removing deleted table list when table is deleted

### ISSUE THREAD

**Issue by drdomark** [nocodb/nocodb#276]
please provide the following details :
NocoDB used as docker : false
NocoDB version : 0.9.3
Database used in NC_DB URL  : defaults to sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created : sqlite3
OS on which NocoDB is running : linux
Node.js version if running as node : 12
Database version : used by nocodb

**Steps To Reproduce**
1. Go to Table and create table, open it in tab. Create another table, open it in tab
2. Move to previous table tab and delete it
3. In table list, table still remains

**Expected behavior**
Should be removed when deleted

**Comment by o1lab** [comment]
Do you see any errors in console / network tab ?

We see it is functioning fine.

**Comment by drdomark** [comment]
No. There were no errors in console/network tab.
Seemed to be css issue.
If it is working for you then may be later will try reinstalling it. Could be some minor caching issue
Closing for now.
