### ISSUE TITLE
[Feature] Horizontal scroll

### ISSUE THREAD

**Issue by systemctls** [nocodb/nocodb#2775]
## Recommending Features

**Need for this feature**

Horizontal scroll

When a table has many columns, it is difficult to scroll horizontally. At present, you can only drag the scroll bar at the bottom of the page with the mouse. I find it difficult to use。

**Describe the solution you'd like**
I think there are two optimization schemes。

1. Space and mouse drag, like Axure or PS 
2. Mouse wheel control 
3. No space is required. In the table view container, the mouse can control horizontal scrolling instead of dragging the scroll bar

**Describe alternatives you've considered**

I looked up some information,  

`better-scroll.js` or use `addEventListener`

**Additional context**

https://github.com/ustbhuangyi/better-scroll

**Comment by lublak** [comment]
@systemctls you can also use shift scroll for this.
Just press hift and scroll. For me it works fine to scroll horizontal.

**Comment by systemctls** [comment]
> @systemctls you can also use shift scroll for this. Just press hift and scroll. For me it works fine to scroll horizontal.

Thank you. It's great. I just lacked a rolling method before. Now shift can meet my needs

**Comment by lublak** [comment]
@systemctls Just for your information. Shift scroll can be used in any application with a vertical scroll bar :).
This input is a standard.

**Comment by o1lab** [comment]
Shift + Scroll does this. Amazing.

Closing this.
