### ISSUE TITLE
[Feature] One-to-One Relationship

### ISSUE THREAD

**Issue by lublak** [nocodb/nocodb#2777]
## Recommending Features

Unfortunately, there is currently no 1-to-1 relationship. But I would like to use it to provide status codes with a description.

**Need for this feature**

I have a table where numbers have to be entered. These number codes are stored in the database by another system with a description.

code_description_table
| number | description |
| ------ | ----------- |
| 890    | test        |
| 840    | work        |

Now I have a second table with inputs.

input_table
| somefield | anotherfield | code |
| --------- | ------------ | ---- |
| blabliblu | lala         | 890  |

Of course, it is not pleasant to work with such numbers.
Therefore, a dropdown would be really cool which displays the description in the dropdown instead of the number (i.e. code_description_table.description). So link record but only with a single value.

**Describe the solution you'd like**

![grafik](https://user-images.githubusercontent.com/44057030/180144493-7ec859f3-2f23-4adb-a777-7becc7654444.png)

With input_table.code, it would make sense to place a foreign key on code_description_table.number.

**Comment by syji35** [comment]
We also need this feature

**Comment by o1lab** [comment]
Tracked in #491
