### ISSUE TITLE
[Feature] unique columns

### ISSUE THREAD

**Issue by lublak** [nocodb/nocodb#2778]
## Recommending Features

Unique columns based on sql indices.

**Need for this feature**

There is often the problem that certain data may not be entered twice. Unique columns are excellent for this.

**Is your feature request related to a problem? Please describe.**

You cannot prevent data from being entered twice.

**Describe the solution you'd like**

A function that makes it possible to define a single column or several columns as a group as unique.
(In sql you can also group several columns as a unique index).
One: The value only occurs once
Multiple: The combination of values only occurs once

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/4728
