### ISSUE TITLE
Why is initEmail commented out?

### ISSUE THREAD

**Issue by toddheslin** [nocodb/nocodb#278]
This isn't as much of a bug as a question. We set up an instance and the product owner set up their account and they added me to the instance. I didn't receive an email so I checked the logs and found:

```
xc_1    | Warning : `mailSend` failed, Please configure emailClient configuration.
xc_1    | Password reset token : xxxxxxxxxxxxxxxxxxxxxx
xc_1    | POST /auth/password/forgot 200 51 - 16.826 ms
```
Which I figured out I could just hit the reset endpoint with this token (`/password/reset/xxxxxxxxxxxxxxxxxxxxxx`)and I'd be good to go. That worked.

But when I was looking how to configure the email adapter it looks like it has been commented out in the source code. I'm just a bit confused why this is.

https://github.com/nocodb/nocodb/blob/master/packages/nocodb/src/lib/noco/meta/NcMetaMgr.ts#L979-L988

Thanks!

**Comment by pranavxc** [comment]
That's our older implementation and we are no longer using it. Currently, we are initializing it from `NcPluginMgr` and you have to provide SMTP details under AppStore.
