### ISSUE TITLE
sort UI broken

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2781]
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.4**

- xcdb project, create table
- keep adding sort options without making any actual configurations

![Screenshot 2022-07-21 at 12 14 18 PM](https://user-images.githubusercontent.com/86527202/180148809-b2c18336-88fe-4612-8406-f7a93a9abccd.png)

**Comment by o1lab** [comment]
Good to close now.
