### ISSUE TITLE
[Feature] conditions for valid data

### ISSUE THREAD

**Issue by lublak** [nocodb/nocodb#2783]
## Recommending Features

The possibility to restrict data to certain values.

**Need for this feature**

Currently there are no possibilities to limit the data entered in the value range.
I know from the postgres sql world that you can limit data.
As an example:

```sql
CONSTRAINT purchasing_check_month CHECK (((month >= 1) AND (month <= 12)))
CONSTRAINT purchasing_pages_check_page_path CHECK (((page_path)::text ~ '^([a-zA-Z0-9\-_ ]+\/)+[a-zA-Z0-9\-_ ~]+\.[tT][iI][fF]'::text))
```

**Is your feature request related to a problem? Please describe.**

Currently, any type of data can be entered. Whether they are valid or not.

**Describe the solution you'd like**

The possibility of setting such constrains minimally.
A few standards should be sufficient at the beginning.
- regex
- min/max

**Comment by dstala** [comment]
To be tracked along with 
[🔦 Feature: Need option to add validation to each column before values are added](https://github.com/nocodb/nocodb/issues/3872)
