### ISSUE TITLE
vue3: Projects

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#2786]
- Project list - table view
     -  Pagination
     -  Reload
     -  Filter
     -  Edit
     -  Delete 
     -  Create button
- Project with external database connection
     -  Test connection
     -  SSL file upload option
     -  Schema select option for pg and mssql
     -  Validations
     -  Monaco editor for custom JSON
- Xcdb project creation page
- Project title edit page

**Comment by o1lab** [comment]
Closing this for #2786
