### ISSUE TITLE
Postgres SSL connections error

### ISSUE THREAD

**Issue by lublak** [nocodb/nocodb#2792]
**Please enter the following details**

```
NocoDB used as docker : false
NocoDB version : 0.92.4
Database used in NC_DB URL  : NC_DB=pg://localhost:5432?u=postgres&p=password&d=newdb
Project was created  by clicking : no
Database on which spreadsheet is created : no
OS on which NocoDB is running : Windows Server 2016
Node.js version if running as node : v16.15.0
Database version : 
```

**Steps To Reproduce**

1. https://docs.nocodb.com/getting-started/installation#npx
2. npx create-nocodb-app
3. select pg
4. keep localhost
5. keep port
6. keep username
7. input password
8. use existing shema name
9. as node.js project
10. edit index.js to another port: 8097
11. npm install
12. npm start

**Expected Behavior**

Should run fine.
It works fine if i use sqlite3 und use postgres as an external database source.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/44057030/180198295-2e519351-ea75-4e0b-8229-d99fb837fb39.png)

**Comment by nith2001** [comment]
I'll take this issue in case no one else has!

**Comment by nith2001** [comment]
Either way, I'm using port 5433 for postgres, even though it kills me to do so. I replicated all of your steps and got the following:

Here's my `index.js`:
```
(async () => {
    try {
        const app = require('express')();
        const {Noco} = require("nocodb");
        const httpServer = app.listen(process.env.PORT || 8097);
        app.use(await Noco.init({}, httpServer, app));
    } catch(e) {
        console.log(e)
    }
})()
```
And I got this:
<img width="682" alt="Screen Shot 2023-04-19 at 12 23 45 AM" src="https://user-images.githubusercontent.com/75632283/232999763-e3c04515-e4ab-4f5e-b836-94e8cd427bc2.png">

**Comment by nith2001** [comment]
Fixed my Postgres to use Port 5432, got the same issue as above again.

**Comment by dstala** [comment]
Closing this issue. Thanks @nith2001 for detailed analysis and report on this.
