### ISSUE TITLE
Error starting in node version v15.14.0 for package azure-function-express@2.0.0

### ISSUE THREAD

**Issue by rjbergerud** [nocodb/nocodb#280]
**Please enter the following details**

please provide the following details :
NocoDB used as docker : false
NocoDB version : 0.9.31
Database used in NC_DB URL  : none
OS on which NocoDB is running : 
Node.js version if running as node : 
Database version : 

**Steps To Reproduce**
1. Go to packages/nocodb/
2. run `yarn install`

```
error azure-function-express@2.0.0: The engine "node" is incompatible with this module. Expected version ">=6.11.2 <11". Got "15.14.0"
error Found incompatible module.
```

Give that Node v14 is the active LTS version, shouldn't dependencies support Node versions >=14?  Node v10 just reached end of life. 

**Expected behavior**
Install all packages

**Screenshots**

Node version : **v15.14.0**
Arch type: **arm64**
Platform: **mac**
Docker: **false**
packageVersion: **0.9.31**

**Comment by pranavxc** [comment]
The `azure-function-express` package is no longer used in our project, please try it now.
