### ISSUE TITLE
Table UI disappears after Page Refresh

### ISSUE THREAD

**Issue by arladmin** [nocodb/nocodb#281]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.9.31**

After a table is refreshed, (Ctrl+R or Ctrl+Shift+R) [Win 10], every now and then, the table UI disappears. 
It does not comes back unless the table is deleted and recreated.
Even docker container restart does not work!

**Screenshots**
![image](https://user-images.githubusercontent.com/64059154/122002323-39686780-cdcf-11eb-9e29-562eb7a02fc5.png)

Audit Trail:
![image](https://user-images.githubusercontent.com/64059154/122002292-2eadd280-cdcf-11eb-89a4-2c9f9cd04d4a.png)

**Comment by arladmin** [comment]
Hi, has there been any update regarding this bug?

**Comment by pranavxc** [comment]
@arladmin  please try our latest release, if the problem persists share the latest error details.

**Comment by o1lab** [comment]
Feel free to reopen if the issue persists
