### ISSUE TITLE
[Feature] Duplicate table

### ISSUE THREAD

**Issue by include** [nocodb/nocodb#2821]
First and foremost - thank you very much for this awesome open-source tool!

I think it would be very useful to be able to clone tables and its views. Simple as that :)

In some situations I need to have the same data replicated into a new table where I can take the old views and revamp them.

A community member came with the idea to integrate AppSmith to do this from API (clone the table) but the views might be a little bit more difficult.

Cheers,
F

**Comment by o1lab** [comment]
Views Can be duplicated

**Comment by include** [comment]
Hi @o1lab thanks for teaching me that :) the icon is so subtle that didn’t noticed it.
How about cloning a table? Am I missing something? thanks.

**Comment by dstala** [comment]
@include cloning table is currently not supported.

**Comment by include** [comment]
@dstala is it something you imagine it would be possible in the future?!

**Comment by o1lab** [comment]
ya sure - this should be possible.

**Comment by 3dprogramin** [comment]
Until the feature is developed and released, is there an easy way to do it manually ? Like creating the DB tables, with specific names, etc.
I have a table with 30+ columns which would constantly need to be recreated.
Tedious to do it by hand.

**Comment by o1lab** [comment]
If there are no relations to this table - then it would be easy. 
- Just hover on the table name with `alt` key pressed - it will show the real name of table in the database. 
- And then you can go duplicate the table in database.
- you will have to do [meta sync](https://docs.nocodb.com/setup-and-usages/sync-schema) before you can see that within the UI

**Comment by 3dprogramin** [comment]
@o1lab 
I tried that, it worked, but the new table is not quite the same.

Original table looks like this
![image](https://i.imgur.com/yteH50c.png)

New table after meta sync
![image2](https://i.imgur.com/2SupyeO.png)

Here are the differences:

- column names were originally snake case, new table has them pascal case
- the status column in original table is single select, while new table has it long text
- I can't modify most cells, getting the error in screenshot
- Id column was also cloned as "normal" row, not system row

Maybe there is a way to clone the project ?
That would also help

**Comment by Charuru** [comment]
Would like a way to do this in the API even if not in the UI yet.

**Comment by 3dprogramin** [comment]
Yes, that would help too.

**Comment by o1lab** [comment]
We added this a while ago.
