### ISSUE TITLE
vue3 : Add User Management (Team and Auth)

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#2825]
- [ ] List users (E-mail, Roles(chip), Actions)
      - [ ] New user
      - [ ] Edit user
      - [ ] Remove user
      - [ ] Filter (search)

**Comment by dstala** [comment]
- [ ] Roles configured not same as v1
  
![Screenshot 2022-08-08 at 10 53 53 PM](https://user-images.githubusercontent.com/86527202/183477032-0dbea78c-5286-4ca2-83d1-3535a3683e7d.png)

- [ ] SignUp URL doesn't work
- [ ] Close modal after error
  
![Screenshot 2022-08-08 at 10 57 11 PM (2)](https://user-images.githubusercontent.com/86527202/183477520-82a2ea9b-baab-4469-a844-3254906816f6.png)

**Comment by mustafapc19** [comment]
@dstala By signup url u mean shared base link? Or the invitation link?

**Comment by dstala** [comment]
- add new user, copy generated URL
- try sign-up using this URL (preferably on incognito mode or different browser profile)
