### ISSUE TITLE
Large tables fail to load

### ISSUE THREAD

**Issue by dismantl** [nocodb/nocodb#283]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.9.32**
NocoDB version : latest
Project was created  by clicking : New Project by connecting to external database

**Steps To Reproduce**
1. Create a connection to a remote database with large tables (20+ million rows)
2. Click on one of the large tables to bring up a tab with the first 25 entires and pagination controls, and wait for it to load.

**Expected behavior**
I would expect the first 25 rows to show up pretty quickly, however they are not displayed until the ajax request for the COUNT of the table completes. For large tables, the first 25 rows return almost immediately but the count request can take several minutes to return (and sometimes times out), and so the first 25 rows don't show up until the count request returns (if at all).

It would also be helpful to see some sort of loading graphic that lets me know it's still waiting for a query to the database to finish. Perhaps display the first 25 rows (since that's a quick query) and then the area for the pagination controls can have a loading graphic until the count is returned, at which point the pagination controls are displayed.

The database I'm using is public, in case you would like to test against it.

**Screenshots**
In this screenshot you can see the count request timed out at 4 minutes, while the first 25 rows are returned in 241ms. This particular table has 26 million rows.
![image](https://user-images.githubusercontent.com/2007008/122127594-66357280-ce01-11eb-9385-a863acd04994.png)

**Comment by o1lab** [comment]
Thanks for the detailed report, we will look into building a workaround.

**Comment by pranavxc** [comment]
> The database I'm using is public, in case you would like to test against it.

Can you DM me in discord : https://discord.gg/5RgZmkW
