### ISSUE TITLE
[Feature] is there any way to remember the login, instead of "Token expired" and need to relogin every day

### ISSUE THREAD

**Issue by bingyupiaoyao** [nocodb/nocodb#2839]
[Feature] is there any way to remember the login, instead of "Token expired" and need to relogin every day

**Comment by dstala** [comment]
@bingyupiaoyao 
You can configure environment variable `NC_JWT_EXPIRES_IN` to a larger number. Default value is 10.
You can find environment variable list [here](https://docs.nocodb.com/getting-started/installation#environment-variables)

**Comment by bingyupiaoyao** [comment]
thanks @dstala !
