### ISSUE TITLE
Enhancement: the loading animation should be placed in the middle of the screen

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#285]
Node: **v12.16.1**
Arch: **x64**
Platform: **win32**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **1.0.0**

**Steps To Reproduce**
1. Create a column called ``col1`` and click save (it also applies other scenarios)
2. Notice that the loading animation is located in top right area

**Expected behavior**

For the UX perspective, it should be placed in the middle of the screen and the size should be larger than the existing one. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35857179/122184182-90993580-cebe-11eb-992f-7e37db06f621.png)

**Comment by o1lab** [comment]
This is sorted now. Loading for meta is still at the top. However, data loading is at the center.
