### ISSUE TITLE
Vue3 : Project menu

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2855]
Having a project menu will help us use layout in a better way in the longer run.

We can have following parts in this menu.
- Project Settings
- User Settings (things on right of top navbar)
- Sign out

#### Menu options

<img width="402" alt="Screenshot 2022-07-27 at 14 24 45" src="https://user-images.githubusercontent.com/5435402/181270551-db38cac3-37d5-4947-87de-563c3e3d4839.png">

#### Nav drawer showing project name with a menu option

<img width="204" alt="Screenshot 2022-07-27 at 15 12 37" src="https://user-images.githubusercontent.com/5435402/181270373-0cd58c2a-41ed-471e-bc33-56b588df499a.png">

**Comment by dstala** [comment]
@bcakmakoglu 
- [ ] After opening the menu, allow `ESC` to close it 
- [ ] `Copy project info`, `Swagger` : Link to be configured
- [ ] For project ID display, would it be a good idea to a prefix 'ID' or 'Project ID'?

**Comment by bcakmakoglu** [comment]
@dstala Relevant PR: https://github.com/nocodb/nocodb/pull/3095

**Comment by bcakmakoglu** [comment]
I am not exactly sure - am I supposed to configure the Link for the Swagger stuff? 😄 Instructions unclear haha

**Comment by o1lab** [comment]
You can ignore the swagger part - @mustafapc19 is on it.

**Comment by bcakmakoglu** [comment]
Coolio
