### ISSUE TITLE
[Feature] Prefill form with default values

### ISSUE THREAD

**Issue by s-h-a-r-d** [nocodb/nocodb#2862]
**Need for this feature**
This would make it easier to verify that the correct default values are submitted.

**Is your feature request related to a problem? Please describe.**
Currently if for some reason you have setup the default value for a column wrong, or an update or something else has broken it, you can't be sure that the correct default value was submitted via form.

**Describe the solution you'd like**
Having the form automatically prefill the default value of a field (if one exists) would quickly tell the user that:

1. The default is set correctly.
2. The default value behaves correctly. (for example in case of `now()` in datetime field)

**Comment by LucBerge** [comment]
Hello, any update ?
