### ISSUE TITLE
[Feature] "Now"-button for datetime field in form view

### ISSUE THREAD

**Issue by s-h-a-r-d** [nocodb/nocodb#2863]
**Need for this feature**
Often you want to be able to pick "now" as the datetime. 

**Is your feature request related to a problem? Please describe.**
Currently you can set a default `now()` for the datetime. But if default for a datetime field is set to something else, then having a "now" button becomes very useful.

**Describe the solution you'd like**
A button next to the datetime field that sets the value to "now" or a button within the time/calendar picker that does the same like this:
![image](https://user-images.githubusercontent.com/5573972/181519402-6faeed55-1361-4377-9629-807d2028039d.png)

**Comment by dstala** [comment]
option available in v0.96.4
