### ISSUE TITLE
Image is not shown in gallery view when the attachment field is hidden

### ISSUE THREAD

**Issue by msjang** [nocodb/nocodb#2864]
Image is not shown in gallery view when the attachment field is hidden. If it is selected, then it shows well.

```
NocoDB used as docker : true
NocoDB version : 0.92.4
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : Rockey Linux 8
Node.js version if running as node : 
Database version : postgres alpine3.16
```

**Steps To Reproduce**

1. Go to 'Gallery View'
2. Click on 'Select Cover Image as an attachment field and hide that field below'
3. See error : No image found

**Expected Behavior**

The attachment would be shown

**Screenshots**
<img width="510" alt="nocodb-img-not-shown" src="https://user-images.githubusercontent.com/2688660/181586504-1114074c-09fe-48e2-bc7e-b5d7b461f3cb.png">

<img width="502" alt="nocodb-img-shown" src="https://user-images.githubusercontent.com/2688660/181586482-8f5492b5-41ae-4ea5-b208-e7500e3b3a43.png">

**Comment by o1lab** [comment]
Feel free to reopen if issue exists in latest release.
