### ISSUE TITLE
User invite email issues

### ISSUE THREAD

**Issue by dismantl** [nocodb/nocodb#287]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.9.32**

**Steps To Reproduce**
1. Invite new user with Viewer role
2. Email is sent to new user
3. Email text says `I invited you to be an Admin of the NocoDB project ". Click the button below to to accept my invitation.`

**Expected behavior**
- The email refers to the invited user as Admin regardless of the role they are given. So an invited user with just the Viewer role is still referred to as an Admin in the email.
- Second, the name of the project is missing from the email and instead just has a double quotation mark.
- Third, the salutation says `Thanks regards Super admin@example.com` which is strange wording, I'm not sure what "Super" refers to.

**Screenshots**
<img width="581" alt="Screen Shot 2021-06-16 at 12 06 11" src="https://user-images.githubusercontent.com/2007008/122254741-68e4a600-ce9b-11eb-9b3e-68913771b5e6.png">

**Comment by wingkwong** [comment]
@dismantl Thanks for reporting. I'll make a PR in the coming days.

**Comment by pranavxc** [comment]
Updated in latest version
