### ISSUE TITLE
Swagger UI doesn't use NC_PUBLIC_URL

### ISSUE THREAD

**Issue by dismantl** [nocodb/nocodb#288]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.9.33**

**Steps To Reproduce**
1. Run NocoDB using Docker, and set the NC_PUBLIC_URL environment variable (e.g. `NC_PUBIC_URL=https://nocodb.example.com`). Serve the site at that URL using a reverse proxy.
2. From NocoDB (at the public URL), click avatar > Swagger APIs Doc to open the Swagger UI
3. Despite being served from the public URL, Swagger shows the base URL as localhost:8080, which causes the endpoints to fail when tested.

**Expected behavior**
I would expect Swagger to use the public URL to generate the REST endpoints.

**Screenshots**
![image](https://user-images.githubusercontent.com/2007008/122275796-1a8ed180-ceb2-11eb-9146-0ccbd5886d94.png)

![image](https://user-images.githubusercontent.com/2007008/122275858-2d090b00-ceb2-11eb-838d-e7f85ab628b2.png)

**Comment by JosXa** [comment]
There is no pull request linked to the closing of this issue. Has it been fixed @pranavxc?

**Comment by pranavxc** [comment]
@JosXa : it's fixed in the latest version, please try it .... `0.9.40`

**Comment by JosXa** [comment]
Ah, that one just isn't on docker hub yet. I'll wait :)
