### ISSUE TITLE
vue3: Rating Cell

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#2894]

**Comment by dstala** [comment]
@wingkwong 

- [x] Migration from v1: values & color, icon & max value configured verified
- [ ] Advanced configuration options are missing. Intended? v1- reference captured here.
  
![Screenshot 2022-08-02 at 12 00 59 PM](https://user-images.githubusercontent.com/86527202/182307285-6277f6dc-4428-468b-9fad-4b0e83fa730a.png)
![Screenshot 2022-08-02 at 12 01 53 PM](https://user-images.githubusercontent.com/86527202/182307563-49eada2f-2c79-4839-b752-9d018054df48.png)

**Comment by wingkwong** [comment]
@dstala That's the in the scope of Rating Column. Will be handled in another PR. This PR only focuses on Rating Cell (like how it displays)
