### ISSUE TITLE
vue3: Percent Cell

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#2895]

**Comment by dstala** [comment]
- [ ] `e` wasn't allowed as input in v1. Try entering 34e45; it gets stored as 3.4e46; in the database, it's recorded as 340000.00

**Comment by wingkwong** [comment]
By design, `e` is not allowed. How can you type `e` in v2?

**Comment by pranavxc** [comment]
> By design, `e` is not allowed. How can you type `e` in v2?

Copy & paste may be possible

**Comment by dstala** [comment]
I just typed 34e45; stored as 3.4e46
