### ISSUE TITLE
Audit Log - DELETE is not right now recording...

### ISSUE THREAD

**Issue by manobalas** [nocodb/nocodb#290]

**Comment by pranavxc** [comment]
Can you provide more details? Are you referring to row delete or table delete or something else?

**Comment by manobalas** [comment]
Yes...
Like now... When updating the audit record is creating.
Like wise.. for delete of a row/record from a table... And deletion of table should be logged... As they are more important... Can say what record they deleted etc...

**Comment by pranavxc** [comment]
Actually, it seems working for me locally. can you share the screenshot of the audit table? You can share it here or DM me in discord(https://discord.gg/5RgZmkW).

Also share the app info(docker version, node version, etc...) you can get it easily as follows.


![projectinfo mov](https://user-images.githubusercontent.com/61551451/122404516-ecd28700-cf9c-11eb-81c4-9c15bdae93b3.gif)

**Comment by manobalas** [comment]
Yes, it's there in new version, in old it was not..
