### ISSUE TITLE
Can't add new record for many-to-many field

### ISSUE THREAD

**Issue by Arkronus** [nocodb/nocodb#2900]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.92.4**
```
I receive an error when try to add a record with many-to-many relationships.

I have a database with following schema
![изображение](https://user-images.githubusercontent.com/6567321/181933738-334775e9-3e48-4d9c-87ed-7ca9aa6b6cdd.png)

I can see order_items list input
![изображение](https://user-images.githubusercontent.com/6567321/181933773-b00e6975-f7ec-4149-9562-ff8094e3f8ac.png)

Then I click to 'Link to order_items' and New Record

![изображение](https://user-images.githubusercontent.com/6567321/181933830-f8a488e9-4bde-4f4b-8ce4-26b82c9776df.png)

I see form for order_items, but when I click 'Save Row' I receive an error

![изображение](https://user-images.githubusercontent.com/6567321/181933895-c283ae6d-f1d2-4262-85d2-7eec9a1a42fa.png)

I also found this error message in terminal

```
nocodb_1   | TypeError: Cannot read property 'column_name' of undefined
nocodb_1   |     at t.BaseModelSqlv2.insert (/usr/src/app/docker/main.js:2:1149813)
nocodb_1   |     at runMicrotasks (<anonymous>)
nocodb_1   |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
nocodb_1   |     at async v (/usr/src/app/docker/main.js:2:1465539)
nocodb_1   |     at async /usr/src/app/docker/main.js:2:37086
nocodb_1   | v :: TypeError: Cannot read property 'column_name' of undefined
nocodb_1   |     at t.BaseModelSqlv2.insert (/usr/src/app/docker/main.js:2:1149813)
nocodb_1   |     at runMicrotasks (<anonymous>)
nocodb_1   |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
nocodb_1   |     at async v (/usr/src/app/docker/main.js:2:1465539)
nocodb_1   |     at async /usr/src/app/docker/main.js:2:37086
nocodb_1   | POST /api/v1/db/data/noco/WMS/order_items 400 57 - 19.280 ms
```

**Expected Behavior**

I should be able to add a new record.

**Comment by o1lab** [comment]
Thank you for the detailed report.

**Comment by o1lab** [comment]
Feel free to reopen if the issue exist in latest release. Latest release has completely revamped UI.
