### ISSUE TITLE
[Feature] Access old field values in webhooks

### ISSUE THREAD

**Issue by rallisf1** [nocodb/nocodb#2902]
**Need for this feature**
Most times I only want to be notified when a certain change is made: e.g. when a status changes from `pending` to `completed`. Right now we only have access to the latest field values both in the webhook body and conditions, thus we can never know what the old field values were. e.g. If I update any field value in a row but not `status` which is already `completed` my on update webhook whose only condition is `where status is equal completed` will still fire and that is wrong for my usecase.

**Describe the solution you'd like**
I'd like to access old field values both in the webhook body (e.g. with prefix `old.`) and in the conditions (e.g. an "Old Values" optgroup inside the dropdown).

**Describe alternatives you've considered**
The only dirty workaround is to keep historical data in a separate table, write the condition logic in my own middleware backend and update the historical data via the API.

**Comment by o1lab** [comment]
Ok, makes sense - we will think about this.

Within audit ( `team & auth` > `audit` ) there will be history. Just a hint.

**Comment by DarkPhoenix2704** [comment]
Hi @dstala , May i know if this is in your roadmap for future releases?

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/3869
