### ISSUE TITLE
[i18n] Language support extension- <language code>

### ISSUE THREAD

**Issue by abosaudtech** [nocodb/nocodb#2904]
# i18n translation request

**Please enter the following details**

1. Select applicalbe
- [ ] **New language support request**
- [ ] **Existing language translation corrections request** 
Verify if language support already exists in the NocoDB i18n master spreadsheet [here](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172)

2. Associated language code (pick from [here](https://developers.google.com/admin-sdk/directory/v1/languages)): 

3. Google spreadsheet
- Procedure to share google spreadsheet can be found [here](https://support.google.com/docs/answer/2494822?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cshare-a-file-publicly) 
  - When requested, select public sharable link. 
- Alternatively, you can download & attach a spreadsheet here along with the issue as well. 
- [ ] **Attached**
- [https://docs.google.com/spreadsheets/d/1pqgTZLYpuaklaRitN4ugSjOEn-HI3nLfrPs8E9YObzI/edit?usp=sharing ] **Shared link**:

4. Summary of the changes made
- You can highlight modified items in the Spreadsheet attached/shared, to help us quickly identify changeset

5. Any specific message to be conveyed to moderators?
- Help us simplify the process if you find something hard about it

**Comment by abosaudtech** [comment]
Please add Arabic language and thank you

**Comment by dstala** [comment]
@abosaudtech 
Help us confirm if the translation captured here sounds right (column `AG` has Google translated words for language code `ar`)
https://docs.google.com/spreadsheets/d/1tArskq7SWdRIHHzXXqIDEO_2TbaOpTemEzSfRhCUP2A/edit?usp=sharing

**Comment by abosaudtech** [comment]
It is better than nothing and need some editing.

**Comment by abosaudtech** [comment]
I can do it for you and translate it to arabic I have good experience in
this manner

**Comment by dstala** [comment]
@ abosaudtech
You can edit that spreadsheet itself & share it with us. We will do the rest of the grunt work.

**Comment by abosaudtech** [comment]
Thank you for giving me the opportunity to collaborate with you.
Below You will find the copy that I edit it.

 edited noco-i18n-ar
<https://docs.google.com/spreadsheets/d/1g2fk7NKXDW4u6OtUuFOW_UJgKz4wKFWePihQMXMMiqs/edit?usp=drive_web>

https://docs.google.com/spreadsheets/d/1g2fk7NKXDW4u6OtUuFOW_UJgKz4wKFWePihQMXMMiqs/edit?usp=sharing
