### ISSUE TITLE
vue3: Attachment Cell

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#2912]
Attachment cells are used to keep attachments.  By default, we are using local storage to keep the files, and in the database keeping the URL as a JSON array string. 
 

## Attachment cell

 <img width="233" alt="image" src="https://user-images.githubusercontent.com/61551451/182098599-62de51de-eca3-420a-a3ac-e6a972a8851c.png">

  -  [x] Clicking <kbd>+</kbd>  icon user could able to upload new image
  -  [x] Expand icon on the right side will open a modal with images
     <img width="857" alt="Screenshot 2022-08-01 at 1 24 31 PM" src="https://user-images.githubusercontent.com/61551451/182100685-ce97f3ee-0e4e-4ebf-b197-1ae5b05b560b.png">
  - [x] On clicking an attachment in the cell it should be open in a full-screen slider
    <img width="1440" alt="Screenshot 2022-08-01 at 1 29 43 PM" src="https://user-images.githubusercontent.com/61551451/182101702-23934321-2a91-4567-8a4e-93a3be01b217.png">
   - [x] There should be a read-only mode, the user can only view cell content. You can get the state by `ReadonlyInj`.

## Expanded modal

<img width="849" alt="Screenshot 2022-08-01 at 1 21 42 PM" src="https://user-images.githubusercontent.com/61551451/182100977-9a4c148e-cef3-44e5-83a6-0dbd0493babc.png">

 - [x] Remove option for images
 - [x] Download option for downloading attachment
 - [x] A button for uploading new attachments
 - [x] Attachements should be sortable    
   <img width="873" alt="Screenshot 2022-08-01 at 1 19 45 PM" src="https://user-images.githubusercontent.com/61551451/182099859-22653fb5-6a9d-4e70-b104-40c43837ef89.png">

## Attachment Slider overlay

<img width="1440" alt="Screenshot 2022-08-01 at 1 29 43 PM" src="https://user-images.githubusercontent.com/61551451/182102251-93904f60-c443-4b8d-8142-46f1331ff6a7.png">

- [x] At the top there should be a download button
- [x] Middle of the screen a slider with next and prev icon
- [x] Bottom small navigation with thumbnails

----

For v1 implementation refer following file :  `packages/nc-gui/components/project/spreadsheet/components/editableCell/EditableAttachmentCell.vue`

> Note : Will add more details later

**Comment by dstala** [comment]
- [ ] for an empty cell, v1 showed both options : `+` and `expand cell`; v2 shows equivalent to only `+` as `add files`. I couldn't attach by using drag drop feature until i upload at least one image
  
![Screenshot 2022-08-09 at 7 09 24 PM](https://user-images.githubusercontent.com/86527202/183664312-9272e72c-4a3a-4332-bc78-fd90220b07f3.png)
![Screenshot 2022-08-09 at 7 10 02 PM](https://user-images.githubusercontent.com/86527202/183664334-46f99396-5a53-450c-81ea-4dcfbfffef67.png)


- [ ] [minor] attachment cell row height can be restricted when we add many files

v1
  
![Screenshot 2022-08-09 at 7 07 15 PM](https://user-images.githubusercontent.com/86527202/183663063-f6d1912f-b2ea-449b-bbd3-93a9ef0c7353.png)
  
v2
  
![Screenshot 2022-08-09 at 7 08 25 PM](https://user-images.githubusercontent.com/86527202/183663343-4b7a7ba9-a741-475a-a3bf-54bec88b428f.png)

**Comment by bcakmakoglu** [comment]
@dstala what is the exanded cell supposed to show when there are no images? it would just be an empty modal then?

I can't seem to reproduce the drop issue. Dropping works fine regardless if there is an image already or not.

Were there any errors in the console when you try to drop into an empty attachment Cell?

**Comment by dstala** [comment]
@bcakmakoglu 
Expanded cell will open a modal to drop images (wouldn't be required if you have configured to let images to be dropped on to cell directly). If I drop images on to cell, image opens in a separate tab in browser - chrome. No error observed in console.

**Comment by bcakmakoglu** [comment]
@dstala 
Dropzone should work correctly now, please try again 😄 
I added a maxheight and made the cell scroll if there's too many items to show at once
