### ISSUE TITLE
Set Content-Type when upload file

### ISSUE THREAD

**Issue by Asindo** [nocodb/nocodb#2918]
Dear team,

When uploading file to S3 through NocoDB, the default value of Content-Type is "application/octet-stream", How can we set the value of Content-Type? such as set it to "Image/png", thanks！

**Comment by o1lab** [comment]
Possible to send this in request header ? please help send a PR if you can

**Comment by Asindo** [comment]
My nocoDB deployed in ECS, can we update request header in task definition? or there are other ways we can update this?
![image](https://user-images.githubusercontent.com/40680075/182811652-8df614ae-a31d-4acd-a772-561cb602a96f.png)

**Comment by Asindo** [comment]
@o1lab ， dear team, may I know if any updates on this? thanks

**Comment by wingkwong** [comment]
I think it'd be better if we could include the option in S3 plugin setting page instead of using an environment variable. Currently this has been marked as enhancement and is not taken by anyone yet. A PR is always welcome.

**Comment by Asindo** [comment]
@wingkwong , Many thanks! Finally ask, could you please tell me when you can release this option if you can?
