### ISSUE TITLE
vue3: TimePicker Cell

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#2921]

**Comment by dstala** [comment]
- Invalid time displayed for a valid time configured in v1
![Screenshot 2022-08-01 at 7 12 11 PM](https://user-images.githubusercontent.com/86527202/182161334-de8374ac-cd02-4c77-83eb-5e448897216f.png)

**Comment by bcakmakoglu** [comment]
Haven't checked but if the code is ok maybe the plugins aren't installed because people import dayjs from 'dayjs' and not from utils 😅 
Relevant PR: #2933

**Comment by mustafapc19** [comment]
@dstala @bcakmakoglu Seems to be the issue with dayjs

**Comment by mustafapc19** [comment]
@dstala We can use 24hours format as well. 12hr looked better so I chose that. I am fine with both ways. I personally find 24 hours harder to calculate 😅

**Comment by dstala** [comment]
@mustafapc19 

pull latest changes - could still see `invalid time`
- could see entered values being stored in DB (MySQL)
- spreadsheet cell, it's still showing `invalid time`
