### ISSUE TITLE
vue3: JSON cell

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#2923]

**Comment by dstala** [comment]
@mustafapc19 

- [ ] Monaco editor dropped?
- [ ] Error message reporting frequency is quite high - currently is on every keystroke. Let us have it on `enter` key or `change of focus` (moving away from cell)
  
![Screenshot 2022-08-08 at 4 54 29 PM](https://user-images.githubusercontent.com/86527202/183407450-1850d430-d03d-4bfe-b31d-873299bc8396.png)
  
- [ ] Edit cell needs fix
  
![Screenshot 2022-08-08 at 4 56 35 PM](https://user-images.githubusercontent.com/86527202/183407846-10315cf5-c96c-42e0-a6a9-1e01812927d9.png)

Verified
- [x] Insert & Clear cell
- [x] Sort & Filter

**Comment by mustafapc19** [comment]
@dstala I don't see issue from my side. We are still using Monaco editor
