### ISSUE TITLE
[vue3] Development/merge issues

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2938]
Quick tests

Rebased at 1200 IST /develop
[Merge pull request](https://github.com/nocodb/nocodb/commit/c2917d090bc27456856d2ad730a78d429f0d8a88) https://github.com/nocodb/nocodb/pull/2992 [from nocodb/fix/grid-view](https://github.com/nocodb/nocodb/commit/c2917d090bc27456856d2ad730a78d429f0d8a88)

## Common

-------------------

### Pranav (@pranavxc)
- [x] Filter delete not working
- [x] Rename active tab table; active tab changes to `team and auth`
- [x] Currency column data is not getting saved
- [x] Rename column, data vanishes (hard refresh brings it back)
- [x] Tooltip for column headers missing
- [x] `Decimal` cells are RO
- [x] `default` columns are displayed empty for first time (hard refresh required after enabling system columns)
  
![Screenshot 2022-08-04 at 2 39 20 PM](https://user-images.githubusercontent.com/86527202/182809768-b5df489a-7882-4490-9d32-e8124dc80ac1.png)

- [x] Allow data-type search by typing during column creation
  
![Screenshot 2022-08-04 at 1 13 49 PM](https://user-images.githubusercontent.com/86527202/182792655-f83c575a-95c9-4f2b-a93a-83c05139ce98.png)
  
- [x] `Record Count` in bottom of page isn't refreshed automatically
- [x] `Warning` information toast message for validation failure (Email/URL) when enabled isn't being displayed
- [x] `Default` value configured for column's not applied
- [x] Edited column parameters need a hard refresh to be applied: Ex: Currency column, change from `USD` to `EUR`
- [x] `Enter` after editing a cell navigates to right instead of next row in same column
- [x] NocoDB icon appears to flicker in spreadsheet tab because of overlap with `loading` icon during any activity. Example: Reload table
- [x] `Gallery view` share view was disabled in v1. Enabled in v2. Intended?
- [x] Tabs are not reset after we toggle to a different/new project. 
- [x] Tabs not removed on `delete table`
- [x] Console error on `delete column` operation
  
![Screenshot 2022-08-04 at 12 54 49 PM](https://user-images.githubusercontent.com/86527202/182788686-9a30a792-576e-4b5a-afea-5166592fc9b7.png)

- [x] Filter doesn't show blue dot `active` badge, after we re-open table tab even if we have a filter configured. Sort & Fields menu badge works just fine.
 
![Screenshot 2022-08-02 at 9 56 55 AM](https://user-images.githubusercontent.com/86527202/182291836-7661ec6f-aa37-4655-be3c-691c02eea21e.png)
-------------------

### Burak (@bcakmakoglu)
- [ ] Highlight the view name that's currently active in the right navigation bar (as in v1)
  
![Screenshot 2022-08-01 at 9 55 00 PM](https://user-images.githubusercontent.com/86527202/182197473-0d4836a2-c084-487a-8222-ab218be761eb.png)

- [ ] Dropping attachment on cell didn't work. UI for attachment cell looks very clean. 
  
![Screenshot 2022-08-04 at 5 28 23 PM](https://user-images.githubusercontent.com/86527202/182841954-2addbe8a-7934-41de-84c9-5c4029557ae9.png)

-------------------

### Mustafa (@mustafapc19)
- [ ] URL: with validation enabled, allowed formats in v1 were `www.google.com`, `https://www.google.com`, `google.com`; v2 allows only `http://www.google.com`
- [x] Invite more option displays an error. Invite a user; & then click on the `invite-more option` (tried on SQLite XCDB project) 
  
![Screenshot 2022-08-02 at 9 21 04 AM](https://user-images.githubusercontent.com/86527202/182288159-9a1411c7-efd2-49a3-b7a8-a2c756bc6c64.png)
  
- [x] Double click on JSON cell shows `[Object, object]`
  
![Screenshot 2022-08-04 at 1 35 49 PM](https://user-images.githubusercontent.com/86527202/182796819-f9007eda-f46b-4101-8991-36d94dcd163f.png)

- [x] Right click opens up both `date modal` and `right click` menu
  

![Screenshot 2022-08-04 at 2 30 31 PM](https://user-images.githubusercontent.com/86527202/182807752-2a3c65a0-7cf0-4511-b08a-e9cb4c98861d.png)
  
-----------------

### WingKWong (@wingkwong)
- [x] Duration column icon displays `number icon`
  
![Screenshot 2022-08-04 at 12 48 08 PM](https://user-images.githubusercontent.com/86527202/182787573-1a4df657-f69f-48cc-a606-df58645923b5.png)

## PG root DB

-----------------

# Leisure items (enhancements)
- [x] Quick option to close all tabs 
- [x] Font & size in `value` input, keep it same as `Operator` and `Field` input
- [x] Darken the filter block OR add a border OR darken the shadow. The modal is currently getting diluted in the spreadsheet.
  
![Screenshot 2022-08-02 at 9 51 35 AM](https://user-images.githubusercontent.com/86527202/182291235-92b5c3ea-0a3e-4346-b305-5a457d6bdccc.png)

**Comment by wingkwong** [comment]
for second point - it may due to the incorrect condition [here](https://github.com/nocodb/nocodb/commit/2520a8ed6c6c57a1bcc5bef99297a243b386ca38#diff-96636f472b0b80d4d1440df2a5e351740a4f8d1d86606b2911ca98c4b42d98f4R38)

**Comment by wingkwong** [comment]
my part is covered in this PR - https://github.com/nocodb/nocodb/pull/2885
