### ISSUE TITLE
Filter feature issue

### ISSUE THREAD

**Issue by BMS-Eiffel** [nocodb/nocodb#295]
I have a table w/ columns accepting null value.

A **nocodb filter** researching column w/ null value return 0 rows. (of course I have plenty of records normally matching the filter. Checked w/ Navicat)

**Comment by pranavxc** [comment]
Can you share more details? like database, metadatabase, etc...

You can copy those details from app as follows

![projectinfo mov](https://user-images.githubusercontent.com/61551451/122871370-85c22300-d34c-11eb-9bf4-62f1fe19b4e0.gif)

**Comment by pranavxc** [comment]
Is column value is `null` or an empty string, please share the response data(you can get it from network tab) if possble.

**Comment by pranavxc** [comment]
You have to use the `is null` option. 

![isnull mov](https://user-images.githubusercontent.com/61551451/122911165-a1d9ba80-d374-11eb-88f5-86c55f6720f2.gif)


`is not null` has some issue and will be fixed in the next release.

**Comment by BMS-Eiffel** [comment]
Sorry but is doesn't work on my table. (tested w/ Chrome & Safari)

Here is my project info:

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.9.35**

I have no issue when I do the select directly via Navicat (is not null).
Same via nocodb doesn't return the proper rows.

**Comment by BMS-Eiffel** [comment]
Why this ticket has been closed without any correction? comments?

Please advise

**Comment by o1lab** [comment]
@BMS-Eiffel : The fix is available in the latest docker. 

You would have to delete the existing container and image from docker dashboard. 

And then download new docker again.

Thank you,

**Comment by BMS-Eiffel** [comment]
Ok thanks

Is this new docker already available?

Thanks

**Comment by o1lab** [comment]
yes in 0.9.36 or latest
