### ISSUE TITLE
vue3: Formula Column

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#2955]

**Comment by dstala** [comment]
@wingkwong 

- [ ] we can explore if we can try and avoid overlap of modal's. in this case, i had many columns already in place & was trying to insert formula column @ end
  
![Screenshot 2022-08-08 at 7 18 13 PM](https://user-images.githubusercontent.com/86527202/183441758-3745c8e2-586b-4706-a6c6-0e18eacbfd1d.png)


- [ ] when composing formula, on selecting field from new right-side menu - formula column menu disappears. it should persist till formula editing is completed; formula tried `{RentalDuration}`
- [ ] formula `CONCAT({field1}, {field2)} :: trying to select these from right hand side menu, the open brace of CONCAT "(" is removed on selecting first field
- [ ] Edit formula menu didn't show previous stored formula

- [ ] formula `10+20.32` results in a string in v2; was a number in v1
  
![Screenshot 2022-08-08 at 7 56 09 PM](https://user-images.githubusercontent.com/86527202/183441446-3c44af4a-59bc-4c7d-afa7-7f037d9ada9b.png)

- [ ] Reference to another formula field is throwing error
  
![Screenshot 2022-08-08 at 7 53 37 PM](https://user-images.githubusercontent.com/86527202/183440770-db198390-a5ef-4d13-b78c-c24762f5a7b9.png)
