### ISSUE TITLE
vue3: LongText Cell

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#2958]

**Comment by dstala** [comment]
- [ ] Some cell's are not editable (observed with `Single Line Text` as well)
  
![Screenshot 2022-08-03 at 1 13 26 PM](https://user-images.githubusercontent.com/86527202/182552616-d6d0ed1f-c006-4127-aad4-feffc11c5204.png)

**Comment by wingkwong** [comment]
@dstala handled in https://github.com/nocodb/nocodb/commit/c4d1bab95e29818f72074653dbcc3d48071558fd
