### ISSUE TITLE
feature: add params in Automations referencing cell values

### ISSUE THREAD

**Issue by mahmouds12** [nocodb/nocodb#296]
![image](https://user-images.githubusercontent.com/15720804/123018072-302e5a80-d3ce-11eb-9b5d-9b468d916d36.png)

In Airtable Automations, we can use the cell values of the updated/created record to send email, whatsapp, or update another record.
Example:
An update happens to a user with email a@gmail.com, I want to send him an email. In nocodb Automations I can't send him in email because I can't reference his email address into Automations

**Comment by pranavxc** [comment]
Currently in the HTTP client, currently values are not accessible rest of the place following values are available.

* `user` - creent user object
* `data` - cell data

You can access it with handlebars template syntax. For example, if you want to access the `title` column value use `{{ data.title }}`. 

In the HTTP client, it will be available in the next release 👍 .
