### ISSUE TITLE
[Vue3] Deferred / Miscellaneous issues

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2962]
#### Grid / Spreadsheet
- [x] `on update` triggers webhook for `Single line text` gets triggered for every character input. In v1, it was once after the complete text was updated.

-------------------

#### Left Navigation Bar

- [x] API Docs (Pages not found - base url)

-------------------

#### Right Navigation Bar

- [x] link webhook drawer (covered in https://github.com/nocodb/nocodb/pull/3051)
- [x] Copy View Not implemented (covered in https://github.com/nocodb/nocodb/pull/3078)
- [x] Clicking Form View should rerender the view. See v1. (covered in https://github.com/nocodb/nocodb/pull/3078)

-------------------

#### Settings

-------------------

#### Tool Bar

- [x] More Action > Upload CSV (covering in https://github.com/nocodb/nocodb/pull/3051)
- [ ] Show password icon shrinks when password length is big for a shared view 
  
![Screenshot 2022-08-02 at 10 01 44 AM](https://user-images.githubusercontent.com/86527202/182292345-7cd2c9d9-7237-4513-87de-06ed5b48791e.png)

-------------------

#### Others
- [x] Airtable import: Log window doesn't scroll down automatically
- [x] Rating Select: antdv doesn't support object as value. need a workaround for it. 
   Covered in https://github.com/nocodb/nocodb/pull/3016
- [x] Checkbox Select: antdv doesn't support object as value. need a workaround for it. 
   Covered in https://github.com/nocodb/nocodb/pull/3016
- [x] formatting broken. e.g. 
  ```vue
            <a-button type="primary" size="small" :disabled="!!error || localValue === vModel"
              ><div class="text-xs" :onclick="onSave">Save</div></a-button
            >
  ```
- [x] refactor - remove icon import. Autoload introduced in [here](https://github.com/nocodb/nocodb/pull/3019). 
   Will be covered in https://github.com/nocodb/nocodb/pull/3044 (partially done now?)
- [x] refactor - ditch toast (@wingkwong)
- [x] Missing isUIAllowed (Covered in https://github.com/nocodb/nocodb/pull/3087)
- [x] Sync i18n files from v1 (do it in the last step)
- [x] lint issues
- [x] refactor - change `context` and `utils` imports to `#imports` (cell will be handled by @wingkwong)

#### changes introduced in v1

- [x] [Excel Import](https://github.com/nocodb/nocodb/pull/2851)

**Comment by bcakmakoglu** [comment]
> #### Grid / Spreadsheet
> 
>     * [ ]  `on update` triggers webhook for `Single line text` gets triggered for every character input. In v1, it was once after the complete text was updated.

* [useDebounceFn](https://vueuse.org/shared/useDebounceFn/#demo) can help here
