### ISSUE TITLE
vue3: Year Column

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#2967]

**Comment by dstala** [comment]
@mustafapc19 

- [ ] right click menu overlaps
![Screenshot 2022-08-08 at 8 21 29 PM](https://user-images.githubusercontent.com/86527202/183446919-8937d611-dcf2-412f-9f75-a5d55dd1f83e.png)

- [ ] records entered into cell are transient. not saved. lost on reload

Verified
- [x] Default configuration
- [x] Column creation
- [x] Clear cell
- [x] Rename column

**Comment by mustafapc19** [comment]
@dstala Seems like some recent changes has broke the updating logic 😅. `Time` cell updating is also broken.
