### ISSUE TITLE
Feature request - Change admin email & manually approve users

### ISSUE THREAD

**Issue by LordZeuss** [nocodb/nocodb#2973]
As of the moment, you cannot change the admin email that was used when creating NocoDB for the first time. I would like an ability to change that. Additionally an ability to approve users, or hide all tables unless approved.

As of now, anyone can view my spreadsheets. No, they cant view the contents, but they can see all of the tables. An ability to manually approve users, or specify which tables they can see (and have them all hidden by default) would be a great start.

Overall, great project!

**Comment by o1lab** [comment]
Pls see NC_ADMIN_EMAIL in [docs](https://docs.nocodb.com/getting-started/installation#environment-variables).

**Comment by include** [comment]
@o1lab I can setup two env variables and restart my container and it will magically update the admin email?

**Comment by include** [comment]
It works but I got many errors defining the new password with the mandatory policy. I am sorry but there should be some bug in the code. I was only able to define a new password with strictly the number of chars described in the message (Example: ```NC_ADMIN_PASSWORD="Abcdefgh0%"``` . If I try something like ```$$$AHHHHfailagaon007" if fails with the default message:
```
Invalid admin password
At least 8 letters. One Uppercase Letter. One Number.
```

Cheers,
F

**Comment by include** [comment]
humm looks like the password was ```"Abcdefgh0%"``` with the `"` . Is it normal/expected?

**Comment by o1lab** [comment]
Manually approving is not planned. Disable user signups. And for changing admin email - its possible with env variables as mentioned.
