### ISSUE TITLE
Feature: Rich editor for multiline text

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#298]
Hi,

Is there any plan to support text area with formatting options in future. For some use cases it would be useful to have it. 
Currently I integrated CK editor with nocodb. Apart from few css issues it was working well.
![text editor](https://user-images.githubusercontent.com/86340924/123048674-47943480-d41c-11eb-801c-3cba297d4c7c.JPG)

It would be helpful in case you can integrate some feature text editor with minimal configuration that could be customized by others as per needs. I tried editorjs, quill, draft, ck editor etc and ckeditor was fulfilling the requirement.

**Comment by o1lab** [comment]
We are exploring this aspect : idea was to support markdown as well.

**Comment by drdomark** [comment]
Yes Rich Text editor is the main requirement. I have tested that aspect as well. CkEditor can be configured to create normal line, html text and coloring also. I have gone through nocodb code base and by changing table-cell text rendering with <span v-else v-html="value"></span> markup text could be rendered as html also.

![image](https://user-images.githubusercontent.com/50301882/123052169-27ff0b00-d420-11eb-9a37-8e07a83a86a7.png)

**Comment by AztrexDX** [comment]
Yes, Rich Text Editor feature would be nice. I have tested that aspect as well. CkEditor can be configured to create normal line, html text and coloring also. Changing table-cell text rendering with v-html, markup text rendering was working good also.
![image](https://user-images.githubusercontent.com/86340924/123052334-567ce600-d420-11eb-9351-b68e3ef83025.png)

**Comment by pranavxc** [comment]
We can add `RichEditor` as a type.

**Comment by AztrexDX** [comment]
Ok. Thanks for Info. Can you tell about in case you have decided you are going to use some library or custom implementation for rich text editor.

**Comment by pranavxc** [comment]
> Ok. Thanks for Info. Can you tell about in case you have decided you are going to use some library or custom implementation for rich text editor.

We are not decided yet but you can suggest if you know something suitable 👍

**Comment by AztrexDX** [comment]
I have tried few rich text editor libraries 
1- Froala Editor and TinyMCE are paid so currently not using in open source projects
2- Ckeditor - plugins are paid but core feature and library is free. Allows highlighting, custom configuration etc. Image upload adapters can be written to upload image to server and get link. One free simple adapter is provided by them. API are accessible so it is very extensible. Provides wrapper for Vue.
3- Quilljs - Similar to ckeditor but maintains support for last two browser versions only. Opensource. Need to write custom image upload plugin.
4- Summernote - Opensource and provides many basic functionality. Need to write custom image upload plugin.

Have used ckeditor mostly as it looked native, can support old browsers and documentation was good. UI looks better but only customizable with bootstrap I think.

There is syncfusion rich text editor also open source but free only to open source projects, upto some revenue limit and upto 5 developers.

**Comment by kemistep** [comment]
need Rich text editor ,this is very userfule;

**Comment by pranavxc** [comment]
> I have tried few rich text editor libraries
> 1- Froala Editor and TinyMCE are paid so currently not using in open source projects
> 2- Ckeditor - plugins are paid but core feature and library is free. Allows highlighting, custom configuration etc. Image upload adapters can be written to upload image to server and get link. One free simple adapter is provided by them. API are accessible so it is very extensible. Provides wrapper for Vue.
> 3- Quilljs - Similar to ckeditor but maintains support for last two browser versions only. Opensource. Need to write custom image upload plugin.
> 4- Summernote - Opensource and provides many basic functionality. Need to write custom image upload plugin.
> 
> Have used ckeditor mostly as it looked native, can support old browsers and documentation was good. UI looks better but only customizable with bootstrap I think.
> 
> There is syncfusion rich text editor also open source but free only to open source projects, upto some revenue limit and upto 5 developers.


Thanks for sharing, we will try them and choose one which suited.

**Comment by v3ss0n** [comment]
I had tried multiple editors that listed before , they didn't integrated well in my expeirence.
Traditional editors are very heavy in resources and very complex. Rich Text editing is not suitable for project like this.
I recommend new generation markdown editors :
https://github.com/writewithocto/octo
it is inplace markdown editor and build for vue so could easily integrate.

**Comment by kemistep** [comment]
up this feature,very userful

**Comment by hosseinvand** [comment]
Please Add this feature. Notion supports this and it is the only feature I miss since migrated to nocodb.

**Comment by joekroese** [comment]
Hi @AztrexDX, can you outline how you integrated CKEditor with nocodb?

I would love to have a markdown editor in nocodb and until it's implemented, your approach looks like the best alternative!

**Comment by AztrexDX** [comment]
There is vue ckeditor wrapper. I created custom nocodb by including it and implementing it. It was for old version. Now nocodb uses new ui and implementation so it doesnt work now.

**Comment by Hernan-2017** [comment]
This would be really useful for me, I'm trying to migrate from SeaTable but not being able to use Rich Format text on LongText columns is making it hard, especially the lack of Code Blocks.

**Comment by cfab** [comment]
Hello, when can we expect this feature to be released ;-) ? Thank you.
