### ISSUE TITLE
vue3: Rollup column

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#2981]

**Comment by dstala** [comment]
@mustafapc19 

- [ ] Edit column for rollup wasn't supported in v1 (we were just allowing column name change in v1, but not rollup configuration). In v2, we have provisioned configuration change as well - it's good, but it doesn't work currently. Either we can revert it to be like v1 or fix it.
  
![Screenshot 2022-08-08 at 5 09 01 PM](https://user-images.githubusercontent.com/86527202/183410111-6fac65c4-4e68-48b3-8d0c-e02e281ec925.png)

- [ ] Not possible to edit only column name, without feeding existing configuration again
  
![Screenshot 2022-08-08 at 5 11 50 PM](https://user-images.githubusercontent.com/86527202/183410343-dc0d13da-a3b6-418c-9959-12153a4cbdb7.png)


Verified
- [x] Add rollup column
- [x] Rollup cell is not editable
- [x] Rollup cell clear not allowed
