### ISSUE TITLE
vue3: Lookup Column

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#2989]

**Comment by dstala** [comment]
Observations @mustafapc19 

- [ ] Not all options listed; v1 and v2 reference images posted below; also, increase display width. information is chopped off in v2
  
Expected:  
![Screenshot 2022-08-08 at 10 33 45 PM](https://user-images.githubusercontent.com/86527202/183473773-1aaef5f2-21b4-4d45-b821-cb3da32ba133.png)

Observed:  
![Screenshot 2022-08-08 at 10 35 45 PM](https://user-images.githubusercontent.com/86527202/183473897-eb3dee92-9da1-454a-a96b-cdbf764d9927.png)

- [ ] Lookup cell contents are not populated (Pranav?)
- [ ] Lookup icon needs update
  
![Screenshot 2022-08-08 at 10 39 43 PM](https://user-images.githubusercontent.com/86527202/183474618-64783ae0-2db2-427a-9f82-db43b60b835a.png)

- [ ] Edit: only column name change was allowed in v1;

**Comment by mustafapc19** [comment]
Lookup cell will be taken care by @pranavxc
