### ISSUE TITLE
vue3: Add LTAR Column

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#3001]

**Comment by dstala** [comment]
Observations @mustafapc19 

- [ ] On creating a new HM relation, BT column doesn't appear until hard-refresh (doesn't appear even on reload)
- [ ] Similar observations as above for MM relation
- [ ] `Add record` option (+) doesn't appear on BT cell
- [ ] v1 didn't allow configuration edit for LTAR. only column rename was allowed; also, its required to pre-populate existing configuration information
  
![Screenshot 2022-08-08 at 10 26 42 PM](https://user-images.githubusercontent.com/86527202/183472458-a8cf04aa-858b-475d-a6c4-3ca712ec3e5c.png)
