### ISSUE TITLE
🐛 Bug: Hours auto-increment when focusing on datetime cell, without doing any change

### ISSUE THREAD

**Issue by hugolmn** [nocodb/nocodb#3004]
Probably linked to #2754, #2339 and #2229 

**Project info**

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.92.4**

**Steps To Reproduce**

1. Create a datetime typed column
2. Insert a row with a value for this datetime column
3. Select the datetime cell as if you were to edit it
4. Click outside of date selector to go back to the table, or click on OK (pressing the escape key prevents this bug)
5. The datetime will increment by X hours even though no change was actually made

**Possible issue**
I suspect the time increase to be based on the timezone. I am located in UTC+2 and the datetime is incremented by 2 hours every single time I repeat the steps described.

**Expected Behavior**
A click on a datetime cell and going back to the table without changing anything should not alter the existing value.

**Screenshots**
Time is 18:41
<img width="98" alt="image" src="https://user-images.githubusercontent.com/39267118/182800863-d4cc5a64-1065-4391-a940-a8dcf200bad3.png">
Click on the cell
<img width="174" alt="image" src="https://user-images.githubusercontent.com/39267118/182800895-0b539938-3b71-43c7-bbb5-81305cd946ab.png">
Back to the table without changing anything: time is now 20:41
<img width="90" alt="image" src="https://user-images.githubusercontent.com/39267118/182800922-86185655-e992-4469-a90d-f65877a41ab2.png">

**Comment by bluemangotree** [comment]
Hi, any updates here?

**Comment by dstala** [comment]
Fixed in latest release. Please reopen if issue perisists
