### ISSUE TITLE
Checkbox as textbox in link expanded form

### ISSUE THREAD

**Issue by alprotasov** [nocodb/nocodb#3018]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.4**
```

**Precondition:**
1. Create two tables, both with checkbox fields
2. Create a field with LinkToAnotherRecord type in one table and connect to another table
3. Create a record in both tables and connect them with a field from step 2

**Steps To Reproduce**
1. Open record details
2. Open linked record

**AR**
Checkboxes are shown as text records
**Video**: https://records.cherishdev.com/conversations/a0f74fea-f183-548e-82ad-98667a4d64eb

**ER**
Checkboxes are shown like checkbox

**Comment by wingkwong** [comment]
We introduced a new UI since 0.96. Therefore now all checkboxes are shown in input box. You can see the checkbox button by hovering the input.
