### ISSUE TITLE
[Feature] Prefill form view input elements from the URL params

### ISSUE THREAD

**Issue by LucBerge** [nocodb/nocodb#3027]
## Recommending Features

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**

Lets assume I have a table with the fields `name` and `description` and a Form view. On the form share link:
- If in the url I add `&name="Lucas"`, the `name` input field is prefilled with `Lucas`.
- If in the url I add `&lock="name", "description"` the inputs `name` and `description` are locked and cannot be changed but are visible (grayed out).
- If in the url I add `&hide="name", "description"` the inputs `name` and `description` are not visible.

It must be possible to combine the parameters.

**Describe alternatives you've considered**
None but there might be an other way.

**Additional context**
It should work whatever the field type, even if it is a link to another table (by using the primary key or id)

**Comment by dstala** [comment]
Associated issue : https://github.com/nocodb/nocodb/issues/2862

**Comment by LucBerge** [comment]
Hello, any update ?

**Comment by sasch901** [comment]
Would be great!
