### ISSUE TITLE
vue3: API Snippet

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3031]

**Comment by dstala** [comment]
@mustafapc19 

- [ ] Right view pane IMO isn't required, as the snippet is small
- [ ] Tab headers, we can mark all caps as in v1 (OR) change following as `JavaScript`, `PHP`, `NocoDB-SDK`
  
  
![Screenshot 2022-08-11 at 12 05 41 PM](https://user-images.githubusercontent.com/86527202/184077194-4a308931-eeeb-494c-8169-ffc6d6621287.png)
  
- [ ] Sub-option-menu (next to clipboard copy) always show's AXIOS, even if AXIOS is not part of drop-down
- [ ] Sub-option-menu should not be displayed for `C`, `Java`, `Ruby`, `PHP`
