### ISSUE TITLE
[i18n] Message "Field is required" not translate

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#3041]
NocoDB used as docker : true
NocoDB version : 0.92.4
Database used in NC_DB URL : pg
Project was created by clicking : Import from Airtable
Database on which spreadsheet is created : pg
Database version : 14-3

**Steps To Reproduce**
 
1. Select French language (or other than English)
2. When  i submit a form with required field, i've got message "Field is required"

This message is hardcoded.

**Expected Behavior**

Translate this message ("Le champ est obligatoire" in French for example)

**Comment by dstala** [comment]
@syji35 we are now live on Crowdin (https://crowdin.com/project/nocodb)
You can propose your changes directly in the Crowdin portal; the rest of the process is automated!

quick guide [here](https://docs.nocodb.com/engineering/translation#how-to-add--edit-translations-)
