### ISSUE TITLE
[Vue3] Attachment cell drop option doesn't appear

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3062]
Base: https://github.com/nocodb/nocodb/commit/a01b7c912d38ecafa3b288b5c50f2db74c6b6416
Root DB: MySQL2

- Attachment: drop in cell option doesn't appear if I close & reopen tab
https://www.loom.com/share/53284f64d36c4970870bfd99ce1211f2

[Minor]
- Make scroll markers (grey rectangle to the right & bottom) appear only when needed, hide otherwise.

**Comment by bcakmakoglu** [comment]
Someone keeps overwriting a style change I pushed 3 times now that fixes the dropzone... would be really great if that would stop.

**Comment by bcakmakoglu** [comment]
@dstala Changes are in here
https://github.com/nocodb/nocodb/pull/3066
