### ISSUE TITLE
[Vue3] User management: Invite URL

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3069]
Accessing invite URL in v2 redirects to general sign-in / sign-up page

- Add new user, any role
- Copy generated URL, access in `incognito mode`
- Redirects to generic sign-up / sign-in [both fail; sign-up says user already exists; can't sign-in without credentials]

Sample URL
http://localhost:3000/#/user/authentication/signup/0c15b8b3-43c1-4f32-8923-f749e5cf657e

**Comment by bcakmakoglu** [comment]
What exactly is supposed to be different? 
The issue outlines what *is* happening and not what is *supposed* to happen. 
Can you instruct me on what the correct process is supposed to be here?

**Comment by o1lab** [comment]
The invited URL should show a sign up. And on successfully entering email and password - they should be able to see project list.

Please see v1 for reference.

**Comment by bcakmakoglu** [comment]
But isn't that what is happening right now? That's why I was confused.

**Comment by bcakmakoglu** [comment]
Ah well, I guess this is a completely new page unrelated to the current signin/signup pages.
Doesn't even exist in V2, yet 😄

**Comment by o1lab** [comment]
Yeah, was wondering the same - its an invited page. Will be similar to signup but with id etc

**Comment by bcakmakoglu** [comment]
I'll get on it 😄

**Comment by bcakmakoglu** [comment]
Relevant PR: https://github.com/nocodb/nocodb/pull/3109
