### ISSUE TITLE
[Vue3] Select field import

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3072]
Use 
- https://airtable.com/shrGpYEGA56xkfYME
- keyn1MR87qgyUsYg4

Refer to `Product` and `Discount band` below

v1 imports single select columns & colours appropriately
  
![Screenshot 2022-08-10 at 9 29 46 PM](https://user-images.githubusercontent.com/86527202/183958498-0dcad926-62ae-4945-b669-0e1653c6ba3e.png)

v2 import needs correction
  
![Screenshot 2022-08-10 at 9 29 35 PM](https://user-images.githubusercontent.com/86527202/183958486-cdb116b5-4ba9-45dc-8943-c273622a4e42.png)

**Comment by mertmit** [comment]
This is not related to import, this is a problem with mysql, mysql trims spaces after enum/set option. I will handle this case for mysql.
