### ISSUE TITLE
[Vue3] Right NavBar - View rename option accepts existing name

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3077]
Validation for view name present only during view creation; required during view rename as well
  
![Screenshot 2022-08-11 at 12 00 58 PM](https://user-images.githubusercontent.com/86527202/184076487-900aa3db-b88d-48c3-8ce6-a4e7e1b30065.png)

**Comment by bcakmakoglu** [comment]
@dstala relevant PR: https://github.com/nocodb/nocodb/pull/3094
