### ISSUE TITLE
Editor group can't attach files while creating a new row

### ISSUE THREAD

**Issue by FrancyMak** [nocodb/nocodb#308]
Node: v10.19.0 Arch: x64 Platform: linux Docker: false Database: mysql2 ProjectOnRootDB: false RootDB: sqlite3 PackageVersion: 1.0.0

**Steps To Reproduce**
1. Login as an editor use
2. Try to attach a file
3. See "not allowed"

**Expected behavior**
A not allowed error

**Comment by pranavxc** [comment]
Fixed in latest version `0.9.38`

**Comment by FrancyMak** [comment]
Still not working. I did git-clone

Inviato da iPhone

**Comment by pranavxc** [comment]
@FrancyMak try the latest docker `0.9.40`
