### ISSUE TITLE
vue3 : Change password error message 

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3084]
<img width="1009" alt="Screenshot 2022-08-11 at 12 32 00" src="https://user-images.githubusercontent.com/5435402/184124345-fd949f75-009d-4441-a332-2d163c262660.png">

Probably something wrong with i18n in this page. 

They key used seems to be right. However instead of the value - key is displayed.

**Comment by bcakmakoglu** [comment]
@o1lab Strange - can you check out the latest develop and try again?

I'm getting the proper error message 😕 

<img width="687" alt="image" src="https://user-images.githubusercontent.com/78412429/184137259-2c7c525f-b8ea-4442-bd17-b65d4eef3dbe.png">

**Comment by o1lab** [comment]
Yes, seems good now! Will keep an eye.

**Comment by dstala** [comment]
I had pushed a change, forgot to link it with this issue :)
