### ISSUE TITLE
vue3 : Entering wrong password while changing password signs you out

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3085]
- Go to change password
- Enter the wrong current password
- Enter new password 

Click on change password button - this will sign out.

**Comment by bcakmakoglu** [comment]
I can't reproduce this issue either:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/78412429/184137809-b93f4b31-ecd7-4996-aeb4-e0e450f8e1dd.png">

Are you sure that your token didn't accidently expire the moment you tried to update the password? I believe there is still some issue with refreshing tokens (if I remember it was due CORS issues but I can't remember correctly anymore @pranavxc maybe you know why the token refresh ends in 400 error?)

**Comment by o1lab** [comment]
Looks fine now - weird 😅 

Looks like there was some issue with merge or it had to rebuilt once I had pulled. Marking fixed.
