### ISSUE TITLE
Condition based automation doesn't work

### ISSUE THREAD

**Issue by pedroreactive** [nocodb/nocodb#309]
Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.9.37**

Steps To Reproduce
1. Go to 'Automations'
2. Click on 'Add new'
3. Enter webhook details and select On condition
4. Click on 'Add filter'
5. Select 'id' as field 'as equal' as operation and enter last id + 1 (for example, if the last row id is 30 enter 31)
6. Click 'Save' and close automation popup
7. Add new row or send API POST request to add new row

**Expected behavior**
Webhook must be send if the row id is equal as in condition, but it never comes. Only webhooks without condition is working.

**Comment by pranavxc** [comment]
Fixed in latest version `0.9.38`
