### ISSUE TITLE
[Vue3] DateTime column width is too wide

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3103]
![Screenshot 2022-08-11 at 10 19 44 PM](https://user-images.githubusercontent.com/86527202/184189751-efd97fc6-4c41-46c1-939d-ff84e60cd0db.png)

**Comment by dstala** [comment]
Also, 
- the column template from the previous selection persists: like create rating column, and when we try to create a new column, the default display isn't single select
- width of `dateTime` `JSON` not natural (too wide)

**Comment by dstala** [comment]
![Screenshot 2022-08-17 at 5 24 36 PM](https://user-images.githubusercontent.com/86527202/185112308-0a7ac16e-3364-4082-bff5-abcba099cdf6.png)

**Comment by wingkwong** [comment]
@dstala How to trigger it?

![image](https://user-images.githubusercontent.com/35857179/185292504-97e2294d-4253-4713-b19c-221182219f71.png)

![image](https://user-images.githubusercontent.com/35857179/185292547-4d449f8c-5a8a-4bd6-81e6-a4ee2aae11d4.png)

**Comment by dstala** [comment]
> @dstala How to trigger it?
> 
> ![image](https://user-images.githubusercontent.com/35857179/185292504-97e2294d-4253-4713-b19c-221182219f71.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/185292547-4d449f8c-5a8a-4bd6-81e6-a4ee2aae11d4.png)

Ah, strange! Nothing specific. Will let you know if I can reproduce.
