### ISSUE TITLE
Bug : Https scheme missing in swagger 

### ISSUE THREAD

**Issue by pranavxc** [nocodb/nocodb#311]
If the app is hosted with SSL scheme should be `https` in swagger but it only shows `http` scheme.

**Comment by oudcheikh** [comment]
Hello any update about this issue ?

**Comment by pranavxc** [comment]
Updated in v0.9.39

**Comment by pranavxc** [comment]
Or it will work by setting `NC_PUBLIC_URL`

**Comment by oudcheikh** [comment]
fine it work new
