### ISSUE TITLE
[Vue3]: Update Users list in Auth tab after sending Invitation

### ISSUE THREAD

**Issue by bcakmakoglu** [nocodb/nocodb#3116]
##

* User list is not updated after sending an invitation to a users email address
	* List should be updated after invitation is sent out / invitation link is generated

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/78412429/184341835-534c0a7f-68c8-4829-a1b0-7466051d0818.png">

**Comment by o1lab** [comment]
Did notice yesterday. Missed to raise. @mustafapc19 to look this up.
