### ISSUE TITLE
json type column

### ISSUE THREAD

**Issue by benitogf** [nocodb/nocodb#312]
any plans on supporting json column display?

![image](https://user-images.githubusercontent.com/1633813/123922449-09d06800-d956-11eb-8de1-02e2b6011e1f.png)

great project!! 🥇 🥇

**Comment by pranavxc** [comment]
Currently, in `mysql` you can choose type as `specificType` and data type as `json` it will show a json editor.

 In future, we will add a `JSON` column as well 👍

**Comment by pranavxc** [comment]
JSON type is added in `0.11.6`.
