### ISSUE TITLE
[Vue3] User management - allow comma separated list of users to be added together

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3122]
V1 accepted CSV to add multiple users in one go
  
![Screenshot 2022-08-12 at 8 07 33 PM](https://user-images.githubusercontent.com/86527202/184378345-d8089395-8e9c-4ffa-a32b-f06c40f395b9.png)

**Comment by o1lab** [comment]
csv ? I dont think so. Comma separated works - had tried it.

**Comment by dstala** [comment]
CSV- I meant comma-separated values. Not like a CSV file :)
Sorry, wasn't clear in description

**Comment by o1lab** [comment]
since the input in example is an invalid email - it is showing warning. This is right behaviour.

**Comment by dstala** [comment]
This feature. We don't want to support anymore? Was convenient actually.
  
![Screenshot 2022-08-13 at 8 33 48 AM](https://user-images.githubusercontent.com/86527202/184466071-4747f2fa-8800-447b-b905-622086a01f13.png)

**Comment by wingkwong** [comment]
We split the input by `,` and validate each email individually. I think the problem in v2 here is that it treats the second email (which is empty) as an invalid email. Just an edge case to fix. CSV feature is kept.
