### ISSUE TITLE
[Vue3] Webhook Pending Items

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3127]
- [x] Discord / Slack / Teams / Mattermost configured channels are not listed (dropdown, v1 sample below)
  
![Screenshot 2022-08-13 at 12 58 47 PM](https://user-images.githubusercontent.com/86527202/184473872-eef7aded-5250-4199-a677-bc838fe8367b.png)

- [x] Webhook Conditional filters

- [x] Resize Header options dropdown
  
v1
![Screenshot 2022-08-13 at 12 42 11 PM](https://user-images.githubusercontent.com/86527202/184473313-cf6c365f-a674-4dd4-ab97-0a2c658acc0c.png)
  
v2
![Screenshot 2022-08-13 at 12 43 36 PM](https://user-images.githubusercontent.com/86527202/184473332-e8afef28-8643-4855-94f9-dda7b35aae5a.png)

- [x] `We are hiring` overlap
  
![Screenshot 2022-08-13 at 12 38 25 PM](https://user-images.githubusercontent.com/86527202/184473150-466ab578-060b-4d47-9499-609be2a48d43.png)
  
- [x] Sample payload
  
![Screenshot 2022-08-13 at 12 51 23 PM](https://user-images.githubusercontent.com/86527202/184473602-3ee58a02-5295-444c-b635-7cbe43d643ca.png)

**Comment by wingkwong** [comment]
@dstala 

>  Discord / Slack / Teams / Mattermost configured channels are not listed (dropdown, v1 sample below)

how did you input the channel and render it as dropdown in v1?

**Comment by dstala** [comment]
You will have to `install` application in app-store
https://docs.nocodb.com/developer-resources/webhooks#2-install-plugin
