### ISSUE TITLE
[Vue3] Roles follow-up

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3137]
`Editor`
- Unable to edit Year, Time, Date, DateTime (Dropdown picker cells)
- Attachment, drop-down option wasn't available for cells
- `Read Only` prefix for attachment expanded row.
  
![Uploading Screenshot 2022-08-13 at 7.54.34 PM.png…]()

`Commenter` / `Viewer`
- Dropdown picker's are active, needs to be disabled
- Attachment cell, here it's active. Could see the drop-file button on the cell
- Expand attachment cell, didn't have any read-only suffix observed in `Editor`
- Sort/Filter didn't work

**Comment by wingkwong** [comment]
@dstala your screenshot is not available.

![image](https://user-images.githubusercontent.com/35857179/184573340-80591b5f-b458-4064-9b37-3ea9677d5ca6.png)
