### ISSUE TITLE
[Vue3] JSON Cell marked editable by default

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3138]
![Screenshot 2022-08-13 at 11 04 58 PM](https://user-images.githubusercontent.com/86527202/184504793-011621e9-9a31-4eb5-9226-fcbeaf166560.png)

**Comment by mustafapc19** [comment]
@dstala Is this issue still happening. I am on master and seems to be fine
<img width="507" alt="image" src="https://user-images.githubusercontent.com/35809690/184870891-019df4c4-0583-47a5-94af-4e80c0896d8e.png">

**Comment by dstala** [comment]
not observed anymore
