### ISSUE TITLE
No Headers/Auth section

### ISSUE THREAD

**Issue by janrito** [nocodb/nocodb#314]
**Please enter the following details**

Copy and paste project info : [Youtube Video](https://www.youtube.com/watch?v=AUSNN-RCwhE)

or 

please provide the following details :
NocoDB used as docker : true
NocoDB version : master
Database used in NC_DB URL: sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created :  sqlite3
OS on which NocoDB is running : ubuntu trusty on docker for mac big sure
Node.js version if running as node : 
Database version : 

**Steps To Reproduce**
1. Go to Automations on a given table 
2. Notifications and set to URL
3. Set a URL
4. set some parameters
5. click on Headers / Auth

**Expected behaviour**
UI to edit the headers or authentication should appear

**Screenshots**

<img width="423" alt="Screenshot 2021-06-30 at 14 23 17" src="https://user-images.githubusercontent.com/31504/123967983-bc341980-d9ae-11eb-8504-c468d20e1595.png">

**ERROR **
```js
TypeError: can't convert undefined to object
    NuxtJS 79
        headerListAutoWithEnv
        get
        evaluate
        In
        fn
        je
        fn
        r
        genWrapper
        render
        _render
        r
        get
        En
        mount
        $mount
        init
        v
        v
        _
        v
        Co
        _update
        r
        get
        En
        mount
        $mount
        init
        v
        v
        _
        v
        Co
        _update
        r
        get
        run
        Sn
        le
        se
        promise callback*re
        le
        update
        update
        notify
        set
        set
        updateItem
        updateItemsState
        le
        se
        promise callback*re
        le
        $nextTick
        updateItemsState
        run
        Sn
        le
        se
        promise callback*re
        le
        update
        update
        notify
        set
        set
        set
        updateSingle
        updateInternalValue
        onClick
        register
        te
        $emit
        toggle
        click
        te
        n
        _wrapper
021e3d9.js:2:12066
    NuxtJS 72
```

Join our discord : https://discord.gg/5RgZmkW for realtime help.

Node version : **v12.22.1**
Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
packageVersion: **0.9.27**

**Comment by pranavxc** [comment]
fixed in `v0.9.40`
