### ISSUE TITLE
graphql: Can't reload view data

### ISSUE THREAD

**Issue by bbigras** [nocodb/nocodb#315]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.9.40**

**Steps To Reproduce**
1. set up project using postgresql with graphql
2. hit "reload view data"

```
XHRPOSThttp://10.1.10.24:30008//nc/repertoire_mpl6/v1/graphql
[HTTP/1.1 404 Not Found 28ms]
```

Note the double `//`

**Expected behavior**

**Screenshots**

**Comment by pranavxc** [comment]
Fixed in `v0.9.41`
