### ISSUE TITLE
[Feature] Gallery Share View button missing

### ISSUE THREAD

**Issue by michacassola** [nocodb/nocodb#3152]
I don't know if this is a bug or a feature request, but a Share View button in a Gallery View would be appreciated!

**Need for this feature**
Being able to share a Gallery View as a link has many use cases.

**Is your feature request related to a problem? Please describe.**
In the Gallery View there is no Share View functionality.

**Comment by wingkwong** [comment]
duplicate. https://github.com/nocodb/nocodb/issues/3986. 

will be available in the next release.
