### ISSUE TITLE
vue3 : Keep the right nav drawer closed by default

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3154]
- [x] Let's keep the right nav drawer closed by default - so there is more space for spreadsheet
- [x] And once toggled, the toggled state has to be saved in browser. Currently, if you open a new table - the toggled state goes back to default.

**Comment by bcakmakoglu** [comment]
Why would the toggled have to be saved?
Never seen any other page save my sidebar of collapsed/open, which imo is strange UX.
