### ISSUE TITLE
vue3 : sidebar collapse improvements

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#3173]
- [ ] Project title should be always visible, even in collapsed mode, also this way we can keep the logo / back button and in this case we can remove project title from dropdown
- [ ] Project dropdown should be fixed to left
- [ ] Long project titles break both dropdown and header

![image](https://user-images.githubusercontent.com/59797957/184826799-bea0f0a8-19d9-43dd-8ede-f636504399ab.png)

**Comment by bcakmakoglu** [comment]
With the redesign this issue is obsolete - I'll close it for now.
