### ISSUE TITLE
Show cover image in gallery view also if fields is not enabled [Feature] 

### ISSUE THREAD

**Issue by ashgard071** [nocodb/nocodb#3199]
The gallery view has the option to show a cover image. In order to show the cover image, the field that contains the image must be enabled. When the image field and cover image are enabled, the gallery card shows both a cover image and the image of the field. The preview of the field is not necessary, as the cover already shows the image. When the image field is disabled, the cover image is not shown. I would expect that the cover image would be shown even if the image field is disabled. Please see attached file.
![no-cover-image](https://user-images.githubusercontent.com/72252838/185046539-9277638f-ecde-437d-b40d-c5770c74a17f.png)
![with-cover-image](https://user-images.githubusercontent.com/72252838/185046540-51b82ff4-f9d1-48c0-bf57-d7602302f780.png)

**Comment by tuxjz** [comment]
I would say, this is not feature request, but bug fix request. You don't need picture twice when you want them in Cover...

**Comment by john-bednar** [comment]
Change the the type to issue / it is not a feature, it is a bug. I found it now and wanted to report it.

**Comment by o1lab** [comment]
Fixed in latest UI rewrite.
