### ISSUE TITLE
[vue3] Lookup shows empty cell

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3200]
<img width="977" alt="Screenshot 2022-08-17 at 12 52 33 PM" src="https://user-images.githubusercontent.com/86527202/185059082-2ff0d74e-757e-4628-a67c-7b6fd0697e02.png">

**Comment by dstala** [comment]
@mertmit observation is same for rollup as well
  
![Screenshot 2022-08-17 at 3 54 00 PM](https://user-images.githubusercontent.com/86527202/185096346-45a77a44-4005-4c70-93c7-a438fc25ad1d.png)

**Comment by mertmit** [comment]
imports are mismatching on VirtualCell.vue but reverting them also cause an issue I will be working on that issue (circular reference)
