### ISSUE TITLE
[Vue3] Get API Snippet button missing

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3205]
- `Get API Snippet` in Right NavBar expanded mode
Console error
  
![Screenshot 2022-08-17 at 4 30 03 PM](https://user-images.githubusercontent.com/86527202/185102962-c69a8504-c1f3-4a0b-882c-f0e719b27e1e.png)

- `Webhooks` and `Get API Snippet` in compact sidebar mode
No action

**Comment by mustafapc19** [comment]
@dstala Api snippet is on hold for now. npm package issues.

**Comment by bcakmakoglu** [comment]
@dstala Yeah, as I mentioned on Monday, due to some package issues we had to disable `httpsnippet` for now, thus the API Snippet component doesn't work as expected.
We should open an issue for that so it can be tracked separately as it's not really a UI issue as this issue suggests 😄

**Comment by dstala** [comment]
Duplicate https://github.com/nocodb/nocodb/issues/3031
