### ISSUE TITLE
[Vue3] Webhook card: Fix `we are hiring` always to the bottom

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3206]
Now it floats along with rest of the list. Ignore if its intended this way by design
  
![Screenshot 2022-08-17 at 4 34 10 PM](https://user-images.githubusercontent.com/86527202/185103466-ec569462-c438-4c5a-bec3-8f4148fc111c.png)

**Comment by o1lab** [comment]
This is minor thing - we can look at it later.
