### ISSUE TITLE
[Vue3] Test webhook when condition enabled

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3207]
For `URL` not configured scenario, 
 - `Test Webhook` succeeds if a `condition` is enabled. 
 - Error displayed if no conditions configured
  
![Screenshot 2022-08-17 at 4 46 37 PM](https://user-images.githubusercontent.com/86527202/185106021-7f7dbdcf-ba43-4e4a-be56-7ddb286be437.png)
![Screenshot 2022-08-17 at 4 46 52 PM](https://user-images.githubusercontent.com/86527202/185106029-ee46ad5d-2bd3-4f3c-bc82-99b500945954.png)

**Comment by wingkwong** [comment]
Couldn't reproduce. Mind to double check again?

![image](https://user-images.githubusercontent.com/35857179/185287772-187a7d62-c512-4266-af00-019efa7eaac2.png)

**Comment by dstala** [comment]
couldn't reproduce either
