### ISSUE TITLE
[Vue3]: Re-open last open table when selecting project

### ISSUE THREAD

**Issue by bcakmakoglu** [nocodb/nocodb#3230]
## 

* When user selects a project, try to navigate to last opened table
	* If no tables exist, navigate to intro page ("Welcome to NocoDB")
	* If no table was open during last visit, navigate to intro page
	* If a table was open during last visit and we can find it saved in localStorage, re-open the table

**Comment by bcakmakoglu** [comment]
@dstala @o1lab Suggestions? Should another page be opened by default?
This was an idea that @mustafapc19 suggested and I like it, we re-open the last table that was open during a users visit.

**Comment by o1lab** [comment]
Yes, defnitely a good idea. However, we can pick this up after the release.

Probably we will have to save teh state in db per user 😅

**Comment by bcakmakoglu** [comment]
We could just save it into localStorage instead of persisting it in the DB.
I don't think it's too dramatic that it could be removed by a user just clearing their storage 😄 

But yeah, we can move this to later on but keep the issue open so we don't forget.

**Comment by dstala** [comment]
Closing, as we do not support tabs anymore. And click on project tile will redirect to project dashboard.
