### ISSUE TITLE
Attachment download blocked

### ISSUE THREAD

**Issue by whyteserious** [nocodb/nocodb#3239]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.92.4**

**Steps To Reproduce**

1. Nginx configuration HTTPS
    server_name  nocodb.internal.com;
    listen       443   ssl;
    ssl_certificate      /etc/nginx/***/internal.crt;
    ssl_certificate_key  /etc/nginx/***/internal..key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers *******;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

2. Can be accessed through https://nocodb.internal.com
3. doc attachment download blocked，pdf will create a new webpage
    but they are all http

**Expected Behavior**

if it's a bug fix it
or not a bug
how to set

**Comment by wingkwong** [comment]
Do you mean when you click download, it pops up an empty page only? If possible, please record a video for demonstration.

**Comment by whyteserious** [comment]
Browse address: https://nocodb.internal.com/
word address: http://nocodb.internal.com/download/noco/project/table/column/xxxx.docx
pdf address: http://nocodb.internal.com/download/noco/project/table/column/xxxx.pdf

so downloading is considered unsafe by the browser
For many users, the browser function may not be set
Is there any other solution

**Comment by wingkwong** [comment]
Did you click the download button to download? or you just browsed the link?

![image](https://user-images.githubusercontent.com/35857179/185590433-8cbcb193-3f81-4300-9595-7db214f3d966.png)

**Comment by whyteserious** [comment]
click the download button to download

**Comment by whyteserious** [comment]
Google Chrome Version 105.0.5195.53 (Official Build) (64-bit)
I use HTTPS to access, and downloads of unsafe content are rejected by default
It's impossible for everyone to set it
![image](https://user-images.githubusercontent.com/42569476/187629559-dd06800c-1948-413a-b80c-4b38561ea07f.png)

Why is the download link HTTP instead of HTTPS
Browse address: https://nocodb.internal.com/
word download address: http://nocodb.internal.com/download/noco/project/table/column/xxxx.docx
pdf download address: http://nocodb.internal.com/download/noco/project/table/column/xxxx.pdf

**Comment by jpbourgeon** [comment]
Hello
Since the latest update, I face this problem from the signin screen. When I try to sign in I receive an network error since the api url asked is served over http and not https

My nocodb is behind an nginx proxy. I didn't find a way to config nocodb to my needs.

Could you help me ?

**Comment by Xinil** [comment]
Experiencing this issue as well, running Noco behind a reverse proxy and images/attachments do not load. JS console says:

`Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR`

**Comment by Xinil** [comment]
I see this is flagged asking for more info.

When utilizing Nocodb behind a revese proxy, and you try to view any attachments, the UI is attempting to load a non-proxied version of the URL. For example, I have NocoDB running at https://nocodb.myhouse.com. When I bring up any table with images in it, all attachment loads fail and attempts to load the localhost instead, for example:

`https://192.168.10.52:8088/download/noco/SaltwareTank/frag%20photos/photo/2lxjSJ.jpg` 

It _should_ be attempting to load: `https://nocodb.myhouse.com/download/noco/Saltwater%20Tank%20Frags/frag%20photos/photo/2lxjSJ.jpg`

**Comment by rsmiles** [comment]
Hello, this looks a lot like an issue that I have been having while trying to host a nocodb instance. Using apache as a reverse proxy for ssl, attachments are loaded directly through plain http requests made directly to the port that nocodb is running on (8080 in my case). If the firewall blocks off port 8080 from the outside, then attachments won't load. I've tried using firewall port forwarding, combined with apache redirects to try to force attachment loading through ssl, but it has not worked so far.

**Comment by pranavxc** [comment]
@Xinil @rsmiles : Please set `NC_PUBLIC_URL` environment variable to resolve the issue. For example, @Xinil in your case set `NC_PUBLIC_URL=https://nocodb.myhouse.com`.

**Comment by rsmiles** [comment]
@Xinil I already thanked Pranav in discord for the help, but I wanted to mention here for anyone looking at this in the future that setting the NC_PUBLIC_URL variable did fix the issue for me. Thank you for your assistance.
