### ISSUE TITLE
vue3: m2m tables listed by default

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3248]
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.92.4**

- create 2 tables, add ltar-mm column
- hard refresh / re-open project

![Screenshot 2022-08-19 at 4 48 43 PM](https://user-images.githubusercontent.com/86527202/185607495-6ad5f9d2-7bd2-41ff-8326-3e46b2c4f2ca.png)

**Comment by o1lab** [comment]
@wingkwong : we need that checkbox within metadata management too

**Comment by wingkwong** [comment]
Checkbox should be there. Lemme check the default value

**Comment by dstala** [comment]
checkbox, we have under `project metadata` `misc`
toggling it didn't change behaviour.
