### ISSUE TITLE
TypeError: snippet.value.convert is not a function

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#3259]
Step to reproduce:

- click `Get API Snippet`

![image](https://user-images.githubusercontent.com/35857179/185729420-1766adc6-b1b7-42bb-bb3c-6d30055e3a99.png)

**Comment by mustafapc19** [comment]
@wingkwong This [issue](https://github.com/nocodb/nocodb/issues/3031) is currently on hold due to package issues.

**Comment by bcakmakoglu** [comment]
There's already an open issue for this: #3205

**Comment by wingkwong** [comment]
Closing as it's duplicate.
