### ISSUE TITLE
Can not edit SingleSelect/MultiSelect type of Column to Add option to the option list

### ISSUE THREAD

**Issue by cn-robert** [nocodb/nocodb#326]
**Please enter the following details**

Copy and paste project info : [Youtube Video](https://www.youtube.com/watch?v=AUSNN-RCwhE)

or 

please provide the following details :
NocoDB used as docker : false
NocoDB version : 1.0.0
Database used in NC_DB URL  : mssql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mssql
OS on which NocoDB is running : windows server 2016 standard (1607)
Node.js version if running as node : node-v14.17.2-x64
Database version : mssql server 2012 enterprise edition sp3 x64

**Steps To Reproduce**
1. Go to existed SingleSelect type column ''
2. Click on 'edit' -> click on '+ Add option' -> fill in an option -> click on 'Save'
3. See error

**Expected behavior**
1. Can Add or Remove options in existing SingleSelect/MultiSelect Column
2. Can Set default value

**Screenshots**
![image](https://user-images.githubusercontent.com/86990878/124535919-8e851f80-de49-11eb-942b-5ee0f9669380.png)
![option_err](https://user-images.githubusercontent.com/86990878/124536165-110ddf00-de4a-11eb-9831-6c3989a69b7c.png)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

Node version : **v14.17.2**
Arch type: **x64**
Platform: **windows server**
Docker: **false**
Database: **mssql**
packageVersion: **1.0.0**

**Comment by doodlemania2** [comment]
Is this specific to mssql driver?

**Comment by o1lab** [comment]
Yes, it looks like.

**Comment by pranavxc** [comment]
Fixed in `0.84.2`
