### ISSUE TITLE
i18n translation question 

### ISSUE THREAD

**Issue by cloudtrends** [nocodb/nocodb#328]
hi all, 

I am using nocodb for several weeks , and want introduce nocodb to many user ( not english speaker ) .

I found the i18n plugins file  ( ..\nocodb\packages\nc-gui\plugins\i18n.js ) , in this file  connect the lang files 

```
// Associate each locale to a content file
    messages: {
      en: require("~/static/lang/en.json"),
      zh: require("~/static/lang/zh.json"),
      ja: require("~/static/lang/ja.json"),
      fr: require("~/static/lang/fr.json")
    }
```

But I could not find the  en.json / zh.json / ja.json / fr.json files  .

could some one told me where those file located? 

thanks in advance .

**Comment by o1lab** [comment]
Tracked in #236
