### ISSUE TITLE
[vue3] grid view share UI corrections

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3282]
![Screenshot 2022-08-22 at 2 11 37 PM](https://user-images.githubusercontent.com/86527202/185878605-3d14f3c1-2e4c-40eb-a690-4ed49740d4f2.png)

- disable `add new row` button
- first column (index row) is empty
- `views` button for right nav bar is redundant; should be hidden
- decrease footer padding (around pagination)

**Comment by o1lab** [comment]
+ Table name in navbar needs to be in white

**Comment by mustafapc19** [comment]
@o1lab The table name style issue has been fixed with this [PR](https://github.com/nocodb/nocodb/pull/3276)
