### ISSUE TITLE
Heroku deployed standard setup - can't delete tables, relation fields failing 

### ISSUE THREAD

**Issue by yellowsnowagency** [nocodb/nocodb#329]
**Please enter the following details**

Copy and paste project info : [Youtube Video](https://www.youtube.com/watch?v=AUSNN-RCwhE)

or 

please provide the following details :
Heroku one-click deploy - version yesterday / today

**Steps To Reproduce**
create table - delete table 

<img width="450" alt="Screen Shot 2021-07-06 at 23 54 38" src="https://user-images.githubusercontent.com/86959832/124659034-8f539b00-deb5-11eb-8bcc-a0e395614925.png">

we thought using the standard deploy should run error free. Do we have to change anything or is there just a bug

thank you

**Comment by amitjainis** [comment]
Hi have shared a screenshot of the same. It throws an error. Missed your email earlier.

**Comment by pranavcbalan** [comment]
Can anyone share logs from Heroku or responses from the browser network tab?

Hopefully this issue may be fixed in the latest release - we'd fixed some knex connection-pool related bugs.

**Comment by o1lab** [comment]
Heroku was limiting number of connections to database in free tier.

Please try latest build.
