### ISSUE TITLE
Feature : REST and GraphQL as data sources

### ISSUE THREAD

**Issue by greddyatpt** [nocodb/nocodb#3293]
Web client applications rarely have direct access to databases.  They use APIs to get/add/update/delete data.  Wondering if this is supported in nocodb.  If yes, appreciate a pointer.  If not, please consider supporting it.

**Need for this feature**
We'd like our apps to  get/add/update/delete data hosted by SaaS providers.  We don't even know what kind of database they use.

**Describe the solution you'd like**
HTTP verbs could represent the CRUD operations on the data behind RESTful APIs.  Provide a mechanism to specify the API URLs and payload formats.

**Comment by o1lab** [comment]
Converting SaaS into a spreadsheet will have some challenges. However, we can do consider them - please help list the SaaS providers you have in mind

**Comment by greddyatpt** [comment]
NocoDB can import data from JSON files.  This feature request is about getting that JSON data through REST APIs with/without GraphQL in the middle.

**Comment by o1lab** [comment]
Covered [here](https://github.com/nocodb/nocodb/issues/2052).
