### ISSUE TITLE
vue3: form view attachment cell drag drop doesn't work

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3297]
- create form view with attachment field
- share view
- open share view link
- drag-drop doesn't work for attachment field (file opens in browser instead if I drag drop).

**Comment by bcakmakoglu** [comment]
Why would the shared view provide the ability to drop files?

No other Cell seems editable in a Shared View, though I noticed that the attachments aren't shown at all.
That, I can fix.

**Comment by dstala** [comment]
@bcakmakoglu 
Shared form view it was. Shared grid view will be read-only.

**Comment by bcakmakoglu** [comment]
@dstala In the current develop, the Form View doesn't work at all for me. I can't drop cells into the form to test them out in the Shared View.

@wingkwong Can you confirm this, or is this just an issue on my side? 😅

**Comment by wingkwong** [comment]
I followed Raju's steps and able to reproduce the issue.

**Comment by dstala** [comment]
@bcakmakoglu - I could see an issue with form view field handling if we add a new field after the form is created. It was fixed earlier by @wingkwong, but has re-appeared. For your tests, you can create form view after adding required columns in grid view.
