### ISSUE TITLE
Bug: Failed to select UUID with SpecificDBType

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#332]
**Please enter the following details**

**Steps To Reproduce**
1. Add a new column
2. Select ``SpecficDBType`` in Column Type
3. Select ``uuid`` in Type in Database
4. It will switch to ``SingleLineText`` in Column Type and empty in Type in Database

**Expected behavior**
It should use ``uuid`` instead of ``SingleLineText``

**Screenshots**

![image](https://user-images.githubusercontent.com/35857179/124760192-11e66400-df63-11eb-8e0a-bc8e9079a6b0.png)

![image](https://user-images.githubusercontent.com/35857179/124760223-1b6fcc00-df63-11eb-9539-3cc44bf2aee8.png)

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.9.42**

**Comment by pranavxc** [comment]
Fixed in `0.10.2`
