### ISSUE TITLE
vue3 : Use right side drawer for SharedView list and add new row

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3332]
Clicking below should result in opening of a right side drawer instead of modals
- [ ] SharedView List from view menu within the grid (this will be similar to webhook list) - View Link can be made as a link
- [x] Add new row (i.e `+` button on grid bar)

**Comment by mustafapc19** [comment]
@o1lab I was doing some basic drawer implementation for shared view list and I dont think it will be a good idea. Main issue is the password. Integrating the password will make the drawer a little clunky as I was going with a card design, plus also adding pagination to a drawer also doesnt seem like a good idea.
<img width="483" alt="image" src="https://user-images.githubusercontent.com/35809690/186598870-62ceecca-f7c3-43ff-896d-0e39fcd96002.png">

Shared view list Drawer:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/35809690/186599114-37399872-6ad1-4c37-b93c-c90c99880eda.png">
