### ISSUE TITLE
Feature: Add MailerSend to the app store

### ISSUE THREAD

**Issue by Agathe-Brusset** [nocodb/nocodb#334]
Hello to the NocoDB team!
I'm Agathe Brusset, project manager of MailerSend, a solution to send transactional emails via API or SMTP. We would love to connect MailerSend to NocoDB. Would you consider integrate our solution into your app store as an email provider?

Please find more details on our website: [www.mailersend.com](https://www.mailersend.com)
Our API documentation: [www.developers.mailersend.com](https://developers.mailersend.com/)
Our SDKs:
- [MailerSend PHP ](https://github.com/mailersend/mailersend-php)
- [MailerSend for Laravel ](https://github.com/mailersend/mailersend-laravel-driver)
- [MailerSend Node.js ](https://github.com/mailersend/mailersend-nodejs)
- [MailerSend Golang ](https://github.com/mailersend/mailersend-go)
- [MailerSend Python ](https://github.com/mailersend/mailersend-python)
- [MailerSend Ruby ](https://github.com/mailersend/mailersend-ruby)

Let us know when you create yourselves an account so we can approve you.

**Comment by pranavxc** [comment]
Added `MailerSend` in `0.11.6`.
