### ISSUE TITLE
vue3: UI ACL lists m2m tables

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3361]
![Screenshot 2022-08-26 at 11 07 53 PM](https://user-images.githubusercontent.com/86527202/186961238-ed07433f-e07b-4647-80ad-8162e163ff51.png)

**Comment by pranavxc** [comment]
Fixed in - https://github.com/nocodb/nocodb/commit/9f94a8605e159be6f6a3ed5b7258910762586777
