### ISSUE TITLE
Improve error handling when external db connection errors out

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#3369]
If we open a project with wrong configuration, the project view is still opens. 

Better way:
- If a user opens the project url then navigate to project list view and show a toaster in why it is erroring out.
- If the user selects a misconfigured project, then we should not open the project view and just show the error toaster.

**Comment by wingkwong** [comment]
preliminary findings:
- with cache disabled, the issue can be reproducible 
- with cache enabled, even the cache is cleaned, the db is still accessible. 

SQL:

```sql
ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
```
