### ISSUE TITLE
Bug: Unexpected M2M columns being created

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#338]
**Please enter the following details**
M2M columns are created unexpectedly. See below steps to reproduce.

**Steps To Reproduce**

Supposing you have 3 tables A, B, and C, each contains several records.

1. In table A, create a M2M column linking to table B. The M2M column can be created successfully.
2. In table A, create a M2M column linking to table C. The M2M column can be created successfully. However, the M2M column created in step 1 got duplicated N times. (See screenshot)

P.S. m2mA_B table looks normal though.

**Expected behavior**
No duplicate / unexpected columns are created.

**Screenshots**
![image](https://user-images.githubusercontent.com/35857179/125299624-e6e18300-e35b-11eb-9fea-803f0f121aa0.png)

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.10.1**

**Comment by pranavxc** [comment]
Fixed in `0.10.3`
