### ISSUE TITLE
build packages/nocodb-sdk throw TypeError: host.fileExists is not a function

### ISSUE THREAD

**Issue by tomorrowcheng** [nocodb/nocodb#3382]
**Please enter the following details**

Copy and Paste Project Info - Tutorials: How to check my Project info? ([YouTube Tutorial](https://www.youtube.com/watch?v=AUSNN-RCwhE) or [Documentation](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-))

```
Node: **v16.17.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.92.4**
```

**Steps To Reproduce**

1. cd packages/nocodb-sdk
2. npm install
3. npm run build

**Expected Behavior**

build success

**Screenshots**

throw TypeError: host.fileExists is not a function; 
I guess something wrong with typescript version，like https://github.com/microsoft/TypeScript/issues/4565； but updated typescript latest version，it has the same error。
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/42925114/187118973-2f2c2ddb-e9ad-4b80-8c52-650fe28d9b01.png">

**Comment by wingkwong** [comment]
seems related to [this issue](https://github.com/acacode/swagger-typescript-api/issues/370).
