### ISSUE TITLE
No data in my tables from a schema

### ISSUE THREAD

**Issue by orsk-moscow** [nocodb/nocodb#3423]
Hi guys! 

thank you a lot for the NocoDB. 

I facef a potential bug, could you please take a look of it?

**Please enter the following details**

Copy and Paste Project Info - Tutorials: How to check my Project info? ([YouTube Tutorial](https://www.youtube.com/watch?v=AUSNN-RCwhE) or [Documentation](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-))

```
Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.9.31**
```

or provide the following info

```
NocoDB used as docker : true
NocoDB version : 0.9.31
Database used in NC_DB URL  : mysql 
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : OS X as a host: 12.4 (21F79) 
Node.js version if running as node : <don't know how to check it>
Database version : 8
```

**Steps To Reproduce**

1. go to main interface
2. select a data source
3. expand a list of tables

**Expected Behavior**

I can show my data rows

**Screenshots**

1 step. 
I have a data stored as a Pandas Dataframe (see variable `df2`, cell 31), num rows = 2921, num columns = 7 (cell 32). 
I try to read a data from `test3` table (`dft` variable), got a `table doesn't exist` error, and this is completely normal (cell 33). 
![Снимок экрана 2022-08-31 в 20 10 55](https://user-images.githubusercontent.com/46628660/187740292-3e79f4ef-ecd0-4698-9887-df6b26fb77b0.png)

2 step. 
insert my data in MySql database (`df2.to_sql` operation, cell 34) and check it (cell 35) exists
![Снимок экрана 2022-08-31 в 20 11 13](https://user-images.githubusercontent.com/46628660/187740315-d6a3e210-8492-4104-9723-42387e17f4ac.png)

3 step
go to interface, reload metadata and select the table in expanded list, see all the columns from my table, but can't see any data rows. 
![Снимок экрана 2022-08-31 в 20 11 48](https://user-images.githubusercontent.com/46628660/187740335-5d866301-bc7c-4755-b1ce-9d4527eca8d5.png)

**Comment by orsk-moscow** [comment]
BTW, guys, looks like your invite link doesn't works: "Join our discord : https://discord.gg/5RgZmkW for realtime help": smth wrong with rate limit

**Comment by orsk-moscow** [comment]
the bug canceled: as i recognized, problem is with name 'Идентификатор операции' - it contains whitespace symbols, and it affects the nocodb engine somehow. After columns was renamed to 'Идентификатор', table looks as expected

**Comment by o1lab** [comment]
use discord.nocodb.com
