### ISSUE TITLE
(gui-v2): import excel failed

### ISSUE THREAD

**Issue by tomorrowcheng** [nocodb/nocodb#3426]
```
Node: **v16.14.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.90.5**
```

**Steps To Reproduce**

1. drop excel file to container

**Expected Behavior**

import success

**Screenshots**

<img width="364" alt="image" src="https://user-images.githubusercontent.com/42925114/187816968-0c97cb9c-0fdd-476b-b1f2-463c2eab4b02.png">
<img width="546" alt="image" src="https://user-images.githubusercontent.com/42925114/187817162-f02401c9-d87b-41c4-8de9-6e384f68cc3f.png">

**Comment by wingkwong** [comment]
Mind to provide a dummy excel for reproducing the issue?

**Comment by tomorrowcheng** [comment]
> Mind to provide a dummy excel for reproducing the issue?
[销售表.xlsx](https://github.com/nocodb/nocodb/files/9466320/default.xlsx)

**Comment by wingkwong** [comment]
Able to reproduce. Will take a look.
