### ISSUE TITLE
Improve validation of add filter form

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#3429]
If you u create a filter of a DateTime type column in shared view of type `>=` and value `2005-0`
Api will error out but there is no indication of that nor an indication that the format of the value give is a wrong one.

**Comment by wingkwong** [comment]
@mustafapc19 is it still reproducible? can you share the error and the project info?

**Comment by mustafapc19** [comment]
Api response now seems fine. Closing the issue.
