### ISSUE TITLE
import csv on existing table allows duplicate data in primary key

### ISSUE THREAD

**Issue by angim** [nocodb/nocodb#3438]
```
NocoDB created in: HEROKU
NocoDB version : 0.92.4
Database used in NC_DB URL  :  pg
Project was created  by clicking : New Project 
Database on which spreadsheet is created :  pg 
Database version : 14.4
```

When importing a CSV into an existing table, this feature inserts duplicate data into the primary key of the table.

![image](https://user-images.githubusercontent.com/22670100/187918562-8270f050-dddb-4dea-a3ac-73d4b1fb09fa.png)

**Comment by wingkwong** [comment]
1. I could see `duplicate key value violates unique constraint` error when I import it. Mind to provide a dummy csv file for reproducing the issue?
2. Is the ID field auto generated? If so, I think you can untick it so that the value can be generated automatically.

**Comment by angim** [comment]
1. Sure, please see the attached CSV file.

[Parameter.csv](https://github.com/nocodb/nocodb/files/9488097/Parameter.csv)

3. No, it's not an auto-generated ID. Please see the definition on the image below.

![image](https://user-images.githubusercontent.com/22670100/188404739-4e96da9e-37c5-48ba-a73c-12b7b1e95a1d.png)

**Comment by wingkwong** [comment]
Can you try on this version? 

```
  docker run -d -p 8888:8080 nocodb/nocodb-timely:0.97.0-pr-3811-20221012-0346
```

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/35857179/195265189-8d489dcf-83ec-421d-84d0-cf920184a8ca.png">

**Comment by angim** [comment]
I tested this version, but it didn't work. 
It does not duplicate data for the primary key but does not make any changes to existing records or create new ones.
When I tried to import, the screen froze for a long time, and the views stopped working correctly. 
After this first attempt, I tried to upload the CSV file again, but the option Upload CSV also stopped working...

![image](https://user-images.githubusercontent.com/22670100/197652963-3ba253b6-f2b1-4d1a-83be-a839e61121a2.png)

![image](https://user-images.githubusercontent.com/22670100/197652907-5142e111-f614-41b0-9e68-617ba7be5abc.png)

**Comment by wingkwong** [comment]
May I know how many records in your csv (and the size please)? I'm building another docker tag for you to test. It should resolve the problem in that version.

The expected behaviour:

- Import from CSV
- Table Created. Data inserted.
- Import the same CSV to the table created in above step
  - include all the fields 
- Error thrown due to duplicate keys

**Comment by angim** [comment]
I can't run the test correctly because I got blocked when I just tried to set the PK... it's generating the following error:

![image](https://user-images.githubusercontent.com/22670100/198043812-a3b1a8af-0050-4510-bf22-32c01ae93320.png)

**Comment by wingkwong** [comment]
> I can't run the test correctly because I got blocked when I just tried to set the PK... it's generating the following error:
> 
> ![image](https://user-images.githubusercontent.com/22670100/198043812-a3b1a8af-0050-4510-bf22-32c01ae93320.png)

I changed the PK in DB directly though. The error reminds me of this issue: https://github.com/nocodb/nocodb/issues/1263
