### ISSUE TITLE
[Feature] Round with decimal cases

### ISSUE THREAD

**Issue by matheusnunes** [nocodb/nocodb#3441]
Hello 

I would like to know if is possible to add a second optional parameter in the round function, this parameter will allow the user to select how many decimal cases he wants in his output value.

For example I've formula that multiplies a decimal field with 4 decimals and a decimal field with 2 decimals, and I want a output with a rounded 2 decimals case number.

Eg.: `5.1704 * 826.53 `gives me the following result `4273.4907120000`.  If I apply the round function the result would be  `4273`. But I want the output to be  `4273.49`.

Thank you.

**Comment by Genne23v** [comment]
The issue seems doable for me. Can I contribute?

**Comment by wingkwong** [comment]
@Genne23v Assigned to you. Please feel free to ping our team in discord if you have any questions.
