### ISSUE TITLE
vue3 : DASHBOARD_URL and other url in env variable

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3443]
Verify if our PR builds works with env variables
- [ ] DASHBOARD_URL
- [ ] *_URL

**Comment by pranavxc** [comment]
- [x] Verified custom dashboard path
   
![Screenshot 2022-09-02 at 12 29 26 PM](https://user-images.githubusercontent.com/61551451/188077750-6106e528-a0b1-4b96-8a6f-239a293d3ff6.png)

- [ ] Custom url - to be done
