### ISSUE TITLE
Issue: Align data to top in grid view

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#345]
Hi,

When too much data is present in one cell, it causes other cell data to be aligned in middle. This makes reading the other cell data difficult. In case data could be aligned at top it will be readable quicker.

Steps to reproduce:
1- Put too much data in longtext cell
2- Put data in cell with single line
3- Select grid view

![image](https://user-images.githubusercontent.com/86340924/125628773-dc2773d7-5f68-4cd3-ae08-336ed527d8e9.png)

**Comment by jpbourgeon** [comment]
Also LongText fields could be trim at a specific length and made expandable with a button.

**Comment by chetanverma16** [comment]
Hey @bcakmakoglu,
Is it still open?

**Comment by bcakmakoglu** [comment]
@chetanverma16 
Current behavior will collapse the long-text cell to a small height when you stop editing so this issue is not necessarily still a thing.
You can align the content to the top and I can take a look if it works better that way though :)

**Comment by dstala** [comment]
closing this. will be further tracked under #2287
