### ISSUE TITLE
vue3: theme palette doesn't work at times

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3459]
The custom theme color picker worked. 
in the color palette, does first row represent `primary` color and second `accent`? or it's just all `primary`? this isn't very clear currently

**Comment by wingkwong** [comment]
both row is for primary color.

**Comment by mertmit** [comment]
Changed theme handling on PR, for ux part:
Color palette actually works as predefined themes, we can use something like this to make it clear that it is going to change both primary and accent
![image](https://user-images.githubusercontent.com/59797957/188288384-872c52f0-1920-4a96-b4ef-22259815312f.png)
**Or like this (accent is easier to recognize)**
![image](https://user-images.githubusercontent.com/59797957/188288481-3527c128-619b-4811-aa77-f154cdc817d5.png)

Waiting for feedback to apply this

**Comment by dstala** [comment]
I understand now. Themes are with a pre-defined combination of primary and accent colors. The current representation is ok IMO.
