### ISSUE TITLE
Bug: failed to execute the auto-generated function after setting the column as PK

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#346]
Goal: change default id column to uuid (auto-generated)

**Steps To Reproduce**
1. create a table
2. create a column "uuid" with auto-generate function, e.g. ``md5(random()::text || clock_timestamp()::text)::uuid``. Make it as NN & PK 
3. delete default existing "id" column
4. create a new record -> no auto generate value
5. It prompts something like column with PK cannot be empty (bc no value begin auto-generated)

however, 

1. create a table
2. create a column "uuid" with auto-generate function, e.g. ``md5(random()::text || clock_timestamp()::text)::uuid``. NOT make it as NN & PK 
3. delete default existing "id" column
4. create a new record -> able to auto generate value

**Expected behavior**
The value can be auto-generated. 

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.10.3**

**Comment by pranavxc** [comment]
fixed in `0.10.5`
