### ISSUE TITLE
vue3: UI ACL displays not-allowed error

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3469]
- create new project with 1 table
- remove access for this table for editor role (UI ACL)
- preview as `editor` opens user-management tab & an error

![Screenshot 2022-09-03 at 12 14 06 PM](https://user-images.githubusercontent.com/86527202/188259250-9108e51b-236c-48b8-aef3-0d60b1999b9b.png)

**Comment by wingkwong** [comment]
@dstala What is the expected behaviour here?

**Comment by dstala** [comment]
show empty page, but not user/api management tab; just trying to avoid displaying error
