### ISSUE TITLE
vue3: gallery filter result, if 1-card - covers entire page

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3474]
![Screenshot 2022-09-03 at 5 33 28 PM](https://user-images.githubusercontent.com/86527202/188269649-e9673de5-dd71-4c51-96b6-23b92b2b5df7.png)

**Comment by o1lab** [comment]
We can do this after the release/

**Comment by mertmit** [comment]
Fixed/closed this as this is only a small css change
