### ISSUE TITLE
vue3: shared view list- `show all shared views of this table` option missing

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3480]
ignore if its by design
  
![Screenshot 2022-09-03 at 8 04 28 PM](https://user-images.githubusercontent.com/86527202/188275269-05676f66-5875-4c8f-b2b4-8e87b37f5d1f.png)
  
![Screenshot 2022-09-03 at 8 04 09 PM](https://user-images.githubusercontent.com/86527202/188275281-d6e0fc64-ca98-4023-8d27-9c5e8c2fc160.png)

**Comment by o1lab** [comment]
We can do this later after the release.

**Comment by mustafapc19** [comment]
Currently `shared view list` list out all the shared view of all views of a table, hence this option will not be required. Earlier in v1 we used to only list shared view of that particular view of that table by default, so we needed that option. The current way imo is a better way of handling this, hence closing the issue.
