### ISSUE TITLE
Bug: Unexpected character "}" in M2M relation

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#349]
Unexpected character "}" in M2M relation

**Steps To Reproduce**
1. Go to Project Metadata
2. Click DB Metadata
3. Click Relations
4. if you have m2m relationship, you should see something like

```
# | Table Name (xx/xx) | Relation | Parent | Child |  
1 | Table_A | HasMany | Table_A | _nc_m2m_Table_B_Table_A}
2 | _nc_m2m_Table_B_Table_A} | BelongsTo | Table B | _nc_m2m_Table_B_Table_A}
```

5. Notice that for all ``relation.tn``, there is an unexpected characher ``}`` at the end.

**Expected behavior**
it should be ``_nc_m2m_Table_B_Table_A`` instead of ``_nc_m2m_Table_B_Table_A}``

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.10.3**

**Comment by pranavxc** [comment]
fixed in `v0.10.5`
