### ISSUE TITLE
🐛 Bug: import excel throw error

### ISSUE THREAD

**Issue by tomorrowcheng** [nocodb/nocodb#3500]
**Please enter the following details**

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.90.5**
```

**Steps To Reproduce**

1. import excel like this:

[测试表格.xlsx](https://github.com/nocodb/nocodb/files/9490181/default.xlsx)

**Expected Behavior**

import success

**Screenshots**

import failed

**Comment by tomorrowcheng** [comment]
> any particular reason to use `0.90.5` ? Suggest to try the latest version.

used the latest version; Sorry, I gave the wrong excel；You can try this:
[测试表格.xlsx](https://github.com/nocodb/nocodb/files/9490327/default.xlsx)

**Comment by wingkwong** [comment]
preliminary findings:

- dtxp looks fine: `FR\\BI','FR','FR\\FT`
- the data type in db is incorrect: `enum('FRBI','FR','FRFT')` while `enum('FR\\BI','FR','FR\\FT')` is expected

**Comment by fulldecent** [comment]
I am experiencing this in the latest version 0.207

![Screenshot 2024-05-13 at 11 18 09](https://github.com/nocodb/nocodb/assets/382183/bac67df0-9c84-4bcd-a686-7629a88de853)

**Comment by dstala** [comment]
Import defaults to single line text now. Please reopen this issue if you face it still in latest release
