### ISSUE TITLE
NocoDB Windows binary download link not working

### ISSUE THREAD

**Issue by IvanDrag0** [nocodb/nocodb#3505]
On the Github project front page, the command to download the Windows binaries (`iwr http://get.nocodb.com/win-x64.exe`) is not working. When trying to run the commands, I get an error `Unsupported platform`.  The issue might stem from the Windows release on the Releases page missing the .exe file extension. When running the command without the .exe extension (`iwr http://get.nocodb.com/win-x64.exe`), the request is redirected to [https://github.com/nocodb/nocodb/releases/download/0.92.4/Noco-win-x64.exe](https://github.com/nocodb/nocodb/releases/download/0.92.4/Noco-win-x64.exe), which shows a page not found since the Releases page lists the Windows releases without the .exe extension (the link works if you remove the extension from the end of the link).

The Windows releases should have the correct extension added (since either way the user has to add the extension manually after download).

**Comment by wingkwong** [comment]
Handled in https://github.com/nocodb/nocodb/pull/3410. Please wait for the next release.

**Comment by IvanDrag0** [comment]
Awesome! You can close this issue.
