### ISSUE TITLE
Docker Volume for App

### ISSUE THREAD

**Issue by alderson59** [nocodb/nocodb#351]
What is the volume for persistence? I referred to the `docker-compose.yml` on the codebase, but it does not have a volume for persistence on the nocodb app.

I find that each time I recreate the container, I have to see the welcome splash and setup my users again. Metadata also have to be reset each time.

Someone on discord mentioned `/usr/src/app`, but I tried this and it didn't work, nor could I find this anywhere else. Any official documentation? :)

**Comment by pranavxc** [comment]
Since `0.10.6`, you can mount `/usr/src/app` folder.
