### ISSUE TITLE
CSV import : auto-populate multi-select options

### ISSUE THREAD

**Issue by apprentiLAB-Suzanne** [nocodb/nocodb#3512]
Hi !
And thanks to all the people working on this amazing app :) 

I was just testing CSV export / import (for backup purposes), and when importing a CSV file to a new table and assigning one of its field to the MultiSelect type, I noticed all my options stayed gray and the option list in the field was empty. Which is a problem for me if I want to add new entries to the table, I have to reenter all the MultiSelect options before adding these options to the new entry. This can be time-consuming, especially with a long option list.

So I was thinking it would be cool for that option list to be auto-populated from the values found in the file that is imported, like it already does for SingleSelect.

I am not a developer so I don't really know how to implement this.

Thanks !

**Comment by wingkwong** [comment]
@apprentiLAB-Suzanne Could you please show a simple example? I wasn't able to reproduce the gray options and empty option list. Did you do that simply by adding some values to a multi-select columns, export and import to the same table? Or you've updated some new options in the file?

**Comment by apprentiLAB-Suzanne** [comment]
> Could you please show a simple example?
Hi @wingkwong, here are some pictures...

My initial table created from scratch with a multi-select. I then export it as CSV : 
![Nocodb_initial](https://user-images.githubusercontent.com/73226532/192240190-31d79803-696b-4eb4-bfb2-cd346a766521.PNG)

___
When I try to reimport the generated CSV file, the field "Domaine" is auto-assigned to SingleLineText : 

![Nocodb_importCSV](https://user-images.githubusercontent.com/73226532/192240687-0bfbfb3b-c87c-42d6-a9e2-7b53c2de6867.PNG)

___
I then assign it manually to MultiSelect, but it doesn't fill the options automatically (and I have a lot of them) : 

![Nocodb_importCSV_selectMulti](https://user-images.githubusercontent.com/73226532/192240738-1b1becff-7e4d-47f7-84d1-c9435be0de34.PNG)

___
My table shoes up with grayed MultiSlect options : 

![Nocodb_grayedMulti](https://user-images.githubusercontent.com/73226532/192240807-1d96f2a0-ea93-4002-9652-5ba34243b22d.PNG)

___
When I go to Edit Field, the options are empty : 
![Nocodb_emptyMulti](https://user-images.githubusercontent.com/73226532/192240959-f978fc23-b554-4940-9a52-fce3804afa53.PNG)

**Comment by wingkwong** [comment]
@apprentiLAB-Suzanne Thank you for your steps. Could you also share your [project info](https://docs-dev.nocodb.com/faqs/#how-to-check-my-project-info-) as well. In latest version, it shows the error when I click import after changing back to MultiSelect with empty select option. 

However, recently I've made some changes. It may probably resolve the problem. Could you please help verify it?

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.97.0-pr-3811-20220927-0451
```

**Comment by apprentiLAB-Suzanne** [comment]
Hi @wingkwong , thanks again for looking into this.

Here's my project info : 

Node: **v16.11.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.4**

Also, I don't think I've mentioned it on this issue but I am using NocoDB as a Yunohost app, I don't know if it changes anything, except it means I am a bit behind on updating since I must wait for PRs on their side : https://github.com/YunoHost-Apps/nocodb_ynh

**Comment by NickJCreed** [comment]
Is this solved? Currently trying to do the same in the cloud version but having no luck.
Goal is to populate multi select options rather than typing them by hand (there's over 100).

Someone advised to import the csv as single line text then convert the column to multi select.
However after doing that the column just goes blank and the multi select has no options.

Has anyone had any success trying to populate a multi select column from a csv or is it not possible with noco?

**Comment by yanayz** [comment]
reiterating the importance of this. If you have existing data and it can't properly be imported - this app becomes a no-go.
The most common use case is importing (CSV) with a column of tags that should translate automatically into a multi-select. 
right now you can't define  it as such during import, and if you try to modify afterwards (from string to multi-select) the values are not auto-created and not separated. you get an unhelpful "unique" values concatenations such as "strategy,tools,", "tools,text", "reread,text,later","later,text", and so on. Not recognized as individual values for the multi-select....
