### ISSUE TITLE
[Feature] Expanded record view : provide option to display hidden fields

### ISSUE THREAD

**Issue by apprentiLAB-Suzanne** [nocodb/nocodb#3513]
Hi !
I was experimenting with the gallery view. I tried hiding fields in the view, but when I click on an entry, and display the bigger popup card for that entry (I don't know how you call it), the same fields are hidden, whereas in Airtable, the hidden fields are displayed on the popup card. I find this behavior disturbing, since I think the goal of that popup card is to view and edit more details about the entry than are displayed on the view. I tried searching for a related issue but couldn't find anything, I might not have the proper keywords. 
Anyway, is this a planned feature ?
Thanks a lot :)

**Comment by dstala** [comment]
@apprentiLAB-Suzanne 
Popup card - we refer to it as `expanded form` or `expanded record` view. We had designed this card to display only enabled fields. It could be nice to have an option to show/hide hidden columns in the expanded record view. 
I will mark this as a feature request. 

Do try out our new UI @ https://github.com/nocodb/nocodb/releases/tag/0.96.2
We will be glad to hear from you.

**Comment by apprentiLAB-Suzanne** [comment]
@dstala thank you !
The way it's done in Airtable, which I think is nice, is that the hidden fields are grouped in a collapsible section on the expanded record view : 

![image](https://user-images.githubusercontent.com/73226532/189066090-f65dea23-7c40-4d29-9b90-f4c840e75a5c.png)

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/4092
