### ISSUE TITLE
Expanded row view is not available for a locked view

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3517]
## Steps : 
- Lock a grid view.
- Observe the expand row option is not available.

## Problem
- Expanded row view is not available after locking the grid view.

## Expected behaviour
- Expanded row view should be available.

**Comment by alprotasov** [comment]
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.4**

Also I can't edit records.

**Video:** https://records.cherishdev.com/conversations/e96267f3-25a3-5ed9-86c5-f69c578e1155
