### ISSUE TITLE
DevOps issues

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#3527]
- [x] incorrect tag (now it tags one of the combined tags of target one)
- [ ] local sdk path
- [ ] contributor PR release 
  - npm ERR! need auth You need to authorize this machine using `npm adduser` 
  - Findings: 
    - we may use `pull_request_target` but it needs a way to check if it's a draft or not
    - security concerns

**Comment by o1lab** [comment]
Can be reopened if required.
