### ISSUE TITLE
Handling support for parsing jdbc connection params has affected NC_DB

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3529]
PG database url is connecting to localhost.

You can downgrade to 0.92.4 for the moment until we make a release today.

**Comment by shin1103** [comment]
Can't  execute nocodb/nocodb:latest using docker-compose.yml.

Is this same issue?

`
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                         ║
║                                                 EXCEPTION OCCURED!! in PGClient @ createDatabaseIfNotExists             ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   MESSAGE:                                                                                                              ║
║   connect ECONNREFUSED 127.0.0.1:5432                                                                                   ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   CODE:                                                                                                                 ║
║   ECONNREFUSED                                                                                                          ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   STACK:                                                                                                                ║
║   Error: connect ECONNREFUSED 127.0.0.1:5432                                                                            ║
║       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)                                                   ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║                                                                                                                         ║
║                                                                                                                         ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}`

**Comment by alprotasov** [comment]
Seems to me, yes. @shin1103

**Comment by shin1103** [comment]
Thanks, wait for fixed this issue.

**Comment by FerLSanchez** [comment]
Seems to be the same happening here, after updating to latest Docker image... :(
Shall we change something in the ENV variables? Just wait for the fix?
Thank you, team!

**Comment by jwillmer** [comment]
Same issue. Investigating since this morning what has gone wrong and finally saw this ticket. Can you please give me some estimate till a fix will be released or to which version/tag I should (and can?) downgrade?

**Comment by alprotasov** [comment]
I think they fixed it and now it's in release process. Waiting for a build.

**Comment by o1lab** [comment]
@jwillmer : release will be out today.

Downgrade to previous 0.92.4 for the moment.

**Comment by o1lab** [comment]
Can you please confirm if below PR-build works for you. We're testing couple of more scenarios.

`nocodb/nocodb-timely:0.96.0-pr-3528-20220907-0904`

**Comment by FerLSanchez** [comment]
This building starts, connects, I can login, see my data, and the API is usable :)
