### ISSUE TITLE
Running nocodb without access to nocodb.com

### ISSUE THREAD

**Issue by maksim77** [nocodb/nocodb#3555]
```
NocoDB used as docker : true
NocoDB version : 0.96.1
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : docker
Node.js version if running as node : 
Database version : 
```

**Steps To Reproduce**

1. Update from 0.92.4 to 0.96.1
2. Open dashboard

Similar to #3540 I have a problem with access to service when host cannot access to nocodb.com.
It seems to me that the problem is here:
https://github.com/nocodb/nocodb/blob/2c88fe34318e4978e5caca962b441e729dd4af0d/packages/nocodb/src/lib/meta/api/utilApis.ts#L83-L92

Maybe it's better to make some kind of configuration flag that would restrict requests to the external Internet in general?

**Comment by mertmit** [comment]
@maksim77 issue should be resolved on latest develop branch, can you confirm if possible?
