### ISSUE TITLE
Impossible to create a new row since 0.96

### ISSUE THREAD

**Issue by FerLSanchez** [nocodb/nocodb#3565]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.96.2**
```

**Steps To Reproduce**

I add all the data, as usual, in a table with three fields that are references to other tables (money type field, and location based commas and points are acting weird again but that's not the main problem).
When I click on save, I have the errors I show you in the screenshots. It seems to be inserting the row with the basic data, and then updating the references. But given the FK fields are also defined as NOT NULL, everything breaks.
The table is not "hand-made" but it was created with Noco with previous versions.

**Screenshots**

<img width="1453" alt="Screenshot 2022-09-09 at 11 48 15" src="https://user-images.githubusercontent.com/2619609/189323494-c12e4acc-22f6-4bd3-b494-8c0a3966a1d3.png">

**Comment by o1lab** [comment]
Can u pls paste a screen shot of the grid view without the errors and fields in question.

You can also do this by opening fields menu and taking a screenshot. Will look into it.

**Comment by FerLSanchez** [comment]
Sure, here you have the fields:
<img width="273" alt="Screenshot 2022-09-09 at 12 09 47" src="https://user-images.githubusercontent.com/2619609/189326882-a48c7648-c68a-4ec2-8940-7a87ff6b7c89.png">

And, also, if it helps, the fields as created in the database:
<img width="788" alt="Screenshot 2022-09-09 at 12 10 25" src="https://user-images.githubusercontent.com/2619609/189327002-b160c154-be19-4b7d-9793-b0e8dcabae67.png">

Thank you!

**Comment by o1lab** [comment]
> I add all the data, as usual, in a table with three fields that are references to other tables

Are you clicking on the `+` button on right top to do this ? I could not manage to see the errors - however the added row is not reflected immediately. And are you on mariadb by any chance - I am on mysql.

**Comment by FerLSanchez** [comment]
I tried with the + button and introducing the line as a new line.
With the new line it happens after I just add the first field, the date. With the top + button it happens when clicking "save row". Then I see the errors I showed you in the first screenshot :/

I am in mysql, version 8.0.30

**Comment by FerLSanchez** [comment]
Maybe solution is to get rid of these NN restrictions in database for the fields, I don't know...

**Comment by o1lab** [comment]
Ya please try setting NN to false outside in your tool. 

Although, I have to note that we have not changed how foreign-keys are created.

**Comment by FerLSanchez** [comment]
Let's take it as a poltergeist and close it by now then. Thank you very much for your support!

**Comment by o1lab** [comment]
Have added this for follow up issue : https://github.com/nocodb/nocodb/issues/3566
