### ISSUE TITLE
🔦 Feature: [Row Expansion] Copy Paste from excel to table + add more records as required

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#3567]
**Need for this feature**
As for Airtable, it would be interesting to be able to paste multiple rows from excel to an existing table (Crtl+C, Ctrl+V)

**Comment by fphg** [comment]
useful feature indeed since it eases user migrations from desktop suites

**Comment by psytron** [comment]
I would rank this as the most important missing feature. All other major apps in this space have this capability.

**Comment by decentropy** [comment]
> I would rank this as the most important missing feature. All other major apps in this space have this capability.

ditto on most important feature

**Comment by LindezaGrey** [comment]
i would also add the possibility to paste complete columns. E.g. you create a new column in your table and copy/paste multiple rows (but only one column) from excel

**Comment by CarlyBobak** [comment]
Would also like to bump up the priority of this feature.

**Comment by ho2021** [comment]
Lack of this feature is the main reason I didn't migrate, looking forward to adding this feature, many thanks

**Comment by dstala** [comment]
Copy paste from excel/spreadsheet is currently supported. It works over existing records; doesn't automatically add more records as of now.

**Comment by jer-dot** [comment]
Important feature. That would facilitate a lot of tedious manual work preparing CSV, import manually, etc...

**Comment by decentropy** [comment]
For those who need open source web spreadsheet with ability to paste multiple cells (like you'd expect any spreadsheet to do)... I found grist 
https://github.com/gristlabs/grist-core

**Comment by lonelyclick** [comment]
Important feature.

**Comment by DarkPhoenix2704** [comment]
Added support for Row Expansion in https://github.com/nocodb/nocodb/pull/9788
