### ISSUE TITLE
🔦 Feature: Infinite Scroll on table

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#3568]
**Need for this feature**

Airtable displays tables with infinite scroll.  

Is it possible to have a mode without pagination and load data when the user scrolls the table ?

**Comment by Rafurus** [comment]
This feature will be very efficent especially that we don't have right now option to go to specific page to speed up looking for something. 
In baserow I can scroll with scroll bar to any percentage of table.

**Comment by bmos** [comment]
This feature is what is keeping me from using Noco DB, along with many other people I'm sure.

**Comment by DesignMike** [comment]
I would like to express my support for a feature that would allow users to change the default number of rows that are loaded on the screen. While the self-hosted version currently allows this through changes to an environmental variable, I am a user of the cloud version and would appreciate a global setting for this purpose.

**Comment by kateyslee** [comment]
I would like to work on this with a team for a university course project! We will likely attempt Issue #7872 before this however.

**Comment by LucBerge** [comment]
I also need this feature

**Comment by LucBerge** [comment]
@dstala why not making the default `pageSize` a table parameter? If I want to query all the records in a table, I just set it to -1 and fetch all the records. Same on API.
