### ISSUE TITLE
MySQL connection issue since 0.96.0

### ISSUE THREAD

**Issue by dib0** [nocodb/nocodb#3576]
```
NocoDB used as docker : true
NocoDB version : 0.96.0
Database used in NC_DB URL  : mysql
OS on which NocoDB is running : Synology NAS (Some form of Linux)
```

I have been running NocoDB using Docker for over several months. I use Watchtower to automatically update docker images every night, when available.
Running NocoDB up to image tagged 0.92.4 was working fine. After updating to 0.96.0 I got the following errors:
App started successfully.
Visit -> https://my url behind reverse proxy
╔══════════════════════════════════════════════════════════════════════════════╗║    
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
 code: 'ECONNREFUSED',
 syscall: 'connect',
 address: '127.0.0.1',
 port: 3306,
  fatal: true
}

It somehow seems to not interpret the NC_DB URL correctly, which is set using an environment variable to "mysql2://{specific ip}3307?u={username}&p={password}".

Reverting to the image tagged 0.92.4 is working fine. I've been waiting for newer images than 0.96.0, but those show the same issue. IS there an error in the docker images, or did something change that I need to change? I've looked at the docs, but can't find anything wrong with or any change in the environment variables I've been using so far.

**Comment by o1lab** [comment]
Can you pls try 0.96.2. we solved an issue with URL in 0.96.0

**Comment by dib0** [comment]
Hi!

Thanks. I tried, but get the same error:
![Screenshot from 2022-09-11 14 49 54](https://user-images.githubusercontent.com/3939328/189528435-03f5bd68-2a18-43f9-a78e-c1a76e196041.png)

**Comment by o1lab** [comment]
@mertmit

**Comment by mertmit** [comment]
We changed our URL handling to support custom parameters looks like those changes caused this.
If possible can you try to use our new `Use Connection URL` option which you can find under `Create By Connecting To An External Database`

![image](https://user-images.githubusercontent.com/59797957/189530156-5f052183-5fb8-476c-8506-7ef17583d72e.png)

Please update me if you can connect using this with your connection URL. If this doesn't work can you please check `Edit Connection JSON` under `SSL & Advanced Parameters` to make sure everything is as expected. (There might be some issue with your password parsing)

Feel free to contact me updating the issue or [via Discord](https://discord.gg/5RgZmkW) (you can find me under Noco-Team) if you need help with any of those steps

**Comment by dib0** [comment]
Hi,

Thank you for the reply. But nocodb isn't even starting, so I can't reach any of the UI bits.
There are no json files in the local mapped storage.

If I open a browser, it just says "Can't GET /", or something like that. Besides, I'm in doubt that creating a new project would let my current project work again, but maybe I'm missing the point.

**Comment by o1lab** [comment]
@mertmit : @dib0 is having issues with NC_DB getting parsed.

@dib0 : pls reach out to Mert on our discord. Happy to help.

**Comment by dib0** [comment]
@o1lab @mertmit Sorry, I'm not on discord...

**Comment by mertmit** [comment]
Can you try this build: nocodb/nocodb-timely:0.96.2-pr-3578-20220911-1344

**Comment by dib0** [comment]
Hi,

Thanks again! I've tested nocodb/nocodb-timely:0.96.2-pr-3578-20220911-1344 and that works like a charm! Got no terminal logging, but I could open the site, login and access all my projects.
Thank you!

I'll wait for the next latest docker to update my container officially.

**Comment by djmaze** [comment]
On the 0.96.2 dockerimage, I had JS errors (404s and "could not load module"), so NocoDB would not even load. 

The `nocodb/nocodb-timely:0.96.2-pr-3578-20220911-1344` seems to solve that as well.
