### ISSUE TITLE
Date field includes time when choosing "date" type.

### ISSUE THREAD

**Issue by sph33r** [nocodb/nocodb#358]
NocoDB used as docker : true 
NocoDB version : 0.10.6
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Ubuntu 21.04
Database version : 12.7

**Steps To Reproduce**
Create a new database field based on "date" which shows an example of "2020-09-09"
Enter a new value for yyyy-mm-dd
View in table, it will show yyyy-mm-dd 00:00:00.000Z

**Expected behavior**
If you select the same date type in Airtable, it just shows yyyy-mm-dd without the time stamp stuff.

**Screenshots**
Airtable:
<img width="303" alt="Screen Shot 2021-07-18 at 16 46 10" src="https://user-images.githubusercontent.com/1290732/126081845-121aff55-f98c-4a9d-b32b-5fc593eda06b.png">

NoCoDB:
<img width="350" alt="Screen Shot 2021-07-18 at 16 46 21" src="https://user-images.githubusercontent.com/1290732/126081859-6dde3bd1-780f-405c-ab1a-e59d672d1d1b.png">

I don't want timestamps, that's why I chose just the date. I can shrink the field to hide the zeros but it would be better if this didn't show up at all since the example shows no timestamp date. 

<img width="405" alt="Screen Shot 2021-07-18 at 16 49 06" src="https://user-images.githubusercontent.com/1290732/126081876-1553a3bb-d86f-420a-acf5-09600d1c85e8.png">

**Comment by pranavxc** [comment]
fixed in `0.11.2`
