### ISSUE TITLE
Column type : QR Code

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3581]
- [x] Design
- [x] Implement
- [x] Tests

More details to come from @spaudanjo

**Comment by spaudanjo** [comment]
Thanks, @o1lab 
Code exploration started/in progress. 
I aim to share more details/ideas /questions till EOW. 

Outcome of first code exploration phase 😆 =>
<img width="591" alt="image" src="https://user-images.githubusercontent.com/249210/189725912-1b3f9480-6be8-46dd-97c1-4467aba41d6c.png">

**Comment by andreas83** [comment]
this is exactly what a client asked for today, keep up the good work.
