### ISSUE TITLE
🐛 Bug: Project info not copied to clipboard - where to find needed info?

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#3598]
Node: v12.22.6
Arch: x64
Platform: linux (QNAP 5.0.0.2131)
Docker: true
Database: mysql2 (MariaDB10.5)
ProjectOnRootDB: true
RootDB: mysql2 (MariaDB 10.5)
PackageVersion: 0.96.4

**Steps To Reproduce**

1. Click on NocoDB-Logo on top left
2. Select 'Copy Project Info' => you will see 'Copied to clipboard'
3. Try to insert the clip
4. In my case i will get whatever is stored in clipboard before - but not the Project Info
5. I have to idea how to find all the needed data for Project Info ?!

**Expected Behavior**

The clipboard should be usable

**Screen Record**

https://user-images.githubusercontent.com/20600342/189838317-b7adc430-c02d-416d-940d-294af4f30fc0.mp4

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by o1lab** [comment]
Which browser is it ?

**Comment by WeT-Klb** [comment]
I tried Microsoft Edge Version 105.0.1343.33 and Google Chrome Version 105.0.5195.54

 

 

 

Von: navi ***@***.*** 
Gesendet: Dienstag, 13. September 2022 09:34
An: nocodb/nocodb
Cc: Werner; Author
Betreff: Re: [nocodb/nocodb] Project info not copied to clipboard - where to find needed info? (Issue #3598)

 

Which browser is it ?

**Comment by WeT-Klb** [comment]
Only to mention - 0.97.0 still can´t copy the project information to clipboard.

**Comment by o1lab** [comment]
It works in chrome on mac :| 

We will look into this.

@mertmit : is this fine on linux ?

**Comment by o1lab** [comment]
In safari, we get an error at first! Then trying again it copies. Weird. @pranavxc 

@WeT-Klb : does trying again - will it copy ? do you seen any error

**Comment by WeT-Klb** [comment]
I can´t see any errors - NocoDB shows "Copy to clipboard"-message - but no chance to insert the infprmation somewhere.
I tried to insert in Word, Editor and Wordpad. No matter how often i try.
No difference here if i use Chrome or Edge.

**Comment by mertmit** [comment]
Works for linux - chrome as well

**Comment by lukurde** [comment]
"Copy Project Info" and "Copy Auth Token" both do not work.

Everything up-to-date, NocoDB (latest docker nocodb-postgres), version: "0.97.0"

Windows + Firefox = do not work
Windows + Firefox= do not work
Windows + Chrome = do not work
Linux + Firefox = do not work

**Comment by lukurde** [comment]
Update: **it works** if app is reverse-proxied (nginx in this case) **with TLS**. With regular unencrypted HTTP copying doesn't work (both directly or through nginx) which makes sense in case of the Auth Token. The user feedback could be better thought, the popup says that the copying succeeded.

**Comment by dstala** [comment]
fix will be available in https://github.com/nocodb/nocodb/milestone/24
