### ISSUE TITLE
Photos in gallery view are "squeezed"

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#3599]
**Please enter the following details**
Node: v12.22.6
Arch: x64
Platform: linux (QNAP 5.0.0.2131)
Docker: true
Database: mysql2 (MariaDB10.5)
ProjectOnRootDB: true
RootDB: mysql2 (MariaDB 10.5)
PackageVersion: 0.96.4```

**Steps To Reproduce**

1. Go to gallery view
2. The picture on top of the column has more length than height
3. So all pictures looks quite distorted

**Expected Behavior**

The pictures should be square

**Screenshots**

![Nocodb](https://user-images.githubusercontent.com/20600342/189836948-8af3cdc3-d5ff-4267-82f4-ff72fd2df88e.jpg)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by WeT-Klb** [comment]
Hi,

with 0.97.0 still the picture looks not right. i suggest to make the pics square - just like in the table itself.
Otherwise always something will be cut off the pic.
Before 0.96.0 i think it was quite perfect - but only my opinion.

![Gallery View neu](https://user-images.githubusercontent.com/20600342/191691297-7fd76142-ad56-470e-86e1-0905b7d4fe96.jpg)

**Comment by o1lab** [comment]
Ah good.
