### ISSUE TITLE
[i18n] Language support extension- <ar>

### ISSUE THREAD

**Issue by abosaudtech** [nocodb/nocodb#3607]
# i18n translation request

**Please enter the following details**

1. Select applicalbe
- [ ] **New language support request**
- [*] **Existing language translation corrections request** 
Verify if language support already exists in the NocoDB i18n master spreadsheet [here](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172)

2. Associated language code (pick from [here](https://developers.google.com/admin-sdk/directory/v1/languages)): 

3. Google spreadsheet
- Procedure to share google spreadsheet can be found [here](https://support.google.com/docs/answer/2494822?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cshare-a-file-publicly) 
  - When requested, select public sharable link. 
- Alternatively, you can download & attach a spreadsheet here along with the issue as well. 
- [ ] **Attached**
- [ ] **Shared link**:

4. Summary of the changes made
- You can highlight modified items in the Spreadsheet attached/shared, to help us quickly identify changeset

5. Any specific message to be conveyed to moderators?
- Help us simplify the process if you find something hard about it

**Comment by bcakmakoglu** [comment]
@abosaudtech If you check the [Spreadsheet](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172) you can see that `ar` is already supported, or are you missing a specific translation / want to make a correction? :)

**Comment by abosaudtech** [comment]
I want to say that ar language was accepted by you but i cant see it in
last version.

**Comment by bcakmakoglu** [comment]
Ah, I see. That issue should be resolved with the next patch, I believe.

**Comment by dstala** [comment]
@abosaudtech We are now switching over to Crowdin portal to ease discussions & contributions around i18n support
You can find project details [here](https://crowdin.com/project/nocodb)
