### ISSUE TITLE
Using nocodb with ORM

### ISSUE THREAD

**Issue by ZiggerZZ** [nocodb/nocodb#361]
I connected nocodb to a Postegres DB with an ORM (https://www.prisma.io/) on top of it. Since nocodb created a `nc_evolutions` table, Prisma was not happy. Is there a way to use nocodb with ORM such as Prisma or Django?

**Comment by o1lab** [comment]
What was the issue ? How was nc_evolutions affecting

**Comment by ZiggerZZ** [comment]
When ORM is used, it is supposed to have complete control on tables. All tables must be create through this ORM.
Consequently, since `nc_evolutions` was not created by Prisma, Prisma "broke" and I can't use it anymore unless I delete `nc_evolutions`.

**Comment by o1lab** [comment]
Weird, I don't think will Django would break if that's the case. 

I guess, this has to be fixed by prisma team :)

**Comment by dismantl** [comment]
IMO it would be ideal to not have NocoDB trying to write tables to connected databases, especially when those databases are read-only (i.e. when a user with SELECT-only permissions is used for the database connection). See #318 for more on that motivation.

**Comment by ZiggerZZ** [comment]
I overcame this problem by creating a Postgres user `nocodb` with limited rights:
```sql
-- Postgres
CREATE USER nocodb WITH ENCRYPTED PASSWORD 'securepassword';
GRANT CONNECT ON DATABASE "my-db" TO nocodb;
GRANT USAGE ON SCHEMA public TO nocodb;
ALTER USER nocodb CREATEDB;
```

But I agree that what @dismantl suggests, would have been more flexible.

**Comment by hongkongkiwi** [comment]
Follow up on this cause I want to do the same thing. How has your experience been using this together with Prisma?

**Comment by ZiggerZZ** [comment]
@hongkongkiwi see my response above. Created a user with limited rights helps it because it doesn’t see irrelevant tables.

**Comment by hongkongkiwi** [comment]
> @hongkongkiwi see my response above. Created a user with limited rights helps it because it doesn’t see irrelevant tables.

Thank you very much for providing that. I'm implementing it now

How has approach worked for you in the past few years? Any problems with these two working together or is it seamless using the above grants?

**Comment by ZiggerZZ** [comment]
I don’t use any of these tools anymore, but at the time it was working fine.
