### ISSUE TITLE
Sorting won't work correctly in column type SingleLineText with number-based text

### ISSUE THREAD

**Issue by pedrorito** [nocodb/nocodb#3615]
```
NocoDB used as docker : true
NocoDB version : 0.96.4
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
OS on which NocoDB is running : Linux
```

**Steps To Reproduce**

In a certain table, using column type SingleLineText, with number-based description (like IP addresses) it doesn't sort properly.
For the example of IP addresses, it will behave like 192.168.1.1, 192.168.1.100, 192.168.1.101, 192.168.1.2, 192.168.1.21...

**Expected Behavior**

In Airtable it would sort normally as 192.168.1.1, 192.168.1.2,  192.168.1.21, 192.168.1.100, 192.168.1.101...
Check screenshots attached for comparison.

**Screenshots**

NocoDB:
![nocodb](https://user-images.githubusercontent.com/26152255/190011219-fcaf1c2e-5702-4cb6-b22e-a839df52f750.jpg)

Airtable:
![airtable](https://user-images.githubusercontent.com/26152255/190011247-3967a650-3231-4c76-a70a-87bf31526d28.jpg)

**Comment by piromsurang** [comment]
Could I work on this issue?

**Comment by bcakmakoglu** [comment]
@piromsurang Sure, feel free to open a PR 👍

**Comment by o1lab** [comment]
@mateonunez wanted to take this up last week when I spoke to - Mateo you are on this ? :D

**Comment by mateonunez** [comment]
@o1lab yep, I'm evaluating the best way to implement this sort at the lowest APIs level. But feel free @piromsurang to work on this, we can share the final solution or review it together. 👀

**Comment by piromsurang** [comment]
@mateonunez I have raised PR [here](https://github.com/nocodb/nocodb/pull/3926). What I did here is to add another order by statement to order by the length of text before the original order by statement. Any suggestions? 😀

**Comment by o1lab** [comment]
From the discussion in the [PR](https://github.com/nocodb/nocodb/pull/3926) - we've was decided not to go for a fix.
