### ISSUE TITLE
Dockerfile typo

### ISSUE THREAD

**Issue by shin1103** [nocodb/nocodb#3619]
In `packages/nocodb/Dockerfile`,
I think the commented out line L39 should be '/usr/src/appEntry/start.sh' instead of '/usr/src/appEntry/start.s'.

**Comment by wingkwong** [comment]
L39 looks fine to me.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/35857179/190053910-9afdd2ad-6955-4d76-96c8-fb0fbae49e84.png">

**Comment by shin1103** [comment]
Sorry, L29 not L39
![Uploading スクリーンショット 2022-09-14 12.48.23.png…]()

**Comment by wingkwong** [comment]
Yes. but that line is not in use though.

**Comment by shin1103** [comment]
Yes, it's not a typo if that's how the nocodb team perceives it.
I used L29 uncommented out because I do not use Litestream. Therefore, it was useful to me.

**Comment by wingkwong** [comment]
@shin1103 updated.
