### ISSUE TITLE
🐛 Bug: Opening Editor component throws errors in console

### ISSUE THREAD

**Issue by bcakmakoglu** [nocodb/nocodb#3631]
# Problem Description

- Opening the Webhooks tab (which opens an Editor including Monacco) causes errors in the console
- The Editor still seems to work fine, regardless of errors thrown

## Screenshot
<img width="433" alt="image" src="https://user-images.githubusercontent.com/78412429/190153601-d415f4f9-5e7c-4836-87e0-524921ab9f7e.png">

**Comment by wingkwong** [comment]
Couldn't reproduce in develop. Can you double confirm it?

**Comment by bcakmakoglu** [comment]
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/78412429/195285264-1eb3710d-4b7d-4586-8d1c-e2b668ea0ddc.png">

Still happens.

1. Open Webhook Drawer
2. Add a new Webhook (which opens Monacco Editor)
3. Open console and see a couple errors

**Comment by o1lab** [comment]
No errors found now. Good to be closed.
