### ISSUE TITLE
Filtering empty nested column not possible via API

### ISSUE THREAD

**Issue by pavvel11** [nocodb/nocodb#3640]
```
Node: **v14.20.0**
Arch: **x64**
Platform: **freebsd**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.96.4**
```

**Steps To Reproduce**
1. Create two tables.
2. Add the "Has Many" relation between two tables (Link To Another Record column)
3. Add some records to both tables. At least two records in the child table - one related to parent and one with null in the foreign key column.
4. Use **API** to get records from parent table which have empty relation.

It is not possible to filter records without relation using the parameter where.
I tried `where=(child_id,is,null)`, `where=(child_id,is,empty)`, `where=(child_id,empty)`.
There is always an wrong response (empty or all records).

**Expected Behavior**
Users should be able to filter out records from the parent table without relation via both UI and API.

UI was fixed #2535 and is working correctly but it is still impossible to use filters via API.

**Comment by o1lab** [comment]
Click -> APIs & Support (bottom left) > Swagger API docs of your project.

Look up the table - there will be nested[table][where]

Probably you need that.

**Comment by pavvel11** [comment]
I tried. It does not work or I'm doing something completely wrong.

**Comment by pranavxc** [comment]
The `child_id` column is part of the child table and not in the parent table so the filter will get ignored. So in your scenario you can do the following to achieve the result.

1. Create a rollup count column in the parent table
2. Use the rollup column to filter the result

Sample `where=(rollupColName,eq,0)` or `where=(rollupColName,lt,1)`

**Comment by pavvel11** [comment]
No, the `child_id` is the part of the parent table as a foreign key.
In the UI this kind of filtering is working (examples can be found in #2535) so I think there is no reason for which it cannot work via API.
Additionally filtering by specific value is working, only `is empty` clause is not.

**Comment by pranavxc** [comment]
@pavvel11 : You can use `blank` or `notblank` operator with `where` query parameter.

Example:

```
where=(LtarColTitle,blank)
where=(LtarColTitle,notblank)
where=(LtarColTitle,is,blank)
where=(LtarColTitle,is,notblank)
```
