### ISSUE TITLE
[Bug]: Icons in Gallery View Drawer are tiny

### ISSUE THREAD

**Issue by bcakmakoglu** [nocodb/nocodb#3647]
# Problem Description

* When clicking an item in the Gallery view the icons of the Drawer in the top right corner are tiny

# Screenshot

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/78412429/190270209-152fcdef-b2a8-42c3-8386-1dd8259487b0.png">

**Comment by chetanverma16** [comment]
Hey @bcakmakoglu  @pranavxc,
I have tried fixing this bug on this PR - https://github.com/nocodb/nocodb/pull/3809
can you please have a look?
thanks
