### ISSUE TITLE
Creating new tags for select and multi-select columns via API [feature request]

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#3661]
If POST request contains new tags targeting select or multi-select values, those text values are set and returned in response but no tags are created and shown in NocoDB UI.

<details> 
  <summary>POST request+response screenshoot </summary>
   
![Screenshot_20220915_121607](https://user-images.githubusercontent.com/61871501/190367966-7690e32c-f24e-48c2-ac24-3d14000beb40.jpg)

</details>

<details> 
  <summary> gif showing result in UI</summary>
   
![Peek 2022-09-15 12-27](https://user-images.githubusercontent.com/61871501/190368597-5eb6708f-d0f8-41e7-a562-bd6c67ebefba.gif)

   
</details>

Feels related to #3512 

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.96.4**

**Comment by o1lab** [comment]
You would have to create new tags and then insert it. We automatically create tags for you - although this is a nice feature when doing it from the UI :)

**Comment by RawmanGrey** [comment]
> You would have to create new tags and then insert it. We WONT automatically create tags for you - although this is a nice feature when doing it from the UI :)

Yeah, fair enough -- let it be a feature request : )

Though, at least some non-handwork way to create plenty of tags has to be... I made this issue mostly to comment on mentioned csv-import request.

**Comment by o1lab** [comment]
Thank you :)

Will move this to discussion.
