### ISSUE TITLE
Unable to create `select` column

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3676]
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.96.4**

```
ALTER TABLE `nc_bseu__Sheet1` ADD COLUMN `title5` enum('a','b',2) NULL; - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2) NULL' at line 3
```

**Comment by dstala** [comment]
- Issue noticed in both single & multi-select
- Issue observed with MySQL only

**Comment by mertmit** [comment]
This caused by useColumnCreateStore changes, will fix it (dtxs appended for every column type)
