### ISSUE TITLE
External MS SQL Server bug on creating foreign keys

### ISSUE THREAD

**Issue by Amonlol** [nocodb/nocodb#3681]
```
NocoDB used as docker : true
NocoDB version : latest
Database used in NC_DB URL  : MS SQL
Project was created by clicking : New Project by connecting to external database
Database on which spreadsheet is created : MS SQL and sqlite3 (tried on both)
OS on which NocoDB is running : Ubuntu 20.04
Node.js version if running as node : -
Database version : SQL Server Developer (64 bit) 16.0.900.3
```

**Steps To Reproduce**

1. Create 2 tables
2. Add some data rows to one of them
3. Add column type "LinkToAnotherRecord" to another table, which links to the first table
4. Add new row with link field
5. Table, which is being linked to, suddenly becomes empty

**Expected Behavior**

Table should still show all data in it. Tried the same thing in PostgreSQL and table shows all data no problem. Also tried to create DB, tables and links (FK + Constraints) via DBMS, still got the same result.

**Screenshots**

![image](https://user-images.githubusercontent.com/72953500/190645723-0749735c-e016-4453-bca2-e407c1e49152.png)
![image](https://user-images.githubusercontent.com/72953500/190646855-335f3315-64c2-4de1-96fb-57a3985d1d55.png)
![image](https://user-images.githubusercontent.com/72953500/190646017-6b48c1f1-33de-4e87-afd5-00e0ad5c8fff.png)
![image](https://user-images.githubusercontent.com/72953500/190646067-6986c232-b649-40c2-ba38-82c54bb82357.png)
![image](https://user-images.githubusercontent.com/72953500/190646100-f1ffbbf4-0893-451f-9e81-34786091378a.png)

However, if link becomes Many-to-many, then suddendly everything works just fine
![image](https://user-images.githubusercontent.com/72953500/190647222-9a3b1801-bd5c-4602-a1a0-f760a0e8b805.png)

**Comment by mertmit** [comment]
Thank you for reporting.
Confirmed, this is reproducible for MSSQL I will look into this

## Some debug info
Error raised by extractRawQueryAndExec:
`RequestError: select * from (select [Sheet1].[id] as [Id], [Sheet1].[title] as [Title], [Sheet1].[created_at] as [CreatedAt], [Sheet1].[updated_at] as [UpdatedAt] from [dbo].[Sheet1] order by [id] asc) __nc_alias - The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.`
