### ISSUE TITLE
[Feature] Webhooks only for specific columns

### ISSUE THREAD

**Issue by Megamezzomixer** [nocodb/nocodb#3693]
**Need for this feature**
To scale Webhooks accordingly. if only one part in a row is changed, I'd want a notification of only this specific value changing instead of all webhooks that also turn out positive to fire.

**Is your feature request related to a problem? Please describe.**
Whenever an update on a row is made, I am getting a line of text into a discord channel.
The main problem is, that I get not only for example a Name change, but I also get the text lines of other webhooks also fired during "On Update" that are not important, because they were not changed.

**Describe the solution you'd like**
I would like to have a possibility to choose on which columns a webhook has to listen to in order to tailor exact messages in an event of a change of a value in that specific column.

**Comment by dstala** [comment]
to be tracked in https://github.com/nocodb/nocodb/issues/4130
