### ISSUE TITLE
Save a new row when only all required fields are entered

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3696]
Please [see here](https://github.com/nocodb/nocodb/discussions/3695#discussioncomment-3671877).

**Comment by PrasanthKumar77** [comment]
can we trigger webhook also when all values are rows are added? currently its being triggered when one column value is added also

**Comment by dstala** [comment]
> can we trigger webhook also when all values are rows are added? currently its being triggered when one column value is added also

@PrasanthKumar77 : You can use `expand row` option to update record. This will trigger webhook only when you click `save` button. On similar lines, you can use `Add new row` button in right top tool bar to insert record. This triggers webhook only on clicking `Save` button. Hope this helps.
