### ISSUE TITLE
NC_PUBLIC_URL not honored in invite email

### ISSUE THREAD

**Issue by Braincoke** [nocodb/nocodb#370]
**Please enter the following details**
Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.11.2**

**Steps To Reproduce**

1. Configure the env variable `NC_PUBLIC_URL`. Example : "https://my-site.com/database"
2. Invite someone by email
3. Configured URL is not honored. Link is something like "https://my-site.com/dashboard" instead of "https://my-site.com/database/dashboard"

**Expected behavior**
The invite URL should use the `NC_PUBLIC_URL`.

**Comment by pranavxc** [comment]
Fixed in `0.11.4`
