### ISSUE TITLE
Table view is empty on initial render

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#3702]
Node: **v16.15.1**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.96.4**

**Steps To Reproduce**

1. Open a table.
2. Refresh the page
3. Table view will be empty

**Screenshots**

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/35809690/190991899-914591e1-663c-4c8c-88d3-a554f3a3743b.png">

**Comment by dstala** [comment]
@mustafapc19 
Try if you can reproduce still after cleanup cache files
from packages/nc-gui, delete folders `.nuxt` and `node_modules/.vite`

Restart browser

**Comment by mustafapc19** [comment]
@dstala I have deleted `.nuxt`, `node_modules/.vite`, cleared local storage, cookies and also have restarted the browser but I can still observe this issue. Its happening 50% of the time I refresh the page.

**Comment by mustafapc19** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/35809690/191012723-c1adfd62-e96c-43d2-b10d-34e0d3811bc5.png">

Seems like state like `ActiveView` and `metas` is undefined
