### ISSUE TITLE
Full width icon is not hiding left nav-drawer

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3761]
- Clicking full width icon is only hiding right side nav-drawer and not the left side navdrawer.

**Comment by bcakmakoglu** [comment]
Title says it's not hiding left drawer, description says it's not hiding right drawer 😄

**Comment by o1lab** [comment]
Ah correct :D

**Comment by dstala** [comment]
@o1lab we couldn't reproduce. you can double check once & close
