### ISSUE TITLE
Cannot open after upgrading version

### ISSUE THREAD

**Issue by whyteserious** [nocodb/nocodb#3780]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
OldPackageVersion: **0.92.4**
NewPackageVersion: **0.97.0**
```

**Steps To Reproduce**
Replace Mirror File

**Screenshots**
500
Unknown variable dynamic import: ../lang/zh_CN.json

**Comment by whyteserious** [comment]
Rollback cannot be opened after upgrading.

Error: The migration directory is corrupt, the following files are missing: nc_019_add_meta_in_meta_tables
    at validateMigrationList (/usr/src/app/node_modules/knex/lib/migrate/Migrator.js:575:11)
    at Migrator.latest (/usr/src/app/node_modules/knex/lib/migrate/Migrator.js:70:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async s.metaInit (/usr/src/app/docker/main.js:2:535920)
    at async U.init (/usr/src/app/docker/main.js:2:3813)
    at async /usr/src/app/docker/main.js:2:576750

**Comment by o1lab** [comment]
You mean downgrading ?

**Comment by pranavxc** [comment]
It would be helpful if you could share the docker logs of the container with the image `0.97.0`.

**Comment by whyteserious** [comment]
[nocodb_upgrad0.97.0.txt](https://github.com/nocodb/nocodb/files/9640964/nocodb_upgrad0.97.0.txt)
[nocodb_downgrad0.92.4.txt](https://github.com/nocodb/nocodb/files/9640965/nocodb_downgrad0.92.4.txt)

**Comment by wingofsky** [comment]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/1725695/192503398-7b12bee2-c2f5-41b8-b2db-502f01c8c10b.png">

me too

**Comment by o1lab** [comment]
Can you please see if there is error in browser console and paste it here. That will be helpful.

**Comment by wingofsky** [comment]
> Can you please see if there is error in browser console and paste it here. That will be helpful.

![image](https://user-images.githubusercontent.com/1725695/192509408-849dc793-14b2-44a9-8f90-d7a7a08a0101.png)

![image](https://user-images.githubusercontent.com/1725695/192509909-7391f9cd-eab3-4995-96bd-c03f38d46f4c.png)

only this information

**Comment by bcakmakoglu** [comment]
@wingofsky Can you try clearing your localStorage?

**Comment by wingofsky** [comment]
> @wingofsky Can you try clearing your localStorage?

![image](https://user-images.githubusercontent.com/1725695/192510794-d927474d-db96-4162-9eac-a0ea091154ca.png)

After clearing the localStorage, can enter the English mode, and it can be displayed normally after switching the language

@whyteserious  [0.97.0]清一下本地缓存，让程序默认进英语模式，然后可以再切到中文可以用了

**Comment by wingofsky** [comment]
> @wingofsky Issue here is that the old CH files have renamed to zh-hans and zh-hant but in your localStorage it has saved the old language.
> 
> We will resolve this in the future without having to clear localStorage 😅
> 
> See #3819

Received, looking forward to helping others with this issue
