### ISSUE TITLE
[Feature] - Granular row and column filtering system

### ISSUE THREAD

**Issue by Bokitza** [nocodb/nocodb#3782]
**Need for this feature**
Granular permissions for different users by role or other metadata- today everyone can see every row. Let's say I want a role named "security manager", who can see only the "security" department in the "employees" database. I want him to edit and view, but now see the other people, not on his department.

This could be implemented by:

defining custom roles and defining the view for each role. 

Adding metadata to users (e.g: department), and making a conditional filter (filter by employee.department===user.department)

This can be done is SharePoint lists, and is a must for big organization who wants granular and dynamic permission systems.

**Comment by PrasanthKumar77** [comment]
hey i would like to know if this in your roadmap.

**Comment by devMls** [comment]
Me too 👍

**Comment by dstala** [comment]
To be tracked under

[🔦 Feature: Row / Column base permission, last edited by / updated by and audit log](https://github.com/nocodb/nocodb/issues/5075)
