### ISSUE TITLE
Import currency field

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3788]
### Discussed in https://github.com/nocodb/nocodb/discussions/3775

<div type='discussions-op-text'>

<sup>Originally posted by **MGW-SumathyV** September 23, 2022</sup>
Hi,

I am importing csv file having a currency field with $ value (for e.g $90). 
But the currency field is showing $0.00 in all the table rows instead of the actual value.
Can you please help in resolving this?

Thanks and Regards,
Sumathy Venugopal</div>

**Comment by asi309** [comment]
Assign me to this task please

**Comment by wingkwong** [comment]
The import looks fine in my local though. I was asking for clarification in the above discussion [post](https://github.com/nocodb/nocodb/discussions/3775).
