### ISSUE TITLE
🐛 Bug: Refresh token leads to logging out

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3792]
- to be investigated
- leads to a cors error

**Comment by bcakmakoglu** [comment]
This sort of configuration is invalid:

```js
cors: {
  origin: '*',
  allowedHeaders: ['xc-auth'],
  credentials: true,
},
```

[According to the MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials)

The [CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS) request was attempted with the credentials flag set, but the server is configured using the wildcard ("*") as the value of Access-Control-Allow-Origin, which doesn't allow the use of credentials.

**Comment by asi309** [comment]
Assign me to this task please

**Comment by o1lab** [comment]
Done, thank you
