### ISSUE TITLE
[Feature] Count items on a many-to-many column

### ISSUE THREAD

**Issue by masfaraud** [nocodb/nocodb#3800]
## Recommending Features

**Need for this feature**

When having two tables linked with a many-to-many relationship, it is impossible to count the number of items in a column
In this example, I would like to add a column that counts matchs won by each player.

![image](https://user-images.githubusercontent.com/14061753/192091981-c048aba4-8bae-4bb9-b25e-6669608af2a3.png)

I have read the doc about Rollup and how it works for one-to-many relationships: https://docs.nocodb.com/setup-and-usages/rollup

**Is your feature request related to a problem? Please describe.**
I think it is a missing feature, not related to a problem.

**Describe the solution you'd like**
Possible ways to implement:
* a formula keyword to count items in an attribute
* handle many-to-many relationships in Rollup

**Describe alternatives you've considered**
No alternative found

**Comment by o1lab** [comment]
Hey, count function for rollup is available for many to many relation.

**Comment by masfaraud** [comment]
Hi, 
It works but it asks for an attribute, and I want to have the number of items of the match won attributes, and not lokking one step further into the table
![image](https://user-images.githubusercontent.com/14061753/192093956-6b99f36b-bea9-48ea-abb1-bb33d625ae4f.png)

**Comment by dstala** [comment]
Rollup count specifies the information required. We understand, when counting - `Child column` is redundant. You can specify any column from child table, it should work though.

![Screenshot 2023-01-19 at 9 06 12 PM](https://user-images.githubusercontent.com/86527202/213485340-c6fa7ea9-15e7-4e49-bbdf-a80851b209e0.png)
