### ISSUE TITLE
🐛 Bug: Unknown variable dynamic import: ../lang/zh_CN.json

### ISSUE THREAD

**Issue by ly120ve980ly** [nocodb/nocodb#3812]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

After upgraded to 0.97.0, tips these words "Unknown variable dynamic import: ../lang/zh_CN.json"
<img width="683" alt="image" src="https://user-images.githubusercontent.com/7520794/192213747-39c337a3-5fcf-4fa7-b51f-03aaed52fdff.png">

### Desired Behavior

Normal to open

### Project Details

nocodb version: 0.97.0
use docker: true

**Comment by o1lab** [comment]
Could you please try hard refresh once ?

**Comment by ly120ve980ly** [comment]
> Could you please try hard refresh once ?

Thanks for your reminder，After I clean up the browser cache & cookies & localstorage，it works!
