### ISSUE TITLE
[Kanban] Delete record option in kanban view

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3833]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Kanban view doesn't have a delete record option; removing a record from the view requires us to visit Grid view

### Desired Behavior

Right-click context menu on kanban card to include the `delete record` option

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.97.0**

**Comment by wingkwong** [comment]
ccc8a04e4
