### ISSUE TITLE
[Kanban] Shared view shows empty page

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3839]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Share view option is enabled; accessing link shows an empty page
- Option to configure `download` during share view menu creation is not available

### Desired Behavior

- Shared kanban view
- Option to disable CSV download in shared view

### Project Details

In development

**Comment by wingkwong** [comment]
Empty page is fixed. Second one is under clarification.

**Comment by dstala** [comment]
observed when we have default value configured for the single-select column. retaining database behaviour.

**Comment by wingkwong** [comment]
@dstala the 2nd one is ready for review

**Comment by dstala** [comment]
- Shared view verified; 

Shared view when opened as tab displays `Add/Edit Stack`. Should be disabled
  
<img width="847" alt="Screenshot 2022-09-29 at 10 57 38 PM" src="https://user-images.githubusercontent.com/86527202/193101657-3759e694-ffde-443f-829c-edc4f4b45868.png">

**Comment by wingkwong** [comment]
Updated.

![image](https://user-images.githubusercontent.com/35857179/193170731-ce632e6b-f7ad-4953-b94d-794ceb15c18c.png)
