### ISSUE TITLE
Feature : Full import/export/backup feature? - docker nocodb

### ISSUE THREAD

**Issue by niksfirefly** [nocodb/nocodb#384]
I cant find option to FULL import/export/backup data in nocodb

there is none?

regards

**Comment by wingkwong** [comment]
You can import / export metadata under ``Project Metadata``. 

https://docs.nocodb.com/setup-and-usages/meta-management

**Comment by o1lab** [comment]
We allow full import and export of metadata. Exporting and importing entire data from database is beyond the scope of this project - for this there are tools like mysqldump or pgdump that can be used.

**Comment by xiamaz** [comment]
It seems import/export of metadata has been deprecated. Is there any replacement? Thanks!

**Comment by wingkwong** [comment]
@xiamaz For metadata, as o1lab said, you can create a database dump. Another way is that you can use NocoDB to connect your `NC_DB` and export the corresponding tables to csv.

**Comment by gagarine** [comment]
Having the capabilities of import/export of the data (so project) of a given user is mandatory by EU law no if you provide this as a cloud servcie?
So not a full export, but of a single project or all project I have access too. Having build in tools for that would facilitate compliance.
