### ISSUE TITLE
[Kanban] Padding observed in display for few columns

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3842]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Align all columns data to the left (if its easy work). 
  
![Screenshot 2022-09-29 at 9 48 43 AM](https://user-images.githubusercontent.com/86527202/192938291-81cd63ab-d029-4973-8b17-89d16ee833dc.png)

### Desired Behavior

Visual alignment

### Project Details

In development

**Comment by wingkwong** [comment]
[07f525b](https://github.com/nocodb/nocodb/commit/07f525b9003c5e5dd433cfdf88cc870c449d50f1)
