### ISSUE TITLE
[ExpandedForm] Click on attach-cell doesn't open attachment drag-drop modal in expanded row drawer

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3843]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Not verified in `develop`
- Drag-drop into text box in expanded row works
  

![Screenshot 2022-09-29 at 10 15 30 AM](https://user-images.githubusercontent.com/86527202/192956620-e786a173-55d6-4fda-8a76-849e737ae3d6.png)

### Desired Behavior

on click, open modal to accept attachments

### Project Details

In development

**Comment by wingkwong** [comment]
I'm using Chrome and it seems working fine.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/35857179/193026962-18ef1dcb-09ad-4047-bb25-b241940094aa.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/35857179/193026737-e2c6ab35-6679-4bbc-ba93-54f1e1bc59ad.png">

**Comment by dstala** [comment]
@wingkwong drop here option is fine. Click on `Add file(s)` doesn't open modal to select files.

**Comment by wingkwong** [comment]
@dstala I've had such issue before not only in nocodb but other websites. Restarting the browser could solve the problem. Not sure what the root cause is.

**Comment by dstala** [comment]
worked when I tried now. closing issue; we can investigate if its consistently reproducible
