### ISSUE TITLE
Wrong URL for the attachments

### ISSUE THREAD

**Issue by s-praveen-kumar** [nocodb/nocodb#385]
Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.11.2**

**Background**
I newly installed nocodb through docker on my VPS deployed behind an Nginx Proxy as a subdir.
### Configuration used:
```
location /noco/ {
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $http_host/noco;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
		proxy_pass http://noco:8080/;
	}

	location /nc {
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
		proxy_pass http://noco:8080;
	}
```
I am successfully able to access the Nocodb instance from `sub.domain.tld/noco/dashboard/`

**The issue**
Everything works fine (atleast as far as I have explored). I was trying to upload attachments through an attachment field configured as text in database. The upload is success. Monitoring the HTTP requests, I can see the POST request for the attachment is successful with the following response.
```
{
"url":"sub.domain.tld/noco/dl/test_project_-Nh2/db/C_P98Y.png",
"title":"fav_32.png",
"mimetype":"image/png",
"size":1776
}
```
But after uploading I cannot see the attachment. Checking the logs I see the GET request for the attachment points to the wrong URL and hence returning 404.
How is it supposed to be : `sub.domain.tld/noco/dl/test_project_-Nh2/db/C_P98Y.png`
How it is : `sub.domain.tld/noco/dashboard/sub.domain.tld/noco/dl/test_project_-Nh2/db/C_P98Y.png`

Is this happening because of a bug or is something wrong with my configuration? 
And thanks for this wonderful project.

**Comment by pranavxc** [comment]
Are you setting `NC_PUBLIC_URL` environment value?

**Comment by s-praveen-kumar** [comment]
@pranavxc Kudos. That was the issue. I had been using `sub.domain.tld/noco`. Changed to `https://sub.domain.tld/noco` Now attachment works. Thank you.
