### ISSUE TITLE
[Cypress] Add tests for Single-select & Multi-select data type

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3858]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

No CY tests currently

### Desired Behavior

Overview

- [x] Create column
  - [x] Add record
  - [x] Update record
  - [x] Clear record
- [x] Add new options
  - [x] Verify availability of option in grid cell dropdown
- [x] Rename options
  - [x] Ensure stored values in the cell are updated 
  - [x] Verify changes in dropdown
- [ ] Reorder options
  - [ ] Verify order of options in grid 
- [x] Remove options
  - [x] Verify updates to existing cells
  - [x] Verify options is removed from dropdown for cell 
- [x] Delete column

We will have to carry out additional activities on the grid validation on the grid view to ensure changes are applied

### Project Details

In development

**Comment by bcakmakoglu** [comment]
FYI
When I add a multi select field and try to update it I get this error:
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/78412429/193944135-ab5cfd98-cfa6-4855-b6bc-06a7d8260576.png">

**Comment by o1lab** [comment]
@mertmit

**Comment by bcakmakoglu** [comment]
Seems to be some inconsistency with the table tbh because no operations work on it.
All the other tables seem to work fine though, strange.

**Comment by o1lab** [comment]
Probably it's deleted at dB level and it's only because it exists at meta level

**Comment by o1lab** [comment]
Not relevant now with us moving to Playwright
