### ISSUE TITLE
🔦 Feature: Need missing features from Airtable for Form View 

### ISSUE THREAD

**Issue by folk-connect** [nocodb/nocodb#3861]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Need missing features from Airtable for Form View
Some features which I desperately want are:
Show / hide a question based on answer of previous question (Conditional Questions)
Filter out options list for Select & Link to Other Table
A multi select "Link to Other Table" field should be able to link multiple values in the form as well
A prefill option and readonly question (Not present in Airtable) is also on my wishlist -- A feature request is already there for this
Without these features, NocoDB forms are not much configurable to me

If it is there on roadmap, please let me know. If it is something which you will not be taking up in near future, I will try to develop a custom solution for myself (outside of NocoDB)

### Suggested Solution

Taking implementation design from Airtable should be sufficient to develop for the usecase. If you need screenshots from Airtable, I can add those

**Comment by folk-connect** [comment]
@o1lab Is it on roadmap or any plans to take up in near future ? Accordingly I'll decide on migration from Airtable to NocoDB

Thanks

**Comment by dstala** [comment]
To be tracked under 
[🔦 Feature: Form View fields based on conditional logic](https://github.com/nocodb/nocodb/issues/4404)
