### ISSUE TITLE
Performance: Page not responding when uploading high no of rows using csv 

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3866]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create a new project
2. create a table with around 4 columns
3. upload a csv with rows around 30k
4. try to upload the same csv 2 or 3 times in same table if you didnt get the dialog box on first try.
5. chrome shown page is not responding dialog box

### Desired Behavior

upload is working sometimes. but i am getting the page not responding multiple times.
i didnt face any issue in 0.92.3 version

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.97.0**

### Attachements

![Screenshot from 2022-09-30 19-04-13](https://user-images.githubusercontent.com/78995399/193281322-46958bbc-01d1-4611-90f9-f5357f60f3bd.png)

**Comment by Gabe-Levin** [comment]
I am having the same issue. Sometimes it resolves after 15 min, sometimes not

**Comment by PrasanthKumar77** [comment]
hi @o1lab, may i know if this is currently in your roadmap?
