### ISSUE TITLE
🐛 Bug: Cannot restrict users from creating projects

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3867]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Invite a new user to project with viewer access
2. join with invited user link. 
3. create a new project with new user account.

### Desired Behavior

this seems to be fixed as posted [here](https://github.com/nocodb/nocodb/issues/793). but i am still facing the issue

only super admin can give permissions for users to create projects instead of individual project owners

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.97.0**

**Comment by PrasanthKumar77** [comment]
hi @o1lab, may i know if this is currently in your roadmap?

**Comment by dstala** [comment]
@PrasanthKumar77 this issue was not observed in latest release. Please re-open this issue if you observe anomalies.
PackageVersion: **0.101.0-beta.0**
