### ISSUE TITLE
🔦 Feature: Trigger selected webhooks for selected rows manually

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3868]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

i have a table with lot of rows. among them i want to select a few rows and send those rows data to some of the webhooks since i want to integrate that data in another service

### Suggested Solution

when multiple rows are selected there should be another option indicating `trigger webhooks` and on clicking it i should have option to trigger selected webhooks or all webhooks.

### Additional Context

since we can already trigger the webhook when a row is inserted/updated/deleted we cannot manually trigger the webhooks with selected rows.
when huge no of rows are uploaded using csv, i would like to send them manually since they wont trigger webhooks

**Comment by PrasanthKumar77** [comment]
hi @o1lab, may i know if this is currently in your roadmap?

**Comment by dstala** [comment]
Button field with "Run Webhook" is now supported
