### ISSUE TITLE
🔦 Feature: Send what changed in webhook data when update action is triggered

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3869]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

when webhook is triggered on updating the value of a row we cannot identify which column is changed and what is the previous value.

### Suggested Solution

should be able to identify what data is changed on seeing the webhook respone data.
webhook should trigger only when all columns are updated. currently it is triggering for change in each column. may be we can provide a option to bulk edit all columns of a row and then trigger webhook once when clicked on update button

**Comment by PrasanthKumar77** [comment]
hi @o1lab, may i know if this is currently in your roadmap?

**Comment by djmaze** [comment]
For me it would already be useful to to know _which field was changed_ in the last update.

Or just make it possible to add a condition _on change_ of a field. So that it will not be triggered again when another field is changed in the same record.

**Comment by PrasanthKumar77** [comment]
Hi @o1lab , May i know if this is in your roadmap for future releases?

**Comment by dstala** [comment]
@PrasanthKumar77 @djmaze Webhook update trigger now sends complete record before and after modification; please check if this caters to your needs. reopen this issue if you need more support on this.

**Comment by djmaze** [comment]
@dstala  Thanks for the improvements, but unfortunately this still does not fulfill my needs.

It is neither possible to filter on the old vs. new value in the condition. Nor can we differentiate if a field was changed inside the body template since the handlebars template is very restrictive and does not allow for really useful `if` conditions here.

**Comment by djmaze** [comment]
But I guess at least I can now implement a custom webhook proxy which can see the old vs new data and decide if a notification should be triggered. So, some additional work, but that should not be too hard to do.
