### ISSUE TITLE
🔦 Feature: Need to show projects to user to which he was invited or has access only

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3871]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

when i invite  a user to project i want him to see projects to which was invited or has access only. currently all projects are shown and on clicking it 403 error message is thrown which is not beautiful.

### Suggested Solution

For user show projects to which he has access or invited instead of all projects

**Comment by PrasanthKumar77** [comment]
hi may i know if this is currently in your roadmap?

**Comment by PrasanthKumar77** [comment]
Hi @o1lab, Any plans on including this in your roadmap for future releases?

**Comment by dstala** [comment]
works this way as seen in 0.111.0
