### ISSUE TITLE
🔦 Feature: Need option to add validation to each column before values are added

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3872]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

i would like to have a validation feature for each column. i have usecases where
1.  i want to have a column with validation of max length 10 and min length 2
2. i want to have date column in particular format only
3. i want age should be only greater than some value

### Suggested Solution

provide a option to add validations for each column. depending on the field type and custom regex should be possible.
the validations should work when adding data through api or bulk inserts like csv updload

**Comment by PrasanthKumar77** [comment]
hi @o1lab, may i know if this is currently in your roadmap?

**Comment by PrasanthKumar77** [comment]
Hi @o1lab , May i know if this is in your roadmap for future releases? we want to enforce unique values in a particular column before adding/bulk adding rows along with above mentioned validations.

**Comment by cons-barathan** [comment]
Hi @o1lab , Is it present in roadmap?
We are expecting, 
1. We need to be able to add Custom Validation for Columns similar to any normal SQL database Check Constraints.
2. If User input any error in the data, then it should highlighted to user mentioned what is the issue before update.
Thanks!

**Comment by dstala** [comment]
We plan to introduce this feature for form based input to start with (a simple range validation mechanism for various types). And depending on the use case, we might consider expanding it to other input mechanisms.

**Comment by dstala** [comment]
form based input validation is supported now in nocodb-cloud.
