### ISSUE TITLE
🐛 Bug: Filtering with equal operator is not working as expected

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3874]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create a new project and create table
2. add rows around 10k with duplicate values
3. apply filter on a column with equal to operator the no of rows matching are not the actual count. i am getting the exact count when like operator is used but it may match other unwanted rows also

### Desired Behavior

when applying a equal to operator all the matching rows should be matched instead of some rows

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.97.0**

**Comment by wingkwong** [comment]
Can you provide a testing csv, the column name and filter value for reproducing the issue?

**Comment by dstala** [comment]
@PrasanthKumar77 - could you help us with a sample CSV to test with?

**Comment by wingkwong** [comment]
Closing - no further response from user.
