### ISSUE TITLE
🔦 Feature: Env var support to not show app creds in UI

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3875]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

i want to use certain apps like email and s3 but when i set the required creds using env vars the apps are picking them but the sensitive creds are shown in UI. i want to see only the non-sensitive creds in UI like username and port etc...

### Suggested Solution

provide a env var to hide sensitive creds like password etc.. for all apps in UI

**Comment by PrasanthKumar77** [comment]
hi may i know if this is currently in your roadmap?

**Comment by dstala** [comment]
App Store & Credentials are now accessible only by Super admin.
