### ISSUE TITLE
🔦 Feature: Copy and and paste a linked record from one cell to another

### ISSUE THREAD

**Issue by 684efs3** [nocodb/nocodb#3878]
### Please confirm if feature request does NOT exists already ?

- [x] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have a table of Countries. I have another table of Continents. In Countries, I have a column called "Title," which has the name of a country, and a linked record called "Continent" which links to the table Continents. The table looks like below. I have linked the first row, United States, with the continent North America. I would like to copy and paste this link into Canada. Right now, I have to go to Canada, click the plus (+) sign, and select North America. If I can copy and paste the link from another cell, this would be significantly faster.

Country table 
| Title | Continent (linked record)|
|-|-|
|United States| North America|
|Canada| + |

### Suggested Solution

Copy a cell with a linked record, and paste that into another cell.

**Comment by wingkwong** [comment]
Copy and Paste for BelongTo column is introduced in #4514

**Comment by dtinth** [comment]
I tried copying a BelongsTo column, unfortunately it seems to no longer works. It says: **Unsupported conversion for LinkToAnotherRecord**

<img width="507" alt="image" src="https://github.com/nocodb/nocodb/assets/193136/054882bf-68ad-4540-889a-8ae2d04310d5">

**Comment by dstala** [comment]
Copy paste on BT is broken.
Copy paste on MM - we have added to our roadmap. Discussing if this feature would make sense for HM
