### ISSUE TITLE
M2M lenked subtable column adding

### ISSUE THREAD

**Issue by Vladimir-Va** [nocodb/nocodb#388]
NocoDB used as docker : true
NocoDB version : 0.11.4
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : linux
Node.js version if running as node : container
Database version : MariaDB10

**Steps To Reproduce**
Go to m2m value, right click, select m2m_autocreated_table, add column, reload table tabs, tables can't load

**Console log**
9c25114.js:2 TypeError: Cannot read property '_cn' of undefined
    at e4574a1.js:2
    at Array.reduce (<anonymous>)
    at f.hasMany (e4574a1.js:2)
    at Cn.get (9c25114.js:2)
    at Cn.evaluate (9c25114.js:2)
    at f.hasMany (9c25114.js:2)
    at f.<anonymous> (e4574a1.js:2)
    at f.t._render (9c25114.js:2)
    at f.r (9c25114.js:2)
    at Cn.get (9c25114.js:2)
re @ 9c25114.js:2
/nc/noco_test_1_YtiM/api/v1/test3?limit=25&offset=0&where=&sort=&hm=&bt=&mm=test2&mfields1=title,id:1 Failed to load resource: the server responded with a status of 400 ()
/nc/noco_test_1YtiM/api/v1/test3/count?where=:1 Failed to load resource: the server responded with a status of 400 ()
e4574a1.js:2 Error: Request failed with status code 400
    at t.exports (9c25114.js:2)
    at t.exports (9c25114.js:2)
    at XMLHttpRequest..onreadystatechange (9c25114.js:2)

**Comment by pranavxc** [comment]
Now you can enable listing M2M table by enabling 

![image](https://user-images.githubusercontent.com/61551451/127503719-7d768f83-0e5a-4d82-89e0-03b93bc6356a.png)

After enabling the option you can open and modify the M2M tables.

---


> Note : We strongly discourage modifying M2M tables since it may break the many to many realtion.
