### ISSUE TITLE
🐛 Bug: text field is populated as datetime field when table is created from import csv

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3889]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create a new project
2. click on create table with import from csv
3. upload csv with text field
4. click on import

### Desired Behavior

there were 2 issues here
1. text field is recognised as datetime field when imported
2. even though i changed it to single text and clicked on import it still populated random datetime values when creating table instead of actual data

need to check if this false auto recognization of column is happening for other fields also

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.97.0**

### Attachements

![Screenshot from 2022-10-01 12-43-08](https://user-images.githubusercontent.com/78995399/193397714-66682f08-7d99-4ed3-b69d-d9efd9130b2c.png)
![Screenshot from 2022-10-01 12-38-04](https://user-images.githubusercontent.com/78995399/193397720-5fa30900-f88c-4ed7-aa97-a501e4b4a209.png)
![Screenshot from 2022-10-01 12-38-50](https://user-images.githubusercontent.com/78995399/193397723-97d94fb6-99ad-47da-be6e-a8a4c4ec356f.png)

**Comment by wingkwong** [comment]
@PrasanthKumar77 can you share this csv for reproducing the issu?

**Comment by PrasanthKumar77** [comment]
[RandomData - pk - Sheet9 (5).csv](https://github.com/nocodb/nocodb/files/9695367/RandomData.-.pk.-.Sheet9.5.csv)
