### ISSUE TITLE
Error when clearing date from date field.

### ISSUE THREAD

**Issue by sph33r** [nocodb/nocodb#389]
NocoDB used as docker : true
NocoDB version : 0.11.5
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
Database version : 12.7

**Steps To Reproduce**
1. Create a database field for type "Date"
2. Create a new row and click the date field
3. A calendar pops up for you to pick a date.
4. Pick a date and move off the field so it populates.
5. Go back to the field and try to remove the date. If you just click, you get the date picker again and there's no way to clear the date. If you're fast enough, you can get a cursor in there to select the date and delete it but then you get error messages once you remove it. 

**Expected behavior**
A clear button would be handy, or at least an easy way to delete the date that doesn't return an error message. It should return to null I assume. 

**Screenshots**
<img width="401" alt="Screen Shot 2021-07-28 at 11 54 40" src="https://user-images.githubusercontent.com/1290732/127356470-1431155f-ed07-4a3b-8318-9b58484e3b5f.png">

<img width="306" alt="Screen Shot 2021-07-28 at 11 54 52" src="https://user-images.githubusercontent.com/1290732/127356530-39bc436f-2a85-400a-8b6c-3f239bb0e864.png">

<img width="703" alt="Screen Shot 2021-07-28 at 12 06 10" src="https://user-images.githubusercontent.com/1290732/127357912-668c52a8-bf4a-45bb-953e-02cf70adae49.png">

**Comment by pranavcbalan** [comment]
We can put a `clear` button or a context menu option to clear(for all kind of cell)

**Comment by pranavxc** [comment]
Added `clear` option in the context menu for resetting the value to `NULL`.  ( available since `0.11.6`)

![image](https://user-images.githubusercontent.com/61551451/127503198-d704ae6b-9231-43b8-93e1-b8d069c9b53d.png)

**Comment by pranavxc** [comment]
Added `clear` option in the context menu for resetting the value to `NULL`.  ( available since `0.11.6`)

![image](https://user-images.githubusercontent.com/61551451/127503198-d704ae6b-9231-43b8-93e1-b8d069c9b53d.png)
