### ISSUE TITLE
🐛 Bug: Change of column is not showing affect on database

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3891]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. populate the csv with high no of rows with duplicate values in a column
2. create table using import from csv
3. it will be auto recognised as singleselect 
4. change the column to single text
5. click on import

### Desired Behavior

1. The column types should be created with selected column type by user instead of auto recognised types

Need to check whether other columns are also ignoring the user selected column type

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.97.0**

### Attachements

![Screenshot from 2022-10-01 12-45-43](https://user-images.githubusercontent.com/78995399/193398114-9467fec2-6f46-4b4a-9e6b-6fa44e0d92d4.png)
![Screenshot from 2022-10-01 12-45-59](https://user-images.githubusercontent.com/78995399/193398119-81d178c3-28b3-4b47-9dd5-ad3645b26322.png)
![Screenshot from 2022-10-01 12-50-42](https://user-images.githubusercontent.com/78995399/193398180-889ad1c4-88af-4dbb-8d17-ddedeefed98c.png)

**Comment by wingkwong** [comment]
@PrasanthKumar77 can you share this csv for reproducing the issue?

**Comment by PrasanthKumar77** [comment]
[RandomData - pk - Sheet8 (2).csv](https://github.com/nocodb/nocodb/files/9695371/RandomData.-.pk.-.Sheet8.2.csv)
