### ISSUE TITLE
🐛 Bug: singleselect column type creation is failed because of high no of values

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3892]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. populate a csv with high no of rows with a column value having duplicates
2. create table with import from csv
3. it will be recognised as singleselect field automatically
4. click on import
5. look at the server logs it is forming the sql query with high no of duplicate values
6. if the query is too high table creation is getting failed

### Desired Behavior

1. when using single select duplicates should be filtered when forming the sql query
2. need to mention a enum values count limit if the values count is too high instead of throwing failed sql query in UI directly

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.97.0**

### Attachements

![Screenshot from 2022-10-01 13-06-05](https://user-images.githubusercontent.com/78995399/193398570-0377c62a-9b5c-4ebb-a059-6c439ee28675.png)

**Comment by wingkwong** [comment]
@PrasanthKumar77 can you provide a dummy csv for reproducing the issue?

**Comment by PrasanthKumar77** [comment]
[RandomData - pk - Sheet8 (2).csv](https://github.com/nocodb/nocodb/files/9695358/RandomData.-.pk.-.Sheet8.2.csv)
