### ISSUE TITLE
🐛 Bug: Table name inconsistent in UI when renamed

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#3893]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create a table
2. rename the table

### Desired Behavior

updated table name should be shown in UI

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.97.0**

### Attachements

![Screenshot from 2022-10-01 13-14-32](https://user-images.githubusercontent.com/78995399/193398952-46e33ee1-e7b6-453d-9288-cca9149ff36b.png)
![Screenshot from 2022-10-01 13-12-34](https://user-images.githubusercontent.com/78995399/193398956-6347b61a-ced8-4a67-8aa0-add71e81c950.png)
![Screenshot from 2022-10-01 13-11-45](https://user-images.githubusercontent.com/78995399/193398957-2f3fa901-8fd4-4bcf-a318-193b56ff93cf.png)

**Comment by dstala** [comment]
- Create a default table (Sheet-1)
- Rename to `new_table`
  - Project tree displays as `NewTable`
  - Tab displays as `new_table` 

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.97.0**
