### ISSUE TITLE
Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call

### ISSUE THREAD

**Issue by tegansnyder** [nocodb/nocodb#390]
First of all this is a wonderful idea. I'm eager to get in the tool and start using it. I'm working on getting the docker container running on a ECS cluster and encountered a strange error. When the app starts up its trying to connect to my Postgres instance and I get the following error:

>7 [r [999;999H [6n 8
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
at Client_PG.acquireConnection (/usr/src/app/node_modules/knex/lib/client.js:348:26) {
sql: "SELECT datname as database FROM pg_database WHERE datistemplate = false and datname = 'nocu'",
bindings: undefined
}

NocoDB used as docker : **true**
NocoDB version : **nocodb/nocodb:latest**
Database used in NC_DB URL : **pg**
Project was created  by clicking : **Haven't be able to create project yet**
Database on which spreadsheet is created : **pg**
OS on which NocoDB is running : **OS from NocoDB supplied Dockerfile running on ECS Fargate cluster.**
Node.js version if running as node : **Node version from NocoDB supplied Dockerfile**
Database version : **Postgres 10**

**Steps To Reproduce**
1. Provision ECS Cluster from NocoDB docker image
2. ECS Task attempts to start application
3. See error

**Expected behavior**
Application starts as expected

Thanks

**Comment by pranavcbalan** [comment]
Can you share  version of `nocodb` ?

**Comment by wingkwong** [comment]
Are you using RDS Postgres? It seems that it is failing due to the connection. Make sure your inbounds / outbounds of SGs of RDS / ECS are correct.

**Comment by tegansnyder** [comment]
Hi @wingkwong  I'm not currently using RDS Postgres. I have just spun up a Postgres container on ECS with an EFS mount for the filesystem. I have both the Postgres and NocoDB container tasks in the same VPC on same subnets with security groups allowing 8080 and 5432. I'm thinking about trying spinning up an RDS Postgres and see if that solves the issue.

**Comment by wingkwong** [comment]
I see. Previously I had the same issue. It was because I forgot to add some inbound / outbound rules so it caused connection error. You may give it a try. ECS with RDS is running fine.

**Comment by tegansnyder** [comment]
Just an update in case someone finds this in the future. What @wingkwong said is always the first thing to check. Having the SG inbound rules is key, in my case the health check was failing because the `/dashboard` URL returns a HTTP 301 to redirect with a trailing slash `/dashboard`. After adding the 301 to the LB health check it started to work.

**Comment by wingkwong** [comment]
Yes. I remember that as well. I just checked if the request to a static image is 200 or not. To supplement a bit, if you are using load balancer, and your service's task take a while to start and respond to health checks, you can specify a health check grace period (default: 0) during which the ECS service scheduler ignores the health check status.
