### ISSUE TITLE
Quick Import - AIRTABLE (Cannot read property 'length' of undefined)

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3927]
### Discussed in https://github.com/nocodb/nocodb/discussions/3925

<div type='discussions-op-text'>

<sup>Originally posted by **kmataeh23** October  4, 2022</sup>
Hi Nocodb team. I am trying to import an air table to noco using its api key and shared base ID but am getting a "cannot read property 'length' of undefined" error in the logs section. Any advice on a workaround for this error?
<img width="1045" alt="read property length undefined" src="https://user-images.githubusercontent.com/70729030/193707852-11b14a29-c632-4f6b-9e67-36d7b07da960.png">
</div>

**Comment by dstala** [comment]
@kmataeh23
You can DM me additional details on discord (@dstala). If you can share the redacted schema, that would be helpful for us to investigate

**Comment by KevinGutowski** [comment]
I believe this is caused by not using the Airtable **_Base_** URL but rather trying to import a shared Airtable **_View_**
