### ISSUE TITLE
🔦 Feature: DropDown menu in nocoDB form 

### ISSUE THREAD

**Issue by aftab70** [nocodb/nocodb#3934]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Hi Team,

I am not abe to confgure ncodb form with dropdown menu, Please suggest a solution for the same.

### Suggested Solution

ropdown menu in form 

### Additional Context

ropdown menu in form

**Comment by bcakmakoglu** [comment]
The description isn't really telling me much and there's no further explanation either.

Could you elaborate what exactly you are trying to achieve?

**Comment by wingkwong** [comment]
Closing - no further feedback from user.
