### ISSUE TITLE
🔦 Feature: Mass assigment in UI

### ISSUE THREAD

**Issue by ogbofjnr** [nocodb/nocodb#3947]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

It's very common when you need to set some field to multiple records. For example you've selected users and want to set them as inactive. 

Without this feature, it a tedious task, to go one by one update each record. 

### Suggested Solution

One selected fields, add edit button, so we can select the field and set value for update.

**Comment by o1lab** [comment]
This is a nice feature. Somebody requested it just this week.

**Comment by rallisf1** [comment]
AFAIK you can set it on one row and copy-paste the rest.

**Comment by dstala** [comment]
bulk update feature is now available in cloud hosted solution. for details, refer https://docs.nocodb.com/records/actions-on-record/#bulk-update-records
