### ISSUE TITLE
[Kanban] Expand record doesn't open drawer for roles = Commenter/Viewer

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3949]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Connect to Sakila DB
- Open `Commenter` in preview mode [or invite new user with `commenter` permissions
- Open any table, click on expand record

### Desired Behavior

- Expand record should open record specific drawer

### Project Details

https://github.com/nocodb/nocodb/pull/3563

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.97.0**

**Comment by wingkwong** [comment]
e520a5da3
