### ISSUE TITLE
🔦 Feature: DATEDIFF()

### ISSUE THREAD

**Issue by tasugo** [nocodb/nocodb#3950]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Useful to calculate durations of any kind, like for how long a task has been open, people's age, etcetera. The use cases are endless, I am surprised no one requested this feature before.

### Suggested Solution

DATEDIFF(Date, Date2, Units)

**Comment by JohnGrisham** [comment]
Can you assign me to this @wingkwong? I would like a little more information about what the ask is here, please. @tasugo

**Comment by wingkwong** [comment]
@JohnGrisham Assigned. To give you more context, this task is to add a new [formula](https://docs.nocodb.com/setup-and-usages/formulas) function to calculate the difference of two given dates.

I would prefer to call it `DATETIME_DIFF` to handle time cases as well. 

```
DATETIME_DIFF(Date, Date2, Units)
```

where the possible `Units` include `milliseconds`, `seconds`, `minutes`, `hours`, `days`, `weeks`, `months`, `quarters`, `years`. It would be nice if you could allow the alias such as `ms`, `s`, `m`, `h`, `d`, `w`, `M`, `Q`, `y`.

**Comment by JohnGrisham** [comment]
@wingkwong https://github.com/nocodb/nocodb/pull/4065

**Comment by folk-connect** [comment]
@wingkwong @JohnGrisham Is this being worked on ? This is very critical formula of which I don't see any workaround

**Comment by wingkwong** [comment]
@JohnGrisham Are you still working on it? Or do you want me to pick up?

**Comment by wingkwong** [comment]
Removing @JohnGrisham 's assignment due to inactivity. I'll pick it up.

**Comment by JohnGrisham** [comment]
Sorry, yes I am no longer working on this, let me know if you have any questions about the current changes.
