### ISSUE TITLE
[Kanban] URL for Expand row error's

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3952]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

https://www.loom.com/share/56c2eb0fe5be471a9250eb3102a70e17

### Desired Behavior

Expand record URL, if valid - should open window. 

If invalid - expand drawer shouldn't (not even empty draw) open. 
Expect toast message `Record not found`

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.97.0**

**Comment by wingkwong** [comment]
Handled in https://github.com/nocodb/nocodb/pull/3563/commits/7d1415a5eea81943199563b45b24f0d60a101336 https://github.com/nocodb/nocodb/pull/3563/commits/83a9de437f1bd9b7e29d4245274d10427a8bed83
