### ISSUE TITLE
🔦 Feature: Hide fields from API calls

### ISSUE THREAD

**Issue by sam-lev-fd** [nocodb/nocodb#3957]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I think it'd be cool to be able to hide columns from API get requests by default. I know that there are API parameters on which fields to show, but I'd like to make the API filtered by default to make them easier to use for my users.

### Suggested Solution

Add a "hide from API" checkbox for a column that makes the field not show unless specifically requested in the API parameters

**Comment by o1lab** [comment]
Create new views for each set of filter you have in mind and [use the view apis](https://apis.nocodb.com/#tag/DB-view-row/operation/db-view-row-list) instead.
