### ISSUE TITLE
[Survey form] Cell cursor persists in edit mode on {enter}

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3968]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

https://loom.com/share/7292895ec657439387b993bc9c58e5aa

if this is an intended change, let me know. will update Cy suite accordingly.

### Desired Behavior

Update cell & move cell out of edit mode

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.97.0**

**Comment by bcakmakoglu** [comment]
@dstala Fixed and changes pushed into survey-form branch
