### ISSUE TITLE
🐛 Bug: Error observed on deleting table

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3971]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a new table
- Delete table

Suspecting this could be a reason for one of Cy inconsistency.

### Desired Behavior

Avoid redundant API call (if any)

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.97.0**

### Attachements

![Screenshot 2022-10-07 at 6 00 54 PM (2)](https://user-images.githubusercontent.com/86527202/194555133-08c0bc1b-eaf8-451a-b74c-0f6d58293bf9.png)

**Comment by bcakmakoglu** [comment]
Seems to happen when you delete the table that's currently open.
I also noticed that the table delete itself seems to work improperly.
1. Create a table called `Sheet-1`
2. Delete the table
3. Try to create a table called `Sheet-1`
4. Error: Table already exists
