### ISSUE TITLE
🐛 Bug: Shared Views do not honour project theme

### ISSUE THREAD

**Issue by dayreiner** [nocodb/nocodb#3974]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Set a theme for a project and all logged-in areas will follow the theme colours.

Shared views however do not. Instead they default to the standard blue theme.

### Desired Behavior

I would expect the colour scheme on shared views and forms to match the theme defined in the project.

### Project Details

Nocodb version: 0.97
In Docker: yes

**Comment by bcakmakoglu** [comment]
That's not really a bug, that's rather a missing feature.
With the coming update you can pick a separate theme for your form views at least.

https://user-images.githubusercontent.com/78412429/194678189-cd18b22f-409a-4875-8686-3613fa42337a.mov

**Comment by dstala** [comment]
@dayreiner as marked by @bcakmakoglu - theme selection options is now available with latest release.
