### ISSUE TITLE
🐛 Bug: Enabling `Locked view`, right click context options for project tree gets disabled

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3987]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Grid view, switch from `collaborative view` to `lock view`
- Right click on project tree: no options displayed
- Change active tab to a different table in `collaborative mode`; right click context menu gets enabled for project tree

----

- Switch to locked view mode
- Create gallery view/kanban view: all fields are editable (by design?)

### Desired Behavior

Collaborative mode shouldn't have any impact on right click context menu for project tree

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.97.0**

**Comment by pranavxc** [comment]
The following commit is causing this behaviour - https://github.com/nocodb/nocodb/commit/fa64125

**Comment by bcakmakoglu** [comment]
Shouldn't this line `v-if="!isLocked && (isUIAllowed('table-rename') || isUIAllowed('table-delete'))"`
be `v-if="!isLocked && ((isUIAllowed('table-rename') || isUIAllowed('table-delete')))"`?

**Comment by pranavxc** [comment]
@bcakmakoglu: Yes, you are right but anyways we are going to revert the change :+1:
