### ISSUE TITLE
🐛 Bug: The migration directory is corrupt, the following files are missing: nc_011_remove_old_ses_plugin

### ISSUE THREAD

**Issue by Achraf-haddar** [nocodb/nocodb#3997]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Got an error: "The migration directory is corrupt, the following files are missing: nc_011_remove_old_ses_plugin" while starting a Noco DB docker instance in an azure app service (configured to connect to mssql database).

### Desired Behavior

Starting correctly.

### Project Details

NocoDB used as docker: true
NocoDB version: latest
Database used in NC_DB URL: mssql

### Attachements

![image](https://user-images.githubusercontent.com/62722610/195034498-a8b9e22b-cf87-4c59-8dfa-944e21c8825e.png)

**Comment by mertmit** [comment]
Which version of nocodb do you use? Looks like you downgraded from your issue. Have you tried using latest version?

**Comment by wingkwong** [comment]
Closing - no further response from user.
