### ISSUE TITLE
🐛 Bug: Windows download links broken and unsecure links promoted in docs

### ISSUE THREAD

**Issue by c33s** [nocodb/nocodb#3998]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

- accessing `https://nocodb.com/release/win-x64.exe` via browser leads to `Unsupported platform`
- accessing the same url via wget leads to `2022-10-10 19:49:53 ERROR 400: Bad Request`
- `wget https://github.com/nocodb/nocodb/releases/download/0.97.0/Noco-win-x64.exe` works

in the docs all the download links are `http`, maybe they should be changed to `https` even if they are redirected to `https`

### Project Details

docs

**Comment by pranavxc** [comment]
In the URL there is no need for `.exe` extension so you can update the URL and use `https://nocodb.com/release/win-x64`. Anyways I will do it in a way such that it will accept both urls (with or without an extension).

**Comment by c33s** [comment]
i have taken the links directly from the docs: https://docs.nocodb.com/getting-started/installation/

![image](https://user-images.githubusercontent.com/649209/195590001-4dbbbf9f-7670-4f34-9b28-b068740a453a.png)

current state is a 404 with that link as it redirects to double `.exe` extention.

```
wget https://nocodb.com/release/win-x64.exe
--2022-10-13 13:59:31--  https://nocodb.com/release/win-x64.exe
Proxy request sent, awaiting response... 302 Found
Location: https://github.com/nocodb/nocodb/releases/download/0.97.0/Noco-win-x64.exe.exe [following]
--2022-10-13 13:59:32--  https://github.com/nocodb/nocodb/releases/download/0.97.0/Noco-win-x64.exe.exe
Proxy request sent, awaiting response... 404 Not Found
2022-10-13 13:59:32 ERROR 404: Not Found.
```

**Comment by pranavxc** [comment]
> i have taken the links directly from the docs: https://docs.nocodb.com/getting-started/installation/
> 
> ![image](https://user-images.githubusercontent.com/649209/195590001-4dbbbf9f-7670-4f34-9b28-b068740a453a.png)
> 
> current state is a 404 with that link as it redirects to double `.exe` extention.
> 
> ```
> wget https://nocodb.com/release/win-x64.exe
> --2022-10-13 13:59:31--  https://nocodb.com/release/win-x64.exe
> Proxy request sent, awaiting response... 302 Found
> Location: https://github.com/nocodb/nocodb/releases/download/0.97.0/Noco-win-x64.exe.exe [following]
> --2022-10-13 13:59:32--  https://github.com/nocodb/nocodb/releases/download/0.97.0/Noco-win-x64.exe.exe
> Proxy request sent, awaiting response... 404 Not Found
> 2022-10-13 13:59:32 ERROR 404: Not Found.
> ```

Thanks for the quick reply, I will update that part :+1:

**Comment by wingkwong** [comment]
Links have been updated.
