### ISSUE TITLE
🐛 Bug: Image, on click from expanded row - appears in background

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4004]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

https://www.loom.com/share/42e2afeed54243a3b992e38d21621e00

### Desired Behavior

Image appears in foreground

### Project Details

Observed in https://github.com/nocodb/nocodb/pull/4003

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.97.0**

### Attachements

![Screenshot 2022-10-11 at 1 14 55 PM](https://user-images.githubusercontent.com/86527202/195028592-bfebdfcd-d790-436d-8b7b-2d60bca7a3c9.png)

**Comment by bcakmakoglu** [comment]
@wingkwong Might just be a z-index issue for the "Carousel" component of the attachment cell
