### ISSUE TITLE
🐛 Bug: Import excel / airtable easily accessible

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4013]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Currently its get lost out

### Desired Behavior

- 

### Project Details

dev

**Comment by KevinGutowski** [comment]
Two spots I was expecting some sort of import and didn't find it:

## Dashboard
![CleanShot 2022-10-11 at 16 25 25@2x](https://user-images.githubusercontent.com/4199296/195216337-dfaecca9-18de-4d36-83e6-f6b2d4eb6976.png)

## Upload for a table
![CleanShot 2022-10-11 at 16 26 10@2x](https://user-images.githubusercontent.com/4199296/195216474-66876c0b-a48c-42c0-a269-af94a69ddec9.png)

Hope that helps make things clearer!
