### ISSUE TITLE
🔦 Feature: Clear selected cell by pressing delete

### ISSUE THREAD

**Issue by KevinGutowski** [nocodb/nocodb#4016]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

It's tedious to have to double click into a cell to delete its contents.

### Suggested Solution

1. Select a cell
2. Press Delete and have contents of that cell cleared.

### Additional Context

Should work for any type of cell

**Comment by pranavxc** [comment]
You can clear the cell(excluding LTAR and other non-virtual column) using context menu option `Clear cell` or by <kbd>delete</kbd> key and <kbd>delete</kbd> key will only work if cell is in not in edit state.
