### ISSUE TITLE
🔦 Feature: Bulk actions like Holding shift to select multiple cells

### ISSUE THREAD

**Issue by KevinGutowski** [nocodb/nocodb#4017]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

It would be great to support a bit more bulk editing. Here is an example from Airtable:

![Oct-11-2022 15-37-14](https://user-images.githubusercontent.com/4199296/195211095-97e48ba8-d7ab-4366-9091-fc5b737cebf2.gif)

You can select multiple items by selecting one cell and then holding down shift and selecting another cell to select all items in that row or all items between that row and column.

Lastly, you should be able to press delete to clear these items.

### Suggested Solution

Have a few more interactions like Airtable. Support shift selections and bulk clearing.

### Additional Context

Note that the other key part of this feature is the Undo stack

![Oct-11-2022 15-40-55](https://user-images.githubusercontent.com/4199296/195211508-49fc05f5-bb50-4455-bdb2-7ac2b1e3ab3a.gif)

If I delete in bulk I get a reminder that I can undo. In Airtable I can always undo by pressing CMD+Z/Control+Z. The toast with the undo action is a helpful reminder that you can preform this action safely.

**Comment by bird-in-a-tree** [comment]
- [x] Multiple select
- [x] Delete on multiple selection
- [x] Paste to multiple selection
- [ ] Edit multiple selected cells in on go
As of 0.109.2

**Comment by dstala** [comment]
Bulk clearing is now supported as of v0.202.5; if you still need additional keyboard shortcuts to be enabled, please reopen this thread.

Bulk updates are possible in our cloud hosted solution. 
https://docs.nocodb.com/records/actions-on-record/#bulk-update-records
