### ISSUE TITLE
🔦 Feature: Automatically create a new row if you are on the last row and hit return

### ISSUE THREAD

**Issue by KevinGutowski** [nocodb/nocodb#4018]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In Airtable, I have the ability to breeze through creating new rows.

![Oct-11-2022 16-16-11](https://user-images.githubusercontent.com/4199296/195215382-71077cc0-62ac-416c-9000-e1fe2096fa40.gif)

However in nocodb I cannot move as fast as I have to type and fill out the row and then move back to my mouse and click the create new cell which dramatically slows me down.

### Suggested Solution

When filling out the last row and the use hits return (or maybe shift + return?) automatically create a new row and focus the users input into that newly created row.

**Comment by wingkwong** [comment]
Reopening it for the next release.
