### ISSUE TITLE
🐛 Bug: Issues with view order in the view sidebar

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#4021]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

 - Create 3 views (Grid, Form, Gallery)
 - Reorder Form and Grid
 - Delete Form
 - Grid will be removed from view list as well(comes back in reload)
 
<img width="283" alt="image" src="https://user-images.githubusercontent.com/35809690/195257428-a086ee69-4855-4348-9324-cff2acba9ec4.png">

Also creating Form outputs this console warning:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/35809690/195257057-1ec316e1-8d21-41db-956f-874d2b758ab7.png">

### Desired Behavior

--

### Project Details

Node: **v16.15.1**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.97.0**

**Comment by bcakmakoglu** [comment]
Apparently lazy loading messes up the whole sidebar -.-
