### ISSUE TITLE
[Cy]: Circular reference in Formula column

### ISSUE THREAD

**Issue by aehiggi** [nocodb/nocodb#4024]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- create new table
- create new formula field 'One': {Title}
- create new formula field 'Two': {One}
- create new formula field 'Three': CONCAT({Two},{Two})
- edit definition of either column One or Two
- add a single space at the end of the formula
- error "Can’t save field because it causes a circular reference" displayed

### Desired Behavior

This should not be flagged as a circular reference and it should be possible to edit the formula fields. Note: The formulas work fine (the expected calculated values are displayed) but further editing of the formulas is impossible.

### Project Details

Node: **v18.10.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.97.0**

**Comment by aehiggi** [comment]
This issue appears to be caused by the existence of duplicate vertices in the graph that is used for "kahn's algo for cycle detection" in /nocodb/packages/nc-gui/components/smartsheet/column/FormulaOptions.vue. Adding a simple fix to remove duplicates resolves the issue and the formula fields can be edited successfully.

**Comment by wingkwong** [comment]
@aehiggi Thanks for spotting out. To be exact, neighbours are duplicated in formula field `Three`. A simple fix can be done in FormulaOptions.vue.

**Comment by jbbn** [comment]
👋 hey there,
I pushed a PR for trying to solve this issue.
I hope it's a good contribution to the project 🙇🏻‍♂️

**Comment by aehiggi** [comment]
@wingkwong Yes you asked me in Discord to write the tests but sorry but I don't have the time to understand the test running structure and create the tests right now. Please reassign.

**Comment by wingkwong** [comment]
okay. @jbbn Can you help take on this task?

**Comment by jbbn** [comment]
Ow, that's embarrassing, I thought @aehiggi was just the reporter, so sorry for the trouble 😩

I can definitely help with the Cy testing 🫡😊🙏🏻🙇🏻‍♂️

**Comment by jbbn** [comment]
(Plus, I joined the Discord server. I couldn't correlate your usernames here and there, but if you need to find me, I am "João Bueno" in Discord 🙏🏻🙇🏻‍♂️)

**Comment by wingkwong** [comment]
@jbbn Sure. Mine is `wkw` (ID: 3278). You can ping any of us under NOCO-TEAM if you have any question.

<img width="205" alt="image" src="https://user-images.githubusercontent.com/35857179/195585949-580573e8-f48b-45ff-a95a-11af389260ff.png">
