### ISSUE TITLE
🐛 Bug: OpenAPI spec errors

### ISSUE THREAD

**Issue by MarvinJWendt** [nocodb/nocodb#4034]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. make project
2. make a table
3. make some rows
4. fill rows with data
5. download swagger.json
6. try to generate a client of the swagger JSON
7. see errors

### Desired Behavior

No errors and a successful generation.

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.97.0**

### Attachements

![image](https://user-images.githubusercontent.com/31022056/195401786-b55ac5d5-4367-48d7-b7f3-b6127848330e.png)

![image](https://user-images.githubusercontent.com/31022056/195401830-903096d4-d3c3-4b98-a556-9aefe17c3216.png)

To fix both errors, you'd have to remove the `wrapped` and change `"count": "number"` to `"count": {"type": "number"}`

**Comment by o1lab** [comment]
Any reason why you are trying to download swagger json ?

**Comment by MarvinJWendt** [comment]
Because I need to modify it, so that it works. If I don't, the errors mentioned above prevent OpenAPI CLI from running:
![image](https://user-images.githubusercontent.com/31022056/195417266-7bf96785-859d-409c-89e8-9d151456dcb7.png)
