### ISSUE TITLE
🐛 Bug: `npx create-nocodb-app` doesn't run

### ISSUE THREAD

**Issue by cjmaxik** [nocodb/nocodb#4041]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Install Node.js
2. Try to run `npx create-nocodb-app`
3. Have this in response:
```
root@nocodb:/home/me# npx create-nocodb-app
usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-M ttl]
	  [-m minttl] [-O length] [-P proxy_username] [-p source_port]
	  [-q seconds] [-s sourceaddr] [-T keyword] [-V rtable] [-W recvlimit]
	  [-w timeout] [-X proxy_protocol] [-x proxy_address[:port]]
	  [destination] [port]
```

### Desired Behavior

NocoDB setup wizard [is running](https://user-images.githubusercontent.com/35857179/161526235-5ee0d592-0105-4a57-aa53-b1048dca6aad.png)

### Project Details

NocoDB used as docker: false
NocoDB version: latest
OS on which NocoDB is running: Ubuntu Server 22.04.1 LTS (`Linux nocodb 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`)
Node.js version if running as node: v18.10.0

**Comment by dstala** [comment]
It worked fine on MAC, I tried using node v16.14.0. Need to try user-specified configuration

**Comment by pranavxc** [comment]
Can you try the latest version with the command as follows

```sh
npx create-nocodb-app@0.1.26
```

**Comment by cjmaxik** [comment]
> Can you try the latest version with the command as follows

The same result, unfortunately.

**Comment by pranavxc** [comment]
That's strange, so can you install it globally and try it once?


```sh
npx i -g create-nocodb-app@0.1.26

create-nocodb-app
```

**Comment by cjmaxik** [comment]
> That's strange, so can you install it globally and try it once?
`npm ERR! could not determine executable to run`

> I think the problem is there is another package with the same nc or create-nocodb-app alias.
`nc` is `netcat` in Ubuntu.

**Comment by pranavxc** [comment]
So it's conflicting with the `netcat` and you couldn't able to install it at all ?

**Comment by cjmaxik** [comment]
Seems like it, it comes with default Ubuntu installation.

**Comment by pranavxc** [comment]
So we will remove the `nc` alias from our package and that will resolve the issue.

**Comment by pranavxc** [comment]
@cjmaxik : Published the changes in latest version of cli, you can try the following command now.

```bash
npx create-nocodb-app@0.1.27
```
