### ISSUE TITLE
🐛 Bug: `npx create-nocodb-app` installed v0.92.4

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4042]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

run `npx create-nocodb-app`
configure for SQLite and NodeJS

-----

Error on closing terminal
```
^C

Error running command internally

	"npm install; npm run start;"

Exiting...
```

### Desired Behavior

install latest release

### Project Details

npx create-nocodb-app

**Comment by pranavxc** [comment]
You can upgrade the version by navigating to the project folder and then run following command.

```bash

npm i --save nocodb@latest

```
or 


```bash

npm i --save nocodb@0.97.0

```



Ref : https://docs.nocodb.com/getting-started/upgrading#node
