### ISSUE TITLE
🔦 Feature: As a superuser i should be able to invite users with permissions to projects 

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#4047]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

The current way is i have to create a project and invite the users and they can create projects after being invited.
i have disabled the signup option for external users.

### Suggested Solution

i would like to have an option to invite users with access across all projects with specific permissions like viewer access to all projects whether he is invited or not to that specific project. similarly commenter/editor access.

when new projects were created these default users should be shown in team of that project. and there should be a option for super admin to view all these users and add/remove them.

**Comment by dstala** [comment]
workspace admin & workspaces are now available in hosted solution. visit https://nocodb.com for more details. 
for docs, visit https://docs.nocodb.com/workspaces/workspace-collaboration
