### ISSUE TITLE
🔦 Feature: Super user should have full access to all projects

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#4048]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

As a super admin i should have access to all projects and tables. as an administrator of team i have use cases to monitor the projects and tables created and their data integrity

### Suggested Solution

can provide creator access to all projects for superadmin. 
show an info button when creating the project that superuser will have access to this project by default

**Comment by PrasanthKumar77** [comment]
Hi @o1lab, May i know if this is in your roadmap?

**Comment by dstala** [comment]
as noted in current release, super-admin does have creator access to all projects. only information display to non admins is requested

`show an info button when creating the project that superuser will have access to this project by default`

**Comment by dstala** [comment]
Super user in release v0.202.5 has complete access. @PrasanthKumar77 reopen this thread if you still see any issues.
