### ISSUE TITLE
New Project button

### ISSUE THREAD

**Issue by blondie63** [nocodb/nocodb#409]
NocoDB used as docker : true 
NocoDB version : 0.11.6

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.11.6**

**Steps To Reproduce**
1. Install new istance by docker
2. Open dashboard with Chome 92.0.4515.107 on MacOS 11.5.1
3. You don't see the "New Project" button / just tried to clean browser cache
4. With Firefox 90 on same Mac, no problem

**Screenshots**
<img width="1824" alt="nocoDB 011 6 mac-chrome92" src="https://user-images.githubusercontent.com/1261851/127775133-04464635-45d9-40c6-a2ff-04fbb84b1e0e.png">
<img width="1665" alt="nocoDB 011 6 mac-Firefox90 0 2" src="https://user-images.githubusercontent.com/1261851/127775137-52de82e9-ad0a-4746-bd24-c96ea4b59015.png">

**Comment by pranavcbalan** [comment]
For time being as a workaround you can clear the localstorage and reload the page.

**Comment by pranavxc** [comment]
Can you share the response details of `/auth/type` API from your browser network tab?

**Comment by blondie63** [comment]
[192.168.1.180 nocoDB.har.zip](https://github.com/nocodb/nocodb/files/6921488/192.168.1.180.nocoDB.har.zip)

Is it ok this ?

**Comment by pranavxc** [comment]
> [192.168.1.180 nocoDB.har.zip](https://github.com/nocodb/nocodb/files/6921488/192.168.1.180.nocoDB.har.zip)
> 
> Is it ok this ?

Ya the response looks good, it's strange something happens for few peoples. Can you clear the browser localstorage and try once.

**Comment by o1lab** [comment]
Can we think of a double click workaround here 😉

**Comment by pranavxc** [comment]
> Can we think of a double click workaround here 😉

Like clearing the loicalstorage or something

**Comment by blondie63** [comment]
Doing other tests it seems that problem is with Chrome 92.0.4515.131 and not only for New project button
Also "Create View" is not there !

**Comment by pranavxc** [comment]
> Doing other tests it seems that problem is with Chrome 92.0.4515.131 and not only for New project button
> Also "Create View" is not there !
Even after clearing localstorage ? 

Do the following -

- Clear the localstorage
- Hard refresh the page ( <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> or <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> )
- Now check the problem still persist or not

**Comment by pranavxc** [comment]
Fixed in `0.11.17`

**Comment by boikoandrii** [comment]
> Fixed in `0.11.17`

Sorry but it's not :( Has the same issue in "0.99.0". For new users there's no button "New project", filters doesn't work for Editors (I'm continue searching what's wrong)
