### ISSUE TITLE
🐛 Bug: LongText Form Field Dark Theme not Working

### ISSUE THREAD

**Issue by BossMBGaming** [nocodb/nocodb#4090]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a Form that contains a LongText Input
2. Set the Form to Dark Mode.

Note: It can be reproduced in both the regular form and the survey form mode.

### Desired Behavior

The LongText Form background should follow the dark theme.

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.98.1**

### Attachements

[2022-10-14 11-43-43.webm](https://user-images.githubusercontent.com/49920384/195890255-35df0ef0-7bbd-47bb-838c-538deffa27a3.webm)

**Comment by bcakmakoglu** [comment]
Thanks for reporting, I'll fix that asap 👍
