### ISSUE TITLE
🔦 Feature: The expanded view should give more information than the cards themselves.

### ISSUE THREAD

**Issue by krokodylek** [nocodb/nocodb#4092]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

The expanded view should give more information than the cards themselves.

This would make it possible to use nocodb as a CRM.

### Suggested Solution

At best, the ability to show everything we want, hide what is unnecessary AND add a new field(column).

**Comment by redhoyasa** [comment]
@krokodylek do you expect that this is only applicable to the kanban view?

**Comment by o1lab** [comment]
Commenting is available see below & customisation of expanded row depends on your fields selected in grid/form view

<img width="991" alt="Screenshot 2022-10-25 at 16 46 42" src="https://user-images.githubusercontent.com/5435402/197820739-c8270fc9-3cf1-4d60-8e79-798a1fba752d.png">

**Comment by krokodylek** [comment]
@o1lab Thanks! deletion of comments would be welcome. The blue badge leaves a permanent mark and I don't know how to get rid of it from the panel now other than deleting the record.
![image](https://user-images.githubusercontent.com/34084110/197835271-25a9ec79-293f-4c6f-a675-3b0fd7a6158b.png)

**Comment by redhoyasa** [comment]
While I agree with @krokodylek on what nocodb needs for CRM use case, I feel that there will be some different problems to make it happen.

In this issue, perhaps we can focus on the kanban things.

Instead of modifying the expanded view (which is possibly more complex and affects other views), I think that we can make the kanban view configurable. 

In Airtable, fields that are shown in the card are configurable (see image below).

<img width="1180" alt="Screenshot 2022-10-27 at 10 20 13 AM" src="https://user-images.githubusercontent.com/1910192/198243980-4c42e876-1db1-470d-b012-062e27d7e227.png">

That makes more sense to me since basically, the expanded view should show all fields, regardless of the view we use. What do you think? @o1lab

**Comment by abosaudtech** [comment]
Why after open recored I can't  see hidden filed

![image](https://user-images.githubusercontent.com/38051894/201469051-493d6266-3804-4036-9964-06bf6319daff.png)

**Comment by o1lab** [comment]
Expanded row is for showing only visible fields at the moment.

**Comment by 3699n** [comment]
It would be a very valuable feature to see a detailed view beyond just the "visible" fields when you click on a card. If you need to make all fields visible (including long text) to be able to see it in the detailed view, it can get cluttered very quickly.

**Comment by kirtan403** [comment]
The expanded row should show all the fields is what I believe, otherwise, we need to go back and forth to the main view to update any data that should not be shown in the kanban view.

**Comment by kirtan403** [comment]
So for example in the board view, in the airtable it shows all the fields with the extra link:

![image](https://user-images.githubusercontent.com/7900938/206098853-716f0fd8-9663-49ad-ad50-7592796d6606.png)

Source: https://airtable.com/shrBMLzcFzFit8KPF/tblpZMgRZq8MVJaGi/viwb80n4xaMu5ftkh/recXPoUDjvV2zj8KV?blocks=hide

Same when using the gallery view:

![image](https://user-images.githubusercontent.com/7900938/206098259-5b3daa24-5222-4d01-98b4-6c2ceac2b581.png)


Source: https://airtable.com/shrdowLoL6vS9srjZ/tbldw7nqxlnfzNIMI/viwM6XhIEFYiAD78q

**Comment by DeyLak** [comment]
Is there any chance this could be done?

**Comment by dstala** [comment]
show hidden fields is now available, as of 0.111.0


![Image](https://github.com/nocodb/nocodb/assets/86527202/213b0504-f8fd-4b5c-be56-2b86b2200c26)
