### ISSUE TITLE
🐛 Bug: Checkbox in survey not ticking

### ISSUE THREAD

**Issue by krokodylek** [nocodb/nocodb#4094]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a checkbox field in table, create a form, share view, open in new card and try to tick the checkbox

### Desired Behavior

Checkbox should tick

### Project Details

Docker, 0.98.1, arm64, default sqlite

### Attachements

![image](https://user-images.githubusercontent.com/34084110/195939560-1b3c6635-913e-490b-be4c-03400c30b5f1.png)
![image](https://user-images.githubusercontent.com/34084110/195939606-bd75948f-c7c8-486b-b4e7-2460d63f6ef3.png)

**Comment by bcakmakoglu** [comment]
Thanks for the report, I'll take a look and fix it asap 😄
