### ISSUE TITLE
🔦 Feature: Single select and Multiple Select -> allow adding new option within the cell.

### ISSUE THREAD

**Issue by krokodylek** [nocodb/nocodb#4095]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Increase in productivity. 

### Suggested Solution

Single select: when cell is empty, writing anything should create new option and store it.
Multi select: mouse click on a background of a cell should enable user to add new option

Adding options should be restricted to creator/owner by default

### Additional Context

This will make nocodb more sheets less database

**Comment by dstala** [comment]
feature available as observed in v0.100.2; @krokodylek you can check latest release; reopen this issue if you need further enhancements
