### ISSUE TITLE
🔦 Feature: Row number in total not per page

### ISSUE THREAD

**Issue by krokodylek** [nocodb/nocodb#4096]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

![image](https://user-images.githubusercontent.com/34084110/195942230-71377014-2b2c-4107-b648-b11bb8324874.png)

Given that it is planned to be able to change the number of results displayed, perhaps there will be an opportunity to display, by the way, a number representing which sorting result we have before our eyes. Displaying a number on a specific page is not very practical

### Suggested Solution

A new environment variable?

**Comment by dstala** [comment]
Available in https://github.com/nocodb/nocodb/releases/tag/0.105.0
