### ISSUE TITLE
Unable to update/delete/select records for composite primary keys from swagger

### ISSUE THREAD

**Issue by hiteshpattanayak-sureify** [nocodb/nocodb#410]
In swagger the primary key field is set to integer by default because it considers the default primary key to be 'id'.
But if we add a new primary key [composite along with default 'id' key], then while updating/deleting/selecting we need to provide value for primary-key in the format <id-field-value>___<secondary-primary-key-value>. So this primary key is a string. 
Can this primary-key type be changed to string instead?

Also if there is a way to remove dependency from default 'id' field, it would be great help?

**Comment by pranavxc** [comment]
Fixed in `0.11.7`
