### ISSUE TITLE
🐛 Bug: Lost characters while typing/randomly deleted string in text fields

### ISSUE THREAD

**Issue by Entmatix** [nocodb/nocodb#4103]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create project.
2. Create table.
3. Type something in text field.
4. See how characters you type are lost during typing or even the whole string disappears.

### Desired Behavior

No lost characters, no lost strings.

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.98.1**

### Attachements

https://0x0.st/ovkn.34.mov

**Comment by pranavxc** [comment]
I'd already fixed a few bugs related to the row insert/update in the following PR #4088 

Can you test the executable or the docker image?


### Docker

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.98.1-pr-4088-20221015-0722
```

### Executables

#### MacOS

```bash
mkdir -p ./0.98.1/pr-4088-20221015-0722 && cd "$_" \
    && curl http://dl.nocodb.com/0.98.1-pr-4088-20221015-0722/Noco-macos-arm64 -o noco -L \
    && chmod +x noco \
    && ./noco
```
#### Linux

```bash
mkdir -p ./0.98.1/pr-4088-20221015-0722 && cd "$_" \
   && curl http://dl.nocodb.com/0.98.1-pr-4088-20221015-0722/Noco-linux-x64 -o noco -L \
   && chmod +x noco \
   && ./noco
```
#### Windows

```bash
iwr http://dl.nocodb.com/0.98.1-pr-4088-20221015-0722/Noco-win-arm64.exe
.\Noco-win-arm64.exe
```

For executables visit [here](https://github.com/nocodb/nocodb-timely/releases/tag/0.98.1-pr-4088-20221015-0722)

**Comment by pranavxc** [comment]
I could able to reproduce the issue locally after adding a delay in the update method. I will work on the bug.

**Comment by pranavxc** [comment]
Fixed issue in following PR - #4118 

Can you test the PR build(executable or docker) from following link and confirm - https://github.com/nocodb/nocodb/commit/96db6145fc1878d24119d5a451b6b8d930a3428d#comments

**Comment by Entmatix** [comment]
Closing it.

**Comment by pranavxc** [comment]
@Entmatix: thanks for confirming it, we will make it part of our next release.

**Comment by Entmatix** [comment]
@pranavxc, nice to see how nocodb develops and grows. Thanks!

**Comment by wingkwong** [comment]
Reopening the issue as it should be closed by Github Action during the next release so that the release version will be commented here. Please stay it opened.

**Comment by leewardbound** [comment]
Confirmed that #4118 fixed the issue for me too, thanks!
