### ISSUE TITLE
Sticky column to the side

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4110]
### Discussed in https://github.com/nocodb/nocodb/discussions/4109

<div type='discussions-op-text'>

<sup>Originally posted by **rafalkukla** October 15, 2022</sup>
To be able to stick to the edge of the screen Name of the Row or ID or even better, right click on the column and choose what we want to stick. So when you scroll sideways to see other data, you can see title of the row or whatever we selected. Useful especially when you amend a row and you want to make sure you working on the right one.  </div>

**Comment by dstala** [comment]
available in v0.105.2
