### ISSUE TITLE
🐛 Bug: Currency record doesn't get saved on UI

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#4113]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Try to update any currency row, click outside (pressing enter works as expected)
Refresh the page using refresh icon or via browser.

### Desired Behavior

It should reflected to back-end

### Project Details

develop

**Comment by johnmpost** [comment]
i encountered this issue with the latest version. it simply doesn't send any request to the server when you edit a currency cell.

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **mysql2**
PackageVersion: **0.109.7**

**Comment by wingkwong** [comment]
@johnmpost are you using firefox? please subscribe this [issue](https://github.com/nocodb/nocodb/issues/6086) and discuss there instead.
