### ISSUE TITLE
🔦 Feature: Add label and description column in View Form

### ISSUE THREAD

**Issue by affinage-digital** [nocodb/nocodb#4116]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Form View has title and description, great! But every column not customization. Example column `Title` I want change to `Please, enter your company name` and description `The company you work for`

### Suggested Solution

In column edit modal add fields Label and Description after column type. Not in `show more +`

### Additional Context

There is no need in the validation of fields yet

**Comment by wingkwong** [comment]
@affinage-digital By clicking the form item, you can change the input title and the help text. Is this something you are looking for?

![image](https://user-images.githubusercontent.com/35857179/196083413-260144f0-b2cb-4728-bde4-c4ae6021fef2.png)

![image](https://user-images.githubusercontent.com/35857179/196083449-76eb6f46-9dd3-4c1f-b998-c1f765728e06.png)

**Comment by affinage-digital** [comment]
You are right, my bad. I checked on my Android phone, and there is no response on clicking on the title.
