### ISSUE TITLE
🐛 Bug: Date time issue

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4129]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

<img width="1031" alt="Screenshot 2022-10-18 at 20 42 02" src="https://user-images.githubusercontent.com/5435402/196528389-9d0d064a-c114-4084-841c-6e5622e93ddb.png">

### Desired Behavior

- Datetime setting should work

### Project Details

Latest

**Comment by wingkwong** [comment]
Expected behaviour.

See https://discord.com/channels/661905455894888490/1031953327862321224/1032142967449866241
