### ISSUE TITLE
🔦 Feature: Modify Field after Webhook "After Update"

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#4130]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently, when trying to use **After Update** webhooks, it is not possible to limit the execution to **only once**. For example, if I want to send an email via a webhook **only once** if a Single Select field is equal to a specific value, I cannot do so. Every time the respective row is updated the email will be sent again so long as the conditional field stays on that specific value.

In Airtable, you can update a field value after an automation / webhook to **record an execution and avoid re-execution**. For example, I can create a checkbox field "Email Sent" and can set it to true after the webhook runs to prevent it from sending the email again and again.

### Suggested Solution

Similar to Airtable, I would recommend the ability to select fields of the trigger row to be set to a specific value in the webhook settings. 

![image](https://user-images.githubusercontent.com/7414843/196564472-005eb531-fd12-4fe4-83b1-12489350b1db.png)

You could use a similar UI to "On Condition":

Checkbox "After Webhook":
Allow the user to select arbitrary field and set them to specific values, similar to how users can choose arbitrary fields to monitor for "On Condition".

**Comment by 3699n** [comment]
For those looking for this functionality currently, I managed to replicate it with N8N using a flow with an After Update Webhook triggering the workflow and updating a boolean in the triggering row once the workflow is done.
![image](https://user-images.githubusercontent.com/7414843/199385442-df0d04d1-667e-4876-b3d9-a07c682eb455.png)

**Comment by dstala** [comment]
`After update` trigger now configured as per the discussion in this thread. When condition configured, webhook will be triggered if
`{ conditions (old values) === false && conditions (new values) === true }`

**Comment by dstala** [comment]
changes will be available from next feature release scheduled by end of this month
