### ISSUE TITLE
🔦 Feature: project lists order manually

### ISSUE THREAD

**Issue by u23a** [nocodb/nocodb#4132]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have many Projects, and I want to order those manually.
Even the Project name starts with "00-name" doesn't work.

### Suggested Solution

Make the front end can order projects manually.

**Comment by dstala** [comment]
duplicate. to be tracked under https://github.com/nocodb/nocodb/issues/5055
