### ISSUE TITLE
🐛 Bug: CSV upload crashes when the table has a primary key

### ISSUE THREAD

**Issue by hugolmn** [nocodb/nocodb#4144]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a table from a CSV file, where a column is a primary key.
- Set all types to LongText except for the Id column which is SingleLineText.
- Remove all rows from the table.
- Try to import the same data using a CSV upload.

In my case, it freezes and end up saying it completed the action but nothing has actually happened. In the console, I get this error repeatedly:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/39267118/197197569-ba332fa8-3420-4b70-ab1a-04a6a8b4db78.png">

### Desired Behavior

Rows should be imported like when there is no primary key.

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.96.2**

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. If possible, please record a video for demo.

> Create a table from a CSV file, where a column is a primary key.

Do you mean primary value?

When you import, is the checkbox checked? 

![image](https://user-images.githubusercontent.com/35857179/197210562-631fbcb4-1b73-4ef0-bc86-43073c5eabc4.png)

**Comment by hugolmn** [comment]
https://user-images.githubusercontent.com/39267118/197485064-b364b1a2-c2a1-4b12-96c3-b6c496e7026a.mp4

**Comment by hugolmn** [comment]
Below are the 2 csv files used:
[test_nocodb_1.csv](https://github.com/nocodb/nocodb/files/9850160/test_nocodb_1.csv)
[test_nocodb_2.csv](https://github.com/nocodb/nocodb/files/9850159/test_nocodb_2.csv)

**Comment by wingkwong** [comment]
Thanks. Will take a look.
