### ISSUE TITLE
🐛 Bug: Cannot delete column from table

### ISSUE THREAD

**Issue by TtuxX** [nocodb/nocodb#4148]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1 - Create a table
2 - Add columns
3 - Use the table for few hours
4 - Delete a column
5 - I cannot delete any column anymore from the table

REQUEST GENERATED WHEN REQUESTING TO DELETE A COLUMN: 
XHR DELETE http://192.168.1.33:8080/api/v1/db/meta/columns/cl_gmqqqap7lqxes6      [HTTP/1.1 400 Bad Request 91ms]

RESULTING ERROR MESSAGE:
{"msg":"Cannot read properties of null (reading '1')"}

### Desired Behavior

Be able to delete any column from a table.

### Project Details

Installed inside a jail on TrueNAS-12.0-U8 (which is based on FreeBSD)

I followed this link to install NocoDB: https://gist.github.com/Zamana/e9281d736f9e9ce5882c6f4b140a590e

NocoDB is deployed thanks to nocodb-seed 

I installed it with command: 
      npm install nocodb --force
as I had errors with just "npm install nocodb"

### Attachements

https://user-images.githubusercontent.com/6570830/197245938-7efbd27d-f4e5-4756-80ca-631397416593.mov

**Comment by o1lab** [comment]
Would need the error logs on the server side. I was able to delete the columns fine on a sqlite db. Wonder if it has to do with TrueNAS and SQLite.

**Comment by TtuxX** [comment]
Thank you very much for your reply @o1lab!
I think you are right. Which logs would you like me to provide you with and where is it possible to retrieve the noco log files? 
Thank you in advance for your kind help

**Comment by jaz000** [comment]
I think I have the same problem.
Same symptoms, using docker image with included db 

docker logs:


╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║   EXCEPTION OCCURED!! in SqliteClient @ tableUpdate                          ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:                                                                   ║║   Cannot read property '1' of null                                           ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   CODE:                                                                      ║║   undefined                                                                  ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   STACK:                                                                     ║║   TypeError: Cannot read property '1' of null                                ║║   at SQLite3_DDL._doReplace (/usr/src/app/node_modules/knex/lib/dialects/s   ║║   qlite3/schema/ddl.js:114:30)                                               ║║   at                                                                         ║║   /usr/src/app/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:294:29   ║║   at Array.forEach (<anonymous>)                                             ║║   at                                                                         ║║   /usr/src/app/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:292:21   ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║                                                                              ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝
TypeError: Cannot read property '1' of null
    at SQLite3_DDL._doReplace (/usr/src/app/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:114:30)
    at /usr/src/app/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:294:29
    at Array.forEach (<anonymous>)
    at /usr/src/app/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:292:21
M :: TypeError: Cannot read property '1' of null
    at SQLite3_DDL._doReplace (/usr/src/app/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:114:30)
    at /usr/src/app/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:294:29
    at Array.forEach (<anonymous>)
    at /usr/src/app/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:292:21

**Comment by dstala** [comment]
@TtuxX if issue still persists for you in our latest release v0.202.5, please reopen this thread
