### ISSUE TITLE
🐛 Bug: Docment【Development setup】not working

### ISSUE THREAD

**Issue by DawnSouther** [nocodb/nocodb#4158]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

my pc is clean, only win10 and nodejs

nocodb use develop branch

Build SDK & Build Backend
npm install -> Error: Timeout trying to fetch resolutions from npm

Build Frontend
npm run dev -> nuxi requires @nuxt/kit to be installed in your project. Try installing nuxt3 or @nuxt/bridge first.

### Desired Behavior

we can normally compile and develop

### Project Details

nodejs@16.15.1

**Comment by o1lab** [comment]
Would help if you can provide the error logs and your npm version
