### ISSUE TITLE
🔦 Feature: add the header type xc-token

### ISSUE THREAD

**Issue by fangjiyuan** [nocodb/nocodb#4159]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I want to use nocodb api in webhook. 
but the header type list have no xc-token, can we add the type?

### Suggested Solution

I want to use nocodb api in webhook. 
but the header type list have no xc-token, can we add the type?

**Comment by o1lab** [comment]
@wingkwong : let's allow any user entered header.

**Comment by wingkwong** [comment]
@fangjiyuan You mean you want to input xc-token in header here right?

![image](https://user-images.githubusercontent.com/35857179/197521749-86ad9439-0e00-4972-af3a-50a6ca4ffbf7.png)

**Comment by o1lab** [comment]
That is right. Before vue3 - this could have custom headers as well.

**Comment by fangjiyuan** [comment]
> 
add the option or  input ,both is ok.

**Comment by fangjiyuan** [comment]
> @fangjiyuan You mean you want to input xc-token in header here right?
> 
> ![image](https://user-images.githubusercontent.com/35857179/197521749-86ad9439-0e00-4972-af3a-50a6ca4ffbf7.png)

you get it .
