### ISSUE TITLE
Lookup column has a different display format than origin

### ISSUE THREAD

**Issue by ejose19** [nocodb/nocodb#416]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.11.7**

**Steps To Reproduce**
1. Create table "a" with a "date" column and insert 1 row
2. Create table "b" with a foreign key to table "a" and insert 1 row
3. Create a lookup column on table "b" to table "a" (date), notice how the display is an entire ISO string

**Expected behavior**
Lookup table should display the same format as origin (YYYY-MM-DD)

**Screenshots**
source
![image](https://user-images.githubusercontent.com/8742215/127919583-fa92c84b-0377-4a79-8a3c-a7d1c21daf52.png)

lookup
![image](https://user-images.githubusercontent.com/8742215/127919606-d79956ed-4d6e-41ce-8b4c-f211eae3fadb.png)

**Comment by pranavxc** [comment]
Resolved in `0.11.14`

**Comment by ejose19** [comment]
Hello @pranavxc, I've updated but I still the see issue for this exact case. Worth noting that the issue is present for `postgres` and not for the embedded database. For other types I do see the same format (like when using single select). One UI improvement though, is that lookup/links also have the same alignment in the cell as the origin.

source
![image](https://user-images.githubusercontent.com/8742215/128906061-46707e63-28bc-426f-a294-31d5115b3bb4.png)

lookup
![image](https://user-images.githubusercontent.com/8742215/128906072-e91931b2-0312-4145-b446-1c1d586e14b8.png)

**Comment by pranavxc** [comment]
> Hello @pranavxc, I've updated but I still the see issue for this exact case. Worth noting that the issue is present for `postgres` and not for the embedded database. For other types I do see the same format (like when using single select). One UI improvement though, is that lookup/links also have the same alignment in the cell as the origin.
> 
> source
> ![image](https://user-images.githubusercontent.com/8742215/128906061-46707e63-28bc-426f-a294-31d5115b3bb4.png)
> 
> lookup
> ![image](https://user-images.githubusercontent.com/8742215/128906072-e91931b2-0312-4145-b446-1c1d586e14b8.png)

Thanks for reporting will look into this. And we are always aligning the lookup/linked record column on the left side and wrapping it with a chip component.

**Comment by ejose19** [comment]
@pranavxc The chip component is not an issue, but it will be consistent if select (and similar) lookups are aligned at center (like the original column).

**Comment by o1lab** [comment]
This is good since our UI in vue3
