### ISSUE TITLE
🐛 Bug:  TOKEN API can be use in all Project

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#4163]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

With an user A, create a project "ProjectA" and generate a token API.  
With an user B, create a project "ProjectB" and go to "API tokens Management".

=> User B can see the token create for project A, and can use it.  

In database, column "project_id" in table "nc_api_token" is always NULL.  

### Desired Behavior

Token API should be use for a specific project.  

### Project Details

NocoDB use as Docker  
NocoDB Version : 0.98.1

### Attachements

![image](https://user-images.githubusercontent.com/45880189/197500071-97942e68-ba4e-491c-b173-0154d862778c.png)

**Comment by wingkwong** [comment]
Covering in this PR https://github.com/nocodb/nocodb/pull/4134.

> Token management
>
>- Newly created tokens are associated with the created user and it will have all permissions that particular user has
>- Existing token will work as it is and only be visible to the super admin

**Comment by wingkwong** [comment]
Fixed in v0.99.0.
