### ISSUE TITLE
🐛 Bug: Abort trap: 6

### ISSUE THREAD

**Issue by 684efs3** [nocodb/nocodb#4177]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I am using NocoDB on Node and I just uninstalled and reinstalled per the upgrade instructions. Now when I go to open a table for my database on NocoDB, I get "Abort trap: 6". The table and database was working fine before the upgrade.

### Desired Behavior

No "Abort trap: 6". Ability to see the table.

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.96.4**

**Comment by o1lab** [comment]
Would need err logs from the backend. Node and npm version too.

**Comment by wingkwong** [comment]
Closing - no further response from user.
