### ISSUE TITLE
🐛 Bug: checkbox cell unselectable

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#4178]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create a column with checkbox type
2. check it. nothing happens
3. open expanded form. check it. nothing happens.

### Desired Behavior

the checkbox should be checked

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.98.1**

**Comment by wingkwong** [comment]
Saw @bcakmakoglu fixed it in https://github.com/nocodb/nocodb/commit/f5fa3cd2d99db50fa5252c1943796ddf9bcb123d before but somehow now it's not working.

**Comment by bcakmakoglu** [comment]
Fix in #4179
