### ISSUE TITLE
🐛 Bug: wrong column gets deleted on CSV import

### ISSUE THREAD

**Issue by hugolmn** [nocodb/nocodb#4180]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Import CSV file
Delete some columns

https://user-images.githubusercontent.com/39267118/197980132-2efbe91d-4ea6-4a1b-b55e-7035b7330898.mp4

### Desired Behavior

The right columns should get deleted.

### Project Details

Node: v12.22.12
Arch: x64
Platform: linux
Docker: false
Database: pg
ProjectOnRootDB: true
RootDB: pg
PackageVersion: 0.96.2

**Comment by wingkwong** [comment]
Thanks for reporting. I'm able to reproduce it. Will fix soon.
