### ISSUE TITLE
🐛 Bug: Attachment URLs are stored with base_url prefixed

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#4185]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Upload any attachment
This causes undesired behavior when reached behind a proxy and later base_url is changed

### Desired Behavior

We should only keep path (we only allow internal attachments), and use append base_url on front-end / middleware

### Project Details

Develop

**Comment by wingkwong** [comment]
Here's the summary after our discussion.

- use `ncSiteUrl` as base url
- for creating a new attachment, the format would be like

```json
[
    {
        "path": "download/noco/xcdb/Sheet-1/title5/39A410.jpeg",
        "title":"foo.jpeg",
        "mimetype":"image/jpeg",
        "size":6494
    }
]
```

For the existing data, when we read / update an attachment, we do the following

- check if `path` is present in attachment object
  - if path is present, check if `url` field is present, if so, delete `url` (during update)
  - if not, use `url`, else construct the link from `ncSiteUrl` and `path` (during read)

cc: @mertmit @pranavxc

**Comment by o1lab** [comment]
Can we write an upgrade function for this fix which does the following
- For all attachment fields, if URL is present lets remove the `url`

**Comment by wingkwong** [comment]
@o1lab In this case we need to find out all attachment columns in users' meta databases (nc_columns_v2) and make connections to the external databases (start new transactions ..). The entire upgrade is happening within a transaction, which may cause some issues.

**Comment by o1lab** [comment]
Upgrade happens on the boot - so holding the transaction within xcdb does not affect any operations in backend or frontend. And external database updates - we do not require it to be done via transaction.
