### ISSUE TITLE
Unexpected behavior when adding roles for users not added to projects

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#420]
Currently if a user that is not in project, adding roles basically has no action. 

**Steps To Reproduce**
1. Supposing there is a user which is not added to the project 
2. Add some roles in Users Management
3. It shows "Successfully updated the user details" and no roles have been added
4. Add the user to the Project
5. Add some roles
6. It shows "Successfully updated the user details" and roles have been added

**Expected behavior**
If no action is expected for those users not in project, I would suggest to hide the edit button to avoid confusion. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35857179/127983552-62782a96-66cf-4734-bce4-5fbf83fa6be4.png)

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.11.6**

**Comment by pranavxc** [comment]
Fixed in `0.11.11`
