### ISSUE TITLE
Gallery view: skip null/empty value display for enabled fields

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4204]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

We skip empty values being displayed on the card in Kanban. emulate similarly for Gallery

### Desired Behavior

Skip empty values on the card 

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.98.1**

**Comment by redhoyasa** [comment]
Is something like this acceptable to you?

<img width="1508" alt="Screenshot 2022-10-28 at 11 14 24 PM" src="https://user-images.githubusercontent.com/1910192/198684441-3aafd6ec-574c-4c5a-beaa-c386cad96b98.png">
