### ISSUE TITLE
🐛 Bug: New rows can't be retrieved after successful csv import message

### ISSUE THREAD

**Issue by Vlados1111** [nocodb/nocodb#4206]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I'm trying to upload csv to a table.
After clicking "Import" button I see message that import was successfull. But then I can't find imported rows in the table.
Earlier I had no such problems with import.
<img width="1678" alt="Снимок экрана 2022-10-27 в 16 33 56" src="https://user-images.githubusercontent.com/90916211/198264406-af5f5ee7-a3a2-4394-b46b-6a48c52f091e.png">
<img width="1678" alt="Снимок экрана 2022-10-27 в 16 41 19" src="https://user-images.githubusercontent.com/90916211/198264433-925c7fca-7c5f-46cf-8be5-289141f1edef.png">
<img width="1297" alt="Снимок экрана 2022-10-27 в 16 42 15" src="https://user-images.githubusercontent.com/90916211/198264451-b46836bb-b6a4-4ac5-8f64-aad336b830b7.png">
<img width="1678" alt="Снимок экрана 2022-10-27 в 16 45 02" src="https://user-images.githubusercontent.com/90916211/198264651-c0f9b872-2457-4a39-8caf-8133f6071335.png">

### Desired Behavior

Would like to see imported rows in the table.

### Project Details

PackageVersion: 0.92.4

### Attachements

[sales_operator_list_nocodb_import2.csv](https://github.com/nocodb/nocodb/files/9878534/sales_operator_list_nocodb_import2.csv)

**Comment by wingkwong** [comment]
This doesn't look like 0.98.1. Please share your project info.

**Comment by wingkwong** [comment]
Looks fine.

![image](https://user-images.githubusercontent.com/35857179/198267126-2f2ce497-5621-4848-ad20-720c93b39304.png)

I think you are filtering the wrong column. By default it is taking the first column.

![image](https://user-images.githubusercontent.com/35857179/198267176-e8e76943-676c-4452-802b-d7026f40699b.png)

**Comment by Vlados1111** [comment]
Sorry, PackageVersion: 0.92.4

**Comment by Vlados1111** [comment]
No, I choose exactly tne "Name" column(

**Comment by wingkwong** [comment]
@Vlados1111 Consider to upgrade your version as it's not reproducible in latest version.

**Comment by Vlados1111** [comment]
Nocodb was upgraded to version 0.98.1. but the problem persists.
Now I don't see message about successful import. After clicking "Import" button Nocodb just thinks a little, then window disappears and nothing happens.
<img width="1673" alt="Снимок экрана 2022-10-27 в 19 35 28" src="https://user-images.githubusercontent.com/90916211/198301560-070e5cff-7aa0-48fb-96ac-c1be7bf44d05.png">

<img width="1677" alt="Снимок экрана 2022-10-27 в 19 36 45" src="https://user-images.githubusercontent.com/90916211/198301580-f7fe82b4-966f-4eac-8560-3c293c663d84.png">

**Comment by wingkwong** [comment]
Please try on 0.98.2. I was testing based on this version in which I've optimised import part. It may probably solve your issue.

**Comment by Vlados1111** [comment]
The problem was solved in 0.98.2, thank you very much!
