### ISSUE TITLE
🐛 Bug: Documentation online is not updated (at least release list)

### ISSUE THREAD

**Issue by mdunisch** [nocodb/nocodb#4211]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Open:
https://docs.nocodb.com/releases

### Desired Behavior

Releases List match https://github.com/nocodb/nocodb/releases, also the Docs have "0.97.0." in the header

### Project Details

Public nocodb documentation

**Comment by wingkwong** [comment]
Updated. https://github.com/nocodb/nocodb/commit/bac3d4794f8a47326ca594fa0bda00d24e767531
