### ISSUE TITLE
Enhancement: missing cursor when editing for Editors

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#423]
**Steps To Reproduce**
1. Create a table and add data using Owner role
2. Try edit data 
3. There is no cursor for editors (See screenshot 1 below) while there is for owners (See screenshot 2 below).
P.S. editors can edit data though.

**Expected behavior**
A cursor should be placed for better UX. 

Screenshot 1:  (Editor)
![image](https://user-images.githubusercontent.com/35857179/127995291-ad6f3655-9f55-41fa-9ada-dd1025f3a801.png)

Screenshot 2: (Owner)
![image](https://user-images.githubusercontent.com/35857179/127995383-3aaf09b3-678e-4945-b8f3-d976098ec1b8.png)

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.11.6**

**Comment by pranavxc** [comment]
Do you mean the cursor or the outline?

**Comment by wingkwong** [comment]
Both. Actually when editor double clicks the cell, it is expected to see the same thing as owner sees. Currently you will see the screenshot when editors double click, they can still edit but it is supposed to see the same UI in screenshot 2.

**Comment by pranavxc** [comment]
Fixed in `0.11.11`
