### ISSUE TITLE
🐛 Bug: AT import fails if other tables present in project

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#4230]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a project
Create a table
Try to import a project
Fetching data blocked at non-imported table

### Desired Behavior

We should only fetch data for imported tables

### Project Details

develop

**Comment by wingkwong** [comment]
Fixed in `0.99.0`
