### ISSUE TITLE
🐛 Bug: Formula ROUND does not work with divisions

### ISSUE THREAD

**Issue by distresscode** [nocodb/nocodb#4232]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have two column types, NUMBER and CURRENCY. If I create a third column type FORMULA and enter the following, all rows are hidden until I delete the formula column and then they would reappear. 

`ROUND({CURRENCY}/{NUMBER}, 2)`

It works with multiplication but not with division. Removing the PRECISION would only cause the Formula output to be hidden and not the entire table.

`ROUND({CURRENCY}/{NUMBER})`

### Desired Behavior

calculate the formula with precision input

### Project Details

App Title and Version: NocoDB 0.98.3
Package Version: com.nocodb.cloudronapp@1.5.2

**Comment by wingkwong** [comment]
LGTM. Please share your project info like the one below.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/35857179/198812624-7542da09-adc4-4510-aa67-1f07ad38d48a.png">

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.98.3**
```

**Comment by distresscode** [comment]
Node: **v16.13.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.98.3**

**Comment by distresscode** [comment]
![123](https://user-images.githubusercontent.com/2686608/198832429-3688eedd-752c-4c06-af2c-7716a39f2b3b.png)
![1234](https://user-images.githubusercontent.com/2686608/198832431-d4d05f20-680a-4e5c-b305-bd93afcfdbc9.png)

**Comment by fmartingr** [comment]
Hello,

just wanted to report a similar (but not the same) problem using `ROUND` with divisions. It works well until I try to round up with decimals:

- `ROUND({Price}+({Price}*({VAT}/100)))` works as expected
- `ROUND({Price}+({Price}*({VAT}/100)), x)` (where x is a number) does not raise an error, but after saving **all rows in the frontend disappear**. (Data is still there, just not shown, no errors on the console). After removing the second parameter from `ROUND` all rows come back.
