### ISSUE TITLE
🔦 Feature: Click on chip in many-to-many relation coloumn to go to the related row

### ISSUE THREAD

**Issue by RahulR100** [nocodb/nocodb#4243]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When I have a many-to-many relationship, I would like to click on the chips that show up in the column to be taken to the specific record in the other table that is linked.

Ex: I have a tasks <-> members table. On the members page I can see the tasks each member is assigned however I cant click on each of the tasks to go view the details of the task. I would like to do this as I have a lot of tasks assigned and don't want people to have to go to a different table and search for it all the time.

### Suggested Solution

Clicking on a chip in a many-one, many-many opens the related task in a new tab.

**Comment by pauljura** [comment]
+1 I would also find this useful

**Comment by dstala** [comment]
Links field now doesn't display the chip but shows rollup count instead; from within linked records modal - you can expand any record you wish to investigate further.
