### ISSUE TITLE
🔦 Feature: Resolve comments

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#4256]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Hi! I'd like to have the ability to resolve a record's comments so that the comment count lessens/disappears. 

### Suggested Solution

Have some kind of checkbox or "Resolved button"

**Comment by salim-b** [comment]
@DarkPhoenix2704 Should this feature be included in v0.250.1? I cannot see any UI for *resolving* comments, only deletion is implemented.

Resolving basically would mean hiding a comment but keeping its data; there would also need to be UI to view resolved (i.e. hidden) comments and allowing them to be reopened (i.e. unhidden).

**Comment by DarkPhoenix2704** [comment]
Resolve comments is currently limited to NocoDB Cloud.

**Comment by salim-b** [comment]
Ok, I see.
