### ISSUE TITLE
🔦 Feature: Mention team members in comments

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#4257]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Hi! Now that record URLs are possible, I'd love to have the ability to mention team members in the comments, and have a notification sent to them that they've been mentioned in a record. 

### Suggested Solution

Airtable implementation: 
![image](https://user-images.githubusercontent.com/55474996/199298731-8b2fc67e-d07d-41d4-9f5c-2668fc0a4e24.png)

**Comment by dalekirkwood** [comment]
Hey All, any idea when this will be on SH?
