### ISSUE TITLE
🐛 Bug: Unauthorized projects should not be listed

### ISSUE THREAD

**Issue by taophp** [nocodb/nocodb#4265]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When logging with an user with low rights, I can see all the projects, including the ones on which I have no access.

### Desired Behavior

The user should not see names of the projects on which he has no right.

### Project Details

NocoDB used as docker : ture
Version: 0.98.3
Database : SQLite3
Projects created by clicking : New project

**Comment by wingkwong** [comment]
Covered in https://github.com/nocodb/nocodb/pull/4134
