### ISSUE TITLE
🐛 Bug: Form validation failed

### ISSUE THREAD

**Issue by Entmatix** [nocodb/nocodb#4276]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. In any table create a new column.
2. Set any column name.
3. Select "Column type" "LinkToAnotherRecord", but DO NOT save column.
4. Select other type of column (I've tried Single Line Text, Long Text, Attachment) for this column (say you've changed your mind and would like to set another type of column or you just misclicked).
5. Try to save column.
6. Get "Form validation failed".

### Desired Behavior

Column should be successfully saved with the latest column type.

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.98.3**

### Attachements

<img width="880" alt="Screenshot 2022-11-04 at 10 59 11" src="https://user-images.githubusercontent.com/96371327/199922413-ecd725cf-2800-4ff5-8721-713626d2e740.png">

**Comment by wingkwong** [comment]
Able to reproduce.
