### ISSUE TITLE
Theme settings not consistent across browsers

### ISSUE THREAD

**Issue by arladmin** [nocodb/nocodb#429]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.11.10**

**Steps To Reproduce**
1. Log into nocodb
2. Change any theme settings (e.g. from light mode to dark)
3. Open nocodb app again, in another browser/incognito and log in
4. Theme settings are same as last time, and not the updated ones

**Expected behavior**
The new theme settings should remain persistent

**Comment by pranavcbalan** [comment]
Currently we are persisting it on browser level(in localstorage)..... May be going ahead we will persist theme settings under metadb(mapped to user)

**Comment by candideu** [comment]
> Currently we are persisting it on browser level(in localstorage)..... May be going ahead we will persist theme settings under metadb(mapped to user)

I'm building a public-facing database, and it would be nice if my custom theme persisted in the "Share View" pages and embedded database. Right now, they're just blue, but I want the colour to match the rest of my website.
