### ISSUE TITLE
enhancement: inconsistent views with Long Text columns with line break

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#430]
Long text is not consistent in the grid view and in edit view. The API is fine though. See screenshots for better understanding.

**Steps To Reproduce**
1. Create a column with Long text type
2. Input two paragraph, separated by a new line
3. Save
4. In grid view, it combines as a long paragraph
5. In edit view, it shows two paragraphs as expected

**Expected behavior**
Both view should be consistent. (i.e. with new lines)

**Screenshots**

Grid view:
![image](https://user-images.githubusercontent.com/35857179/128368051-61366898-af59-4e29-8429-95ea15db77b3.png)

Edit view:
![image](https://user-images.githubusercontent.com/35857179/128368102-ff5f28cc-79dc-4ad5-a2be-b2fdb87b9ab5.png)

Node: **v16.5.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.11.10**

**Comment by pranavxc** [comment]
Resolved in `0.11.11`
