### ISSUE TITLE
Tests (Playwright): Break test if un-expected network error message received

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4300]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Some of the errors observed during execution of E2E tests, if unexpected - should be caught.

### Desired Behavior

- Hook for network error (ignore the one's expected as per test scenario)
  

### Project Details

Development

**Comment by mustafapc19** [comment]
Closing. Tracking this in this [issue](https://github.com/nocodb/nocodb/issues/4277)
