### ISSUE TITLE
🐛 Bug: Text in GridView gets deleted at the end while inputting text in SingleLineText cell

### ISSUE THREAD

**Issue by spaudanjo** [nocodb/nocodb#4303]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

* Interacted in GridView with a SingleLineText cell
* text then gets randomly cut off from time to time at the end (my last typed characters get removed)

### Desired Behavior

Text does not get(apparently) randomly cut of when interacting with SingleLineText cells (not tested for other cell types)

### Project Details

* Tested this on Heroku deployment (deployment done on 25th of October 2022, with Heroku Install button on readme). 

### Attachements

https://user-images.githubusercontent.com/249210/200313016-258ef47c-0a5d-4832-b023-5c8ff919e1bd.mov

**Comment by pranavxc** [comment]
Could be duplicate of https://github.com/nocodb/nocodb/issues/4103

**Comment by wingkwong** [comment]
Can you show the project info?

**Comment by wingkwong** [comment]
Closing - see above issue.
