### ISSUE TITLE
🔦 Feature: default Inflection

### ISSUE THREAD

**Issue by lublak** [nocodb/nocodb#4308]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Since I don't need the function on any project and I have to keep switching it around. It would be handy if you can set it permanently.

### Suggested Solution

An option or environment variable to set this.

**Comment by wingkwong** [comment]
@lublak Sorry. I couldn't understand what you try to achieve. When you create the project, you can change the inflection here.

![image](https://user-images.githubusercontent.com/35857179/201635702-cda6e1b8-1794-4d6b-9838-37b4c052c3f7.png)

**Comment by lublak** [comment]
@wingkwong Actually, only that there is an option to set this by default. Currently I have to change this for every project because I don't want inflation.
An option that changes the default value would be handy.

**Comment by wingkwong** [comment]
So instead of using `camerlize` as the default one, you want to have a ENV variable to change the default to `None` right?

**Comment by lublak** [comment]
@wingkwong yes! Sorry that I am so bad at explaining. ^^"

**Comment by dstala** [comment]
default now set to `none`
