### ISSUE TITLE
🔦 Feature: parent_id primary key

### ISSUE THREAD

**Issue by lublak** [nocodb/nocodb#4319]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I currently have two tables.
Parent and child.
Parent has a has many on the child.
So there is a column at the child with the parent id. On the one hand I want to set this column as primary key. But on the other hand I want to add another column. Both columns then form a unique data set.

### Suggested Solution

~~Postgres has a very simple column editor. Evnetull you can introduce something like this in nocodb.would make the primary key setting here easier. (especially with multiple columns) and I think the whole editing is easier.~~

Allow also the parent_id as primary key.

**Comment by lublak** [comment]
![image](https://user-images.githubusercontent.com/44057030/200554612-6c128e9f-aa42-418a-96a2-b24785b9835c.png)
Currently it is completely unsupported. The display is then a bit strange. On the one hand, only a primary key is displayed. On the other hand I can set the primary key as primary key (which of course does nothing).

**Comment by wingkwong** [comment]
I think you're mixing up [Primary Value](https://docs.nocodb.com/setup-and-usages/primary-value) and [Primary Key](https://docs.nocodb.com/setup-and-usages/primary-key). 

Currently you can have multiple primary keys. When you create / edit a column, you can check NN (Not null) and PK (Primary Key).

![image](https://user-images.githubusercontent.com/35857179/201579538-e79ea37a-cfb5-450c-8457-8bb007d5c5a2.png)

**Comment by lublak** [comment]
@wingkwong Oh, I guess you're right. I think I messed up a bit there. Thanks for the clarification.

**Comment by wingkwong** [comment]
@lublak 

> Allow also the parent_id as primary key.

About that, `parent_id` is of `ForeignKey` type which almost always allows duplicates (since you're using HasMany). I don't think it is a good choice to choose it as a part of Primary keys. Do you mind to elaborate more about your use case with more details?

**Comment by lublak** [comment]
@wingkwong With me it is so that two columns result in the primary key.
Once the parent_id and once an additional identifkationswert, the name.
That means each name exists only once for parent_id.
Example:

parent_id, name
1, firstname
1, secondname
1, thirdname
1, firstname <- not allowed
2, firstname
2, secondname
2, thirdname

**Comment by wingkwong** [comment]
Seems your use case is more on One-to-One relationship.

**Comment by lublak** [comment]
@wingkwong 
no of course not. because for each parent_id several names may exist.
![image](https://user-images.githubusercontent.com/44057030/201628829-7c6764c4-bb8b-4d33-95bf-259ff2511d1a.png)
![image](https://user-images.githubusercontent.com/44057030/201629062-021f044d-1ffd-405b-9b15-b69e4123df3d.png)
Here is a example from me directly: Here is only the parent_id with the name Unique.
Here: Parent_id + element = Unique.
Only Parent_id? Not unique
Only element? Not unique
For each parent there are several children with different names that must be unique (but only per parent).
This means that in a new line of the parent, the same names may be assigned.

**Comment by dstala** [comment]
@wingkwong can this problem be now with we supporting formula column as display value column?

**Comment by o1lab** [comment]
Could be closed. It about having a unique formula columns coupled with mix of values from current table and relational table. This we achieve in the release after 0.105
