### ISSUE TITLE
🐛 Bug: Socket hang up when importing from Airtable

### ISSUE THREAD

**Issue by itay-sgh** [nocodb/nocodb#4326]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

* set up nocodb locally through docker-compose with pg - https://docs.nocodb.com/getting-started/installation#docker-compose
* Adding new table from Airtable
* Sometime after importing the first table I get "socket hang up" on the "Quick Import - AIRTABLE" modal
* Eventually see "socket hang up" on the logs

### Desired Behavior

* Connection retry and continue to import data from Airtable

### Project Details

docker-compose pg from nocodb repository - https://docs.nocodb.com/getting-started/installation#docker-compose

**Comment by mertmit** [comment]
Thank you for reporting this, confirmed this happens for long imports(import process still continue in background), I will implement a fix.

**Comment by itay-sgh** [comment]
Thanks for the quick response. Do you have an estimation when it should be resolved? We can't move forward with the migration till this one is fixed.

**Comment by itay-sgh** [comment]
Hey @mertmit have you made progress with this one?

**Comment by wingkwong** [comment]
Fixed in `0.100.1`.
