### ISSUE TITLE
🐛 Bug: Unusable for large databases

### ISSUE THREAD

**Issue by quidnu** [nocodb/nocodb#4327]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a database with millions of rows. When trying to view the database in NocoDB it can take several minutes for the data to appear (spinner). This is because the code calls "count(*)" which requires iterating over every row in the database. "count(*)" is inherently slow in SQL on large databases; there is no way to do it that will give interactive performance on a large database.

I think the relevant call to "count(*)" through "getCount" is  nc_configureFields in job.ts.

### Desired Behavior

The data should appear instantly for database of any size. On large databases "count(*)" should not be called and page numbers should be "1 of ?". One problem here is that the "first" page doesn't make sense without an "order by" clause in SQL and that also requires traversing all of the rows.

 Alternatively you should be able to cancel loading and manually disable rows from appearing until you can set filters that will only show a subset of the data.

### Project Details

docker (latest as of a few days ago)
ubuntu 22.10
postgres (docker) / sqlite

**Comment by o1lab** [comment]
Duplicate #4287
