### ISSUE TITLE
🐛 Bug: cell data disappears after page refresh

### ISSUE THREAD

**Issue by distresscode** [nocodb/nocodb#4329]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I'm creating a new row and adding some data either by copy/pasting data into cells or typing them. If I refresh the page or relog, some data in certain cells just disappear! 

Column types are: singlelinetext, currency, number

### Desired Behavior

retain cell data

### Project Details

Node: **v16.13.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.98.4**

### Attachements

![noco_1](https://user-images.githubusercontent.com/2686608/200664046-b5eb62bb-49c6-4119-a37f-692c46702955.png)
![noco_2](https://user-images.githubusercontent.com/2686608/200664042-f1af44e4-87fe-484a-a852-1c4a45923a9e.png)

**Comment by dstala** [comment]
tried it in below environment & couldn't reproduce. could you help us with more details about your setup? if you can share a screen recording with network tab open, it would be great!

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.98.4**

**Comment by distresscode** [comment]
I tested three browsers (edge, brave, firefox) and it's only happening on firefox. I disabled all extensions on firefox and it still caused data loss. I'm running firefox in strict mode so maybe that has something to do with it. In the network tab, I get the following error: https://domainc.com/socket.io/?EIO=4&transport=polling&t=OHTAMbv

**Comment by dstala** [comment]
could reproduce in firefox. thanks for narrowing it down for us @distresscode

**Comment by distresscode** [comment]
It's not related to strict mode. I tried default ff (standard protection) and issue persisted.

**Comment by dstala** [comment]
@distresscode issue is no more observed in v0.100.2; please reopen this issue if you observe this again. Thanks for your support!

**Comment by distresscode** [comment]
@dstala issue is back - data is getting wiped in firefox 109.0 (64-bit).

Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.101.2**
com.nocodb.cloudronapp@1.9.1
