### ISSUE TITLE
sign up disable

### ISSUE THREAD

**Issue by clubeplus** [nocodb/nocodb#4330]
Hello, how do I disable registration in the panel, before logging in?

**Comment by o1lab** [comment]
Set `NC_INVITE_ONLY_SIGNUP ` in env variable. Read the [docs](https://docs.nocodb.com/getting-started/installation#environment-variables).

**Comment by clubeplus** [comment]
Where can I edit the variables, I can't find the location, I installed it via docker

**Comment by prononext** [comment]
The env does not work anymore on  0.202.8 and even using the admin menu checking "Allow signup only using invite url"
The signup link is still there, but gives interal server error. 

**Would be really nice to have the signup link dissapear on the login page somehow!**
