### ISSUE TITLE
🔦 Feature: For Linked Record modal - display more information, not just primary key & value

### ISSUE THREAD

**Issue by fangjiyuan** [nocodb/nocodb#4335]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

link record only can see key value, we can add more info in sheetlist?
![196948254-20a8cc32-1f7e-4c1e-8351-8adcf10fdfe6](https://user-images.githubusercontent.com/36502693/200811589-d567b2c0-0085-4bc8-bd98-96a096723764.png)

### Suggested Solution

link record only can see key value, we can add more info in sheetlist?

**Comment by dstala** [comment]
@fangjiyuan - Primary value is displayed on the link record modal. On hove, primary-key is displayed additionally.
You can re-configure primary value to a different column if required. 
https://docs.nocodb.com/setup-and-usages/primary-value#how-to-set-primary-value-

Displaying additional information on this card is not in the roadmap currently. You can help us with more details about use-case for such.

**Comment by lublak** [comment]
So in twas gibts auch schon ein feature request:
https://github.com/nocodb/nocodb/issues/4305

**Comment by fangjiyuan** [comment]
> @fangjiyuan - Primary value is displayed on the link record modal. On hover, primary-key is displayed additionally. You can re-configure primary value to a different column if required. https://docs.nocodb.com/setup-and-usages/primary-value#how-to-set-primary-value-
I try to  re-configure primary value to a different column ,but the  column which i want use is a column of linktoanothertable ,
its seems like i can't configure primary value to this column.

my suggest is  link record can display the primary value and  also display other useful info like so :

![image](https://user-images.githubusercontent.com/36502693/200987981-f6519f7d-b043-479b-a339-bcae3542b772.png)

**Comment by ServiceDog** [comment]
Bumping this, here is our use case.

We're using NocoDB for requirements management. We have a table for Level 3 requirements and a table for Level 4 requirements.

The L4 requirements table has a column for linking to a "Parent" in the L3 Table.

![image](https://user-images.githubusercontent.com/6334638/208745610-dec1f3b9-6c01-4a37-b6eb-22106a866191.png)

Currently, to link to a parent, this is what we see:

![image](https://user-images.githubusercontent.com/6334638/208745684-3956f4ae-b3b0-43ef-b299-6b52225e20a2.png)

We would love to be able to view and filter on a second column. In this case , the second column would be the "Text" column, so we can identify the correct L3 to link to without having to open a new tab and copy over the label ID into this filter.

**Comment by dstala** [comment]
release v0.202.0 has more information being displayed in linked records modal. 4 additional fields apart from display value are listed on the card.

https://docs.nocodb.com/fields/field-types/links-based/links/#list-linked-records

**Comment by ServiceDog** [comment]
> release v0.202.0 has more information being displayed in linked records modal. 4 additional fields apart from display value are listed on the card.
> 
> https://docs.nocodb.com/fields/field-types/links-based/links/#list-linked-records

Beautiful, thank you! Love what you all are doing
