### ISSUE TITLE
Project Metadata Sync messes up the schema

### ISSUE THREAD

**Issue by arladmin** [nocodb/nocodb#434]
Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.11.11**

**Steps To Reproduce**
1. Create 2 separate projects (using internal database) with table(s) in them
2. Go To ```Project Metadata``` and click on ```Sync Tables```
3. In the UI, you can now see that all the tables of both the projects are available, in each of the project.
4. These tables are also available for complete modification from the projects other than their parent.

**Expected behavior**
Unless it's a properly structured design decision, which doesn't seem to be the current case, intermingling of tables from other projects should not be possible at all.

**Comment by pranavxc** [comment]
Fixed in `0.11.15`
