### ISSUE TITLE
NC_INVITE_ONLY_SIGNUP

### ISSUE THREAD

**Issue by clubeplus** [nocodb/nocodb#4342]
The problem still persists :(
![WhatsApp Image 2022-11-09 at 12 43 07](https://user-images.githubusercontent.com/117778218/200875593-786a4a3f-8783-4809-8d93-65666bcc6a96.jpeg)

**Comment by clubeplus** [comment]
I'm installing like this, is it correct?

docker run -d -p 8080:8080 \
     -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
     -e NC_INVITE_ONLY_SIGNUP="true" \
     nocodb/nocodb:latest

**Comment by o1lab** [comment]
Installation is fine. The page of signup is available but not the signup. On attempting signup, this is what one sees.

<img width="567" alt="Screenshot 2022-11-09 at 15 49 40" src="https://user-images.githubusercontent.com/5435402/200876634-782e2e7b-74f6-40ce-a7c6-e2912b1d85ab.png">

**Comment by clubeplus** [comment]
PERFECT!!!!!!!!!
