### ISSUE TITLE
🔦 Feature: File / photo : upload via URL

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4347]
### Discussed in https://github.com/nocodb/nocodb/discussions/4346

<div type='discussions-op-text'>

<sup>Originally posted by **Dont-ask-for-it** November  9, 2022</sup>
Would save a step when image is already found via web (no need to save image on my computer first)</div>

**Comment by cocoonkid** [comment]
oh yes, for using badges from an API gitlab and others that would be soooo nice!

**Comment by WarWolf47** [comment]
Figma Link added in Project Field

**Comment by DarkPhoenix2704** [comment]
Available in latest release
