### ISSUE TITLE
🐛 Bug: Unwanted record insertion when creating a form view

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#4358]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Select a table.
2. Go to "Create a view" and select "Form".
3. A form editor with a "submit" button appears.
4. Click on the "Submit" button.
5. A new empty record just got inserted into the table.

### Desired Behavior

When a user want to create a form, there is a "submit" button at the bottom of the form. If a user clicks on this button, an empty records gets inserted into the actual database table and this is quite annoying.
I prefer having new entries only if the form is shared and somebody fills the form.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.98.4**

**Comment by o1lab** [comment]
I was not able to reproduce this scenario. Can you share more details or a video please.

**Comment by okaeiz** [comment]
Here is what I meant by "unwanted record insertion".

Imagine we have a table like this:


![Screenshot (16)](https://user-images.githubusercontent.com/100111649/201649836-d2c1d91f-4825-4e3b-bba4-7760bf896cc1.png)


Then we create a form, and we are editing this form. We do NOT share this form yet. We are just playing around with it, and we click on "submit".


![Screenshot (17)](https://user-images.githubusercontent.com/100111649/201650048-c28c6d8e-6b75-4f06-99ef-350fcc9ff0e8.png)


Here it comes! A new empty record has been inserted into the table.


![Screenshot (18)](https://user-images.githubusercontent.com/100111649/201650155-54be8742-5cd8-4a7a-9af2-4a8b99f0f6fc.png)


This is annoying because when we are editing the form, we are using it for experimenting. We do not want any record because we are just testing the form.

**Comment by o1lab** [comment]
By hitting submit - what is being tried to achieve here? If its just muscle memory - we cannot help :)

Form shared or without shared is meant for creating rows.
