### ISSUE TITLE
🔦 Feature: Support SQL views

### ISSUE THREAD

**Issue by quidnu** [nocodb/nocodb#4363]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

SQL views are like SQL queries that can be treated as tables. They allow you have a filtered/transformed table and are widely used in databases and they should be visible/useable in NocoDB.

### Suggested Solution

Treat SQL views as any other SQL table.

**Comment by o1lab** [comment]
SQL views are already show in table list and treated as grid view
