### ISSUE TITLE
🔦 Feature: View based Api key forever 

### ISSUE THREAD

**Issue by lublak** [nocodb/nocodb#4368]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently there is a possibility to get an api key for a view. Unfortunately, this is only valid for one day.
I need a key that I can generate that is limited to one view and does not expire.
![image](https://user-images.githubusercontent.com/44057030/201337409-90988f7d-3dd1-418e-b030-95814681320e.png)

### Suggested Solution

![image](https://user-images.githubusercontent.com/44057030/201337657-84b2ae5a-a8b1-4bad-a3d3-d9106c375c3d.png)
That you can create an api key for each view as well as a global api key. Or that the keys simply no longer expire.

In addition, it would be practical to have no code snipped but a simple view with:
url: http://
xc-auth: dfgdcdvfv

(so without curl, wget or javascript, but only the bare information)

### Additional Context
![image](https://user-images.githubusercontent.com/44057030/201338017-99ed6a04-94d5-49ba-b784-f6d2bb02cbcf.png)

**Comment by o1lab** [comment]
Use [api token](https://docs.nocodb.com/developer-resources/accessing-apis#api-token)

**Comment by o1lab** [comment]
And why API token for only one view ?

**Comment by lublak** [comment]
@o1lab Because I insert this in an excel file and make it available to a user. But I do not want that he theoretically gets access to all data via this key.
That would be a big security problem. And could so nocodb actually no longer use.

**Comment by o1lab** [comment]
Do you think you use our share view with password for this? It will have [an api](https://all-apis.nocodb.com/#tag/DB-view-share/operation/db-view-share-list)

**Comment by lublak** [comment]
@o1lab The user himself does not use nocodb. It is used as an internal tool to connect databases, create tables and connect rest interfaces to excel. Da share is an access to the view itself. But this is of no use if the user wants to edit the data directly in excel. Diagrams. Pivots. etc.
Many functionalities are used directly in Excel. Power Query is used for the import of json.
