### ISSUE TITLE
🐛 Bug: Can't set FK as Not Null

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4370]
Need to see if something has changed with foreign key creation

### Discussed in https://github.com/nocodb/nocodb/discussions/4251

<div type='discussions-op-text'>

<sup>Originally posted by **ahtned** November  1, 2022</sup>
Recently updated to 0.98.3 and now FK / lookup columns are required. I can uncheck the NN box and save but it just resets. Any help would be appreciated, thanks!
![Capture54325234](https://user-images.githubusercontent.com/107133240/199238283-e53c9796-9484-4291-af68-31dc1e7e5a53.PNG)
</div>

**Comment by ahtned** [comment]
Found a workaround by editing the "req" column for the FK in the nc_columns_v2 table from true to false and then forcing a rebuild and deployment on digital ocean.
