### ISSUE TITLE
🐛 Bug: Docker terminal not accessible

### ISSUE THREAD

**Issue by Dont-ask-for-it** [nocodb/nocodb#4372]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Pull and install NocoDB on a Synology with Docker app (nocodb/nocodb:latest)
Go into ther NocoDB container on docker App 
Open a new terminal

![image](https://user-images.githubusercontent.com/5061749/201411185-6ab8c2d3-329a-49bd-8cb4-319fcdd8982b.png)

### Desired Behavior

To work

### Project Details

NocoDB latest

### Attachements

![Animation](https://user-images.githubusercontent.com/5061749/201411805-4cec2611-4eea-4092-b8d8-a891d380bb40.gif)

**Comment by djmaze** [comment]
@Dont-ask-for-it There is no `bash` in the container. You need to choose `sh`.
