### ISSUE TITLE
🔦 Feature: Support Oracle Database For Connection To An External Database

### ISSUE THREAD

**Issue by gbonazzoli** [nocodb/nocodb#4375]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

"Support Oracle Database For Connection To An External Database" seems simple If you have a database abstraction layer between the main code and the actual RDBMS implementation.

And all the others the abstarction layes has.

### Suggested Solution

<img width="947" alt="Screenshot 2022-11-12 at 05 51 32" src="https://user-images.githubusercontent.com/17742862/201457951-9eb921ee-770d-4358-8c1c-917f815c2352.png">

**Comment by wingkwong** [comment]
Closing as duplicate as https://github.com/nocodb/nocodb/issues/1730
