### ISSUE TITLE
No data in my tables from a schema

### ISSUE THREAD

**Issue by Cailrorn** [nocodb/nocodb#438]
Hello,

I am under Microsoft SQL Server and I followed the following tutorial to access my tables which are presented under a schema

https://www.youtube.com/watch?v=rS0NRwRCjx0&t=30s

![image](https://user-images.githubusercontent.com/6215266/128686719-11ba53c4-2ba2-4a0f-9a37-6ab27de9d6d8.png)

The problem is that once the connection is successful, the application shows me the name of my tables, but without "_" and without data 

![image](https://user-images.githubusercontent.com/6215266/128686482-211d07f6-e248-4fc6-8dcd-ab8e2660eef8.png)

Can you please take a look?

Thank you

**Comment by pranavxc** [comment]
Can you share the actual column names?

**Comment by Cailrorn** [comment]
> Can you share the actual column names?

![image](https://user-images.githubusercontent.com/6215266/128686854-cb90815f-b359-4c02-a3c9-ef1956e710eb.png)

**Comment by pranavxc** [comment]
Fixed in `0.11.14`
