### ISSUE TITLE
🐛 Bug: number sorting and filters don't work when column was changed from text to something numberic

### ISSUE THREAD

**Issue by conorpp** [nocodb/nocodb#4380]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a column with a text like type ("SingleLineText") and input rows "4.2", "30.1", "2.0".
2. Change column to Decimal.
3. Sort 9->1 and see the sorting is not correct.

It will still sort alphabetically instead of numerically.

### Desired Behavior

It should sort numerically if the column type is numeric.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.98.4**

### Attachements

<img width="758" alt="Screen Shot 2022-11-13 at 2 35 10 PM" src="https://user-images.githubusercontent.com/3942133/201543533-b749bfbb-11d7-49fe-a935-b741f66a202d.png">
<img width="407" alt="Screen Shot 2022-11-13 at 2 35 06 PM" src="https://user-images.githubusercontent.com/3942133/201543535-0cbe32f3-f6e2-4015-9eab-71b8f517ae2e.png">

**Comment by wingkwong** [comment]
Able to reproduce. It seems it happens in SQLite only.
