### ISSUE TITLE
🐛 Bug: Importing CSV without data results in infinity wait

### ISSUE THREAD

**Issue by krokodylek** [nocodb/nocodb#4383]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

v0.98.4
Add new table via CSV import,
Upload CSV file,
Uncheck "Import Data",
Wait.......
![image](https://user-images.githubusercontent.com/34084110/201551500-1372a8cf-ffba-441e-ad9f-70b4ec138c01.png)

### Desired Behavior

This should add new table with imported headers without data

### Project Details

98.4, postgres 14, arm64

**Comment by wingkwong** [comment]
Can you share the csv to me via Discord (My ID: 3278)?

**Comment by wingkwong** [comment]
Able to reproduce the issue.
