### ISSUE TITLE
🐛 Bug: Changing the Persian interface font  

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#4389]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

First off, similar issues had been raised for this purpose by me; but they have been closed for some reason.

Related issues:
#1610
#2154
#2302

1. Change the interface to Persian (فارسی).
2. See? There are tons of great fonts for Persian language. I suggested [this one](https://github.com/rastikerdar/vazirmatn) which is a beautiful Persian font and I think it would better if the Persian interface of NocoDB had it.
 

### Desired Behavior

I will be grateful if NocoDB developers could change the font. The current one is not that bad but when it comes to sharing forms to other people, a beautiful font will definitely help.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.98.4**

**Comment by o1lab** [comment]
Sorry, we do not have much experience with Persian fonts. And the font suggested by you has a custom license. We would like to avoid it. Hope you understand. And please do see on how to make contribution of Persian strings [here](https://docs.nocodb.com/engineering/translation).
