### ISSUE TITLE
Feature: edit external database connection details

### ISSUE THREAD

**Issue by dismantl** [nocodb/nocodb#439]
I want to change the credentials I'm using to connect to an external database, but I can't seem to find a way to do that. Since I have all the NocoDB users attached to that particular project, I'l rather not have to delete and recreate the project because then I would have to redo all the user accounts and permissions.

**Comment by o1lab** [comment]
We added this feature while ago.

Go to :
1. Right top menu
2. Themes
3. Double click on themes tab header
4. Edit project opens up :adjacent to themes tab :)

**Comment by o1lab** [comment]
https://user-images.githubusercontent.com/5435402/131334542-bb6d7ced-6582-44fb-9b23-0692e1c45080.mov

**Comment by bonacci-johannes** [comment]
Please update how to change the credentials, the manual above is outdated :/

**Comment by artem-snopkov** [comment]
+1

**Comment by tomdevlive** [comment]
+1

**Comment by dstala** [comment]
feature live now in pre-release https://github.com/nocodb/nocodb/releases/tag/0.101.0-beta.0

procedure captured here
https://docs.nocodb.com/setup-and-usages/meta-management#edit-external-database-configuration-parameters
