### ISSUE TITLE
🐛 Bug: Windows Binary

### ISSUE THREAD

**Issue by hachete01** [nocodb/nocodb#4394]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

on Windows, download executable from http://get.nocodb.com/win-x64... upon executing it the command prompt gives the following error: 

Error: Cannot find module 'C:\snapshot\pkg-executable\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node'
Require stack:
- C:\snapshot\pkg-executable\node_modules\sqlite3\lib\sqlite3-binding.js
- C:\snapshot\pkg-executable\node_modules\sqlite3\lib\sqlite3.js
- C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js
- C:\snapshot\pkg-executable\index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\pkg-executable\node_modules\sqlite3\lib\sqlite3-binding.js:4:17)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\snapshot\\pkg-executable\\node_modules\\sqlite3\\lib\\sqlite3-binding.js',
    'C:\\snapshot\\pkg-executable\\node_modules\\sqlite3\\lib\\sqlite3.js',
    'C:\\snapshot\\pkg-executable\\node_modules\\nocodb\\dist\\bundle.js',
    'C:\\snapshot\\pkg-executable\\index.js'
  ],
  pkg: true
}

### Desired Behavior

Started application after visiting localhost:8080 on the browser.

### Project Details

NocoDB on Windows with executable with no environment variables previously installed. Latest version. Previously working version was from last week.

**Comment by pranavxc** [comment]
Can you download it from here - https://github.com/nocodb/nocodb/releases/tag/0.98.4 and confirm? It's working for me, if still failing can you share more details like your Windows version, processor, etc.

**Comment by hachete01** [comment]
Just tried it (noco-win-x64), but the issue persists. My details:

Windows 11 Pro
Version 10.0.22621 Build 22621
x64-based PC
12th Gen Intel(R) Core(TM) i7-12800H, 2400 Mhz, 14 Core(s), 20 LP

Here is the error:

Error: Cannot find module 'C:\snapshot\pkg-executable\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node'
Require stack:
- C:\snapshot\pkg-executable\node_modules\sqlite3\lib\sqlite3-binding.js
- C:\snapshot\pkg-executable\node_modules\sqlite3\lib\sqlite3.js
- C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js
- C:\snapshot\pkg-executable\index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\pkg-executable\node_modules\sqlite3\lib\sqlite3-binding.js:4:17)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\snapshot\\pkg-executable\\node_modules\\sqlite3\\lib\\sqlite3-binding.js',
    'C:\\snapshot\\pkg-executable\\node_modules\\sqlite3\\lib\\sqlite3.js',
    'C:\\snapshot\\pkg-executable\\node_modules\\nocodb\\dist\\bundle.js',
    'C:\\snapshot\\pkg-executable\\index.js'
  ],
  pkg: true
}

**Comment by luffs** [comment]
I get the same error message. The earlier release, 0.98.3 works without issue.

> Can you download it from here - https://github.com/nocodb/nocodb/releases/tag/0.98.4 and confirm? It's working for me, if still failing can you share more details like your Windows version, processor, how you downloaded the latest version, etc?

Maybe it's working for you because you have the folder/file C:\snapshot\pkg-executable\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node ?

**Comment by hachete01** [comment]
Yes, I can confirm that 0.98.3 is working without issue. I did not download it though, I used a previously downloaded binary in my desktop. I did confirm that the file corresponds to v. 0.98.3

**Comment by candideu** [comment]
@hachete01 Quick question: do you use the Windows binary like you would a regular desktop app?

**Comment by hachete01** [comment]
> @hachete01 Quick question: do you use the Windows binary like you would a regular desktop app?

Well, yes... It opens in the browser.

**Comment by pranavxc** [comment]
Verified in Windows 11 Home edition x64

![image](https://user-images.githubusercontent.com/61551451/204968485-836d3144-2f10-4a25-8ef3-bfedf7e3b29f.png)

**Comment by hachete01** [comment]
The issue appears fixed. Tested on release v. 0.100.2
