### ISSUE TITLE
🔦 Feature: Private S3 Bucket Support

### ISSUE THREAD

**Issue by kusold** [nocodb/nocodb#4398]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

**User Story:** As a user, I would like to attach documents containing PII data. As an organization, we absolutely cannot allow PII data to be public.

There are numerous other use cases for sensitive files that we may want to upload, but cannot allow to be public.

### Suggested Solution

nocodb should allow private uploads and return [presigned](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) urls with configurable expiration times.

### Additional Context

This is closely related to https://github.com/nocodb/nocodb/issues/2956.

**Comment by azhirov** [comment]
Up

**Comment by DarkPhoenix2704** [comment]
Presigned Url support is added for all the storage plugins in https://github.com/nocodb/nocodb/pull/9104
