### ISSUE TITLE
🔦 Feature: Form View fields based on conditional logic

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4404]
### Discussed in https://github.com/nocodb/nocodb/discussions/4403

<div type='discussions-op-text'>

<sup>Originally posted by **roelofsdevries** November 16, 2022</sup>
Would anyone know if there exists a possibility in NocoDB for setting conditions for certain entries in form view? Would be very interesting if I could conditional logic to show or hide certain fields based on the entry in previous fields. Thus far, I haven't managed to find a way to do so. 

Many thanks in advance!</div>

**Comment by dstala** [comment]
discourse related discussion
https://community.nocodb.com/t/conditional-values/927/2

**Comment by LucBerge** [comment]
I am also looking for this feature. @dstala is it a work in progress?
