### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of “text/html”. Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by ramsigmoid** [nocodb/nocodb#4416]
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of “text/html”. Strict MIME type checking is enforced for module scripts per HTML spec.
When running nocodb.

NocoDb - Latest release ([Development setup - NocoDB](https://docs.nocodb.com/engineering/development-setup/))
OS :- Ubuntu 22.04
Node :- v16.18.1
Npm :- 8.19.2

**Comment by wingkwong** [comment]
Did you see the issue when running locally?

**Comment by ramsigmoid** [comment]
yes, in latest build on chrome console

**Comment by ramsigmoid** [comment]
any update or previous build which we can use?

**Comment by wingkwong** [comment]
Also using latest chrome but didn't see such error. Can you show which page throws this error?

**Comment by ramsigmoid** [comment]
![Captur1e](https://user-images.githubusercontent.com/98207372/202838116-e661f770-927b-428c-872b-fd9d4a75e65b.JPG)
![Capture](https://user-images.githubusercontent.com/98207372/202838117-fbe93e96-9c9d-4c56-975e-d4f990319482.JPG)

Hi, please see the attach screenshot.
Also, let me know the steps you are following, will follow the same steps and build if you can provide.

**Comment by ramsigmoid** [comment]
> Also using latest chrome but didn't see such error. Can you show which page throws this error?

Tell me your machine config and build (AWS), will deploy on same machine.

**Comment by wingkwong** [comment]
I'm running it on my local machine only, not AWS, with the steps under Development Setup in the documentation. However, what is the reason to setup the development environment on a remote machine rather than using docker or nodejs app?

**Comment by ramsigmoid** [comment]
> I'm running it on my local machine only, not on AWS, with the steps under Development Setup in the documentation. However, what is the reason to setup the development environment on a remote machine rather than using docker or nodejs app?

We need to make some changes, so using development setup. But it failed.

**Comment by ramsigmoid** [comment]
Problem is with multiple node version was install, we have identify and solve the same.
