### ISSUE TITLE
🐛 Bug: fail to connect MSSQL db

### ISSUE THREAD

**Issue by Naude555** [nocodb/nocodb#4419]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

running docker with the MySql command on the server

docker run -d --name nocodb-mysql \
    -v "$(pwd)"/nocodb:/usr/app/data/ \
    -p 8080:8080 \
    -e NC_DB="mysql2://host.docker.internal:3306?u=root&p=password&d=d1" \
    nocodb/nocodb:latest

When trying to add mssql db connection I recive the following error: 
$ npm install mssql --save
Cannot find module './msal-node.cjs.production.min.js'
Require stack:
- /usr/src/app/node_modules/@azure/msal-node/dist/index.js
- /usr/src/app/node_modules/@azure/identity/dist/index.js
- /usr/src/app/node_modules/tedious/lib/connection.js
- /usr/src/app/node_modules/tedious/lib/tedious.js
- /usr/src/app/node_modules/knex/lib/dialects/mssql/index.js
- /usr/src/app/node_modules/knex/lib/dialects/index.js
- /usr/src/app/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /usr/src/app/node_modules/knex/lib/knex-builder/Knex.js
- /usr/src/app/node_modules/knex/lib/index.js
- /usr/src/app/node_modules/knex/knex.js
- /usr/src/app/docker/main.js
    at Client_MSSQL.initializeDriver (/usr/src/app/node_modules/knex/lib/client.js:194:13)
    at new Client (/usr/src/app/node_modules/knex/lib/client.js:75:12)
    at new Client_MSSQL (/usr/src/app/node_modules/knex/lib/dialects/mssql/index.js:25:5)
    at knex (/usr/src/app/node_modules/knex/lib/knex-builder/Knex.js:16:28)
    at new KnexClient (/usr/src/app/docker/main.js:1:120317)
    at new d (/usr/src/app/docker/main.js:1:621857)
    at Function.create (/usr/src/app/docker/main.js:1:94409)
    at Function.testConnection (/usr/src/app/docker/main.js:1:315070)
    at y (/usr/src/app/docker/main.js:1:1467185)
    at /usr/src/app/docker/main.js:1:39698
    
I tried running locally connecting to the db same as above and try to connect to the MSSQL db and did not get the same error.. 
    
I tried installing mssql as suggested but no avail. Also should the docker not address this issue?

### Desired Behavior

What steps can I take to get my MSSQL db connected?

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.98.4**

**Comment by Naude555** [comment]
I tried changing my approch and instead of setting up MySql as production enviroment I tried setting up MSSQL as my production DB 
Still got this error 

 - /usr/src/app/docker/main.js
    at Client_MSSQL.initializeDriver (/usr/src/app/node_modules/knex/lib/client.js:194:13)
    at new Client (/usr/src/app/node_modules/knex/lib/client.js:75:12)
    at new Client_MSSQL (/usr/src/app/node_modules/knex/lib/dialects/mssql/index.js:25:5)
    at knex (/usr/src/app/node_modules/knex/lib/knex-builder/Knex.js:16:28)
    at t.default (/usr/src/app/docker/main.js:1:434092)
    at new g (/usr/src/app/docker/main.js:1:548224)
    at new s (/usr/src/app/docker/main.js:1:1337428)
    at new U (/usr/src/app/docker/main.js:1:6259)
    at Function.init (/usr/src/app/docker/main.js:1:6907)
    at /usr/src/app/docker/main.js:1:593813

**Comment by wingkwong** [comment]
Didn't reproduce the issue. Mind to record a video?

**Comment by Naude555** [comment]
Like said earlier, it works fine locally but not on the server, don't know if its because I run linux 20.04 locally and 18.04 on the server. Both is in a docker container, the other difference is locally I have node 12 and on the server node 16

Local working version:
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.98.1**

Server not working version
Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.98.4**


https://user-images.githubusercontent.com/60476722/202665765-47aae0df-5613-45c3-ab06-a48aedc9105e.mp4



![image](https://user-images.githubusercontent.com/60476722/202664904-77c26cdb-fb08-428b-bb1c-d75838abc0b5.png)

Running locally and trying to connect to MSSQL gives the expected Failure: Failed to connect 
![image](https://user-images.githubusercontent.com/60476722/202666780-b9914f22-7028-4d80-9c52-b7cd16676b7e.png)

**Comment by Naude555** [comment]
I finally figured it out the problem is in the latest docker image. I changed my docker image on the server back to 0.98.1 and it worked as expected.

**Comment by wingkwong** [comment]
preliminary findings:

- the problem exists in `0.98.4` only. probably it's related to knex upgrade.
- `msal-node.cjs.production.min.js` is missing in `/usr/src/app/node_modules/@azure/msal-node/dist/index.js`
- the file may be removed from `modclean`

**Comment by wingkwong** [comment]
Covered [here](https://github.com/nocodb/nocodb/pull/4426/commits/ca55217e4741508268083ef369fa81dc7a6e2a95).
