### ISSUE TITLE
Shared View GET API

### ISSUE THREAD

**Issue by sameer119** [nocodb/nocodb#442]
Currently there is only a post api for the shared view with view_id and other params.. if you can open a GET api for the same views it would be a great feature as it will restrict users to view data of other users as all data are getting stored for in same table.

**Comment by akctba** [comment]
Hi,
I think this is the same issue as #253
https://github.com/nocodb/nocodb/issues/253

**Comment by wingkwong** [comment]
Closing this issue as it's available now in latest version.

See dbViewRow [here](https://apis.nocodb.com/#operation/db-view-row-list) for more.
