### ISSUE TITLE
🐛 Bug: Problem with CORS when accessing via browser

### ISSUE THREAD

**Issue by EVAUTOAI** [nocodb/nocodb#4427]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I'm trying to get data from NocoDB but i can't because the call is blocked by CORS policy. I can get data from Postman but not from my React project.
![image](https://user-images.githubusercontent.com/97277014/202690253-9435a5d3-9612-4bb4-a44c-6d680f5318f6.png)

Below are whats been installed:
nocodb - 0.92.4
npm - 8.19.1
cors - 2.8.5

I have also updated the nocodb-seed/index.js file to include the below code, but to no use:
(async () => {
	try {
		const cors = require("cors");
        const app = require('express')();
        const {Noco} = require("nocodb");
		app.use(cors());
        app.use(await Noco.init({}));
		console.log(`Visit : localhost:${process.env.PORT}/dashboard`)
		app.listen(8040, '0.0.0.0');
	} catch(e) {
		console.log(e)
	}
})()

### Desired Behavior

Able to access the APIs without facing CORS error in browser

### Project Details

Not using docker
Database used - mysql
OS - Mac
nocodb - 0.92.4
npm - 8.19.1
cors - 2.8.5

**Comment by dstala** [comment]
@EVAUTOAI Please reopen this thread if issue still persists with v0.202.5+
