### ISSUE TITLE
🔦 Feature: API needed for DB table column list

### ISSUE THREAD

**Issue by ashgard071** [nocodb/nocodb#4433]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

The DB table column API currently includes an endpoint to Create, Update, Delete or set as primary Column. The response of the create endpoint includes a list of all current columns. However, there is not endpoint to list all current column directly. That would be useful though. 

### Suggested Solution

Add Column List endpoint to DB Table Column.

**Comment by o1lab** [comment]
Can be found [here](https://all-apis.nocodb.com/#tag/DB-table/operation/db-table-list)
