### ISSUE TITLE
🔦 Feature: Row level access control based on `Created By` column

### ISSUE THREAD

**Issue by liuyangedu** [nocodb/nocodb#4437]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I create a table that many people will fill in.
I just want the people edit the row they edit and cannot see the row added by others

### Suggested Solution

add a new type of column that fill the username of user automatically
then add a filter to show the CURRENT user

**Comment by mayeulk** [comment]
I discuss some possible ways to get this, at the backend level, here: https://github.com/nocodb/nocodb/issues/6076

**Comment by dstala** [comment]
To be tracked under

[🔦 Feature: Row / Column base permission, last edited by / updated by and audit log](https://github.com/nocodb/nocodb/issues/5075)
