### ISSUE TITLE
🐛 Bug: Previously shared views need to be re-shared with 0.98.4

### ISSUE THREAD

**Issue by s-h-a-r-d** [nocodb/nocodb#4446]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a form view from a table using 0.96.4 version (anything older should work as well).
- Share this view and copy the link.
- Upgrade NocoDB to 0.98.4
- Try to access the shared view using the copied link.

### Desired Behavior

Form view expected to work as previously, but only a blank page opens.

Workaround: Go to the shared view and click "Share View" button again.

As the url and everything else stays the same, I assume it just "enables" what the latest version disabled.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.98.4**

**Comment by dstala** [comment]
@s-h-a-r-d thanks for bringing this to our notice. if you notice this issue in newer releases, do reopen this issue again.
