### ISSUE TITLE
🐛 Bug: Filtering on single select empty cells are ignored 

### ISSUE THREAD

**Issue by davidpfahler** [nocodb/nocodb#4462]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a table with a single select column
2. Create rows with no value selected in this single select column
3. Create a filter for this single select column with one of these comparisons: "is empty" OR "is not equal" to some value
4. Result: No rows where the single select column is empty are returned

### Desired Behavior

The filter should return all rows where the single select column is empty.

### Project Details

NocoDB used in docker: yes

**Comment by wingkwong** [comment]
Can you share the [project info](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-) please?

**Comment by davidpfahler** [comment]
Here is the project info:

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.98.4**

**Comment by davidpfahler** [comment]
https://user-images.githubusercontent.com/908242/203331327-b5ae48a6-0eb2-4d22-9084-debc476161f5.mp4

**Comment by wingkwong** [comment]
Preliminary findings:

The difference between `isEmpty` and `isNull` is that 

- originally when a new row is created, data is null if there is no input. (`isEmpty = false` and `isNull = true`)
- update the data
- clear the data
- now the data is considered as empty. (`isEmpty = true` and `isNull = false`)

However, when the single select field is cleared, the value turns `NULL`. Therefore, `isEmpty` is never in use for single select case.
