### ISSUE TITLE
🐛 Bug: Creating tables via API is resulting in problems

### ISSUE THREAD

**Issue by sinksar** [nocodb/nocodb#4464]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Hi,
I have tried the API from Thunder Client and faced this issue, after I created (on purpose) a wrong project 

1. [POST] /api/v1/db/meta/projects/
   Body: {
  "id": "pubslic-3",
  "title": "public",
  "order": 0,
  "is_meta": true,
  "prefix": "pp_mue",
  "external": true
}
1. [GET] /api/v1/db/meta/projects/
Response: {
  "msg": "Cannot read properties of null (reading 'deleted')"
}

Docker Log:
TypeError: Cannot read properties of null (reading 'deleted')
    at /usr/src/app/docker/main.js:1:57386
    at Array.filter (<anonymous>)
    at Function.list (/usr/src/app/docker/main.js:1:57369)
    at async P (/usr/src/app/docker/main.js:1:1364291)
    at async /usr/src/app/docker/main.js:1:39692

### Desired Behavior

Should return the right list of Projects

### Project Details

NocoDB used as docker: true
NocoDB version: latest
Database used: sqlite3

**Comment by dstala** [comment]
Handled as in v0.202.5
