### ISSUE TITLE
Bug: Mysql meta migration fails

### ISSUE THREAD

**Issue by pranavxc** [nocodb/nocodb#447]
![image](https://user-images.githubusercontent.com/61551451/129018207-f028c39e-3e0b-4089-87a7-b562d7432939.png)

**Comment by pranavxc** [comment]
fixed in `v0.11.16`

**Comment by Cailrorn** [comment]
Same error on the table "nc_models" after update of nocodb at v0.11.16

![image](https://user-images.githubusercontent.com/6215266/129213201-8e2b076c-dbcd-456e-a0d4-5778fae77cc0.png)

event-loop-stats not found, ignoring event loop metrics...
migration file "project" failed
migration failed with error: alter table `nc_models` add index `nc_models_db_alias_title_index`(`db_alias`, `title`) - La clé est trop longue. Longueur maximale: 1000

**Comment by pranavxc** [comment]
@Cailrorn Please recreate the metadb using following queries

```SQL
DROP DATABASE IF EXISTS <YOUR_DATABASE_NAME>;
CREATE DATABASE <YOUR_DATABAE_NAME> DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
```

For more info refer - https://stackoverflow.com/a/42497309

**Comment by o1lab** [comment]
Feel free to reopen if issue still persists after using above sugggestion.
