### ISSUE TITLE
Feature: Update Webhooks aren't triggered on M2M Table Updates (or LInkToAnotherRecord)

### ISSUE THREAD

**Issue by tsteffek** [nocodb/nocodb#4474]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a Table with an M2M field
- set up a webhook that gets triggered on update
- update M2M column
- no webhook was sent

### Desired Behavior

A webhook should be triggered if an M2M column is updated, as there should be no distinguishment between those columns

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.98.4**

**Comment by dstala** [comment]
related: https://github.com/nocodb/nocodb/issues/4475

**Comment by ashgard071** [comment]
> ### Please confirm if bug report does NOT exists already ?
> * [x]  I confirm there is no existing issue for this
> 
> ### Steps to reproduce ?
> * Create a Table with an M2M field
> * set up a webhook that gets triggered on update
> * update M2M column
> * no webhook was sent
> 
> ### Desired Behavior
> A webhook should be triggered if an M2M column is updated, as there should be no distinguishment between those columns
> 
> ### Project Details
> Node: **v16.17.1** Arch: **x64** Platform: **linux** Docker: **false** Database: **pg** ProjectOnRootDB: **false** RootDB: **pg** PackageVersion: **0.98.4**
> 
> ### Attachements
> _No response_

Please note that this also applies if the field has the type Formula.

**Comment by Eggwise** [comment]
What is the status on this ?

It would be logical to trigger webhook updates when you change the value of a (m2m) column....

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/6817
