### ISSUE TITLE
🐛 Bug: Feeding any character when date cell in-focus, clears cell contents

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4493]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- click on date column cell
- type any character
- cell contents disappear. they reappear on reload/refresh

### Desired Behavior

- ideally we should allow feeding in date manually. if its hard, let us not make contents disappear on key stroke

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.99.0**

**Comment by wingkwong** [comment]
This issue also applies on other computed cells such as LTAR, formula, etc.
