### ISSUE TITLE
🐛 Bug: Related database is not shown correctly since upgrade from 0.99.0 to 0.99.1

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#4500]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create table "Arztadressen"
2. Create table "Impfbuch Werner"
3. Create lookup-connection
4. The desired picture from "Arztadressen" ist not shown in "Impfbuch Werner" anymore since upgrade vom 0.99.0 to 0.99.1
5. The entries in other fields are weired to

**One interesting thing is if i move back to 0.99.0 everything works again. So it seems the database itself is not damaged.**

### Desired Behavior

The pictures and other fields from related base should be shown correctly

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.99.1**

### Attachements

![Noco 1](https://user-images.githubusercontent.com/20600342/204031530-ac79b1e1-8d17-4d61-a9db-7c9670f1ee75.jpg)
![Noco 2](https://user-images.githubusercontent.com/20600342/204031535-acc3d484-e9e9-49e3-a892-02da8938f99b.jpg)

**Comment by o1lab** [comment]
What is the relation between these two tables : "Arztadressen", "Impfbuch Werner"

**Comment by WeT-Klb** [comment]
It´s a Lookup relation. The "Impfbuch Werner (injection book)" has a lookup relation to "Arztadressen (doctor adress).
On Pic one you can see "Impfbuch Werner" got the name, the picture and the adress from table "Arztadressen".
I can change the doctor name inside table "Impfbuch" - but the picture won´t show up anmyore.

This is what it should look like:
![Noco 3](https://user-images.githubusercontent.com/20600342/204052629-bdb7cef0-6a6c-42ae-a8f5-dc12e8ff9313.jpg)

![Noco 4](https://user-images.githubusercontent.com/20600342/204052644-251f4f8d-3877-4445-b483-40c9eac894e7.jpg)
