### ISSUE TITLE
Feature : Column options

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4523]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] Duplicate
- [x]  Insert left
- [x]  Insert right
- [x]  Sort asc
- [x]  Sort Desc
- [x]  Hide field
- [x] Fields/Sort/Filter - to have number badge

### Desired Behavior

.

### Project Details

Develop

**Comment by dstala** [comment]
Released in v0.100.0
