### ISSUE TITLE
🐛 Bug: Division in formula display nothing

### ISSUE THREAD

**Issue by chxp** [nocodb/nocodb#4527]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

## Original csv file:

region,steplength,steps
6.2-3.1,0.5,3.1
5.5-3.0,0.1,2.5
5.5-3.0,0.02,2.5

## Detail:
- region is a string SingleSelect
- steplenth is a enum SingleSelect
- steps is a formula.

- I want to calculate the steps of by using `(LEFT({region},3)-RIGHT({region},3))/{steplength}`, however, it displays nothing and the whole data disappears as follows:
![图片](https://user-images.githubusercontent.com/14882692/204482293-5e037026-68d2-48ec-8d3e-469eba1ec0a2.png)

- The formular of `(LEFT({region},3)-RIGHT({region},3))` works fine as follows:
![图片](https://user-images.githubusercontent.com/14882692/204482607-d5b06e36-d13d-4d27-a5dc-499bd2149cf7.png)

### Desired Behavior

What happened?

### Project Details

NocoDB used as docker: true
NocoDB version: latest
Database used in NC_DB URL: mysql5.7
OS: Ubuntu 20.04.5 LTS

**Comment by wingkwong** [comment]
Tried those 2 given formulaes and they both work fine. I'm wondering why the first region doesn't have a chip. Please check the server log to see if there is any error.

![image](https://user-images.githubusercontent.com/35857179/204492291-24ee4bb0-2be4-40ba-a63a-41a578551d99.png)

 Also you may edit the column to see if `6.2-3.1` is one of the options.

![image](https://user-images.githubusercontent.com/35857179/204492720-17d2b9fe-5d90-458e-a5c1-6844044dc6cf.png)

**Comment by wingkwong** [comment]
Can you try the following

1. edit the column to see if 6.2-3.1 is one of the options.
2. try importing to another table and see if it can be still reproducible.

**Comment by chxp** [comment]
1. 6.2-3.1 is one of the options.
2. I try to create a new example, but it makes me more confused (col2/col3 still SingleSelect):
- `{col2}+{col3}`
![图片](https://user-images.githubusercontent.com/14882692/204521454-0050ba40-3205-47d0-9568-2f32c5ea8aa6.png)

- `{col2}*{col3}`
![图片](https://user-images.githubusercontent.com/14882692/204521581-762388be-ea74-4df6-a770-c128087321d1.png)

- `{col2}/{col3}` still noting.

**Comment by wingkwong** [comment]
I don't think that command is related. I can reproduce the issue. Will take a look later.

**Comment by chxp** [comment]
The problem still exists in the new version.

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.100.2**

**Comment by wingkwong** [comment]
@chxp Can you record a video? This is what I get.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/35857179/206727083-95e4c9ba-918c-4fb0-88b0-404482017bf0.png">
