### ISSUE TITLE
🐛 Bug: On going issues in develop ( >0.99.2 )

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4529]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [ ] Quick tab opening. After 7th or 8th tab switching breaks.
- [x] Opening project sometimes - doesn't open the page it completely.

### Desired Behavior

.

### Project Details

Develop

**Comment by mertmit** [comment]
Second one resolved with https://github.com/nocodb/nocodb/commit/6f0deb5e657a3214da61f9228fa1fa5e00441dd9
This commit is in multiple-source branch but that should be fine as it should be in soon.

**Comment by o1lab** [comment]
@mertmit : cool. We plan to have multi source thing after 0.100 release.
