### ISSUE TITLE
postgres - Connection terminated unexpectedly

### ISSUE THREAD

**Issue by ejose19** [nocodb/nocodb#453]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.11.16**

**Steps To Reproduce**
1. Make sporadic insert requests to nocodb
2. Notice how some of them randomly fail with: 400: `insert into ...  - Connection terminated unexpectedly`

**Expected behavior**
No sporadic errors should occur

**Additional info**

On postgres, I see many `LOG:  could not receive data from client: Connection reset by peer`

Relevant upstream `knex` issues: https://github.com/knex/knex/issues/3523 https://github.com/knex/knex/issues/3447

**Comment by o1lab** [comment]
Where is the postgres hosted ? Is this like a free version by a cloud provider, if so any ideas on connection pool limit and such.

@pranavxc : do you suspect this is new changes related to handle non-public schema may be ?

**Comment by pranavxc** [comment]
@o1lab no it's not related to that..... some knex related issue I think...  

Maybe setting min pool size to `0` may be a workaround for the issue - https://github.com/knex/knex/issues/3523#issuecomment-722574083

**Comment by o1lab** [comment]
@ejose19 : please try @pranavxc suggested link.

**Comment by ejose19** [comment]
@o1lab @pranavxc The proposed solution looks like a `knex` configuration change, however I don't see anything in `nocodb` to configure that (neither on UI nor ENV), how should I proceed?

**Comment by pranavcbalan** [comment]
If you are setting `NC_DB` , add following in url .... `&pool.min=0`

**Comment by ejose19** [comment]
Thanks, I see that feature was added in last version: https://github.com/nocodb/nocodb/commit/3cc0cecad2562680e61fb559276e3cf7a7b95bbf, I can submit a PR to mention in docs this feature (in the `Environment Variables` entry)

**Comment by ejose19** [comment]
Actually, I think https://github.com/nocodb/nocodb/issues/425#issuecomment-893488379 is the best approach here, since the config is complex and there will be edge cases that the conversion won't do

**Comment by pranavcbalan** [comment]
> Thanks, I see that feature was added in last version: [3cc0cec](https://github.com/nocodb/nocodb/commit/3cc0cecad2562680e61fb559276e3cf7a7b95bbf), I can submit a PR to mention in docs this feature (in the `Environment Variables` entry)
> 
> EDIT: Regarding the issue itself, it doesn't seem to work:
> 
> ```
> 2021-08-12T15:40:57.980362094Z Error: Tarn: opt.min must be an integer >= 0
> 2021-08-12T15:40:57.980422334Z     at new Pool (/usr/src/app/node_modules/tarn/dist/Pool.js:20:19)
> 2021-08-12T15:40:57.980431818Z     at Client_PG.initializePool (/usr/src/app/node_modules/knex/lib/client.js:329:17)
> 2021-08-12T15:40:57.980437531Z     at Client_PG.Client (/usr/src/app/node_modules/knex/lib/client.js:71:12)
> 2021-08-12T15:40:57.980442826Z     at new Client_PG (/usr/src/app/node_modules/knex/lib/dialects/postgres/index.js:16:10)
> 2021-08-12T15:40:57.980448332Z     at Object.Knex [as default] (/usr/src/app/node_modules/knex/lib/knex.js:14:28)
> 2021-08-12T15:40:57.980453723Z     at Object.t.default [as XKnex] (/usr/src/app/docker/main.js:2:179377)
> 2021-08-12T15:40:57.980459176Z     at new A (/usr/src/app/docker/main.js:2:230118)
> 2021-08-12T15:40:57.980464472Z     at new n (/usr/src/app/docker/main.js:2:720262)
> 2021-08-12T15:40:57.980469692Z     at new C (/usr/src/app/docker/main.js:2:27347)
> 2021-08-12T15:40:57.980474927Z     at Function.init (/usr/src/app/docker/main.js:2:28118)
> ```
> 
> All config is stored as string, but some of these are strict in the input type.
> https://github.com/nocodb/nocodb/blob/3cc0cecad2562680e61fb559276e3cf7a7b95bbf/packages/nocodb/src/lib/utils/NcConfigFactory.ts#L315-L327
> 
> Should we add some conversion logic to this function?

Oh yeah the type will be always string, boolean type I'm handling by checking the value .... Number also we can do but it may cause some problem as well..... About json also I thought it may become confusing for people that's why I didn't implemented... Anyways will add that feature.

An another approach will be a json file like by default we will look for a nc_config.json in the tool directory if it present we can use that. In addition to that we can make that file path configurable with a env var like `NC_DB_JSON_FILE`

**Comment by ejose19** [comment]
I can contribute this feature, probably will want to keep both `NC_DB_JSON` & `NC_DB_JSON_FILE` as using first one may be the only option under PaaS.

**Comment by o1lab** [comment]
> An another approach will be a json file like by default we will look for a nc_config.json in the tool directory if it present we can use that. In addition to that we can make that file path configurable with a env var like `NC_DB_JSON_FILE`

Have a look at this environment variable ```DATABASE_URL_FILE```
