### ISSUE TITLE
🐛 Bug: Super admin is not assigned. How to asign and change admin?

### ISSUE THREAD

**Issue by bonacci-johannes** [nocodb/nocodb#4532]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

The first created user doesn't has the super admin role.
How to assign or change a super-admin, once nocodb is already set up and running

### Desired Behavior

Improved Usermanagment

### Project Details

NocoDB used as docker: true
NocoDB version: 0.99.2
Database used in NC_DB URL: postgres

**Comment by mertmit** [comment]
You can use environment variables `NC_ADMIN_EMAIL` and `NC_ADMIN_PASSWORD` to recover / create superuser for existing instance.
reference: #2760

Please let me know if this works out for you.

**Comment by bonacci-johannes** [comment]
Yes it worked for me. Thanks a lot for the quick support.
