### ISSUE TITLE
🔦 Feature: LinkRecord modal, additional information in link cards like vika

### ISSUE THREAD

**Issue by catcherxuefeng** [nocodb/nocodb#4539]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

[![iDeJF.png](https://i.328888.xyz/img/2022/11/30/iDeJF.png)](https://imgloc.com/i/iDeJF)

### Suggested Solution

![iD6DH.png](https://i.328888.xyz/img/2022/11/30/iD6DH.png)

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/issues/4335
