### ISSUE TITLE
🔦 Feature: LinkToAnotherRecord with a filter set of records

### ISSUE THREAD

**Issue by liuyangedu** [nocodb/nocodb#4541]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When I add a link in table A to table B, I need to constrain the link to a view.
for example
I have a USER table, and a PROJECT table
PROJECT table has a link to USER table
I just want to link to some certain user but not all

### Suggested Solution

I`d like to create a view of a table and the link can constrain the link to a view but not the whole table

**Comment by dstala** [comment]
will be tracked under https://github.com/nocodb/nocodb/issues/4899
