### ISSUE TITLE
🐛 Bug: Grid cell in edit mode - mouse based operations doesn't work

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4542]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a text / number cell
- Add some contents - say `abcdefgh`
- [ ] Click using mouse in between text - should place cursor appropriately. Only way to move now is using arrow keys
- [x] Ctrl-A: should select all text in the cell
- [ ] Double click- should select word under focus
- [ ] Click and drag- should select text selected

### Desired Behavior

mouse based operations expected to work as described 

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.99.2**

**Comment by wingkwong** [comment]
@dstala Can you verify the above items on `feat/keyboard-manoeuvre`. I think I've resolved some of them.

**Comment by dstala** [comment]
@wingkwong all 3 are open still in `feat/keyboard-manoeuvre`

**Comment by dstala** [comment]
with commit 4820c09f65e34d84dc8eeb24a634c7abd7841d48, `cmd-a` to emulate select-all work fine in `feat/keyboard-manoeuvre`
