### ISSUE TITLE
🐛 Bug: Error occur when updating a record on page 2 and switching to another table

### ISSUE THREAD

**Issue by davidpfahler** [nocodb/nocodb#4557]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create one table (Sheet-1) with a date column
2. Fill Sheet-1 until it has a second page
3. Create a second table (Sheet-2)
4. Go to page 2 of Sheet-1 and select a date in a cell in the date column
5. Immediately navigate to Sheet-1

Result: Errors occur, sometimes leading to the date cell not being update. For details, see video attached.

### Desired Behavior

No errors occur and records are updated successfully.

### Project Details

This was tested in a local test environment with the following details: 

```
Node: **v16.17.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.100.0**
```

But it also occurs in production with postgres under the hood.

### Attachements

https://user-images.githubusercontent.com/908242/205058901-34629643-ba7a-464a-b76e-3149ea3f9568.mov

**Comment by o1lab** [comment]
Thank you for reporting the issue. Was this in 0.99.2 as well ?

**Comment by davidpfahler** [comment]
Both in `0.99.2` (in production) and `0.100.0` (local, as you see above.)

**Comment by o1lab** [comment]
Issue with rebasing a large PR - we should have the fix in next hour.

**Comment by davidpfahler** [comment]
Thank you very much for fixing this so swiftly! I really appreciate your fast response time.
