### ISSUE TITLE
Feature : Meta APIs

### ISSUE THREAD

**Issue by yesoreyeram** [nocodb/nocodb#457]
APIs to get projects list / project schema will be useful in long term. 

Thank you for the wonderful project ❤️ 

### Discussed in https://github.com/nocodb/nocodb/discussions/456

<div type='discussions-op-text'>

<sup>Originally posted by **yesoreyeram** August 12, 2021</sup>
Are there any REST APIs to get the schema/meta data about the project/table?</div>

**Comment by o1lab** [comment]
Meta apis are documented in https://all-apis.nocodb.com

**Comment by dengmingcong** [comment]
APIs listed in https://all-apis.nocodb.com/ are for v1 now, I finally found v2 from https://meta-apis-v2.nocodb.com/.
