### ISSUE TITLE
Enhancements: Keyboard & UX follow up's

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4573]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] Single select
  - [x] first click, it should be select mode; i should not see cursor
  - [x] double click, it should go to edit mode
  - [x] enter when in select mode - open options
  - [x] escape key, when in edit mode, should toggle to select mode
  - [x] when in select mode - should be able to navigate between cells using arrow keys
- [x] Enable auto focus on `project create` window; 
- [x] Ester egg for `show-more`: by default should show only `default`; enabling ester egg menu, show all options. for now keep it same for both xcdb & external db project. we can discuss with navi later if we need to show by default for external db project.
- [ ] Default value- should be able to configure without explicit quotes
- [ ] Default value- make it similar to grid cell (use picker/select options/...)
- [ ] Example was not displayed for datatype `number`
  
<img width="449" alt="Screenshot 2023-01-30 at 9 10 22 PM" src="https://user-images.githubusercontent.com/86527202/215523035-3d385a11-2393-4a2b-8976-a477e9aa9401.png">

- [x] Restrict height of long-text field. Currently it grows as text grows, making it difficult to work with grid
  - https://github.com/nocodb/nocodb/issues/4639
- [x] provide a default project name in `xcdb project create` as in case of `create project by connecting to external DB`
- [x] Invite team modal triggered from `Alt I` (after a table is created) : auto-focus on `Email` field
- [x] After closing invite menu, `Alt I` still opens invite URL window
- [x] Invite team modal : after inviting user, unable to close modal using `esc` key
- [x] Add new row `Alt R` : auto focus (edit mode) on first cell in newly added row
- [ ] Edit column menu : Column name is highlighted on opening menu. Click on `esc` first time should move away from edit mode for column name text box; clicking `esc` again should close modal
- [x] Cell : remove inner border for `single select` `multi-select` `duration` `long text` `JSON`
- [x] Sometimes, cursor movement is blocked due to a cell stuck in edit mode
- [x] For cell in edit mode (long text), add support for `home` and `end` key. Former should move to beginning of text, latter should move to end of it.
- [x] Right align cell for numerical fields (number, decimal, currency, duration, percent). Expanded form, should be left aligned : https://github.com/nocodb/nocodb/issues/204
- [x] Column edit modal: clicking on right hand empty space of column name input field, should disable text selection & move cursor to the end of text; also clicking in between text should place cursor in that position. Also applicable for rename modal
![Screenshot 2022-12-05 at 3 07 23 PM](https://user-images.githubusercontent.com/86527202/205603933-c2f81ddc-e8fc-47b5-bbfe-395763ab5a79.png)
- [x] duplicate table presence alert message not displayed during table rename (it is present only for table create)
  
<img width="681" alt="Screenshot 2022-12-09 at 6 47 04 AM" src="https://user-images.githubusercontent.com/86527202/206601296-0a0baceb-c5af-40e9-a309-9e638bb69c6d.png">
<img width="601" alt="Screenshot 2022-12-09 at 6 47 17 AM" src="https://user-images.githubusercontent.com/86527202/206601301-ed9e2f23-6b5f-4a1d-a8f7-779a2e7dbbe1.png">

- [ ] [to be discussed before staring on this] column create menu & edit menu - make it minimal
  
<img width="466" alt="Screenshot 2023-01-30 at 9 22 53 PM" src="https://user-images.githubusercontent.com/86527202/215526281-8d2a79ab-2b13-40b5-83f9-d56a7c5308c0.png">

### Desired Behavior

-

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.100.1**

**Comment by wingkwong** [comment]
Closing - the rest of the items will be tracked in 5013.
