### ISSUE TITLE
🔦 Feature: Extend support for Expanded row in Shared view

### ISSUE THREAD

**Issue by AlienHub** [nocodb/nocodb#4579]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I hope you can click on the data to view all fields in the right drawer under the sharing view.
![image](https://user-images.githubusercontent.com/44266450/205267141-f65fe84f-91ec-4d3c-931b-e13d3c5c83fd.png)

### Suggested Solution

-

**Comment by dstala** [comment]
duplicate; to be tracked under https://github.com/nocodb/nocodb/issues/2293
