### ISSUE TITLE
🐛 Bug: Use of space-bar in Shared grid view throws error 

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4580]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Open shared grid view link
- Press space key

Access control error - as space bar now tries to expand row 

### Desired Behavior

- No error

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.100.2**

**Comment by wingkwong** [comment]
May need to check if the cell can be editable by typing something.
