### ISSUE TITLE
🐛 Bug: Expert a string but recevied an array 

### ISSUE THREAD

**Issue by origyn-admin** [nocodb/nocodb#4589]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Upload XLS or XLSX to import a new table from URL

We obtain : Expert a string but recevied an array 

### Desired Behavior

imported data from XLS from an URL

### Project Details

NocoDB  version : 0.100.2

**Comment by wingkwong** [comment]
Please provide a sample URL for reproducing the issue.

**Comment by wingkwong** [comment]
Closing due to no feedback from user.
