### ISSUE TITLE
Upload csv for existing data not working,

### ISSUE THREAD

**Issue by ramsigmoid** [nocodb/nocodb#4600]
![image](https://user-images.githubusercontent.com/98207372/205598007-b03bd7da-e880-427d-bd5c-17430bfa76d9.png)

Issue with router.patch(
‘/api/v1/db/data/bulk/:orgs/:projectName/:tableName’,
apiMetrics,
ncMetaAclMw(bulkDataUpdate, ‘bulkDataUpdate’)
);

patch is not executing…Manually have called method and seems working fine…

Also in patch it should insert data if in sheet new data is there.

Node: v18.0.0
Arch: x64
Platform: linux
Docker: false
RootDB: sqlite3
PackageVersion: 0.100.2

**Comment by wingkwong** [comment]
The error is expected as the import is to insert the data to the target table. Patching with given keys is not available at this moment.

**Comment by dstala** [comment]
@ramsigmoid please re-open this issue if you have any additional queries.
raise a github feature request with additional details if you think this should be a feature within NocoDB
