### ISSUE TITLE
🐛 Bug: 1-click deploy to heroku is broken

### ISSUE THREAD

**Issue by ajonesw** [nocodb/nocodb#4602]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When deploying to Heroku no resources appear in the list and you are unable to go any further or deploy the app

<img width="878" alt="Screenshot of Google Chrome (05-12-2022, 12-02-34)" src="https://user-images.githubusercontent.com/6555333/205632891-0a5e9946-4a90-424f-b0f1-004c6e99ad59.png">

### Desired Behavior

Deploy to Heroku

### Project Details

Deploy to Heroku

**Comment by JHSheridan** [comment]
Can confirm. I'm experiencing the same issue as @ajonesw.

**Comment by wingkwong** [comment]
@ajonesw @JHSheridan Starting November 28, 2022, Heroku has removed free product. May I know if you've setup payment on Heroku (i.e. paid users)?

**Comment by ajonesw** [comment]
Wee have setup an active payment profile on Heroku and have an active card on the account yet it's still not letting us go any further or prompting us to add paid resources

--- original message ---
On December 7, 2022 at 8:40 AM GMT ***@***.*** wrote:



@ajonesw @JHSheridan Starting November 28, 2022, Heroku has removed free product. May I know if you've setup payment on Heroku (i.e. paid users)?

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by JHSheridan** [comment]
I was testing a nocodb instance with the free product. When they announced it was going away, I decided I would delete my free test instance, add my card info, and deploy a fresh instance on a paid plan.

That's when I bumped into this issue.

**Comment by wingkwong** [comment]
Just discussed with the team, we're removing it from Heroku. The corresponding content will be removed soon.

**Comment by ajonesw** [comment]
Less than ideal reply - we activated and linked our card details to a Heroku account that started charging us only to get started with your app.
Your response is simply — issue closed: Heroku doesn't work + use something else 

--- original message ---
On December 7, 2022 at 9:36 AM GMT ***@***.*** wrote:



Closed #4602 as completed.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by o1lab** [comment]
Heroku has been a long standing free service that was made unavailable recently. This is beyond our control unfortunately - having said that we will try to rework on what is required to make it work, but please understand you could also make a PR for these things. There are many many cloud providers and we would need the help of community too.

**Comment by ajonesw** [comment]
Appreciate the explanation. Wondering do you have any recommendations on which might be the easiest to set up and maintain 
We currently use Airtable and are looking for the simplest possible way to migrate to your app without managing servers. 
We would have opted for your Cloud hosted variant if this would have been available to reduce management costs 

--- original message ---
On December 7, 2022 at 12:39 PM GMT ***@***.*** wrote:



Heroku has been a long standing free service that was made unavailable recently. This is beyond our control unfortunately - having said that we will try to rework on what is required to make it work, but please understand you could also make a PR for these things. There are many many cloud providers and we would need the help of community too.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by o1lab** [comment]
Use digital ocean, spin up a droplet (server). Install docker and docker-compose on it. And run [this docker-compose](https://github.com/nocodb/nocodb/tree/develop/docker-compose/mysql) file. If you have never done it - it has learning curve. We are working on our cloud and you should be able to hear from us soon. Please [subscribe for](https://docs.google.com/forms/d/e/1FAIpQLSfKLe8Rcrq0uo2_jM5W1kbVBbzDiQ3IvlP8Iov61FTekVAvzA/viewform) the launch.
