### ISSUE TITLE
🐛 Bug: Setting primary value removes existing relations

### ISSUE THREAD

**Issue by xiamaz** [nocodb/nocodb#4606]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create nocodb with Tables A and B in a nocodb with postgres backend
2. Define a one-to-many relation from Table A to B
3. Change Primary Value in Table B
4. Observe that All existing relation entries between Table A and B are lost

### Desired Behavior

Changing primary value should not affect existing relations, as this could have unintended catastrophic consequences.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.99.2**

**Comment by folk-connect** [comment]
This is mostly a UI problem. I have seen sometimes that changing some metadata causes UI to show no rows. Better to check in DB if data is still there or not

**Comment by dstala** [comment]
I wasn't able to reproduce on `develop`. @pranavxc give it a try from your end.

**Comment by xiamaz** [comment]
Thanks for looking into this issue. I tested this again on two different systems running 0.99.2 and 0.100.2 and did not see the issue again. It might have been an issue in the UI as @folk-connect suggests.
