### ISSUE TITLE
Support same table names across projects

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#461]
Currently we can't have same table across projects given the existing structure. 

![image](https://user-images.githubusercontent.com/35857179/129510759-19eee28f-23d5-453e-8142-97ad57bbca8f.png)

**Steps To Reproduce**
1. Create a Project called Project A connecting to an external DB
2. Create a table called LandingPage in Project A
3. Create a Project called Project B connecting to an external DB
4. Create a table called LandingPage in Project B
5. It prompts an error
6. Refresh the page. LandingPage can be seen in Project B. Changing it would affect both projects. LandingPage in Project A & Project B should be different tables. 

**Suggestions**

Add a prefix in DB level like ``<project_prefix>_<table_name>`` so that we could have same table names across projects. In the frontend, it only shows ``<table_name>`` like current behavior. 

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.11.12**

**Comment by o1lab** [comment]
As discussed, if project is created by connecting to same external database then tables within them would be same.
