### ISSUE TITLE
🔦 Feature: UX improvement: Remove copy invite token button for registered users

### ISSUE THREAD

**Issue by vijayrathore8492** [nocodb/nocodb#4617]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In the current situation when you click on the actions button in front of a user under the user management screen, It opens up 
<img width="251" alt="Screenshot 2022-12-06 at 18 17 39" src="https://user-images.githubusercontent.com/17380265/205916726-94cef736-85b0-4f60-a6bc-2c524960f8f9.png">
a menu with 2 options (Resend Invite E-mail and Copy Invite URL). 

These options are redundant for already registered users.

### Suggested Solution

 For better UX and to reduce user confusion these options should only be shown for users that are not yet registered successfully.

**Comment by o1lab** [comment]
@vijayrathore8492 : can u please send a PR

**Comment by wingkwong** [comment]
fixed and will be available in the [next release](https://github.com/nocodb/nocodb/milestone/22).
