### ISSUE TITLE
🐛 Bug: Error comes whenever monaco editor is opened

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#4619]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

In console whenever monaco editor is opened error comes
![image](https://user-images.githubusercontent.com/86340924/205951153-03c66a3d-ac4c-4c35-9d2c-53d9d0e04ed4.png)

### Desired Behavior

Error should not come

### Project Details

Node: **v16.18.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.99.2**

**Comment by dstala** [comment]
No issue was observed with following configuration; need to try in `win32`

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.100.2**

**Comment by wingkwong** [comment]
Not sure if it is related. Previously there was a [PR](https://github.com/nocodb/nocodb/pull/4531) trying to resolve a monaco editor error on Windows platform but it was closed.

**Comment by AztrexDX** [comment]
try to edit in json field monaco editor and check console.

**Comment by mertmit** [comment]
I can't reproduce it using (Windows 10):
```
Node: **v16.14.1**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.100.2**
```
