### ISSUE TITLE
🐛 Bug: Default value automatically sets as NULL for SingleSelect

### ISSUE THREAD

**Issue by folk-connect** [nocodb/nocodb#4625]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a Single Select field with no option and save.
After that, edit the field and add options.
Try to save

Error shows up saying default value NULL is not an option
Same happens for SingleLineText fields also. NULL is automatically set.
If you  are unable to reproduce let me know and I'll provide some screenshots

One more similar issue is initial length type is set as 45 which is too low for most of the cases. Using some environment variable can we increase the default initial length of the column

### Desired Behavior

In my opinion, setting default value as String "NULL" is not meaningful. There is no need of setting default value for enum and varchar fields

### Project Details

Node: **v14.19.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.100.2**

**Comment by wingkwong** [comment]
> Create a Single Select field with no option and save.
> After that, edit the field and add options.
> Try to save

I believe you haven't inputted anything? `NULL` is the default value here because when you haven't selected any option, the cell value would be NULL. That's why you cannot leave the option blank. I don't see why there is no need of setting default value for it.

![image](https://user-images.githubusercontent.com/35857179/206120688-0d16867a-8496-4528-bbf6-6d0957b7255a.png)

**Comment by folk-connect** [comment]
NULL is actually not NULL but String "NULL". I am attaching video to make point more clear. This happens for SingleLineText as well when I try to edit that field

[screen-capture.webm](https://user-images.githubusercontent.com/113366228/206135456-78ae90cf-23c4-49e2-96cc-d62686ba7ae1.webm)

**Comment by wingkwong** [comment]
@folk-connect thanks for the video. It's more clear now. However, I couldn't see there is `NULL` under Default value. The project info indicates you're not using Docker. May I know how you setup NocoDB?

![image](https://user-images.githubusercontent.com/35857179/206148949-250ef4f4-5693-42d0-88e1-1e404d3afeef.png)

**Comment by folk-connect** [comment]
[screen-capture (1).webm](https://user-images.githubusercontent.com/113366228/206152040-195deb36-b0e2-4c9c-959b-9b518028dd19.webm)

I am using Digital ocean droplet with nocodb-seed repo. If there is an ideal configuration, please let me know and I will shift to that. The setup that you guys use to develop and test

**Comment by semmjon** [comment]
The error still occurs when importing a table (via a file -> Excel / CSV).

**Comment by folk-connect** [comment]
@mertmit I had a MariaDB instance. When I reported it, @wingkwong tested it and she wasn't able to reproduce it either on her machine. So I came to conclusion that it's mostly a MariaDB thing

**Comment by mertmit** [comment]
I confirm this issue is reproducible using MariaDB I will share updates here.
