### ISSUE TITLE
🔦 Feature: BLANK Formula

### ISSUE THREAD

**Issue by folk-connect** [nocodb/nocodb#4626]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

For LTAR fields, if we need to check that any field is empty or not (in a formula field), there seems to be no option for that. 
Right now I am using a workaround to check if respective foreign key id is greater than 0. See the screenshot for the same. Here ```Mobile``` is LTAR field and ```Mobile Number``` is SingleLineText Field
<img width="440" alt="image" src="https://user-images.githubusercontent.com/113366228/206139923-16747eeb-9eb6-4e6f-bb08-de7a2a5748b8.png">

### Suggested Solution

In Airtable, there is a special function for this ```BLANK()```. That can be implemented or anything similar

**Comment by samuraicow** [comment]
Following for updates!

**Comment by dstala** [comment]
Since the introduction of "Links" field (LTAR is now deprecated in NocoDB), we display linked record count & that can be used in formula.

Something like `IF(LinkField==0, TRUE(), FALSE())` works

Reopen this thread if that still doesn't solve your case
