### ISSUE TITLE
🐛 Bug: referenced Number is "null" if the Value in the other Table is 0

### ISSUE THREAD

**Issue by sasch901** [nocodb/nocodb#4628]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create two tables. Connect it. Referencing a Field as Number. If the Number in the referenced Table is Zero, the field is empty. 
Table 1: 
<img width="672" alt="image" src="https://user-images.githubusercontent.com/25210586/206151634-5d002ff3-88ed-4ec6-9141-1020da4000b9.png">

Table 2: 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/25210586/206151713-f43eef24-a5ff-4851-8654-fac842d679d3.png">
Here, in the First ROW should be "0" in the DisplayID Field

Also the Api is a "null" 
<img width="187" alt="Bildschirm­foto 2022-12-07 um 11 07 57" src="https://user-images.githubusercontent.com/25210586/206151221-67f8cc28-5f55-4cf2-8430-c0d83a0a3efc.png">

### Desired Behavior

make it Possible :D 

### Project Details

MySQLi
Node.JS

**Comment by dstala** [comment]
Observed with HM & MM; BT column type is fine for `0` reference
