### ISSUE TITLE
Enhancement: Retain search items on tab switch

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#4636]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- search item in one tab
- change tab and come back to tab that searched item
- search is reset

![image](https://user-images.githubusercontent.com/86340924/206281639-8433d39f-40a2-4884-afe6-a9bc6082c473.png)

### Desired Behavior

search should not reset when changing tab

### Project Details

Node: **v16.18.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.99.2**

**Comment by wingkwong** [comment]
I've made this enhancement recently. Just tested on latest version and the search wasn't reset. Please try on the latest version.

**Comment by wingkwong** [comment]
Closing it now. If it's still not working on latest version, please reopen this issue with a video to show the issue.
