### ISSUE TITLE
🐛 Bug: When saving long text the cell size increases

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#4639]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When saving long text cell size increases
![image](https://user-images.githubusercontent.com/86340924/206544370-54b02bac-aa72-4853-8ecf-e974248f5ee4.png)

### Desired Behavior

There should be option to let it increase or increase upto some size then hide text

### Project Details

Node: **v16.18.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.99.2**

**Comment by dstala** [comment]
duplicate- to be tracked under 
[[Feature] Cell Display Options#2287](https://github.com/nocodb/nocodb/issues/2287)

**Comment by karan-quickwork** [comment]
![image](https://user-images.githubusercontent.com/99945603/223090226-8e300c3f-a654-4bc0-b53e-91bf8215b10a.png)

Facing same issue for kanban view (long text field).
Not sure if there is option to adjust row height .
