### ISSUE TITLE
🐛 Bug: Application crashes during Airtable import

### ISSUE THREAD

**Issue by cspocsai** [nocodb/nocodb#4642]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Start locally the latest version of the application (0.100.2) and try to import from an Airtable database where the unique constraints are not set properly.

`SQLITE_CONSTRAINT: **UNIQUE constraint failed: nc_f3vl___Variants.ncRecordId]** {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}
POST /api/v1/db/data/bulk/nc/Test/md_bsxf8aoyoy9rxx 400 4531 - 1118.293 ms

C:\Development\playground\nocodb\packages\nocodb-sdk\node_modules\axios\lib\core\createError.js:16
  var error = new Error(message);
              ^
Error: Request failed with status code 400
    at createError (C:\Development\playground\nocodb\packages\nocodb-sdk\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Development\playground\nocodb\packages\nocodb-sdk\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Development\playground\nocodb\packages\nocodb-sdk\node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[nodemon] app crashed - waiting for file changes before starting...`

### Desired Behavior

Even though the original Airtable table is not well prepared the NocoDB application crash is still unacceptable. The server should catch the exception and continue the import.
Moreover, it would be awesome if the users could see the exception message on the UI - now it is just hanging for eternity.

### Project Details

I followed the steps written here: https://docs.nocodb.com/engineering/development-setup

The current version of the application is 0.100.2

**Comment by Neptunespace** [comment]
My API request for Sqlite
```
curl -X 'POST' \
  'http://MYSERVER.com:8080/api/v1/db/data/v1/besto/client' \
  -H 'accept: application/json' \
  -H 'xc-token: MYAPITOKEN' \
  -H 'Content-Type: application/json' \
  -d '{
  "Id": 0,
  "path": "testtest",
  "CreatedAt": "string",
  "UpdatedAt": "string"
}'
```


Response
```
{
  "msg": "insert into `nc_5hnt__Download` (`created_at`, `id`, `path`, `updated_at`) values ('string', 0, 'testtest', 'string') - SQLITE_CONSTRAINT: UNIQUE constraint failed: nc_5hnt__Download.id"
}
```

**Comment by dstala** [comment]
@cspocsai good number of fixes have gone in for airtable import in release v0.202.5; please let us know if this issue still persists. you can reopen this thread if it does.
