### ISSUE TITLE
🔦 Feature: Make stable bound to the audit log

### ISSUE THREAD

**Issue by jrico207** [nocodb/nocodb#4643]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Right now it seems the audit log that noco maintains in it's sqlite db isn't bounded.  I'm running an automated application that uses an API token to make frequent updates.  Although I'm not adding much data, Noco is adding growing about 10MB/hour.  I'd like to be able to opt out of this audit log or set a bound to stop it from growing.

Shown is graph of disk used for Noco and disk used for the postgres database it's connected to.  Already noco has ratio'd postgres :)

### Suggested Solution

- Allow configuration to opt out of this audit log or set a bound to stop it from growing.

### Additional Context

<img width="1701" alt="Screen Shot 2022-12-08 at 8 36 34 PM" src="https://user-images.githubusercontent.com/120114141/206612000-f2c04f83-afbb-4410-97ac-2297b71922a5.png">

**Comment by o1lab** [comment]
Makes sense. We will introduce env variables for this in next release - stay tuned.
