### ISSUE TITLE
🐛 Bug: Knex timeout error when importing from Airtable

### ISSUE THREAD

**Issue by itay-sgh** [nocodb/nocodb#4650]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Importing a large Airtable base, table with ~35k rows and ~130 fields.

### Desired Behavior

Successfully import large bases from Airtable. I'm trying for weeks now..

### Project Details

docker compose PG
nocodb 0.100.2  
Apple M1

### Attachements
![image](https://user-images.githubusercontent.com/81905441/207042924-8dbc8538-7443-4d6e-844b-db69f1c761b2.png)

**Comment by mertmit** [comment]
Hi @itay-sgh is it possible for you to contact me via mert@nocodb.com or Discord (mertmit in our community server)

**Comment by dstala** [comment]
Closing this; please connect with us again if issue persist.
