### ISSUE TITLE
🐛 Bug: Missing/Blocking Features-Behaviours

### ISSUE THREAD

**Issue by abunet** [nocodb/nocodb#4653]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I've created a small application that tries to describe all the blocking problems that prevent the choice of this product in my company

The app is a classical Project Dashboard app
I've created Customers, Projects, Milestones and Tasks sheets
![image](https://user-images.githubusercontent.com/804576/207252284-73f69c6b-b951-4494-9682-b09dfe0736b6.png)
![image](https://user-images.githubusercontent.com/804576/207252372-6b0b3583-2a5b-4595-a474-47907e16a869.png)
![image](https://user-images.githubusercontent.com/804576/207252422-28b188cb-90cd-4ad8-b756-4ddf6288ec97.png)
![image](https://user-images.githubusercontent.com/804576/207252468-a3247032-c894-41c0-9f22-a4f35165b433.png)

### Desired Behavior

the problems are:
1) The link record view (for example when I try to link a customer to a project)
![image](https://user-images.githubusercontent.com/804576/207252750-80bff602-a616-44f0-9f0e-f021a2ceecf2.png)
doesn't display enought data (for example phone, email). 
In my opinion the link record View could be rendered with the "default" table view of customers sheet (if exists at least a table view, otherwise the current list). 
2) As you can see in the images milestones could have the same title for different projects (for example all my projects have a "development" milestone). When I add a task and I try to link to a milestone, I can't understand nothing because the list shows only the title of the record.
![image](https://user-images.githubusercontent.com/804576/207253575-a1b76601-970d-435f-a250-168b72bd8e9c.png)
3) In the task sheet I've added a Project field and a Milestone Field. I've added the Project field as a Link Record and not as a lookup field beacause I want allow the user to add a Task without specifying a Milestone (it's optional).
If a user add a Task and link to a Project, then choose a Milestone, I'd like to filter the list of Milestones by the selected project in the Task. 
![image](https://user-images.githubusercontent.com/804576/207254417-6d0ed5ff-5949-4487-9a77-c37efa922fd9.png)

The product has great potential but for me these are blocking features.

Regards
Marco

### Project Details

version: 0.98.3
Used with Docker

**Comment by abunet** [comment]
HI, any news about this?

**Comment by dstala** [comment]
v0.202.5 now has better modal for linked records display
https://docs.nocodb.com/fields/field-types/links-based/links#link-new-records

please reopen this thread if you need more help on this.
