### ISSUE TITLE
🔦 Feature: Abiliy to select date field through date picker in filter

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#4655]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Rather inputting directly there should be date picker when filtering
![image](https://user-images.githubusercontent.com/86340924/207626594-0cd24326-8377-41e0-be22-cbc445faa5a2.png)

### Suggested Solution

Add date picker in filter

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/5185
