### ISSUE TITLE
🐛 Bug: Publicly shared Gallery Views don't show the cover image

### ISSUE THREAD

**Issue by spaudanjo** [nocodb/nocodb#4664]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

* Create a table with an attachment column
* Add some rows with images for the attachment column
* Create a Gallery View for that table and selected the attachment column for the Cover column
* Ensure that the Gallery looks as expected regarding the Cover Image
* Then, via `Share View`, open the public version of the Gallery view

Issue: The cover image is not shown 

### Desired Behavior

The Cover Image should be shown the same way for shared views. 

### Project Details

Just create a simple project and table as described above. 

## Regular Gallery View
<img width="939" alt="image" src="https://user-images.githubusercontent.com/249210/208094984-762e431d-d622-4ac4-b958-903c06e6b943.png">

## Publicly shared view
<img width="834" alt="image" src="https://user-images.githubusercontent.com/249210/208094722-a382d23b-51a4-4284-a610-51e43d50a760.png">

**Comment by wingkwong** [comment]
Preliminary findings:

- gallery data is not loaded in shared view
- gallery data is retrieved from `$api.dbView.galleryRead` which is not a public API. 

ref: `packages/nc-gui/composables/useViewData.ts`

```js
async function loadGalleryData() {
  if (!viewMeta?.value?.id || isPublic.value) return
  galleryData.value = await $api.dbView.galleryRead(viewMeta.value.id)
}
```

Solution: Need to fetch shared view data like grid view instead.
