### ISSUE TITLE
UX/UI: field helptext is hidden by error text

### ISSUE THREAD

**Issue by evangrim** [nocodb/nocodb#467]
When creating a new column, some or all column types display help/hint text. E.g. on the Formula column, "Available column types are ..." When I enter an invalid formula and this text is hidden, it is more difficult for me to understand the problem with my entry.

1.
![image](https://user-images.githubusercontent.com/11548185/129786292-1e9424e5-4662-4404-8678-2c3e0042e003.png)

2. (problem -- hint text is now hidden)
![image](https://user-images.githubusercontent.com/11548185/129786987-bce3b11e-7d4f-476c-b0c1-92801b146b22.png)

**Please enter the following details**

Copy and paste project info : N/A

or 

please provide the following details :
NocoDB used as docker : false
NocoDB version : 0.11.21
Database used in NC_DB URL  : sqlite3?
Project was created  by clicking : Heroku one-click deploy
Database on which spreadsheet is created : sqlite3 ?
OS on which NocoDB is running : windows 10
Node.js version if running as node : N/A
Database version : unsure

**Steps To Reproduce**
3. See error

**Expected behavior**
Hint text should still be visible or accessible when error messages are displayed; ideally, it is possible to link to more in-depth documentation from relevant UI areas (in this case, it may be the Create Column modal).

**Screenshots**

Join our discord : https://discord.gg/5RgZmkW for realtime help.

Node version : **v12.22.1**
Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
packageVersion: **0.9.27**

**Comment by iamnamananand996** [comment]
right now I can see only formula field have this kind for hint, so by just changing the error message can fix the issue, or else the better way will be to create a wrapper on top of `v-text-field` and not use ```persistent-hint and hint``` directly.

@o1lab , @pranavxc 


![Capture1](https://user-images.githubusercontent.com/31537362/163867267-41a26a6a-8d48-4c57-bedf-d901c347233a.PNG)
