### ISSUE TITLE
🐛 Bug: "Share View" of Kanban is showing up blank

### ISSUE THREAD

**Issue by green-globe** [nocodb/nocodb#4670]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a Kanban view
2. Click on "Share View"
3. A popup displays the URL and checked option for "Download allowed"
4. Copy the URL into the browser
5. Press Enter
6. HTTP page is loaded with no KANBAN being displayed

### Desired Behavior

The Kanban should be displayed.

### Project Details

Running latest on Google Cloud Run.

### Attachments

![image](https://user-images.githubusercontent.com/88571410/208493280-06706d39-38ab-46b7-adcc-d5ad2855d52a.png)

**Comment by green-globe** [comment]
Update: It seems to be related to "Fields" and "Stacked by".

If it is "Stacked By" Field A then we filtered the Field A from "Fields", everything becomes blank. It seems redundant to display the particular Field if it is already Stacked By.

**Comment by wingkwong** [comment]
Able to reproduce the issue.
