### ISSUE TITLE
🔦 Feature: Lock select columns or rows in view

### ISSUE THREAD

**Issue by xiamaz** [nocodb/nocodb#4673]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In some tables we are using new data needs to be added constantly, but old data is only needed for reference and most edits might most likely be accidental edits.

For columns, certain columns might need to only be edited by certain applications/users and should prevent accidental manual editing.

### Suggested Solution

Rows and Columns should have a "lock" feature, which prevents manual edits without explicit unlocking. This feature is mainly intended to prevent accidental edits and so no access controls or security measures should be added. Unlocking a row/column should create an entry in the audit log.

### Additional Context

A similar feature had already been asked in the following discussion: https://github.com/nocodb/nocodb/discussions/4268

**Comment by dstala** [comment]
related - https://github.com/nocodb/nocodb/issues/4437

**Comment by dstala** [comment]
To be tracked under

[🔦 Feature: Row / Column base permission, last edited by / updated by and audit log](https://github.com/nocodb/nocodb/issues/5075)
