### ISSUE TITLE
🐛 Bug: Formula IF is null not working

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#4678]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a Formula -> Enter: IF({column} == null,"Value",null)
Output always null. Noco doesnt recognize a null value on operand

### Desired Behavior

Operand works with null value

### Project Details

Docker, postgres, 0.100.2

**Comment by wingkwong** [comment]
This should be considered as an invalid formula. You may try the following instead

```
IF({column} == "", "Value", "")
```

**Comment by emre1e** [comment]
If i go with == "" its not working with null values. Only for empty strings. 

null is recognized by nocodb so its not invalid. You can also use null as success or elsecase and set it, but not as Expression.

Thank you.
