### ISSUE TITLE
🐛 Bug: expected a string but received a array 

### ISSUE THREAD

**Issue by whyteserious** [nocodb/nocodb#4685]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

expected a string but received a array  in version 0.100.2 
I know there are some characters can cause this problem 
but l can import the same excel  file  in 0.92.4 

### Desired Behavior

 Maybe find a solution

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.100.2**

**Comment by wingkwong** [comment]
Please provide a dummy file for reproducing the issue.

**Comment by whyteserious** [comment]
[test.csv](https://github.com/nocodb/nocodb/files/10286271/test.csv)

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. Please record a video for demostration.

**Comment by whyteserious** [comment]
https://user-images.githubusercontent.com/42569476/209270627-354b714e-a542-4d0a-a986-0909340dc22e.mp4

**Comment by wingkwong** [comment]
Can you provide that excel file? You provided a csv file and I thought it was CSV import.

**Comment by whyteserious** [comment]
[test.xlsx](https://github.com/nocodb/nocodb/files/10292227/test.xlsx)

**Comment by wingkwong** [comment]
I think I've fixed it in develop branch already. Can you try on this tag `nocodb/nocodb-daily:0.100.2-20221223-0602` ?

![image](https://user-images.githubusercontent.com/35857179/209287856-491478f8-6410-491e-89c3-fe207966f2cd.png)

**Comment by whyteserious** [comment]
it works    thank you

**Comment by whyteserious** [comment]
expected a string but received a Date 

This problem is caused by the time column
The content format is the same as test.excel

**Comment by wingkwong** [comment]
Which column is time column? If your data is Date, then it is expected to see that error.

**Comment by whyteserious** [comment]
column n is the date column 
my data is Date type and i expected a date type or a string type

**Comment by wingkwong** [comment]
It looks fine on my side (develop branch). Which version are you using?

![image](https://user-images.githubusercontent.com/35857179/209902460-d0da3e85-4fec-4b19-b9e3-f55b1c151074.png)

![image](https://user-images.githubusercontent.com/35857179/209902479-bea731d6-2d52-4496-8a57-5856eb1011dc.png)

**Comment by whyteserious** [comment]
nocodb/nocodb-daily:0.100.2-20221223-0602

**Comment by whyteserious** [comment]
my side alse fine , but my colleagues not

**Comment by wingkwong** [comment]
It's hard to tell what's going wrong here. You may help check the difference between your setup and your colleagues' ones.

**Comment by whyteserious** [comment]
the same excel can import in version 0.92.4

**Comment by wingkwong** [comment]
Are you guys using the same NocoDB? same version? same project? if not, please provide those info.

**Comment by whyteserious** [comment]
don't  select the Auto-select Fields Types  can  import

**Comment by whyteserious** [comment]
l'm admin and devops   they are users 
we use the same nocodb,the same version, the same project
the nocodb update from 0.92.4 to 0.100.2

**Comment by wingkwong** [comment]
`nocodb/nocodb-daily:0.100.2-20221223-0602` is not the official version. It's just a timely-built version. You may wait for the next release.
