### ISSUE TITLE
🐛 Bug: CSV Upload does not strip % symbol out of % fields causing sort issues

### ISSUE THREAD

**Issue by HStep20** [nocodb/nocodb#4687]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a CSV file with a column of various percentages, including the % symbol
2. Create a table with a % field
3. Upload the CSV file with the column mapped to the % field

### Desired Behavior

Id expect it to match the required format when manually inputting data. 

While its not a large priority bug, it leads to a secondary bug, where trying to sort data from High to Low (9-1) in the Percentage column where % symbols are present leads to the '100%' values being read as a '1' value, meaning they show up at the bottom of the table when sorted - They should be at the top

Percent Symbol % fields with Sort Applied:
![image](https://user-images.githubusercontent.com/6693120/209226862-b2b4761c-dabc-4c6c-899c-209ceff3f447.png)

![image](https://user-images.githubusercontent.com/6693120/209226911-54df08e9-74ee-4bbf-a07a-5313b694d4aa.png)

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.100.2**

**Comment by wingkwong** [comment]
Percent Type has been reverted at some point so currently the value will be displayed in text only. Hence, there is no logic handling the symbol at all.

may subscribe this issue https://github.com/nocodb/nocodb/issues/4457 for the update

**Comment by dstala** [comment]
CSV import defaults to single line text now. And post import, one can convert field to numeric type (% symbol will be removed)
