### ISSUE TITLE
🔦 Feature: sql query and sql import

### ISSUE THREAD

**Issue by itorz7** [nocodb/nocodb#4689]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

this sql query like phpmyadmin
![image](https://user-images.githubusercontent.com/30155968/209236833-bcc57fc8-4565-427e-bc4b-e607ea4ae9ea.png)

and sql import by .sql

### Suggested Solution

-

### Additional Context

I know it's in a lot of other apps but I wish it had. 
Because it will help teach people who don't know sql commands to be familiar with, learn when searching, blah blah, show sql commands, but I need switch to phpmyadmin to query, import sql, learn sql commands from it.
,,,
because of this nocodb let me know column selection

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/issues/137

**Comment by dstala** [comment]
will be tracked under https://github.com/nocodb/nocodb/issues/137
