### ISSUE TITLE
🐛 Bug: nocodb\packages\nocodb\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node is not a valid Win32 application

### ISSUE THREAD

**Issue by huangzongming** [nocodb/nocodb#4695]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

cd packages/nocodb
npm install
npm run watch:run

### Desired Behavior

cd packages/nocodb
npm install
npm run watch:run

### Project Details

cd packages/nocodb
npm install
npm run watch:run

### Attachements

cd packages/nocodb
npm install
npm run watch:run

**Comment by wingkwong** [comment]
@huangzongming Can you provide the full error logs and what is your node version?

**Comment by huangzongming** [comment]
![c9e947c39f3365ce3383c34421a011b](https://user-images.githubusercontent.com/37889515/209427370-b1528ec3-e82b-4c55-af6c-d6a3c9d0753b.png)

**Comment by huangzongming** [comment]
node v18;npm v9

**Comment by wingkwong** [comment]
Is your Windows on ARM64?

**Comment by huangzongming** [comment]
![8f52d01e983c89e7faca3b6c6be896a](https://user-images.githubusercontent.com/37889515/209454881-c6ae7b71-a484-4cac-8be0-d3ff401d3227.png)
![eb481d1dcb126fa7dcb7215ffc94811](https://user-images.githubusercontent.com/37889515/209454883-b99e3d54-0507-4f72-91ef-9517f465d0af.png)

**Comment by wingkwong** [comment]
You may downgrade your node to v16.x, remove your node module and install again. If it still doesn't work, you may install sqlite3 with `--build-from-source` flag. See the [repo](https://github.com/TryGhost/node-sqlite3) for reference.

**Comment by huangzongming** [comment]
thank you,the v16.x is ok~

**Comment by wingkwong** [comment]
Thanks for confirming. We're using node v16.x to develop. Higher versions may cause unexpected errors. Closing this issue now.
