### ISSUE TITLE
🐛 Bug: Error popup when clearing a number field for a row in a postgres database

### ISSUE THREAD

**Issue by jrico207** [nocodb/nocodb#4701]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create database with postgres
2. create a column with `Number` type.
3. create a row and enter a number value.
4. clear the number entry to "" and hit enter.

### Desired Behavior

It should clear the value without error.

### Project Details

```
Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.100.2**
```

### Attachements

<img width="1170" alt="Screen Shot 2022-12-26 at 9 55 27 AM" src="https://user-images.githubusercontent.com/120114141/209565591-1046b66f-4d3e-42b3-a5c8-2dc23e226bd2.png">

**Comment by dstala** [comment]
"" not allowed as input character for `number` column
I could see error when trying to copy paste from an empty cell onto a valid cell (both of type number)
