### ISSUE TITLE
🐛 Bug:  When the primary key contains /, an error occurs when updating data

### ISSUE THREAD

**Issue by 4blacktea** [nocodb/nocodb#4704]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When the value of the primary key in my data table contains /, when updating the data, the relevant API will treat the slash as a url route, resulting in the failure of the data to be updated successfully

### Desired Behavior

I tried escaping the / as %2f when submitting the data update request, and that does the trick

### Project Details

docker

### Attachements

![image](https://user-images.githubusercontent.com/81417218/209652132-bf8589df-696d-4a58-ad1a-1ef4fa015769.png)

**Comment by Afsalmc** [comment]
I can still reproduce this issue. Using version [0.109.7](https://github.com/nocodb/nocodb/releases/tag/0.109.7)

**Comment by Afsalmc** [comment]
My primary key value is GET /api/ping
