### ISSUE TITLE
🔦 Feature: Need aggregation capabilities

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#4730]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

i have use case where i want to show how many times a value is there in DB and can if we can apply futher filters on it like get rows with count greater than 1 etc.. it would be great.
since our team has only access to view data using the views its not possible to see these type of things in short glance.
other alternatives could be connecting the db to some other tool and view these but i think that will be lot of tools and i feel it can be provided here if its under the product scope.

### Suggested Solution

Can implement a custom editor where we can write sql queries and the results will be displayed in a grid view or can provide UI to basic filters with support to above use case.
Able to write custom sql will open up lot of possibilities. queries with read level access only should be executed.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/issues/137
https://github.com/nocodb/nocodb/issues/4336

@PrasanthKumar77 we will track this under #137 and #4336
