### ISSUE TITLE
🔦 Feature: Support to delete rows in bulk

### ISSUE THREAD

**Issue by PrasanthKumar77** [nocodb/nocodb#4731]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently could not delete rows that satisfy a given condition.
As the views will be the only source for our team to communicate with data, it would be nice to have this. instead of they again contacting the person with db access to do these type of operations. 

### Suggested Solution

provide an option to delete rows that satisfies the given condition.
we can upload a csv and select a column all the rows that match the value in the column should be deleted.
initially can support single column comparison and can later extend it to support different conditions and columns

**Comment by dstala** [comment]
@PrasanthKumar77 You can create a filter, click on `select all` & delete. Let us know if this resolves for you.


![Image](https://github.com/nocodb/nocodb/assets/86527202/67857694-6024-493d-a047-789c8353627e)

**Comment by dstala** [comment]
@PrasanthKumar77 marking this issue as closed as we now support bulk delete over UI. reopen this thread if you still wish the csv way to do it.

**Comment by lazmo88** [comment]
> @PrasanthKumar77 marking this issue as closed as we now support bulk delete over UI. reopen this thread if you still wish the csv way to do it.

#3870 mentioned especially the issue when you have multiple pages of data you want to delete. The current filter only selects current page items, but what if you have 27 pages? You repeat the action 27 times.

Gmail UI has a good example to select all (even non-visible emails/rows) and apply bulk command accordingly.

I believe this feature could still need to be worked on.

**Comment by sant1dom** [comment]
For me this issue should be reopened, is not possible to delete in bulk more pages.

**Comment by firstcomeuropeag** [comment]
please reopen

**Comment by besserai** [comment]
+1

**Comment by plang** [comment]
Yes, please reopen this ticket: with a big table of several thousand records over several UI pages, deleting all the rows at once is not possible.
