### ISSUE TITLE
feat: Freeze columns and header

### ISSUE THREAD

**Issue by remlemartin** [nocodb/nocodb#4753]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Adding freeze columns  and header for easily navigation of the longer dataset is a good idea.

### Suggested Solution

> Freeze columns to easily navigate horizontally

> Freeze row header to easily navigate vertically

### Additional Context

One of the problem that I noticed is navigating longer dataset.  Most people prefer to use grid view by default than form view.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/issues/1589

**Comment by dstala** [comment]
duplicate
