### ISSUE TITLE
🐛 Bug: API for nested fields other than primary field

### ISSUE THREAD

**Issue by GripenANM** [nocodb/nocodb#4757]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

This is an issue/question that extended from https://github.com/nocodb/nocodb/discussions/1507

Given Two Table 

[![Image from Gyazo](https://i.gyazo.com/40b521e31f637f504de826786bfacd75.png)](https://gyazo.com/40b521e31f637f504de826786bfacd75)
[![Image from Gyazo](https://i.gyazo.com/c3a2437aa4dc83fd541f4fc9a5c98c10.png)](https://gyazo.com/c3a2437aa4dc83fd541f4fc9a5c98c10)

API documentation states that the result when querying through
[![Image from Gyazo](https://i.gyazo.com/5c36c872cfba1b8b46e94e85c14dc13d.png)](https://gyazo.com/5c36c872cfba1b8b46e94e85c14dc13d)
nested fields should also be returned(Desired Behavior)

But when calling the API only The key and Primary Value is returned. 
[![Image from Gyazo](https://i.gyazo.com/02e92bf93ddf111a875d61758d953eaf.png)](https://gyazo.com/02e92bf93ddf111a875d61758d953eaf)

### Desired Behavior

 supposed to be showing all nested fields from the one to many relation field:
[![Image from Gyazo](https://i.gyazo.com/cdd68ba84fe715865aedc90260acf0e0.png)](https://gyazo.com/cdd68ba84fe715865aedc90260acf0e0)

is this an intended behaviour or I am missing some kind of configuration to enable the return of nested non-primary values in one to many or many to many relation field.

### Project Details

NocoDB used as docker : **true** / false
NocoDB version : 
Database used in NC_DB URL  : **mysql** | pg | mssql | sqlite3 / (defaults to sqlite3 if empty)
Project was created  by clicking : **New Project** | New Project by connecting to external database
Database on which spreadsheet is created : **mysql** | pg | mssql | sqlite3 / (defaults to sqlite3 if empty)
OS on which NocoDB is running: WSL 2 through Docker
Node.js version if running as node : 
Database version : 

```docker-compose.yml
version: "2.1"
services: 
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "mysql2://root_db:3306?u=noco&p=password&d=root_db"
    image: "nocodb/nocodb:latest"
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
      - "nc_data:/usr/app/data"
  root_db: 
    environment: 
      MYSQL_DATABASE: root_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: noco
    healthcheck: 
      retries: 10
      test: 
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    image: "mysql:5.7"
    restart: always
    volumes: 
      - "db_data:/var/lib/mysql"
#    below line shows how to change charset and collation
#    uncomment it if necessary
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes: 
  db_data: {}
  nc_data: {}
```

**Comment by pranavxc** [comment]
To fetch nested fields from the LTAR column, you can pass the fields query parameter `nested[LinkToFoo][fields]=*` in request. Or if you want to get specific fields then you can pass it as comma-separated field names as follows - `nested[LinkToFoo][fields]=fieldq,field2`

**Comment by wingkwong** [comment]
Closing - see the above comment for the info.
