### ISSUE TITLE
🐛 Bug: DATETIME_DIFF Not Working on sqlite

### ISSUE THREAD

**Issue by ozcpa** [nocodb/nocodb#4778]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. A field of type Date is created (say "DOB")
2. A field of type Formula is created (say "Age")  with the formula of DATETIME_DIFF({DOB}, NOW(), "years")
3. The result is BLANK (i.e. DATETIME_DIFF function doesn't work).  However, if the field contains the formula of DATETIME_DIFF("2000-07-08","2023-01-08","years") then the correct result IS displayed

### Desired Behavior

The DATETIME_DIFF function should work as outlined in the documentation (i.e. by being able to use two fields etc)

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**

**Comment by wingkwong** [comment]
1. What is the nocodb version?
2. what is the date format for DOB?

**Comment by ozcpa** [comment]
Thanks for your reply.  The download was made about 24 hours ago from: http://get.nocodb.com/win-x64.exe ... I can’t find the version information.

 

I have tested the DATETIME_DIFF function with the date set to YYY-MM-DD, and DD-MM-YYYY, and MM-DD-YYYY … and none of them work.

 

As mentioned, the version of NOCODB that I downloaded yesterday doesn’t work properly with DATETIME_DIFF unless the dates are actually entered (e.g. DATETIME_DIFF( “2023-09-01”, “2018-12-23”, “years”).  Now, I have just (a few minutes ago) downloaded the LATEST version from your site at: http://get.nocodb.com/win-x64.exe and that doesn’t allow me to use the DATETIME_DIFF function AT ALL.

**Comment by wingkwong** [comment]
Okay. Will take a look later.

**Comment by ozcpa** [comment]
Many thanks 😊

**Comment by ozcpa** [comment]
I did some further testing (using the version where DATETIME_DIFF was being recognised, although not working properly).  That function works properly if I use a MySQL data source, but it does NOT work with SQLite (which I was using before).

**Comment by ozcpa** [comment]
The DATETIME_DIFF function now also doesn't work with MySQL in the latest version of the program (downloaded on 10 January 2023 at 21:20 Australian Time)

**Comment by ozcpa** [comment]
I just tried using the Docker version.  The DATETIME_DIFF function is no longer available!

Details of NOCODB are as follows:
Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**

**Comment by wingkwong** [comment]
Actually DATETIME_DIFF hasn't been publicly released. If you're using `0.100.2`, which you can verify by hovering the icon on the top left side, it is expected to see it is not available. 

Here's my result on my local. Please share the error log if possible.

f: `DATETIME_DIFF({DOB}, "2023-01-11", "years")`
f2: `NOW()`
f3: `DATETIME_DIFF({DOB}, NOW(), "years")` 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/35857179/211713534-4f1cf8ea-9c95-40e0-81ce-e1ed13b42f07.png">

**Comment by ozcpa** [comment]
The Docker version that I downloaded today is V 0.100.2 and the DATETIME_DIFF function definitely isn’t available (as you have mentioned).

 

However, the WINDOWS version (i.e. Noco-win-x64) that I downloaded from your site on the evening of 8 January 2023 (Australian time) definitely DOES have the DATETIME_DIFF function available (see screenshot attached)

 

I cannot tell you the version because a “black square” appears when I hover (see attached screenshot)

**Comment by wingkwong** [comment]
Okay. I figured it out. The executable is pointing to the beta version which is not expected (will handle in a separate issue). However, From you screenshot, it can show the result. Is it all good now?

**Comment by ozcpa** [comment]
It works with a MySQL database, but I was intending to use it with SQLite (as mentioned in my original comment).  So it still doesn’t really work for me.

 

When do you think that the DATETIME_DIFF function will be released so that it will work in ALL versions of NOCODB?
