### ISSUE TITLE
Airtable Import With Attachments 

### ISSUE THREAD

**Issue by theayushshinde** [nocodb/nocodb#4785]
Whenever I am trying to import a base from airtable and some of those tables contain attachments, I am not able to import that particular field(attachments). 

I have attached a screenshot too. Also not able to download those attachments. I have checked the logs too and I don't see any error there.

![image](https://user-images.githubusercontent.com/61621927/211257411-b022bf7a-d7a0-4126-a8f6-c32be696a2cf.png)

While if I perform the same thing on localhost I am able to get all attachments easily.

I have observed some errors in the console.

![image](https://user-images.githubusercontent.com/61621927/211257494-bb5162dd-94fb-4d48-9df8-970ae92a7888.png)

**Comment by pranavxc** [comment]
Are you using it locally or self-hosted? if self-hosted then please configure `NC_PUBLIC_URL` with your URL and try it out.

**Comment by dstala** [comment]
@theayushshinde many of import related issues are fixed in release v0.202.5; please reopen this ticket if you still face issue in our latest release.
