### ISSUE TITLE
🐛 Bug: Multiple incomplete records added while adding new row

### ISSUE THREAD

**Issue by modularizer** [nocodb/nocodb#4789]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

On 0.101.0-beta.0 when using the "Add new row" button below the last row in a table grid view, the new row is inserted as I fill out the first column of the row (in my case the "name" primary key column). So if the name is "testing_abc", I get maybe 3 or 4 records with names "testin", "testing", "testing_a", "testing_abc".  The database is running locally on a Linux machine talking with a postgres database on the same machine.

### Desired Behavior

The record should not be created until I focus out of the row I am adding, or at least it should not be created until I focus out of the cell I am typing or hit Enter.

### Project Details

Node: **v18.11.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.101.0-beta.0**

### Attachements

![noco_bug](https://user-images.githubusercontent.com/82345008/211428112-0301b188-20e8-4214-a755-17690878a838.png)

**Comment by wingkwong** [comment]
@modularizer I couldn't reproduce the issue. Could you please provide a video for demonstration?
