### ISSUE TITLE
Whitespace in tablename while creating m2m relation leads to column not being shown.

### ISSUE THREAD

**Issue by wshen001** [nocodb/nocodb#479]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.11.21**

**Steps To Reproduce**
Create 3 tables in DB. Here are the table definitions:

Table 1:  "Products" table in which contains "title", "SKU", "description" and "category" which links to the "categories" table.
Table 2:  "Categories" table in which contains a list of categories.
Table 3: "Status" table in which should have a few column links to the records in "Products" table. 

When I tried to set up the columns for Table 3 (Status table) with the "linked to other records" option and to set the column with "many to many" properties to the "Products" table. Then it shows me "relational created . successfully", however, nothing gets inserted into the table... 

But when I choose the option to "one to many" instead of "many to many", it inserts correctly.  I assume it's the bug of the software? I tried to do the same operation on Airtable, and it works correctly.

**Expected behavior**
The Status table should have a column called "product" links to Products table's column to display the SKU, title or description information.

**Comment by o1lab** [comment]
> Table 1: "Products" table in which contains "title", "SKU", "description" and "category" which links to the "categories" table.

By links : many to many ?


> Table 3: "Status" table in which should have a few column links to the records in "Products" table.

By links : many to many ?


I wasn't able to reproduce the issue.

**Comment by wshen001** [comment]
@o1lab  thank you for asking!

Yes, the "Products" table links to the Categories table with "many to many". This many to many is inserted successfully between "Products" and "Categories" tables.

However, when I tried to link the "Status" table with the "Products" table with many to many relationships, I can't get it working.

**Comment by wshen001** [comment]
@o1lab you can access the sample NocoDB I made (https://products-status-demo2.herokuapp.com/)
I have created an account for you to your GitHub email. Here is the invite token. (https://products-status-demo2.herokuapp.com/dashboard/#/user/authentication/signup/e191936b-8a9f-44df-bcaf-76e7fbe882b1)

**Comment by o1lab** [comment]
Please change my permissions to creator, I don't have the permission to add columns :)

**Comment by o1lab** [comment]
Looks like product and status has already a relation (belongsTo). See image below - that might be the reason ?

<img width="228" alt="Screen Shot 2021-08-23 at 11 23 17" src="https://user-images.githubusercontent.com/5435402/130397270-7137dbe1-6609-4abc-9d96-554aa2b6b86c.png">

**Comment by wshen001** [comment]
@o1lab  sorry for being late. You are now assigned as a `creator`. 

Yes, they already have a one-to-many relationship in the previous setup. As I stated in the ticket description. I can set the `one-to-many` relationship but not the `many-to-many` relationships for the test tables.  In order for you to easily duplicate the issue, I have removed the product and status relation in the `status` table. And you can give it a try to add a `many-to-many` relation with the status and products table in the Status table, you will see nothing get inserted when you do it.

**Comment by o1lab** [comment]
may be it is the ```status table``` name is the issue.

Guess its the space between words. Could you recreate tables without space and give it a go ?

If its the case then we can change the heading of this.

**Comment by wshen001** [comment]
@o1lab  ok, let me try to recreate a table without the space.

However, I do suggest that the `nocodb` should give the end-user more flexibility in defining the name for `table` and `column`. I constantly see the error when using `uppercase` in any of the definitions.

**Comment by wshen001** [comment]
@o1lab  after I re-create a table without the space of the table name, it works!

I have tested that many-to-many relation works as expected.

**Comment by o1lab** [comment]
Thank you, I've made changes to title to this issue.

**Comment by pranavxc** [comment]
> @o1lab after I re-create a table without the space of the table name, it works!
> 
> I have tested that many-to-many relation works as expected.

We had fixed it in our recent release, can you try our latest version and confirm.

**Comment by wshen001** [comment]
@pranavxc  thank you for letting me know! Yes, I will try the latest version v0.84.9 and will let you know.
