### ISSUE TITLE
🐛 Bug: Error 403 when the editor uploads the image

### ISSUE THREAD

**Issue by mcnaveen** [nocodb/nocodb#4805]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Deploy the nocodb in a docker container. Using this command.

```
docker run -d --name nocodb-app \
--network postgress_internal \
--ip 172.19.0.10 \
-v "$(pwd)"/nocodb:/usr/app/data/ \
-p 8080:8080 \
-e NC_DB="pg://pgdb:5432?u=postgres&p=postgres&d=nocodb" \
-e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
-e "VIRTUAL_HOST=mydomain.com" \
-e "LETSENCRYPT_HOST=mydomain.com" \
--restart unless-stopped \
nocodb/nocodb:latest
```

1. Then create a user
2. Add Editor
3. Inside the table try to upload an image from editor profile

### Desired Behavior

It should upload the image

### Project Details

```
Docker: True
Nocodb Version: Latest one from Dockerhub
DB: pg
Project: New Project Button
```

### Attachements

![image](https://user-images.githubusercontent.com/8493007/211879428-767597fc-a09b-4d72-94a3-8af848b6b205.png)
![image](https://user-images.githubusercontent.com/8493007/211879451-c2c14bc9-7152-408e-952d-ab3c624f9117.png)

**Comment by wingkwong** [comment]
Please provide the docker log as well.

**Comment by mcnaveen** [comment]
Hi @wingkwong 

Here is the docker log when I'm trying to upload attachment from `Editor` account

```
GET /api/v1/db/data/noco/p_1liwpzrlywk02m/md_i1zd5sd94z4kw5/views/vw_t510qtlxjg0ffp?offset=0&limit=25 
304 - - 594.369 ms
 s [Error]: upload - org-level-viewer : Not allowed
    at Function.forbidden (/usr/src/app/docker/main.js:1:40923)
    at /usr/src/app/docker/main.js:1:15935
    at /usr/src/app/docker/main.js:1:40191
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at /usr/src/app/docker/main.js:1:15565
    at /usr/src/app/docker/main.js:1:40191
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at t.default (/usr/src/app/docker/main.js:1:572567)
POST /api/v1/db/storage/upload?path=noco%2FTradexx%2FTest%2Ftest_upload 403 49 - 15.093 ms
```

**Comment by wingkwong** [comment]
@mcnaveen Sorry for the late reply. May I know which version you're using? It seems that this bug has been fixed in https://github.com/nocodb/nocodb/issues/4699. Please try the latest version.

**Comment by mcnaveen** [comment]
Will check and update.

**Comment by mcnaveen** [comment]
Will check and update.

**Comment by djmaze** [comment]
Similar problem here. When using the _shared base link_, even when set to the `editor` role, people can`t upload any attachments.

I guess this broke because of this change: https://github.com/nocodb/nocodb/commit/1f17da4b95113ce069fc3cd3bdc4d4aaf01e5e1e
