### ISSUE TITLE
🔦 Feature: Move columns/rows using a drag & drop gesture

### ISSUE THREAD

**Issue by EgonHeuson** [nocodb/nocodb#4811]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

It would be amazing to have the possibility to reorder the rows and columns using the mouse (actually I didn't find how to do it at all). This would help reorganizing manually entries and columns. 

### Suggested Solution

Like a drag and drop gesture of a column/row at the side of another one.

**Comment by dstala** [comment]
@EgonHeuson 
Reordering rows is not supported.
Columns you can re-order
https://docs.nocodb.com/setup-and-usages/column-operations#re-order-columns
https://www.loom.com/share/bb1602992e7d4d7d829b58b80b6a38d1

**Comment by EgonHeuson** [comment]
Ah my bad for the rows. For the columns, it would be nice to be able to use the mouse gesture to move them to the left or the right :-)
For the rows, is there any reason for this?

**Comment by EgonHeuson** [comment]
Damned, I need to rest a bit, cannot see my screen clearly apparently! Very sorry.
