### ISSUE TITLE
🔦 Feature: Show all the rows on the same page

### ISSUE THREAD

**Issue by EgonHeuson** [nocodb/nocodb#4813]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

It's quite frustrating sometimes to forget some people you want to email because their entry were moved to another page. Would it be possible to select the number of rows to show in a single page? 

### Suggested Solution

The possibility to enter a custom number (or to select a defined number) of rows to show on a single page.

**Comment by dstala** [comment]
@EgonHeuson 
Not possible from UI. You can configure environment variable `DB_QUERY_LIMIT_DEFAULT`
Note that, Max allowed value is 1000
https://docs.nocodb.com/getting-started/installation#environment-variables
