### ISSUE TITLE
🔦 Enhancement: Option to download barcode

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4814]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

<img width="1381" alt="Screenshot 2023-01-12 at 10 18 55" src="https://user-images.githubusercontent.com/5435402/212040865-c17614ae-ae20-4503-b046-e884aea60d46.png">

### Suggested Solution

- option to download barcode

**Comment by frankMagoba** [comment]
@o1lab can I pick this up?
