### ISSUE TITLE
🐛 Bug: Deleting user from main admin panel needs text change.

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4815]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

<img width="400" alt="Screenshot 2023-01-12 at 12 15 29" src="https://user-images.githubusercontent.com/5435402/212064871-fd8abe02-be1c-43dc-98de-4305ea232419.png">

### Desired Behavior

.

### Project Details

0.101

**Comment by frankMagoba** [comment]
@o1lab , do you mean the `user will remove...` grammar error?

**Comment by o1lab** [comment]
Yep

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/commit/b3c8650122fbeda1344a2ce7f3c09aade0d1d82c
