### ISSUE TITLE
🐛 Bug: socket.io does not use subfolder URL

### ISSUE THREAD

**Issue by gitfvb** [nocodb/nocodb#4818]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Using nocodb version 0.101.0
Installed today with node LTS and upgraded npm

My nocodb is guided through a reverse proxy and is found in a subdirectory `/dt/`

All looks good so far, but the socket.io does "forget" the subdirectory dt and requests plain to the url. So instead of 

https://example.com/dt/socket.io/?EIO=4&transport=polling&t=OMcmeNR

it uses

https://example.com/socket.io/?EIO=4&transport=polling&t=OMcmeNR

to ask for polling. I have defined `.env` like

```
#PORT=8080      # default port to run on
#NC_DB=	    #See our database URLs	A local SQLite will be created in root folder
#DATABASE_URL=	    #JDBC URL Format. Can be used instead of NC_DB. Used in 1-Click Heroku deployment
#DATABASE_URL_FILE=	    #path to file containing JDBC URL Format. Can be used instead of NC_DB. Used in 1-Click Heroku deployment
NC_PUBLIC_URL=https://example.com/dt/ 	#Used for sending Email invitations	Best guess from http request params
#NC_AUTH_JWT_SECRET=	    #JWT secret used for auth and storing other secrets	A Random secret will be generated
#NC_SENTRY_DSN=	    #For Sentry monitoring
#NC_CONNECT_TO_EXTERNAL_DB_DISABLED=	#Disable Project creation with external database
#NC_DISABLE_TELE=	    #Disable telemetry
NC_BACKEND_URL=http://localhost/	    #Custom Backend URL
```

I have changed the url due to security reasons.

### Desired Behavior

The socket.io request does include the subdirectory defined in the `.env` file for the external url

### Project Details

NoCoDB running in Docker: false
NoCoDB version: 0.101.0
Node version: 18.13.0 (LTS)

**Comment by raisinbear** [comment]
@gitfvb would you mind sharing how you managed to get nocodb working on a subfolder URL at all?

I just tried docker as well as binary, defining 

```
location /ndb {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;

    proxy_pass http://127.0.0.1:5600;
}
```

in my server block and exported `NC_PUBLIC_URL=http://10.0.2.15/ndb/`, as well as `PORT=5600` as environment variables. When running as docker image, I will at least get prompted `Visit : http://10.0.2.15/ndb/dashboard`. Running the binary directly would still say `Visit : localhost:5600/dashboard`, regardless of `NC_PUBLIC_URL`.

But both, docker and binary, are reporting

`GET /ndb/ 404 143 - 9.305 ms`

when visiting the subpath URL. So the request is hitting nocodb but the subpath config doesn't appear to be doing anything!?

**Comment by gitfvb** [comment]
Hi @raisinbear 

Thanks for having a look. I have done it through IIS with a reverse proxy, which works fine except for sockets.io

After putting it to the root, there is still another problem with websockets I need to solve first. I am documenting my steps and will post it here once sockets are working. NoCoDB works almost fine, but not showing new tables or fields without refreshing the browser. Will let you know of any progress.

**Comment by o1lab** [comment]
@gitfvb : is this making the UI NOT usable ?

**Comment by gitfvb** [comment]
Hi @raisinbear , you can see it here. It is not unusable, but without websockets a lot of polling does not seem to work properly. I think entering data is just fine, but change of datamodel needs a lot of manual refreshments. You can see it here:

https://user-images.githubusercontent.com/14135678/212640265-2dd29a9c-216c-442c-bdd1-78f3588551c7.mp4

**Comment by gitfvb** [comment]
Hi @raisinbear , so I have now followed the steps from this tutorial exactly to configure IIS and it worked now straight away.

![grafik](https://user-images.githubusercontent.com/14135678/212660831-3201d256-36b8-4897-a0bf-f4d9ad7aa76b.png)

All communication and 101 swichting of socket.io works now. So other tutorials weren't successful, but this one helped. So maybe a good reference when using IIS as reverse proxy for nocodb node configuration.

**Comment by raisinbear** [comment]
Hey @gitfvb, thanks for all the feedback! But am I missing something or is the link to the tutorial missing? Would like to confirm the procedure is applicable to other reverse proxies.
Thanks! :)

**Comment by gitfvb** [comment]
Sorry @raisinbear ... you can find it here: https://adrianjnkns.medium.com/iis-as-reverse-proxy-to-websocket-server-c4fb5a7166f5

**Comment by raisinbear** [comment]
Perfect, thanks a lot @gitfvb !
