### ISSUE TITLE
Bug : MSSQL - Field Date is Defaulting to Varchar instead of Date

### ISSUE THREAD

**Issue by MatthiasMT** [nocodb/nocodb#4826]
![image](https://user-images.githubusercontent.com/13175677/212400954-70384983-452a-4db8-9a95-53d8660f41bf.png)

![image](https://user-images.githubusercontent.com/13175677/212400967-9ca2c09b-b8fa-46c9-b0b3-d212f5ec6fbe.png)

**Comment by o1lab** [comment]
what database is it ?

**Comment by MatthiasMT** [comment]
Database connection is MSSQL. Currently using the latest version of Nocodb.

Not sure if this is useful for you: Node: **v16.17.1** Arch: **x64** Platform: **linux** Docker: **true** RootDB: **sqlite3** PackageVersion: **0.101.0**

**Comment by MatthiasMT** [comment]
> what database is it ?

Database connection is MSSQL. Currently using the latest version of Nocodb.

Not sure if this is useful for you: Node: **v16.17.1** Arch: **x64** Platform: **linux** Docker: **true** RootDB: **sqlite3** PackageVersion: **0.101.0**

**Comment by MatthiasMT** [comment]
> what database is it ?

Just in case you were requesting this:

_**Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64) May 29 2022 15:55:47 Copyright (C) 2019 Microsoft Corporation Express Edition (64-bit) on Windows Server 2019 Standard 10.0 (Build 17763: ) (Hypervisor)**_

**Comment by lvarming** [comment]
I can confirm this problem which I have in my setup too. This on both MS SQL Server 2019 Express as well as MS SQL Server 2017. Nocodb is 0.101.0 running in a docker container.
