### ISSUE TITLE
🔦 Feature: Trigger Webhook (after update) for changes in LinkToAnotherRecord field

### ISSUE THREAD

**Issue by ashgard071** [nocodb/nocodb#4827]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently a webhook (after update) isn't triggered when the value of a LinkToAnotherRecord field is changed. It would be useful if this would create a trigger as it does change the record. 

### Suggested Solution

Create trigger when value of LinkToAnotherRecord field is changed.

**Comment by o1lab** [comment]
Tracked in #4474
