### ISSUE TITLE
🐛 Bug: import data from excel or csv ,the header changed

### ISSUE THREAD

**Issue by catcherxuefeng** [nocodb/nocodb#4841]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

source data:
`ABCD_NET`
nocodb data:
`AbcdNet`

### Desired Behavior

the data imported is the same as the original data

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.101.2**

**Comment by frankMagoba** [comment]
@o1lab can I pick this up?

**Comment by wingkwong** [comment]
@frankMagoba go ahead.

**Comment by dstala** [comment]
not reproducible in latest release. reopen this ticket if there is a case you see still
