### ISSUE TITLE
🐛 Bug: App Store not working: "pluginList - org-level-creator : Not allowed"

### ISSUE THREAD

**Issue by hismayilov** [nocodb/nocodb#4845]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Go To Project
Click "Team & Settings"
Click "App Store"

### Desired Behavior

App Store may work as expected.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.101.2**

### Attachements

![image](https://user-images.githubusercontent.com/676555/212540585-924940cb-5a43-44ab-9e04-9731da8d547f.png)

**Comment by dstala** [comment]
App Store access is only available for super-admin. We will make required UI changes to hide this menu item from users who do not have access permissions.

**Comment by hismayilov** [comment]
But I am super admin :)

**Comment by candideu** [comment]
I'm having the same issue @dstala, and I'm also a superadmin. I've been able to add plugins in the past...

![image](https://user-images.githubusercontent.com/55474996/213010513-cf9d03dc-d345-42e5-aa19-dce1c35079c7.png)

**Comment by candideu** [comment]
@hismayilov See https://github.com/nocodb/nocodb/issues/4867#issuecomment-1386480502 for the solution.
