### ISSUE TITLE
🐛 Bug: Skip displaying AppStore under project-menu

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4852]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

AppStore is accessible only for super-admin and configurations are global. Hence skip displaying appStore under project settings menu. Currently we display error on access.

### Desired Behavior

Better UX. Avoids confusion
https://github.com/nocodb/nocodb/issues/4845

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.101.2**

**Comment by candideu** [comment]
App store should be available for Creators as well. I'm having trouble accessing my app store, despite being the one managing the instance on Railway:

![image](https://user-images.githubusercontent.com/55474996/213010924-759cd855-3351-44bd-84a0-7a048de3973c.png)

How do I make myself superadmin?
