### ISSUE TITLE
🐛 Bug: Can't delete columns

### ISSUE THREAD

**Issue by linucksrox** [nocodb/nocodb#4858]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a sample table and add some columns. Then try deleting a column and confirm deletion.

### Desired Behavior

Column would be deleted.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.101.2**

### Attachements

![nocodb-error](https://user-images.githubusercontent.com/5169868/212707035-75153c2c-524d-4ca6-9447-025301da9300.png)

**Comment by wingkwong** [comment]
@linucksrox please provide the steps in detail, e.g what columns you've added, what column you select when you create barcode, which column type of the column you delete etc

From the error message, what I've tried

- create a barcode column on a SingleLineText column -> delete barcode column -> able to delete
- create a barcode column on a SingleLineText column -> delete SingleLineText column -> able to delete

**Comment by dstala** [comment]
Additionally, I tried relational columns delete as well (has many and many-many) - worked fine.

**Comment by linucksrox** [comment]
@wingkwong I have an existing table from a previous nocodb version, with columns ID, SingleSelect, Number, SingleSelect, Currency. Today I upgraded to 0.101.2 and added a QR Code column, then attempted to delete it and got the error message. I added another QR code column and saw the same issue attempting to delete it. I then attempted to delete the Number column and see the same error.

Is there any other information I can share to help debug this issue?

**Comment by pranavxc** [comment]
Please check the meta database and verify `nc_col_barcode_v2` table exists or not

**Comment by linucksrox** [comment]
No, there is no table named `nc_col_barcode_v2` but there is one named `nc_col_qrcode_v2` which is what I would expect to be used for my QR code columns, not the one with barcode in the name.

**Comment by o1lab** [comment]
Did you happen to change the database using another tool ?

cc : @flisowna

**Comment by linucksrox** [comment]
I did not make any database changes manually.
As a test, I created the nc_col_barcode_v2 table by copying the qrcode schema and renaming it, which seemed to have resolved the issue. But I suspect something went wrong with the database migration from v 0.100.2 to 0.101.2

**Comment by include** [comment]
I am having a similar behavior. Created a column "Full Name" and another "FullName" can delete them. Another situation was changing the Column type from DateTime to Date. The column disappeared completely.

**Comment by o1lab** [comment]
@linucksrox - we werent able to reproduce & it appears to have resolved the issue. I suspect, this had to do with metadata changes (without your notice). Will reopen if we have other user facing it and more details like logs.

@include your problem is a different - pls raise another issue.
