### ISSUE TITLE
Issue: Error when editing by clicking edit button on column header

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#486]
I tried multiple times compiling and running each time getting error. Last week this issue was not there. Please see in case you are also facing this issue

NocoDB used as docker : false
NocoDB version : current
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : Both New Project, New Project by connecting to external database
Database on which spreadsheet is created : sqlite3
OS on which NocoDB is running : Windows
Node.js version if running as node : v14.17.3
Database version : as used by nocodb

**Steps To Reproduce**
1. Create project or import already created sqlite database
2. Go to grid view and try to edit by edit button on column header (although sqlite column type is restricted)
3. Will get error
4. 
![image](https://user-images.githubusercontent.com/86340924/130362813-1ce05317-8266-4204-b8b5-6e8a223b1584.png)

**Expected behavior**
Should show pop up

**Comment by o1lab** [comment]
Was unable to reproduce the issue.

Could you do a hard refresh so that new UI gets loaded. And give it a try again.

**Comment by AztrexDX** [comment]
I did hard refresh also but didn't work. When I used code from 1 week back creating separate build it worked fine. Will see if there some issue with data.

**Comment by AztrexDX** [comment]
closing as it was some data issue
