### ISSUE TITLE
🐛 Bug: Unable to set myself as superadmin to access plugin list

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#4867]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I've been using Nocodb over the past year, and set some plugins to a shared plugin.

I've upgraded to the latest version, and I'm unable to access the plugins.

![image](https://user-images.githubusercontent.com/55474996/213013727-be208662-cd43-43a9-b641-99b110947bae.png)

This issue https://github.com/nocodb/nocodb/issues/4845 mentions that only superadmins can access the plugins, but I'm the first person to have create an account and I manage the instance. How can I set myself as superadmin on the backend?

### Desired Behavior

I need to access the Plugins list

### Project Details

NocoDB deployed on Railway, with Postgres as the database

### Attachements

There's a table in my Postgres called nc_users_v2. My role is set as `org-level-creator`, and my ID is `1`.

Should I rename it to something else?
Should I be modifying another table?

![image](https://user-images.githubusercontent.com/55474996/213015007-170446e1-ba17-4e69-be52-ac90621fd834.png)

![image](https://user-images.githubusercontent.com/55474996/213014558-127ea62f-18fa-4a77-9323-f8a57dbb8567.png)

**Comment by wingkwong** [comment]
You may update `roles` by changing to `org-level-creator,super`. Restart and retry.

**Comment by candideu** [comment]
@wingkwong That works! Thank you.

For reference, I went to the `nc_users_v2` table and updated my `roles` field from `org-level-creator` to `org-level-creator,super`. I then redeployed my Railway app.
