### ISSUE TITLE
Feature: bulk process column type during schema definition

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#487]
When creating new table and adding columns it takes time to create column one by one. A dialog to provide all fields at once will be very useful
![image](https://user-images.githubusercontent.com/86340924/130365488-4975647a-a3ce-4bce-9f1b-ca301bf55815.png)

**Comment by o1lab** [comment]
Yes, makes sense. It was like this earlier - will rethink about it.

**Comment by dstala** [comment]
v0.202.5 now has multi fields editor. thanks @AztrexDX for your input. please try out multi fields editor & help us make it better. 

https://docs.nocodb.com/fields/multi-fields-editor
