### ISSUE TITLE
🐛 Bug: Search on Kanban View not Working

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#4895]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Switch to Kanban View
2. Search for a record with the appropriate field and press enter
3. The search does not filter and the view is unchanged.

![image](https://user-images.githubusercontent.com/7414843/213828018-f7bad500-fabd-470a-991f-bf60869fac9e.png)

Error from the JS Dev Console:
```
SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 302 of the JSON data
    NuxtJS 128
index.e6f01166.js:1:8753
SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 284 of the JSON data
    NuxtJS 128
index.e6f01166.js:1:8753
SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 236 of the JSON data
    NuxtJS 128
index.e6f01166.js:1:8753
SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 236 of the JSON data
    NuxtJS 128
index.e6f01166.js:1:8753
SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 231 of the JSON data
    NuxtJS 128
index.e6f01166.js:1:8753
SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 261 of the JSON data
    NuxtJS 128
index.e6f01166.js:1:8753

```
There are no errors in the NocoDB Server logs.

### Desired Behavior

The search should function normally and filter the records in the Kanban view.

### Project Details

```
Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.101.2**
```

**Comment by dstala** [comment]
Fixed. Will be available in release https://github.com/nocodb/nocodb/milestone/22
