### ISSUE TITLE
🔦 One-to-one in LinkToAnotherRecord not implemented

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#491]
As titled.

**Steps To Reproduce**
1. Create 2 tables and some columns
2. Create a new column with ``LinkToAnotherRecord ``
3. One To One is dimmed and cannot be selected

**Expected behavior**
It is not dimmed 
It can be selected
Behind the scene it can link to another record

**Screenshots**

![image](https://user-images.githubusercontent.com/35857179/130428696-6ae73601-ccd0-42f5-9618-008ebee3f2d9.png)

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.11.23**

**Comment by rmeekers** [comment]
any updates on this? It seems that this is still not implemented? Or do I miss something?
<img width="394" alt="image" src="https://user-images.githubusercontent.com/5755308/177979600-8e8d7d8f-b2f8-4e3b-87a4-c1b43fda4cb5.png">

**Comment by devinnasar** [comment]
Hello, is there any progress on this or a workaround? This immediately shuts down usefulness for nocodb for me.

**Comment by devinnasar** [comment]
This is still driving me to other projects without this.

**Comment by danbarbarito** [comment]
Is this still not implemented? I don't see any way to do this seemingly simple thing...

**Comment by licht1stein** [comment]
This is is the main feature that is required.

**Comment by tan-yong-sheng** [comment]
Hi upvoted for this. One to one relationship is needed.

**Comment by florianheinze** [comment]
From a user perspective this seems like such a basic feature, feels odd that it is still missing, as the rest of NocoDB looks so promising.

My guess is there is a technical challenge why this is not implemented? Not on the DB level but on the handling/dialogs/whatever?

At least to mention it in the docs, that "one-to-one" "belongs-to" relationships is a missing feature, would be helpful.

Do we have any clue what is holding this back? Where to start to make this happen?

**Comment by ravindra-wts** [comment]
Still waiting for this update to be done

**Comment by YaokunLin** [comment]
would be excited if this feature is implemented.

**Comment by devinnasar** [comment]
I'm finished with nocodb. This is a basic relational feature and it is bizarre that it has taken this long for there to be any kind of response or alternative offered. I would recommend that people look elsewhere for these features.

**Comment by HRNPH** [comment]
any update on one2one or what's the problem adding it and how could we help?

**Comment by nonacc** [comment]
is there any chance you prioritize this feature please? it's super crucial.

**Comment by o1lab** [comment]
[Available in 0.207](https://github.com/nocodb/nocodb/releases/tag/0.207.0)
