### ISSUE TITLE
Feature: Allow custom CSS injection

### ISSUE THREAD

**Issue by hannahildebrandt** [nocodb/nocodb#4913]
I'd love to have the option to inject custom global CSS to allow extra customization, such as being able to force max heights on longtext fields or to adjust interface colours.

The easiest way to do this would be to check for something like "custom.css" and load it along with the rest of the CSS, though an even easier option would be to literally add a style tag to the page header pointing to an external CSS, which just silently fails if the file doesn't exist. The extreme option would be a "custom CSS rules" box on the settings page.

Regardless, I think this would be a great addition, because:

1. It's extremely low-stakes, it's extremely difficult to break things completely through CSS alone, doesn't affect any other systems, and if things do break from user error, you can fix it by just killing off that CSS files
2. It opens up the opportunity for people to make fairly robust custom themes, which could make NocoDB more appealing to people who like deeper customization or the ability to brand an interface
3. It allows users to "fix" things in NocoDB that might not be "broken", but don't work well with their workflow (like the aforementioned longtext fields, which are fine for 90% of use cases but make navigation extremely difficult for people storing large amounts of text -- something which can be fixed with a single line of CSS. This can currently be achieved by using another extension to inject CSS at the browser level, but doesn't help clients who may not have the ability to run an additional extension or just want to access it from a new computer/browser).

**Comment by candideu** [comment]
Love this idea, especially the Custom CSS option in the settings! This level of customization isn't even possible on Airtable.

**Comment by dstala** [comment]
To be tracked along with

[Feature request : CSS Styling](https://github.com/nocodb/nocodb/issues/181)
