### ISSUE TITLE
data issues with Firefox 

### ISSUE THREAD

**Issue by distresscode** [nocodb/nocodb#4927]
@dstala issue is back - data is getting wiped in firefox 109.0 (64-bit).

Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.101.2**
com.nocodb.cloudronapp@1.9.1

_Originally posted by @distresscode in https://github.com/nocodb/nocodb/issues/4329#issuecomment-1404183957_

**Comment by distresscode** [comment]
Creating a new column type caused the data to get deleted the behavior is identical as in issue #4329

**Comment by wingkwong** [comment]
I installed firefox 109.0 and tried the steps you mentioned for like 5 minutes and couldn't see the data missing. Any errors you could see from the logs?

**Comment by distresscode** [comment]
@wingkwong Noco is installed via Cloudron. I only see an .env file and my upload folder, no log files. In the app, there's an "audit" section. Is that it?

**Comment by dstala** [comment]
@distresscode couldn't reproduce it either. can you check if you are still facing this issue with noco release v0.202.5? reopen this thread if you still have this issue.
