### ISSUE TITLE
🐛 Bug:  Failed Upgrade 0.100.2 to  0.104.1

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#4948]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

With docker, change version nocodb/nocodb:0.100.2 to nocodb/nocodb:0.104.1

### Desired Behavior

Migration Done with success

### Project Details

NocoDB use as Docker : True

### Attachements

```

App started successfully.
Visit -> http://localhost:8080/dashboard
┌ Migration from 0098005 to 0101002 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      ││   TypeError: e.getConnectionConfig is not a function                         ││   at Function.get (/usr/src/app/docker/main.js:1:59295)                      ││   at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458050)   ││   at processTicksAndRejections (node:internal/process/task_queues:96:5)      ││   at async Function.upgrade (/usr/src/app/docker/main.js:1:1435436)          ││   at async q.init (/usr/src/app/docker/main.js:1:7461)                       ││   at async /usr/src/app/docker/main.js:1:634009                              ││                                                                              ││                                                                              ││   Please raise an issue in our github by using following link :              ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   ││   e=bug_report.md                                                            ││                                                                              ││   Or contact us in our Discord community by following link :                 ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
TypeError: e.getConnectionConfig is not a function
    at Function.get (/usr/src/app/docker/main.js:1:59295)
    at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458050)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.upgrade (/usr/src/app/docker/main.js:1:1435436)
    at async q.init (/usr/src/app/docker/main.js:1:7461)
    at async /usr/src/app/docker/main.js:1:634009


```

**Comment by o1lab** [comment]
App started successfully.
Visit -> http://localhost:8080/dashboard
┌ Migration from 0098005 to 0101002 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      ││   TypeError: e.getConnectionConfig is not a function                         ││   at Function.get (/usr/src/app/docker/main.js:1:59295)                      ││   at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458050)   ││   at processTicksAndRejections (node:internal/process/task_queues:96:5)      ││   at async Function.upgrade (/usr/src/app/docker/main.js:1:1435436)          ││   at async q.init (/usr/src/app/docker/main.js:1:7461)                       ││   at async /usr/src/app/docker/main.js:1:634009                              ││                                                                              ││                                                                              ││   Please raise an issue in our github by using following link :              ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   ││   e=bug_report.md                                                            ││                                                                              ││   Or contact us in our Discord community by following link :                 ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
TypeError: e.getConnectionConfig is not a function
    at Function.get (/usr/src/app/docker/main.js:1:59295)
    at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458050)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.upgrade (/usr/src/app/docker/main.js:1:1435436)
    at async q.init (/usr/src/app/docker/main.js:1:7461)
    at async /usr/src/app/docker/main.js:1:634009

**Comment by syji35** [comment]
I tried to install version 0.101.2, but I got an error that the migration folder is corrupt :

```
App started successfully.
Visit -> http://localhost:8080/dashboard
Error: The migration directory is corrupt, the following files are missing: nc_025_add_row_height
    at validateMigrationList (/usr/src/app/node_modules/knex/lib/migrations/migrate/Migrator.js:566:11)
    at Migrator.latest (/usr/src/app/node_modules/knex/lib/migrations/migrate/Migrator.js:69:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async s.metaInit (/usr/src/app/docker/main.js:1:586942)
    at async $.init (/usr/src/app/docker/main.js:1:7370)
    at async /usr/src/app/docker/main.js:1:630700
```

What can I do ?

**Comment by pranavxc** [comment]
@syji35 : Can you try the following PR build?

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.104.1-pr-4947-20230127-1553
```
