### ISSUE TITLE
🐛 Bug: Firefox issue with fixed row heigh

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4952]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

<img width="1391" alt="Screenshot 2023-01-27 at 22 29 39" src="https://user-images.githubusercontent.com/5435402/215218493-9305601b-3451-468d-95a9-6c9665789799.png">

### Desired Behavior

.

### Project Details

0.104+

**Comment by dstala** [comment]
will be available in release https://github.com/nocodb/nocodb/milestone/22
