### ISSUE TITLE
🔦 Feature: Documentation of relations

### ISSUE THREAD

**Issue by Varming73** [nocodb/nocodb#4962]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

On the [documentation page](https://docs.nocodb.com/setup-and-usages/link-to-another-record) for relations there is no mention of how to use On Update, On Delete and the Virtual Relation. Especially the Virtual Relation is not easy to guess how is used.

![image](https://user-images.githubusercontent.com/60294362/215273538-4963e67e-da02-40d6-87b8-f5063a4635d1.png)

### Suggested Solution

Update the documentation so that it reflects the actual fields.

**Comment by dstala** [comment]
'On Update' & 'On Delete' actions are now deprecated with introduction of "Links" field. To be revisited if we introduce it back.
