### ISSUE TITLE
Error on Start after docker-compose down, docker-compose pull, docker-compose up -d

### ISSUE THREAD

**Issue by cr4zyiw4n** [nocodb/nocodb#4965]
Hi guys, 
i got an error after pulling the new docker image file via docker-compose.

docker-compose version 1.25.0, build unknown

I have a backup, so its no problem. 
But maybe interesting for you?

┌ Migration from 0098005 to 0101002 failed ────────────────────────────────────┐
│                                                                              
││   Error                                                                      
││   -----                                                                      
│
│   Error: Malformed UTF-8 data                                                
││   at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)   
││   at WordArray.init.toString                                                 
││   (/usr/src/app/node_modules/crypto-js/core.js:278:38)                       
││   at h.getConnectionConfig (/usr/src/app/docker/main.js:1:72475)             
││   at Function.get (/usr/src/app/docker/main.js:1:59295)                      
││   at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458069)   
││   at processTicksAndRejections (node:internal/process/task_queues:96:5)      
││   at async Function.upgrade (/usr/src/app/docker/main.js:1:1435436)          
││   at async q.init (/usr/src/app/docker/main.js:1:7461)                       
││   at async /usr/src/app/docker/main.js:1:634009                              
││                                                                              
││                                                                              
││   Please raise an issue in our github by using following link :              
││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   
││   e=bug_report.md                                                            
││                                                                              
││   Or contact us in our Discord community by following link :                 
││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     
││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
Error: Malformed UTF-8 data
    at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)
    at WordArray.init.toString (/usr/src/app/node_modules/crypto-js/core.js:278:38)
    at h.getConnectionConfig (/usr/src/app/docker/main.js:1:72475)
    at Function.get (/usr/src/app/docker/main.js:1:59295)
    at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458069)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.upgrade (/usr/src/app/docker/main.js:1:1435436)
    at async q.init (/usr/src/app/docker/main.js:1:7461)
    at async /usr/src/app/docker/main.js:1:634009

**Comment by mertmit** [comment]
Hi, thank you for the report.
If possible can you share which database you were using as NC_DB? Have you used any other tool and interfered with the database you used for NocoDB instance?

**Comment by cr4zyiw4n** [comment]
Hi mertmit,
yes of course.

I'm using 10.5.18-MariaDB.
There were no other tools i used. 
Just docker-compose down, pull and up

**Comment by mertmit** [comment]
This error is related to NC_AUTH_JWT_SECRET, you must use same one for same NC_DB after initial setup.
If you've left it empty & tried to add afterwards it will also fail (in this case one will be randomly generated for you which you can find in nc_store table inside your database)
