### ISSUE TITLE
🐛 Bug: Valid attachment JSON is replaced with escaped JSON when saving in Kanban view

### ISSUE THREAD

**Issue by HappyFr1day** [nocodb/nocodb#4971]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Likely related to this:

https://github.com/nocodb/nocodb/issues/4691

Repro:

- Create a table with an attachment column and a singleselect colum
- Add a row with an attachment (in my example, I used /bin/ls)
- Create a Kanban view stacked over the singleselect column
- Open the new row in the kanban view, then save it
- Observe the attachment is no longer accessible; on 0.100.2, the entire Kanban view dies.

PG Contents before/after edit:
```

root_db=# select * from "nc__f8r___AttachmentTest";
 id | title |       created_at       |         updated_at         |                                                                  Attachment                                                                   | Status 
----+-------+------------------------+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+--------
  1 |       | 2023-01-30 17:51:16.76 | 2023-01-30 17:54:25.113746 | [{"path":"download/noco/Test/AttachmentTest/Attachment/ICsSBksorsFMJ4Od9a","title":"ls","mimetype":"application/octet-stream","size":138208}] | One
(1 row)

root_db=# select * from "nc__f8r___AttachmentTest";
 id | title |       created_at       |         updated_at         |                                                                          Attachment                                                                           | Status 
----+-------+------------------------+----------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+--------
  1 |       | 2023-01-30 17:51:16.76 | 2023-01-30 17:54:47.440316 | {"{\"path\":\"download/noco/Test/AttachmentTest/Attachment/ICsSBksorsFMJ4Od9a\",\"title\":\"ls\",\"mimetype\":\"application/octet-stream\",\"size\":138208}"} | One
(1 row)

```

The following JSON request is submitted by the browser frontend shortly before the error occurs:
'PATCH | http://127.0.0.1:8080/api/v1/db/data/noco/Test/AttachmentTest/2'

Req:

```{"Id":2,"CreatedAt":"2023-01-30T17:57:05.313Z","UpdatedAt":"2023-01-30T17:57:05.313Z","Attachment":[{"path":"download/noco/Test/AttachmentTest/Attachment/e_B-0ZkMRINUZt_pjy","title":"ls","mimetype":"application/octet-stream","size":138208}]}```

Resp:

```{"Id":2,"Title":null,"CreatedAt":"2023-01-30T17:57:05.313Z","UpdatedAt":"2023-01-30T17:57:11.896Z","Attachment":"{\"{\\\"path\\\":\\\"download/noco/Test/AttachmentTest/Attachment/e_B-0ZkMRINUZt_pjy\\\",\\\"title\\\":\\\"ls\\\",\\\"mimetype\\\":\\\"application/octet-stream\\\",\\\"size\\\":138208}\"}","Status":null}```

### Desired Behavior

The attachment doesn't go away, and the row's valid attachment isn't replaced with broken attachment JSON.

### Project Details

Observed against:
Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.104.2**

**Comment by HappyFr1day** [comment]
A colleague was able to reproduce this in front of me with the grid view as well (they edited several fields), but I don't have and can't get logs from that right now, and it's not reproducing for me on my test instance.

**Comment by wingkwong** [comment]
@HappyFr1day Did your colleague use the same instance? In the given project info, you showed the version is 0.104.2 but you also showed 0.100.2 in your steps. So which version is your colleague using?

**Comment by HappyFr1day** [comment]
@wingkwong My colleague was using a different instance on 0.100.2, I tested with a clean instance on 0.104.2. I see similar bad data in the Postgres database on both instances.

Also, I was able to reproduce my colleague's issue by switching grid views after editing a row - the attachment JSON in the database gets corrupted:
- Create a new table and an additional grid view for that table
- Add an attachment column and a singleselect column
- Upload an attachment
- Change the value in the singleselect column
- Select the other view in the same table
- The attachment will disappear on the UI and the attachment JSON in Postgres will be corrupted/escaped. I have reproduced this on 0.100.2 and 0.104.2.

Thanks!

**Comment by HappyFr1day** [comment]
This use case is also broken with SQLite on 0.104.2 (docker):

```
[Error: update `nc_ju3f___Test` set `title6` = {"path":"download/noco/Test/Test/title6/kqTmfRSqTMEt3CrSeA","title":"ls","mimetype":"application/octet-stream","size":138208} where `id` = '2' - SQLITE_ERROR: unrecognized token: "{"] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
A :: [Error: update `nc_ju3f___Test` set `title6` = {"path":"download/noco/Test/Test/title6/kqTmfRSqTMEt3CrSeA","title":"ls","mimetype":"application/octet-stream","size":138208} where `id` = '2' - SQLITE_ERROR: unrecognized token: "{"] {
  errno: 1,
  code: 'SQLITE_ERROR'
}

```
[sqlite.txt](https://github.com/nocodb/nocodb/files/10550669/sqlite.txt)

```
Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.104.2**
```

**Comment by wingkwong** [comment]
Thanks for the steps. I could reproduce now. Will investigate today.

**Comment by wingkwong** [comment]
@HappyFr1day Can you try on the following image?

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.104.2-pr-4987-20230201-0939
```

**Comment by HappyFr1day** [comment]
@wingkwong 

Looks good on both my SQLite test instance and postgres test instance. It's not reproducing with either the grid or kanban view.

**Comment by wingkwong** [comment]
Thanks for confirming.
