### ISSUE TITLE
🐛 Bug: nc-icon display issues

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#4974]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

some icons position are unexpected.

![image](https://user-images.githubusercontent.com/35857179/215667763-53d34fa3-aab9-4ed5-ae83-19057aad52ce.png)

### Desired Behavior

They should be inline

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.104.2**

**Comment by dstala** [comment]
Will be available in https://github.com/nocodb/nocodb/milestone/22
