### ISSUE TITLE
🐛 Bug: save row on linking a record

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#4978]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Add a new row
Add link without entering any other data
Refresh

### Desired Behavior

Row should be saved

### Project Details

develop

### Attachements

https://user-images.githubusercontent.com/59797957/215714623-f0a29241-e8cb-4b26-a3c5-b2378b331d8e.mov

**Comment by dstala** [comment]
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.104.2**
