### ISSUE TITLE
🐛 Bug: Re-ordering of images creates invalid input syntax for type json error

### ISSUE THREAD

**Issue by GordonFleming** [nocodb/nocodb#4985]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When trying to re-order any images, I get the following response after trying to save the order:

> 2023-01-31T19:58:35.065190512Z A :: error: update "nc_gtel__products" set "images" = E'{"{\\"url\\":\\"some_mg.webp\\",\\"title\\":\\"Ow7Ij0_Super Kick Off Blue White_new_cropped.webp\\",\\"mimetype\\":\\"image/webp\\",\\"size\\":19990}","{\\"url\\":\\"some_url.com\\",\\"title\\":\\"Super Kick Off Black White.jpg\\",\\"mimetype\\":\\"image/jpeg\\",\\"size\\":4170143}","{\\"url\\":\\"https:///9d8eLu_Super Kick Off Red White_new.webp\\",\\"title\\":\\"Super Kick Off Red White_new.webp\\",\\"mimetype\\":\\"image/webp\\",\\"size\\":20152}"}' where "id" = '41' - invalid input syntax for type json
> 2023-01-31T19:58:35.065044922Z at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
> 2023-01-31T19:58:35.065050191Z at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
> 2023-01-31T19:58:35.065053678Z at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
> 2023-01-31T19:58:35.065056975Z at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
> 2023-01-31T19:58:35.065060752Z at Socket.emit (node:events:513:28)
> 2023-01-31T19:58:35.065078036Z at Socket.emit (node:domain:489:12)
> 2023-01-31T19:58:35.065081161Z at addChunk (node:internal/streams/readable:315:12)
> 2023-01-31T19:58:35.065084027Z at readableAddChunk (node:internal/streams/readable:289:9)
> 2023-01-31T19:58:35.065086752Z at Socket.Readable.push (node:internal/streams/readable:228:10)
> 2023-01-31T19:58:35.065089627Z at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
> 2023-01-31T19:58:35.065092463Z length: 210,
> 2023-01-31T19:58:35.065095198Z severity: 'ERROR',
> 2023-01-31T19:58:35.065098043Z code: '22P02',
> 2023-01-31T19:58:35.065100809Z detail: 'Expected ":", but found ",".',
> 2023-01-31T19:58:35.065103965Z hint: undefined,
> 2023-01-31T19:58:35.065106500Z position: '43',
> 2023-01-31T19:58:35.065109366Z internalPosition: undefined,
> 2023-01-31T19:58:35.065112121Z internalQuery: undefined,
> 2023-01-31T19:58:35.065114936Z where: 'JSON data, line 1: ...p\\",\\"mimetype\\":\\"image/webp\\",\\"size\\":19990}",...',
> 2023-01-31T19:58:35.065118583Z schema: undefined,
> 2023-01-31T19:58:35.065121329Z table: undefined,
> 2023-01-31T19:58:35.065123944Z column: undefined,
> 2023-01-31T19:58:35.065126639Z dataType: undefined,
> 2023-01-31T19:58:35.065129223Z constraint: undefined,
> 2023-01-31T19:58:35.065132059Z file: 'jsonfuncs.c',
> 2023-01-31T19:58:35.065134684Z line: '621',
> 2023-01-31T19:58:35.065137259Z routine: 'json_ereport_error'
> 2023-01-31T19:58:35.065139974Z }

### Desired Behavior

This should just simply re-order the images, as it did in previous versions. I am not sure what has changed here, but it did just work previously. 

### Project Details

Docker: true
Database: Postgres < v14.1
OS: Ubuntu < v20
Deployment: Caprover
NocoDb: 0.104.2

**Comment by wingkwong** [comment]
@GordonFleming Can you try on the following image?

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.104.2-pr-4987-20230201-0939
```

**Comment by GordonFleming** [comment]
Thank you @wingkwong working perfectly now. 😄
