### ISSUE TITLE
🐛 Bug: No picture showed if there is only a single picture attachment in Gallery View

### ISSUE THREAD

**Issue by chxp** [nocodb/nocodb#4991]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### original data:
![Screenshot_20230201_185041](https://user-images.githubusercontent.com/14882692/216024613-947a8c05-0833-4887-a628-b3187b8c2881.png)

### gallery view:
![Screenshot_20230201_185115](https://user-images.githubusercontent.com/14882692/216024694-9de889b1-543f-4136-9102-b6671fc3bd80.png)

### if row 1 has 2 pictures attachment
![Screenshot_20230201_185159](https://user-images.githubusercontent.com/14882692/216024834-76b7fa4b-c525-48a2-af91-939639c01b7a.png)
Meanwhile, the second picture of row 1 still sees nothing in the gallery view.

### Desired Behavior

- Display the picture if there is only a single picture attachment.

- Display all the pictures if there are many picture attachments in the row.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.104.2**

**Comment by wingkwong** [comment]
Duplicated as #4958. The issue has been resolved. Please wait for the next release.

![image](https://user-images.githubusercontent.com/35857179/216031924-0ca8a05a-2773-47e9-800d-9f9a71f86b7a.png)
