### ISSUE TITLE
🐛 Bug: Performance degradation when upgrading to 0.104.2

### ISSUE THREAD

**Issue by davidpfahler** [nocodb/nocodb#4992]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I just upgraded our production environment from 0.101.0-beta.0 to 0.104.2. Switching from one table to another is noticeably slower which I suspect is due to the new row height feature requiring a lot more work on the client.

### Desired Behavior

Opening a table should display the data as fast as possible.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.104.2**

**Comment by o1lab** [comment]
Thanks for the reporting.

@mertmit - please have a look

**Comment by pavelkalin** [comment]
We also see this problem in our development

**Comment by distresscode** [comment]
My instance is running slow too after the recent updates. I'm using Noco on Cloudron.

Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.104.3**

**Comment by mertmit** [comment]
Thank you for reporting this issue.
If possible can you try PR build and feedback if this is resolved.
```docker run -d -p 8888:8080 nocodb/nocodb-timely:0.104.3-pr-5015-20230203-0852```

**Comment by davidpfahler** [comment]
@mertmit Unfortunately, I cannot notice an improvement in performance. It actually appear to me that there is further drastic performance degradation going from `0.104.2` to `0.104.3`, but that is just a feeling. Data not not only seems to need long to render on the client side, but it actually take very long for any data whatsoever to arrive.

Just looking at the network tab, it seems like for some boards nocodb is making dozen even hundreds of requests when the board contains a file column and **is downloading all the files attached to the rows every time**. Boards without a file column seem ok.

**Comment by davidpfahler** [comment]
@mertmit @o1lab You need to see this, this is pretty broken on `0.104.3`. This is the network tab when I open our invoices table, which has an attachments column that has one PDF per row:

https://user-images.githubusercontent.com/908242/217005100-11ae789d-cc40-4448-9122-5e46eb09bed2.mov

**Comment by davidpfahler** [comment]
Yes, both this build and latest

**Comment by o1lab** [comment]
We are looking into it & will keep it posted.

**Comment by mertmit** [comment]
@davidpfahler this PR resolves attachment issue as well, please let me know if performance issue still persists
`docker run -d -p 8888:8080 nocodb/nocodb-timely:0.104.3-pr-5046-20230206-1740`

**Comment by davidpfahler** [comment]
@mertmit This feels much faster now. The attachment issue is definitely fixed. Thanks!
