### ISSUE TITLE
🔦 Feature: Add S3 endpoint & S3 path style option to env vars

### ISSUE THREAD

**Issue by loulou2852** [nocodb/nocodb#4993]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I'm using an alternative S3 provider (Contabo object storage), but actually, there is no custom endpoints in env vars. (ie NC_S3_ENDPOINT).
This allows integrating other S3 compatible providers in Nocodb.

Furthermore, Contabo use “path style” type of request. 
So maybe including an option to set a path style to true via NC_S3_PATH_STYLE var.

### Suggested Solution

Ideally,

Adding to environment vars NC_S3_ENDPOINT & NC_S3_PATH_STYLE, so that other S3 providers can connect to Nocodb.

### Additional Context

If necessary, I can provide access to a Contabo Bucket if needed in private for testing purpose.

**Comment by loulou2852** [comment]
It can be an addition of another plugin similar to S3, with these two parameters added.

**Comment by AzazKamaz** [comment]
For specifying endpoint there exists Minio plugin. [Minio](https://min.io) is basically self hosted S3 compatible storage, so you can point that plugin to any S3 you want

**Comment by loulou2852** [comment]
![](https://user-images.githubusercontent.com/4818634/217372164-9a900eb7-cb61-4a2a-ae1b-50fe2b3bf5d1.png)

I tested with the MINIO one, the file is saved in the object sotrage, but due to lack of path style setting missing or something else, it can't detect the image within nocodb.

this is the 404 url I've got from Nocodb screenshot cell: [https://eu2.contabostorage.com:443/nocodb/nc/uploads/noco/Test/Content/file/f_J0q9uxQgR-xo0jg6.jpg](https://eu2.contabostorage.com:443/nocodb/nc/uploads/noco/Test/Content/file/f_J0q9uxQgR-xo0jg6.jpg)

This is a working url from contabstorage:

[https://eu2.contabostorage.com/84721fb304514bc6a1901ae7e2107411:nocodb/nc/uploads/noco/Test/Content/file/f_J0q9uxQgR-xo0jg6.jpg](https://eu2.contabostorage.com/84721fb304514bc6a1901ae7e2107411:nocodb/nc/uploads/noco/Test/Content/file/f_J0q9uxQgR-xo0jg6.jpg)

And this is the settings:

![](https://user-images.githubusercontent.com/4818634/217375105-b3b1f80b-76fb-40fe-91b9-829d99a21956.png)

**Comment by AzazKamaz** [comment]
> https://eu2.contabostorage.com/84721fb304514bc6a1901ae7e2107411:nocodb/nc/uploads/noco/Test/Content/file/f_J0q9uxQgR-xo0jg6.jpg

Maybe you can just use `84721fb304514bc6a1901ae7e2107411:nocodb` as bucket name?
As I remember, bucket name is used only in url so if it is the same for downloading and uploading you can just use it

**Comment by AlexSnet** [comment]
Could you please add an ability to change region of minio endpoint?

**Comment by salim-b** [comment]
- Support for `NC_S3_ENDPOINT` env var was added in https://github.com/nocodb/nocodb/pull/8886 (it currently requires support for "object-level ACLs" by the object storage provider, see https://github.com/nocodb/nocodb/issues/9054). 

- https://github.com/nocodb/nocodb/pull/9137 will introduce support for `NC_S3_PATH_STYLE`, it appears.

**Comment by DarkPhoenix2704** [comment]
Both PathStyle and the Endpoint are added to the S3 Plugin
They can also be configured via [envs](https://docs.nocodb.com/getting-started/self-hosted/environment-variables/#storage)
