### ISSUE TITLE
🐛 Bug: Illegal arguments (string, object) on sign in

### ISSUE THREAD

**Issue by ruieduardolopes** [nocodb/nocodb#4997]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I had created an account and then on sign in the following error appears: "Illegal arguments: string, object". This is depicted in an attachment.

### Desired Behavior

It is desirable to fill out my e-mail address (the account was verified to be already created) and password, and to be able to successfully log in.

### Project Details

NocoDB version 0.104.2, running on Docker

### Attachments

![Screenshot 2023-02-02 at 10 10 23](https://user-images.githubusercontent.com/6137052/216299462-576e2001-e64c-44a3-b0ea-dc2cfcc0bed6.png)

**Comment by wingkwong** [comment]
preliminary finding: it seems it happens when a null salt to be hashed.

**Comment by kvr2007** [comment]
Apologies for re-opening an old issue, I have discovered another case when this error occurs. Here is my system info (running in docker):
```
Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.255.2**
```
to reproduce:
1. create a new account associated with an email
2. try to log in (not sign up) using this email and any password

The issue goes away once the sign-up was properly performed.

Maybe a more informative error message would be helpful here?
