### ISSUE TITLE
Enhancement: UX: default value configuration

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5013]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Moving changes from here https://github.com/nocodb/nocodb/issues/4573

- Default value- should be able to configure without explicit quotes
- Default value- make it similar to grid cell (use picker/select options/...)
- Example was not displayed for datatype number
- Add support for Database functions as well (CURRENT_TIMESTAMP, and such)
-  Edit column menu : Column name is highlighted on opening menu. Click on `esc` first time should move away from edit mode for column name text box; clicking `esc` again should close modal
- [ ] [to be discussed before staring on this] column create menu & edit menu - make it minimal
  
<img width="466" alt="Screenshot 2023-01-30 at 9 22 53 PM" src="https://user-images.githubusercontent.com/86527202/215526281-8d2a79ab-2b13-40b5-83f9-d56a7c5308c0.png">

### Desired Behavior

Better way to configure default values

### Project Details

`develop`

**Comment by 3699n** [comment]
I just noticed that if you try to include a question mark `?` in the default value of a long text field, it is replaced with a dollar sign `$`.
