### ISSUE TITLE
🐛 Bug: old data remains in spreadsheet

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#5020]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

If i switch tabs(1,2,3,4...), then some data not dissapearing until i press row height and change it to different value.

### Desired Behavior

The fields are empty in the database, it should be blank.

### Project Details

Docker, postgres, 0.104.3

### Attachments

![image](https://user-images.githubusercontent.com/117290601/216655734-b880a2d1-ae3f-4f09-ba1c-493050fdec26.png)
![image](https://user-images.githubusercontent.com/117290601/216655800-1a460bbe-6b07-49a9-bf1f-5e0972e18d32.png)

**Comment by mertmit** [comment]
Hey @emre1e, thank you for reporting, this issue fixed by: https://github.com/nocodb/nocodb/commit/64163881535d3dc953eb6d029bbfe825e34ea49f

Can you confirm if this build fix your issue:
`docker run -d -p 8888:8080 nocodb/nocodb-timely:0.104.3-pr-5015-20230203-0852`

**Comment by dstala** [comment]
will be available in https://github.com/nocodb/nocodb/milestone/24
