### ISSUE TITLE
Feature:  In shared Grid view it's not possible to edit or add data

### ISSUE THREAD

**Issue by Varming73** [nocodb/nocodb#5028]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

In a shared grid view the button to add a new row is there but it's not possible to enter values in that row. Neither is it possible to update/edit data in existing rows

### Desired Behavior

In a shared grid view it should be possible to add new rows and edit/update data in existing rows in a table.

### Project Details

All versions

**Comment by danieltarazona** [comment]
Confirmed!

**Comment by dstala** [comment]
to be tracked under
https://github.com/nocodb/nocodb/issues/815
