### ISSUE TITLE
🐛 Bug: Failed Upgrade 0.100.2 to 0.104.1

### ISSUE THREAD

**Issue by kevin-lot** [nocodb/nocodb#5032]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Migration from 0100002 to 0104002

### Desired Behavior

Working migration

### Project Details

App started successfully.
--
Visit -> https://nocodb.dotic.fr/dashboard
┌ Migration from 0100002 to 0104002 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      ││   Error: Malformed UTF-8 data                                                ││   at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)   ││   at WordArray.init.toString                                                 ││   (/usr/src/app/node_modules/crypto-js/core.js:278:38)                       ││   at h.getConnectionConfig (/usr/src/app/docker/main.js:1:72106)             ││   at Function.get (/usr/src/app/docker/main.js:1:59320)                      ││   at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458406)   ││   at processTicksAndRejections (node:internal/process/task_queues:96:5)      ││   at async Function.upgrade (/usr/src/app/docker/main.js:1:1435630)          ││   at async q.init (/usr/src/app/docker/main.js:1:7461)                       ││   at async /usr/src/app/docker/main.js:1:634156                              ││                                                                              ││                                                                              ││   Please raise an issue in our github by using following link :              ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   ││   e=bug_report.md                                                            ││                                                                              ││   Or contact us in our Discord community by following link :                 ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
Error: Malformed UTF-8 data
at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)
at WordArray.init.toString (/usr/src/app/node_modules/crypto-js/core.js:278:38)
at h.getConnectionConfig (/usr/src/app/docker/main.js:1:72106)
at Function.get (/usr/src/app/docker/main.js:1:59320)
at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458406)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Function.upgrade (/usr/src/app/docker/main.js:1:1435630)
at async q.init (/usr/src/app/docker/main.js:1:7461)
at async /usr/src/app/docker/main.js:1:634156

**Comment by pranavxc** [comment]
If you had defined `NC_AUTH_JWT_SECRET` environment value earlier then you have to use the same key even when upgrading since it is suing to encrypt/decrypt the project config. The above error happens when the secret key is different.

**Comment by kevin-lot** [comment]
However I am using exactly the same token, it has not changed since the server was started.
NocoDB is started on AWS with ECS Fargate using the latest version available on dockerhub.
I only change the version of the docker image.

**Comment by o1lab** [comment]
Also use the latest `0.104.3`

**Comment by kevin-lot** [comment]
```
App started successfully.
--
Visit -> https://nocodb.dotic.fr/dashboard
┌ Migration from 0100002 to 0104002 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      ││   Error: Malformed UTF-8 data                                                ││   at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)   ││   at WordArray.init.toString                                                 ││   (/usr/src/app/node_modules/crypto-js/core.js:278:38)                       ││   at h.getConnectionConfig (/usr/src/app/docker/main.js:1:72106)             ││   at Function.get (/usr/src/app/docker/main.js:1:59320)                      ││   at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458406)   ││   at processTicksAndRejections (node:internal/process/task_queues:96:5)      ││   at async Function.upgrade (/usr/src/app/docker/main.js:1:1435630)          ││   at async q.init (/usr/src/app/docker/main.js:1:7461)                       ││   at async /usr/src/app/docker/main.js:1:634156                              ││                                                                              ││                                                                              ││   Please raise an issue in our github by using following link :              ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   ││   e=bug_report.md                                                            ││                                                                              ││   Or contact us in our Discord community by following link :                 ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
Error: Malformed UTF-8 data
at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)
at WordArray.init.toString (/usr/src/app/node_modules/crypto-js/core.js:278:38)
at h.getConnectionConfig (/usr/src/app/docker/main.js:1:72106)
at Function.get (/usr/src/app/docker/main.js:1:59320)
at Object.t.default [as handler] (/usr/src/app/docker/main.js:1:1458406)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Function.upgrade (/usr/src/app/docker/main.js:1:1435630)
at async q.init (/usr/src/app/docker/main.js:1:7461)
at async /usr/src/app/docker/main.js:1:634156
```

Sorry, I have the same error.

**Comment by kevin-lot** [comment]
My bad, issue was on your own.
The database was migrated, and I think the `NC_AUTH_JWT_SECRET` was the same at this moment.
Like you said here https://github.com/nocodb/nocodb/issues/5032#issuecomment-1416796155.

If the `NC_AUTH_JWT_SECRET` was not changed, maybe the database was.

Sorry about that. I reset my database, no issue now.

Best regards.
