### ISSUE TITLE
🐛 Bug: Some features not working on hosted without internet connection

### ISSUE THREAD

**Issue by andrzejhoc** [nocodb/nocodb#5036]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Some features not working without access to the Internet:

- Kanban board 
- Swagger API

Missing required javascripts and css

### Desired Behavior

All external links to CDN on hosted environment should be accessible locally. I propose to use fallback url parameter to custom CDN.

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.104.3**

**Comment by wingkwong** [comment]
Can you show which js & css are missing?

**Comment by andrzejhoc** [comment]
For example when enter url:
http://localhost:8080/api/v1/db/meta/projects/p_dxlz1g5eaf2i0f/swagger
These javascripts need to be accesible
https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.5.2/swagger-ui-bundle.min.js
https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.5.2/swagger-ui.min.css

But as I said when there is no internet connection there is a problem with
displaying website.

Generally when you scan your source code within typescript files than you
will find script section which contains url to 'https://cdnjs.cloudflare.com
'.
I'm using Nocodb in hosted environment without internet connection so this
is a big problem for me.

**Comment by wingkwong** [comment]
Thanks. Will look into it.
