### ISSUE TITLE
🔦 Feature: bulk / batch update column for multiple rows

### ISSUE THREAD

**Issue by davidpfahler** [nocodb/nocodb#5045]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

As a user, I would like to be able to batch update one column of several selected rows at once. For example, if I had a `Todos` table with columns `title` and `status`, I would like to be able to select several rows and change their `status` from `to do` to `done`.

### Suggested Solution

I do not want to presume what the best UI/UX would be for this feature, but one idea could be to have an Excel-style "Extend series or fill"

**Comment by o1lab** [comment]
We will prioritise this after our release next week.

**Comment by max-santiago** [comment]
Are there any updates on this?

**Comment by wingkwong** [comment]
Currently you can achieve this by using Bulk Update API with conditions. The below example would update `status` to `done` for those records with ID greater than 5.

```
curl -X 'PATCH' \
http://localhost:8080/api/v1/db/data/bulk/noco/foo/bar/all?where=(Id,gt,5) \
-H "Content-Type: application/json" \
-H 'accept: application/json' \
-H 'xc-auth: <REDACTED>' \
--data '{ "status": "done" }'
```

**Comment by davidpfahler** [comment]
@wingkwong Thanks, but this is impractical (at least for me) to link several entries at once to another entry (in my case link time entries to an invoice).

**Comment by davidpfahler** [comment]
It seem this was not included in release `0.106.0` correct?

**Comment by wingkwong** [comment]
@davidpfahler so far I don't see there s any PR linking to this issue. The batch-update on UI is not available in 0.106.0.

**Comment by davidpfahler** [comment]
@wingkwong I was just asking because @o1lab said it would be in the next release. I understand plans change, it's just that it would be a really useful feature.

**Comment by dstala** [comment]
Bulk update from UI is available in NocoDB hosted solution. 

For a free technical preview, visit www.nocodb.com

**Comment by aks-cadesign** [comment]
when will it be available on the self hosted solution? Unfortunately, without this feature, NocoDB is completely useless for a lot of use-cases.
