### ISSUE TITLE
🐛 Bug: No autosave when moving to "Next Row" in expanded record view

### ISSUE THREAD

**Issue by perplexes** [nocodb/nocodb#5049]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a new table.
2. Create a long text column, call it "Notes"
3. Add data for two records: Title "A" and Title "B"
4. Expand the "A" record.
5. Enter data in "Notes" field
6. Click the "Next Row" button in the upper right
7. Click the "Previous Row" button
8. Data is gone :(

### Desired Behavior

Please make step 8. be instead "Data is there!" -- i.e. autosave the record when I press next row.

### Project Details

Node: **v19.2.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.104.3**

### Attachments

https://user-images.githubusercontent.com/13812/217116594-6bff8e63-6ed4-410a-8fad-47602c350e42.mov

**Comment by frankMagoba** [comment]
Hi @o1lab, is it okay if I work on this issue?
