### ISSUE TITLE
🐛 Bug: filter table display the wrong results until reload whole webpage

### ISSUE THREAD

**Issue by chxp** [nocodb/nocodb#5053]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

#### The data is:
![Screenshot_20230207_225035](https://user-images.githubusercontent.com/14882692/217279602-920daa52-70b0-4e68-837c-50c5146b11b4.png)

#### Accending sort the column 1 as the follow or another filter method:
![Screenshot_20230207_225301](https://user-images.githubusercontent.com/14882692/217279847-57e33d77-0b20-4d4a-9f5f-1ce0b09db30b.png)

#### The table will display as:
![Screenshot_20230207_225057](https://user-images.githubusercontent.com/14882692/217280084-f6929156-03f9-4a14-baf0-754342f989c3.png)

#### The following button did not work:
![Screenshot_20230207_225751](https://user-images.githubusercontent.com/14882692/217280432-3119443d-deb9-4b73-939b-b3bb0e2b1a5a.png)

#### Until you refresh/reload the webpage, it works now:
![Screenshot_20230207_225127](https://user-images.githubusercontent.com/14882692/217280575-6ce36126-d5c4-486b-838d-5631f9f0c401.png)

### Desired Behavior

display the right results without reloading the webpage again.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.104.3**

**Comment by dstala** [comment]
@chxp thanks for the details! this issue is fixed and will be available in next release
https://github.com/nocodb/nocodb/pull/5012
