### ISSUE TITLE
🔦 Feature: Manual reorganisation of project list

### ISSUE THREAD

**Issue by s-arjune** [nocodb/nocodb#5055]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

On the initial dashboard displaying "My projects" it would be helpful to organise existing projects. If a user has many different projects with various collaborators the initial dashboards gets overwhelming. Currently projects appear in the order of their date of creation and their order cannot be changed once they are created.

### Suggested Solution

On the initial dashboard displaying "My projects" it would be helpful to organise the projects either by filtering (e.g. if projects are names 01_project or by date) or having a folder structure.

**Comment by frankMagoba** [comment]
Hi @o1lab, is it okay if I work on this issue?

**Comment by o1lab** [comment]
Sorry, we arent going to support this immediately.

**Comment by u23a** [comment]
Any progress on this?
I have many projects, but the current UI order is hard for me to find the project I want.
"manual ordering" is a common feature in every application and it's very usefule.

**Comment by o1lab** [comment]
Can you help understand how many?

**Comment by dstala** [comment]
NocoDB supports starred projects & re-order as well. Reopen this ticket if additional assistance is required
