### ISSUE TITLE
🐛 Bug: incorrect values in grid view

### ISSUE THREAD

**Issue by andris1** [nocodb/nocodb#5059]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- start a new table, 
- keep col 1 as single line text and fill in at least 50 rows with any text,
- add col 2 as single line text and fill out only row 25 for it,
- refresh the page so you get 25 items per page,
- navigate to page 2,
- see that line 50 for col 2 has values of line 25

### Desired Behavior

Correct values would be preferred. :)

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.104.3**

**Comment by dstala** [comment]
@andris1 thanks for the details! this issue is fixed and will be available in next release
https://github.com/nocodb/nocodb/pull/5012
