### ISSUE TITLE
🔦 Feature: Share one row in Form view to update 

### ISSUE THREAD

**Issue by Sadefish** [nocodb/nocodb#5069]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Sharing one row in a form view, makes ohter user especially from a mobile device can easily update data. It works like a interactive APP.

### Suggested Solution

Develop a build-in feature using the patch API.

**Comment by dstala** [comment]
@Sadefish tried forms in survey mode?
https://github.com/nocodb/nocodb/releases/tag/0.98.1

**Comment by Sadefish** [comment]
@dstala it's not just the way form view presents, but I want the shared form linked to one specific row with values already filled, submit the form could updates the table. 
![image](https://user-images.githubusercontent.com/104753097/218126511-1c603971-29c6-4633-82fb-bb2e2d21ed88.png)
Take this for example, share one row with related information already filled, while an accessory remains to be uploaded. In this way we can conduct a data collect.

**Comment by egutierrez-ar** [comment]
Greetings,

I would also like to see something like this implemented.

Something where you can append the `rowId` parameter on the form to get the UI for the form results

`dashboard/#/nc/form/<form-id>?rowId=<>`

To avoid contamination of responses from users navigating across serial ID's I would recommend the database to be using a `UUID` field as a primary key

**Comment by dstala** [comment]
Record URL is supported over Grid for signed users. 
https://docs.nocodb.com/records/expand-record#copy-record-url

That suffice?

**Comment by Sadefish** [comment]
Thx, I'll close the issue.
