### ISSUE TITLE
🐛 Bug: UTC datetime in database

### ISSUE THREAD

**Issue by coutouly** [nocodb/nocodb#5072]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

insert an UTC datetime in nocodb datetime field
refresh and it become an timezone datetime 

### Desired Behavior

possibility to choose timezone to display datetime

### Project Details

Nocodb docker

**Comment by dstala** [comment]
@coutouly we have enhanced our support for date time field. date time will be browser based & will persist that way even on refresh. It will be stored in database timezone in the backend (often UTC)

please reopen this thread if you still face any issues.
