### ISSUE TITLE
🐛 Bug: Cells show incorrect values in UI; cells do not refresh properly.

### ISSUE THREAD

**Issue by HappyFr1day** [nocodb/nocodb#5098]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

This issue seems to occur when using the pagination feature, cells do not refresh properly when the to-be-rendered cell contains an empty value.

1. Create an empty table
2. Add a Long Text column to that table
3. Add 50 rows to that table
4. Enter some text into the long text in the field on Row 7
5. Switch to page 2 using the pagination feature at the bottom of the screen
6. Note that the long text from Page 1 Row 7 is still visible on Page 2's Row 7.
![image](https://user-images.githubusercontent.com/123981629/218888766-aad521fd-706f-4a94-a349-0005ada20807.png)
![image](https://user-images.githubusercontent.com/123981629/218888878-9dd2db49-f40e-4e9a-8be6-78c16921d3b1.png)
![image](https://user-images.githubusercontent.com/123981629/218889097-eae0e43c-cfcf-4415-bf17-5ad619e96a93.png)
7. Observe using psql (or the API) that only the original edited row contains the expected cell text contents; however, the UI will show the text contents for other rows.

### Desired Behavior

Cells should show correct (empty) value.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.104.3**

**Comment by whyteserious** [comment]
me too
add  column type  SinglelineText  or LongText
enter something 
same row of the empty data(UI) in the next or last few pages will display the data that according to the latest selected  page

**Comment by dstala** [comment]
is fixed & will be available in next release
https://github.com/nocodb/nocodb/pull/5012
