### ISSUE TITLE
🐛 Bug: Losing Super Admin role after upgrading from 0.101.2 to 0.104.3

### ISSUE THREAD

**Issue by CrisLi** [nocodb/nocodb#5101]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Upgrade from 0.101.2 to 0.104.3, the App Store is gone in the setting menu. The `super admin` role is gone in the new version as well.

0.101.2 version:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/360767/218916715-b7008054-c06c-4cd5-9cbf-3dfca3743197.png">

<img width="379" alt="image" src="https://user-images.githubusercontent.com/360767/218916977-34c894a2-175d-472a-bbbe-1281a40d2d8d.png">

0.104.3 version:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/360767/218916843-07db0943-8385-4ae0-9146-d639d3cc1e6f.png">

<img width="242" alt="image" src="https://user-images.githubusercontent.com/360767/218917038-f7aa3930-fb13-4b73-8a63-89bddcf1407d.png">

### Desired Behavior

We should able to manage the app store and plungin

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.104.3**

**Comment by wingkwong** [comment]
It has been moved to Account Settings.

https://docs.nocodb.com/setup-and-usages/account-settings#app-store

For super admin, you can reset by specifying `NC_ADMIN_EMAIL` and `NC_ADMIN_PASSWORD` during startup.

**Comment by dstala** [comment]
@CrisLi You query addressed or you need more help?

**Comment by CrisLi** [comment]
i have found that solution with @wingkwong's help , thank you both
