### ISSUE TITLE
🐛 Bug: Wrong baseId is used in QuickImport, when a secondary database is only active. So the Table is created in the hidden DB.

### ISSUE THREAD

**Issue by semmjon** [nocodb/nocodb#5103]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Setup secondary catabase connection
![image](https://user-images.githubusercontent.com/42977205/218985622-98fc3fc8-d57f-4430-9616-014c59108592.png)

2. Deactivate base connection
![image](https://user-images.githubusercontent.com/42977205/218985808-fac9c778-64b3-47ca-a109-3953e3989145.png)

3. Import a Table from csv, excel, json with the Drag / Load Dialog
![image](https://user-images.githubusercontent.com/42977205/218985866-5c945f27-5153-429b-9427-b1d07f5aa7f6.png)
![image](https://user-images.githubusercontent.com/42977205/218985927-db5dd272-1252-42e1-9367-6f86e087ed8d.png)

### Desired Behavior

The Table will be created in the enabled Database not the hidden once.

### Project Details

```
Docker used: false
NocoDB Version: develop
NC_DB: NC_DB="mysql2://<ip>:3306?u=<user>&p=<password>&d=nocodb"
```

### Attachments

Possible Fix:

1. 
   File: https://github.com/nocodb/nocodb/blob/develop/packages/nc-gui/composables/useProject.ts
   Change:
   ![image](https://user-images.githubusercontent.com/42977205/218988734-771d6b74-4533-4373-a52a-bef198e259fe.png)
2. File: https://github.com/nocodb/nocodb/blob/develop/packages/nc-gui/pages/[projectType]/[projectId]/index/index/index.vue
    Change:
    ![image](https://user-images.githubusercontent.com/42977205/218989535-22ddda09-38c7-4975-b941-53af8f4e9cb6.png)

> :info: **Hurray!**: For me it will fix also this issue (that was still an issue): https://github.com/nocodb/nocodb/pull/4633

**Comment by dstala** [comment]
@semmjon can you create a PR?

**Comment by semmjon** [comment]
I'm partly working on other features or still have custom adjustments. I'll adjust my fork repository again and create a branch to do PR's so I don't accidentally merge anything wrong.
