### ISSUE TITLE
🐛 Bug: Data display issue when sorting lines with empty fields

### ISSUE THREAD

**Issue by User4572** [nocodb/nocodb#5104]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When I use the sort option on a data base containing some empty cells for SingleLineText rows, it creates data on it (based on other cells). It also happens on multiple cells on the same line if the lines contain multiples empty cells (because of multiple SingleLineText rows).

Step 1:
![image](https://user-images.githubusercontent.com/125454950/219003605-498c200b-a83e-4e13-b419-5cca8ef4f451.png)

Step 2:
![image](https://user-images.githubusercontent.com/125454950/219003948-9757829d-6fd1-4ec9-9436-78eedafc1bbb.png)

Step 3:
Here is the problem.
![image](https://user-images.githubusercontent.com/125454950/219004076-17aba7df-e7df-4752-8457-3a367af2b845.png)

Step 4:
When I refresh the webpage, the sorting is done and the empty cells are back to their true empty state (the newly copied data are gone).
![image](https://user-images.githubusercontent.com/125454950/219004417-692892eb-57fc-4818-a4ab-365931240088.png)

### Desired Behavior

 The empty cells must stay empty without having to refresh the page.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.104.3**

**Comment by ainihonglang** [comment]
I have the same problem !

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/5012 should fix this. please try with release https://github.com/nocodb/nocodb/releases/tag/0.105.0

**Comment by User4572** [comment]
> #5012 should fix this. please try with release https://github.com/nocodb/nocodb/releases/tag/0.105.0

Perfect !
Thank you for your responsiveness.
