### ISSUE TITLE
🔦 Feature: Prefilled forms

### ISSUE THREAD

**Issue by airhuman** [nocodb/nocodb#5107]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Is there a similar functionality?
https://support.airtable.com/docs/prefilling-a-form

### Suggested Solution

.

**Comment by dstala** [comment]
to be traced under https://github.com/nocodb/nocodb/issues/3027

**Comment by airhuman** [comment]
Уважаемый(ая) Raju Udava Спасибо, что обратились в Службу Поддержки SkillFactory! Номер Вашего обращения 12652 "Re: [nocodb/nocodb] 🔦 Feature: Prefilled forms (Issue #5107)" Мы уже работаем над ним и ответим Вам в ближайшее время. С Уважением,Служба Поддержки SkillFactoryI_S_S_U_E_I_D_c4354972-d032-4d13-b254-f01874276453
Closed #5107 as not planned.

**Comment by airhuman** [comment]
Уважаемый(ая) Raju Udava Спасибо, что обратились в Службу Поддержки SkillFactory! Номер Вашего обращения 12654 "Re: [nocodb/nocodb] 🔦 Feature: Prefilled forms (Issue #5107)" Мы уже работаем над ним и ответим Вам в ближайшее время. С Уважением,Служба Поддержки SkillFactoryI_S_S_U_E_I_D_84761f06-4eb6-4abd-8855-3ab4d8c2b28b
to be traced under #3027
