### ISSUE TITLE
[Feature] Order of many to many relations

### ISSUE THREAD

**Issue by paulgirard** [nocodb/nocodb#511]
Use case:
I have a portfolio table linked to a media table by a many to many link record.
The portfolio is an edited set of media.
A media is container arround attachments adding title credits... 
I'd like to be able to change the order of the media linked into one portfolio.

On the data management side it would require to add a order column into the many_to_many table on top of both ids and sort by this order column when displaying.

On the UI side, it would require to add drag/drop feature to the many to many dialog box or cell. And add handler to edit the order property.

**Comment by o1lab** [comment]
Solved in 0.90

**Comment by Untilo** [comment]
Hello Would you please point to the documentation adressing this thru an API call ?
