### ISSUE TITLE
[Feature] Use Lookup column in Formula

### ISSUE THREAD

**Issue by FWMatt** [nocodb/nocodb#512]
NocoDB used as docker : true
NocoDB version : 0.11.29
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Linux

I would like to be able to combine the results of Lookup columns in a Formula. This is important for me as my projects require me to create a normalised schema and return API results of joined tables, i.e.

Appointments (time, date, booked?, belongs_to Clinic)
Clinic (name, district, has_many Appointments)

I then need to create an API query which provides a list of booked appointments showing the clinic information.

**Comment by FWMatt** [comment]
Similar requirement to https://github.com/nocodb/nocodb/issues/514

**Comment by dwzkit** [comment]
In fact, this feature is also very important to me, and it would be great if it could be solved as soon as possible. Currently I have to manually write a set of APIs that can return the result by join multiple tables, and the front-end application has to call nocodb's APIs and my own APIs independently, which is very fragmented.

**Comment by niklas-heer** [comment]
This feature would also be important to me to be able to build a prioritization system.

**Comment by o1lab** [comment]
Available in 0.90 release

**Comment by alexn-s** [comment]
the issue still persists for me:

```
Node: **v16.3.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.91.7**
```

i want to use the lookup field in a formula (colum also named formula).
![image](https://user-images.githubusercontent.com/60710873/173424308-9808ce4d-61b5-49f8-8b3b-d5434ce5ecf3.png)


error msg:

![image](https://user-images.githubusercontent.com/60710873/173424525-3204a169-07bc-4303-9be8-f910038147fb.png)

**Comment by wingkwong** [comment]
@alexn-s Please subscribe https://github.com/nocodb/nocodb/issues/2304

**Comment by devhero** [comment]
I think "Rollup" field could be solve the problem: [https://docs.nocodb.com/setup-and-usages/rollup](https://docs.nocodb.com/setup-and-usages/rollup)
