### ISSUE TITLE
🐛 Bug: sticky column field can be dragged & realigned in sql views

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5122]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

in sql views, display value field can be realigned by drag-drop

### Desired Behavior

similar to table views

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.104.3**

**Comment by 3dprogramin** [comment]
I can confirm from my end too, but version is **0.105.0** on my end.

Node: v16.18.1
Arch: amd64
Platform: linux
Docker: false
RootDB: pg
PackageVersion: 0.105.0

**Comment by mertmit** [comment]
Confirmed, this is because we don't assign display value for sql views, I will try to cover this case with a PR
