### ISSUE TITLE
🐛 Bug: SwaggerUI not working with latest release

### ISSUE THREAD

**Issue by 3dprogramin** [nocodb/nocodb#5125]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

SwaggerUI page isn't working anymore, with the release of version 0.105.0
It does work with previous version 0.104.3

Clone nocodb-seed, make sure it's nocodb latest version 0.105.0.
`npm install`
`npm start`

Log into the dashboard and click `Swagger: Rest APIs` link.
Page returned is blank and doesn't load anything.

Taking a look at the requests, looks like the swagger js and css files are missing and 404 is returned:
- `/css/swagger-ui-bundle.4.5.2.min.css`
- `/js/swagger-ui-bundle.4.5.2.min.js`

Once again, it does work just fine with the previous version.

### Desired Behavior

check attachments

### Project Details

NocoDB used as docker: false
NocoDB version: 0.105.0
Databased used: sqlite3
Project was created by: new project, but with previous version
Database on which spreadsheet is created: pg
OS: linux
Node.js version: tested both v16.19.0 and v16.18.1
Database version: postgres:latest docker

### Attachments

![404-swagger](https://user-images.githubusercontent.com/36532753/219476284-b404e8c6-c651-49cf-8e6f-406a8fb42c42.png)
![click_swagger](https://user-images.githubusercontent.com/36532753/219476287-f0d25082-f751-44b6-8fda-eaa96a7420d5.png)
![working_previous_version](https://user-images.githubusercontent.com/36532753/219476288-bf863893-294e-463d-a7f6-b6e492250084.png)

**Comment by shrsv** [comment]
I am facing this exact issue in the latest docker v`0.107.1`. Tried v`0.107.0` - the issue seems to persist.

**Comment by Shahin-rmz** [comment]
Hello, same here

**Comment by Nciso** [comment]
same, :)

**Comment by joncutrer** [comment]
I am seeing this error when running noco docker, checked out tag version 0.107.1

**Comment by wingkwong** [comment]
@Shahin-rmz @Nciso @joncutrer Can you guys try on the following version?

```
docker run -d -p 9999:8080 nocodb/nocodb-timely:0.107.1-pr-5693-20230522-0338
```

**Comment by Shahin-rmz** [comment]
> are you guys using Docker or Docker Compose?


I am using docker, postgres version.

**Comment by lhr0909** [comment]
> @Shahin-rmz @Nciso @joncutrer Can you guys try on the following version? Also are you guys using Docker or Docker Compose?
> 
> ```
> docker run -d -p 9999:8080 nocodb/nocodb-timely:0.107.1-pr-5693-20230522-0338
> ```

Hi, I am testing with `FROM nocodb/nocodb-timely:0.107.1-pr-5693-20230522-0338` and still getting the blank Swagger API page. Error in the console matches the issue description.
