### ISSUE TITLE
🐛 Bug: 

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#5135]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Swagger page not working after update to 0.105.0

### Desired Behavior

It should open

### Project Details

Docker, postgres, 0.105.0

### Attachments

![image](https://user-images.githubusercontent.com/117290601/219601441-e7d8c2af-0fe7-4302-ba76-78d0991ca737.png)

**Comment by o1lab** [comment]
#5125 : duplicate. Fixing coming soon.
