### ISSUE TITLE
🐛 Bug: Slow Performance

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#5136]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Hi,

NocoDB is running really slow since 0.101.0

See attached picture

### Desired Behavior

The initial load of 25 rows should be really fast

as soon as i delete fields with many to many relation, it speeds up.

### Project Details

Docker, postgres, 0.105.0

### Attachments

1. With Relation many to many field:
![image](https://user-images.githubusercontent.com/117290601/219607263-eaa33cf4-a1eb-43b1-b576-3977f276ce3d.png)

2. Without relation field
![image](https://user-images.githubusercontent.com/117290601/219609744-dde4f412-e753-4ce2-b93e-d750be0b2f2b.png)

**Comment by o1lab** [comment]
How many rows are there in these related tables ? And have you applied any filters and sorts ? 

Plus upgrade to latest - there are some improvements. However, a lot would depend on the answer to the above questions

**Comment by emre1e** [comment]
I am on 0.105.0

86 rows with 29 columns

**Comment by o1lab** [comment]
what about the other tables related - how many rows ? And have you applied any filters and sorts ?

**Comment by emre1e** [comment]
no filters, no sorts.

1 Table 29 Rows and 16 Columns
1 Table 86 Rows and 29 Columns

**Comment by o1lab** [comment]
If the base is not confidential, can you invite into your base and send the invite url to n at nocodb.com

**Comment by emre1e** [comment]
cant sent srry. There are confidential datas inside

**Comment by syji35** [comment]
I also noticed some slowness in the browser since I upgraded from 0.100.2 to 0.104.2. When importing 3 tables with PostgreSQL, each with 20 columns (all containing only strings) and a one-to-many reference, the browser is significantly slower in version 0.104.2.

**Comment by syji35** [comment]
@o1lab 
Hello,
Since I regularly update NocoDB from version 0.100.2, I have noticed a degradation in performance on Chrome browser: frozen pages, data not displaying, etc. Is there an underlying issue that needs to be addressed to improve the interface's performance?

**Comment by o1lab** [comment]
What version are you on ?

**Comment by syji35** [comment]
I am on version 0.104.2. I have stopped upgrading because I am afraid of the performance impact.

**Comment by o1lab** [comment]
We 've made improvements since then. Please upgrade and see how it goes.

**Comment by Falstafff** [comment]
We are using mysql v8.0.32 during local development and aws rds mysql v8.0.32 on stage environment. 

As I said, we see performance issue on client side during UI rendering phase.

**Comment by o1lab** [comment]
I think we've a hint on this and you should the fix in the upcoming release today.

**Comment by o1lab** [comment]
hey, we have postponed this to tomorrow morning - pls stay tuned.

**Comment by Saurabh-Shrivastava-Narvar** [comment]
@o1lab I work with @gitram - the above build renders the header and placeholder table structure fast, but displaying actual data still takes a long time ( ~1 minute). We use external postgres database and are sure that db is not the problem because nocodb API calls via curl statements return results instantaneously.

**Comment by o1lab** [comment]
Hey Saurabh, nice to meet you.

Here is a new build out from our latest changes : pls do try & would love to learn if this will improved

`docker run -d -p 8888:8080 nocodb/nocodb-timely:0.105.3-pr-5392-20230330-1816`

The PR is [here](https://github.com/nocodb/nocodb/pull/5392/files/e3556315ca2b7f3cbd38cd24a7b698112f7d8ff3..88349195aadde36f253ab9be5f468f4aeb37a640).

Do ping me in discord - Im happy to learn more on the problem over a call if possible.

**Comment by Saurabh-Shrivastava-Narvar** [comment]
@o1lab new build didn't help, we still face the same issue. I am not able to log into discord for nocodb. Whenever I go to: https://discord.com/invite/5RgZmkW I always get the error: "Unable to accept the invite".

**Comment by o1lab** [comment]
Try this : https://discord.gg/gsfZWmt9

**Comment by o1lab** [comment]
Yes, makes sense @vadim-oss. We will take up this as part of next release.

cc : @mertmit

**Comment by pranavxc** [comment]
Hi @Saurabh-Shrivastava-Narvar, We took another build after fixing some UI issues please try it out when you guys have time. Thanks.

---

⚠️ ⚠️ ⚠️ : Do NOT use the below build without reading the instructions in this comment 

This build below has a partial fix for the UI performance and use it if ONLY if you can run this independently as a new docker container
- Without providing your current environment variables. (we do not want to upgrade your internal metadatabase yet)
- And only if you are connecting to an external database - you can try the build-out.

If you feel its not clear or more clarifications are required - don't run the build :)

`docker pull nocodb/nocodb-timely::0.106.0-beta.0-pr-5392-20230331-1925`


ref: https://github.com/nocodb/nocodb/commit/1f4465b1de641dff856f4936345c198cefd83992#commitcomment-107013868

**Comment by vadim-oss** [comment]
@pranavxc Confirm this build is awesome  nocodb/nocodb-timely::0.106.0-beta.0-pr-5392-20230331-1925 ! 
It fixes the performance issue with > 200 columns

**Comment by pranavxc** [comment]
> Hi @Saurabh-Shrivastava-Narvar, We took another build after fixing some UI issues please try it out when you guys have time. Thanks.
> 
> ⚠️ ⚠️ ⚠️ : Do NOT use the below build without reading the instructions in this comment
> 
> This build below has a partial fix for the UI performance and use it if ONLY if you can run this independently as a new docker container
> 
> * Without providing your current environment variables. (we do not want to upgrade your internal metadatabase yet)
> * And only if you are connecting to an external database - you can try the build-out.
> 
> If you feel its not clear or more clarifications are required - don't run the build :)
> 
> ```shell
> docker pull nocodb/nocodb-timely::0.106.0-beta.0-pr-5392-20230331-1925
> ```
> 
> ref: [1f4465b#commitcomment-107013868](https://github.com/nocodb/nocodb/commit/1f4465b1de641dff856f4936345c198cefd83992#commitcomment-107013868)
> 
> **UPDATE:** Added a few more optimization in the following docker image
> 
> * Route navigation delay optimization
> * Lazy loading cell which is out of the viewport
> 
> ```shell
> docker pull nocodb/nocodb-timely:0.106.0-beta.0-pr-5392-20230403-1619
> ```
> 
> ref: [f23f454#commitcomment-107354751](https://github.com/nocodb/nocodb/commit/f23f4543413e552c3dcbd2edaaae42e196bd7deb#commitcomment-107354751)
> 
> cc: @gitram

@gitram, @Saurabh-Shrivastava-Narvar - Please try out the latest build, It will be helpful if you guys can confirm.

**Comment by Saurabh-Shrivastava-Narvar** [comment]
@pranavxc @o1lab Wow, now it is superfast, it fixes our performance issue. Thank you for resolving this.

**Comment by emre1e** [comment]
@o1lab i will test it as soon it will not in beta phase :)

**Comment by o1lab** [comment]
Fix to this is now available in latest release [0.106-beta.1](https://github.com/nocodb/nocodb/releases/tag/0.106.0-beta.1)

**Comment by emre1e** [comment]
if i recreate the docker with the latest tag. I still get 0.105.3. Do you know why?

**Comment by pranavxc** [comment]
@emre1e: Since it's a beta release we are not tagging docker with `latest`. So if you want to try it out replace `latest` with the exact version. I hope it helps.

**Comment by emre1e** [comment]
its much faster now. Thank you.

**Comment by wingkwong** [comment]
We're releasing 0.106.0 now. Stay tuned.

**Comment by wingkwong** [comment]
Closing this issue as `0.106.0` has been released.
