### ISSUE TITLE
Migration failed :  0100002 to 0104004

### ISSUE THREAD

**Issue by benintende** [nocodb/nocodb#5147]
Hi everyone,

after updating nocodb today I get the following error message in Terminal, and I can't open nocodb anymore:

(node:1732) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `nocodb --trace-warnings ...` to show where the warning was created)
┌ Migration from 0100002 to 0104004 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      ││   Error: connect EHOSTDOWN 192.168.1.68:3306 - Local (192.168.1.7:50512)     ││   at internalConnect (node:net:953:16)                                       ││   at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)           ││   at node:net:1044:9                                                         ││   at processTicksAndRejections (node:internal/process/task_queues:78:11)     ││                                                                              ││                                                                              ││   Please raise an issue in our github by using following link :              ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   ││   e=bug_report.md                                                            ││                                                                              ││   Or contact us in our Discord community by following link :                 ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
Error: connect EHOSTDOWN 192.168.1.68:3306 - Local (192.168.1.7:50512)
    at internalConnect (node:net:953:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1044:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -64,
  code: 'EHOSTDOWN',
  syscall: 'connect',
  address: '192.168.1.68',
  port: 3306,
  fatal: true
}

Any ideas/suggestions?

**Comment by o1lab** [comment]
This has nothing to do with M1.

Which build were you trying - looks like schema migrations have failed. Provide more details on environment variables

**Comment by benintende** [comment]
Hello, thanks for your quick answer! Not sure which build it was, I updated to the latest version available today via curl http://get.nocodb.com/macos-x64 -o nocodb -L && chmod +x nocodb && ./nocodb

**Comment by benintende** [comment]
I assume it's version 0.105.2

**Comment by o1lab** [comment]
Take a back up and run again :
`cp noco.db noco_backup.db`
./nocodb

**Comment by benintende** [comment]
Ok, I will try that. Nope, haven't touched any files regarding nocodb or the database at any point – I also haven't updated anything else

**Comment by benintende** [comment]
Ok, I have sent the backup file. 👋

**Comment by benintende** [comment]
Ok thank you! 👋

**Comment by wingkwong** [comment]
@benintende There is a data source (192.168.1.68:3306) that is inaccessible. In this case, you need to fix the connection issue first and then retry the upgrade. Alternatively, you can remove that data source from your project using the old version and retry.

**Comment by benintende** [comment]
Ok thanks. What would be the easiest way to revert to an old version?

**Comment by wingkwong** [comment]
You can download the executable with specific version via `https://github.com/nocodb/nocodb/releases/download/<YOUR_PREVIOUS_VERSION>/Noco-macos-x64`. 

Change `<YOUR_PREVIOUS_VERSION>` above.

**Comment by benintende** [comment]
Hi @wingkwong, just to confirm that reverting to my previous version, then deleting the inaccessible connection and then updating again worked, thanks for the help 👋
