### ISSUE TITLE
migrate `@aws-sdk` to v3

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#5150]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Reasons:
-  The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
- AWS SDK for JavaScript version 3 (v3) comes with modularized packages so as to reduce the bundle size.

See https://github.com/aws/aws-sdk-js-v3 for more.

### Suggested Solution

- migrate the v2 code under `nocodb/packages/nocodb/src/lib/plugins` to v3

**Comment by frankMagoba** [comment]
Hi @wingkwong is this still up to be picked?

**Comment by wingkwong** [comment]
@frankMagoba I think not - DarkPhonexi2704 is working partially.

**Comment by trivikr** [comment]
AWS SDK for JavaScript v2 will enter maintenance mode on September 8, 2024 and reach end-of-support on September 8, 2025. For more information, check blog post at https://a.co/cUPnyil

**Comment by trivikr** [comment]
I quickly looked at AWS SDK for JavaScript v3 imports in nocodb:
* The `@aws-sdk/client-kafka`
  * added in https://github.com/nocodb/nocodb/pull/6222
  * doesn't seem to be used.
* The `@aws-sdk/client-s3` and `@aws-sdk/s3-request-presigner`
  * added in https://github.com/nocodb/nocodb/commit/68fb42714fb6febb5caa282b821ed1b25284b885
  * used in https://github.com/nocodb/nocodb/commit/4f54084f8c2dc534e6e7b04b9bb2a2fd3271e3c8
* The `@aws-sdk/lib-storage`
  * added in https://github.com/nocodb/nocodb/commit/2e4486cd73b180dc396ac992de8930e32c1a0191
  * used in https://github.com/nocodb/nocodb/commit/cfcdb895b0dbdb4e465b2d69a1b2aef4ca6ba325

**Comment by DarkPhoenix2704** [comment]
Migrated to aws-sdkv3 in https://github.com/nocodb/nocodb/pull/9104
