### ISSUE TITLE
[Feature] JSON helper for Handlebars

### ISSUE THREAD

**Issue by er1z** [nocodb/nocodb#516]
I want to pass all the record data via webhook; is it possible to add `toJSON` helper for Handlebars or something like that?

**Comment by o1lab** [comment]
Could you expand the usecase ? all data via webhook - insert webhook ?

**Comment by er1z** [comment]
For example, I set up a webhook on insert to the table. I want to send all the record via payload, without the need to specify particular fields I want to send.

Currently, if I specify `{{ data }}` as a payload, I get a `[object Object]` in request. What I need is to provide either pre-serialized values or `toJSON` filter that could simply serialize supplied variable.

**Comment by pranavxc** [comment]
@er1z It's possible to add helper as in this answer - https://stackoverflow.com/a/10233247 . Will add this feature soon

**Comment by er1z** [comment]
I know it's possible with additional filter, but it'll be nice to have it as a stock one, especially if it's a webhook context.

Thank you.

**Comment by pranavxc** [comment]
Added in `0.11.30`
