### ISSUE TITLE
🔦 Feature: using LinkToAnotherRecord for linking a row to a user from the teams & management

### ISSUE THREAD

**Issue by shahidcodes** [nocodb/nocodb#5169]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I want to link each row to a user in the Teams section. 

### Suggested Solution

Show users table when `columnType` is selected as `LinkToAnotherRecord`

**Comment by dstala** [comment]
To be tracked under https://github.com/nocodb/nocodb/issues/3787
