### ISSUE TITLE
[Feature] page transition

### ISSUE THREAD

**Issue by Teeeeeth** [nocodb/nocodb#5177]
Thank you for your assistance.

Due to automatic translation, there may be errors in English grammar.
Please understand.

We have tried NOCODB locally.
I found it to be a very nice product, but
but there were some parts that were difficult to use.

It is the page transition in the table.
It displays only 25 rows per page, which is inconvenient when you want to browse only by scrolling.
Also, the loading time of the page transition was a bit annoying.
I also wish the vertical width could be narrowed a little more.

It would be great if all data could be viewed on one page with only scrolling, like other cloud DB services!
Until then, I will unavoidably pay for Airtable.

Thank you for reading.
Best regards.

Translated with www.DeepL.com/Translator (free version)

**Comment by o1lab** [comment]
Since we connect to real databases - some of our users have upwards of million rows. Hence the pagination. However will think about it.

**Comment by dstala** [comment]
Thanks for the details @Teeeeeth 
This issue will be tracked further under https://github.com/nocodb/nocodb/issues/3568
