### ISSUE TITLE
🐛 Bug: SingleSelect focus is a bit broken in Firefox

### ISSUE THREAD

**Issue by djmaze** [nocodb/nocodb#5179]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

In a Firefox browser:

1. Create a table with a `SingleSelect` field and some options
2. Add a new row 
3. Click inside the field in order to show the dropdown handle
4. Realize that the dropdown handle only shows if you click very far at the left or the right corner of the field

### Desired Behavior

It should be possible to show the dropdown handle by clicking _anywhere_ within the field. The current behaviour is unintuitive to say the least. (I got reports from users who thought that the field is completely non-working.)

### Project Details

```
NocoDB used as docker: true
NocoDB version: 0.105.3
Database used in NC_DC URL: pg
Project was created by clicking: New Project
Database on which spreadsheet is created: pg
OS on which NocoDB is running: Docker host is Ubuntu 22.04
Database version: Postgres 15.0
```

**Comment by dstala** [comment]
@djmaze Works fine for me. Can you do a screen recording to explain?
We did change the behavior for many data types. The core principle is, 
- First click on cell should only select cell: `select mode`; select mode, you can use arrow keys to navigate between cells in the grid
- Subsequent click or keystroke (like `Enter` or any datatype associated key): change to `edit mode`

We have also tried to retain the same behavior for `select` cells.

**Comment by djmaze** [comment]
Okay, seems this seems to happen not in Chromium-based browsers, but in **Firefox** only.

**Comment by o1lab** [comment]
Ah thank you for the details. We will look into asap tomorrow.
