### ISSUE TITLE
[Feature] Edit table without logging in.

### ISSUE THREAD

**Issue by almosnow** [nocodb/nocodb#518]
Is there a way to share a table so that anyone with a specific link can edit it? Without having to register/login?

Thanks.

**Comment by almereyda** [comment]
A special case of this will also be useful for #142 when one will want to allow people to add new rows without being logged in.

**Comment by o1lab** [comment]
Without loggin in, adding rows via form is fine. To do so via spreadsheet 've to be thought about a little.

**Comment by almosnow** [comment]
>Adding rows in grid view without auth doesn't make sense for.

How about "I want to share this with 10 people but don't want to create and manage user accounts for all of them" ...

**Comment by pranavxc** [comment]
Shared base with editor role added in `0.83.2`

**Comment by o1lab** [comment]
@almosnow : there you go.
