### ISSUE TITLE
Date Filter doesn't include date operations

### ISSUE THREAD

**Issue by manwithpowers** [nocodb/nocodb#5186]
When filtering a Date or DateTime column, the operators don't include date specific operations, specifically "_is on_", "_is on or after_", etc; or for that matter more general numeric operations like "_greater than_" or "_greater than or equal to_". This makes filtering by date difficult, particularly when one wants to see all dates before or after a specific date.

![Screenshot 2023-02-22 at 11 45 44](https://user-images.githubusercontent.com/5508635/220598605-57a720cd-d175-45fc-a26e-30eb2cd38300.png)

Additionally, it would be helpful to have dynamic values for date filtering (e.g. "_Today_")

nocodb 0.105.3 (macos binary)

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/5185

**Comment by manwithpowers** [comment]
> #5185

Thanks, did not see this when I searched for previous issues.
