### ISSUE TITLE
Too many fields for a table 

### ISSUE THREAD

**Issue by sureifyram** [nocodb/nocodb#519]
Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.11.29**

**Steps To Reproduce**
1. Create sample tables with relations (Please find the attached sample schema.txt) in postgres
2. Create a project in nocodb with the above external sample database.
3. Please refer the screenshot

**Expected behavior**
1. Expected result it to have only one foreign key field for a relation.

**Screenshots**
![image](https://user-images.githubusercontent.com/66383594/132551438-776e4939-0a71-40df-82ee-f35c59629125.png)
[schema.txt](https://github.com/nocodb/nocodb/files/7130573/schema.txt)

**Comment by o1lab** [comment]
Thank you for the detailed report. Was able to reproduce it.

Looks tables 've foreign keys not pointing to primary keys of other tables and some tables do not have primary keys. Either ways, we should be able to handle this.

**Comment by pranavxc** [comment]
Fixed in `0.11.31`
