### ISSUE TITLE
🐛 Bug: Cannot change Single and MultiSelect value from the Child list

### ISSUE THREAD

**Issue by Maelstro** [nocodb/nocodb#5191]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Hi, I tried to edit a SingleSelect field in a entity by the related fields list and I wasn't able to do so - selector is not responding to clicking, I'm only able to deselect the current value. I tried to do the same with MultiSelect and I got the same behavior - not being able to set a new value to the MultiSelect field, only to deselect  the current value.

Steps to reproduce:
1. Create two tables, one with primary key and Single or Multiselect column, and the second with primary key and relation to one of the rows in first table.
2. Go to the second table, select Child List and pick one of the listed fields.
3. Try to select new value in selector.
4. Selector does not respond to clicking.

I also attached a screen recording that shows the issue.

### Desired Behavior

Able to choose a new selector value when object is accessed through Child list.

### Project Details

NocoDB used as Docker: true
NocoDB version: 0.105.3
Database used in NC_DB URL: `mysql`
Database on which spreadsheet is created: `mysql`
OS on which NocoDB is running: Docker, with Debian 11 as host
Database version: MySQL 5.7

### Attachments

[nocodb-cannot-edit-select.webm](https://user-images.githubusercontent.com/33695680/220668341-380d920c-2b40-4a67-a87d-6387e7f825b0.webm)

**Comment by o1lab** [comment]
Thanks for the detailed report with a video. This helps.
