### ISSUE TITLE
🐛 Bug: Activity.ListSharedView double click Table headers

### ISSUE THREAD

**Issue by u9voj** [nocodb/nocodb#5197]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

open a link of Activity.ListSharedView,
double click any cell of table headers,
open a box of edit coloumn name...

### Desired Behavior

the box is a bug

### Project Details

Nocodb: v0.105.3
Database: mysql

### Attachments

![nocodb-sharelink-tableheader](https://user-images.githubusercontent.com/4011192/220854728-76bbbfab-4181-499f-bea4-d5db38ab31b3.png)

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/5206
