### ISSUE TITLE
SMTP authentication is mandatory

### ISSUE THREAD

**Issue by loftwah** [nocodb/nocodb#520]
Hello, I haven't added some details because it isn't really important for the bug/request I'm submitting.

Currently, the app store allows us to add SMTP, I have some use cases where the SMTP server I use is based on whitelisting an IP address rather than user/pass. Can I please ask for a feature request to make the authentication part of SMTP optional? Also, the expected values for the Secure field aren't clear. Would a user  add SSL, TLS, True or False? I can make these changes if you think it is a good idea.

**Steps To Reproduce**
1. Go to 'App store'
2. Click on 'SMTP'
3. See error (not really an error)
![chrome_xTHWW0kv4d](https://user-images.githubusercontent.com/19922556/132617911-515ef58b-3722-49ab-ac8b-d90ed2a80943.png)

BTW NocoDB ROCKS!

**Comment by loftwah** [comment]
![image](https://user-images.githubusercontent.com/19922556/132617961-13f6dcf6-892c-466e-a8d7-7392e08e6c44.png)

This is a better screenshot, it shows the fields are required.

**Comment by o1lab** [comment]
secure : true/false

Could you pls confirm, the settings you are suggesting will work with [nodemailer](https://nodemailer.com/usage/)

**Comment by loftwah** [comment]
Yep, don't include auth at all, it will let you.

```js
"use strict";
const nodemailer = require("nodemailer");

// async..await is not allowed in global scope, must use a wrapper
async function main() {
  // create reusable transporter object using the default SMTP transport
  let transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    secure: false, // true for 465, false for other ports
    // auth: {
    //   user: 
    //   pass: 
    // },
  });

  // send mail with defined transport object
  let info = await transporter.sendMail({
    from: '"Dean Lofts" <dean@deanlofts.xyz>', // sender address
    to: "dean+sucks@deanlofts.xyz", // list of receivers
    subject: "Hello ", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>I'm Ron Burgandy?</b>", // html body
  });

  console.log("Message sent: %s", info.messageId);

main().catch(console.error);
```

**Comment by o1lab** [comment]
Can you pls try building this change locally in [development setup](https://github.com/nocodb/nocodb#development-setup) and see if that is fine with our code. Happy to take a PR.

Need to set following values to false.
https://github.com/nocodb/nocodb/blob/master/packages/nocodb/src/plugins/smtp/index.ts#L46
https://github.com/nocodb/nocodb/blob/master/packages/nocodb/src/plugins/smtp/index.ts#L52

Once setup, you can click on 'Test' before 'Save' (this I think sends a test email to email that is been used for signup) or invite a new user (this should send an invite email)

**Comment by loftwah** [comment]
Sure thing, I can't do it right away. If I haven't gotten to you by Sunday please give me a bump.

**Comment by loftwah** [comment]
https://github.com/nocodb/nocodb/pull/523 I've submitted a pull request. If I've messed anything up let me know, I am a bit of a newb at the actual coding thing tbh, I come from a systems background.

**Comment by pranavxc** [comment]
Resolved in `0.11.30`

**Comment by patelbhavinoutlook** [comment]
i have below settings for office 365... this work in other scripts but not working here.. 

![image](https://user-images.githubusercontent.com/28344691/193763556-ba30b313-31ef-4c52-92f1-edbe4ae41da9.png)

i get below error..

![image](https://user-images.githubusercontent.com/28344691/193763812-ede428a9-5984-42c2-9330-061f5ab4ee64.png)

**Comment by patelbhavinoutlook** [comment]
MTP test error ::  [Error: 139789660212552:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}
p :: Error: SMTP test failed, please check server log for more details.
    at t.default.test (/usr/src/app/docker/main.js:2:987445)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
POST /api/v1/db/meta/plugins/test 400 69 - 32.512 ms
