### ISSUE TITLE
🐛 Bug: LinkToAnotherRecord update via REST API doesnt work

### ISSUE THREAD

**Issue by ljacho** [nocodb/nocodb#5213]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Sending data to column LinkToAnotherRecordvia Resttt API? Tried to send array of whole objects of record in linked table, or just ID and Display value - no effect

### Desired Behavior

Data will be stored and available to retrieve via REST API back.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

**Comment by RawmanGrey** [comment]
It should be a feature request: to have on option to set relations in one call with creating rows or updating other fields.

@ljacho, meanwhile, as of 0.105.3, it is possible, while not mentioned in [docs](https://docs.nocodb.com/developer-resources/rest-apis/), to set relations one by one, in separate POST calls like below:
`<yourBaseURL>`/api/v1/db/data/noco/`<projectName>`/`<tableName>`/`<targetRowId>`/`<relationType: mm or bt>`/`<relationColumnName from tableName>`/`<relatedRowId>`

PS: probably this endpoint is shown in swagger playground, but in latest version it is [broken a bit](https://github.com/nocodb/nocodb/issues/5125).

**Comment by dstala** [comment]
V2 Link records API can consume array of record IDs
https://data-apis-v2.nocodb.com/#tag/Table-Records/operation/db-data-table-row-nested-link

Please reopen this ticket if you need more help on this.
