### ISSUE TITLE
🐛 Bug: the position of "next" and "previous" buttons in forms is confusing for RTL languages

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#5217]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When I create a form in Persian - an RTL language - and the form has multiple questions, the position of 'next' and 'previous' button is confusing (I will attach its screenshot).

### Desired Behavior

I think it would be better if the whole element could be center-aligned. Moreover, the buttons' position should be switched.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.2**

### Attachments

![cap1](https://user-images.githubusercontent.com/100111649/221475849-74e7e9f5-c43b-4379-9175-d1eaf41a8d51.PNG)

**Comment by okaeiz** [comment]
I saw this just right now. The 'previous' and 'next' button in the projects (under the tables) is also confusing.

![Capture](https://user-images.githubusercontent.com/100111649/221511886-eaf20aa7-861a-4fb9-838d-df69ca80cb94.PNG)

**Comment by okaeiz** [comment]
Hi there again! Thanks for helping us out. Is this issue being considered?

**Comment by frankMagoba** [comment]
Can I pick this up?

**Comment by wingkwong** [comment]
@frankMagoba assigned. please free feel to ping the team members in discord if you need any help.

**Comment by okaeiz** [comment]
@frankMagoba thanks for working on this bug. I will be grateful if you keep me informed.

**Comment by dstala** [comment]
works fine in v 0.111.0
