### ISSUE TITLE
🐛 Bug: project setting "Show NULL and EMPTY in Filter" has no effect

### ISSUE THREAD

**Issue by davidpfahler** [nocodb/nocodb#5219]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- go to Team & Setting > Project Settings and check "Show NULL and EMPTY in Filter" checkbox
- reload the page
- result: null and empty are still not available in filters (only blank)

### Desired Behavior

null and empty should be available in filters

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

**Comment by wingkwong** [comment]
May I know which column type you apply the filter on? `null` or `empty` may not be supported for some column types. You can refer the filter matrix [here](https://docs.nocodb.com/setup-and-usages/column-operations#supported-filters).

**Comment by davidpfahler** [comment]
@wingkwong You are right, I tested this on a LinkToAnotherRecord, which is not supported for null and empty.
