### ISSUE TITLE
NoCobd Error - TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by dwelsh-clouru** [nocodb/nocodb#522]
**Please enter the following details**

Hi there I am getting an error when trying to log into a nocodb instance and connect to a project - please see error via youtube video below. 

https://youtu.be/xs-FRbNUt2Q

**Further details:**

NocoDB used as docker : True
NocoDB version : pg - latest version
Project was created  by clicking: New Project by connecting to external database
Database on which spreadsheet is created : pg 
OS on which NocoDB is running : Mac
Database version : 13

**Expected behavior**
Log in and connect to a project.

**Comment by o1lab** [comment]
What is the error ? more details & screenshot will help

**Comment by dwelsh-clouru** [comment]
Sure please see attached - are you able to see the youtube video?

https://user-images.githubusercontent.com/75716290/132659091-cf8f6e73-5b77-4ed6-aa32-b156fe8f3cc9.mov

**Comment by o1lab** [comment]
Ah, sorry missed the video. 

Are you running this on herkou/cloud/locally ?

It is saying Token expired - would you like to recreate the project once ? just to be sure.

Docker logs & browser console error will help understanding.

**Comment by dwelsh-clouru** [comment]
there was a project that was recreated. I will try and get the browser console error.

**Comment by o1lab** [comment]
Pls ping me on discord : https://discord.gg/5RgZmkW - happy to help

**Comment by pranavxc** [comment]
Is it the super admin or invited user?

**Comment by o1lab** [comment]
@pranavxc : Their setup was in GCP (cloud-run + cloud-sql). This issue had to relate with connection pool becoming full.

**Comment by wingkwong** [comment]
Closing stale issue
