### ISSUE TITLE
🐛 Bug: Swagger schema not matching API call result

### ISSUE THREAD

**Issue by marcomow** [nocodb/nocodb#5224]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

In the swagger definitions (checked through the interface) some schemas aren't matching the actual result.

In my specific case, some properties of a row are declared in the schema as values, but returned as an array of such values. It looks like the mismatch affects properties that are linked from another table. 

for insance
schema
```typescript
"linkedProperty":{
  "id":string,
  "value":string
}
```
api call
```json
"linkedProperty":[{
  "id":"123",
  "value":"234"
}]
```

### Desired Behavior

the schema should match the returned values in the api call

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

**Comment by wingkwong** [comment]
Can you share which api call is that?

**Comment by marcomow** [comment]
A simple `list` call to list all the rows of a table; in the swagger generated docs, the very first one after the header with the table's name

**Comment by wingkwong** [comment]
Mind to provide a screenshot? I still don't get what you mean. For `swagger generated docs`, do you mean Swagger UI or API Doc?

**Comment by marcomow** [comment]
Here a dummy base where I was able to reproduce the issue https://seedlist.up.railway.app/dashboard/#/nc/p_nktkn1sx1ammhn/table/md_2i9m33x6ixt44s

here the schema
![image](https://user-images.githubusercontent.com/4977000/222123402-902ff42e-8f0f-452f-89ee-0ab34c9fbacc.png)

and the actual API call result
![image](https://user-images.githubusercontent.com/4977000/222123496-5324413e-bd0f-43c0-9552-922b5e596155.png)

notice how the linked properties `color` and `name` are declared as an object in the schema, but returned as an array of such objects in the API call result

**Comment by wingkwong** [comment]
Thanks a lot. It's clear now. Will take a look.

**Comment by wo0lien** [comment]
Hi, still getting the same issue on 

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.111.4**

Should I open a new issue for that ?
