### ISSUE TITLE
🔦 Feature: Updating table values in bulk

### ISSUE THREAD

**Issue by max-santiago** [nocodb/nocodb#5228]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I want to be able to update rows in bulk with a CSV/Excel file.

### Suggested Solution

For example:
1. Let's say I have an existing table `my_table` with columns `id` (primary key), `col_1`, `col_2`, `col_3` in NocoDB.
2. I upload a csv containing the columns `id`, `col_2`, `col_3`.
3. NocoDB will update _only_ the values of `col_2` and `col_3` for the rows that match the `id` column in the uploaded CSV file. This as opposed to trying (and failing) to insert those rows.

**Comment by dstala** [comment]
Feature request similar to https://github.com/nocodb/nocodb/issues/3899

**Comment by dstala** [comment]
to be tracked under 
https://github.com/nocodb/nocodb/issues/3899
