### ISSUE TITLE
🐛 Bug: CSV import Id fields doesn't effect table Id counter

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#5243]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1) Create new table
2) Import CSV like below:
```
Title,Id
A,3
B,4
C,5
```
3) Map Title and Id to corresponding fields
4) Create few new rows from interface and get errors on violating constraints.  

### Desired Behavior

On successful import to table (if any Id's were set), its Id counter should be compared to highest Id value. If counter is smaller, set it to maximum imported Id value plus one.

Why it is important?
If imported data is intended to have relations with existing data or further imports, setting Id directly is very handy : )

If changing counter logic is not possible, importing Id's should be forbidden, cause it leads to bugs.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

**Comment by wingkwong** [comment]
If `Id` is set as auto increment, then you don't need to map `Id`. The `id` would be always max + 1. Would it be more simple?

**Comment by RawmanGrey** [comment]
> If `Id` is set as auto increment, then you don't need to map `Id`. The `id` would be always max + 1. Would it be more simple?

Thanks for your response, @wingkwong! 

Simpler = better : ) But will it noticeably affect performance on massive creating rows, e.g. with import?

**Comment by dstala** [comment]
@RawmanGrey From next release,
- User will not be able to map to nocoDB's ID field during CSV import to create a new table. 
- ID field if present in CSV being imported will have to mapped as a generic field

This would sort out issues noticed often with CSV import with duplicate record information.

Support for mapping to ID field will continue to exist in case of upload CSV to existing table case.
