### ISSUE TITLE
🐛 Bug: Advanced column options are not displayed

### ISSUE THREAD

**Issue by SchmaR** [nocodb/nocodb#5245]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a new table
2. Edit the auto generated title column
4. Click "show more" to access advanced column options as described in https://docs.nocodb.com/setup-and-usages/table-operations#column-add

### Desired Behavior

The advanced column options (Not Null, Primary Key, Foreign Key, Unique etc.) should be displayed as shown in the documentation. 

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.105.3**

This was tested running NocoDB on GCP Cloud Run.

### Attachments

<img width="798" alt="image" src="https://user-images.githubusercontent.com/1245103/222725638-d360e416-8e8e-4180-8f8c-768bd2e5c334.png">

**Comment by chxp** [comment]
Seem the same issue: https://github.com/nocodb/nocodb/issues/4850

Node: *v16.17.1*
Arch: *x64*
Platform: *linux*
Docker: *true*
RootDB: *mysql2*
PackageVersion: *0.104.3*

Version <= 0.104.2 will be okay, however, version >= 0.104.3 will lose these advanced options. I checked the latest version, it still has the problem.

**Comment by dstala** [comment]
Prior to v0.104.3, Advanced menu by default displayed developer specific database configuration options. To avoid unintended tweaks from user, these are now hidden under an easter egg menu. To enable, double click on `show more`/`hide all` button in column edit modal.

![Screenshot 2023-03-06 at 10 45 26 AM](https://user-images.githubusercontent.com/86527202/223024810-85dac1c6-87ef-4193-90cb-3a05be8ccc1d.png)
