### ISSUE TITLE
Foreign Key does not display in primary table when reference column is changed

### ISSUE THREAD

**Issue by perrinromney** [nocodb/nocodb#525]
**Please enter the following details**

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.11.29**

**Steps To Reproduce**
1. Create Table A
2. Create Table B
3. 2. Create Item A as a row on Table A
4. 2. Create Item B as a row on Table B
5. On Table A, Create New column of Type "ForeignKey".
6. Make Reference Table Table B.
7. Make Reference Column something other than the ID.
8. On Table A, Link Item A to Item B using the Foreign Key.
9. Open Table B or Refresh.
10. Open Table A or Refresh.
11. Error should present.

**Expected behavior**
Expect Foreign Key to show up in column on Table A and Table B, but ity only shows in Table B.
**Screenshots**
![image](https://user-images.githubusercontent.com/68754259/132877057-6a345171-c3ee-4e9f-a46a-0802753702c8.png)

**Comment by o1lab** [comment]
Tracked in #148

**Comment by sepbin** [comment]
你是怎么能选从键的，为什么我就选不了？
