### ISSUE TITLE
🐛 Bug: improper ERD portrayal 

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#5254]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

As you can see in the screenshot below, sometimes the ER diagram drawn by NocoDB  is messy.

### Desired Behavior

I expect to have a proper ERD with exact relationship portrayals.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.2**

### Attachments

![photo_۲۰۲۳-۰۳-۰۶_۰۹-۵۲-۳۱](https://user-images.githubusercontent.com/100111649/223033542-85d72a47-03a4-4abd-8297-619dee1519b4.jpg)

**Comment by dstala** [comment]
@okaeiz can you confirm if you are still able to reproduce issue after upgrade to v0.111.0?

**Comment by dstala** [comment]
closing this thread for now. reopen if issue persists with latest release
