### ISSUE TITLE
🐛 Bug: incomprehensible errors when validating records

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#5257]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When I have to insert , say, a numeric type of data but I insert  some text instead, the error which pops up is so confusing and long!
It would be great if the validation took place near the field that has improper data and the error were more comprehensible.

### Desired Behavior

Shortening the error and putting it next to the corresponding field is a good idea.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.2**

### Attachments

![image_2023-03-06_11-21-11](https://user-images.githubusercontent.com/100111649/223063082-22f414b4-ca3c-4024-937e-6346ff431011.png)

**Comment by okaeiz** [comment]
Currently, it seems like NocoDB puts the whole query in the error and the end users have to recognize the problems all by themselves.

**Comment by okaeiz** [comment]
Well, how is this issue going?

**Comment by dstala** [comment]
@okaeiz 
we have reduced display of SQL errors in good number of places in v0.202.5; 
if you can find any reproducible scnearios with SQL error dumped, let us know. we will fix it.

**Comment by dstala** [comment]
closing this thread for now. reopen if you can find any error instances

**Comment by okaeiz** [comment]
Hi there! When modifying table records, I keep seeing this error like every five seconds: 
```
cannot read properties of undefined 'column_name'
```
and it's too annoying.

**Comment by dstala** [comment]
@okaeiz could you please help add more details here? if you are using self hosted instance, let us know your base information. if you can share any additional logs available (console or backend), that would help. 

reopening this thread to track further.

**Comment by okaeiz** [comment]
I am using `v0.252.0` deployed via Docker Compose on an Ubuntu server. Here are the container logs:
```bash
[Nest] 8  - 08/12/2024, 4:33:49 AM   ERROR [GlobalExceptionFilter] Cannot read properties of undefined (reading 'column_name')
TypeError: Cannot read properties of undefined (reading 'column_name')
    at BaseModelSqlv2.nestedInsert (/usr/src/app/docker/main.js:2:574881)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatasService.dataInsert (/usr/src/app/docker/main.js:2:1959805)
    at async DataAliasController.dataInsert (/usr/src/app/docker/main.js:2:364399)
```

I connected to an external Postgresql data source which has a table whose fields names are Farsi. When I open the table in NocoDB, I keep getting that error.

**Comment by o1lab** [comment]
Will be tracked [here](https://github.com/nocodb/nocodb/issues/9207). We can close this issue.
