### ISSUE TITLE
🐛 Bug: Mysql Decimal Field length 10 is not enough

### ISSUE THREAD

**Issue by liuwanzhen** [nocodb/nocodb#5259]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1 .Create a column with column type Decimal.
2. input a number 123456789.01
3. can not save the number, it prompt up hint with save the row error.
<img width="978" alt="image" src="https://user-images.githubusercontent.com/1404352/223307398-123a0bd8-0edf-4cbc-a99a-0b8257df640a.png">
 

### Desired Behavior

when decimal field number's length is bigger than 10,then can not save.

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
RootDB: **mysql2**
PackageVersion: **0.105.3**

**Comment by dstala** [comment]
on mysql, didn't notice any error. but did see issue. number if fed was 123456789.01 - was displayed on refresh as 99999999.99

**Comment by dstala** [comment]
@liuwanzhen you can reconfigure precision using advanced menu hidden under easter egg
https://docs.nocodb.com/setup-and-usages/table-operations#column-edit

I tried below configuration & was able to store bigger decimals. 

![Screenshot 2023-03-07 at 10 57 57 AM](https://user-images.githubusercontent.com/86527202/223329134-eaf48e07-2188-49f9-b0ae-ba2119ae16a3.png)

![Screenshot 2023-03-07 at 10 58 24 AM](https://user-images.githubusercontent.com/86527202/223329193-ceb651aa-70a7-49d3-9746-7ba8fe7ef3cb.png)
