### ISSUE TITLE
How to calculate the sum of column A grouped by column B by calling APIs?

### ISSUE THREAD

**Issue by dwzkit** [nocodb/nocodb#526]
NocoDB used as docker : false
NocoDB version : 0.11.29
Database used in NC_DB URL : mariadb
Project was created by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mariadb
OS on which NocoDB is running : MAC OS
Node.js version if running as node : v14.15.1
Database version : 10.6.4-MariaDB-1:10.6.4+maria~focal

**Steps To Reproduce**
1. Want to  calculate the sum of column "file_size" grouped by column "activity_id" 
![image](https://user-images.githubusercontent.com/41875799/132937017-6fd3c9bf-7c61-459a-a4da-c05e57860bb0.png)

2. Can not calculate the sum of column "file_size" grouped by column "activity_id" by calling Aggregate functions
![image](https://user-images.githubusercontent.com/41875799/132937193-0f79debf-c1b2-406f-aa00-19eb5ea0e4a0.png)

3. When checking the SQL statement being executed
{
  sql: 'select `attachment`.`id` as `Id`, `attachment`.`created_at` as `CreatedAt`, `attachment`.`updated_at` as `UpdatedAt`, `attachment`.`file_name` as `FileName`, `attachment`.`file_url` as `FileUrl`, `attachment`.`file_size` as `FileSize`, `attachment`.`user_id` as `UserId`, `attachment`.`activity_id` as `ActivityId`, sum(`file_size`) as `sum` from `attachment` **group by `file_size`** limit ?',
  bindings: [ 20 ]
}

only calculate the sum of column "file_size" grouped by column "file_size"

**Expected behavior**
Whether Aggregate functions can calculate the sum of column A by grouping column B?

**Comment by o1lab** [comment]
This is tracked in #188

**Comment by yashchanda721** [comment]
It is not very clear in issue number 188, how exactly can we perform group by in table
