### ISSUE TITLE
🔦 Feature: Confirmation on delete record

### ISSUE THREAD

**Issue by TomBirchHansen** [nocodb/nocodb#5263]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

The ability on a table basis, to define if a warning should appear before a record is deleted.
Currently deleting a record is easily done with right click. This is often very convenient, but a deletion of important data can happen easily by mistake.
By making it possible to enable warnings ( a confirmation pop up) will prevent accidental deletion of critical data.

### Suggested Solution

On each table, there could be a setting that can be set to enable 'delete confirmations'. To enable/disable this feature, the user would need some 'table-admin' rights.
When this setting is enabled, each time a user right-clicks 'delete rows' on records in the table, a confirmation popup appears, with text such as "Confirm to permanently delete the selected record", and a "confirm" and "cancel" button. The "cancel" button should be the default button.

**Comment by frankMagoba** [comment]
Can I pick this up?

**Comment by TomBirchHansen** [comment]
yes, sure

**Comment by dstala** [comment]
this one's in roadmap. will be of help
https://github.com/nocodb/nocodb/issues/5258
