### ISSUE TITLE
🐛 Bug: Failed to fetch dynamically error

### ISSUE THREAD

**Issue by topsage** [nocodb/nocodb#5266]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

use docker 
docker run -d --name nocodb \
-v "$(pwd)"/nocodb:/usr/app/data/ \
-p 8080:8080 \
nocodb/nocodb:latest

but dashboard  open error 
![image](https://user-images.githubusercontent.com/51810073/223617334-c3b1b5cc-39a9-4b5a-906a-13022a86539d.png)

### Desired Behavior

dashboard  open error 

### Project Details

dashboard  open error

**Comment by wingkwong** [comment]
Not able to reproduce this issue on 0.106.1. Please retry on the latest version. Reopen if the issue persists.
