### ISSUE TITLE
🐛 Bug: Cannot Change A Users Role With Postgres Backend

### ISSUE THREAD

**Issue by BrettNWoods** [nocodb/nocodb#5287]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Go to 'User Management' within 'Teams & Auth'
2. Select a user with 'Editor' permissions
3. Click 'Select User Role'
4. Change user role to 'Creator'
5. Save

The following error will pop up without changing the role;

`update "nc_project_users_v2" set "roles" = $1, "updated_at" = CURRENT_TIMESTAMP where "fk_user_id" = $2 and "project_id" = $3 - cannot update table "nc_project_users_v2" because it does not have a replica identity and publishes updates` 

### Desired Behavior

The user with a Super Admin role should be able to able to change the user role from 'Editor' to 'Creator'.

### Project Details

Running in CloudRun with the latest NocoDB image with a Postgres backend hosted with CloudSQL

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.105.3**

### Attachments

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/47704209/224581639-e82cf424-4bfd-4281-afe4-071315823be8.png">

**Comment by dstala** [comment]
I was unable to reproduce locally (tried with official image on docker)

Node: **v16.19.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

**Comment by BrettNWoods** [comment]
Hi @dstala, PG version is pg 14.4.

**Comment by dstala** [comment]
@BrettNWoods We would appreciate if you can try this in our latest build v0.111.0 & let us know if you still see issue. Reopen if you are able to reproduce this issue.
