### ISSUE TITLE
Past table from from buffer

### ISSUE THREAD

**Issue by bambus1980** [nocodb/nocodb#5288]
Very need to use simple past table or single row from buffer.
One time we browse internet and find interesting data table from what uoy can copy some rows and save in notesbook. Nocodb is very nice notesbook. Sometime it more comfortable copy/past some rows or full table from somewhere to your knowbase, and it better then past to EXCEL and then import to Nocodb.
Simple way - past rows from buffer to string only fields. But, wa can think up the way to past to any type filds by match types by coded aliases. As sample: "Singleselect" field could mach for alias "1....3" as count variants as has field:

Sample buffer text: "lalala field1", "lalala fiald2", "[1]", "[5,6]"
Sample result to past: "lalala field1", "lalala fiald2", "lalala singleselect1", "lalala multiselect5; lalala multiselect6".

Sorry for my english and I hope you understand me.

**Comment by bambus1980** [comment]
What about suggestion?

**Comment by dstala** [comment]
@bambus1980 
direct copy paste to multiple cells is now supported in NocoDB. try out our latest release v0.202.5 & if you still have better suggestions - reopen this thread.
