### ISSUE TITLE
🔦 Feature: Formula MONTH() to extract month from a date

### ISSUE THREAD

**Issue by sebkur** [nocodb/nocodb#5297]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have a table with events and I'd like to create views that are filtered by month, i.e. they only contain events, let's say in April this year. I can currently work around it like this:

* Define a month column with this forumla: `SUBSTR(CONCAT({date_column}, ""), 6, 2)`
* Filter by new column `month is equal 04`

### Suggested Solution

I think it would be useful to have more functions like the already existing `WEEKDAY`. MONTH would make sense, probably also YEAR and DAY_OF_MONTH

### Additional Context

@spaudanjo and I ran into this issue when drafting tables for use cases in our co-working space.

**Comment by dstala** [comment]
MONTH(dateField) is supported now

**Comment by heiko-r** [comment]
Hi @dstala, I'm running version 0.204.1 in Docker, and the new `MONTH` formula does not seem to exist. Should I file this as a new bug or is there some obvious thing I'm doing wrong?
