### ISSUE TITLE
No Decimal Place on Some Formula Outputs where Needed

### ISSUE THREAD

**Issue by williambarberjr** [nocodb/nocodb#530]
**Please enter the following details**

Please provide the following details :
NocoDB used as docker : false
NocoDB version : 
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created : sqlite3
OS on which NocoDB is running : heroku?
Node.js version if running as node : 
Database version : No idea

**Steps To Reproduce**
1. 1 click deploy via heroku, add a new table (not sure if my background stats are correct for my environment but as of today, 9/14/2021, I hit one click deploy of onto heroku and tested out the default setup)
2. Add two integer columns with integer types to the new table
3. Enter 1 in the first column and 4 in the second column
3. Add an formula column as a third column, make it the average of the prior two integer columns
4. See the following "error" - the output is 2 and there is no way to change the view to display a decimal, presumably because the formula column has inherited the integer type from the two columns it depends on.

**Expected behavior**
While from some developer's perspective, displaying the average of 1 and 4 as the integer 2 might be the "expected behavior" in the sense that they would know that the formula column is coded to inherit the types of the columns it depends on. From a no-code user's perspective like me - I expect to see 2.5 or if I see 2, I expect to be able to change the view or some other property of the formula column to display the correct average of the two columns: 2.5

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by pranavxc** [comment]
Fixed in `0.11.31`
