### ISSUE TITLE
🐛 Bug: Unable to download attachment

### ISSUE THREAD

**Issue by whyteserious** [nocodb/nocodb#5326]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

upload  outlook .msg and md format file
Unable to download attachment
web ui   Failed to download file
only pdf can download

### Desired Behavior

maybe can resolve the  problem

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.105.3**

**Comment by wingkwong** [comment]
Already fixed in https://github.com/nocodb/nocodb/pull/5303. Please wait for the upcoming release.

Tested locally - able to download both .md and .msg.

![image](https://user-images.githubusercontent.com/35857179/226301803-9cab5d34-4842-4f01-bd2e-23e86a0a86a1.png)
