### ISSUE TITLE
🐛 Bug: "failed to copy to clipboard" when more than one cell is selected

### ISSUE THREAD

**Issue by maximemoreillon** [nocodb/nocodb#5333]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Deploy NocoDB with PostgreSQL as DB using the docker-compose.yml file provided in the NocoDB repo
- Select more than one cell in a table, right click and click "copy".

Notes:
- Copy works when only one cell is copied
- Neither the browser nor server console log any errors

### Desired Behavior

A successful copy to the clipboard of the selected cells

### Project Details

NocoDB used as docker: true
NocoDB version: 0.105.3
Databased in NC_DB_URL: pg
Project was created by clicking: New project
Database on which spreadsheet is created: pg
OS on which NocoDB is running: Ubuntu 20.04 LTS
Database version: postgres:latest
Browser: Chrome (112.0.5615.121), Firefox: (112.0)
NocoDB accessed via plain HTTP
NocoDB installed on a remote server in my LAN, i.e. accessed via http://server-ip:8080 and not http://localhost:8080

### Attachments

![nocodb_copy](https://user-images.githubusercontent.com/29086128/226537563-5c1cc762-88bd-42f7-a458-50e63e71d278.gif)

**Comment by wingkwong** [comment]
Any error messages you can share? I'm able to copy in 0.106.0 (pg).

**Comment by maximemoreillon** [comment]
Hello @wingkwong, 
thanks so much for your reply!
I tried the docker-compose.yml file provided in the NocoDB repo again after pulling the latest image (0.106.0). Unfortunately, the problem still occurs.
I can copy a single cell just fine but if more than one is selected, I get a "Failed to copy to clipboard" snackbar.
There are no error messages in either the browser console nor the server console.

**Comment by wingkwong** [comment]
@maximemoreillon 

1. Can you show your browser info?
2. Are you able to select multiple cells and copy by keyboards (i.e. ctrl + c in windows, cmd + c in mac) ?

**Comment by maximemoreillon** [comment]
@wingkwong Sure!

1. My browser is  Google Chrome version 111.0.5563.146 (Official Build) (64-bit).
It is running on Fedora Linux 37 (Workstation Edition)

2. The "Failed to copy to clipboard" appears when I copy using either right click > copy or ctr + c

**Comment by dstala** [comment]
I did see issue with firefox (111.0.1 (64-bit)). no console errors.
unable to reproduce it in my chorme (Version 112.0.5615.49 (Official Build) (arm64))

@maximemoreillon can you update chrome / firefox to latest and test once? we will look into this meanwhile to see if we can get some clues.

**Comment by maximemoreillon** [comment]
Hello @dstala, thanks a lot for your reply!

I upgraded my browsers to:
- Chrome: 112.0.5615.121
- Firefox: 112.0 

Despite that, I still get the "Failed to copy to clipboard" snack when I copy more than one cell.

I will try on a Windows machine tomorrow and report back.

**Comment by maximemoreillon** [comment]
Until now, I was using a NocoDB instance deployed using docker-compose on a remote server of my LAN.

So, as a test, I tried deploying directly on my laptop and access it via http://localhost:8080.
There I correctly get a "Copied to clipboard" when copying multiple cells so the copy seems to work.
However, when pasting the multiple cells I copied, their content gets lumped together in the selected cell.

Here's a short clip illustrating what I mean:
![Kooha-2023-04-16-15-27-34](https://user-images.githubusercontent.com/29086128/232277168-0a58a36a-4368-4244-a472-282b1856dc64.gif)

**Comment by maximemoreillon** [comment]
I tried copying multiple cells on Chrome 112.0.5615.121 (Official Build) (64-bit) running on a Windows 10 machine and NocoDB being deployed on a remote server of my LAN. I unfortunately still get the "Failed to copy to clipboard".

Would it be possible that this issue is related to `navigator.clipboard` [not being accessible for insecure origins](https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined)?

**Comment by wingkwong** [comment]
Another difference would be OS. Our team members are using Mac.

**Comment by maximemoreillon** [comment]
I see! Sorry I cannot be of much help for that matter as I don't own a Mac to test with

**Comment by EngiBenchi** [comment]
I do have this same issue. On multiple select  a copy gives  an error  
Iḿ on Linux Popos and firefox and the latest Docker-compose in Ubuntu lts 

![image](https://user-images.githubusercontent.com/20003780/233854937-0d6d12dd-3e4c-43bf-9501-dd7ec6c59632.png)

**Comment by sskf** [comment]
我也被这个问题困扰很久，今天尝试用windows直接运行，竟然可以，linux还是不行，版本是最新的，那看来是跟操作系统有关，或者跟CPU有关。。。

**Comment by sskf** [comment]
我也被这个问题困了很久，今天试试用windows直接运行，竟然可以，但是linux还是不行（docker、本地直接运行都不行），nocodb版本都是最新的，那看来是跟操作系统有关，或者跟CPU有关。。。

**Comment by sskf** [comment]
我也被这个问题困了很久了，今天尝试用windows直接运行，竟然可以，但是linux还是不行（docker、本地直接运行都不能行），nocodb版本都是最新的，那看来是跟操作系统相关，或者说跟CPU相关。。。

**Comment by EngiBenchi** [comment]
I had some hope this bug was crushed by a recent multiple copy/past Commit (86527201)
So this issue is still present in version 0.109.2 in a Linux docker as server and Linux and windows client (both in Chrome and Firefox) 
![Screenshot from 2023-06-22 19-39-27](https://github.com/nocodb/nocodb/assets/20003780/f793825c-d8ff-4b9d-82a1-a18553aa76d9)

**Comment by ilyak0** [comment]
I also have the same issue on
 Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.4**

However it's the same problematic base/table as in 
[Bug: unable to download table data ((t || []).map is not a function)](https://github.com/nocodb/nocodb/issues/5552)

**Comment by carr0t2** [comment]
My debugging result is that the ClipboardItem is undefined
![image](https://github.com/nocodb/nocodb/assets/62796978/f5490757-2b0e-44de-b267-55358acdecda)

**Comment by wingkwong** [comment]
@carr0t2 can you also share your browser info and which nocodb version are you using?

**Comment by carr0t2** [comment]
According to MDN documents, ClipboardItem is indeed unable to use in a non HTTPS Website.
> ClipboardItem
> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem#browser_compatibility).

It is recommended to document or print "only HTTPS webpage support copy and paste" in the web console

**Comment by dstala** [comment]
Thanks for the confirmation @carr0t2! we will move these details to FAQ

**Comment by TangXY123** [comment]
@dstala I just met this issue, and this still exists in version **0.205.0**. My test steps are as follows, hope can provide some infomations for you guys to shoot this issue.
**[Environment]**
- Windows VS code development enviroment.
- with "pnpm run watch:run" command to run the project.

**[steps]**
- Access "http://localhost:port" . Can copy nomally.
![image](https://github.com/nocodb/nocodb/assets/48933981/ec2167a8-d95f-45d7-b132-c7334536be56)
- Access "http://127.0.0.1:port" .Can copy nomally,too.
![image](https://github.com/nocodb/nocodb/assets/48933981/4b235c37-4609-4ba5-b027-b5ed3e86eae0)
- Access "http://IP:port". It goes wrong!
![image](https://github.com/nocodb/nocodb/assets/48933981/a8665fce-1603-467b-85aa-a7ba423cd2c2)
![image](https://github.com/nocodb/nocodb/assets/48933981/e48f4fde-8409-4c0f-9257-f293951f0435)

Looking forward to your reply！

**Comment by TangXY123** [comment]
@dstala I just met this issue, and this still exists in version **0.205.0**. My test steps are as follows, hope can provide some infomations for you guys to shoot this issue.
**[Environment]**
- Windows VS code development enviroment.
- with "pnpm run watch:run" command to run the project.

**[steps]**
- Access "http://localhost:port" . Can copy nomally.
![image](https://github.com/nocodb/nocodb/assets/48933981/ec2167a8-d95f-45d7-b132-c7334536be56)
- Access "http://127.0.0.1:port" .Can copy nomally,too.
![image](https://github.com/nocodb/nocodb/assets/48933981/4b235c37-4609-4ba5-b027-b5ed3e86eae0)
- Access "http://IP:port". It goes wrong!
![image](https://github.com/nocodb/nocodb/assets/48933981/a8665fce-1603-467b-85aa-a7ba423cd2c2)
![image](https://github.com/nocodb/nocodb/assets/48933981/e48f4fde-8409-4c0f-9257-f293951f0435)

Looking forward to your reply！
