### ISSUE TITLE
🔦 Enhancement: Migrate NC-GUI nuxt 3 internal to stable release

### ISSUE THREAD

**Issue by dammy001** [nocodb/nocodb#5334]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Nuxt 3 stable has a lot of improvements and bug fixes but GUI is still on release candidate.

### Suggested Solution

#5299

**Comment by wingkwong** [comment]
Closing - not applicable now. version has been upgraded.
