### ISSUE TITLE
🐛 Bug: BullMQ: DEPRECATION WARNING! Your redis options maxRetriesPerRequest must be null. On the next versions having this settings will throw an exception

### ISSUE THREAD

**Issue by sehrish30** [nocodb/nocodb#5335]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Start the app it throws this error

### Desired Behavior

I don't have maxRetriesPerRequest anywhere in my code

### Project Details

bullmq Verion: 3.10.1
Nodejs version: 19.3.0
ioredis version: 5.3.1

### Attachments

<img width="574" alt="Screen Shot 2023-03-21 at 5 51 30 PM" src="https://user-images.githubusercontent.com/66527974/226644736-c50c7429-3282-4efe-b2de-fd14bf4e01f9.png">

**Comment by wingkwong** [comment]
@sehrish30 May I know which nocodb version you are using?
