### ISSUE TITLE
🐛 Bug: Failure to download doc attachment

### ISSUE THREAD

**Issue by ilyak0** [nocodb/nocodb#5344]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Uploaded attachement in doc/x format - either tru form or directly - could not be downloaded

<img width="864" alt="image" src="https://user-images.githubusercontent.com/111974217/226855697-3f211288-1c30-43a5-982b-7cf0288c91f9.png">

### Desired Behavior

Docs are downloaded like other file types

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.105.3**

**Comment by wingkwong** [comment]
Please wait for the upcoming release.

Tested locally.

![image](https://user-images.githubusercontent.com/35857179/226868078-9251d04e-dc64-406a-9ce4-a6448ceb54d4.png)

**Comment by SNiari** [comment]
I am experiencing the same issue with all documents except for pictures. Is there any solution available for this?

**Comment by wingkwong** [comment]
@SNiari Please share your base info and DM me at discord.

**Comment by SNiari** [comment]
Thank you, I've already sent you a DM on Discord.
