### ISSUE TITLE
Deleted table still visible in navigation pane

### ISSUE THREAD

**Issue by bannmann** [nocodb/nocodb#535]
Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.11.29**

**Steps To Reproduce**
1. Delete a table
2. Click 'Submit' to confirm table deletion
3. Check the navigation pane on the left

**Expected behavior**
The deleted table should disappear from the list immediately, not only after reloading the page.

**Comment by pranavxc** [comment]
Fixed in `0.11.31`

**Comment by o1lab** [comment]
Still seen in 0.11.32

**Comment by o1lab** [comment]
I feel this there is race condition here. We would have to see whether table in virtual schema has got deleted in sync fashion or whether we area calling reload of tables too soon. @pranavxc

**Comment by o1lab** [comment]
Fixed 0.11.36
