### ISSUE TITLE
"Editor" role not allowed to upload files

### ISSUE THREAD

**Issue by bannmann** [nocodb/nocodb#536]
Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.11.29**

**Steps To Reproduce**
1. Log in as a user with "editor" role
2. In an "Attachment" field, try to upload or remove a file

**Expected behavior**
Editors should be able to manage attachments.

Currently, one needs to be "creator" to do this. However, that role also allows users to change the table structure! This is surprising as "editor" is documented as "Can edit records but cannot change structure of database/fields". Being a programmer, I know that attachments are stored separately and only referenced by the record. But I still consider them to be _values_, not part of the _table/database structure_.

**Comment by o1lab** [comment]
Makes sense. This was missed out in ACL rules.

**Comment by pranavxc** [comment]
Fixed in `0.11.31`
