### ISSUE TITLE
🐛 Bug: VULNERABILITY: Sign Out doesn't work

### ISSUE THREAD

**Issue by bonacci-johannes** [nocodb/nocodb#5361]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

The sign out doesn't work.
To reproduce the error start a fresh docker using:

```
docker run -d \
 --name nocodb-test \
 -p 1111:8080 \
 nocodb/nocodb:latest
```
create a user and sign out. When signing out you are forwarded to the sign in page 'host:1111/dashboard/#/signin'.
But when simply entering host:1111 in the firefox or chrome browser you are logged in without providing any credentials.

When opening a fresh browser without any data saved and accessing 'host:1111' the user is forwarded as expected to 'http://host:1111/dashboard/#/signin' but receives the error message 'request failed with status code 400'

### Desired Behavior

A proper sign out for safety reasons :-)

### Project Details

NocoDB Version 0.105.3 used as Docker on linux server

**Comment by wingkwong** [comment]
Fixed [here](https://github.com/nocodb/nocodb/commit/e57b0e7e1ce8733a4b774ab74bcd678b90e1ffa6) last week. Please wait for the next release (scheduled next week).

**Comment by bonacci-johannes** [comment]
The release 0.106.0 doesn't fix this bug!

**Comment by wingkwong** [comment]
@bonacci-johannes Can you provide a video for demonstrating? I just tested on chrome. Accessing `host:1111` would stay in sign in page.

**Comment by jeanbaptistevilain** [comment]
Hi, thanks for the work on nocodb.
I'm having a similar issue with a self-hosted instance (not using Docker).
I can't seem to logout, the POST request sent to "/api/v1/auth/user/signout" returns a 404 code (not found).
Behavior reproduced both in Firefox and Chrome, using version 0.106.0.

**Comment by wingkwong** [comment]
Able to reproduce. Will take a look.

**Comment by bonacci-johannes** [comment]
the productive setting is using a postgres to store all nocodb related settings  (-e DATABASE_URL="pg://some_host:5432?u=user&p=pwd&d=nocodb")
Maybe this might play a role.
