### ISSUE TITLE
drag and drop a table in another database [Feature] 

### ISSUE THREAD

**Issue by bitsByB** [nocodb/nocodb#5362]
it would be cool to drag and drop a table in another database.
for example instead to have to delete my table in Default db and recreate it in openblocks_db it would be great to just drag and drop it
![image](https://user-images.githubusercontent.com/102392085/227578220-8d4fc164-8385-426c-942b-f6272cdd5a56.png)

**Comment by o1lab** [comment]
It will not be as easy if they are in different DB altogether :)

So closing this for now.
