### ISSUE TITLE
🐛 Bug: nested filtering doesn't work properly

### ISSUE THREAD

**Issue by pashkatrick** [nocodb/nocodb#5365]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create two tables.
2. Add the "Has Many" relation between two tables (Link To Another Record column)
3. Add some records to both tables. At least two records in the child table - one related to parent and one with null in the foreign key column.
4. Use API to get records from parent table which contains concrete id from child records like:
`nested[child][where]=(field1,eq,value)`
but getting all records instead

Expected Behavior
User should be able to filter out records 

### Desired Behavior

just fix current logic pls

### Project Details

nocodb is in docker
nocodb db is sqlite
OS - MacOS
test on built in swagger

**Comment by davidpfahler** [comment]
This seems to be a renewed occurrence of https://github.com/nocodb/nocodb/issues/5218. I can confirm that I have the same bug with the following project details:

```
Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**
```

**Comment by wingkwong** [comment]
@davidpfahler The issue you linked has marked the milestone "Next Release: 0.106.0", which means the fix will be available in 0.106.0. The next release will take place on Wed.

**Comment by davidpfahler** [comment]
@wingkwong Thanks, so it may be the same issue.

**Comment by namnhfreelancer** [comment]
I have same issue in 0.109.6

**Comment by pranavxc** [comment]
The `nested[child][where]` is for  nested LTAR data, the filter applied for the child list and not on the root list.
