### ISSUE TITLE
🐛 Bug: various small annoyances

### ISSUE THREAD

**Issue by brunov25** [nocodb/nocodb#5377]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

these are probably due to my being a nocodb newbie experimenting extensively before fully understanding the nocodb ecosystem, specifically, i started with 0.105.3 (stable) and then switched to the timely version for a week before realizing it was too cutting edge, then trying to return to stable was quite the challenge .

1. the vertical spacing between the tablenames on the left sidebar is quite wide ... such that only 2 tables show at any time, requiring much scrolling. Workaround: F12, filter: h-full, ^F search: h-full, uncheck the first occurence and then the table listing is clean again. This has to be done every time the nocodb docker is restarted and for each tab
2. exporting tables in csv with nocodb timely web interface produces files that contain a bit of HTML at the top and bottom, and does not produce json for the file attachments, as well as html's &quot; intead of actual quote symbols.  Workaround:  export directly from sqlite3
3. if i change my mind and rename a table, the primary view still has the original name. If I upload a cvs file to create (recreate) any table, the table name is the name of the file including the csv bit... and i can rename it but the primary view wont change name.    Workaround:  import directly in the database
4. and if I delete a table and recreate it ... such that somehow the primary view is a duplicated name, then data entry with this duplicated view causes "undefined bindings detected when binding" errors multiple times while doing data entry and produces a lot of partial rows as it creates what should be only one row.  Workaround:  create a new form view and use that instead  (and delete spurious rows)

hopefully this is slightly useful and somewhat understandable

### Desired Behavior

- listing of tables should not be spaced out more than one line apart
- exporting tables to csv is apparently not a stable feature yet
- the primary view name should be editable

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.105.3**

as well as a week long foray into timely last week

**Comment by brunov25** [comment]
the default CSS that affects the first issue is `.h-full {height: 100%} `  
replacing that with 'auto' instead of '100%' solves it: `.h-full {height: auto} `

**Comment by brunov25** [comment]
any chance that default can be changed in the official source code?

**Comment by wingkwong** [comment]
For the issue 1 & 2, can you please show some screenshots?

For the issue 4, I couldn't reproduce. Can you please provide a video record to demonstrate?

> the default CSS that affects the first issue is .h-full {height: 100%} 
> replacing that with 'auto' instead of '100%' solves it: .h-full {height: auto} 

That's defined from windicss. Changing the value for a predefined class is not appropriate. If you need to use `auto`, then you may consider to use `h-auto` instead. However, I need to make sure I fully understand the issue before verifying if this is the correct fix.

**Comment by wingkwong** [comment]
@brunov25 Can you try on the latest version for the first 2 items?

**Comment by wingkwong** [comment]
@brunov25 Since you've upgraded, can you please provide the screenshots?

**Comment by brunov25** [comment]
update:  i tried again from scratch with nocodb 0.105.3 with just a couple of tables

issues 1 and 2 go away 

then i upgraded to nocodb 0.106.beta1 and issues 1 and 2 are gone there as well

so i think my original work is slightly corrupted from having  switched between versions last month ... i will try rebuilding the entire database (which is time consumming since the csv files there are all slightly corrupted) and see these results still hold

thank you for your patience

**Comment by brunov25** [comment]
finally found the problem:  it was a stanza involving  ProxyHTMLURLMap directives in apache's configuration.  As soon as I commented it out, the annoyance issues went away on the site where these annoyances started in the first place.  So no data was corrupted , not even slightly.

As far as I am concerned, this issue is closed.
