### ISSUE TITLE
🔦 Feature: Logged in user information in form submission

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5378]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

![Screenshot 2023-03-28 at 3 23 36 PM](https://user-images.githubusercontent.com/86527202/228199547-24a110c0-d66b-40a8-bbc9-f02a6cbf7af2.png)

### Suggested Solution

- ability to access logged in user info (`Created By` column?)

### Additional Context

Requested by Discord user "lcslouis"

**Comment by computersrmyfriends** [comment]
Need logged in user info in api hooks, column field type, etc

Please provide the user info on who has entered the data. It's seriously a very big limitation.

**Comment by dstala** [comment]
`Created by` `Updated by` field type support

**Comment by dstala** [comment]
To be tracked under

[Feature : New columns => created_by, last_updated_by](https://github.com/nocodb/nocodb/issues/499)
