### ISSUE TITLE
Tables list is not getting refreshed when I click refresh

### ISSUE THREAD

**Issue by abhinav054m** [nocodb/nocodb#538]
I am trying to refresh the tables on the dashboard , but it doesn't show the newly added tables to the database. I am new to the project can you please guide me how to debug the issue.

**Comment by o1lab** [comment]
Were the tables added from a different tool or using our GUI ?

**Comment by abhinav054m** [comment]
the tables were added from a different tool.

**Comment by o1lab** [comment]
Idea with nocodb is to connect to a new/exisitng database and start making changes via nocodb GUI. We keep a virtual schema mirroring the actual schema.

If schema is changed outside nocodb GUI, it has to be synced. See project metadata (at bottom left) and then second tab. There is an option to sync the metadata.

However, the idea is to use nocodb GUI.

**Comment by abhinav054m** [comment]
Thanks, I'll check it out.

**Comment by rlfrahm** [comment]
Is this documented anywhere? This is a really import functionality that has caused me to stop using Nocodb for several projects because our code bases/schema had changed and I couldn't figure out how to update Nocodb.

**Comment by abhinav054m** [comment]
Have you synced the schema from project metadata.

**Comment by rlfrahm** [comment]
Yes I've fixed it after reading this thread. What I'm suggesting is that the documentation should highlight this functionality because it's really important (and missing).

Link to docs: https://docs.nocodb.com/setup-and-usages/meta-management#database-metadata

**Comment by o1lab** [comment]
On it now.

**Comment by o1lab** [comment]
https://docs.nocodb.com/setup-and-usages/sync-schema

There are two things here.

- **Syncing schema changes of a database to NocoDB.**
  -  Changing the schema outside nocodb GUI means - nocodb can still sync the changes. However then nocodb is not responsible for keeping track of metadata changes which will come into play while moving from one environment to another environment.
- **Metadata migration from one environment to other.** - this is different than schema sync.
  -  If all changes were done in nocodb GUI - schema migrations work.

For now, syncing schema changes and migrations from env to another work with projects created by connecting to external databases.

Having said above, managing schema migrations and sync is a complex operation in any application and we 've spent considerable effort on this. 

We will document this well and iron out the edge cases.

**Comment by rlfrahm** [comment]
For some backstory, our use case is such that we have a dev team build a web application and a business team who are the main users of NocoDB. So the dev team being able to come in and manually sync schema works great for us. Previous to today I didn't even know this was possible. Thanks for the prompt follow-up!

**Comment by o1lab** [comment]
Thank you for the usecase. Noco makes some of the things seamless with migrations. However, there is some learning required here. We will build a matrix of sort to cover the usecase.
