### ISSUE TITLE
🔦 Feature: LinktoAnotherRecord automatically update the same field

### ISSUE THREAD

**Issue by Charuru** [nocodb/nocodb#5385]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

For example if I have a person table with a married partner column. I would want the partner's married column to update when one person is set as married. Currently, it creates a second column to update.

### Suggested Solution

Allow setting the column to update for the LinktoAnotherRecord field.

**Comment by dstala** [comment]
@Charuru not very clear with requirement. Could you help elaborate?
