### ISSUE TITLE
Issue: Setting default value involving symbols or multiline gives errors when setting default value for longtext

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#539]
Hi,

When saving default value involving symbol or new line then getting error. In case it could be supported would be helpful to store things like pre formatted text that will be updated later
Steps:
1- Make column with longtext having default value as symbol or new line
2- Save. On saving getting error
![image](https://user-images.githubusercontent.com/86340924/133630724-69408f1d-e68a-4c03-852a-2fa2d0476828.png)
![image](https://user-images.githubusercontent.com/86340924/133630929-b885c464-7c03-4b78-92cd-4420ca9d2464.png)

Database: sqlite

**Comment by ismaildawoodjee** [comment]
How do you access the Debugger or the log information?

**Comment by pranavxc** [comment]
Wrap the text with a double quote and then it should be fine.

![image](https://user-images.githubusercontent.com/61551451/148759307-c25f36ac-6fd5-4832-9832-466dc8ce8798.png)
