### ISSUE TITLE
🐛 Bug: vultr s3 bucket 

### ISSUE THREAD

**Issue by 1letzgo** [nocodb/nocodb#5401]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Unfortunately, when adding a vultr bucket via App Store, it does not work.
Nocodb tries to add an ovh bucket instead.

### Desired Behavior

Van you fix this? 

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

**Comment by wingkwong** [comment]
@1letzgo Can you help test on the following image?

```
 docker run -d -p 8888:8080 nocodb/nocodb-timely:0.106.0-beta.1-pr-5445-20230411-0845
```
