### ISSUE TITLE
[Feature]  when creating linked tables, use NLP to name columns correctly

### ISSUE THREAD

**Issue by ibercovich** [nocodb/nocodb#5409]
For example if I have a table called "companies" and another called "employees" and each employee works for one company, name the column automatically created in employees, "company" (singular)

**Comment by dstala** [comment]
Links field now support singular / plural representation for associated count. For column name, no immediate plan in our roadmap

![Image](https://github.com/nocodb/nocodb/assets/86527202/026b5fdb-cb5c-43a2-9a2f-099d06f957cd)
