### ISSUE TITLE
Bug: failed to restore database from a snapshot

### ISSUE THREAD

**Issue by Sitin** [nocodb/nocodb#541]
**Steps To Reproduce**
1. Create a snapshot of NocoDB main database
2. Create a new database from the snapshot (use different hostname and credentials)
3. Point NocoDB to the new database

**Expected behavior**
Application should be up and running. All configured projects should be available.

**Actual behaviour**
Application fails to run due to the `Malformed UTF-8 data` error.

```
Error: Malformed UTF-8 data
    at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:513:24)
    at WordArray.init.toString (/usr/src/app/node_modules/crypto-js/core.js:268:38)
    at /usr/src/app/docker/main.js:2:246006
    at Array.map (<anonymous>)
    at n.projectList (/usr/src/app/docker/main.js:2:245815)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async P.initProjectBuilders (/usr/src/app/docker/main.js:2:35579)
    at async P.init (/usr/src/app/docker/main.js:2:32588)
    at async /usr/src/app/docker/main.js:2:249194
```

Node version : **v12.22.1**
Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
packageVersion: **0.11.29**

Looks like it is linked to the #343.

**Comment by o1lab** [comment]
In the project info provided, the root database information is missing. 

Was it pg ? 

And if you had used NC_JWT_AUTH_SECRET then you would have to use the same secret while pointing it to new database.

From the error, looks like this is a result of secret being not the same. We keep all database credentials for creating new projects in encrypted fashion. And we use above env variable for it. If its not the same - there will be errors.

**Comment by o1lab** [comment]
Please feel free to reopen if you have a reproducible steps. Happy to take a look.
