### ISSUE TITLE
🐛 Bug: renaming tables only renames part of the metadata

### ISSUE THREAD

**Issue by ibercovich** [nocodb/nocodb#5410]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When I import data, I don't want the table name to remain the automatically generated one.

![image](https://user-images.githubusercontent.com/613679/229652463-9ac866b5-899f-41b5-85c4-e9680e370aa6.png)

### Desired Behavior

When I change the name of a table, it should change everywhere

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.106.0-beta.0**

**Comment by aagrawal7** [comment]
Can I work on this @wingkwong

**Comment by wingkwong** [comment]
@aagrawal7 assigned. feel free to discuss with the team via discord.

**Comment by aagrawal7** [comment]
@ibercovich 
I suppose this is expected behavior.
Separate views are created for each table, changing table name will not change the view name .

Can you please elaborate on the issue

**Comment by dstala** [comment]
with v0.202.5, default view name is no more table name but will remain static as `Default view`; this issue would hence be no more relevant
