### ISSUE TITLE
🔦 Feature: Import linked tables

### ISSUE THREAD

**Issue by ibercovich** [nocodb/nocodb#5411]
let the import know which column I am using as the identifier and get the two tables linked

**Comment by EngiBenchi** [comment]
Yes I'm missing that feature as well. Edditing 1600 rows one by one aint fun
Dragging down values like in Excel or airtable would help Or copy past in a linked cel the correct data would be ideal. Or converting a column with the correct data into a linked column

**Comment by dstala** [comment]
to be tracked under [🔦 Feature: Use existing columns between two tables to create a relationship.](https://github.com/nocodb/nocodb/issues/6848)
