### ISSUE TITLE
🔦 Feature: Possibility to edit all fields when expanded

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#5416]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

We can show important rows in the grid view himself and if we want to edit, we can expand and edit the rows. Would also increase the speed of the initial loading time(We can hide most of the Fields then and still able to edit everything we want).

![image](https://user-images.githubusercontent.com/117290601/229751549-b8e05f36-f2cc-405d-af84-eed6e7cbc338.png)
![image](https://user-images.githubusercontent.com/117290601/229752140-b7c9e01b-8059-48f3-bedb-108f4265eb40.png)

### Suggested Solution

Possibility to choose which fields are able to edit in the expanded view. Right now same fields are shown in the grid view and the expand view.

Maybe we can have 2 Checkboxes in the Fields section. 1x for grid view and 1x for expanded view

![image](https://user-images.githubusercontent.com/117290601/229754388-1fee3909-c568-4f32-a541-a6f8d0ff4e5c.png)

**Comment by dstala** [comment]
`Show hidden fields` option now available in release v0.202.5
