### ISSUE TITLE
🐛 Bug: NocoDB is not syncing to Postgres

### ISSUE THREAD

**Issue by fteklitz-mpg** [nocodb/nocodb#5418]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

# FrankMPG — 4/3/23 at 11:47 AM
I just set up NocoDB with Docker, using a Postgres database for my source data.

The first time I sync'ed the Postgres database I was able to import the metadata for each table. When the primary key sync'ed, nocoDB worked great. In some cases the primary keys did not sync and I could not do updates to the data in NocoDB. Resyncing did not fix the problem. I tried reconnecting. That did not help. I deleted the tables and not only would nocoDB not resync the primary keys, it would not resync the table metadata. I deleted the project and sync'ing no longer works at all. This seems pretty fragile to me.

What are my options?

# o1lab | NocoDB Team — 4/3/23 at 11:49 AM

why dont u try reconnecting it again

# FrankMPG —  4/3/23  at 11:55 AM

I will try that

# FrankMPG — 4/3/23 at 1:33 PM

Ok, rebooted my server, which brought up nocoDB and docker and postgres. I signed into NocoDB on the web. Deleted the old projects. and created a new one. Added a data source and synced it. Got a message that "Tables metadata is in Sync," but no tables were added to the project from postgres.

So what do we do? It kind of worked the first time I synced. It should now. I have no logs to inspect to discover execution issues. Looking for ideas.

# Additional Note:

When I went to the ERD diagram I could see the tables and columns and the primary keys, which according to the documentation should enable me to do updates.  This only worked for one table out of four that had primary keys.

### Desired Behavior

1. Sync should recognize when tables do not exist (or are updated or deletedd) in nocoDB and add them to nocoDB project
2.  NocoDB should be able to recognized primary keys and enable changes to fields
3.  CLI interface for logs, versions, etc. would be useful

### Project Details

NodoDB uses docker
Nododb version should be latest, downloaded last week
Database used for NC_DB URL: pg
Project created by clicking: New Project
Note: No "New Project by connecting to external database" presented
Database on which spreadsheet is created: pg
OS on which NocoDB is running: Windows device with WSL
Not using Node.js (using Docker)
Database version: pg 
Version
6.19
Application Mode
Desktop
Current User
pgadmin4@pgadmin.org
NW.js Version
0.55.0
Browser
Chromium 92.0.4515.107
Operating System
Windows-10-10.0.19045-SP0

**Comment by o1lab** [comment]
As mentioned in discord, could you try reconnecting the database once please

**Comment by fteklitz-mpg** [comment]
The connection works fine.  If the connection failed, why would NocoDB tell me "Tables metadata is in Sync"?

**Comment by fteklitz-mpg** [comment]
![Screenshot 2023-04-04 135620](https://user-images.githubusercontent.com/91699997/229877898-47d7c183-8580-4d31-bde9-833f3c3e8afa.png)
![Screenshot 2023-04-04 135557](https://user-images.githubusercontent.com/91699997/229877919-601399d1-6916-4e79-af8f-19553a2b113b.png)

**Comment by fteklitz-mpg** [comment]
I think I see the problem (and I will test this to make sure).  Only one of my test tables was getting the primary key so I could do updates.  Syncing did not seem to fix this.  So I deleted the tables from nocodb.  It appears that it also deleted my tables in postgres, hance syncing nothing.  I was assuming that nocodb would only delete the metadata, given the tables belong to me.  Silly me.

If your product will not sync my primary keys (even if I do them later), yet will gladly delete my tables, that is not cool.

I will let you know.

**Comment by fteklitz-mpg** [comment]
Okay.  It is up and working again.  I put the Primary Key clause in the Create Table statement and it is working cleanly so far.  This caused Noco to make mods to the noco metadata that the Alter statement did not.
