### ISSUE TITLE
Unable to pick May 31 2021 in date picker

### ISSUE THREAD

**Issue by sph33r** [nocodb/nocodb#542]
NocoDB used as docker : true
NocoDB version :  0.11.32
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project 
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Ubuntu 20.04 Server
Node.js version if running as node : 
Database version : Postgres 12.8

**Steps To Reproduce**
1. Create new column
2. Column Type: Date
3. Type in database: date
4. Click field to get date picker
5. Try to pick May 31 2021 - it only goes up to 29.

**Expected behavior**
I expect the correct number of days in the calendar month.

**Screenshots**
![no-may-31](https://user-images.githubusercontent.com/1290732/133867692-7e3c761c-4bdf-4ab1-a7ab-6b388da916d6.png)

**Comment by o1lab** [comment]
Which browser is it - chrome?

**Comment by sph33r** [comment]
Sorry, I verified it happens in Firefox and Chromium but I failed to mention that.

**Comment by pranavxc** [comment]
Fixed in `0.11.39`
