### ISSUE TITLE
🐛 Bug: webhook timestamp's differ in timezone

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5423]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- create insert/update/delete webhook
- add record

- delete record : will trigger delete webhook
```
{
  "type": "records.after.delete",
  "id": "c120aa17-c5f6-4a70-8a3d-04c82e01e15f",
  "data": {
    "table_id": "md_5nqpbgs330yf17",
    "table_name": "Sheet-1",
    "view_id": "vw_wtbgkpya0h2mdv",
    "view_name": "Sheet-1",
    "rows": [
      {
        "Id": 2,
        "Title": "a",
        "CreatedAt": "2023-04-05T00:40:09.260Z",
        "UpdatedAt": "2023-04-05T00:42:07.694Z"
      }
    ]
  }
}
```

- undo : will trigger insert webhook
```
{
  "type": "records.after.insert",
  "id": "d0e3b51f-0e0d-4217-96b4-80c25b19ce25",
  "data": {
    "table_id": "md_5nqpbgs330yf17",
    "table_name": "Sheet-1",
    "view_id": "vw_wtbgkpya0h2mdv",
    "view_name": "Sheet-1",
    "rows": [
      {
        "Id": 2,
        "Title": "a",
        "CreatedAt": "2023-04-04T19:10:09.260Z",
        "UpdatedAt": "2023-04-04T19:12:07.694Z"
      }
    ]
  }
}
```

created at & updated at timestamps displayed on UI are consistent. but somehow date differs (could be related to timezone handling). 

### Desired Behavior

expect to retain similar timezone formats across undo operation

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.106.0-beta.0**

**Comment by wingkwong** [comment]
@mertmit I think the root cause is that during insert, the previous data including `CreatedAt` & `UpdatedAt` is provided. I just had a quick test - by removing those 2 fields in insertObj, the response data looks ok. Those auto-generated fields shouldn't be included in this case.

**Comment by mertmit** [comment]
@wingkwong DBs other than pg keeps original values, my intention was same with pg but there is a ui/backend mismatch on pg. Example using GMT+3 tz:
When you insert a record at 12.00 creates_at on ui shows 09.00 and when we check db value for same record(or simply copy record) it is 06.00
So when we insert with undo again it reflects timezone difference and shifts 3 more hours.

**Comment by RASBR** [comment]
Hi,
I am in a GMT+3 TZ and the system time for fields date created and updated is correct when using the UI, but when inserting a local time using the API it adds 3 hours to it. I tried setting the TZ environment variable to Asia/Amman but it didn't change anything.
