### ISSUE TITLE
🐛 Bug: Primary column shows red border

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5424]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![Screenshot 2023-04-05 at 11 24 27 AM](https://user-images.githubusercontent.com/86527202/230002491-fb8d481d-b3ee-455b-bd2f-c4ca0af2a751.png)
![Screenshot 2023-04-05 at 11 24 38 AM](https://user-images.githubusercontent.com/86527202/230002515-484e9954-5539-4e73-b54b-10e6c12e9120.png)

PG- customer table. Primary column shows red border. And it look’s fine when show system fields is enabled
Similar observation with inventory table

### Desired Behavior

display normal cell layout

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.106.0-beta.0**

**Comment by frankMagoba** [comment]
can I pick this up?
