### ISSUE TITLE
🔦 Feature: formula column filter type support based on formula resultant type

### ISSUE THREAD

**Issue by ly120ve980ly** [nocodb/nocodb#5437]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

formula column (numeric result) need compare filter:  =, >, <

### Suggested Solution

formula column (numeric result) need compare filter:  =, >, <

**Comment by RawmanGrey** [comment]
Plus, as formula column can return date, string and number, ___all___ filtering and sorting options should come back.

PS: not quite sure how to handle cases where formula can return several types...

**Comment by wingkwong** [comment]
Resolved in above linked PR.
