### ISSUE TITLE
🔦 Feature: Add new rows and make cell editble in Locked View mode

### ISSUE THREAD

**Issue by semighoti** [nocodb/nocodb#5439]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Locked View and Shared View basically the same at the moment. If we can make cells editable + add new rows (not add columns)  for manager level in Locked View, it will be great in term of management.

Another use case is setting up a grid for company's employees, then let them edit it without changing any filters or sorts. Editable  in Locked View can provide a great control for executive level in a company.

Locked view editable feature is employed on Seatable, and t is very useful feature according to some Redditors.

### Suggested Solution

Add ability for user (editors) to be able to edit cells and add new rows in Locked View.

**Comment by dstala** [comment]
Could be better to allow checkbox menu on selecting `locked view` to let users decide what to lock
- add / edit columns
- add / edit records
- add / edit field configurations (filter, sort, fields)

will have to check with designer to see if it's a overkill though

**Comment by dstala** [comment]
Locked view has records editable (as seen in latest release). Please reopen this ticket if you see any anomaly
