### ISSUE TITLE
🔦 Feature:  Add CloudFlare R2  Support 

### ISSUE THREAD

**Issue by Bad3r** [nocodb/nocodb#5441]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Cloudflare R2 is an alternative service to AWS S3 buckets.
They have a compatible API, and it should be relatively simple to add support for it.
https://developers.cloudflare.com/r2/

### Suggested Solution

https://developers.cloudflare.com/r2/api/s3/api/

**Comment by ReessKennedy** [comment]
@Bad3r ... have you tried to use the Minio plugin for this? I am trying it right now and can't get it to go but thought it could work because it allow you to define an endpoint so I just plugged in the Cloudflare r2 endpoint there.

**Comment by DarkPhoenix2704** [comment]
R2 support is added in https://github.com/nocodb/nocodb/pull/9104

Will be available in next release
