### ISSUE TITLE
🐛 Bug: incorrect results of concat formula

### ISSUE THREAD

**Issue by ilyak0** [nocodb/nocodb#5449]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Concat function does not return consistent results, ie the link to the date field returns values in different formats.
See the formats at the display value. First 2 differ  (both the order of the values as well as dividers are wrong from the 3rd one - which is correct as per the following formula "CONCAT({дата}, "-", {номер})"

<img width="817" alt="image" src="https://user-images.githubusercontent.com/111974217/231213191-cd6b814e-fe7b-43eb-a18c-876e839b9aca.png">

### Desired Behavior

The returned values are consistent, and are in the same format as the initial value.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.105.3**

**Comment by wingkwong** [comment]
@ilyak0 The date format for дата is `DD/MM/YYYY` and on row 3 you have `29/03/2023` in your table. That's why it shows `Invalid date`. `CONCAT` is simply combine the values of the given inputs, then you will have `29/03/2023` + `-` + `019-2023/HW`. In this case, you can simply update the date value on row 3.

**Comment by ilyak0** [comment]
Thanks for the prompt answer. May be I wasn't clear enough - the issue I've raised is not about invalid date.

As you correctly note, the format for "дата" is DD/MM/YYYY, however the output of the concat function in the display value is in the format  YYYY-MM-DD, not in the one that in the input cell "дата" (DD/MM/YYYY)

Now even one of the values is updated, the issue remains 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/111974217/231422916-eb6cc8fa-3710-4d6e-b5e9-ae439dcf6dc0.png">

Kindly advise

**Comment by wingkwong** [comment]
@ilyak0 I got your point now. Currently `CONCAT` will concatenate the value in the database. However, if a date is referenced in formula, it should use the display format to concatenate. Will work on it. Thanks for reporting.
