### ISSUE TITLE
Support for low-cost serverless NoSQL databases

### ISSUE THREAD

**Issue by achataignier** [nocodb/nocodb#545]
It would be great if NocoDB could support serverless databases such as DynamoDB. Along with ECS/fargate support (already supported), this would reduce the cost of small apps hosting that use NocoDB to almost zero cost.

[NoSQL support ](https://github.com/nocodb/nocodb/issues/184)is first required before being able to support NoSQL serverless DBs such as DynamoDB.

**Comment by o1lab** [comment]
Is there be a difference between MongoDB and DynamoDb ? if they are same - we can close this.

**Comment by achataignier** [comment]
Yes the hosting cost is very different : MongoDB requires servers or instances that incurs significatn costs even when the DB is not much used, while DynamoDB is a serverless DB which costs only based on usage (and has almost zero cost for small DBs)

**Comment by o1lab** [comment]
Now tracked #184

**Comment by KalanaPerera** [comment]
@achataignier Thank you for raising this topic. Appreciate it.

**Comment by mgmonteleone** [comment]
Mongodb also has a serverless option as well as a free tier

**Comment by naqeebrajput** [comment]
can we used nocodb with DynamoDB if yes then how we connect nocodb with DynamoDb?
