### ISSUE TITLE
🐛 Bug: Link feature is not working

### ISSUE THREAD

**Issue by fteklitz-mpg** [nocodb/nocodb#5451]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Testing Link and Lookup features.

I am using your test example: https://docs.nocodb.com/setup-and-usages/lookup

I created and loaded my tables per the enclosed txt document.

When using the Link feature I get the following error message:

Link failed: update "employees" = (select * from (select "teamcode" from "company" where "teamcode" = $1 limit $2) as "__cn_alias") where employee_name" $3 - value too long for type character(1)

See the enclosed screen captures for specifics.

### Desired Behavior

I wish to get the same results as the example case: https://docs.nocodb.com/setup-and-usages/lookup

### Project Details

NocoDB uses docker:
Version: 0.105.3: Bug Fix Release (latest?)
Database: pg
Project was created with "New Project"
OS: WSL on Windows
Node.js - na
PostgreSQL 13.8

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

### Attachments

[NocoDB Tests.txt](https://github.com/nocodb/nocodb/files/11204336/NocoDB.Tests.txt)
![1  Put Penelope in Company List](https://user-images.githubusercontent.com/91699997/231271962-ca808ec8-673d-4001-8439-380b423f82e3.png)
![2  Error when putting Penelope in Company List](https://user-images.githubusercontent.com/91699997/231271963-08e6cfc1-aaa8-4363-935a-4827305f8773.png)
![3  Use Company table to add Penelope](https://user-images.githubusercontent.com/91699997/231271966-91378243-f939-49bb-b6ff-26cd2c0a0d9e.png)
![4  Same error when using Company table to add Penelope](https://user-images.githubusercontent.com/91699997/231271968-b32e0290-7e1d-4a02-b48d-67a5b487bec7.png)

**Comment by wingkwong** [comment]
@fteklitz-mpg The error gives the hint - `value too long for type character(1)` - which means the data type you set is not enough to store the expected value. You may try `varchar`. Also your table should have id column. 

Here's the result I just tested.

![image](https://user-images.githubusercontent.com/35857179/231345206-0f7724f7-bf7d-473f-af2f-fd0f86aff94a.png)

![image](https://user-images.githubusercontent.com/35857179/231345221-34df330c-e8ff-4faa-bd5d-8667383d4eb9.png)

**Comment by fteklitz-mpg** [comment]
I will change the types to varchar and make them longer.  Regarding an id column,  are you talking about added an id using AUTO_INCREMENT?

**Comment by fteklitz-mpg** [comment]
Also for  the error message " value too long for type character(1)"  I don't have any  types character(1).

**Comment by wingkwong** [comment]
> I will change the types to varchar and make them longer. Regarding an id column, are you talking about added an id using AUTO_INCREMENT?

yes

> Also for the error message " value too long for type character(1)" I don't have any types character(1).

I was wondering where it comes from too. Let's see if it can be fixed purely changing the type.

**Comment by fteklitz-mpg** [comment]
Sure,  technology can be mysteriously irritating.

**Comment by fteklitz-mpg** [comment]
Well, changing to varchar fixed the problem (see enclosed)

I have one last question:  I have hundreds of employees per department in our company.  Is there a way to add employees (rows) to a list in bulk?  I would like to create a closed loop system to feed NocoDB and update operational tables from NocoDB.


![1  It worked](https://user-images.githubusercontent.com/91699997/231553709-a5371b4e-6fe1-4611-acb0-db07e8f42eab.png)

**Comment by fteklitz-mpg** [comment]
wingkwong,  thank you for your help.  You have helped me make some really great progress
