### ISSUE TITLE
🐛 Bug: API Where clause not working with 106

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#5456]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

If you make an api call and use isnot null in combination with "DATE" Fields, we get an internal Server error.
( Example: (Id,eq,column2)~and(column1,isnot,null) )

![image](https://user-images.githubusercontent.com/117290601/231401750-a789d924-0542-4793-9371-d7027bf7f2c4.png)

### Desired Behavior

get return value

### Project Details

0.106.0
PG

**Comment by wingkwong** [comment]
@emre1e AFAIK, that combination is not correct. `null` is not a subset of`isnot` for date. In this case, you may use `notblank` instead. E.g.`(date,notblank)`

![image](https://user-images.githubusercontent.com/35857179/231404243-f7f1d03f-ff7f-4443-aba8-8993a1ec5d92.png)

**Comment by emre1e** [comment]
its not working. With notblank im always getting an response, even the date is empty

**Comment by wingkwong** [comment]
@emre1e please DM me in discord (`wkw#3278`)

**Comment by emre1e** [comment]
i dont have discord on my company notebook srry.
![image](https://user-images.githubusercontent.com/117290601/231420596-1822431c-c1f8-4809-8607-40dc79389bce.png)
![image](https://user-images.githubusercontent.com/117290601/231420654-c1d35120-6dce-49ac-93df-f1f207dbe3f7.png)

Here you can see perfectly the results

**Comment by emre1e** [comment]
@wingkwong thank you for your advise the right syntax is:

(date,notblank,)

I dont know why i need to put a comma at the end, but with it it works

**Comment by wingkwong** [comment]
@emre1e Adding a commas can temporarily solve the problem but not the correct fix.  I think I got the root cause. Will keep you posted.
