### ISSUE TITLE
🔦 Feature: We have questions about commercial licensing, can you contact us?

### ISSUE THREAD

**Issue by iQiFengLe** [nocodb/nocodb#5464]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

We want to get a commercial license for this project, what should we do?
Is it possible to provide some development assistance for secondary development after obtaining commercial authorization?
How much does a commercial license cost?
please contact me if possible
E-mail: m.zxt@foxmail.com

This is the content translated by the translation software, and the expression may not be so accurate

### Suggested Solution

no

**Comment by o1lab** [comment]
Pls reach out via this [link](calendly.com/nocodb-meeting)

**Comment by nosorio2** [comment]
Hi @o1lab , the link lead to a 404.

**Comment by o1lab** [comment]
@nosorio2 https://calendly.com/nocodb-meeting
