### ISSUE TITLE
🐛 Bug: can't find swagger.json anymore

### ISSUE THREAD

**Issue by j2l** [nocodb/nocodb#5474]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

/api/v1/db/meta/projects/{projID}/swagger.json doesn't work anymore and link below the title is gone.

### Desired Behavior

/api/v1/db/meta/projects/{projID}/swagger.json

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.106.0**

**Comment by dstala** [comment]
With below configurations running over docker, I could access swagger both via API & UI. Can you provide more details about your issue & log if any?

```
Node: **v16.19.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.106.0**
```

**Comment by j2l** [comment]
Thank you @dstala
Which url do you use?

**Comment by wingkwong** [comment]
Do you mean to access Swagger UI? 

![image](https://user-images.githubusercontent.com/35857179/232033301-8d5870a8-b03b-4950-ab29-371b6e702b4d.png)

**Comment by j2l** [comment]
Nope, I'm speaking about swagger.json:
![Screenshot from 2023-04-14 13-37-44](https://user-images.githubusercontent.com/65325/232033938-6503095c-bc40-48f6-8f87-b6d54e034d73.png)
It was a link to the json file, it's part of swagger.

**Comment by wingkwong** [comment]
Preliminary finding:

- swagger.json url is now protected - currently it can be only fetched from API with xc-auth header.

**Comment by j2l** [comment]
Thanks @wingkwong, indeed it works for me via API.
Could you please tell me where this change was stated and why removing the link?

**Comment by o1lab** [comment]
Pls lookup the issues - one of it was requesting to not expose the schema.

**Comment by j2l** [comment]
OK, I was wondering if there's a changelog or else to recap all changes from version to version.

**Comment by wingkwong** [comment]
@j2l You can find the changelog in each release note. Just FYI. The change was done in this [commit](https://github.com/nocodb/nocodb/commit/675a95b132bf54cd00132334f5f962b5acf09a27#diff-44fa2e58a4c1c60470c3b8d97ad06776af37cebf7b6bb790874836fde2adec60).

**Comment by j2l** [comment]
Thanks @wingkwong 
Please understand that as a user it's just not obvious: 
Release has a line "refactor: ajv validation & swagger" linking to "swagger schema refactoring" in the PR, linking to  "Bug: Error thrown when editing a form". 
Nowhere does it state something like "we removed the swagger.json link, now it's through API only", not even explaining how to access it. Even if you look for swagger.json, I didn't find any specific title in issues.
I know you know what you did  on the code side, but the titles are not explanatory enough for me. :smile_cat:

**Comment by webdiller** [comment]
Also can't find the solution to get swagger.json

**Comment by FrancisVarga** [comment]
Anyhow we can get the json some how?

**Comment by ne7shii** [comment]
@FrancisVarga  you can get json by `/api/v1/db/meta/projects/{projectId}/swagger.json`
with header `ac-token:<your api token>`

**Comment by maticjbalis** [comment]
This worked for me, but with `xc-token` rather than `ac-token`.

**Comment by MrApe** [comment]
Any way to get the v3 version api, as from the interface?

<img width="414" height="404" alt="Image" src="https://github.com/user-attachments/assets/e37b45e2-572e-4095-bb91-a45db4614741" />

**Comment by MrApe** [comment]
> Any way to get the v3 version api, as from the interface?
> 
> <img alt="Image" width="414" height="404" src="https://private-user-images.githubusercontent.com/98466/550878328-e37b45e2-572e-4095-bb91-a45db4614741.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzEzMjIwNzEsIm5iZiI6MTc3MTMyMTc3MSwicGF0aCI6Ii85ODQ2Ni81NTA4NzgzMjgtZTM3YjQ1ZTItNTcyZS00MDk1LWJiOTEtYTQ1ZGI0NjE0NzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE3VDA5NDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNjQyNjUyNjk4MmQ2NzM4YzA2NWQ1ZTE2MDM3MjZkODA3NGZlOWIxZmUxNmJiN2U2ZThmNTNkNTJiOWE4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iCcoVuPeiRZj7qXfhfSh8uNoyn6kwh4xXns-XEStgIE">

Answering myself: `/api/v3/meta/bases/{{baseid}}/swagger.json`

Did I miss it in the documentation or is it missing there?
