### ISSUE TITLE
enhancement: add scrollbar in column list

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#5482]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

there are more than 8 columns in the table - currently the list shows like users can only select these 8. Even thought scrolling down can see other options, to achieve better UX, it is better to have a scrollbar indicating more options can be selected.

![image](https://user-images.githubusercontent.com/35857179/232203337-e27881bc-d253-40ec-bddb-c5f5b0223df1.png)

### Desired Behavior

If there are more columns to show - show a scrollbar to indicate

### Project Details

Node: v16.19.1
Arch: x64
Platform: linux
Docker: true
RootDB: pg
PackageVersion: 0.106.0

**Comment by frankMagoba** [comment]
Can I pick this up?

**Comment by DarkPhoenix2704** [comment]
Instead of current pagination, loading on scroll would be nice

**Comment by wingkwong** [comment]
@frankMagoba any update? 

@DarkPhoenix2704 This issue is about the column list. I think what you said is about data list.

**Comment by wingkwong** [comment]
@frankMagoba Currently the scrollbar shows only when I scroll.

![image](https://user-images.githubusercontent.com/35857179/235873953-286ac9fe-f9fd-409f-b5c0-06e895d7edf0.png)

**Comment by frankMagoba** [comment]
> @frankMagoba Currently the scrollbar shows only when I scroll.
> 
> ![image](https://user-images.githubusercontent.com/35857179/235873953-286ac9fe-f9fd-409f-b5c0-06e895d7edf0.png)

I see, I will add a scrollbar view that is visible to give the user an impression of other columns at first glance, is that alright?

**Comment by wingkwong** [comment]
@frankMagoba Yes. That's correct.
