### ISSUE TITLE
🐛 Bug: Text selected alongside cells

### ISSUE THREAD

**Issue by akoen** [nocodb/nocodb#5484]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Select any group of cells in the table view. Text is selected alongside the cells (undesired).

### Desired Behavior

Text should not be selected. I can fix this locally by adding a css rule:

``` css
* {
  user-select: none !important;
}
```

but this is probably overkill.

### Project Details

Any

### Attachments

![image](https://user-images.githubusercontent.com/43913902/232251432-660d5792-e777-4058-94ec-74f8393dc665.png)

**Comment by wingkwong** [comment]
Adding the above CSS may lead to some unexpected behaviour - e.g. fail to select text in comments
