### ISSUE TITLE
Setting and changing relations performance is dropped in 0.106.0

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#5487]
First things first — huge thanks for great performance improvements made in 0.106.0! Most of my GET API calls run from x1.5 to x4 times faster, and using UI feels way better  : ) 
### Problem
POST requests containing "belong to" foreign key takes x10 more time (in my case from 220ms to 2900ms). PATCH requests slowed even worse. Interestingly enough, setting "belong to" relation in UI by choosing from list works instant, comparing to setting Id in related system field.
> **UPD:** _using bulk POST endpoint with "belong to" foreign key is fast as it was before 0.106.0_ 

Same slowdown happened with "many to many" POST on `/api/v1/db/data/v1/{projectName}/{table}/{rowId}/{relationType}/{columnName}/{refRowId}` endpoint. In my case, request slowed down from 150ms to 2900ms. Adding "many to many" relation from UI feels as slow as from API. 

Above timings came from comparing versions 0.100.2 and 0.106.0. No correlation with adding or removing webhooks noticed.

### CTA 
1) Investigate slowdown and if acceptable — improve performance.
2) Adding or removing relations feels like a bad UX: after choosing new relation or removing existing one nothing happens. Some progress indication should be shown on those user actions.

**Comment by dstala** [comment]
@RawmanGrey tried this over PG database & didn't see any issue with nested record create / update procedures. can you share more details about your setup & logs if any?

**Comment by RawmanGrey** [comment]
@dstala, sorry, I should have tested on fresh DB: problem is in my data, probably created on one of NocoDB updates my instance took. We are sticking around since ~v0.84.16.

Unfortunately, I can't share postgres dump. There is nothing weird in docker logs, except 2400ms+ time to handle mentioned requests and below spoiler's content, which doesn't seem related.

<details> 
<summary>Error complaining on formula (which is working fine). Removing it from table doesn't change a thing.</summary>

### The only formula in table:
IF((NOW() < DATEADD({CreatedAt}, 1, "day")), IF(({Checkbox1} == false), true, IF(({Checkbox2} == true), true, false)), false)


### Error from container's logs:
```
Error: Formula error: select CASE WHEN ([object Promise] OR [object Promise]) THEN TRUE ELSE FALSE END  as "__dry_run_alias" from "nc_xcf___journal" - syntax error at or near "["
    at t.default (/usr/src/app/docker/main.js:1:204366)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.t.columnUpdate (/usr/src/app/docker/main.js:1:1761185)
    at async u (/usr/src/app/docker/main.js:1:1970137)
    at async /usr/src/app/docker/main.js:1:14818
error: select CASE WHEN ([object Promise] OR [object Promise] OR [object Promise]) THEN TRUE ELSE FALSE END  as "__dry_run_alias" from "nc_xcf___journal" - syntax error at or near "["
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 90,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '19',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror'
}
```
</details>

I think, issue will be fixed by recreating my project from scratch, but without control over Id counter ( #5243 ), restoring relations isn't easy task. Therefore, I'll try to dig deeper and report if any progress. Any suggestions what can be helpful?


Btw, current project info:
Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.106.0**

**Comment by wingkwong** [comment]
@RawmanGrey I've fixed this formula issue 3 days ago and it hasn't been released yet. Can you try it with the following image?

 ```
nocodb/nocodb-daily:0.106.0-20230417-1203
```

**Comment by RawmanGrey** [comment]
@wingkwong, confirming — no more errors in container's logs with `nocodb/nocodb-daily:0.106.0-20230417-1203` image. Unfortunately, no effect on my troubling requests' timings.

**Comment by dstala** [comment]
@RawmanGrey Do you still notice these issues with v0.111.0?

**Comment by RawmanGrey** [comment]
> @RawmanGrey Do you still notice these issues with v0.111.0?

Unfortunately I can't upgrade: there are breaking changes forcing me to invest more time that I can afford. Apologies, I can't help with test soon.

**Comment by dstala** [comment]
@RawmanGrey closing this thread for now. if you have upgraded to v0.202.4+ & still facing issue, let us know.
