### ISSUE TITLE
🐛 Bug: Populating select values via the API doesn't fully work

### ISSUE THREAD

**Issue by arladmin** [nocodb/nocodb#5492]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a new table
2. Create a Single select field, Test
3. Do not add any options to Test
4. Add data to the table via the REST API
5. Refresh the table UI
6. All fields other than Test will appear populated
If you click on Test, then the data written will be visible
If you read the Test data via the API, it will be included
But, in the UI, it will show as blank. Also, if you edit the field Test, no Options are present, indicating that the API call did not add the incoming data as an option to the field!

### Desired Behavior

The incoming data should automatically populate wherever is required, so that, the data is available via the UI and API.

### Project Details

Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.106.0**

**Comment by dstala** [comment]
Proposal for such instances
- default behaviour: return error "undefined option"; data pertaining to rest of the columns is also not inserted
- introduce a new query parameter "bestEffort"; default false; when set to true, options not defined will be defined before attempting to insert the record on to the table

**Comment by dstala** [comment]
return error "undefined option"; we shouldn't insert data to rest of the fields as well

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/7070

**Comment by Kiss-World** [comment]
> Proposal for such instances
>
> * default behaviour: return error "undefined option"; data pertaining to rest of the columns is also not inserted
> * introduce a new query parameter "bestEffort"; default false; when set to true, options not defined will be defined before attempting to insert the record on to the table

How to set Besteffort, I set it in the header, and I did not take effect
