### ISSUE TITLE
🐛 Bug: API filtering a date field as "is not null" gets a 500

### ISSUE THREAD

**Issue by FerLSanchez** [nocodb/nocodb#5507]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Table with a date field, let's call it Date
2. Go to swagger and test the Get, adding in the "where": (Date,isnot,null)
3. You receive a 500, and in the server log you can find a "[Error]: 'null' is not supported."

### Desired Behavior

It returns all the registers with a not null Date, or an empty list if no register matches the condition.

It used to work some version ago, I have a project using it that stop working :(

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.106.1**

**Comment by wingkwong** [comment]
@FerLSanchez `null` has been deprecated in Date filter. Now you should use `(date,notblank)`.

**Comment by FerLSanchez** [comment]
Oh, my fault then! So sorry!
I tried (date,isnot,blank) but not that!
Thank you!

**Comment by dav1app** [comment]
https://docs.nocodb.com/developer-resources/rest-apis#comparison-operators

The example on the doc refers only to (..., isnot, null)

**Comment by shixiaobao17145** [comment]
> @FerLSanchez `null` has been deprecated in Date filters. Now you should use the following
> 
> * `(date,isnot,null)` -> `(date,notblank)`.
> * `(date,is,null)` -> `(date,blank)`.

This should be claimed in doc which I have not yet find in any places in the docs.

**Comment by onejgordon** [comment]
Filtering text fields using `(str_col,notnull)` and `(date_col,notblank)` appear to both work to ignore empty values as of today, but neither appears in the [REST API documentation](https://docs.nocodb.com/developer-resources/rest-apis/#query-params).

Would you accept a PR for this doc fix?

**Comment by BenitezDev** [comment]
Has the documentation been updated anywhere? I still can't see the documentation for these changes

**Comment by EverGrowthLeaders** [comment]
(FECHA REGISTRO,eq,2024-04-22) gives me error: '2024-04-22' is not supported.

**Comment by NeuroWhAI** [comment]
Any update? It's amazing that we don't have documents for this.

**Comment by yunyu950908** [comment]
> (FECHA REGISTRO,eq,2024-04-22) gives me error: '2024-04-22' is not supported.

Any solutions? I‘ve meet the same problem
