### ISSUE TITLE
🐛 Bug: Labeling columns with special characters causes form to break

### ISSUE THREAD

**Issue by alexiskattan** [nocodb/nocodb#5523]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a sheet
2. Label column "?@% ++ ()"
3. Create form
4. Submit form
5. Get error the "column on the sheet does not exist" or "sql query error"

### Desired Behavior

Columns should be able to have special characters.  Or if columns shouldn't for technical reasons it should throw an error preventing the user from naming them in this way.

### Project Details

Node: **v18.14.1**
Arch: **x64**
Platform: **win32**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

**Comment by nikumbgo12345** [comment]
could you please assign this to me

**Comment by wingkwong** [comment]
@nikumbgo12345 assigned. please brief your solution with the team once in discord before your implementation.

**Comment by dstala** [comment]
works in v0.202.5 when tried with PG as RootDB. if issue persists, please re-open this thread.

@alexiskattan
