### ISSUE TITLE
🐛 Bug: import csv data : you mixed columns and rows

### ISSUE THREAD

**Issue by Productivix** [nocodb/nocodb#5529]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

create a table or "articles" by importing the csv joined
you will be blocked at 1st step and mention that the import program takes csv lines for columns and reverse : it is obvious on screen shot attached !
![Capture d’écran_error_column_line](https://user-images.githubusercontent.com/6737060/233959501-57572c2b-a349-44bb-987f-4c528448c020.png)

### Desired Behavior

have a normal import : see objective (reached with other nocode program)
![Capture d’écran_objective_import -csv](https://user-images.githubusercontent.com/6737060/233960064-9fe1a12d-b0f0-4273-ab53-10f7a0503f63.png)

### Project Details
[modele_articles.csv](https://github.com/nocodb/nocodb/files/11309081/modele_articles.csv)

NocoDb used on nococloud.dev - but in V99.2

**Comment by wingkwong** [comment]
From the csv you provided, I don't see there is header shown in the second screenshot. You may provide the header in the csv or edit in the UI.

**Comment by Productivix** [comment]
the csv has just been updated but still without header, same behaviour

**Comment by Productivix** [comment]
[modele_articles_headers.csv](https://github.com/nocodb/nocodb/files/11309152/modele_articles_headers.csv)
same (bad) behaviour with headers (model joined)

**Comment by dstala** [comment]
NocoDB Discord - what's error? If you have not verified yourself - please do that. 
<img width="1218" alt="Screenshot 2023-04-25 at 10 32 55 AM" src="https://user-images.githubusercontent.com/86527202/234178919-4768b5c5-a454-45a9-99bb-de880dc53afa.png">

**Comment by Productivix** [comment]
thanks - i did it day before , not it works - thanks for your help
