### ISSUE TITLE
NocoDB is adding "ISN" infront of my table names

### ISSUE THREAD

**Issue by Soneji** [nocodb/nocodb#554]
NocoDB is adding "ISN" infront of my table names that start with numbers

**Please enter the following details**

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.11.33**

**Steps To Reproduce**
1. make a mysql database and add a new table called something like "2020 test"
2. Setup a nocodb with mysql backend
3. nocodb will rename the table to "ISN2020 test" 

**Expected behavior**
no renaming

**Comment by o1lab** [comment]
Could you please double check - I tried and I am not seeing the issue

While creating table, there are two input fields - one is the alias and another is table name. Guess ISN was entered within 2nd input ?

**Comment by pranavxc** [comment]
If the table name starts with number then we are adding `ISN` prefix

**Comment by o1lab** [comment]
Ah I missed the name with a number. Yes we do that to manage the internal naming of APIs

However, the option to keep the numbered table should be possible - cause we do provide the option to specify actual tablename in the database.

**Comment by Soneji** [comment]
Sorry I'm not entirely sure what you mean by this... how exactly do I keep the original name?
