### ISSUE TITLE
🐛 Bug: unable to download table data ((t || []).map is not a function)

### ISSUE THREAD

**Issue by ilyak0** [nocodb/nocodb#5552]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Any download results in the same error 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/111974217/234894198-4658d7e5-c4e5-4f5b-87fe-479d42d454d3.png">

<img width="204" alt="image" src="https://user-images.githubusercontent.com/111974217/234894252-fd5f5f27-6a7f-4a52-9ef9-34c2e9cb5872.png">

### Desired Behavior

Need to get the file downloaded

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.106.1**

**Comment by wingkwong** [comment]
I'm not able to reproduce the issue. Can you show the schema?

**Comment by ilyak0** [comment]
Just opening the first table and trying to download the files... Nothing special
Other tables in the base are easily downloaded, only the first one causes this issue

<img width="646" alt="image" src="https://user-images.githubusercontent.com/111974217/236164604-8b338237-9e0d-490e-8de6-d1ef117e8191.png">

**Comment by wingkwong** [comment]
Can you share the list of column types you have in that table? Also are you downloading as CSV or XLSX or both failed?

**Comment by ilyak0** [comment]
Both fail

<img width="316" alt="image" src="https://user-images.githubusercontent.com/111974217/236196991-bed2a67f-3546-4eff-b538-f9c51757926e.png">
<img width="343" alt="image" src="https://user-images.githubusercontent.com/111974217/236197079-8655877a-31e7-4011-9a4d-641d315189c1.png">
<img width="297" alt="image" src="https://user-images.githubusercontent.com/111974217/236197126-23603c3c-d78b-4c2b-b1bc-2d686481d1f7.png">
<img width="323" alt="image" src="https://user-images.githubusercontent.com/111974217/236197167-e8a32c11-90b6-48ae-afb5-9220ac6163d8.png">

**Comment by wingkwong** [comment]
do other tables (except the first one) contain attachment fields?

**Comment by ilyak0** [comment]
Some of them do. And those tables could be downloaded.

пт, 5 мая 2023 г. в 10:12, աɨռɢӄաօռɢ ***@***.***>:

**Comment by ilyak0** [comment]
@wingkwong any news on that please?

**Comment by wingkwong** [comment]
@ilyak0 I still couldn't reproduce the issue.

**Comment by ilyak0** [comment]
Maybe I can provide you with some additional data that may help? It's our
main student database and not being able to export it makes life very
tough...

чт, 18 мая 2023 г. в 10:21, աɨռɢӄաօռɢ ***@***.***>:

**Comment by ilyak0** [comment]
Here's the docker log for example, however may be not too informative.. https://pastebin.com/wQ9vU18k

**Comment by abovesky** [comment]
I have also encountered this problem, and no matter what fields are included in the first table, the download will fail.

**Comment by shashankvish** [comment]
I'm not able to reproduce the issue, as you mentioned that the first table fails to download. I'm able to download it even checked by adding attachment fields, but if you are still facing the issue please provide some more information on it.

**Comment by ilyak0** [comment]
@shashankvish thanks for looking into it. What kind of info may help you pls?

**Comment by wingkwong** [comment]
@ilyak0 Sorry for the wait. So far it's hard to debug given that I don't have a reproducible environment. I guess the error may be thrown from papaparse and your attachment value format got messed up. Can you try the following?

1. Disable all attachment fields, are you able to export the table?
2. Enable all attachment fields back (i.e. undo above step), Create a formula referencing on one of the attachments, check if there is a difference between new records and old records. Copy the value and send to me via [Discord](https://discordapp.com/users/495466997304262658). I wanna verify the attachment value structure.

**Comment by dstala** [comment]
@ilyak0 please try our latest release v0.202.5; if issue still persists, please reopen this thread.

**Comment by rossmills99** [comment]
I can confirm I see the same issue on v0.202.5,

The table in question has a lookup field, which itself is an attachment.  If I hide that column (deselect it in the Fields dropdown), then I am able to download the data.

**Comment by Juvls** [comment]
@dstala Hi, I still have the same issue on 0.207.3. Can this issue be re-open or should I open a new bug? Thanks.

**Comment by o1lab** [comment]
Please open a new bug
