### ISSUE TITLE
🐛 Bug: Cannot retrieve data from tables for how queries are formed

### ISSUE THREAD

**Issue by kevinmamaqi** [nocodb/nocodb#5562]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Add pg provider
2. The pg database uses a different schema and database name than public/postgres.
3. Import adding the URL and making sure that pg JSON connection has proper search path
4. Connection satisfactory
5. Import tables
6. Go to view any of the imported tables
7. No data on the tables and the following error:

```
2023-04-29 09:56:59.138 UTC [507] ERROR:  relation "location" does not exist at character 209
2023-04-29 09:56:59.138 UTC [507] STATEMENT:  select "location"."id" as "Id", "location"."name" as "Name", "location"."local_name" as "LocalName", "location"."slug" as "Slug", "location"."level_id" as "LevelId", "location"."parent_id" as "ParentId" from "location" order by "created_at" asc limit 25
```

### Desired Behavior

It should retrieve the data within the tables that was already able to introspect, because columns and structure/type are well defined in the UI.

### Project Details

Node: **v16.19.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.106.1**

### Attachments

<img width="683" alt="Screenshot 2023-04-29 at 18 42 07 1" src="https://user-images.githubusercontent.com/972664/235313941-8ced3392-168e-4cfb-b12e-c9976bf109a1.png">

**Comment by dstala** [comment]
@kevinmamaqi it would be of great help if you could let us know if issue persists in release v0.202.5

**Comment by dstala** [comment]
@kevinmamaqi reopen this issue if you still see it in v0.202.5
You can reach to us over discord or at community.nocodb.com as well.
