### ISSUE TITLE
🐛 Bug: model list cache ignores base_id

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#5568]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Model.list function caches based on project_id,
so when we call list tables api for base when cache enabled it always results with all the available bases in project.

### Desired Behavior

Base list tables api should only return models belonging to that base.

Opening this to discuss how to approach that issue, as storing models based on project_id might be more efficient if so we might filter cached response before returning.

### Project Details

develop

**Comment by wingkwong** [comment]
We can include `base_id` in most cases. However, how do we deal with `xcVisibilityMetaGet` and `swaggerJson` where `base_id` is null?

**Comment by wingkwong** [comment]
> We can include `base_id` in most cases. However, how do we deal with `xcVisibilityMetaGet` and `swaggerJson` where `base_id` is null?

After checking the code, those parts are fine since we've removed null value in cache key.
