### ISSUE TITLE
[Feature] Version Control on Rows

### ISSUE THREAD

**Issue by ServiceDog** [nocodb/nocodb#5589]
NocoDB has a straightforward interface allowing parent/child linking and simple API interaction, so we've been using it to track requirements (label, primary text, expected release, last test result,etc.). We chose it so we could programmatically update rows with the results from integration tests.

To this end, the primary feature we would benefit from is modification history (commit hash, who modified, what was changed) per row. At the moment our plan is to snapshot the entire database at the end of every release, but we obviously miss out on who changed what and why.

Potentially out of NocoDB's scope, thought I'd ask or get some guidance to open-source alternatives.

**Comment by o1lab** [comment]
https://docs.nocodb.com/setup-and-usages/expanded-form/#activity-feed
