### ISSUE TITLE
🔦 Feature: Include lookup fields in webhook body

### ISSUE THREAD

**Issue by thesauravmitra** [nocodb/nocodb#5600]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

All columns of a record, including lookup fields, should be available through a webhook, otherwise critical data is missing.

### Suggested Solution

In the webhook body (both v1 and v2), include lookup fields and ideally, include LTAR columns with their display values.
Speed isn't very critical in webhooks so any increase in time taken while grabbing these fields shouldn't matter.

**Comment by wingkwong** [comment]
Can you provide the project info? I can see lookup & LTAR columns with values in the webhook body. (latest version)

![image](https://user-images.githubusercontent.com/35857179/236438060-95adba15-a6d6-4918-8356-46deec4c2299.png)

**Comment by thesauravmitra** [comment]
```
Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.106.1**
```
I was pretty sure I'm on the latest version available for the nocodb/nocodb Docker image

**Comment by wingkwong** [comment]
Can you show us an example? Like your table schema and what you get in webhook body.

**Comment by dstala** [comment]
reopen this issue if issue still persists with latest release (v0.202.5)
