### ISSUE TITLE
Feature: Field Display Order in New Record Modals for Relation Fields

### ISSUE THREAD

**Issue by athshean** [nocodb/nocodb#5603]
I was trying to create a new record in a table that had related entries in other tables. When I got to the relation field, selected 'Add New Record'.

The order in which the fields were presented in the Add New Record modal were in the order in which the columns were first created on the table. Is there a way to reorder this? Or alternatively, is there a way to link the New Entry modal to an existing form view for the table?

I'd like to be able to change the order in which these fields are displayed so things like Forename is right after Surname in the screenshot. And all lists of relations from other tables are hidden.

![Screenshot from 2023-05-06 11-16-06](https://user-images.githubusercontent.com/107076468/236618634-c7613b2a-175c-4c50-8934-84a7a7dbf0d5.png)

So far the only workaround I have is to create a new table entirely where I define the columns in order, but it gets messy when columns from other table relations get added.

So far the table is an SQLite table (as I'm still just testing). I don't know if it's possible to do this in a MySQL database under the hood later. Not sure if that would affect this.

**Comment by reenphygeorge** [comment]
Can I work on this issue @dstala  ?

**Comment by dstala** [comment]
@reenphygeorge How do you propose to solve this? can you add a brief note here?

**Comment by reenphygeorge** [comment]
I was planning to make the fields in the modal "draggable". After re-ordering the fields, the new order of fields will be stored along with the project data. This could save more time as re-ordering the fields in a database is not practical (creating new table with fields in the new order and copying old data). Now every time the fields will be rendered in the updated order. Initially the order of fields will be the same as that in the database.

**Comment by dstala** [comment]
@athshean the order of fields displayed in expanded form can be controlled by re-ordering fields in associated table. hope that helps. maintaining an explicit order otherwise will be cumbersome. 

To re-order fields in a table, use drag drop icon from `fields` menu in the toolbar of that table

**Comment by andrewkrain** [comment]
@dstala the order of fields in the table is enforced on the New Record from if called from within said table (which is what you are referring to and it makes perfect sense), but not when its called from within another related table via a relationship field (which is what OP is referring to and i'm struggling with as well). can you please reopen this issue? 

cc @athshean @reenphygeorge

**Comment by andrewkrain** [comment]
@dstala - have you seen my comment above?

cc @athshean @reenphygeorge

**Comment by ulut0002** [comment]
I’m encountering similar issue with my current “Blog” structure. I designed it with "Header-Line" structure. Each line has its own custom properties, but there’s no drag-and-drop functionality for reordering them on the header object.

This means users have to enter the lines carefully, and adding something in the middle requires them to re-enter relationships. While this is manageable, it’s not ideal from a UX perspective.

To address this, I’ve added an “Order” field for each “Line” object. Now, users either need to manually adjust the Order No. or re-enter the lines on the header and re-link the records.
