### ISSUE TITLE
Issue: Shared base UX & permissions

### ISSUE THREAD

**Issue by compasssites** [nocodb/nocodb#5630]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I wish to share a base in editor mode via a link. This is being shared to people who are spreadhseet users and dont know what bases/RDBS are. 

When i share the link and open in a new tab, the first tab that opens is the "Team and Auth" tab and followed by an error "userList - editor : Not allowed'. IMHO, both are not required. It will confuse and scare the user who might not understand how to navigate further to the tables or views. 

### Desired Behavior

The first or the main or the default table should be displayed first. "Team and Auth" should not be the first table to be displayed at all or atleast not the first/default one. 

Also, there are other buttons or features which are not allowed (for that role), and they can be hidden and make the interface clutter free. Else, they click and get error. Why show them if they dont have permissions or access?

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.106.1**

**Comment by compasssites** [comment]
Even on non shared bases, one opened by owner, why should the Team and Auth be the default open table? One opens a base to work on data first on most of the ocassions and sometimes to chages users and stuff.

**Comment by dstala** [comment]
@compasssites 
I believe, you had opened shared base link as a new tab on same browser. In such cases, you will notice `team & auth` tab as there is already an active session on this browser with appropriate credentials logged in

Try opening this link in incognito mode (OR) in a new system, you will see following screen
![Screenshot 2023-05-15 at 11 48 05 AM](https://github.com/nocodb/nocodb/assets/86527202/dad0d3de-dc25-4bbd-b855-73b32f3e3c60)

After you access link in this way - for additional buttons (or options) that you think should not be available in `Editor` mode, let us know. Will check it further.

**Comment by compasssites** [comment]
Wow, this makes sense. Thanks. Its way cleaner when opened in new Pirvate window. Am sure, when shared with others, it gets intuitive now. 

The other buttons also dissapear magically. Except on the left bottom side APIs and Support and Join NocoDB cloud. The former can be hidden as might not be useful for average user with shared base. The latter is upto you for branding. Or a simple powered by should be enough. Or option to remove like in Wordpress. 

Thanks.
