### ISSUE TITLE
🐛 Bug: Filter dropdown for select fields disabled

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5632]
Reported by discord user
https://discord.com/channels/661905455894888490/661905455894888493/1107384212912341102

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Shared view, unable to filter records on select options

![Screenshot 2023-05-15 at 12 11 56 PM](https://github.com/nocodb/nocodb/assets/86527202/be22e728-3c0f-47da-84c9-f65d085cf31a)

### Desired Behavior

filter using select fields

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.107.0-beta.1**

**Comment by tecwat** [comment]
Thanks a lot ! 🙂 As it seems that this issue could affect many users using shared views, could it be solved in the next release (0.107.0) ? Which version is advised for a production deployment today ? Thanks a lot for your answers.
