### ISSUE TITLE
🔦 Enhancement: Formula functions prefer to be case-insensitive

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5640]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

<img width="725" alt="Screenshot 2023-05-16 at 9 39 47 AM" src="https://github.com/nocodb/nocodb/assets/86527202/c6492c32-7880-41ce-84e3-2e86b1bc8e57">

### Suggested Solution

SaaS in similar space provide case-insensitive options. Generate better error otherwise if we prefer to stick to all caps. 

### Additional Context

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.107.0-beta.1**

**Comment by frankMagoba** [comment]
Can I pick this up?

**Comment by wingkwong** [comment]
@frankMagoba please look at those unassigned issues instead.
