### ISSUE TITLE
When I modified the column names in nocodb after connecting to the database, the field names in the database also changed. How can I avoid this situation and how should I make modifications?

### ISSUE THREAD

**Issue by shiliu2023** [nocodb/nocodb#5646]
When I modified the column names in nocodb after connecting to the database, the field names in the database also changed. How can I avoid this situation and how should I make modifications?

**Comment by dstala** [comment]
This is intended by design- as many of users connecting to external DB are using NocoDB to work & manage external database. We do not support column alias currently. Any specific reason for you to do it otherwise?
