### ISSUE TITLE
🔦 Feature: Translation: "User acount Settings" pages  and "Data types" are translated in json file, but the newest release still keep untraslated

### ISSUE THREAD

**Issue by yangf73** [nocodb/nocodb#5655]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

~~1, In latest release, "Full User acount Settings" pages are not tranlated. but Crodin translation page shows these phrases are already translated~~

2, columnTypes, such as "SingleLine Text", are NOT translate.  but Crodin translation page shows these phrases are already translated

### Suggested Solution

Translate these phrases in next release.

**Comment by wingkwong** [comment]
For the first point, if the translation is available in Crowdin but not displaying in app, then it means we haven't applied i18n for those texts. Any PR is welcome.

For the second point, someone made a PR and it is being reviewed at this moment.

**Comment by frankMagoba** [comment]
can i pick this up?

**Comment by wingkwong** [comment]
@frankMagoba assigned. this one should be easy.
