### ISSUE TITLE
🔦 Feature:  Exiting columns conert to  SingleSelect/MultiSelect should autoconvert existing data to select options

### ISSUE THREAD

**Issue by yangf73** [nocodb/nocodb#5656]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In some cases, tables are upload from a xlsx file. datatypes are SingleLineText. when I convert an exiting column to   SingleSelect/MultiSelect, datas are missing. So I have to set options manuly and rebuild the datas.

### Suggested Solution

When convert a column from text to select, should auto add option from existing datas and convert text datas to select options.

**Comment by dstala** [comment]
@yangf73 this is now supported in v0.202.5 release. not that, text with comma's are not allowed as select options.
