### ISSUE TITLE
🔦 Feature: Is the backend source code of the nocodb project open source now? How can I obtain the backend source code

### ISSUE THREAD

**Issue by laochaoxiaochao** [nocodb/nocodb#5668]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Is the backend source code of the nocodb project open source now? How can I obtain the backend source code

### Suggested Solution

Is the backend source code of the nocodb project open source now? How can I obtain the backend source code

### Additional Context

Is the backend source code of the nocodb project open source now? How can I obtain the backend source code

**Comment by o1lab** [comment]
Its always available [here](https://github.com/nocodb/nocodb/tree/develop/packages/nocodb).

**Comment by laochaoxiaochao** [comment]
Which directory is the backend source code located in the nocodb code？




老超小超
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nocodb/nocodb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月19日(星期五) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nocodb/nocodb] 🔦 Feature: Is the backend source code of the nocodb project open source now? How can I obtain the backend source code (Issue #5668)





 
Its always available here.

**Comment by wingkwong** [comment]
@laochaoxiaochao 后端代码在 `packages/nocodb/` 或者你可以点击上面那个链接

**Comment by laochaoxiaochao** [comment]
在nocodb的表新增和编辑列的时候，是否能加自定义属性呢


老超小超
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nocodb/nocodb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月19日(星期五) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nocodb/nocodb] 🔦 Feature: Is the backend source code of the nocodb project open source now? How can I obtain the backend source code (Issue #5668)





 
@laochaoxiaochao 后端代码在 packages/nocodb/ 或者你可以点击上面那个链接

**Comment by laochaoxiaochao** [comment]
Can custom attributes be added when adding and editing columns in the nocodb table?




老超小超
***@***.***



&nbsp;

**Comment by wingkwong** [comment]
@laochaoxiaochao 目前仍不支持自定义属性

**Comment by laochaoxiaochao** [comment]
docker 部署nocodb的默认数据库连接是哪个地址呢


docker 部署nocodb的默认数据库连接是哪个地址呢

老超小超
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nocodb/nocodb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月22日(星期一) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nocodb/nocodb] 🔦 Feature: Is the backend source code of the nocodb project open source now? How can I obtain the backend source code (Issue #5668)





 
@laochaoxiaochao 目前仍不支持自定义属性

**Comment by wingkwong** [comment]
@laochaoxiaochao 如果你没有配置 `NC_DB` 那么默认数据库将使用 sqlite (`/usr/app/data/`)

https://github.com/nocodb/nocodb/blob/develop/markdown/readme/languages/chinese.md#docker-%E9%83%A8%E7%BD%B2
