### ISSUE TITLE
Feature request: Json editor in fullscreen

### ISSUE THREAD

**Issue by MiroslavMikus** [nocodb/nocodb#570]
Hey, 

I was checking this awesome app in my docker environment, and it's just impressive :relaxed:

I'm not sure if there is already some feature like this:

I would like to edit long text and JSON text in full screen or some pop-up.

![image](https://user-images.githubusercontent.com/29312172/134696184-e714f8ac-1e2c-47dd-bc66-567fc8a42d1a.png)

Right now the `monaco` editing experience is somehow ruined by the cringing editor dimensions :flushed:

I suggest to add the expand icon somewhere near to these fields:

In the table view:
![image](https://user-images.githubusercontent.com/29312172/134697367-9dfce9dc-4fda-4f31-915c-75da7626e0c4.png)

and in the detail view as well:
![image](https://user-images.githubusercontent.com/29312172/134697500-4fa3d4a5-23a4-4fe8-8a89-84ae24f030e6.png)

Thanks upfront

**Comment by pranavxc** [comment]
Added expand icon in `0.11.41`
