### ISSUE TITLE
🐛 Bug: Metadata not in sync and breaking most of the features

### ISSUE THREAD

**Issue by Sov3rain** [nocodb/nocodb#5701]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Spin up an instance of Noco with a separate PostgresQL database for metadata.
2. Create another PostgresQL database to save your real data.
3. Add your "data" database to any project.
4. Start populating your database (create multiple tables, relations, etc). For this example, we have two tables
  - Organization (with a relation to many Products)
  - Product (with a relation to one Organization) 
5. Go to the "Team and Settings" menu, then "Data sources", check out the sync button: you metadata db is out of sync. Click the "sync metadata" button, you'll see on each of your table, under the "sync state" the message "Table removed".
6. Click on "sync now". An error message appears stating "The referenced row does not exist".
7. Return to the main interface.
8. Everything is broken at this point. It is missing some tables or all of them. I can't add rows, can't change filters. 

### Desired Behavior

Well, I don't know where to start. At this point I can't use this product as a whole, because every time I add a separate data source, metadata DB goes out of sync and it breaks everything.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.107.2**

Deployed on Railway.app

### Attachments

![image](https://github.com/nocodb/nocodb/assets/10755450/36418bf6-c454-4b0f-ad0f-eef0e56f3694)
![image](https://github.com/nocodb/nocodb/assets/10755450/b0abce3a-35bb-41cc-ba57-617f6f208ffe)
![image](https://github.com/nocodb/nocodb/assets/10755450/cbd03bc1-daca-4d66-8718-d0b5f7c99d6e)

**Comment by Sov3rain** [comment]
After some digging, it may be related to #4442, after a redeploy, I'm in sync with the metadata db but I'm out of sync on the data db, which gives me errors on relations:
![image](https://github.com/nocodb/nocodb/assets/10755450/2c8c3650-676d-4e79-abe7-0d570c83d048)

**Comment by o1lab** [comment]
To summarise the problem metadata db is showing 'Out of sync' when any change is made to data db. This needs to be corrected. @mertmit @pranavxc

**Comment by Sov3rain** [comment]
Well, in the meantime, do you advise not using the sync feature? Because right now, clicking the "sync now" button is breaking everything.

**Comment by wingkwong** [comment]
@Sov3rain It seems the root cause comes from cache part. At the same time, you may try disable the cache by setting `NC_DISABLE_CACHE=true`.

**Comment by o1lab** [comment]
`NC_DISABLE_CACHE=true` is only a workaround and it may slow down your queries. We will have a fix soon for this.

**Comment by Sov3rain** [comment]
> @Sov3rain It seems the root cause comes from cache part. At the same time, you may try disable the cache by setting `NC_DISABLE_CACHE=true`.

Thanks for the workaround, at least desync is gone now. Looking forward for the fix 🤞. Let me know if you need anything else.
