### ISSUE TITLE
Currency fields always displayed with $

### ISSUE THREAD

**Issue by bannmann** [nocodb/nocodb#572]
I created a currency field with "Type in database" set to `money`. I use PostgreSQL.

In my table, I want to work with prices in Euro (€), but the values I enter are always displayed as US Dollar ($).

Could you please have NocoDB allow selection of the currency to be used? This should be selectable for each column (or at least on project level) as I imagine it's not useful to simply rely on global settings such as the server system locale or database locale.

**Comment by nil0x42** [comment]
I need this too !

**Comment by mertmit** [comment]
@bannmann @nil0x42 I am happy to announce we have revised the currency column to support different locales and currency codes. I hope our new implementation in develop branch cover your needs. Feel free to update the issue if anything missing for you.
![image](https://user-images.githubusercontent.com/59797957/170151515-7d0ff620-d1d2-44d3-a7e8-62947d4fcc15.png)

**Comment by mertmit** [comment]
Confirmed this is a problem with 'money' type from postgreSQL I've created an issue you can follow updates from there https://github.com/nocodb/nocodb/issues/2255
