### ISSUE TITLE
🔦 Feature: Confirmation request and default settings in the view sharing form

### ISSUE THREAD

**Issue by tecwat** [nocodb/nocodb#5725]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When you click on the "share view" button:
- The view is shared without confirmation request
- The view is shared by default without password
- The view is downloadable  by default

This default setting could be a problem regarding data privacy. Indeed, users do not realize that they have shared a view since there is no confirmation request. Moreover, the data would then be downloadable without password if you have the link.

### Suggested Solution

The following behaviour would improve data privacy :
	1) Show a confirmation request popup before the view sharing is effective
	2) By default a password should be requested (the password checkbox should be activated by default)
	3) The view should not be downloadable by default (the "download enabled" checkbox should be unchecked by default)

**Comment by dstala** [comment]
@tecwat 
New UI handles this better by having a button to toggle with a clear message `Enable public viewing`
We would like to continue to keep `restrict access with password` disabled by default & `allow download` enabled by default as these are the standard options used by most of our users. 

![Screenshot 2023-10-27 at 8 08 39 PM](https://github.com/nocodb/nocodb/assets/86527202/4ef63475-4bb7-4e7a-897f-7bb32813a1bd)
