### ISSUE TITLE
🐛 Bug: Filter modal not displaying applied filter content

### ISSUE THREAD

**Issue by Sov3rain** [nocodb/nocodb#5738]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Add a filter on a table
- Apply that filter and quit the modal
- Re-open the modal, the field where you entered your filter string is missing

I added a log file of the error and a screenshot.

### Desired Behavior

We should be able to see the content of the filter, just to check it out or to change it.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.107.4**
Infra: **cloud (Railway.app)**

### Attachments

[1685025389773.log](https://github.com/nocodb/nocodb/files/11566157/1685025389773.log)
![Screenshot_1](https://github.com/nocodb/nocodb/assets/10755450/8c490350-c706-4b2a-99c5-f6877d35119c)

**Comment by dstala** [comment]
@Sov3rain 
If issue is reproducible with release v0.202.5, please reopen this thread.
