### ISSUE TITLE
🐛 Bug: Uncaught ReferenceError: SwaggerUIBundle is not defined

### ISSUE THREAD

**Issue by dav1app** [nocodb/nocodb#5739]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Update to the latest version 
- Go to Swagger Rest APIs
- Nothing displays on screen, just a blank screen with "we are hiring" banner.

### Desired Behavior

- Open REST APIs

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.107.3**

### Attachments

```
Uncaught ReferenceError: SwaggerUIBundle is not defined
    at xmlhttp.onload (swagger:28:14)
xmlhttp.onload @ swagger:28
load (async)
(anonymous) @ swagger:26
```
```
GET [my endpoint]/css/swagger-ui-bundle.4.5.2.min.css net::ERR_ABORTED 404
GET [my endpoint]/js/swagger-ui-bundle.4.5.2.min.js net::ERR_ABORTED 404
```
```
{"msg":"Cannot GET /css/swagger-ui-bundle.4.5.2.min.css"}
```

**Comment by wingkwong** [comment]
@dav1app we fixed this issue yesterday and it is available in `0.107.4`. Please upgrade it. Feel free to reopen if it is not working.
