### ISSUE TITLE
🐛 Bug: Form view not rendering available options

### ISSUE THREAD

**Issue by pradeepdhankhar** [nocodb/nocodb#5740]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Created table A has one-to-many relation with Table B
2. Created add record form for table B 
3. In the relation field options are not visible although I have the data in Table A.
4. 

### Desired Behavior

Option from relation should be visible.

### Project Details

Node: **v19.8.1**
Arch: **x64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.107.0**

### Attachments

![Screenshot-20230526020033](https://github.com/nocodb/nocodb/assets/4024774/5d5ad8f7-c780-4b5a-8fda-51c74e1aa23b)

**Comment by wingkwong** [comment]
@pradeepdhankhar This issue has been resolved in #5697. Please upgrade to the latest version. Feel free to reopen if issue persists.
