### ISSUE TITLE
Can I still register an account in the code sandbox environment?

### ISSUE THREAD

**Issue by jinhaoxu** [nocodb/nocodb#5744]
Hi, there. I wanted to have a quick look for NocoDB, so I tried to register an account in the code sandbox to experience the demo, but it said "Not allowed to signup, contact super admin.". 

Any help will be appreciated. thx

**Comment by dstala** [comment]
You can now try NocoDB quickly for free on our hosted solution here. https://app.nocodb.com/#/signin
