### ISSUE TITLE
🔦 Feature: Bulk checking existence using the REST API

### ISSUE THREAD

**Issue by singleparadox** [nocodb/nocodb#5745]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently, checking for the existence of a row can become very slow if there are a lot of data inside a table:
`/api/v1/db/data/{orgs}/{projectName}/{tableName}/{rowId}/exist`

You would need to send an API request one by one to check which rows exists.

### Suggested Solution

It would be nice if there was a way to send multiple data in one request instead of sending a request one by one.

Something like this (Example: Check if rows with titles exist already in the database):
`
[
   {
      "Title": "Trees"
   },
   {
      "Title": "Cats"
   }
]
`

and return only those which exists in the database:
`["Trees"]`

Alternative: return those which do not exist:
`["Cat"]`

**Comment by pranavxc** [comment]
You can use the filter and do the same, for example with query parameter `where`.

```
where=(Title,eq,Trees)~or(Title,eq,Cats)
```

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/issues/5745#issuecomment-1571492358
