### ISSUE TITLE
🐛 Bug: Attachment column shows broken filename with umlauts

### ISSUE THREAD

**Issue by GiantCrocodile** [nocodb/nocodb#5758]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Add an attachment column to a table
2. Upload a file with a filename that contains German umlauts (ä, ö, ü)
3. See filename in grid view

### Desired Behavior

Umlauts are properly displayed

### Project Details

Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.107.5**

### Attachments

![grafik](https://github.com/nocodb/nocodb/assets/6271057/857300fc-58c0-4273-b010-2ee3d5a8b6e5)

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/6824
