### ISSUE TITLE
🐛 Bug: form view do not extent text area

### ISSUE THREAD

**Issue by hodanli** [nocodb/nocodb#5765]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create text field
2. create form view
3. create share link
4. enter long text to the form using shared view

## Expected behavior

text ares should expand.

### Project Details

deployed on digitalocean server using docker

### Attachments

Screenshots

![image](https://github.com/nocobase/nocobase/assets/6535865/3b2a8a4d-b691-4262-9883-856247021a67)

**Comment by ShubhamPatilsd** [comment]
Will be reserving this for students at [CodeDay Labs](https://labs.codeday.org/) to be working on in our summer cohort.

**Comment by Mercywanjohi** [comment]
> Will be reserving this for students at [CodeDay Labs](https://labs.codeday.org/) to be working on in our summer cohort.

Claiming this issue, will be working with @PyJim for the CodeDay Labs internship.

**Comment by wingkwong** [comment]
fixed in #6121
