### ISSUE TITLE
🐛 Bug: Crash with 0.108.0 when NC_PUBLIC_URL is set

### ISSUE THREAD

**Issue by gramakri** [nocodb/nocodb#5778]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

* Start nocodb with NC_PUBLIC_URL environment variable set
* The code crashes with
```
# node index.js 
[Nest] 135  - 05/31/2023, 3:47:16 PM     LOG [NestFactory] Starting Nest application...
[Nest] 135  - 05/31/2023, 3:47:16 PM     LOG [InstanceLoader] PassportModule dependencies initialized +31ms
[Nest] 135  - 05/31/2023, 3:47:16 PM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 135  - 05/31/2023, 3:47:16 PM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 135  - 05/31/2023, 3:47:16 PM     LOG [InstanceLoader] o dependencies initialized +0ms
[Nest] 135  - 05/31/2023, 3:47:16 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +4ms
[Nest] 135  - 05/31/2023, 3:47:16 PM   ERROR [ExceptionHandler] Cannot read properties of undefined (reading '_noco')
TypeError: Cannot read properties of undefined (reading '_noco')
    at m.create (/app/code/node_modules/nocodb/dist/bundle.js:1:1313136)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Desired Behavior

Should not crash

### Project Details

I am the maintainer of the Cloudron package. This was found when updating to latest version

**Comment by gramakri** [comment]
It seems the issue is from maybe [this commit](https://github.com/nocodb/nocodb/commit/1c884299db1fb0b37e43d273c2744bec138cf255) . Specifically:

https://github.com/nocodb/nocodb/blob/master/packages/nocodb/src/utils/nc-config/NcConfig.ts#L123

I guess `ncConfig.envs['_noco']` is not initialized .

**Comment by gramakri** [comment]
I guess the envs stuff should go away entirely since it's not used afaict. From https://github.com/nocodb/nocodb/blob/master/packages/nocodb/src/utils/nc-config/NcConfig.ts#L43

```
  // TODO what is this?
  envs: any;
```

**Comment by pranavxc** [comment]
The `envs` is no longer in use I will remove it, thanks for reporting the bug.

**Comment by gramakri** [comment]
Can confirm it's fixed. Thanks for the quick fix.
