### ISSUE TITLE
CORS in heroku

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#579]

**Comment by pranavxc** [comment]
Configuring `NC_PUBLIC_URL` environment variable will resolve the issue.

You can add the env by following steps:

1. Open settings tab from heroku app dashboard 
     ![image](https://user-images.githubusercontent.com/61551451/134891271-3dcd7bc0-332f-417d-b725-8b06b6e4f7f9.png)
2. Click **Reveal Config vars** button
     ![image](https://user-images.githubusercontent.com/61551451/134891486-4f912d4c-4bb7-435b-ae4b-6b3ecdabb2ea.png)
3. Add the new environment `NC_PUBLIC_URL`
     ![image](https://user-images.githubusercontent.com/61551451/134891685-d6b95247-7236-45f7-a3b8-dcc86aa26a6a.png)
