### ISSUE TITLE
🐛 Bug: Grid Cell selection along with mouse movements

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5791]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

https://www.loom.com/share/2d1f0ff7786442f3b3b85c77b0e5efd1

### Desired Behavior

- [ ] Right click on any cell should clear previous cell selection
- [ ] Esc should close context menu
- [ ] Right click & moving around mouse should not select cells by default (currently emulates click drag behaviour)

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.108.1**

**Comment by DIWAKARKASHYAP** [comment]
in my system it work perfectly
