### ISSUE TITLE
🐛 Bug: API Calls with where sometimes not working

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#5796]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Since the upgrade to 0.108.0 our api calls getting sometimes a return datas and sometimes empty list.

### Desired Behavior

Should always return the datas.

### Project Details

Docker
PG
0.108.0

**Comment by emre1e** [comment]
where i can get the error logs inside the docker container?

API: just the normal list API

**Comment by o1lab** [comment]
Can you capture the http API call made and paste it here (redact things that are sensitive) and are the APIs being paginated ?

**Comment by emre1e** [comment]
Without the where clause:
![image](https://github.com/nocodb/nocodb/assets/117290601/d44035c6-a620-497d-ab69-29be6af5df45)

**Comment by o1lab** [comment]
Would need it in the form of text please & include where clause if this was involved. 

We dont see a reason as of now why this should occur in latest build - how many time have you seen this ?

**Comment by o1lab** [comment]
20 mins!! :) or seconds ?

**Comment by emre1e** [comment]
can´t include in text from because there are confidential data

**Comment by emre1e** [comment]
for more information i upgraded from 0.106.1

**Comment by emre1e** [comment]
so now i got more infos. Even if i exceute the API without the where, im only getting 2 rows. So the reponse is always wrong, not depending to the where clause.

**Comment by o1lab** [comment]
> Would need it in the form of text please & include where clause if this was involved.

We need your http api request in text. Also please reach out to @pranavxc in discord.

**Comment by emre1e** [comment]
request is here:
http://10.140.94.94:8080/api/v1/db/data/v1/Gamble/Fälle?limit=25&shuffle=0&offset=0&nested%5Bnc_wd2c___nc_m2m_p9cul6j36e%20List%5D%5Boffset%5D=0&nested%5Bnc_wd2c___nc_m2m_p9cul6j36e%20List%5D%5Blimit%5D=25&nested%5BWenn_mehrere_Casinos_True_Bespieltes_Casino%5D%5Boffset%5D=0&nested%5BWenn_mehrere_Casinos_True_Bespieltes_Casino%5D%5Blimit%5D=25&nested%5BGegneranwalt%5D%5Boffset%5D=0&nested%5BGegneranwalt%5D%5Blimit%5D=25&nested%5Bnc_wd2c___nc_m2m_s3uu2jwl57%20List%5D%5Boffset%5D=0&nested%5Bnc_wd2c___nc_m2m_s3uu2jwl57%20List%5D%5Blimit%5D=25&nested%5Bnc_wd2c___nc_m2m_h5o3f81z64%20List%5D%5Boffset%5D=0&nested%5Bnc_wd2c___nc_m2m_h5o3f81z64%20List%5D%5Blimit%5D=25&nested%5BGericht%5D%5Boffset%5D=0&nested%5BGericht%5D%5Blimit%5D=25&nested%5BKlagegegner%5D%5Boffset%5D=0&nested%5BKlagegegner%5D%5Blimit%5D=25&nested%5Bnc_wd2c___nc_m2m_1b1ja6d357%20List%5D%5Boffset%5D=0&nested%5Bnc_wd2c___nc_m2m_1b1ja6d357%20List%5D%5Blimit%5D=25

**Comment by emre1e** [comment]
we found the problem, please fix thisssss :)

if you set a filter on the View with the same name, the API output the same rows then

before the update the API without /views/ in the url was not affected by this.

**Comment by pranavxc** [comment]
If `viewId` is not defined it will fall back to the default view and the view filters will get applied. To make it behave like before keep the default view without any filter. We will revert the change if required after an internal discussion with the team.

**Comment by jellederijke** [comment]
I noticed this, as well. I experience this as unexpected behaviour. When I filter something in the default view, I do not expect that this influences all API calls.

**Comment by onejgordon** [comment]
Big +1 to this issue. Current behavior prevents any robust integration that depends on query results to an underlying table not shifting in response to UI actions (which users cannot predict will affect responses to external core table API calls).

As a concrete example, we have a backup service that queries all rows on the table via REST, and stores the JSON response. This backup service fails if any user filters the default view of the table.

**Comment by dstala** [comment]
fixed; will be available in v0.202.6
https://github.com/nocodb/nocodb/pull/6941
