### ISSUE TITLE
🐛 Bug: nocodb  sorry, too many clients already

### ISSUE THREAD

**Issue by linqianppb** [nocodb/nocodb#5806]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

use this  /api/v1/db/data/noco/p_1e95yltabcnbpq/md_2splaf6125f8ma/views/vw_skzki2m8spxdvh
error sorry, too many clients already

### Desired Behavior

use this  /api/v1/db/data/noco/p_1e95yltabcnbpq/md_2splaf6125f8ma/views/vw_skzki2m8spxdvh
error sorry, too many clients already

### Project Details

use this  /api/v1/db/data/noco/p_1e95yltabcnbpq/md_2splaf6125f8ma/views/vw_skzki2m8spxdvh
error sorry, too many clients already

**Comment by pranavxc** [comment]
@linqianppb Can you share the backend(docker/node) log ? You can share it here or ping me (pranavxc) in our discord channel -  https://discord.gg/5RgZmkW.

**Comment by dstala** [comment]
@linqianppb please reopen this thread if you are facing this issue even with latest release.
