### ISSUE TITLE
🐛 Bug: Schema filter not working for SQL Views in database connections

### ISSUE THREAD

**Issue by zyst1988** [nocodb/nocodb#5823]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

schema filter in SQL connection does not work for views i.e. NocoDB doesn't apply the schema filter to views and brings them all in. 

### Desired Behavior

Views that don't belong to the specified schema should be filtered out (just like the tables are).  

### Project Details

Using latest version of NocoDB on Docker

**Comment by zyst1988** [comment]
Hi,

Yes, that is correct, the schema filter does not appear to be applied to views and all the views including those from other schemas are being imported - in my case, I'm using an external MSSQL database. Sorry for not being clear!

Thanks,
M

**Comment by pranavxc** [comment]
Thanks for the quick response, I've fixed it for Postgres and will check the MSSQL part as well :+1:

**Comment by zyst1988** [comment]
Yes, I'm using MSSQL as data source so that would be great - thank you!

**Comment by pranavxc** [comment]
@zyst1988 Can you test with following PR build.

```sh
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.108.1-pr-5870-20230612-1025
```



https://github.com/nocodb/nocodb/commit/1c6850e56342052d85895b01a0b6a4de80792af1#comments

**Comment by zyst1988** [comment]
Perfect, the filter now works as expected! Thank you for resolving this so quickly! 

When do we think this will be rolled out to the users?

Cheers,
M

**Comment by zyst1988** [comment]
Amazing, thank you very much for your help!
