### ISSUE TITLE
🐛 Bug: can't open table on mobile chrome oa

### ISSUE THREAD

**Issue by Dont-ask-for-it** [nocodb/nocodb#5857]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Clicking on table do nothing 

### Desired Behavior

Should open the table 

### Project Details

Latest version

**Comment by prononext** [comment]
Yes the same here on Version 0.109.4

Mobile Browsers can Login but not able to open, view or edit any table on all major mobile browsers.

Firefox, Chrome, Safari etc.

**Comment by dstala** [comment]
v0.202.5 has some responsive issues addressed. please try it out & if you still see some issues, help us by reopening this thread.
