### ISSUE TITLE
How to hide the auto-generated id field🐛 Bug: 

### ISSUE THREAD

**Issue by sigmoidfrog** [nocodb/nocodb#5879]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![image](https://github.com/nocodb/nocodb/assets/118798560/9993b06e-da0d-495e-9083-04a30f914a51)
cannot hide or move the default created field

### Desired Behavior

field should be hide or moved

### Project Details

Node: **v18.0.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.105.3**

**Comment by dstala** [comment]
@sigmoidfrog are you referring to `Master_SKU` field? Display value field can't be hidden. You will have to set another field as `Display value` & then hide `Master_SKU`

https://docs.nocodb.com/setup-and-usages/display-value#how-to-set-display-value-

**Comment by sigmoidfrog** [comment]
ok, But what if we want to hide the Primary field , we don't want it

**Comment by dstala** [comment]
@sigmoidfrog NocoDB needs one `display value` field to work with LTAR/Links. So, to hide primary field, you can mark any other relevant field as `display value` field & then hide primary field.
