### ISSUE TITLE
🐛 Bug: Latest Build Failed

### ISSUE THREAD

**Issue by sigmoidfrog** [nocodb/nocodb#5882]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![image](https://github.com/nocodb/nocodb/assets/118798560/cf0270a6-a658-4975-a08e-d307ef49c4e9)

### Desired Behavior

build should work after npm install

### Project Details

latest version on 13-06-2023

**Comment by dstala** [comment]
@sigmoidfrog can you try clearing `/node_modules` folder & carry out `npm install` again? do let us know if you still face issue.

**Comment by sigmoidfrog** [comment]
This issue has been fixed, by taking latest again and doing npm install again.
Thanks
