### ISSUE TITLE
🐛 Bug: projects' Actions missing in dashboard's UI 

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#5883]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

As on version 0.108.1 or 0.109.0,
open https://<your-domain>/dashboard/#/
and see no way to delete/edit projects : (

### Desired Behavior

Projects should have controls in dashboard, as was before or better : )

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.0**

### Attachments

![image](https://github.com/nocodb/nocodb/assets/61871501/2bbea81b-6909-4027-a37b-016b713834b7)

**Comment by dstala** [comment]
@RawmanGrey : sure you have access to those projects? I tried on that release - and was able to access project menu options. In network tab, can you check response of `/api/v1/db/meta/projects` & share it here?

You can also DM me on Discord (dstala) for further debugging if issue perissts

**Comment by RawmanGrey** [comment]
@dstala, Yes, that was owner's account.. I even sometimes see flashing items after click on project and before corresponding page loads.
<details> 
  <summary>Code 200 response on `/api/v1/db/meta/projects` request</summary>
   
   ```
   {
    "list": [
        {
            "id": "someId",
            "title": "someProjectTitle",
            "prefix": "nc_xcf___",
            "status": null,
            "description": null,
            "meta": "{\"theme\":{\"primaryColor\":\"#381475\",\"accentColor\":\"#517514ff\"},\"showNullAndEmptyInFilter\":true}",
            "color": "#381475",
            "uuid": null,
            "password": null,
            "roles": null,
            "deleted": false,
            "is_meta": true,
            "order": null,
            "created_at": "2022-04-20 08:18:39+00:00",
            "updated_at": "2023-06-11 18:29:22+00:00"
        },
        {
            "id": "someId",
            "title": "someProjectTitle",
            "prefix": "nc_i9mp__",
            "status": null,
            "description": null,
            "meta": "{\"showNullAndEmptyInFilter\":false}",
            "color": null,
            "uuid": null,
            "password": null,
            "roles": null,
            "deleted": false,
            "is_meta": true,
            "order": null,
            "created_at": "2022-04-21 10:14:59+00:00",
            "updated_at": "2023-06-11 12:37:09+00:00"
        },
        {
            "id": "someId",
            "title": "someProjectTitle",
            "prefix": "nc_v74r__",
            "status": null,
            "description": null,
            "meta": null,
            "color": null,
            "uuid": null,
            "password": null,
            "roles": null,
            "deleted": false,
            "is_meta": true,
            "order": null,
            "created_at": "2023-06-11 18:45:11+00:00",
            "updated_at": "2023-06-11 18:45:11+00:00"
        },
        {
            "id": "someId",
            "title": "someProjectTitle",
            "prefix": "nc_y29e__",
            "status": null,
            "description": null,
            "meta": null,
            "color": null,
            "uuid": null,
            "password": null,
            "roles": null,
            "deleted": false,
            "is_meta": true,
            "order": null,
            "created_at": "2023-06-12 09:51:01+00:00",
            "updated_at": "2023-06-12 09:51:01+00:00"
        }
    ],
    "pageInfo": {
        "totalRows": 4,
        "page": 1,
        "pageSize": 4,
        "isFirstPage": true,
        "isLastPage": true
    }
}
```
</details>


I've tried on fresh install and failed to reproduce. However, I've noticed that owner on fresh install has "Super Admin" role, and there is no such role on my poduction-copy-test instance.

Cheating by altering user's role from  "org-level-creator" to "org-level-creator,super" in `nc_users_v2` table had no effect.

**Comment by pranavxc** [comment]
@RawmanGrey : I've fixed the bug in the following PR - https://github.com/nocodb/nocodb/pull/5885 . 

At the moment it's showing project actions only for the `super` admin user but it should be based on the project-specific user role and necessary changes are introduced in above PR.

**Comment by pranavxc** [comment]
> Cheating by altering user's role from "org-level-creator" to "org-level-creator,super" in nc_users_v2 table had no effect.

If you directly change the role, you must restart the app since user details will be in the cache. If you are using Redis for cache then clear the cache once.

**Comment by RawmanGrey** [comment]
> If you directly change the role in db, you must restart the app since user details will be in the cache.

I've done container restart (along with all cache removal). After your comment even recreated container, but unfortunately with no effect.

**Comment by pranavxc** [comment]
Can you try out the following PR build

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.109.0-pr-5885-20230613-1750
```

Ref: https://github.com/nocodb/nocodb/commit/80bd4b9ef72b0d367fa9bf7fb48356d950978c98#commitcomment-117875063

**Comment by pranavxc** [comment]
> 

Really thanks for confirming and we will make a bug fix release tomorrow.
