### ISSUE TITLE
🐛 Bug: Swagger bundle js error in latest build

### ISSUE THREAD

**Issue by sigmoidfrog** [nocodb/nocodb#5889]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![image](https://github.com/nocodb/nocodb/assets/118798560/dea174bc-4801-418b-a563-a474e2f1fdbd)
![image](https://github.com/nocodb/nocodb/assets/118798560/32463ebe-3a9b-4df5-8399-1e626a754a25)

### Desired Behavior

swagger should open and work

### Project Details

latest version, install on 13-06-2023 on linux machine

### Attachments

1

**Comment by pranavxc** [comment]
Can you share a few more details,

1. Are you using the docker / nodejs app ?
2. Is it deployed under a sub domain ?

**Comment by sigmoidfrog** [comment]
Are you using the docker / nodejs app? -- Nodejs app
Is it deployed under a subdomain? -- No

I think it is missing nc_siteurl,

**Comment by pranavxc** [comment]
> Are you using the docker / nodejs app? -- Nodejs app Is it deployed under a subdomain? -- No
> 
> I think it is missing nc_siteurl,

It will be helpful if you can share the steps you followed to run the application.

**Comment by sigmoidfrog** [comment]
git clone https://github.com/nocodb/nocodb
cd nocodb/packages

# build nocodb-sdk
cd nocodb-sdk
npm install
npm run build

cd /nocodb/packages/nc-gui
npm run build:copy
cd /nocodb/packages/nocodb/node_modules/nc-lib-gui/lib/dist
cp -R /nocodb/packages/nc-gui/.output/public/. .


cd /nocodb/packages/nocodb
npm run build
npm run start

**Comment by valentt** [comment]
I had this bug with version that I installed 5 weeks ago via docker-compose, I have now pulled latest docker image and swagger api page works as expected.

**Comment by dstala** [comment]
@sigmoidfrog please upgrade to latest release & reopen this thread if you issue still persists.
