### ISSUE TITLE
🔦 Feature: Add Select All / Unselect All buttons to the UI Acl Panel

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [nocodb/nocodb#5892]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

It's one hell of a hassel to check / uncheck all the boxes when you have hundreds of tables within on database. 

### Suggested Solution

It'll be really handy if there was a 'Select All' and 'Unselect All' button for each role.

### Additional Context

![2023-06-14_14-35-06_FGNC Sheet-1  NocoDB - Cent Browser](https://github.com/nocodb/nocodb/assets/63704404/76168ca4-00e6-421d-84b2-a02bc9110493)

**Comment by frankMagoba** [comment]
Hi @o1lab can I pick this up?
