### ISSUE TITLE
🔦 Feature: sql query as table

### ISSUE THREAD

**Issue by sunknight** [nocodb/nocodb#5900]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

create a view table from sql query, query can join 2 or more tables . new view table columns use source table's column define

### Suggested Solution

select a.id, a.title, b.name, b.value from table1 as a left join table2 as b on a.pid=b.id 
new view table is :
id, title, name, value

**Comment by o1lab** [comment]
Create a view and have the meta synced. You should be able to see that as query.

**Comment by sunknight** [comment]
thanks

**Comment by o1lab** [comment]
https://docs.nocodb.com/setup-and-usages/sync-schema#how-to-sync-schema-changes-to-nocodb
