### ISSUE TITLE
🐛 Bug: sync meta error after delete table 

### ISSUE THREAD

**Issue by sunknight** [nocodb/nocodb#5902]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I delete some table from mysql database, in nocodb datasource page, use sync meta, can detected change.
but when sync meta, have this notice:

delete from `nc_columns_v2` where `fk_model_id` = 'md_zdl6obhvi9imbu' - Cannot delete or update a parent row: a foreign key constraint fails (`nocodb`.`nc_col_relations_v2`, CONSTRAINT `nc_col_relations_v2_fk_parent_column_id_foreign` FOREIGN KEY (`fk_parent_column_id`) REFERENCES `nc_columns_v2` (`id`))

### Desired Behavior

the tables is create by nocodb in other database

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.1**

### Attachments

<img width="972" alt="image" src="https://github.com/nocodb/nocodb/assets/3024264/46e82195-15b5-4f3a-ac79-ff5a8220bfb9">

<img width="1353" alt="image" src="https://github.com/nocodb/nocodb/assets/3024264/31c2a20f-705a-4de1-a892-d6b6314cc34d">

**Comment by dstala** [comment]
did you end up deleting some of meta tables of NocoDB? @sunknight please reopen this thread if issue still persists with latest release.
