### ISSUE TITLE
🐛 Bug: Not all records returned in row with relations

### ISSUE THREAD

**Issue by punndcoder28** [nocodb/nocodb#5906]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have 2 tables, `Table A` and `Table B`. `Column A` in `Table A` has a many to many relation with `Column B` in `Table B`. Now the number of records linked to to row in `Table A` in `Table B` is greater than 25 which is causing some of the linked records to not show when I query a row from `Table A`. I am using the `nocodb-sdk` JS sdk for the project and the api method `api.dbTableRow.read` to read the row details. Is there a method to get all the linked records as part of the api response or any configuration I can make which will enable me to get all the records.

### Desired Behavior

The desired behaviour would be where all the items in the relation are returned even if the records are more than 25 or details in the documentation on how we can achieve this behaviour.

### Project Details

```
Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.106.1**
```

**Comment by dstala** [comment]
@punndcoder28 use api.dbTableRow.nestedList

**Comment by punndcoder28** [comment]
Hi @dstala . Thanks for the quick response, with pagination and the method suggested, I was able to achieve what I needed. Will close the issue
