### ISSUE TITLE
[Feature] Reopen all open tabs (of tables)

### ISSUE THREAD

**Issue by compasssites** [nocodb/nocodb#5916]
When a user jumps to another base adn tries to come back again, he has to open all the tables again one by one. Can we have an option to re-open all the previous tabs (or tables) like the Safari/Chrome browser. There could also be a toggle as some may not want this feature or it may overload the resources.

**Comment by dstala** [comment]
Closing this, as tabs are no more relevant in new design (v0.111.0)
