### ISSUE TITLE
🐛 Bug: Single select doesn't work

### ISSUE THREAD

**Issue by alprotasov** [nocodb/nocodb#5926]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1) Create any table with single select field
2) Create a form view
3) Open form
4) Try to select any value for single select field

PS There is an exception in console
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'content')
    at Object.initialize (cs.js:1:366691)`

### Desired Behavior

Options appeared

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.1**

**Comment by ilyak0** [comment]
Now it works on 109.3, but still necessary to add one more click on the field to proceed with the selection.

https://github.com/nocodb/nocodb/assets/111974217/1955e2a0-0762-4e17-bd2c-97efda6ebc46

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.3**
