### ISSUE TITLE
🐛 Bug: uppercase should be after lowercase when sort `A-Z`

### ISSUE THREAD

**Issue by m2acgi** [nocodb/nocodb#5929]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![image](https://github.com/nocodb/nocodb/assets/34497122/93e003fb-e829-4832-b952-0535398f706d)

### Desired Behavior

uppercase should be after lowercase when sort `A-Z`

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.107.5**

**Comment by dstala** [comment]
@m2acgi that's standard ascending sort order accepted in general. Hence we will skip this request. 

https://www.codeproject.com/Questions/232878/Sorting-Capital-letters-come-first-than-small-lett
