### ISSUE TITLE
🐛 Bug: Delete record, undo; links are not re-inserted

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5935]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Sheet1 <hm> Sheet2, each sheet has 5 records each
- Link record-1 of Sheet-1 to [1,2,3]
- Link record-2 of Sheet-1 to [4,5]
- Delete record-1, undo
- On UI, links show that they are inserted back. Reload page- links vanish

### Desired Behavior

Links should get inserted back

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.109.1**

**Comment by GreeneyeAlx** [comment]
I apologized yes it do not existSent from my iPhoneOn Jun 21, 2023, at 1:26 AM, Raju Udava ***@***.***> wrote:﻿
Please confirm if bug report does NOT exists already ?

 I confirm there is no existing issue for this

Steps to reproduce ?

Sheet1  Sheet2, each sheet has 5 records each
Link record-1 of Sheet-1 to [1,2,3]
Link record-2 of Sheet-1 to [4,5]
Delete record-1, undo
On UI, links show that they are inserted back. Reload page- links vanish

Desired Behavior
Links should get inserted back
Project Details
Node: v16.14.0
Arch: arm64
Platform: darwin
Docker: false
RootDB: pg
PackageVersion: 0.109.1
Attachments
No response
