### ISSUE TITLE
🐛 Bug: Syncing NC_DB metadata removes visibility to all tables from external DB

### ISSUE THREAD

**Issue by lcavasso** [nocodb/nocodb#5944]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Created several tables, including different relationships. There are also SQL views that were created on back end.
![image](https://github.com/nocodb/nocodb/assets/35540322/1260e5d3-9812-440b-bfde-89fde30bf605)
2. Check if tables data is out of sync - it shows that BASE is out of sync.
![image](https://github.com/nocodb/nocodb/assets/35540322/6901f153-ecba-49ec-8420-1469188267e4)
3. Click BASE's Sync Metadata button, see that it thinks existing tables have been added/removed (they have not changed)
![image](https://github.com/nocodb/nocodb/assets/35540322/94502c5d-01cd-49b7-8395-b9b0ed412add)
5. Click Sync Now
![image](https://github.com/nocodb/nocodb/assets/35540322/f8656bc0-634f-491a-9e1d-c6ea23c4d092)
6. Tables no longer show up in external db:
![image](https://github.com/nocodb/nocodb/assets/35540322/9f210112-d42f-4eb6-ae34-5708ca5e9a15)
(they are still there on backend though - no data loss)
![image](https://github.com/nocodb/nocodb/assets/35540322/cb70cdc3-aac9-49d5-838b-c13b99293e4d)
7. Back to Data Sources menu - now external DB is out of sync.
![image](https://github.com/nocodb/nocodb/assets/35540322/06ab47c9-fe5f-4c31-8899-5df1f1b5694d)
![image](https://github.com/nocodb/nocodb/assets/35540322/d967d47d-c979-4429-bb4e-08d293e11080)
8. Click Sync Now (for external DB)
9. Tables show up again, but any custom order for tables to appear in, emoji icons, or underscores in names are all reset
![image](https://github.com/nocodb/nocodb/assets/35540322/1fc64481-a0e9-40ba-9558-6c6af3ba2e9f)
10. Look at Data Sources menu again - now BASE is out of sync!
![image](https://github.com/nocodb/nocodb/assets/35540322/554f96ac-6a80-4474-8898-7464d1910d3b)
11. Repeat 3-10 infinitely.
Just to be clear, no changes were made in MySQL from step 2 onwards. Also tried installing a new NocoDB container linked to the same external database, but using an `NC_DB` on the same MySQL instance (different database from the external one though). Same pattern emerges.

These issues have some similarities, but don't quite seem the same as what I'm experiencing:
https://github.com/nocodb/nocodb/issues/5902
https://github.com/nocodb/nocodb/issues/1009

### Desired Behavior

Syncing BASE metadata should not make external DB tables invisible to NocoDB. BASE should not show that tables have changed when the changed tables are in a different database (in this case the externally linked one, not BASE).
Syncing external DB metadata should not cause underscores to disappear from names (for example the MySQL table `X_Family` shows in NocoDB as XFamily). It also should not change order of tables in NocoDB sidebar or reset emoji icons.

### Project Details

First occurred on:
Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.106.1**

Also reproduced on:
Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.106.1**

**Comment by pranavxc** [comment]
Thanks for reporting this bug. We've investigated the issue and have been unable to reproduce it with our latest release. However, we can see that the bug exists in the older version 0.106.1.

We recommend that you upgrade to our latest release. If the bug still persists, please let us know and we'll investigate it further.

**Comment by lcavasso** [comment]
Sorry for the delayed response - updated and am not seeing the same issue.

Project details post update, for posterity:
Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.4**
