### ISSUE TITLE
🔦 Feature: Expand record option for shared view

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#5945]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

![image](https://github.com/nocodb/nocodb/assets/55474996/77867d3c-f713-40cf-9692-ca8d32af1659)

If I share a Table view or embedded it on my site, it's not possible for a viewer to expand a long text-field or open any of the record in expanded card mode to read the entire cell. Making the cell-height-bigger doesn't help either.

### Suggested Solution

Just like for Editors:

When viewers hover of the record's number, they should be able to expand the record in card mode.

![image](https://github.com/nocodb/nocodb/assets/55474996/99009c90-3a02-458d-b373-1c13c2374028)

When the viewer hovers over a long-text field, they should be able to expand that individual cell to read its entire text (with scroll)

![image](https://github.com/nocodb/nocodb/assets/55474996/e8a9022b-d7e5-4fef-889a-cbc1e79ed447)

Text should also be displayed in "Wrap text" mode (whilst respecting the cell height) -> see example from Excel:

![image](https://github.com/nocodb/nocodb/assets/55474996/a4e802e4-93d6-4b3c-a52b-341ca8456358)

### Additional Context

Related: https://github.com/nocodb/nocodb/issues/2271

Airtable example:
![](https://user-images.githubusercontent.com/86527202/172102383-26472fd1-662b-4642-90f8-c602285b1678.png)

**Comment by dstala** [comment]
expansion of expanded record is now available; but viewer still doesn't have expand record option
