### ISSUE TITLE
🐛 Bug: Slow Performance since update 0.109.0

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#5946]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Since update to [0.109.0](https://github.com/nocodb/nocodb/releases/tag/0.109.0) the performance got worse.

### Desired Behavior

No Performance problems

### Project Details

Docker
PG
0.109.2

**Comment by o1lab** [comment]
Can you provide more details like how many has-many and many-to-many columns you have in that table.

And is the PG database external or internal.

**Comment by emre1e** [comment]
its internal, we have many fields(20 - 30), but the performance degreation can be replicated. If i downgrade my version, everything works fine.

**Comment by o1lab** [comment]
Can you please ping me in discord. We can have a quick look at what might be the issue.

**Comment by emre1e** [comment]
there are really sensitive data in it, so i cant show you, Sorry for not being a help :(

**Comment by o1lab** [comment]
Open browser console and use the 'reload' icon adjacent to '+' 

Check what is the Xc-db-response time under browser console > network > 'Fetch/XHR'

See if its the same amount of time as the time it takes to laod the data. Asking it to verify if the load is in data fetch from your db or displaying it. 

<img width="1243" alt="image" src="https://github.com/nocodb/nocodb/assets/5435402/368d9fa6-9b7c-4bd9-b79c-fd190d9e5bd6">

**Comment by emre1e** [comment]
![image](https://github.com/nocodb/nocodb/assets/117290601/0340425a-3bd9-4857-8a87-2ef6a790e986)

**Comment by o1lab** [comment]
But what about the 'response headers' value of 'Xc-db-response'. See my image above - its showing 35.061. 

And how long do you think it is taking to load the table ?

**Comment by emre1e** [comment]
![image](https://github.com/nocodb/nocodb/assets/117290601/36047ac3-89d7-4527-ac66-57a3ad4f3c6e)

**Comment by andr-ec** [comment]
I can confirm this is the case as well. We see this especially when opening different views on a table with many columns. 
Our workaround is to use nocodb/nocodb:0.108.1

**Comment by o1lab** [comment]
Can you provide the performance difference as explained above in the issue. Also do provide how many lookups, formulas exist.

And @emre1e : I see the response time is 468 (is milliseconds) which is not a lot. You will have to clarify the speed here pls or you looked up the wrong APIs response time.

**Comment by o1lab** [comment]
Ok can you get on a call with one of our engineer @pranavxc in discord. That will help to debug.

**Comment by o1lab** [comment]
@andr-ec : thanks for showing us through the problem and confirming the fix. I understand we 've made some optimisations for the slowness and a fix in the upcoming release. However we also learnt that you had like columns close to 400 :) - please try having necessary columns that you need in the grid view.
