### ISSUE TITLE
🔦 Feature: Keyboard shortcuts for Pagination navigation

### ISSUE THREAD

**Issue by glodov** [nocodb/nocodb#5948]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Add shortcuts for navigation through the tables).

### Suggested Solution

1. Add shortcuts for navigation through the tables (ALT+K, ALT+L) or
1. make group of components (Tables, Rows, etc.) in which TAB navigation is enabled and the ability to switch between such components (ALT-W).

**Comment by dstala** [comment]
[🔦 Feature: Keyboard shortcuts for Pagination navigation](https://github.com/nocodb/nocodb/issues/5178)
