### ISSUE TITLE
🐛 Bug: QR Code column type not working when input column is a formula

### ISSUE THREAD

**Issue by Sov3rain** [nocodb/nocodb#5963]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

* Create a column with type "formula", add a simple formula, mine is something like this: `CONCAT('url', {uid}) ` where uid is a db type (here `uuid`). The output of this formula is a simple link.
* Create another column, with type "qr code" and select your formula column as input.
* The QR code is not generated

Here is the error in console:

```
ant-design-vue.25ebc081.js:1 Error: 
The chosen QR Code version cannot contain this amount of data.
Minimum version required to store current data is: 5.

    at ve (QrCode.5b416672.js:4:3335)
    at Nt.create (QrCode.5b416672.js:7:517)
    at QrCode.5b416672.js:8:569
    at new Promise (<anonymous>)
    at mt (QrCode.5b416672.js:8:528)
    at Bt.$t.immediate (QrCode.5b416672.js:8:924)
    at ta (ant-design-vue.25ebc081.js:1:13958)
    at qn (ant-design-vue.25ebc081.js:1:14037)
    at m (ant-design-vue.25ebc081.js:1:24285)
    at Wl (ant-design-vue.25ebc081.js:1:24492)
dI @ ant-design-vue.25ebc081.js:1
```

### Desired Behavior

The QR code should display properly. It works when the input is not a formula though.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.107.5**

Deployed on Railway.app

### Attachments

![Screenshot_4](https://github.com/nocodb/nocodb/assets/10755450/bb8f8bdb-be1a-4cb1-8261-fe9d8db5fadb)
![Screenshot_6](https://github.com/nocodb/nocodb/assets/10755450/4269a54f-e75f-41c3-8a4b-7d5e59e63756)

**Comment by Sov3rain** [comment]
After further investigation, it seems like the error was pretty descriptive: QR Code v4 is too small to contain my full URL, which is composed of a UUID and and domain name.

The maximum allowed characters in a QR Code v4 is apparently 63.

So what appears to be a bug is now more of a feature request: be able to use QR Code v5.

What do you guys thinks?

**Comment by shashankvish0010** [comment]
I cannot reproduce the issue, even with a 70-character URL, the QR code is generated. Are you still facing this issue?

**Comment by Sov3rain** [comment]
Yes, I do. I tried on a clean slate instance of Noco, still the same. Didn't tried on recent versions though (I'm on 107.5).
