### ISSUE TITLE
🐛 Bug: "Missing 'parentId' property in request body" creating a new column with LinkToAnotherRecord type

### ISSUE THREAD

**Issue by nilsreichardt** [nocodb/nocodb#5964]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Set up NocoDB
2. Create project
3. Create table
4. Create a colum with the type LinkToAnotherRecord

### Desired Behavior

From older version I know I could select the relation type, like many to many. This is not visible anymore. Is this the expected behavior?

When I click save, I get a "Missing 'parentId' property in request body" error.

### Project Details

```
Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.109.2**
```

### Attachments

https://github.com/nocodb/nocodb/assets/24459435/defc042d-07cb-498d-a428-8bb5c5a11ec4

**Comment by dstala** [comment]
Tried locally; did not see any issue. 

Node: **v16.20.0**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.2**

Can you share log data from browser console? Are you connecting to External DB? If you have any more log details - do share.

**Comment by nilsreichardt** [comment]
I can't reproduce it anymore. But yes, the DB is an external Postgres dB.

**Comment by wingkwong** [comment]
Closing - not reproducible.
