### ISSUE TITLE
Feature: Global search should include all fields by default

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#5970]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Open a View.
Type something into the search field.
No Search Result.
Press the arrow behind the lens icon.
Choose the field, where the searched text appears.
Search result found.

### Desired Behavior

Search function should look in all rows? Is this the desired behavior? What is searched if i dont select anything.

Extension:

It woulb be nice to select multiple fields to search in.

### Project Details

Docker
PG
0.109.2

**Comment by nilsreichardt** [comment]
> Search function should look in all rows? Is this the desired behavior? What is searched if i dont select anything.

I think there is no built option for this right now.

However, as a workaround, you add a new row and use the type Formula where you concat all rows, like:

```
CONCAT({First Name}, " ", {Last Name}, " ", {Organizations}, " ", {Phone Numbers}, " ", {Email Addresses}, " ", {Position}, " ", {Twitter}, " ", {Websites}, " ", {LinkedIn})
```

Additionally, you can hide the field in the UI but still use the search 👍

**Comment by emre1e** [comment]
Thank you. Do you know the Answer on this:

In which fields will be searched, if I do not select anything?

**Comment by nilsreichardt** [comment]
Good question! Seems to be a full-text search which would be mean you don't need my workaround

**Comment by emre1e** [comment]
Then back to the beginning. I think the problem is related to formula and lookup fields. If no field is defined in the search, it searches only in text fields and ignores the lookups and formula fields.

**Comment by dstala** [comment]
If not selected anything, default search will be over 'Primary value' sticky column
Search works in both lookup & formula- but only when that specific field is selected from the dropdown.
Essentially, the search in its current form is more like `quick search within a specific column` 

Marking the following as feature request
- By default search across table
- Allow user to configure multiple columns to be included in search
