### ISSUE TITLE
🔦 Feature: Add "Copy Value" button in context menu

### ISSUE THREAD

**Issue by nilsreichardt** [nocodb/nocodb#5972]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have a table with my contacts and table with email addresses. A contact has in the row "Email Addresses" a link to the "Email Addresses" table. When I need to copy the email address, I copy the cell with all the metadata. However, I only need the email address.

```
[{"Id":25867,"Email Address":"nils@sharezone.net"}]
```

https://github.com/nocodb/nocodb/assets/24459435/44070ed3-71f7-4f53-b8ec-4d1114170618

### Suggested Solution

Having a "Copy Value" button that just copies the value of the cell would be helpful 👍 

<img width="638" alt="image" src="https://github.com/nocodb/nocodb/assets/24459435/34dcb34e-f9a5-4190-b059-c703c1589068">

**Comment by dstala** [comment]
Or may be by default what gets into clipboard for all cell types should be what is being displayed.

**Comment by sreehari2003** [comment]
is this issue resloved ? i tried reproducing the issue but worked good for me

**Comment by wingkwong** [comment]
@sreehari2003 The issue is still reproducible. That one is LTAR field. I believe you've tested on a normal field.

**Comment by dstala** [comment]
LTAR field is now changed to rollup based Links field. 
One can create a lookup field on Links field; copy on lookup field yields mail ID but wrapped under quotes & square brackets`["raju@nocodb.com"]`
