### ISSUE TITLE
🐛 Bug: Webhook trigger is different between Form and Share View Form

### ISSUE THREAD

**Issue by dawidszpilewski** [nocodb/nocodb#5973]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Steps are shown on attached movie

### Desired Behavior

NocoDB generates more than Webhooks when used normal Form. The data in each Webhook is different. If you use Share View Form - only one Webhook is generated (as supposed) however Formula Columns are not included.

It should work as previously (don't remember which version). When used Shareview Form all data (columns) were inluded in Webhook body.

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.2**

https://github.com/nocodb/nocodb/assets/52066687/e314ac10-8e0e-4633-a40b-007205bac0bf

**Comment by dstala** [comment]
Noticed a parallel issue- where in multiple webhook notifications are getting triggered for single event. Need to investigate further.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/6817
