### ISSUE TITLE
🔦 Feature: Use value of formula in lookups

### ISSUE THREAD

**Issue by nilsreichardt** [nocodb/nocodb#5986]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have table with email addresses and a table with humans. Humans have an email address. However, I want to add a lookup in the table email addresses to the name of humans. The name of humans is formula (Concat on first & last name). However this display differently from the value in Humans

How it looks in the email addresses table as lookup:

![image](https://github.com/nocodb/nocodb/assets/24459435/2ef51bc0-8ab1-4b8e-9901-4beea1757a57)

How it should look:

![image](https://github.com/nocodb/nocodb/assets/24459435/19a9e4bb-98ad-4805-b8c5-cd62b7149daf)

It should not have the brackets and the double quotes.

The formula:

```
CONCAT({First Name}, " ", {Last Name})
```

### Suggested Solution

![image](https://github.com/nocodb/nocodb/assets/24459435/19a9e4bb-98ad-4805-b8c5-cd62b7149daf)

**Comment by Hanaffi** [comment]
Hi Can you assign this to me?

**Comment by Hanaffi** [comment]
@nilsreichardt  Hi Can you assign this to me please?

**Comment by nilsreichardt** [comment]
@Hanaffi I'm unable to assign people because I'm not part of the NocoDB team. The reason why I could assign o1lab was that GitHub did this automatically after creating the issue.

**Comment by wingkwong** [comment]
@Hanaffi Assigned. Please feel free to ping the team members in Discord if you have any questions.

**Comment by wingkwong** [comment]
resolved in above PR
