### ISSUE TITLE
🐛 Bug:  NC_CONNECT_TO_EXTERNAL_DB_DISABLED without any function

### ISSUE THREAD

**Issue by prononext** [nocodb/nocodb#5987]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Using nocodb/nocodb:0.109.3 I was wondering why I do not see that create from external Database on my dashboard?

![image](https://github.com/nocodb/nocodb/assets/24569958/cf77f116-116e-408a-9fb4-506c86d84d45)

trying with and without true and false of NC_CONNECT_TO_EXTERNAL_DB_DISABLED did not change anything.

### Desired Behavior

- Standard fresh install should give the possibility of creating  a project via external database. 
- when using NC_CONNECT_TO_EXTERNAL_DB_DISABLED with true it should be deactivate
- when using NC_CONNECT_TO_EXTERNAL_DB_DISABLED  with false it should be active

### Project Details

nocodb/nocodb:0.109.3 docker
postgres12
redis6

**Comment by o1lab** [comment]
The screenshot above - from where is this ? This does not look like latest version of nocodb

**Comment by wingkwong** [comment]
@prononext `Create By Connecting To An External Database` has been removed from My Project page. Also `NC_CONNECT_TO_EXTERNAL_DB_DISABLED` is not in use in latest version. All project meta will be stored under `NC_DB`. However, you can still connect to external databases inside the project.
