### ISSUE TITLE
🔦 Feature: Monday as first day of week in calendar popup

### ISSUE THREAD

**Issue by NaleVex** [nocodb/nocodb#5988]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently popup calendar view only shows Sunday as first day of week which is not right for most European side of the world and use Monday as first day instead.
![f1e44c0015438911](https://github.com/nocodb/nocodb/assets/20393079/496edb1b-9036-4757-b941-527367105df2)

### Suggested Solution

Add a project setting to change first day to Monday when using calendar popup while changing value in date type column.

**Comment by frankMagoba** [comment]
Hi @o1lab can I work on this?

**Comment by dstala** [comment]
@frankMagoba let me know if you still wish to pick this up? this should be made configurable using an ENV variable

**Comment by frankMagoba** [comment]
Yes @dstala I wish to pick it up. Should I make it configurable via env?

**Comment by dstala** [comment]
No. Lets just make monday as first value always. So that weekend dates sit together in the end.
