### ISSUE TITLE
🐛 Bug: swagger not working

### ISSUE THREAD

**Issue by ramsigmoid** [nocodb/nocodb#5999]
git clone https://github.com/nocodb/nocodb
cd nocodb/packages

build nocodb-sdk
cd nocodb-sdk
npm install
npm run build

build frontend - runs on port 3000
cd ../nc-gui
npm install
npm run build:copy

build backend - runs on port 8080
cd ../nocodb
npm install
npm run start

swagger is not working

### if i do npm run watch:run then swagger works

Desired Behavior
swagger should work

Project Details
Node: v18.16.0
Arch: x64
Platform: linux
Docker: false
RootDB: pg
PackageVersion: 0.109.3

**Comment by wingkwong** [comment]
Please follow the commands in [Development Setup](https://docs.nocodb.com/engineering/development-setup).
