### ISSUE TITLE
Feat: Ability to set default ID type

### ISSUE THREAD

**Issue by OmgImAlexis** [nocodb/nocodb#602]
For example I'd like to use a `UUID` with `uuid_generate_v1()` as  the default value for all tables.

If there's a workaround for this please let me know.

**Comment by wingkwong** [comment]
Hi @OmgImAlexis, 

Have you tried the following steps?

- Create a column called ``UUID`` with Column Type ``SpecificDBType``
- Select ``uuid`` in Type in Database
- Input your generation function in Default value box

**Comment by OmgImAlexis** [comment]
@wingkwong that doesn’t let me set the default for all new tables.

**Comment by Chitsoehein** [comment]
hello dear bro first so sorry for my own problems of using mobile. I don't
have the laptop or desktop computer.dear sir,  now, used my ph is can not
get the download fully for requirements.only copy link or copy to clipboard
to sharing access that is use for me.I do the copy is nothing to rebuild.I
want the learning for coding portion. I need to update for security Parth
install for my ph I finding future opportunities for using my ph.I hearing
the OEM news is 2021 after android 6.0 is not available for support.
my ph is LenovoK5note a7020. before I don't have for coding and programming
knowledge. I got the mobile buying from Thailand.I seems  the first time of
codes is  from Google play store  . start to seen is android developer
apps. I used for trying to our mobile updated change better for something
gotten knowledge. interested the program for android apps.already trying
for miui and android os installion used mobile phone.but, not easy for
combination with used for me my mobile is not enough for 2 framework. I I
go the errors is my mobile broken aging in 7 or 10 already,🤕🤕🤕
can't learning the programming plan.now is learnings from sololearning apps
and
java developer apps and more than future.I apologies for copyright holder
for your privacy.I wanna login to GitHub to my profile. but every time isI
have the password problem sir.that is I can't login to GitHub profile to my
profile.please forgive me for my own problems.thhanks for understanding my
situation and wrong using system.

**Comment by wingkwong** [comment]
@OmgImAlexis Yes. That's my workaround.

**Comment by OmgImAlexis** [comment]
That’s not a workaround as the ID column still exists. Adding a new column isn’t the issue.

**Comment by wingkwong** [comment]
Actually you can delete the ID column If you don't need that. After that, you can create a new UUID column with PK.

**Comment by dstala** [comment]
@OmgImAlexis you can reopen this thread if your concern isn't solved by @wingkwong recommended workaround. Or you can reach out to us at community.nocodb.com
