### ISSUE TITLE
🐛 Bug: Error Cannot read properties of null (reading 'date_format') when import excel or csv file

### ISSUE THREAD

**Issue by Arkronus** [nocodb/nocodb#6035]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Import Excel file in attachment to PostgreSQL table
2. Receive error Cannot read properties of null (reading 'date_format')

[commerce_dashboard_data_11_07_2023.xlsx](https://github.com/nocodb/nocodb/files/12013755/commerce_dashboard_data_11_07_2023.xlsx)

DDL statement for table
```
CREATE TABLE commerce_dashboard_data (
	period_dt date NOT NULL,
	director varchar NOT NULL,
	city varchar NOT NULL,
	staff_coef numeric(20, 2) NULL,
	gross_profit_fot numeric(20, 2) NULL,
	id serial4 NOT NULL,
	staff_coef_2 numeric(20, 2) NULL,
	CONSTRAINT commerce_dashboard_data_pk PRIMARY KEY (id)
);
```

### Desired Behavior

Data succesfully inserted

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.3**

**Comment by pranavxc** [comment]
Thank you for reporting this issue. We'd like to help you get to the bottom of the problem you're facing. To do that, could you please provide us with the backend log? Having access to the log will enable us to identify the exact cause of the issue and assist you better.

Based on the details you've shared, it's possible that the problem might be related to the missing meta data in the date column, which includes the date_format. However, to confirm this, we need to analyse the backend log.

**Comment by Arkronus** [comment]
I cannot see background logs for import error, but I see other errors (like when user enters incorrect value). Where I can find logs in docker file system?

**Comment by dstala** [comment]
I was able to import attached XLSX file into a new table in v0.202.5 successfully. Upload file into an existing table feature is supported only for CSV. 
@Arkronus if you still see this issue, please reopen this thread
