### ISSUE TITLE
🐛 Bug: API name of Grid do not change after Duplicate

### ISSUE THREAD

**Issue by Productivix** [nocodb/nocodb#6038]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- have a table named "Sc_Reappro"
- duplicate it and rename into "Sc_Inventaire" in the NocoDb interface as Ower,
- in Swagger rest Api , you get : Sc_Reappro copy ( Sc_Inventaire grid )
-  and the 1st line (GET)  and the following are : "/api/v1/db/data/v1/effective_whitefish/Sc_Inventaire/views/Sc_Reappro copy"

('effective_whitefish' is the project name)

### Desired Behavior

 in Swagger rest Api , you should get : Sc_Inventaire ( Sc_Inventaire grid )
the  1st line (GET)  and the following are : "/api/v1/db/data/v1/effective_whitefish/Sc_Inventaire/views/Sc_Inventaire"

by the way as you should correct , I suggest to **simplify** the grid path into : 
"/api/v1/db/data/v1/effective_whitefish/Sc_Inventaire/views"

### Project Details

Node: **v18.14.2**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.109.3**

**Comment by pranavxc** [comment]
Renaming a table won't automatically update the names of any existing views associated with that table. If you rename the table, make sure to manually update the view names accordingly.

**Comment by Productivix** [comment]
Can and how the name of the grid in the API (the path see the screen copy to be sure of what we are speaking of ) can be changed ?
![Capture d’écran_2023-07-22_18-35-16](https://github.com/nocodb/nocodb/assets/6737060/9e5523b4-b69c-4693-b096-15828723651b)

**Comment by pranavxc** [comment]
You can rename the grid by double-clicking the view name in the right sidebar.


https://github.com/nocodb/nocodb/assets/61551451/874071b9-f8f7-42d0-86e1-80f1047cc855
