### ISSUE TITLE
🐛 Bug: field name 1st letter in Uppercase : no change in certain cases

### ISSUE THREAD

**Issue by Productivix** [nocodb/nocodb#6041]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- create a Postgresql table with a tool (DBeaver for ex) , create one field at least as a "primary key" and written in lowercase
- link that base in NocoDb
- see that the field name starts with a Uppercase letter
- you cannot change it in "edit" 

(if you create the table with Nocodb , this has no impact here, only if you link an existing dataBase)

This has an impact in mobile programs that address the data through the Nocodb API : the record field names have been changed)

### Desired Behavior

 I think the best is not changing the 1st letter case if the databases (as PostgreSQL) exists or the field name is a primary key

### Project Details

Node: **v18.14.2**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.109.4**

### Attachments
![column names in DBeaver](https://github.com/nocodb/nocodb/assets/6737060/d4845ce0-2e77-4316-aa78-8fce5720eeea)

![field_name-uppercase](https://github.com/nocodb/nocodb/assets/6737060/8100d259-f9bc-41d5-978a-4eddbbae484d)

**Comment by Productivix** [comment]
I remain at your disposal to explain : it is an important bug

**Comment by o1lab** [comment]
When connecting your database - you will have to use right inflection. See advanced params while connecting - see our [docs](https://docs.nocodb.com/setup-and-usages/dashboard#connecting-to-external-database).

**Comment by Productivix** [comment]
ok thank you , I did not saw ! good for every one. I remove the issue so.
