### ISSUE TITLE
🐛 Bug: Deleting tables/columns fails with "Cannot read properties of undefined (reading 'fk_index_name')"

### ISSUE THREAD

**Issue by mdebic** [nocodb/nocodb#6063]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

If I am trying to delete a table or a column in the table, I get the following error:

`Cannot read properties of undefined (reading 'fk_index_name')`

The table or column does not get deleted.

### Desired Behavior

To actual delete the table/column.

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.4**

**Comment by o1lab** [comment]
Straight forward delete is working.  So we will need more details on how this occurred like the table name, columns details. Plus was an external db connected or was a meta sync done ? If you can attach a small video that will help as well. Please show the fields menu before you attempt delete - that will be help ful

**Comment by mdebic** [comment]
There was somehow a complete mess with the docker volumes of my postgres db, which obviously had an impact on NocoDB, not clue how it got messed up. On first look I just thought it is related to NocoDB.

**Comment by tan-yong-sheng** [comment]
Hey, I have similar problem

![image](https://github.com/nocodb/nocodb/assets/64836390/632adcfb-860c-4115-b2cb-91e400c0117f)

Here is the error code:
![image](https://github.com/nocodb/nocodb/assets/64836390/88cd69c3-3314-403e-b06e-53f39232ac07)

![image](https://github.com/nocodb/nocodb/assets/64836390/6f2e10db-41de-40e2-82a2-ad5edde54701)
