### ISSUE TITLE
🐛 Bug: Webhook - After Insert event triggers 2+ requests if table has relation 

### ISSUE THREAD

**Issue by ghaccff** [nocodb/nocodb#6068]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create table "Project"
2. Create table "Source"
3. Add column "Sources" in "Project" table with one to many relation
4. Add a new project "Project1" record
5. Configure webhook for "Source" table 
    - Event = "After Insert"
    - Type = "URL"
6. Add a new Source record with "Project1" record linked
7. 3 requests are generated from created webhook 

### Desired Behavior

7. 1 request is generated after a record is created

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.109.4**

### Attachments

https://github.com/nocodb/nocodb/assets/1577090/35f1d53c-7178-4b85-95cb-23bb9c14f4e1

**Comment by ghaccff** [comment]
If a new record is added via table view (row is not expanded) then 2 requests are generated

**Comment by SchmaR** [comment]
Is there any estimate when this issue might be fixed? It is currently blocking me from updating since I've a use case which requires "at most once" delivery of the webhooks payload.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/6817
