### ISSUE TITLE
row level security workaround (implemented at the backend)

### ISSUE THREAD

**Issue by mayeulk** [nocodb/nocodb#6076]
Hello,
I'm thinking of workarounds or hacks to implement RLS (Row-Level Security) for Nocodb, in PostgreSQL, playing with constraints or triggers on the backend. (Motivation for studying this route: of the nocodb stack, Postgres is the part I know best).

I played a bit with things like:

```
ALTER TABLE nc_yvap___my_table
  ADD CONSTRAINT nc_yvap___my_table_check 
  CHECK (field_2 IS NOT NULL);
```
This works somehow as expected: row creation is prevented, with an error message (still, the error message is show as soon as we start to validate field_1)

 I tried this, to prevent inserts:
```
ALTER TABLE nc_audit_v2
  ADD CONSTRAINT nc_audit_v2_no_insert_check 
CHECK (op_sub_type != 'INSERT');

```
With nc_audit_v2_no_insert_check, the insert in the audit table does not occur, still, data are inserted in my_table.
I was hoping that both INSERTs (in my_table and in nc_audit_v2) would be in a PG transaction, so the failure of the second INSERT would allow to prevent the insertion in my_table.
In Audit.ts (https://github.com/nocodb/nocodb/blob/fe630d0db754d601ba6b2d91063e5303bf7b1ce5/packages/nocodb/src/models/Audit.ts#L77C1-L77C1 ) I read:
 // Will only await for Audit insertion if `forceAwait` is true, which will be true in test environment by default
Is this related to some kind of transaction management in test env., which could be used to achieve rejection of INSERT in my_table under some conditions?

I can see a "user" field in nc_audit_v2, which might open doors to user-based RLS. (See https://supabase.com/docs/guides/auth/row-level-security - thanks @pemontto)

Some ideas:
1) If UPDATEs, INSERT, DELETE on my_table and INSERT to nc_audit_v2 were in a transaction, I could add SQL constraints to nc_audit_v2 to implement RLS on my_table.

2) For INSERT and UPDATE on my_table, one could think of columns "created_by", "last_updated_by", as suggested in: https://github.com/nocodb/nocodb/issues/499
Then, a CONSTRAINT on "user" (in the sense of nc_audit_v2."user") would achieve some RLS:

ALTER TABLE my_table
ADD CONSTRAINT my_table_user_check 
CHECK (last_updated_by == created_by);

This would  work at least for updates (do not update a row you have not created).
For deletes, it could work too but with bigger changes, for instance something like forcing an update (to check the rights) before the delete:

```
BEGIN;
UPDATE my_table SET "last_updated_by" = current_user WHERE ID=1;
DELETE  FROM my_table WHERE ID=1;
COMMIT;

```

3) If the above is not possible, I'm thinking of a (more complex) rollback system:
If a row, related to a forbidden action on my_table, is inserted to nc_audit_v2, a trigger is activated, which rollbacks the offending action in my_table. nc_audit_v2.description would need to be formatted differently to help this. Also "Record with ID undefined has been inserted into my_table" (as seen in nc_audit_v2) is an issue. How users will see changes is another problem here.
For the rollback, a built-in trigger might be devised (otherwise: see the emaj rollback extension for PG: https://github.com/dalibo/emaj).

Thanks in advance for comments, and for this nice product!

Mayeul Kauffmann

### Discussed in https://github.com/nocodb/nocodb/discussions/640

<div type='discussions-op-text'>

<sup>Originally posted by **acivitillo** October 11, 2021</sup>
I am considering to use nocodb as an HRMS. In an HRMS we have employee information that should be visible only to the employee and their manager, this requires Row Level Security on top of the Project level one.

Are you guys considering RLS?</div>

**Comment by maeno14** [comment]
RLS is what Nocodedb needs to be serious. All the functionality it has is nice but without RLS is actually bad

**Comment by dstala** [comment]
To be tracked under

[🔦 Feature: Row / Column base permission, last edited by / updated by and audit log](https://github.com/nocodb/nocodb/issues/5075)

**Comment by sebdodt** [comment]
The workaround worked perfectly for me. Cheers!
