### ISSUE TITLE
🐛 Bug: insufficient and incorrect documentation for `/auth/token/refresh` endpoint

### ISSUE THREAD

**Issue by johnmpost** [nocodb/nocodb#6078]
### Please confirm if bug report does NOT exists already ?

- [x] I confirm there is no existing issue for this

### Steps to reproduce ?

https://apis.nocodb.com/#tag/Auth/operation/auth-token-refresh

this page is not clear. the description is "regenerate user refresh token," which is only half of what the endpoint actually does.

in addition, the "response sample" for the 200 ok response shows a "token" that is clearly not a JWT token. i suspect that it is actually a refresh token.

### Desired Behavior

the description for the endpoint should probably mention that it creates both a new refresh token AND a new JWT auth token for the user. the refresh token is sent as a cookie, and the JWT auth token is sent in the response body.

the "response sample" should be updated so that there is a fake JWT token in the "token" field.

### Project Details

not relevant

**Comment by aashishagrawall** [comment]
@dstala Can you assign this to me .
