### ISSUE TITLE
🐛 Bug: Filters return all records when specifying an incorrect field name

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#6081]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When we specify the incorrect field name, it returns all the records. 

```
curl --request GET \
  --url '<REDACTED>/api/v1/db/data/noco/<PROJECT_ID>/<TABLE_ID>/views/<VIEW_ID>?offset=0&limit=25&where=(NON_EXISTING_FIELD,eq,FOO)' \
  --header 'xc-auth: <REDACTED>'
```

### Desired Behavior

The expected behaviour would be returning 0 record.

### Project Details

Node: **v16.20.0**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.109.4**

**Comment by frankMagoba** [comment]
Hi @wingkwong  can I work on this?

**Comment by wingkwong** [comment]
@frankMagoba Assigned. Thanks.

**Comment by frankMagoba** [comment]
@wingkwong you can assign @amisdun he's already working on it.
