### ISSUE TITLE
🐛 Bug: In table, my filtered data are changing when the other editor or creator creates a filter 

### ISSUE THREAD

**Issue by Kartheravi** [nocodb/nocodb#6083]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a table and share the project with one more user and make them as a creator/editor. 
When both the users are working in a same table and if one changes the filter for the table, automatically the filter gets applied for all the users.

### Desired Behavior

The filter should be independent for individual user.

### Project Details

NocoDB used as docker : **true**
NocoDB version : **0.109.4**
Database used in NC_DB URL: -
OS version: Ubuntu **22.04**
Node.js version: -
Database version: **Postgres 15**

**Comment by o1lab** [comment]
That is the desired behaviour. The views are not specific to individual users.

**Comment by wingkwong** [comment]
Closing this issue as this is expected behaviour. Also replied in Discord.
