### ISSUE TITLE
🔦 Feature:  view the images in fullscreen mode by clicking on them in the gallery view.

### ISSUE THREAD

**Issue by NeonBubbles** [nocodb/nocodb#6084]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I can directly click on my pictures to view them in full screen in grid view, but I can't do this in the gallery view.
The images displayed directly in the gallery view are a bit small, sometimes they are not clear and I need to click to view in full screen. I often need to quickly view images.

### Suggested Solution

1. Allow users to click on images to enter full-screen viewing.
2. I hope the user can adjust the default display size of the images in the gallery view.
3. Be able to hide field names in the gallery view and directly display content. Otherwise, the gallery card will become too long if there are too many fields.

**Comment by dstala** [comment]
@NeonBubbles gallery view since v0.202.4 has been enhanced. If you still face any of these issues, please reopen this thread.

**Comment by gmdelisle** [comment]
Hi,
I'd like to reopen this ticket on this feature. 
As of September 2025, this feature is not present, even after the Gallery view enhancements in v0.202.4.

Attached a video on how [Teable](https://github.com/teableio/teable) handles clicking on an image in Gallery view. This is the requested behavior for this feature.

https://github.com/user-attachments/assets/73087f8a-0a8f-498f-9873-8ebe38b6f26e

* Clicking on an image in **Grid view** in NocoDB opens the _image_ in full screen.
* Clicking on an image in **Gallery view** opens the _record_ (with image record being hidden)

Love NocoDB. This is small quality of life improvement suggestion.
