### ISSUE TITLE
🐛 Bug: Values in currency fields are not saved [Firefox]

### ISSUE THREAD

**Issue by djmaze** [nocodb/nocodb#6086]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a new table, add a currency field (settings do not matter).
2. Enter a record and add a value in the currency field.
3. Refresh the table.
4. See that the currency value is gone.

In the network inspector, I can see that changing the field does not even trigger a request (as opposed to changing other fields in the record).

### Desired Behavior

Well.. The field should be saved of course.

### Project Details

```
Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.4**
```

**Comment by wingkwong** [comment]
I couldn't reproduce the issue (tried different Currency Locale & Currency Code). 

- Can you try the same steps on the new table to see if you can reproduce the issue?
- Can you try adding values to other field types to see if they can be saved or not? 
- Any specific errors you can find in the log?

![image](https://github.com/nocodb/nocodb/assets/35857179/c4aa9f70-a928-4a3b-92aa-50e7e51d5722)

**Comment by shashankvish0010** [comment]
I'm not able to reproduce the issue, even after refreshing page the currency value is there.

**Comment by djmaze** [comment]
Turns out this is (again, I experienced this before) a Firefox-specific problem. It works for me in Chromium and Brave, but not in Firefox (105.0).

**Comment by wingkwong** [comment]
@djmaze Thanks for the info. Now I can reproduce the issue on Firefox.

**Comment by distresscode** [comment]
I'm experiencing the same in Firefox. The behavior is similar to issue #4329 

App/Server: NocoDB 0.109.5 via Cloudron 7.5.0 on Ubuntu 22.04.

**Comment by johnmpost** [comment]
I am having the exact same issue

**Comment by wingkwong** [comment]
preliminary findings:
- `submitCurrency` is fired when it is blurred (e.g. click outside the cell) as expected
- `submitCurrency` is not fired when pressing `enter` (in firefox only)

**Comment by alexgtn** [comment]
same here

**Comment by Erudition** [comment]
Tried clicking outside of the field instead but it's not saved either.
Tried in Chromium and I get an error popup, `Record update failed a.includes is not a function`.

**Comment by davidbgk** [comment]
Confirmed with Firefox 121, the content is not saved if you press `Enter` but it *might* save the number if you `Tab` into another cell. Note that it doesn't work every time so beware.
