### ISSUE TITLE
Cell Scaled Picture/Attachment Thumbnail [Feature] 

### ISSUE THREAD

**Issue by Clarionhue** [nocodb/nocodb#6099]
Currently nocodb supports picture attachments and generates a thumbnail, but the thumbnail does not scale to the size of the cell's interior. Airtable does this the best as it auto scales based on the few cell height options it has. Seatable does something similar, but doesnt fully scale to the entire cell, instead leaving quite a noticeable border.

Is there plans to include this in a future version?

**Comment by dstala** [comment]
the feature is now enabled since release v0.202.4.
