### ISSUE TITLE
🔦 Feature: When multiple people edit data at the same time，can real-time refresh

### ISSUE THREAD

**Issue by houhoufm** [nocodb/nocodb#6103]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When multiple people edit data at the same time, manual refresh is still required; can real-time refresh be achieved? This experience will be better

### Suggested Solution

Set refresh time? I'm not a professional, I'm afraid I don't have good advice

### Additional Context

Fill out the form with colleagues, other people's additions and modifications cannot be seen in real time; I need to click reload to be able to

**Comment by dstala** [comment]
to be tracked under

[Feature : Realtime Collaboration](https://github.com/nocodb/nocodb/issues/148)
