### ISSUE TITLE
🐛 Bug: webhook response differs when EE is enabled

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6108]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Without license key configuration
```
{"type":"records.after.insert","id":"06cb76e2-8747-4cd0-9d99-ef7a050c4f6a","data":{"table_id":"md_2128ukr937l0hx","table_name":"Sheet-1","view_id":"vw_qy3c7hruwtd3wi","view_name":"Sheet-1","rows":[{"Id":1,"Title":"a"}]}}
```

With License key configuration
```
{
  "Id": 2,
  "Title": "b"
}
```

### Desired Behavior

let us have version-2 response by default for all new webhook when Enterprise keys are configured.

### Project Details

Node: **v16.20.0**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.2**

**Comment by wingkwong** [comment]
Here's some backgroud info. Let's call the detailed payload as v2 payload and the original one as v1 payload. 

1. Starting from a specific version (best guess > 0.105.4), the new webhook is considered as v2 and those created before this version will be set as v1 (See ncHookUpgrader.ts).
2. If the webhook version is v1, then v1 payload will be used.
3. If the webhook version is v2 AND
    - EE is enabled, then v1 payload will be used
    - Else, v2 payload will be used
