### ISSUE TITLE
🐛 Bug: Minor Airtable import issue if user is already in the nocodb space

### ISSUE THREAD

**Issue by briankinney** [nocodb/nocodb#6110]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1) Create an Airtable base with your email as an owner of the base
2) Create a new nocodb space with the same email address
3) Import the Airtable base using the UI
4) Import appears to fail. Tables do not appear in UI. Refreshing the page makes the tables appear.
5) Server logs read as follows

```
n [Error]: ****@****.com with role owner already exists in this project
at Function.badRequest (/usr/src/app/docker/main.js:1:654431)
at O.userInvite (/usr/src/app/docker/main.js:1:1201722)
at async Promise.all (index 3)
at async fe (/usr/src/app/docker/main.js:1:933652)
at async te.job (/usr/src/app/docker/main.js:1:938935)
at async i.jobWrapper (/usr/src/app/docker/main.js:1:897594)
at async run (/usr/src/app/node_modules/p-queue/dist/index.js:163:29)
```

### Desired Behavior

Airtable base is imported and tables immediately appear in the UI

### Project Details

NocoDB used as Docker
Default metadata store
Project created via UI

**Comment by mertmit** [comment]
Hi @briankinney, there was an issue about parsing and logging error messages to UI but this is a non-blocking issue for import, so it should continue even if you see those errors in the backend.

Are you sure there are no other errors? 

Feel free to contact me from our Discord channel if you would like to share base information for me to try

**Comment by briankinney** [comment]
I'm not sure that this was the only error. I initially thought that that the entire import had failed and started writing this bug report as if that were the case but then I refreshed the page and saw my tables.

I also feel that it should be an option to not import all the users from Airtable.

**Comment by mertmit** [comment]
That makes sense, thank you for your input.

I've created a feature request for you:
https://github.com/nocodb/nocodb/issues/6117

I will be closing this, as there seem to be misunderstanding.
Feel free to reopen or raise another issue.
