### ISSUE TITLE
🐛 Bug: Webhook doesn't work when condition is turned on

### ISSUE THREAD

**Issue by alprotasov** [nocodb/nocodb#6111]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

**STR**
1) Create a webhook with condition
2) Test it
See videos
**AR:**
Webhook doesn't work
**ER:**
Webhook works correctly
**Videos:**
https://records.cherishdev.com/conversations/8ce50788-01f4-5488-b7cd-ae8dc539ca37
https://records.cherishdev.com/conversations/2937c244-cda9-5634-a812-3475dadd6616

**EDITED:** It does work for webhook test. For real webhook it doesn't work at all

### Desired Behavior

It should just work :)

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.5**

**Comment by dstala** [comment]
Additional note : Webhook triggers work with condition. `Test webhook` fails when conditions are enabled.
