### ISSUE TITLE
🐛 Bug: XLSX Table Download Broken for Big Tables

### ISSUE THREAD

**Issue by ProbstenHias** [nocodb/nocodb#6116]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. open table with more than 300 rows
2. download table as xslx
3. open file
4. see that only 300 rows are in file, others are missing

### Desired Behavior

I would like to download all rows of a table

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.106.1**

**Comment by wingkwong** [comment]
I've tested a bit on the latest version (0.109.6) and it is working fine. I assume you haven't added any filters right? If there is no filter applied on the table, then I suggest to upgrade to the latest version and retry.

**Comment by nosorio2** [comment]
Hi, I tested the following: 

### Steps to reproduce: 

- Open a table with over 400 entries (in my case 3000)
- Download table as xslx
- Open file
- See that only 400 rows are in file, others are missing
- Go back to the browser (Microsoft Edge, Version 115.0.1901.188 (Official build) (64-bit))
- Browser requests permission to download more files
- Allow request
- 8 more files are downloaded, each containing 400 entries
- Total amount of files downloaded: 9 files

### Desired Behaviour

I would like that all entries are contained in the one xslx downloaded file 

### Project Details:

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.6**

**Comment by dstala** [comment]
@nosorio2 it was intended by design to break down larger file downloads into segments. You can control this behaviour by configuring time in `NC_EXPORT_MAX_TIMEOUT`. It defaults to 5000 milliseconds (5  seconds).
https://docs.nocodb.com/getting-started/self-hosted/environment-variables
