### ISSUE TITLE
🔦 Feature: Import into existing table

### ISSUE THREAD

**Issue by tino** [nocodb/nocodb#6118]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have a table already, and I want to add rows produced in another system. That system can export a CSV (or Excel). 

### Suggested Solution

Just like the "Quick Import From" I would expect a similar feature on an existing table.

Of course the headers will have to match, otherwise an error would be thrown.

**Comment by wingkwong** [comment]
Is it what you want?

![image](https://github.com/nocodb/nocodb/assets/35857179/27286169-8b8d-4480-8638-4d7beccc812e)

**Comment by tino** [comment]
Ahhhh, perfect!

I must say that that is well hidden 😅.
