### ISSUE TITLE
🐛 Bug: Sort from column header only works if other sorts are already applied

### ISSUE THREAD

**Issue by madebycaliper** [nocodb/nocodb#6119]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this
- Related to https://github.com/nocodb/nocodb/issues/5355 

### Steps to reproduce ?

- I created a new nocodb connection to my existing MySQL database
- Then I tried to select a sort option from the column

### Desired Behavior

Sorting should work via column header dropdown menu

### Project Details

```
Node: **v16.20.0**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.6**
```

### Attachments

![Screen Shot 2023-08-02 at 11 50 19](https://github.com/nocodb/nocodb/assets/5473496/663a894e-94ae-4484-8e29-d25de26b1fab)

**Comment by dstala** [comment]
works in release v0.111.0
reopen issue if you still notice this issue.
