### ISSUE TITLE
🐛 Bug: NC_SMTP_SECURE is always true

### ISSUE THREAD

**Issue by RuriRyan** [nocodb/nocodb#6124]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

We're running NocoDB in kubernetes and inject environment variables via kubernetes secrets. This shouldn't really matter how the variables got there, but just for completion purposes.

Whenever NocoDB restarts, for whatever reason, the value of NC_SMTP_SECURE is true, as we can't really check the value, we use the App Store to validate the config and then the Secure checkbox is true, as you can see in the screenshot below.
I manually checked the env variables inside the container to double check the value and as indicated by the second screenshot, the value of NC_SMTP_SECURE was actually false. Yet it still showed as true in the GUI settings. And of course sending mails didn't work.

The documentation states:
> NC_SMTP_SECURE  - For SMTP plugin (Optional) - To enable secure set value as true any other value treated as false

I didn't test any other values for NC_SMTP_SECURE, but removing it "fixed" the problem as now the value is actually false, even after a restart (confirmed by checking the config via the App Store again). 

Either there's a bug somewhere with the interpreting of environment variables, or the documentation is wrong.

### Desired Behavior

The value of NC_SMTP_SECURE should actually matter.

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.6**

### Attachments

![rustdesk_RSvMSCVb2X](https://github.com/nocodb/nocodb/assets/2413490/be1265e4-e7a8-4977-a381-b4156ea6292a)
![rustdesk_rFfte76udu](https://github.com/nocodb/nocodb/assets/2413490/8141db36-bd4f-4224-9c1b-370882424db8)

**Comment by wingkwong** [comment]
After checking the code, `NC_SMTP_SECURE` is used when `NC_SMTP_FROM`, `NC_SMTP_HOST` and `NC_SMTP_PORT` are provided. It will update SMTP configure in `nc_plugins_v2` table. Besides, I checked the value of `NC_SMTP_SECURE` with different values and they were expected. I didn't see secure is always true. If you've an access to your `NC_DB`, you may check the config of SMTP in `nc_plugins_v2` table.

**Comment by RuriRyan** [comment]
When readding NC_SMTP_SECURE:
![rustdesk_gI2436DPu3](https://github.com/nocodb/nocodb/assets/2413490/126bef6e-b58c-4618-98c1-0e70bd75cb1d)
I get an additioal "field" (?) in the DB, marked with yellow:
![rustdesk_NyiY0EgeD1](https://github.com/nocodb/nocodb/assets/2413490/16bd9533-2a9a-4090-99b0-634693fb8d8b)
This is also false, so far so good.

But sending emails still fails and the UI again shows secure as true.
![rustdesk_eDbKkug9ev](https://github.com/nocodb/nocodb/assets/2413490/e2b22ba8-816c-4c0d-9aa4-7bf3733b29bf)

**Comment by wingkwong** [comment]
@RuriRyan Thanks for the screenshot. I got the problem now.
