### ISSUE TITLE
🐛 Bug: QR-Code limited number of characters

### ISSUE THREAD

**Issue by xcojonny** [nocodb/nocodb#6128]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

create "singlelineText" and fill with URL with around 85 chars
create "QR code" column and choose newly created singleLineText column

with my iPhone I'm not able to read the QR code.

results in "undefined"

for a text with less chars its working fine

### Desired Behavior

display properly the URL when capturing the QR-Code

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.6**

**Comment by sreehari2003** [comment]
![image](https://github.com/nocodb/nocodb/assets/66205494/fe17c002-fb61-4b60-9b72-3b03f0411425)

## I tried  to reproduce the issue  , this is the bug you are referring here right ?

**Comment by xcojonny** [comment]
Yes. Right.

**Comment by sreehari2003** [comment]
@wingkwong  how does this should be done ? should I break the line or hide the overflow text ?

**Comment by wingkwong** [comment]
@sreehari2003 I believe the issue is that the QR code fails to show if the data is too long, given the current qr code version. 

The root cause is that we are using version: 4 (See `packages/nc-gui/components/virtual-cell/QrCode.vue`) which is not enough for storing such amount of data.

See https://github.com/soldair/node-qrcode#qr-code-capacity

> Each version has a different number of modules (black and white dots), which define the symbol's size. For version 1 they are 21x21, for version 2 25x25 e so on. Higher is the version, more are the storable data, and of course bigger will be the QR Code symbol.

<img width="439" alt="image" src="https://github.com/nocodb/nocodb/assets/35857179/376e784f-e7e7-48db-9301-9626c2fa7584">

<img width="740" alt="image" src="https://github.com/nocodb/nocodb/assets/35857179/e9119b98-f98a-41d5-9b7b-b77abfc8ed70">

**Comment by sreehari2003** [comment]
increasing the version will increse the qr code size , I should either limit user input size  or increase version right ? which is better  ? 

> @sreehari2003 I believe the issue is that the QR code fails to show if the data is too long, given the current qr code version.
> 
> The root cause is that we are using version: 4 (See `packages/nc-gui/components/virtual-cell/QrCode.vue`) which is not enough for storing such amount of data.
> 
> See https://github.com/soldair/node-qrcode#qr-code-capacity
> 
> > Each version has a different number of modules (black and white dots), which define the symbol's size. For version 1 they are 21x21, for version 2 25x25 e so on. Higher is the version, more are the storable data, and of course bigger will be the QR Code symbol.
> 
> <img alt="image" width="439" src="https://user-images.githubusercontent.com/35857179/258764298-376e784f-e7e7-48db-9301-9626c2fa7584.png"> <img alt="image" width="740" src="https://user-images.githubusercontent.com/35857179/258765149-e9119b98-f98a-41d5-9b7b-b77abfc8ed70.png">

**Comment by wingkwong** [comment]
@sreehari2003 I don't think you can limit the input as it is referenced from other columns. You may go for the latter. Please explore if there is any downsides first.

**Comment by sreehari2003** [comment]
> @sreehari2003 I don't think you can limit the input as it is referenced from other columns. You may go for the latter. Please explore if there is any downsides first.

if we increase the version for now in future if someone else input some URL more than the possible will cause same error right ? instead what if we show something like
![image](https://github.com/nocodb/nocodb/assets/66205494/24672410-3812-4d77-be6f-437f30043c47)

**Comment by wingkwong** [comment]
If so, then it shouldn't show the broken image at the first place.

![image](https://github.com/nocodb/nocodb/assets/35857179/210e68a2-108a-4b37-ab29-e08425b16d72)

**Comment by sreehari2003** [comment]
> If so, then it shouldn't show the broken image at the first place.
> 
> ![image](https://user-images.githubusercontent.com/35857179/258783006-210e68a2-108a-4b37-ab29-e08425b16d72.png)

yes I wanted to just ask for confirmation before doing it

**Comment by Sov3rain** [comment]
Also closes #5963

**Comment by xcojonny** [comment]
Awesome! thanks!
