### ISSUE TITLE
🐛 Bug: Single and Multi select both are not working in forms

### ISSUE THREAD

**Issue by ramsigmoid** [nocodb/nocodb#6131]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create table with single select and multiselect
create forms from above table
single and multiselect values are not getting populated.

### Desired Behavior

single and multiselect values should get populated. For each bug cannot update whole project, can we release changes list for fixes.

### Project Details

Node: **v18.16.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.109.0**

### Attachments

![image](https://github.com/nocodb/nocodb/assets/98207372/d2808657-a1ab-4e83-9c3d-fe34262d1d60)

**Comment by wingkwong** [comment]
@ramsigmoid please try on the latest version. There're some bug fixing in the past few releases related to select fields.

![image](https://github.com/nocodb/nocodb/assets/35857179/729e2e2b-dd55-4530-aba6-975d1a66a52f)

**Comment by mustafaazad03** [comment]
Is this issue open ?? can I contribute ??

**Comment by ramsigmoid** [comment]
> @ramsigmoid please try on the latest version. There're some bug fixing in the past few releases related to select fields.
> 
> ![image](https://user-images.githubusercontent.com/35857179/258563367-729e2e2b-dd55-4530-aba6-975d1a66a52f.png)

can you tell me which files has been modify for this bugs, so will replace those files only?

**Comment by ramsigmoid** [comment]
> Is this issue open ?? can I contribute ??

yes

**Comment by wingkwong** [comment]
@mustafaazad03 I believe the issue has been fixed already as I couldn't reproduce with the latest version. 
@ramsigmoid I won't recommend that. You should upgrade `nocodb` to the latest version instead. How do you start your application? Are you using `nocodb-seed` or just running locally?

**Comment by ramsigmoid** [comment]
running locally with development setup

**Comment by wingkwong** [comment]
@ramsigmoid If you are cloning our repository, you can just pull the latest source code. If you are starting a node app, you can just runt `npm uninstall nocodb` and run `npm install nocodb` back.
