### ISSUE TITLE
🐛 Bug: Couldnot send the sample payload data to mail using webhook

### ISSUE THREAD

**Issue by Nishanth1806** [nocodb/nocodb#6132]
### Please confirm if bug report does NOT exists already ?

- [x] I confirm there is no existing issue for this

### Steps to reproduce ?

I tried to send data to my mail from my payload using webhooks. The datas are available in the image:
![image](https://github.com/nocodb/nocodb/assets/116356018/f7f8dc61-2107-4dac-b34b-4b596e99d749)

Whenever i triggered the webhook, it sends the data as follows:
![image](https://github.com/nocodb/nocodb/assets/116356018/52896985-4869-47b5-95b6-49445223599a)

### Desired Behavior

The payload must be send to mail directly as required

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.4**

**Comment by wingkwong** [comment]
preliminary finding - paylaod format seems not matched with the actual one.

**Comment by dstala** [comment]
moustache syntax is deprecated; webhook response by default will be static & standard response - samples are here

https://docs.nocodb.com/automation/webhook/create-webhook/#webhook-response-sample
