### ISSUE TITLE
🐛 Bug: The filter when searching the table as specified in the description (where=(colName,like,%name) ) does not work with Cyrillic.

### ISSUE THREAD

**Issue by a-sukhan** [nocodb/nocodb#6135]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Such a filter as specified in the description (where=(colName,like,%name) ) takes case when searching. The problem is only when working with Cyrillic characters. It works correctly in Latin characters. If there is a word "Cava" in the table and I search for the word "cava", it works correctly. If the table contains the word "Bread" (in Russian "Хлеб") and I search for "bread" (in Russian "хлеб"), it does not find it.

### Desired Behavior

If a table has fields with values containing the words "Хлеб" and "хлеб" in Russin, then a search for the word "хлеб" should produce both values.

### Project Details

Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.6**

**Comment by dstala** [comment]
@a-sukhan this appears to work fine in latest release v0.202.5; I tried example with хлеб over swagger & filter in UI. if you are still seeing this issue persist, please re-open this issue.
