### ISSUE TITLE
Feature : Bulk update relational columns via API 

### ISSUE THREAD

**Issue by mwolfaardt** [nocodb/nocodb#6144]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Use the API to update a colum for all rows to a related table

### Desired Behavior

Bulk update using the API

### Project Details

Using in Docker with the latest version and MySQL
I do a post to http://myhost/api/v1/db/data/bulk/noco/p_mqkjuzdj6okyqe/Product/ to update the products table and set the supplier column to a referencing table
My body that I submit looks like : 

```
[{
    "Supplier" : [{
                    "Id": 1,
                    "Title": "Supplier ABC"
                }],
    "nc_ptnp___nc_m2m_eaie951o4r List": [
                {
                    "table2_id": 1,
                    "table1_id": 2
                }
            ]
}]
```

I get the amound to rows back as a response, but there is no update to the rows

**Comment by dstala** [comment]
With v2 data APIs, you can bulk update relational columns via API. 
https://data-apis-v2.nocodb.com/#tag/Table-Records/operation/db-data-table-row-nested-link

@mwolfaardt please reopen this issue if you still prefer to propose further enhancements
