### ISSUE TITLE
🐛 Bug: REST API filter get data outside conditions. 

### ISSUE THREAD

**Issue by Rafurus** [nocodb/nocodb#6148]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I'm using n8n integration.
In node I get 1 row where filter is (quotaLimit,gt,0)~and(domainList,like,www.vredacted.com)
In noco I have table with keys that need to be downloaded. 
The problem is that this filter sometimes is getting wrong damainList - it's getting www.zredacted.com.pl which is row 5 on screen instead of row 9.

Since there in no contains filter I'm using like.

<img width="691" alt="image" src="https://github.com/nocodb/nocodb/assets/12428720/d7dd9c9c-ee1a-4aeb-8cab-245935415a68">

### Desired Behavior

Filter should get only data within conditions. 

### Project Details

Docker
Version 109.6
pg 15.1
Ubuntu 20.04.6 LTS
Node 17.9

**Comment by wingkwong** [comment]
> it's getting [www.zredacted.com.pl](http://www.zredacted.com.pl/) which is row 5 on screen instead of row 9.

Why row 9 only? row 10 seems also matching with the condition. 

Also, does row 5 contain other records also?

**Comment by Rafurus** [comment]
> > it's getting [www.zredacted.com.pl](http://www.zredacted.com.pl/) which is row 5 on screen instead of row 9.
> 
> Why row 9 only? row 10 seems also matching with the condition.
> 
> Also, does row 5 contain other records also?

Row 5 have only 1 domain - z. 

Row 10 is also matching but I get 1 by 1 row that matching conditions and then do something with them.

**Comment by Rafurus** [comment]
Additional important information:
I do of course loop when i get one by one row. 
And first loop is GOOD, second one is BAD. 
Right now i don't know if it's nocodb problem with api or that n8n is ommiting filters in loop.

**Comment by dstala** [comment]
@Rafurus you still have this issue? we now have v2-data-apis. you can try them out! 
https://data-apis-v2.nocodb.com/

please reopen this issue if you still have problems with filters
