### ISSUE TITLE
🐛 Bug: Not able to directly set the display column as formula type

### ISSUE THREAD

**Issue by briankinney** [nocodb/nocodb#6150]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a new table
2. Edit the type of the display column
3. Search for formula type in type selector drop down menu
4. Formula type is not available

### Desired Behavior

Formula type is available in the list.

Note: I put this as a bug because I was able to set an existing formula-type column as the display column. Perhaps the bug is that I am able to bypass the intended no-formulas-as-display columns limitation?

It also seems that formulae as display column is not totally supported because I was also unable to convert the display column type from formula to text. I am met with this error message.
        ```Updating SingleLineText => SingleLineText is not implemented```

### Project Details

Running nocodb docker
Version 0.109.5
Postgres backend

**Comment by wingkwong** [comment]
When you say display column, do you mean [Display Value](https://docs.nocodb.com/setup-and-usages/display-value])? In fact, we don't have implementation for changing the existing type to certain types such as lookup, LTAR, formula, and etc. For example, let's say I have a column with `SingleLineText` type with some arbitrary data on it, it is not possible to have a formula generating such data. 

What is the reason you don't create a new formula but editing existing SingleLineText one? When you create a formula column, you can set it as display value. Here's the screenshot from 0.109.7.

<img width="694" alt="image" src="https://github.com/nocodb/nocodb/assets/35857179/860fd819-3656-442d-9896-fff9c3be2ace">

**Comment by briankinney** [comment]
Yes I do mean Display Value

> What is the reason you don't create a new formula but editing existing SingleLineText one?

If I want to have a formula column as my Display Value I will certainly create a new formula and then set it to be the Display Value. The bug here is that I can't do it by modifying the existing column set as the Display Value. It's not that I need this to work in order to get something done, but it is against my expectation when I try to interact with the Display Value. I don't need conversion of a column from Text -> Formula to preserve the values. I understand that would be impossible.

The secondary issue here (which I think should be its own bug but I thought it was connected initially) is that I was not able to convert a formula column to a text column. This definitely should work.

**Comment by wingkwong** [comment]
I second that. Actually this implementation is just missing. For `SingleLineText -> Formula`, a message box should show to warn users the column will be erased as the data cannot be preserved. For `Formula -> SingleLineText`, the exact value should be preserved. Moreover, there would be other cases like `Formula -> Number`, then we need to check if it is compatible to convert. Also since formula is a virtual column, we may need to take care about it as well.

**Comment by nowrds** [comment]
I had the same problem when importing tables from Airtable where I had set the display column as a formula. As a result, the field was not created/imported correctly.

After a few tests it seems that you can't change **any** existing field type to Formula, so you always have to create a new column and set the type to Formula before using it. This is not only very annoying, but also confusing. 

Running nocodb docker
Version: 0.111.3

**Comment by dstala** [comment]
Type conversion for formula field is disabled to avoid confusion. And Formula field can now be set as display value too.
