### ISSUE TITLE
🐛 Bug: File name extends the area on CSV import.

### ISSUE THREAD

**Issue by shashankvish0010** [nocodb/nocodb#6151]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Steps to reproduce:
1. Import a CSV file with a large filename.
2. You will see that the filename extends the area.

### Desired Behavior

The filename should fit inside the box.

### Project Details

Version 0.109.4

### Attachments

![Screenshot (268)](https://github.com/nocodb/nocodb/assets/140178357/c94be805-ba9e-47fe-a93a-f5ebb3eb278e)

**Comment by dstala** [comment]
doesn't occur in v0.202.5
