### ISSUE TITLE
🐛 Bug: nested[where] doesn't work with primary key if have display value

### ISSUE THREAD

**Issue by namnhfreelancer** [nocodb/nocodb#6154]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Table "members" have column member_id (primary key), member_name (Display Value when use in UI) , member_roles (many to many with table roles)
2. Table "roles" have column role_id (primary key), role_name (Display Value when use in UI)), role_members (many to many with table members)

### Desired Behavior

When use API in table members with nested[member_roles][where]=(member_roles,eq,SAMPLE_ROLE_ID) it doesn't work (Return all data instead of only filtered data)

It only work if use nested[member_roles][where]=(member_roles,eq,SAMPLE_ROLE_NAME)

I expect when use this api, we alway use primary key, not display value (Value use only for display) because primary key is not duplicate and it is identify of a row, not display value

### Project Details

NocoDb 109.6

**Comment by dstala** [comment]
@namnhfreelancer 
For `Links` field : now we display rollup count & hence nested where clause is no more supported

In older versions (you were on v 109.6), the way you were using the query was incorrect. You need to specify field name from adjacent table. 

example: 
nested[member_roles][where]=(role_id,eq,SAMPLE_ROLE_ID)

**Comment by dstala** [comment]
reopen this thread if you have any more queries. apologies for delayed response on this
