### ISSUE TITLE
🔦 Feature: In embedded view, anybody should be able to copy cells

### ISSUE THREAD

**Issue by Angeall** [nocodb/nocodb#6155]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

For someone that has never logged in to NoCoDB, or has no account, it is currently impossible to copy the value of a given cell in a public embedded shared view.

For example, in private navigation mode, the contextual menu does not appear when right clicking on a cell, and it is hence impossible to copy the value.

### Suggested Solution

For anyone, logged in or not, private navigation included, show a contextual menu in the embedded shared view to copy the value of the selected cell(s)

**Comment by frankMagoba** [comment]
Can I work on this?

**Comment by frankMagoba** [comment]
Is this still up @o1lab ?

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/6922
