### ISSUE TITLE
🐛 Bug: Filters in GUI also affects the data API

### ISSUE THREAD

**Issue by CorinnaHe** [nocodb/nocodb#6159]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

**Problem:** Filters in GUI also affects the data API

**Steps to Reproduce:**

Table without Filters in GUI:
<img width="542" alt="image" src="https://github.com/nocodb/nocodb/assets/26124563/1a95d274-f837-4664-8c33-85aa99ee9ee5">

**1. Query the table via the data API without any active filter in the GUI**
base_url/api/v1/db/data/noco/project_name/table_name

`{
  "list": [
    {
      "Id": 1,
      "Title": "a",
      "CreatedAt": "2023-08-11 08:42:17+00:00",
      "UpdatedAt": "2023-08-11 08:42:20+00:00"
    },
    {
      "Id": 2,
      "Title": "b",
      "CreatedAt": "2023-08-11 08:42:22+00:00",
      "UpdatedAt": "2023-08-11 08:42:22+00:00"
    },
    {
      "Id": 3,
      "Title": "c",
      "CreatedAt": "2023-08-11 08:42:24+00:00",
      "UpdatedAt": "2023-08-11 08:42:24+00:00"
    },
    {
      "Id": 4,
      "Title": "d",
      "CreatedAt": "2023-08-11 08:42:26+00:00",
      "UpdatedAt": "2023-08-11 08:42:26+00:00"
    }
  ],
  "pageInfo": {
    "totalRows": 4,
    "page": 1,
    "pageSize": 25,
    "isFirstPage": true,
    "isLastPage": true
  }
}`
**2. Create Filter in the GUI**
<img width="799" alt="image" src="https://github.com/nocodb/nocodb/assets/26124563/166d7b4a-628b-4b48-a72f-9f74b3f8755d">

**3. Query the data api** 
`{
  "list": [
    {
      "Id": 1,
      "Title": "a",
      "CreatedAt": "2023-08-11 08:42:17+00:00",
      "UpdatedAt": "2023-08-11 08:42:20+00:00"
    }
  ],
  "pageInfo": {
    "totalRows": 1,
    "page": 1,
    "pageSize": 25,
    "isFirstPage": true,
    "isLastPage": true
  }
}`
-> we get back the filtered rows also via the API without it knowing that there are filters in place

### Desired Behavior

A Filter in the GUI should not be affecting the API.

Currently we are preventing not getting back all of the rows via the API by creating a view for every table that should be specifically used for filtering. But if someone filters the original table by accident, we won't get back the expected result from the API.

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.5**

**Comment by edohay** [comment]
I have exactly the same issue with API and GUI

**Comment by woutervddn** [comment]
I'm also faced with this issue.

That being said, the issue type is not set so in the project board this issue is not visible under 'bugs'.

**Comment by jomarspiral** [comment]
same here

**Comment by dstala** [comment]
will be fixed in v0.202.6
https://github.com/nocodb/nocodb/pull/6941
