### ISSUE TITLE
🐛 Bug: Text overflows in form

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#6173]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Put large text longtext in form

![image](https://github.com/nocodb/nocodb/assets/86340924/e5f05574-e5ff-459a-8dad-f1808f6c564d)

### Desired Behavior

Should not overflow

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.109.4**

**Comment by wingkwong** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/6121. Please wait for the next release.
