### ISSUE TITLE
🐛 Bug: Hidden tables showing up

### ISSUE THREAD

**Issue by ghost** [nocodb/nocodb#6179]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I am not sure, I was just creating new tables and then they started showing up.

### Desired Behavior

These tables should now show up

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.109.7**

### Attachments

![Screenshot 2023-08-14 192715](https://github.com/nocodb/nocodb/assets/103607256/1a07723b-5216-46e7-af6d-e2c3c4b06f78)

**Comment by o1lab** [comment]
You can disable M2M tables here. 

Between you mentioned about an error in reddit - Do you have more details and logs for it ? DM in discord with more details.

**Comment by wingkwong** [comment]
It could be disabled in Team & Settings > Project Setting > Untick Show M2M Tables

![image](https://github.com/nocodb/nocodb/assets/35857179/e7ad3dfd-ed40-4b84-9cfb-15815b6a6789)
