### ISSUE TITLE
🐛 Bug: Cannot import xlsx ods csv tables in Docker

### ISSUE THREAD

**Issue by mayeulk** [nocodb/nocodb#6192]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I manage to upload files  but not to import them, even if they are very simple.
I first have messages like:
"Uploaded file test_table.xlsx successfully"
Then, 
When trying to import csv file: the error message is:
"node wa not found"

When trying to import one of these file types: xlsx, ods: 
the error message is "f[0] is undefined"

all files (created with LibreOffice Calc) have this content (see attachments; below: csv content)
```
col1,col2
1,a
2,z
3,e
4,r
5,t
```
(Same with other more complex files that I cannot share).
Edit: as first column header, I initially had "id", but replacing with "col1" does not fix the bug.

Same error with 3 options  checked or unchecked:
Auto-Select Field Types
Use First Row as Headers
Import Data

There are no new lines in the logs of the nocodb and postgres containers.

### Desired Behavior

Table should be imported

### Project Details

Project was created: New Project by connecting to external database
The project already has some tables (some where already in pg at project creation, some created later with NocoDB GUI).

NocoDB used as docker: true
NocoDB version: from Docker, built yesterday, see below
Docker-compose containing a root_db service (container running pg, Dockerfile starting with: FROM postgres:15.3-alpine3.18)

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.7**

### Attachments

![nocodb_xlsx_import_fails](https://github.com/nocodb/nocodb/assets/768570/0af4e397-3ee6-41b7-9ca0-f83351f85a0e)
[test_table.xls](https://github.com/nocodb/nocodb/files/12378356/test_table.xls)
[test_table.xlsx](https://github.com/nocodb/nocodb/files/12378357/test_table.xlsx)
[testtable.csv](https://github.com/nocodb/nocodb/files/12378358/testtable.csv)
[test_table.ods](https://github.com/nocodb/nocodb/files/12378359/test_table.ods)
[testtable2.csv](https://github.com/nocodb/nocodb/files/12378926/testtable2.csv)

**Comment by wingkwong** [comment]
Any detailed error logs you can share? I've tried those 5 attached files and all could be uploaded.

![image](https://github.com/nocodb/nocodb/assets/35857179/9e1c81cd-b51c-4dbb-b97d-aacf93ded2a3)

**Comment by mayeulk** [comment]
Problem was: in a Virtualbox VM shared folder (host: WIndows, guest: Ubuntu), group and owner of the files were root:root.
Solution: move files in /home/my_user, then import them into Nocodb

**Comment by mayeulk** [comment]
For completeness, for those having this issue and wanting to avoid having to move the files, a different mounting procedure might help avoid this issue:

https://askubuntu.com/questions/747974/virtualbox-shared-folders-are-owned-by-root-in-lubuntu-guest

https://forums.virtualbox.org/viewtopic.php?t=75833

https://superuser.com/questions/640027/why-cant-i-chown-a-virtualbox-shared-folder
