### ISSUE TITLE
What could cause HTTP 431 response to socket.io POST ?

### ISSUE THREAD

**Issue by Pierric82** [nocodb/nocodb#6193]
Hi,

I'm not opening this as a bug as I'm pretty sure it has something to do with my setup.

I have nocoDB run as a container, and it auto-upgrades via WatchTower (bad practice, I know!) I only check in from time to time, and today I found it was now broken. The current version is 0.109.7.

I run this behind a reverse proxy. I can log in and see my landing screen with my project, but there are already errors in the browser console. If I go into the project, I get pings about errors in the page, and the same kind of errors in the console. The errors are all about POSTs to URLs starting with /socket.io that go wrong. In the console I see error 500, because of the proxy. But the proxy itself logs errors 431:
```
2023/08/18 12:57:03 [error] 568#568: *1575 auth request unexpected status: 431 while sending to client, client: x.x.x.x, server: rows.*, request: "POST /socket.io/?EIO=4&transport=polling&t=Oe8IgEG&sid=MpR2p7DKRCgPsXvzAAAP HTTP/2.0", host: "rows.x.net", referrer: "https://rows.x.net/dashboard/"
```

What could be causing this error (this setup worked in the past with earlier version of nocodb, though I couldn't give you the last version I'm aware was working). Thanks in advance for any help!

P.

**Comment by wingkwong** [comment]
may relate to #6157. cc @lolgopher

**Comment by lolgopher** [comment]
give the information below, I can check it in more detail about 431 error.

- contents of the request where the error occurred(use chrome developer tools)
- more details about your reverse proxy environment(ex. nginx configuration file)
- information about the nocoDB container(ex. docker inspect)

**Comment by Pierric82** [comment]
Hi @lolgopher !
Thanks for this.

- [Here](https://pastebin.com/b1UYQcq6) is a paste bin of the curl-style request copied from chrome dev tools for one of the errors.
- My nginx runs via a linuxserver Docker container (swag), I've put the nocodb config, as well as the couple of files it relies on, all in [this pastebin](https://pastebin.com/H3vGX9yr)
- It runs behind Authelia as extra authentication, which hasn't been a problem in the past. I'm not including those files but let me know if you think it'd be relevant.
- output of `docker inspect nocodb` is [here](https://pastebin.com/CG9MNx2v)

And for completeness here's the fresh log of errors captured by nginx:
```
2023/08/21 10:52:59 [error] 565#565: *70328 auth request unexpected status: 431 while sending to client, client: 192.168.1.40, server: rows.*, request: "POST /auth/token/refresh HTTP/2.0", host: "rows.domain.net", referrer: "https://rows.domain.net/dashboard/"
2023/08/21 10:53:02 [error] 565#565: *70328 auth request unexpected status: 431 while sending to client, client: 192.168.1.40, server: rows.*, request: "POST /socket.io/?EIO=4&transport=polling&t=OeNJ2pO&sid=WBTkvs43b-3f2QM4AAAS HTTP/2.0", host: "rows.domain.net", referrer: "https://rows.domain.net/dashboard/"
2023/08/21 10:53:02 [error] 565#565: *70328 auth request unexpected status: 431 while sending to client, client: 192.168.1.40, server: rows.*, request: "POST /socket.io/?EIO=4&transport=polling&t=OeNJ2rE&sid=WBTkvs43b-3f2QM4AAAS HTTP/2.0", host: "rows.domain.net", referrer: "https://rows.domain.net/dashboard/"
2023/08/21 10:53:02 [error] 565#565: *70328 auth request unexpected status: 431 while sending to client, client: 192.168.1.40, server: rows.*, request: "POST /socket.io/?EIO=4&transport=polling&t=OeNJ2rI&sid=Q3MMNyR10OwjD5HKAAAU HTTP/2.0", host: "rows.domain.net", referrer: "https://rows.domain.net/dashboard/"
2023/08/21 10:53:02 [error] 565#565: *70328 auth request unexpected status: 431 while sending to client, client: 192.168.1.40, server: rows.*, request: "POST /socket.io/?EIO=4&transport=polling&t=OeNJ2rK&sid=7xUsGbe-ggTMURB2AAAT HTTP/2.0", host: "rows.domain.net", referrer: "https://rows.domain.net/dashboard/"
2023/08/21 10:53:03 [error] 565#565: *70328 auth request unexpected status: 431 while sending to client, client: 192.168.1.40, server: rows.*, request: "POST /socket.io/?EIO=4&transport=polling&t=OeNJ2ru&sid=Q3MMNyR10OwjD5HKAAAU HTTP/2.0", host: "rows.domain.net", referrer: "https://rows.domain.net/dashboard/"
2023/08/21 10:53:03 [error] 565#565: *70328 auth request unexpected status: 431 while sending to client, client: 192.168.1.40, server: rows.*, request: "POST /socket.io/?EIO=4&transport=polling&t=OeNJ2s2&sid=7xUsGbe-ggTMURB2AAAT HTTP/2.0", host: "rows.domain.net", referrer: "https://rows.domain.net/dashboard/"
2023/08/21 10:53:06 [error] 565#565: *70328 auth request unexpected status: 431 while sending to client, client: 192.168.1.40, server: rows.*, request: "GET /api/v1/auth/user/me?project_id=p_rz1l2e602tdoz4 HTTP/2.0", host: "rows.domain.net", referrer: "https://rows.domain.net/dashboard/"
2023/08/21 10:53:06 [error] 565#565: *70328 auth request unexpected status: 431 while sending to client, client: 192.168.1.40, server: rows.*, request: "GET /api/v1/db/meta/projects/p_rz1l2e602tdoz4/users?limit=10&offset=0&query= HTTP/2.0", host: "rows.domain.net", referrer: "https://rows.domain.net/dashboard/"
```

I hope that's sufficient, let me know otherwise!

**Comment by lolgopher** [comment]
Hello @Pierric82,

I've reviewed the provided logs and information, but request copied from chrome dev tools was Not Found.
It appears that the 431 error is likely occurring due to the usage of Authelia in conjunction.
To resolve this, I recommend referring to the following post:

https://stackoverflow.com/questions/66554067/nginx-431-request-header-fields-too-large-in-reverse-proxy

**Comment by Pierric82** [comment]
Hi @lolgopher ,

Thank you so much for your time and advice. You were spot on, my nginx in the swag container was set up for 32k headers, and Authelia had no specific setting. Explicitly setting this to 32k as per the link you shared did the trick and now nocodb runs fine again. I suppose noco is the only thing I'm self-hosting that makes use of big headers, which is why nothing else was causing issues and that misled me to look only at noco!

Really appreciate the help! 👏 👏
