### ISSUE TITLE
🐛 Bug: Swagger is not openned in https from the https dashboard

### ISSUE THREAD

**Issue by Productivix** [nocodb/nocodb#6195]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

open in https the dashbord, open "Swagger REST API" from the menu
https://user-images.githubusercontent.com/6737060/261594754-c5bff459-5f97-4d4f-960d-98253c552705.png
you get in the Swagger page an url in https , ok but the server and curt requests are in "http" :
![swagger_http](https://github.com/nocodb/nocodb/assets/6737060/75bd098c-fa6f-4a97-9b8b-f32a888114d0)

### Desired Behavior

the server choice to be in HTTPS

### Project Details

Node: **v18.14.2**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.109.7**

**Comment by wingkwong** [comment]
Have you set `NC_PUBLIC_URL` explicitly?

**Comment by Productivix** [comment]
I do not know where is that setting : can you please tell me ?

**Comment by wingkwong** [comment]
You can set environment variables in `.env`. If `NC_PUBLIC_URL` is not specified, then the value should come from the request.

**Comment by Productivix** [comment]
is it documented on https://docs.nocodb.com/getting-started/environment-variables as useful for email id , ... 
I changed it to https : no change in swagger server, 
I have now in .env the following settings , beside my password and login:
`NUXT_PUBLIC_NC_BACKEND_URL: "https://lic.productivix.eu/"
NC_PUBLIC_URL: "https://lic.productivix.eu/"`
and still a Swagger server at http value.

**Comment by Productivix** [comment]
still not working, NO documentation corresponding to NC_PUBLIC_URL
??

**Comment by wingkwong** [comment]
May I know how you start your app? are you using seed? running locally?

**Comment by Productivix** [comment]
hi, yes indeed : I run it on Node under a pm2 process : (https://pm2.keymetrics.io/) 
I type the command : 
`pm2 start "npm run start"`
because I cannot put your process inside a process list like "ecosystem" , it is not adapted. If could do adaptations, I would be top !

**Comment by Productivix** [comment]
hi, 
thanks, I did that all, 

The .env has inside  : ```
NC_DISABLE_AUDIT='true'
NC_PUBLIC_URL: "https://lic.productivix.eu/"
```
I am not sure of this .env cause "NC_PUBLIC_URL" is not documented .

and the swagger server is still http.

**Comment by wingkwong** [comment]
please DM me at Discord.

**Comment by dstala** [comment]
@Productivix was the issue resolved?

**Comment by Productivix** [comment]
Hi, not at my knowledge, my prod version has remained in 0.111.0

**Comment by wingkwong** [comment]
From the previous discussion, here's the summary.

- the protocol is from the request side. 
- suspecting something from nginx side. 
- couldn't reproduce locally. need the exact VPS setup for reproduction
- workaround: correct it by using custom url in swagger ui

**Comment by Productivix** [comment]
Yes right
I looked in Nginx config but do not found.
and the workaround: correct it by using custom url in swagger ui, works
I can close it for now
