### ISSUE TITLE
🔦 Feature: Formatting on formula fields

### ISSUE THREAD

**Issue by philoptimusprime** [nocodb/nocodb#6197]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

The ability to format data in **Formula** and **Look Up** Fields.

### Suggested Solution

When doing formulas for Currency this could display as currency format in the formula field:

e.g.:
![Screenshot 2023-08-18 221605](https://github.com/nocodb/nocodb/assets/103607256/9070663c-2887-42f8-ae4c-7a93b920bc86)

**Comment by frankMagoba** [comment]
Hi @wingkwong can I pick this up?

**Comment by wingkwong** [comment]
@frankMagoba Assigned. Suggested to show me your proposal first before actual implementation. Please free feel to DM me at Discord.

**Comment by frankMagoba** [comment]
Hi @wingkwong I sent you a DM on discord

**Comment by Brausmith** [comment]
Adding my support for this feature.

**Comment by wingkwong** [comment]
For anyone who is interested in this feature, please DM me at discord for discussion first.

**Comment by dstala** [comment]
Related 
[[Enhancement] add the function of "number format options" under the rollup column](https://github.com/nocodb/nocodb/issues/5312)
