### ISSUE TITLE
🐛 Bug: Redo doesn't work on macOS

### ISSUE THREAD

**Issue by bird-in-a-tree** [nocodb/nocodb#6200]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Do some edit
- Press CMD+Z to Undo
- Press CMD+SHIFT+Z
- Undo is performed instead of expected Redo

### Desired Behavior

Redo operation on CMD+SHIFT+Z

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.109.2**

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. Please use the latest version as there was some bug fixing related to redo/undo in recent releases. Please free feel to reopen if issue persists.
