### ISSUE TITLE
🐛 Bug: QR Code Column gets deleted on Sync Metadata

### ISSUE THREAD

**Issue by xcojonny** [nocodb/nocodb#6206]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create new Column with type QR-Code
2. Go to Settings and Data Sources -> Sync Metadata -> Sync State "Column removed (QR-Code)"
3. Press "Sync Now"
4. Column is deleted

### Desired Behavior

The column should still exist.

### Project Details

```
Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.7**
```

**Comment by Astorek86** [comment]
Hello,

Just wanna say that I have the same Problem with the latest version and MariaDB.

Node: **v16.20.1**
Arch: **x64**
Platform: **linux (debian 12 stable)**
Docker: **true (installed through get.docker.com)**
RootDB: **mariadb:11**
PackageVersion: **0.111.4**
