### ISSUE TITLE
🐛 Bug: QR-Code on API Call not transmitted as image

### ISSUE THREAD

**Issue by xcojonny** [nocodb/nocodb#6209]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Connect n8n to nocodb
2. Get a single row with a QR-Code
3. The received data for the QR-Code-Column is a STRING

### Desired Behavior

receive the actual QR-code as an image

### Project Details

```
Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.7**
```

**Comment by dstala** [comment]
@xcojonny as of now, we do not plan to support QR/Barcode image in API response.
