### ISSUE TITLE
{"msg":"Unauthorized access : xc-auth does not have admin permission"}

### ISSUE THREAD

**Issue by srch07** [nocodb/nocodb#621]
NocoDB used as docker : true
NocoDB version : v0.11.39
Database used in NC_DB URL  : pg (1 click heroku deployment)
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql 

**Steps To Reproduce**

1. Create a new project and add an external database.
2. Go to project invite an user on a new email id with role "creator".
3. Copy invite link for new user and sign up.
4. Browser goes into infinite loop stating ({"msg":"Unauthorized access : xc-auth does not have admin permission"}) in ajax call (No error on screen). Endpoint : https://<url>/dashboard/?q=sqlOp_PROJECT_READ_BY_WEB
5. Enter details and click on project you are invited too.

Below happens in browser behind the scene
6. Ajax call - Endpoint:https://<url>/auth/refresh-token - Error:{"msg":"Invalid refresh token"}
7. In Ajax call / Browser Debug ({"msg":"Unauthorized access : xc-auth does not have admin permission"}), Endpoint : https://<url>/nc/structural_dingo_3Sn_/projectApiInfo
8. Finally https://<url>/admin/roles , Error : {"msg":"Access denied"}
9. You are thrown out of login.

**Expected behavior**
The invited user should be able to work on project with creator role

**Comment by o1lab** [comment]
Couldn't get to reproduce this problem on heroku and locally. Only difference is I'm on latest. 

In step 3, have you logged out from super admin or trying it from incognito or other browser ?

**Comment by o1lab** [comment]
would you like to deploy a new one on heroku or [upgrade](https://docs.nocodb.com/getting-started/upgrading#heroku) and check if the issue persists.

**Comment by srch07** [comment]
Sure will do that, today or tomorrow.

**Comment by o1lab** [comment]
Please feel free to reopen if you are able to reproduce.
