### ISSUE TITLE
🐛 Bug: Editors cannot use filter groups

### ISSUE THREAD

**Issue by lcavasso** [nocodb/nocodb#6224]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create filters on a table that involve at least one filter group
2. Create a user with editor permissions
3. Log in as editor user
4. Look at the table you made filters for in step 1
5. Click the Filter dropdown
6. Get error: "filterChildrenList - editor : Not allowed"; anything within the filter group is blank, though the filter still seems to be applied correctly.

Alternatively,

1. Log in as user with editor permissions
2. Attempt to create a filter with a filter group
3. Get the same error "filterChildrenList - editor : Not allowed", though the filter group is still created and can be applied

### Desired Behavior

Editor users should be able to create and see filters that include filter groups

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.7**

### Attachments

Logged in as editor:
![image](https://github.com/nocodb/nocodb/assets/35540322/948e8236-5f71-4861-85ca-cc685f985e8a)
Logged in as super user (same if logged in as creator):
![image](https://github.com/nocodb/nocodb/assets/35540322/96ec0aa2-1753-47ef-bb9b-277a2e07ded0)

**Comment by sant1dom** [comment]
This issue should be reopened it is still present. To reproduce just redo the steps described above and login as editor and you'll receive the following error "You do not have permission to perform the action "filterChildrenList" with the roles: Editor."
