### ISSUE TITLE
Bug: The Role is not super admin,  just  project's owner cannot change project name, still  view old project name

### ISSUE THREAD

**Issue by binli123-max** [nocodb/nocodb#6226]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![GIF](https://github.com/nocodb/nocodb/assets/110003071/76bda5bb-443c-4f3b-ad92-91be5e273574)

you  can   see   my  project list  ,   it just  show  old project name ,if  i  click  edit button ,  i  change   new  name ,also  i  click  project  ,  jump to  project info  page ,  the  project name is  new name .  however, jump to  dashboard  , the preject  is old name

### Desired Behavior

you  can   see   my  project list  ,   it just  show  old project name ,if  i  click  edit button ,  i  change   new  name ,also  i  click  project  ,  jump to  project info  page ,  the  project name is  new name .  however, jump to  dashboard  , the preject  is old name

### Project Details

you  can   see   my  project list  ,   it just  show  old project name ,if  i  click  edit button ,  i  change   new  name ,also  i  click  project  ,  jump to  project info  page ,  the  project name is  new name .  however, jump to  dashboard  , the preject  is old name

**Comment by wingkwong** [comment]
please show your [project info](https://docs.nocodb.com/faqs/#how-to-check-my-project-info-).

**Comment by binli123-max** [comment]
![image](https://github.com/nocodb/nocodb/assets/110003071/3473db61-1bb3-48f4-90a2-44124ab46b27)
![image](https://github.com/nocodb/nocodb/assets/110003071/04ae9eeb-adbc-4d57-9c48-adec63c5b840)
first image  is   dashboard project name,
second image is   project  info  name 
they  are not  equal

**Comment by wingkwong** [comment]
please copy your [project info](https://docs.nocodb.com/faqs/#how-to-check-my-project-info-).

![image](https://github.com/nocodb/nocodb/assets/35857179/f7cdd8d6-8f5b-4053-9511-b37a4ce30cba)

It should look like this

```
Node: **v16.20.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.109.7**
```

**Comment by binli123-max** [comment]
Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.4**

**Comment by binli123-max** [comment]
0.109.7    also   this  bug

**Comment by wingkwong** [comment]
Thanks. Able to reproduce the issue.

**Comment by wingkwong** [comment]
Due to the layout change, this bug is no longer reproducible in latest version (0.111.0). Please upgrade it.
