### ISSUE TITLE
🔦 Feature: Pin a project on top

### ISSUE THREAD

**Issue by Kartheravi** [nocodb/nocodb#6238]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In the new UI, If the user has large number of projects then there is a chance that the user will get lost while scrolling it

### Suggested Solution

Ability to pin a project/table will help the user to access the frequently using projects/table easily

**Comment by o1lab** [comment]
Just curious - how many projects do you have ? @Kartheravi

**Comment by Kartheravi** [comment]
Currently i have 10 projects and in the future i was planning to migrate all my projects/planning from excel to nocodb.

**Comment by dstala** [comment]
starred projects is now available in cloud hosted solution.
