### ISSUE TITLE
🔦 Feature:  Ability to hide/unhide the table/project

### ISSUE THREAD

**Issue by Kartheravi** [nocodb/nocodb#6239]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Some tables in the project are static and those tables are used very occasionally, in that case when the project of 30+ tables it is occupying lot of real estate in the left nav. of the page when all the projects are appearing in the left nav. 

P.S: In the older version, i push those tables to the bottom of the project so out of sight, out of mind. 

### Suggested Solution

(In 0.111) It would be great if the user can hide/unhide the table.

**Comment by dstala** [comment]
having `starred` projects should address this & https://github.com/nocodb/nocodb/issues/6238

**Comment by Kartheravi** [comment]
Hi @dstala, 
In the previous UI, i used the drag and drop feature extensively. the new UI was awesome and looks great. I faced these challenges when i was working with baserow in the past,

**Comment by dstala** [comment]
cloud hosted solution now has concept of workspace. 
both self hosted & cloud hosted solutions support drag drop for tables.
no immediate plans in our roadmap to support hiding tables additionally
