### ISSUE TITLE
Enhancement: Move views panel to left below table

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#624]
Hi,

Could the view panel be moved to left below table. The workspace becomes a bit less. On moving it to right like in airtable more space would be available
![image](https://user-images.githubusercontent.com/86340924/136431988-0f710366-a2fb-4ff6-9b3d-488a49c5d47a.png)

**Comment by o1lab** [comment]
I think in earlier versions we'd an version to toggle left nav drawer. PR will help.

**Comment by lielfr** [comment]
I thought of making it like this (notice the TAB 1 below the pagination). Is it a good idea?
![Screen Shot 2021-10-10 at 8 32 01](https://user-images.githubusercontent.com/360928/136683673-c8f5a4ab-0b96-4dfb-bc66-494947e8fa38.png)

Also, how do you think it should be styled? I thought making it similar to the project tabs below, but maybe that will confuse the users?

**Comment by o1lab** [comment]
@lielfr Could you please ping me in discord. I was thinking mostly to toggle the nav-drawer. Having tabs at end will confuse :)

**Comment by o1lab** [comment]
![toggle](https://user-images.githubusercontent.com/5435402/136686152-bc26c89a-3046-46ca-8b88-77a0d07189a8.png)

**Comment by wingkwong** [comment]
Closing it as it has been released in ``0.80.0``.
