### ISSUE TITLE
🔦 Feature: Ability to group multiple projects in to a folders

### ISSUE THREAD

**Issue by Kartheravi** [nocodb/nocodb#6240]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When displaying multiple projects in a single left nav., for some use cases like *maintaining multiple projects with similar suffixes* 
(mostly I use it for testing by duplicating the project), the user will gets lost when scrolling the current left nav. and the scope of clicking the wrong project might be pretty frequent. 

P.S: In the previous versions, i suggest browser bookmark folders to group the projects and navigate between the projects and the scope was limited to that particular project, so the user can't enter into a wrong project while navigating unless the user comeback and click on the other project with different suffixes.

### Suggested Solution

Ability to group multiple projects in to a folder.

**Comment by dstala** [comment]
Cloud hosted solution now has workspaces & starred projects within workspaces.
