### ISSUE TITLE
🐛 Bug: Login e-mail form field is not autocompleted

### ISSUE THREAD

**Issue by salim-b** [nocodb/nocodb#6241]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Open your NocoDB login page (`https://YOUR.DOMAIN/dashboard/#/signin`).

2. Click in the e-mail field and press <kbd>↓</kbd> (arrow down) on your keyboard. No list with previously entered e-mail addresses appears.

### Desired Behavior

In step 2 above, a list with previously entered e-mail addresses should be displayed.

For this, the `<input>` element of the e-mail address field on the login page should be changed to have the attributes [**`type="email"`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) (currently it has `type="text"`, see screenshot below) as well as [**`autocomplete="email"`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete).

Besides, the `<input>` element of the *password* field should have [**`autocomplete="current-password"`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) (it already has the proper `type="password"`).

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.111.0**

### Attachments

Current `<input>` element of the e-mail address field on the login page:

![Bildschirmfoto vom 2023-08-26 13-49-01](https://github.com/nocodb/nocodb/assets/20040931/023bda4a-6d43-4c63-87bb-b02d95091b99)

**Comment by frankMagoba** [comment]
Hi @o1lab can I pick this up?

**Comment by wingkwong** [comment]
@frankMagoba we've assigned & resolved internally.

**Comment by salim-b** [comment]
@wingkwong @DarkPhoenix2704 Thanks for implementing this in https://github.com/nocodb/nocodb/pull/6249. I've just tested [v0.111.1](https://github.com/nocodb/nocodb/releases/tag/0.111.1) that includes this and unfortunately, there's still an issue with Firefox (latest v117 with vanilla profile and no add-ons):

After the initial page load of the login screen (`https://YOUR.DOMAIN/dashboard/#/signin`), the e-mail field is still not auto-completed. But after switching to the sign-up screen (`https://YOUR.DOMAIN/dashboard/#/signup`) and then back to the login screen again, the e-mail field is suddenly auto-completed.

I made a short screen recording to illustrate the problem:

[Bildschirmaufzeichnung vom 04.09.2023, 14:51:45.webm](https://github.com/nocodb/nocodb/assets/20040931/ac64fca2-6071-46d3-857f-b6f27a52fe04)

The issue doesn't occur with Google Chrome (e-mail field is auto-completed from the beginning). I don't know what's going on behind the scenes. Probably related to some Nuxt JS (not) getting loaded?

**Comment by salim-b** [comment]
Just a short addendum, as this is a very annoying issue:

I just noticed that with latest NocoDB v0.202.8, the `<input>` element of the e-mail address field on the initial login page has still `type="text"` and no `autocomplete="email"` attribute set:

![Bildschirmfoto vom 2023-11-22 00-05-50](https://github.com/nocodb/nocodb/assets/20040931/1ee973d2-751e-49d3-bf93-861b855f1460)

It should be changed to have the attributes [**`type="email"`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) as well as [**`autocomplete="email"`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete).

Additionally, the `<input>` element of the *password* field should have [**`autocomplete="current-password"`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) to fully adhere to the relevant web standard.

My best guess is that Chrome performs some "magic" non-standard input type detection (to accommodate all the different SPA frameworks) which Firefox does differently – and hence the issue I described in the [post above](https://github.com/nocodb/nocodb/issues/6241#issuecomment-1705230388) only occurs in Firefox.

**Comment by salim-b** [comment]
Just for the record: In the latest version of NocoDB and/or Firefox, the issue doesn't occur anymore, i.e. the login form is auto-filled on first page load. But the e-mail field still has `type="text"` and not `type="email"` and the `autocomplete="email"` attribute is missing.
