### ISSUE TITLE
🐛 Bug: Webhook call sending Parameters doesn't work

### ISSUE THREAD

**Issue by xcojonny** [nocodb/nocodb#6246]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Hey there,

since the last update the sending Parameters via web hook fails.

1. Create Webhook
2. Create parameters
3. Test webhook
4. Newly created parameters (after the update) are not attached to the web hook
5. Parameters created before the update are attached to the web hook

### Desired Behavior

attach all Parameters.

I think the issue is, that in the current version the check boxes are missing for the parameters. When you go on the headers tab, then the check boxes are still there.

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.0**

### Attachments

<img width="752" alt="Bildschirmfoto 2023-08-27 um 11 39 13" src="https://github.com/nocodb/nocodb/assets/22481238/8c27d340-a3d6-44a4-b86a-2de7e5f32c11">
<img width="743" alt="Bildschirmfoto 2023-08-27 um 11 39 07" src="https://github.com/nocodb/nocodb/assets/22481238/d710b9c5-a916-411c-a174-e30ea12b19d1">

**Comment by dstala** [comment]
@xcojonny 
in the latest webhook, all associated parameters are by default sent in body - including previous row contents. do we still need to continue support for moustache syntax? any specific use case that it helps?

**Comment by o1lab** [comment]
This is about request params. @pranavxc to see.

**Comment by snowity** [comment]
I've found that custom header in webhook doesn't send to API server
