### ISSUE TITLE
🔦 Feature: Personal view or how to how to allocate work space.

### ISSUE THREAD

**Issue by G4CHIM4STER** [nocodb/nocodb#6252]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Hello guys. My team and I are using NocoDB for quite along time and now it's time to raise the issue about personal view or personal workspace. How long will it take to create a personal view for every contributor in a project ?
Also, there is a question about roles in the project. the fact is that if you give the rights "editor" to the participants and allow him to create a filter on the table, then all other participants will see it, and in our work very often several people need to work on the table at the same time. we got out of this situation by creating a view for each employee and giving them "creator" rights, but now there is a need to restrict rights. 

### Suggested Solution

Can you please help me to solve this problem and tell for how long should it take to reproduce "personal view" mode for tables ?

**Comment by oosthuizenb** [comment]
Is there a progress update? We are in the process of deciding to switch over to NocoDB or Baserow. This is a make or break for us. Would be amazing to have this feature available. Is there maybe a time estimate on completion?

**Comment by bebr43** [comment]
SQL offers these features of the shell - see:
https://www.postgresql.org/docs/current/sql-grant.html
If you see NocoDB as a mere Web-Interface to your Database .. voilà.

**Comment by fabfont** [comment]
Hi,
One of my client asked me if I could implement this feature.
Looking at the code, it seems not to be a very big deal but that depends on how you though to implement this feature.

Have you already a clear vision of the way you want to implement it?
If so, could you share me your vision? 

On my side, I though of a very simple implementation : 

- Add the information whether a view is personal or not
- Add the view owner id in view (to define exactly where)
- When retrieving the views, only the non-personal views and the personal views of the user will be send back to the front
- Add an item in front menu to switch this personal information only on views the user have created

 It's a very simple implementation but we can think of a more complex one with the sharing of a view among a set of users or groups/roles.

I will probably develop a solution for this problem for my client but if it's done the way you though, it's better :)

Thank you

**Comment by t0mdicks0n** [comment]
I am considering moving our companies operations workflows to NocoDB. What is very strange to me is that for example the table filters are shared by all users as a default. As a user I would much prefer if I can mock around and add filters to the table without making any changes to my colleagues experience looking at the same table/"base" unless I explicitly want to save my changes.

**Comment by mekedron** [comment]
We would like to entirely move our company processes to NocoDB from Google Sheets.
We have around _40 team members_ who'd like to use NocoDB on daily basis. And actually NocoDB is covering almost all our needs. However, we discovered that all the filters are going to be shared across all the team members which makes it almost impossible to use, as we have more than 10 records in a single table. Much more. Hundreds of the records.

And you can say, hey, the filters in Google Sheets are applied to the whole spreadsheet, the same as in NocoDB. You're right. Fair point.

However, right now with our current Google Sheets workflows we split all our information to many different spreadsheets with many different sheets in it. And we could do the same with NocoDB, and replace this multiple spreadsheet-sheet approach with NocoDB views, however, it doesn't work that well as we need to create about _40-50 views_ for every table we have to cover all our needs, but it would be quite hard to manage, so we'd like to make it possible to allow users to use filters instead.

**Comment by sant1dom** [comment]
This is a must have feature. Is impossible to work in team without the possibility to filter data based on the logged user.
With the views it should be possible to enable "locked" filters so you can only refine more and not less, but having the filters open to anyone is just a mess.

**Comment by dstala** [comment]
Personal views are now available in cloud. In this view mode, other users can see view & associated configurations - but will not be able to make any changes to the configuration.

**Comment by sant1dom** [comment]
@dstala why only cloud? Will it also be available in the on-premise version in the future?
