### ISSUE TITLE
🔦 Feature: form with pre-compiled, "hidden" fields 

### ISSUE THREAD

**Issue by niccolosanarico** [nocodb/nocodb#6253]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

My desired behavior is to replicate what is available to Airtable forms: https://community.airtable.com/t5/announcements/new-feature-hide-form-field-by-url-parameters/ba-p/40373

We are using Airtable forms to collect information from a list of third parties, and each of them receives a form link with personalized pre-compiled fields hidden from their view. All the data collected from the forms flows into a specific table. 

### Suggested Solution

Replicating the behavior of the Airtable form would be acceptable for us. Open to suggestions about how to achieve the same result with the current Nocodb features. 

Thank you!

**Comment by dstala** [comment]
To be tracked under

[[Feature] Prefill form view input elements from the URL params](https://github.com/nocodb/nocodb/issues/3027)
