### ISSUE TITLE
🐛 Bug: Currency field updation not reflecting to external postgres DB

### ISSUE THREAD

**Issue by iqbalpb** [nocodb/nocodb#6255]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Spin up noco in docker compose [with external postgress]
2. Created a project named neon
3. Add data datasource Postgres's from [neon.tech](https://neon.tech) with a free account
4. Created two table: cafe & food
5. my data inside [cafe](https://snipboard.io/lp47Q8.jpg)
6. my data inside [food](https://snipboard.io/QtqyAi.jpg)
7. Updated price of cake, frappe & burger not reflecting in neon, I refreshed noco lost update in forntend

>  No errors in docker compose logs

### Desired Behavior

Data need to be updated

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.0**

### Attachments

Issue unlisted YouTube Video: [price data not updating](https://youtu.be/8Vr6dwfNZtQ)
I created a field qty for testing(updating or not working), that data update reflects: [Data updation working video](https://youtu.be/Dlu6NpK1y6Y)

**Comment by o1lab** [comment]
Thank you @iqbalpb for so detailed issue. Was about to ask you more details until I saw the video. Really appreciate it. Will have it fixed in next release. 🙏

**Comment by wingkwong** [comment]
Are you using Firefox?

**Comment by iqbalpb** [comment]
No safari

**Comment by divemasterza** [comment]
I can confirm this is still the case and reproducible on 1.14.1
