### ISSUE TITLE
🐛 Bug:  form field is not changing on tab or press enter

### ISSUE THREAD

**Issue by FreyrThor** [nocodb/nocodb#6257]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Using SFF.vc contact us powered by NocoDB the fill-in boxes don't flow, resulting in hidden required boxes, disabling submission, using Powermac current OS

### Desired Behavior

The submission template upon hitting return or tab needs to continue to flow to the next tab

### Project Details

no code suggested

### Attachments

<img width="1564" alt="Screenshot 2023-08-28 at 10 30 12 AM" src="https://github.com/nocodb/nocodb/assets/143437442/7f5a0d94-719c-43ef-9610-1d0de76a3ed3">

**Comment by FreyrThor** [comment]
issue for this bug does not exist

**Comment by dstala** [comment]
On pressing tab, we should switch over to next available form input field. @FreyrThor Let us know if my understanding of your change request is correct?

**Comment by FreyrThor** [comment]
Thanks Raju,

I figured it out.

It's just not intuitive when you need to go back up, but the alt tap worked
for me.

Matter solved.

best


Freyr Thor
Chairman & CFO + Co-Founder
***@***.***
562 204 6327
