### ISSUE TITLE
🔦 Feature: add option to pause animations - Gallery view carousel

### ISSUE THREAD

**Issue by strmca** [nocodb/nocodb#6258]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Give users the ability to stop animations (slideshow / carousel) in the Gallery view for preference or accessibility reasons. 

### Suggested Solution

The autoplay option in the Antdesigns carousel component used for Gallery Photos has a default of false which would result in no motion on the screen. 

The current build (the x64 Windows build 0.111.0) has this feature set to true which results in a lot of large movement on the screen if the cover photo field selected contains multiple photos.  The photos in each record sometimes move at different rates.  Screenshot shows photos with various amounts of the preceding photo showing in each record.

![NoCoDBGalleryIssue](https://github.com/nocodb/nocodb/assets/44687131/ab4181bd-232c-4b44-9713-9bde51020e73)

An option to toggle animations on or off, or at a minimum respecting the prefers-reduced-motion option in a browser would go a long way to making this application more usable to a large portion of the population.

### Additional Context

The W3C spec currently in draft recommends the ability to pause, cancel or control the speed of animations. https://drafts.csswg.org/web-animations/#pausing-an-animation-section

Accessibility is part of the reason for these recommendations.  Large scale movement especially on websites (including self hosted applications with web interfaces) can cause vestibular disturbances in susceptible people.  

https://vestibular.org/about/
> More than 35% of US adults aged 40 years and older (69 million people) experience vestibular dysfunction at some point in their lives; many of them go on to develop a chronic vestibular disorder. 

This is a large number of people to bar from using your stellar project.  For me, this turned the perfect app for my needs into an unusable one because I couldn't stop the motion that produces migraines, dizziness and nausea.   

https://www.a11yproject.com/posts/understanding-vestibular-disorders/

> "Don't make animations, sliders, videos, or rapid movement start automatically. Give an indicator of what movement will happen on the site when someone takes action. Allow the option to turn off any animation and movement at any point in the process.
> 
> Also, with the CSS [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query you can write conditional CSS animations and transitions based on the user's preference exposed from the browser settings. For example, you can disable all animations and transitions for users who explicitly prefers reduced motion:"

https://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity/

> "Relative size of movement

> "Animations that move an object across a large amount of space are most apt to trigger a negative response for someone suffering from a vestibular disorder. The physical size of screen matters less than the size of the motion relative to the screen space available—so a small button with a 3D rotation probably won’t cause trouble, but a full-screen wipe transition covering the entire screen likely would. Animation that involves only non-moving properties, like opacity, color, and blurs, are unlikely to be problematic."

**Comment by dstala** [comment]
Thanks for sharing a detailed report @strmca. We will discuss about it & keep you posted.

**Comment by strmca** [comment]
Thank you!  I appreciate your attention to this.  I will watch for any updates.

**Comment by dstala** [comment]
@strmca carousel is by default disabled in gallery view.

**Comment by strmca** [comment]
Thank you so much!  I really appreciate this! I' so happy I'll be able to use the program again!
