### ISSUE TITLE
🐛 Bug: Cannot Bulk Delete

### ISSUE THREAD

**Issue by TheOneValen** [nocodb/nocodb#6260]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have a model with PK "Id" which is a string. I want to delete e.g. 2 rows, as far as I understand the API I must DELETE call this:

`[{"Id": "someid"}, {"Id": "otherid"}]`

It comes back with 200 but the rows are not deleted.

There is also a security problem with this which I will report seperately.

### Desired Behavior

Deletion of rows.

### Project Details

nocodb v 0.111.0

ID Is a PK (a string)
Some other str and int colums.

**Comment by wingkwong** [comment]
can you show which endpoint you are using and the response data?

**Comment by TheOneValen** [comment]
`/api/v1/db/data/bulk/v1/<project>/<table>` but I recreated my situation from scratch, now it works. Sorry for the confusion. The Advisory I created is still relevant though.
