### ISSUE TITLE
🐛 Bug: Showing Empty could be removed

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#6264]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1- Add some database
2- Open it on left
3- If there is no table created for default database it shows empty

### Desired Behavior

It would be much better rather than showing empty it is hidden.

![image](https://github.com/nocodb/nocodb/assets/86340924/5db60e35-0fd2-4d19-97f4-b2dff6ea78c3)

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.111.0**

**Comment by dstala** [comment]
Project specific tables (which become part of NC DB & not external DB) can also be created. Hence`Empty` in that location was introduced to indicate no project specific tables were created.

**Comment by AztrexDX** [comment]
ok. It is like I have added many database and I am seeing lot of empty. I will close it if thats how it is going to work
![image](https://github.com/nocodb/nocodb/assets/86340924/8d95ba4e-36c8-4013-88df-ca5b41a3dc95)

**Comment by AztrexDX** [comment]
Thanks for info
