### ISSUE TITLE
🐛 Bug: Cannot send multiple user invites to a project by separating with a comma

### ISSUE THREAD

**Issue by ornellabordino** [nocodb/nocodb#6267]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Go to a project´s collaborators' view
2. In the invite section, Input more than one email, separated by a comma, and click the "Add User/s" button:
![image](https://github.com/nocodb/nocodb/assets/7105253/5cc43dba-0c53-4bd1-966d-7082e743f2b4)
3. The error `"/email - must match format "email""` will appear:
![image](https://github.com/nocodb/nocodb/assets/7105253/2468e4e0-424d-4391-8c70-677c73d37360)

Sending only 1 invite works fine. The problem is trying to append multiple emails with a comma.

### Desired Behavior

As suggested in the documentation, we expect to be able to invite more than one user with a single action.
The documentation [here](https://docs.nocodb.com/setup-and-usages/team-and-auth/) suggests that invitations can be sent if we separate emails with a comma:

![image](https://github.com/nocodb/nocodb/assets/7105253/aab8f367-e5f7-427a-ba66-3c695e1d09c4)

 However, it seems that a validation is being done, preventing the feature from working. We think that the validation might be a swagger one [here](https://github.com/nocodb/nocodb/blob/f228c4ec34fb7a7df392a2285c4aa17b9775c18c/packages/nocodb/src/services/project-users/project-users.service.ts#L45)

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.111.0**

**Comment by frankMagoba** [comment]
Hi @wingkwong can I work on this?
