### ISSUE TITLE
Sponsored issue: Feature to input new record from form view.

### ISSUE THREAD

**Issue by shawnkeqin** [nocodb/nocodb#6281]
## Priority Support

- @shawnkeqin is using  [Mintycode](https://mintycode.io) to fund this issue.
- You can receive ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) if you provide priority support to @shawnkeqin. 
- To view the support request and terms go to  [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=a6638cab-c181-4616-b410-5e21dfd5537d&owner=nocodb&name=nocodb).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by o1lab** [comment]
This github is for tracking the issues related to the software. And unfortunately, above doesnt anything about the issue faced or support needed. I am not opposed to bounty here however this deosnt help. Closing it. Open it if you can add all the details.
