### ISSUE TITLE
🐛 Bug: Geodata column type missing 

### ISSUE THREAD

**Issue by iqbalpb** [nocodb/nocodb#6294]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Add a new column and search for data. type Geodata.
GeoData column type mentioned in docs: [GeoData](https://docs.nocodb.com/setup-and-usages/column-types/#geodata)

### Desired Behavior

Geo Data should be found and I can enter latittude and longtittude

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.0**

### Attachments

<img width="895" alt="Screenshot 2023-09-02 at 11 43 53 AM" src="https://github.com/nocodb/nocodb/assets/19872875/61db2d78-5403-4964-80f7-d965d1d8b1c3">

**Comment by dstala** [comment]
It was a developmental beta feature under easter egg in earlier UI (before v0.111.0). What is the specific use case that you are working with?

**Comment by iqbalpb** [comment]
That feature is not that much important for my use case, but I saw that field type in previous releases.

**Comment by filcuk** [comment]
I was looking for the best way to store manually entered position info (lat/lon) and have found this type in docs: https://docs.nocodb.com/setup-and-usages/column-types/#geodata

I was also confused not finding it in the UI.

My use is: get a place on maps -> copy position -> enter as a new record, for the purpose of recording locations with a bunch of custom logs and metadata

**Comment by tubia** [comment]
I was searching exactly the same column type which would be greatly useful to collect POIs from a map.

Any plan for implementing this?

**Comment by dstala** [comment]
will be available from next bugfix release in OSS
