### ISSUE TITLE
🔦 Feature: Env variable for the CSV / Excel file upload (only for OSS)

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#6295]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

<img width="781" alt="image" src="https://github.com/nocodb/nocodb/assets/5435402/673b172a-b96b-4659-bdb5-06fdb107322b">

https://www.reddit.com/r/NocoDB/comments/11iltfz/increase_import_file_size/

### Suggested Solution

.

**Comment by ecomm-michael** [comment]
Wow, this is for real?

**Comment by dstala** [comment]
[🔦 Feature: Edit the size limit to import bigger excel files](https://github.com/nocodb/nocodb/issues/5858)

**Comment by yuriolive** [comment]
@dstala What is the env variable to be used to increase the limit?

**Comment by dstala** [comment]
@yuriolive i had closed this issue to track this under https://github.com/nocodb/nocodb/issues/5858
I am not sure if we had this checked in. will update you.
