### ISSUE TITLE
🐛 Bug: Mirroring Popup Window

### ISSUE THREAD

**Issue by iqbalpb** [nocodb/nocodb#6296]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Try to import a CSV

### Desired Behavior

clean import popup

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.0**

### Attachments

https://github.com/nocodb/nocodb/assets/19872875/06206b18-5cbb-442e-a1f0-3078a6aa24c4

**Comment by o1lab** [comment]
which browser is it ?

**Comment by iqbalpb** [comment]
safari latest

**Comment by iqbalpb** [comment]
Safari Version 16.6 (18615.3.12.11.2)

**Comment by dstala** [comment]
for the record, this renders fine in older version of safari (v14.2). haven't tried in latest version

**Comment by iqbalpb** [comment]
The mirroring issue is occurring in many places, hope you will fix in future releases

**Comment by dstala** [comment]
@iqbalpb can you help us check if issue still persists with latest release?

**Comment by dstala** [comment]
@iqbalpb reopen if issue persists with latest release. thanks!
