### ISSUE TITLE
🐛 Bug: Can't grab slide bar on the right side in Microsoft Edge or Chrome

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#6299]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Try to grab the slider on the right side - it can´t be grabbed.

That one for sidewards works good.

Both should be more visible.

### Desired Behavior

The slider should be usable to move downwards.

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.111.1**

### Attachments

![Bar](https://github.com/nocodb/nocodb/assets/20600342/0d81b397-7b0d-4230-bb64-8c8ce8ee55b4)

**Comment by dstala** [comment]
Is the issue more to do with overlapping of re-size bar over scroll bar? on chrome, I was able to grab- but the re-size bar did cause hinderance.

![Screenshot 2023-09-05 at 10 33 33 AM](https://github.com/nocodb/nocodb/assets/86527202/d6a0cd25-6dbb-4c15-a079-386ae00577d7)

**Comment by WeT-Klb** [comment]
Well - at least I can´t grab it. Instead like you said the re-size bar always got active.

No matter if I use Edge or Chrome.

 

 

Von: Raju Udava ***@***.*** 
Gesendet: Dienstag, 5. September 2023 07:06
An: nocodb/nocodb
Cc: Werner; Author
Betreff: Re: [nocodb/nocodb] 🐛 Bug: Can't grab slide bar on the right side in Microsoft Edge or Chrome (Issue #6299)

 

Is the issue more to do with overlapping of re-size bar over scroll bar? on chrome, I was able to grab- but the re-size bar did cause hinderance.

 <https://user-images.githubusercontent.com/86527202/265590411-d6a0cd25-6dbb-4c15-a079-386ae00577d7.png> Screenshot 2023-09-05 at 10 33 33 AM

**Comment by dstala** [comment]
is now made more visible & thick. should be available from next release.
