### ISSUE TITLE
🐛 Bug: Test Webhooks not working anymore

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#6300]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create Webhook and press Test.

![image](https://github.com/nocodb/nocodb/assets/117290601/18918eae-d058-4e18-a542-44ab12d864b5)

### Desired Behavior

Should work

### Project Details

Docker
PG
0.111.1

**Comment by wingkwong** [comment]
@emre1e Please share more info, e.g. what webhook event, error logs etc. I just tested a bit using https://webhook.site/ and it's working fine. 

<img width="494" alt="image" src="https://github.com/nocodb/nocodb/assets/35857179/44f66307-df35-4e9e-b815-061b3bbe7266">

**Comment by emre1e** [comment]
Thanks for the help. It seems you changed the payload and thats why we got this error messages.

**Comment by emre1e** [comment]
before the update the webhook was sending just 1 root json.

Now it has many parents and childs. That was the issue. We will adjust our code. Thanks for the help. We can close the ticket.

**Comment by wingkwong** [comment]
@emre1e Okay. For the structure, you may refer to sample payload.

![image](https://github.com/nocodb/nocodb/assets/35857179/d19cce97-4d9f-4ada-8013-90ddf5efffd9)
