### ISSUE TITLE
🐛 Bug: View DIV not showing all Values

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#6301]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Not showing all Views, the css is bugged. If you zoom out all gets visible, if you zoom in many views gets out zoomed.

![image](https://github.com/nocodb/nocodb/assets/117290601/f51aad44-b1c9-4ed5-8e95-3168e473d640)

### Desired Behavior

Views tab should be fixed and scrollable.

### Project Details

docker
pg 
0.111.1

**Comment by dstala** [comment]
<img width="259" alt="Screenshot 2023-09-05 at 10 29 12 AM" src="https://github.com/nocodb/nocodb/assets/86527202/6b8f6be7-897d-4015-b63b-05fc7987e7e0">

**Comment by cppchriscpp** [comment]
Just ran into this myself too - an `overflow: auto` on the `.nc-view-sidebar` seems like it fixes it.
