### ISSUE TITLE
🐛 Bug: Performance Issues since 0.111.0

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#6302]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Load a Table with many Columns

![image](https://github.com/nocodb/nocodb/assets/117290601/7a47ac86-8264-417e-b6c1-bfbbb61159e7)
![image](https://github.com/nocodb/nocodb/assets/117290601/592d10f3-e80b-4bfd-8613-7a7cec27d70a)

### Desired Behavior

Was loading wayyy faster before.

### Project Details

Docker 
PG
0.111.1

**Comment by o1lab** [comment]
Would need more details on the table like how many LTAR, Lookup, Rollup, formulas. It should be ideally better the speed.

**Comment by emre1e** [comment]
300 columns 24 formulas 45 lookups 15 many to many

But even if i put a filter in and show only 10 rows, its still slow.

**Comment by emre1e** [comment]
The API is responding veryy slow

**Comment by emre1e** [comment]
the formulas are standart if value = "THIS", "Hello", "Bye"

It feels like there is cap in request. If nobody is working in Noco its super fast. As soon as 3-4 People joins the table, its getting super slow and the api gets longer and longer to work.

**Comment by emre1e** [comment]
Now the Websocket started to take to long.

![image](https://github.com/nocodb/nocodb/assets/117290601/5f3f4f7c-1a49-4791-b2c1-4317bc77a178)

**Comment by emre1e** [comment]
more Infos:
![image](https://github.com/nocodb/nocodb/assets/117290601/27b1ae57-1277-4bc5-abc8-87e138a5a8ff)

**Comment by emre1e** [comment]
we can also have a live session tomorow if it helps. I already tried to rollback but is not working.

**Comment by o1lab** [comment]
Happy to help - please [book a time](https://calendly.com/nocodb-meeting).

**Comment by emre1e** [comment]
Hi,
The CPU usage is now sometimes high sometimes low. 
yes it got faster but still wayyyy slower then 0.109. If we change views or switch pages between views it freezes for 5-20 secs. I replied to your Mails and sent you the log.

**Comment by o1lab** [comment]
Ok, we see your mails in spam for some reason. Thanks for sending them - we are looking at the logs and will revert back.

**Comment by dstala** [comment]
@emre1e good amount of changes to improve performance are done with latest release. if you still face issue, reopen this thread.

**Comment by emre1e** [comment]
The Formula Bug is still existing.

Create a Table and add 10 Fields with Formula.
For each formula you add the Update/View time of each row increases by 1-2 secs.

**Comment by emre1e** [comment]
@dstala can you reopen this ticket please. Thank you
