### ISSUE TITLE
🐛 Bug: Table Permissions through UI ACL don't work

### ISSUE THREAD

**Issue by nosorio2** [nocodb/nocodb#6306]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Open Project*
2. remove permissions for "editor, commenter, viewer" from a table
3. Open the project with an user with editor role
4. The user with editor role can see the "hidden table"

*This project existed before updating to current version. 

### Desired Behavior

The users with a role without permission to see a table should not see the tables. 
![image](https://github.com/nocodb/nocodb/assets/46441491/2d9da782-ce85-4cff-8e7c-4a4a3d78bdc0)
Logged in as Editor: 
![image](https://github.com/nocodb/nocodb/assets/46441491/63ec22c6-c889-4fb8-ac49-d4f97dd19e3a)

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.1**

**Comment by nosorio2** [comment]
btw the weird named tables appear once after synching metadata. I can't delete them. I don't know exactly what they relate to. I deleted one once and lost information. So That's why I hide them from people. Terrible work around, but it worked before.

**Comment by dstala** [comment]
@nosorio2 
Looks like you have sync'd NocoDB's meta tables. Will check issue with UI ACL if we can reproduce
