### ISSUE TITLE
🐛 Bug: Table not loading. (Console Error: Failed to fetch dynamically imported module)

### ISSUE THREAD

**Issue by buikemichael** [nocodb/nocodb#6326]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Load nocodb on an iframe
2. click on any table immediately the page loads
3. The table will be blank and the browser will show a console error  `Failed to fetch dynamically imported module ...dashboard/_nuxt/Smartsheet`
4. Note: Allowing for some delay of about 5 seconds before interacting with the page will make the page work just fine

### Desired Behavior

The table should load

### Project Details

NocoDB version: 0.111.1
Database used in NC_DB URL: pg
Project was created by clicking: New Project by connecting to external database
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.111.1**

**Comment by dstala** [comment]
@buikemichael there are some fixes gone in recently related to iFrames. Please reopen this thread if you still see issue in v0.202.5+
