### ISSUE TITLE
Outdated screenshots in README.md

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#6327]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- since a new UI has been introduced in 0.111.0, some of the screenshots in README.md are outdated.

### Desired Behavior

- update with the latest one to avoid confusion

### Project Details

N/A

**Comment by dstala** [comment]
will update GIF. rest done.
