### ISSUE TITLE
🐛 Bug: Unauthorized Access

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#6328]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Some users reported Unauthorized Access after upgrading to latest version `0.111.2`. 

**from user sukhan**

> Something's broken. All applications that access the API give the error "Forbidden - perhaps check your credentials?". The key is correct.

![image](https://github.com/nocodb/nocodb/assets/35857179/0f1c2fa6-4770-427e-b6f8-569a8582b7f3)

**from user RAPTOR_6**

> I can't even log in anymore Error: Invalid credentials. Before, it gave me permission errors in GUI and I thought I would just relogin, which turn out to be a bad idea. The thing is that I had a backup from 2 hours before and the 0.111.0 and 0.111.1 versions are not working with database restored from backup, as I can't login using my admin account. I can't reset the password either, as the SMTP is broken for my provider from the start.

> I try to login using the GUI and it is not working, eg. Invalid credentials, this is the output:

```
09/08/2023 9:46:43 AM [Nest] 11  - 09/08/2023, 7:46:43 AM   ERROR [i] Invalid credentials
09/08/2023 9:46:43 AM Error: Invalid credentials
09/08/2023 9:46:43 AM     at Function.badRequest (/usr/src/app/docker/main.js:1:681451)
09/08/2023 9:46:43 AM     at f.validate (/usr/src/app/docker/main.js:1:1377403)
```

**from user Blusky**

> Using the API with an API token that previously worked. I also tried creating a new API Key (in case of wether or not it's a api key migration issue), same error. Also using n8n.

```
[Nest] 11  - 09/08/2023, 7:43:13 AM   ERROR [i] Unauthorized access
Error: Unauthorized access
    at Function.forbidden (/usr/src/app/docker/main.js:1:681524)
    at _.intercept (/usr/src/app/docker/main.js:1:803076)
    at /usr/src/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
    at InterceptorsConsumer.intercept (/usr/src/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:25:24)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:60
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by sasch901** [comment]
same here. Trying to connect via API :) - would be great to have a rollback function for versions

**Comment by fengjiongmax** [comment]
I'm also getting this but I'm not sure if it is related to this issue:
```json
{
  "msg": "Unauthorized access"
}
```
I'm using an API Token created by a viewer account, which has granted access to a base, and I can browse data on the browser with that account logged in. But I get the above error message when I use the API Token in Swagger ( and have logged in by putting the value in xcToken).

**Comment by mertmit** [comment]
@fengjiongmax which version you're having this issue?
We've just released a bugfix on this https://github.com/nocodb/nocodb/releases/tag/0.202.10
If you're not on v0.202.10 can you give it a try and let me know

**Comment by fengjiongmax** [comment]
I was on v0.202.9, and after updating to v0.202.10, the REST API no longer gives me this error when using xc-token!
Thank you @mertmit !

**Comment by Kiss-World** [comment]
@mertmit xc-token and xc-auth are different, please explain it in the api document. The current API document description is wrong. The document requires xc-auth to start with, even if it is token

**Comment by o1lab** [comment]
cc : @dstala 

I think we 've removed copy auth token (which was xc-auth). We should remove any reference to it from docs as that token is ephermal.

**Comment by dstala** [comment]
@o1lab marked as deprecated
`Use of Auth tokens is deprecated since v0.205.1. Please use API Tokens for authentication.`
https://docs.nocodb.com/account-settings/api-tokens/#auth-tokens

Remove that section completely?
