### ISSUE TITLE
📝 i18n Translations 📝

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#633]
# Hello!

NocoDB supports many foreign languages & we welcome community contributions via an easy to use [google-spreadsheet](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172). Your help in fixing i18n goes a long way supporting NocoDB. 

We're looking for contributors to verify / translate our i18n data. 

## First time here? 

Please check out [How to participate in Community](https://github.com/nocodb/nocodb/issues/601) first.

## i18n Contribution Guide

Please check out [How to contribute for community members](https://docs.nocodb.com/engineering/translation#how-to-contribute--for-community-members).

**Comment by kinga-marszalkowska** [comment]
@wingkwong Do you also need help with languages that are not listed in the spreadsheet? For example: Polish?

**Comment by kinga-marszalkowska** [comment]
Thanks, as I was working on the translations I noticed that column 53 and 55 are duplicates. Just as 81-84. Should I create an issue? Also, I'm done with translations but on https://i18n.nocodb.com/ there is no Polish language in the combobox.

**Comment by kinga-marszalkowska** [comment]
The file was downloaded correctly but I can't confirm whether it uploaded into the site. The problem is that when I upload it for the first time it says "No csv is selected". When I use the button to try again it allows me to select file but doesn't  show any progress bar or any indication that the file is being loaded.

**Comment by sesam** [comment]
I've started translating to Slovenian. Then found the language needs to be implemented in the translation help tool.
But then I found I can just make a .csv with a header that's already supported, or edit the i18 website form and enter the language code there.

So I have a Slovenian (sl_SI) translation about halfway done -- PR welcome?

**Comment by sesam** [comment]
@kinga-marszalkowska I can help getting your csv to JSON :). I had to disable some Chrome plugin, but you can just as well try in Private / Incognito mode on https://i18n.nocodb.com/ and the copy-to-clipboard part should work. Afterwards, go to https://github.com/nocodb/nocodb/edit/master/packages/nc-gui/lang/pl.json and overwrite with your translations, that should do it.

**Comment by kinga-marszalkowska** [comment]
@sesam Unfortunately, the copy to clipboard part doesn't work in private mode, I've already checked a couple of browsers. Can you help me convert the file? 
[polish_translations.csv](https://github.com/nocodb/nocodb/files/7360563/polish_translations.csv)

**Comment by kinga-marszalkowska** [comment]
Thank you @sesam for the help, I corrected the mistakes in the JSON file :)

**Comment by christiaanwesterbeek** [comment]
I'd like to fix some typos in the dutch translation file. But furthermore I see that formal and informal is mixed (je / u). In German I would say it would always be formal, but in Dutch I would go for informal, but formal would be fine too. When for a language (like Dutch) both formal and informal are excepted, which is preferred by nocodb?
