### ISSUE TITLE
🔦 Feature: Incomplete translation display

### ISSUE THREAD

**Issue by starmisszhang** [nocodb/nocodb#6338]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When I am using it, I can always see many English settings. Although I have set them to Chinese and registered Crowdin, there are no options for Crowdin without translation

### Suggested Solution

I hope to provide more translation options and try to make translation coverage close to perfection. I am also happy to work with everyone to improve translation

### Additional Context

![screenshot20230909 (1)](https://github.com/nocodb/nocodb/assets/19522799/b89f8dd6-04fd-4477-b16f-8a92885859e6)
![screenshot20230909 (5)](https://github.com/nocodb/nocodb/assets/19522799/1836b6d9-20e8-4107-ad58-b84d9650963e)
![screenshot20230909 (4)](https://github.com/nocodb/nocodb/assets/19522799/a578a5ef-b612-456d-90f9-212be7297b5e)
![screenshot20230909 (3)](https://github.com/nocodb/nocodb/assets/19522799/2a4b6039-af32-411d-839f-7f3d21496d7d)
![screenshot20230909 (2)](https://github.com/nocodb/nocodb/assets/19522799/80574bec-c666-4ab6-9f2a-354895cad7a4)
![screenshot20230909](https://github.com/nocodb/nocodb/assets/19522799/cc2286f1-be72-4d96-a4f2-13349d7244e9)

**Comment by dstala** [comment]
@starmisszhang Thank you for providing details. We have missed to include strings for translation in few menu items. Will add them soon, so that they appear in Crowdin for subsequent work. Will keep you posted

**Comment by jkalousek** [comment]
Same is happening with Czech translation but additionally we have a lot of missing strings that are just showing key names instead of English like:
![image](https://github.com/nocodb/nocodb/assets/8996764/037c5a54-ce22-4559-aa27-86930e62c1b6)
![image](https://github.com/nocodb/nocodb/assets/8996764/b4ddcd51-4cb9-49bc-8bd3-805013e58b45)
![image](https://github.com/nocodb/nocodb/assets/8996764/e896aa0f-089f-4cd1-bcdb-4308a5b4338c)

**Comment by frankMagoba** [comment]
Hi @wingkwong Can I pick this up or it's been assigned already?

**Comment by dstala** [comment]
@frankMagoba Assigned.

**Comment by mateusztylec** [comment]
Hi. Is there an estimated time when this feature will be implemented?
