### ISSUE TITLE
🔦 Feature: REST API Parameter unification

### ISSUE THREAD

**Issue by starmisszhang** [nocodb/nocodb#6339]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

(DB Table Row , DB View Row)  All using the Name parameter.
(DB Table ,DB Table Column)   All using the Id parameter.

### Suggested Solution

I hope to operate with unified parameters,It's better to use Name for simplicity.
I hope to add the DELETE FROM function,Many times it is necessary to clear the database, and I have to manually do so

### Additional Context

![screenshot20230909](https://github.com/nocodb/nocodb/assets/19522799/77a0726d-2915-4d74-8d73-5273388fb9b3)
![screenshot20230909 (1)](https://github.com/nocodb/nocodb/assets/19522799/1f387077-5b69-484e-bef9-18c81aecb341)

**Comment by dstala** [comment]
@starmisszhang we will likely move away from project name (or table name, field name) - and rely more on associated IDs. This will help APIs remain in tact even when associated entity gets renamed.

**Comment by starmisszhang** [comment]
@dstala associated ID It's also very good, I just suggest using unified parameters.
DELETE FROM Is this feature easy to add?

**Comment by dstala** [comment]
> DELETE FROM Is this feature easy to add?

Something like https://www.1keydata.com/sql/sqldelete.html?

It will be easier to get it done using existing set of APIs (List records using filter, Delete). So a specific API just to do it might need string reasoning. You have any?

**Comment by starmisszhang** [comment]
Thank you, I know how to do it now
