### ISSUE TITLE
🐛 Bug: Migration from 0108002 to 0111002 failed

### ISSUE THREAD

**Issue by FerLSanchez** [nocodb/nocodb#6345]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have a Noco docker deployed since long ago, updated through watchtower without issues until now. Since two days ago, it's not starting, with Migration from 0108002 to 0111002 failed error showing in the log (with a loooooooong message after, plenty of \, I can share if needed).

Thank you!

### Desired Behavior

Starting...

### Project Details

I can't access this.

**Comment by FerLSanchez** [comment]
If it helps, the problem appears just after "Starting upgrade for LTAR relations in XCDB bases to add missing index"

**Comment by o1lab** [comment]
Ok please DM @pranavxc in our discord.
