### ISSUE TITLE
🐛 Bug: Access select list not active after searching collaborators

### ISSUE THREAD

**Issue by DavidIsaacBPS** [nocodb/nocodb#6346]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Select project
2. Click Collaborator
3. Enter user name in "Search collaborators" field
4. See that Access select dropdown is grayed out

### Desired Behavior

User should be able to set access after searching for a user

### Project Details

Linux binary install v 0.111.2

**Comment by frankMagoba** [comment]
Hello @o1lab, am I able to take on this task, or has it already been allocated to someone else?
