### ISSUE TITLE
🔦 Feature: Add "collaborator" field type to support assignments

### ISSUE THREAD

**Issue by DavidIsaacBPS** [nocodb/nocodb#6356]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Allow responsibility for an item to be assigned to an authorized user for the project.  This field type would ensure that only a current project member is assigned.  It would also enable related features, such as automatic notification of users when an item has been assigned to them.

### Suggested Solution

Create a new "Collaborator" field type that is a special type of selection list, which is linked to the project users.  

### Additional Context

See Airtable Collaborator field type for an example.

**Comment by timkley** [comment]
This is actually one of the only things holding us back from switching from Airtable. It's such an important feature that I was a little surprised it doesn't exist. Especially given the feature set already present in this project.

Would love to see this added :)

**Comment by dstala** [comment]
To be tracked under

[[Feature] Link to User](https://github.com/nocodb/nocodb/issues/2382)
