### ISSUE TITLE
🐛 Bug: The expansion of long text is not available in the shared table view

### ISSUE THREAD

**Issue by AlienHub** [nocodb/nocodb#6359]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. In the edit state, you can use an expansion to view long text content
![image](https://github.com/nocodb/nocodb/assets/44266450/cc9d134a-7a94-4f44-b6bb-35f3150caf41)
2. You can not click expand to view long text in the table's shared view
![image](https://github.com/nocodb/nocodb/assets/44266450/dcab8ad1-31d6-4c03-98ee-17fa6e0c11c0)

### Desired Behavior

1. Support for viewing long text by expansion in shared view, as in Edit mode

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.3**

### Attachments

Related:
#2271 
#5945

**Comment by sheldon-welinga** [comment]
Hi @o1lab , is this issue available to be picked?

**Comment by wingkwong** [comment]
@sheldon-welinga assigned.
