### ISSUE TITLE
🐛 Bug: Unclear documentation about choosing a database

### ISSUE THREAD

**Issue by mauriciabad** [nocodb/nocodb#6364]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

> This is not a bug, but a documentation improvement.

In the `README.md` > `Quick Try` > `Docker`

There are comments saying `# for SQLite`, `# for MySQL`, `# for PostgreSQL` and `# for MSSQL`.

These comments are very ambiguous and don't explain "What the database type is for" or why it matters. 

I'm relatively new into backend stuff, and I thought that I had to choose the same database as the one I wanted to connect to. So I was trying to put my external database URL in the `NC_DB` env variable, but my tables were not showing up. 

Nowhere is explained that you can set up NocoDB with, let's say, SQLite and manage a db in MySQL. It may seem obvious, but it wasn't to me as the first time seeing this software. 

In the page [Data Sources > Accessing Data Sources](https://docs.nocodb.com/setup-and-usages/meta-management/#accessing-data-sources) you show that connecting to other DBs is possible, but it looks like an extra feature, and that the proper DB has to be the one that is marked as `Default`. 

### Desired Behavior

1. In the README, explain that the different commands just indicate the database that NocoDB will use internally, but that doesn't influence the ability to connect to a different database type.
2. In Data sources page (inside the Project dashboard), clarify what is the `Default` db is the `Internal` db used by NocoDB to save configurations and also additional tables you may want to create inside the instance.
    - A possible solution: Adding an ![info](https://img.icons8.com/?size=1x&id=82742&format=png) icon with a tooltip containing a small explanation, next to the `Default` label, and renaming `Default` to `NocoDB` or `Internal`.

### Project Details

_Not relevant_

**Comment by dstala** [comment]
@mauriciabad Thanks for the detailed comment. We are enhancing our documentation & will capture this information explicitly.

**Comment by dstala** [comment]
@mauriciabad some related details are captured here, if you had missed it out
https://docs.nocodb.com/engineering/architecture

**Comment by dstala** [comment]
updated readme
https://github.com/nocodb/nocodb/blob/develop/README.md
