### ISSUE TITLE
🐛 Bug: undo don't work properly

### ISSUE THREAD

**Issue by sudoexec** [nocodb/nocodb#6371]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Created a record from expanded row
- Then open the webhook and edit, the undo(Ctrl+Z) will delete last record

### Desired Behavior

When edit webhook, undo should be disable.
Related PR: https://github.com/nocodb/nocodb/pull/5989

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.6**

**Comment by mertmit** [comment]
Thank you for the report, this will be included in next release
