### ISSUE TITLE
🐛 Bug: default value not applied if value was modified before submitting link shared form

### ISSUE THREAD

**Issue by michag86** [nocodb/nocodb#6372]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- create a table with the column "port" of type number
- set the default value "443" for the column "port"
- create a form for this table
- share the form by link
- open the form via link
- type a number in the field "port"
- remove the value so that it is empty
- press submit

### Desired Behavior

There is a new record created with value 443 in the column port, because the field from the form was empty.

Actual Behavior:
column is empty because the form is send with value "null" for column "port"
This only happens on shared form. Submitting form as registered user works fine.
For shared form value is also applied correctly, if the column "port" was not modified

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **false** (podman)
RootDB: **sqlite3**
PackageVersion: **0.109.1**

**Comment by sheldon-welinga** [comment]
Hi @o1lab, can I pick this issue?

**Comment by wingkwong** [comment]
@sheldon-welinga assigned
