### ISSUE TITLE
🐛 Bug: 

### ISSUE THREAD

**Issue by masciugo** [nocodb/nocodb#6373]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

By starting from a fresh nocodb installation and create a very basic project I still get the old rest API url with the random projectId in the path instead of `{orgs}/{projectName}`

### Desired Behavior

Having the new New URL Path (>v0.90) as stated in the docs

### Project Details

Node: **v16.20.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.111.4**

**Comment by wingkwong** [comment]
This is by design in latest version. We had replaced title with id to keep it same even after changing the project title. Actually we support both title and id in api path but it recommended to use id over title since in future we are planning to remove title support.

**Comment by masciugo** [comment]
Fair enough. Thank you
