### ISSUE TITLE
🐛 Bug: Sidebar being Inverted

### ISSUE THREAD

**Issue by DarkPhoenix2704** [nocodb/nocodb#6374]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Saw this randomly 3 Times. 
Couldn't reproduce again. Reloading page fixes the issue

### Desired Behavior

The ProjectNodes should be above the EmailID

### Project Details

```
Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.2**
```

### Attachments

![image](https://github.com/nocodb/nocodb/assets/64391274/ca9d36b4-6dbf-464f-9947-91c39b329837)

**Comment by wingkwong** [comment]
+ 1

**Comment by dstala** [comment]
not noticed with recent release. reopen if you find a way to reproduce
