### ISSUE TITLE
🐛 Bug: Search Box Autosearch --> executing to many api calls

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#6379]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

The search box is retriggered automatically with each new number or letter in the box.

As an example, I enter "Hello World" in the field. The API now fires 
like '%H%'
like '%He%'
like '%Hel%'
....
like '%Hello World%'

### Desired Behavior

The search box should be executed with Enter or a magnifying glass.

### Project Details

0.111.4
PG
DOCKER

**Comment by dstala** [comment]
We can consider adding a delay instead of waiting for `Enter` key to be pressed.

**Comment by emre1e** [comment]
yeah it should be also fine, but not to long :)

**Comment by dstala** [comment]
debounce set to 600ms;
