### ISSUE TITLE
🐛 Bug: Tables in sidebar always showed titlecased 

### ISSUE THREAD

**Issue by masciugo** [nocodb/nocodb#6381]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I add a base by specifying inflection none (which should be the default imho)

<img width="643" alt="image" src="https://github.com/nocodb/nocodb/assets/454321/2f2390c3-a4ef-4812-8583-c8325c04aea8">

It works but the tables showed on the sidebar are still titlecased

<img width="1113" alt="image" src="https://github.com/nocodb/nocodb/assets/454321/b9fd265b-3afc-403a-b48d-8cd30e71f420">

### Desired Behavior

the tables should showed in the same manner everywhere. Thank you

### Project Details

Node: **v16.20.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.111.4**

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/6768
