### ISSUE TITLE
🐛 Bug: Import Data button doesn't work correctly for Excel imports

### ISSUE THREAD

**Issue by lvarming** [nocodb/nocodb#6385]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

We tried to import an Excel sheet into a MS SQL 2022 database in Nocodb 0.111.4 using the large Import Data button. We then choose Excel and drag/dropped the Excel sheet. The Excel parser is slow and after pressing Import we never get the data from Excel into the database. It's like Nocodb works on something but nothing happens.

![image](https://github.com/nocodb/nocodb/assets/111744156/ac60f1ca-3870-47e1-b0c3-939a023909c0)

We then tried the "old" way of pressing the three small dots next to the project, choose "Quick Import From > Microsoft Excel". The Excel parser is a lot faster here and after pressing Import on the exact same Excel sheet the data is imported after 12-13 seconds.

### Desired Behavior

Pressing the Import Data button and the three small dots, choose "Quick Import From > Microsoft Excel" should give the exact same outcome. 

### Project Details

Nocodb 0.111.4 (winx64 version (.exe))
Windows server 2022
MS SQL 2022

**Comment by dstala** [comment]
@lvarming could you help us know if issue is still reproducible in latest release? you can close this issue if it isn't.

**Comment by dstala** [comment]
if you can share a sample redacted file, we can try and fix issue. please open this thread if you have a sample file for us to work with or additional logs. recommend you to try on v0.202.5 as some fixes have gone in recently.
