### ISSUE TITLE
🐛 Bug: Collaborator Access is read only

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#6391]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Press on Project go to collaborators. Access is read only.

![image](https://github.com/nocodb/nocodb/assets/117290601/cc56dacc-6bc4-41d1-9007-d2d136f4cee3)

### Desired Behavior

Should be editable. Im Super Admin

### Project Details

nocodb/nocodb-timely:0.111.4-pr-6375-20230914-0909
Docker
PG

**Comment by dstala** [comment]
@emre1e You might not have access provided to that project by the project creator. Our current design doesn't allow collaboration edit if you do not have access to project.

**Comment by emre1e** [comment]
i have access to the project. Im Super Admin + Creator in this project.

**Comment by emre1e** [comment]
Ok sorry. More Infos:

First opening all are read only.
I scroll down to the end then i can edit editor, viewers and commenters
Creators are still read only.

**Comment by emre1e** [comment]
btw how can i set Owners? I have no Owners in this project, so nobody can delete oder update creators.

**Comment by dstala** [comment]
fixed in latest release
