### ISSUE TITLE
Confusing / Misleading Create Database

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#6398]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When you click `New Project`, a Create Database modal will pop up as below. From the text, it looks like NocoDB would create a new database for me. However, it won't create a database behind the scene. It just creates a new project.

![image](https://github.com/nocodb/nocodb/assets/35857179/faa35a8f-46b4-4b3c-84b9-f3805f0b1604)

If you create a new table under this so-called new `Database`, basically the table is just created under `NC_DB`. The icons are also misleading, as they are just projects, not databases at all.
![image](https://github.com/nocodb/nocodb/assets/35857179/a0e47ba8-bb36-4a73-bbbc-be464e457f67)

### Desired Behavior

- A proper label should be `Create Project`. As when you delete it, it shows `Delete Project`, not `Delete Database`.
- The icon should be revised as well. Using a database icon is misleading.

### Project Details

Node: **v18.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **mssql**
PackageVersion: **0.111.4**

**Comment by thevinitgupta** [comment]
I would love to work on this.

**Comment by dstala** [comment]
resolved in new UI
