### ISSUE TITLE
🐛 Bug: Linked item fields show wrong order in popup

### ISSUE THREAD

**Issue by nowrds** [nocodb/nocodb#6403]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When you click on a linked item, a popup will show you all the details of the linked item, where you can edit them as well.
Unfortunately, the order of the fields is fixed and does not reflect the order in the table. 
From my tests, it looks like the fields are ordered by the time the columns were created in the table.
It's even worse when you import tables from Airtable. The order in which the fields are created is quite random.

To reproduce this problem

1. Create 2 tables and add a few columns to the table that will contain the linked value (easiest to name them from 1 ascending).
2. Fill a field with some values so you can link it
3. Add a "Link" column type in the other table
4. Add the linked element with some values
5. Open the linked item in the link column and check the field order in the popup.
6. Change the field order in the linked item table
7. Check the field order in the popup for changes

### Desired Behavior

It would be great if the fields of the linked items represented the order of the columns in their table and changes to the order in the table were reflected in the pop-up of the linked items.

### Project Details

Docker: true
Version: 0.111.4
Database: sqlite3

### Attachments

![SCR-20230916-kxzv](https://github.com/nocodb/nocodb/assets/108593063/84cfdbd0-3a6b-4d15-8bc6-3ccca3c47494)

**Comment by mr-loop-1** [comment]
Hi @nowrds @wingkwong , I would like to work on this. Please assign me

**Comment by dstala** [comment]
![Screenshot 2023-10-21 at 1 05 54 PM](https://github.com/nocodb/nocodb/assets/86527202/a64d730b-f671-4b60-a25a-138cefe43925)

**Comment by dstala** [comment]
Order of the fields can be inferred from default view always.

**Comment by mr-loop-1** [comment]
Hi @dstala , I would like to work on this. Can you please assign me.
