### ISSUE TITLE
🐛 Bug: Emoji not visible after modifying the corresponding smartsheet

### ISSUE THREAD

**Issue by geone-cloud** [nocodb/nocodb#6406]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a smartsheet
2. Add an emoji on this smartsheet in the left menu
3. Modify a column in this smartsheet.
4. Then the emoji sometimes disappears

### Desired Behavior

The emoji should stay visible.

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.107.5**

**Comment by dstala** [comment]
@geone-cloud issue reported is on older version of NocoDB. Let us know if you still face this issue with our latest release. 
https://github.com/nocodb/nocodb/releases/tag/0.111.4

**Comment by dstala** [comment]
reopen if you still see issue with latest release
