### ISSUE TITLE
🐛 Bug: Tables appear several times in the left menu times after Syncing metadata

### ISSUE THREAD

**Issue by geone-cloud** [nocodb/nocodb#6407]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a project with differents views for your smartsheet (ex Customer table, Top Customers view)
2. Sync Metadata
3. Then when have two Customer tables in the left menu.

### Desired Behavior

There should be juste one table of each.

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.107.5**

**Comment by dstala** [comment]
@geone-cloud reopen this issue if you are able to reproduce with new release.
