### ISSUE TITLE
generated uuid is not returned on record creation with rest API

### ISSUE THREAD

**Issue by arrowcircle** [nocodb/nocodb#641]
**Please enter the following details**

NocoDB used as docker : true
NocoDB version : 0.11.42
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Ubuntu 20.04
Node.js version if running as node : as in docker image
Database version : Postgres 14.0

**Steps To Reproduce**
1. Create any table
2. Add any field with uuid type with `gen_random_uuid()` default value
3. Create any record with rest api. Result will include null value for the field.

**Expected behavior**
Result should include generated uuid.

**Comment by o1lab** [comment]
@fgkolf - please go for it

**Comment by fgkolf** [comment]
@arrowcircle I tried to reproduce this problem but didn't manage to. Here is my project info:
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.11.42**

I run a docker image of postgres v14.0 and created a project by _connecting to external database_. 
I created a table and a column of type `ID` with the config shown below:
![image](https://user-images.githubusercontent.com/23259199/137585817-9dffb6b0-953a-4149-8c10-cd389f06d31a.png)

Then created a record through the api and the fiels seems to be populated and returned as expected.
![image](https://user-images.githubusercontent.com/23259199/137585843-85fc11a6-3f2e-4906-861b-6b1a57c341d2.png)

Am i missing something in the reproduction configuration above?

**Comment by o1lab** [comment]
Thank you @fgkolf - @arrowcircle can you clarify on this ?

**Comment by pranavxc** [comment]
> @arrowcircle I tried to reproduce this problem but didn't manage to. Here is my project info: Node: **v12.22.6** Arch: **x64** Platform: **linux** Docker: **true** Database: **pg** ProjectOnRootDB: **false** RootDB: **pg** PackageVersion: **0.11.42**
> 
> I run a docker image of postgres v14.0 and created a project by _connecting to external database_. I created a table and a column of type `ID` with the config shown below: ![image](https://user-images.githubusercontent.com/23259199/137585817-9dffb6b0-953a-4149-8c10-cd389f06d31a.png)
> 
> Then created a record through the api and the field seems to be populated and returned as expected. ![image](https://user-images.githubusercontent.com/23259199/137585843-85fc11a6-3f2e-4906-861b-6b1a57c341d2.png)
> 
> Am i missing something in the reproduction configuration above?



Please do the following :

- Delete the default primary column 
- Create a new column and select `ID`
- Expand the advance option and select both `not null` and `pk`
- Set default value as `gen_random_uuid()` and click `Save` button

**Comment by o1lab** [comment]
Please feel to reopen if its reproducible.
