### ISSUE TITLE
🐛 Bug: linked modal search doesn't work when accessing 2nd page onwards

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6418]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

open linked records modal
navigate to second page
searc

### Desired Behavior

search should work

### Project Details

x

**Comment by DarkPhoenix2704** [comment]
- [ ] Close Links Modal on Escape
- [ ] Skeleton Loader
