### ISSUE TITLE
graphql query throws sql error

### ISSUE THREAD

**Issue by cybrwshl** [nocodb/nocodb#643]
**Please enter the following details**

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.11.42**

**Steps To Reproduce**
1. create table item
2. create table invoice
3. create column with link to another record on item.id (many to many)
4. query with graphql:
```
{
  InvoiceList {
    ItemList {
      title
    }
  }
}
```
5. get error:
`"message": "(select \"xa5__item\".\"id\" as \"id\", \"xa5__item\".\"created_at\" as \"created_at\", \"xa5__item\".\"updated_at\" as \"updated_at\", \"xa5__item\".\"description\" as \"description\", \"xa5__item\".\"xa5__invoice_id\" as \"xa5__invoice_id\" from \"xa5__item\" where \"xa5__invoice_id\" = $1 limit $2) limit $3 - multiple LIMIT clauses not allowed",`

**Expected behavior**
get no error and all data returned.

**Comment by wingkwong** [comment]
GQL has been deprecated.
