### ISSUE TITLE
🐛 Bug: Autonumber column not working

### ISSUE THREAD

**Issue by DavidIsaacBPS** [nocodb/nocodb#6435]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create table with first column "Autonumber" type
2. Create several records
3. Wait a few days
4. Create another record
5. See that the Autonumber column is blank.

### Desired Behavior

Autonumber should continue to work.

### Project Details

Docker=false
DB=SQLite
Machine=Linux x86 AWS instance t2.medium, binary install.
Version=0.111.2

### Attachments

![Screenshot 2023-09-21 153908](https://github.com/nocodb/nocodb/assets/131489274/caa88c2f-44f3-457c-bb72-2fb0f8187f17)

**Comment by wingkwong** [comment]
Are you sure that column is `AutoNumber`? I've seen that `AutoNumber` has been deprecated  5 months ago and couldn't create it in latest version.

**Comment by cppchriscpp** [comment]
If it helps I'm seeing this too, and it's in tables I imported from airtable in the past couple weeks.

**Comment by DavidIsaacBPS** [comment]
Confirmed that column type is Autonumber based on Airtable import, but Autonumber cannot be selected for new columns.  So, I guess it is really just Number now.  NOTE: Airtable Collaborator column similarly is shown as original Airtable type but is really just Text.  

+1 on request to add/restore this feature...very handy for creating unique IDs for user stories, issues, and lots of other things.

**Comment by DavidIsaacBPS** [comment]
I will close this issue and open as a feature request.

**Comment by DavidIsaacBPS** [comment]
Moving to feature request.

**Comment by DavidIsaacBPS** [comment]
Moving to feature request.
