### ISSUE TITLE
🐛 Bug: Form view attachments issue

### ISSUE THREAD

**Issue by alprotasov** [nocodb/nocodb#6436]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

**Precondition**
Create a table with attachment field
Create form view

**Steps to reproduce:**
Open the form
Attach one file
Try to attach a new one file to the same field

**AR:**
There is no possibility to add another file to the same field

### Desired Behavior

There is an icon to "open" attachment field to add more files 

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.111.4**

### Attachments

![att_field](https://github.com/nocodb/nocodb/assets/7497700/fb61dcdc-fa12-44b0-93c8-2486136424a4)

**Comment by wingkwong** [comment]
Able to reproduce.

![image](https://github.com/nocodb/nocodb/assets/35857179/b07f34d7-791a-4a84-9467-f16a0c9737cc)

**Comment by sheldon-welinga** [comment]
Hi @o1lab, can I work on this?

**Comment by o1lab** [comment]
@sheldon-welinga : assigned
