### ISSUE TITLE
🔦 Feature: SEARCH function should support searching from the end

### ISSUE THREAD

**Issue by AndrewSav** [nocodb/nocodb#6448]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Let's say I have a field "FilePath", e.g. "/path/to/my/file". I want to have a formula field with just the file name, that is "file", in this example.

### Suggested Solution

There should be a more flexible way to search, then the SEARCH function. E.g.:

`SUBSTR({FilePath},SEARCHLAST({FilePath},'/')+1)`

### Additional Context

Other SEARCH improvements, such as ability to specify start index for search, or specify which occurrence of the search string we are after are also welcome.

**Comment by dstala** [comment]
Regular expressions are supported now & you can use something like `REGEX_EXTRACT({Title}, ".*/([^/]+)")`

Note that, regular expression related formula functions should be available from next feature release scheduled in this month end

**Comment by jfreake** [comment]
> Regular expressions are supported now & you can use something like `REGEX_EXTRACT({Title}, ".*/([^/]+)")`
> 
> Note that, regular expression related formula functions should be available from next feature release scheduled in this month end

Has this been implemented yet? @dstala

**Comment by dstala** [comment]
@jfreake Supported. Let us know if you face any issue.

**Comment by jfreake** [comment]
Current version info:
Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.204.5**


None of the REGEX functions (Extract, Match, Replace) are autocompleting. Even if I try to manually type them in and ignore the autocompletion, the formula field will not save.

![2024-03-14 12_02_55-NocoDB](https://github.com/nocodb/nocodb/assets/6330871/ccc58331-8722-4fd1-bf80-bb8086fa413f)

![2024-03-14 12_02_36-NocoDB](https://github.com/nocodb/nocodb/assets/6330871/caa01603-7e5e-4e80-98cc-cbc1cb36d1c3)


Maybe still listed as unsupported?
![image](https://github.com/nocodb/nocodb/assets/6330871/8365b4dc-294f-4c1a-886a-29d9ab6ca990)

**Comment by jfreake** [comment]
@dstala should I open a new issue for this?
