### ISSUE TITLE
🐛 Bug: Columns created as "LinkToAnotherRecord" moved to "Links" but still showing child records instead of new display

### ISSUE THREAD

**Issue by jer-dot** [nocodb/nocodb#6453]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Upgrade to 0.111 version with new feature "LinkToAnotherRecord" instead to "Links".
Table columns of type "LinkToAnotherRecord" created before the upgrade still displaying all child records instead of the new display : <number of child records> <child table>

### Desired Behavior

"LinkToAnotherRecord" upgraded to "Links" use the new simplified display

### Project Details

NocoDB version : 0.111.4

**Comment by dstala** [comment]
@jer-dot by design, we didn't migrate `LinkToAnotherRecord` type to `Links` as we didn't want to disturb existing deployed systems. Only newly created relations will be of type `Links`
