### ISSUE TITLE
🐛 Bug: Data source sync action not present in frontend

### ISSUE THREAD

**Issue by MichaelCereda** [nocodb/nocodb#6479]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Navigate to a project > Data sources.
Stare into the abyss.

### Desired Behavior

Navigate to a project > Data sources.
Under actions, I should be able to click "Sync Data Source"

### Project Details

NocoDB version 0.111.4

### Attachments

![image](https://github.com/nocodb/nocodb/assets/107390/c8d15156-7bbc-45ff-a8b0-e6dee4cc2c03)

**Comment by o1lab** [comment]
Its available for external data source and not the internal ones.
