### ISSUE TITLE
🐛 Bug: Linked modal issues

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#6482]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] Update table icon in sidenavbar
- [x] First time linked modal is opened - the skeleton is not seen. 
- [x] From links field we already know how many links are present - so only those many skeleton should be loaded.
- [x] The display value overflow in linked modal
<img width="864" alt="image" src="https://github.com/nocodb/nocodb/assets/5435402/28746e3a-bd9e-4965-a044-3322e306ba78">

### Desired Behavior

.

### Project Details

.

**Comment by dstala** [comment]
![Screenshot 2023-10-01 at 7 23 07 PM](https://github.com/nocodb/nocodb/assets/86527202/e681d791-b507-4004-a122-5684a7abe2f1)

**Comment by dstala** [comment]
- [ ] Audit auto scroll
- [ ] Audit icons showing same colour
- [ ] Audit icons in bold in audit, not bold in comments. keep it bold in both
- [ ] Project icon & table icon - confirm with Shreyas
