### ISSUE TITLE
🐛 Bug: The content of the button "Save" is cut in some languages

### ISSUE THREAD

**Issue by geone-cloud** [nocodb/nocodb#6485]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Set Language to French
2. Open a Detail formular from a row
3. The content of the "Save button" does not show completely. It might also happen for other langages.

Having to click on the three dots  each time to close the formular is not practical.

### Desired Behavior

The text in the button should be visible completely.
Have a "Close" button to close the Formular (like in the previous versions)

### Project Details

Node: **v18.13.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.111.4**

### Attachments

![bug](https://github.com/nocodb/nocodb/assets/108124336/2f55a6f1-7799-489d-979a-2deab02a56c9)

**Comment by frankMagoba** [comment]
Hi @o1lab can I work on this?

**Comment by o1lab** [comment]
@frankMagoba : assgined

**Comment by frankMagoba** [comment]
Hi @o1lab , a quick clarification, after puling latest changes, I'm unable to replicate the issue, could you help confirm if it was resolved?
<img width="1440" alt="Screenshot 2023-09-27 at 08 43 16" src="https://github.com/nocodb/nocodb/assets/38047577/9a08eb04-dec5-46ec-8f23-2c4da9cf8ffc">

**Comment by wingkwong** [comment]
No longer reproducible with the new UI design. Will be available in the next release.
