### ISSUE TITLE
🐛 Bug: Expanded view save should be disabled till there is an edit

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#6503]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] Enable save only on edit.
- [ ] Column name labels are quite dark.
- [ ] Link for the record button is needed. (same as in ee)

### Desired Behavior

.

### Project Details

.

**Comment by dstala** [comment]
![Screenshot 2023-10-06 at 3 55 14 PM](https://github.com/nocodb/nocodb/assets/86527202/aa00b04b-f7c3-4d50-b7d5-35604cc84a61)
