### ISSUE TITLE
Grid View UX Issues

### ISSUE THREAD

**Issue by WarWolf47** [nocodb/nocodb#6505]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

/

### Desired Behavior

/

### Project Details

Give Extra padding on right side of grid to allow user to scroll and bring [+ field] button to centre
![image](https://github.com/nocodb/nocodb/assets/116950167/42535826-7bfc-4c4e-bc04-8bb7a17f24fb)

Highlight field that is being edited, & time field shows calendar icon instead of clock icon in grid
![image](https://github.com/nocodb/nocodb/assets/116950167/eb292c30-dbf1-4b61-ad72-1a34c9618a2b)

Auto scroll and bring new field into centre after it is created
![image](https://github.com/nocodb/nocodb/assets/116950167/3a649d7a-b739-4f50-a11f-c00629931836)

Default name for fields should be in format: Untitled {field type} field, Untitled {field type} field 2, Untitled {field type} field 3 etc.
![image](https://github.com/nocodb/nocodb/assets/116950167/a8318af2-e4cd-487c-86e2-9f9890bc34a4)

Search field dropdown icon only shows on hover
![image](https://github.com/nocodb/nocodb/assets/116950167/4ba8339f-b9ba-4b9f-8cdc-01ad7e72ea1d)

New Record button gets covered when scrolled to view other fields
![Screenshot 2023-09-27 at 6 48 11 PM](https://github.com/nocodb/nocodb/assets/116950167/5879bd3e-1d83-4186-9a62-133c6580be4c)

Replace check/uncheck icons with ones attached
![image](https://github.com/nocodb/nocodb/assets/116950167/8c1018f6-a2bc-4031-8d9a-d2ca94d492b2)

View options, delete hover needs to be red-100
![image](https://github.com/nocodb/nocodb/assets/116950167/7d8b7439-21ca-498e-aa68-a9e83e9e641b)

### Attachments

![Checkbox-unchecked](https://github.com/nocodb/nocodb/assets/116950167/41521c91-5d87-4d36-a8a9-d0f9e98e3e3e)
![Checkbox](https://github.com/nocodb/nocodb/assets/116950167/69dc69bc-9c6d-4f7c-bef5-045c71ffc50b)

**Comment by dstala** [comment]
Pending items
- [ ] checkbox icon change
- [ ] `add-edit`modal : highlight field that is being edited, & time field shows calendar icon instead of clock icon in grid


Deferred
- [ ] Default name for fields should be in format: Untitled {field type} field, Untitled {field type} field 2, Untitled {field type} field 3 etc.
- [ ] Auto scroll and bring new field into centre after it is created

**Comment by reenphygeorge** [comment]
So default name should be like title1, title2, ... ?

**Comment by reenphygeorge** [comment]
Can you provide the new checkbox icon.
Also the `add-edit modal` issue is not reproducible for me.

**Comment by WarWolf47** [comment]
@reenphygeorge the default name for 
A ‘link’ field type should be: untitled link field, untitled link field 2 and so on
A ‘phone number’ field type: untitled phone number field, untitled phone number field 2 and so on
If there is an ‘untitled link field’ and the user creates a phone number field the default name will be ‘untitled phone number field’ and NOT ‘untitled phone number filed 2’ numbering will start only if an unnamed filed of the same field type exists

**Comment by dstala** [comment]
should we consider getting rid of `Untitled`; the field name becomes tad lengthy.
