### ISSUE TITLE
Bug: Sidebar is not shown properly on initial load

### ISSUE THREAD

**Issue by sreehari2003** [nocodb/nocodb#6518]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![image](https://github.com/nocodb/nocodb/assets/66205494/b832123b-48af-4800-8e81-a0d15d8e90fe)

### Desired Behavior

it should not crash

### Project Details

on initial loading the sidebar is miss aligned but if you restart it or reload it it works fine

.

**Comment by sreehari2003** [comment]
## LOGS


![image](https://github.com/nocodb/nocodb/assets/66205494/2ca0a3c7-9ea6-4e9e-b58e-6b5bdd84eeb4)



https://github.com/nocodb/nocodb/assets/66205494/c4efa3ca-d9bf-49d7-ab55-222ac9c9c15e

**Comment by dstala** [comment]
closing this. if issue happens again, reopen
