### ISSUE TITLE
🐛 Bug: Expanded record

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6520]
https://github.com/nocodb/nocodb/issues/6506

### Steps to reproduce ?

- [x] Remove `Expand` for long text
- [x] Comments: all user name are displayed using same icon colour
- [x] Comments: if user name is not configured, we should display name part of the email
- [x] Save modal is old
- [x] Delete modal is not in red
- [x] Left padding needs fix for few data types like Links, DateTime, etc.
![Screenshot 2023-09-29 at 11 08 42 AM](https://github.com/nocodb/nocodb/assets/86527202/a8bcca61-c5db-4303-a82a-67796d6278c8)
- [x] remove table name from display
- [x] for last record, next record navigation should be disabled
- [ ] flickering when navigating between records should not exist
- [x] comments should auto scroll to show the latest one 
- [ ] verify keyboard shortcuts
<img width="936" alt="Screenshot 2023-09-29 at 3 19 42 PM" src="https://github.com/nocodb/nocodb/assets/86527202/ac9ff19e-4654-431a-acd1-20782869b150">

**Comment by WarWolf47** [comment]
- [ ] Text truncation handled

![image](https://github.com/nocodb/nocodb/assets/116950167/5a74763d-87d4-4336-a26e-1c54f021d1ea)

**Comment by sreehari2003** [comment]
some of the issued are handled here #fix/link
