### ISSUE TITLE
🐛 Bug:  Missing bottom radius for field

### ISSUE THREAD

**Issue by DarkPhoenix2704** [nocodb/nocodb#6523]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a table with only one column

### Desired Behavior

There should be bottom radius

### Project Details

.

### Attachments

![image](https://github.com/nocodb/nocodb/assets/64391274/18a709e2-d327-4935-9643-2f5a750e7031)

**Comment by pedrobruneli** [comment]
Can i work on this? @DarkPhoenix2704

**Comment by sreehari2003** [comment]
> Can i work on this? @DarkPhoenix2704

@pedrobruneli  yes
