### ISSUE TITLE
🐛 Bug: WebHook configuration options doesn’t show

### ISSUE THREAD

**Issue by maaper** [nocodb/nocodb#6525]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Install NocoDB in docker on my Synology NAS.

### Desired Behavior

Wanted to config a trigger using webhooks everytime I update a row and everytime I add a row in a table, but doesn’t find the options to configure them.
I will use n8n to configure the webhooks.

### Project Details

node:%20**v16.20.1**%0AArch%3A%20**x64**%0APlatform%3A%20**linux**%0ADocker%3A%20**true**%0ARootDB%3A%20**pg**%0APackageVersion%3A%20**0.111.4**

### Attachments

![IMG_0748](https://github.com/nocodb/nocodb/assets/56989894/43e00669-275c-47da-9a6a-8a7826f51c6a)

**Comment by maaper** [comment]
Now I see that the issue only happens on Safari for IPAD browser.
Is there any way to solve?
Thanks.

**Comment by dstala** [comment]
@maaper we have a new release v0.202.4; can you confirm if you still see this issue with that release?

**Comment by dstala** [comment]
@maaper please reopen this thread if issue persists with v0.202.5+
