### ISSUE TITLE
🐛 Bug:  A line on screen when we try to delete  a column

### ISSUE THREAD

**Issue by sreehari2003** [nocodb/nocodb#6526]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![image](https://github.com/nocodb/nocodb/assets/66205494/5e2a17f1-dc73-4157-be99-a935f7930f99)

### Desired Behavior

therese should not be aline

### Project Details

/

### Attachments

* create a table
* create a cloumn
* delete the column

**Comment by bharathkalyans** [comment]
* As we shift the window focus, it automatically goes away!

**Comment by bharathkalyans** [comment]
* Plus what I have observed is that the white line appears on the axis of that particular column only, see the below recording for more info

https://github.com/nocodb/nocodb/assets/49526472/25b01fbd-9946-4a3c-8fd5-4dbd375ba929

* I think the bug has to do something with the modal positioning!!

**Comment by bharathkalyans** [comment]
* Tried recreating this issue again, but the white line didn't appear this time!!!!!

**Comment by sreehari2003** [comment]
### How To reproduce ? 
 
 * right click(context menu)  on the column header the line will appear , it is only noticeable when we open the delete modal

**Comment by mustafapc19** [comment]
Have been fixed with this [PR](https://github.com/nocodb/nocodb/pull/6803)
