### ISSUE TITLE
🐛 Bug: Grid creation modal is having a large delay when closed

### ISSUE THREAD

**Issue by sreehari2003** [nocodb/nocodb#6527]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

try creating a grid and cancel the issue

### Desired Behavior

.

### Project Details

.

### Attachments

https://github.com/nocodb/nocodb/assets/66205494/f5289517-311e-4cb5-b60d-76ad036bb549

**Comment by frankMagoba** [comment]
Hi @o1lab can I work on this? I found the bug.

**Comment by dstala** [comment]
@frankMagoba assigned

**Comment by o1lab** [comment]
Closing this as its [resolved](https://github.com/nocodb/nocodb/pull/6538#issuecomment-1750417881) in develop.
