### ISSUE TITLE
🐛 Bug:  xls import does not work.

### ISSUE THREAD

**Issue by cocoonkid** [nocodb/nocodb#6556]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Try to import xls

![image](https://github.com/nocodb/nocodb/assets/43231640/1ff138b4-5f68-42ba-888e-075944c0b9e8)

### Desired Behavior

Import the xls

### Project Details

nocodb docker  latest

**Comment by dstala** [comment]
@cocoonkid can you share details about the version of NocoDB that you are using? You can copy project info from the project or user menu

**Comment by dstala** [comment]
we have a new release (v0.202.4). please reopen this, preferably with a sample redacted excel if issue is still reproducible.
