### ISSUE TITLE
🐛 Bug: When I switched to Simplified Chinese, some languages didn't switch over. Why?

### ISSUE THREAD

**Issue by mrchenxxx** [nocodb/nocodb#6564]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When I switched to Simplified Chinese, some languages didn't switch over. Why?

### Desired Behavior

Hope to be able to write in Simplified Chinese

### Project Details

Hope to be able to write in Simplified Chinese

### Attachments

![image](https://github.com/nocodb/nocodb/assets/44868578/245f6f5e-6af4-46ed-b61a-fb7554a54696)
![image](https://github.com/nocodb/nocodb/assets/44868578/2778c2b6-8185-4825-80f0-17cb92ab5088)
![image](https://github.com/nocodb/nocodb/assets/44868578/a41f367c-ca38-45dd-85bf-accad75ec532)

**Comment by dstala** [comment]
Support for language translations is community driven (crowdin) & we also have few places where we have not enabled internationalisation (i18n) - like column title.

**Comment by mrchenxxx** [comment]
> Support for language translations is community driven (crowdin) & we also have few places where we have not enabled internationalisation (i18n) - like column title.

What am I supposed to do?

**Comment by dstala** [comment]
We are working on including missing labels & text for i18n that appear in English by default even after language switch. You can help us by
- identifying such instances you see & reporting us here
- prepare a PR to hep fix such instances

We have noted down the one's that you have listed in this PR & will work soon to close on it.

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/6613
