### ISSUE TITLE
German translations: request for proofreading

### ISSUE THREAD

**Issue by sesam** [nocodb/nocodb#657]
I'm no native speaker, but the German translation has at least one translation that looks out of context. We cannot have it like that now, can we :)

The one I especially noticed was `projects.notifications.clear` that is currently translated to `Klar` but should be something more in the direction of `Löschen`

Any native German speakers, or someone using German software daily, please take a read through https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit?usp=sharing

**Comment by o1lab** [comment]
https://github.com/nocodb/nocodb/pull/672
