### ISSUE TITLE
🔦 Feature: Reindex/ Refresh Field names manually

### ISSUE THREAD

**Issue by tfbecker** [nocodb/nocodb#6587]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

After adding a new field in a PostgreSQL table I cannot find the field.
ALTER TABLE "nc_9842___ScreeningLovisa" ADD COLUMN IF NOT EXISTS "DateAdded" DATE;

There should be a button to refresh/ reindex the table schema.

I now have to create/ change column names via NocoDB GUI to do this.

### Suggested Solution

Refresh button for tables

**Comment by tfbecker** [comment]
I realized that this is available for external datasources but not if you set up NocoDb with railway.app.

**Comment by dstala** [comment]
We strongly recommend not to make any changes to the schema directly for bases created using NocoDB UI. There can be multiple bases on same instance, there are many virtual column types managed by NocoDB & hence it becomes very tedious for us to handle various scenarios.
