### ISSUE TITLE
🔦 Feature: Pop Up for delete confirmation

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#6596]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Now, if you accidentally delete rows, NocoDB does not ask if you are sure you want to delete the whole row. 

Sometimes you want to press clear but accidently pressing "Delete Row"

![image](https://github.com/nocodb/nocodb/assets/117290601/a5ee175d-b6ec-4068-997e-baaa77ccb524)

### Suggested Solution

It should open a pop up asking if I am sure to delete the whole line/row.

Would this be possible.

**Comment by dstala** [comment]
You can undo `Delete row` using Cmd Z; 
if you are facing any issue with Undo, please reopen this or create a new issue.
