### ISSUE TITLE
🐛 Bug: All Multiselect Options Spontaneously Deleted From Field

### ISSUE THREAD

**Issue by dbrand-s** [nocodb/nocodb#6602]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Unclear. All options have been wiped from the only one multiselect field and removed from all records. All other multiselect fields are intact. I suspect this happened when adding a link between tables on a different field. I had not otherwise touched the system for 24 hours.

### Desired Behavior

Data should not spontaneously delete.

### Project Details

Node: **v16.20.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.111.4**

**Comment by dstala** [comment]
couldn't reproduce. @dbrand-s if you can find any other clue to help reproduce this issue, let us know.

**Comment by dstala** [comment]
@dbrand-s please reopen this issue if you are able to reproduce. we will try from our end too, to see if we can reproduce it locally.
