### ISSUE TITLE
🐛 Bug: Error: “Only 1000 records are allowed in your table, for more please upgrade your plan”

### ISSUE THREAD

**Issue by stephen-ondyr** [nocodb/nocodb#6679]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Just started using the SaaS version. Pretty buggy and feels half baked so far. Not giving up on it yet but hopefully it improves soon.

The latest issue I am trying to working through is the error: “Only 1000 records are allowed in your table, for more please upgrade your plan”

I got this when I was trying to add 2000 more rows via csv import to a DB table that already had 1000 rows and this popped up. No mention of a limit like this from what I saw when signing up. Any ways to getting past this?

### Desired Behavior

Successful import

### Project Details

Saas

### Attachments

![nocodb error](https://github.com/nocodb/nocodb/assets/49404691/8da681d2-be0a-44e6-b7fd-8d88710834af)

**Comment by o1lab** [comment]
Closing it here. [Details here](https://community.nocodb.com/t/getting-error-only-1000-records-are-allowed-in-your-table-please-upgrade-your-plan/888/2).
