### ISSUE TITLE
🐛 Bug: SQLite created-at, updated-at says `Invalid Date`

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6683]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![Screenshot 2023-10-13 at 4 35 08 PM](https://github.com/nocodb/nocodb/assets/86527202/a7bc1565-8ea3-4e53-9fbc-d04883aa7c05)

### Desired Behavior

Populate date appropriately

### Project Details

Node: **v18.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.202.4**

**Comment by chaturrved** [comment]
I would like to work on this. please assign me.

**Comment by dstala** [comment]
@chaturrved any progress on this?
