### ISSUE TITLE
🐛 Bug: development setup in docs doesn't mention nocodb-sdk error

### ISSUE THREAD

**Issue by razaahmad333** [nocodb/nocodb#6686]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Follow the Development setup guide available on docs 
https://docs.nocodb.com/engineering/development-setup

after installing when tried to start frontend or backend 
got an error, which talks about not availability of "nocodb-sdk"

for backend
```sh
ERROR Internal server error: Failed to resolve entry for package "nocodb-sdk". The package may have incorrect main/module/exports specified in its package.json.
```
and something similar in frontend too

### Desired Behavior

If I follow the Development setup guide, I should not get any error

### Project Details

Installing nocodb for development purpose

**Comment by razaahmad333** [comment]
But when I ran the command 
```sh
pnpm install local-sdk
```
and then started frontend and backend
It worked!

Should I update the docs and give pr accordingly?

**Comment by wingkwong** [comment]
Use `pnpm bootstrap` instead of `pnpm i`.
