### ISSUE TITLE
🐛 Bug: (CLOUD) Route is not changing when clicked on table node (Not reproducible)

### ISSUE THREAD

**Issue by sreehari2003** [nocodb/nocodb#6693]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

click on table node

### Desired Behavior

it should show the grid

### Project Details

.

### Attachments

https://github.com/nocodb/nocodb/assets/66205494/cb152df8-87b6-4e74-aad3-615795c89b70

**Comment by sreehari2003** [comment]
## i couldnt reproduce this issue but I noticed something else
 

https://github.com/nocodb/nocodb/assets/66205494/e9184e1f-fcec-4a41-bb17-33ea50546107

**Comment by sreehari2003** [comment]
![image](https://github.com/nocodb/nocodb/assets/66205494/48b96596-01d9-450c-8be8-12e0de098197)

**Comment by o1lab** [comment]
@sreehari2003 : the screenshot seems not related to original issue raised here. If you 've doubts like this pls reach out internally through our chat in slack.

**Comment by dstala** [comment]
reopen if you are able to reproduce with latest release.
