### ISSUE TITLE
🐛 Bug: Table context menu missing shadow

### ISSUE THREAD

**Issue by sreehari2003** [nocodb/nocodb#6694]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

.

### Desired Behavior

.

### Project Details

.

### Attachments

![image](https://github.com/nocodb/nocodb/assets/66205494/12a08450-1a20-45bd-a3cf-0b24c767bb31)

**Comment by dstala** [comment]
looks fine in OSS/develop

**Comment by dstala** [comment]
reopen if you still find this issue
