### ISSUE TITLE
🐛 Bug: webhook cannot set IP address as URL

### ISSUE THREAD

**Issue by AlienHub** [nocodb/nocodb#6696]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![image](https://github.com/nocodb/nocodb/assets/44266450/771c3d37-54af-4f50-8510-6de334124ae4)

### Desired Behavior

Can use IP address as webhook URL

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.4**

**Comment by dstala** [comment]
@AlienHub You can set environment variable `NC_ALLOW_LOCAL_HOOKS=true`
https://docs.nocodb.com/getting-started/self-hosted/environment-variables

**Comment by AlienHub** [comment]
> @AlienHub You can set environment variable `NC_ALLOW_LOCAL_HOOKS=true` https://docs.nocodb.com/getting-started/self-hosted/environment-variables

Thank !
