### ISSUE TITLE
🐛 Bug: Failed to load list: b.startsWith is not a function when linking records

### ISSUE THREAD

**Issue by TobiasDax** [nocodb/nocodb#6697]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

We have a base with two tables. Table A has entries with a lot of metadata and around 120 entrie Table B has a kanban board for issues and references entries from Table A. When i go to link entries and use the search function to find the correct entriy i get the error message

`Failed to load list: b.startsWith is not a function
`
The find function is also not working, the list of entries does not get smaller

The Main Field for Table A and the thing i am searching for is a Number Field.

Also if i am Searching for anythiung else besides a number (string of text) i get an even more convoluted error:

`Failed to load children list: select (select count("__nc_rollup"."ncRecordId") from "nc_3b6m___Videoproduktion" as "__nc_rollup" inner join "nc_3b6m___nc_m2m_aq3jk50nk1" on "nc_3b6m___nc_m2m_aq3jk50nk1"."table2_id" = "__nc_rollup"."ncRecordId" where "nc_3b6m___nc_m2m_aq3jk50nk1"."table1_id" = "nc_3b6m___Stundenproduktion"."ncRecordId") as "Videoproduktion", (select count("__nc_rollup"."ncRecordId") from "nc_3b6m___Stundenproduktion" as "__nc_rollup" inner join "nc_3b6m___nc_m2m_o4fhlh5xqe" on "nc_3b6m___nc_m2m_o4fhlh5xqe"."table1_id" = "__nc_rollup"."ncRecordId" where "nc_3b6m___nc_m2m_o4fhlh5xqe"."table2_id" = "nc_3b6m___Stundenproduktion"."ncRecordId") as "Stundenproduktions", (select count("__nc_rollup"."ncRecordId") from "nc_3b6m___Stundenproduktion" as "__nc_rollup" inner join "nc_3b6m___nc_m2m_o4fhlh5xqe" on "nc_3b6m___nc_m2m_o4fhlh5xqe"."table2_id" = "__nc_rollup"."ncRecordId" where "nc_3b6m___nc_m2m_o4fhlh5xqe"."table1_id" = "nc_3b6m___Stundenproduktion"."ncRecordId") as "Field 57", "nc_3b6m___Stundenproduktion"."Nummer" as "Nummer", "nc_3b6m___Stundenproduktion"."Vorschauvideo" as "Vorschauvideo", "nc_3b6m___Stundenproduktion"."Video_01_Vorwissen_aktivieren" as "Video 01 - Vorwissen aktivieren", "nc_3b6m___Stundenproduktion"."Video_02_Einf_hrung" as "Video 02 - Einführung", "nc_3b6m___Stundenproduktion"."_bung_03_mit_Grafiken_" as "Übung 03 (mit Grafiken)", "nc_3b6m___Stundenproduktion"."Video_04_Erarbeitung" as "Video 04 - Erarbeitung", "nc_3b6m___Stundenproduktion"."_bung_05_mit_Grafiken_" as "Übung 05 (mit Grafiken)", "nc_3b6m___Stundenproduktion"."Video_06_Vertiefung" as "Video 06 - Vertiefung", "nc_3b6m___Stundenproduktion"."Video_07_Ergebnissicherung" as "Video 07 - Ergebnissicherung", "nc_3b6m___Stundenproduktion"."Arbeitsblatt_mittel_" as "Arbeitsblatt (mittel)", "nc_3b6m___Stundenproduktion"."Abschlusstest_mittel_" as "Abschlusstest (mittel)", "nc_3b6m___Stundenproduktion"."_bung_08_mit_Grafiken_" as "Übung 08 (mit Grafiken)", "nc_3b6m___Stundenproduktion"."Danksagungen_vollst_ndig" as "Danksagungen vollständig", "nc_3b6m___Stundenproduktion"."Metadaten_vollst_ndig" as "Metadaten vollständig", "nc_3b6m___Stundenproduktion"."Fremdlogos_und_Nutzungsrechte" as "Fremdlogos und Nutzungsrechte", "nc_3b6m___Stundenproduktion"."Vorschauvideo_Link_" as "Vorschauvideo (Link)", "nc_3b6m___Stundenproduktion"."Video_01_Link_" as "Video 01 (Link)", "nc_3b6m___Stundenproduktion"."Video_02_Link_" as "Video 02 (Link)", "nc_3b6m___Stundenproduktion"."Video_04_Link_" as "Video 04 (Link)", "nc_3b6m___Stundenproduktion"."Video_06_Link_" as "Video 06 (Link)", "nc_3b6m___Stundenproduktion"."Video_07_Link_" as "Video 07 (Link)", "nc_3b6m___Stundenproduktion"."Bereich" as "Bereich", "nc_3b6m___Stundenproduktion"."Abschlusstest_schwer_" as "Abschlusstest (schwer)", "nc_3b6m___Stundenproduktion"."Abschlusstest_leicht_" as "Abschlusstest (leicht)", "nc_3b6m___Stundenproduktion"."Arbeitsblatt_schwierig_" as "Arbeitsblatt (schwierig)", "nc_3b6m___Stundenproduktion"."Arbeitsblatt_leicht_" as "Arbeitsblatt (leicht)", "nc_3b6m___Stundenproduktion"."Video_01_Button" as "Video 01 Button", "nc_3b6m___Stundenproduktion"."Video_02_Button" as "Video 02 Button", "nc_3b6m___Stundenproduktion"."Video_04_Button" as "Video 04 Button", "nc_3b6m___Stundenproduktion"."Video_06_Button" as "Video 06 Button", "nc_3b6m___Stundenproduktion"."Video_07_Button" as "Video 07 Button", "nc_3b6m___Stundenproduktion"."Vorschauvideo_Button" as "Vorschauvideo Button", "nc_3b6m___Stundenproduktion"."Skript" as "Skript", "nc_3b6m___Stundenproduktion"."Gesamtstatus" as "Gesamtstatus", "nc_3b6m___Stundenproduktion"."Jahrgangsstufe" as "Jahrgangsstufe", "nc_3b6m___Stundenproduktion"."Autor" as "Autor", "nc_3b6m___Stundenproduktion"."Skript_Link_" as "Skript (Link)", "nc_3b6m___Stundenproduktion"."Skript_ffnen" as "Skript öffnen", "nc_3b6m___Stundenproduktion"."Ver_ffentlicht" as "Veröffentlicht", "nc_3b6m___Stundenproduktion"."Gedreht" as "Gedreht", "nc_3b6m___Stundenproduktion"."Name" as "Name", "nc_3b6m___Stundenproduktion"."Protagonist" as "Protagonist", "nc_3b6m___Stundenproduktion"."Produktionsleitung" as "Produktionsleitung", "nc_3b6m___Stundenproduktion"."Kamera" as "Kamera", "nc_3b6m___Stundenproduktion"."Ton" as "Ton", "nc_3b6m___Stundenproduktion"."Schnitt" as "Schnitt", "nc_3b6m___Stundenproduktion"."Animationen_und_Grafiken" as "Animationen und Grafiken", "nc_3b6m___Stundenproduktion"."YouTube_Teaser" as "YouTube Teaser", "nc_3b6m___Stundenproduktion"."YouTube_Link" as "YouTube Link", "nc_3b6m___Stundenproduktion"."Dreh_Ordner" as "Dreh-Ordner", "nc_3b6m___Stundenproduktion"."Aufgaben_entsprechen_dem_Arbeitsblatt" as "Aufgaben entsprechen dem Arbeitsblatt", "nc_3b6m___Stundenproduktion"."Abschlusstest_entspricht_dem_Arbeitsblatt" as "Abschlusstest entspricht dem Arbeitsblatt", "nc_3b6m___Stundenproduktion"."_berpr_ft_von" as "überprüft von", "nc_3b6m___Stundenproduktion"."Antares_Jahr" as "Antares-Jahr", "nc_3b6m___Stundenproduktion"."_fn_utitel_" as "'fn_utitel'", "nc_3b6m___Stundenproduktion"."Antares_Nummer" as "Antares-Nummer", "nc_3b6m___Stundenproduktion"."Antares_Schlagw_rter" as "Antares-Schlagwörter", "nc_3b6m___Stundenproduktion"."Antares_Teaser" as "Antares-Teaser", "nc_3b6m___Stundenproduktion"."Antares_URL" as "Antares-URL", "nc_3b6m___Stundenproduktion"."Antares_Lernziele" as "Antares-Lernziele", "nc_3b6m___Stundenproduktion"."Antares_Bemerkung" as "Antares-Bemerkung", "nc_3b6m___Stundenproduktion"."ncRecordId" as "ncRecordId", "nc_3b6m___Stundenproduktion"."ncRecordHash" as "ncRecordHash" from "nc_3b6m___Stundenproduktion" inner join "nc_3b6m___nc_m2m_aq3jk50nk1" on "nc_3b6m___nc_m2m_aq3jk50nk1"."table1_id" = "nc_3b6m___Stundenproduktion"."ncRecordId" where "nc_3b6m___nc_m2m_aq3jk50nk1"."table2_id" in (select "ncRecordId" from "nc_3b6m___Videoproduktion" where "ncRecordId" = 'rc_hq88ky0d81hi65') and (("Nummer" = '' or "Nummer" is not null)) limit 10 - invalid input syntax for type bigint: ""`

My Table Data is imported from AIrtable, so mybe something got messed up there?

### Desired Behavior

When i search for an entry while linking Tables it should display that entry and no error messages

### Project Details

NocoDB runs a s a docker through the provided docker-compose file

Base Info:
Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.4**

### Attachments

![Screenshot (69)](https://github.com/nocodb/nocodb/assets/42605856/63269bdc-1e82-4ce5-9ccb-5a10d5d4c969)
![Screenshot (70)](https://github.com/nocodb/nocodb/assets/42605856/d79a9d20-70ce-4d55-bc71-0719ddc48cf9)

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/commit/cd8b6a1f33532881981547cc98d8085f0db8d51c

**Comment by TobiasDax** [comment]
@dstala I just realised that my issue seemed to be two issues in one. The first one from the title is fixxed since your update, but the second part (the longer errror message) is still prevalent.

Not sure if best practice is reopening this issue or creating a new one for the second half of this issue.
Thanks for the quick help
