### ISSUE TITLE
🐛 Bug: The page is displayed as the key of the i18n json file

### ISSUE THREAD

**Issue by AlienHub** [nocodb/nocodb#6700]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![image](https://github.com/nocodb/nocodb/assets/44266450/c95f6657-2b0f-4094-aca2-44c0d3af14d4)

### Desired Behavior

Display text content correctly

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.4**

**Comment by dstala** [comment]
I tried few & worked fine for me on my docker v0.202.4; which language did you set?

**Comment by AlienHub** [comment]
> I tried few & worked fine for me on my docker v0.202.4; which language did you set?

Simplified Chinese

**Comment by dstala** [comment]
Unable to reproduce. @wingkwong able to find any clue?

**Comment by wingkwong** [comment]
I couldn't reproduce as well. @AlienHub can you try the following

- hard refresh
- try other langs to see if it happens the same

**Comment by o1lab** [comment]
I have seen this behaviour once while talking to a customer who was using Polish language.

**Comment by AlienHub** [comment]
> I couldn't reproduce as well. @AlienHub can you try the following
> 
> * hard refresh
> * try other langs to see if it happens the same

I use docker-compose to deploy, and it seems that only English is normal, other languages have problems, and it is clear that the browser cache is also invalid.

**Comment by AlienHub** [comment]
![image](https://github.com/nocodb/nocodb/assets/44266450/be691d01-b068-43a9-97e6-a0197d8ba52b)
![image](https://github.com/nocodb/nocodb/assets/44266450/32c670e6-b75a-429a-9aa5-302a91798e65)
![image](https://github.com/nocodb/nocodb/assets/44266450/f06557ef-bcc4-40e1-8d66-a84ed1d0e808)

**Comment by AlienHub** [comment]
> I couldn't reproduce as well. @AlienHub can you try the following
> 
> * hard refresh
> * try other langs to see if it happens the same

I found that it was normal after switching from English to Chinese, but once I clicked the browser's refresh button, the English in the page changed to the key value.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/6758
