### ISSUE TITLE
🐛 Bug: custom singular / plural label for links field was reset after docker restart

### ISSUE THREAD

**Issue by bfansheng** [nocodb/nocodb#6702]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. custom singular / plural label
2. docker compose restart

### Desired Behavior

keep it after restart

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.202.4**

**Comment by wingkwong** [comment]
What do you mean by custom singular / plural label? Please provide more details and steps for us to reproduce the issue.

**Comment by bfansheng** [comment]
> What do you mean by custom singular / plural label? Please provide more details and steps for us to reproduce the issue.

1. Modify label values
![image](https://github.com/nocodb/nocodb/assets/16935251/584f7c46-e6ed-484e-841b-1e0960824a1a)
![image](https://github.com/nocodb/nocodb/assets/16935251/1531e9d7-5a7c-4ef9-970f-092988e549ba)

2. restart docker 
![image](https://github.com/nocodb/nocodb/assets/16935251/6b10d83a-e235-40ec-ade2-632a5075daf6)

3. The label value has been restored
![image](https://github.com/nocodb/nocodb/assets/16935251/f0aaefeb-b4bb-497b-ac4a-b16f08c552a8)
