### ISSUE TITLE
🐛 Bug: Cloud : import in csv file 

### ISSUE THREAD

**Issue by AshikDavidRoy** [nocodb/nocodb#6703]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

While importing a CSV file, the format of the record changed, and the `Field-Type` changed to `SingleLineText` while the original  
`Field-Type`  was `MultiSelect`.Also, the color palette of the `MultiSelect` is gone when imported.

### Desired Behavior

Hopefully, the format does not change when imported.

### Project Details

NocoDB Cloud

**Comment by o1lab** [comment]
Are you using the cloud or selfhosted - provide the version number of nocodb.

If its latest 0.202.4 : you can change it back to multiselect from column options.

**Comment by AshikDavidRoy** [comment]
Using the cloud

**Comment by o1lab** [comment]
Thank you for the confirmation.

cc : @mertmit

**Comment by dstala** [comment]
@AshikDavidRoy Will help if you can share redacted CSV file & clear steps to reproduce.

**Comment by dstala** [comment]
I know @reenphygeorge CSE 👍 :)

**Comment by dstala** [comment]
on v202.5, 
Department & Status were identified as `Single Select`
`Category`- I manually changed to `Multi Select` & it worked. 

There are few fixes gone in v202.5 release. See if it helps. If you need some more auto detection, will be happy to receive a PR on that. 

![Screenshot 2023-10-21 at 11 57 50 AM](https://github.com/nocodb/nocodb/assets/86527202/2f593c00-c089-4eec-ad5c-32bbbff554db)

**Comment by AshikDavidRoy** [comment]
Okay....
thank you appreciate your assistance
