### ISSUE TITLE
🐛 Bug: Import error `Uncaught SyntaxError: Cannot use import statement outside a module`

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6720]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Uncaught SyntaxError: Cannot use import statement outside a module

### Desired Behavior

No error

### Project Details

Node: **v18.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.202.4**

**Comment by wingkwong** [comment]
preliminary finding: 

- caused by this commit https://github.com/nocodb/nocodb/pull/6708/commits/610524c443a4dc7386d6eb3d790ad926b3c9c7a1
