### ISSUE TITLE
🐛 Bug: Image permalinks broke after update - how to get new ones? 

### ISSUE THREAD

**Issue by zblesk** [nocodb/nocodb#6745]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Repro steps: just upgrading NocoDb.

I use NocoDB for data, parts of which are extracted into a different system. 
That includes links to images. The other system just hotlinks to NocoDB.

Previously, the URLs were easy to construct and looked something like this: 

`/download//OrtduwPNi3O7C7bwot`

Now, the same image sits at: 

`/dltemp/kCEJFZUozAEqWv57/1697758800000//OrtduwPNi3O7C7bwot`

Looking at multiple links, I don't see how to extract a permalink; and the use of word "temp" in there seems to hint the link might change again.

### Desired Behavior

I need a static, unchanging link to an image resource. How to get it? 

Thank you.

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.4**

ps: you may wanna change the wording here; "Click on top left icon and click Copy Project Info." is no longer correct.

**Comment by dstala** [comment]
From recent release, two environment variables are introduced. These should help control behaviour. I will get back with exact details in a while.

https://docs.nocodb.com/getting-started/self-hosted/environment-variables

NC_SECURE_ATTACHMENTS
NC_ATTACHMENT_EXPIRE_SECONDS

**Comment by zblesk** [comment]
Thank you. But something still isn't right. 

- I didn't specify NC_SECURE_ATTACHMENTS (I didn't even know it exists) - but the old links still broke after update.
- I tried explicitly setting NC_SECURE_ATTACHMENTS  to False in the compose file, but it hasn't changed anything. 
- The original URL `/download//_u8NJi5XwViCi-9H9N` returns `/usr/app/data/nc/uploads/_u8NJi5XwViCi-9H9N`. If I try getting that from the browser, I get JSON saying `{"msg":"Cannot GET /usr/app/data/nc/uploads/_u8NJi5XwViCi-9H9N"}`.

Why is this getting deprecated? 
Seems like it'll make integrating to NocoDb harder.

**Comment by mertmit** [comment]
There was an issue with old link support thank you for the report. After my PR it will be fixed so you can keep using your old links without any change (no need to recreate or smth.)

On deprecation part: we support shared views and shared bases so any external user can have access to those permanent links and even after you stop sharing they will be exposed. In our new approach all links will be temporarily available (2~hours by default but you can change with new environment variable) so even if you share a view or base your attachments are not going to be exposed after you stop sharing.

I would be glad if you can share your use-case, and let me know why new approach is not working for you.

Thanks~

**Comment by zblesk** [comment]
Okay, thank you. I will wait for that update. 

Maybe I'll be able to make the new approach work, I'll have to see how NocoDB handles it when finalized. 

Basically, my approach is - for this case, I'm circumventing NocoDB and reading straight from the DB. 
I need to extract data from various data sources and send them to an indexer. Instead of calling APIs, I just query the DB and generate everything, including static image URLs, in one go. 

The important thing here is that once the item is indexed, the image was always available.

It would take a lot longer to get the data via API calls; and I would have to refresh them periodically, for the entire index. 
I'm not saying it's not doable. Again, we'll see if it's worth it after things are finalized. 

Thanks again for your time.

**Comment by dstala** [comment]
@zblesk Thanks you for your inputs on this. Closing this thread for now. You can reopen this later (or create a new one) if you need more help on this.
