### ISSUE TITLE
🐛 Bug: Not getting correct response in webhook payload.

### ISSUE THREAD

**Issue by RahimDobani** [nocodb/nocodb#6746]
### Please confirm if bug report does NOT exists already ?

- [x] I confirm there is no existing issue for this

### Steps to reproduce ?

Attach webhook url to any table of nocodb and check response in your webhook response body.

### Desired Behavior

Why webhook response is coming like this 
{
  '{"type":"records.after.insert","id":"ced0d079-72b6-470e-99d5-f5ed6255bd77","data":{"table_id":"md_ofshl8723ymhva","table_name":"forms_entry_adnananwarali","view_id":"vw_zwmr2jt5zqskj8","view_name":"forms_entry_adnananwarali","rows":': {
    '{"Id":52,"CreatedAt":"2023-10-13 12:56:32","UpdatedAt":"2023-10-13 12:56:32","req_id":null,"form_id":"333333","entry_data":null,"language":"en"}': ''
  }
}
but in example its shown like this
{
  "type": "records.after.insert",
  "id": "32e366b6-32a5-4444-a334-d9e30042f313",
  "data": {
    "table_id": "md_ofshl8723ymhva",
    "table_name": "forms_entry_adnananwarali",
    "view_id": "vw_zwmr2jt5zqskj8",
    "view_name": "forms_entry_adnananwarali",
    "rows": [
      {
        "Id": 1,
        "CreatedAt": "2023-10-13T08:11:07.913Z",
        "UpdatedAt": "2023-10-13T08:11:07.913Z",
        "req_id": "Sample Text",
        "form_id": "Sample Text",
        "entry_data": "{}",
        "language": "Sample Text"
      }
    ]
  }
}
also i have updated to latest version.

### Project Details

{
  "name": "help",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "echo \"Build\"",
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js",
    "upgrade": "npm uninstall --save nocodb && npm install --save nocodb"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "nocodb": "^0.202.4"
  }
}

NC_DB=mysql2://localhost:3306?u=root&p=&d=pagematic_master_instance
PORT=3060
NC_ALLOW_LOCAL_HOOKS=true

**Comment by dstala** [comment]
Node: **v18.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **mysql2**
PackageVersion: **0.202.4**

I tried inserting record, both from UI & API. Webhook response was as in sample.

{
  "type": "records.after.insert",
  "id": "53ec4dec-fe04-4c1b-94d7-04444117d40b",
  "data": {
    "table_id": "mfhfyhg0iitdp7a",
    "table_name": "Features",
    "rows": [
      {
        "Id": 4,
        "Title": "Test",
        "CreatedAt": "2023-10-20 06:30:05+00:00",
        "UpdatedAt": "2023-10-20 06:30:05+00:00"
      }
    ]
  }
}

**Comment by aboveagency** [comment]
I can reproduce this bug with update events

**Comment by manwithpowers** [comment]
I can reproduce this with update events, as well.
