### ISSUE TITLE
🐛 Bug: Filters not updating after upgrade

### ISSUE THREAD

**Issue by ckunderd** [nocodb/nocodb#6752]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Whenever I try to update a filter or add a new filter, no filtering happens. When I reload the URL from the browser, no filter changes have been saved. 

### Desired Behavior

When I filter, I want to see the filtering change. 

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.202.4**

### Attachments

https://watch.screencastify.com/v/ALTx2Vam819ZnyxFqgQ0

**Comment by dstala** [comment]
@ckunderd 
- what role are you in for this base? 
- check on console if you see any error?
- does this happen just on existing table after migration or even for filters created on new table?

**Comment by dstala** [comment]
@ckunderd 
we suspect it could be with `auto save` option disabled earlier with filters.

Please try the following & let us know if it helps
- Open `Applications` tab
- Select `Local storage`
- Right click on key `nocodb-gui-v2`
- `Delete`

Reopen project. Let us know if it helps.

![Screenshot 2023-10-20 at 5 05 31 PM](https://github.com/nocodb/nocodb/assets/86527202/2ef3087e-f00b-4815-80bd-35e7b497d7f1)

**Comment by ckunderd** [comment]
Yep that worked for sure! Thank you!

**Comment by dstala** [comment]
Thanks for the confirmation @ckunderd!
