### ISSUE TITLE
🐛 Bug: Webhook link can't be private IP address of LAN

### ISSUE THREAD

**Issue by snowity** [nocodb/nocodb#6757]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I want to test webhook function to trigger a link of the same server. So I use the LAN IP address of the server 192.168.2.x, but it can't be webhook link address. When I use http://192.168.2.x:5001/..., the error log tell me that this IP address is a private address that can't be webhook address.

### Desired Behavior

In regard of many webhook trigger address maybe on the same server, it must be a private IP address like 127.0.0.1, 10.x.x.x, 172.x.x.x or 192.168.x.x.  So if the relevant module config-file could be adjust to allow all IP address include private address, it'll be much better to match the situation

### Project Details

NocoDB used as docker : true
NocoDB version : 0.202.4
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created : sqlite3
OS on which NocoDB is running :  Windows Docker Desktop
Node.js version if running as node : 18.17.1-r0
Database version : 

### Attachments

![image](https://github.com/nocodb/nocodb/assets/148554332/38a177f1-2dba-4f1a-a51d-fd8163de42c7)

**Comment by dstala** [comment]
@snowity Use environment variable `NC_ALLOW_LOCAL_HOOKS` to control this behaviour
https://docs.nocodb.com/getting-started/self-hosted/environment-variables

**Comment by snowity** [comment]
Thank you very much. When I set NC_ALLOW_LOCAL_HOOKS=true
this problem has been solved.
