### ISSUE TITLE
🔦 Feature: Search fields

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#6795]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

We have about 200 columns and its really hard to find the column in the Searchbox.

![image](https://github.com/nocodb/nocodb/assets/117290601/800b19f6-fd29-4d8e-a48f-611fca670231)

### Suggested Solution

Create a textfield where you can filter the columns.

Like in Excel:

![image](https://github.com/nocodb/nocodb/assets/117290601/acd31344-9985-4265-8f2e-f304cbfe99ed)

**Comment by dstala** [comment]
- autocomplete search 
- experiment with `CMD K` for fields

**Comment by emre1e** [comment]
@dstala any news? :)

**Comment by emre1e** [comment]
any news?

**Comment by salim-b** [comment]
This is implemented in latest NocoDB:

![Image](https://github.com/nocodb/nocodb/assets/20040931/7a21a887-278c-4e8d-bd3c-52d15927c26b)


@dstala I think this issue can be closed.
