### ISSUE TITLE
🐛 Bug: Default View not showing if you moved it to other row in past version

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#6798]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Noco 0.111.4

Move the Default view to position 2

Update to Noco 0.202.5.

Default View not showing anymore. If you added filter in the past version you cant edit it anymore and the API ist broken.

### Desired Behavior

Make Default View visible again in the Grid View or disable it completely.

### Project Details

Noco 0.202.5
PG
Docker.

**Comment by dstala** [comment]
@emre1e default view, since v0.202.4 is not listed explicitly in view list; but it is the one that gets displayed when you click on the table name in the left side bar.

**Comment by dstala** [comment]
API is broken. can you add some more details?

**Comment by emre1e** [comment]
The "db/data" API is associated with the primary view of a table.

As mentioned earlier (refer to my images), I have moved the primary view to position 2. Upon updating to version 0.202.5, the primary view is no longer displayed when I select the table name; instead, the view from position 1, which existed prior to the update, is shown.

If you had previously set any filters, you can't delete them now as the primary view, where this action is usually performed, is no longer displayed.

![image](https://github.com/nocodb/nocodb/assets/117290601/d182350c-08bc-4b46-baf5-e2eea712beae)

**Comment by dstala** [comment]
I had missed out your comment; can you provide your base information? You can copy base information from base context menu (use `...` next to your base name)

**Comment by emre1e** [comment]
Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.5-20231114-1154**

**Comment by emre1e** [comment]
The image provided earlier was an example. The main objective was to illustrate the issue. Before update it is crucial to ensure that the default view is set to position 1. If its not on the first position, its lost after the update. 

Now, if we click on the table name, it will directly jump to the view that occupied position 1 prior to the update.
