### ISSUE TITLE
🔦 Feature: Expanded Row Autosave and Searchtool

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#6799]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When a row is expanded for editing, there should be an auto-save feature. Occasionally, one might inadvertently click outside the window causing the pop-up to close without saving changes.

Alternatively, a warning message could be displayed when you click outside the pop-up without having first saved any changes.

Moreover, it would be beneficial to include a search box with selection options in the window. This would allow for editing multiple lines directly within the window and not opening the Window over and over again.

### Suggested Solution

See above

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/6834

**Comment by timkley** [comment]
@dstala from a UX perspective it would be better to provide an autosave functionality. How about triggering the save button automatically when the expanded record is closed, removing the need of manual saving and the modal entirely?
