### ISSUE TITLE
🔦 Feature: The Buttons in the Header Section Lacks Transition

### ISSUE THREAD

**Issue by DeepRahangdale** [nocodb/nocodb#6804]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Adding a transition of scale 95/105 on Hovering Over them !!
Good user Interface!!

### Suggested Solution

similar to this site.
https://drive.google.com/file/d/1Gm2KpWL_40dTaTYSwiTKyI3HPI0nPcQw/view?usp=sharing

**Comment by dstala** [comment]
@DeepRahangdale can you share a screenshot of "header" that you are discussing here.

**Comment by DeepRahangdale** [comment]
https://drive.google.com/file/d/1Pderl_s31RQoYNf-fsBx948CZag_Z_Qe/view?usp=sharing taking about this butons

**Comment by dstala** [comment]
to be discussed & taken care during next roll-out of web portal
