### ISSUE TITLE
🔦 Feature: Web clipper extension

### ISSUE THREAD

**Issue by ananggadipa** [nocodb/nocodb#6806]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Can it incorporate a web clipping feature similar to the one found in Airtable? This feature simplifies the process of extracting data from the web.

### Suggested Solution

Similar to what's available in Airtable: [Web Clipper Extension - Overview | Airtable Support](https://support.airtable.com/docs/web-clipper-extension)

**Comment by dstala** [comment]
duplicate of https://github.com/nocodb/nocodb/issues/5628
