### ISSUE TITLE
🔦 Feature: Table Level Access

### ISSUE THREAD

**Issue by cons-barathan** [nocodb/nocodb#6813]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

We are expecting Table level Access like, for every table we can add Users who can only View/Edit data
The users without View permission should not be able to view the particular table
Similarly user without Edit permission should not be able to Edit the particular table

### Suggested Solution

Add a option for every table to give permission to the Users and their Role

**Comment by dstala** [comment]
To be tracked under

[🔦 Feature: Row / Column base permission, last edited by / updated by and audit log](https://github.com/nocodb/nocodb/issues/5075)
