### ISSUE TITLE
🔦 Feature: Checkbox based Kanban Board

### ISSUE THREAD

**Issue by reenphygeorge** [nocodb/nocodb#6818]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently there is no option to categorize kanban based on checkbox.
For example for a field `Done` of type `Checkbox` a kanban can be created with two options [`checked` or `unchecked`]

### Suggested Solution

Add support to checkbox for categorizing kanban board

**Comment by dstala** [comment]
Kanban's are typically used for state management & support for checkbox would likely be fancy expansion. If still required, alternative exists as one can map checkbox field as true/false single select field. Closing this issue for now. We can revisit if there is a strong need for this case.
