### ISSUE TITLE
🔦 Feature: Use AWS instance/container IAM profiles for S3 access

### ISSUE THREAD

**Issue by spyoungtech** [nocodb/nocodb#6819]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Today, it is [required to explicitly define](https://github.com/nocodb/nocodb/blob/804edeeacf253e09ba58d9bfc0ac757f0e0163d7/packages/nocodb/src/helpers/NcPluginMgrv2.ts#L113-L118)  `NC_S3_ACCESS_SECRET` and `NC_S3_ACCESS_KEY`, which implies the necessity to create persistent access keys.

However, this should not be required when running NocoDB in an AWS service with builtin IAM roles, such as ECS task containers or EC2 instances, which can supply their own IAM roles through the environment. SDKs can access the builtin IAM roles without the need to configure static credentials.

The lack of this feature means that users must forego best practices of using builtin service-based roles and places an additional burden of provisioning, monitoring, and rotating standard access keys.

### Suggested Solution

NocoDB should only necessarily require `NC_S3_BUCKET_NAME` to configure use of object storage when running in AWS ECS or EC2 (or similar). For example, when running in ECS, the [ECS task role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) can be used for accessing S3.

The AWS SDK uses this as part of its standardized credential providers. When running AWS SDKs in AWS services, providing explicit access keys is not necessary and it will detect container task credentials automatically. Typically, this means just simply omitting the access key ID and secret key parameters altogether and relying on the normal [precedence of settings](https://docs.aws.amazon.com/sdkref/latest/guide/settings-reference.html#precedenceOfSettings) to automatically configure credentials.

**Comment by Upgreydd** [comment]
https://github.com/nocodb/nocodb/pull/9642
