### ISSUE TITLE
🐛 Bug: keyboard shortcut- map backspace to clear cell

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6821]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Macbook keyboard doesn't have delete button. Good to support backspace also as trigger for clear cell. (or selected cells).

### Desired Behavior

backspace should also clear cell

### Project Details

0.202.5

**Comment by wingkwong** [comment]
FYI. Delete in macbook is `fn + backspace`.
