### ISSUE TITLE
🐛 Bug: Webhook payload not escaped/formatted correctly

### ISSUE THREAD

**Issue by manwithpowers** [nocodb/nocodb#6822]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a webhook for a table with columns or records that characters that need to be escaped (&, ?, =, etc). Could also be due to URIs/links in records. Or linked records.
The corresponding payload I receive is not escaped correctly and is unparseable.
For example:
```
[
  {
    "headers": {
      "host": "n8n.**.com",
      "user-agent": "axios/0.21.4",
      "content-length": "1814",
      "accept": "application/json, text/plain, */*",
      "content-type": "application/x-www-form-urlencoded",
      "x-forwarded-for": "***",
      "x-forwarded-host": "n8n.***.com",
      "x-forwarded-proto": "https",
      "accept-encoding": "gzip"
    },
    "params": {},
    "query": {},
    "body": {
      "{\"type\":\"records.after.update\",\"id\":\"477a4ae4-96a1-4ef2-ab4f-ffc5d8111ae2\",\"data\":{\"table_id\":\"md_68ge795k0zdtbp\",\"table_name\":\"Schedule\",\"previous_rows\":[{\"ShowTime\":\"18:30:00\",\"Frequency\":\"Weekly\",\"NumOfClasses\":8,\"Instance\":\"Test (Mondays)\",\"Id\":176,\"Registrations\":0,\"AttendanceId\":null,\"CreatedAt\":null,\"TicketExp\":\"2024-02-29\",\"google_group\":\"\",\"EventId\":31002,\"LastModified\":null,\"Capacity\":16,\"ShowDate\":\"2024-02-29\",\"StartDate\":\"2024-01-08\",\"Notes\":\"\",\"EndTime\":\"21:30:00\",\"Skipping\":null,\"EventType\":\"Test\",\"InternalRef\":\"Test (Mondays)\",\"EndDate\":\"2024-02-26\",\"Sync to Site\":\"URI::(https://n8n.***.com/webhook/ae47680c-***-4191-86ec-4a4e5a30ed0e?id": "176)\",\"StartTime\":\"19:00:00\",\"Day\":\"Monday\",\"Confirmed\":0,\"Recurring\":1,\"Locations\":{\"Name\":\"Tést\",\"Id\":3},\"Link\":{\"Name\":\"Test\",\"Id\":2},\"Name\":\"Test\",\"Attendance List\":[]}],\"rows\":[{\"ShowTime\":\"18:30:00\",\"Frequency\":\"Weekly\",\"NumOfClasses\":8,\"Instance\":\"Test (Mondays)\",\"Id\":176,\"Registrations\":0,\"AttendanceId\":null,\"CreatedAt\":null,\"TicketExp\":\"2024-02-29\",\"google_group\":\"\",\"EventId\":31002,\"LastModified\":null,\"Capacity\":16,\"ShowDate\":\"2024-02-29\",\"StartDate\":\"2024-01-08\",\"Notes\":\"\",\"EndTime\":\"21:30:00\",\"Skipping\":null,\"EventType\":\"Test\",\"InternalRef\":\"Test (Mondays)\",\"EndDate\":\"2024-02-26\",\"Sync to Site\":\"URI::(https://n8n.***.com/webhook/ae47680c-***-4191-86ec-4a4e5a30ed0e?id=176)\",\"StartTime\":\"19:00:00\",\"Day\":\"Monday\",\"Confirmed\":1,\"Recurring\":1,\"Locations\":{\"Name\":\"Tést\",\"Id\":3},\"Courses\":{\"Name\":\"Test\",\"Id\":2},\"Attendance List\":[],\"Name\":\"Test\"}]}}"
    }
  }
]
```

`"Sync to site":"URI::(https://n8n.***.com/webhook/ae47680c-***-4191-86ec-4a4e5a30ed0e?id:176)"`
The URL in question here is `https://n8n.***.com/webhook/ae47680c-***-4191-86ec-4a4e5a30ed0e?id=176`

Could be related to https://github.com/nocodb/nocodb/issues/6746 but it seemed like there was something else going on here.

### Desired Behavior

An actual JSON object in the webhook payload

### Project Details

Node: **v18.17.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.202.5**

**Comment by snowity** [comment]
The payload sample in test is different from the actrual payload content, but the doc is right. It will disturb the test of webhook

**Comment by mertmit** [comment]
Hi @manwithpowers, thank you for reporting. I was able to reproduce this on my side, this is happening because of Content-Type header. If you pass `Content-Type: application/json` for your webhook it will be resolved.

<img width="781" alt="image" src="https://github.com/nocodb/nocodb/assets/59797957/5d8d52ff-7d4e-4be0-b675-721cd25240e6">

Meanwhile we will discuss this internally to make this as default behavior.

**Comment by manwithpowers** [comment]
Thanks @mertmit, that did it. Appreciate the tip, and I think setting this as default would definitely be helpful.
