### ISSUE TITLE
🐛 Bug: API LINK RECORDS ENDPOINT NOT WORKING.

### ISSUE THREAD

**Issue by yourtrashistrash** [nocodb/nocodb#6823]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

ERROR: The resource you are requesting could not be found
404 - "{\"msg\":\"Column with id '0' not found\"}"

All linked field columns have an id of 0

### Desired Behavior

link record to field

### Project Details

latest version with docker

**Comment by wingkwong** [comment]
Please provide Base Info and also steps to reproduce. A demo video would be better.

**Comment by biancamoldovanm** [comment]
I am also getting the same error when creating a link record via the API `api/v2/tables/{tableId}/links/{linkFieldId}/records/{recordId}`.

To reproduce follow these steps:
1. Create 2 tables via the API (v2)
2. Create a column using LinkToAnotherColumn Request Model on the parent table
3. Link a record from parent table to child table using this API `api/v2/tables/{tableId}/links/{linkFieldId}/records/{recordId}`, where tableId is the parent table id, linkFieldId is the id of the column created in step 2 and the recordId is the Id of the record that needs to be linked. The child record id is then added to the Body of the request: `[{Id: childId}]`.

While the POST request is throwing the error below, the GET request is working.
`row: {
    message: "The column '6400aa89091745001d8be3d5' does not exist.",
    type: 'COLUMN_NOT_EXIST',
    extra: { column: '6400aa89091745001d8be3d5' },
    info: {
        message: 'select "Id", "nc_1qti___nc_m2m_ofc2x447s5"."table1_id" from "Entrepreneur" left join "nc_1qti___nc_m2m_ofc2x447s5" on "nc_1qti___nc_m2m_ofc2x447s5"."table2_id" = "Entrepreneur"."Id" and "nc_1qti___nc_m2m_ofc2x447s5"."table1_id" = "6400aa89091745001d8be3d5" where "Id" in ($1) - column "6400aa89091745001d8be3d5" does not exist',
        code: '42703'
    }
}`

`6400aa89091745001d8be3d5` represents the recordId.

**Comment by dstala** [comment]
@biancamoldovanm can you provide base information? you can copy base info from your base context menu

**Comment by samjaninf** [comment]
Hey @dstala I am getting the same error as @biancamoldovanm. 

Trying to link to records together via the v2 API and it's saying the coloumn (recordID) doesn't exist. Can't get past it.

My Base info is:

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.7**

If there is a fix out already, please let me know. Thanks.

**Comment by pranavxc** [comment]
Can you share the url you are using, fill the values in the api. From the error it looks like `recordId` is getting passed as `linkFieldId` and causing the problem. I will check the v2 api swagger and update if there is something wrong.

**Comment by pranavxc** [comment]
@samjaninf : Thanks for the quick reply. We found a bug when the id value is a string and made a fix as well. Can you try with following PR build to confirm.

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.202.7-pr-7017-20231117-0934
```

**Comment by samjaninf** [comment]
> @samjaninf : Thanks for the quick reply. We found a bug when the id value is a string and made a fix as well, can you try with following PR build to confirm.
> 
> ```
> docker run -d -p 8888:8080 nocodb/nocodb-timely:0.202.7-pr-7017-20231117-1015
> ```

Hey, Thanks for the quick response as well. I just tried this container but I get an error:

`400 - {"msg":"Undefined binding(s) detected for keys [0] when compiling RAW query: ?"}`

This is the URL:
http://<self-hosted>:8080/api/v2/tables/mcyswsxmnbc3gxq/links/cjj9yl5oaep0mb5/records/1

I created a new table and the rowId was 1.

This was the payload:
[{ "Id": 1}]

This is my Base info.

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.7-pr-7017-20231117-1015**

Let me know if there is anything else you need @pranavxc

**Comment by pranavxc** [comment]
> > @samjaninf : Thanks for the quick reply. We found a bug when the id value is a string and made a fix as well, can you try with following PR build to confirm.
> > ```
> > docker run -d -p 8888:8080 nocodb/nocodb-timely:0.202.7-pr-7017-20231117-1015
> > ```
> 
> Hey, Thanks for the quick response as well. I just tried this container but I get an error:
> 
> `400 - {"msg":"Undefined binding(s) detected for keys [0] when compiling RAW query: ?"}`
> 
> This is the URL: http://:8080/api/v2/tables/mcyswsxmnbc3gxq/links/cjj9yl5oaep0mb5/records/1
> 
> I created a new table and the rowId was 1.
> 
> This was the payload: [{ "Id": 1}]
> 
> This is my Base info.
> 
> Node: **v18.17.1** Arch: **x64** Platform: **linux** Docker: **true** RootDB: **pg** PackageVersion: **0.202.7-pr-7017-20231117-1015**
> 
> Let me know if there is anything else you need @pranavxc

Thanks for testing and the response. We found the bug and fixed, you can test it using following pr build.

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.202.7-pr-7017-20231120-0716
```
