### ISSUE TITLE
🐛 Bug: Deployment Failure when migrating from 0.111.1 to 0.202.5 (Railway) - "Migration from 0108002 to 0111002 failed", Relation aready exists

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#6826]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When adapting to upgrade Nocodb on Railway from  0.111.1 to 0.202.5, my deployment crashed.

Here are some error messages I've extracted from the Deployment logs:

![image](https://github.com/nocodb/nocodb/assets/55474996/06cb0abb-391e-4c4f-9f8e-465493157b73)

![image](https://github.com/nocodb/nocodb/assets/55474996/94d131f7-f634-4f79-a35f-79ad9b38a12b)

![image](https://github.com/nocodb/nocodb/assets/55474996/e7a600f8-251b-45d6-9597-a7415c527785)

![image](https://github.com/nocodb/nocodb/assets/55474996/85553030-1078-46a6-aa7a-12c47d6d3f8b)

### Desired Behavior

After redeploying, deployment works as it did before.

### Project Details

Deployment: Railway
Version: 0.202.5
Database: Postgres

**Comment by pranavxc** [comment]
I've few queries which will be helpful to debug more

1. Which version of Postgres are you using?
2. Did you modified database outside Nocodb using CLI or any other tool ?
3. Do you have access to postgres, if yes can you run the following query and the result.

```sql
SELECT
      f.attname AS cn,
      i.relname as key_name,
      ix.indnatts, ix.indkey, f.attnum as seq_in_index,
      pg_catalog.format_type(f.atttypid,f.atttypmod) AS type,
      f.attnotnull as rqd,
      p.contype as cst,
      p.conname as cstn,
      CASE
          WHEN i.oid<>0 THEN true
          ELSE false
      END AS is_index,
      CASE
          WHEN p.contype = 'p' THEN true
          ELSE false
      END AS primarykey,
      CASE
          WHEN p.contype = 'u' THEN 0
      WHEN p.contype = 'p' THEN 0
          ELSE 1
      END AS non_unique_original,
      CASE
          WHEN p.contype = 'p' THEN true
          ELSE false
      END AS primarykey,
      CASE
          WHEN p.contype = 'u' THEN 0
      WHEN p.contype = 'p' THEN 0
          ELSE 1
      END AS non_unique,
      CASE
          WHEN f.atthasdef = 't' THEN pg_get_expr(d.adbin, d.adrelid)
      END AS default  FROM pg_attribute f
      JOIN pg_class c ON c.oid = f.attrelid
      JOIN pg_type t ON t.oid = f.atttypid
      LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = f.attnum
      LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
      LEFT JOIN pg_constraint p ON p.conrelid = c.oid AND f.attnum = ANY (p.conkey)
      LEFT JOIN pg_class AS g ON p.confrelid = g.oid
      LEFT JOIN pg_index AS ix ON f.attnum = ANY(ix.indkey) and c.oid = f.attrelid and c.oid = ix.indrelid
      LEFT JOIN pg_class AS i ON ix.indexrelid = i.oid
      WHERE
        c.relkind = 'r'::char
      AND n.nspname = 'public'
      AND c.relname = 'nc_goya__nc_m2m_rv6ot3ewwh'
      and i.oid<>0
      AND f.attnum > 0
      ORDER BY i.relname, f.attnum;
```

**Comment by candideu** [comment]
Hi @pranavxc !

>  Which version of Postgres are you using?

PostgreSQL 13.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit

> Did you modified database outside Nocodb using CLI or any other tool ?

No

> Do you have access to postgres, if yes can you run the following query and the result.

I ran the query in Railway and it said it was successful. I restarted the database and tried to redeploy the app.

The deployment still crashed though...

**Comment by pranavxc** [comment]
> Hi @pranavxc !
> 
> > Which version of Postgres are you using?
> 
> PostgreSQL 13.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
> 
> > Did you modified database outside Nocodb using CLI or any other tool ?
> 
> No
> 
> > Do you have access to postgres, if yes can you run the following query and the result.
> 
> I ran the query in Railway and it said it was successful. I restarted the database and tried to redeploy the app.
> 
> The deployment still crashed though...
> 
> ![image](https://user-images.githubusercontent.com/55474996/279733933-b2895636-fe1b-4183-a75d-2011a798e147.png)
> 
> ![image](https://user-images.githubusercontent.com/55474996/279733660-0680cdff-af50-4c99-bde1-4079e8c57be2.png)

Can you share the result of the query, which will help us to figure out the cause.

**Comment by candideu** [comment]
@pranavxc There weren't any particular results, it just said "successful". Would the results show up, anywhere in the tables?

**Comment by pranavxc** [comment]
@candideu : We are using that query for getting indexes for a particular table but it seems not returning anything and which causing the issue. One more query, are you using a different schema other than default `public` schema and does the user have all permissions(postgres user) ?

**Comment by candideu** [comment]
Also, I ran the query again in Railway and it said, "No data to display, table is empty." I can try again withthe Postgres desktop app, if you think that would produce different results.

**Comment by candideu** [comment]
> Permission-wise: Let me ask the Railway team.

Based on what I've been told by a Railway community member, the permissions should be the same as what is included in the dockerfile: https://github.com/railwayapp-templates/postgres-ssl/blob/main/Dockerfile.latest

```
FROM postgres:latest

# Install OpenSSL and sudo
RUN apt-get update && apt-get install -y openssl sudo

# Allow the postgres user to execute certain commands as root without a password
RUN echo "postgres ALL=(root) NOPASSWD: /usr/bin/mkdir, /bin/chown" > /etc/sudoers.d/postgres

# Add init scripts
COPY init-ssl.sh /docker-entrypoint-initdb.d/
COPY wrapper.sh /usr/local/bin/wrapper.sh

# Set permissions
RUN chmod +x /docker-entrypoint-initdb.d/init-ssl.sh
RUN chmod +x /usr/local/bin/wrapper.sh

ENTRYPOINT ["wrapper.sh"]
CMD ["postgres", "--port=5432"]
```

**Comment by pranavxc** [comment]
Can you run following query and share the result

```
SELECT
    tablename,
    indexname,
    indexdef
FROM
    pg_indexes
WHERE
    schemaname = 'public'
ORDER BY
    tablename,
    indexname;
```

**Comment by candideu** [comment]
> Can you run following query and share the result

It produced 14 pages of results in Railway

<details>

<summary>Click here to view screenshots</summary>

![image](https://github.com/nocodb/nocodb/assets/55474996/25f20ca1-7097-4877-920e-a22e69bccc80)

![image](https://github.com/nocodb/nocodb/assets/55474996/315d8680-2f52-4a7f-bb25-3a00c6d7499f)

![image](https://github.com/nocodb/nocodb/assets/55474996/d4eca90b-3534-4075-8c6f-392022ec8a8e)

![image](https://github.com/nocodb/nocodb/assets/55474996/a292987b-9e79-44dc-a38a-e19e6584d4a0)

![image](https://github.com/nocodb/nocodb/assets/55474996/422e6ac3-782d-4f8c-b87d-bf2c64c9f623)

![image](https://github.com/nocodb/nocodb/assets/55474996/b253f4f5-fdb5-4dc1-a108-ae95464bdf77)

![image](https://github.com/nocodb/nocodb/assets/55474996/c487b795-eec3-4ce1-ad93-b838aa38ba12)

![image](https://github.com/nocodb/nocodb/assets/55474996/1bb809c9-b1f1-47c0-b992-6f12a6126f03)

![image](https://github.com/nocodb/nocodb/assets/55474996/9d30569c-6993-44fc-a8ea-e58a0f3bdcce)

![image](https://github.com/nocodb/nocodb/assets/55474996/10a7ade6-809a-4c9b-a857-9466ad60d66d)

![image](https://github.com/nocodb/nocodb/assets/55474996/d0088667-8da0-48a5-aa24-34ccc6ecf560)

![image](https://github.com/nocodb/nocodb/assets/55474996/36c54015-b7ab-429f-9b1b-010ccff170e4)

![image](https://github.com/nocodb/nocodb/assets/55474996/a0459a1f-55d4-4e56-a1d6-aeeaf739bce5)

![image](https://github.com/nocodb/nocodb/assets/55474996/cea426dd-e80e-4431-b956-f4bd558c3273)

</details>

**Comment by candideu** [comment]
Unfortunately, I'm still running into issues with this deployment. See: https://github.com/nocodb/nocodb/issues/7242
