### ISSUE TITLE
🔦 Feature:  Manager users

### ISSUE THREAD

**Issue by pixplix-user** [nocodb/nocodb#683]
List all users in a view where i can see where have rol, edit, ban, etc... because actually i only can watch when i'm in a project

**Comment by dstala** [comment]
All users belonging to a base (project) can be managed now using members tab easily
https://docs.nocodb.com/bases/base-collaboration

& in hosted solution, workspace management in similar fashion is also possible
https://docs.nocodb.com/workspaces/workspace-collaboration
