### ISSUE TITLE
🐛 Bug: AUTH TOKEN FOR CLOUD VERSION DOES NOT WORK WITH N8N

### ISSUE THREAD

**Issue by yourtrashistrash** [nocodb/nocodb#6837]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

copy auth token from dash board and try to use with n8n with nocodb.com as host.

### Desired Behavior

successfully retrieve data

### Project Details

nocodb cloud

**Comment by o1lab** [comment]
Try with `workspace_id.nocodb.com` 

The API path can be found under Details > API tab

<img width="1163" alt="image" src="https://github.com/nocodb/nocodb/assets/5435402/76a62d31-81af-448e-a90b-26c9cd859da8">

**Comment by mertmit** [comment]
We have a open PR on n8n repo to support our new release & cloud https://github.com/n8n-io/n8n/pull/7329
