### ISSUE TITLE
🐛 Bug: Cannot change the Account Name

### ISSUE THREAD

**Issue by wachirapohn** [nocodb/nocodb#6841]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Hi,

I've install NocoDB via docker compose
Then, I try to change my account name on NocoDB Self-hosted (Open source) but when I changing my name and refresh on WebUI. Account name will change back to Account Email ID
![Account Name Issue](https://github.com/nocodb/nocodb/assets/145309221/cd3eaac9-750c-48f2-91bc-5c225eed0ffa)

So, I've checked on NocoDB Database and found the account name already changed but on WebUI still show the Account Email ID

Before change account name
<img width="1270" alt="image" src="https://github.com/nocodb/nocodb/assets/145309221/af1aed60-f9e3-45ea-a8f6-5d3086418f42">

After change account name
<img width="1273" alt="image" src="https://github.com/nocodb/nocodb/assets/145309221/3f036e2e-e47e-477e-b967-e4af306f8e7c">

I do something wrong? or missing some config? Kindly advise. Thank you!

### Desired Behavior

NocoDB can change the Account Name

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.5**

**Comment by dstala** [comment]
Fixed. Should work fine after our next bug fix release.
