### ISSUE TITLE
🐛 Bug: Invalid redirection URL

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6843]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Ends up in an infinite loop

REDIRECT_AFTER_SIGNIN

```
views.ts:178 Error: Request failed with status code 400
    at createError (createError.js:16:15)
    at settle (settle.js:17:12)
    at XMLHttpRequest.handleLoad (xhr.js:62:7)
```

### Desired Behavior

No error

### Project Details

v0.202.5

**Comment by sheldon-welinga** [comment]
Hi @dstala, is there a way to reproduce the above issue? Tried to sign in and it works normally on my end

**Comment by dstala** [comment]
@sheldon-welinga This was something related to browser-storage. You can skip this issue;

**Comment by sheldon-welinga** [comment]
> @sheldon-welinga This was something related to browser-storage. You can skip this issue;

Ok, got it. Thanks!
