### ISSUE TITLE
🐛 Bug: display column ID in multi-fields editor

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6850]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Often when working with Link Record APIs, we need column IDs; an easy way to access it is required

### Desired Behavior

Display field ID on multi fields editor. One possible location is - to the right of field name

![Screenshot 2023-10-31 at 9 03 01 PM](https://github.com/nocodb/nocodb/assets/86527202/2361fcc1-8532-4597-83c2-8da9b0b1b062)

### Project Details

v0.202.5

**Comment by o1lab** [comment]
Better to show it next to column name in column list. And confirm we show the original column id from the table and not the view.

**Comment by dstala** [comment]
+ Ensure that it's easy to copy field ID.
