### ISSUE TITLE
🐛 Bug: view context menu to include download CSV & upload CSV options

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6857]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Download CSV, Upload CSV, Locked view are now available as context menu within toolbar. These often, for new users are easy to find. 

### Desired Behavior

Will be good to include these also in view context menu in left sidebar.

### Project Details

v0.202.5

**Comment by WarWolf47** [comment]
https://www.figma.com/file/aoqjDe4lNtFy7xCuNQFYlx/Misc-Design-Fixes?type=design&node-id=43-19623&mode=design&t=vbtOzKAjmYiQGDQI-4

**Comment by frankMagoba** [comment]
Hi @dstala is this issue available to be worked on?

**Comment by dstala** [comment]
@mustafapc19 working on it
