### ISSUE TITLE
🔦 Feature: Do not automatically reveal newly created fields in all of the previously existing views

### ISSUE THREAD

**Issue by MagicDM** [nocodb/nocodb#6858]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

The current behavior is that, when a new field is added to a table, all existing views of that table will, by default, now show/reveal that newly added field.   As views are, very often, intended to be semi-static/fixed entities (in other words, their Field, Sort, Group By, Filter settings are all intended to hold their configuration until changed, this is part of what makes each view unique), it seems strange that a new field created for the table as a whole, should upset the other views revealed Fields setting.   Personally, whenever I create a new field, I do not intend it to be shown in all of my views (in fact, the opposite is usually the case).  As a result, whenever a new field is created for a table , I have to  go through all of my existing views and then hide that new field (so that I can restore the view to its intended configuration).

### Suggested Solution

The request is to either 

A. Change the default behavior (in other words, whenever a field is created for the table, only reveal it in the current view - do not automatically reveal it in all of the other views - this, incidentally, is how Airtable handles the creation of new fields)

or

B. Create a preference/setting somewhere (either in a menu or a config file), that lets you choose/toggle the default behavior for new fields and weather or not they are automatically revealed in all existing views.

### Additional Context

Thanks, in advance, for looking into this.  Let me know if you need clarification of the idea.

**Comment by o1lab** [comment]
This makes sense. We will prioritise this.

**Comment by MagicDM** [comment]
Amazing!  This would be a huge help for my team's workflow and, I hope, generally useful overall.   Appreciate your team taking a look at this : )

**Comment by dstala** [comment]
will be available in next release

**Comment by MagicDM** [comment]
First, thank you so much, again, for implementing this feature!   I just wanted to mention that (as of the release I am using  0.203.2),   when you create a link between tables,  the field for the link on the child table still automatically appears in all of the views of the child table (this appears, from my testing, to only effect link fields -  the creation of any other field type no longer does this).     Thanks, again, everyone!

**Comment by dstala** [comment]
@MagicDM - Thanks for letting us know on Link field behaviour. We had missed on that part when we fixed this.
