### ISSUE TITLE
🐛 Bug: .HEIC files are not supported

### ISSUE THREAD

**Issue by RGNagel** [nocodb/nocodb#6866]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Try to upload a .HEIC file to any table column of type Attachment. The error returned is: `Request failed with status code 413`

### Desired Behavior

The file should be uploaded without errors. According to the documentation (https://docs.nocodb.com/fields/field-types/custom-types/attachment): 

> You can upload any file type

Note: the file is under 5MB in size. 

### Project Details

```
NocoDB used as docker : true
NocoDB version : 0.111.0
Database used in NC_DB_URL : sqlite3
Project was created by clicking : New Project
Database on which spreadsheet is created : pg
OS : Ubuntu 20.04
Node.js version : 18
```

**Comment by frankMagoba** [comment]
Hi @o1lab can I pick this up?

**Comment by dstala** [comment]
@frankMagoba assigned

**Comment by RGNagel** [comment]
Actually it wasn't a problem with .HEIC files, instead, I was receiving the error "413 Request Entity Too Large" because my nginx and NC_REQUEST_BODY_SIZE configuration were not large enough to support the upload of big files.
