### ISSUE TITLE
🔦 Feature: Support details in README

### ISSUE THREAD

**Issue by kprajval** [nocodb/nocodb#6868]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Hi, 
You can add a support system in README.md file so that user can easily contact people who are well grossed with this software

### Suggested Solution

you can use discord channel for this. Like when people have any issue they can post it over there and people working on this can help them out. 

### Additional Context

And I would like to work please assign me this work

**Comment by dstala** [comment]
Details are listed here

![Screenshot 2023-11-03 at 12 03 09 PM](https://github.com/nocodb/nocodb/assets/86527202/dd079765-c745-4155-85b4-094bd220f62f)
