### ISSUE TITLE
🔦 Feature: Still not possible to rollup a formula field

### ISSUE THREAD

**Issue by bitsByB** [nocodb/nocodb#6881]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In one table I have this formula field:
![image](https://github.com/nocodb/nocodb/assets/102392085/fa9f0a20-9500-4616-9045-5ec9927fd866)
But in the my other table that formula field is not proposed in the rollup field:
![image](https://github.com/nocodb/nocodb/assets/102392085/8dae8175-b701-4950-ae23-750684a5891d)

### Suggested Solution

Would be great to have that feature added.

**Comment by dstala** [comment]
Duplicate. To be tracked under [[Feature] Use Formula result in Rollup#3014](https://github.com/nocodb/nocodb/issues/3014)
