### ISSUE TITLE
🔦 Feature: Base Reordering

### ISSUE THREAD

**Issue by MrMK0R** [nocodb/nocodb#6882]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Simple drag and drop reordering of bases. 

### Suggested Solution

Allow for drag and drop reordering of bases, like the table views.

**Comment by dstala** [comment]
Duplicate. To be tracked under [🔦 Feature: Reorder base#1487](https://github.com/nocodb/nocohub/issues/1487)

**Comment by vaz-ar** [comment]
> Duplicate. To be tracked under [🔦 Feature: Reorder base#1487](https://github.com/nocodb/nocohub/issues/1487)

The link does no point to anything, and issue 1487 does not look related, could you update the link to point to the issue tracking this ?

**Comment by asasn** [comment]
Request such functionality.
It's really important.
**Resort row by dragging.**

**Comment by dongphuchaitrieu** [comment]
Yes, please! It made me crazy as I have many Base and can't arrange them at all :(
