### ISSUE TITLE
🐛 Bug: Nest can't resolve dependencies of the EventSubscribersLoader

### ISSUE THREAD

**Issue by memellow85** [nocodb/nocodb#6884]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I update nocodb from 0.111.4 version to 0.202.4, but when I write 'npm start' I have this error:

Nest can't resolve dependencies of the EventSubscribersLoader (DiscoveryService, EventEmitter, EventsMetadataAccessor, MetadataScanner, ?). Please make sure that the argument ModuleRef at index [4] is available in the EventEmitterModule context.

Potential solutions:
- Is EventEmitterModule a valid NestJS module?
- If ModuleRef is a provider, is it part of the current EventEmitterModule?
- If ModuleRef is exported from a separate @Module, is that module imported within EventEmitterModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })

### Desired Behavior

.

### Project Details

nocodb don't started.
I have this version for node v18.12.0 and I have postgres for db

**Comment by dstala** [comment]
@memellow85 since release v0.202.0, we have switched over to PNPM instead of NPM. Please see updated docs support for development environment here https://docs.nocodb.com/engineering/development-setup

Let us know if that solve's.

**Comment by wingkwong** [comment]
Just a reminder. Please remove all the `node_modules` first before running `pnpm bootstrap`.

**Comment by memellow85** [comment]
Thanks for the support!
