### ISSUE TITLE
🔦 Feature: Turn all values in a column into a linked field.

### ISSUE THREAD

**Issue by yourtrashistrash** [nocodb/nocodb#6892]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Converting existing fields to linked records

Is there something like this in Nocodb?

https://support.airtable.com/docs/converting-existing-fields-to-linked-records

I have a list of Airports and corresponding countries in one "Airports" table (well in a CSV).
I'd like to have the airport's country actually be a link to an entry in the "Country" table...

Im also open to using nocodbs api and N8n to achieve this goal if thats possible

### Suggested Solution

Converting existing fields to linked records

Is there something like this in Nocodb?

https://support.airtable.com/docs/converting-existing-fields-to-linked-records

I have a list of Airports and corresponding countries in one "Airports" table (well in a CSV).
I'd like to have the airport's country actually be a link to an entry in the "Country" table...

Im also open to using nocodbs api and N8n to achieve this goal if thats possible

**Comment by dstala** [comment]
To be tracked under [🔦 Feature: Use existing columns between two tables to create a relationship.](https://github.com/nocodb/nocodb/issues/6848)
