### ISSUE TITLE
🔦 Feature: Do have the function of printing design？

### ISSUE THREAD

**Issue by mrchenxxx** [nocodb/nocodb#6906]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Can achieve online printing

### Suggested Solution

Can achieve online printing

**Comment by dstala** [comment]
@mrchenxxx can you help us understand more about your requirement? may be a closer solution that you would have used or seen in other applications for reference.

**Comment by mrchenxxx** [comment]
> @mrchenxxx can you help us understand more about your requirement? may be a closer solution that you would have used or seen in other applications for reference.您能帮助我们更多地了解您的要求吗？可能是您在其他应用程序中使用或看到的更接近的解决方案，以供参考。

Like Excel , it can print online and set headers and footers

**Comment by mrchenxxx** [comment]
> @mrchenxxx can you help us understand more about your requirement? may be a closer solution that you would have used or seen in other applications for reference.您能帮助我们更多地了解您的要求吗？可能是您在其他应用程序中使用或看到的更接近的解决方案，以供参考。

Like Excel , it can print online and set headers and footers

**Comment by githubmyname** [comment]
@mrchenxxx  Is that what you need? 
 https://github.com/nocodb/nocodb/issues/580#issuecomment-1798182799

**Comment by mrchenxxx** [comment]
> @mrchenxxx Is that what you need?这是你需要的吗？ [#580 (comment) #580 （评论）](https://github.com/nocodb/nocodb/issues/580#issuecomment-1798182799)

Yes. When will this feature be available?

**Comment by githubmyname** [comment]
> > @mrchenxxx Is that what you need?这是你需要的吗？ [#580 (comment) #580 （评论）](https://github.com/nocodb/nocodb/issues/580#issuecomment-1798182799)
> 
> Yes. When will this feature be available?

As you can see here, it is still "Features" and is not yet in progress.
https://github.com/nocodb/nocodb/projects/1#card-72630528

**Comment by githubmyname** [comment]
> > @mrchenxxx Is that what you need?这是你需要的吗？ [#580 (comment) #580 （评论）](https://github.com/nocodb/nocodb/issues/580#issuecomment-1798182799)
> 
> Yes. When will this feature be available?

As you can see here, it is still "Features" and is not yet in progress.
https://github.com/nocodb/nocodb/projects/1#card-72630528

**Comment by mrchenxxx** [comment]
Can you customize the print template for MySQL versions, such as setting headers, footers, and so on?
