### ISSUE TITLE
Connect New Data Source

### ISSUE THREAD

**Issue by c2006878** [nocodb/nocodb#6913]
I have created a new base and I want to connect to a local data source. Why hasn't I been able to connect?
![image](https://github.com/nocodb/nocodb/assets/58558960/0b87638c-d0ca-453a-a39d-50ddb3a3367e)

**Comment by wingkwong** [comment]
If you are using docker, then use `host.docker.internal` instead of `localhost`

**Comment by c2006878** [comment]
I haven't deployed to Docker yet, and I want to try connecting locally. Why is it that localhost doesn't work?

> If you are using docker, then use `host.docker.internal` instead of `localhost`

**Comment by dstala** [comment]
@c2006878 can you confirm if you are able to connect to database using same credentials on say TablePlus?

**Comment by c2006878** [comment]
> @c2006878 can you confirm if you are able to connect to database using same credentials on say TablePlus?

How to do this? How are credentials configured?

**Comment by c2006878** [comment]
> @c2006878 my question was- are you able to connect to mysql `d1` database on port 3306 using root/123456 as username and password from outside nocodb from your local system? using any other tools like TablePlus or Dbeaver?

Sure.

**Comment by c2006878** [comment]
> @c2006878 my question was- are you able to connect to mysql `d1` database on port 3306 using root/123456 as username and password from outside nocodb from your local system? using any other tools like TablePlus or Dbeaver?

![1699925004756](https://github.com/nocodb/nocodb/assets/58558960/6e380432-bebb-4812-895f-c7ea5e88404f)
I would like to know where the default connected database is located. If I upload a document, where should I go to find this document?

**Comment by c2006878** [comment]
> @c2006878 my question was- are you able to connect to mysql `d1` database on port 3306 using root/123456 as username and password from outside nocodb from your local system? using any other tools like TablePlus or Dbeaver?

Additionally, I have connected to an external database and found the relevant path information **【'1', '111', '2023-11-03 15:00:12', '2023-11-03 15:00:15', '[{\"title\":\"《C++程序设计》期末考试及答案.doc\",\"mimetype\":\"application/msword\",\"size\":66088,\"path\":\"download/noco/pc86i3cahrx9l3c/mtens4mpn1ohqu3/csol8s27xrcefpf/8k1-nu5GNkgFd4pp4m.doc\",\"signedPath\":\"dltemp/9xfLfkPur0JHmr1u/1699002600000/noco/pc86i3cahrx9l3c/mtens4mpn1ohqu3/csol8s27xrcefpf/8k1-nu5GNkgFd4pp4m.doc\"}]'
】**about the document in the database tool after uploading the document. Where should I look for it now? I am currently conducting code tests locally.

**Comment by dstala** [comment]
@c2006878 please reopen this thread or ping us on discord if issue still persists. 
https://discord.gg/5RgZmkW
