### ISSUE TITLE
🐛 Bug: Google auth token parse failure

### ISSUE THREAD

**Issue by rjhawar** [nocodb/nocodb#6915]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Setup Nocodb so it allows for single sign on with Google

1. Create an OAuth client id in GCP 
2. Setup Nocodb with the following environment variables and values taken from step 1
NC_GOOGLE_CLIENT_ID and NC_GOOGLE_CLIENT_SECRET
3. Navigate to the nocodb sign-in page and select "sign in using Google"
4. After successfully authorizing with Google verify the following error message appears:
```Cannot read properties of undefined (reading 'continueAfterSignIn')```
Note: If above issue does not occur try logging out and then signing in again

```
From the dev console here is the error:
[nocodb] [Nest] 11  - 11/08/2023, 4:53:03 AM   ERROR [GlobalExceptionFilter] Bad Request
[nocodb] TokenError: Bad Request
[nocodb]     at OAuth2Strategy.parseErrorResponse (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:373:12)
[nocodb]     at OAuth2Strategy._createOAuthError (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:420:16)
[nocodb]     at /usr/src/app/node_modules/passport-oauth2/lib/strategy.js:177:45
[nocodb]     at /usr/src/app/node_modules/oauth/lib/oauth2.js:191:18
[nocodb]     at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth2.js:132:9)
[nocodb]     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:157:7)
[nocodb]     at IncomingMessage.emit (node:events:526:35)
[nocodb]     at IncomingMessage.emit (node:domain:489:12)
[nocodb]     at endReadableNT (node:internal/streams/readable:1359:12)
[nocodb]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
Strangely if you reload the page Nocodb will authorize you as that user instead of taking you back to the sign-in page

### Desired Behavior

You should be able to login successfully after the redirect. 

### Project Details

Node: **v18.17.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.5**

**Comment by pranavxc** [comment]
Hi @rjhawar, thanks for reporting the bug. We had fixed the issue in following pr #6940 and we made a custom image for that PR, can you try it and confirm.

```
nocodb/nocodb-timely:0.202.5-pr-6940-20231110-0616
```

**Comment by rjhawar** [comment]
@pranavxc the fix worked for me I can now login without any issues, thanks for the quick turnaround!

**Comment by pranavxc** [comment]
Thanks for confirming, We will rollout the change in next release. Till that you can use the pr build .
