### ISSUE TITLE
Easy to overwrite existing values in a database 

### ISSUE THREAD

**Issue by hreinn** [nocodb/nocodb#692]
I just recently stumbled upon this project - it's great - to say the least.

I just want to flag an issue with the dangers of people connecting this with production databases - and ease of which it automatically saves blanks over existing values in the user interface.

Clicking in a column - and pressing CTRL-A (Select all) which would usually mean "select all text in the column" deletes the existing contents and there is no undo.  If you exit the column the database gets updated with a blank value.

![image](https://user-images.githubusercontent.com/1555736/138466057-ed269471-3c79-4615-882b-34f3d340238a.png)

After pressing CTRL-A

![image](https://user-images.githubusercontent.com/1555736/138466593-7ab581ea-ea35-4eff-ba10-b4cba3587a24.png)

This could cause people massive problems.  I was on a test db, but was tempted to connect to the production after previously testing it out on a sample db - but had not seen this as an issue before.

**Comment by pranavxc** [comment]
Fixed in `0.81.0`
