### ISSUE TITLE
🐛 Bug: No EOF in long text and impossible to see in a lookup

### ISSUE THREAD

**Issue by HenriChanzy** [nocodb/nocodb#6929]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a long text and write it with some end of line (in my case, shift+enter). 
When you click on the expand button, you can see the end of line, but they are removed in the normal view.
When you create a lookup to this text, it is written on only one line, and cannot be read because of the length of the text.

### Desired Behavior

Change the view to add the end of line on the normal view and export the expand view and this view to lookup

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.5**

### Attachments

![image](https://github.com/nocodb/nocodb/assets/114398515/97e20a3f-e3e6-4efe-82de-cae9cfa1201d)
![image](https://github.com/nocodb/nocodb/assets/114398515/fea07d50-d40e-4f5c-b77a-9cfb44a242f0)
![image](https://github.com/nocodb/nocodb/assets/114398515/0be1b8be-ca3a-4a52-8b3c-d94101df7b48)

**Comment by dstala** [comment]
Click on lookup tile now opens expanded view for longText field

https://github.com/nocodb/nocodb/commit/d78e019b3f6e6f70296a4c43287be47e9acadeaf
