### ISSUE TITLE
🐛 Bug: Locked view

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6934]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

# General
- [ ] Locked view
  - mode change to/from locked view possible by only creator / owner 
  - locked view will restrict any collaborators to change any view configurations like enable/disable fields, sort, filter, group by, row height & such; but working with records should be allowed based on user's role. = editor will still be able to add / edit records, commenter comment on records
- [ ] display lock icon next to locked view

# Grid
- [ ] double click on column edit to open add-edit column modal --- should be disabled
- [ ] multi fields editor should be disabled when in locked view
- [ ] create new grid view; change view mode to locked; click on details tab
- [ ] record context menu should be accessible based on role
```
Uncaught (in promise) TypeError: Cannot set properties of null (setting 'Sortable1699545635884')
    at Sortable.destroy (sortable.esm.js:2458:15)
    at sort.ts:55:42
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:32)
    at effect2.onStop (runtime-core.esm-bundler.js:1783:7)
    at ReactiveEffect.stop (reactivity.esm-bundler.js:198:14)
    at EffectScope.stop (reactivity.esm-bundler.js:64:25)
    at unmountComponent (runtime-core.esm-bundler.js:6338:11)
    at unmount (runtime-core.esm-bundler.js:6242:7)
    at unmountComponent (runtime-core.esm-bundler.js:6341:7)
    at unmount (runtime-core.esm-bundler.js:6242:7)
```
- [ ] duplicate locked grid view
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')
    at unmountComponent (runtime-core.esm-bundler.js:6331:63)
    at unmount (runtime-core.esm-bundler.js:6242:7)
    at unmountChildren (runtime-core.esm-bundler.js:6361:7)
    at unmount (runtime-core.esm-bundler.js:6262:9)
    at unmountComponent (runtime-core.esm-bundler.js:6341:7)
    at unmount (runtime-core.esm-bundler.js:6242:7)
    at unmountComponent (runtime-core.esm-bundler.js:6341:7)
    at unmount (runtime-core.esm-bundler.js:6242:7)
    at unmountChildren (runtime-core.esm-bundler.js:6361:7)
    at unmount (runtime-core.esm-bundler.js:6262:9)
```

# Form view
- [ ] view settings should be disabled; no changes to view configurations (like reorder, add/remove field, change label/help text, submit options, etc). but based on role, collaborator can use form to submit data.

# Kanban & Gallery
- [ ] Tool bar icon, some are partially greyed out. Make it consistent. 

### Desired Behavior

Locked view should only restrict changes to view configurations.

### Project Details

0.202.5

**Comment by emre1e** [comment]
@dstala Is there any chance to have 2 different function in this Topic:

Collaborative: Like now. Able to edit everything

Locked: locked view will restrict any collaborators to change any view configurations like enable/disable fields, sort, filter, group by, row height & such and no editing on records

Then in a new Window there is multi choice:

Filters: locked view will restrict any collaborators to change any view configurations like enable/disable fields, sort, filter, group by, row height & such; but working with records should be allowed based on user's role. = editor will still be able to add / edit records, commenter comment on records

No Delete: editor will still be able to add / edit records, commenter comment on records, but cant delete any records

No Insert: Editing is enabled but can insert new Lines

Something like this:

![image](https://github.com/nocodb/nocodb/assets/117290601/9d23dfe3-a86d-46e1-8c0e-9368fa061868)

**Comment by dstala** [comment]
@emre1e that's an interesting take; we have plans for more granular access control but as Enterprise feature. For current phase, we would go with planned version of Locked view limiting view configuration abilities.

**Comment by emre1e** [comment]
@dstala do you have a beta docker image for this? Would like to test it.

Thank you.

**Comment by dstala** [comment]
@emre1e ongoing here https://github.com/nocodb/nocodb/actions/runs/6966577515
will share once its ready

**Comment by dstala** [comment]
@emre1e you can check this 
DOCKER BUILD nocodb/nocodb-timely:0.202.8-20231123-1023

**Comment by emre1e** [comment]
@dstala thanks i like it but the complete lock function is missing now. Can we have both please? 

Locked Mode and Full Locked Mode

**Comment by dstala** [comment]
@emre1e complete locked mode like no one will be able to edit records? Can we not assign role?
