### ISSUE TITLE
🐛 Bug: Migration directory is corrupt

### ISSUE THREAD

**Issue by Teslamancer** [nocodb/nocodb#6936]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

using external mysql db
docker-compose down
upgrade version from 0.111.1 -> latest
docker-compose up

### Desired Behavior

should run migrations to use existing DB

### Project Details

NocoDB used as docker: true
NocoDB version: latest
Database used in NC_DB URL: mysql

**Comment by Teslamancer** [comment]
Here's the error:
ERROR [ExceptionHandler] The migration directory is corrupt, the following files are missing: nc_035_add_username_to_users, nc_036_base_deleted, nc_037_rename_project_and_base
[docker-compose redacted.txt](https://github.com/nocodb/nocodb/files/13313194/docker-compose.redacted.txt)

docker-compose is attached

**Comment by pranavxc** [comment]
Looks like you had upgraded to latest version and then downgraded to the older version. Please confirm the version and instead of using `latest` use exact version value.

```
nocodb/nocodb:0.202.5
```

**Comment by dstala** [comment]
@Teslamancer let us know if that solves issue that you were facing

**Comment by dstala** [comment]
@Teslamancer Please reopen this thread if issue still persists.
