### ISSUE TITLE
🐛 Bug: Invalid filter in list API

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6943]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Invalid filters in existing list APIs are being ignored. & API returns results as if the filter wasn't applied; 
apply changes for both v1 and v2

### Desired Behavior

we should return error instead. 

### Project Details

0.202.5

**Comment by christiankriedemann** [comment]
I hope this isn't the wrong place. But I think there might be a connection.

Through the API (v1 & v2), only data that is visible in the frontend can be retrieved and modified. This means that if fields are hidden or records are filtered out in the frontend (in the browser), then the API cannot read or modify the data.

As a workaround, I have set up a locked view that displays all records and all fields. Only through this can the API currently work reliably.

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.5**

**Comment by dstala** [comment]
@christiankriedemann is a bug that we noticed too. we are working on a fix and should be available in our next release expected on 16th of this month
