### ISSUE TITLE
🐛 Bug: import file content title not support unicode eg.(emoji🔥, Chinese)

### ISSUE THREAD

**Issue by boomxy** [nocodb/nocodb#6959]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. excel/csv file,  [attchement-right.xlsx](https://github.com/nocodb/nocodb/files/13332868/attchement-right.xlsx)
[attchement-error-field.xlsx](https://github.com/nocodb/nocodb/files/13332869/attchement-error-field.xlsx)
[attchement-error.xlsx](https://github.com/nocodb/nocodb/files/13332870/attchement-error.xlsx)
2. from base **import data** 
3. got error. "The column 'field' already exists."
4. The reason : File content title not support unicode eg.(emoji🔥, Chinese)

### Desired Behavior

File content title can support unicode eg.(emoji🔥, Chinese)when import excel/csv file

### Project Details

```
NocoDB used as docker :  false 
NocoDB version : 0.202.5
Database used in NC_DB URL  : SQLite
Project was created  by clicking : true
```

### Attachments

[attchement-right.xlsx](https://github.com/nocodb/nocodb/files/13332868/attchement-right.xlsx)
[attchement-error-field.xlsx](https://github.com/nocodb/nocodb/files/13332869/attchement-error-field.xlsx)
[attchement-error.xlsx](https://github.com/nocodb/nocodb/files/13332870/attchement-error.xlsx)

**Comment by wingkwong** [comment]
@boomxy in the next release, you can set `NC_SANITIZE_COLUMN_NAME=false` to support unicode.
