### ISSUE TITLE
🐛 Bug: Regression on json column type, cannot use json array, invalid input syntax

### ISSUE THREAD

**Issue by Sov3rain** [nocodb/nocodb#6963]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Add a JSON column type.
2. Try to add a json array : 
```json
[ "one", "two", "three" ]
```
3. Console throws the error : 
```
SyntaxError Expected property name or "}" in JSON at position 1 (line 1 column 2)
```
4. UI throws the error : 
```
Record update failed update "" set "" = '{["30df306a-jfhf-7949-hgjgh-c37856e2a3e9","19223cef-26f7-4eb0-9ea1-e1dde3a91e2e"]}' where "id" = '7' - invalid input syntax for type json
```
5. The cell will be populated with a invalid json object automaticaly:
```json
{[ "one", "two", "three" ]}
```
6. Trying to further modify the cell will endup with the same error and the generation of the same invalid json object.

### Desired Behavior

On previous version `0.107.5` we were able to add json arrays, not just json objects.
We would like that behaviour back. Adding a root object with an array in it is not acceptable for backwards compatibility.

One weird thing: copying the content of the cell (without opening the full cell edition mode), modifying the content elsewhere (in a text editor) and pasting the new value back in the cell (still without using the full cell edition mode) will do the trick. Maybe it bypasses the (falsy) validation? 

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.5**

### Attachments

![chrome_8BByOFYLTX](https://github.com/nocodb/nocodb/assets/10755450/ed8be9c9-75c2-4dcd-9805-40cafda0e44a)

**Comment by mpearce-bain** [comment]
Confirming I've observed the described behaviour as well
