### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by c2006878** [nocodb/nocodb#6968]
Currently, I can only see some imported tables in the project's relationship diagram, but I am unable to see the relationships between these tables, something like what's shown below. What should I do?
![image](https://github.com/nocodb/nocodb/assets/58558960/2946571b-a713-4eb0-ba70-c6634d1966bd)

**Comment by dstala** [comment]
@c2006878 
- help us with your base info? open base context menu (`...`) in left side bar & copy base info
- does your base title or fields contain any non-english characters? 
- what kind of links have you created between tables?
- does this happen even after you sign out & sign back in?
