### ISSUE TITLE
🐛 Bug: Api linked fields duplicated

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#7020]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

excecute the get api in Version 2 or version 1

Results in linked tables are duplicated, even only 1 link is selected

New in 202.7

![image](https://github.com/nocodb/nocodb/assets/117290601/9f9bb55f-1c3f-475e-9791-0329e934054e)

### Desired Behavior

should only show once like before the update

![image](https://github.com/nocodb/nocodb/assets/117290601/891ac89e-b11c-43e0-a79b-c3441cd3f393)

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.7**

**Comment by dstala** [comment]
- Is this problem noticed after migration?
- Which data type are you using to create relations -  "Links" or "LinkToAnotherRecord"?
- What's your relation type : has-many or many-many?
- Does this issue happen even for a newly created table?

We tried under same environment as your's Docker + PG, but we were unable to reproduce it yet.

**Comment by emre1e** [comment]
im just excecuting the get api. All linked fields are duplicated. Example:

![image](https://github.com/nocodb/nocodb/assets/117290601/27cf5bf4-aade-4148-9b59-258a4c94d6fb)

**Comment by emre1e** [comment]
Forgot what i said...

after the migration somehow all linked entries are duplicated.

Did you had a script to migrate linktoanotherrecord fields to links fields?

**Comment by dstala** [comment]
> Did you had a script to migrate linktoanotherrecord fields to links fields?

No. Migrations were not enforced. We had left `LTAR` fields as is. `Links` type was introduced additionally.

**Comment by emre1e** [comment]
ok then something is really wrong in the api. 

Linktoanother records are duplicated. 

links are fine.

In the database its correct for both.

![image](https://github.com/nocodb/nocodb/assets/117290601/e665d661-d6c9-4ec6-b5c6-4930979feda3)

**Comment by pranavxc** [comment]
Hi I've few queries which may help us to debug.

-  From which version did you migrated to the latest ?
- Is there multiple entry in the actual db ?
- Which relation type are you using (has many / many to many) ?
- Are you using Redis for caching ?
- If you add new row to the existing link column does it getting duplicated ?

**Comment by dstala** [comment]
@emre1e if you are available, you can DM @pranavxc on discord for quick sync. 
Discord ID : pranavxc#7398
Discord : https://discord.gg/5RgZmkW

**Comment by emre1e** [comment]
From which version did you migrated to the latest ? --> 202.5
Is there multiple entry in the actual db ?  --> no
Which relation type are you using (has many / many to many) ? --> many to many
Are you using Redis for caching ? --> yes
If you add new row to the existing link column does it getting duplicated ? --> no because with the new relation links its working
