### ISSUE TITLE
🐛 Bug: API V2 Update API /rowid is missing

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#7021]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Update to 202.7

Update API doesnt work, because its not accepting the row id.

![image](https://github.com/nocodb/nocodb/assets/117290601/b37f332a-773c-4a5a-b868-de93d5a41275)

### Desired Behavior

It should accept it.

![image](https://github.com/nocodb/nocodb/assets/117290601/fc14366c-7cbf-4a1f-8b94-d736fcb0374c)

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.7**

**Comment by dstala** [comment]
@emre1e in v2, we have unified single & bulk API. Record ID hence should be part of body of the message.
Details here. https://data-apis-v2.nocodb.com/#tag/Table-Records/operation/db-data-table-row-update

**Comment by emre1e** [comment]
Somehow its still not working:

{
    "Id": 2821,
    "Aktenzeichen_eagle": "GAM2399999",
    "Verfahrensstatus": "Vergleich"
}

Return:

{
    "msg": "Record with pk undefined not found"
}

**Comment by pranavxc** [comment]
@emre1e Can you try the following image

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.202.7-pr-7017-20231117-1015
```

**Comment by emre1e** [comment]
its still the same

![image](https://github.com/nocodb/nocodb/assets/117290601/ccfc6540-532a-4e69-850d-2ebfc9ec7989)

**Comment by pranavxc** [comment]
> its still the same
> 
> ![image](https://user-images.githubusercontent.com/117290601/283797129-ccfc6540-532a-4e69-850d-2ebfc9ec7989.png)


Thanks for the quick reply and I've few queries which will help us to debug.

1. Are you using composite primary key ?
2. Is it external database ?
3. Can you try passing `"id"`(which is the actual column name) and test once.

**Comment by emre1e** [comment]
no only id is primary key
no docker internal postgres
tried id but same
