### ISSUE TITLE
🐛 Bug: page reloads without any reason sometimes

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7033]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- often seen with development setup
- one possible scenario as seen in latest release
  - start development setup
  - import csv / xlsx

page reloads during import as if we pressed refresh button. not observed in staging / EE 

### Desired Behavior

x

### Project Details

0.202.6

**Comment by wingkwong** [comment]
in frontend console, did you see `optimized dependencies changed. reloading`?

**Comment by dstala** [comment]
✔ Nitro built in 2074 ms                                                                                            nitro 7:56:17 PM
ℹ Vite client warmed up in 10235ms                                                                                        ✨ new dependencies optimized: rfdc, @vue/runtime-core, @ant-design/icons-vue, @vue/runtime-dom, @vue/reactivity, sortablejs, @vue-flow/additional-components, @iconify/vue
ℹ ✨ optimized dependencies changed. reloading                                                                            
ℹ ✨ new dependencies optimized: splitpanes                                                                               
ℹ ✨ optimized dependencies changed. reloading                                                                            
ℹ ✨ new dependencies optimized: emoji-mart-vue-fast/src, v3-infinite-loading, vuedraggable                               
ℹ ✨ optimized dependencies changed. reloading                                                                            
ℹ ✨ new dependencies optimized: monaco-editor                                                                            
ℹ ✨ optimized dependencies changed. reloading                                                                            
ℹ ✨ new dependencies optimized: deep-object-diff, httpsnippet                                                            
ℹ ✨ optimized dependencies changed. reloading

**Comment by dstala** [comment]
in development environment only due to Vite; not in prod environment
