### ISSUE TITLE
🐛 Bug: Cannot read properties of undefined (reading 'table_name')

### ISSUE THREAD

**Issue by mdebic** [nocodb/nocodb#7039]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I click on my table in the UI to view my data. No data is shown, just an error, "Error loading data". This happen with three of my tables, did not add or delete anything to the tables, just happend out of nowhere.

The database logs do not show anything. The nocodb logs show the following:

```
nocodb       | [Nest] 11  - 11/20/2023, 5:20:02 PM   ERROR [i] Please check server log for more details
nocodb       | Error: Please check server log for more details
nocodb       |     at Function.internalServerError (/usr/src/app/docker/main.js:1:681593)
nocodb       |     at w.getDataList (/usr/src/app/docker/main.js:1:1228972)
nocodb       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocodb       |     at async w.dataList (/usr/src/app/docker/main.js:1:1226894)
nocodb       |     at async p.dataList (/usr/src/app/docker/main.js:1:53356)
nocodb       | TypeError: Cannot read properties of undefined (reading 'table_name')
nocodb       |     at N.getTnPath (/usr/src/app/docker/main.js:1:233727)
nocodb       |     at t.default (/usr/src/app/docker/main.js:1:325085)
nocodb       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocodb       |     at async N.selectObject (/usr/src/app/docker/main.js:1:229213)
nocodb       |     at async N.list (/usr/src/app/docker/main.js:1:205870)
nocodb       |     at async w.getDataList (/usr/src/app/docker/main.js:1:1228897)
nocodb       |     at async w.dataList (/usr/src/app/docker/main.js:1:1226894)
nocodb       |     at async p.dataList (/usr/src/app/docker/main.js:1:53356)

```

What server logs? 

### Desired Behavior

To see my data.

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.4**

**Comment by mdebic** [comment]
Okay I managed to find the root cause somewhere in one table, table A, which is the only one now not loading anymore. Table A still has a column as link to another table, table B, altough I deleted table B. I guess table B is the table which cannot by found anymore when I want to retreive my data from table A? I cannot delete that column in table A, it throws the folling error:

```
[Nest] 11  - 11/20/2023, 6:35:55 PM   ERROR [i] Cannot read properties of null (reading 'getModel')
TypeError: Cannot read properties of null (reading 'getModel')
    at C.columnDelete (/usr/src/app/docker/main.js:1:1204616)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async f.columnDelete (/usr/src/app/docker/main.js:1:41545)
```

How can I fix this, without losing my data?

**Comment by dstala** [comment]
you are currently on older release (0.111.4). can you let us know if issue still persists when you migrate to v0.202.7?

**Comment by mdebic** [comment]
Right, thats on me, always forget pulling the newest image. Ok now im running on:
```
Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.8**
```
The problem still persists, exactly the same. I guess I just need to find a way to delete that broken link to the unexisting table. Probably I would not have that problem if I was running on newer version. But still, is there a way to delete it, maybe altering the db directly?

**Comment by mdebic** [comment]
Hi, I managed to fix it, so I can least work with the tables again. Copying the table with the broken column worked. Everything was copied, except the non-existing link to another database. The only problem now is, I cannot delete the old table, I am still geting the error:
```
[Nest] 11  - 11/20/2023, 6:35:55 PM   ERROR [i] Cannot read properties of null (reading 'getModel')
TypeError: Cannot read properties of null (reading 'getModel')
    at C.columnDelete (/usr/src/app/docker/main.js:1:1204616)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async f.columnDelete (/usr/src/app/docker/main.js:1:41545)
```
Anyone know a way to delete that table?

**Comment by dstala** [comment]
@mdebic the table will have to be removed removed from the backend directly - assuming this to be an unexpected error. if you still face issue, connect with me on discord (dstala)
