### ISSUE TITLE
🔦 Feature: Support Pasting Images for File Type Tables

### ISSUE THREAD

**Issue by AlienHub** [nocodb/nocodb#7045]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In the current version, when the table type is set to "File," only image file uploads are supported, and pasting images directly into the table is not possible. I believe allowing users to paste images directly would enhance user experience by reducing unnecessary steps.

### Suggested Solution

I would like NocoDB to support pasting images directly into tables when the table type is set to "File," eliminating the need to save images as files before uploading. This would make it more convenient for users to add images to tables and reduce operational complexity.

**Comment by dstala** [comment]
related 
[🔦 Feature: File / photo : upload via URL](https://github.com/nocodb/nocodb/issues/4347)
[[Feature] More options for uploading attachment files, referencing external URLs as attachments](https://github.com/nocodb/nocodb/issues/842)

**Comment by dstala** [comment]
Pasting images directly into attachment type field from the clipboard is now supported.
