### ISSUE TITLE
🐛 Bug: Hit delete key on formula focused textfield will remove the whole new field

### ISSUE THREAD

**Issue by xJkit** [nocodb/nocodb#7050]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Go to the **Details** tab
2. Click `New Field`
3. Select `formula`for the data type.
4. Click the textfield below(make it focused).
5. If you have a typo and want to delete a single character, hit the "Delete" button on your keyboard (or backspace) will remove the new field. 

### Desired Behavior

Hit the "Delete" button will just remove a single character inside the textfield instead of the whole field.

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.8**

### Attachments

![CleanShot 2023-11-21 at 23 30 29](https://github.com/nocodb/nocodb/assets/18704345/28d02b97-9734-49bd-9f8d-6a4def156a21)

![CleanShot 2023-11-21 at 23 34 02](https://github.com/nocodb/nocodb/assets/18704345/fc3f1cfd-f222-4e4c-9494-03aaae5998af)

**Comment by dstala** [comment]
issue noticed for formula field & checkbox field (click delete after clicking on default options)
