### ISSUE TITLE
🐛 Bug: Upgrading from 0.105.1 to latest fails

### ISSUE THREAD

**Issue by nicolabisio** [nocodb/nocodb#7075]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Change in docker compose the tag from 0.105.1 to latest

### Desired Behavior

Simply that the machine continue to working

### Project Details

```
NocoDB used as docker : true 
NocoDB version : 0.105.1
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project by connecting to external database
OS on which NocoDB is running : ubuntu
Database version : MariaDB 10.11
```

### Attachments

![Schermata del 2023-11-23 18-37-30](https://github.com/nocodb/nocodb/assets/2479973/a8e9e1df-e9fe-423b-9197-e4cfbb19cb48)

**Comment by nicolabisio** [comment]
I've also followed these steps [these steps](https://github.com/nocodb/nocodb/issues/6233)

**Comment by pranavxc** [comment]
Both table may have different collation and which causing the foreign key creation error.

Refer : https://stackoverflow.com/a/4398866

**Comment by dstala** [comment]
@nicolabisio if the issue still persists, please re-open this ticket
