### ISSUE TITLE
🐛 Bug: Use ncRecordId with API

### ISSUE THREAD

**Issue by pedralmeida22** [nocodb/nocodb#7086]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

As specified in the [documentation](https://docs.nocodb.com/0.109.7/setup-and-usages/primary-key/), the primary key of the tables imported from Airtable  is mapped to `ncRecordId`. Therefore, there is no `Id` field in this tables.

Take the following request as an example:
`http://localhost:8080/api/v1/db/data/{orgs}/{baseName}/{tableName}/{rowId}`

If `rowId` is an `ncRecordId` value the reply is:
```
{
    "msg": "Undefined binding(s) detected when compiling SELECT. Undefined column(s): [ncRecordId]
    ...
}
```

This means the API knows that it needs to search the column `ncRecordId` but is not able to find it.
However, if listing all table rows of imported table the column `ncRecordId` is present.

Alternatively, the [find-one](https://apis.nocodb.com/#tag/DB-Table-Row/operation/db-table-row-create) method combined with conditions can be used to retrieve the desired `ncRecordId`. However, other methods which use the `ncRecordId` will fail.

### Desired Behavior

We should be able to use the API with the `ncRecordId`. 

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.8**

**Comment by dstala** [comment]
tried using swagger. worked fine for both v1 & v2


![Screenshot 2023-11-25 at 9 23 17 AM](https://github.com/nocodb/nocodb/assets/86527202/f4137f2b-9bb7-4489-b40d-6188ddc01c72)
![Screenshot 2023-11-25 at 9 21 52 AM](https://github.com/nocodb/nocodb/assets/86527202/5c2b37a5-766c-4339-a60e-7247a6d4f39c)


 

```
Node: **v18.17.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.8**



```

**Comment by pedralmeida22** [comment]
![nocodb-print](https://github.com/nocodb/nocodb/assets/40249872/9881e6ed-640b-4ab9-a3bb-eee0b13b8cb1)

**Comment by pedralmeida22** [comment]
This issue only to happens in this specific table. Therefore, the problem seems to not be related with the API. The issue can be closed.
