### ISSUE TITLE
🔦 Feature: linked records - click opens linked record not removes it

### ISSUE THREAD

**Issue by HelloGithubUniverse** [nocodb/nocodb#7099]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When you Open a linked record a click on the linked item removes the link. This can cause an unintended remove of an item as the User might expect that a click on an item opens it.

### Suggested Solution

- When User is removing an item, show a „are you sure you want to remove…“ modal before.
- Click event on item: Opens the linked record
- Add an extra Symbol (e.g. Trash) to remove an item

**Comment by erobertsme** [comment]
This happens very frequently, even when the user is aware of this.

**Comment by erobertsme** [comment]
This issue can be closed now. Unlinking and Linking now requires intentionally clicking the square to the right side.

<img width="144" alt="image" src="https://github.com/nocodb/nocodb/assets/9193319/99aff3b6-ea58-4d5a-a5b4-1f5de5a7e3f4">
