### ISSUE TITLE
🔦 Feature: Column data aggregation

### ISSUE THREAD

**Issue by travisgu** [nocodb/nocodb#7100]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In Excel spreadsheet, it is widely used to put a sum or avg cell below the last row of the records. It can be simply achieved by add a formula to that cell.  I searched the document site and didn't find how to do that. This is really helpful for using NocoDB to replace Excel.

### Suggested Solution

If this feature is already supported, please kindly help to point out how to do this. If not, please consider this as a new feature into future releases. Thanks.

**Comment by dstala** [comment]
@travisgu field aggregation- feature in our roadmap, but is not supported.

**Comment by travisgu** [comment]
> @travisgu field aggregation- feature in our roadmap, but is not supported.

Thanks for your reply, glad to know it is in the roadmap.

**Comment by Raincle** [comment]
This feature would be very useful if we could aggregate a column in the UI.

As an alternative, to perform aggregation calculations，
I looked through the API docs and couldn't find how to aggregate a column.
If there is a way to do aggregation through the API, please let me know.
