### ISSUE TITLE
🐛 Bug: Anonymous SMTP authentication fails

### ISSUE THREAD

**Issue by aretaon** [nocodb/nocodb#7103]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Use the SMTP App to configure sending mails to internal web server that accepts anonymous authentication via Port 465.
Enter server hostname, from and smtp port, leave the username and password fields blank and click on "test".
Nocodb will inform that "SMTP test failed, please check server log for more details." and the log will state

` response: '535 5.7.8 Error: authentication failed: authentication failure',`

This is possibly related to #5559 but reopened here as new issue for better reference.

### Desired Behavior

The SMTP app sends an email via anonymous authentication (see https://github.com/nocodb/nocodb/issues/520) and does not produce an error.

### Project Details

NocoDB used as docker: yes
NocoDB version: "nocodb/nocodb:latest"
Database used: mysql
OS: Ubuntu 22.04

Detailed log:
```
Error: SMTP test failed, please check server log for more details.
    at SMTP.test (/usr/src/app/docker/main.js:2:1462617)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsService.pluginTest (/usr/src/app/docker/main.js:2:1684404)
    at async PluginsController.pluginTest (/usr/src/app/docker/main.js:2:435331)
SMTP test error ::  Error: Invalid login: 535 5.7.8 Error: authentication failed: authentication failure
    at SMTPConnection._formatError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
    at SMTPConnection._actionAUTHComplete (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:1564:34)
    at SMTPConnection.<anonymous> (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:546:26)
    at SMTPConnection._processResponse (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:969:20)
    at SMTPConnection._onData (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)
    at SMTPConnection._onSocketData (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9) {
  code: 'EAUTH',
  response: '535 5.7.8 Error: authentication failed: authentication failure',
  responseCode: 535,
  command: 'AUTH PLAIN'
```

**Comment by Zeoic** [comment]
I am having the same issue in our environment. We have a local only SMTP relay setup to allow anonymous requests, but get this same error in nocodb. Did you end up finding a way around this?

**Comment by aretaon** [comment]
No so far I did not solve this. There were other things with priority in the meantime but I am still very keen on getting this running.
Please let me know if you manage!

**Comment by Zeoic** [comment]
I spent a few more hours trying then eventually gave up and used Office365 directly with their SMTP service. We would have much preferred to use our relay which is already set up how we like it, but that wasn't in the cards it seems.

**Comment by aretaon** [comment]
Thanks @MarleTangible  for linking this here. Indeed adding the name attribute alone did not help, I additionally had to remove the authentication attribute to allow anonymous authentication.

First modification as suggested:
```javascript
if (process.env.NC_SMTP_FROM && process.env.NC_SMTP_HOST && process.env.NC_SMTP_PORT) {
    const e = await E.default.getPluginByTitle(y.default.title);
    await E.default.update(e.id, {
        active: !0,
        input: JSON.stringify({
            from: process.env.NC_SMTP_FROM,
            name: 'my-domain.name',
        })
    })
```

Second modification:
```javascript
async init() {
    var e, t, a, i, r, l, c, d, u, p, m;
    const _ = {
        ...
        // remove the following lines
        auth: {
            user: null === (u = this.input) || void 0 === u ? void 0 : u.username,
            pass: null === (p = this.input) || void 0 === p ? void 0 : p.password
        },
        ...
    };
    this.transporter = s.default.createTransport(_)
}
```

To avoid doing this manually all the time I added the following commands to my update script

```sh
docker exec -t -i mysql_nocodb_1 sed -i -e "s/from:process.env.NC_SMTP_FROM,host:process.env.NC_SMTP_HOST/from:process.env.NC_SMTP_FROM,name:'my-domain.name',host:process.env.NC_SMTP_HOST/g" docker/main.js
docker exec -t -i mysql_nocodb_1 sed -i -e "s/d.ignoreTLS),auth:{user:null===(u=this.input)||void 0===u?void 0:u.username,pass:null===(m=this.input)||void 0===m?void 0:m.password},tls:/d.ignoreTLS),tls:/g" docker/main.js
```

From my side, I can live with this solution,. However, I would very much welcome if future versions of NocoDB would include the option for anonymous authentication.

**Comment by aretaon** [comment]
@MarleTangible Thanks for pointing out the correct position of the `name` attribute. Nevertheless, I still have to remove the authentication to get it working for me. The SMTP server I use requires implicit TLS over port 465. 
![image](https://github.com/nocodb/nocodb/assets/17356695/75e37e33-20f4-44d5-904c-67e882b28535)

**Comment by DarkPhoenix2704** [comment]
@MarleTangible @aretaon  Can you try this docker build? 

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.205.0-pr-8412-20240506-1153
```
