### ISSUE TITLE
🐛 Bug: Fields are no longer displayed in full.

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#7108]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When you move the mouse over a field, it is no longer fully displayed.

![image](https://github.com/nocodb/nocodb/assets/117290601/1a125283-b010-4416-b667-798f41edefd2)

Same for column Headers. Hover Function missing:

![image](https://github.com/nocodb/nocodb/assets/117290601/79d51f10-b025-448b-a0d9-8d2ac3ab510b)

### Desired Behavior

Please reintroduce hover and use the DIV little bit more. There is plenty of space left and right. 

Alternatively, you could make it two lines.

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.8-20231123-1023**

**Comment by aboveagency** [comment]
Agree with the things that have been said. Also 'LongText' fields should not be truncated inside of the Kanban view, they should wrap. We use those fields for order information that we need to see at a glance, it slows us down to click into the record, which right now doesn't even show the full value.

Thank you!

**Comment by dstala** [comment]
fixed. should be available from next release.
