### ISSUE TITLE
🐛 Bug: Links and Link to another record API strange behavior

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#7109]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When we use the API "/api/v2/tables/md_zw2tsruga3v4lz/records/", the linktoanother records are displayed as Nested JSON.

However, when we add a fields=Nestedjsonfield to the API URL, we always get the message {"msg": "Invalid field: Nestedjsonfield "}

![image](https://github.com/nocodb/nocodb/assets/117290601/d11232b6-cd9b-4acf-8107-c14c1916092f)

Also all new LINKS fields are not even displayed in the results. Therefore if we want to use the API correct, we need to add all Fields as lookups.

For example:

We want to extract all Data with all linked columns:

First we need to excecute "/api/v2/tables/md_zw2tsruga3v4lz/records" API.

Then we need to excecute this api "/api/v2/tables/md_zw2tsruga3v4lz/links/cl_hdrjkni3qjd28x/records" in a for loop. This will excecute the API 10000 times.

### Desired Behavior

Please make the nestedjson fields back availabe in the "List Table Records" (For "Read Table Record" its working)

Also create a API where we can get all Data with linked Records in a single API Call even if its LINKS or LinkToAnother Field. This API will not be needed for the Frontend, but working with Noco data its important.

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.8-20231123-1023**

**Comment by dstala** [comment]
fixed. https://github.com/nocodb/nocodb/pull/7111
