### ISSUE TITLE
October 31 not displayed

### ISSUE THREAD

**Issue by FrancisVarga** [nocodb/nocodb#711]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.80.0**

**Comment by o1lab** [comment]
Fix will be available in version > 0.80

**Comment by pranavxc** [comment]
Fixed in `0.81.0`
