### ISSUE TITLE
🐛 Bug: Not able to change body in webhook of  nocodb cloud 

### ISSUE THREAD

**Issue by sangeet-verma** [nocodb/nocodb#7118]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Login to NocoDB cloud 
2. open webhooks 
3. add webhooks 
4. Body is not coming to update

### Desired Behavior

As per documentation Body should come to update body of webhook 

### Project Details

NocoDb Cloud 

### Attachments

<img width="1440" alt="Screenshot 2023-11-29 at 11 54 14 PM" src="https://github.com/nocodb/nocodb/assets/131944682/183ec9fe-3540-4754-a2d2-60ad4c978d99">

**Comment by sangeet-verma** [comment]
> @sangeet-verma since last few releases, support for configurable body is deprecated. webhook response for all the triggers will be standard response https://docs.nocodb.com/automation/webhook/create-webhook/#webhook-response-sample

Do you anticipate potential challenges arising from the deprecation of support for configurable bodies in webhook responses, particularly concerning the standardized response format? Considering the standardization, could this pose issues when aiming to adhere to specific body formats, such as those required by platforms like Slack?

**Comment by o1lab** [comment]
To adapt the response of webhooks response to various platforms - its best to write a middleware layer instead or use n8n/make/zapier kinda thing or wait for our automation feature (mid next year :).
