### ISSUE TITLE
Recreating metadata on Models resets some column types to LongText

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#712]
**Steps To Reproduce**
1. Create a table 
2. Add some fields (longtext, checkbox, single select, image, multiple select)
3. Input some data
3. Go to Meta Management, click ``recreate metadata`` under Actions
4. Go back to table view, those fields with single select, image & multiple select type become LongText while longtext and checkbox remain unchanged.

**Expected behavior**
The column type shouldn't be changed.

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.80.0**

**Comment by wingkwong** [comment]
Also it will remove all the relations (one-to-many) columns

**Comment by o1lab** [comment]
Solved in 0.84.1
