### ISSUE TITLE
🐛 Bug: All the links have disappeared

### ISSUE THREAD

**Issue by starmisszhang** [nocodb/nocodb#7125]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Am I the only one experiencing this problem? 

### Desired Behavior

Such a serious bug,Resulting in the loss of all data.

### Project Details

0.202.9

**Comment by dstala** [comment]
@starmisszhang could you help us with your base information?

**Comment by starmisszhang** [comment]
@dstala 
Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.202.9**

**Comment by raphaeldeux** [comment]
Hello,

I have the same problem. All the links are gone, but the data is not loss.

![Screenshot of NocoDB](https://github.com/nocodb/nocodb/assets/111633984/4cbd0e5f-2239-441b-a146-92ddf5d645b2)

**Comment by o1lab** [comment]
Are there any errors your see in browser console or your server ? We need base info (can be found from three dots / base menu). Please get in touch with @mertmit in our [discord](https://discord.gg/c7GEYrvFtT)

**Comment by pranavxc** [comment]
We had made a fix, please try the following PR build to verify the fix.

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.202.9-pr-7161-20231205-1350
```

**Comment by raphaeldeux** [comment]
@pranavxc alright, the patch is working :) thanks !
