### ISSUE TITLE
🐛 Bug: OTP not sending Email 

### ISSUE THREAD

**Issue by speed127** [nocodb/nocodb#7129]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Click on Teams & Settings
Enter an Email address with Edit rights
New User received email
Clicked on link
Clicked on Forgot Password
DID NOT RECEIVE OTP
Clicked on resend OTP
Still not received

### Desired Behavior

Receive the OTP on email

### Project Details

https://app.nocodb.com/

**Comment by dstala** [comment]
@speed127 I just tried, did receive OTP; can you confirm if the user for which you are trying to reset password - had originally signed up using username / password or cognito?

**Comment by dstala** [comment]
@speed127 reopen this thread if issue still persists
