### ISSUE TITLE
Feature: Grid view - Add keyboard shortcuts support

### ISSUE THREAD

**Issue by automationsClub** [nocodb/nocodb#713]
It would be great to have support for all the usual key combinations actions:

| Key | Action |
|---|---|
| ctrl+c | copy |
| ctrl+z | undo |
| ctrl+y | redo |
| ctrl+a | select all grid |
| ctrl+arrows | jump to end of raw/column |
| shift+arrows | select while moving on grid |
| ctrl+shift+arrows | select till end of raw/column |

**Comment by o1lab** [comment]
Capture in #352
