### ISSUE TITLE
🐛 Bug: Comments added through API TOKEN request cannot be displayed, but are displayed normally through JWT TOKEN

### ISSUE THREAD

**Issue by AlienHub** [nocodb/nocodb#7132]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### API TOKEN

1. Add comments using API TOKEN as authentication
![image](https://github.com/nocodb/nocodb/assets/44266450/7ff00a27-578f-4d68-9e59-94dd0492ed04)
2. View form comment information on the web page
![image](https://github.com/nocodb/nocodb/assets/44266450/01b023f5-70cc-46fd-a4cc-b9bba1ebd945)
![image](https://github.com/nocodb/nocodb/assets/44266450/37282d70-8ac7-4a6a-b838-6dc819360684)

### JWT TOKEN
1. Add comments using JWT TOKEN as authentication
![image](https://github.com/nocodb/nocodb/assets/44266450/f810e8a8-ab7a-46f3-892e-f332d801f52a)
2. View form comment information on the web page
![image](https://github.com/nocodb/nocodb/assets/44266450/0ee19c96-9351-43a9-bebd-9577f045ab99)

### Desired Behavior

.

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.8**

**Comment by wingkwong** [comment]
What is the role of your account? admin or editor?

**Comment by dstala** [comment]
Possible that token is old & doesn't belong to any user? Does the issue persist even with newly created token?

**Comment by AlienHub** [comment]
> Possible that token is old & doesn't belong to any user? Does the issue persist even with newly created token?

Using a new token is also invalid, and using the token to update rows and other operations is normal.
![image](https://github.com/nocodb/nocodb/assets/44266450/6fa1aa02-7c72-4563-acaf-75119e5f2874)
![image](https://github.com/nocodb/nocodb/assets/44266450/4381f39c-d1e9-4e96-82c8-f95edfd87e49)
![image](https://github.com/nocodb/nocodb/assets/44266450/a4af0b51-76be-4a25-b7f6-4065ff8c3425)

And it is worth noting that in the table view, the number of comments displayed by the icon at the front of the row will be updated, but the comments cannot be seen.

**Comment by aashishagrawall** [comment]
@dstala @wingkwong  my observation when creating comment through postman using api token

![Screenshot_20231203_125937](https://github.com/nocodb/nocodb/assets/14330781/88aee18b-d1cb-47a0-96f1-228209643b19)

user email is not being store in nc_audit_v2 table  which creating comments through api token

This is creating issue while fetching comment list because audit table  is joining with users table

![Screenshot_20231203_130135](https://github.com/nocodb/nocodb/assets/14330781/6fdfe3ea-ce5f-4047-b5ef-6cdfe95af7ae)

**Comment by salim-b** [comment]
I think this could be due to the [` GET /api/v1/auth/user/me API endpoint.`](https://data-apis-v1.nocodb.com/#tag/Auth/operation/auth-me) returning different data (fields) when calling it with an `xc-token` (API token) vs. an `xc-auth` (user access token) header.

**Comment by pranavxc** [comment]
With the latest version and a new API token, the issue appears to be resolved. Please feel free to reopen this if the problem persists on your end.”
