### ISSUE TITLE
🐛 Bug: Rename View In Dropdown menu

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#7136]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Rename in view dropdown menu not working (double click works just fine)

### Desired Behavior

-

### Project Details

develop

### Attachments

<img width="626" alt="image" src="https://github.com/nocodb/nocodb/assets/59797957/6534ea8a-db49-49dc-b8ec-ab77bc83d0b0">

**Comment by dstala** [comment]
Rename from similar menu accessible from top bar bread crumb works just fine.
