### ISSUE TITLE
🔦 Feature: When "grouping by", allow to select the number of elements to display

### ISSUE THREAD

**Issue by Angeall** [nocodb/nocodb#7147]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Hello,

When using the "group by" feature, records are limited to 10 per page.
It would be very cool to be able to select the number of max records per page.

![image](https://github.com/nocodb/nocodb/assets/6820648/f5899b39-d765-4ceb-98c4-5e26e5f5d2dd)

### Suggested Solution

Something like a selectbox on the bottom of each group, with a preset of values like "10, 25, 50, 100".
It should also work when multiple fields are selected for the 'group by', and either have one per group or one that applies to all groups.

**Comment by dstala** [comment]
@Angeall we have two environment variables to control this, but nothing on the UI yet (we decided against it to reduce configuration burden on the end user)

`DB_QUERY_LIMIT_GROUP_BY_GROUP` : Group per page limit. Defaults to 10
`DB_QUERY_LIMIT_GROUP_BY_RECORD` : Record per group limit. Defaults to 10 

https://docs.nocodb.com/getting-started/self-hosted/environment-variables

**Comment by Angeall** [comment]
Ok thank you very much.
Indeed in my usecase, this solves the issue I had, and this matches my need.

If you say it's a decision to not have it on the front end, group by group, then please close this feature request :)
