### ISSUE TITLE
🐛 Bug: UI/UX fixes

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7156]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] `Group-by` initial menu to be made similar to `Sort`
![Screenshot 2023-12-05 at 2 40 12 PM](https://github.com/nocodb/nocodb/assets/86527202/01dd83f2-5017-4a81-8fc9-777d4c52aa25)
![Screenshot 2023-12-05 at 2 40 24 PM](https://github.com/nocodb/nocodb/assets/86527202/5b6ace32-e381-4a47-b6a5-db359287393d)

- [x] Update `Group-by` testcases

- [x] DateTime field, on the picker - set default time to current time always & enable `OK` button by default

- [x] Default name for token, let it be `Token-1` `Token-2` `Token-3` and such
![Screenshot 2023-12-06 at 12 35 13 PM](https://github.com/nocodb/nocodb/assets/86527202/83e2a462-4262-437f-bb30-ff161e67a77a)

- [x] Webhook modal
  - [x] Default name, let it be `Webhook-1` `Webhook-2` and such
  - [x] Set first option in the trigger list as selected by default
![Screenshot 2023-12-06 at 12 37 52 PM](https://github.com/nocodb/nocodb/assets/86527202/7d1254c4-bf1f-4f4e-956b-644ea516f5d6)
- [x] Created-at, Updated-at : right click should disable `Clear` option;
- [x] Introduce paste option in cell right click context menu
- [x] System column shouldn't be editable
- [x] Junction table shouldn't be editable
![Screenshot 2023-12-06 at 4 06 35 PM](https://github.com/nocodb/nocodb/assets/86527202/ed6aac35-ad27-472b-b14a-5502caa3bfdf)
![Screenshot 2023-12-06 at 4 06 51 PM](https://github.com/nocodb/nocodb/assets/86527202/5f028d14-b352-4555-869e-2e3d0b749b9a)

- [x] Minimum width for select drop down's
![Screenshot 2023-12-07 at 9 57 09 PM](https://github.com/nocodb/nocodb/assets/86527202/604fed6b-744d-46eb-afb7-c06b6fea9c6d)

### Desired Behavior

x

### Project Details

202.9

**Comment by gauravruhela07** [comment]
Hey, just getting started with making contributions. I would like to work on it, can you please assign this issue to me? Thank you.

**Comment by rameshmane7218** [comment]
Hi @gauravruhela07, I have already started working on this issue. You can find another issue.

Thanks for showing interest in contributing to NocoDB!

**Comment by rameshmane7218** [comment]
@dstala is their any specific min width for `select drop down's` ?

**Comment by rameshmane7218** [comment]
@dstala I'm setting min-width = max-content

**Comment by dstala** [comment]
> @dstala I'm setting min-width = max-content

Let us use fixed width; IMO, we can have width equal to default field width on grid

**Comment by rameshmane7218** [comment]
> > @dstala I'm setting min-width = max-content
> 
> Let us use fixed width; IMO, we can have width equal to default field width on grid

And what about option max line, text should wrap to next line or text should be hidden (this is current)
<img width="218" alt="Screenshot 2023-12-11 at 11 09 33 AM" src="https://github.com/nocodb/nocodb/assets/101566080/0322ea86-749b-49b9-a50c-ddb8bfbe7cee">

**Comment by dstala** [comment]
- [ ] Open token page, error noticed
```
[Nest] 46679  - 12/12/2023, 12:41:53 PM   ERROR [GlobalExceptionFilter] select "nc_api_tokens"."id", "nc_api_tokens"."token", "nc_api_tokens"."description", "nc_api_tokens"."fk_user_id", "nc_api_tokens"."base_id", "nc_api_tokens"."created_at", "nc_api_tokens"."updated_at", (select "email" from "nc_users_v2" where nc_users_v2.id = nc_api_tokens.fk_user_id) as "created_by" from "nc_api_tokens" limit $1 - LIMIT must not be negative
error: select "nc_api_tokens"."id", "nc_api_tokens"."token", "nc_api_tokens"."description", "nc_api_tokens"."fk_user_id", "nc_api_tokens"."base_id", "nc_api_tokens"."created_at", "nc_api_tokens"."updated_at", (select "email" from "nc_users_v2" where nc_users_v2.id = nc_api_tokens.fk_user_id) as "created_by" from "nc_api_tokens" limit $1 - LIMIT must not be negative
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by dstala** [comment]
> > > @dstala I'm setting min-width = max-content
> > 
> > 
> > Let us use fixed width; IMO, we can have width equal to default field width on grid
> 
> And what about option max line, text should wrap to next line or text should be hidden (this is current) <img alt="Screenshot 2023-12-11 at 11 09 33 AM" width="218" src="https://private-user-images.githubusercontent.com/101566080/289435863-0322ea86-749b-49b9-a50c-ddb8bfbe7cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjUxODAsIm5iZiI6MTcwMjM2NDg4MCwicGF0aCI6Ii8xMDE1NjYwODAvMjg5NDM1ODYzLTAzMjJlYTg2LTc0OWItNDliOS1hNTBjLWRkYjhiZmJlN2NlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwNzA4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWZmZjE4ZTczNWEyZWE0ZTNlOTRkOTlhNmNlMTcxN2FjOWI3YjUxZDI2MjdlMTIyN2NlZDVjZGExZDA5YmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmMamUetxcuR0Qs4GidAATR5tbGBLOLalKQfxR6iW90">

Use ... & show full text on hover in a tooltip

**Comment by rameshmane7218** [comment]
> > > > @dstala I'm setting min-width = max-content
> > > 
> > > 
> > > Let us use fixed width; IMO, we can have width equal to default field width on grid
> > 
> > 
> > And what about option max line, text should wrap to next line or text should be hidden (this is current) <img alt="Screenshot 2023-12-11 at 11 09 33 AM" width="218" src="https://private-user-images.githubusercontent.com/101566080/289435863-0322ea86-749b-49b9-a50c-ddb8bfbe7cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjUxODAsIm5iZiI6MTcwMjM2NDg4MCwicGF0aCI6Ii8xMDE1NjYwODAvMjg5NDM1ODYzLTAzMjJlYTg2LTc0OWItNDliOS1hNTBjLWRkYjhiZmJlN2NlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwNzA4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWZmZjE4ZTczNWEyZWE0ZTNlOTRkOTlhNmNlMTcxN2FjOWI3YjUxZDI2MjdlMTIyN2NlZDVjZGExZDA5YmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmMamUetxcuR0Qs4GidAATR5tbGBLOLalKQfxR6iW90">
> 
> Use ... & show full text on hover in a tooltip

- Added tooltip for this and the max width of option is fixed to 20 char width even if select dropdown width is greater than 20 char width

**Comment by rameshmane7218** [comment]
> > > > > @dstala I'm setting min-width = max-content
> > > > 
> > > > 
> > > > Let us use fixed width; IMO, we can have width equal to default field width on grid
> > > 
> > > 
> > > And what about option max line, text should wrap to next line or text should be hidden (this is current) <img alt="Screenshot 2023-12-11 at 11 09 33 AM" width="218" src="https://private-user-images.githubusercontent.com/101566080/289435863-0322ea86-749b-49b9-a50c-ddb8bfbe7cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjUxODAsIm5iZiI6MTcwMjM2NDg4MCwicGF0aCI6Ii8xMDE1NjYwODAvMjg5NDM1ODYzLTAzMjJlYTg2LTc0OWItNDliOS1hNTBjLWRkYjhiZmJlN2NlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwNzA4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWZmZjE4ZTczNWEyZWE0ZTNlOTRkOTlhNmNlMTcxN2FjOWI3YjUxZDI2MjdlMTIyN2NlZDVjZGExZDA5YmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmMamUetxcuR0Qs4GidAATR5tbGBLOLalKQfxR6iW90">
> > 
> > 
> > Use ... & show full text on hover in a tooltip
> 
> * Added tooltip for this and the max width of option is fixed to 20 char width even if select dropdown width is greater than 20 char width

Reverted back as this changes leads to fail playwright test cases where we did getOptionByText()
