### ISSUE TITLE
🔦 Feature: Switching among RTL form fields using tab button

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#7157]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Thanks to the visual improvements of RTL forms, we can now create dozens of visually appealing forms in Farsi and they are super easy to use. However, there is an issue. When we want to switch to the next field in the form, we need to use the mouse pointer. It would be much better if we could use the tab button; like many other forms in other platforms. It increases the ease of use.

### Suggested Solution

I think it'd be great if we could get the control of the next field using the tab button on keyboard.

**Comment by dstala** [comment]
general issue, not specific to RTL
to be tracked under [🔦 Feature: Pressing tab while on a form should move the cursor to the next field#5969](https://github.com/nocodb/nocodb/issues/5969)
