### ISSUE TITLE
🐛 Bug: Audit log for external database not visible through UI

### ISSUE THREAD

**Issue by lcavasso** [nocodb/nocodb#7165]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Set up an external database
2. Select the base in NocoDB (in the example below, 0.202.8 is external)
3. Go to Data Sources tab
4. There is no button to view the audit log for the external database; only the default one
![image](https://github.com/nocodb/nocodb/assets/35540322/a5a66392-260c-4de0-b82a-c68d11d9e965)

Looked in the backend, there are logs in `nc_audit_v2`, just seems they are not exposed through the UI?

### Desired Behavior

Add a button for auditing the external database, just like there is for the default one.

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.202.8**

**Comment by dstala** [comment]
@rameshmane7218 let us enable this for OSS only

**Comment by rameshmane7218** [comment]
Fixed in PR #7173

**Comment by lcavasso** [comment]
This issue has returned; there is now no option to audit default database either.
![image](https://github.com/nocodb/nocodb/assets/35540322/94bc4496-f26c-4f1a-b23e-6f3f0e519e82)

**Comment by o1lab** [comment]
Click on the data source - you will see something like below

![Uploading image.png…]()

**Comment by lcavasso** [comment]
Ah, it looks like this for me - still no audit option on the external database. 
![image](https://github.com/nocodb/nocodb/assets/35540322/b82e5d79-c554-4ead-8ace-9e95b6675fbf)

It shows up correctly as you mention for the default one.
