### ISSUE TITLE
🔦 Feature: Filter Days now uniformly utilizes 'datetime' for all calculations.

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#7176]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Current Functionality:
The existing filter displays all entries occurring after the specific date and time:

where(2023-12-05 13:30:00+00:00,ge,today) 
In this case, all events after '2023-12-05 13:30:00+00:00' are shown.

![image](https://github.com/nocodb/nocodb/assets/117290601/d402b55f-14d4-4e1b-a8b6-994f18651264)

### Suggested Solution

New Functionality:
The proposed filter will display all entries occurring after the specific date, disregarding the time:

where(2023-12-05 13:30:00+00:00,geDate,today) 
With this, all events after '2023-12-05 00:00:00+00:00' will be displayed, irrespective of the time.

### Additional Context

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.9-20231204-1203**

**Comment by dstala** [comment]
@emre1e can you help us understand purpose of this change proposal? if we wish to disregard time, is it not good idea to switch over to date type instead of date time?
