### ISSUE TITLE
Table rename . failed

### ISSUE THREAD

**Issue by Charlie-Rem** [nocodb/nocodb#718]
I cannot rename a table. I get the following error message: 

Table rename . failed

Here is a 2 minutes 17 seconds video which shows exactly my problem, from deploying the app to Heroku to this bug: [https://youtu.be/jQsplCDoR_w](https://youtu.be/jQsplCDoR_w)

This was on 30th october 2021, so with the latest version to this day, that is 0.80.0

**Comment by o1lab** [comment]
Thank you for the detailed report.

This is tracked in #205 and I see your comment in that.
