### ISSUE TITLE
🐛 Bug: API made calls not shown in the audit log

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#7201]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Is it somehow possible to show external api calls in the audit log? In the database they are existing. Just the User field is empty

![image](https://github.com/nocodb/nocodb/assets/117290601/31628a36-31d3-4d2a-8cd6-fa8eb77049f6)

### Desired Behavior

ENV variable to turn it on?

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.9-20231204-1203**

**Comment by cchance27** [comment]
Was wondering this as well, honestly seems odd, the API knows who owns the key, so seems odd that the api edit is null

**Comment by emre1e** [comment]
@dstala Are there any possibilities to see the update made with the token via the API in the audit log?

**Comment by dstala** [comment]
we will work on it here
https://github.com/nocodb/nocodb/issues/8868
