### ISSUE TITLE
🐛 Bug: Grid View - When adding a new Record with a Group By on the view, the field corresponding to the Group By remains empty

### ISSUE THREAD

**Issue by progamax** [nocodb/nocodb#7204]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create Table A and Table B. The Table A must have a column that is a NOT NULL foreign key corresponding to table B
- Put one or two records in table B and also in table A
- In the Grid View of Table A, apply a Group By on this new column
- Open one of the group and click on "New Record - Form"
No record can be link visually

Note : I put NOT NULL flag on the Table A's column manually with an SQL command and then I synced the scheme in NocoDB settings

### Desired Behavior

The form's field that corresponds to the Group By column should be prefilled with the value of the group in which we click "New Record - Form"
( Or at least, the field should not be blocked )

### Project Details

NocoDB from node

### Attachments

https://github.com/nocodb/nocodb/assets/16340531/36879d36-0259-45ea-9bbf-62fcdc33c0a0

**Comment by wingkwong** [comment]
which version are you using? v0.202.9?

**Comment by pranavxc** [comment]
Hi @progamax, Thanks for pointing out the bug - we can't pre-fill in these scenarios since it's grouped based on the count and it can map to any rows to achieve the count. So the ideal solution will be allowing user to manually select in these scenarios.

**Comment by progamax** [comment]
I am using 0.202.8
