### ISSUE TITLE
🐛 Bug: UI/UX fixes - 2

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7210]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] Need tooltip on hover
![Screenshot 2023-12-12 at 8 47 31 PM](https://github.com/nocodb/nocodb/assets/86527202/98827a17-7384-4909-9c5f-7c98167bb838)
- [x] Select option text and icon are not aligned center 
![Screenshot 2023-12-18 at 1 24 56 PM](https://github.com/nocodb/nocodb/assets/101566080/a4649116-56e3-4490-aa6f-1cdc9fc35b7e)

- [x] group by `new record` and add new row : default value is not reflected immediately
- [x] group by when done over dateTime or time field, format of the dateTime/time display should be same as cell display
![Screenshot 2023-12-12 at 12 39 33 PM](https://github.com/nocodb/nocodb/assets/86527202/e0699ed3-4f71-4cd2-8874-d0b947c30ef0)
- [x] Shared grid view, nothing is displayed in first column 
![Screenshot 2023-12-08 at 9 14 41 PM](https://github.com/nocodb/nocodb/assets/86527202/f6893631-4588-40c6-bfb5-0b6accd860fa)
- [x] Horizontal scroll bar for Kanban
- [x] Hide paste option on Shared grid view <img width="601" alt="Screenshot 2023-12-13 at 11 00 09 AM" src="https://github.com/nocodb/nocodb/assets/101566080/4386190b-f12d-4500-a970-c83811c7d7ce">

- [x] Expand icon for long text & rich text, should become visible on hover / on click. Not always. <img width="722" alt="Screenshot 2023-12-16 at 8 10 06 AM" src="https://github.com/nocodb/nocodb/assets/86527202/4be8bbf9-ee48-4752-955a-8ef5eafe6c54">

- [x] Display tooltip only when we truncate text. in this case, its always displayed on hover <img width="468" alt="Screenshot 2023-12-16 at 8 13 00 AM" src="https://github.com/nocodb/nocodb/assets/86527202/313e159c-3198-4192-859e-87435f1f44fb">

- [x] Set the default hook title only when creating a new hook.
![Screenshot 2023-12-16 at 10 40 43 AM](https://github.com/nocodb/nocodb/assets/101566080/600d4569-121f-4422-b2fa-b38e54cb4755)

- [x] The message notice icon is not aligned center ![Screenshot 2023-12-18 at 4 23 07 PM](https://github.com/nocodb/nocodb/assets/101566080/a1797c1b-9309-4107-954c-7eb05d4eee0c)

### Desired Behavior

x

### Project Details

202.9

**Comment by rameshmane7218** [comment]
@dstala "group by new record : default value is not reflected immediately" this is working properly

**Comment by dstala** [comment]
> @dstala "group by new record : default value is not reflected immediately" this is working properly

on 202.10 / `PG`
- create a table with 2 fields, field1, field2
- configure default value for field2
- create group by over field1
- expand one of the group by, add records
- expected : new records added should have default value configured for field2

**Comment by rameshmane7218** [comment]
> > @dstala "group by new record : default value is not reflected immediately" this is working properly
> 
> on 202.10 / `PG`
> 
> * create a table with 2 fields, field1, field2
> * configure default value for field2
> * create group by over field1
> * expand one of the group by, add records
> * expected : new records added should have default value configured for field2

Now I got it, the issue is only `groupBy` field default value is added in new record but not other fields default value
