### ISSUE TITLE
🐛 Bug: excel import error

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7211]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

import excel

Source : Musharaf
[file_example_XLS_50.xls](https://github.com/nocodb/nocodb/files/13645054/file_example_XLS_50.xls)

### Desired Behavior

create table with data

### Project Details

Node: **v18.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.202.9**

**Comment by wingkwong** [comment]
preliminary findings:

- `Id` will be treated as system field 
- there are duplicate records in `id`

**Comment by dstala** [comment]
discussed with @wingkwong 
`Id` field, as its being treated as system field can't have duplicates. Correcting such records manually or changing column name works (temporary fix). This will be discussed in another thread for appropriate fix
