### ISSUE TITLE
🐛 Bug: Grouping by lookup column does not display the group name

### ISSUE THREAD

**Issue by rogoersTPH** [nocodb/nocodb#7226]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have a table with this schema:

![image](https://github.com/nocodb/nocodb/assets/91682637/f57d54ac-4856-454b-9ce3-89f8fe5b5c38)

Where "Tasks" is linked to a "Tasks" table and "Project" is a lookup to this table. The idea is, that the user only needs to choose the task from the link candidates and the Project is filled in automatically. 
That works.

However, creating a Grid view where I group first by project and then by task, results in
![image](https://github.com/nocodb/nocodb/assets/91682637/e3e0aadd-5c65-44f6-a16d-fa969d33a031)
The Project name is missing even though the grouping works.

### Desired Behavior

The name of the group should be displayed when using a lookup column as a grouping variable.

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.10**

**Comment by dstala** [comment]
@rogoersTPH can you try in 203.2 and let us know if issue persists? if it does, help us with more information - like what type of the fields were you looking up?

we tried group-by over lookup in 203.2 - and it seems fine.
