### ISSUE TITLE
🐛 Bug: Subsequent Longtext fields are distorted in Gallery or Kanban view

### ISSUE THREAD

**Issue by rogoersTPH** [nocodb/nocodb#7227]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When I have a table with two Longtext columns, the text is not displayed properly in the Gallery or Kanban view.

This
![image](https://github.com/nocodb/nocodb/assets/91682637/958fc05e-812e-48e5-88e6-8ddabcc14f23)
results in this Gallery view
![image](https://github.com/nocodb/nocodb/assets/91682637/98268b3b-52fd-4852-966c-06bf677f4937)
or this Kanban view
![image](https://github.com/nocodb/nocodb/assets/91682637/0d8dc177-4d2b-43e5-8fa8-132f02dde7f9)

As you can see, the text of the two fields is overlapping each other.

### Desired Behavior

The text should be readable and not overlapping.

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.10**

**Comment by dstala** [comment]
@rogoersTPH should be available from next release;

**Comment by rogoersTPH** [comment]
@dstala Thanks a lot!
