### ISSUE TITLE
🐛 Bug: Record height in expanded view should be adjustable

### ISSUE THREAD

**Issue by rogoersTPH** [nocodb/nocodb#7228]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

If this record 
![image](https://github.com/nocodb/nocodb/assets/91682637/e2ea8c40-5745-4238-b8f7-edfd3a81196e)
is expanded, the result is
![image](https://github.com/nocodb/nocodb/assets/91682637/4e18c5d5-cc06-4c33-a81d-1823b057516e)
which looks fine.

However, if the record height is set to short
![image](https://github.com/nocodb/nocodb/assets/91682637/d119ae25-0651-4288-bb54-ccefd4ddddeb)
it is also (too) short in the expanded view
![image](https://github.com/nocodb/nocodb/assets/91682637/efc2e8e7-bacc-4901-b8a9-30c3accf398d)
and requires the user to click on the expand button of the individual long text fields in order to see the full content.

### Desired Behavior

I think it would be good if either the height of records in expanded view containing long text is adjusted automatically to a certain degree and then scrollable.
Or that the user can adjust the height of records in the expanded view separately. 
(or both ;))

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.10**

**Comment by dstala** [comment]
Good to
- auto adjust height of long text (+ rich text) field if cell has upto 6-8 lines may be; for more, provide scroll
- provide option to expand modal in right bottom corner + option for pop-up modal if required

**Comment by dstala** [comment]
supported now as seen in v0.204.9; if any other similar issues noticed, reopen this thread.
