### ISSUE TITLE
🔦 Feature: Improve URL readability

### ISSUE THREAD

**Issue by orangetruth** [nocodb/nocodb#7239]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently URLs are mostly gibberish. For example, something like mydomain.com/dashboard/#/nc/fgdisjg2/gdf9gu902g.

It would be better to have readable, user-friendly URLs like mydomain.com/name-of-the-base, or maybe mydomain.com/table-name instead.

### Suggested Solution

Make URLs user friendly and based on the base/table/view name, rather than randomly generated

**Comment by dstala** [comment]
URL formula now supports providing an alternative text. If that doesn't suffice for this use case, please reopen this thread.
