### ISSUE TITLE
🐛 Bug:  V2 API - Impossible to unlink records -  always "invalid input syntax for type integer" error

### ISSUE THREAD

**Issue by woodmin** [nocodb/nocodb#7262]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Linking 1:M Records (POST) using /api/v2/tables/{tableId}/links/{linkId}/records/{recordId} endpoint succeeds.
Using exactly the same settings to unlink (DELETE) fails with error:
Response:
{
  "msg": "select \"id\" from \"Table_Name\" where \"id\" in ('{\"Id\":1}', '{\"Id\":2}') - invalid input syntax for type integer: \"{\"Id\":1}\""
}

### Desired Behavior

Should be able to unlink records over API V2. Currently only manual unlinking works.

### Project Details

Docker: **true**
PackageVersion: **0.202.10**
Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
RootDB: **pg**
Database version : **15.5**

### Attachments

![image](https://github.com/nocodb/nocodb/assets/65443816/3b34cac0-f032-4758-8402-5e6fecc27930)

**Comment by dstala** [comment]
worked fine. 

```
curl -X 'DELETE' \
  'http://localhost:9000/api/v2/tables/mbxfalx7lk6jxg4/links/c43jv5c0eez03xe/records/9' \
  -H 'accept: application/json' \
  -H 'xc-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbm9jb2RiLmNvbSIsImlkIjoidXMxODg1dmdudDh0cmZvZyIsInJvbGVzIjoib3JnLWxldmVsLWNyZWF0b3Isc3VwZXIiLCJ0b2tlbl92ZXJzaW9uIjoiYWM3Mzc4YmFkYTA2MDIyMDgwYTQxZTJkN2NjMzhhODgwZjcwNzQ0YWEwZTQ2Y2JlZTQ3ZmZjNDViYWRiYzczYjlmZDNkOTFiMjFhNmE5MWIiLCJpYXQiOjE3MDMwNTc0NTQsImV4cCI6MTcwMzA5MzQ1NH0.OKqKya993f5iI1gUWG021GCJhdzFaBRentUkwzocJww' \
  -H 'Content-Type: application/json' \
  -d '[
  {
    "Id": 1
  },
  {
    "Id": 2
  }
]'
```

**Comment by dstala** [comment]
what relation did you try to unlink? i tried for many-many & it worked fine.

**Comment by woodmin** [comment]
Tried to unlink 1 to Many connection. In Swagger copied exactly the same data from Link to Unlink and failed as described above. Tried on a few dbs/tables with the same result.
