### ISSUE TITLE
🐛 Bug:  Gallery View Image View is broken.

### ISSUE THREAD

**Issue by cocoonkid** [nocodb/nocodb#7264]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Gallery View Image View is broken.

Upload Image as attachment.
Be able to view the whole size or be able to modify it so it makes sense visually.Especially in the Gallery View.

The image size and view could be more optimized.  I think it is a very important part.

https://old.reddit.com/r/NocoDB/comments/14zogr7/attachments_image_thumbnail_size/
https://www.reddit.com/r/NocoDB/comments/11556xx/am_i_doing_it_wrong_or_are_image_attachments_not/

Thank you for your consideration.

### Desired Behavior

Be able to view the whole size or be able to modify it so it makes sense visually.

### Project Details

nocodb latest docker

### Attachments

![image](https://github.com/nocodb/nocodb/assets/43231640/cc07c5ca-4138-4d0d-b6b6-e82b844d2466)

**Comment by dstala** [comment]
can you share some sample images that you upload & let us know how you wish them to see?
are you referring to `crop` `fit` kind of opitons?

**Comment by ScriptJunky** [comment]
I don't believe this is an issue, more that it is a lack of functionality. I was about to file a feature request for similar -- **Clicking on an item in a locked gallery should allow the viewer to see  full size images and fields not already displayed on the card itself, unless specifically hidden**.

**Comment by rameshmane7218** [comment]
> I don't believe this is an issue, more that it is a lack of functionality. I was about to file a feature request for similar -- **Clicking on an item in a locked gallery should allow the viewer to see full size images and fields not already displayed on the card itself, unless specifically hidden**.

@ScriptJunky We have fixed this issue and In order to see image in full size you have to follow below steps:
- Click on the card to open expanded form
- Find attachment field and click on image to see in full size
- If attachment field is hidden then it will be under hidden fields so click on `Show hidden fields`

**Comment by dstala** [comment]
@cocoonkid try gallery view on latest gallery view. Let us know if the changes over there help.

**Comment by ScriptJunky** [comment]
@dstala I have all of my data in BaseRow currently, but would definitely love to test this (and move back to NocoDB). Is there any effort underway to support importing from BaseRow (similar to AirTable importing)?

**Comment by dstala** [comment]
@ScriptJunky No plans on that in our current roadmap.

**Comment by dstala** [comment]
Closing this issue as Gallery view now supports crop/fit configurable option
