### ISSUE TITLE
🔦 Feature: Browse documentation easily

### ISSUE THREAD

**Issue by vasnt** [nocodb/nocodb#7267]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

<img width="535" alt="image" src="https://github.com/nocodb/nocodb/assets/117589240/0912afe8-6800-4215-8888-58df318f97f8">

I think circled things should be clickable so one can move back & forth documentation easily. 

### Suggested Solution

make them hyperlink/clickable elements.

**Comment by o1lab** [comment]
Thanks for bringing that to our notice - indeed much needed. 

cc : @dstala
