### ISSUE TITLE
🐛 Bug: Cannot use nocodb after signing up for a free account

### ISSUE THREAD

**Issue by mjog** [nocodb/nocodb#7282]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Sign up for a new account via https://app.nocodb.com
2. Enter verification code sent via email
3. Watch as the app hangs forever when loading the UI:

![Screenshot from 2023-12-23 10-19-23](https://github.com/nocodb/nocodb/assets/3745088/9885af82-c5b0-4972-b652-3a77cbac4073)

NB the `TypeError: document.fonts.values() is not iterable` error show above is always presented in the console on page load/reload.

### Desired Behavior

The app completes loading and I can start using it.

### Project Details

Reproducible using both Firefox 121 & GNOME Web 45.1 on Ubuntu 23.10.

**Comment by dstala** [comment]
fixed now. @mjog thanks for bringing this to our attention
