### ISSUE TITLE
🐛 Bug: Toggle `Show NULL in Cells`removes table/schema editor access

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7295]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- login as admin
- go to base settings
- toggle `Show NULL in Cells`
- close modal
- until page reload, unable to add fields / table

### Desired Behavior

user permissions should remain intact

### Project Details

202.10

**Comment by rameshmane7218** [comment]
@dstala, could you please check from your side if this issue still exists in the new version? I've checked it in production as well as locally in OSS, and it's working fine.

**Comment by wingkwong** [comment]
No longer reproducible.
