### ISSUE TITLE
🐛 Bug: Webhooks with new conditions checker

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#7312]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Regarding this new Feature "Condition(old-record) = false and Condition(new-record) = true." 

### Desired Behavior

What happens on delete and insert? Are they untouched? Otherwise this condition stuff will break all my "After Delete" webhooks.

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.10**

**Comment by dstala** [comment]
@emre1e : delete & insert should work like before. if you face any issues, do let us know.

**Comment by emre1e** [comment]
ok Thank you very much. I will give it a try next week.

**Comment by dstala** [comment]
Reopen this thread if you need more details or ping us on discord
