### ISSUE TITLE
🔦 Feature: Using field values in the success message after submitting a form

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#7314]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When a form is successfully filled out and submitted, a message will be shown to the user. This message can be modified by editors. Sometimes, it is useful for the user that has submitted a form to see some of the values that they have entered in the form. Here's the example:
1. The user fills a form of a shop and confirms their order.
2. After the form is submitted, it is good for the user to be able to see the order datetime or the title of his order again in the success message.

### Suggested Solution

It seems good to be able to use curly brackets to select the field that we desire and create a success message such as the one below:

_You have successfully ordered a {{ordered_product}} at {{order_datetime}}._

(Where ordered_product and order_datetime are the table fields that have been filled out by the user using the form)

**Comment by okaeiz** [comment]
uhm... any responses?

**Comment by dstala** [comment]
@okaeiz this is a good proposal. noted. we might not pick it up immediately. any PRs on this from the community is welcome!
