### ISSUE TITLE
🐛 Bug: Currency datatype keeps changing to SpecificDBType automatically

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#7315]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When I set the cost column to currency in NocoDB, then it is changed to numeric type in the database (I am using postgresql).
When I get back to NocoDB and sync the database, the field is not currency anymore. I guess it is because the type is numeric in database and it does not recognize commas and letters (such as USD).
It is frustrating.
To reproduce this error, follow the steps below:
1. Change a field's data type to currency (I select IRR).
2. Go  to the database; the data type of the column has set to numeric.
3. Sync NocoDB with the database. The field is not of type 'Currency' anymore.

### Desired Behavior

I need to have a varchar column and make it display as Currency in NocoDB UI.

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.4**

**Comment by dstala** [comment]
@okaeiz You are on a older version of NocoDB. I tried this on v0.203.0 & seemed to be fine.
When you go to database in step (2) - do you make change to this currency field?

**Comment by okaeiz** [comment]
No I don't.
Let me update my NocoDB and I will give you further information.

**Comment by dstala** [comment]
@okaeiz reopen this thread if you still face this issue.
