### ISSUE TITLE
🐛 Bug: richtext- underline & strikethrough formatting doesn't persist

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7318]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- add underline / strikethrough formatting using rich text menu options, save. expand cell again, changes doesn't persist
- `use <u>underline text</u> to add underline manually. save. expand cell - underline persists. now add strikethrough using ~strikethrough~, underline disappears.`

### Desired Behavior

formatting should get saved

### Project Details

203.0

**Comment by mertmit** [comment]
#7320
