### ISSUE TITLE
No option to delete a user

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#733]
I created a user with the wrong email and couldn't delete it now.

**Steps To Reproduce**
1. Go to User Management
2. Create a user 

**Expected behavior**
There should be some buttons to delete users

**Screenshots**

![image](https://user-images.githubusercontent.com/35857179/139787127-b3d3f61f-8bcc-4c34-9899-30b2377b6058.png)

![image](https://user-images.githubusercontent.com/35857179/139787167-c79d42a1-4f03-422f-ac6f-ce882ac57d17.png)

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.81.1**

**Comment by o1lab** [comment]
duplciate #214
