### ISSUE TITLE
🐛 Bug: Updating to the latest version overwrites fields with the NOW() formula

### ISSUE THREAD

**Issue by ItsABlackScreen** [nocodb/nocodb#7332]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1.On nocodb version : 0.202.10, Have an sqlite3 database.
2. Populate a few fields with the NOW() formula.
3. Update to the latest version.
4. The existing data in those fields in now overwritten by the launch time of the new version.

### Desired Behavior

1.Update to the latest version. 
2.Fields with existing data from the NOW() function have time set to 00:00 with the existing date to preserve data. 

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.203.0**

**Comment by ItsABlackScreen** [comment]
So i had NOW() as a formula in a field called Date modified, as i assumed that it would be run only on changing a row. But it is rather run on every program start, effectively over writing itself on every program run. 

I now see there already is a system field recording that info. 
This issue can be closed.

**Comment by dstala** [comment]
Thanks @ItsABlackScreen for the update
