### ISSUE TITLE
🐛 Bug: Select field while it is updating the data, the changes are not being visually displayed.

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#7334]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a select field, try to change the values
its always showing empty, you need to hard refreh the site before seeing new values

### Desired Behavior

should work like in 0.203.0.

This Bug is happening from 203.0 to 203.1

I think is connected to https://github.com/nocodb/nocodb/commit/d12a18781e7d20612ab1e34f72b2b239b57e954b

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.203.1-pr-7325-20231229-0954**

**Comment by dstala** [comment]
check in v0.203.2 & let us know if you still face this issue

**Comment by emre1e** [comment]
fixed
