### ISSUE TITLE
Column with checkbox type may not be updated for consecutive clicks

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#734]
**Steps To Reproduce**
1. Create a project
2. Create a table
3. Create a column with checkbox type
4. Input multiple records, says 10 records
5. Tick all the record one by one as fast as you could 
6. The UI is updated but some may be not ticked after clicking review

Basically it's fine only If I click it, wait for the message box popping out, then click the next one. If I click them quickly, some may be not updated.

**Expected behavior**
The checkbox values can be updated even I click them fast.

Node: v12.22.6
Arch: x64
Platform: linux
Docker: false
Database: pg
ProjectOnRootDB: false
RootDB: pg
PackageVersion: 0.81.1

**Comment by nickneustroev** [comment]
Struggling with this bug too. When updating multiple checkboxes, I need to click first, then wait for update confirmation, then click another checkbox etc. Otherwise it doesn't apply (And I don't realise it until page update).

**Comment by o1lab** [comment]
Fixed in 0.82

**Comment by pranavxc** [comment]
Fixed in `0.83.1`

**Comment by nickneustroev** [comment]
Latest update 0.83.2
Still there :)

(Tested after hard refresh, even it Incognito mode)

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.83.2**

**Comment by pranavxc** [comment]
Fixed in `v0.83.3`

**Comment by nickneustroev** [comment]
Yay, fixed! Everything works fine now, thank you
