### ISSUE TITLE
🐛 Bug: getaddrinfo ENOTFOUND host.docker.internal

### ISSUE THREAD

**Issue by ajitgoel** [nocodb/nocodb#7340]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

i ran the following command to run nocodb for the first time and I am unable to access the dashboard. Would the community have an input? 

`docker stop nocodb-postgres && docker rm nocodb-postgres && docker run -d --name nocodb-postgres -v "$(pwd)"/nocodb:/usr/app/data/ -p 8080:8080 -e NC_DB="pg://host.docker.internal:5432?u=root&p=password&d=d1" -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" --net=host nocodb/nocodb:latest`

**Stack Trace:**
`Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'host.docker.internal'
}
[Nest] 11  - 01/01/2024, 6:43:36 PM     LOG [NestFactory] Starting Nest application...
[Nest] 11  - 01/01/2024, 6:43:36 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 11  - 01/01/2024, 6:43:36 PM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 11  - 01/01/2024, 6:43:36 PM     LOG [InstanceLoader] MulterModule dependencies initialized +1ms
[Nest] 11  - 01/01/2024, 6:43:36 PM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 11  - 01/01/2024, 6:43:36 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 11  - 01/01/2024, 6:43:36 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 11  - 01/01/2024, 6:43:36 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 11  - 01/01/2024, 6:43:36 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 11  - 01/01/2024, 6:43:36 PM   ERROR [ExceptionHandler] Error: getaddrinfo ENOTFOUND host.docker.internal
Error: Error: getaddrinfo ENOTFOUND host.docker.internal
    at NcConfig.create (/usr/src/app/docker/main.js:2:1892717)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1360883)
    at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
    at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
`

### Desired Behavior

.

### Project Details

.

**Comment by wingkwong** [comment]
Can you verify if your Postgres DB is up and running?

**Comment by ajitgoel** [comment]
My local postgres database(not in docker container) is up and running, however the connection string is different than what i have listed above(the above instructions are from the nocodb readme documentation)
I am using Linux(ubuntu) OS. 
Can you please advise?

**Comment by wingkwong** [comment]
@ajitgoel For Linux, you need to pass `--add-host=host.docker.internal:host-gateway` to your command in order to bind host ip to `host.docker.internal`. It is not automatically binded as in other operating systems.

**Comment by ajitgoel** [comment]
I get a `[dumb-init] --add-host=host.docker.internal:host-gateway: No such file or directory` error when I check using the `docker logs nocodb-postgres` command.

**Comment by wingkwong** [comment]
Did you add it to your docker run command?

**Comment by ajitgoel** [comment]
I was able to resolve the issue by 
a. adding `listen_addresses = '*'` in the postgresql.conf file
b. adding `host all all 0.0.0.0/0 md5` in the pg_hba.conf file
c. running the following command:
`docker stop nocodb-postgres && 
docker rm nocodb-postgres && 
docker run -d --add-host=host.docker.internal:172.17.0.1 --name nocodb-postgres -v "$(pwd)"/nocodb:/usr/app/data/ -p 8080:8080 -e NC_DB="pg://host.docker.internal:5432?u=postgres&p=<<password>>&d=postgres" -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" --net=host nocodb/nocodb:latest `

This issue can be closed.
