### ISSUE TITLE
wrong nav drawer toggle button position after adjusting the nav drawer weight 

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#735]
**Steps To Reproduce**
1. Go to Project page - it looks fine - see the 1st screenshot
2. Hover the line and drag it to somewhere
3. the nav drawer toggle button remains the same position - See the 2nd screenshot

**Expected behavior**
The nav drawer toggle button should be moved along with the line

**Screenshots**

## Screenshot 1

![image](https://user-images.githubusercontent.com/35857179/139833840-27faf560-94d2-4314-adc6-8b99d76bca8f.png)

## Screenshot 2 

![image](https://user-images.githubusercontent.com/35857179/139833884-17e27579-e45d-414a-b742-e18abbe3ab9c.png)

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.81.1**

**Comment by o1lab** [comment]
@lielfr : could you pls help us on this.

**Comment by lielfr** [comment]
I'll take a look now. Apologies for the delay

**Comment by lielfr** [comment]
it seems it's already fixed.

**Comment by o1lab** [comment]
Fixed in 0.82
