### ISSUE TITLE
🐛 Bug: Rich text & long text modal UX

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7359]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Rich text
- [x] align it to the centre always with following configurations
width: 100%, max-width: 1280 px, min-margin (side): 320px
height: 100%, max-width: 864px, min-margin (top, bottom): 108px (edited) 
- [x] provide an option for manual expand / shrink at the right bottom, as its available for comment box on github
- [x] adding a lengthy text should not auto expand width of the modal

Long text
- [x] follow similar practice when using in-cell expand modal

- [x] For both rich text & long text : remove expand icon in link record modal. We can just have expand option for entire record.
- [x] For both, when row height is short : show only one complete line; no partial line display

### Desired Behaviour

x

### Project Details

203.2

**Comment by siwamsingh** [comment]
hey @dstala can you  provide a screenshot or a short video i identifying this problem
