### ISSUE TITLE
🐛 Bug: API V2 - when Page Size > Total Records returned, API response contains incorrect page size and isLastpage values

### ISSUE THREAD

**Issue by woodmin** [nocodb/nocodb#7368]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create 4 records.
Set offset to 2.
Set Page Size to 50.
Returns `page: 1.04` decimal (!?) and incorrect
Returns `isLastPage: false` incorrect

### Desired Behavior

Should return `page: 1` integer
Should return `isLastPage: true`

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.203.2**
Database version : **16.1**

### Attachments

![image](https://github.com/nocodb/nocodb/assets/65443816/0095e2ca-3cfa-4143-a1ef-a0544e345fc5)

**Comment by woodmin** [comment]
I have reported other API Error Message / Status mismatches before. Could it be also checked along if any more errors (messages) are not set to be returned with 200 status? For example: Invalid URL Format, Missing Required Parameters, Request Size Too Large, etc.?

**Comment by dstala** [comment]
`isLastPage` always returns false if offset is set. fix for `page` to be discussed

**Comment by woodmin** [comment]
1. I think there is some misunderstanding regarding `isLastPage` - it is not always returning `false` if offset is set. It only returns `false ` if the page is not the last, and it **does** return `true` on the last page. This is the whole point of `isLastPage` and we are using it to stop turning pages at the end of the results. Offset is always used (`offset = n x limit`) for every page except the first one. Please see screenshot below.
So to summarize: in normal circumstances `isLastPage` works as it should, and returns `true` for the last page with the last page `offset` value. 
![image](https://github.com/nocodb/nocodb/assets/65443816/8fcb1234-c51e-463a-8251-b6dd00a1c14d)

2. The problem reported here is that it does not work as expected for the last page ONLY WHEN when Page Size (`limit`) > Total Records (`totalRows`) returned. This does not happen in regular pagination situations, but when some offset is applied from the get-go. We encountered it when we wanted to retrieve the last record in the table. So having n records in the table we applied n-1 offset to retrieve that last record. However, since our Page Size (`limit`) was > Total Records (`totalRows`), `isLastPage` incorrectly returned `false ` although it should have worked wirth any Page Size (`limit`).

Hope it clarifies it.

**Comment by wrb2012** [comment]
I think I still encounter this isLastPage always false issue in 0.263.8
