### ISSUE TITLE
Unknown Table List Ordering

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#737]
**Steps To Reproduce**
1. Go to Project
2. Create N tables
3. Randomly update the tables
4. Right click ``Table`` and click ``Table Refresh``
5. Repeat step 3 - 4. notice that the order of the table is changed 

**Expected behavior**
The table names should be listed alphabetically. Or there should be some options for users to select.

**Screenshots**
![image](https://user-images.githubusercontent.com/35857179/139913731-5af4b7e4-216e-43c5-a729-0c7f48585aa5.png)

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.81.1**

**Comment by pranavxc** [comment]
Implemented in `0.83.2`
