### ISSUE TITLE
🐛 Bug: Groupby doesn't work on formula fields with numbers

### ISSUE THREAD

**Issue by ItsABlackScreen** [nocodb/nocodb#7382]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create two fields with type number, a and b and populate with values
2. Create a third field with type formula, c, (formula is {b}-{a})
3. Select group by field c.
4. It shows the correct number of fields within count when collapsed, but on expanding it is a blank state and the count reduces to zero. 

### Desired Behavior

The goupby feature should work as it does with other fields.

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.203.2**

**Comment by dstala** [comment]
SQLite3 specific issue. Works fine in PG

**Comment by rameshmane7218** [comment]
GroupBy and Filter is not working if the formula field cell value is `numeric` in `SQLite3`
