### ISSUE TITLE
🐛 Bug: time format not matched in UI and API

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#7385]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

from a discord user

> I have a time field, the time in API is showing as “09:00:00” but inside nocodb it’s correct as “09:00”, how to hide milliseconds in the API output?

### Desired Behavior

HH:mm format in both UI and API response

### Project Details

latest

**Comment by dstala** [comment]
IMO, API response should always carry additional precision if we have it in the backend. This would also apply to precision for decimal, percent and such fields. Or even for currency where we display with UI friendly prefix or suffix, but in the backend - its essentially a number. 

Truncating additional information shouldn't be a problem once the data is received. 

@wingkwong what is the way out that you propose here?

**Comment by dstala** [comment]
Discussed with @wingkwong 
API response details for each field to be documented.
