### ISSUE TITLE
🐛 Bug: newest dev build 0.203.2-20240108-0603 not working

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#7387]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Start Docker -->

ERROR [ExceptionHandler] select * from "nc_sources_v2" where (("is_meta" = $1) or ("is_local" = $2)) - column "is_local" does not exist

is_local not existing in database, only is_meta is there

After adding is_local to db:

┌ Migration from 0111002 to 0111004 failed ────────────────────────────────────┐│ 
││ Error ││---- - 
││ TypeError: Cannot read properties of undefined(reading 'id')
││ at / usr / src / app / docker / main.js: 2: 1946267 
││ at process.processTicksAndRejections 
││(node: internal / process / task_queues: 95: 5)
││ at async Promise.all(index 8)
││ at async t.default[as handler](/usr/src / app / docker / main.js: 2: 1946100)
││ at async NcUpgrader.upgrade(/usr/src / app / docker / main.js: 2: 1911994)
││ at async InstanceWrapper.useFactory[as metatype]││(/usr/src / app / docker / main.js: 2: 1364964)
││ at async Injector.instantiateClass ││(/usr/src / app / node_modules /  @ nestjs / core / injector / injector.js: 369: 37)
││ at async callback ││(/usr/src / app / node_modules /  @ nestjs / core / injector / injector.js: 65: 34)
││ at async Injector.resolveConstructorParams 
││(/usr/src / app / node_modules /  @ nestjs / core / injector / injector.js: 144: 24)
││ at async Injector.loadInstance ││(/usr/src / app / node_modules /  @ nestjs / core / injector / injector.js: 70: 13)
││ Please raise an issue in our github by using following link: 
││ https: //github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&template=bug_report.md    ││                                                      │└──────────────────────────────────────────────────────────────────────────────┘

### Desired Behavior

should work

### Project Details

0.203.2-20240108-0603

**Comment by mertmit** [comment]
Hi @emre1e, please stick to last release for now. Our last upgrader in dev is still WIP.
We are planning to have a feature release soon 🙌🚀
