### ISSUE TITLE
Unknown Data button on nav bar

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#739]
**Steps To Reproduce**
1. Go to Project page
2. Hover on the title nav bar
3. Left click and right click repeatedly
4. A new button Data is shown
5. Click that button
6. It shows ``This page could not be found``

**Expected behavior**
No such easter egg I guess

**Screenshots**
![image](https://user-images.githubusercontent.com/35857179/140006229-414f725a-7f92-4ab2-a79a-c1df96e772bb.png)

![image](https://user-images.githubusercontent.com/35857179/140006236-a6460c58-e13b-4eba-927d-60b516f08bd1.png)

Node: v12.22.6
Arch: x64
Platform: linux
Docker: false
Database: pg
ProjectOnRootDB: false
RootDB: pg
PackageVersion: 0.81.1

**Comment by pranavxc** [comment]
Removed in latest version `0.83.1`
