### ISSUE TITLE
🐛 Bug: GUI does not save custom order of Table Views

### ISSUE THREAD

**Issue by woodmin** [nocodb/nocodb#7395]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a few views of the table.
Rearrange their order by dragging and dropping.
Refresh page.
View order set by Drag and drop will be ignored (not saved) and views will be ordered by creation date after refresh.

### Desired Behavior

When set by drag and drop, order of views should persist after refresh and across login sessions.

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.203.2**
Database version : **16.1**

**Comment by asasn** [comment]
I have the same problem. For now, it seems that the ability to manually adjust record order is not available.
Dragging in the Kanban view only adjusts the group left and right, up and down is meaningless.
In an excel like grid view, you can't drag.
I sincerely hope that such a feature can be added.

**Comment by woodmin** [comment]
Actually I interpreted it as a bug. Because feature to drag views around is clearly implemented. It can be dragged and stays there, unless page is refreshed. So it seems like it is a bug of memorising/retaining position of view in the list, not a new feature, since a feature itself (rearranging order of views by dragging) is already implemented.

**Comment by dstala** [comment]
@woodmin @asasn 
View order information will be user specific. We would be required to store additional meta in the backend for every table / user. We are aware of this issue & will discuss internally.
