### ISSUE TITLE
🔦 Feature: Bases search field or filter

### ISSUE THREAD

**Issue by divemasterza** [nocodb/nocodb#7417]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When using a large number of bases, it becomes difficult to locate the base you want to work on

### Suggested Solution

Ajax search field on top of the bases column to filter (or even sort) the bases 

### Additional Context

This will improve UX

**Comment by o1lab** [comment]
How many bases do you have @divemasterza ? 

In our cloud offering there CMD+K option to jump to any view instantly. And CMD+L to iterate over recent views if that helps.

**Comment by divemasterza** [comment]
@o1lab we have quite a few bases, and as superAdmin they are all listed... makes a long scroll-n-seek :)

(Using the Community Edition)

**Comment by o1lab** [comment]
That is so exciting to hear - a number would help to spread some joy for the community here :)

**Comment by divemasterza** [comment]
@o1lab we currently have about 35 bases with close to 100 tables. In the next month we are going to double this as we are importing from Airtable. (about 34 team users + a couple externals (clients) )

Storage is done via Backblaze, but Wasabi is far more affordable, so we going to mount a Wasabi drive for future storage.
