### ISSUE TITLE
🔦 Feature:  Allow  to @ or @@ other team members and show as notication or email.

### ISSUE THREAD

**Issue by cocoonkid** [nocodb/nocodb#7430]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

🔦 Feature:  Allow  to @ or @@ other team members and show as notication or email.

This makes it easy to notify team members of changes or where their input is needed.

This is a essential and expected feature in todays business software and would make a great addition to nocodbs feature set. 

### Suggested Solution

🔦 Feature:  Allow  to @ or @@ other team members and show as notication or email.

Add a small notification bell + history menu at the top left to the "Share" Button.

Allow to @@ other members of the base with a suggestions dropwdown fuzzy user search.

**Comment by dstala** [comment]
To be tracked along with [🔦 Feature: Mention team members in comments](https://github.com/nocodb/nocodb/issues/4257)
