### ISSUE TITLE
🐛 Bug: SUBSTR({Date Field}, idx, idx) not working anymore.

### ISSUE THREAD

**Issue by nil0x42** [nocodb/nocodb#7440]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Input SUBSTR({Date Field}, 0, 11) in any formula.

### Desired Behavior

Before the regression, the implicit cast did work correctly. From now, all my formulas using `substr(date...` don't work anymore.
This is related to issue: https://github.com/nocodb/nocodb/issues/4732 (which was closed, but apparently came back recently)

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.204.0**

### Attachments

![2024-01-16_13-15](https://github.com/nocodb/nocodb/assets/3504393/cc27d23a-de25-457c-beb0-0e415fc912ee)

**Comment by o1lab** [comment]
We are looking into it. Will have it fixed part of next release
