### ISSUE TITLE
🐛 Bug: UX/UI Bug cross-linked data not visible in cell

### ISSUE THREAD

**Issue by alfureu** [nocodb/nocodb#7442]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a cross-linked column from another table
2. Even if data is available, only a small (x) icon appears that the data is linked, however, the cells are empty
3. Tested in Firefox and Chrome, so I suppose it is not a browser rendering issue

### Desired Behavior

The cells should show the cross-linked data - always

On the attached screenshot one can see there is a little (x) highlighing an existing cross-link, but the cell is empty in any of the Record Height view

### Project Details

```
NocoDB used as docker: true
NocoDB version: 0.204.0
NC_DB URL: pg
```

### Attachments

![image](https://github.com/nocodb/nocodb/assets/10846169/8e20d959-ab93-45a4-960b-2748f34b6a5e)

**Comment by dstala** [comment]
- Is this a LTAR (Link To Another Record) column created using earlier versions of NocoDB?
- Can you try creating a new "Links" column & see if it works?

**Comment by alfureu** [comment]
Hi @dstala, to answer your questions:

1. yes, I run nocodb for quite some while, and never faced a similar issue before of 'seemingly' disappearing cells (I use the word seemingly, as the values upon inspection are there, just they do not render)
2. I verifies that the links do exist, they just do not render, no idea what is going on

**Comment by alfureu** [comment]
Oh, and btw creating another LTAR column is not really feasible, as these cross-links have been hand picked, so we would need to redo a huge table... 🙄

**Comment by dstala** [comment]
i tried migrating older version LTAR fields (from 109.3) to v0.204.0; migration went fine & i was able to see the link fields
- when you load page, do you see any errors on the console?
- what type of field have you set as display value?

**Comment by dstala** [comment]
@alfureu did you change display value field by any chance? we did notice an issue with it & it will be fixed soon

**Comment by alfureu** [comment]
> @alfureu did you change display value field by any chance? we did notice an issue with it & it will be fixed soon

Hm, not aware of any such a change. Apologies, did not have a chance to check for this error and show the logs, as I am travelling and away from the machine with the db. Will share the error, if any, as soon as possible

**Comment by dstala** [comment]
@alfureu please reopen this thread if issue still persists at your end
