### ISSUE TITLE
🐛 Bug: Record URL is broken

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7453]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Directly accessing record URL throws error

```
"TypeError: Cannot read properties of undefined (reading 'columns')"
```

### Desired Behavior

No error

### Project Details

0.204.0

**Comment by rameshmane7218** [comment]
Merged with PR #7855
