### ISSUE TITLE
create-nocodb-app fail when used from a path containing a space

### ISSUE THREAD

**Issue by fbossiaux** [nocodb/nocodb#747]
please provide the following details :
NocoDB used as docker : false
NocoDB version : 0.81.1
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created : sqlite3
OS on which NocoDB is running : macos 12.0.1
Node.js version if running as node : v14.17.1
Database version : NA

**Steps To Reproduce**
1. `cd` to folder with spaces in the path (ie: `/Users/flavien/Developer/My Repositories`)
2. Run `npx create-nocodb-app`
3. Answer questions (sqlite3, as Node.js Project)

And here it is:
```
Now, executing command : cd /Users/flavien/Developer/My Repositories/impressed_ferret

/bin/sh: line 0: cd: /Users/flavien/Developer/My: No such file or directory

Error running command internally
	"cd /Users/flavien/Developer/My Repositories/impressed_ferret"
Exiting...
```
**Expected behavior**
Take spaces in path into account, and don't throw error.

**Screenshots**
![image](https://user-images.githubusercontent.com/46444098/140413033-a1720e15-ab88-400f-83dd-14d1e013ecf7.png)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

Node version : **v14.17.1**
Arch type: **x64**
Platform: **macos**
Docker: **false**
Database: **sqlite3**
packageVersion: **0.81.1**

**Comment by pranavxc** [comment]
Fixed in latest `nc-cli` release
