### ISSUE TITLE
🐛 Bug:  Cannot use 'in' operator to search for  'id' in 1 error on insert

### ISSUE THREAD

**Issue by sph33r** [nocodb/nocodb#7470]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I'm seeing this pop up when entering data in grid view, via form, or via the API. Nothing will insert a new row in my base. I even tried creating a new base, same issue. I mainly use the api to insert data but if I'm using the web interface, I choose to use the form. Both are returning "Cannot use 'in' operator to search for 'id' in 1" when attempting to save/insert new data. At this point, I can't insert anything into any base. 

### Desired Behavior

The data will insert as expected. 

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.204.0**

### Attachments

<img width="1276" alt="nocodb_errors" src="https://github.com/nocodb/nocodb/assets/1290732/1d4f5f23-ad95-4005-bcfc-aa54ff2fb9cc">

**Comment by pranavxc** [comment]
We made a fix already and it will be part of the next release. Release delayed since we are planning to include few more minor bug fixes. 

You can check the following PR build until we make the release.

```
nocodb/nocodb-timely:0.204.0-pr-7432-20240115-1806
```


PR  - https://github.com/nocodb/nocodb/pull/7432

**Comment by nil0x42** [comment]
Hi ! I have the exact same issue, hopefully the PR will fix it.

**Comment by dstala** [comment]
@sph33r @nil0x42 Closing this thread. Reopen if issue still persists with latest release. Thanks!
