### ISSUE TITLE
🐛 Bug: cannot delete a row with a column of type link: "Failed to deleted record: the referenced record does not exist"

### ISSUE THREAD

**Issue by Sov3rain** [nocodb/nocodb#7480]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a row in a table to another row in any other table.
2. Try to delete the row.
3. You get the "Failed to deleted record: the referenced record does not exist".
4. Delete the linked record on the row.
5. Try to delete the row.
6. Works Fine

### Desired Behavior

Either you should show a more relevant error message, like "Cannot delete a row with linked records" or let the user delete a row that has linked records.

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.203.2**
hosting: **railway.app**

### Attachments

![image](https://github.com/nocodb/nocodb/assets/10755450/d5e61e23-c27b-467c-a040-4cf531880cab)
![image](https://github.com/nocodb/nocodb/assets/10755450/945eb6b0-7ebb-4138-b836-2ef2056ce9ea)

**Comment by DanielSolano1** [comment]
Hey just to update anyone interested on the issue I am trying to find a fix.

**Comment by DanielSolano1** [comment]
@Sov3rain Hello, I tried to reproduce the bug/issue you had with the steps provided, but was unable to have any luck, I couldn't get the error message to show up. Maybe there was a forgotten step on these instructions or a non standard environment was used? Would it be possible if you tried to recreate this error to see if the issue persists?

**Comment by Sov3rain** [comment]
Hey @DanielSolano1! Sure, I'll try to find something. Our environment is the following:
- Hosted on Railway.app using the community template
- 2 Postgres db : one for the noco metadata, one for the data itself

I'll try to export you the relation diagram if that can help with anything.

**Comment by Sov3rain** [comment]
Hey @DanielSolano1, I tried to reproduce the issue on 204.1, but it seems like its gone! Don't know if it was intentional but for now it works.

**Comment by DanielSolano1** [comment]
@Sov3rain Great!

**Comment by dstala** [comment]
Closing this issue for now- assuming it was fixed in one of our earlier releases. If issue persists, reopen this thread.

**Comment by dinesh-hills** [comment]
I would like to reopen this issue,

Steps to reproduce:
1. have sqlite/postgres as nocodb metadata db.
2. Connect to a main data source db as *Postgres* and (error happens only on this main connected data db not on metadata db).
3. Create two tables and create a linked column with "Has Many" relation type.
4. now create and add a new record/reference to the new created "Has Many" relation column.
5. now if you try to delete the column you could reproduce this error.

**Comment by dinesh-hills** [comment]
Here is a log of error raised when using "mysql" database as source.
```
Nest] 8  - 09/02/2024, 1:59:44 AM   ERROR [GlobalExceptionFilter] delete from `Table-2` where `id` = '1' - Cannot delete or update a parent row: a foreign key constraint fails (`dmb`.`Table-2`, CONSTRAINT `fk_Table_2_Table_2_gzvadppgfw` FOREIGN KEY (`Table-2_id`) REFERENCES `Table-2` (`id`))
Error: delete from `Table-2` where `id` = '1' - Cannot delete or update a parent row: a foreign key constraint fails (`dmb`.`Table-2`, CONSTRAINT `fk_Table_2_Table_2_gzvadppgfw` FOREIGN KEY (`Table-2_id`) REFERENCES `Table-2` (`id`))
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:738:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
```

**Comment by dinesh-hills** [comment]
On postgres a simple text is being loaded as following - `A valid integer must be provided to limit`.

**Comment by dinesh-hills** [comment]
I am using the latest version of nocodb. `v0.255.2`

**Comment by t0mdicks0n** [comment]
Any updates on this? I am having the issue when using NocoDB Cloud and are trying to delete a row with a field linked to another table. This is a very annoying issue for non-technical users.
