### ISSUE TITLE
🐛 Bug:   When searching for a non-existant entry it is fine on page 1 of tables but shows"internal  error" when doing the same in any other page number.

### ISSUE THREAD

**Issue by cocoonkid** [nocodb/nocodb#7501]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

🐛 Bug:   When searching for a non-existant entry it is fine on page 1  but shows"internal  error" when doing the same in any other page number.

1. Create 30 entries.   
2. Got to page 2 which now shows 5 entries. 
3. Search for non-existant entry.
4.  See internal error happen.

### Desired Behavior

It should just show no result or the result as applicable like it does on page 1

### Project Details

Nocodb latest with docker. postgres.

### Attachments

![image](https://github.com/nocodb/nocodb/assets/43231640/90d09b5e-e34f-4f43-acc7-ac7d53a2ce4a)

Nothing in the logs about the problem.

**Comment by dstala** [comment]
I see a different error (in staging)
`Offset is beyond total number of records`

**Comment by cocoonkid** [comment]
Can I help further ?
Maybe the debug messages are a little more intentionally "unclear" in prod?

**Comment by mogsub** [comment]
it also happens when you search for an existant record that exists on the first page but you are searching for it while on the second page
