### ISSUE TITLE
🐛 Bug: file attachment didnt attached while sending it with a form

### ISSUE THREAD

**Issue by Valeronich** [nocodb/nocodb#7507]
### Please confirm if bug report does NOT exists already ?

- [x] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create table with "attachment" field
2. Create form with "attachment" field
3. Try to fill form and upload any file in that field
4. Check uploaded file in previously created table

### Desired Behavior

Files are successfully uploaded to the nocodb when it uploads with Forms

### Project Details

self-hosting: true
Platform: Linux Ubuntu
Arch: x64
Docker: true
RootDB: pg
PackageVersion: 0.204.0

**Comment by dstala** [comment]
tried uploading a pdf file from a form view in pg/0.204.0/docker, worked fine.
@Valeronich 
- which browser are you using? if its not chrome, can you try it out in chrome once?
- what was the file type that you were attaching?
- what was the file size?
- did you notice any error on the UI or on the console?
- do you see rest of the fields in the form submitted to the grid & only attachment missing?

**Comment by Valeronich** [comment]
1. Browser: Arc (Chromium)
2. File type: jpeg\png
3. Less than 5 mb
4. Didnt notice any errors. Even in log files
5. Yes, other fields is successfully submitted and loaded properly

**Comment by dawidszpilewski** [comment]
There must be a difference between uploading attachments via grid and VIA form. I have desceibed it in #5886. Unfortunately that Idzie has been closed but not resolved. I kindly ask to re-open #5886 because I don't see that option.

**Comment by dstala** [comment]
@dawidszpilewski 
I tried it on Arc browser today & was able to upload attachments from shared form view. 

Arc browser version - Version 1.29.0 (46113)
Tried both drag drop & click upload method for attaching a file; file type uploaded .png & .jpeg

upgrade your Arc browser if you haven't and give it another try.
I tried this on mac; let me know if you are on a different OS?
Root DB in my case was PG

If you can upload a video of this behaviour (if still reproducable), it would help

**Comment by dstala** [comment]
if issue still persists, reopen this thread
