### ISSUE TITLE
🔦 Feature: Keyboard interactions on tables: new rows

### ISSUE THREAD

**Issue by BVengo** [nocodb/nocodb#7519]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Hitting tab on the last column of the last record in a table should add a new row. Alternatively (or additionally) hitting the down arrow. This is just a QoL feature, but feels critical when entering many rows.

### Suggested Solution

Hitting tab on the last column of the last record in a table should add a new row. Alternatively (or additionally) hitting the down arrow.

If this is a table spanning multiple pages, this behaviour should only apply on the last table. On other pages, hitting down/tab should navigate to the next page (i.e. prioritise navigation over adding rows).

### Additional Context

As a primary keyboard user and frequent user of AirTable (among other tabular software), I'm noticing many lacking features for keyboard navigation. Perhaps I'm just unaware of the hotkeys, but I'd hope they're intuitive enough for migrating users to use them naturally without needing to look them up!

**Comment by rameshmane7218** [comment]
@BVengo Holding down `Tab` or `ArrowDown` for a while results in adding multiple rows, so we are adjusting the keyboard listener from `keyDown` to `keyUp` to ensure that a new row is added only when `Tab` or `ArrowDown` is released after being pressed from the last row of the last page.
