### ISSUE TITLE
🐛 Bug: Tabbing in the 'Add New Link' page doesn't select the record components

### ISSUE THREAD

**Issue by BVengo** [nocodb/nocodb#7520]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When navigating via tab through the 'Add New Link' page, it goes from the `+ New Record` button up the top directly to the page navigation components down the bottom.

### Desired Behavior

The tab behaviour should iterate through the record components. Currently there is no way to add a linked record without swapping to the mouse and clicking on it (as far as I can tell).

### Project Details

Node: **v20.11.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **mysql2**
PackageVersion: **0.204.0**

**Comment by dstala** [comment]
@BVengo Let us know if below proposal looks good
- select first record by default
- use up & down arrow to move between records
- use enter to link / unlink

**Comment by BVengo** [comment]
That sounds perfect (assuming I understand correctly). Adding a couple things to clarify further:

1. Search selected by default
2. Tab behaves as it already does but includes the records container (not contents) where the first is selected by default
3. Up/down to navigate through the container itself. Tabbing skips past it.
