### ISSUE TITLE
🔦 Feature: Visual indicator on rich text fields that aren't fully displayed

### ISSUE THREAD

**Issue by BVengo** [nocodb/nocodb#7521]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have a table with short record height since it needs to be navigated through quickly. It has a few long-text columns that contain some multi-line information, which isn't fully displayed.

Adding a visual indicator for undisplayed information would make it clear that there is more to the record than is displayed on the screen.

### Suggested Solution

Add a gray '...' right aligned in the field if all the text can't be displayed. This could be due to the column not being wide enough, or because it's a multi-line long text without enough vertical space.

**Comment by dstala** [comment]
is done for long text. needs to be done for `rich text`

**Comment by rameshmane7218** [comment]
> is done for long text. needs to be done for `rich text`

Okay
