### ISSUE TITLE
🐛 Bug: webhook body tab absent

### ISSUE THREAD

**Issue by Jhon-Mosk** [nocodb/nocodb#7525]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. open the desired table
2. go to the tab "Details"
3. go to the tab "Webhooks"
4. push the button "New webhook"
5. we don't find the tab "Body"

### Desired Behavior

In the first version of webhooks, it was possible to customize the sent body. I would like to be able to do this in the second version.  
In [documentation](https://docs.nocodb.com/automation/webhook/create-webhook) in the screenshot there is a tab for setting up the body.
![image](https://github.com/nocodb/nocodb/assets/40711760/94ac0643-6d95-461d-a7f3-442a1feb5825)
But I don't have it
![image](https://github.com/nocodb/nocodb/assets/40711760/01721e98-377b-4675-acbd-e3b3d5e110df)

### Project Details

Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.204.0**

**Comment by dstala** [comment]
@Jhon-Mosk support for customisable webhook body has been deprecated.

**Comment by Jhon-Mosk** [comment]
@dstala And in the API, I hope they are not going to remove methods for working with webhooks?

**Comment by dstala** [comment]
No change in API behaviour. If you notice any issue, reopen this thread.
