### ISSUE TITLE
🐛 Bug: Base page doesn't show table icons

### ISSUE THREAD

**Issue by BVengo** [nocodb/nocodb#7533]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a base with a few tables.
- Give them icons in the left panel.
- Click on the base to go to the base page (the one with the 'New Table', 'Import Data', 'Connect a Data Source' buttons).
- Note that the listed tables do not have icons, despite displaying in the left panel.

### Desired Behavior

Tables in the base page show their correctly allocated icons.

### Project Details

Node: **v20.11.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **mysql2**
PackageVersion: **0.204.0**

**Comment by rameshmane7218** [comment]
We made a fix already and it will be part of the next release. 

You can check the following PR build until we make the release.

```
nocodb/nocodb-timely:0.204.0-pr-7424-20240116-1205
```
PR - https://github.com/nocodb/nocodb/pull/7424

OR latest
```
nocodb/nocodb:latest
```

**Comment by BVengo** [comment]
Ah awesome, thanks!
