### ISSUE TITLE
🐛 Bug: Unique value constraint in field is ignored

### ISSUE THREAD

**Issue by akrea** [nocodb/nocodb#7541]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- create new field
- set "UN" option
- create first entry
- create second entry with identical content

### Desired Behavior

reject entries that are identical in this field

### Project Details

nocodb dockerized: true
nocodb version: 0.204
database for data: timescale
nocodb database: default
tables were created by nocodb

### Attachments

![image](https://github.com/nocodb/nocodb/assets/16197061/9f82e363-e07c-4f83-9425-e38a46ca047d)
![image](https://github.com/nocodb/nocodb/assets/16197061/1613456d-fafd-44ee-b79c-323abee78ce6)

**Comment by lupa18** [comment]
Hi ! any update on this?

thanks in advance !

**Comment by salim-b** [comment]
> set "UN" option

@akrea The `UN` attribute does not stand for *unique* but [***unsigned***[(https://docs.nocodb.com/fields/field-types/custom-types/specific-db-type/#advanced-field-attributes), i.e. it

> Ensures that a column can only store non-negative numbers, commonly used for counters, identifiers, or monetary values.

**Comment by lupa18** [comment]
Hi @salim-b and is there some "unique" flag to check?

**Comment by akrea** [comment]
I see. In that case chatgpt is making up stuff. I did not check the official documentation for this specific question. 

This still begs the question why you can select this option when the data type is non-numeric...?

![Screenshot_20240629-065050.png](https://github.com/nocodb/nocodb/assets/16197061/64d03fda-60eb-45c3-96bf-f9aac716e66f)

**Comment by salim-b** [comment]
> is there some "unique" flag to check?

I don't think so. But you could add the `UNIQUE` constraint on the DB level, see e.g. [here](https://stackoverflow.com/questions/1194438/can-i-add-a-unique-constraint-to-a-postgresql-table-after-its-already-created) for PostgreSQL, or if you're relying on NocoDB's default SQLite DB to store data, [`CREATE UNIQUE INDEX`](https://www.sqlite.org/lang_createindex.html) should do.

**Comment by akrea** [comment]
Thanks by now i realized that. I am picky here, but in that case wouldn't it make more sense for this option only to show up if the data type is an integer?
