### ISSUE TITLE
🐛 Bug: CSV Import fails in localhost

### ISSUE THREAD

**Issue by DarkPhoenix2704** [nocodb/nocodb#7544]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Run nocodb locally. 
Try to import a csv

### Desired Behavior

Should Import successfully

### Project Details

.

### Attachments

![image](https://github.com/nocodb/nocodb/assets/64391274/e642c4ee-9b05-4f66-a0a7-a2b6d86e16a4)

Breaks in the else statement of workerUtils.ts
![image](https://github.com/nocodb/nocodb/assets/64391274/90be930e-8b4e-4baf-8f85-19328b437945)

**Comment by dstala** [comment]
[🐛 Bug: CSV import fails locally in DEV environment](https://github.com/nocodb/nocohub/issues/2271)

**Comment by ZoeLeee** [comment]
https://github.com/nocodb/nocodb/issues/8018

The issue still remains
