### ISSUE TITLE
🐛 Bug: After insert webhook triggering when clicking add row

### ISSUE THREAD

**Issue by AlexHladin** [nocodb/nocodb#7545]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a table
2. Create  `After insert` webhook
3. Click `add row` in the table

### Desired Behavior

It should trigger after a new row is submitted.

### Project Details

nocodb dockerized: true
nocodb version: latest github version
database for data: postgresql
tables were created by nocodb

### Attachments

https://github.com/nocodb/nocodb/assets/7945837/562fe60c-9fcb-4f3c-8025-18f080c67872

**Comment by dstala** [comment]
@AlexHladin You still see this issue with v0.204.9 release?

**Comment by AlexHladin** [comment]
@dstala yes, now it works as expected.
