### ISSUE TITLE
🔦 Feature: Locked Galleries should only be locked granularly

### ISSUE THREAD

**Issue by ScriptJunky** [nocodb/nocodb#7547]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In a locked gallery, a viewer can only see what is checked in card details for every object. Clicking on an object does not open the object and expose more info about it.

### Suggested Solution

What should happen when a user clicks on an object, is that a exploded view is opened, showing the rest of the un-hidden fields. As part of this, they should get the expanded images view like an editor has, so that they can see full size versions of the pictures attached.

**Comment by dstala** [comment]
Supported this way in v0.204.9; viewer could expand record, view hidden fields & expand attachments in gallery view.

Reopen this thread if issue persists on your end.
