### ISSUE TITLE
Incorrect offset in pagination when increased number of shown records

### ISSUE THREAD

**Issue by nickneustroev** [nocodb/nocodb#755]
I successfully increased number of records shown in tables via changing DB_QUERY_LIMIT_MIN, but pagination still using offset equal 25.

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.81.1**

**Steps To Reproduce**
1. Create new project via Heroku, internal DB, new table
2. Create 200 records
3. In Config Vars add DB_QUERY_LIMIT_MIN = 100
4. See first 100 records on the first page of pagination
5. But also, see many other pages in pagination. Second page shows records from 26 to 126. Third page shows records from 51 to 151, etc. 

**Expected behavior**
In this example would be 2 pages in pagination. Second page shows records from 101 to 200.

**Comment by pranavxc** [comment]
Fixed in `0.83.0`
