### ISSUE TITLE
🐛 Bug: copy paste on dateTime field with formatting applied

### ISSUE THREAD

**Issue by rameshmane7218** [nocodb/nocodb#7557]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Set `date format` option in dateTime field as `DD-MM-YYYY`
- Change the date in cell
- Copy the date and paste in another cell, it will create pasted cell value insted of replace
- Paste the copied date in outside cell e.g: console or in text file: the copied data is `empty` 

### Desired Behavior

Take formatting specified into account during copy paste

### Project Details

204.3

**Comment by dstala** [comment]
Related https://github.com/nocodb/nocodb/issues/7552
