### ISSUE TITLE
Table Many to Many Lookup

### ISSUE THREAD

**Issue by TonioLavega** [nocodb/nocodb#757]
NocoDB used as docker : true 
NocoDB version : 0.81.1
Database used in NC_DB URL  : pg 
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Linux
Node.js version if running as node :  v12.22.6
Database version : 

**Steps To Reproduce**
1. Go to on a table, add field and create "LinkToAnotherRecord" / "Many To Many" with another table.
2. On Metadata add the new relation table "m2mTable1_Table2" in the global view
2. On this new table, add field " Lookup",  child table "Table1" child column "TitleX"
3. See error : No data appears in this new column.

**Expected behavior**
See the field in relation with the ID on child Table. Not only the 2 Foreign Key, it will be better to indicate the title or another field.

**Screenshots**
![20211109Capture](https://user-images.githubusercontent.com/93984831/140919396-30413d9f-1c9b-4c4a-9357-32eb6f640ef3.JPG)

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.81.1**

**Comment by dstala** [comment]
works fine in v0.202.5; @TonioLavega if issue still persists in latest release, please reopen this thread.

we wouldn't recommend modifying schema for junction table.
