### ISSUE TITLE
CSV export of jsonb column does not work

### ISSUE THREAD

**Issue by arrowcircle** [nocodb/nocodb#758]
**Please enter the following details**

Copy and paste project info : [Youtube Video](https://www.youtube.com/watch?v=AUSNN-RCwhE)

or 

please provide the following details :
NocoDB used as docker : true
NocoDB version : 0.81.1
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Ubuntu
Node.js version if running as node : as in docker
Database version : 14.0

**Steps To Reproduce**
1. Create table with jsonb field, fill few values with this field
2. Click on export to CSV
3. instead of json field you will see `[object Object]`

**Expected behavior**
jsonb field should be exported properly

**Comment by pranavxc** [comment]
Set the column type as `JSON` and test CSV export, which may sort out the problem.

**Comment by pranavxc** [comment]
Fixed in `v0.83.0`
