### ISSUE TITLE
🐛 Bug: MySQL Server Created-at, Updated-at issue

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7585]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

https://discord.com/channels/661905455894888490/661905455894888493/1205267802106241044

Hello everybody... I have a MySQL server that works well in a BASE that I created some time ago... I don't know if it has to do with the latest update, but today I tried to create another BASE with another table on the same MySQL and I get this error.

The error happens when I try to add a new row... and it actually blocked people from submitting a form...
insert into `Table-1` (`created_at`, `created_by`, `updated_at`, `updated_by`) values ('2024-02-08 21:39:23+00:00', 'XXXdeletedXXX', NULL, NULL) - Incorrect datetime value: '2024-02-08 21:39:23+00:00' for column `test_noco`.`Table-1`.`created_at` at row 1

Anybody knows what it is? I have the feeling it has to do with the new feature Introducing "Created At" and "Last Modified At" Fields!

### Desired Behavior

no error

### Project Details

0.204.0

**Comment by pirachute** [comment]
Thanks dstala for creating the issue here... =)

**Comment by pirachute** [comment]
I reinstalled from 0, remade my admin account and reconnected to the DB and now it works fine... So I confirm, the update made some mess there...

**Comment by njinco** [comment]
also having the same issue glad someone opened a ticket here. Since i installed on a docker. i am thinking of downgrading to a docker version on nocodb before they introduced the new feature? (created at)

**Comment by pirachute** [comment]
> also having the same issue glad someone opened a ticket here. Since i installed on a docker. i am thinking of downgrading to a docker version on nocodb before they introduced the new feature? (created at)

I didn't find a real solution for this, but by accident my nocodb docker installation got reset... I reconnected the database (external MariaDB) and everything worked fine...

So it doesn't seem to be a DB problem.

I'd suggest trying to disconnect and reconnect the database, if possible, and see what happens...

**Comment by mertmit** [comment]
This issue should be resolved with our latest release, feel free to raise another issue or comment if you are still having issues https://github.com/nocodb/nocodb/releases/tag/0.204.1
