### ISSUE TITLE
🐛 Bug: CmdL UI/UX changes

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7592]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] fixed width for displaying information on the right side info
- [x] show both base & table name
- [x] discuss if its possible to change default view name to table name - pros & cons? how to handle rename table behaviour?
- [x] grey color’d base icon. it is getting highlighted a lot on the modal
- [x] font size for right side base (+table name) display can be reduced
- [x] keyboard navigation for listed recent view items using both CmdL & arrow keys

### Desired Behavior

x

### Project Details

Develop

**Comment by WarWolf47** [comment]
https://www.figma.com/file/qoq8iYlwAmZ0Q5jft7OmLe/Cmd%2BK?type=design&node-id=292-12160&mode=design&t=ipdomx06QpQMpMT1-4
