### ISSUE TITLE
🔦 Feature: Comment removal

### ISSUE THREAD

**Issue by mathyvds** [nocodb/nocodb#7600]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

At the moment I don't think it's possible to remove comments, is that right? Only editing.

### Suggested Solution

An option to remove comments

**Comment by salim-b** [comment]
Related to https://github.com/nocodb/nocodb/issues/4256.

**Comment by DarkPhoenix2704** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/8564
