### ISSUE TITLE
🐛 Bug: Failed to group by related Formula field.

### ISSUE THREAD

**Issue by malbruk** [nocodb/nocodb#7654]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have 'Groups' table with Formula as the display field (the formula concats some other fields). Also I have 'Users' table with relationship of one-to-many with 'Groups' (every user has one group). I try to group users by 'Group' field (related to 'Groups' table), but it failed. no data is displayed.

### Desired Behavior

It should be grouped by the Formula field as well.

### Project Details

Node: **v20.9.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.204.0**

**Comment by dstala** [comment]
@malbruk I tried the said case on v0.204.0 (SQLite as rootDB). Group-by worked just fine. Can you help us with more details on this? If you can add some screenshots & error logs (if any), or a video of the issue that you see, it will help us narrow it down.

**Comment by dstala** [comment]
@malbruk reopen this thread if you are still facing this issue.
