### ISSUE TITLE
🐛 Bug: Unable to render this definition. The provided definition does not specify a valid version field. <Swagger API UI>

### ISSUE THREAD

**Issue by toduyemi** [nocodb/nocodb#7657]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Steps to reproduce ?

-Login with super admin credentials
-right click base in sidebar
-click swagger
-click rest APIS

### Desired Behavior

Swagger page for API

### Project Details

Node: **v18.14.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.204.0**

### Attachments

<img width="886" alt="Screenshot 2024-02-19 at 8 46 19 PM" src="https://github.com/nocodb/nocodb/assets/63010977/45cfd9e5-9892-49c9-b158-3dd5ef295cca">

network browser response:
<img width="968" alt="Screenshot 2024-02-19 at 8 46 58 PM" src="https://github.com/nocodb/nocodb/assets/63010977/ad540147-bda6-4515-837a-91e0ecd23474">

back-end server log:
<img width="1252" alt="Screenshot 2024-02-19 at 8 47 20 PM" src="https://github.com/nocodb/nocodb/assets/63010977/b67074f4-61e2-442a-b92e-ea80f8d3fdf9">

**Comment by mustafa-hanif** [comment]
I am also facing this

**Comment by gitcob** [comment]
Same here

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.204.5**

Oddly enough, when I tried again a few times it randomly worked.

**Comment by pranavxc** [comment]
It expects token in localstorage, so do the following:

- Visit `http://localhost:8080`
- Login with your credential
- Now go back to the swagger URL
