### ISSUE TITLE
Blank page after filtering; need to click page in pagination to see results

### ISSUE THREAD

**Issue by nickneustroev** [nocodb/nocodb#766]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.81.1**

**Steps To Reproduce**
1. Create table with more than 25 records. For example, 30. Therefore, pagination shows with page 1 and 2.
2. Go to the last (second) page
3. Create new filter, that must show less records, for example 20. So pagination show only 1 page
4. We see blank page. To see the filtered records, we need manually click the page 1 in the pagination.

**Expected behavior**
If filtering changing the number of pages, then we should be automatically directed to the page with records

**Comment by pranavxc** [comment]
Fixed in `v0.83.0`
