### ISSUE TITLE
🔦 Feature: Field Descriptions / Help text

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#7665]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Adding additional information to help users understand the function of a field.

### Suggested Solution

Airtable example:

![image](https://github.com/nocodb/nocodb/assets/55474996/28451c44-2065-4bfd-812a-e3a225fc73e1)

On hover:

![image](https://github.com/nocodb/nocodb/assets/55474996/b948a0f0-51e6-4eb2-8646-19dce6d68eb8)

**Comment by salim-b** [comment]
As I already mentioned in https://github.com/nocodb/nocodb/issues/3571, for tables from external SQL data sources, it would be great if you could just read the data for such "column descriptions" from the SQL `COMMENT`s that are set on the table's columns (if any).

Ideally, you would interpret the `COMMENT`s the same way that [PostgREST does](https://postgrest.org/en/v12/references/api/openapi.html):

- If the comment is a single line, treat it as a *column description*.
- If the comment consists of multiple lines, treat the first paragraph as *column summary* (= human-friendly column title) and the second paragraph as *column description*.

**Comment by springfielddatarecovery** [comment]
+1 for this feature

**Comment by dstala** [comment]
will be available from next release
