### ISSUE TITLE
🐛 Bug: Form field order is different in backend than in the public view

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#7671]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create columns/fields to populate a form, re-arrange them:

![image](https://github.com/nocodb/nocodb/assets/55474996/d6651724-2708-47b5-80fd-778ec3cd4165)

![image](https://github.com/nocodb/nocodb/assets/55474996/3ca33a7f-ebd7-44d3-8900-36fe5386946b)

2. Create a public view link

3. Order of fields in the public form doesn't correspond to order in NocoDB:

![image](https://github.com/nocodb/nocodb/assets/55474996/78092e65-1cf5-49cc-ac99-9485bb616bd7)

### Desired Behavior

Order of fields in app should be reflected in the public form.

### Project Details

NocoDB hosted, Firefox browser

**Comment by dstala** [comment]
@candideu Order of the fields doesn't reflect even after a page reload? I tried it out in both chrome & firefox with a mix of long text & single line text fields; order was retained as it was in form designer. 
- you see any console errors?
- if you can share a video recording of the issue, that would help

**Comment by candideu** [comment]
@dstala Looks like it solved itself when I logged back in the following day and re-arranged some of the fields. Not sure what happened, so I'll close for now.
