### ISSUE TITLE
Rename a table which as a space - it leads to an error

### ISSUE THREAD

**Issue by eliasmistler** [nocodb/nocodb#768]
**Please enter the following details**

Node: **v12.22.6**
Arch: **arm64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.81.1**

(running the latest docker image)

**Steps To Reproduce**
1. Create a new table containing a space, e.g. `Test Space`
2. Try to rename the table
3. Error: `Table rename . failed`

**Expected behavior**
Table is renamed.

**Further issues**
Spaces in table names seem to be a wider issues, as NocoDB also failed to create a many-to-many relationship including a table with a space in the name.

**Comment by yuting1010** [comment]
Hey, could you elaborate on "NocoDB also failed to create a many-to-many relationship"? I am new to the community who wants to know more. Thank you very much!

**Comment by wingkwong** [comment]
Closing this issue as it has been handled in previous version. Now spaces are not allowed when creating / renaming a table. 

![image](https://user-images.githubusercontent.com/35857179/153343172-e5ed77a2-9f45-4eef-8043-88dae8352aa6.png)

![image](https://user-images.githubusercontent.com/35857179/153343194-b0be02e2-c17d-40c3-a403-4e50f8e001eb.png)
