### ISSUE TITLE
🐛 Bug: Duplicating a form view only adds fields; all other form and field configurations are missing.

### ISSUE THREAD

**Issue by rameshmane7218** [nocodb/nocodb#7686]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- 

### Desired Behavior

Duplicate form view should also add form and field configurations in duplicated form

### Project Details

-

**Comment by jdaviescoates** [comment]
I just spotted this too. Would be really nice if duplicating a form actually duplicated it.

**Comment by rameshmane7218** [comment]
Merged with PR #7717
