### ISSUE TITLE
🔦 Feature: Add to context menu, open in new tab

### ISSUE THREAD

**Issue by RichardUUU** [nocodb/nocodb#7693]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

When looking at a table, I'd like to be able to look at a different table, without losing my place in the current table.  

### Suggested Solution

Add to the table context menu "Open in new tab"

**Comment by rameshmane7218** [comment]
👋 Hi @RichardUUU , thanks for the suggestion! Instead of adding to the context menu, we can use the default behavior. Just press `Ctrl or Cmd` key and `click on the base/table/view`, and it will open in a new tab.
