### ISSUE TITLE
🐛 Bug: SingleLineText field silently drops part of text

### ISSUE THREAD

**Issue by opokhvalit** [nocodb/nocodb#7694]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

The SingleLineText field silently drops part of text over some limit. For my case it drops all text over 45 symbols without any warning. And, unfortunately, any limits are not described in the documentation.
Mysql8 is used as backend DB with utf8 encoding

For reproduce:
- create SingleTextLine field in the table
- fill it by some text with lench over 45 symbols
- save data
- refresh page

### Desired Behavior

1. describe SingleLineText size limits (if any) in the documentation
2. show error message, do not allow to save oversized text line

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.204.0**

**Comment by dstala** [comment]
@rohittp0 
- check the limit that we have in PG. if its easy to extend limit for single line text for mysql - let us do it. 
- and let us limit the input box after that many characters are filled in. user should not be able to add more & see that its dropped silently.
