### ISSUE TITLE
🔦 Feature: Attachment related enhancements

### ISSUE THREAD

**Issue by liuhaili** [nocodb/nocodb#7698]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

1.能否去掉这个附件列的文字提示？
![image](https://github.com/nocodb/nocodb/assets/4023364/9555e4ff-7e52-4ce1-98d5-1be1985c6525)
2.能否修改下面新增技能的默认模式，刷新又变回去了
![image](https://github.com/nocodb/nocodb/assets/4023364/83cf4a24-5203-4ca3-a158-728af92533c3)

### Suggested Solution

1.去掉文字提示，或者可以选择是否显示提示
2.可以选择新增记录的模式，就是设置里可以设置
3.附件图片最好可以浏览器剪切板复制、粘贴

**Comment by dstala** [comment]
Proposals

1. [Attachment field, default `Add file(s)` display on the grid] Remove the text prompt, or you can choose whether to display the prompt
2. [Toggling to Add new record via Form doesn't persist on page reload] You can choose the mode for adding new records, which can be set in the settings.
3. It is best to copy and paste the attached image from the browser clipboard

Copying image from browser clipboard is supported in cloud & will be rolled out to OSS in next release

**Comment by liuhaili** [comment]
我看到可以复制图片了，但是前两项还没有设置的地方

**Comment by liuhaili** [comment]
![image](https://github.com/nocodb/nocodb/assets/4023364/d7165a7e-3e24-42ca-93f7-c5f4f9159657)
因为这里的添加显得比较怪异。我的数据是排了序的，根据时间倒叙排列，如果这个添加在最上面还说的过去。当然这取决于排序

**Comment by dstala** [comment]
All features requested here are now supported
