### ISSUE TITLE
🐛 Bug: Submit attachment in form does not working

### ISSUE THREAD

**Issue by kdamsmt** [nocodb/nocodb#7699]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

The form view attachment does not show up image or content in table view when we allow user to attach the files.

### Desired Behavior

I like to allow user submit form and attach files than I can view in the table view like Images.

### Project Details

NocoDB cloud.

### Attachments

<img width="436" alt="image" src="https://github.com/nocodb/nocodb/assets/17005582/cf11bb09-8ead-4dc4-a0ce-6c1c8a814cf2">
You can see above the last row I directly attach image than it can show up but the the rows 1-3 that submit by form does not show any files.

**Comment by dstala** [comment]
@kdamsmt can you share your project information? or did you try it out on cloud technical preview?

**Comment by kdamsmt** [comment]
Hi @dstala 

PNG image - 100 KB 
1792 × 2284

**Comment by kdamsmt** [comment]
Just try to remove the current image (attachment) column and create new column with (attachment style) than it worked.
