### ISSUE TITLE
docker run with mysql error

### ISSUE THREAD

**Issue by 350050183** [nocodb/nocodb#771]
`docker run --name smy-table -d -p 8080:8080 -e NC_DB="mysql2://smy-mysql:3306?u=root&p=&d=" --link smy-mysql:smy-mysql nocodb/nocodb:latest`

Error: create database if not exists  - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by wingkwong** [comment]
You should specify the database name (after `&d=`).

For example:

`
docker run --name smy-table -d -p 8080:8080 -e NC_DB="mysql2://smy-mysql:3306?u=root&p=&d=meta" --link smy-mysql:smy-mysql nocodb/nocodb:latest`
