### ISSUE TITLE
🔦 Feature: Reset form in less than 5 seconds

### ISSUE THREAD

**Issue by RichardUUU** [nocodb/nocodb#7711]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently a form can be set to reset after five seconds. That's a bit long to wait if you're wanting to add things quickly. 

### Suggested Solution

Create an environment variable that lets us change the interval for resetting a form, Or make it an option on each form to set the reset time.

**Comment by dstala** [comment]
Another option is to enable `Submit another form` button. You will be able to initiate a new form immediately post form submission

**Comment by RichardUUU** [comment]
You're right. I think that's a good enough solution to close this issue.
