### ISSUE TITLE
🐛 Bug: Sometimes after editing a form view it randomly stops being viewable when visiting the public share link

### ISSUE THREAD

**Issue by jdaviescoates** [nocodb/nocodb#7714]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I've just spent ages trying to work out how to reproduce this, but failed.  But it's happened to me lots of times. I _think_ it could possibly maybe have something to do when duplicating and/ or deleting fields (just because in some cases I've also found it impossible to delete some fields, although of course that could easily be a totally different bug).

See this thread for a bit more info https://forum.cloudron.io/post/83861

### Desired Behavior

Forms should always be displayed when visiting their publicly available share link.

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.204.1**

Note: The title of this, the help text and YouTube video are completely out of date. The docs actually helped, but are also out of date because it's now "Copy Base Info". This should be renamed to Base Details and the help text needs editing because it's not the top left icon and the YouTube link should probably just be removed.

**Comment by dstala** [comment]
@jdaviescoates thanks for the detailed information here https://forum.cloudron.io/topic/11169/nocodb-is-an-awesome-app-to-make-forms-with/2?_=1711788101658&lang=en-GB

I could see that, the forms with issues are sorted out now. not sure if you ended up recreating or fixing them. can you let us know if you still face any issue with forms. if you do on the latest version of NocoDB - will get it fixed on priority. 

We have updated our docs & have revamped out form view. Expect new changes to be rolled out soon. You can try them out in our cloud technical preview though. We would love to get a feedback on the new form layout & anything that you think we can do better.

Apologies for delayed response on this thread.

**Comment by jdaviescoates** [comment]
Thanks, I think this issue must've been resolved by some of the updates that have happened in the interim as now all the form that weren't previously displaying when visiting their Share links do in fact display fine.

I'll report back if it happens again (or indeed if I hit other bugs too :) )
