### ISSUE TITLE
🔦 Feature: Set tab titles for forms and tables.

### ISSUE THREAD

**Issue by RichardUUU** [nocodb/nocodb#7719]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I often have a bunch of NocoDB tabs open for both forms and UI. There is no way to tell by looking at the tabs to know what they point to.

### Suggested Solution

For forms, allow users to set a title that would show in the browser tab.
For tables, allow users to set a title that would show in the browser tab.

**Comment by salim-b** [comment]
I second this.

But NocoDB should just default to using native object names in browser window titles, i.e. the **table name** plus optionally an existing SQL `COMMENT` on the table. So I'd suggest the resulting browser window title should by default look something like:

- `<TABLE name> – NocoDB`  for grid view
- `<TABLE name> – NocoDB (form view)` for form view

**Comment by o1lab** [comment]
Will be in next release!

**Comment by RichardUUU** [comment]
Glad to hear it's in the works. FWIW, salim-b's idea for a default is fine, but it doesn't eliminate the need for being able to override the default. Using his example, when tabs get narrow, or if the table name is long, `(form view)` would be truncated.

**Comment by o1lab** [comment]
Let's also include the emoji if it is set for table and views.
