### ISSUE TITLE
🐛 Bug: MAX() in formula did not get the desired result

### ISSUE THREAD

**Issue by asasn** [nocodb/nocodb#7720]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have multiple columns:
```
A: number
B: link to multiple lines，Field A
C: Lookup columnB
D: The formula takes the maximum value in C
```

### Desired Behavior

In my mind, I should get the **maximum value from column C** of the current record row
but，When I use MAX({C}) in D, it gets the max result of **"all the rows"**，In that case, the other lines disappear

### Project Details

versions 0.204.1

**Comment by dstala** [comment]
@asasn reopen this thread if you still see this happening. closing this for now.
