### ISSUE TITLE
Nocodb always open registration

### ISSUE THREAD

**Issue by sniffingsugar** [nocodb/nocodb#773]
NocoDB used as docker : true
NocoDB version : latest/0.81.1/ce40a5849fb4
Database used in NC_DB URL  :  sqlite3
OS on which NocoDB is running : alpine

Hey everyone,

NocoDB default has open registration enabled, in the Docs is no Option for disabling it. ?

Its a bit problematic if you want to expose NocoDB to the public.

**Comment by pranavxc** [comment]
You can disable it by adding the environment variable `NC_INVITE_ONLY_SIGNUP` value can be anything other than empty string. We will update it in documentation soon.
