### ISSUE TITLE
Where should I modify the sorting data query logic in order to customize the sorting functionality?

### ISSUE THREAD

**Issue by c2006878** [nocodb/nocodb#7737]
The current sorting in ascending and descending order only applies to English characters. If there are Chinese characters in the column, then the sorting becomes chaotic. Where should I modify the sorting data query logic in order to customize the sorting functionality?

**Comment by mertmit** [comment]
Hi @c2006878,
we are handling our sort logic inside **packages/nocodb/src/db/sortV2.ts**
please feel free to raise a PR with your fix we would love to support better sorting for Chinese
