### ISSUE TITLE
🐛 Bug:  Unable to add new record to linked table by "add new link"

### ISSUE THREAD

**Issue by geofflambeth** [nocodb/nocodb#7748]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- I'm using app.nocodb.com, haven't validated in a self-hosted installation
- Create two new tables within a single base
- Add a new field with
    - Type: "link"
    - Relation: either "many to many" or "has many"
    - Child table: whichever table not currently using
- On record, select open "linked records"
- Select "link records"
- select "new record"
- Attempt typing into any fields on the new record, **text appears in the previous "link records" window's search bar—not in the "new record" fields.**
    - I'm able to get data to populate there by right clicking to paste. Typing directly or using keyboard shortcuts is not working for me.

### Desired Behavior

Able to type directly into a new linked record's fields without a workaround.

### Project Details

NocoDB used in the app.nocodb.com site, not self-installed
Bases created within app.nocodb.com, not connected to an external data source

### Attachments

https://github.com/nocodb/nocodb/assets/66445285/a6dcccf9-af4f-47ea-b062-0cf9d153895d

**Comment by lcavasso** [comment]
Facing the same issue on a self-hosted install. This bug does not exist in 0.204.0.

Also, technically the issue is not with adding a new record (as stated in title), but with editing any data in a record accessed via a link.

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.204.1**

**Comment by dyltay** [comment]
I agree with what lcavasso says, editing or creating entries via a link results in typing through to the underlying page.

I was using the following when seeing this behavior:

Arch:  **Noco-win-x64.exe** 
Platform: **Windows**
Docker: **false**
RootDB: **sqlite3**
PackageVersion:  **0.204.1**
