### ISSUE TITLE
Nocodb mysql connection timeout

### ISSUE THREAD

**Issue by tenyo** [nocodb/nocodb#775]
We are running nocodb in a container, connecting to an AWS Serverless MySQL database.
The database automatically pauses after 10 minutes of inactivity and starts up when new connections come in. The problem is that it takes about 1 minute to start up, so that first connection needs to wait a long time.

When we restart the Nocodb container while the database is paused, the app fails to start with the following message:

```
  | 2021-11-15T14:39:34.396-05:00 | ║ EXCEPTION OCCURED!! in MysqlClient @ createDatabaseIfNotExists ║
  | 2021-11-15T14:39:34.396-05:00 | ║ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ║
  | 2021-11-15T14:39:34.396-05:00 | ║ MESSAGE: ║
  | 2021-11-15T14:39:34.396-05:00 | ║ connect ETIMEDOUT ║
  | 2021-11-15T14:39:34.396-05:00 | ║ ║
  | 2021-11-15T14:39:34.396-05:00 | ║ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ║
  | 2021-11-15T14:39:34.396-05:00 | ║ CODE: ║
  | 2021-11-15T14:39:34.396-05:00 | ║ ETIMEDOUT ║
  | 2021-11-15T14:39:34.396-05:00 | ║ ║
  | 2021-11-15T14:39:34.396-05:00 | ║ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ║
  | 2021-11-15T14:39:34.396-05:00 | ║ STACK: ║
  | 2021-11-15T14:39:34.396-05:00 | ║ Error: connect ETIMEDOUT ║
  | 2021-11-15T14:39:34.396-05:00 | ║ at Connection._handleTimeoutError (/usr/src/app/node_modules/mysql2/lib/connection.js:189:17) ║
  | 2021-11-15T14:39:34.396-05:00 | ║ at listOnTimeout (internal/timers.js:554:17) ║
  | 2021-11-15T14:39:34.396-05:00 | ║ at processTimers (internal/timers.js:497:7) ║
  | 2021-11-15T14:39:34.396-05:00 | ║ ║
  | 2021-11-15T14:39:34.396-05:00 | ║ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ║
  | 2021-11-15T14:39:34.396-05:00 | 
```

I'm assuming it just times out after 10s (or whatever the default connection timeout is), before the database has had a chance to start.

We've tried adding these two parameters to our `NC_DB` connection string, but it didn't make any difference:
`&connectTimeout=90000&acquireTimeout=90000`

Is there any way to increase that initial connection timeout, or make nocodb retry a few times?

**Comment by o1lab** [comment]
A retry mechanism is required here, what is serverless mysql service called in AWS ?

**Comment by o1lab** [comment]
Also give a try with ```connection.connectTimeout=90000&connection.acquireTimeout=90000```

**Comment by tenyo** [comment]
> A retry mechanism is required here, what is serverless mysql service called in AWS ?

It's AWS Aurora Serverless: https://aws.amazon.com/rds/aurora/serverless/

**Comment by dstala** [comment]
@tenyo reopen this issue if it still persists with v0.111.0
