### ISSUE TITLE
🐛 Bug: app.nocodb.com API limiting to 100 rows even when limit set higher

### ISSUE THREAD

**Issue by geofflambeth** [nocodb/nocodb#7761]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- authorize to api using access or API token
- ```GET``` request API records endpoint on a table with greater than 100 records 
     - example: https://app.nocodb.com/api/v2/tables/{table id}/records?limit=150&shuffle=0&offset=0
- check # of records returned or check ```pageInfo.pageSize``` in JSON response

### Desired Behavior

Should return up to the # of records set in the ```limit``` parameter sent with the request. Swagger documentation within the app says: "The limit parameter used for pagination, the response collection size depends on limit value with default value 25 and maximum value 1000, which can be overridden by environment variables DB_QUERY_LIMIT_DEFAULT and DB_QUERY_LIMIT_MAX respectively." Based on this, I would expect to be able to set the limit as high as 1000 as this isn't a self-hosted installation.

### Project Details

- app.nocodb.com production
- bases/tables built within nocodb, not linked to an external source

### Attachments

https://github.com/nocodb/nocodb/assets/66445285/51ef2a7e-cb4d-4433-9b68-5649aac88c7b

**Comment by dstala** [comment]
@geofflambeth On cloud, we had reduced the limit to 100. Will this be a blocker requirement for you?

**Comment by geofflambeth** [comment]
Good to know, thank you getting back quickly! It will create an issue with many of my current integrations with other tools, but if needed I can work on procuring infrastructure to self host for my organization. I'm currently using the cloud based app due to lack of infrastructure within my department, so it will be a blocker for a while until I can get organizational approval for a VPS.

**Comment by o1lab** [comment]
The max records that can be fetched in cloud will be 100. Will update the docs shortly. We've to unofortunately do this to stop abuse usecases.

**Comment by geofflambeth** [comment]
Great to hear! I can share the docs with my leadership and use it as fuel in an attempt to fast-track the approvals for infrastructure we truly need anyway... thanks!
