### ISSUE TITLE
🐛 Bug: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? After upgrade to 0.204.1 (and .2)

### ISSUE THREAD

**Issue by christophberger** [nocodb/nocodb#7770]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

> Note: This issue *may* be similar to #7263, but the NocoDB version and the stack trace are different. 

Start `nocodb` after upgrading to v0.204.1 or v0.204.2, respectively. 

Result: 

```
[Nest] 4869  - 03/01/2024, 11:18:50 AM   ERROR [ExceptionHandler] Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

Full output:

```
> nocodb
(node:4869) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `nocodb --trace-warnings ...` to show where the warning was created)
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1709288270211] Upgrading base Getting Started(pttzmb21egwz63x,btp3s1hihe3iz6i) (1/1)
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1709288330228] Upgrading model 'Features'(mkecf72talq0b0e) from base 'Getting Started'(pttzmb21egwz63x}) failed
┌ Migration from 0111002 to 0111005 failed ─────────────────────────────────────────────────────────┐│                                                                                                   ││   Error                                                                                           ││   -----                                                                                           ││   KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you      ││   missing a .transacting(trx) call?                                                               ││   at Client_SQLite3.acquireConnection                                                             ││   (/snapshot/pkg-executable/node_modules/knex/lib/client.js:312:26)                               ││   at async Runner.ensureConnection                                                                ││   (/snapshot/pkg-executable/node_modules/knex/lib/execution/runner.js:287:28)                     ││   at async Runner.run                                                                             ││   (/snapshot/pkg-executable/node_modules/knex/lib/execution/runner.js:30:19)                      ││   at async View.clearSingleQueryCache                                                             ││   (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1369270)                         ││   at async Column.update                                                                          ││   (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1261462)                         ││   at async /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1995281                  ││   at async Promise.all (index 0)                                                                  ││   at async /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1994625                  ││   at async /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1994480                  ││   at async i (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1892126)              ││                                                                                                   ││                                                                                                   ││   Please raise an issue in our github by using following link :                                   ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&template=bug_report.md         ││                                                                                                   ││   Or contact us in our Discord community by following link :                                      ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )                          ││                                                                                                   │└───────────────────────────────────────────────────────────────────────────────────────────────────┘
[Nest] 4869  - 03/01/2024, 11:18:50 AM     LOG [NestFactory] Starting Nest application...
[Nest] 4869  - 03/01/2024, 11:18:50 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +2ms
[Nest] 4869  - 03/01/2024, 11:18:50 AM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 4869  - 03/01/2024, 11:18:50 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 4869  - 03/01/2024, 11:18:50 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 4869  - 03/01/2024, 11:18:50 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 4869  - 03/01/2024, 11:18:50 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 4869  - 03/01/2024, 11:18:50 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 4869  - 03/01/2024, 11:18:50 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
[Nest] 4869  - 03/01/2024, 11:18:50 AM   ERROR [ExceptionHandler] Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/snapshot/pkg-executable/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/snapshot/pkg-executable/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/snapshot/pkg-executable/node_modules/knex/lib/execution/runner.js:30:19)
    at async View.clearSingleQueryCache (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1369270)
    at async Column.update (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1261462)
    at async /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1995281
    at async Promise.all (index 0)
    at async /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1994625
    at async /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1994480
    at async i (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1892126)
```

### Desired Behavior

`nocodb` should start the server.

### Project Details

NocoDB used as docker : false
NocoDB version : 0.204.1 and 0.204.2
Database used in NC_DB URL : SQLite
Project was created by clicking : New Project by connecting to external database
Database on which spreadsheet is created : SQLite
OS on which NocoDB is running : macOS
Node.js version if running as node : v21.6.2
Database version : n/a

**Comment by pranavxc** [comment]
We made a fix in following PR #7777. Could you kindly verify it by using following PR docker build. 

```
nocodb/nocodb-timely:0.204.2-pr-7777-20240302-0712
```

**Comment by christophberger** [comment]
That was quick! 
I'll test it when I'm at my desk

**Comment by christophberger** [comment]
It works! The error is gone, and I can start NocoDB. 

For some reason, I didn't get my config back. I guess this is because I test with Docker but my previously working setup does not use Docker. I mapped the directory containing my noco.db to /usr/app/data in Docker but to no avail.

At least, the error is gone.

**Comment by christophberger** [comment]
Update for whom it may concern: The latest version 0.204.4 starts fine outside docker (that is, with my standard setup). The error is gone.

However, the config remains lost.

I therefore conclude that the upgrade process has erased all my config (views etc) from NocoDB's meta database.

**Comment by o1lab** [comment]
hey @christophberger : had you set NC_DB variable and if not had you mounted the volume ? before and after this process.

If not, the metadata was stored in SQLite and is no longer present. Hope that clarifies.

**Comment by christophberger** [comment]
@o1lab Thanks for the reply. 
No, NC_DB is not set.
I put noco.db and my data DB into one directory and mounted it to /usr/app/data. NocoDB can access the data DB, hence I assume it also can (and does) access noco.db. 

> If not, the metadata was stored in SQLite and is no longer present.

Not sure if I understand. Why is it no longer present?

**Comment by o1lab** [comment]
Ok, thanks for the reply. We would like to debug on what is happening here.

@pranavxc will come back on this as he has more context (he is off sick today).

**Comment by pranavxc** [comment]
@christophberger If possible can you share the docker command or docker-compose with the volume mounting arg to confirm ?

**Comment by christophberger** [comment]
@pranavxc Sure:

```sh
nerdctl run -d --name newsdb \
  -v /<long_path_omitted>/newsdb/:/usr/app/data/ \
   -p 4040:8080 \
   nocodb/nocodb:latest
```

`noco.db` and the data DB are both in the `/.../newsdb` directory.

**Comment by pranavxc** [comment]
> @pranavxc Sure:
> 
> ```shell
> nerdctl run -d --name newsdb \
>   -v /<long_path_omitted>/newsdb/:/usr/app/data/ \
>    -p 4040:8080 \
>    nocodb/nocodb:latest
> ```
> 
> `noco.db` and the data DB are both in the `/.../newsdb` directory.

Are you connecting sqlite as external source as well ?

**Comment by christophberger** [comment]
Yes, I connect a sqlite DB as external source.

**Comment by pranavxc** [comment]
- If the `NC_DB` environment variable is not defined, we search for the `noco.db` file in the application's working directory, which is `/usr/app/data`. If the file is missing, we will create it. 
- If you have a base and an additional SQLite source added to the same base, then we look for the file based on the path saved in the connection configuration.


And in your case all the bases, users, table, views,… are  missing or just the data from these views? If possible can you do a screen record and share, that way it’s easier to understand the real problem you are facing.

**Comment by christophberger** [comment]
I have some news. 

In February, I "moved" noco.db to a new location. 
Or it seems I rather *copied* it. 
Because I discovered that I still have the original noco.db in the old location.

I copied it over to the new location, 
started the v0.204.4 container with it, 
and all the views and filters etc. are there again!

Conclusion: The upgrade to v0.204.0/1/2/3 did not remove the config and metadata; something else did.

BUT now NocoDB says it cannot load the data from the external data DB, although the DB's location did not change. The error message is: `SQLITE_CANTOPEN: unable to open database file` without further details.

<img width="1068" alt="Screenshot 2024-03-09 at 10 15 10" src="https://github.com/nocodb/nocodb/assets/3835890/109a80cc-85bb-4921-8b3c-f6beace52c3e">

However, the metadata of the external DB is available:

<img width="1021" alt="Screenshot 2024-03-09 at 10 16 28" src="https://github.com/nocodb/nocodb/assets/3835890/d3c1c8e8-780e-4e64-a996-c774146ac31d">

This is the Schema Sync dialog box:

<img width="647" alt="Screenshot 2024-03-09 at 10 19 06" src="https://github.com/nocodb/nocodb/assets/3835890/91fb3e4b-2e4b-4fdc-a115-8ebeec2ae589">

And here are the settings for the external DB:

<img width="648" alt="Screenshot 2024-03-09 at 10 20 17" src="https://github.com/nocodb/nocodb/assets/3835890/adf13593-fa5f-4876-b5bc-0d4b2b500581">

(BTW, it does not seem to matter if I use the full path, the filename only, or `./newsletter.sqlite`. It works with the newer noco.db and fails with the older one.)

So I have
- A newer copy of noco.db, with which the external database works but the metadata is no there,
- and an older copy of noco.db that has all the metadata but somehow prevents NocoDB from connecting to the external database.

A strange situation!

I compared both noco.dbs in DBeaver:


Structure | noco.db.2024-03-08 | noco.db.older-copy
-- | -- | --
Connection | noco.db.2024-03-08 | noco.db.older-copy
Tables | Tables | Tables
Table | nc_j4bt___Features | N/A
Table | N/A | nc_evolutions
Sequences | Sequences | Sequences
Sequence | nc_store | nc_store
Value | 5 | 6
1573 objects compared

I know I'm doing blind guesswork.
Can we draw any conclusions from all that?

**Comment by pranavxc** [comment]
> I have some news.
> 
> In February, I "moved" noco.db to a new location. Or it seems I rather _copied_ it. Because I discovered that I still have the original noco.db in the old location.
> 
> I copied it over to the new location, started the v0.204.4 container with it, and all the views and filters etc. are there again!
> 
> Conclusion: The upgrade to v0.204.0/1/2/3 did not remove the config and metadata; something else did.
> 
> BUT now NocoDB says it cannot load the data from the external data DB, although the DB's location did not change. The error message is: `SQLITE_CANTOPEN: unable to open database file` without further details.
> 
> <img alt="Screenshot 2024-03-09 at 10 15 10" width="1068" src="https://private-user-images.githubusercontent.com/3835890/311427402-109a80cc-85bb-4921-8b3c-f6beace52c3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTEwNTIsIm5iZiI6MTcwOTk5MDc1MiwicGF0aCI6Ii8zODM1ODkwLzMxMTQyNzQwMi0xMDlhODBjYy04NWJiLTQ5MjEtOGIzYy1mNmJlYWNlNTJjM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMTMyNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzc4NTZlMGY1MTYwMjRhMDA2NGVhNjc1ZGJiZTUyZmQ3NzY2M2NiMGY1ZDViMjUzN2E0N2FiYzk4ZmUyMGM4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ix-aJtxGxU7VXCu7lff7TCxt8646LdqHTQuZ__-CMrM">
> However, the metadata of the external DB is available:
> 
> <img alt="Screenshot 2024-03-09 at 10 16 28" width="1021" src="https://private-user-images.githubusercontent.com/3835890/311427420-d3c1c8e8-780e-4e64-a996-c774146ac31d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTEwNTIsIm5iZiI6MTcwOTk5MDc1MiwicGF0aCI6Ii8zODM1ODkwLzMxMTQyNzQyMC1kM2MxYzhlOC03ODBlLTRlNjQtYTk5Ni1jNzc0MTQ2YWMzMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMTMyNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBhZTE1MGUyNWNjODg0YWQ1MmFhNTEzYTg1NzhiNTM5MTE5MjQ1ZDBkNWE5ZmRlN2ZjOTJlNmNkMDg1NDFmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KFOG2S78T9Iwv7lKcnstvZgSyHt6eH71ufaFKlLVVTw">
> This is the Schema Sync dialog box:
> 
> <img alt="Screenshot 2024-03-09 at 10 19 06" width="647" src="https://private-user-images.githubusercontent.com/3835890/311427608-91fb3e4b-2e4b-4fdc-a115-8ebeec2ae589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTEwNTIsIm5iZiI6MTcwOTk5MDc1MiwicGF0aCI6Ii8zODM1ODkwLzMxMTQyNzYwOC05MWZiM2U0Yi0yZTRiLTRmZGMtYTExNS04ZWJlZWMyYWU1ODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMTMyNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFiNGNhYTk2ZWQ3YTM2OTUzZTIxZTUzYzMyNmM0NjhlMzkyMTc0YjJlM2ZkZGY3ZjE2NThjNzEzNWQ0OTliNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t4SbohOi-UWzWVMKhRx6BIzTB9z9MyY03j0wrdHsl4E">
> For comparison, the same dialog for the newer copy of noco.db, where the data is there but the views, filters, etc. are missing:
> 
> <img alt="Screenshot 2024-03-09 at 10 34 02" width="644" src="https://private-user-images.githubusercontent.com/3835890/311428336-88e18f8d-09dc-41c4-b817-84aab99f5f1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTEwNTIsIm5iZiI6MTcwOTk5MDc1MiwicGF0aCI6Ii8zODM1ODkwLzMxMTQyODMzNi04OGUxOGY4ZC0wOWRjLTQxYzQtYjgxNy04NGFhYjk5ZjVmMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMTMyNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVlYmVmMWZlNTI0OGY0NTBhZjUxM2RiOTg2MTZjMTMyZGM1NGRkZTk2NGQzNTgzMjFlMGE5ODNiNzVjMmI5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EEI40kXbp6PUzyWEIIJDdgkzuZFaL30D-P5pkH4AVvU">
> So I have
> 
> * A newer copy of noco.db, with which the external database works but the metadata is no there,
> * and an older copy of noco.db that has all the metadata but somehow prevents NocoDB from connecting to the external database.
> 
> A strange situation!
> 
> I compared both noco.dbs in DBeaver:
> 
> Structure	noco.db.2024-03-08	noco.db.older-copy
> Connection	noco.db.2024-03-08	noco.db.older-copy
> Tables	Tables	Tables
> Table	nc_j4bt___Features	N/A
> Table	N/A	nc_evolutions
> Sequences	Sequences	Sequences
> Sequence	nc_store	nc_store
> Value	5	6
> 1573 objects compared		
> I know I'm doing blind guesswork. Can we draw any conclusions from all that?

To make the external source work you have to copy the file to the exact same path(within container) where it currently present.

**Comment by christophberger** [comment]
It is. I did not move it.

**Comment by pranavxc** [comment]
> It is. I did not move it.

When you added external source under a base you may provided a path to your sqlite file and within the newly created docker container it will check that path for the external db file since the path is stored in the metadb as you inputed initially. And from the error it’s clear that the file is not exist in that path to confirm you can check for any backend error log in docker as well.

**Comment by christophberger** [comment]
Ok, sorry, I misunderstood your previous comment. 

In both cases, I configured the path to the external DB as `/usr/app/data/newsletter.sqlite`. The path is properly mounted to the local path where the DB file actually lives.

**Comment by pranavxc** [comment]
> Ok, sorry, I misunderstood your previous comment.
> 
> In both cases, I configured the path to the external DB as `/usr/app/data/newsletter.sqlite`. The path is properly mounted to the local path where the DB file actually lives.

Ok then it looks like some permission error, can you check the docker container logs and share it if there any error?

**Comment by christophberger** [comment]
Sure. When I attempt to access a table, the docker logs show these errors:

```log
[Nest] 9  - 03/10/2024, 8:57:33 PM   ERROR [GlobalExceptionFilter] SQLITE_CANTOPEN: unable to open database file
Error: SQLITE_CANTOPEN: unable to open database file
[Nest] 9  - 03/10/2024, 8:57:33 PM   ERROR [DatasService] Error: SQLITE_CANTOPEN: unable to open database file
```

**Comment by pranavxc** [comment]
> Sure. When I attempt to access a table, the docker logs show these errors:
> 
> ```
> [Nest] 9  - 03/10/2024, 8:57:33 PM   ERROR [GlobalExceptionFilter] SQLITE_CANTOPEN: unable to open database file
> Error: SQLITE_CANTOPEN: unable to open database file
> [Nest] 9  - 03/10/2024, 8:57:33 PM   ERROR [DatasService] Error: SQLITE_CANTOPEN: unable to open database file
> ```
> 
> Those errors aren't in the log if I use the other noco.db.

Confirm the sqlite file path under Datasources tab.


https://github.com/nocodb/nocodb/assets/61551451/95515282-62c4-4b42-ad1c-d9b78f42c376

**Comment by christophberger** [comment]
I use `/usr/app/data/newsletter.sqlite`, and `/usr/app/data` is mapped to the host directory where the SQLite file lives.

![Screenshot 2024-03-12 at 11 22 45](https://github.com/nocodb/nocodb/assets/3835890/afeff29d-07f1-426b-8dc2-05d8cd3da473)

Note that the same path works with the newer version of noco.db (the one that has no metadata), all else being unchanged.

I already tried `newsletter.sqlite` and `./newsletter.sqlite`, with the same result.

I suspect that the problem is rooted somewhere inside the older version of noco.db. But I have no idea where to look.

**Comment by pranavxc** [comment]
The error is happening with Sqlite which couldn't able to open the file and the reason could be any of the following,

- Read permission is missing for the `newsletter.sqlite` file
- File is missing in the provided path
- Corrupted sqlite file 

You can get inside the container and verify that the file exist or not, verify read permission and try to connect it from external tool to verify sqlite file is not corrupted. If the path shown in edit source is `/usr/app/data/newsletter.sqlite` then it will provide that value to `knex` package(it uses `sqlite3` internally) and knex will do the rest. 

For more info you can check this - https://www.sqlite.org/rescode.html#cantopen

**Comment by christophberger** [comment]
A new test brought new insights.

Currently, my NocoDB instance runs with the older version of noco.db, the one with the base that has all the views, filters etc. but cannot open the external DB.

I just created a new base in this instance, with the external DB as datasource. 

The new base can open the database without any issues.

So the problem is 100% a problem of metadata in the base that fails to open the external db.

Which of its metadata does a base use for opening and reading an external database? Is there any chance that I can somehow repair that data in a DB app like DBeaver? It took me a while to set up all the views, filters, sorting, column types, etc., and I don't look forward to doing all that again.

**Comment by pranavxc** [comment]
> A new test brought new insights.
> 
> Currently, my NocoDB instance runs with the older version of noco.db, the one with the base that has all the views, filters etc. but cannot open the external DB.
> 
> I just created a new base in this instance, with the external DB as datasource.
> 
> The new base can open the database without any issues.
> 
> So the problem is 100% a problem of metadata in the base that fails to open the external db.
> 
> Which of its metadata does a base use for opening and reading an external database? Is there any chance that I can somehow repair that data in a DB app like DBeaver? It took me a while to set up all the views, filters, sorting, column types, etc., and I don't look forward to doing all that again.

Let's connect over a call, you can ping me in Discord https://discord.gg/5RgZmkW ( user - `@pranavxc` )

**Comment by christophberger** [comment]
Thank you, @pranavxc, for resolving the issue on the call! I never would have been able to track that down, let alone fix, on my own. 

For interested readers, the problem was caused by the base's config that pointed to an outdated path. This part of the config is inaccessible in the UI, though; it's an internal config setting. After fixing the path, the base works again! 🎉
