### ISSUE TITLE
🐛 Bug: External data source (PostgreSQL) not editable after creation

### ISSUE THREAD

**Issue by salim-b** [nocodb/nocodb#7783]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Setup NocoDB with SQLite as its own DBMS.
2. Create a new *base* via NocoDB's UI.
3. Add an external PostgreSQL data source to the newly created base.
4. Try to edit the external PostgreSQL data source by clicking on its "edit" button. The edit dialogue immediately vanishes and the error message `Something went wrong. Please reload the page if page is not functioning properly.` is displayed.

### Desired Behavior

The edit dialogue should show without an error.

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.204.3**

### Attachments

[Bildschirmaufzeichnung vom 03.03.2024, 22:38:06.webm](https://github.com/nocodb/nocodb/assets/20040931/e4dcbc80-35a3-4194-b34a-ecb93eb1cb5d)

**Comment by dstala** [comment]
@salim-b 
It worked fine on my localhost development environment. We would need your help to sort this out
- If there are any errors on the browser console or on the server, retrieve it for us
- Node version, I am on v18.14.0; PG on 14.7. just for the record, am not sure if it will have an impact here.

**Comment by salim-b** [comment]
Sorry, I didn't check the browser console. The following two messages are printed in Firefox when clicking the PG data source's "edit" button:

```
Error in parsing value for ‘width’.  Declaration dropped.
UI ERROR Error: please transfer a valid name path to validate!
```

Or as a screenshot (expanded): 
![Bildschirmfoto vom 2024-03-04 11-06-02](https://github.com/nocodb/nocodb/assets/20040931/1a29f08d-5d2b-4a66-ae00-42b2a9bf444b)


I don't see any related messages on the NocoDB server's console (I'm running the [official Docker image](https://hub.docker.com/r/nocodb/nocodb) with NocoDB's SQLite DB ["litestreamed"](https://litestream.io/) to an object storage service and no other persistent storage). Are there other (NocoDB-specific) logs I need to check?

**Comment by salim-b** [comment]
Update: With NocoDB v204.4, the error message from the browser console is now conveyed to the NocoDB user in a dialogue saying "Oops! Something unexpected happened :/" with the following details:

```
message: please transfer a valid name path to validate!

de@https://example.com/dashboard/_nuxt/index.B1qgAmjN.js:1:5735
f@https://example.com/dashboard/_nuxt/index.B1qgAmjN.js:1:6525
j@https://example.com/dashboard/_nuxt/index.B1qgAmjN.js:1:6956
L@https://example.com/dashboard/_nuxt/index.B1qgAmjN.js:1:7954
$@https://example.com/dashboard/_nuxt/index.B1qgAmjN.js:1:8569
vs@https://example.com/dashboard/_nuxt/entry.B3TBl9q2.js:1:14878
Ko@https://example.com/dashboard/_nuxt/entry.B3TBl9q2.js:1:14959
D@https://example.com/dashboard/_nuxt/entry.B3TBl9q2.js:1:25671
vs@https://example.com/dashboard/_nuxt/entry.B3TBl9q2.js:1:14886
IT@https://example.com/dashboard/_nuxt/entry.B3TBl9q2.js:1:16561
```

(I replaced the acual domain with `example.com`.)

**Comment by dstala** [comment]
thanks @salim-b!
we will look into it ..

**Comment by salim-b** [comment]
Data sources UI was overhauled recently, but issue is still present in latest NocoDB v0.207.2 when navigating to *base* → <kbd>...</kbd> → <kbd>Settings</kbd> → <kbd>Data Sources</kbd> → *data source* → <kbd>Connection Details</kbd>.

Same error message:

```
message: please transfer a valid name path to validate!

de@https://example.com/dashboard/_nuxt/zUoyaCGf.js:1:5554
f@https://example.com/dashboard/_nuxt/zUoyaCGf.js:1:6344
j@https://example.com/dashboard/_nuxt/zUoyaCGf.js:1:6775
L@https://example.com/dashboard/_nuxt/zUoyaCGf.js:1:7773
$@https://example.com/dashboard/_nuxt/zUoyaCGf.js:1:8388
Gs@https://example.com/dashboard/_nuxt/DJALOdOY.js:14:1375
ga@https://example.com/dashboard/_nuxt/DJALOdOY.js:14:1448
M@https://example.com/dashboard/_nuxt/DJALOdOY.js:14:12621
Gs@https://example.com/dashboard/_nuxt/DJALOdOY.js:14:1383
Ix@https://example.com/dashboard/_nuxt/DJALOdOY.js:14:3116
```


(Actual domain was replaced with `example.com`.)

**Comment by pranavxc** [comment]
Fixed here https://github.com/nocodb/nocodb/pull/8573
