### ISSUE TITLE
Record Sometimes gets duplicated

### ISSUE THREAD

**Issue by zan-xhipe** [nocodb/nocodb#779]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.81.1**

Sometimes when entering a record and linking it to another table the record get duplicated

**Steps To Reproduce**
1. Create two tables with a many to many link between them
2. Add an entry to the first table
3. Link it to a record in the second table
4. Save the record
5. see that another of of the record has appeared in the table

**Expected behavior**
No duplicate record should appear

**Screenshots**
The record `This Record will Disappear`  gets duplicated, I was trying to replicate a different bug, hence the name.

![Bug 1](https://user-images.githubusercontent.com/356086/142047339-a249585a-1c8f-4355-bbf0-fb8ed1e6453a.PNG)
![Bug 2](https://user-images.githubusercontent.com/356086/142047346-f60fb6ed-c49e-43cd-8ebc-3f011cd127c6.PNG)
![Bug 3](https://user-images.githubusercontent.com/356086/142047333-07b98173-5652-4f9e-8cc2-58b1012836f5.PNG)

**Comment by pranavxc** [comment]
Fixed in `0.83.3`
