### ISSUE TITLE
First letter of record disappears

### ISSUE THREAD

**Issue by zan-xhipe** [nocodb/nocodb#780]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.81.1**

Sometimes when entering a records title the first letter you type vanishes

**Steps To Reproduce**
1. In the grid view add a new record
2. Type in the title for the record
3. The first letter is visible, then disappears

**Expected behavior**
Things you type in should not disappear

**Comment by pranavxc** [comment]
Can you share the browser details?

**Comment by zan-xhipe** [comment]
<html>
<body>


Vivaldi | 4.3.2439.65 (Stable channel) (32-bit)
-- | --
Revision | 422e3f53c5055d214398129edf198ce15d0fcdd7
OS | Windows 8.1 (Build 9600)
JavaScript | V8 9.4.146.24
User Agent | Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36


</body>
</html>

**Comment by pranavxc** [comment]
> Vivaldi	4.3.2439.65 (Stable channel) (32-bit)
> Revision	422e3f53c5055d214398129edf198ce15d0fcdd7
> OS	Windows 8.1 (Build 9600)
> JavaScript	V8 9.4.146.24
> User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36

Thanks for sharing the information, we will look into the issue soon.

**Comment by wingkwong** [comment]
@zan-xhipe are you able to reproduce this issue in latest version?

**Comment by o1lab** [comment]
Please feel free to reopen if issue exists.

**Comment by enfyrneaux** [comment]
I'm seeing this issue with Firefox 131.0.3 on Windows, on NocoDB 0.260.1.
