### ISSUE TITLE
🐛 Bug: Handle forbidden column reordering more gracefully

### ISSUE THREAD

**Issue by salim-b** [nocodb/nocodb#7808]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When an *Organization Level Viewer* tries to reorder columns via the <kbd>Fields</kbd> menu of a table from an external data source, an error pops up:

```
message: Request failed with status code 403

Wt@https://example.com/dashboard/_nuxt/entry.B3TBl9q2.js:95:104673
XZ@https://example.com/dashboard/_nuxt/entry.B3TBl9q2.js:97:1050
T@https://example.com/dashboard/_nuxt/entry.B3TBl9q2.js:97:4249
```

### Desired Behavior

The above error might make sense technically. But it would be nice to handle this case more gracefully – or even better hide the re-ordering UI for users with insufficient rights in the first place.

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.204.4**

### Attachments

[Bildschirmaufzeichnung vom 06.03.2024, 22:38:15.webm](https://github.com/nocodb/nocodb/assets/20040931/bf04063f-26dc-4944-82d4-66cd4f14bf7f)

**Comment by dstala** [comment]
@salim-b fixed. if you happen to notice this again, let us know.

**Comment by salim-b** [comment]
@dstala Thanks a lot, confirmed as fixed! I especially like the fact that users without sufficient rights to alter the table can still re-order columns temporarily for themselves 🎉
