### ISSUE TITLE
Link to another record doesn't always populate possible options

### ISSUE THREAD

**Issue by zan-xhipe** [nocodb/nocodb#781]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.81.1**

When trying to link to another record the dialog doesn't always populate available records. This happens in various different scenarios. In this one you need to save the record you are editing before the dialog populates

**Steps To Reproduce**
1. Have a table with a many to many link to another table
2. Create a record in the table
3. Open the record and click on `Link to 'Table'` 
4. Click `+ New Record` 
5. In the New record Link to a record from the first table
6. The dialog opens but doesn't populate with entries, the filter also doesn't work
7. Cancel that dialog
8. Save the record
9. Try linking to the other table again, the dialog works fine now.

**Expected behavior**
The Dialog to link to another record should always populate with the available options

**Screenshots**
![Filter not loading 1](https://user-images.githubusercontent.com/356086/142049887-26a792fb-88b1-40de-9485-719176987581.PNG)
![Filter not loading 2](https://user-images.githubusercontent.com/356086/142049897-f8e0e76e-ec6d-487a-a9b1-62c8d179f725.PNG)
![Filter not loading 3](https://user-images.githubusercontent.com/356086/142049905-93a30e95-19d6-4cc2-8a4f-f7cddc0fac72.PNG)

**Comment by bchaz42** [comment]
Bonjour, 
J'ai créé une table avec plusieurs champs en  lien many to many tout est ok. Je peux ajouter des nouveaux records, le lien fonctionne en affichant la liste des valeurs possibles ==> OK . 
Lorsque je reviens pour poursuivre mes ajouts d'enregistrements, quelques jours après, les liens ne fonctionnent plus, je n'obtiens plus la liste des valeurs possibles.  et ce qui est proposé comme solution en haut du message ne fonctionne pas

**Comment by o1lab** [comment]
6. The dialog opens but doesn't populate with entries, the filter also doesn't work

is the issue

Filter is working on enter.

**Comment by wingkwong** [comment]
Fixed in ``0.84.12``.
