### ISSUE TITLE
🔦 Feature: Generate image thumbnails?

### ISSUE THREAD

**Issue by dolsem** [nocodb/nocodb#7810]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Right now when you use image attachments they get rendered as is in the table view. Even if the image is 20MB, it is fully rendered into a 35x30 px box. This makes the page freeze when there are too many images.

### Suggested Solution

Automatically generate thumbnails when a user uploads a picture. Probably makes sense to just store them on disk instead of trying to upload to the same image provider, since they are only relevant to NocoDB UI.

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/5207
