### ISSUE TITLE
Feature: Button to toggle html text to html view for text in cells

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#782]
Hi,

It would be useful to have a button to render html text to html view when clicked on it.
Example:
Html text in some cell like below:
![image](https://user-images.githubusercontent.com/86340924/142055389-1fb3bdfc-8a8b-4680-a67a-6e0e04de196c.png)

Html view when clicked on it:
![image](https://user-images.githubusercontent.com/86340924/142055502-8bf061e4-524c-4338-8ddb-3b5689239f54.png)

Would be useful to be able to reference images, be able to style text etc. when required

**Comment by dstala** [comment]
to be tracked under
[Feature: Rich editor for multiline text](https://github.com/nocodb/nocodb/issues/298)
