### ISSUE TITLE
Support for searching the tables

### ISSUE THREAD

**Issue by vrajroham** [nocodb/nocodb#783]
### Feature request
When there are 100s of tables it's harder to scroll and find out the tables. It would be great if there is a search bar on top which filters the table.

**Comment by alexn-s** [comment]
i definitely need that feature. would be great

**Comment by o1lab** [comment]
Would love to get a PR

**Comment by alexn-s** [comment]
i would offer my help if someone would be interested to mainly develop this feature (not too familiar with vue, used to react)

**Comment by gemurdock** [comment]
Seems like a good easy issue, I am going to look at taking a stab at it.

**Comment by woodroom** [comment]
Slightly expanded on the structure management search idea in #801

**Comment by pranavxc** [comment]
Table search option added in `0.83.2`
