### ISSUE TITLE
🐛 Bug: Creating a new table hangs if Default database is not visible

### ISSUE THREAD

**Issue by XenonSup** [nocodb/nocodb#7850]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a new base.
Connect an external base (any).
Go to base's Data Sources. Toggle off the visibility of the Default base.
Create a new table (From either the base dashboard or the "+" icon next to the base's name)
It will look like a new table is being created, but the loading animation keeps going forever on the Data tab, and clicking the "+" icon to add a column throws this error: `te.value is undefined`

If you go back to the Data Sources and enable the Default base, the table you attempted to create does show up and seems functional.

### Desired Behavior

Either
1. Fail to create the table because the Default base is hidden, so you shouldn't be able to add tables to it, or
2. Add the table to the external database by default instead.

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.204.4**

**Comment by dstala** [comment]
fix should be available in next release.

**Comment by XenonSup** [comment]
Thank you for the quick response.

The new version disabled the "+" icon in the sidebar, but the "New Table" button on the base dashboard **is still available and results in the same issue.**

I think disabling the option in the sidebar is intuitive because there's another "+" icon next to the external data source's name.
But I think from the dashboard if there's no option to create a table on the external database, there needs to at least be a dialog or tooltip explaining why one can't add a table.
