### ISSUE TITLE
🐛 Bug: Commenter/Viewer can enable columns in View but they show empty 

### ISSUE THREAD

**Issue by IFGGit** [nocodb/nocodb#7867]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. As SuperAdmin you hide some columns.
2. As Commenter/Viewer you can show these columns but the values in these columns are empty.

### Desired Behavior

Commenter/Viewer shouldn’t see hidden columns in the Fields menu. 

I can fix this bug if you agree with this proposal.

### Project Details

Node: v18.18.2
Docker: false
RootDB: Postgres
PackageVersion: 0.204.5

### Attachments

https://github.com/nocodb/nocodb/assets/162738418/5c1d35df-aa39-461b-9715-801e1ed8e0e2

**Comment by dstala** [comment]
@IFGGit agree with your proposal. You can help us with a PR on this.

**Comment by sreehari2003** [comment]
@dstala  can i work on this ?

**Comment by o1lab** [comment]
Let's hold back on this since as hidden fields can be still seent
- opening up expanded record from a relational table using a lookup etc
- from other views from the same table
