### ISSUE TITLE
🐛 Bug: form with default value configured for select field leads to error

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7869]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

`Invalid option "'Todo'" provided for column "Status". Valid options are "Todo, In progress, Done"`

### Desired Behavior

should work without error

### Project Details

x

**Comment by dharmik3504** [comment]
hello @dstala 
not sure how to reproduce the error can you please provide more detail .

**Comment by dstala** [comment]
- On grid view, add a select field with options "Todo, In progress, Done"; 
- Set default value to "Todo"
- Create a form view, share form view
- Submit data from form view without modifying select field
