### ISSUE TITLE
Feature : Row number required 

### ISSUE THREAD

**Issue by ahmetveburak** [nocodb/nocodb#787]
NocoDB used as docker : false
NocoDB version : 0.82.0
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : 
Node.js version if running as node : v16.11.1
Database version : 13.4

**Steps To Reproduce**
1. Create new table
2. Add some columns
3. Add empty rows (Check Image: STEP 3)
4. Add data to first row: Also, that could be another issue. Empty rows should not be created in database. (multiple rows can be filled) (Check Image: STEP 4)
5. Add Form View and submit a form with random values
6. Change to Grid View, you can datas changed position. (Check Image: STEP 6)

**Expected behavior**
Empty rows shouldn't commited. Submitted form data should appended after the last filled row or table data must keep own position.

**Screenshots**
STEP 3
![STEP 3](https://user-images.githubusercontent.com/31131727/142478744-7e711686-50d4-4f5b-a2df-c80f12593bdc.png)

STEP 4
![STEP 4](https://user-images.githubusercontent.com/31131727/142478847-2dd729e2-613a-4886-9da9-88a38b4e53c1.png)

STEP 6
![STEP 6](https://user-images.githubusercontent.com/31131727/142479309-a8a3267d-d9d8-4d43-b8bc-094809bda0a8.png)

Node version : **v16.11.1**
Arch type: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
packageVersion: **0.82.0**

**Comment by wingkwong** [comment]
Empty rows won't be saved to DB in latest version.
