### ISSUE TITLE
🔦 Feature: Add a settings per projects and/or per tables for the pagination and number of rows shown

### ISSUE THREAD

**Issue by AlexandreBonneau** [nocodb/nocodb#7872]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently, the only way to change the number of rows displayed, is to change the environment variable (see https://docs.nocodb.com/getting-started/self-hosted/environment-variables/) `DB_QUERY_LIMIT_DEFAULT`.

### Suggested Solution

It would be great to be able to change that number per projects, and even per tables (since you can have a case where you want your users to be able to sift through huge number of rows for simple tables, but want to prevent overloading your server with more complex tables).

### Additional Context

Ideally, this feature would allow the user to change the default 25 rows limit without having to change the env variable.
This feature could play well with the [infinite scroll feature request](https://github.com/nocodb/nocodb/issues/3568) as well.

**Comment by dstala** [comment]
pagination supported now @ 25/50/75/100 per page;
