### ISSUE TITLE
NocoDB random table identifier on V2 API Spec

### ISSUE THREAD

**Issue by MoeDawood15** [nocodb/nocodb#7879]
Hi Noco Team 

Hope all is well 

I have a quick question regarding the v2 API 

I noticed table names are masked with a random value , is this a security feature ?

http://localhost:8080/api/v2/tables/**mgngz7s2d6igiyi**/records

Is there no way I can get data by using my actual table name instead of the random ID generated ?

http://localhost:8080/api/v2/tables/addresses/records

**Comment by dstala** [comment]
@MoeDawood15 Use of table name in v2 APIs is deprecated. We did notice lot of messed up routes due to complex character sets on field & table names - and hence decided to go with only ID based routes.

**Comment by salim-b** [comment]
> Is there no way I can get data by using my actual table name instead of the random ID generated ?

@MoeDawood15 You can use the [meta API](https://meta-apis-v2.nocodb.com/#tag/DB-Table/operation/db-table-list) to retrieve the mapping of table names <-> IDs.

**Comment by mystica555** [comment]
@salim-b I'm not understanding what I am reading at your link.  
Can you please explain, perhaps via example of an api call, how to do what you say is possible?

**Comment by salim-b** [comment]
> @salim-b I'm not understanding what I am reading at your link.

You're reading the meta API documentation, specifically the section about the *List Tables* endpoint that allows to "List all tables in a given base". 😉

The JSON response to such an API call will include a `list` objects that is an array with a metadata element per table in the specified base. Every such metadata element includes i.a. the two fields `id` and `table_name`. These two should allow you to derive a table's ID from its name. 😉

An example response (for a base with a single table) looks as follows:

```json
{
  "list": [
    {
      "id": "md_5hua2iqloqirhd",
      "source_id": "ds_jxuewivwbxeum2",
      "base_id": "p_tbhl1hnycvhe5l",
      "table_name": "nc_b84e___Sheet-1",
      "title": "Sheet-1",
      "type": "table",
      "meta": null,
      "schema": null,
      "enabled": true,
      "mm": false,
      "tags": null,
      "pinned": null,
      "deleted": null,
      "order": 1,
      "created_at": "2023-03-11T09:11:45.907Z",
      "updated_at": "2023-03-11T09:11:45.907Z"
    }
  ],
  "pageInfo": {
    "isFirstPage": true,
    "isLastPage": true,
    "page": 1,
    "pageSize": 10,
    "totalRows": 1
  }
}
```
