### ISSUE TITLE
 Failed to resolve entry for package "nocodb-sdk"🐛 Bug: 

### ISSUE THREAD

**Issue by longtraninfodation** [nocodb/nocodb#7896]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

j2ee@j2ee:~/Desktop/001/002/nocodb-0.204.5$ cd packages/nc-gui/
j2ee@j2ee:~/Desktop/001/002/nocodb-0.204.5/packages/nc-gui$ pnpm run generate || ERROR="gui build failed"

### Desired Behavior

Build failed in 23.53s

### Project Details

nocodb-0.204.5/packages/nc-gui

**Comment by dstala** [comment]
AFAIK, `pnpm run generate` is to be triggered from root folder. @wingkwong, can you please help me confirm here.

**Comment by dstala** [comment]
reopen this thread if issue still persists
