### ISSUE TITLE
🐛 Bug: Attachment file names have redundant file extension if MIME type extension != existing file extension

### ISSUE THREAD

**Issue by salim-b** [nocodb/nocodb#7897]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Configure an object storage provider to store file attachments (I'm using Backblaze B2).
1. Create a new column of type `Attachment` in a table of your choice.
1. Upload a JPEG file with a `.jpg` file suffix as attachment in the newly created column. The uploaded filename[^field] will become `FILENAME.jpg.jpeg`, which is obviously ugly and redundant.

[^field]: The `title` field in the JSON metadata string that represents the attachments, to be more precise.

### Desired Behavior

NocoDB should either
- not add a file extension suffix to the filename if one already exists, or
- overwrite an existing file extension suffix with the proper MIME type suffix (`FILENAME.jpg` -> `FILENAME.jpeg`).

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.204.5**

**Comment by dstala** [comment]
@salim-b any other file extension apart from .jpg where you saw this issue?

**Comment by salim-b** [comment]
> @salim-b any other file extension apart from .jpg where you saw this issue?

Yes, it happens whenever a file is uploaded that has a three-letter file extension but a four-letter MIME-type suffix. I just verified this for  `.tif`, `.mid` and `.mpg`.

A non-exhaustive [list of such 4- vs. 3-letter file extensions](https://fileinfo.com/help/different_extensions):

- AIFF vs. AIF
- HTML vs. HTM
- JPEG vs. JPG
- MIDI vs. MID
- MPEG vs. MPG
- PICT vs. PCT
- TIFF vs. TIF
- WAVE vs WAV

**Comment by salim-b** [comment]
@dstala I just updated to NocoDB v0.204.9, but this issue is still persistent... 🫤

**Comment by dstala** [comment]
@salim-b - i tried few, worked fine. can you share sample files that caused issues to you? we will get it investigated

<img width="1080" alt="image" src="https://github.com/nocodb/nocodb/assets/86527202/dfe29f5d-f92b-4878-b890-952f4ff641a4">

**Comment by salim-b** [comment]
E.g. this file with local name `wallhaven-0w8j56.jpg` will be named `wallhaven-0w8j56.jpg.jpeg` after upload: 
![wallhaven-0w8j56](https://github.com/nocodb/nocodb/assets/20040931/6ed131e3-400b-424a-8e86-7a4fff2f612d)

**Comment by dstala** [comment]
can reproduce. issue is sorted out for cloud but somehow persist for OSS. we will clear it off soon.

**Comment by salim-b** [comment]
This appears to be fixed in v0.205.0, thanks!
