### ISSUE TITLE
Is there an undo and redo?

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#790]
**Please enter the following details**

Copy and paste project info:

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.82.0**

**Steps To Reproduce**
1. Add or delete something
2. Hit CTRL + Z (undo) or CTRL + Y (redo)
3. Nothing happens

**Expected behavior**
- Action is undone or redone.
- Undo and redo button visible

**Comment by o1lab** [comment]
Will cover it in #352. And close this.
