### ISSUE TITLE
🔦 Feature: While editing webhook show bulk hooks in disabled state

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#7913]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

- Create a webhook on 'after insert'
- Then come to webhook list
- Try editing the webhook and see 'Bulk' webhooks are not shown from the list. 

<img width="1272" alt="image" src="https://github.com/nocodb/nocodb/assets/5435402/c05ea644-a87f-43d2-965d-4d5046f4fc8c">

### Suggested Solution

- We should show the bulk webhooks but in disabled state from the drop down.

**Comment by dstala** [comment]
- [ ] new webhook, i should be able to toggle trigger after creation
- [ ] edit webhook, UI display is incorrect for parameters and headers
