### ISSUE TITLE
Controlling Project Creation by the Users ...

### ISSUE THREAD

**Issue by vidcentum** [nocodb/nocodb#793]
Node: **v14.18.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.82.0**

NC_DB = MySQL

Is there any way to restrict users creating Projects by users? 

For example, 
a) I created a project. 
b) Invited a user
(Made the user editor)
c) User login (Newly created user)
d) User can see ```New Project ``` option and create projects.

NC_CONNECT_TO_EXTERNAL_DB_DISABLED may be an option to disable creating projects with external databases.
But the user can create projects.
Meta Data is stored in NC_DB
Data stored in NC_DB

We would like to keep the NC_DB from unwanted user projects data.

Is there any way to restrict users creating Projects by users in both the project types: Create new project, Create new project with external DB?

Best Regards
Maruthi

**Comment by o1lab** [comment]
This has been fixed in one of the earlier releases.

A new user with editor or lesser permission, no longer will be able to create projects.
