### ISSUE TITLE
Split value based on special character

### ISSUE THREAD

**Issue by alfureu** [nocodb/nocodb#794]
NocoDB used as docker : true 
NocoDB version : 0.82.0
Database used in NC_DB URL  : mysql 
Project was created  by clicking :  New Project by connecting to external database
Database on which spreadsheet is created : mysql 
OS on which NocoDB is running : linux
Node.js version if running as node : 
Database version : 5.7

**Steps To Reproduce**
1. I am absolutely new to NocoDB but I was wondering whether it would be possible to change/convert value types (mutliline > single line) if that value has a special character, e.g. comma, |, ;, etc.  
2. I have field with a value called "keywords" (= comma separated list of words), and I think it would be great if it would be possible to split, instead of export it to CSV, do the split in some other app, and reimport it... Maybe a feature function with a right mouse click could be introduced, or some type of action?

**Comment by woodroom** [comment]
I have a Single line column.  It contains the names of the companies.  Some cells contain several names separated by the separator ",".  It would be very cool to be able to convert such a column to a table of unique values ​​and establish a multi select relationship

**Comment by dstala** [comment]
in v0.202.5, single line text to single/multi select is supported. multi select expects options to be separated by comma's.

@woodroom @alfureu i will close this thread. please reopen if you need more help. 

You can also reach to us in community.nocodb.com or discord for direct help.
