### ISSUE TITLE
🐛 Bug:  ACL base editor permission, it not quite right

### ISSUE THREAD

**Issue by Bleoo** [nocodb/nocodb#7992]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

admin base setting for other member:
<img width="958" alt="image" src="https://github.com/nocodb/nocodb/assets/11569795/2f3e248e-71c9-4f35-859d-d909fe9483ef">
<img width="1097" alt="image" src="https://github.com/nocodb/nocodb/assets/11569795/c5a27e15-6ce8-4699-a810-1c82ff07a18b">

the other member saw this:
<img width="415" alt="image" src="https://github.com/nocodb/nocodb/assets/11569795/5ed98a0f-bb60-40e2-bfd9-a365b5e790dd">

### Desired Behavior

I created a new database data source in base, and i set a member as an editor in the base and grant them view permissions for all tables. However, he cannot see all tables on their own interface; he can only see tables where he have editor permissions. I believe he if he have editor permissions for the base, he should also have view permissions for the tables, right?

### Project Details

-

### Attachments

-

**Comment by dstala** [comment]
@Bleoo by assigning a particular user as editor / commenter / viewer, you have already given them access based on role at base level.

UI ACL can additionally restrict the views that they are able to see.

Table or View level access control is not available in NocoDB at the moment. So, if you wish your editor to see all the tables & views in a base & edit just one of the tables - it is not possible.

**Comment by dstala** [comment]
To be tracked along with
[🔦 Feature: View Level Permission Control](https://github.com/nocodb/nocodb/issues/7523)
[Giving Specific Access to different tables.](https://github.com/nocodb/nocodb/issues/7131)
