### ISSUE TITLE
Node v16 NPM can't install packages for nc-gui

### ISSUE THREAD

**Issue by gemurdock** [nocodb/nocodb#800]
For the nc-gui package, Node v14 can install without problems. Node v16 shows errors and can't install or upgrade packages.

please provide the following details :
NocoDB used as docker : false
NocoDB version : 0.82.0
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created : sqlite3
OS on which NocoDB is running : Ubuntu 21.04
Node.js version if running as node : 16.13.0
NPM Version: 8.1.0
Database version : UNK

**Steps To Reproduce**
1. git clone git@github.com:nocodb/nocodb.git (0.82.0 at the time)
2. cd ./nocodb/packages/nc-gui
3. npm i

**Expected behavior**
Expect NPM to install all packages.

**Attached files**
1. Error from console for command 3 (npm i).

[NPM Error 22 Nov 2021.log](https://github.com/nocodb/nocodb/files/7584973/NPM.Error.22.Nov.2021.log)

**Comment by gemurdock** [comment]
Figured out the two packages causing the issues.

1. vue-github-buttons: git+https://github.com/xgenecloud/vue-github-buttons.git
2. monaco-editor-webpack-plugin: ^1.9.1

If you delete these, there is no install issue.

**Comment by gemurdock** [comment]
If you update everything to most recent, for the packages that were adjusted in the commit, then the install works.

Look at latest commit here: https://github.com/gemurdock/nocodb/tree/node16-fix

**Comment by pranavxc** [comment]
Fixed in `0.84.2`
