### ISSUE TITLE
🔦 Feature:  Media attachment thumbnails maintain the aspect ratio of the source

### ISSUE THREAD

**Issue by mlathrom** [nocodb/nocodb#8004]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

This is useful for visual projects. My own use case is for Film and TV Visual Effects shot tracking. Being able to see the thumbnail of the full image is important for tracking, especially since shots may have differing aspect ratios.

### Suggested Solution

Check the source pixel dimensions, set a maximum height and width, then generate the thumbnail without cropping.

**Comment by dstala** [comment]
To be tracked under [🔦 Feature: Thumbnail generator for image uploaded](https://github.com/nocodb/nocodb/issues/5207)
