### ISSUE TITLE
🐛 Bug: isFunction is not a function

### ISSUE THREAD

**Issue by ZoeLeee** [nocodb/nocodb#8018]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When I attempted the rapid import of a JSON file, an error occurred, with the message stating 
```
Uncaught TypeError: isFunction is not a function
    at defineComponent (runtime-core.esm-bundler.js:2339:10)
    at index.js:6:16

```

![image](https://github.com/nocodb/nocodb/assets/33168975/8281f90c-24da-4b71-9694-333848626fcb)

This error prevented the JSON data from being parsed correctly.

### Desired Behavior

According to the debugging code, it appears that an unexpected component was imported in the worker service environment.

### Project Details

Node: **v18.19.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.204.9**

**Comment by dstala** [comment]
Tried JSON import with attached file, lead to `Record already exists` error.



[Features - Default.json](https://github.com/nocodb/nocodb/files/15043306/Features.-.Default.json)

**Comment by rameshmane7218** [comment]
> Tried JSON import with attached file, lead to `Record already exists` error.
> 
> [Features - Default.json](https://github.com/nocodb/nocodb/files/15043306/Features.-.Default.json)

I think this is not the same issue as @ZoeLeee is mentioned

**Comment by rameshmane7218** [comment]
@ZoeLeee can you please provide json file used for import so that I can reproduce this `isFunction is not a function` error

**Comment by ZoeLeee** [comment]
#8303
