### ISSUE TITLE
🐛 Bug: NocoDB does not like importing SingleSelect objects that contain single quotes

### ISSUE THREAD

**Issue by ScriptJunky** [nocodb/nocodb#8019]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a CSV with multiple columns and rows.
Make sure you have an item in a SingleSelect column that contains a single quote.
Try to import.

Receive this error;

`Invalid option "Putt'R" provided for column "model". Valid options are "A5, Alpas, Anode, Antidote, Archon, Aries, Atom, AvengerSS, Aviar, AviarX3, Beast, Berg, Boss, Breakout, Buzzz, Caltrop, Catalyst, Cobra, Colt, Comet, Crank, Crave, Creature, Cyclone, D4, D6, Daedalus, Dart, DD3, Deflector, Defy, Deputy, Destroyer, Detour, Diamond, Dimension, Drift, Dune, Echo, Entropy, Envy, Explorer, F3, F5, F7, Fairway Driver, Fierce, Fireball, Freedom, Full Tilt, Gator, Glitch, Groove, Harp, Hatchet, Hex, Impulse, Inertia, Inner Core, Insanity, Invader, Ion, IT, Jet, Judge, Judge (EMac), Katana, King Cobra, Krait, Leopard, Lex, Lift, Lion, Longhorn, Luna, M2, M4, Mako3, Mamba, Manta, Mantis, Matrix, Maya, MD3, Meteor, Mirage, Monarch, Motion, Nitro, Nomad, Nova, Nuke, Octane, Ohm, Orbital, PA-1, PA-4, PA-5, Paradox, Particle, Peace Train, Pearl, Photon, Pig, Pilot, Polecat, Proxy, Pure, Putt''R, Pyro, Queen, Reactor, Relativity, Relay, Resistor, Rhyno, Rhythm, Roach, Roadrunner, Roc3, RocX3, Rollo, Runway, Sapphire, Servo, Shark, Shark3, Shryke, Sidewinder, Signal, Skeeter, Sombra, Sonic, Spin, Stabilizer, Stalker, Starfire, Super Stingray, Tangent, Tantrum, Teebird, Teleport, Tempo, Tenacity, Tern, Terra, Tesla, Theory, Time Lapse, Trace, Trance, Truth (EMac), Uplink, Valkyrie, Vandal, Vanish, Virus, Volt, VRoc, Vulcan, Warship, Watt, Wave, Wraith, Wrath, X5, Xpress, Zone, Ascend, Pixel, Axis, Switch, Lasso, Penny Putter"`

A lot to parse, but here's the meat of it --
`Invalid option "Putt'R" provided for column "model"`

` Valid options are ..... Putt''R, .....`

Attemtping to import after changing the object name to be `Putt''R` produced the same error.

### Desired Behavior

Import of items that include a single quote works, and doesn't break the import.

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.204.9**

**Comment by dstala** [comment]
as on 251.2, import is always as single line text. and from then onwards, type conversion from single line text to single select works with `'`. we continue to have restrictions with comma though.
