### ISSUE TITLE
Multiple id columns are shown when there is only 1 id column in the table.

### ISSUE THREAD

**Issue by vijayrathore8492** [nocodb/nocodb#806]
### System Details :
NocoDB used as docker : true / false
NocoDB version : 0.82.0
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Ubuntu 20.04
Node.js version if running as node : v14.5.0
Database version : PostgreSQL 14.0 (Debian 14.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Steps To Reproduce**
1. Create a table in postgres with `id` as primary key
2. Click on Project metadata on bottom left -> Click on Meta management tab -> Click on Sync Now
3. Newly synced table (from step 1) will show 2 id fields. (Intermittently, Sometimes it show 2 fields). _I created 2 tables with same schema, it showed 2 id columns for table1 and it showed only 1 id column for table 2._ 

**Expected behavior**
It should not show 2 id columns in UI as table has only 1 id column.

**Screenshots**
Table DDL:-
```
CREATE TABLE newtable2 (
	id varchar NOT NULL,
	CONSTRAINT newtable2_pkey PRIMARY KEY (id)
);
```

Table view in GUI:-
![Screenshot from 2021-11-24 22-27-38](https://user-images.githubusercontent.com/17380265/143282501-22cd65af-699d-454b-b84f-2e6bfba41eb4.png)

PS: In my initial debugging I found out that `sqlClient` returns incorrect `columnList`.

**Comment by pranavcbalan** [comment]
We will look into this, thanks for reporting the issue.

**Comment by pranavxc** [comment]
Thanks for reporting, we look into the issue.

**Comment by o1lab** [comment]
This can be closed as this was closed in ```0.84.1```

**Comment by o1lab** [comment]
@vijayrathore8492 : could you please verify if this still exists 0.90.5

**Comment by dstala** [comment]
@vijayrathore8492 closing this issue. reopen if issue persists in latest release.
