### ISSUE TITLE
Option to Prevent Download

### ISSUE THREAD

**Issue by doodlemania2** [nocodb/nocodb#807]
## Recommending Features

Would be wonderful if a public shared view could be configured to not permit CSV export.

**Need for this feature**
I value the data I'm sharing and am happy to share it visibly. But would prefer to not have the data wander off.

**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
When publicly sharing (non-authenticated view), have the ability to turn off the export to CSV feature.

**Describe alternatives you've considered**
Different tool :)

**Additional context**
n/a

**Comment by o1lab** [comment]
Sure, we will consider this :)

**Comment by gemurdock** [comment]
Wouldn't it still be accessible via API? Not exactly sure how NocoDB works here. Have yet to figure out if GUI fetches data via API as well, but I think this could be an additional issue.

**Comment by doodlemania2** [comment]
> Wouldn't it still be accessible via API? Not exactly sure how NocoDB works here. Have yet to figure out if GUI fetches data via API as well, but I think this could be an additional issue.

It's a reasonable question - in this instance, I don't need it to be impossible to copy down (one could also just grab screenshots or do table selects), but a CSV export on the shared page makes it a bit TOO easy :)
