### ISSUE TITLE
🔦 Feature: Group by multiple fields

### ISSUE THREAD

**Issue by karthikvk** [nocodb/nocodb#8183]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have a table with SEO keywords and I'd like to group them by "topic" and "level 1 keyword" so I can look at all the long tail keywords that are for a specific level 1 keyword and a specific topic.

### Suggested Solution

Instead of the dropdown for the "Group By" filter above the table, make it a checkbox so we can pick more than one.

### Additional Context

This feature is available in Airtable.

**Comment by dstala** [comment]
@karthikvk You referring to this option? it wasn't very clear to me from the description.

![Screenshot 2024-04-06 at 10 09 49 AM](https://github.com/nocodb/nocodb/assets/86527202/8ad60ca5-aaf4-41ee-9629-c5acc9205967)

**Comment by karthikvk** [comment]
My bad, I should've been clearer. Please see the attached image.
![nocodb-github-featurerequest](https://github.com/nocodb/nocodb/assets/2264473/1604e10e-0674-432a-900b-72bc0e92c582)
