### ISSUE TITLE
🐛 Bug: Survey Form - attempting to create line breaks on mobile using ENTER produces unwanted action (limitations of SHIFT + ENTER)

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#8184]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I applaud the nocoDB team's work on the form view and surveys. The appearance has improved incredibly, and I'm happy to see the Survey view back!

I especially love the UI at the bottom of the text boxes that indicates how to create a line break (related: https://github.com/nocodb/nocodb/issues/7668#issuecomment-1955878123):

![image](https://github.com/nocodb/nocodb/assets/55474996/3670e5b2-1b1d-495b-a9fc-2b84bef82322)

That said, on mobile, it's not possible to do SHIFT + ENTER to create a line break, so clicking on the ENTER keypad button moves the user to the next question (tested on Android 14, Firefox and Chromium).

### Desired Behavior

Here are some ideas:

1. Disabling the "ENTER to go to next question" action when the rich text box is active.
2. Using a different shortcut to go to the next question (arrow keys? SHIFT + ENTER instead of the other way around?)
3. Disabling the "ENTER for next question" action on mobile (the keyboard isn't activated for other question types anyway, so it's not a shortcut that can really be leveraged on touch screens and keyboard-less interfaces)

### Project Details

NocoDB hosted version

### Attachments

![](https://i.imgur.com/H27w3nV.gif)

**Comment by candideu** [comment]
Here's an example of a similar form by Formbricks which can do "ENTER for next question", but disables the action for long form text:

https://app.formbricks.com/s/cltn3ngh41nzef8j1ul4vb2jc

**Comment by rameshmane7218** [comment]
@candideu we will disable `Enter for next question` in mobile
