### ISSUE TITLE
[Feature] Gray out not available column types instead of removing them from selection

### ISSUE THREAD

**Issue by torwag** [nocodb/nocodb#822]
Problem:
I might be wrong, but if you select a certain type for a column and want to change it later. Nocodb seems not to display types which seems to be incompatible with the already entered data.
That is ok to make sure that data is consistent.
However, users might look up and down the list wondering why they can't find a particular type anymore. There is no indicator that the displayed list is no longer complete.
E.g. having a SingleSelect type one can't change it to formula later.

Solution:
Instead of removing incompatible types from the list, just gray them out. That makes people aware that they are there, but not selectable for a reason.

Bonus: 
Tooltip over a gray-out element tells people "This type is incompatible with the already entered data in that column".

## Recommending Features

NocoDB thrives on community needs. Many of our existing features are derived from community requirements & we will continue to build that way. We invite ideas to make NocoDB better. Do note that, we being an open-source team are constrained by resources & will be able to pick only limited **high demand** ideas for release. So, if you wish to pick this feature request early - spread the word, discuss it in Discord/blog/Reddit, ask your peers & colleagues to vote up for this feature request!

**Need for this feature**
What purpose does your Idea serve? What use cases does it solve?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dstala** [comment]
This is done in most of the scenarios now. If you find any new such instance, let us know.
