### ISSUE TITLE
LinktoAnotherRecord shows a time stamp instead of the selected entry

### ISSUE THREAD

**Issue by torwag** [nocodb/nocodb#823]
Project info:
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.83.5**

mysql version: :5.7

usage of  the provided docker-compose file in /mysql without modifications.
 

Project was created  by clicking : New Project se
Database on which spreadsheet is created : mysql 

**Steps To Reproduce**
1. Create two tables
2. Create a new column in table 1. Select LnktoAnotherRecord point to table2
3. Select an entry for the first row in table 1. Selection seems valid
4. Select an entry for the second row in table 1. Selection window is valid, but the entry shows a timestamp 
5. Select another table or refresh the browser page. The time entry row is gone.

**Expected behavior**
1. Starting from row 2, one expect the see the same possible selections as it works for row 1.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/2484912/143931645-8ad61e3a-462e-4f8a-9c3c-5913cb775193.png)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

[Nc_fiwm_dozent.txt](https://github.com/nocodb/nocodb/files/7620729/Nc_fiwm_dozent.txt)
[Nc_fiwm_dozenten.txt](https://github.com/nocodb/nocodb/files/7620730/Nc_fiwm_dozenten.txt)

**Comment by o1lab** [comment]
Thank you for showing this over a call. Problem occurs when table is created without title (primary value). And then even after setting primary value - timestamp remains as primary value

**Comment by pranavxc** [comment]
Fixed in `0.83.6`
