### ISSUE TITLE
🐛 Bug: Copying and pasting from Excel overwrites one additional row cell

### ISSUE THREAD

**Issue by halphalp** [nocodb/nocodb#8230]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Copy values from Excel
2. Select a location in a NocoDB table to paste
3. Paste the values and note that the row after the last pasted row has its value erased

Essentially, if I copy 5 cells from Excel and paste them into rows 1-5 in a NocoDB table, the value in the column I'm pasting for row 6 will be erased if it exists.

### Desired Behavior

Only update the rows being pasted - not beyond.

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.205.1**

**Comment by dstala** [comment]
tried copying from a Google spreadsheet, unable to reproduce. Can you confirm if you by mistake didn't copy one extra empty cell? you can paste us a video of this issue. would help us.

Haven't tried using MS Excel though

**Comment by o1lab** [comment]
Could you please try it in chrome or others once.

**Comment by xtyuns** [comment]
the same question，When the content copied from excel exceeds 1 column, you will also encounter an error message from the front end.

step1: create a table
![r1](https://github.com/nocodb/nocodb/assets/41326335/0c0a2b91-a6d4-4f80-b688-9379a6df2854)

step2: copy from excel
![r2](https://github.com/nocodb/nocodb/assets/41326335/1d702191-e310-44dc-ae83-6b452c241e1c)

step3: paste in table
![r3](https://github.com/nocodb/nocodb/assets/41326335/4e05a5f5-adb6-478d-8543-fa4998a0be6f)

**Comment by xtyuns** [comment]
The reason for this problem is that clipboardData always ends with `\n`.
![image](https://github.com/nocodb/nocodb/assets/41326335/cb4c9187-675d-4024-8bef-9061f4d9c797)

So when you select 2 columns from Excel copy and paste them into nocodb, it will produce an extra row with only one column
![image](https://github.com/nocodb/nocodb/assets/41326335/24ad7f07-ad0b-4319-8787-87f8f7a083c8)
