### ISSUE TITLE
🔦 Feature: Increase amount of records shown in grid view

### ISSUE THREAD

**Issue by halphalp** [nocodb/nocodb#8231]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have several large tables of data stored in NocoDB and often find it difficult to view/add records given the 25 row restriction on grid views.

### Suggested Solution

Allow the user to specify different numbers of records to show in grid views (25, 50, 100, 500, etc.).

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/4050
