### ISSUE TITLE
🐛 Bug: Grid View's titles disappear when mouse scrolling down.

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8234]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Here are the test data. we will group by "Column2", and the quantity of  each type of "Column2"'s data need exceed 10(To trigger the issue).
![image](https://github.com/nocodb/nocodb/assets/48933981/f686bed7-08aa-4cd6-a1e6-319c33450f55)
- Create a Grid View, group by Column2.
![image](https://github.com/nocodb/nocodb/assets/48933981/cb3b4c86-a838-4072-ba9c-83df8a70bc93)
- Scrolling down, then the title will disappear.
**nomal:**
![image](https://github.com/nocodb/nocodb/assets/48933981/b0c9bea4-70c0-4931-80af-da658bcf4fb2)
**disapear:**
![image](https://github.com/nocodb/nocodb/assets/48933981/c520d0bf-2a98-494a-84c0-7d2415f3848b)

### Desired Behavior

x

### Project Details

- docker build
- version 0.205.0
- mysql8.0

**Comment by rameshmane7218** [comment]
@TangXY123, this looks like a browser-specific issue. Could you please provide browser information (name and version)?

**Comment by TangXY123** [comment]
> @TangXY123, this looks like a browser-specific issue. Could you please provide browser information (name and version)?
yes！I use **Microsoft Edge**
版本 123.0.2420.65 (正式版本) (64 位)
And I also tried **Chrome**
Chrome 已是最新版本
版本 123.0.6312.106（正式版本） （64 位）

The issue is same.

**Comment by TangXY123** [comment]
> @TangXY123, this looks like a browser-specific issue. Could you please provide browser information (name and version)?

yes！I use Microsoft Edge
版本 123.0.2420.65 (正式版本) (64 位)
And I also tried Chrome
Chrome 已是最新版本
版本 123.0.6312.106（正式版本） （64 位）

The issue is same.

**Comment by TangXY123** [comment]
> @TangXY123, this looks like a browser-specific issue. Could you please provide browser information (name and version)?

yes！I use **Microsoft Edge**
版本 123.0.2420.65 (正式版本) (64 位)
And I also tried **Chrome**
版本 123.0.6312.106（正式版本） （64 位）

The issue is same.

**Comment by dstala** [comment]
Tried on Version 123.0.6312.107 (Official Build) (arm64)
Couldn't reproduce either. Will keep an eye

**Comment by TangXY123** [comment]
> Tried on Version 123.0.6312.107 (Official Build) (arm64) Couldn't reproduce either. Will keep an eye

Get it! Maybe I can do more tests to clarify this issue.

**Comment by TangXY123** [comment]
Here is a video, if it helps.
https://github.com/nocodb/nocodb/assets/48933981/4760cc7e-3f2d-42e3-a8c9-02b5a211d233

**Comment by rameshmane7218** [comment]
> Here is a video, if it helps. https://github.com/nocodb/nocodb/assets/48933981/4760cc7e-3f2d-42e3-a8c9-02b5a211d233

Thanks for the video explanation.
