### ISSUE TITLE
🐛 Bug: Some rows doesn't have data when draging in the bottom right corner of the cell to copy data

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8235]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Some rows doesn't have data when draging in the bottom right corner of the cell to copy data. we have to drag two times.
![image](https://github.com/nocodb/nocodb/assets/48933981/582c456b-c18a-4ff2-8101-668b5406018f)
![image](https://github.com/nocodb/nocodb/assets/48933981/90b3ec6c-7e00-439f-94d9-a5af9cf65102)

### Desired Behavior

x

### Project Details

- docker build
- version 0.205.0
- mysql8.0

**Comment by rohittp0** [comment]
[recording-27_05_2024 (1).webm](https://github.com/nocodb/nocodb/assets/45072928/135b8e96-49b3-4fc9-8143-34c4657fbba7)

Testing on the latest develop branch with MySQL. The behaviour was same with Postgres as well

**Comment by TangXY123** [comment]
> recording-27_05_2024.1.webm 
> Testing on the latest develop branch with MySQL. The behaviour was same with Postgres as well

hi, rohittp0, I notice this issue may have been fixed in 0.207.1.(which is found in 0.205.0)

**Comment by dstala** [comment]
@rohittp0 
try the staging base here https://staging.noco.to/#/wqd7e84kkpg8169/pwvt6deb9owszvl/ms6qjj4fk2bgk18
https://github.com/nocodb/nocodb/assets/86527202/f1756282-a099-4755-aacd-ca0bca1e2188
