### ISSUE TITLE
🐛 Bug: Primary key shouldn't be deleted manually.

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8236]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- The table's System Fields can be hidden or shown, and system fields can be also deleted! Although system fields can not be edited.
![image](https://github.com/nocodb/nocodb/assets/48933981/7d335c64-181a-4a01-8a3d-38e6a082614f)
- If users delete the Id, which is the primary key of the table, the system will throw out Error: "Update not allowed for table which doesn't have primary key."
![image](https://github.com/nocodb/nocodb/assets/48933981/4117d8bf-8dba-41c0-8a24-4365d96d1b4b)
![image](https://github.com/nocodb/nocodb/assets/48933981/d9168601-4fa6-472f-abe9-cc5a2aab6f47)
- This is not reasonable. System fields can be shown, but cannot be deleted or edited, I think.

### Desired Behavior

x

### Project Details

- docker build
- version 0.205.0
- mysql8.0

**Comment by dstala** [comment]
Agree. Works that way with PG. Need to disable delete button in general for system fields to avoid any confusion.

**Comment by sreehari2003** [comment]
@dstala  can I work on this? I can disable the delete button for system fields.

**Comment by dstala** [comment]
@sreehari2003 assigned

**Comment by o1lab** [comment]
This can be closed - deleting ID field no longer possible.
