### ISSUE TITLE
No Calendar & Kanban view 

### ISSUE THREAD

**Issue by idntty** [nocodb/nocodb#824]
There is no Calendar & Kanban view in last Docker or installation from source.

I tried installing the solution in different ways, tried different sources as databases - SQLLite or PG. But not the application does not allow to run these views.

**Comment by bit-lang** [comment]
the same issue / question comes up several times. looking forward to it getting resolved.

**Comment by devsvc** [comment]
but they have this in the pic, and videos. feel being fooled after try.
