### ISSUE TITLE
End of table name has a space will cause insert error

### ISSUE THREAD

**Issue by duanfuqiang1128** [nocodb/nocodb#825]
## Please enter the following details
NocoDB used as docker : true
NocoDB version : v0.82.0
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : the official docker image, host on ubuntu 20.04
Node.js version if running as node : 
Database version :  mysql:5.7

## Steps To Reproduce
1. create a table named `test `(has a space)
![图片](https://user-images.githubusercontent.com/44457606/144009361-06d84600-0497-4c47-ac6c-192bd9e7dbd9.png)

2. insert a row in table `test `, got a error
![图片](https://user-images.githubusercontent.com/44457606/144009597-dd30740c-85b2-4ca5-b707-8c75e2f101d3.png)

3. delete table `test `, got a error
![图片](https://user-images.githubusercontent.com/44457606/144009783-6c3e19f4-cc2c-4fed-b680-94baf5f751fd.png)

In mysql database table `nc_models`, the virtual table name is `test `(has a space),  but the real table name is `test'(no space)
![图片](https://user-images.githubusercontent.com/44457606/144010689-18bb6b7a-ddd7-45fe-8605-8887cb0f2e3f.png)

![图片](https://user-images.githubusercontent.com/44457606/144010588-8edb195c-f8de-4d17-a2ad-a725ae8d3f65.png)

it seem like when i create a table in nocodb, the request from the front-end doesn't remove the blank end of table name

**Comment by wingkwong** [comment]
Closing as this issue has been fixed in ``0.83.0``.

![image](https://user-images.githubusercontent.com/35857179/151647750-202bbe4b-acc6-4d92-abeb-9e40cf97d61b.png)
