### ISSUE TITLE
"Delete table" should be part of the tooltip menu of tables 

### ISSUE THREAD

**Issue by torwag** [nocodb/nocodb#826]
Hi,
I noticed a little inconsitencey in the GUI. 
One can add a table, rename it and set the UI ACL in the table section. However, one can not delete a table. The delete table icon is part of the menu-bar on top of the table. However, most of other icons there deal with modification of the given table, like adding a row, sort, filter, etc.

I believe it would be more logical if the "delete table" function is part of the tooltip menu in the table section as this is the one which give the overview of the given tables as a whole.

**Comment by jmkucz** [comment]
Hello! I am going to take a look at this

**Comment by tuutoo** [comment]
Yes...I was also looking for the delete button from the tooltip menu... Until i finally find this issue....
The Table delete is far away from the table name...
The delete table should be with the rename table function...
