### ISSUE TITLE
Mailer send app has an issue

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#827]
https://discord.com/channels/661905455894888490/661905455894888493/915625578500067338

**Comment by jrvidotti** [comment]
![image](https://user-images.githubusercontent.com/5623041/144268601-c62357bc-2ebe-4d74-b7e1-666a7455d515.png)

**Comment by TechMasterElvy** [comment]
Forgot to search before creating the same issue
https://github.com/nocodb/nocodb/issues/855

Feel free to close as duplicate or merge with this one @pranavxc

**Comment by pranavxc** [comment]
Fixed in `0.83.6`
