### ISSUE TITLE
🐛 Bug: Cannot search by email when user renamed the account.

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8270]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Here is a user and the email is "user2@test.com", Sometimes, maybe the user will set the "name" of his account.
![image](https://github.com/nocodb/nocodb/assets/48933981/255baf92-b46e-46a6-bb44-77b32f8241d5)
- However, after he renamed the account, we cannot search this user by email anymore. Same in "Base Member Management" and "Users Management". This is unconvient for users, expecially for those non-English users.
![image](https://github.com/nocodb/nocodb/assets/48933981/119d56a1-67cd-4d3f-aaaa-06c1ef2d0062)
![image](https://github.com/nocodb/nocodb/assets/48933981/ed5ea97e-ac12-4e86-9716-dda062d680a6)
- My opinion: we can add a field named "Email" replaced the "User" Field, "User" or "Username" Field just show the username, if user don't renamed his account, this field is empty. And most important, We can search Not only by username, but also Email.
![image](https://github.com/nocodb/nocodb/assets/48933981/2e7c0f06-63f2-45bb-96e2-fb960ca6794e)

By the way, I'm not sure this should be a bug or a feature, but maybe it is more like a bug, haha.

### Desired Behavior

x

### Project Details

Version: 0.205.0

**Comment by rameshmane7218** [comment]
@TangXY123: Enabling search by email as well as username.
- To add a new 'Username' column, we need to have an internal discussion.
- Currently, we have functionality where if a username is configured, it will be displayed in the list. Hovering over the username will display the associated email.
