### ISSUE TITLE
🔦 Feature: The privilege of "switch Language" should be controlled.

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8272]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Thank you for taking the time to view this request!
- We find out that the setting of  "switch language" is global, and it can be changed by a viewer who just signup to the system! Maybe this should be controlled.
![image](https://github.com/nocodb/nocodb/assets/48933981/893bf8df-4c04-4980-8516-d4d25851bb91)
![image](https://github.com/nocodb/nocodb/assets/48933981/d9ac0c6e-7ef5-4749-838a-0ca8c710ccbf)

### Suggested Solution

Here are two ways, maybe:
1. Change "switch language" to be a "session" operation. Then language changing will have no influence to others.
2. Change "switch language" to be a "Admin" operation. Then the language can be only setting by Admin User.

**Comment by mertmit** [comment]
Hi @TangXY123,

Switch language is a client-side operation & it will be only applied for your browser (it is saved to local storage of browser).
For example your choice will be gone if you clear local storage or access via different browser (eg. incognito)
 
Please let me know if you are seeing a different behavior.

**Comment by TangXY123** [comment]
> Hi @TangXY123,
> 
> Switch language is a client-side operation & it will be only applied for your browser (it is saved to local storage of browser). For example your choice will be gone if you clear local storage or access via different browser (eg. incognito)
> 
> Please let me know if you are seeing a different behavior.

Thank you for replying，this behaves as you say. I just test in my own browser with different users，My mistake~
