### ISSUE TITLE
Inserting new row with not null fields in grid view doesn't works

### ISSUE THREAD

**Issue by jrvidotti** [nocodb/nocodb#828]
**Please enter the following details**

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.83.5**

**Steps To Reproduce**
1. Create not null fields
2. Try to insert a new row

**Screenshots**
https://discord.com/channels/661905455894888490/661905455894888493/915636198104518696

**Comment by wingkwong** [comment]
One more observation:

``Title2`` can be NULL but it requires a value there.

![image](https://user-images.githubusercontent.com/35857179/151647921-d04188ab-c966-4eb5-8518-a4009ea4e80f.png)

**Comment by wingkwong** [comment]
Fixed in ``0.84.9``.
