### ISSUE TITLE
[Feature] Set the number of items per page

### ISSUE THREAD

**Issue by YuanVR** [nocodb/nocodb#8284]
We currently have 25 items per page, which is insufficient for our needs. Would it be possible to increase the number to 100?

**Comment by YuanVR** [comment]
Got an answer from Discord. The developer team said they would have this feature soon. Love it

**Comment by dstala** [comment]
to be tracked under
[🔦 Feature: Option to change pagesize from UI](https://github.com/nocodb/nocodb/issues/4050)
