### ISSUE TITLE
🔦 Feature: Open file in attachment in the browser like we do for images

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#8304]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

File types like pdf, docs are getting downloaded. Instead, they should open in the browser itself.

### Suggested Solution

.

**Comment by dstala** [comment]
On MAC OS
- Chrome : file gets downloaded
- Firefox : file gets opened in adjacent tab

**Comment by rohittp0** [comment]
Seems to be working as expected for me

https://github.com/nocodb/nocodb/assets/45072928/97c00ef4-2e30-4276-b8df-c97fdd245093

**Comment by dstala** [comment]
Something to do with browser setting? I see that the file gets downloaded instead

**Comment by rohittp0** [comment]
[chrome://settings/content/pdfDocuments](chrome://settings/content/pdfDocuments)

Can you check this

**Comment by dstala** [comment]
For me, PDF file is still downloaded automatically. Image opens up properly though

![Image](https://github.com/nocodb/nocodb/assets/86527202/a44d44e9-9ced-49a7-9dcd-42212ca8a3bd)

**Comment by DarkPhoenix2704** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/8990
