### ISSUE TITLE
🐛 Bug: An “Record N not found” exception throws when deleting in the grid view with groupby.

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8305]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Thank you lovely guys for taking the time to read my request report!
- Here is a grid view， group by some fields. When I delete a record, the page sames like not being refreshed. And then if we delete   again, it throws out Exception"Record N not found".
![image](https://github.com/nocodb/nocodb/assets/48933981/73ba97ab-c7dd-4289-a3ab-90cf7a933bd9)

### Desired Behavior

x

### Project Details

0.205.1

**Comment by dstala** [comment]
Issue noticed when bulk delete option is used; works fine when we use row delete
