### ISSUE TITLE
Feature : Set fixed row height

### ISSUE THREAD

**Issue by apprentiLAB-Suzanne** [nocodb/nocodb#831]
When putting a lot of data into a field, the visible overflow makes for very large row height. 
When looking at the table, you might want to get a rough overview of your rows, seeing as many of them at the same time, without necessarily viewing all details. 

Airtable has a similar feature, in which you can set fixed row heights (from short to extra tall), and you can still expand row or fields to get the complete data.

I haven't found a way to do that in NocoDB, is it implemented ?

Thanks !

**Comment by lino-levan** [comment]
I second this. I regularly end up storing long pieces of text (>2000 characters) in some fields which ends up making nocodb borderline unusable. As a temporary fix, I'm just hiding the fields for now but it would be really nice if there was an option for something like this.

**Comment by candideu** [comment]
I'd like to see this as well! it would be great to have the option of wrapping text or having fixed heights

**Comment by brandnewx** [comment]
I find it weird that the height of rows are not fixed. It's a big NO NO.
