### ISSUE TITLE
🐛 Bug: Calendar view is broken in shared base UI 

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#8311]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![Screenshot 2024-04-22 at 11 30 13 AM](https://github.com/nocodb/nocodb/assets/86527202/40326aab-32b5-4c0b-9f8e-c5c0bea6896c)

### Desired Behavior

x

### Project Details

x

**Comment by DarkPhoenix2704** [comment]
https://github.com/nocodb/nocodb/pull/8379
