### ISSUE TITLE
🔦 Feature: Line breaks in comments

### ISSUE THREAD

**Issue by timkley** [nocodb/nocodb#8323]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently there seems to be no way to make a line break in comments which makes it difficult to format text properly.

### Suggested Solution

Make it possible to use “Shift” + “Enter" to create a line break in comments.

**Comment by dstala** [comment]
line breaks will be supported from our next release. we are discussing if its viable to support rich text as well.
