### ISSUE TITLE
🔦 Feature: dynamic line height for comment textarea

### ISSUE THREAD

**Issue by timkley** [nocodb/nocodb#8324]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

The input field for comments is a single text line and does not change it’s height according to the length of the text typed in it. It would be great to see the entire length of the comment not shown in one line but as a text block.

### Suggested Solution

Implement a dynamic max-height or the field with an upper boundary of 10 to 15 lines of text.

**Comment by dstala** [comment]
will be supported from next release
