### ISSUE TITLE
🐛 Bug: No option to duplicate a table when in postgres datasource

### ISSUE THREAD

**Issue by akrea** [nocodb/nocodb#8325]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Connect to a Postgres as a dataSource
- Create table in nocodb (written to PG)
- Click on the ... --> no duplicate option

### Desired Behavior

As far as i recall it used to offer the duplicate option in this menu even if the dataSource was external. Would be great to have it (back).

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.205.1**

### Attachments

![Screenshot 2024-04-23 153122](https://github.com/nocodb/nocodb/assets/16197061/cf007fce-5923-41c7-9dfb-a7be5ca32b1f)

**Comment by dstala** [comment]
This option was removed by design- as for some of the external connected tables, managing duplicate was time consuming, hard and error prone.

**Comment by akrea** [comment]
OK - thanks for the reply!
