### ISSUE TITLE
🐛 Bug:  postgres float8 not recognized as a 'numeric' field.

### ISSUE THREAD

**Issue by dopry** [nocodb/nocodb#8337]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a postgres db with a table with a float8 column
2. Add the db as a data source to a nocodb instance
Note that nocodb interprets it to be a Single Line Text field.

### Desired Behavior

It should be treated as a Decimal ui field.

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.205.1**

**Comment by maheshdhoran** [comment]
Hi @mertmit ,

Following your guidance, I have implemented the necessary changes for the issue with the PostgreSQL 'double precision' data type. Here is the [PR- 8353](https://github.com/nocodb/nocodb/pull/8353)

This is my first contribution to open source, and I'm keen to learn from this experience. Could you please review my changes?

Thank you for your help!

**Comment by mertmit** [comment]
Hi @maheshdhoran ,

Thank you for the PR, I've requested some minor adjustments. Once you've made those changes, I'll proceed with merge process.

Congratulations on your first OSS contribution!

**Comment by maheshdhoran** [comment]
Hi @mertmit,

Thanks for the feedback! Changes implemented as requested.

**Comment by dopry** [comment]
@maheshdhoran Thank you so much for this. I've been super busy and wasn't able to submit a PR.  @mertmit Thanks for ushering  this through.
