### ISSUE TITLE
[Feature] Hide main Table view from `comment` and `view` roles

### ISSUE THREAD

**Issue by guzmonne** [nocodb/nocodb#834]
## Recommending Features

I love that I can create `Locked Views` that limit, sort, and filter the data being shown to the end users. This is an awesome feature because I can curate the data before I present it to the LoB. It also helps alleviate security concerns, like exposing sensitive data to people that shouldn't see that data. For example: credit card numbers, social security numbers, password hashes, etc.

As mentioned before, I can create views to hide this columns from the users, but I can't hide the main table view. Meaning, they can still see everything stored on the table by selecting the entire table instead of the locked view.

I would like to be able to limit the views that other roles can see.

**Need for this feature**
It allows me to keep sensitive data secure and private. It also simplifies the UI for user who needs to see the data in a specific way.

**Is your feature request related to a problem? Please describe.**
There are currently security issues with the current implementation. Noco DB exposes all the tables by default, and even if you remove a table from another role, it stills show every column from the tables that the do have access.

**Describe the solution you'd like**
I believe the best solution is to add a `hide` button to the main table view, just like there is for custom created views.

**Describe alternatives you've considered**
I haven't found a workaround to this behavior given the current features of the app.

**Additional context**

![image](https://user-images.githubusercontent.com/1446448/144424880-5da63403-e60c-4ad5-a7cd-c6eb002959ac.png)
![image](https://user-images.githubusercontent.com/1446448/144424953-5e5eec1e-b885-4d0b-a1be-b9290b1b9a38.png)
![image](https://user-images.githubusercontent.com/1446448/144425040-7f0f87bc-f05d-4718-a570-bc53859013b4.png)

**Comment by dstala** [comment]
@guzmonne You can hide main-table visibility by configuring from UI ACL in Settings/DataSource
Please reopen this request if this doesn't suffice your requirements

![Screenshot 2023-01-07 at 5 48 03 PM](https://user-images.githubusercontent.com/86527202/211150285-98d2a0be-7047-4c5d-b12a-ea44828821ef.png)
