### ISSUE TITLE
🔦 Feature: Define data type of formula result

### ISSUE THREAD

**Issue by despens** [nocodb/nocodb#8341]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Formulas can have different data types as a result, for instance a URL (that users then might want to click on) or formatted text (that should be rendered appropriately), etc.

### Suggested Solution

When creating a formula column, let users chose a target data type that will cause correct rendering and re-usability of the formula result. Alternatively, provide a formula function that lets users typecast.

**Comment by mertmit** [comment]
Hi @despens,

We provide variety of [string manipulation functions](https://docs.nocodb.com/fields/field-types/formula/string-functions/). As well as [URL Formula](https://docs.nocodb.com/fields/field-types/formula/string-functions#url) for generating links within formula cells.

Please let me know if those are working for your use-case. If not maybe you can share an example use-case so we can figure it out.

**Comment by despens** [comment]
That you @mertmit, I tried your suggestion and this works!

It might be cool to have the ability to typecast to Attachment or relations as well, but that's for another feature request.
