### ISSUE TITLE
🔦 Feature: Consistent keyboard navigation and editing across multiple field types

### ISSUE THREAD

**Issue by despens** [nocodb/nocodb#8343]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently it is not possible to move the cell cursor across the grid and "start typing" to edit a cell and then hit Esc to leave the editor for all field types.

For instance, fields of type select, multiselect, year, and probably some others, do not allow to leave focus by hitting Esc. The year type doesn't allow typing or selecting a year using arrow keys/enter.

### Suggested Solution

Would be great to normalize keyboard operation across all field types.

**Comment by dstala** [comment]
Some of the corrections have been introduced. reopen this thread and list out if you face any more navigation issues that you think are required.
