### ISSUE TITLE
🔦 Feature: Add Workspaces to self hosted versions

### ISSUE THREAD

**Issue by mdvertola** [nocodb/nocodb#8344]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

An (example) organization wants to/needs to run nocodb in a self-hosted environment. Organization also has several teams within their organization and needs to create logical separation between the teams/limit access to certain data across the team. With workspaces, organization would be able to create workspaces for each team within the org and manage user access accordingly. 

### Suggested Solution

Incorporate workspaces as they exist in the cloud deployment model into the self hosted version.

### Additional Context

For organizations with strict data protection/supply chain requirements, self-hosting is often the only acceptable option regarding security/compliance. Adding workspaces to these self-hosted environments would be massively helpful.

**Comment by dstala** [comment]
@mdvertola Workspaces are available in self-hosted enterprise plans. Please drop a mail to support@nocodb.com or book a meeting [here](https://calendly.com/nocodb-meeting)
