### ISSUE TITLE
[Feature] Support for `readonly views` and `editable views`

### ISSUE THREAD

**Issue by guzmonne** [nocodb/nocodb#835]
## Recommending Features

> All my comments in this issue about table views are in the context of using PostgreSQL. I don't know if any of my statements around the behavior of views extend to other database engines like MySQL, Oracle, or MSQL.

Currently, when you create a new Noco DB project you can connect it to a PostgreSQL database to handle all the tables inside a given `schema`. What I would like is to also be able to handle Table Views along with normal Tables. They behave almost exactly as tables but allow to customize how the underlying data is seen. From PostgreSQL documentation:

> Making liberal use of views is a key aspect of good SQL database design. Views allow you to encapsulate the details of the structure of your tables, which might change as your application evolves, behind consistent interfaces.
> 
> Views can be used in almost any place a real table can be used. Building views upon other views is not uncommon.
> ~~[Source](https://www.postgresql.org/docs/13/tutorial-views.html)

In our case, support for views would allow us to solve the following issue we currently have with NocoDB:

- Allow us to limit the number of tables a user can see, by creating views under a new `schema`.
- Allow us to limit the columns that the user can see.
- Combine fields, and manipulate the data before it arrives to NocoDB, without having to depende on NocoDB to do so.

I understand that handling views can be complex, because they may be created by joining multiple tables. This would make it hard to handle `updates/inserts` as they are currently done for tables. Nonetheless, PostgreSQL supports multiple ways to allow updates on a view. For example, if the view is created from a `single base relation` PostgreSQL will take the `UPDATE/INSERT` statement from the view, and pass it to the proper relation. Basically, it can be treated as a normal table. If the view is more complex, there are still ways to configure PostgreSQL to support applying updates to the table.

I think that the responsibility of configuring views to be editable should fall to the database administrators and not on NocoDB. NocoDB should just expose a way to handle views just like it handle tables, and leave update implementation on the backend to the database owners.

[Here is a deeper explanation of the way that PostgreSQL handles updates to views](https://www.postgresql.org/docs/14/rules-views.html).

**Need for this feature**
As mentioned before, with this feature we can:

- Customize how the data is viewed before it reaches NocoDB.
- Filter the `views` that users can see by creating views on different schemas.
- Address security concerns by hidden sensitive data from end users.

**Is your feature request related to a problem? Please describe.**
There are no workarounds currently for the last point of the previous section. The two first point can be remediated using the current features.

**Describe the solution you'd like**
I would like for NocoDB to recognize `views` just as it recognizes `tables`. And treats them as equals.

**Describe alternatives you've considered**
I have considered creating a new database or schema where only certain data is replicated. But this is cumbersome and hard to maintain.

**Comment by o1lab** [comment]
Thanks for the detailed request. Appreciate it.

We will keep the support of views simple to begin in this solution:
- SQL Views will be read only.
- If the requirement is an updatable view - then it can be created via noco GUI itself (on a single table or a joined table)
- I recognise postgres allows updatable views where you can setup trigger to update even views with joined tables. However, we will see this later after the initial implementation.

**Comment by guzmonne** [comment]
Great I think Readonly views is a good first approximation to the full feature.

I do believe that once you start working with views inside Noco DB you'll be able to add the ability to update without much further modifications to the current codebase. As I mentioned on the issue, simple views (views created without joins) can be treated as tables. PostgreSQL will make sure to update the correct underlying resource.

**Comment by o1lab** [comment]
Available in 0.83.6
