### ISSUE TITLE
[Feature] Select to use the title instead of the id for REST endpoints

### ISSUE THREAD

**Issue by TacEtarip** [nocodb/nocodb#836]
I want it to be possible to select to use the title of the project in the REST endpoint instead of the id.

**Need for this feature**
To create a more readable REST endpoint.

**Describe the solution you'd like**
An environment variable to select this behaviour.

**Describe alternatives you've considered**
Been able to select this in the GUI for each project.

**Comment by jonathan-chin** [comment]
+1

**Comment by wingkwong** [comment]
Available since `0.90.x`
