### ISSUE TITLE
Website redirecting to github

### ISSUE THREAD

**Issue by RadekHavelka** [nocodb/nocodb#839]
Hi, this is not about the code, but about your site - i want to check the videos, demos etc, but the site after several seconds keep redirecting to this github page. Very annoying :(

**Comment by gemurdock** [comment]
Not an issue for me, I don't think it is for anyone else.

**Comment by o1lab** [comment]
We will look into this.

In the meanwhile : demos are available in our [docs](https://docs.nocodb.com/getting-started/demos) as well.

**Comment by RadekHavelka** [comment]
easy reproduction - go to homepage https://nocodb.com/, launch HOW IT WORKS video, around the time the user opens the Muhammad Ali poster, about 10 secs of the video, i get redirected to this github page.  This happend before by other videos as well, cannot reproduce it right now, but its weird.

**Comment by candideu** [comment]
Getting the same issue when clicking on the "How it works" video, as indicated by @RadekHavelka. I'm using the latest version of Firefox. That said, it also happens on its own if I open the website in a background tab and leave it alone for about a min.

**Comment by o1lab** [comment]
fixed
