### ISSUE TITLE
[Feature] Attachment Previews and Embeds for More File Types

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#841]
## Recommending Features

Hello! I would like to see previews for audio, PDFs, documents, videos, etc. file types right inside of the app, much like we can preview images.

**Need for this feature**
This is useful for teams that are sharing files, or for sharing a large database of documents, sounds, videos, etc. with the public. Users can preview the media first without having to download each attachment separately.

**Is your feature request related to a problem? Please describe.**
As of now, if I add audio or PDFs, they open in a new tab (if my browser can preview it) or immediately start downloading.

**Describe the solution you'd like and additional context**
Here are some examples from Airtable. I believe Airtable uses Box.com to preview documents:

![image](https://user-images.githubusercontent.com/55474996/145275676-67c8bc34-b8be-4ddd-aaa4-c6a7de679d15.png)
![image](https://user-images.githubusercontent.com/55474996/145276045-d1c94ec1-54c7-4b2e-b24a-7828a8203af7.png)
![image](https://user-images.githubusercontent.com/55474996/145276079-aecc50aa-7aef-4593-848c-dc9381da4211.png)
![image](https://user-images.githubusercontent.com/55474996/145276233-d30832a2-4263-4c19-bae1-2567d4d28c90.png)

**Comment by DarkPhoenix2704** [comment]
Added in https://github.com/nocodb/nocodb/pull/8990


Attachment Preview will available for 

- Videos
- Audios
- Images
- PDF & Office FIle - Google Viewer

**Comment by candideu** [comment]
Incredible!
