### ISSUE TITLE
🔦 Feature:  New Form (Landscape) Entry left to right rather than top to bottom

### ISSUE THREAD

**Issue by DunnBrokeIT** [nocodb/nocodb#8430]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

The use case for me is similar to Asana for Task Management. This functionality mirrors the field data itself with scrolling many fields and rows can be seen visually.

### Suggested Solution

New Form (Landscape) Entry left to right rather than top to bottom

**Comment by dstala** [comment]
NocoDB does support form views in survey mode. Is this what you are referring to here? Please check out this 
https://docs.nocodb.com/views/view-types/form/#survey-form-view

Reopen this ticket if you need more details

**Comment by DunnBrokeIT** [comment]
> NocoDB does support form views in survey mode. Is this what you are referring to here? Please check out this https://docs.nocodb.com/views/view-types/form/#survey-form-view
> 
> Reopen this ticket if you need more details

I need the form to support landscape supporting multiple columns wide. I see no way to have this option currently.
Thanks,
Dana
