### ISSUE TITLE
Can not see data - graphql 404

### ISSUE THREAD

**Issue by iBobik** [nocodb/nocodb#845]
I've just upgraded to 0.83.5, but except schema database seems empty in UI.

In logs I see GraphQL endpoin does not work:
Response in browser console:
`Cannot POST /nc/berubitcoin_ct8v/v1/graphql`
Container logs:
`POST /nc/berubitcoin_ct8v/v1/graphql 404 170 - 0.887 ms`

**Please enter the following details**

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.83.5**

**Comment by iBobik** [comment]
Btw, I can not reproduce it in a new instance, just in my older one.

**Comment by o1lab** [comment]
Did you 've any columns or tables with - or space. GQL fails on these.

**Comment by iBobik** [comment]
Yes, I have.

Thank you for a quick help.
