### ISSUE TITLE
🐛 Bug: Initial invitation e-mail is sent twice

### ISSUE THREAD

**Issue by salim-b** [nocodb/nocodb#8460]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Set up a self-hosted NocoDB instance and configure SMTP via the [`NC_SMTP_` environment variables](https://docs.nocodb.com/getting-started/self-hosted/environment-variables/).

1. Navigate to the [user management page](https://docs.nocodb.com/collaboration/oss-specific-details/#user-management) and invite a new user to the instance. The exact same invitation e-mail (i.e. incl. the same invitation token in the <kbd>Signup</kbd> button link) is sent *twice*.

### Desired Behavior

The invitation e-mail should only be sent *once*.

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.207.0**

### Additional info

Only the *initial* invitation e-mail is sent twice. When <kbd>Resend Invite E-mail</kbd> is triggered from the user management page, the new invitation e-mail is only sent once.

**Comment by pbelouin-mpiwg** [comment]
same issue here, but I've set up the SMTP settings through the nocodb UI

**Comment by salim-b** [comment]
> the email (single in this case) arrives with both Role and Base name blank.

Yeah, I noted that [before](https://github.com/nocodb/nocodb/pull/8529#issuecomment-2120168307), but didn't get a reply...
