### ISSUE TITLE
🐛 Bug: Function MONTH is not available

### ISSUE THREAD

**Issue by gehoida** [nocodb/nocodb#8464]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Use a Formula field and enter 'MONTH('2022-03-14')' als formula. 

### Desired Behavior

Result is 3

### Project Details

NocoDB used as docker

**Comment by rameshmane7218** [comment]
@gehoida Earlier, we used to remove unsupported formulas from the list, but now we are showing them in the list and marking them as disabled to avoid misunderstandings.
![Screenshot 2024-06-04 at 12 10 01 PM](https://github.com/nocodb/nocodb/assets/101566080/10167b1a-465a-4b4c-8ade-e77950f81d31)

**Comment by rameshmane7218** [comment]
Fixed in PR #8516
