### ISSUE TITLE
Add mobile support

### ISSUE THREAD

**Issue by Rednas83** [nocodb/nocodb#850]
**Need for this feature**
Are there plans for a better view for small screens like phones/tablets?

**Is your feature request related to a problem? Please describe.**
Currently NocoDB on a mobile looks like this
![image](https://user-images.githubusercontent.com/25219229/145565929-0ceb7a5a-b3cc-4d21-804b-4a4415cb4f77.png)

**Comment by gemurdock** [comment]
Progressive web app? :)

**Comment by Rednas83** [comment]
Not perse, more like responsive. The idea of mobile first
* Hide the menu behind a button for small screens
* Make the spreadsheet fullscreen for small screens

Something like:
![image](https://user-images.githubusercontent.com/25219229/145706084-fb676634-aa8e-4da5-b517-bc8f38a586f5.png)

**Comment by Morakhiyasaiyam** [comment]
+1

**Comment by louwers** [comment]
Duplicate of #158

**Comment by o1lab** [comment]
Tracked in #158
