### ISSUE TITLE
🐛 Bug: no access to bulk update

### ISSUE THREAD

**Issue by jbricout007** [nocodb/nocodb#8504]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have no access to bulk update when I select a few lines on my table in NOCODB.
However, I ca bulk delete.

How can I access to this function ? Is there a specific parameter to activate ?
![No bulk update](https://github.com/nocodb/nocodb/assets/90313104/58953139-19d7-42f4-a494-705d0322d288)

### Desired Behavior

Access to bulk update function after select a few lines

### Project Details

Experimentation of NOCODB to create, update and delete some data

**Comment by dstala** [comment]
@jbricout007 Bulk update is Cloud only enterprise feature.
