### ISSUE TITLE
🐛 Bug: meta sync doesn't identify change in table name

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#8506]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- connect to external data source
- change table name outside nocodb (table plus)
- meta sync doesn't identify change
- on the grid, accessing table throws error `table not found`

### Desired Behavior

- meta sync should work

### Project Details

207.1

**Comment by o1lab** [comment]
Its not possible to know the rename of any db entities that way.
