### ISSUE TITLE
Virtual hasMany relationships disappears when the table metadata is recreated

### ISSUE THREAD

**Issue by vijayrathore8492** [nocodb/nocodb#851]
NocoDB used as docker : false
NocoDB version : 0.83.5
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Ubuntu 20.04.3 LTS
Node.js version if running as node : 14.5.0
Database version : psql (PostgreSQL) 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

**Steps To Reproduce**
1. Create new column of type `LinkToAnotherRecord` in the table
2. Click `hasMany` radio and select child table
3. Tick `virtual relation` and save
4. After successful creation of the new virtual relationship column go to Meta management
5. Under Db Metadata, recreate metadata for the table.

**Expected behavior**
The virtual relationship should be kept intact after metadata recreation. but it doesn't exist on the table anymore.

**PS**
In debugging I found that `this.sqlClient.relationListAll()` does not return virtual hasMany relationships.

**Comment by o1lab** [comment]
When doing step 5 - before recreate, the current model has to be saved and then merged with actual model. And ```relationListAll``` only queries non-virtual relations from database (actual foreign keys)..

As discussed over the call - it would have some limitations like
- If a column has been renamed - there is no easy way to identify it. This will affect all places where that column was used 
filters, sort, fields, conditions in webhook etc. This case will be treated as column delete.
- Virtual relations can be difficult here even if one of the columns has been renamed - it will be treated as virtual relation  delete. And it will have to be recreated manually. If it is present, previous model will have to be merged with actual physical model.

**Comment by vijayrathore8492** [comment]
@o1lab I would still consider it as a bug as it changes the underlying database, and it adds a column to the referenced table. 
When the virtual relationship is lost by metadata recreation, the column still exists. 
IMO It brings the overall system into an inconsistent state. e.g. If you try to recreate the same virtual relationship manually, it will throw an error mentioning that column already exists.

**Comment by o1lab** [comment]
Thank you @vijayrathore8492 for showing the problem over a video call.

As discussed - I believe, the term recreate metadata is misleading. It should be 'reset metadata from database' which means loss of virtual parts of metadata.

As in previous comment, the goal is to retain the virtual parts of metadata. But please do understand, the schema diff and sync are larger problem on their own and there are standalone products for them and we are trying to provide them as a feature. We will improve the messaging on the metadata tab.

**Comment by o1lab** [comment]
Closing this as the findings are above.
