### ISSUE TITLE
🐛 Bug: File preview images do not display.

### ISSUE THREAD

**Issue by jyoketsu** [nocodb/nocodb#8532]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I deployed using docker-compose and accessed via HTTPS. When uploading files, the preview images do not display correctly because the file URLs are HTTP.

### Desired Behavior

In HTTPS mode, the URL of the preview images should also be HTTPS.

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.207.2**

### Attachments

<img width="396" alt="截屏2024-05-20 15 28 40" src="https://github.com/nocodb/nocodb/assets/20631967/90d66513-220c-4dba-b58f-67d710b95850">

**Comment by pranavxc** [comment]
By default, the URL is constructed from the request. If a proxy service is used in between, the URL will be extracted as `http`.  To override this behaviour, set the `NC_PUBLIC_URL` environment variable with your URL using `https`.

**Comment by jyoketsu** [comment]
> By default, the URL is constructed from the request. If a proxy service is used in between, the URL will be extracted as `http`. To override this behaviour, set the `NC_PUBLIC_URL` environment variable with your URL using `https`.

Thank you, this worked.
