### ISSUE TITLE
[Feature] Gantt view

### ISSUE THREAD

**Issue by chenshuichao** [nocodb/nocodb#854]
how to get these feature?

**Comment by dstala** [comment]
to be tracked under https://github.com/nocodb/nocodb/issues/141

**Comment by sorenwacker** [comment]
I am looking for this feature Grantt chart, but it's not in the current docker image. Do I need to run a different version to try this feature or was it removed again?

**Comment by wingkwong** [comment]
@sorenwacker Current we only support the below four views, this issue was closed due to duplicate. It's tracked in above-linked 141 instead.

![image](https://github.com/nocodb/nocodb/assets/35857179/4d4f4090-f46b-4a7e-9836-3d5a6bfb41f3)

**Comment by morandalex** [comment]
hey guys, seems planned not for the community edition...

![Image](https://github.com/user-attachments/assets/a1f69bdb-ce92-4ebb-885c-4d383278004a)

But I dont agree with . timeline should be open!!!
