### ISSUE TITLE
🐛 Bug: Views (join query generated) from a external source result in Errors

### ISSUE THREAD

**Issue by akrea** [nocodb/nocodb#8545]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a view with a join query in an external database (in my case timescale/postgres)
- Load external data source --> schema with the views in it
- Click on the view in nocodb

With the click I get e.g. (same for all multitable views, single table views work fine): 
```
[Nest] 11  - 05/22/2024, 7:37:56 AM   ERROR [DatasService] error: select ("cpu"."time" AT TIME ZONE CURRENT_SETTING('timezone') AT TIME ZONE 'UTC') as "cw4u63jvsypl0xu", "cpu"."cpu" as "c8v89xy9yilbu0q", "cpu"."host" as "csa3ofjbjoj67u8", "cpu"."usage_idle" as "c3i75lrzarq01fh", "cpu"."usage_iowait" as "cfy2silxltb37re", "cpu"."usage_system" as "cbipo5hbhn3i54k", "cpu"."usage_user" as "c90iqibr1u2r1xf" from "cpu" limit 200 - column cpu.cpu does not exist
[Nest] 11  - 05/22/2024, 7:37:56 AM   ERROR [GlobalExceptionFilter] Please check server log for more details
```

### Desired Behavior

The view should be displayed as intended.

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.205.1**

**Comment by akrea** [comment]
Update: In this Version

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.207.2**

The Problem does not exist.

**Comment by dstala** [comment]
@akrea thanks for the update. Will close this issue then.
