### ISSUE TITLE
🐛 Bug: Persistence not backing up to S3 on latest version of Noco

### ISSUE THREAD

**Issue by MoeDawood15** [nocodb/nocodb#8549]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Deploy as ECS task on FARGATE 

Set the following variables
NC_S3_BUCKET_NAME | AWS S3 bucket name for S3 storage plugin. |  
NC_S3_REGION | AWS S3 region for S3 storage plugin. |  
NC_S3_ACCESS_KEY | AWS access key ID for S3 storage plugin. |  
NC_S3_ACCESS_SECRET | AWS access secret for S3 storage plugin.

Deploy a new service 

Am I missing something , all my permissions are set correctly as this worked previously for me  with 

AWS_ACCESS_KEY | AWS access key ID for S3 storage plugin. |  
AWS_ACCESS_SECRET | AWS access secret for S3 storage plugin.

This is now deprecated 

### Desired Behavior

Folder with persistence should be created on S3

This worked fine on the older version

### Project Details

Noco DB used on AWS ECS Fargate

**Comment by pranavxc** [comment]
We changed the environment variable and deprecated the old one but forgot to add backward compatibility. We fixed it here - https://github.com/nocodb/nocodb/pull/8526, will make a bug fix release tomorrow with the change.

**Comment by MoeDawood15** [comment]
Hi 

Thank you for the prompt response 

I will try the image below and await the fix

**Comment by NViviers** [comment]
Hey, I'm working on the exact same environment as @MoeDawood15, pulling this image seems to help a little bit, but it causes further issues. Our existing user's account details are showing as incorrect, and using the "forgot password" feature gives me this error:
```
message: Request failed with status code 400

undefined
```

**Comment by pranavxc** [comment]
> Hey, I'm working on the exact same environment as @MoeDawood15, pulling this image seems to help a little bit, but it causes further issues. Our existing user's account details are showing as incorrect, and using the "forgot password" feature gives me this error:
> 
> ```
> message: Request failed with status code 400
> 
> undefined
> ```

Can you check the docker log and share if you found any error logs?

**Comment by NViviers** [comment]
Absolutely, I've attached the a CSV for the logs.
[log-events-viewer-result.csv](https://github.com/nocodb/nocodb/files/15412917/log-events-viewer-result.csv)

**Comment by pranavxc** [comment]
@NViviers: Can we connect over our discord channel ? https://discord.gg/5RgZmkW (my user id: @pranavxc)
