### ISSUE TITLE
🐛 Bug: Router Resolver Issues with all Docker Installs

### ISSUE THREAD

**Issue by Compg** [nocodb/nocodb#8560]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Attempt a fresh install of 0.207.2 running on local, new Amazon Linux ec2, and existing ec2 using a docker compose file with standard ports and volume mapping
- Appears to launch successfully and can login and create bases, but it’s riddled with errors when trying to use API, appstore, or access certain images.

It always throws GlobalExceptionFilter: Cannot get _____ or Notfound exception. 

![router resolver](https://github.com/nocodb/nocodb/assets/134229312/1d7eaed3-95b8-4b3e-b430-e1e3ee7121a2)

- Appears some of the default nestjs routes do not resolve. 
- On the Appstore page, I can see all images and the image url points to /dashboard/plugins/s3/png. 
- When I open the configuration, dashboard is not included in URL.

![logos](https://github.com/nocodb/nocodb/assets/134229312/99a21857-0099-4318-93a9-6194771c6977)

Examples: 

From Appstore Listing page: -> http://localhost:8080/dashboard/plugins/s3.png

![valid path](https://github.com/nocodb/nocodb/assets/134229312/a32f60d9-5653-452f-a5ce-eb102f80722c)

From Appstore S3 config page - >[localhost:8080/plugins/s3.png](http://localhost:8080/plugins/s3.png)

![broken path](https://github.com/nocodb/nocodb/assets/134229312/f783dbc5-0304-409c-978c-06f41c2d1e7e)

This holds true even if I explictly set the value of NC_DASHBOARD_URL=/dashboard

### Desired Behavior

All routes respect NC_DASHBOARD_URL. Images and API calls are impacted.

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.207.2**

## Error Message
![router resolver](https://github.com/nocodb/nocodb/assets/134229312/1d7eaed3-95b8-4b3e-b430-e1e3ee7121a2)

## All Images displayed
![logos](https://github.com/nocodb/nocodb/assets/134229312/99a21857-0099-4318-93a9-6194771c6977)

## Valid Path
![valid path](https://github.com/nocodb/nocodb/assets/134229312/a32f60d9-5653-452f-a5ce-eb102f80722c)

## Broken Path

![broken path](https://github.com/nocodb/nocodb/assets/134229312/f783dbc5-0304-409c-978c-06f41c2d1e7e)

**Comment by dstala** [comment]
@pranavxc is this related to https://github.com/nocodb/nocodb/pull/8573 ?

**Comment by pranavxc** [comment]
> @pranavxc is this related to #8573 ?

It's not related.
