### ISSUE TITLE
🐛 Bug: Webhook and Discord not working with handlebar

### ISSUE THREAD

**Issue by paolorota** [nocodb/nocodb#8563]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create a simple base
2. create a discord webhook
3. configure the webhook for the base (e.g., _after insert_)
4. test a handlebar

### Desired Behavior

The message is correctly prompted with and without handlebar

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.207.2**

### Attachments

This is the structure of the base:
![Screenshot 2024-05-23 at 18 46 26](https://github.com/nocodb/nocodb/assets/6144618/21a587d7-4a48-4eb1-8954-d0eba7ba1f2b)

This is the configuration of the webhook.
![Screenshot 2024-05-23 at 18 46 37](https://github.com/nocodb/nocodb/assets/6144618/0bd3b73d-d346-4020-8163-5400b2abe1cb)
Notice that the Sample Payload is generic (_"Title": "Sample Text",_) and not showing a sample (_"Title": "Some title"_),. Is this the problem? How can I solve it?

**Comment by dstala** [comment]
https://docs.nocodb.com/automation/webhook/create-webhook/#webhook-with-custom-payload-

Should be `{{ json event.data.rows[0].Title }}`

**Comment by paolorota** [comment]
This is not working. I tried multiple configurations but the handlebar is not resolved.
<img width="399" alt="Screenshot 2024-05-25 at 12 38 05" src="https://github.com/nocodb/nocodb/assets/6144618/540fe5b2-1672-4715-96a6-0ae7e0e7a887">
<img width="163" alt="Screenshot 2024-05-25 at 12 37 52" src="https://github.com/nocodb/nocodb/assets/6144618/a63a1f8e-3207-456c-8e1c-5e2a0f268b3f">

**Comment by BhuviTheDataGuy** [comment]
+1

**Comment by paolorota** [comment]
How can we reopen this? I don’t think they provided a solution…
