### ISSUE TITLE
Install nocodb with mysql error. Shows "services.nocodb.depends_on contains an invalid type" inside docker-compose.yml

### ISSUE THREAD

**Issue by rizomaa** [nocodb/nocodb#857]
I use:

NocoDB used as docker : yes, I  try to install the instance with docker-compose
NocoDB version : latest (cloned from github today) - commit: c50435c
Database used in NC_DB URL: mysql
OS on which NocoDB is running : ubuntu 16.04 
Node.js version if running as node : 16.13.1
Database version : Mysql 5.7.33

**Steps To Reproduce**
1. Follow the part https://docs.nocodb.com/getting-started/installation/#docker-compose
2. Launch: sudo docker-compose up 
3. See error: 

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.nocodb.depends_on contains an invalid type, it should be an array

```

**Expected behavior**
I expect there will not be errors

**Comment by pranavxc** [comment]
@rizomaa updated docker-compose file, please pull the latest changes and try it.

**Comment by pranavxc** [comment]
updated docker-compose files
