### ISSUE TITLE
When connecting to existing DB, FK relationships work properly. But if I get `Recreate Metadata` per table, the FK relationships don't show in CRUD table view

### ISSUE THREAD

**Issue by TechMasterElvy** [nocodb/nocodb#858]
NocoDB used as docker : false (heroku)
NocoDB version : 0.83.5

Database used in NC_DB URL  pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : heroku hobby dynamo
Node.js version if running as node : v12.22.6
Database version : 
* NoCoDB: PostgreSQL 13.5 (Ubuntu 13.5-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
* Project DB: PostgreSQL 14.1 on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, 64-bit

**Steps To Reproduce**
1. Connect to an existing DB that has FK relationships
2. All table CRUD views show proper UI to edit values of existing rows
<img width="837" alt="image" src="https://user-images.githubusercontent.com/40030320/145790596-c5ee68c9-7452-46cc-8288-01a90bbb7d08.png">
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/40030320/145790635-986bc169-fbb1-44fd-ac53-0787b8fe8122.png">
3. Recreate Table Metadata, the UI stops showing FK editors
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/40030320/145790651-a8b64a14-b6ee-4bdb-812d-bdea99eb8d12.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/40030320/145790663-b51a9001-43ce-4b77-b286-67218b1a1822.png">
<img width="626" alt="image" src="https://user-images.githubusercontent.com/40030320/145790671-ae183a93-75a0-45d5-a8da-40a5cc2f16a2.png">

**Expected behavior**
Whether I connect to an existing DB or hit recreate DB metadata, the CRUD Table grid should show the UI that respects existing FKs

Only workaround then is is to delete the project in nocodb and create a new one and connect to same DB to show the proper UI

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.83.5**

**Comment by o1lab** [comment]
Release 0.84.1 solves this
