### ISSUE TITLE
🔦 Feature Request : Have the ability to separate hundreds and thousands for numeric values 

### ISSUE THREAD

**Issue by jbricout007** [nocodb/nocodb#8589]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

It is difficult ti read in Nocodb numedic values because hundreds and thousands are not separable.
This feature would give an option to separate thoudans and hundreds in Nocodb to help users.

### Suggested Solution

Have a boolean for numeric values, giving the opportniy to separate billions, millions, thousands and hundreds in numeric values.

**Comment by dstala** [comment]
@jbricout007 have you tried out currency field? below is the screenshot with currency field locale set to en-US / USD. For different separators, you can try out different locale.

![Screenshot 2024-05-28 at 2 52 50 PM](https://github.com/nocodb/nocodb/assets/86527202/1b9707f6-d187-4764-b10c-a57a56d8d6c1)

does this help?

**Comment by jbricout007** [comment]
@dstala : yes, I noticed the currency field but most of these are not amounts, they are integer. 
We do not want to have a currency mentioned on it, we would be able to separate in the integer field also.
Moreover, we have a lot of formula on which we cannot change the formate : that's the reason why we need to apply it on other fields which are being used by these formula.

Thanks

**Comment by jbricout007** [comment]
Another point : it seems we cannot change the number of decimals in currencies, it is two.
We would like no decimals in these

Thanks !

**Comment by dstala** [comment]
@WarWolf47 for field type `number` and `decimal`, we can consider introducing `thousands separator` as an option.

**Comment by dstala** [comment]
@jbricout007 in our next OSS release, likely tomorrow
