### ISSUE TITLE
Column values become blank after naming the column that is in sort list

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#859]
**Steps To Reproduce**
1. Create a table ``TableA``
2. Create a column ``order`` with Number type
3. Input something. See Screenshot 1.
4. Add a sort option on ``order``. See Screenshot 2.
5. Rename ``order`` to ``order2``
6. The data under ``order2`` becomes blank. See Screenshot 3.

P.S. It affects both GQL / REST projects. Renaming back to ``order`` or removing the filter would resolve the problem but we need better handling here.

**Expected behavior**

**Screenshots**

Screenshot 1:

![image](https://user-images.githubusercontent.com/35857179/145811140-8b3db28b-f4da-4ecd-88ab-951e5a3b0182.png)

Screenshot 2:

![image](https://user-images.githubusercontent.com/35857179/145811240-603c911d-e373-4dce-a5f7-d319e1def08f.png)

Screenshot 3:

![image](https://user-images.githubusercontent.com/35857179/145811268-7730841d-f252-48b1-868e-e960afb3e24d.png)

Node: **v14.18.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.83.5**

**Comment by pranavxc** [comment]
Fixed in `0.83.6`
