### ISSUE TITLE
🔦 Feature:  Documentation clarification request regarding "This feature is available only in the paid plans."

### ISSUE THREAD

**Issue by brandondrew** [nocodb/nocodb#8610]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Regarding other issues: I did a search for "This feature is available only in the paid plans." and nothing appeared in the results.

On the forms view page (https://docs.nocodb.com/views/view-types/form/) there is a statement regarding the removal of branding, stating that branding removal is only available on paid plans.  This seems to imply that it is not available in the open source NocoDB that we can host ourselves, but that is not 100% clear. So my question:

Does this statement only apply to the hosted service, or does the exclusion of branding removal also apply to the open source version, leaving us unable to remove branding even when we host NocoDB ourselves?

### Suggested Solution

Ideally the documentation should make this clearer.

**Comment by brandondrew** [comment]
It would be quite disappointing if the open source version has this feature removed, since the main thing that attracted me to NocoDB was the fact that it appeared to avoid the games everyone else plays of removing important features from the open source version.

I like very much that (from what I've seen) NocoDB "Enterprise" features are _actually_ things that mainly only large companies are likely to care a lot about.

**Comment by dstala** [comment]
@brandondrew Cloud only features are marked with a ☁ icon on the documentation page.

**Comment by brandondrew** [comment]
Your answer is not entirely clear either.  You made a statement that perhaps you thought implied an answer to my question, but I apparently lack whatever background knowledge would allow me to draw the inference you intended me to draw.  If possible, an explicit answer would be preferable.

I don't see the cloud icon either in that info box or next to the heading for that feature, so does that mean that the open source version is also able to remove branding????

**Comment by dstala** [comment]
@brandondrew 

Option to remove branding will be available only on paid plans (both in cloud-hosted & self-hosted case). We are working on providing a license mechanism for self hosted users to use add-on advanced & enterprise features. 

Will update documents accordingly to clarify this aspect.

**Comment by dstala** [comment]
Docs updated

**Comment by carrete** [comment]
> Docs updated

Where? To say what? I'm really confused too (after reading each comment in this issue). How is it possible that AGPL licensed software could disallow some kinds of source code modification?
