### ISSUE TITLE
🐛 Bug: Broken Links on https://docs.nocodb.com/fields/fields-overview/

### ISSUE THREAD

**Issue by brandondrew** [nocodb/nocodb#8611]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Go to https://docs.nocodb.com/fields/fields-overview/
2. Scroll down to the section on Formulas
3. Follow any of the links
4. Notice that they are broken, for example https://docs.nocodb.com/fields/fields-overview/field-types/formula/formula gives a 404 error.

### Desired Behavior

Those links should lead to actual pages, not 404s.

### Project Details

Not applicable

**Comment by o1lab** [comment]
@brandondrew Thank you so much for reporting this. We will fix them.

Here is a sample link for time being 
- https://docs.nocodb.com/fields/field-types/formula/formula

As a work around you can use CMD+K to search the docs
