### ISSUE TITLE
🐛 Bug: field sorting will send two requests in weak network

### ISSUE THREAD

**Issue by chavyleung** [nocodb/nocodb#8613]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![CleanShot 2024-05-30 at 16 12 51](https://github.com/nocodb/nocodb/assets/29748519/24d8baa3-098a-4b59-83db-256b4dd8ed6a)

### Desired Behavior

Send request only once

### Project Details

Node: **v18.19.1**
Arch: **x64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.207.3**

**Comment by dstala** [comment]
@pranavxc to review #8614
