### ISSUE TITLE
Better rendering of LongText rows in Gallery View. 

### ISSUE THREAD

**Issue by kristinbb** [nocodb/nocodb#862]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.83.5**

**Steps To Reproduce**
1. Create a table. 
2. Create a LongText column in the table with some long text (> 200 characters). 
3. Choose Gallery View on top of this table. 

**Expected behavior**
In Gallery View, the long text columns runs out of the card assigned to each row in the table.

**Comment by pranavxc** [comment]
Fixed in `0.84.2`
