### ISSUE TITLE
🐛 Bug: External data source options not available in 0.207

### ISSUE THREAD

**Issue by maximemoreillon** [nocodb/nocodb#8621]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I can't see the option to connect to an external data source in NocoDB v0.207.3. either on new bases or existing ones:

![image](https://github.com/nocodb/nocodb/assets/29086128/d03ccac2-fc1a-4cdd-aadc-3fc6b31ca22d)

### Desired Behavior

Options for connecting to an external data source was available in my previous install, using 0.205.1

![image](https://github.com/nocodb/nocodb/assets/29086128/0aef6568-dc24-4f0c-8f16-572b75898d6f)

### Project Details

- NocoDB used as Docker: true
- NocoDB version 0.207.3
- Database used in NC_URL: Postgresql

**Comment by o1lab** [comment]
https://docs.nocodb.com/data-sources/connect-to-data-source/

**Comment by maximemoreillon** [comment]
Oh my bad, I wasn't aware the options had been moved

Sorry about the confusion and thanks for your reply!
