### ISSUE TITLE
🐛 Bug: count api sometimes returns 0

### ISSUE THREAD

**Issue by sjad5241** [nocodb/nocodb#8631]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

i called count  nocodb  api several times and sometimes it return 0 for me but i know the result is not 0

### Desired Behavior

i want to always count api return a reliable response for me

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.204.0**

**Comment by dstala** [comment]
@sjad5241 few more queries to help us narrow down 
- How many records exist in your DB?
- How frequently did you trigger API?
- Did you connect to external DB?

**Comment by pranavxc** [comment]
@sjad5241: It looks like you are using an older version of nocodb. Please upgrade to the latest version and let us know if you are still facing any issues after the upgrade.

**Comment by dstala** [comment]
@sjad5241 please reopen this thread if you are able to reproduce this issue with v0.207.3+
