### ISSUE TITLE
🐛 Bug: Cell drag is not resulting in audit entries

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#8641]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

<img width="833" alt="image" src="https://github.com/nocodb/nocodb/assets/5435402/18cb30b8-74ae-4e69-ab33-51ad552ad753">

### Desired Behavior

.

### Project Details

.

**Comment by dstala** [comment]
![Screenshot 2024-06-27 at 5 58 46 AM](https://github.com/nocodb/nocodb/assets/86527202/54cf0322-b734-40b4-8d7c-4d4759fcf387)
![Screenshot 2024-06-27 at 5 58 26 AM](https://github.com/nocodb/nocodb/assets/86527202/0ac594dd-9489-4cc5-8350-26037b192da4)
