### ISSUE TITLE
🔦 Feature: The color of scrollbar need to be more obvious.

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8659]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

- In default view, the color of scrollbar is dark enough.
![image](https://github.com/nocodb/nocodb/assets/48933981/b697fa0c-00aa-4713-acc5-be3891c6a230)
- But when we group by the table, the color of scrollbar is too light, and it is hard to recognized.
![image](https://github.com/nocodb/nocodb/assets/48933981/05e541e7-8e08-4214-8769-080005ef724c)

### Suggested Solution

The color of scrollbar need to be more obvious.

**Comment by WarWolf47** [comment]
@dstala are these changes done?

**Comment by TangXY123** [comment]
@dstala hi, may I repair this issue myself?

**Comment by dstala** [comment]
if you want to help with a PR, go ahead. otherwise- will follow up and get it fixed in our next release

**Comment by TangXY123** [comment]
> if you want to help with a PR, go ahead. otherwise- will follow up and get it fixed in our next release

I notice that it has been fixed in the newest 'develop' branch, thank you guys!
