### ISSUE TITLE
Automations "Send Email" doesn't retain input fields

### ISSUE THREAD

**Issue by TechMasterElvy** [nocodb/nocodb#866]
NocoDB used as docker : false (heroku)
NocoDB version : 0.83.6

Database used in NC_DB URL  pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : heroku hobby dynamo
Node.js version if running as node : v12.22.6
Database version : 
* NoCoDB: PostgreSQL 13.5 (Ubuntu 13.5-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
* Project DB: PostgreSQL 14.1 on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, 64-bit

**Steps To Reproduce**
1. Go to any table
2. Open `Automations`
3. Create new `Automation` and set `Notification` to `Email`
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/40030320/145886704-bb9adfb1-b3dd-47ac-8972-eafb7572f62c.png">
4. Close `Automations` modal window
5. Re-open `Automations` modal window

**Expected behavior**
Modal should show all the fields that have been set

** Actual Behaviour**
Automation fields have been reset
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/40030320/145886820-58561aeb-e0a9-47ea-bd6e-b7b639fc983e.png">

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.83.6**

**Comment by pranavxc** [comment]
Fixed in `v0.84.1`
