### ISSUE TITLE
🐛 Bug: Webhook delete payload is only visible columns

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#8667]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Execute After Delete Webhook, only visible columns are sent

### Desired Behavior

All columns should be sent.

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.207.1**

**Comment by emre1e** [comment]
This is becoming really critical

We have webhooks that are reverting changes upon deletion, and now we can't do it anymore. Some fields are just not included in the webhook call now. We need to make everything visible to get it to work.

**Comment by emre1e** [comment]
@dstala any news on this topic? 
I don't think it was intentional.
Webhooks are still only transmitting visible data. This is fatal when dealing with a large amount of data.

**Comment by dstala** [comment]
@emre1e - will discuss with the team & update. Agree, we should ideally be sending complete record

**Comment by emre1e** [comment]
@dstala any news? It got so critical :( All the webhooks now failing and i cant do anything. Its only submitting whats is visible in view :(

**Comment by dstala** [comment]
@emre1e this item is listed for next release. will keep you posted once we fix here
