### ISSUE TITLE
🐛 Bug: After creating the project, the entry to create the data source cannot be found

### ISSUE THREAD

**Issue by xy-qimu** [nocodb/nocodb#8669]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Deploy with docker

### Desired Behavior

Deploy with docker

### Project Details

Deploy with docker

### Attachments

![image](https://github.com/nocodb/nocodb/assets/46561657/5dde0ebe-72b2-4998-879d-74f7c0991447)

**Comment by o1lab** [comment]
https://docs.nocodb.com/data-sources/connect-to-data-source
