### ISSUE TITLE
[Feature] Allow filtering on "LinkToAnotherRecord" field

### ISSUE THREAD

**Issue by rona-62** [nocodb/nocodb#868]
I'm trying to implement a "tags" field. I've tried with multiselect but with that is difficult to add new tags.
So I've tried with LinkToAnotherRecord field type linking to a second Tags table and it works very well. The only problem is that is not possible to filter on it making it not very useful.

**Comment by flemay** [comment]
I was doing something similar as well.
- Searching `LinkToAnotherRecord` and `Lookup` columns would be very handy
- Multiple selection would also be convenient. Imagine you have 100 tags to choose from and you want to tag a specific row with 50 tags, that's a lot of clicking!

**Comment by jfacemyer** [comment]
+1

**Comment by kingbling** [comment]
+1 this is one of the feature why we used airtable at all. easy for people with no understanding whatsover getting list with crossreferences.

also comparing to airtable the listview should have either an infiinite scroll or more than 25 rows. anyway this one is less important

**Comment by splieseis** [comment]
+1

**Comment by myGitMaster** [comment]
+1

**Comment by kulukyo** [comment]
+1
need this feature

**Comment by nilsreichardt** [comment]
Please don't write `+1`. Instead, use the thumbs up reaction (👍) to the ticket because they are relevant if you want to sort the ticket by the most thumbs up.

**Comment by o1lab** [comment]
Good point @nilsreichardt

**Comment by jfacemyer** [comment]
+1

JUST KIDDING! Going to use the thumb right now!

**Comment by o1lab** [comment]
This is available since version 0.90. I guess there was a duplicate issue that I did close. However, the filtering works if it does not have more than one linkToAnotherRecord field. For multiple - there is an [issue opened today](https://github.com/nocodb/nocodb/issues/1799).
