### ISSUE TITLE
🐛 Bug: NocoDB API Snippets Broken

### ISSUE THREAD

**Issue by springfielddatarecovery** [nocodb/nocodb#8685]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Make a database at nocodb.com
2. Go to 'details' at top
3. Go to 'API Snippets'
4. All snippets provide a header with `xc-auth` but this will get you an "authorization" error. `xc-auth` needs to be renamed to `xc-token` to work

### Desired Behavior

The API request should be successful

### Project Details

Nocodb hosted at nocodb.com

**Comment by o1lab** [comment]
Its already xc-token in the cloud - what version are you on ? We recently updated this.

**Comment by springfielddatarecovery** [comment]
I am on a cloud-hosted version at nocodb.com. The snippets are still showing the old xc-auth header instead of xc-token

**Comment by dstala** [comment]
tried in cloud. could find xc-token in all snippets. reopen this thread if you still see issue persisting.

**Comment by springfielddatarecovery** [comment]
Just letting you know I can confirm this issue is fixed on our end thank you!!! 🫡
