### ISSUE TITLE
[Feature] Allow editing fileds if SQLite database is being used.

### ISSUE THREAD

**Issue by rona-62** [nocodb/nocodb#869]
For my project is good enough to use SQLite since is very small and just used internally for hobby. The problem is that I cannot edit fields after creating them, an overlay appears stating "This spreadsheet is connected to an SQLite DB. For production please see <here>."
By removing temporarily the css overlay I was actually able to edit the fields without problems, so I'm not sure why it is forbidden.
In any case maybe there could be a setting to disable the block if someone wants and is aware of the eventual risks, without resorting to temporary and complicated tricks.

**Comment by dittorahmat** [comment]
Hi @rona-62 ,

Can you share your temporary css overlay trick ? I'm having the same problem as you were.

**Comment by vladkrutenyuk** [comment]
So smb has solved this problem?( its awful that i cant change variants for multiselect and etc. (It doesnt matter for me what DB  - I choose SQLite bcs it was first variant) HELP PLS

**Comment by vladkrutenyuk** [comment]
What shall I do? dont understand where is "removing temporarily the css overlay" :(

**Comment by UbioZur** [comment]
Same issue here, with the added that cliking on the 'here' does not open the page...

If the user usage is good enough with sqlite, then the user should be able to use nocodb to it's full extent.
If it's a test/dev environement using sqlite, then the user should be able to edit the fields to set such environment and/or learn and/or test the tool.

As it stand right now, any testing to see if nocodb can fit the need is invalidated as it cannot edit the fields...

> This spreadsheet is connected to an SQLite DB
Exactly how I installed it to use SQLite. So let see what the doc says for a production setup.

> By default, SQLite is used for storing meta data.
Sound like a default that is good enough for my need in production...

> However, you can specify your own database.
I am happy with the default, so even if I **can** I don't need to.

So the default for the production setup (to create a SQLite Database), with the **option** to change to another database (more options are always amazing). But that **option** is not so optional...


@vladkrutenyuk @dittorahmat
> What shall I do? dont understand where is "removing temporarily the css overlay" :(

You can right click on it and select inspect. you will see the html and css. you can find the div `<div data-v-5f934a18="" class="disabled-info">` and by clicking on it you can have the css for disabled-info.
You can edit it from `display: flex;` to `display: none;`

**Comment by aGolduck** [comment]
Same issue here. I specify a customized sqlite NC_DB and same message received.
