### ISSUE TITLE
🐛 Bug: qrcode and barcode are not exported.

### ISSUE THREAD

**Issue by Tatametheus** [nocodb/nocodb#8696]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create qrcode or barcode filed.
2. Download Excel

### Desired Behavior

/

### Project Details

/

**Comment by dstala** [comment]
@Tatametheus for QR & Bar code fields - download CSV will pull associated source field information. Downloading image if required needs to be triggered manually from the UI.
