### ISSUE TITLE
🔦 Feature: Export all the content of a table in only one csv/xls file

### ISSUE THREAD

**Issue by jbricout007** [nocodb/nocodb#8698]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

We would like to export an entire table in only one xls or csv file from NOCODB.
At the time, it seems not to be possible to have all values in only one xls or csv file We have to concatenate manually.
For example, we do have 9064 lines in our main table.

We have already tried to change the settings "DB_QUERY_LIMIT_MAX" or "NC_EXPORT_MAX_TIMEOUT" but it did not worked.

Thanks for your help.

### Suggested Solution

Having the ability to export all the content of a table in one xls or csv file, instead of on file per page

### Additional Context

NOCODB VERSION : 0.204.0

**Comment by jbricout007** [comment]
Hi @dstala : this is a very convenient feature !

Could you please confirm the version of Nocodb thaht will give the opportunity to use it ? I will foresee an upgrade.

**Comment by springfielddatarecovery** [comment]
This issue is still happening for us. Using "filter" gets records exported to a single CSV, but if we use the search function at the top right, it still tries to export to multiple CSVs (one for each page) even if only  a single record is found.
