### ISSUE TITLE
🐛 Bug: drag icon click on cell changes updated-at time

### ISSUE THREAD

**Issue by kangjianhua** [nocodb/nocodb#8702]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![1718186968478(1)](https://github.com/nocodb/nocodb/assets/8625261/c7b50960-f174-460f-8561-b14673b662fb)
Clicking this button updates the value of the entire column and changes the UpdatedAt time for the entire table

### Desired Behavior

Clicking this button will update the value of the entire column and change the UpdatedAt time of the entire table so that we can't use it for project management,

### Project Details

Clicking this button will update the value of the entire column and change the UpdatedAt time of the entire table so that we can't use it for project management,

### Attachments

Clicking this button will update the value of the entire column and change the UpdatedAt time of the entire table so that we can't use it for project management,

**Comment by dstala** [comment]
@kangjianhua i tried it out, attaching video. didn't see any issue with the drag icon click. can you help us with more details + your base information.

https://github.com/nocodb/nocodb/assets/86527202/c1d8ff0c-fedc-4506-8ec9-6eefcd85fbf7

**Comment by dstala** [comment]
@kangjianhua reopen this thread if issue is still reproducible on your end. Please also append project details when you append.

https://docs.nocodb.com/FAQs#how-to-check-my-project-info-
