### ISSUE TITLE
🐛 Bug: Unable to download csv or excel when column with attachment is present

### ISSUE THREAD

**Issue by Juvls** [nocodb/nocodb#8717]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Same issue than described here 5552 but issue is closed.

If you select a view with a column type "Links" pointing to a image (attachment field), see below and you try to download data csv or Excel, you have the error **(t || []).map is not a function** 
<img width="218" alt="image" src="https://github.com/nocodb/nocodb/assets/12261309/17fce420-af1a-4cf5-b587-74040fb10637">

I can see the following error in the log
TypeError: (t || []).map is not a function

at w (/usr/src/app/docker/main.js:2:1017680)

at /usr/src/app/docker/main.js:2:1018144

at Array.map (<anonymous>)

at w (/usr/src/app/docker/main.js:2:1018130)

at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

at async v (/usr/src/app/docker/main.js:2:1019257)

at async t.extractXlsxData (/usr/src/app/docker/main.js:2:1020205)

at async DataAliasExportController.excelDataExport (/usr/src/app/docker/main.js:2:335017)

est] 3  - 06/13/2024, 11:55:25 AM   ERROR lobalExceptionFilter] (t || []).map is not a function

### Desired Behavior

Be able to download the data even with this column, it should probably be just ignored for the export as it's an attachment.

### Project Details

NoCoDB on Docker, runs latest 0.207.3 via https://www.pikapods.com, I don't have more details available.

**Comment by o1lab** [comment]
Thank you @Juvls for all the details. We will have this fixed.

**Comment by mertmit** [comment]
This is fixed in #9010
But it caused a side effect to avoid some looked up attachments which will be fixed with #9151
