### ISSUE TITLE
🔦 Feature: Expand all / Collapse all feature for group by view.

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#8722]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

https://community.nocodb.com/t/default-expansion-of-grouped-data-cards/1209

> Question about viewing data when it is “Grouped” by a particular column. The groups are presented in these expandable/collapsible cards, which is very nice. However, is it possible to have them be expanded by default? Or even to select all then expand? I’m dealing with a situation where I could have 100+ of these cards and expanding them all manually every time is not ideal.

### Suggested Solution

Ability to toggle grouped by rows into expanded or collapsable state. The option can be part of either group by menu itself.

**Comment by saran-gogosoon** [comment]
any update on this?

**Comment by saran-gogosoon** [comment]
Sorry for my previous comments, after digging deep with source code I found this is already available, just adding screenshot here so others can utilize this...

Hover the mouse near count, you will get the option to expand all

![Image](https://github.com/user-attachments/assets/1cf8ce0e-7d6f-4e0c-97fa-f03519bc8aa9)

**Comment by kjanel** [comment]
I have the same issue as @rwong01 - I only see "Expand group" when I click on the 3 dots, there isn't any "Expand all" option

**Comment by Orsova** [comment]
I get nothing at all.
