### ISSUE TITLE
🐛 Bug: After upgrading to 0.250.1 -> search doesn't work

### ISSUE THREAD

**Issue by memellow85** [nocodb/nocodb#8738]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I upgraded my Docker installation of NocoDB to 0.250.1 - after start the search box into link fields doesn't works.
<img width="578" alt="Screenshot 2024-06-13 at 23 13 52" src="https://github.com/nocodb/nocodb/assets/41187263/ef5ce8a9-3185-4449-ab6f-8b5667724d8f">

### Desired Behavior

The search box it's works

### Project Details

Node: **v20.12.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.250.1**

### Attachments

<img width="578" alt="Screenshot 2024-06-13 at 23 13 52" src="https://github.com/nocodb/nocodb/assets/41187263/679d21f7-88d8-4a3f-9d08-99ab8bc30205">

**Comment by o1lab** [comment]
We 've a fix for this and should be released tomorrow.

**Comment by memellow85** [comment]
Thanks.
