### ISSUE TITLE
D.O. Spaces plugin fails with "null" popup

### ISSUE THREAD

**Issue by jfacemyer** [nocodb/nocodb#875]
**Please enter the following details**

Node: **v17.2.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.83.8**

**Steps To Reproduce**
1. App Store
2. Spaces
3. Enter auth data and click "test"

I get a pink "null" popup.

If I put in an incorrect bucket / key, I just get the "null" popup.

I also get a bunch of console messages like:
`Cookie “tk_or” will be soon treated as cross-site cookie against “http://ndb.impressusart.com/dashboard/?q=sqlOp_xcPluginTest” because the scheme does not match.`

If I change the Region to an unknown region I get an error:
`Hostname/IP does not match certificate's altnames: Host: ***.nyc3d.digitaloceanspaces is not in the cert's altnames: DNS:*.com.com DNS:com.com`

No matter what creds I put in, uploads also give me the "null" popup.

**Expected behavior**
Some sort of success or failure message, and success with correct credentials.

**Screenshots**

**Comment by DarkPhoenix2704** [comment]
Hii @jfacemyer 

We have refactored all the storage plugins and verified that all of them works. Please try latest version and reopen if the issue still exists.
