### ISSUE TITLE
🐛 Bug: Unable to delete user (`Table not accessible from this scope`)

### ISSUE THREAD

**Issue by salim-b** [nocodb/nocodb#8750]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

After updating from NocoDB v0.207.3 to v0.250.1, user cannot be deleted anymore. An API call to [`DELETE /api/v1/users/{userId}`](https://docs.nocodb.com/0.109.7/developer-resources/rest-apis/#meta-apis) fails with HTTP 400 Bad Request and message

```
Table not accessible from this scope
```

### Desired Behavior

User deletion should work as in previous versions.

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.250.1**

### Attachments

[Bildschirmaufzeichnung vom 14.06.2024, 12:50:37.webm](https://github.com/nocodb/nocodb/assets/20040931/420f0201-633e-4ad5-98a4-0ef7f1c15aab)

**Comment by mertmit** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/8742

It will be released soon
