### ISSUE TITLE
Causes Safari to Freeze

### ISSUE THREAD

**Issue by itopaloglu83** [nocodb/nocodb#8760]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

This is a rather strange but so please bear with me.
1. Open Safari and navigate to NocoDB cloud or any other installation.
2. Stay on that tab for at least 90 seconds clicking around.
3. After a while, usually 90 seconds mark, Safari freezes.

### Desired Behavior

Safari compatibility.

### Project Details

- Apple MacBook Pro with M1 Pro and macOS Sonoma 14.5 (latest)
- Safari with no extensions or DNS level filtering.
- The tab freezes and stops responding to user actions and the user cannot even refresh, a new tab must be opened afterwards.
- No other errors or messages in the developer console. 

### Attachments

I couldn't upload the full video due to 10MB size limit so the video below starts at the 1:15 mark. You can see the hover effects disappearing towards the end and as I click on various items nothing happens. 

https://github.com/nocodb/nocodb/assets/461270/5685e4cb-0e97-4d01-a6df-8c457d2478db

**Comment by itopaloglu83** [comment]
It might be a problem with my computer as well. I just don’t have any other device to test with.

**Comment by christiankriedemann** [comment]
Same here on a Apple M3 Pro with Sonoma 14.5 (23F79) and Safari 17.5 (19618.2.12.11.6). 
Nocodb runs as a Docker Container on my Debian Server.
It works for me when I switch to Google Chrome temporarily.

**Comment by o1lab** [comment]
Have narrowed down the scenario - if we go to kanban and back to project home screen. The clicks freeze after like 5-10 seconds. Otherwise they mostly function.

**Comment by itopaloglu83** [comment]
I wasn't able to replicate the kanpan path, but it seems like switching to another tab expedites the issue. 

Here's the bare minimum way I was able to replicate it.
- Navigate to app.nocodb.com
- Wait for over 90 seconds without interacting with the page.

I believe this might be related to how Safari stops the execution of background tabs, especially when they are invisible. 

Another interesting thing is the polling request getting stuck right around the same time. So I blocked the `api/v1/notifications/poll` endpoint which seems to alleviate the issue.

<img width="1304" alt="Screenshot 2024-06-15 at 11 01 52" src="https://github.com/nocodb/nocodb/assets/461270/0a373e09-0d81-485d-ba7b-9f7b332c8c48">

**Comment by christiankriedemann** [comment]
For me, the tab freezes after I have worked in another tab and return. 
Sometimes while I am working in nocodb
Interestingly, it doesn't seem to occur when I have the web information (CMD + OPTION + I) open.

**Comment by itopaloglu83** [comment]
I'm not familiar with the code base but it looks like 55425f57de2eabb31fdeee193be407c3604d9138 made the `pollNotifications` function recursive. Check L31 below.

https://github.com/nocodb/nocodb/blob/30aa5fdf3a1fb810dc73183215dadff3a3018e8a/packages/nc-gui/store/notification.ts#L19-L36

This might be the issue, I'm going to update the code to see what if it removes the issue.

**Comment by itopaloglu83** [comment]
Works like a charm. Replacing `await pollNotifications()` with `setTimeout(pollNotifications, 0)` resolved the issue. I used the following sed command to update the compiled code in place.

``` Bash
sed -i 's/await i()/setTimeout(i, 0);/g' /usr/src/app./node_modules/nc-lib-gui/lib/dist/_nuxt/BVffXuyZ.js
```

**Comment by christiankriedemann** [comment]
> Works like a charm. Replacing `await pollNotifications()` with `setTimeout(pollNotifications, 0)` resolved the issue. I used the following sed command to update the compiled code in place.
> 
> ```shell
> sed -i 's/await i()/setTimeout(i, 0);/g' /usr/src/app/./node_modules/nc-lib-gui/lib/dist/_nuxt/BVffXuyZ.js
> ```

Thank you very much @itopaloglu83 it works for me too. I ran your sed command inside my Docker container and it works like a charm. 👍🏻

Chrome needs 3-5 times more RAM, compared to Safari, for the same Websites open. So i use Chrome only if really necessary.

**Comment by DarkPhoenix2704** [comment]
```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.250.2-pr-8772-20240616-1919
```


Can you verify if this image fixes the issue

**Comment by christiankriedemann** [comment]
Yes, it works flawlessly for me too

**Comment by o1lab** [comment]
Thank you @itopaloglu83 @christiankriedemann for lending a helping a hand here.
