### ISSUE TITLE
🐛 Bug: NocoDB ignores end date for calendar view

### ISSUE THREAD

**Issue by xonacs** [nocodb/nocodb#8785]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I am uploading a CSV file that includes the below fields:

AppointmentData,StartDate,EndDate
XYZABC,14/06/2024  08:00:00, 14/06/2024  18:00:00
WACABC,15/06/2024  09:00:00, 15/06/2024  11:00:00

I can correctly get the calendar view to show the  entry at the right start time, but EndDate is ignored and view shows everything as being 30 minutes...

### Desired Behavior

Show correct start/end on calendar view.

### Project Details

NocoDB Cloud

**Comment by dstala** [comment]
@xonacs NocoDB calendar view currently doesn't support date & date-time range. issue requested will be tracked in this feature request https://github.com/nocodb/nocodb/issues/8583
