### ISSUE TITLE
🐛 Bug: When trying to add a new option in a Single select, the first option value is updated as well

### ISSUE THREAD

**Issue by AlexandreBonneau** [nocodb/nocodb#8790]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Have a single select already configured from a previous NocoDB install (where it was created from the NocoDB UI)
2. Have the first option selected as the default value
3. Click "Add option", and start typing
4. -- Faulty behavior starts here --
5. While typing your new option value, the very first option is modified at the same time (leading to the warning message "Select options can't have duplicates"

Do note that if you type your new option name "foo", then the first option is renamed "foo", but you can then go edit the first option back to its original name....however as soon as you type some text in the new option field, the very first field is updated again.

![2024-06-18_114953_Screenshot](https://github.com/nocodb/nocodb/assets/7248877/47fc4cd3-8917-40c8-b4ad-ae7923dead4a)

This effectively makes single select element hard to use since you need to save the initial first value somewhere, edit the new option name, then edit back the first value, then save. This way it works.

### Desired Behavior

Be able to add new option without it changing the value of the other options.

### Project Details

NocoDB docker : true
NocoDB Version : not sure how to check that since it does not seem to be written on the web pages
NC_DB : pg
New project from the UI
Running on Linux

**Comment by dstala** [comment]
@AlexandreBonneau This seems to be an issue with older version. Can you help us confirm if you are on the latest docker?
Version can be checked using base context menu
https://docs.nocodb.com/FAQs#how-to-check-my-project-info-

**Comment by AlexandreBonneau** [comment]
This is the version I'm running :
Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.250.2**

**Comment by dstala** [comment]
@AlexandreBonneau Issue reproducible when working with MultiField Editor. Works fine on grid (if you need a workaround for now). We will fix it in our next release, likely by Monday
