### ISSUE TITLE
🔦 Feature: Import CSV - skip field mapping during import

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#8796]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Field mapping during import process is prone to errors -- more so when we are handling different date-time formats & select based fields. Identifying such errors during CSV data import is hard.

### Suggested Solution

- Skip field mapping during CSV import (not upload) 
- All the fields will be imported either as Single line text or Long text
- Post import, User can selectively convert fields to required types as required. Errors over here are easier to identify and manage.

**Comment by dstala** [comment]
Related
https://github.com/nocodb/nocodb/issues/8794

**Comment by dstala** [comment]
- [ ] disable field type mapping; on hover, show tooltip `Use field edit menu for type conversions after file is imported`
- [ ] icon alignment in buttons to add new fields; we can even remove these. @o1lab ?
- [ ] remove options to configure `number of records to infer datatype`
- [ ] disable `auto select field type` -- mark it as `coming soon`

![Screenshot 2024-06-29 at 9 56 37 AM](https://github.com/nocodb/nocodb/assets/86527202/2e1509b6-c0a8-4fdb-a995-8682d6d6f200)

![Screenshot 2024-06-29 at 9 55 39 AM](https://github.com/nocodb/nocodb/assets/86527202/cef23c02-2b8f-40ed-a263-ffd0919f1755)

**Comment by candideu** [comment]
Are there any plans to bring this feature back? It would save a lot of time, and is something that Airtable does out of the box.

**Comment by dstala** [comment]
@candideu not immediately. we did face good number of issues with our end users with auto type detection & conversion. current approach helps user clearly understand what step went wrong during the process. i will discuss with the team if we can enable the earlier approach under a feature flag.
