### ISSUE TITLE
Upload CSV Import Error

### ISSUE THREAD

**Issue by SyedAsadKazmi** [nocodb/nocodb#880]
NocoDB used as docker : false
NocoDB version : 0.83.8
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : New Project
Database on which spreadsheet is created : sqlite3 
OS on which NocoDB is running : Ubuntu 20.04.3 LTS
Node.js version if running as node : v14.13.0
Database version : 3.33.0

**Steps To Reproduce**
1. Go to New/Existing Project -> Tables -> New/Existing table
2. Click on Action -> Upload CSV -> Select any csv file having all the required columns (id, title) -> Import
3. See error: 

     POST /nc/xyz_op0t/api/v1/xyz/bulk 400 40 - 7.051 ms
     .returning() is not supported by sqlite3 and will not have any effect.

**Expected behavior**
The selected CSV file is supposed to be imported and shown as table.

**Screenshots**

![Screenshot from 2021-12-18 23-31-02](https://user-images.githubusercontent.com/36279345/146651266-7e51be31-3aa1-4a6b-9177-5e23ea214762.png)

![Screenshot from 2021-12-18 23-32-22](https://user-images.githubusercontent.com/36279345/146651350-7953badf-56a1-44f2-b56d-2f9b30bd2a7c.png)

![Screenshot from 2021-12-18 23-32-26](https://user-images.githubusercontent.com/36279345/146651360-ee56d427-3ec1-4829-829b-8ca782485111.png)

![Screenshot from 2021-12-18 23-32-46](https://user-images.githubusercontent.com/36279345/146651370-77eb6eeb-b2ee-408b-bded-764eb4a50dee.png)

![Screenshot from 2021-12-18 23-32-49](https://user-images.githubusercontent.com/36279345/146651378-4c2081b4-1ac8-4776-87c2-e75c4b263f4e.png)

![Screenshot from 2021-12-18 23-33-14](https://user-images.githubusercontent.com/36279345/146651386-34f51369-98ae-48b0-974b-69b3e305fd77.png)

**Comment by pranavxc** [comment]
You have to choose the destination column from the dropdown

**Comment by ArjonBu** [comment]
@pranavxc I have another issue with importing where it says that I need to select a field for the mandatory "id" column but even if I select it, the error doesn't go away and the import button is not clickable.

**Comment by oisidnel** [comment]
same problem - this project looks amazing but CSV import is not working properly
I tried it with several CSVs on the one click heroku deployment

**Comment by Kuuchuu** [comment]
Same issue as @ArjonBu
I'm unable to upload any of my existing data as a csv. Status 400 when doing so.

**Comment by sangroxx** [comment]
![image](https://user-images.githubusercontent.com/10852022/147924589-c13307c5-7bf5-41be-941f-d61ae15931fb.png)

Hi, got the same problem.

**Comment by pranavxc** [comment]
Improved cdv import in `v0.84.5`

**Comment by spencerflagg** [comment]
**v0.84.8**
Getting the same 400 errors.

If I uncheck all the columns that aren't SingleLineText, then the import proceeds without error. Presumably this is due to some errant values in the CSV that don't align with the datatype of the column?

**However**, when the import runs successfully, the number of rows imported is roughly (but not exactly) 3 times the number of rows in the CSV. And the first several pages contain rows that are mostly empty.

**Comment by wingkwong** [comment]
Fixed in ``0.84.12``.
