### ISSUE TITLE
🐛 Bug: Noco-win-x64.exe After importing an image, the image cannot be previewed

### ISSUE THREAD

**Issue by Kiss-World** [nocodb/nocodb#8800]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Noco-win-x64.exe After importing an image, the image cannot be previewed

### Desired Behavior

Noco-win-x64.exe After importing an image, the image cannot be previewed

### Project Details

Noco-win-x64.exe After importing an image, the image cannot be previewed

**Comment by giangdinhx** [comment]
Same issues
