### ISSUE TITLE
🐛 Bug: User cannot see a base if added, removed, and re-added

### ISSUE THREAD

**Issue by lcavasso** [nocodb/nocodb#8804]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a Base
1.  Give a user access to the Base (I gave them Creator to start with)
2. Remove the user's access to the Base
3. Grant access to the base again
4. Login as user; user cannot see the Base.

### Desired Behavior

User should have all the normal permissions associated with their role once they're re-added. In other words, a removed and re-added Creator should have the same permissions as a newly added Creator user.

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.250.2**

**Comment by dstala** [comment]
fixed in [Miscellaneous bug fixes nocodb/nocohub#3196](https://github.com/nocodb/nocohub/pull/3196)
