### ISSUE TITLE
[Design] 🐛 Bug: expanded record UI/UX

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#8814]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Keep height for QR & Bar code same as attachment field in expanded record.

### Desired Behavior

![Screenshot 2024-06-21 at 10 49 08 AM](https://github.com/nocodb/nocodb/assets/86527202/104ce493-941a-49c9-b756-cda4e1d28ff0)

### Project Details

205.1

**Comment by dstala** [comment]
@WarWolf47 You also wanted to try tad more padding between two fields. we can get it done along with this issue

**Comment by WarWolf47** [comment]
- [ ] Increase field gap to 24px
- [ ] Update field design according to design
https://www.figma.com/design/wk60YBDpJ2TcKR3C7vWHE7?node-id=33-16518#847823356
