### ISSUE TITLE
🔦 Feature: Add real-time update and show all lines(user selects how many lines to show).

### ISSUE THREAD

**Issue by Grown1968** [nocodb/nocodb#8860]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Show lines for page and update data in realtime

### Suggested Solution

I would suggest updating the data in real time, and also when showing the row data, show all the rows that the user wants, as today it only shows 100 per page and that's really bad.

### Additional Context

suggest

**Comment by dstala** [comment]
Issue to be tracked under
[Feature : Realtime Collaboration](https://github.com/nocodb/nocodb/issues/148)
[[Feature] Infinite Scroll on table](https://github.com/nocodb/nocodb/issues/3568)
