### ISSUE TITLE
Where is the kanban/calendar view?

### ISSUE THREAD

**Issue by C-Fu** [nocodb/nocodb#887]
I can't find it. Where should I go?
From Readme.md
![image](https://user-images.githubusercontent.com/6426597/147206807-77d52e20-1a9d-41aa-8f4a-aa87e744f2be.png)

**Comment by o1lab** [comment]
#140

**Comment by C-Fu** [comment]
Maybe it's better if somebody added a (coming soon!) text in the two images?
