### ISSUE TITLE
🔦 Feature: Calendar View via CreatedAt | UpdatedAt fields

### ISSUE THREAD

**Issue by rallisf1** [nocodb/nocodb#8873]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

There are times where you want a Calendar View based on the record creation date, but you still need to add your own date field (with default value `now()`) even though there is a default `CreatedAt` field.

### Suggested Solution

Enable creating a Calendar View via `CreatedAt` and `UpdatedAt` fields

**Comment by DarkPhoenix2704** [comment]
https://github.com/nocodb/nocodb/pull/8904 Will add support for this. 

CreatedAt, UpdatedAt and Formula are Read only fields. Hence drag & drop will be disabled for these.
