### ISSUE TITLE
🐛 Bug: Checkbox Rollup Count not counting as expected

### ISSUE THREAD

**Issue by LnLcFlx** [nocodb/nocodb#8879]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a table *A* with a *"has many" link-column* to table *B*
- Create a table *B* with a *checkbox column* and one row for each of the entries in table *A* where some are checked and some unchecked
- Now go back to table *A* and create a *Rollup column* for the checkbox column of table *B*. Use the only available aggregate function *Count*.

### Desired Behavior

One then notices that this rollup column does not count the number of checked boxes in *B* for a given entry *a* in *A*, but just the amount of entries *b* in *B* that are linked to *a*.

*A*:
|name|*B* entries (has many)|Count(checked) from *B*|
|-   |-          |-                      |
|a1  |b1, b2      |2 (correct*)     |
|a2  |b3         |1 (should be 0)    |
|a3  |b4, b5       |2 (should be 1)    |

*this row is there to show that the rollup also does not count the number of unique states the checkboxes for a1 are in, which would be 1 in this case

*B*:
|name|*A* entry (has one)|checked|
|-   |-        |-      |
|b1  |a1       |✅     |
|b2  |a1       |✅     |
|b3  |a2       |      |
|b4  |a3       |      |
|b5  |a3       |✅     |

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.251.0**

**Comment by dstala** [comment]
@LnLcFlx 
Rollup aggregate function `count` returns the record count linked. And it can't be used for the scenario that you had mentioned. https://docs.nocodb.com/fields/field-types/links-based/rollup/#aggregation-functions

Something similar can be achieved with summary fields once we introduce aggregations to group-by. You will have to wait for next release.

**Comment by dstala** [comment]
In Rollup, we do not support "Sum" as an option. If this is introduced, this use case can be handled.

**Comment by dstala** [comment]
Supported now.
