### ISSUE TITLE
Commenter can't upload files using the form

### ISSUE THREAD

**Issue by FrancyMak** [nocodb/nocodb#888]
Node: **v16.13.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.83.8**

**Steps To Reproduce**
1. Create a user with commenter as role
2. Try to attach something to a module
3. See error "Not allowed"

**Comment by o1lab** [comment]
Commenter is not allowed to change any field.
