### ISSUE TITLE
🐛 Bug: UI ACL changes are not saved

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#8905]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Changes made to UI ACL are not getting saved

### Desired Behavior

UI ACL to save after changes are made

### Project Details

251.0

**Comment by woodmin** [comment]
Have the  same on latest version. Very dangerous bug due to data privacy nature. Hope it gets resolved soon.
Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.250.2**
