### ISSUE TITLE
[Feature] Better docs for switch expression

### ISSUE THREAD

**Issue by singpolyma** [nocodb/nocodb#892]
## Recommending Features

**Need for this feature**

It is not clear what the switch function in a formula can do.  The docs say 'pattern' but then show matching against literal numbers.  Is it just equality and on any type, then, or is some kind of pattern microlanguage also supported?

**Comment by wingkwong** [comment]
Example is shown below.

https://docs.nocodb.com/setup-and-usages/formulas#conditional-expressions
