### ISSUE TITLE
🐛 Bug: The minio attachement URL contains the port number, even if it is the default one

### ISSUE THREAD

**Issue by kuon** [nocodb/nocodb#8924]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a minio integration using default https port 443.
- Create an attachement colum
- Upload an attachement

The resulting URL is correct, but it contains the port number.

### Desired Behavior

If the port number is the default protocol port number, it should be trimmed to improve readability.

For example `https://minio.example.com:443/xxx` -> `https://minio.example.com/xxx`

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.207.3**

**Comment by DarkPhoenix2704** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/9104
