### ISSUE TITLE
🐛 Bug: Attachments are broken on windows host

### ISSUE THREAD

**Issue by erem2k** [nocodb/nocodb#8925]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create SQLite datasource, create a table with attachment column
2. Create a row through grid view
3. Upload a file to row's attachment column
3. Note that attached files cannot be downloaded and previews for images are broken

Affects default and custom SQLite datasources.
Untested on MySQL/PostgreSQL.

It does seem that files are uploaded at their expected location on disk, but Noco frontend tries to pull them from different path:

Log:
```
[GlobalExceptionFilter] ENOENT: no such file or directory, stat 
'C:\NocoTest\nc\uploads\download\noco\pl5uwzf34bhgmu7\mc8bf62kd3rt4t2\c8srco8ks7wvrml\testorig_pflTj.jpg'
```

Real location:
```
C:\NocoTest\nc\uploads\noco\pl5uwzf34bhgmu7\mc8bf62kd3rt4t2\c8srco8ks7wvrml\testorig_pflTj.jpg
```

Seems to affect both form and grid-uploaded attachments

### Desired Behavior

Attachments are available after upload

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.251.1**

### Attachments

[log.log](https://github.com/user-attachments/files/16090200/log.log)
![image](https://github.com/nocodb/nocodb/assets/7237119/f8c98bd1-a1de-4268-9ab7-7a6d255ded6f)
![image](https://github.com/nocodb/nocodb/assets/7237119/eb683a7e-a570-417e-835f-5f0da9ad811f)

**Comment by erem2k** [comment]
FYI, after retesting this on 0.207.3 by recreating the table with same setup the text/binary files become available, but images are still broken - so, no preview and no option to open them

**Comment by salim-b** [comment]
@erem2k Does it only happen for file attachments over a certain file size (~5MiB)? If so, this issue might share the underlying cause with https://github.com/nocodb/nocodb/issues/5914#issuecomment-2005008734.

**Comment by mertmit** [comment]
Thanks for reporting.

This issue is reproducible on windows host and it is related to path separator difference on windows.

PRs are welcome! If none arise and I find the bandwidth, I will assign this to myself and work on a fix.
