### ISSUE TITLE
🐛 Bug: "w.replace is not a function" on CSV import

### ISSUE THREAD

**Issue by springfielddatarecovery** [nocodb/nocodb#8928]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Import a CSV file which for some unknown reason causes this error (this is on instance hosted on app.nocodb.com)
2. "w.replace is not a function" shown in pop-up alert at bottom right of screen
3. No records are imported

### Desired Behavior

CSV imports without errors and/or identifies the record causing the error so the user can remedy it

### Project Details

hosted on app.nocodb.com

**Comment by dstala** [comment]
@springfielddatarecovery during CSV import, fields are now by default imported as Single line text. If you see this issue during field conversion after the file is imported in newer release, do reopen this thread.

**Comment by springfielddatarecovery** [comment]
@dstala Getting a similar issue now, I refreshed to make sure I was on the latest copy of the code on nocodb.com. `h.replace is not a function`

**Comment by springfielddatarecovery** [comment]
I don't believe I can re-open the issue, so I created a new one instead https://github.com/nocodb/nocodb/issues/8969
