### ISSUE TITLE
🐛 Bug: "Rename view" should be "rename form"

### ISSUE THREAD

**Issue by springfielddatarecovery** [nocodb/nocodb#8930]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a database at NoCoDB.com
2. Create a table
3. Create a form for the table
4. Click three-dot menu on form, it will display "rename view" and "duplicate view"

### Desired Behavior

Since NoCoDB has decided that "view" and "form" are different things with different names, these rename and duplicate options should reflect that. Change "rename view" and "duplicate view" to "rename form" and "duplicate form" respectively.

### Project Details

None

**Comment by priyanshuverma-dev** [comment]
I would like to work on this @springfielddatarecovery
