### ISSUE TITLE
🐛 Bug: docker: invalid reference format.

### ISSUE THREAD

**Issue by F041** [nocodb/nocodb#8932]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

```
docker run -d --name nocodb-postgres \
-v "$(pwd)"/nocodb:/usr/app/data/ \
-p 8080:8080 \
-e NC_DB="pg://host.docker.internal:5432?u=root&p=password&d=d1" \ 
-e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
nocodb/nocodb:latest
```
from https://github.com/nocodb/nocodb

on Ubuntu server, via PuTTY

### Desired Behavior

the stack starts

### Project Details

I wanted to start in on my VPS. I tried to follow https://bobcares.com/blog/docker-invalid-reference-format-pwd/ without success.
Starting the stack from portainer gave another problem: Waiting no matching manifest for linux/arm64/v8 in the manifest list entries
but this doesn't fit with this issue

**Comment by mertmit** [comment]
```
docker run -d --name nocodb-postgres \
-v "$(pwd)"/nocodb:/usr/app/data/ \
-p 8080:8080 \
-e NC_DB="pg://host.docker.internal:5432?u=root&p=password&d=d1" \
-e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
nocodb/nocodb:latest
```

Can you try this instead? It looks like there is an extra trailing space that went unnoticed.
