### ISSUE TITLE
Bug: Missing image quick switch button

### ISSUE THREAD

**Issue by Kiss-World** [nocodb/nocodb#8937]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

gallery
![image](https://github.com/nocodb/nocodb/assets/44720566/c0a9339c-0b22-4fbb-bd40-a81a1108c87d)

### Desired Behavior

I remember there were left and right arrows to switch buttons

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.251.1**

**Comment by dstala** [comment]
Tried in OSS/develop. Those buttons appear on hover. Can you please double check.
![Screenshot 2024-07-05 at 10 06 04 AM](https://github.com/nocodb/nocodb/assets/86527202/421ad7b2-b39c-402b-9d12-8d6dc1a44d54)

**Comment by dstala** [comment]
@Kiss-World closing this. if you are able to reproduce, please re-open this ticket
