### ISSUE TITLE
🐛 Bug: Modal from belongs-to chip doesn't show links

### ISSUE THREAD

**Issue by sebastianoe** [nocodb/nocodb#8940]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Assume you have two tables `Books` and `Authors` where an author `has-many` books.

<img width="570" alt="image" src="https://github.com/nocodb/nocodb/assets/962041/7375ad9e-3c64-417b-8b24-89d0531c250b">

As expected, the `Books` table gets a corresponding `belongs-to` field which shows the author in a chip.

1. Click the chip in the `Books` table to open the author details.
3. See that the modal containing the author details says `No records linked` although there should be some.
4. Click `Reload` via the modal's menu and see that the linked records are now shown.

<img width="424" alt="2024-07-05_09-16-39" src="https://github.com/nocodb/nocodb/assets/962041/b97c41a9-3e9d-460f-8cd1-533bfae5b3ee">
<img width="524" alt="2024-07-05_09-16-56" src="https://github.com/nocodb/nocodb/assets/962041/35e2596e-b676-4c2f-a1da-9f27533768fd">
<img width="798" alt="2024-07-05_09-17-30" src="https://github.com/nocodb/nocodb/assets/962041/45f731a3-ec9a-4f79-8dfc-e4f6d3855251">
<img width="538" alt="2024-07-05_09-17-36" src="https://github.com/nocodb/nocodb/assets/962041/a4d94146-c777-4038-a132-eb77ccf3c1b5">

### Desired Behavior

The linked records should be visible without explicit reloading.

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **mysql2**
PackageVersion: **0.251.0**

**Comment by dstala** [comment]
- issue reproducible in PG also (staging)
- we can also skip showing expand icon. instead, click on the chip should expand. 
![Screenshot 2024-07-05 at 2 08 15 PM](https://github.com/nocodb/nocodb/assets/86527202/2b3b3d2c-428d-410f-bb49-d73db13440db)
![Screenshot 2024-07-05 at 2 07 42 PM](https://github.com/nocodb/nocodb/assets/86527202/a6446d0f-335a-42b9-a2eb-8f522be3443c)

**Comment by rameshmane7218** [comment]
@dstala This issue is present in all links type of `LinkToAnotherRecord` field as we are using same `chip` component to render cell and we are showing only availble row data based on row id which contains only primaries column data
