### ISSUE TITLE
Bug: ' not escaped in MultiSelect option

### ISSUE THREAD

**Issue by PierreMacherel** [nocodb/nocodb#896]
Node: **v12.22.6**
Arch: **arm**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.83.8**
Project was created  by clicking : **New Project**
OS on which NocoDB is running : **aarch64 GNU/Linux**

**Steps To Reproduce**
1. Add a new table name `test`
2. Add a new column
3. Column type: MultiSelect
4. Create an option containing the character `'`, for example `a'a`
5. save the new column
6. See error `You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use ` on docker logs, and `update table.test failed` on front-end

**Expected behavior**
Use of `'` should be possible in a MultiSelect option.

**Cause**
`'` is not escaped. I can escape it during the MultiSelect creation with `\`, but then it is displayed as `a\'a` in the front-end.

**Comment by pranavxc** [comment]
Fixed in `0.84.2`
