### ISSUE TITLE
🐛 Bug: "h.replace is not a function" on CSV import

### ISSUE THREAD

**Issue by springfielddatarecovery** [nocodb/nocodb#8969]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Import a CSV file which for some unknown reason causes this error (this is on instance hosted on app.nocodb.com)
2. "h.replace is not a function" shown in pop-up alert at bottom right of screen
3. No records are imported

follow-up based on issue https://github.com/nocodb/nocodb/issues/8928

### Desired Behavior

CSV imports without errors and/or identifies the record causing the error so the user can remedy it

### Project Details

hosted on app.nocodb.com

**Comment by dstala** [comment]
@springfielddatarecovery could you help us share a sample CSV file with redacted confidential information?

**Comment by springfielddatarecovery** [comment]
[redacted.csv](https://github.com/user-attachments/files/16137741/redacted.csv)

I'll DM you our DB info

**Comment by springfielddatarecovery** [comment]
Actually I guess github doesn't have DMs? Lmk your email I guess?

**Comment by dstala** [comment]
> Actually I guess github doesn't have DMs? Lmk your email I guess?

r@nocodb.com
you can find me as `dstala` on our discord channel https://discord.gg/5RgZmkW

**Comment by dstala** [comment]
@springfielddatarecovery I was able to successfully import the CSV you had shared into a new table. Didn't see any errors.
https://wpq9c053.nocodb.com/#/nc/view/58e4ca00-112c-4d7b-8b74-1733286b0813

**Comment by springfielddatarecovery** [comment]
Just tried again and can confirm the import error is still happening. I DMed you on discord our database info

**Comment by springfielddatarecovery** [comment]
After some additional testing, I figured out what caused this failure. It's because we were trying to import data into a boolean field, the data was "true" instead of "True". Changing the capitalization fixed this. NoCoDB should automatically detect and rectify this situation, or at least display a useful warning to the user.

**Comment by dstala** [comment]
Now CSV imports are all mapped to "Single select field" during import. Post import, during field conversions - if any such errors will be easy to identify.

To support conversion in case sensitive manner, will try it out.

**Comment by ramisedhom** [comment]
My data was coming as CSV from Airtable with "Checkbox" field value is written as "checked". I confirm, changing this field value from "checked" to "TRUE" resolve the issue. Meaningful error however is needed.

**Comment by o1lab** [comment]
@mertmit
