### ISSUE TITLE
Bug: swagger API doc

### ISSUE THREAD

**Issue by PierreMacherel** [nocodb/nocodb#897]
Node: **v12.22.6**
Arch: **arm**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.83.8**
Project was created  by clicking : **New Project**
OS on which NocoDB is running : **aarch64 GNU/Linux**

**Steps To Reproduce**
1. Create a table with some column
2. Go to the `Swagger API Doc` from the upper right button also used for logout
3. Click on an API (exemple: `/nc/orsay_megy/api/v1/Orsay/{OrsayId}`)
4. Both the clicked API and its bulk version are expanded (in my example `/nc/orsay_megy/api/v1/Orsay/bulk`)

**Expected behavior**
Only the clicked API should expand/collapse.

**Comment by pranavxc** [comment]
Fixed in `0.84.0`
