### ISSUE TITLE
🐛 Bug: noco minio plugin "minio deps" version between "in Docker image" and "in repos"

### ISSUE THREAD

**Issue by u-u-z** [nocodb/nocodb#8970]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

After docker [0.207.1](https://hub.docker.com/layers/nocodb/nocodb/0.207.1/images/sha256-bf01da3bfb62be58e9318cfa2b16bb590fb5d724a92d90d2da42564b9a3b7ab2?context=explore) and [0.251.1](https://hub.docker.com/layers/nocodb/nocodb/0.251.1/images/sha256-fddf4b4741f79be6c338b817b571b2635e432e8221e8905ede19dd4b4d2d8247?context=explore) we used version, the minio deps version is `7.1.4`, but repos [pnpm-lock.yaml](https://github.com/nocodb/nocodb/blob/ea512fd54055db7b4edbcdf87f641974f90b05d5/pnpm-lock.yaml#L20864) is 7.1.3, we check it by docker images `/usr/src/app/pnpm-lock.yaml`
<img width="320" alt="image" src="https://github.com/nocodb/nocodb/assets/11187239/0549c73d-3ceb-4ea0-b51e-c882093d1706">

## BEFORE: Verify S3 Services / minio works ✅
use repo's deps minio `7.1.3` connect services directly it's works, and Mountain Duck tools they all works can upload files.

## With Docker container start nocodb
Start nocodb container
	```
	docker run -d --name nocodb \
		-v "$(pwd)"/nocodb:/usr/app/data/ \
		-p 8081:8080 \
		nocodb/nocodb:latest
	```

### With minio
1. Run minio container 
	```shell
	 docker run -p 9000:9000 -p 9001:9001 \
	  quay.io/minio/minio server /data --console-address ":9001"
	```

3. Create User, Bucket and Access Key, Secret for auth
4. 🚨 Response Error `S3Error: You must specify at least one part`

### With S3 Services (Huaweicloud)
1. Set up config Access Secrets
2. 🚨 Connect directly response: `The XML you provided was not well-formed or did not validate against our published schema` [**MalformedXML** error](https://support.huaweicloud.com/intl/en-us/sdk-ios-devg-obs/obs_27_1601.html)

### Run directly
Tag: 0.251.1

```shell
pnpm install
# installed minio version is `7.1.3`
pnpm bootstrap
pnpm start:frontend
pnpm start:backend
```
Connect minio docker & huawei s3 services works directly. ✅
### Desired Behavior

minio its important plugin for nocodb users, it resolve storage issues, costs controllable ...

So we need ensure proper operation: ensure the minio versions are consistent in Docker and in the repository

Based on my testing, **I recommend continuing to use version 7.1.3** to temporarily ensure the issue is resolved.

### Project Details

- NocoDB used as docker: `true` && `work directly`
- NocoDB version: `0.251.1` and `0.207.1` we used
- Database: `sqlite` (just reproduce the bug)
- OS: `MacOS 14.5` and `Debian 12`
- Node version (run directly) `v18.18.2`

**Comment by u-u-z** [comment]
## More Details about MalformedXML error
[MalformedXML error](https://support.huaweicloud.com/intl/en-us/sdk-ios-devg-obs/obs_27_1601.html)

- in `7.1.3` minio deps use `PUT` upload
- in `7.1.4` minio try to use `POST` request

DM me cant show more details with my network packages ... 
![CleanShot 2024-07-09 at 14 41 50@2x](https://github.com/nocodb/nocodb/assets/11187239/6d50808f-894e-4f4f-8301-1de6af65366c)

![CleanShot 2024-07-09 at 14 45 23@2x](https://github.com/nocodb/nocodb/assets/11187239/bc973f08-e6c2-468b-8bed-9f219ff68f0f)
<img width="1093" alt="image" src="https://github.com/nocodb/nocodb/assets/11187239/075fc819-298e-468c-ae73-6222cb090992">

**Comment by DarkPhoenix2704** [comment]
Fixed in Fixed in https://github.com/nocodb/nocodb/pull/9104
