### ISSUE TITLE
0.83.8 update from 0.83.6: can't browse from Chromium anymore

### ISSUE THREAD

**Issue by j2l** [nocodb/nocodb#898]
Hello,
I use Chromium on my Ubuntu desktop to test NocoDB.
I updated NocoDB to 0.83.8 from 0.83.6, and now Chromium doesn't display the web page, asking if I updated every minute (see screenshot below) and throwing errors in console:
```
e2e512f.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
e89d4ff.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
8ac8854.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
0c86e45.js:1
```
Container's logs (multiple attempts after clicking "OK'):
```
GET /dashboard/ 304 - - 3.827 ms
GET /dashboard/_nuxt/e2e512f.js 404 165 - 3.682 ms
GET /dashboard/_nuxt/e89d4ff.js 404 165 - 2.905 ms
GET /dashboard/_nuxt/8ac8854.js 404 165 - 2.242 ms
GET /dashboard/_nuxt/0c86e45.js 404 165 - 2.165 ms
GET /dashboard/favicon-32.png 304 - - 0.598 ms
GET / 302 64 - 0.925 ms
GET /dashboard/ 304 - - 0.729 ms
GET /dashboard/_nuxt/e2e512f.js 404 165 - 2.923 ms
GET /dashboard/_nuxt/e89d4ff.js 404 165 - 2.694 ms
GET /dashboard/_nuxt/8ac8854.js 404 165 - 2.302 ms
GET /dashboard/_nuxt/0c86e45.js 404 165 - 2.177 ms
```

I tried dumping cookies, localstorage, restart the browser, without luck.

NocoDB used as docker : true
NocoDB version : 0.83.8
Database used in NC_DB URL  : not relevant to the bug
Database on which spreadsheet is created : not relevant to the bug
OS on which NocoDB is running : Ubuntu 21.04

**Steps To Reproduce**
1. Go to  http://0.0.0.0:8081/dashboard/
2. See error:
![image](https://user-images.githubusercontent.com/65325/147824499-3a733494-e293-4d0c-bb54-b581c49ce67f.png)

**Expected behavior**
On firefox, it works fine:
![image](https://user-images.githubusercontent.com/65325/147824655-f429b3fa-ee6e-402b-9f05-8b7a6d9b4421.png)

prefilled?:
Node version : **v12.22.1**
Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
packageVersion: **0.9.27**

**Comment by o1lab** [comment]
Please do hard refresh = ctrl+shift+r

Sometimes, hard refresh is not triggered on clicking OK.
