### ISSUE TITLE
🔦 Feature: when creating views, having the hability to always see column headers when scrolling vertically

### ISSUE THREAD

**Issue by jbricout007** [nocodb/nocodb#9018]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

When creating some views underneath each other, headers of columns finally disappear which is not vey helpful to identify type of data. The idea is to have the abily of displaying headers evey time when scrolling vertically.

### Suggested solution

Option to display or mask headers automatically

### Additional context

![header_visible](https://github.com/user-attachments/assets/0d4fba1d-da7d-4bcd-9270-0ee68759c53d)
![headers_non_visible_when scrolling](https://github.com/user-attachments/assets/ee95e96d-285a-4c9c-8254-90489ff96db8)

**Comment by DarkPhoenix2704** [comment]
hi @jbricout007.  

Looks like you are using an older version of NocoDB. Can you verify if the issue still exists in the latest [release](https://github.com/nocodb/nocodb/releases/tag/0.251.1)

**Comment by jbricout007** [comment]
hi @DarkPhoenix2704 : an upgrade will be planned in a few times. Will have a look oin that issue at the moment.
Thanks

**Comment by dstala** [comment]
Please reopen this ticket if issue still persists in latest release v0.255.2
