### ISSUE TITLE
🐛 Bug: Webhook Parameters are not sent

### ISSUE THREAD

**Issue by timkley** [nocodb/nocodb#9021]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Add a new webhook and add a parameter:
![image](https://github.com/user-attachments/assets/806730b6-87d1-4295-bc11-3deebe7549bd)

2. Trigger the webhook

### Desired Behavior

The parameters should be sent with the request, currently, they are not.

I tried to debug a little bit and found that the code for [putting together the request](https://github.com/nocodb/nocodb/blob/develop/packages/nocodb/src/helpers/webhookHelpers.ts#L430) checks to see if a parameter is enabled but there is no way to enable a parameter.

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.251.1**

**Comment by dstala** [comment]
@timkley there was supposed to be a checkbox to enable or disable parameter, but is somehow missing in the UI in our recent release. we will fix this soon in our next release.

thanks for bringing this to our attention.
