### ISSUE TITLE
🔦 Feature: Column type button

### ISSUE THREAD

**Issue by LucBerge** [nocodb/nocodb#9022]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

I would like to have a button type column to open new ab computed from row values like in airtable.

### Suggested solution

- Create a new button type
- In the type "link" make it possible to use formula to define the value and add an option to make the link as a button

### Additional context

Existing feature in airtable

**Comment by dstala** [comment]
Related

[[Feature] Custom buttons (ribbon) rest call actions on selection of records](https://github.com/nocodb/nocodb/issues/1041)
[Button and scripts feature.](https://github.com/nocodb/nocodb/issues/1980)

**Comment by LucBerge** [comment]
@dstala 

1. I am looking for a button in ribbon performing action on the selected record like in #1041. I'm looking for a new column type where you have a button in each cell. Like in Airtable. I don't see how it is linked to #1041.
2. I'm ok to work on it. Are contributors allowed to work on core features?

**Comment by dstala** [comment]
@LucBerge URL formula now supports additional text. See if it helps for your use case. 



![Image](https://github.com/user-attachments/assets/a769027f-ff0c-4d21-a12e-03176134c0d7)



We do have plans to introduce button functionality & are discussing work scope. We will keep you posted on that.

**Comment by dstala** [comment]
We will happily accept feature updates from contributors. Please do discuss your approach with one of core-contributors (@DarkPhoenix2704 @pranavxc @mertmit @rameshmane7218 ) before you get started.

**Comment by LucBerge** [comment]
Hello @dstala, Yes, it helps but there is still two missing features:
- The design: Being able to customize the button look & color
- Disable button: In airtable, if the url is not valid, the button is disabled and greyed out. This is an interesting feature because you can enable the button once the required fields are filled or disable the button on a given condition.

**Comment by dstala** [comment]
@LucBerge Thanks for the suggestions. We are introducing buttons field soon. Disable button for invalid URL is an interesting suggestion. We will look into it. 
cc @DarkPhoenix2704

**Comment by LucBerge** [comment]
Wow, that was quick! Thanks for the work.

How does the deployement pipeline works?
How many time before it is available on nocodb cloud?
How many time before it is available on docker-hub?
