### ISSUE TITLE
🔦 Feature: Unlimited record per page

### ISSUE THREAD

**Issue by LucBerge** [nocodb/nocodb#9023]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

The default number of records per page is 25. The maximum is currently 100. I do not want any pages = Unlimited number of records per page.

### Suggested solution

Add an "unlimited" option in the bottom right corner right after "100".

**Comment by dstala** [comment]
This would slow down the application if you are dealing with lot of records. How many records do you have per table?

**Comment by LucBerge** [comment]
> This would slow down the application if you are dealing with lot of records. How many records do you have per table?

Isn't it the user problem ?
Would it take a lot of memory on server side too ?


A good implementation would be NOT to display everything in the browser:
- only the visible records
- +10 records up (for smooth UX)
- +10 records down (for smooth UX)

When the user scroll down, the records are retrieved from the database. It avoids loading everything in the browser and taking a lot of memory on user side.

**Comment by salim-b** [comment]
> A good implementation would be NOT to display everything in the browser:

What you're describing is already requested in https://github.com/nocodb/nocodb/issues/3568, so I think this can be closed as duplicate.

**Comment by LucBerge** [comment]
@salim-b I agree. I close.
