### ISSUE TITLE
🐛 Bug: impossible to submit new record form with defaut values

### ISSUE THREAD

**Issue by jbricout007** [nocodb/nocodb#9024]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

I have a table with some mandatory fields, wich have default values such as zero (numeric fields)
I try to add a new record by clicking on "new record-form"
The button is not available : I have to change the default value to submit the record
The problem does not appear  with "new record-grid" function

### Desired Behavior

It normally has to be possible to sumbit the new form without changing default values to add a new record

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.204.0**

### Attachments

![Form_before_changing_mandatory_value_with_default_value_KO](https://github.com/user-attachments/assets/8dee5a4a-482b-4cc1-9ef6-4f132730a389)
![Form_after_changing_mandatory_value_with_default_value_OK](https://github.com/user-attachments/assets/5ab62542-5f4e-4a2e-9f19-95cac79437d9)

**Comment by dstala** [comment]
@jbricout007 if i create a table from nocodb & set a field with default value - i am able to create new record by using form mode. are you connecting to external db in this case? if so, can you let us know if the field has any additional constraints set?

**Comment by dstala** [comment]
also, can you upgrade to latest version of nocodb. easy for us to support that way

**Comment by salim-b** [comment]
I *think* I observed the same issue in older NocoDB versions: In a table with a column having a `DEFAULT` value as well as a `NOT NULL` constraint set from an external PostgreSQL data source, a new row could only be added via form view when a value was explicitly set for that column (otherwise an error was displayed that the column cannot be NULL). Via grid view, it always worked.

At least in the latest stable release (v0.251.1), this issue doesn't seem to be present anymore (at least I can't reproduce it anymore). Hope that helps narrowing it down.

**Comment by jbricout007** [comment]
> @jbricout007 if i create a table from nocodb & set a field with default value - i am able to create new record by using form mode. are you connecting to external db in this case? if so, can you let us know if the field has any additional constraints set?

hi @dstala : an upgrade will take place in a few times. Perhaps it will be corrected seeing the explanation of @salim-b 
Yes we are connected to an external database (postgresql) but the field doses not have anay constraint : we just parameter in nocodb "NOT null" field and a default value for that field (0)

**Comment by dstala** [comment]
Thanks for the details. Please reopen this ticket once you upgrade & if issue still persists.
