### ISSUE TITLE
🔦 Feature: better user experience when completing form view

### ISSUE THREAD

**Issue by jbricout007** [nocodb/nocodb#9025]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

It is not very convenient to complete a form view in Nocodb because :
- whe have to use the mouse to navigate from field to field.
- using "Enter" on the keyboard will immediately save a new record which is quite confusable for most users

### Suggested solution

Would be much better that using "Enter" on the keyboard will go automatically to the next field of the form instead of submitting the form and creating a new uncompleted record in the table.

**Comment by dstala** [comment]
@jbricout007 agree with your observation

@rameshmane7218 
Use of "Enter" key action, we need to scope it to cell level. If cell has a picker, "Enter" can be used to open picker. Otherwise, "Enter" should not do anything. When focus is on "Submit" button, enter key should submit form.

**Comment by salim-b** [comment]
> we have to use the mouse to navigate from field to field.

I am able to navigate from field to field via <kbd>Tab</kbd>, both on Firefox and Google Chrome (on Ubuntu 22.04).

**Comment by jbricout007** [comment]
Hi,

I confirm that part of this is corrected on 0.258 NOCODB version.
Now, when we are clicking on "enter", it does not automatically submit the new form. 
However, it does not go automatically to next field, would it be possible to have this option also ? Would be very helpuf for our users when completing the form in NOCODB.

Thanks
