### ISSUE TITLE
NocoDB chokes when attempting to import CSV 

### ISSUE THREAD

**Issue by danielrosehill** [nocodb/nocodb#9027]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Attempt to import CSV and in my cloud environment it fails

![csv import choke](https://github.com/user-attachments/assets/6e73093c-7a8a-4a50-8978-7e307a6db0a4)

![csv laytout](https://github.com/user-attachments/assets/e80b5a19-250d-498a-ac34-c02af55d282b)

### Desired Behavior

CSV will import

### Project Details

NPM deployment with Postgres database (deployed PG not Docker image)

**Comment by dstala** [comment]
There are some improvements done for CSV import & they will be available in OSS in our next release [expected early next week]. I tried the file that you had shared in cloud & it seems to work fine. Here is shared view for it. You can try it out in your app.nocodb.com account

https://wpq9c053.nocodb.com/#/nc/view/d4a06c4f-143d-46f9-b161-9cc80f9b34c9

**Comment by dstala** [comment]
Please reopen this ticket if issue still persists.
