### ISSUE TITLE
🐛 Bug: Airtable import not importing the data

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#9032]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Have tried importing sample data and no data was imported.

<img width="799" alt="image" src="https://github.com/user-attachments/assets/8aa5bedd-5701-40a5-80c6-df97d5182473">

### Desired Behavior

Should import data

### Project Details

.

**Comment by dstala** [comment]
[at-import-logs (1).txt](https://github.com/user-attachments/files/16318546/at-import-logs.1.txt)

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/pull/9037
