### ISSUE TITLE
🐛 Bug: Minio plugin error: The XML you provided was not well-formed or did not validate against our published schema

### ISSUE THREAD

**Issue by mlepeshkin** [nocodb/nocodb#9103]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Setup NocoDB & Mini instance.
Configure Minio plugin.
Press 'Test' button in 'Configure Minio' window.
The error message is displayed: 'The XML you provided was not well-formed or did not validate against our published schema.'
When trying to attach any file it's content does not stored in configured Minio bucket.

Log contains the following lines:
```
[Nest] 9  - 07/29/2024, 2:53:49 PM   ERROR [MissingDBError] S3Error: The XML you provided was not well-formed or did not validate against our published schema.
[Nest] 9  - 07/29/2024, 2:53:49 PM   ERROR [GlobalExceptionFilter] The XML you provided was not well-formed or did not validate against our published schema.
S3Error: The XML you provided was not well-formed or did not validate against our published schema.
    at parseError (/usr/src/app/node_modules/minio/dist/main/internal/xml-parser.js:47:13)
    at Object.parseResponseError (/usr/src/app/node_modules/minio/dist/main/internal/xml-parser.js:94:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.makeRequestStreamAsync (/usr/src/app/node_modules/minio/dist/main/internal/client.js:491:19)
    at async Client.completeMultipartUpload (/usr/src/app/node_modules/minio/dist/main/internal/client.js:1162:17)
    at async /usr/src/app/node_modules/minio/dist/main/internal/client.js:1458:14
    at async Promise.all (index 1)
    at async Client.uploadStream (/usr/src/app/node_modules/minio/dist/main/internal/client.js:1412:20
```

### Desired Behavior

Minio plugin configuration without errors. 
Attached files are saved to Minio bucket.

### Project Details

NocoDB docker v. 0.251.3 
Separate Minio instance v. RELEASE.2023-02-27T18-10-45Z (commit-id=0ff931dc765d5d8fdddcdf7687fec1b0b194fca9)

**Comment by DarkPhoenix2704** [comment]
Hey @mlepeshkin . Can you verify if the following build fixes the issue and is compatible with the existing attachments? 


```bash
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.251.3-pr-9104-20240730-0336
```

**Comment by mlepeshkin** [comment]
Thank you @DarkPhoenix2704! I confirm, this version works for me.

**Comment by DarkPhoenix2704** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/9104
