### ISSUE TITLE
1-click deploy to heroku is broken

### ISSUE THREAD

**Issue by Overdrivr** [nocodb/nocodb#911]
It looks like the 1-click deploy to heroku is broken, I just did the following :
1. Click `1-click deploy`
2. Give it a new unique name
3. Choose Europe as region
4. Click deploy

![image](https://user-images.githubusercontent.com/1294805/148024540-e5fe6a29-6f81-444f-9b8c-946a5a2592c3.png)

**Comment by o1lab** [comment]
We've fixed it now. Please try it.

This has occured before and both times there was a github redirect issue of [nocodb-seed-heroku](https://github.com/nocodb/nocodb-seed-heroku)
