### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by c2006878** [nocodb/nocodb#9118]
### Discussed in https://github.com/nocodb/nocodb/discussions/9116

<div type='discussions-op-text'>

<sup>Originally posted by **c2006878** July 31, 2024</sup>
After executing the command (./build-local-docker-image.sh) and deploying it on Docker, the following error occurred. Can anyone help me?
![image](https://github.com/user-attachments/assets/2ec0e762-b2d2-4391-a7de-ccb558d5fe53)
</div>

**Comment by DarkPhoenix2704** [comment]
Hey @c2006878

Can you try again? We just updated the package causing that issue

**Comment by pranavxc** [comment]
Thank you for reporting the issue. It was related to a missing file in the last release of the nc-plugin package. We have now rolled out a new version with all the necessary files included.

**Comment by c2006878** [comment]
It works. Thank you
