### ISSUE TITLE
🔦 Feature: Is there a way to display the linked record name in the original table? 

### ISSUE THREAD

**Issue by danielrosehill** [nocodb/nocodb#9145]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

I have created a table for storing ChatGPT output.

Here's a demo entry:

![image](https://github.com/user-attachments/assets/ed08f0dd-5b41-4829-b837-a0cda5c11c3d)

I am using a separate table to organise the categories.

For example:

![image](https://github.com/user-attachments/assets/d79e56ca-4a30-40a4-bec3-f24977c6a236)

I can create the "one to many" relationship however the field value cannot be displayed by name?

This is what I see:

![image](https://github.com/user-attachments/assets/81880aed-7d94-4429-9b4d-99357514ef89)

### Suggested solution

It would be very helpful if the linked values themselves were displayed on the original table.

It would also be nice if they could be automatically organised alphabetically to support the common "picker" / dropdown use-case:

![image](https://github.com/user-attachments/assets/83ad1705-eee5-4a4b-94da-89f7dade937f)

**Comment by o1lab** [comment]
You can add [lookup](https://docs.nocodb.com/fields/field-types/links-based/lookup/) fields from the related table.

**Comment by danielrosehill** [comment]
> You can add [lookup](https://docs.nocodb.com/fields/field-types/links-based/lookup/) fields from the related table.

Thx

**Comment by martinfojtik** [comment]
@danielrosehill Adding a Lookup field next to the Links field feels clumsy. The UX would be much better if we could see a list of linked records inside the Link column. The Airtable or Teable has that feature.
