### ISSUE TITLE
🐛 Bug: 0.251.3 fails to start on `armv7` architecture

### ISSUE THREAD

**Issue by raisinbear** [nocodb/nocodb#9147]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Hi, first off, thanks so much for this awesome project! As far as container tags go, `arm32/v7` should still be supported, however the latest version `0.251.3` will not run in docker. Sorry if there is already a ticket for it, but I couldn't find any. Feel free to close, if this is a duplicate of course.

- Try to run docker image version `0.251.3` on `armv7` device.

### Desired Behavior

Startup is successful.

### Project Details

Docker: true
Database: sqlite3

### Attachments

Output during failed startup:

```
/usr/src/app/node_modules/sharp/lib/sharp.js:114
  throw new Error(help.join('\n'));
  ^

Error: Could not load the "sharp" module using the linuxmusl-arm runtime
Possible solutions:
- Manually install libvips >= 8.15.2
- Add experimental WebAssembly-based dependencies:
    npm install --cpu=wasm32 sharp
    npm install @img/sharp-wasm32
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
```

**Comment by pranavxc** [comment]
I'd made fix for the `arm7`, please try the following image to confirm.

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.251.3-pr-9163-20240806-1313
```

**Comment by raisinbear** [comment]
> I'd made fix for the `arm7`, please try the following image to confirm.
> 
> ```
> docker run -d -p 8888:8080 nocodb/nocodb-timely:0.251.3-pr-9163-20240806-1313
> ```

Hey thanks for the reply. Looks good, it’s running and working fine so far! Thanks a lot for the fix. 😊 Is there a reason not to stay on this intermediate version until this makes it into the main branch?

**Comment by pranavxc** [comment]
> > I'd made fix for the `arm7`, please try the following image to confirm.
> > ```
> > docker run -d -p 8888:8080 nocodb/nocodb-timely:0.251.3-pr-9163-20240806-1313
> > ```
> 
> Hey thanks for the reply. Looks good, it’s running and working fine so far! Thanks a lot for the fix. 😊 Is there a reason not to stay on this intermediate version until this makes it into the main branch?

Thanks for confirming. You can use the PR build until we deploy, we will do the release soon.
