### ISSUE TITLE
🔦 Feature: Add quarter formula function

### ISSUE THREAD

**Issue by mingfang** [nocodb/nocodb#918]
Please add the quarter function as documented here
https://www.postgresql.org/docs/8.3/functions-datetime.html

The quarter function is very important for business use cases, eg what are the quarterly total sales for this year?

**Comment by dstala** [comment]
You can use the following formula instead `ROUNDUP((MONTH({dateField}) / 3))`

**Comment by dstala** [comment]
ROUNDUP, will be available from next feature release scheduled by end of this month
