### ISSUE TITLE
🔦 Feature: Is there any way to increase the session duration?

### ISSUE THREAD

**Issue by danielrosehill** [nocodb/nocodb#9195]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

Making intensive daily use of NocoDB from a secure stationary desktop computer

### Suggested solution

Would like to be able to increase the session duration manually to something longer than it appears to be currently (24 hours or less)

**Comment by o1lab** [comment]
Pls use [NC_JWT_EXPIRES_IN](https://docs.nocodb.com/getting-started/self-hosted/environment-variables/#authentication)

**Comment by dstala** [comment]
@danielrosehill Please reopen this issue if that doesn't help.
