### ISSUE TITLE
🔦 Feature: allow self-signed certificate for Minio (nocodb Error: self-signed certificate)

### ISSUE THREAD

**Issue by anskibe** [nocodb/nocodb#9201]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

When i try to connect nocodb with my local self-hosted minio with self-signed certificate, i can't do this due to an error. Why?

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1533:34)
    at TLSSocket.emit (node:events:537:28)
    at TLSSocket.emit (node:domain:482:12)
    at TLSSocket._finishInit (node:_tls_wrap:947:8)
    at ssl.onhandshakedone (node:_tls_wrap:728:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}

Node.js v18.5.0

### Suggested solution

let us use self-signed certificate for localhost minio installations

**Comment by anskibe** [comment]
the certificate for minio is valid, even browser doesn't throw any error
i use both nocodb and minio directly in windows by binary files
but the same behaviour i mentioned before on my linux installation (experemental)

**Comment by anskibe** [comment]
i'm sure that i'ts nodejs issue
but i still don't know how to fix it using source code to rebuild my own nocodb without this error
and i'm sure that it's useful to fix this error in new public release

**Comment by anskibe** [comment]
https://stackoverflow.com/questions/53864398/self-signed-certificate-in-certificate-chain-error-while-using-node-js-sdk-for-w

**Comment by anskibe** [comment]
well
i was able to fix it locally in package.json

"watch:run": "cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 ....

**Comment by anskibe** [comment]
can anyone suggest how or where it will be better to implement it in code 
to commit in project repo
where to search the right way?

**Comment by DarkPhoenix2704** [comment]
useSsl is set to mandatory by accident. Has been reverted here

https://github.com/nocodb/nocodb/pull/9205



If you want to add support for custom certificates, You can refer this

https://github.com/nocodb/nocodb/blob/1916d5a037a8f1a57d1e76fb2e4c03d0fbf9c814/packages/nocodb/src/plugins/mino/Minio.ts#L25

https://min.io/docs/minio/linux/developers/javascript/API.html#http-request-options
