### ISSUE TITLE
🐛 Bug: Link URLs are sometimes not working - link takes me to a different view

### ISSUE THREAD

**Issue by danielrosehill** [nocodb/nocodb#9202]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

I have views that I frequently access in my NoCoDB deployment (NPM on a Linux server) saved as Chrome bookmarks.

Sometimes, when I click on the bookmarks, instead of taking me to the view I had saved they take me to another one.

It sometimes takes refreshing the tab a few times for the URL to update.

I verified that the correct URLs are bookmarked.

### Desired Behavior

Each view has a unique URL so that you can store a bookmark that will "jump" you straight to that part of the navigation. I presume this is how the feature is supposed to work.

### Project Details

Server: Linux
Installation method: NPM
Database: Standalone Postgres

**Comment by danielrosehill** [comment]
Hi everyone!

I *think* I have figured out a resolution.

I was testing the API yesterday and noticed that the base URL was http://. After updating that to https:// the URLs now seem to be taking me to the correct views. 

(Leaving open just in case you wish to track it further)

**Comment by chuntungho** [comment]
I tested that it not support `mailto:` or `tel:` schema.
Though I can use http redirect to work around, but it open url in a `_blank` window, hope the target can be configured.

**Comment by jpfaias** [comment]
my problem is somehow related. i'm trying to add a URL that starts with "rustdesk://" but choosing URL type it always adds https to the beggining. I was going for a clickable link but witha a complete url pre formated
