### ISSUE TITLE
🔦 Feature: Live refresh on data tables

### ISSUE THREAD

**Issue by danielrosehill** [nocodb/nocodb#9209]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

Although NocoDB isn't intended as a standalone backend (right?), for many it's "good enough" to meet that need. 

One minor limitation that it would be great to be able to work around: the ability to automatically refresh data. 

The use-case would be something like this:

Person A is populating data into a very frequently updated table. For argument's sake, perhaps it contains reports of some nature or another. 

Person B is responsible for evaluating that data as it comes in.

In a setup like this, it would be helpful if the view (element) that person B was looking at cook check for new rows every X seconds and automatically add them to the view if they were detected

### Suggested solution

Not sure how or whether this could be implemented technically but I think the above describes the idea (FYI: I'm pretty sure that Airtable has this feature already)

**Comment by dstala** [comment]
@danielrosehill we will be happy to know more about your use case. 

Real time collaboration is an old pending feature request & can be tracked over here. [Feature : Realtime Collaboration](https://github.com/nocodb/nocodb/issues/148). Will close this issue hence.
