### ISSUE TITLE
🔦 Feature: The ability to configure a default value for date parameters to be today's date

### ISSUE THREAD

**Issue by danielrosehill** [nocodb/nocodb#9224]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

It's very common in database systems to have the ability to configure a default parameters for a date column type with today's date.

Use-case is data entry where the vast majority of entries are dated at today's date with only a narrow series of cases being entered with retrospective dates (etc).

### Suggested solution

Just as you can configure a default option in dropdowns, it would be great if there were an option to have a default value for the date field to default to today

**Comment by dstala** [comment]
this feature is supported now. should be available from next OSS release.
