### ISSUE TITLE
🐛 Bug: Postgres test connection succeed even though no database exist

### ISSUE THREAD

**Issue by nghduc97** [nocodb/nocodb#9257]
### Please confirm that the bug report does ***not*** already exist

- [x] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Create a Postgres connection to a running Postgres instance
2. In the `database` field, enter a random name that doesn't exist
3. Click `Test connection`

Here the UI will show `Test successful` while in the logs:
```
nocodb-1  | error: database "xyz" does not exist
nocodb-1  |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
nocodb-1  |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
nocodb-1  |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
nocodb-1  |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
nocodb-1  |     at Socket.emit (node:events:519:28)
nocodb-1  |     at Socket.emit (node:domain:488:12)
nocodb-1  |     at addChunk (node:internal/streams/readable:559:12)
nocodb-1  |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
nocodb-1  |     at Readable.push (node:internal/streams/readable:390:5)
nocodb-1  |     at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
nocodb-1  |   length: 89,
nocodb-1  |   severity: 'FATAL',
nocodb-1  |   code: '3D000',
nocodb-1  |   detail: undefined,
nocodb-1  |   hint: undefined,
nocodb-1  |   position: undefined,
nocodb-1  |   internalPosition: undefined,
nocodb-1  |   internalQuery: undefined,
nocodb-1  |   where: undefined,
nocodb-1  |   schema: undefined,
nocodb-1  |   table: undefined,
nocodb-1  |   column: undefined,
nocodb-1  |   dataType: undefined,
nocodb-1  |   constraint: undefined,
nocodb-1  |   file: 'postinit.c',
nocodb-1  |   line: '1019',
nocodb-1  |   routine: 'InitPostgres'
nocodb-1  | }
```

### Desired Behavior

Show errors saying on the UI saying database doesn't exist

### Project Details

Node: **v20.15.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.252.0**

**Comment by nghduc97** [comment]
The code seems to explicitly check `postgres` database in case the given database doesn't exist, can any maintainer give insight why this was the case?

https://github.com/nocodb/nocodb/blob/2f2395fb7268557ebb5fe5f375c35a3b623fffa9/packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts#L254-L268

**Comment by dstala** [comment]
Database, if it doesn't exist will be created. There is a placeholder that displays this info.



![Image](https://github.com/user-attachments/assets/4fa2edf9-dbdb-41b8-8e51-dec043eda8ac)

**Comment by nikhilbhatia08** [comment]
@dstala But there is no such placeholder that displays info
<img width="789" alt="Screenshot 2024-09-15 at 12 42 07 PM" src="https://github.com/user-attachments/assets/fcd0a093-e550-47a1-8801-8880f755add6">
I would like to work on this issue and fix it

**Comment by nikhilbhatia08** [comment]
@dstala I think we need to change the placeholder here also
<img width="789" alt="Screenshot 2024-09-15 at 12 42 07 PM" src="https://github.com/user-attachments/assets/744e99aa-a558-4282-a557-0078f15cd2a7">
If there are any changes required I would like to contribute to the issue.

**Comment by dstala** [comment]
this is by design. we intend to create database if it doesn't exist. the place holder is apt & explains the situation appropriately already.
