### ISSUE TITLE
🔦 Feature: Multi field editor - show system fields

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#9264]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

introduce 3 dot menu around new field area & include following options
- hide all / show all
- hide / show system fields

### Suggested solution

- hide all / show all will toggle visibility status of the field, will not remove it from the MFE list shown
- system fields when displayed will continue to remain in read only mode

### Additional context

x

**Comment by yaten2302** [comment]
Hey @dstala , could you please guide that where's the new field area? I was searching for it in a sample table, but I wasn't able to find that? <br>
![image](https://github.com/user-attachments/assets/f3a2f289-0011-41c6-b09c-b1ef1c3dda80)

**Comment by dstala** [comment]
@yaten2302 Please pick the issues marked as "👋 For : Community or Good First Issue"
