### ISSUE TITLE
🐛 Bug: Button in kanban has issue

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#9272]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

<img width="616" alt="image" src="https://github.com/user-attachments/assets/c25d80a7-7f7b-4598-a567-c330b9653414">

### Desired Behavior

.

### Project Details

.

**Comment by DarkPhoenix2704** [comment]
https://github.com/nocodb/nocodb/pull/9273 will fix the issue
