### ISSUE TITLE
🔦 Feature: Add display names for fields

### ISSUE THREAD

**Issue by fengdu126** [nocodb/nocodb#9298]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

Currently, in all views, fields display the field names from the database,This is not very intuitive.

### Suggested solution

Hope to add display names for the fields

**Comment by salim-b** [comment]
You can already change the title of any field, either via right-click <kbd></kbd> or via the RESTful API (NocoDB internally keeps a `title` attribute besides the DB-level `column_name` for every table column).

Changing it via the UI alters both `column_name` and `title` internally, so it will result in a DB-level change. But via the [`PATCH /api/v2/meta/columns/{id_col}`](https://meta-apis-v2.nocodb.com/#tag/DB-Table-Column/operation/db-table-column-update) API endpoint, you can only change the `title` and keep the `column_name` the same (NocoDB displays the `title` in the UI).

Hope this helps.

**Comment by dstala** [comment]
Thanks for the details @salim-b 
Please reopen this ticket @fengdu126 if you need additional support on this.

**Comment by fengdu126** [comment]
![image](https://github.com/user-attachments/assets/af02a03d-d8cf-4114-bd0e-20fd1add3e74)

I tried to use the API to make changes, but encountered an error:
Cannot read properties of undefined (reading 'replace')

**Comment by salim-b** [comment]
> I tried to use the API to make changes, but encountered an error:
> Cannot read properties of undefined (reading 'replace')

As far as I can tell, the [`PATCH /api/v2/meta/columns/{columnId}`](https://meta-apis-v2.nocodb.com/#tag/DB-Table-Column/operation/db-table-column-update) API endpoint requires both `column_name` and `title` in the request body to be set. Simply set `column_name` to the old value if you don't want to alter the DB schema.

**Comment by fengdu126** [comment]
> > I tried to use the API to make changes, but encountered an error:
> > Cannot read properties of undefined (reading 'replace')
> 
> As far as I can tell, the [`PATCH /api/v2/meta/columns/{columnId}`](https://meta-apis-v2.nocodb.com/#tag/DB-Table-Column/operation/db-table-column-update) API endpoint requires both `column_name` and `title` in the request body to be set (at least for non-virtual columns). Simply set `column_name` to the old value if you don't want to alter the DB schema.

thanks!!! it is ok...

**Comment by Aaron-Lutz** [comment]
Hey guys @salim-b @fengdu126 

Is still approach still working for you guys? I tried the same and get this response:

{
  "error": "DATABASE_ERROR",
  "message": "There was a syntax error in your SQL query.",
  "code": "ER_PARSE_ERROR"
}

I set both the title and column_name, and also tried with additional fields that might inexplicitly be required.
