### ISSUE TITLE
🐛 Bug: On windows file thumbnail not showing & no file found when trying to download attachments

### ISSUE THREAD

**Issue by Sohail2949000** [nocodb/nocodb#9317]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Trying to upload attachments with records in windows after upload is completed the file thumbnails not showing 
![image](https://github.com/user-attachments/assets/4231f3f6-ec51-445e-a2b8-ffde7eae5f90)

and if we open the attachments no preview available 
![image](https://github.com/user-attachments/assets/b0cb7212-641e-434e-95dc-72f7921e305c)

and if we try to download it says file not found.
![image](https://github.com/user-attachments/assets/b26b56e8-c193-4b81-9822-c6be24467bb5)

### Desired Behavior

the attachments should show thumbnails and able to download

### Project Details

![image](https://github.com/user-attachments/assets/07948ddb-bf56-4076-a88c-d1acc6515655)

**Comment by DarkPhoenix2704** [comment]
Can you share the attachment cell contents here? 


Also which Storage plugin are you using?

**Comment by Sohail2949000** [comment]
[Files+and+Folders+advanced+level+provisioning+based+on+different+parameters.pdf](https://github.com/user-attachments/files/16719711/Files%2Band%2BFolders%2Badvanced%2Blevel%2Bprovisioning%2Bbased%2Bon%2Bdifferent%2Bparameters.pdf)
![Screenshot (2)](https://github.com/user-attachments/assets/de6110b3-42d6-404f-9675-f0e668c579e6)
