### ISSUE TITLE
🔦 Feature: Select type field to increase the ability to associate to other tables

### ISSUE THREAD

**Issue by fengdu126** [nocodb/nocodb#9327]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

Now the options are fixed, not dynamically selected from other tables.

### Suggested solution

Hope then select type field to be associated with other tables.

**Comment by dstala** [comment]
Related issue(s) where this particular feature request will be tracked. Please vote up in the associated issues

[[Feature] Multiselect > option auto-populate values from column rows](https://github.com/nocodb/nocodb/issues/1036)
[🔦 Feature: Populating single select columntype with database records](https://github.com/nocodb/nocodb/issues/4356)
[🔦 Feature: Single select values from table](https://github.com/nocodb/nocodb/issues/7154)
