### ISSUE TITLE
🔦 Feature: the calculated items in the footer automatically calculated

### ISSUE THREAD

**Issue by fengdu126** [nocodb/nocodb#9331]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

First open the view, the calculated items in the footer are not automatically calculated,must click and select again to display the calculation results.

![image](https://github.com/user-attachments/assets/34190aa8-b3e3-4e77-af3f-6e72cd2f77c9)

### Suggested solution

Hope when first open the view,the calculated items in the footer can be  automatically calculated.

![image](https://github.com/user-attachments/assets/bc84367e-b667-405a-acbc-d8dd8f09d14a)

**Comment by fengdu126** [comment]
> This seems to be a bug.
> 
> Would you be able to share the columns and the associated aggregations in that table?
> 
> Also, what database are you using?

thanks,it is my problem,i change the column title with api not with the uidt.

**Comment by DarkPhoenix2704** [comment]
> thanks,it is my problem,i change the column title with api not with the uidt.


No no, it should work have worked in that case also

**Comment by DarkPhoenix2704** [comment]
Do you have any invalid Formula Column, configured in the view?

**Comment by dstala** [comment]
@fengdu126 please reopen this ticket with additional details if you still face this issue in latest release (0.257)
