### ISSUE TITLE
🔦 Feature: display the column id

### ISSUE THREAD

**Issue by fengdu126** [nocodb/nocodb#9335]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

the table id can be displayed:
![image](https://github.com/user-attachments/assets/5d6b88c3-11e8-4755-84bc-0f4563f7f088)

but the column id  only be found in the database.

### Suggested solution

It would be nice if it could be displayed here and could be paste：

![image](https://github.com/user-attachments/assets/1bd9bd66-4672-4214-962b-be093a0c1c1b)

**Comment by DarkPhoenix2704** [comment]
This is included in the https://github.com/nocodb/nocodb/pull/9256

Will be available in next release

**Comment by fengdu126** [comment]
> This is included in the #9256
> 
> Will be available in next release

If you switch the language to a different one, the ID will not be displayed：

![image](https://github.com/user-attachments/assets/3838ced6-c8d6-4f4e-a298-4076fc1b9e50)

If it's in English, there's no problem：

![image](https://github.com/user-attachments/assets/c7c84661-74a7-4a6f-8cd8-0a3bf2fbf2bf)
