### ISSUE TITLE
`npx create-nocodb-app` infinite output loop

### ISSUE THREAD

**Issue by codesplode** [nocodb/nocodb#934]
**Steps To Reproduce**
1. Run `npx create-nocodb-app`
2. Wait
3. See infinite loop of output (see screenshot).

**Expected behavior**
An install similar to the sample.

**Screenshots**
![image](https://user-images.githubusercontent.com/823828/148663754-779513ae-ccda-430a-ba4d-4528d7f4d5d7.png)

NocoDB version : **0.84.1**
Node version : **v16.13.1**
Arch type: **x64**
Platform: **Ubuntu Server 20.04**
Docker: **false**
packageVersion: **0.84.1**

**Comment by codesplode** [comment]
It appears after further research that Marak, creator of the colors library has sabotaged his own library to make some sort of statement. Because so many dependencies depend on colors, it is best to override those to version 1.4.0 from what I have read so far. Hopefully a fork comes out of it and Marak can get the help he needs.

https://github.com/Marak/colors.js/issues/285

**Comment by DABH** [comment]
Please just pin the colors dependency to 1.4.0, and see the following if you need additional context: https://github.com/Marak/colors.js/issues/285#issuecomment-1008212640

**Comment by wingkwong** [comment]
@o1lab Apart from changes done in aa57501, please also bump ``cli-table3`` version to ``0.6.1``. They've fixed it in [here](https://github.com/cli-table/cli-table3/commit/e5fa021a9a38a035124da3a2b80fd572046c068a).

https://github.com/nocodb/nocodb/blob/aa57501949bb50221a4f14eb904d2a89416e0005/packages/nc-cli/package.json#L63

**Comment by wingkwong** [comment]
Verified - 6d39462.

**Comment by pranavxc** [comment]
Fixed in `0.84.4`
