### ISSUE TITLE
🐛 Bug: Form description revert to original after a while (Duplicate)

### ISSUE THREAD

**Issue by igmarketing** [nocodb/nocodb#9340]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Duplicate a table with a form view, and edit the form description.

Note: Fields change works fine, the only problem is with the form description. Also, please note that this works fine for a few hours, up to a day.. but the next day it will be reverted to the original form description (copied one)the 

### Desired Behavior

The form description should remain after being edited, it shouldn't revert to the initial form description from copied table.the 

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.255.0**

**Comment by DarkPhoenix2704** [comment]
Tried in the NocoDB Cloud and Opensource. 

I couldn't reproduce the issue

**Comment by DarkPhoenix2704** [comment]
Not Reproducible

**Comment by EllieJudge** [comment]
Can confirm I have also had this problem, twice.
