### ISSUE TITLE
Reset password page title

### ISSUE THREAD

**Issue by Louis-Simon22** [nocodb/nocodb#935]
Hello, just to point out that the reset password page's title seems to be from a template

NocoDB version: 0.84.3

![image](https://user-images.githubusercontent.com/22861550/148720616-dd1d3ae0-25b2-4801-be0f-13ecd96d50de.png)

**Comment by wingkwong** [comment]
Thanks for reporting. Will fix soon.

**Comment by pranavxc** [comment]
Fixed in `0.84.5`
