### ISSUE TITLE
🔦 Feature: when check the "Limit record selection to a view",configure filter...

### ISSUE THREAD

**Issue by fengdu126** [nocodb/nocodb#9364]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

Deployed through docker with latest, it was found that the filtering function was missing:

![image](https://github.com/user-attachments/assets/9213984a-c147-4bb2-8c71-c0cfc1a891d4)

But I found that the documentation has this item in it：

![image](https://github.com/user-attachments/assets/48cea3e8-ac4d-4028-9e55-13dc262363dd)

### Suggested solution

Hope to add the configure filter

**Comment by nnasirzada** [comment]
Hi, the filter is still missing.

**Comment by gdpix** [comment]
It looks like this feature might only be offered in the cloud version of NocoDB
I noticed the cloud icon beside the feature in the docs

<img width="996" alt="image" src="https://github.com/user-attachments/assets/e506c606-315b-42ea-b3cd-063adc234733">
