### ISSUE TITLE
RELATIOn HAS ONLY ONE

### ISSUE THREAD

**Issue by bchaz42** [nocodb/nocodb#938]
Bonjour, 
Nous connaissons les relations HAS MANY et MANY to MANY mais la relation HAS ONE n'est pas disponible. Cette relation est essentielle car elle permettrait  d'utiliser une table , avec des tris et des recherches pour établir une relation.  Un champ de type "Single select" ne permet pas de trier ou filtrer la liste des valeurs possibles. 

Merci par avance

**Comment by o1lab** [comment]
When you create a has many relation between say a ```parent``` and ```child``` table. Child table has one relation. There is an issue open to sort and filter based on other table values so I would be closing this. Feel free to reopen if I didn't understand it correctly  (translated the French in google)

**Comment by bchaz42** [comment]
Bonjour, Could we have new  relation "HAS ONE".  We knew already "HAS MANY"  et "MANY TO MANY". 
This  relation "HAS ONE" must be like red example. 
![image](https://user-images.githubusercontent.com/94845203/148902054-726fd129-18b4-4cae-bf21-8eb2f7ef2ea2.png)

Table parent can have only one link with table child, but table child can be share with table parent

**Comment by LnLcFlx** [comment]
I understand that this is possible by adding a "Has Many" column in table A to contains entries in table B (then table B would have a "Has One" column with a single entry of table A).
But it took me very long to figure this out.
It would be more user-friendly to be able to do this from inside the UI of table *B*.
Meaning: Adding a "Has one" column in table B would simply be implemented by adding a "has many column" in table A.

Maybe there is another even more intuitive way to revamp the entirety of the linking system but the state it is in rn is not very straight forward.
