### ISSUE TITLE
🐛 Bug: No Super-Admin available

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#9386]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Today I upgraded to 0.255.2 - and found out there is no Super-Admin anymore.
I have two instances in Docker:
1. On Port 9090 with meta and data in one table - that one causes the problem.
2. On Port 9092 with separate meta and data table - that one works perfect.
In 1. I found out there is no Super-Admin - therefor I don't have rights to watch audit logs nor get settings buttons.

### Desired Behavior

Installation on port 9090 should have the same behaviour like on port 9092.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.255.2**

Installation on port 9090:

![NocoDB 9090](https://github.com/user-attachments/assets/eb70060d-cf2c-41e0-ad4c-61f26fd6785a)

![NocoDB 9090-2](https://github.com/user-attachments/assets/24aef176-1631-46c0-9c12-169be387ee4e)

Installation on port 9092:

![NocoDB 9092](https://github.com/user-attachments/assets/c211195c-677e-4bd8-9f49-92d2a7611d2d)

**Comment by pranavxc** [comment]
Can you clarify couple of things,

- What you mean by `with meta and data in one table` ? Do you mean no external DB connected ?
- Are you modifying metatables('nc_users_v2') using external tools ?
- Do you have any environment variable configured for setting up super admin ? (`NC_ADMIN_EMAIL` and `NC_ADMIN_PASSWORD`)

**Comment by WeT-Klb** [comment]
I use NocoDB on my NAS. The installation on port 9092 is separated into database nocodb_meta and nocodb_data - both on MariaDB running on the NAS - but not inside Docker. It was my mistake - i should write database instead of table.

The installation on port 9090 is running in only one database nocodb_docker - meta and data together. But also running outside Docker.

Before i had some trouble with NocoDB - so I was told (maybe from you ?) what exactly to type in phpMyAdmin to make it work again.

I didn't set anything by myself . If you want I can send a DUP of my database to you, if you tell me how.
Just don't want to post it here in public.

**Comment by pranavxc** [comment]
> I use NocoDB on my NAS. The installation on port 9092 is separated into database nocodb_meta and nocodb_data - both on MariaDB running on the NAS - but not inside Docker. It was my mistake - i should write database instead of table.
> 
> The installation on port 9090 is running in only one database nocodb_docker - meta and data together. But also running outside Docker.
> 
> Before i had some trouble with NocoDB - so I was told (maybe from you ?) what exactly to type in phpMyAdmin to make it work again.
> 
> I didn't set anything by myself . If you want I can send a DUP of my database to you, if you tell me how. Just don't want to post it here in public.

Thanks for sharing the details, let's connect over discord for further details. Our discord channel link - https://discord.gg/5RgZmkW

**Comment by dstala** [comment]
Please reopen if you need any further help or connect with us on discord
