### ISSUE TITLE
can't reset password

### ISSUE THREAD

**Issue by wonb168** [nocodb/nocodb#9389]
![image](https://github.com/user-attachments/assets/62951f13-3fea-437c-89de-6de4b8be71e9)

**Comment by pranavxc** [comment]
Looks like you are using older version of NocoDB, please upgrade to latest version to avoid any issues in older versions.  Then forgot password option only works if any of the Email plugin is configured. If not configured you have to login as super admin user and from user management menu you can get reset url for the user. In case if you forgot password of super admin user then use following environment variables to reset email and password of super admin.

`NC_ADMIN_EMAIL` and `NC_ADMIN_PASSWORD`

Ref: https://docs.nocodb.com/getting-started/self-hosted/environment-variables
