### ISSUE TITLE
🐛 Bug: Invalid date on postgresql DB "date" field

### ISSUE THREAD

**Issue by nirkons** [nocodb/nocodb#9409]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

I added to my DB a "date" field (not timestamp)
I inserted a date, I tried directly on the DB and via nocodb API (which works),
on the DB the value is fine, in format YYYY-MM-DD
on nocodb I see "Invalid date"

I tried clicking "edit field" and changing the format (though the default format was correct), did not help.

![image](https://github.com/user-attachments/assets/774ebb61-3267-4d18-ab80-cb5f5ccbf289)

### Desired Behavior

the date should be displayed in the UI

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.255.2**

**Comment by nirkons** [comment]
> Hey @nirkons! I'm here to help you with any bugs, questions, or contributions you have in mind. Let's work together to resolve your issue.
> 
> To fix the issue where a "date" field in PostgreSQL DB shows as "Invalid date" in the NocoDB UI despite being correctly formatted as YYYY-MM-DD in the database, you should ensure that the date format in NocoDB is configured to match the format used in your PostgreSQL database.
> 
> Here are the steps to configure the date format in NocoDB:
> 
> 1. Click on the `+` icon to the right of the `Fields header`.
> 2. In the dropdown modal, enter the field name (optional).
> 3. Select the field type as `Date` from the dropdown.
> 4. Configure the `Date Format` to `YYYY-MM-DD`.
> 5. Configure the default value (optional).
> 6. Click on the `Save Field` button.
> 
> By ensuring that the date format in NocoDB is set to `YYYY-MM-DD`, it should correctly interpret and display the date values from your PostgreSQL database [[1]](https://docs.nocodb.com/fields/field-types/date-time-based/date).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I've done that, as mentioned, does not help.

**Comment by dstala** [comment]
@nirkons how did you insert into date cell? was it by typing entire date manually? copy paste? or by manually selecting from the dropdown picker?

**Comment by dstala** [comment]
Also, did you configure any default value? If you can help share a video to reproduce this issue on a new table - it will help.

**Comment by salim-b** [comment]
I cannot reproduce this with NocoDB v0.255.2 and an external PostgreSQL (16.4) data source.

**Comment by nirkons** [comment]
I resolved the issue.

The DB Datestyle was:
POSTGRES, YMD

once I changed it to
ISO, YMD

the dates appeared in nocodb properly.

**Comment by dstala** [comment]
Thanks for the confirmation @nirkons
