### ISSUE TITLE
[Feature] Limit API Token Permissions

### ISSUE THREAD

**Issue by Keyruu** [nocodb/nocodb#941]
Hello,
I just discovered this awesome tool and it fits my needs almost perfectly.

**Need for this feature**
One thing that I would need for my specific use-case would be to limit the API token to just be able to GET entries from a table. The API token shouldn't be able to POST, DELETE or PUT.

**Describe the solution you'd like**
A solution could be to limit the HTTP methods or limit the API token per endpoint basis.

**Describe alternatives you've considered**
A workaround for me currently would be to write an ambassador service that wraps the API.

**Comment by o1lab** [comment]
The current API tokens work according the role of the user.
