### ISSUE TITLE
🐛 Bug: text to numerical type conversion ignores negatives

### ISSUE THREAD

**Issue by sioutisc** [nocodb/nocodb#9417]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

- create new table
- create new column with name "test" and type "single line text"
- create new row and add the following data "-123" under column "test"
- select "edit field" for column test and convert to "number"
- The column is converted to numbers but the value is changed to "123"

### Desired Behavior

- the value upon conversion of row should be "-123"

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.255.2**

**Comment by salim-b** [comment]
On latest NocoDB v0.255.2, I can reproduce this bug with an external PostgreSQL data source. With an SQLite data source OTOH, negative numbers are properly converted from text to integer.
