### ISSUE TITLE
[Feature] : Has one

### ISSUE THREAD

**Issue by bchaz42** [nocodb/nocodb#943]
Bonjour, Pourrions-nous avoir une nouvelle relation "HAS ONE". On connaissait déjà "HAS MANY" et "MANY TO MANY".
Cette relation "A UN" doit être comme exemple rouge.
![image](https://user-images.githubusercontent.com/94845203/149143757-8cde0dd8-7d82-4a7b-9014-dba5d75a89d7.png)

La table parent ne peut avoir qu'un seul lien avec la table enfant, mais la table enfant peut être partagée avec la table parent

**Comment by o1lab** [comment]
Tracked in #491
