### ISSUE TITLE
🐛 Bug: Missing default value for "sum" rollup

### ISSUE THREAD

**Issue by LucBerge** [nocodb/nocodb#9437]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Create a table B
2. In table B create a field called "price" as number/currency
3. Create a table A
4. In table A, create a field called "sum" as a sum rollup of prices from table B
5. In table A, create a field called "formula" which is "sum + 1"
6. Create a new record in table A

The display value in "sum" for the new record is blank because there is no B object linked to A. Because of this, the cell "formula" cannot be computed either.

### Desired Behavior

The default value for rollups with the `Sum` function should be 0. Like `Count` and `Count distinct`.

**Comment by space-w-alker** [comment]
I'm new here and would like to contribute. Can this issue be assigned to me?
