### ISSUE TITLE
🐛 Bug: Meta API for get all bases with 403 response

### ISSUE THREAD

**Issue by dodevs** [nocodb/nocodb#9444]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

I'm receiving 403 from https://app.nocodb.com/api/v2/meta/bases. 

https://app.nocodb.com/api/v2/meta/bases/:baseId is working with no problem.

I'm sending xc-token in both requests

### Desired Behavior

I need the list of bases to map tables to when starting my service, so I would like there to be a solution

### Project Details

Using cloud

**Comment by dstala** [comment]
The following end point can be used to retrieve bases. 
/api/v1/workspaces/:workspaceId/bases


@pranavxc to confirm corresponding endpoint in v2.

**Comment by dodevs** [comment]
> The following end point can be used to retrieve bases. /api/v1/workspaces/:workspaceId/bases
> 
> @pranavxc to confirm corresponding endpoint in v2.

Nice! Thanks a lot

**Comment by dodevs** [comment]
Waiting for @pranavxc confirm v2 endpoint

**Comment by pranavxc** [comment]
> Waiting for @pranavxc confirm v2 endpoint

We have only `v1` api mapping for that endpoint, which is `/api/v1/workspaces/:workspaceId/bases`. Soon I will add these missing alias in controller and add them in swagger. We have an active branch for these changes - https://github.com/nocodb/nocodb/tree/nc-feat/missing-api-v2.
