### ISSUE TITLE
🐛 Bug: API does not adhere to 'limit' parameter if 'limit' of results per page is less than 10.

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#9445]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

As reported on discord; reproducible

### Desired Behavior

adhere to specified limit

### Project Details

255.2

**Comment by pranavxc** [comment]
By default, an upper and lower bound is set for the query limit. You can adjust the minimum value by setting the `DB_QUERY_LIMIT_MIN` environment variable. For more details, refer to the documentation: [NocoDB Environment Variables](https://docs.nocodb.com/getting-started/self-hosted/environment-variables/#product-configuration).

**Comment by woodmin** [comment]
Set ENV DB_QUERY_LIMIT_MIN to 1. Adde url parameter limit=1. No effect. NocoDB still gets multiple items.
