### ISSUE TITLE
🐛 Bug: REST APIs display pageSize: 10 if limit<10

### ISSUE THREAD

**Issue by Sunatley** [nocodb/nocodb#9451]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Try to run a get request to the api, for example:

curl -X 'GET' \
'https://.../api/v2/tables/.../records?limit=9&shuffle=0&offset=0 ' \
  -H 'accept: application/json' \
  -H 'xc token: ...'

Where limit < 10, pageSize will be always 10.

### Desired Behavior

If limit < 10, i want to get pageSize = limit

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.255.2**

**Comment by o1lab** [comment]
The minimum page size is now 10 if there are that many records. You can paginate on the client side.

**Comment by dstala** [comment]
@Sunatley You can configure DB_QUERY_LIMIT_MIN as per your needs on self hosted instance. Details here https://docs.nocodb.com/getting-started/self-hosted/environment-variables

**Comment by Sunatley** [comment]
> @Sunatley You can configure DB_QUERY_LIMIT_MIN as per your needs on self hosted instance. Details here https://docs.nocodb.com/getting-started/self-hosted/environment-variables

Environment variables do not change behavior

Environment variables:
<img width="588" alt="Screenshot 2024-09-11 at 12 15 19" src="https://github.com/user-attachments/assets/85101f7c-698e-4f07-bca8-6dd1d69f8da0">

Request:
<img width="1395" alt="Screenshot 2024-09-11 at 12 16 53" src="https://github.com/user-attachments/assets/358b4dd0-f3ff-4b6a-8607-7066448355f3">
