### ISSUE TITLE
[Bug] Formula LOG on MSSQL

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#949]
LOG formula works as documented for SQLITE, MySQL, PostgreSQL. Fails for MSSQL

SQLITE documentation- In the two-argument version of log(B,X), the first argument is the base and the second argument is the operand. This is the same as in PostgreSQL and MySQL, but is reversed from SQL Server which uses the second argument as the base and the first argument as the operand.

**Expected behavior**
NocoDB documentation indicates LOG function to be log(B,X). MSSQL, its reversed.

**Comment by pranavxc** [comment]
Fixed in `0.84.7`
