### ISSUE TITLE
🐛 Bug: Open .doc format is not working.

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#9495]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Try to open any .doc format file from attachment - it mentiong open in google doc but never works.

### Desired Behavior

.

### Project Details

.

**Comment by DarkPhoenix2704** [comment]
[file-sample_100kB.doc.zip](https://github.com/user-attachments/files/17144170/file-sample_100kB.doc.zip)


Tried using a sample doc file. It works. 

Can you verify the file is not corrupted
