### ISSUE TITLE
🐛 Bug: Nested Create Record Modal - Hide Fields, change display value field

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#9498]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Open a new record form for a link field
Hidden fields of default view are not applied
When you try to hide a field it throws

### Desired Behavior

It should simulate exact behavior with expanded form of linked table (default view) - So user should see hidden fields as following as well as should be able to hide them
<img width="258" alt="image" src="https://github.com/user-attachments/assets/1f024a35-c2af-4663-ba13-5529cb13a80d">

### Details

Reported by: XORAO from Discord

### Attachments

https://discord.com/channels/661905455894888490/661905455894888493/1285462294633119744

**Comment by rameshmane7218** [comment]
- [ ]  Change display value fields visibility issue if we open expanded form from link record dropdown
![Screenshot 2024-12-27 at 12 48 13 AM](https://github.com/user-attachments/assets/191468e3-ab47-4bc5-b67f-d5e3a312987e)
