### ISSUE TITLE
🐛 Bug: nocodb form browser tabs redirect after opening nocodb in a second tab

### ISSUE THREAD

**Issue by ghost** [nocodb/nocodb#9501]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

whenever i have a nocodb form open in a tab and then open another tab with nocodb itself so i can directly edit data in my tables, the browser tab with the nocodb form is redirected to nocodb as well.

this can be frustrating as it occasionally happens when i'm filling out a form and i lose progress when the form redirects.

### Desired Behavior

the browser tab with the form should not be impacted when opening nocodb in another tab.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.255.2**

**Comment by pranavxc** [comment]
Are you referring to shared form view by mentioning  `Nocodb form browser tabs`?

**Comment by pranavxc** [comment]
> > Are you referring to shared form view by mentioning `Nocodb form browser tabs`?
> 
> yes, sorry - should have elaborated. i've created forms and favorited the shared links so i can easily open and input data without having to open nocodb. those are the forms that redirect when i open nocodb in another tab while filling them out.

Thank you for confirming. It seems to be related to token generation. I’ll try to reproduce the issue locally and work on a fix.
