### ISSUE TITLE
🐛 Bug: Search doesn't find entry but filter does

### ISSUE THREAD

**Issue by springfielddatarecovery** [nocodb/nocodb#9514]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

We have a large table with approximately 10,000 records, I believe this is what causes the issue as other tables do not have it.

1. Go to search icon at top right
2. Enter text which a record has
3. Record will not be found
4. Use filter instead
5. Record found!

These records have a text field which usually stores < 10 characters. But search can't find the record with this search text, I believe because it's only searching the first page?

### Desired Behavior

Make the search function actually search

### Project Details

Hosted on app.nocodb.com.

**Comment by springfielddatarecovery** [comment]
1. Searching past the first page should not require modifying database settings.
2. I do not believe we can change these settings as we are hosted on app.nocodb.com.

**Comment by mertmit** [comment]
Can you give us a sample data & what you are searching?
Search works as temporary filter on selected field on the underlying layer - you can see the API call on your browser's developer tools network tab

Path should look something like: https://WSID.nocodb.com/api/v1/db/data/noco/BASE/MODEL/views/VIEW?offset=0&limit=25&where=(COLUMNTITLE,like,%25QUERY%25)

Can you confirm what is happening on your side?

**Comment by springfielddatarecovery** [comment]
Now upon trying to replicate this bug for a test case I am unable to do so, but I can affirmatively report that this has happened several times in September. Perhaps the bug fixed itself. You can close this issue for now, I will re-open if we run across it again.
