### ISSUE TITLE
[Bug] Condition for webhook automation does not take boolean type into consideration

### ISSUE THREAD

**Issue by arecvlohe** [nocodb/nocodb#953]
NocoDB used as docker : **false**
NocoDB version : **"nocodb": "^0.84.6"**
Database used in NC_DB URL  : **pg**
Project was created  by clicking : **New Project by connecting to external database**
Database on which spreadsheet is created : **pg**
OS on which NocoDB is running : **Ubuntu 18.04.6 LTS**
Node.js version if running as node : **v15.3.0**
Database version : **Postgres 12.9**

**Steps To Reproduce**
1. Install Slack App
1. Create webhook automation for Slack app that happens after an update
1. Add a condition for when the update happens
1. Condition needs to be related to a column like a checkbox or another column that implements a boolean type (TRUE/FALSE) 
1. Example condition would be: `where, column_name, is equal, true`

**Notes**
1. An example JSON that is sent back to the BE is: 
```"[{\"field\":\"Validated\",\"op\":\"is equal\",\"value\":\"true\",\"logicOp\":\"and\"}]")```.
1. Even after the values are parsed, with JSON.parse, the value remains a string:
```
[
  {
    "field": "Validated",
    "op": "is equal",
    "value": "true",
    "logicOp": "and"
  }
]
```
1. The check I believe happens here: https://github.com/nocodb/nocodb/blob/1cbaaab6bf838aa8c38a35f3fab06670ca8d9264/packages/nocodb/src/lib/noco/common/BaseModel.ts#L397. `data[field]` is probably `TRUE` while `con.value` is `"true"`. These would never equate unless the value itself is parsed further to see if it can be converted into a boolean value. The suggested change would probably be to just do: `JSON.parse(con.value)`.

**Expected behavior**
When the condition is met, such as when a column is true and the condition put in is `"true"`, then the webhook should be sent out afterward. I believe this is not happening because the values are not parsed from the JS side, I believe they are all literal strings instead of appropriate values.

**Comment by o1lab** [comment]
Fixed in 0.84.7

**Comment by arecvlohe** [comment]
Awesome!

**Comment by anonfreak** [comment]
So I expect the same problem in the current version. It seemed to be fixed in one of the later versions.
In the GUI, I want to set a webhook condition based on a boolean. (See below)
![image](https://user-images.githubusercontent.com/11429848/194838058-938dd790-f545-4f41-8f9b-6c4d7b3e2990.png)
But when I change the specific field from false to true, nothing gets triggered. Could someone verify the bug exists in the current version?
