### ISSUE TITLE
🐛 Bug: "Redirect to URL" setting does not work in a Form View 

### ISSUE THREAD

**Issue by imajus** [nocodb/nocodb#9571]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Anyone should be able to reproduce simply as follows:
1. Set "Redirect to URL" setting in a Form View to `https://example.com/{record_id}`
2. Share the Form View
3. Open the public form link in a new tab (incoginto/private is good)
4. Submit the form 

### Desired Behavior

It must redirect user to a link specified as the "Redirect to URL" option.
And it actually triggers the redirection but then another redirection is requested, essentially cancelling previous (see an attached screenshot).

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.255.2**

### Attachments

Form View settings:
![Screenshot from 2024-09-30 17-36-25](https://github.com/user-attachments/assets/6c693b90-70a5-4916-ad8b-fdc318308d1e)

Double redirection: 
![Screenshot from 2024-09-30 17-37-30](https://github.com/user-attachments/assets/89ce7c4b-1943-4313-b12c-3a95e0b11e4e)

**Comment by RangerCreaky** [comment]
Is this task completed? Or Can I pick this up?

**Comment by mohit-bhandari45** [comment]
Want to work on this issue, Please give me assignment.

**Comment by danewhitfield** [comment]
Happy to pick this up if it still requires work 😄
