### ISSUE TITLE
🐛 Bug: CSV import doesn't care for duplicated field names

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#9572]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

During CSV import, duplicated field names should be auto renamed. Currently they are retained as is & subsequent operations throw error

### Desired Behavior

Duplicated field names should be auto renamed with appropriate suffix

### Project Details

255.2

**Comment by mohit-bhandari45** [comment]
I want to work on this issue under hacktpober. Please assign me.

**Comment by PritamP20** [comment]
I too wanted to work on this🥲

**Comment by mohit-bhandari45** [comment]
> I too wanted to work on this🥲

we both can work, maybe

**Comment by PritamP20** [comment]
Perfect let's do it

**Comment by mohit-bhandari45** [comment]
> Perfect let's do it

hey bro have you done it?

**Comment by mohit-bhandari45** [comment]
@dstala Hey sir, I tested the application csv import, actually it is duplicating the field  names, and with that it is considering the data in the second duplicated field value from the first actual value. You can see in the image.
What this need to be? then!
![image](https://github.com/user-attachments/assets/93171557-a69d-47a9-928b-625c4d19d309)
