### ISSUE TITLE
🐛 Bug: skip confirmation modal for duplicate view

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#9576]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

- copy description as well by default when view is duplicated
- suffix `copy` for the new view name
- unlike table / base / field duplication, there are no configurable parameters here
- current view duplication confirmation modal is different from base / field / table duplication modal

### Desired Behavior

x

### Project Details

255.2

**Comment by mohit-bhandari45** [comment]
Please assign this to me.

**Comment by rameshmane7218** [comment]
@mohit-bhandari45 hey, I already started working on it, you can pick different issue
