### ISSUE TITLE
cannot read property "builder" of undefined

### ISSUE THREAD

**Issue by amarnath-wego** [nocodb/nocodb#960]
**Please enter the following details**

Node: v12.22.6
Arch: x64
Platform: linux
Docker: true
Database: mysql2
ProjectOnRootDB: false
RootDB: pg
PackageVersion: 0.84.6

Issue: 
Hello, i am trying to configure SES in nocodb and i am getting error `cannot read property "builder" of undefined`.
 what am i missing here? Any help is highly appreciated!

**Comment by pranavxc** [comment]
Fixed in `0.84.7`
