### ISSUE TITLE
🐛 Bug: Field "Show On Conditions" missing

### ISSUE THREAD

**Issue by AntoineChauvet** [nocodb/nocodb#9602]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

When creating a form, the field "Show On Conditions" is missing
![nocodedb](https://github.com/user-attachments/assets/8cad51d0-0ea5-4190-851b-f147685b2eb9)

### Desired Behavior

I should be allowed to cretae conditional field but the field does not appear

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.255.2**

(deployed via cloudron)

**Comment by rameshmane7218** [comment]
@AntoineChauvet Hey!, this feature is only available in the cloud version of NocoDB. 
But still this option will be visible in OSS  with disabled state and will be added in next release

**Comment by rameshmane7218** [comment]
@AntoineChauvet, we’ve decided to enable this feature in the OSS, and it will be available in the next release.

**Comment by AntoineChauvet** [comment]
Great ! Thank you for your quick answer
