### ISSUE TITLE
Feature: Allow "Monday" to be configured as first column in date picker

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#9633]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Currently it defaults to Sunday

### Desired Behavior

Date picker should be configurable

### Project Details

256

**Comment by dstala** [comment]
![Screenshot 2024-10-10 at 7 30 03 PM](https://github.com/user-attachments/assets/91b23aa0-1cf7-41b6-9df2-db72049e70b4)

**Comment by MaryamAlkhater** [comment]
Hello, I am a college student currently taking a software engineering class, and I am interested in working on an open-source project. Could I be assigned to this issue? @dstala
