### ISSUE TITLE
🔦 Feature: Pin datasheets as favorites for quick access

### ISSUE THREAD

**Issue by lumos0** [nocodb/nocodb#9635]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

If you want to quickly access the most frequently used or most critical datasheets from a variety of files in your workflow, you can now add them to the "Pin" section at the top of the left sidebar.

### Suggested solution

Pin datasheets as favorites
like https://help.aitable.ai/docs/guide/manual-favorite/#pinning-datasheets-as-favorites

### Additional context

![image](https://github.com/user-attachments/assets/4accb9a3-22b3-42d5-a2e1-9dbcbf90e3f4)

_No response_

**Comment by dstala** [comment]
@lumos0 NocoDB allows mapping selected bases as "Starred". Details [here](https://docs.nocodb.com/bases/actions-on-base/#star-base)

Proposal here is to star selected views?

**Comment by lumos0** [comment]
> @lumos0 NocoDB allows mapping selected bases as "Starred". Details [here](https://docs.nocodb.com/bases/actions-on-base/#star-base)
> 
> Proposal here is to star selected views?

Yes, I think starred datasheets/views will be used more frequently than starred bases

**Comment by lumos0** [comment]
> @lumos0 NocoDB allows mapping selected bases as "Starred". Details [here](https://docs.nocodb.com/bases/actions-on-base/#star-base)
> 
> Proposal here is to star selected views?

Yes, I think starred datasheets/views will be used more frequently used than starred bases
