### ISSUE TITLE
Getting spinning circle not initial page.

### ISSUE THREAD

**Issue by dgleba** [nocodb/nocodb#964]
NocoDB used as docker : true 
NocoDB version :        image: nocodb/nocodb:0.84.3
Database used in NC_DB URL  : mysql   -  NC_DB=mysql2://dbm:3306?u=muser&p=-xx-&d=dkrdb

Project was created  by clicking : 
Database on which spreadsheet is created : 
OS on which NocoDB is running :  ubuntu docker
Node.js version if running as node : docker
Database version : mysql 8

**Steps To Reproduce**
Start up db.
start up nocodb container.

just get spinning circle.

![image](https://user-images.githubusercontent.com/4622715/150060994-68a1cf38-8f7c-43ef-9589-69465c531db6.png)
```
albe@pmdsdata9:/srv/dkr/620dkrcollection/noco618_a_yard$ docker-compose -f ./618nocodb/docker-compose.yml up
Starting 618nocodb_nocodb_1 ... done
Attaching to 618nocodb_nocodb_1
nocodb_1  |
select * from `nc_api_tokens`
nocodb_1  | App started successfully.
nocodb_1  | Visit -> http://localhost:8080/dashboard
nocodb_1  | GET /dashboard/ 304 - - 65.837 ms
nocodb_1  | GET /dashboard/_nuxt/eff9a73.js 304 - - 33.053 ms
nocodb_1  | GET /dashboard/_nuxt/de1f174.js 304 - - 31.225 ms
nocodb_1  | GET /dashboard/_nuxt/c0536a2.js 304 - - 33.089 ms
nocodb_1  | GET /dashboard/_nuxt/b8e9d9d.js 200 1994932 - 70.759 ms
nocodb_1  | GET / 302 64 - 19.033 ms
nocodb_1  | GET /dashboard/ 304 - - 4.589 ms
nocodb_1  | GET /dashboard/_nuxt/eff9a73.js 304 - - 19.180 ms
nocodb_1  | GET /dashboard/_nuxt/de1f174.js 304 - - 15.155 ms
nocodb_1  | GET /dashboard/_nuxt/c0536a2.js 304 - - 15.916 ms
nocodb_1  | GET /dashboard/_nuxt/b8e9d9d.js 200 1994932 - 5.474 ms
nocodb_1  | GET /dashboard/ 304 - - 6.505 ms
nocodb_1  | GET /dashboard/_nuxt/eff9a73.js 304 - - 5.719 ms
nocodb_1  | GET /dashboard/_nuxt/de1f174.js 304 - - 12.215 ms
nocodb_1  | GET /dashboard/_nuxt/c0536a2.js 304 - - 13.005 ms
nocodb_1  | GET /dashboard/_nuxt/b8e9d9d.js 200 1994932 - 22.876 ms
```

**Expected behavior**

Get initial login page

**Screenshots**

Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql**
packageVersion:

**Comment by o1lab** [comment]
packageVerson is missing.

Could you please give a hard refresh = cmd+shift+r or ctrl+shift+r

**Comment by dgleba** [comment]
Today it is working. hmm. It may have been related to the internet connection I was using from off-site. It was a hotel.
