### ISSUE TITLE
🔦 Feature: Set `Date` default value to `today`

### ISSUE THREAD

**Issue by LucBerge** [nocodb/nocodb#9644]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

I have a table with a column date. When I create a new row, I want the default date value to be today.

I cannot use the `Created date` column type because:
1. I just want the YYYY-MM-DD format
2. I want to be able to change the date on the need

### Suggested solution

Maybe it is possible to add an option here to set the default value to today ![](https://www.pixenli.com/image/DpJMhhqc)

### Additional context

This is a existing feature in airtable.

**Comment by DarkPhoenix2704** [comment]
![image](https://github.com/user-attachments/assets/d6644784-0e69-400b-915b-13d48cff1944)

This is already available. Set the default value to current Date

**Comment by DarkPhoenix2704** [comment]
Closing this issue

**Comment by LucBerge** [comment]
Ok my bad, I opened an issue to quickly...
