### ISSUE TITLE
🐛 Bug:  Application crashes when concatenating date intervals using & operator in Excel.

### ISSUE THREAD

**Issue by qosh-dev** [nocodb/nocodb#9650]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

I play with date columns and face a bug 

Details: When attempting to calculate the difference between two date columns to get the interval in months and days, the formula used is:

ROUND(((DATETIME_DIFF({Max(Date) from Payment}, {Min(Date) from Payment}, "h") / 24) / 30), 0) & 
" " & 
ROUND(((DATETIME_DIFF({Max(Date) from Payment}, {Min(Date) from Payment}, "h") / 24) % 3

The issue arises when trying to concatenate the calculated values for months and days using the & operator. The application hangs indefinitely and becomes unresponsive, requiring a full restart to resolve the issue.

Suspected Cause: The & operator may be causing the issue during concatenation when working with numeric results of the DATETIME_DIFF function. Additionally, TEXT function is not available to properly format the numbers as strings(also tried CONCAT function but it convert int to decimal).

Steps to Reproduce:
Create two columns with date values.
Use the above formula to calculate and concatenate the difference in months and days.
Attempt to run the formula.
Observe the application hang.

### Project Details

Node: **v20.15.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.257.0**

**Comment by qosh-dev** [comment]
Yes I try this method 
Concat convert 2 2 ([month] [day])
to 2.0 2.0

**Comment by pranavxc** [comment]
Are`Max(Date) from Payment` and `Min(Date) from Payment` Rollup columns ?

**Comment by pranavxc** [comment]
Thanks for reporting the bug, we found the bug related to formula and made a bug fix PR here - https://github.com/nocodb/nocodb/pull/9662. Please try out following pr build to verify the fix: 

```bash
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.257.0-pr-9662-20241015-1838
```

**Comment by pranavxc** [comment]
Fixed here - https://github.com/nocodb/nocodb/pull/9662
