### ISSUE TITLE
🐛 Bug: Failed to decrypt any source or integration. Please configure correct encryption key.

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#9653]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Hi! I'm self-hosting nocodb with Railway, and tried to upgrade from 0.255.2 to 0.257.0, and ran into the following error:

```
[Nest] 9 - Failed to decrypt any source or integration. Please configure correct encryption key.
Error: Failed to decrypt any source or integration. Please configure correct encryption key.
at t.default [as handler] (/usr/src/app/docker/main.js:2:2333236)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async NcUpgrader.upgrade (/usr/src/app/docker/main.js:2:2307440)
at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1885383)
at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
```

### Desired Behavior

Working deployment

### Project Details

NocoDB hosted on Railway:

![image](https://github.com/user-attachments/assets/e4dccb7b-4b93-473f-b430-2b5bc416f043)

**Comment by emre1e** [comment]
how can i find the NC_CONNECTION_ENCRYPT_KEY ?

**Comment by pranavxc** [comment]
> how can i find the NC_CONNECTION_ENCRYPT_KEY ?

By default it's not set, Earlier we used to encrypt config using `NC_AUTH_JWT_SECRET` since it's problematic we now introduced a new env and by default config won't be in encrypted format. If you want to encrypt you can set `NC_CONNECTION_ENCRYPT_KEY` and restart, on init it will encrypt the config.

--------------------

@candideu : It looks like in your case the `NC_AUTH_JWT_SECRET` changed somehow. Could you share the steps you followed to upgrade Docker in Railway app? If the environment variable got a new value, it wouldn’t be able to decrypt the config anymore.

**Comment by emre1e** [comment]
@pranavxc Somehow it was set by default. I could find it under nc_store and inserted it under NC_CONNECTION_ENCRYPT_KEY . Since then its working

**Comment by pranavxc** [comment]
> @pranavxc Somehow it was set by default. I could find it under nc_store and inserted it under NC_CONNECTION_ENCRYPT_KEY . Since then its working

We do not store the `NC_CONNECTION_ENCRYPT_KEY` in the database. If this key is missing, the source and integration configurations will not be encrypted. However, if the `NC_AUTH_JWT_SECRET` is missing, a default value is automatically generated and stored.

**Comment by emre1e** [comment]
@pranavxc i checked my backups and the whole time there was a nc_auth_jwt_secret in nc_store. I needed exactly this key in NC_CONNECTION_ENCRYPT_KEY env variable. Otherwise it was not working.

**Comment by pranavxc** [comment]
> @pranavxc i checked my backups and the whole time there was a nc_auth_jwt_secret in nc_store. I needed exactly this key in NC_CONNECTION_ENCRYPT_KEY env variable. Otherwise it was not working.

Can you ping me in discord for further discussion - https://discord.gg/5RgZmkW ( user id - `pranavxc` )

**Comment by candideu** [comment]
I was able to solve the issue thanks to @pranavxc! I just had to copy the `nc_auth_jwt_secret` value in the `nc_store` table of the Postgres database, paste it in the deployment's `NC_AUTH_JWT_SECRET` value, then redeploy.

**Comment by kevinsantiago-mnltechnology** [comment]
Hello @pranavxc i got the same issue but i cannot find nc_auth_jwt_secret in the nc_store. i tried manually creating a record with same value i used in NC_AUTH_JWT_SECRET but issue persists. can please help? thanks.

**Comment by pranavxc** [comment]
> Hello @pranavxc i got the same issue but i cannot find nc_auth_jwt_secret in the nc_store. i tried manually creating a record with same value i used in NC_AUTH_JWT_SECRET but issue persists. can please help? thanks.

Can you ping me in Discord with the backend error log : our discord channel - https://discord.gg/5RgZmkW ( user id - pranavxc )
