### ISSUE TITLE
🔦 Feature: NC_DB env nolonger support MySQL server ???

### ISSUE THREAD

**Issue by geekyouth** [nocodb/nocodb#9658]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

https://docs.nocodb.com/getting-started/self-hosted/environment-variables#database

### Suggested solution

I hope MySQL server will be in use forever behind NC server 👀

**Comment by dstala** [comment]
You can still use MySQL for `NC_DB`. This part hasn't been changed.

**Comment by dstala** [comment]
Reopen this ticket if further clarity required
