### ISSUE TITLE
🐛 Bug: self hosted, data-api slow performance on linking records

### ISSUE THREAD

**Issue by skatilmi** [nocodb/nocodb#9692]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Every step here is performed using the API version “v2” and “v1”
1) Create two tables _A_ and _B_
2) Create a lookup column in _A_ that links to some column of in _B_ as using [this endpoint here](https://meta-apis-v1.nocodb.com/#tag/DB-Table-Column/operation/db-table-column-create) with type “oo” and uidt “LinkToAnotherRecord”
3) Create some sample records, 10 in _A_ and 10 in _B_. These rows will be linked to one another, so save the return values
4) Use the api endpoint /api/v2/tables/{tableId}/links/{linkFieldId}/records/{recordId} as explained [here](https://data-apis-v2.nocodb.com/#tag/Table-Records/operation/db-data-table-row-nested-list)

It works but the performance is very slow. About 1 second for each link, which sums up when dealing with thousands of rows. I’m using python to make changes to the database. The performance does not change when using Linux terminal with ```curl```

If needed I can provide the Jupyter notebook and after removing my credentials.
Cheers

### Desired Behavior

The links between records should be created really fast. Pushing rows to the database is much quicker (less than a second for 400+ rows). Base info says not docker but im running it with docker compose?

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.255.2**

**Comment by dstala** [comment]
Tried it out locally using Axios. Time consumed was around 60-90ms. Can you provide a screen recording or screen shot?
Is the behaviour same when creating links from UI?
