### ISSUE TITLE
🔦 Feature: Add webhook trigger when a form is submited

### ISSUE THREAD

**Issue by LucBerge** [nocodb/nocodb#9696]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

I want to trigger a webhook when a user inserts a record via form but I do not want to trigger it when record is manually insert. The current "On Record Insert" does not make the difference between the two.

### Suggested solution

Add a trigger "On Form Submited" and select the specific form that triggers the workflow.

**Comment by dstala** [comment]
One hack that you can use for now 
- Create a field "Source" 
- Create form with a "Source" pre-filled to "Form". you can hide this field as well from the user
- Trigger webhook conditionally when the "Source" is set to "Form"

Another option is to check "CreatedBy" field conditionally if you wish to avoid creating another pre-filled field.
