### ISSUE TITLE
🐛 Bug: Can't sync external database (Postgres 17)

### ISSUE THREAD

**Issue by m4rcelpl** [nocodb/nocodb#9728]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Add new datasource (Postgres 17) with with super user privileges. 
Try to Sync Now.  
Infinite Loading and error in log:
Cannot read properties of undefined (reading 'fk_related_model_id')

### Desired Behavior

Completion of synchronization and correct detection of relationships.

### Project Details

NocoDB version: 0.257.2 (Docker)
External database: Postgres 17

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.257.2**

### Attachments

<img width="1419" alt="Zrzut ekranu 2024-10-28 o 17 21 29" src="https://github.com/user-attachments/assets/e18875a5-5100-454b-9cfc-28c4add5f5ee">

<img width="1593" alt="Zrzut ekranu 2024-10-28 o 17 26 48" src="https://github.com/user-attachments/assets/3b1bb8f7-c4ba-480c-ac7f-78f350bc5ae0">

**Comment by m4rcelpl** [comment]
Thank you for your response, but it seems to me that all the keys (relationships) are correct. I wonder if all the selected relationships are incorrect, or just one of them and the error interrupts checking the rest. In any case, let’s check an example. The relationship between the ⁠`standard_items_templates` table and ⁠`standard_templates`


**standard_items_templates**
```SQL
CREATE TABLE IF NOT EXISTS public.standard_items_templates
(
    standard_item_id uuid NOT NULL,
    standard_template_id uuid NOT NULL,
    CONSTRAINT pk_standards PRIMARY KEY (standard_item_id, standard_template_id),
    CONSTRAINT fk_standard_item_id FOREIGN KEY (standard_item_id)
        REFERENCES public.standard_items (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_standard_template_id FOREIGN KEY (standard_template_id)
        REFERENCES public.standard_templates (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)
CREATE INDEX IF NOT EXISTS fki_fk_standard_item_id
    ON public.standard_items_templates USING btree
    (standard_item_id ASC NULLS LAST)
    TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS fki_fk_standard_template_id
    ON public.standard_items_templates USING btree
    (standard_template_id ASC NULLS LAST)
    TABLESPACE pg_default;
```

**standard_templates**
```SQL
CREATE TABLE IF NOT EXISTS public.standard_templates
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    update_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    name character varying(320) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT it_systems_template_pkey PRIMARY KEY (id)
)
```

**standard_items**
```SQL
CREATE TABLE IF NOT EXISTS public.standard_items
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    nanoid character varying(255) COLLATE pg_catalog."default",
    guid uuid,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT it_systems_pkey PRIMARY KEY (id),
    CONSTRAINT uq_nanoid UNIQUE (nanoid)
        INCLUDE(nanoid)
)
```


<img width="1161" alt="Zrzut ekranu 2024-10-29 o 09 29 28" src="https://github.com/user-attachments/assets/8f0fa775-bf0a-4596-821e-5ec57da455b3">



Additionally, such a situation causes an error on the ERD View tab:
<img width="569" alt="Zrzut ekranu 2024-10-29 o 09 30 09" src="https://github.com/user-attachments/assets/9af45e67-1b88-46a3-8907-edc32d01a6d2">
<img width="657" alt="Zrzut ekranu 2024-10-29 o 09 30 34" src="https://github.com/user-attachments/assets/64f3d53c-fee9-4f49-8b3c-5178bc45a06c">

**Comment by m4rcelpl** [comment]
Hi, I didn’t have time to wait for a response, so I decided to find the cause of the problem myself. I removed all indexes and foreign keys, then added them back again, and now it works! It seems to me that the problem was renaming one of the columns that had a foreign key set. In such a situation, PGAdmin removes the previously assigned index.

**Comment by gaurav-peswani-truva** [comment]
I am getting the same error. Checked the Foreign Key contraints and indexes as well. They look to be correct. 
```
[Nest] 32836  - 12/30/2024, 11:49:38 PM   ERROR [NcHelp] 
TypeError: Cannot read properties of undefined (reading 'fk_related_model_id')
```
I tried to run the NocoDB deployment locally to debug this. Added couple of loggers to see what the issue might be. The error seems to be coming due to the [following line in Column.ts file](https://github.com/nocodb/nocodb/blob/ba0ff3fba28cf957d2b8c633a4db4360132967c5/packages/nocodb/src/models/Column.ts#L1557).
```
for (const linkCol of ltarColumns) {
        // console.log(`linkCol:${JSON.stringify(linkCol)}`);
        await View.clearSingleQueryCache(
          context,
          (linkCol.colOptions as LinksColumn).fk_related_model_id, <-- CULPRIT!
          null,
          ncMeta,
        );
      }
```
The `linkCol` object does not seem to have the `colOptions` attribute which causes the  `(linkCol.colOptions as LinksColumn)` to become `undefined` throwing the error: `TypeError: Cannot read properties of undefined (reading 'fk_related_model_id')
`
Here is a sample of the `linkCol` object that I logged in my local setup.
```
{
    "id": "**************",
    "ref_db_alias": null,
    "type": "bt",
    "virtual": 0,
    "db_type": null,
    "fk_column_id": "**************",
    "fk_related_model_id": "**************",
    "fk_child_column_id": "**************",
    "fk_parent_column_id": "**************",
    "fk_mm_model_id": null,
    "fk_mm_child_column_id": null,
    "fk_mm_parent_column_id": null,
    "ur": null,
    "dr": null,
    "fk_index_name": "_TableIndexName_fkey",
    "deleted": null,
    "created_at": "2024-12-30 17:08:20+00:00",
    "updated_at": "2024-12-30 17:08:20+00:00",
    "fk_target_view_id": null,
    "base_id": "**************"
}
```

I changed the line from
```
(linkCol.colOptions as LinksColumn).fk_related_model_id,
```
to
```
linkCol.fk_related_model_id,
```
and this seems to have solved the issue. 

Not sure if this is the correct fix or expected behaviour. Can someone please confirm this?
