### ISSUE TITLE
🐛 Bug: No "equal to" option in AND conditional statements

### ISSUE THREAD

**Issue by huornlmj** [nocodb/nocodb#9745]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

It appears that only less than "<" or greater than ">" operators are available when using AND statements.  For example, the following works:
```sql
AND(({field1} < 2), ({field2} > 10))
```
But the following does not:
```sql
AND(({field1} = 2), ({field2} = 10))
```
It says `Unexpected "=" at character 54`.  So how are you supposed to make an AND statement for two conditions that are explicitly equal to values?

### Desired Behavior

Provide an explicit option for values that are equal, not just greater than or less than.

### Project Details

Using  nocodb:latest docker image ( 527b2fa8f4b0) with the supplied readme startup Docker command, using SQLlite supplied option.

**Comment by huornlmj** [comment]
I've answered this myself during a break.  It's double "=="'s are needed.  Please include this in your "AND()" example within the tool.  Would have saved me a lot of time. https://docs.nocodb.com/fields/field-types/formula/conditional-expressions/#and

**Comment by dstala** [comment]
Updated here
https://github.com/nocodb/nocodb/pull/9771
