### ISSUE TITLE
🐛 Bug: Webhook does not fire on API row update

### ISSUE THREAD

**Issue by 0nl1n1n** [nocodb/nocodb#9761]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

- I have verified if the webhook manually works ("Test Webhook") and it does
- I use API through the N8N node to create the record.
- I enter the record with all the data already.
 
![image](https://github.com/user-attachments/assets/7b009813-43a1-4eea-8cea-d5ecc11b8b05)
![image](https://github.com/user-attachments/assets/05c9de76-20ab-4ccb-8869-ac8f57561a3b)

### Desired Behavior

Ideally, the webhook would fire on a row creation / update

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.257.2**

**Comment by dstala** [comment]
Node: **v20.15.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.257.2**

@0nl1n1n I tried it out using following steps

- Create a "Insert trigger" webhook with `KW>200` OR `KW M6>500`
- Insert a new record using API (tried using swagger API)
- Webhook was triggered and below is the captured response
```json
{"type":"records.after.insert","id":"978d3d1d-0d5e-4fb9-a70b-633a5f4af88c","data":{"table_id":"mgajsdyex155i8l","table_name":"Table-1","rows":[{"Id":7,"Title":"string","CreatedAt":"2024-11-04 10:08:51+00:00","UpdatedAt":null,"MW":200,"MW M6":400}]}}
```

**Comment by dstala** [comment]
please reopen this ticket when we have more details to reproduce

**Comment by thesobercoder** [comment]
I'm also facing the same @dstala.

**Comment by dstala** [comment]
> I'm also facing the same [@dstala](https://github.com/dstala).

Do you have conditional filters enabled? Please be aware about the trigger in such case
https://docs.nocodb.com/automation/webhook/create-webhook/#webhook-with-conditions

**Comment by thesobercoder** [comment]
@dstala I do have conditional filters enabled, but I'm also sure that the webhook works perfectly when I'm changing values from the UI. As soon as this is triggered by an N8N node, where I send the `Id` and the `Status` (this the conditional field), it doesn't trigger.

So, according to the docs, the `Condition(old-record) = false` and `Condition(new-record) = true` satisfies my case because the Status was `New` before and the new status is `Updated`. The conditional is set to call the webhook when the status is set to `Updated`. I can clearly see in my N8N execution, the webhook call is not triggered.

**Comment by tiangao88** [comment]
I have exactly the same problem as described by @thesobercoder on a self-hosted version.
NC_ALLOW_LOCAL_HOOKS is set to true
I have a conditional webhook On Record Update that checks that the column status is changed to 'not_verified'
That change is made using the n8n nocodb node.

Please reopen this ticket.

**Comment by theluk** [comment]
Same here, who is addressing this?

@dstala please reopen this

**Comment by fendle** [comment]
I have the same issue. When I create a new entry, my webhook is triggered but by update it's not.

**Comment by TheNexter** [comment]
Same problem @dstala The issue still present.

Edit : I have any condition in my webhook.

![Image](https://github.com/user-attachments/assets/ce4ae90f-20b0-42a3-ac11-9556a520e90e)

**Comment by dstala** [comment]
# Record Update Trigger Issue

**@TheNexter** - Please note an important distinction that may explain the issue you're experiencing. If you've configured the "On Record Update" trigger but are performing bulk operations, the webhook won't fire. Your request will be treated as a bulk update if you're either:


## Webhook Trigger Types

There are two separate webhook triggers for record updates:

- **"On Record Update"** - Triggers for single record updates only
- **"On Multiple Record Update"** - Triggers for bulk record updates

## Common Issue

If you've configured the "On Record Update" trigger but are performing bulk operations, the webhook won't fire. Your request will be treated as a bulk update if you're either:

- Using the bulk record update API
- Sending an array `[ ]` in your record payload

## Next Steps

To help investigate further, please share:

- Your API endpoint and request method
- The payload structure (with sensitive data redacted)  
- Your base configuration details

## Testing Notes

I've tested both scenarios on cloud and self-hosted Docker environments, and the triggers work as expected when properly configured. Once we see your setup, we can identify the exact cause.

```
Node: **v22.16.0**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.263.7**
```

```json
{
  "type": "records.after.update",
  "id": "f6c04259-bb11-4721-9416-815015c9a36b",
  "data": {
    "table_id": "mruabi57zlesjk0",
    "table_name": "Features",
    "previous_rows": [
      {
        "Id": 1,
        "CreatedAt": "2025-06-19 10:08:21+00:00",
        "UpdatedAt": "2025-06-19 10:08:22+00:00",
        "Title": "a"
      }
    ],
    "rows": [
      {
        "Id": 1,
        "CreatedAt": "2025-06-19 10:08:21+00:00",
        "UpdatedAt": "2025-06-19 10:09:08+00:00",
        "Title": "string"
      }
    ]
  }
}
```

You can access base info from base context menu -- displayed below.  
  
<img width="602" alt="Image" src="https://github.com/user-attachments/assets/738ef305-ab89-4f50-9ee8-591569cac7d1" />

**Comment by TheNexter** [comment]
> * Sending an array `[ ]` in your record payload

Okayyyy this help me allot. N8N send array `[]` even if the tool is capable to update only one single row in the AI Agent...

For those how have the same problem with n8n AI Agent :
Use this option :

![Image](https://github.com/user-attachments/assets/e88663ec-e025-46d8-b373-515314456bee)

It was working great using the manual API that do not send array but nocodb tool for AI Agent is sending the array for whatever reason.

Thx for your help @dstala 😍 

Now i have only one very last issue to solve with date format in Nocodb API 😄

**Comment by fendle** [comment]
Hi,
what I experienced, when you have maintained on status update a "trigger on event", no webhook is send out.
A webhook is only send, if there are no trigger.
