### ISSUE TITLE
[Feature] Copy-Pasting from NocoDB tables

### ISSUE THREAD

**Issue by kristinbb** [nocodb/nocodb#978]
## Recommending Features

Easier copy-pasting possibility from NocoDB tables into Excel, Word or Notes.

**Need for this feature**
Copying data from the interactive spreadsheet tables across columns and rows into various docs. 

**Describe the solution you'd like**
Ability to select the cells I'd like to copy with my mouse and paste it in the same cell format into excel, word or other notes like application.

**Comment by Cirsten** [comment]
Is there a time frame on this, if at all

As I am wanting to migrate from Airtable, this would be a massive boon as I would like almalgamate a few together, so just importing from Airtable won't suffice

Thanks in Advance

**Comment by ketewan** [comment]
We also need this feature and we have already started the same task in our fork. Can I assign the task to me, so that when the task is finished, I will simply open PR?

**Comment by MrCaringi** [comment]
any "forecast" about this feature?
Is really holding back a lot a use case scenarios!

**Comment by MrCaringi** [comment]
still not working
"failed to copy to clipboard"

**Comment by wingkwong** [comment]
@MrCaringi Just tested and it's working on latest version. Please record a video for demonstration.

**Comment by maximemoreillon** [comment]
Hello, 

First of all, I want to congratulate the team on the awesome work they have put in NocoDB. It is a brilliant piece of software.

I am also getting the "failed to copy to clipboard" error when copying multiple cells.

I checked the browser console but no errors over there.

**Comment by wingkwong** [comment]
@maximemoreillon please create a new issue with a video record for demostrating.

**Comment by maximemoreillon** [comment]
@wingkwong Thanks a lot for your reply! I will do that shortly
