### ISSUE TITLE
🔦 Feature: Date Range field type and show on Calendar 

### ISSUE THREAD

**Issue by qhoirulanwar** [nocodb/nocodb#9785]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

on Calendar view show 1 record in multiple colomn (date range)

### Suggested solution

Date Range field type or 2 Date (start date and end date) to range view in calendar

**Comment by mrxorao** [comment]
I need this too!

**Comment by madwebskills** [comment]
I'm also hanging out for this feature to create a scheduling app for bookings across multiple days. 
I think it might already be [on the roadmap](https://github.com/nocodb/nocodb/issues/8583).

**Comment by cansik** [comment]
@DarkPhoenix2704 This should be [released](https://github.com/nocodb/nocodb/releases/tag/0.258.3) and available now, right? It seems to be disabled in my calendar view (even for `Date`).

![image](https://github.com/user-attachments/assets/4e5db98e-fc8c-42e1-bf1b-5c3d5ffdb21b)

I also don't see a "Date Range" field type. How do I use this feature?

**Comment by DarkPhoenix2704** [comment]
Calendar End Date support is available only for NocoDB Cloud / EE

**Comment by cansik** [comment]
@DarkPhoenix2704 Thanks for the clarification, but why is the end date of a calendar entry an enterprise feature?

You are [state](https://github.com/nocodb/nocodb/blob/8b78e7b821c1b844a4705488011945970c91e1c5/packages/noco-docs/docs/990.FAQs.md?plain=1#L50-L55) that enterprise features are things like SSO and SLA and stuff that an organisation needs. I can't really see the point of making such a feature enterprise only?

```
## Do we plan to have an Enterprise Edition?
For features that make sense for enterprises like below - yes 
- SSO, SLA, Organisation wide reports and analytics, 
- Advanced Audit or ACL,  
- Bespoke implementations & integrations,
- A hosted solution.
```
