### ISSUE TITLE
🐛 Bug: webhook is not working with External Source DB

### ISSUE THREAD

**Issue by mishlaev-personal** [nocodb/nocodb#9787]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Created a new table that is connected with our production Postgres:
<img width="1552" alt="Screenshot 2024-11-10 at 4 32 37 PM" src="https://github.com/user-attachments/assets/d822c3e7-2d16-4c65-af24-2146c48e2032">
Everything is updated as needed. DB sync works perfectly.

I've set up an n8n webhook. The test event works wonderfully.
<img width="1552" alt="Screenshot 2024-11-10 at 4 33 08 PM" src="https://github.com/user-attachments/assets/24fa5407-c5e2-4af9-a381-0e1fd30489e0">

But as new records are added to our looker table, I can see it onside NoCoDB, but no new webhooks are created.

### Desired Behavior

As we have new records from synced external Postgress DB, I want to have webhooks for those new records.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.257.2**

**Comment by mishlaev-personal** [comment]
@dosu Yes, it's the answer to my problem, but it's very frustrating

**Comment by kairosplan** [comment]
I’m experiencing the same issue. Webhooks don’t work with external databases, even when changes are made through NocoDB (API or UI).

**Comment by hvahora** [comment]
+1 I am also having the same issue.

**Comment by o1lab** [comment]
We do not support webhook triggering for changes made outside our ui and api. And we don't have plans to support it.

@kairosplan : are you sure you don't have any filters and such in your webhook. We keep getting these queries when filter are at place or there is something wrong in url. You can open a new issue for this with all details.
