### ISSUE TITLE
🐛 Bug: Invalid Date error format in calendar view

### ISSUE THREAD

**Issue by dawidmachon** [nocodb/nocodb#9808]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

- Create Table
  - Add field name a, Data Time -> format: YYYY-MM-DD HH:mm
  - Add field name b, Data Time -> format: DD-MM-YYYY HH:mm
- Add record: name: test | a: now() | b: now()
- Add view Calendar and set field for a
- Share calendar
- Open shared calendar
- Field a -> displaying ok || Field b -> displaying invalid.

### Desired Behavior

Field b should display correct format date time. On web UI everything is fine, only on shared view, there is a problem.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.257.2**

### Attachments

![image](https://github.com/user-attachments/assets/1e708662-8c11-4648-97d5-55708733a292)

![image](https://github.com/user-attachments/assets/08a1bc06-f460-440a-89d9-33d98d9cefce)

![image](https://github.com/user-attachments/assets/758973dd-4158-44d6-a4e6-38f79c0f01c0)

**Comment by dawidmachon** [comment]
@dosu As long format in field is keep YYYY on start, then it works. But if date starts with MM or DD, then showing in browser, invalid date. It only happens in shared view and only in overall view. On detailed view in shared view, all dates showing correctly.

**Comment by DarkPhoenix2704** [comment]
Thank you @dawidmachon for reporting this issue. I have created a [PR](https://github.com/nocodb/nocodb/pull/9809) for this.

**Comment by dawidmachon** [comment]
@DarkPhoenix2704 Great, thanks for fast fix.
