### ISSUE TITLE
When importing Excelsheet the scroll bar for field mapping is very hard to see

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#984]
**Please enter the following details**

NocoDB used as docker : true
NocoDB version : v0.84.6
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : QNAP-NAS v5.0.0.1891
Node.js version if running as node : 
Database version : Mariadb10

**Steps To Reproduce**
1. Go to 'Projekt'
2. Right-Click on 'Table"
2. Click on 'Import Excel'
3. See error: The scrollbar is very hard to be seen in Microsoft Edge v97.0.1072.69 on Win10 on a Notebook with **1368x768 screen resolution**.

**Expected behavior**
The scrollbar should be more easy to be seen.

**Screenshots**
![Excel-Import](https://user-images.githubusercontent.com/20600342/150750395-ed9e58d2-6fbe-4883-a164-b07e70230a20.png)

**Comment by wingkwong** [comment]
Closing it as new UI has been introduced. Feel free to reopen if you still encounter the issue with latest version.
