### ISSUE TITLE
Once signed in & signed out from a browser - invalid credentials also signs in (This has to be the same browser)

### ISSUE THREAD

**Issue by dgleba** [nocodb/nocodb#985]
please provide the following details :
NocoDB used as docker : true  - official.
NocoDB version : 0.84.6
Database used in NC_DB URL  : mysql 
Project was created  by clicking : New Project 
Database on which spreadsheet is created : mysql
Node.js version if running as node : 
Database version : 8.0

**Steps To Reproduce**

- open a fresh browser you never save info in. In my case Edge.
- login as admin. In my case - dgleba@gmail.com
- sign out.
- try to sign in with incorrect username: a and password: a  [or any username and password like that].
- projects are shown. username in top corner is `sign up`.
- you can edit data.

**Expected behavior**
incorrect credentials should not give successful access to data.

**Screenshots**

Platform: **linux**
Docker: **true**

**Comment by o1lab** [comment]
Just tried a wrong password and it is showing an error. Could you please recheck the scenario.

<img width="961" alt="Screenshot 2022-01-24 at 14 41 35" src="https://user-images.githubusercontent.com/5435402/150803839-9e0a4e54-6c56-4938-a9e1-853e6f37b3a5.png">

**Comment by o1lab** [comment]
I am on latest docker too.

**Comment by dgleba** [comment]
Did you try username without @gmail.com. Try  username `oof`.

**Comment by o1lab** [comment]
Ya got it. Thanks for the report and details. We're looking into it.

**Comment by dgleba** [comment]
I re-checked.

-clear all data from Edge.
-login as owner.
-signout.
-sign in as user a, password a gives full access.

The pic below shows not logged in but it shows data. That should not be possible. I can do all owner actions after trying to sign out.


![image](https://user-images.githubusercontent.com/4622715/150805628-6889e4fd-c9cd-40bb-8647-9a67b8a84828.png)

**Comment by pranavxc** [comment]
@dgleba :  thanks for reporting the bug. We figured out the bug It's recreating token using `refresh-token` which we are not removing on signout. We will fix it in the next release.

**Comment by dgleba** [comment]
Do you want me to edit this to obscure the content so it's not common knowledge?

**Comment by o1lab** [comment]
The issue has been before the new user with wrong credentials signs in (it has to be same browser), an API kind of refreshes the cookie. Trying the same on on an incognito or new browser or machine wont allow the sign in to happen. We;re gonna fix and make a release :)

**Comment by pranavxc** [comment]
Fixed in `0.84.7`
