### ISSUE TITLE
🔦 Feature: Add generic s3 compatible storage (e.g. iDrive e2)

### ISSUE THREAD

**Issue by cbertelli** [nocodb/nocodb#9865]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

We use iDrive e2 which is compatible with AWS S3, but we cannot enable it as a storage because no integration lets us state the provider but only the bucket name

### Suggested solution

Modify an existing integration (s3? Backblaze B2?).

**Comment by cbertelli** [comment]
Thank you, I did not suppose it was generic. Anyway I get an "Invalid URL"
error.
It may be that I fill the interface with the wrong info.
*Bucket Name* should be filled with the name I gave to the bucket, say
"photos" or it should be something like "photos.b6r8.fra5.idrivee2-91.com"?
*Region* can be filled with the name of the region ("Frankfurt") or it is a
URL?
*Endpoint* should be the endpoint of the bucket (say "
photos.b6r8.fra5.idrivee2-91.com") or it should be the general endpoint
address (say "b6r8.fra5.idrivee2-91.com")?
*Access Control Lists (ACL)* may be empty? I have no ACL in my bucket. It
is the "name" of the access key?
TIA

**Comment by salim-b** [comment]
- Bucket name is just the bucket name.
- Region is the region identifier (part of the endpoint URL). But region is actually ignored if endpoint is set, the UX/UI could be improved here, see https://github.com/nocodb/nocodb/pull/9053.
- ACL only supports [*canned ACL*](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl) keywords, I think. But I'm not certain. @DarkPhoenix2704 worked on ACLs, maybe they can shed some light on the details here.

 The following settings work for me with Backblaze B2, maybe it helps:
 
![Screenshot from 2024-11-23 15-25-23](https://github.com/user-attachments/assets/55f7edcd-8712-460a-bc4c-5554ec72b6f6)

**Comment by cbertelli** [comment]
It worked.
I just added "https://" before the endpoint, changed Region with the proper
part of the endpoint URL, and added the ACL from this table:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#permissions
Thank you

**Comment by cbertelli** [comment]
Thank you, the documentation needs some improvement, and the GUI should say S3 *compatible* instead of S3 only. But it is working well.
