### ISSUE TITLE
🔦 Feature: Date Format

### ISSUE THREAD

**Issue by Crispitol** [nocodb/nocodb#9869]
### Please confirm that the feature request does ***not*** already exist

- [X] I confirm there is no existing issue for this feature request.

### Use case

Sometimes I need to know the day of the week corresponding to a date, so I hope nocodb can add a date format, such as " 2024-01-01 Monday", or other forms that can express the day of the week.

### Suggested solution

Add a new format to the Date column. Users only need to select the date, and the day of the week automatically correspond.

**Comment by MaryamAlkhater** [comment]
Hello, I am a college student currently taking a software engineering class, and I am interested in working on an open-source project. Could I be assigned to this issue? @dstala

**Comment by dstala** [comment]
You can use this formula

SWITCH(WEEKDAY({Date}), 0, "Monday", 1, "Tuesday", 2, "Wednesday", 3, "Thursday", 4, "Friday", 5, "Saturday", 6, "Sunday")

{Date} => Date field

Pleas re-open this ticket if that doesn't suffice.
