### ISSUE TITLE
🐛 Bug: Unable to view record in group view

### ISSUE THREAD

**Issue by springfielddatarecovery** [nocodb/nocodb#9875]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Create some records
2. Create a view which groups the records somehow
3. If you click on a record (or the "expand" icon to the left of the record name), it does not display the record in a pop-up window like Kanban or other views. There's no way to see the full record.

### Desired Behavior

A pop-up window displaying the full record once it has been clicked on

### Project Details

On hosted nocodb.com instance

**Comment by o1lab** [comment]
Just tried on grid and kanban in our cloud - it seems to be fine.

Do you see any error in the chrome/browser console (cmd+alt+i or ctrl+alt+i)

**Comment by springfielddatarecovery** [comment]
Kanban works for us, the only issue is in the "grouped" view. If somebody from the nocodb team wants, I can send them a link to the specific table that's causing the issue (via e-mail or other non-public method)

**Comment by dstala** [comment]
You tried this? doesn't work?
![Image](https://github.com/user-attachments/assets/d3c6a118-07d4-42fb-be92-a3f9165c2538)

You can DM me over discord (Username: "dstala") if you wish to share specific details
[Discord](https://discord.gg/5RgZmkW)

**Comment by springfielddatarecovery** [comment]
Yep, clicking that does nothing. DMing you via discord

**Comment by dstala** [comment]
@springfielddatarecovery not sure if I missed DM over discord. You can share details over mail as well if that works out. r@nocodb.com

**Comment by springfielddatarecovery** [comment]
@dstala just sent the e-mail
