### ISSUE TITLE
🐛 Bug: WTF ? How to make a percentage of tasks done ?

### ISSUE THREAD

**Issue by romainds-tech** [nocodb/nocodb#9888]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Create a Task table with the column present in the screenshot
Try to make a percentage of tasks done ?

### Desired Behavior

Count true and false task ? we can't do it with formula. I feel like I'm constrained by this column, I rack my brains trying to make things simple and it never works. Isn't it possible to use native JS?

### Project Details

Node: **v20.15.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.258.2**

### Attachments

<img width="1396" alt="CleanShot 2024-11-25 at 22 01 18@2x" src="https://github.com/user-attachments/assets/1a6c145a-6a01-4cba-b35d-3ee004804aab">

**Comment by dstala** [comment]
You can use aggregation footer bar.

![Image](https://github.com/user-attachments/assets/37280c8e-d19d-45ca-b417-daa4f58279c2)
