### ISSUE TITLE
🐛 Bug: Cannot use s3 ovh plugin, error: "cannot read property of undefined (reading builder)"

### ISSUE THREAD

**Issue by Rae-op** [nocodb/nocodb#9890]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Issue Encountered Since Version 0.255.0 or Later
When attempting to upgrade, I encounter the error: "Migration failed" (refer to the attached error screenshot).
Additionally, when trying to connect to an OVH S3 instance via the interface, I receive the following error message: "cannot read property of undefined (reading builder)".

### Desired Behavior

Ability to connect to the OVH S3 plugin and use it effectively for adding and uploading attachment files.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.255.2**

### Attachments
![image](https://github.com/user-attachments/assets/25d2fe37-b656-4d01-a5fb-729c0f0e5302)
![image](https://github.com/user-attachments/assets/247efb61-f2e8-421f-9a01-97aa8d2f16eb)
![image](https://github.com/user-attachments/assets/7e278fc3-1ce4-4cbb-b536-da4cc5a7fa99)

**Comment by jbricout007** [comment]
This problem is blocking the upgrade because :
- **We cannot add or download an attachment**
- We can delete, rename or view an existing attachment

**Comment by DarkPhoenix2704** [comment]
Related Issue https://github.com/nocodb/nocodb/issues/9828

**Comment by jbricout007** [comment]
we have just tested this new version and we get an error : when we put S3 parameters we get : "Invalid region : region was not a valid DNS name"
![image (1)](https://github.com/user-attachments/assets/efec9969-7c69-4eb0-a391-97db982fd158)

**Comment by jbricout007** [comment]
We have juste tested this version and get a new error : "Invalid region : region was not a valid DNS name"
![image](https://github.com/user-attachments/assets/85d66f26-997c-42a3-b15d-89fc52d7aea0)
