### ISSUE TITLE
🐛 Bug: Formula doesn't update and deletes data in other fields if ENTER isn't pressed in other fields

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#9897]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Create a Currency field called "Unit Cost":

![image](https://github.com/user-attachments/assets/5fbeec59-e6fe-4e9d-94ee-73e14ff3a1b8)

2. Create a Number field called "Quantity":

![image](https://github.com/user-attachments/assets/963b39eb-5520-4422-a1b1-5d9649a3e181)

3. Create a Formula field that calculates the multiplies the fields: `({Unit Cost} * {Quantity})`:

![image](https://github.com/user-attachments/assets/addb60eb-b60e-4943-b618-4ced4187bc97)

4. Create a sum at the bottom of the Formula field:

![image](https://github.com/user-attachments/assets/6d40fce1-da0e-419e-a043-8b1e5c9bb36a)

5. Enter numbers in the records. The formulas aren't automatically updated, and the data in other fields may get deleted...:

![](https://i.imgur.com/YUnZZrv.gif)

https://i.imgur.com/YUnZZrv.mp4

The data only gets saved and updated if you hit ENTER... 

The sum only gets updated if you re-select it...

### Desired Behavior

The formula field should update automatically, and not delete the data in other fields. It should get saved and updated whether you hit ENTER or click away from the cell

### Project Details

Hosted app.nocodb.com

**Comment by wrb2012** [comment]
Still not fixed in 0.260.0
