### ISSUE TITLE
🐛 Bug: thousands separator not work for Decimal column

### ISSUE THREAD

**Issue by rupzhou** [nocodb/nocodb#9900]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. create one column with Decimal type, and enable the thousands separator
2. type value as  2323900
3. no thousands separator shown

### Desired Behavior

The decimal value is supposed to be shown as 2,323,900

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.258.2**

### Attachments

![image](https://github.com/user-attachments/assets/ebb9c016-3b20-4916-b476-5d860e84db75)
![image](https://github.com/user-attachments/assets/85c79491-8c30-401f-95da-0f0275d5360d)

**Comment by rupzhou** [comment]
> Hey @rupzhou! I'm here to help you with any bugs, questions, or contributions you have. Let's squash those bugs together! 🤖
> 
> The issue with the thousands separator not working for Decimal columns in MySQL might be related to how the `isLocaleString` property is being handled in the NocoDB codebase. The thousands separator feature is controlled by a switch in the `NumberOptions.vue` component, which toggles the `isLocaleString` property in the `meta` object. If this property is not being set or read correctly, it could result in the behavior you're experiencing [[1]](https://github.com/nocodb/nocodb/blob/develop/packages/nc-gui/components/smartsheet/column/NumberOptions.vue).
> 
> You might want to check if the `isLocaleString` property is being correctly set when you enable the thousands separator. Additionally, ensure that the frontend is correctly interpreting this property to format the number with a thousands separator. If the issue persists, it could be a bug in the implementation that needs further investigation.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Could you kindly advise how to set "isLocaleString" property ? I see no such option in UI.

**Comment by zsubzwary** [comment]
Guys, we are also facing the same issue.
@rameshmane7218
