### ISSUE TITLE
View does not has action type for downloading csv file as table does. However the shared view link does.

### ISSUE THREAD

**Issue by daleydeng** [nocodb/nocodb#991]
View does not has csv download action button as table does. But the shared view link has. Check out the snapshots.
![1153164307](https://user-images.githubusercontent.com/770506/150912409-e0c4fd15-2be4-4bbc-8001-8ad17af1548c.jpg)
![642750568](https://user-images.githubusercontent.com/770506/150912418-e11a235b-bd40-4cb4-9990-2395bd1407ec.jpg)

**Comment by wingkwong** [comment]
Fixed in ``0.84.10``.
