### ISSUE TITLE
🐛 Bug: 0.258.3: User Management Access Button Lost Labels

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#9924]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/b51f8e06-0681-4e61-966d-5d4d2e19261d">

### Desired Behavior

.

### Project Details

.

**Comment by rameshmane7218** [comment]
<img width="724" alt="Screenshot 2024-12-02 at 4 48 54 PM" src="https://github.com/user-attachments/assets/5dc27fda-69dd-409a-918f-e54b2515540b">
