### ISSUE TITLE
🐛 Bug: Unable to see Bases after Upgrading to latest version

### ISSUE THREAD

**Issue by nakul251197** [nocodb/nocodb#9931]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

I have upgraded a self-hosted NocoDB to the latest version using the docker run command and pointing it to the Postgres database used earlier.

Since the upgrade I am unable to see any of the bases and getting the below error.

![image](https://github.com/user-attachments/assets/1e4c224d-fd88-4dc7-b3d8-0129d13a1775)

### Desired Behavior

Able to see the previously added bases and interact with it.

### Project Details

Arch: x64
Platform: linux
Docker: true
RootDB: postgres
PackageVersion: 0.258.3

**Comment by mertmit** [comment]
Hi @nakul251197 
We will need more information. Which version you were using before upgrade & have you changed anything in your NC_DB?
Also can you please check which tables are available in your database using following command and share with us:
````
SELECT * FROM information_schema.tables WHERE table_schema = '<YOUR_SCHEMA>';
```

**Comment by nakul251197** [comment]
Hello @mertmit ,
Thank you for getting back to me. I used version 0.255.2 before the upgrade and then tried upgrading to the latest version. I have not changed anything in the NC_DB database.

Please find the list of tables as requested:

"table_name"
"xc_knex_migrations"
"xc_knex_migrations_lock"
"nc_store"
"nc_api_tokens"
"nc_shared_bases"
"xc_knex_migrationsv2"
"xc_knex_migrationsv2_lock"
"nc_shared_views_v2"
"nc_orgs_v2"
"nc_teams_v2"
"nc_team_users_v2"
"nc_plugins_v2"
"nc_map_view_columns_v2"
"nc_users_v2"
"notification"
"nc_bases_v2"
"nc_user_refresh_tokens"
"nc_extensions"
"nc_calendar_view_range_v2"
"nc_col_barcode_v2"
"nc_col_formula_v2"
"nc_col_lookup_v2"
"nc_col_qrcode_v2"
"nc_col_relations_v2"
"nc_col_rollup_v2"
"nc_col_select_options_v2"
"nc_jobs"
"nc_audit_v2"
"nc_columns_v2"
"nc_comment_reactions"
"nc_comments"
"nc_disabled_models_for_role_v2"
"nc_form_view_columns_v2"
"nc_form_view_v2"
"nc_gallery_view_columns_v2"
"nc_gallery_view_v2"
"nc_grid_view_columns_v2"
"nc_grid_view_v2"
"nc_hook_logs_v2"
"nc_hooks_v2"
"nc_kanban_view_columns_v2"
"nc_kanban_view_v2"
"nc_map_view_v2"
"nc_models_v2"
"nc_sort_v2"
"nc_sync_logs_v2"
"nc_sync_source_v2"
"nc_user_comment_notifications_preference"
"nc_views_v2"
"nc_calendar_view_v2"
"nc_calendar_view_columns_v2"
"nc_file_references"
"nc_base_users_v2"
"nc_integrations_store_v2"
"nc_filter_exp_v2"
"nc_source_v2"
"nc_integrations_v2"
"nc_col_button_v2"

**Comment by mertmit** [comment]
Have you used a PR build or timely build in that instance at any point?

**Comment by nakul251197** [comment]
I might have used a PR build initially and then used a timely build after the PR got merged and the issue was fixed.

**Comment by mertmit** [comment]
Alright this explains it, sorry for inconvenience we had one unwanted commit in develop branch at that point of time.
So please use `ALTER TABLE nc_source_v2 RENAME TO nc_sources_v2;` on your database to fix this issue.

**Comment by nakul251197** [comment]
That worked! Thank you!
