### ISSUE TITLE
🐛 Bug: No option to create form on the top nav bar

### ISSUE THREAD

**Issue by nakul251197** [nocodb/nocodb#9963]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Create a base.
2. Create or import a table.
3. Click on the Deafult view at the top and then on Create View.
4. There is no option to create a form.
![image](https://github.com/user-attachments/assets/da55aa2f-a3e3-48ba-8c16-798da7fcb257)
Default

### Desired Behavior

An option to create a form must be provided.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.258.3**

**Comment by rameshmane7218** [comment]
@nakul251197 can you confirm that view options are same in both places, in sidebar and toppbar ?

Also another point is if source is data readonly then we are not allowing user to create form view

```ts
<NcMenuItem v-if="!source.is_data_readonly" @click="onOpenModal({ type: ViewTypes.FORM })">
  <div class="item" data-testid="sidebar-view-create-form">
    <div class="item-inner">
      <GeneralViewIcon :meta="{ type: ViewTypes.FORM }" />
      <div>Form</div>
    </div>

    <GeneralLoader v-if="toBeCreateType === ViewTypes.FORM && isViewListLoading" />
    <GeneralIcon v-else class="plus" icon="plus" />
  </div>
</NcMenuItem>
```

**Comment by nakul251197** [comment]
@rameshmane7218 The options in the sidebar and the topbar are different. The topbar does not have the create form option.

The source is not read-only.

If you point me in the right direction, I can try to fix the issue.

**Comment by dstala** [comment]
What is your role in this base?

**Comment by nakul251197** [comment]
I am the "Owner" of the base.

**Comment by dstala** [comment]
Editor & below shouldn't see `Create View` option. Creator+,  they should see create view for all types. 

If its still reproducible, please
- share a video of the steps if you can
- from console, please share if you see any error logs

**Comment by nakul251197** [comment]
Please find the attached screenshots:

![image](https://github.com/user-attachments/assets/881f8dbc-b366-4a95-b369-8c97361cdb23)

I am unable to see the Form option in the "Create View" in the Topbar.

Whereas for the same base and table if click on the create view option from the sidebar I can see the Form option.

![image](https://github.com/user-attachments/assets/3023e336-c3b2-467d-a83e-c0c9e7ff32c2)


Please let me know if you need additional details.

**Comment by rameshmane7218** [comment]
@nakul251197 is that external source ?

Can you please share fullscreen screenshot ?

**Comment by nakul251197** [comment]
@rameshmane7218 Yes, it is connected to an external Postgres database.

![image](https://github.com/user-attachments/assets/02f4921b-2d9e-4b6d-bc90-716a04d07759)
